### ISSUE TITLE
Scrcpy often crashes

### ISSUE THREAD

**Issue by aoy1** [Genymobile/scrcpy#1001]
AMD 2700X
GTX1660
WIN10 1909
（Another old Intel machine is more stable）

**Comment by rom1v** [comment]
What do you mean "crash"? What is printed in the console?

I guess the window closes because the connection with `adb` is lost (the device is disconnected): #281 #283.

**Comment by aoy1** [comment]
> What do you mean by "crash"? What is printed in the console?
> 
> I guess the window closes because the connection with `adb` is lost (the device is disconnected): #281 #283.
> 
> _(I edited the title, because it may not be related to AMD or intel CPU)_

The window flickered directly.Sorry, I do n’t understand the code, it ’s for Xiaobai users, I use a software called Scrcpy_GUI_byCZ_V1.6.0.exe, there is no command line.Using a wifi connection

**Comment by rom1v** [comment]
> Sorry, I do n’t understand the code

Which code? You don't need to understand code here. If the window closes itself, try another USB port/cable (see #281 #283).

> I use a software called Scrcpy_GUI_byCZ_V1.6.0.exe,

I don't know what this is (probably a GUI which executes scrcpy).

If you still encounter the problem, use scrcpy directly and copy-paste what is printed in the console.

**Comment by aoy1** [comment]
> > Sorry, I do n’t understand the code
> 
> Which code? You don't need to understand code here. If the window closes itself, try another USB port/cable (see #281 #283).
> 
> > I use a software called Scrcpy_GUI_byCZ_V1.6.0.exe,
> 
> I don't know what this is (probably a GUI which executes scrcpy).
> 
> If you still encounter the problem, use scrcpy directly and copy-paste what is printed in the console.

Sorry, I'm using gui software, I won't use the command line, so I can't see the console, and I don't know what is printed. The software is really great. I especially like using WiFi connection. If it is convenient, please test the stability of the WiFi connection. thank you very much

**Comment by rom1v** [comment]
> Sorry, I'm using gui software, I won't use the command line, so I can't see the console, and I don't know what is printed.

OK, but if you don't want to run `scrcpy.exe` once to help finding the cause of your problem, I can't help you.

**Comment by aoy1** [comment]
> > Sorry, I'm using gui software, I won't use the command line, so I can't see the console, and I don't know what is printed.
> 
> OK, but if you don't want to run `scrcpy.exe` once to help finding the cause of your problem, I can't help you.

OK, I ’ll learn how to use it and give you a reply as soon as possible,
Even better if you can make a GUI

**Comment by rom1v** [comment]
> OK, I ’ll learn how to use it and give you a reply as soon as possible,

It's easy: download the release and double-click on `scrcpy.exe`.

**Comment by aoy1** [comment]
> > OK, I ’ll learn how to use it and give you a reply as soon as possible,
> 
> It's easy: download the release and double-click on `scrcpy.exe`.

I mainly test the connection through WiFi. In fact, your instructions are very detailed. It should not be difficult. I will take a closer look. I'm at work now, I will try it when I get home

**Comment by aoy1** [comment]
![image](https://user-images.githubusercontent.com/57678227/70713471-07c99880-1d21-11ea-8f77-22b72e163cc3.png)
![image](https://user-images.githubusercontent.com/57678227/70713499-1912a500-1d21-11ea-96e1-ac8d0e0005ee.png)

**Comment by npes87184** [comment]
I am **NOT** recommend using the wrapper version. Unless it is open source, we cannot assure that the author of the wrapper version not doing anything bad.

Using scrcpy is very easy in windwos, just download it from [release page](https://github.com/Genymobile/scrcpy/releases), enable usb debugging on your phone. Finally, double click `scrcpy.exe`.

**Comment by aoy1** [comment]
> I am **NOT** recommend using the wrapper version. Unless it is open source, we cannot assure that the author of the wrapper version not doing anything bad.
> 
> Using scrcpy is very easy in windwos, just download it from [release page](https://github.com/Genymobile/scrcpy/releases), enable usb debugging on your phone. Finally, double click `scrcpy.exe`.


Thank you for your reminder, but WiFi connection seems a bit difficult

**Comment by aoy1** [comment]
> > OK, I ’ll learn how to use it and give you a reply as soon as possible,
> 
> It's easy: download the release and double-click on `scrcpy.exe`.

![image](https://user-images.githubusercontent.com/57678227/70782242-7c541400-1dc1-11ea-8d30-7f4920beeb8c.png)
Please help me look, thank you very much.

**Comment by rom1v** [comment]
`WARN: Device disconnected`

You lost the connection to the device.

For example, if you run in a separate terminal `adb logcat`, it will ends at the same time as scrcpy.

**Comment by aoy1** [comment]
> > ```
> > WARN: Device disconnected
> > ```
> 
> You lost the connection to the device.
> 
> For example, if you run in a separate terminal `adb logcat`, it will ends at the same time as scrcpy.

But I did nothing

**Comment by aoy1** [comment]
> > > ```
> > > WARN: Device disconnected
> > > ```
> > 
> > 
> > You lost the connection to the device.
> > For example, if you run in a separate terminal `adb logcat`, it will ends at the same time as scrcpy.
> 
> But I did nothing

![image](https://user-images.githubusercontent.com/57678227/70782618-685ce200-1dc2-11ea-96fd-5360f6b17d4a.png)
This is the interface that I reconnected and displayed.

**Comment by rom1v** [comment]
Oh, you have something on your computer which runs adb 31. Find this program and stop it, or make it use the same adb as scrcpy (41, the latest).

(please copy-paste text of console instead of screenshots)

**Comment by aoy1** [comment]
> Oh, you have something on your computer which runs adb 31. Find this program and stop it, or make it use the same adb as scrcpy (41, the latest).
> 
> (please copy-paste text of console instead of screenshots)

By the way, I used an Android simulator. Can I replace adb.exe directly?

**Comment by aoy1** [comment]
I replaced the adb.exe in Android simulator and it is stable at present. Very happy, the problem has been solved, so cool, thank you. @ @rom1v
