### ISSUE TITLE
how can I make the screen to my system

### ISSUE THREAD

**Issue by huangli44** [Genymobile/scrcpy#1011]
how can I make the screen to my system

**Comment by npes87184** [comment]
Sorry, I don't know your problem. If you are asking how to use `scrcpy`. You can check [README](https://github.com/Genymobile/scrcpy#get-the-app) for getting `scrcpy`, and then execute it.

**Comment by huangli44** [comment]
What should I do If I need to implement screen projection and mobile phone interaction on my own system

**Comment by rom1v** [comment]
Implement on your own system? What do you mean?

Can you run scrcpy and see your device on your computer? If not, what problem do you observe?

**Comment by huangli44** [comment]
i&nbsp;need&nbsp;to&nbsp;implement&nbsp;a&nbsp;function,for&nbsp;the&nbsp;user,they&nbsp;can&nbsp;click&nbsp;the&nbsp;button&nbsp;,then&nbsp;the&nbsp;scrcpy&nbsp;screen&nbsp;coming,they&nbsp;can&nbsp;operate&nbsp;the&nbsp;sceen,then&nbsp;the&nbsp;mobile&nbsp;change.Now&nbsp;at&nbsp;your&nbsp;scrcpy&nbsp;project&nbsp;implement&nbsp;the&nbsp;function,but&nbsp;i&nbsp;need&nbsp;to&nbsp;implement&nbsp;at&nbsp;my&nbsp;system


---Original---

**Comment by rom1v** [comment]
OK, so you would like a lib instead of an application to control Android devices.

For now, there is no lib. This is something I'd like to do in the future, but probably not in the short term. See https://github.com/Genymobile/scrcpy/issues/707#issuecomment-520941669

**Comment by huangli44** [comment]
If I need to implement, do I need to rewrite the client?

**Comment by rom1v** [comment]
Rewrite or fork it, yes, probably.

Note that the protocol between the client and the server is not "stable" (https://github.com/Genymobile/scrcpy/issues/673#issuecomment-516360374), so it may (and will) change on new scrcpy versions.

**Comment by huangli44** [comment]
can you speak Chinese

**Comment by rom1v** [comment]
#1016
