### ISSUE TITLE
scrcpy quit automatically with exit code 1 whenever i open my vs code and build flutter app

### ISSUE THREAD

**Issue by uzairleo** [Genymobile/scrcpy#1012]
also i get sometime this error FLUTTER DAEMON HAS RESTARTED in vscode whenever i tried to open scrcpy while my vscode is open i got either the above error or the returned 1 error

**Comment by uzairleo** [comment]
plz help

**Comment by uzairleo** [comment]
/home/uzairleo/Pictures/adb.png

**Comment by uzairleo** [comment]
![adb](https://user-images.githubusercontent.com/52172428/70860399-198a8600-1f43-11ea-87b8-10ea8b669980.png)

**Comment by uzairleo** [comment]
help me plzzzzzzzzzzzzzz

**Comment by rom1v** [comment]
#992
