### ISSUE TITLE
怎么去Debug the server，usb连接之后项目就自动监测到设备了

### ISSUE THREAD

**Issue by huangli44** [Genymobile/scrcpy#1014]
怎么去Debug the server，usb连接之后项目就自动监测到设备了

**Comment by huangli44** [comment]
devolop.me里面说的是加一个配置，但是没找到配置在哪

**Comment by rom1v** [comment]
Please write in English, and describe what you did and what did not work.

**Comment by huangli44** [comment]
Can I get a video stream from the project

**Comment by rom1v** [comment]
See #613 #129
