### ISSUE TITLE
1.12 and 1.12.1 version error message appears, 1.11 is no problem, for some reason

### ISSUE THREAD

**Issue by jean-reno** [Genymobile/scrcpy#1015]
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
stat: No such file or directory
ERROR: 'E:\安卓\黑域\scrcpy-win64-v1.12.1\scrcpy-server' does not exist or is not a regular file
Press any key to continue...

**Comment by rom1v** [comment]
Fixed by #1002 (merged on `dev`).

To avoid the problem for now, do not use non-ASCII characters in your path (so move `E:\安卓\黑域\scrcpy-win64-v1.12.1` to `E:\Android\scrcpy-win64-v1.12.1` for example).

_Please post issues in English, I don't understand chinese._

**Comment by jean-reno** [comment]
1.12 and 1.12.1 version error message appears, 1.11 is no problem, for some reason
