### ISSUE TITLE
Window Position

### ISSUE THREAD

**Issue by Mataira86** [Genymobile/scrcpy#1018]
First things first, I appreciate all the hard work that has gone into scrcpy, so BIG thank you!.
I have been using scrcpy for a couple years now on a daily basis. On previous versions of scrcpy when window position and size wasnt available I have been using Auto Hot Key to do this. Thought I would let scrcpy do it instead but have run into a problem. My PC is currently running 3 screens, which I think maybe the problem. Using the same x y positions that a used with Auto Hot Keys gives me this error: ERROR: Could not parse window position: value (-1080) out-of-range (-1; 32767). I use AHK's windows spy to get the x y positions, not too sure if that has anything to do with it. Is there another way to get x y positions that scrcpy will accept? Cheers again.

**Comment by rom1v** [comment]
>     ERROR: Could not parse window position: value (-1080)

There is now more checking for input values.

Currently, a window position may not be negative in scrcpy. The reason is that it seems that SDL does not support negative values (it places the window at 0 anyway).

I just allowed negative values locally, and tested with multiple screens, I cannot reproduce a case where a negative value is correctly handled by SDL.

In practice, why do you pass `-1080`?

**Comment by Mataira86** [comment]
![screen](https://user-images.githubusercontent.com/58959522/71031231-d7965580-2177-11ea-9e8e-99842ae6f3dc.png)

Hi again, changing my main screen to screen 1 will get the results that I'm after but not what I want. If my screens are layed out side by side it also works just abit of getting used to. Cheers again

**Comment by rom1v** [comment]
Unfortunately, it seems SDL does not allow to pass negative values. Or more precisely, it behaves as if you passed 0.

This is weird because it is not possible to initialize a window partially offscreen on the left, but once it is created, we can move it manually…

**Comment by rom1v** [comment]
In fact, it is programmatically possible to set a negative position, but only once the window is shown (and we can see it "jump").

```diff
diff --git a/app/src/screen.c b/app/src/screen.c
index beb1075..3521331 100644
--- a/app/src/screen.c
+++ b/app/src/screen.c
@@ -236,6 +238,7 @@ screen_init_rendering(struct screen *screen, const char *window_title,
 void
 screen_show_window(struct screen *screen) {
     SDL_ShowWindow(screen->window);
+    SDL_SetWindowPosition(screen->window, -100, 100);
 }
 
 void
```
:confused:
