### ISSUE TITLE
Unable to query log using logcat

### ISSUE THREAD

**Issue by primejava** [Genymobile/scrcpy#1027]
I use `adb logcat |find "scrcpy"` to  view the log,but only` I SurfaceFlinger: [scrcpy (type:2)] fps:0.984708,dur:1015.53,max:1015.53,min:1015.53` ,How can I see the real log?thank you

**Comment by rom1v** [comment]
There are very few logs in logcat (and they should be also written to the console), especially in release mode. (But even in debug mode there are not many)

What logs do you want?

**Comment by primejava** [comment]
yes ,i want debug the code by log,but i cannot see anything.As shown in the figure,`test`
![2019-12-20_015352](https://user-images.githubusercontent.com/10646824/71197450-9b283e00-22cc-11ea-9224-d293bbca0af8.png)
![2019-12-20_015858](https://user-images.githubusercontent.com/10646824/71197464-a11e1f00-22cc-11ea-8d24-8b9cc0a66b0a.png)

 didn't print out

**Comment by primejava** [comment]
And I am very confused about why `I SurfaceFlinger: [scrcpy (type:2)] fps:0.984708,dur:1015.53,max:1015.53,min:1015.5` can be printed out, because this keyword `SurfaceFlinger `does not appear in the java server code

**Comment by rom1v** [comment]
`SurfaceFlinger` is a component in the Android system. It probably logs internally with the String passed here:

https://github.com/Genymobile/scrcpy/blob/31bd95022bc525be42ca273d59a3211d964d278b/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java#L163

> yes ,i want debug the code by log,but i cannot see anything.As shown in the figure,test

_(please copy paste code instead of screenshot, it's easier to search/copy-paste…)_

`Ln.d` is enabled only in debug. Do you compile in debug mode? (do not pass `--buildtype=release` in `meson`)

Anyway, just replace it with `Ln.i`.

**Comment by primejava** [comment]
I have no idea about meson, so I use Android studio to build  class, and package it to dex, and then convert it into jar. This jar file can work normally, but can't output logs.
i had try with `Ln.i("test");` ,but still can't print it

**Comment by rom1v** [comment]
> i had try with Ln.i("test"); ,but still can't print it

Something is probably wrong with your build then.

How do you execute it on Android? Does it print something in the console?

**Comment by primejava** [comment]
i want debug the server code in android studio,but i don't kown how to do it. so i just build out a jar file and  replace the original jar in scrcpy-win64-v1.10 folder with it, and try to  view log in cmd

**Comment by rom1v** [comment]
> i want debug the server code in android studio

https://github.com/Genymobile/scrcpy/blob/master/DEVELOP.md#debug-the-server

> so i just build out a jar file and replace the original jar in scrcpy-win64-v1.10

That should work (but you should replace the right version, for example if you use the master branch, you must replace it in `scrcpy-win64-v1.12.1`).
