### ISSUE TITLE
No console

### ISSUE THREAD

**Issue by Gnonymous7** [Genymobile/scrcpy#1029]
i have a bat file to run my custom commands for scrcpy. But how can i make it no console? I only want the device window to be displayed

**Comment by rom1v** [comment]
Call `scrcpy-no-console.exe` instead of `scrcpy.exe`?

**Comment by dilbert168** [comment]
I loaded the V1.12.1 but calling "scrcpy-noconsole.exe" still show the command prompt console...

**Comment by rom1v** [comment]
Out of curiosity, if you just click on `scrcpy-noconsole.exe`, it does not open a console, right?

Show your .bat content.

**Comment by dilbert168** [comment]
It is correct. 
scrcpy-noconsole.exe  --bit-rate 12M --render-expired-frames
I guess the "INFO" come from Android Server side, right ?  Any way not showing it when using batch file ?

**Comment by Gnonymous7** [comment]
I did run noconsole.exe without any bat. It stilll shows the console.

**Comment by Gnonymous7** [comment]
> I did run noconsole.exe without any bat. It stilll shows the console.

Updated the scrcpy its working now, but still not working on bat command

**Comment by Gnonymous7** [comment]
My bat command:
scrcpy-noconsole.exe -m 1010 --always-on-top -S

Log on cmd just like usual scrcpy log:
D:\Programverse\Apps\scrcpy-win64-v1.12.1>scrcpy-noconsole.exe -m 1010 --always-on-top -S
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
INFO: Initial texture: 464x1008

**Comment by rom1v** [comment]
The console is opened to execute a `.bat`.

Try adding `start` in your script to start scrcpy and continue:

```cmd
start scrcpy-noconsole.exe ...
```

**Comment by Gnonymous7** [comment]
> The console is opened to execute a `.bat`.
> 
> Try adding `start` in your script to start scrcpy and continue:
> 
> ```batchfile
> start scrcpy-noconsole.exe ...
> ```

OK that's works just fine. Thanks

**Comment by AhmedGodaa** [comment]
I'm alwayes using  Scrcpy With Screen off - Stay awak and and no  Command Prompt for this i use  

```
scrcpy-noconsole --turn-screen-off --stay-awake
```
or 
```
scrcpy-noconsole -Sw
```
