### ISSUE TITLE
Shortcut vol + and - do not work

### ISSUE THREAD

**Issue by RedMoonOTInetwork** [Genymobile/scrcpy#103]
Hi, Shortcuts to increase or decrease the phone volume do not work

**Comment by rom1v** [comment]
Thank you for your report.

On what system (Linux, Windows, MacOS)? On what device, with which keyboard layout?

**Comment by rom1v** [comment]
What if you manually execute:

```bash
adb shell input keyevent 24 # volume up
adb shell input keyevent 25 # volume down
```
?

**Comment by RedMoonOTInetwork** [comment]
@rom1v Thanks to you for the answer and if you settle! Windows 7, Huawei P9 lite, QWERTY italian layout

**Comment by RedMoonOTInetwork** [comment]
@rom1v no I use the keyboard shortcut but Do not work

**Comment by wieuwzak** [comment]
- hold shift + right shift on the folder that scrcpy is in.
- click "open command shell here" (something like this, I have different language)
- plug in your phone and execute command: "adb devices" to see if it's connected
- execute the command "adb shell input keyevent 24"
- see if your phone responds to the command, it should be turning the volume up.
- if it doesn't respond to the command, paste the output of the command shell here.

**Comment by rom1v** [comment]
OK, thank you, I reproduced on Windows.

I could not make Ctrl+`+` and Ctrl+`-` work for every keyboard on every platform with SDL2. It seems I am not alone: https://stackoverflow.com/questions/41570751/how-to-correctly-handle-control-key-combinations-in-sdl2

So I changed the shortcuts to Ctrl+`↑` and Ctrl+`↓`.

**Comment by RedMoonOTInetwork** [comment]
@rom1v thanks, You are very kind, I hope it will work in the next version :3
