### ISSUE TITLE
does not recognize all mouse input using SmartNav (a head controlled mouse)

### ISSUE THREAD

**Issue by livingator** [Genymobile/scrcpy#1033]
this issue actually happens since v 1.10 and i'm forced to stay on 1.9. all input from mouse using it doesn't work and it doesn't even recognize cursor is moved if i have someone (since i can't physically use a normal mouse) clicking to emulate touch and me moving the cursor using the head controlled mouse aka SmartNav. site below for what SmartNav is.

https://www.naturalpoint.com/smartnav/

**Comment by rom1v** [comment]
Hi,

I can't see a change from v1.9 to v1.10 which could cause this problem: https://github.com/Genymobile/scrcpy/releases/tag/v1.10

Maybe the SDL version upgrade (if you use Windows): try to use the latest version of scrcpy, but overwrite the SDL2.dll from v1.9.

**Comment by livingator** [comment]
@rom1v your suggestion of replacing SDL2.dll works. but will it cause any issues by doing that? (although i can't see "anything" bad as of right now)

**Comment by rom1v** [comment]
It's just an older version of SDL, so probably some bugs have been fixed, but some others have been introduced :wink: Use the old version if it works for you.

You should report your problem to libsdl, so that it can possibly be fixed in future SDL releases.

**Comment by livingator** [comment]
i'm not exactly sure what to report it under (i found their site after googling) but i'll do that and hopefully it'll be fixed in future.

**Comment by dedosmedia** [comment]
> i'm not exactly sure what to report it under (i found their site after googling) but i'll do that and hopefully it'll be fixed in future.

@livingator have you reported the bug to libsdl?
I found exctaly the same issue when connecting to a remote PC (where scrcpy is running) when using Logmein Client, scrcpy (1.10+) window is not responding to mouse events so I can not control the device. However with scrcpy 1.9 it works great, and I can control the device clicking on the window.
So, I guess it's due to the same issue with SDL.
