### ISSUE TITLE
Is this feature currently available? Use the Enter key of the keyboard to simulate the send key of the phone keyboard.

### ISSUE THREAD

**Issue by a516117636** [Genymobile/scrcpy#1034]
Is this feature currently available? Use the Enter key of the keyboard to simulate the send key of the phone keyboard.

**Comment by reversegear** [comment]
In whatsapp go to Settings>>Chats>>enable Enter is send.

**Comment by rom1v** [comment]
#72

**Comment by a516117636** [comment]
solved

**Comment by mattalexx** [comment]
This does not seem solved to me. I see an app specific fix, but still no way to "Use the Enter key of the keyboard to simulate the send key of the phone keyboard".

For example, I'm using the [Messages app](https://play.google.com/store/apps/details?id=com.google.android.apps.messaging&hl=en_US&gl=US), and I don't seem to have the equivalent setting in that app.

Is there any workaround for me?
