### ISSUE TITLE
App crashed after opened it

### ISSUE THREAD

**Issue by war10zx** [Genymobile/scrcpy#1036]
Sorry if bothering user(s) that gonna reply this issue. I'm new to this sofware and I tried to use this for gaming purpose. I already tested with other apps and worked out fine. The problem is I can't open the game (which is Fate Grand Order NA version) due to layout orientation issue. Also app can't even opened after the incident. So, do this software has reset command or alternatives that can fix this issue? Thanks for advance

**Comment by rom1v** [comment]
If you still have the issue, post the logs printed in the console.
