### ISSUE TITLE
Issue when running command scrcpy

### ISSUE THREAD

**Issue by henwill8** [Genymobile/scrcpy#1040]
command: 

> scrcpy

output: 

> INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
/home/willfam/Desktop/scrcpy/scrcpy-se...shed. 6.0 MB/s (18802 bytes in 0.003s)
ERROR: Exception on thread Thread[main,5,main]
java.lang.NumberFormatException: For input string: "1.12.1"
	at java.lang.Integer.parseInt(Integer.java:521)
	at java.lang.Integer.parseInt(Integer.java:556)
	at com.genymobile.scrcpy.Server.createOptions(Server.java:52)
	at com.genymobile.scrcpy.Server.main(Server.java:101)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)

It states I am in scrcpy 1.12.1 instead of 1.4, is this because of a mistake in deleting previous version of scrcpy?

**Comment by rom1v** [comment]
You are using a wrong prebuilt server.

Download the last one and retry: https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#prebuilt-server

**Comment by rom1v** [comment]
> It states I am in scrcpy 1.12.1 instead of 1.4,

Oh, you want to run scrcpy 1.4? (why?)

You need to use the scrcpy server 1.4 then (or build it manually from the v1.4 tag).

**Comment by henwill8** [comment]
Oh, I thought it needed to be 1.4 because of it saying scrcpy 1.4 at the bottom, I am just dumb.

**Comment by henwill8** [comment]
Yeah, I was using the prebuilt server at the bottom

**Comment by rom1v** [comment]
> I thought it needed to be 1.4 because of it saying scrcpy 1.4 at the bottom

Where? At the bottom of what?

**Comment by henwill8** [comment]
Oh, this: https://github.com/Genymobile/scrcpy/blob/audio/BUILD.md

**Comment by rom1v** [comment]
Oh, you're reading the BUILD.md from an old (obsolete) branch (`audio`).

**Comment by henwill8** [comment]
so should I make the current one and does it include the audio beta?

**Comment by henwill8** [comment]
So I tried just making it completely from this but it didnt have the -a option: https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#prebuilt-server

**Comment by henwill8** [comment]
Yeah, so I am confused, what should I download then for the -a option?

**Comment by rom1v** [comment]
Don't use it, it's obsolete.

If you want, you cab use [USBaudio](https://github.com/rom1v/usbaudio) separately. But it's also obsolete since AOA audio has been deprecated. See #14

**Comment by henwill8** [comment]
Just tried making USBaudio, ended up with three errors:
[INFO] Device: [2833:0183] 1PASH9A3UU9153
[ERROR] Pipe error
[ERROR] Could not get AOA protocol version
[ERROR] Could not forward audio

**Comment by rom1v** [comment]
If it does not work with USBaudio, it should not work with the old `audio` branch.
