### ISSUE TITLE
how easy is it for someone to take this solution and build a spyware to control my phone without me knowing

### ISSUE THREAD

**Issue by xXDarkCubeXx** [Genymobile/scrcpy#1041]
I mean this solution is great, really, well done. But after I enabled tcp/ip it became veeeery easy to connect to my phone and control it. convenient me and you can describe it, vulnerable a hacker might call it.
could someone like activate that command by quickly plugging, for example, their phone or a raspberry pi or something easily opening that bridge of vulnerability to control it whenever he wants.
so my question is: how worried/ careful should we be?

**Comment by rom1v** [comment]
The whole authentication is managed by adb: when you authorize a computer to connect to a device over `adb`, you grant to it shell access on the device.

So, yes, you should not authorize a computer you don't trust to connect over `adb` (scrcpy or not).

**Comment by imvickykumar999** [comment]
Turn off the `USB Debugger` or `Developer mode` to remove connected Devices.
