### ISSUE TITLE
How to use the computer Task Scheduler to  start Scrcpy automatically when I insert my phone to computer

### ISSUE THREAD

**Issue by Ice-Castellan** [Genymobile/scrcpy#1042]
Recently, an idea came to my mind,that is how to use the computer Task Scheduler to  start Scrcpy automatically when i insert my phone to computer by using the USB cable. I hope someone can help me.That will be a very interesting experience. 
I do not know how to use the trigger to achieve this effect, what's more, I can not find some useful message in the Internet.

**Comment by rom1v** [comment]
See #352

**Comment by Ice-Castellan** [comment]
Thank you,but  I'm a newbie, I do not quite understand this command:
> while :; do adb wait-for-device && scrcpy; done
Where to run the command? cmd console?

**Comment by Ice-Castellan** [comment]
@rom1v  I want to use the Windows Task Scheduler to start Scrcpy, I do not know how to use the trigger to achieve this effect, what's more, the udev is too difficult for me.

**Comment by rom1v** [comment]
I just wrote a tiny tool `autoadb`. See https://github.com/Genymobile/scrcpy/issues/352#issuecomment-569517922

**Comment by Ice-Castellan** [comment]
@rom1v  oh, thank you! I'll try.

**Comment by lemiges** [comment]
You can achieve it by Windows Task Scheduler.
This is the event to catch.
![image](https://user-images.githubusercontent.com/78954183/134772251-f362b328-6d1d-4bcf-a211-6cffc14ec6e2.png)

Tested on Windows 10 21H1.

**Comment by Dhyfer1** [comment]
@lemiges Hi. I have left the task the same as in your image, but after clicking on Ok it asks me for more information. Can you show me your settings in the General and Actions tabs of that task?

**Comment by lemiges** [comment]
![2022-01-31 08_39_13-How to use the computer Task Scheduler to start Scrcpy automatically when I inse](https://user-images.githubusercontent.com/78954183/151755873-c9f93988-f8b7-4bff-b59b-32f7fb07e058.png)
![2022-01-31 08_42_41-Task Scheduler](https://user-images.githubusercontent.com/78954183/151755875-e462c7dc-e5b8-491e-86a9-81416338e732.png)

**Comment by Dhyfer1** [comment]
@lemiges Thank you for the images, they have been very helpful as a guide. Now I have 2 questions:

1.  In the first image, where do you get the value 1000 in Event ID?
2.  Before you found the solution using the task scheduler, did you already know the autoadb tool from the same developer, because I think autoadb can do the same thing without creating a task in the task scheduler, I just don't know how.

**Comment by lemiges** [comment]
@Dhyfer1 Hi, 1. Observing the EventViewer while connecting the cable. 2. Yes I read about it, but I don't want another tool to sit in memory when I can use means of operating system.

**Comment by Dhyfer1** [comment]
@lemiges Hi. 

I don't understand how you did it. I did it this way, but I don't get the value 1000:
- I open Device Manager 
- Select my device in "Portable Devices", then right click and select Properties.
- In the Properties window, and inside the Events tab I click on the "View all events" button,
- The Event Viewer window opens, but I only get ID's 20003 and 430 as you can see in the following image

![Sin título](https://user-images.githubusercontent.com/50301201/154173772-b1b66b03-bdc4-4c68-9e59-1a6987960f60.png)

Is that the ID in Event ID (in your example 1000) is different for each connected device? I don't know if the way I got the value to know the Event ID was the correct one, if not, can you give me more information about how you got the value 1000?

2. I understand, it was a smart move on your part.

**Comment by lemiges** [comment]
See folder Aplication and Services logs / Microsoft / Windows / WPD-MTPClassDriver / Operational in EventViewer

**Comment by Dhyfer1** [comment]
@lemiges 

Thank you very much, I found the value 1000 with the path you indicated. In fact, there are more values: 1000, 1001, 1002, 1003 etc. The ID values that appear as 1000 and 1001 are "Driver Initialization", the others appear as "Driver Operation" or "Device Error". 

So I guess if you had put 1001 instead of 1000 in the Event ID box in your first image, Scrcpy would have had no problem starting up with the task scheduler.
