### ISSUE TITLE
number pad issues

### ISSUE THREAD

**Issue by KIMYONGUP** [Genymobile/scrcpy#1048]
When Num Lock is off, the keys are supposed to function to left, right, up or down. But they aren't working.

**Comment by rom1v** [comment]
Fixed by #1188.

**Comment by lollita** [comment]
It not work also for me now.

**Comment by rom1v** [comment]
It's fixed on `dev` branch. You could take this build to test: https://github.com/Genymobile/scrcpy/issues/898#issuecomment-610932491

**Comment by lollita** [comment]
Ty.
dev branch is accessible via Github?

**Comment by rom1v** [comment]
The take these binaries: https://github.com/Genymobile/scrcpy/issues/898#issuecomment-610932491

**Comment by lollita** [comment]
I test dev binaries but key pad not work again.

**Comment by rom1v** [comment]
@KIMYONGUP Could you test, please?
