### ISSUE TITLE
Cannot access scrcpy *universally*, even after setting the PATH

### ISSUE THREAD

**Issue by swingcake** [Genymobile/scrcpy#105]
scrcpy doesn't run from anywhere outside of where it is located in Windows 10. I've set the PATH, so the command gets recognized but does nothing.

![screenshot 61](https://user-images.githubusercontent.com/32037820/38137188-dd45b6cc-3440-11e8-97fa-c96297230392.png)
![screenshot 62](https://user-images.githubusercontent.com/32037820/38137189-dd753b86-3440-11e8-964f-726a44415220.png)
![screenshot 64](https://user-images.githubusercontent.com/32037820/38137190-ddabcf3e-3440-11e8-90cd-eec0eee3bd09.png)

**Comment by rom1v** [comment]
Please check the [output](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#on-windows-i-have-no-output-in-the-console) of the command when it does not work.

**Comment by swingcake** [comment]
I installed MSYS2, but since I have never used it before I'm not certain as to what I am doing wrong here.

![screenshot 66](https://user-images.githubusercontent.com/32037820/38141818-94daeb7a-3457-11e8-8b28-31c5df635bee.png)

**Comment by rom1v** [comment]
Run:

     ./scrcpy

**Comment by swingcake** [comment]
Yep. Same issue. No output.

![screenshot 67](https://user-images.githubusercontent.com/32037820/38145002-dcc542a2-3464-11e8-9ca9-3e6ad2c5f56e.png)

**Comment by rom1v** [comment]
What is the result of `adb devices` or `./adb devices`?

**Comment by rom1v** [comment]
Ah sorry, I didn't remember what the problem was (I confused with another question).

MSYS2 will not help here, since it will not check the same `PATH`.

Maybe you could create a script `run-scrcpy.cmd` in the _scrcpy_ directory:

```bash
scrcpy >stdout 2>stderr
```

Then execute from somewhere else (from `cmd.exe`):

    run-scrcpy

**Comment by rom1v** [comment]
Ah, you are using PowerShell. What if you use `cmd.exe` instead?

**Comment by swingcake** [comment]
So I created `run-scrcpy.cmd` in the same directory where `scrcpy.exe` is located.

- When I ran the command `run-scrcpy` from within the same directory, it ran perfectly and created 2 files *stdout* and *stderr*. 

  - stderr:
`INFO: Initial texture: 1080x1920`

  - stdout is empty.

- But when I run the same command from any other directory, I get the usual output from the CLI which is `scrcpy  1>stdout 2>stderr`. However, scrcpy doesn't run. The outputs of *stderr* and *stdout* are as follows.

  - stderr:
`ERROR: "adb push" returned with value 1`

  - stdout is empty.

**Comment by rom1v** [comment]
Ah, I think I get it.

The prebuilt windows is a "portable" version (`scrcpy-server.jar` is not located in a predefined absolute path, cf [`Makefile`](https://github.com/Genymobile/scrcpy/blob/master/Makefile)).

In this version, it just executes `adb push scrcpy-server.jar`, so it expects it to be in the current directory.

To confirm, please try to copy `scrcpy-server.jar` to the directory you execute `scrcpy.exe`.

**Comment by swingcake** [comment]
You're right. Works!
