### ISSUE TITLE
"scrcpy does not exist or is not a regular file"

### ISSUE THREAD

**Issue by hikarishiro** [Genymobile/scrcpy#1050]
I'm trying to use the 32-bit Windows version of scrcpy on a friend, but for some reason it says the file is missing but is there
"
C:\Users\-------\Downloads\scrcpy-win32-v1.12.1>scrcpy
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
stat: No such file or directory
ERROR: 'C:\Users\------\Downloads\scrcpy-win32-v1.12.1\scrcpy-server' does not e
xist or is not a regular file
Press any key to continue...
"

**Comment by rom1v** [comment]
See #1002
