### ISSUE TITLE
problem with "ninja -Cx" step of installation

### ISSUE THREAD

**Issue by suspiciouschadjensen** [Genymobile/scrcpy#1052]
> ninja -Cx
> ninja: Entering directory `x'
> [24/26] Generating scrcpy-server-prebuilt with a custom command.
> FAILED: server/scrcpy-server 
> cp '/home/felicitous/Téléchargements/' server/scrcpy-server
> cp: -r non spécifié ; omission du répertoire '/home/user/Téléchargements/'
> [25/26] Compiling C object 'app/scrcpy@exe/src_sys_unix_command.c.o'.
> ninja: build stopped: subcommand failed.

This is the issue I get when running the command. I am not sure how to resolve. I used the prebuilt server, because I don't have Android Studio. Been unable to find any documentation on how to resolve this issue.

**Comment by rom1v** [comment]
Could you please post the result of `meson configure x`?

(surround code blocks by ```)

**Comment by suspiciouschadjensen** [comment]
> Core properties:
>   Source dir /home/user/scrcpy
>   Build dir  /home/user/scrcpy/x
> 
> Core options:
>   Option          Current Value Possible Values                                  Description
>   ------          ------------- ---------------                                  -----------
>   buildtype       release       [plain, debug, debugoptimized, release, minsize] Build type to use.
>   warning_level   2             [1, 2, 3]                                        Compiler warning level to use.
>   werror          false         [true, false]                                    Treat warnings as errors.
>   strip           true          [true, false]                                    Strip targets on install.
>   unity           off           [on, off, subprojects]                           Unity build.
>   default_library shared        [shared, static]                                 Default library type.
> 
>   Option            Current Value Description
>   ------            ------------- -----------
>   backend_max_links 0             Maximum number of linker processes to run or 0 for no limit
> 
> Base options:
>   Option      Current Value Possible Values                                               Description
>   ------      ------------- ---------------                                               -----------
>   b_asneeded  true          [true, false]                                                 Use -Wl,--as-needed when linking
>   b_colorout  always        [auto, always, never]                                         Use colored output
>   b_coverage  false         [true, false]                                                 Enable coverage tracking.
>   b_lto       true          [true, false]                                                 Use link time optimization
>   b_lundef    true          [true, false]                                                 Use -Wl,--no-undefined when linking
>   b_ndebug    false         [true, false, if-release]                                     Disable asserts
>   b_pch       true          [true, false]                                                 Use precompiled headers
>   b_pgo       off           [off, generate, use]                                          Use profile guided optimization
>   b_sanitize  none          [none, address, thread, undefined, memory, address,undefined] Code sanitizer to use
>   b_staticpic true          [true, false]                                                 Build static libraries as position independent
> 
> Compiler arguments:
>   c_args []
> 
> Linker args:
>   c_link_args []
> 
> Compiler options:
>   Option Current Value Description
>   ------ ------------- -----------
>   c_std  c11           C language standard to use
> 
> Directories:
>   Option         Current Value        Description
>   ------         -------------        -----------
>   prefix         /usr/local           Installation prefix.
>   libdir         lib/x86_64-linux-gnu Library directory.
>   libexecdir     libexec              Library executable directory.
>   bindir         bin                  Executable directory.
>   sbindir        sbin                 System executable directory.
>   includedir     include              Header file directory.
>   datadir        share                Data file directory.
>   mandir         share/man            Manual page directory.
>   infodir        share/info           Info page directory.
>   localedir      share/locale         Locale data directory.
>   sysconfdir     etc                  Sysconf data directory.
>   localstatedir  /var/local           Localstate data directory.
>   sharedstatedir /var/local/lib       Architecture-independent data directory.
> 
> Project options:
>   Option             Current Value                     Possible Values Description
>   ------             -------------                     --------------- -----------
>   compile_app        true                              [True, False]   Build the client
>   compile_server     true                              [True, False]   Build the server
>   crossbuild_windows false                             [True, False]   Build for Windows from Linux
>   hidpi_support      true                              [True, False]   Enable High DPI support
>   portable           false                             [True, False]   Use scrcpy-server from the same directory as the scrcpy executable
>   prebuilt_server    /home/user/Téléchargements/                 Path of the prebuilt server
>   server_debugger    false                             [True, False]   Run a server debugger and wait for a client to be attached
>   windows_noconsole  false                             [True, False]   Disable console on Windows (pass -mwindows flag)
> 
> Testing options:
>   Option    Current Value Possible Values Description
>   ------    ------------- --------------- -----------
>   stdsplit  true          [true, false]   Split stdout and stderr in test logs.
>   errorlogs true          [true, false]   Whether to print the logs from failing tests.

I'm not sure I recognize any "code blocks", sorry - that's the full output.

**Comment by rom1v** [comment]
> I'm not sure I recognize any "code blocks", sorry - that's the full output.

Yes, I mean surround the output by ``` (instead of prefixing by `>`)

**Comment by rom1v** [comment]
>     prebuilt_server    /home/user/Téléchargements/

Here is what is wrong: you passed a directory here, you need to pass the whole path to the server (probably `/home/user/Téléchargements/scrcpy-server-v1.12.1`).

You can change it:

```bash
meson configure x -Dprebuilt_server='/home/user/Téléchargements/scrcpy-server-v1.12.1'
```

**Comment by suspiciouschadjensen** [comment]
Ah, great! That was the issue, thanks!
