### ISSUE TITLE
copy and paste 

### ISSUE THREAD

**Issue by ariagecheney** [Genymobile/scrcpy#1057]
Copy-paste
It is possible to synchronize clipboards between the computer and the device, in both directions:

Ctrl+c copies the device clipboard to the computer clipboard;
Ctrl+Shift+v copies the computer clipboard to the device clipboard;
Ctrl+v pastes the computer clipboard as a sequence of text events (but breaks non-ASCII characters).

1  I can't do that with CTRL +c in my cell phone(mirror windows ), and then moving my mouse  towards PC ,and paste!! 
If you can, please describe the operation in detail sincerely！

2 this is my trouble.
https://github.com/srevinsaju/guiscrcpy/issues/44

**Comment by rom1v** [comment]
> 1 I can't do that with CTRL +c in my cell phone(mirror windows ), and then moving my mouse towards PC ,and paste!!

1. select the text somewhere
2. long-click, and press "copy" (this copies the text into the device clipboard)
3. press `Ctrl`+`c` in the scrcpy window (this synchronized the device clipboard to the computer clipboard)
4. press `Ctrl`+`v` in some app on your computer.

**Comment by ariagecheney** [comment]
> > 1 I can't do that with CTRL +c in my cell phone(mirror windows ), and then moving my mouse towards PC ,and paste!!
> 
> 1. select the text somewhere
> 2. long-click, and press "copy" (this copies the text into the device clipboard)
> 3. press `Ctrl`+`c` in the scrcpy window (this synchronized the device clipboard to the computer clipboard)
> 4. press `Ctrl`+`v` in some app on your computer.

thank you very much and your patience !!!  i always  think  wrong by my own mind!

**Comment by rom1v** [comment]
Does it work now?

**Comment by ariagecheney** [comment]
> Does it work now?
thank you! now it work very correctly  instructed by your steps!  thank you very much!

**Comment by carstenhag** [comment]
Issue can be closed :)
