### ISSUE TITLE
Mi9T no control

### ISSUE THREAD

**Issue by Vanman989** [Genymobile/scrcpy#1065]
I cant click or use the phone from my computer

**Comment by Vanman989** [comment]
didnt have right settings enabled

**Comment by Nabagata** [comment]
@Vanman989 what are the right settings?

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#i-can-only-mirror-i-cannot-interact-with-the-device
