### ISSUE TITLE
Some characters are not written correctly

### ISSUE THREAD

**Issue by jrcacd** [Genymobile/scrcpy#1067]
Examples: ã á à â ...

**Comment by rom1v** [comment]
Try:

    scrcpy --prefer-text

(ref #650)

**Comment by jrcacd** [comment]
Ok, thanks.

One note: This way, an comand windows also needs to remain open.

**Comment by rom1v** [comment]
> One note: This way, an comand windows also needs to remain open.

No, just create a `myscrcpy.bat` containing:

```
start scrcpy-noconsole --prefer-text
```

and double-click on it.

**Comment by jrcacd** [comment]
Very good, thanks for the fast response.

**Comment by jrcacd** [comment]
Another question:
Could the pasting text speed be faster?

**Comment by rom1v** [comment]
Not really, it injects each char one by one.

The alternative is to synchronize clipboard (Ctrl+Shift+v), which is immediate, but then you have to long-press a textfield and click PASTE on your device (but it has the advantage to never corrupt the content, which may contain non-ASCII chars).

**Comment by jrcacd** [comment]
> Not really, it injects each char one by one.
> 
> The alternative is to synchronize clipboard (Ctrl+Shift+v), which is immediate, but then you have to long-press a textfield and click PASTE on your device (but it has the advantage to never corrupt the content, which may contain non-ASCII chars).

Very good, many thanks.
