### ISSUE TITLE
scrcpy error in ubuntu

### ISSUE THREAD

**Issue by dhruvvvvvv** [Genymobile/scrcpy#107]
command------->>>>meson x --buildtype release --strip -Db_lto=true
output------------>>>>Error during basic setup:
                                 [Errno 2] No such file or directory: '/home/dh/scrcpy/x'

**Comment by rom1v** [comment]
What is your meson version?

On old versions, you may need to create the build directory manually before:

```bash
mkdir x
meson x --buildtype release --strip -Db_lto=true
```
