### ISSUE TITLE
fps drop either going gradually worse to unusable level or when trying to power phone up from pc side

### ISSUE THREAD

**Issue by livingator** [Genymobile/scrcpy#1076]
as subject says, it's happening on both phone and pc side for scrcpy v1.12.1.
when fps is dropping, skipped frames are also increasing. switching app and close>reopen app return it to normal fps then it gradually goes worse again.
after some testing it appears to be fixed by replacing sdl2.dll (version 2.0.8) by taking 2.0.9 sdl2.dll from scrcpy v1.5.

just posting in case people have similar issue and/or future version is fixing it or something, i'll keep testing each day and post if the issue returns.

**Comment by rom1v** [comment]
> after some testing it appears to be fixed by replacing sdl2.dll (version 2.0.8)

You mean 2.0.10?

Thanks for the info.

Does it happen at a lower definition too? (`scrcpy -m 1024`)

**Comment by livingator** [comment]
yeah it does, i kept reducing it to 600 with no luck. also tried lowering bitrate to 2m and the only solution is what i said above. i really meant 2.0.8 because i'm the 1 mentioning about SmartNav issue and you suggested me to grab the dll from v 1.9 (2.0.8 SDL2.dll). so i can't really say if 2.0.10 is fine or not

**Comment by rom1v** [comment]
#425

**Comment by livingator** [comment]
welp i shouldn't have jinx it, the issue is back and i'm back trying to figure out if it can be solved

**Comment by livingator** [comment]
turning auto sleep off (asus zenfone 3) seems to be the real fix and not dll change, it's fixed now and running well for a couple days already.
