### ISSUE TITLE
when is 32 bit coming

### ISSUE THREAD

**Issue by Kaiju-A** [Genymobile/scrcpy#108]
when is the 32 bit version being released , not able to rebuild it on my own and no luck finding one

**Comment by rom1v** [comment]
I will probably provide a 32 bits version for the next release (which is not planned yet).

Meanwhile, I updated the [README](https://github.com/Genymobile/scrcpy/blob/master/README.md#windows) to list the required packages for Windows 32 bits.

**Comment by Kaiju-A** [comment]
can u make the instructions for windows, much clearer, detailed and less specific( file locations, etc ).
its hard to tell where im going wrong and if im doing it correctly

**Comment by rom1v** [comment]
The release v1.2 is available in 32 bits for windows :tada:
