### ISSUE TITLE
Netlifx black screen

### ISSUE THREAD

**Issue by ozshabat** [Genymobile/scrcpy#1085]
This problem already been mentioned in:
https://github.com/Genymobile/scrcpy/issues/62

I just wanted to know if someone resolved it.

I'm currently using versions:
scrcpy 1.12.1

dependencies:
 - SDL 2.0.9
 - libavcodec 58.35.100
 - libavformat 58.20.100
 - libavutil 56.22.100

And still having this annoying issue. 

btw, I tried to look in the settings of the app for a screen security setting or something like it, but there isn't any.

Thanks.

**Comment by StylishBoyGaming** [comment]
netflix used DRM(search on google) in app.. so that netflix dont allow to mirror or record its content

**Comment by rom1v** [comment]
That's expected, they use DRM.

**Comment by shaneHowearth** [comment]
FWIW I can watch Netflix using scrcpy, but I cannot watch Disney+.

Watching Netflix might be allowed because I have the DRM installed on my Ubuntu desktop?
Also the video comes through, but the audio doesn't (it's played on the tablet)

**Comment by rom1v** [comment]
> FWIW I can watch Netflix using scrcpy, but I cannot watch Disney+.

Yes, it depends on the DRM used (Level 1 or level 3 I think).

> Watching Netflix might be allowed because I have the DRM installed on my Ubuntu desktop?

No.

> Also the video comes through, but the audio doesn't (it's played on the tablet)

scrcpy does not forward audio.
