### ISSUE TITLE
scrcpy v1.12.1 scrcpy-noconsole.exe virus detected

### ISSUE THREAD

**Issue by nrlaiman** [Genymobile/scrcpy#1088]
Hi,
First of all, thank you very much for developing this useful tool.
My team & I are currently using scrcpy for our project. However, yesterday, McAfee antivirus has detected a virus threat on one of our team member's PC, originating from scrcpy-noconsole.exe file. The threatname/domain is RDN/Generic.RP.

I'm currently using v1.10 on my PC & after this incident happened, I've ran antivirus scan onto the scrcpy folder & .zip file but my McAfee antivirus did not detect any abnormalities on the v1.10 version.

Do you know any possible cause of this issue and perhaps fix it?
Thank you very much!

**Comment by rom1v** [comment]
Probably a false positive from your anti-virus…

https://www.virustotal.com/gui/url/883fcae2fd9f15c5644925a7ec39476d814f9c4e290df7684b4ead726fbf34aa/detection

**Comment by rom1v** [comment]
Oh, giving the URL to virustotal is not sufficient, it seems it does not follow the redirection (so it does not really scan the file).

The win32 version does actually trigger some antivirus. See #1102.

I'm closing this issue, please continue the discussion in #1102.
