### ISSUE TITLE
Keyboard presses are being sent out too fast(repetititve)

### ISSUE THREAD

**Issue by wieuwzak** [Genymobile/scrcpy#109]
Hi,

When using chat apps through scrcpy, one enter key press seems to send multiple enter key presses.
For instance, when I press enter in whatsapp, my message gets sent and the typing bar emptied itself. But also tries to send out a message that contains no letters. This gives me an annoying toast that says I cant send blank messages. Happens almost on every enter press. Looks like it sends multiple enter presses while it should be one.

**Comment by rom1v** [comment]
> one enter key press seems to send multiple enter key presses.

I am not able to reproduce for now.

**Comment by rom1v** [comment]
If you press enter in any text editor on your computer, does it sometimes generate several newlines?

What is your OS (Linux, Windows, macOS…)?

**Comment by EnderHDMC** [comment]
You can also test this in games and things. Minecraft is a good example. If you hold W, instead of it being one continuous keystroke, it seems to send it as many short keystrokes, this makes it impossible to walk properly. The character walks for a few milliseconds, stops, and repeats this until you let go of W.

**Comment by rom1v** [comment]
OK. So the solution is probably to [forward](https://github.com/Genymobile/scrcpy/blob/78da66f126e80ba7bb272e4105c9fc73e11b0ab6/app/src/convert.c#L121) the `repeat` field of [`SDL_KeyboardEvent`](https://wiki.libsdl.org/SDL_KeyboardEvent), and [inject](https://github.com/Genymobile/scrcpy/blob/78da66f126e80ba7bb272e4105c9fc73e11b0ab6/server/src/main/java/com/genymobile/scrcpy/EventController.java#L89) it on the device.

**Comment by wieuwzak** [comment]
My keyboard functions as normal in all other situations. I have "press enter to send message" option enabled in Whatsapp. I just feel like we are missing a basic function where repetitive keystrokes are being issued too fast. For example when long pressing enter in a normal situation, there's a time limit before a keystroke is being noticed as repetitive. But when in scrcpy I feel like that time limit is non existent? Rom1v thank you for your solution and work!

**Comment by maiconandsilva** [comment]
Same issue here. To me, It happens on Duolingo.

![captura de pantalla](https://user-images.githubusercontent.com/23154044/42039113-04453464-7ac3-11e8-93dd-87c2d91207e2.png)

Any advance on this issue? **Thanks in advance**

**Comment by rom1v** [comment]
Could you test with v1.4 please? Maybe #87 fixes your problem as a side-effect.

**Comment by maiconandsilva** [comment]
#### Tested with v1.4, and the issue now is typing latin characters like `áãàâ` or `óôòõ`. It duplicates the caracter with its correspondent without accents and tilde.

![screenshot_scrcpy](https://user-images.githubusercontent.com/23154044/46506036-60da9a00-c809-11e8-82a0-cd75140cc677.png)

**Comment by rom1v** [comment]
@maiconandsilva Thank you for your feedback.

> the issue now is typing latin characters like `áãàâ` or `óôòõ`

The fact that these chars are duplicated is still the same issue: it seems that there is a problem in your Android version either to convert a String to a list of events, or the way the events generated are interpreted.

If you (or someone having a device with the same problem) can figure out if something is wrong with the result of [`charMap.getEvents(chars)`](https://github.com/Genymobile/scrcpy/blob/v1.4/server/src/main/java/com/genymobile/scrcpy/EventController.java#L95).

The fact that the accents or tilde are not added is a separate issue, and probably comes from your Android keyboard not supporting "diacritical dead key characters" (see [Handle accented characters](https://blog.rom1v.com/2018/03/introducing-scrcpy/#handle-accented-characters)).

**Comment by Mehardeep** [comment]
SDL generates fake repeated keypresses if you hold a key long enough. This is used mostly for text input.
The original key press has .repeat == 0, and fake presses have .repeat == 1
SDL_KeyboardEvent *event 
   if(event->repeat ==0){
}

**Comment by rom1v** [comment]
Does it stlil happen on latest version?

**Comment by PIprog3592** [comment]
@rom1v  I think this issue still occurs. I tested on both the v1.12 and v1.14 in terms of typing into google docs, and if a key is held down long enough, it does seem to generate fake repeated keypresses (maybe that is where the lag comes from).

I think this is the issue I encountered in Minecraft as well. Once I hold down a key for an extended period of time, the character will continue moving for several seconds even after the key is released. It has nothing to do with the screen mirroring lag between computer and phone. 

Is there anyway I can fix it/reduce performance issues?

**Comment by rom1v** [comment]
Could you test with this change:

```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/Device.java b/server/src/main/java/com/genymobile/scrcpy/Device.java
index 349486c..9f1b69f 100644
--- a/server/src/main/java/com/genymobile/scrcpy/Device.java
+++ b/server/src/main/java/com/genymobile/scrcpy/Device.java
@@ -164,7 +164,7 @@ public final class Device {
     }
 
     public boolean injectEvent(InputEvent event) {
-        return injectEvent(event, InputManager.INJECT_INPUT_EVENT_MODE_ASYNC);
+        return injectEvent(event, InputManager.INJECT_INPUT_EVENT_MODE_WAIT_FOR_FINISH);
     }
 
     public boolean injectKeyEvent(int action, int keyCode, int repeat, int metaState) {
```

or this one:

```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/Device.java b/server/src/main/java/com/genymobile/scrcpy/Device.java
index 349486c..eb877e9 100644
--- a/server/src/main/java/com/genymobile/scrcpy/Device.java
+++ b/server/src/main/java/com/genymobile/scrcpy/Device.java
@@ -164,7 +164,7 @@ public final class Device {
     }
 
     public boolean injectEvent(InputEvent event) {
-        return injectEvent(event, InputManager.INJECT_INPUT_EVENT_MODE_ASYNC);
+        return injectEvent(event, InputManager.INJECT_INPUT_EVENT_MODE_WAIT_FOR_RESULT);
     }
 
     public boolean injectKeyEvent(int action, int keyCode, int repeat, int metaState) {
```

**Comment by PIprog3592** [comment]
@rom1v  

I think I have found the correct file under[https://github.com/Genymobile/scrcpy/blob/master/server/src/main/java/com/genymobile/scrcpy/Device.java ](url).

In order to make the change, how can I alter the code on my local PC? Or should I push the code onto github?

**Comment by rom1v** [comment]
No, you must apply the changes and [build](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md) locally.

Anyway, here is the server (to replace in v1.14) with `WAIT_FOR_FINISH`:

 - [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/issue109/1/scrcpy-server)
  _SHA256: a9d56b4b8914ad949f5f191f01a983c6a43df0c88b7ba4973881017bf851c7f3_

**Comment by PIprog3592** [comment]
@rom1v I have tested it on google docs on v1.14

It seems like the words continue to lag during typing. Visually, after the changes, there is a difference in typing, but not much improvement.

For the file you suggested, did you provide the "WAIT_FOR_FINISH" or the "WAIT_FOR_RESULT"?

**Comment by PIprog3592** [comment]
@rom1v  May you also supply the server for v1.12 for both "WAIT_FOR_FINISH" and "WAIT_FOR_RESULT"? Perhaps its a combination of both the rendering GUI + the keyboard issue.

**Comment by rom1v** [comment]
No, that was just a quick test, I don't think it has any impact. And there is no rendering issue on v1.14.

**Comment by PIprog3592** [comment]
Since we already tested "WAIT_FOR_FINISH", would the "WAIT_FOR_RESULT" improve performance instead?

I took a look at the java code on github, and it seemed like most of these changes are simply constant values in the Java InputManager class. Do you think there is something else that's slowing this down?

**Comment by rom1v** [comment]
The slowdown is probably in the Android rom itself when we send too many events too quickly.

**Comment by PIprog3592** [comment]
I see. Is there anyway this can be fixed? Or is this likely an issue on the android's part?

**Comment by rom1v** [comment]
I don't know. It greatly depends on the device. On my device I have no problem.

**Comment by PIprog3592** [comment]
What is your device? Do you have any settings on?

**Comment by PIprog3592** [comment]
I tested this over wireless, thinking that it may be the data cable being slow, but the keyboard lag is still persistant.

Under the developer options for my phone, I also reduced all three animation scales, forced GPU rendering, force 4x MSAA, hoping that it would improve my phone's performance, but did not fix the keyboard lag.

**Comment by PIprog3592** [comment]
I have noticed that when copy-pasting a long line of text in google docs, there is also a keyboard lag. Interestingly, the characters when pasted are typed out one by one on the display, rather than all at once.
