### ISSUE TITLE
scrcpy running, then device power off->power on again, can not show devices screen?

### ISSUE THREAD

**Issue by hongjojjay** [Genymobile/scrcpy#1092]
Hi, i have this below use case:
scrcpy is running, then power off device and power on again, manual run the scrcpy-server by "adb -s 988a98454858384c49 shell CLASSPATH=/data/local/tmp/scrcpy-server app_process / com.genymobile.scrcpy.Server 1.11 0 8000000 0 false - true false"
but device screen can not display.
Could you debug it?

**Comment by rom1v** [comment]
What isCprinted in the console? Also check the output of `adb logcat`.

**Comment by hongjojjay** [comment]
hi, thanks for your reply.
(1)I means, firstly scrcpy running successfully, and device screen display normally. Then device power off->power on, manual run the scrcpy-server by "adb -s 988a98454858384c49 shell CLASSPATH=/data/local/tmp/scrcpy-server app_process / com.genymobile.scrcpy.Server 1.11 0 8000000 0 false - true false", but device screen can not display.
(2)The adb logcat as below:
[server] ERROR: Exception on thread Thread[main,5,main]
java.io.IOException: Connection refused
        at android.net.LocalSocketImpl.connectLocal(Native Method)
        at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:292)
        at android.net.LocalSocket.connect(LocalSocket.java:145)
        at com.genymobile.scrcpy.DesktopConnection.connect(DesktopConnection.java:40)
        at com.genymobile.scrcpy.DesktopConnection.open(DesktopConnection.java:63)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:21)
        at com.genymobile.scrcpy.Server.main(Server.java:163)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)

**Comment by rom1v** [comment]
> manual run the scrcpy-server by "adb -s 988a98454858384c49 shell CLASSPATH=/data/local/tmp/scrcpy-server app_process / com.genymobile.scrcpy.Server 1.11 0 8000000 0 false - true false", but device screen can not display.

Why do you do that?

**Comment by hongjojjay** [comment]
Because my use case is automation test, running some test case, and then device power off->power on...
After that, i need get the devices screen again.

**Comment by rom1v** [comment]
> Because my use case is automation test, running some test case, and then device power off->power on...
> After that, i need get the devices screen again.

On power off, the device gets disconnected (and scrcpy is closed). Once it is powered on again (and detected by `adb` as connected), re-run `scrcpy` (not an internal command to start the server).
