### ISSUE TITLE
Add shortcut to rotate screen

### ISSUE THREAD

**Issue by MCMic** [Genymobile/scrcpy#11]
When I go back to home screen the phone goes back to portrait mode and then after starting an app I have to manually lean the phone to rotate the screen, it would be easier if there was a shorcut which rotates the screen.

**Comment by npes87184** [comment]
Reference #218

**Comment by rom1v** [comment]
As a workaround:

    # disable auto rotation
    adb shell settings put system accelerometer_rotation 0
    # use custom rotation (0=portrait, 1=landscape)
    adb shell settings put system user_rotation 1

https://github.com/Genymobile/scrcpy/issues/284#issuecomment-426269845

**Comment by ChristopherKrohn** [comment]
Is there a way to put the monitor in landscape while the camera is showing?
I tried the above commands both while scrcpy was active in terminal, and when it was not, and nothing happened when I executed the commands.

Am I missing something, or is the monitor simply not willing to be in landscape while the camera app is open?

**Comment by rom1v** [comment]
Some camera apps keep the device in landscape mode (and rotate their icons manually when the device is rotated). This avoids a glitch due to the portrait/landscape switch.

The "solution" is to implement a (manual) client-side rotation in scrcpy.

**Comment by ChristopherKrohn** [comment]
Aha, that makes sense! Thanks for the fast response!

Is there a simple way of implementing this, or is this something I should just leave be?
I'm just wondering if it is possible to rotate the mirror shown on my desktop some way.

I have absolutely no experience with this though.

**Comment by rom1v** [comment]
It is probably not very difficult, but it is quite intrusive (we need to check everywhere the current rotation to reverse width and height).

It's in my (virtual) todo list when I have time (maybe after the "device screen off" while mirroring).

**Comment by ChristopherKrohn** [comment]
Alright! Thanks!

In the meantime I'll just use another app that rotates with the screen.
Open Camera worked really well, for other users having the same issue.

Thanks again!

**Comment by agsola** [comment]
This would be great to be implemented in next release.

Appart from this it has everything needed to work daily with it.

**Comment by srevinsaju** [comment]
`def reorientP():
print("LOG: Passing REORIENT [POTRAIT]")
adb_reo = po("adb shell settings put system accelerometer_rota"
"tion 0; adb shell settings put system"
" user_rotation 0", shell=True)
def reorientL():
print("LOG: Passing REORIENT [LANDSCAPE]")
adb_reoo = po("adb shell settings put system accelerometer_rota"
"tion 0; adb shell settings put system"
" user_rotation 1", shell=True)
`
This is how reorient function is implemented in Python, in guiscrcpy,
https://github.com/srevinsaju/guiscrcpy

I don't know any C* code, so I couldn't open a pull request.

**Comment by manishxshrestha** [comment]
i added shortcut key for screen rotation
here's the code:
https://files.catbox.moe/c8lz87.c
Place input_manager.c inside project-> app--src folder and build it using
ninja -Cx
./run x

Ctrl+q = Change screen density to 200
Ctrl+w = Reset screen density
Ctrl+e = landscape mode
Ctrl+r = portrait mode

try this first in adb if rotation doesnt work
adb shell settings put system accelerometer_rotation 0

**Comment by rom1v** [comment]
I just implemented it on branch `rotatedevice` (eb0f339271862af38693913e5ce1d4078d2c9e56).

Just press `Ctrl`+`r` (or `Cmd`+`r` on macOS) to rotate the device.

Feedbacks welcome :)

**Comment by r4dixx** [comment]
Tested on Pixel 2 and Pixel 4 - Android 10
Works perfectly! Thanks

**Comment by rom1v** [comment]
Merged in `dev`.
