### ISSUE TITLE
Device disconnected error

### ISSUE THREAD

**Issue by IvorTollah** [Genymobile/scrcpy#1103]
Hi, I am running Linux Mint 19.3 Cinnamon version 44.8, the laptop I am using has an Intel Pentium CPU  N3710  @ 1.60GHz × 4 processor.

I have connected my Umidigi Z2 and have enabled USB debugging in the developer options, once the phone is connected to my laptop I have also selected "transfer files" from the MTP alert that appears in the notification shade. 

I have also run "_adb devices_" from the "_android_sdk/platform-tools/_" directory and confirmed that the laptop recognises the phone as a connected device. ]

After installing the SCRCPY snap package and running the scrcpy command from the terminal I get an error message (attached) saying the device is not connected, clearly it is and the system has recognised the phone is attached to the laptop. 

I initially thought it may have been because I was using an SD card as my internal storage, so I changed it to portable storage and tried again, still the same issue. 

![Device disconnected SCRCPY error](https://user-images.githubusercontent.com/56367983/72784270-5443b480-3c8d-11ea-9edd-bdabccd8e3ac.png)

Any help you can give me with this would be much appreciated.

**Comment by rom1v** [comment]
The server "crash" due to an `IllegalStateException`, which closes the socket connected to the client, causing the `Device disconnected` message.

This `IllegalStateException` is the same as #465 (so I'm closing this one).

_Please copy-paste text instead of posting screenshots, so that it can be found easily when searching an error message._

**Comment by rom1v** [comment]
Could you execute the following commands:

```
adb logcat -c
scrcpy
adb logcat -d > logcat.txt
```

then post `logcat.txt`, please?

**Comment by rom1v** [comment]
Also, out of curiosity, could you test with this server (replace it in v1.12.1):

[`scrcpy-server`](https://tmp.rom1v.com/scrcpy/issue465/2/scrcpy-server)  
_SHA-256: f4281e2b49eae96acaea8dbbb3dc447736b1f1237c61dc26d55e9ee1310172e0_

Here is the diff:
```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java b/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java
index 1c71eab..6966983 100644
--- a/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java
+++ b/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java
@@ -145,7 +145,7 @@ public class ScreenEncoder implements Device.RotationListener {
         format.setString(MediaFormat.KEY_MIME, "video/avc");
         format.setInteger(MediaFormat.KEY_BIT_RATE, bitRate);
         // must be present to configure the encoder, but does not impact the actual frame rate, which is variable
-        format.setInteger(MediaFormat.KEY_FRAME_RATE, 60);
+        format.setInteger(MediaFormat.KEY_FRAME_RATE, 30);
         format.setInteger(MediaFormat.KEY_COLOR_FORMAT, MediaCodecInfo.CodecCapabilities.COLOR_FormatSurface);
         format.setInteger(MediaFormat.KEY_I_FRAME_INTERVAL, iFrameInterval);
         // display the very first frame, and recover from bad quality when no new frames
```

**Comment by rom1v** [comment]
I just came across your reddit post: https://www.reddit.com/r/androidapps/comments/ers0dl/looking_for_an_app_that_will_allow_me_to_mirror/ff72703/

So it seems to be resolved by `scrcpy -m1024` (I post it here for other users).
