### ISSUE TITLE
Nothing happens on startup

### ISSUE THREAD

**Issue by antonok-edm** [Genymobile/scrcpy#1114]
The display on my Oneplus One with LineageOS broke recently so I tried this for the first time.

When I try to start `scrcpy` I get the following in my terminal:
```
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed. 4.9 MB/s (26202 bytes in 0.005s)
```

And the following output in `adb logcat`:
```
D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
W app_process: Could not reserve sentinel fault page
D AndroidRuntime: Calling main entry com.genymobile.scrcpy.Server
```

Other than that output, nothing visible happens - no window is opened.

Any help would be appreciated, thanks!

**Comment by rom1v** [comment]
>     W app_process: Could not reserve sentinel fault page

It seems it's just a warning, but should not prevent the process to start:
https://android.googlesource.com/platform/art/+/08a1d1ba90c69e4b39f2df90eacee2c5413f8b4e/runtime/runtime.cc#1227

I have never seen this before.

Could you add a log at the beginning of the `main()` method to see if it's called?
https://github.com/Genymobile/scrcpy/blob/39356602ed472cc3f533e36ae04a110b247c29e0/server/src/main/java/com/genymobile/scrcpy/Server.java#L152

Could you test the steps to execute a [hello world](https://blog.rom1v.com/2018/03/introducing-scrcpy/#hello-world) java application, please?

**Comment by antonok-edm** [comment]
@rom1v as luck would have it, my phone's screen started to work once again after a reboot. I suspect it was actually some kind of OS issue!

Just for the sake of closure, I tried running it once again and it appears to work flawlessly. Thanks for your quick response and awesome work on the tool :)
