### ISSUE TITLE
is it possible to simulate camera input through scrcpy?

### ISSUE THREAD

**Issue by Litchilitchy** [Genymobile/scrcpy#1115]
when I am connecting phone using scrcpy, is it possible to simulate camera input?

for example, the camera program is running, but the phone screen does not capture the picture through its camera, but the camera gets the input from my computer, e.g. a picture or a video.

**Comment by rom1v** [comment]
No, _scrcpy_ does not do that. I'm not sure it's even possible with standard ROMs.

**Comment by Litchilitchy** [comment]
got it, thanks. closed.

**Comment by Litchilitchy** [comment]
Reopened for it labelled 'question'.

**Comment by rom1v** [comment]
(because it was a question, but it can be closed :wink:)
