### ISSUE TITLE
the length of texts copying from devices to PC is limited to 4093.

### ISSUE THREAD

**Issue by NewUserHa** [Genymobile/scrcpy#1117]
https://github.com/Genymobile/scrcpy/issues/145#issuecomment-579276891

nowadays, the big file is not unusual.

what about increasing it to 32M or 64M? or even a whole binary data file like some .so or game data?

could it even detect clipboard changes automatically to avoid to let users need to find out they have to press c-c one time separately?

thanks!

**Comment by NewUserHa** [comment]
4093 is even unable to copy an Adaway host/DNS plain text file from devices to PC.

**Comment by rom1v** [comment]
> nowadays, the big file is not unusual.

If you want to copy a file, you should use `adb pull`.

> what about increasing it to 32M or 64M?

At the default bitrate (8Mbits/s, ie 1Mbyte/s), this would be the same size as 32 or 64 seconds of video in the clipboard. That seems huge to me.

Anyway, I guess the Android clipboard has a lower limit anyway: https://stackoverflow.com/questions/28100218/is-there-any-characters-bytes-limit-in-the-android-clipboard-android-developme

> could it even detect clipboard changes automatically to avoid to let users need to find out they have to press c-c one time separately?

I am not aware of any solution for this.

**Comment by NewUserHa** [comment]
>the big plain text config file is not unusual.

I feel the windows clipboard can handle big MBs plain text.

Then what about incresing it to 1M or 4M?

**Comment by NewUserHa** [comment]
so it's able to copy some big logs from devices to PC

**Comment by reversegear** [comment]
> 
> 
> so it's able to copy some big logs from devices to PC

Files can be easily copied via `adb pull` request
only text copy paste has a limitation

**Comment by rom1v** [comment]
> could it even detect clipboard changes automatically to avoid to let users need to find out they have to press c-c one time separately?

This is done by #1465. Please test it and provide feedback :)

I increased the clipboard size form 4k to 256k: [`clipboard`](https://github.com/Genymobile/scrcpy/commits/clipboard).

After all previous commits for making it possible, the increase is done by 913a9f3694362400761696c93d33f4301a10966e. On my computer, beyond 256k, `SDL_GetClipboard()` returns an empty string.

I implemented these changes above #1465, so shortcuts have changed! (TL;DR: use `Ctrl`+`c` to copy and `Ctrl`+`v` to paste).

Feedback welcome :)

## Binaries for testing

For windows users, take both `scrcpy.exe` and `scrcpy-server`, and replace them in your scrcpy v1.14 release.

For other platforms, take `scrcpy-server` and [build](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#prebuilt-server) only the client.

 - [`scrcpy.exe`](https://tmp.rom1v.com/scrcpy/1117/1/scrcpy.exe)
  _SHA256: b5fb3b193474702a6045545022e138a5daa7952ae3994dfa840491f694826231_
 - [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/1117/1/scrcpy-server)
  _SHA256: 15533c3d4a4a12a20e2afe9cd7dfb8efecd3f990227ac8262bb79998c1fc3af5_

**Comment by rom1v** [comment]
I rebased the increase from 4k to 256k on `dev` and merged, without the content of #1465 (which required more work).
