### ISSUE TITLE
Problems with keyboard (input)

### ISSUE THREAD

**Issue by usa052** [Genymobile/scrcpy#1122]
I've been looking for this program for a long time. And, at least, I've found it. But there is a problem. I use two languages (English & Russian).  I have problems with both. When I start to type everything works fine, but after I push "space" a few of my keys stops to work. I have no idea why. After a few words the error pops up: [server] WARN: Could not inject char u+0431
![000198 (2)](https://user-images.githubusercontent.com/60317056/73535520-d2921a80-4434-11ea-9dbf-2225ac980257.png)
It shows errors, but it continues to print 90% characters, except (see attachment)
In Russian, there are pretty necessary characters
![000199 (2)](https://user-images.githubusercontent.com/60317056/73536074-2ea96e80-4436-11ea-98d5-b94c153ab65d.png)
, it's a problem for me.

Thank you!

**Comment by rom1v** [comment]
> but after I push "space" a few of my keys stops to work

But before you press space, they worked?

**Comment by usa052** [comment]
It stops to work spontaneously (after a few words usually)
Phone: Xiaomi Remi Note 7
PC: Lenovo, Windows 10

**Comment by usa052** [comment]
Those keys [~, <, > : ; ' ] stops to work spontaneously for both languages (English/Russian) in the application.

(My laptop's keyboard works fine in Windows OS though)

**Comment by usa052** [comment]
Some application messed up with my input. Right now everything works stable!

Thank you!
