### ISSUE TITLE
can i use low compress rate codecs?

### ISSUE THREAD

**Issue by djdisodo** [Genymobile/scrcpy#1124]
like mpeg-2, h263
those codecs will work with lower cpu usages

**Comment by rom1v** [comment]
No, it only supports H.264 for now. But H.264 is typically both harware-encoded and decoded.

**Comment by djdisodo** [comment]
@rom1v do you have any plan to support other codecs?

**Comment by rom1v** [comment]
Probably when there are hardware encoders and decoders for the current generation of codecs (AV1, HEVC).
