### ISSUE TITLE
Hide and Show Mouse Cursor On KeyPress

### ISSUE THREAD

**Issue by hammad2224** [Genymobile/scrcpy#1127]
How can i hide the mouse cursor and show that on a key press event?

like in emulator games we press a key and mouse cursor is visible and then we press the same key again it locks and hides the mouse.

is it possible to do that is scrcpy?

**Comment by hammad2224** [comment]
@rom1v can you please answer this???

**Comment by rom1v** [comment]
No, it is not supported.

Do you mean "capturing the mouse" (#269), or just hide it?

**Comment by hammad2224** [comment]
i meant capture the mouse and hide it. like in emulators when you press a key mouse is shown and when you press the key again the mouse is hidden.

like in .net 
Cursor.Hide()
Cursor.Show()

**Comment by rom1v** [comment]
> i meant capture the mouse and hide it.

OK, so this is #269.

I'm closing as duplicate.
