### ISSUE TITLE
Mouse constant capture in games

### ISSUE THREAD

**Issue by maciejmrozinski** [Genymobile/scrcpy#1128]
Hi,

I'm trying to run GeForce Now app on Android 6 and stream it to Ubuntu 19.04 laptop. Is there any possibility to automatically capture mouse movements and restrict it to scrcpy window (as in VirtualBox window)?

**Comment by rom1v** [comment]
Hi,

For now, it is not possible.

There is a feature request: #269. I'm closing this one as a duplicate.
