### ISSUE TITLE
Specifying which device to connect to over TCP/IP

### ISSUE THREAD

**Issue by richbordoni** [Genymobile/scrcpy#1131]
Hi, I'm sorry if this isn't the right place for this. I read the instructions and they say that if you have more than one device under `adb devices` you have to specify the serial number of which device you want to connect to. But is there a way to specify which device you want to connect to over TCP/IP when you have multiple devices connected without using the serial number? Like just by specifying the IP address of the device or something like that? 

The reason I ask is because when devices are connected over USB the serial number is listed when you do `adb devices` (I'm pretty sure that's the serial number... right?) which makes it easy to then input as `scrcpy -s whateveryourserialnumberis` but when devices are connected over TCP/IP it just shows the IP. So you either have to have your serial number written down and saved somewhere or possibly run an adb command to get it (although I can't seem to get any to work). 

It's not a big deal for someone like me who is only ever really connecting to 2 devices, my phone and my tablet, but I'm interested in if there's a way to do this entirely within the command line rather than having to input the serial number from a saved file or a sticky note or something like that.

**Comment by rom1v** [comment]
For example:

```
scrcpy -s 192.168.0.1:5555
```

(it works like `adb -s …`)

**Comment by richbordoni** [comment]
Huh, I could've sworn that I tried that! I think I forgot to put the port on the end of it and then I don't know why I didn't try it again with the port. Well, thanks anyway! Works perfectly.

**Comment by rom1v** [comment]
> Might want to add that to the readme though?

1144f642144103a3b0bbd017998d75edd9d2a8b8 :+1:
