### ISSUE TITLE
May have perminant damage to my device after using the -S switch

### ISSUE THREAD

**Issue by GodlyEcstasy** [Genymobile/scrcpy#1136]
My device will now randomly switch to a black screen (its not turned off, its just black).  This never happened until my second day using this program. Things i've tried:
1. Not using the -S switch
2. Rebooting device and not starting the ADB Listening
3. Disabling developer options

Pls help

Edit: The screen was still viewable through this program but i've since disabled developer options hoping it would fix the issue

Edit 2: Device is LG G3 D850.  Not rooted, not capable of root (to my knowledge)

I'm just going to stop counting edits from here:

Now i'm noticing that when my phone is asleep, i can see the notification light.  When i attempt to turn the screen on, the light disappears until i either let the screen timeout and go back to sleep, or press the power button and make it sleep again.  Also using the right-click to wake the phone up has a much higher chance of actually turning on the display of my phone (9/10 right-clicks will turn it on while 3/10 power button clicks will turn it on)

**Comment by rom1v** [comment]
> Now i'm noticing that when my phone is asleep, i can see the notification light. When i attempt to turn the screen on, the light disappears until i either let the screen timeout and go back to sleep, or press the power button and make it sleep again. Also using the right-click to wake the phone up has a much higher chance of actually turning on the display of my phone (9/10 right-clicks will turn it on while 3/10 power button clicks will turn it on)

In fact, even when the screen is "turned off" (physically, but not in scrcpy), it is considered on. So if you press power, it switches off. You have to press it again to turn it on.

I initially implemented a shortcut to turn the physical screen on (without turning the whole thing off beforehand), but there were bugs in Android that could make it worse: https://github.com/Genymobile/scrcpy/issues/175#issuecomment-497946596
