### ISSUE TITLE
i have a problem "[server] ERROR: Exception on thread Thread[main,5,main]"when i use scrcpy

### ISSUE THREAD

**Issue by CrazyGoood** [Genymobile/scrcpy#1139]
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
E:\RTXC File List\scrcpy-win64-v1.12.1...shed. 6.2 MB/s (26202 bytes in 0.004s)
INFO: Initial texture: 1080x2336
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2698)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:92)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:7
3)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
        at com.genymobile.scrcpy.Server.main(Server.java:163)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:383)
WARN: Device disconnected
Press any key to continue...

**Comment by npes87184** [comment]
Try lower definition?

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#i-get-an-error-could-not-open-video-stream

**Comment by CrazyGoood** [comment]
thanks a lot @npes87184

**Comment by Jenfong** [comment]
> Try lower definition?
> 
> https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#i-get-an-error-could-not-open-video-stream

1.Is the same root case for this error? error log as follow:
# scrcpy -s 192.168.3.14:5555
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed. 1.0 MB/s (18802 bytes in 0.019s)
ERROR: Exception on thread Thread[main,5,main]
java.lang.NumberFormatException: For input string: "1.16"
	at java.lang.Integer.parseInt(Integer.java:615)
	at java.lang.Integer.parseInt(Integer.java:650)
	at com.genymobile.scrcpy.Server.createOptions(Server.java:52)
	at com.genymobile.scrcpy.Server.main(Server.java:101)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

2.version info

# adb --version
Android Debug Bridge version 1.0.40
Version c7815d675
Installed as /usr/bin/adb
]# scrcpy -v
scrcpy 1.16

dependencies:
 - SDL 2.0.12
 - libavcodec 58.54.100
 - libavformat 58.29.100
 - libavutil 56.31.100

# cat /etc/redhat-release 
Fedora release 32 (Thirty Two)

**Comment by rom1v** [comment]
> java.lang.NumberFormatException: For input string: "1.16"

You don't use the right `scrcpy-server`.

Maybe you installed a wrong version manually, or wrongly set `SCRCPY_SERVER_PATH` (unset it).

**Comment by MuhammedTaha02** [comment]
> > Try lower definition?
> > https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#i-get-an-error-could-not-open-video-stream
> 
> **### 1.Is the same root case for this error? error log as follow:**
> 
> ```
> # scrcpy -s 192.168.3.14:5555
> INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
> /usr/share/scrcpy/scrcpy-server: 1 file pushed. 1.0 MB/s (18802 bytes in 0.019s)
> ERROR: Exception on thread Thread[main,5,main]
> java.lang.NumberFormatException: For input string: "1.16"
> 	at java.lang.Integer.parseInt(Integer.java:615)
> 	at java.lang.Integer.parseInt(Integer.java:650)
> 	at com.genymobile.scrcpy.Server.createOptions(Server.java:52)
> 	at com.genymobile.scrcpy.Server.main(Server.java:101)
> 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
> 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
> ```
> 
> **### 2.version info**
> 
> ```
> # adb --version
> Android Debug Bridge version 1.0.40
> Version c7815d675
> Installed as /usr/bin/adb
> 
> # scrcpy -v
> scrcpy 1.16
> 
> dependencies:
>  - SDL 2.0.12
>  - libavcodec 58.54.100
>  - libavformat 58.29.100
>  - libavutil 56.31.100
> 
> #java -version
> java version "1.8.0_211"
> Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
> Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
> 
> # cat /etc/redhat-release 
> Fedora release 32 (Thirty Two)
> ```

I have the same problem. I am using Gentoo. And I tested it by downloading the ebuild file. How can I solve this problem?

**Comment by rom1v** [comment]
> java.lang.NumberFormatException: For input string: "1.16"

You don't use the same version for the server and the cliebt. If you use the prebuilt server, don't forget to download the version which matches the client version you compile.
