### ISSUE TITLE
KWin compositor crashes on scrcpy launch

### ISSUE THREAD

**Issue by LER0ever** [Genymobile/scrcpy#114]
On Plasma Desktop, compositor crashes on every scrcpy launch and recovers after scrcpy exits.

### Actual Behavior
Desktop effects and transparency not working, i.e. compositor exits or crashes.

### Environment
Desktop: KDE Plasma 5.12
Kernel: 4.16.0
Graphics: NVIDIA 390
Distro: Manjaro Linux

**Comment by rom1v** [comment]
Thank you for the report.

Are there any logs in the terminal when it crashes?

Some possibly related links:
- https://www.mail-archive.com/kde-bugs-dist@kde.org/msg88598.html
- https://www.mail-archive.com/kde-bugs-dist@kde.org/msg88606.html
- https://bugs.kde.org/show_bug.cgi?id=382485
- https://devtalk.nvidia.com/default/topic/1025735/kde-compositing-crash-on-nvidia-drivers-384-90-/

**Comment by LER0ever** [comment]
While there is nothing in stdout, there is a bunch of QPainter errors that may or may not be related to this. I've uploaded the `journalctl -f` output [here](https://pastebin.com/bZw0iK8P)

![screenshot_20180404_181922](https://user-images.githubusercontent.com/10568668/38339741-7ec4dda0-3835-11e8-8758-7c73892a2bde.png)

Also, I found that after the compositor recovers (that is after I Ctrl-C'ed the scrcpy), although the transparency and visual effects are back, I cannot take Window screenshot (full screenshot is fine), KWin crashes along with the compositor after I request the screenshot of my terminal window.

**Comment by LER0ever** [comment]
Ahh, sorry I did not read your links before replying... The issue is indeed due to SDL blocking the compositor, and I manage to work around this using KDE Window Rules (Preventing scrcpy from blocking compositors)

----------
Attaching the Window Rule config in case someone also need a temporary fix on this problem.
![image](https://user-images.githubusercontent.com/10568668/38340101-43136bc6-3837-11e8-83e1-037e4bb16aa4.png)
![image](https://user-images.githubusercontent.com/10568668/38340111-50e3acac-3837-11e8-8e7b-480cf02bfe98.png)

**Comment by Dakai** [comment]
@LER0ever Thank you! It works like a charm.

**Comment by rom1v** [comment]
Does #522 fixes the initial issue, or is it unrelated?
