### ISSUE TITLE
No display when connecting a vivo phone

### ISSUE THREAD

**Issue by Tyson0314** [Genymobile/scrcpy#1149]
Scrcpy: v1.12.1
Device: vivo
Android version: 9
ROM: funtouchos
Host: Windows 10

console log:
```
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
E:\scrcpy-win64-v1.12.1\scrcpy-server: 1 file pushed. 3.9 MB/s (26202 bytes in 0.006s)
INFO: Initial texture: 1080x2336
```

**Comment by Tyson0314** [comment]
The phone is connected to a remote computer with USB, there is no way to re-plug the USB.

**Comment by rom1v** [comment]
Looks like a hardware encoder problem.

**Comment by Tyson0314** [comment]
It worked fine a few days ago, and this problem appeared after restarting the remote computer today.

**Comment by Tyson0314** [comment]
Is there a way to solve this problem?

**Comment by rom1v** [comment]
Does screenrecord work?

```bash
adb shell screenrecord /sdcard/file.mp4
adb pull /sdcard/file.mp4
```

**Comment by Tyson0314** [comment]
No problem now, thank you~
