### ISSUE TITLE
Enforce Issue Template 

### ISSUE THREAD

**Issue by srevinsaju** [Genymobile/scrcpy#1157]
I have been noticing a lot of spam issues on scrcpy. it would be nice to have an issue template for example the Gimp Organization. this helps the maintainers to get all the information without asking for it again from the issue holder. 
this is a feature request, I have seen the same issue repeatedly come up again, out of the 1k issues, probably only 10% would be a genuine one.

thanks

**Comment by rom1v** [comment]
As a first step, I'm working of FAQ improvements: https://github.com/Genymobile/scrcpy/blob/faq/FAQ.md (branch `faq`).

(I'll reference the FAQ from the issue template)

Do you see other common problems which should be explained here?

**Comment by srevinsaju** [comment]
Ok, thanks for this, but I actually wanted to way to control the amount of spam issues which is not visually appealing to some extend, or which needs to be reported. This repository is developing very nice, and I personally didn't want the current position to go down. During the stream of unusual issues, I was forced to Unwatch the repository because it spammed by Inbox too. Maybe a member from @github could help us out.

**Comment by srevinsaju** [comment]
@rom1v , maybe it is necessary to add these to the FAQ improvement (some suggestions)
* add the add to PATH for Windows, Scrcpy too
```bash
scrcpy not found
```
* Add to PATH using GUI, as mentioned here https://www.architectryan.com/2018/08/31/how-to-change-environment-variables-on-windows-10/

* Shortcut to scrcpy on windows

**Comment by srevinsaju** [comment]
Thanks
