### ISSUE TITLE
Support screen recording

### ISSUE THREAD

**Issue by sergeyfitis** [Genymobile/scrcpy#116]
Feature request: Support screen recording

**Comment by meiser79** [comment]
duplicate of #21

**Comment by rom1v** [comment]
This is implemented in v1.5:

    scrcpy --record file.mp4

:tada:

**Comment by Noob567** [comment]
And how to stop screen recording?

**Comment by rom1v** [comment]
@Noob567 It stops when you close _scrcpy_.

**Comment by KeronCyst** [comment]
Also, is it possible for non-microphone audio recording to be added?

**Comment by lae** [comment]
@KeronCyst you can do this in bash.

    scrcpy --record $(date +%s).mp4

There's also the `audio` branch but I haven't been able to get it working myself.

**Comment by KeronCyst** [comment]
Sorry, by "bash" do you mean I can just enter that exactly as you put?
