### ISSUE TITLE
Record the audio output of the audio device while recording

### ISSUE THREAD

**Issue by burpheart** [Genymobile/scrcpy#1160]
I used OBS to achieve this goal, but I found that there is a certain loss of quality. 
And using OBS and scrcpy at the same time has a high CPU usage, which leads to even worse video quality.
This problem can be solved if scrcpy can add one or more audio input devices.
If possible, it's best to add audio delay options to correct the capture delay

**Comment by LBensman** [comment]
So you're able to use OBS to capture _audio_ and _video_ from Android?
