### ISSUE TITLE
Max Fps not working

### ISSUE THREAD

**Issue by sharukhkhanajm** [Genymobile/scrcpy#1168]
hi, this is a new issue which I found.
here is my command
adb devices
scrcpy -b 6m -m 1024 --max-fps 48 -n

when i run this i get this error
unknown option -- max-fps and unknown option -n

what should i do now i want to lock max fps at 48 or so any solution ?

**Comment by rom1v** [comment]
Which version of scrcpy do you use? (`scrcpy -v`)

**Comment by sharukhkhanajm** [comment]
scrcpy v1.2

dependencies:
 - SDL 2.0.8
 - libavcodec 58.18.100
 - libavformat 58.12.100
 - libavutil 56.14.100

**Comment by sharukhkhanajm** [comment]
thanks for your support I have updated the version and everything is working thanks :)
