### ISSUE TITLE
Cannot rotate some apps

### ISSUE THREAD

**Issue by LEENO82** [Genymobile/scrcpy#1180]
Hallo
cannot rotate some apps like this

`https://i.imgur.com/lKPzlEg.jpg`

tryed:

adb shell settings put system accelerometer_rotation 1

adb shell content insert --uri content://settings/system --bind name:s:accelerometer_rotation --bind value:i:1

adb shell settings put system user_rotation 1

adb shell content insert --uri content://settings/system --bind name:s:user_rotation --bind value:i:3

adb shell content insert — uri content://settings/system — bind name:s:user_rotation — bind value:i:3

but not fixed.

Tryed other apps like airdroid, have rotate button doing the job, but i like scrcpy, i hope can fix this problem

**Comment by rom1v** [comment]
#218

See PR https://github.com/Genymobile/scrcpy/pull/1151
