### ISSUE TITLE
cannot stat 'build-server/server/scrcpy-server': No such file or directory make: *** [Makefile.CrossWindows:100: dist-win32] Error 1

### ISSUE THREAD

**Issue by jhachandan1994** [Genymobile/scrcpy#1182]
I am getting below error while building crosswindows distribution file on ubuntu 19.10 please help:

```
Configuring config.h using configuration
Build targets in project: 2
Found ninja-1.9.0 at /usr/bin/ninja
ninja -C "build-win32-noconsole"
ninja: Entering directory `build-win32-noconsole'
[25/25] Linking target app/scrcpy.exe.
mkdir -p "dist/scrcpy-win32"
cp "build-server"/server/scrcpy-server "dist/scrcpy-win32/"
cp: cannot stat 'build-server/server/scrcpy-server': No such file or directory
make: *** [Makefile.CrossWindows:100: dist-win32] Error 1
```

**Comment by schyjxy** [comment]
I had the same problem, but you can find scrcpy.exe in scrcpy/build-win32/app, it means that complise server fail

**Comment by rom1v** [comment]
What command did you execute exacly?

**Comment by schyjxy** [comment]
make -f Makefile.CrossWindows

**Comment by rom1v** [comment]
>     cp "build-server"/server/scrcpy-server "dist/scrcpy-win32/"

It looks like it failed to build the server.

Do you have any failure related to gradle before the logs you posted? (did you install the Android SDK?)

But even if this is the case, it should fail before, without continuing…

What are the results of:
```
ls build-server
find -name scrcpy-server
```

**Comment by jhachandan1994** [comment]
> > ```
> > cp "build-server"/server/scrcpy-server "dist/scrcpy-win32/"
> > ```
> 
> It looks like it failed to build the server.
> 
> Do you have any failure related to gradle before the logs you posted? (did you install the Android SDK?)
> 
> But even if this is the case, it should fail before, without continuing…
> 
> What are the results of:
> 
> ```
> ls build-server
> find -name scrcpy-server
> ```

Yes I got the error as SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/home/lamarca/Downloads/scrcpy/local.properties'.

Then I made a local. Properties file in scrcpy directory and tried to compile the project using
make -f Makefile.CrossWindows
Then I got the above error. My Android sdk location is set in env variables of ubuntu still I got the above error.

**Comment by rom1v** [comment]
> Then I made a `local.properties` file in scrcpy directory and tried to compile the project using
`make -f Makefile.CrossWindows`

Do you have gradle logs when executing that command (suggesting that the server build have either succeeded or failed)?

**Comment by jhachandan1994** [comment]
> > Then I made a `local.properties` file in scrcpy directory and tried to compile the project using
> > `make -f Makefile.CrossWindows`
> 
> Do you have gradle-related logs when executing that command (suggesting that the server build have either succeeded or failed)?

here is the complete log after i run the makefile command:

Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

BUILD SUCCESSFUL in 51s
2 actionable tasks: 2 up-to-date
rm -rf "build-server" "build-win32" "build-win64" \
           "build-win32-noconsole" "build-win64-noconsole" "dist"
[ -d "build-server" ] || ( mkdir "build-server" && \
	meson "build-server" \
		--buildtype release -Dcompile_app=false )
The Meson build system
Version: 0.51.2
Source dir: /home/jhachandan/scrcpy-master
Build dir: /home/jhachandan/scrcpy-master/build-server
Build type: native build
Project name: scrcpy
Project version: 1.12.1
C compiler for the host machine: cc (gcc 9.2.1 "cc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Program ./scripts/build-wrapper.sh found: YES (/home/jhachandan/scrcpy-master/server/./scripts/build-wrapper.sh)
WARNING: Project targetting '>= 0.37' but tried to use feature introduced in '0.48.0': console arg in custom_target
DEPRECATION: build_always is deprecated. Combine build_by_default and build_always_stale instead.
Build targets in project: 2
WARNING: Project specifies a minimum meson_version '>= 0.37' but uses features which were added in newer versions:
 * 0.48.0: {'console arg in custom_target'}
Found ninja-1.9.0 at /usr/bin/ninja
ninja -C "build-server"
ninja: Entering directory `build-server'
[0/1] Generating scrcpy-server with a custom command.
(not invoking gradle, since we are root)
make -C prebuilt-deps prepare-win32
make[1]: Entering directory '/home/jhachandan/scrcpy-master/prebuilt-deps'
SDL2-2.0.10: found
ffmpeg-4.2.1-win32-shared: found
ffmpeg-4.2.1-win32-dev: found
platform-tools: found
make[1]: Leaving directory '/home/jhachandan/scrcpy-master/prebuilt-deps'
[ -d "build-win32" ] || ( mkdir "build-win32" && \
	meson "build-win32" \
		--cross-file cross_win32.txt \
		--buildtype release --strip -Db_lto=true \
		-Dcrossbuild_windows=true \
		-Dcompile_server=false \
		-Dportable=true )
The Meson build system
Version: 0.51.2
Source dir: /home/jhachandan/scrcpy-master
Build dir: /home/jhachandan/scrcpy-master/build-win32
Build type: cross build
Project name: scrcpy
Project version: 1.12.1
C compiler for the build machine: cc (gcc 9.2.1 "cc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008")
C compiler for the host machine: /usr/bin/i686-w64-mingw32-gcc (gcc 9.2.0 "i686-w64-mingw32-gcc (GCC) 9.2-win32 20191008")
Host machine cpu family: x86
Host machine cpu: i686
Target machine cpu family: x86
Target machine cpu: i686
Build machine cpu family: x86_64
Build machine cpu: x86_64
Library SDL2 found: YES
Library SDL2main found: YES
Library avcodec-58 found: YES
Library avformat-58 found: YES
Library avutil-56 found: YES
Library mingw32 found: YES
Library ws2_32 found: YES
Configuring config.h using configuration
Build targets in project: 2
Found ninja-1.9.0 at /usr/bin/ninja
ninja -C "build-win32"
ninja: Entering directory `build-win32'
[25/25] Linking target app/scrcpy.exe.
[ -d "build-win32-noconsole" ] || ( mkdir "build-win32-noconsole" && \
	meson "build-win32-noconsole" \
		--cross-file cross_win32.txt \
		--buildtype release --strip -Db_lto=true \
		-Dcrossbuild_windows=true \
		-Dcompile_server=false \
		-Dwindows_noconsole=true \
		-Dportable=true )
The Meson build system
Version: 0.51.2
Source dir: /home/jhachandan/scrcpy-master
Build dir: /home/jhachandan/scrcpy-master/build-win32-noconsole
Build type: cross build
Project name: scrcpy
Project version: 1.12.1
C compiler for the build machine: cc (gcc 9.2.1 "cc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008")
C compiler for the host machine: /usr/bin/i686-w64-mingw32-gcc (gcc 9.2.0 "i686-w64-mingw32-gcc (GCC) 9.2-win32 20191008")
Host machine cpu family: x86
Host machine cpu: i686
Target machine cpu family: x86
Target machine cpu: i686
Build machine cpu family: x86_64
Build machine cpu: x86_64
Library SDL2 found: YES
Library SDL2main found: YES
Library avcodec-58 found: YES
Library avformat-58 found: YES
Library avutil-56 found: YES
Library mingw32 found: YES
Library ws2_32 found: YES
Configuring config.h using configuration
Build targets in project: 2
Found ninja-1.9.0 at /usr/bin/ninja
ninja -C "build-win32-noconsole"
ninja: Entering directory `build-win32-noconsole'
[25/25] Linking target app/scrcpy.exe.
mkdir -p "dist/scrcpy-win32"
cp "build-server"/server/scrcpy-server "dist/scrcpy-win32/"
cp: cannot stat 'build-server/server/scrcpy-server': No such file or directory
make: *** [Makefile.CrossWindows:100: dist-win32] Error 1

**Comment by rom1v** [comment]
Is it generated somewhere else?

From your scrcpy root directory:

    find -name scrcpy-server

**Comment by jhachandan1994** [comment]
> Is it generated somewhere else?
> 
> From your scrcpy root directory:
> 
> ```
> find -name scrcpy-server
> ```

only meson logs are available:

Build started at 2020-02-29T08:33:56.735396
Main binary: /usr/bin/python3
Python system: Linux
The Meson build system
Version: 0.51.2
Source dir: /home/jhachandan/scrcpy-master
Build dir: /home/jhachandan/scrcpy-master/build-server
Build type: native build
Project name: scrcpy
Project version: 1.12.1
No CFLAGS in the environment, not changing global flags.
No LDFLAGS in the environment, not changing global flags.
No CPPFLAGS in the environment, not changing global flags.
Sanity testing C compiler: cc
Is cross compiler: False.
Sanity check compiler command line: cc -pipe -D_FILE_OFFSET_BITS=64 /home/jhachandan/scrcpy-master/build-server/meson-private/sanitycheckc.c -o /home/jhachandan/scrcpy-master/build-server/meson-private/sanitycheckc.exe
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /home/jhachandan/scrcpy-master/build-server/meson-private/sanitycheckc.exe
No CFLAGS in the environment, not changing global flags.
No LDFLAGS in the environment, not changing global flags.
No CPPFLAGS in the environment, not changing global flags.
Sanity testing C compiler: cc
Is cross compiler: False.
Sanity check compiler command line: cc -pipe -D_FILE_OFFSET_BITS=64 /home/jhachandan/scrcpy-master/build-server/meson-private/sanitycheckc.c -o /home/jhachandan/scrcpy-master/build-server/meson-private/sanitycheckc.exe
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /home/jhachandan/scrcpy-master/build-server/meson-private/sanitycheckc.exe
C compiler for the host machine: cc (gcc 9.2.1 "cc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Program ./scripts/build-wrapper.sh found: YES (/home/jhachandan/scrcpy-master/server/./scripts/build-wrapper.sh)
WARNING: Project targetting '>= 0.37' but tried to use feature introduced in '0.48.0': console arg in custom_target
DEPRECATION: build_always is deprecated. Combine build_by_default and build_always_stale instead.
Build targets in project: 2
WARNING: Project specifies a minimum meson_version '>= 0.37' but uses features which were added in newer versions:
 * 0.48.0: {'console arg in custom_target'}
Found ninja-1.9.0 at /usr/bin/ninja

**Comment by rom1v** [comment]
> only meson logs are available

What is the result of `find -name scrcpy-server`? It does not return anything?

This is weird because you get `BUILD SUCCESSFUL in 51s` for the gradle build.

**Comment by jhachandan1994** [comment]
> > only meson logs are available
> 
> What is the result of `find -name scrcpy-server`? It does not return anything?
> 
> This is weird because you get `BUILD SUCCESSFUL in 51s` for the gradle build.

yes i am getting empty response i think the server file is not generated is it possible to use prebuilt server while using the make -f Makefile.CrossWindows command to make distribution for windows.

**Comment by jhachandan1994** [comment]
problem is solved i solved the problem by defining ANDROID_SDK_ROOT in my environment variables and removing ANDROID_HOME from the environment variables.

Thanks
