### ISSUE TITLE
Unknown Option

### ISSUE THREAD

**Issue by StuffOfSonny** [Genymobile/scrcpy#1183]
For reasons I don't understand, any time I attempt to run a command, I am met with an "unknown option" error. I've tried reformatting the commands in various styles but nothing seems to be making them work.

![cmd_2020-02-27_14-55-47](https://user-images.githubusercontent.com/61560546/75481600-4f031500-5971-11ea-9fa1-e525459e0345.png)

**Comment by rom1v** [comment]
It's `scrcpy --window-borderless` or `scrcpy.exe --window-borderless`, not `scrcpy.exe scrcpy --window-borderless`.

**Comment by rom1v** [comment]
(Please copy-paste text instead of posting a screenshot of a terminal)

**Comment by StuffOfSonny** [comment]
I apologize for using a screencap over text.
That said, the error persists.

C:\Users\[Name Withheld]>D:Libaries\Programs\scrcpy-win64\scrcpy --window-borderless
D:Libaries\Programs\scrcpy-win64\scrcpy: unknown option -- window-borderless

C:\Users\[Name Withheld]r>D:Libaries\Programs\scrcpy-win64\scrcpy.exe --window-borderless
D:Libaries\Programs\scrcpy-win64\scrcpy.exe: unknown option -- window-borderless

**Comment by rom1v** [comment]
_(There is no space between `--` and `window-borderless`.)_

Which scrcpy version do you use?

```
scrcpy -v
```

**Comment by StuffOfSonny** [comment]
I am not adding the space between `-- `and `window-borderless`, that is Command Line's error reporting.

scrcpy 1.10 should I also include the dependencies?

**Comment by rom1v** [comment]
`--window-borderless` has been added in 1.11.

Just download the latest version.

**Comment by StuffOfSonny** [comment]
Were the window positioning tools also added in 1.11? Because those were not working either.

**Comment by StuffOfSonny** [comment]
Well, The old issue is now solved, but a new one has arose, as it doesn't seem to recognize my secondary monitor. Since I have the monitor set to the left of my Main display, the target X position is in the negatives, however scrcpy tells my that -686 is outside of its range (-1, 32767).
I tried assuming it'd loop around, but that was not the case.

**Comment by rom1v** [comment]
Yes, because passing a negative number to SDL (the framework used by scrcpy) just did not work. So I didn't authorize it.

**Comment by StuffOfSonny** [comment]
So is it safe to assume there is no means of getting it onto my leftmost display whilst retaining the borderless window at the current time? Using arrows+windows key snaps it to a few fixed locations, but none of them are satisfactory.

**Comment by rom1v** [comment]
In fact it seems to work on some windows manager. See #1242.
