### ISSUE TITLE
Start video recording not at startup but at any time

### ISSUE THREAD

**Issue by dedosmedia** [Genymobile/scrcpy#1186]
Hi.
I just want to ask about this feature. I would like to start researching how to do it, but first I need to know your opinion on whether this is a feasible option or definitively it would not work.  
I would like to pass an option like --recording_time=10 (seconds) and once I type a shortcut (Ctrl+Shift+R) on the window, scrcpy starts recording a video for 10 seconds.
I would need to record several videos during a single session (it does not matter if all the videos are going to be saved with the same filename).
would it be possible? If so, any ideas to start working on?

**Comment by rom1v** [comment]
Ref #475 #1032 

For my information, what is your concrete use case to record videos of exactly 10 seconds?

Recording may only start on new keyframe (it may not just be "passive", record where you are). To start recording in the middle of the stream, the client must request to the device to generate a new keyframe (typically, just restart the encoding like on device rotation), then ignore all frames received before that keyframe (+ the config packet).

**Comment by dedosmedia** [comment]
This is a specific use case, for a videobooth project I am doing integrating Android + Windows TouchScreen Kiosk.  There is Spark AR filter running into the Android and I need to record a video from that for about 10 seconds, the start recording command will come from an user interaction with the Windows Kiosk which I will forward to scrcpy (I use scrcpy only for visualization, people are not able to interact with phone neither through its screen nor the scrcpy window).
I was thinking about to launch adb screenrecord, and then pull the video but in that case, I would need to crop the video (as I launch scrcpy with --crop 720:720:x:y -n) and I want to avoid another extra step, but maybe this is much more difficult to do what I was thinking for.
