### ISSUE TITLE
Server debug: handshake failed - connection prematurally closed

### ISSUE THREAD

**Issue by dedosmedia** [Genymobile/scrcpy#1187]
I am using msys2 for building scrcpy for windows.

This is how I configure meson:
meson debug --buildtype debug --strip -Db_lto=true -Dportable=true -Dcompile_app=false -Dcompilie_server=true -Dserver_debugger=true
ninja -Cdebug

First, I downloaded the binaries  (1.12.1)  from the releases into github. I copied them to C:\scrcpy
Once ninja finish building, I move the file from /debug/server/scrcpy-server  into C:\scrcpy\ scrcpy-server

I launch scrcpy, it shows my device screen, so it's working great.
Then from the command line: adb forward tcp:5005 tcp:5005
(adb forward --list  shows it's right)

Then with Android Studio( 3.4.2)  and scrcpy sources from the master branch, I load the scrcpy/server project into Android Studio. Then Edit configurations ->+ Remote with info: localhost and 5005 

Whenever I start to debug from Android Studio I get: 
Error running 'debug': Unable to open debugger port (localhost:5005): java.io.IOException "handshake failed - connection prematurally closed"

What am I doing wrong?

**Comment by rom1v** [comment]
> Then with Android Studio( 3.4.2) and scrcpy sources from the master branch, I load the scrcpy/server project into Android Studio. Then Edit configurations ->+ Remote with info: localhost and 5005

What are you trying to do?

**Comment by dedosmedia** [comment]
I am trying to get a screenshot with a shortcut.
I know there is a: adb exec-out screencap -p > file.png, to run from a command line, anyway I wanted something integrated to scrcpy.
So I also did a similar thing but launching it from a shortcut into scrcpy (Ctrl+Shift+s).
It launches adb exec-out screencap -p  (much the same like scrcpy does any other adb_execute calls) and then I am saving the STDOUT to a file and It works, just a delay ( You already explained why this delay with adb shell calls). So know I would like to learn how to do it but from the server and then send it to the client already cropped (when --crop is used). 
I know it's too much difficult, first because I have never done android programming, second because there is not a Context (I think) but at least if I am not able to do it, I will learn new things.

**Comment by dedosmedia** [comment]
Seems that I have to enable -Dcompile_app=true also. Anyway although I see the log: 
INFO: Server debugger waiting for a client on device port 5005...
when I start Debug on Android Studio I get the same error.

**Comment by dedosmedia** [comment]
I have compiled scrcpy.exe and scrcpy-server again using MSYS2, with :
```
meson release --buildtype release --strip -Db_lto=true -Dportable=true -Dcompile_app=true -Dcompilie_server=true -Dserver_debugger=true
```
I have pushed scrcpy-server to Android like this:
```
adb push scrcpy-server /data/local/tmp/scrcpy-server.jar
Then:
```
adb reverse localabstract:scrcpy tcp:27183
forward tcp:5005 tcp:5005
```

The started the server through app_process like this:
```
./adb shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process -agentlib:jdwp=transport=dt_socket,suspend=n,server=y,address=5005 / com.genymobile.scrcpy.Server 1.12.1 0 8000000 0 false - true true
```

**Comment by dedosmedia** [comment]
I had to change:
```
"-agentlib:jdwp=transport=dt_socket,suspend=n,server=y,address=" SERVER_DEBUGGER_PORT,
```
by:
```
"-XjdwpProvider:internal -XjdwpOptions:transport=dt_socket,suspend=n,server=y,address=" SERVER_DEBUGGER_PORT,
```
And finally I was able to debug the server.  Do you know why?

**Comment by dedosmedia** [comment]
Finally, I was able to do some changes to the server. I am using the code from:
https://github.com/rayworks/DroidCast/blob/master/app/src/main/java/com/rayworks/droidcast/ScreenCaptorUtils.java#L15

Right now I have the shortcut Ctrl+Shift+S which send the controlmessage to the server, the server is taking the screenshot and returning it as a bitmap, then it's being cropped according to the -crop argument, and it has into account the device rotation (only tested in Android P, as lower Android versions do not have rotation parameter in the screenshot call, so I don't know how to handle it).
The bitmap is being compressed as PNG and being stored in SDcard, but I would like to send it directly to the client. Would it be possible?

**Comment by dedosmedia** [comment]
I was able to send the Image as bytearray through the control socket connection, but it was so slow... a screenshot at 1080x1920 is about 3 MB (png), and takes 4 seconds to transfer. 
I decided to save the picture on the android, and then I call adb_execute inside the client to execute "adb pull  /sdcard/picture.png", it works, and it seems the transfer time is quicker (just the transfer time), because executing adb pull takes some time before it starts transferring the file, so it takes 2 or 3 seconds.

Why is h264 encoded stream transfer so quickly? it's because of the compression? the socket configuration?

Sorry, for bothering you  @rom1v with these things, I just want to try to make some changes to your version by myself.  Thanks for your patience.

**Comment by rom1v** [comment]
> I was able to send the Image as bytearray through the control socket connection, but it was so slow... a screenshot at 1080x1920 is about 3 MB (png), and takes 4 seconds to transfer.

How did you encode the screenshot to png?

If you capture it as a bitmap transferred to the CPU, then encode it to PNG, it adds some latency:
 - transfer the big bitmap to the main memory
 - encode it with the CPU (slow!)

I am not sure, but I guess `MediaCodec` use hardware encoder even for pictures: https://developer.android.com/guide/topics/media/media-formats#image-formats
That way, you could retrieve a compressed picture immediately.

But anyway, a lossless picture (PNG) will take some time to transfer… but maybe it's acceptable.

> Why is h264 encoded stream transfer so quickly?

It's hardware encoded, and the video is very compressed. For example, by default scrcpy requests 8Mbits/s, which is 1Mbyte/s, which is, at 60fps, 17Kb/frame! (it's a mean, the keyframes are way bigger than the others).

**Comment by dedosmedia** [comment]
Maybe you or someone else wanted to take a look at my changes.
Sorry, maybe my code is not that great, It's just a first step to implement this feature, I have seen some people asking for something similar.


https://github.com/dedosmedia/scrcpy/tree/server_screenshot
https://github.com/Genymobile/scrcpy/compare/master...dedosmedia:server_screenshot

> How did you encode the screenshot to png?

I am taking a screenshot (Bitmap) with SurfaceControl, then to compress it as PNG, I just do:
```bitmap.compress(Bitmap.CompressFormat.PNG, 100, out);```

> If you capture it as a bitmap transferred to the CPU, then encode it to PNG, it adds some latency:
> 
> * transfer the big bitmap to the main memory
> * encode it with the CPU (slow!)
> I am not sure, but I guess `MediaCodec` use hardware encoder even for pictures: https://developer.android.com/guide/topics/media/media-formats#image-formats
> That way, you could retrieve a compressed picture immediately.
> 
It would be wonderful that way, however, I don't know how to do it with MediaCodec. Any help appreciated.
I agree using SurfaceControl and encoding on CPU is slow, although saving a screenshot directly from scrcpy is a little bit better for me than using exec-out screencap from the command line.

> But anyway, a lossless picture (PNG) will take some time to transfer… but maybe it's acceptable.
>
JPG would be great too if that reduces the transfer time a bit.


> > Why is h264 encoded stream transfer so quickly?
> 
> It's hardware encoded, and the video is very compressed. For example, by default scrcpy requests 8Mbits/s, which is 1Mbyte/s, which is, at 60fps, 17Kb/frame! (it's a mean, the keyframes are way bigger than the others).

That's a crazy difference!! I understand why it's so quick!! Thanks for clarifying it 


BTW, I still have the same issue with "handshake failed - connection prematurely closed" when trying to debug on Android Studio, so I had to change this line: 
https://github.com/dedosmedia/scrcpy/blob/a685138aacf85a2212eaecbb51ebc8efe9325e42/app/src/server.c#L137
Actually it's the issue why I originally opened this case. It would be a good thing if I could solve it too.

I also had another issue which I posted here:
https://github.com/Genymobile/scrcpy/issues/1209#issue-581011033


Thanks so much for your time.

**Comment by rom1v** [comment]
> It would be wonderful that way, however, I don't know how to do it with MediaCodec. Any help appreciated.

You could check [`ScreenEncoder`](https://github.com/Genymobile/scrcpy/blob/master/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java) and adapt.

> BTW, I still have the same issue with "handshake failed - connection prematurely closed" when trying to debug on Android Studio, so I had to change this line:
> https://github.com/dedosmedia/scrcpy/blob/a685138aacf85a2212eaecbb51ebc8efe9325e42/app/src/server.c#L137

So you replaced:

    "-agentlib:jdwp=transport=dt_socket,suspend=y,server=y,address="

by:

    "-XjdwpProvider:internal -XjdwpOptions:transport=dt_socket,suspend=n,server=y,address="

Is `suspend=n` necessary (instead of `y`)?

Sorry, I don't understand those magic incantations. Which ones are supposed to work in which environment? :confused:

**Comment by dedosmedia** [comment]
> You could check [`ScreenEncoder`](https://github.com/Genymobile/scrcpy/blob/master/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java) and adapt.
> 
Thanks, I will take a look at it!

> So you replaced:
> 
> ```
> "-agentlib:jdwp=transport=dt_socket,suspend=y,server=y,address="
> ```
> 
> by:
> 
> ```
> "-XjdwpProvider:internal -XjdwpOptions:transport=dt_socket,suspend=n,server=y,address="
> ```
> 
> Is `suspend=n` necessary (instead of `y`)?
> 
Yes, that is exactly what I did. 
suspend=y  also works (only that I don't always need to debug server, so I don't like scrcpy to wait for the debugger before being launched)
The issue is only -agentlib:jdwp not being recognized.

> Sorry, I don't understand those magic incantations. Which ones are supposed to work in which environment? 😕
>
Yes, I know you don't build it from windows so I suppose it's due to my environment (windows/MSYS2).
I tried to prepare a Docker container for compiling from there, but I had a lot of issues. Maybe I need to try to run a Debian/Ubuntu VM instead and cross compile. Anyway thanks for taking a look at this

**Comment by dedosmedia** [comment]
I got an Android 8.1 device, and I was able to debug the server without making changes, so -agentlib:jdwp seems to work perfectly on Android Oreo, but it does not work for me on Android Pie 
Not sure if it's something just happening to Android Pie+ (The same happens on two different Android Pie devices I have).

Looking at ART sourcecode I can see the same Logcat error message I am having with Android Pie (The line was added on 2018, so I suppose it was a change for Android Pie): https://android.googlesource.com/platform/art/+blame/master/runtime/runtime.cc#1432

@rom1v Could you confirm you are able to debug the server on Android Pie?

**Comment by rom1v** [comment]
@dedosmedia Indeed, I tested on two devices (Android 6, Android 10), one method only works on my Android 6, the other only on Android 10.

So I added a compilation flag: https://github.com/Genymobile/scrcpy/commit/902b99174df8ffc1fe7548399c19e446aa5488b6

Thank you :+1:

**Comment by dedosmedia** [comment]
@rom1v  Thanks to you for solving it! It works like a charm
