### ISSUE TITLE
casting full 360 degree view of vr headsets (android based)

### ISSUE THREAD

**Issue by snoledan** [Genymobile/scrcpy#1196]
Hi 
Is there any way to cast and record one single full 360 degree view of what is playing on Oculus Go ?
thanks

**Comment by rom1v** [comment]
Not with scrcpy, which captures the surface (what is rendered).

**Comment by snoledan** [comment]
> Not with scrcpy, which captures the surface (what is rendered).
do you know any other application which can make it?

**Comment by rom1v** [comment]
No, I don't. (I would have said it)
