### ISSUE TITLE
Can't Click on things

### ISSUE THREAD

**Issue by TacoBuritt0** [Genymobile/scrcpy#1198]
So I can click to swipe between homescreens just fine, I can use mouseclicks to go back/home, and the keyboard works fine. But I can't directly click like to open an app or select an onscreen item.
Phone is an LG V40 Thinq

**Comment by rom1v** [comment]
Which version of scrcpy?

Do you have such an option:
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#i-can-only-mirror-i-cannot-interact-with-the-device
?

**Comment by TacoBuritt0** [comment]
Running the latest version. And no, sadly that isn’t a setting on this phone



________________________________

**Comment by TacoBuritt0** [comment]
So its working now, I don't know what was going on before but I've just tried again without changing anything and its working fine
