### ISSUE TITLE
adb push error

### ISSUE THREAD

**Issue by padok** [Genymobile/scrcpy#12]
I installed the last version with 
```
padok@Idris:~/git/scrcpy$ meson x --buildtype release --strip -Db_lto=true
The Meson build system
Version: 0.42.1
Source dir: /home/padok/git/scrcpy
Build dir: /home/padok/git/scrcpy/x
Build type: native build
Project name: scrcpy
Native C compiler: cc (gcc 7.2.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency libavformat found: YES 57.71.100
Native dependency libavcodec found: YES 57.89.100
Native dependency libavutil found: YES 55.58.100
Native dependency sdl2 found: YES 2.0.6
Configuring config.h using configuration
Program ./scripts/build-wrapper.sh found: YES (/home/padok/git/scrcpy/server/./scripts/build-wrapper.sh)
Build targets in project: 6
padok@Idris:~/git/scrcpy$ cd x
padok@Idris:~/git/scrcpy/x$ ninja
[30/30] Generating scrcpy-server with a custom command.
:server:preBuild UP-TO-DATE
:server:preReleaseBuild UP-TO-DATE
:server:compileReleaseAidl UP-TO-DATE
:server:compileReleaseRenderscript UP-TO-DATE
:server:checkReleaseManifest UP-TO-DATE
:server:generateReleaseBuildConfig UP-TO-DATE
:server:prepareLintJar UP-TO-DATE
:server:generateReleaseResValues UP-TO-DATE
:server:generateReleaseResources UP-TO-DATE
:server:mergeReleaseResources UP-TO-DATE
:server:createReleaseCompatibleScreenManifests UP-TO-DATE
:server:processReleaseManifest UP-TO-DATE
:server:splitsDiscoveryTaskRelease UP-TO-DATE
:server:processReleaseResources UP-TO-DATE
:server:generateReleaseSources UP-TO-DATE
:server:javaPreCompileRelease UP-TO-DATE
:server:compileReleaseJavaWithJavac UP-TO-DATE
:server:compileReleaseNdk NO-SOURCE
:server:compileReleaseSources UP-TO-DATE
:server:lintVitalRelease
:server:mergeReleaseShaders UP-TO-DATE
:server:compileReleaseShaders UP-TO-DATE
:server:generateReleaseAssets UP-TO-DATE
:server:mergeReleaseAssets UP-TO-DATE
:server:transformClassesWithPreDexForRelease UP-TO-DATE
:server:transformDexWithDexForRelease UP-TO-DATE
:server:mergeReleaseJniLibFolders UP-TO-DATE
:server:transformNativeLibsWithMergeJniLibsForRelease UP-TO-DATE
:server:processReleaseJavaRes NO-SOURCE
:server:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:server:packageRelease UP-TO-DATE
:server:assembleRelease

BUILD SUCCESSFUL in 1s
24 actionable tasks: 1 executed, 23 up-to-date
padok@Idris:~/git/scrcpy/x$ sudo ninja install
[1/2] Generating scrcpy-server with a custom command.
(not invoking gradle, since we are root)
[1/2] Installing files.
Installing app/scrcpy to /usr/local/bin/scrcpy
Stripping target 'app/scrcpy'
Installing server/scrcpy-server.jar to /usr/local/share/scrcpy/scrcpy-server.jar
```

---
When I tried to use scrcpy with my mobile phone I got the error message
```
padok@Idris:~/git/scrcpy/x$ adb connect 10.80.0.138
connected to 10.80.0.138:5555
padok@Idris:~/git/scrcpy/x$ scrcpy 
exec: No such file or directory
ERROR: "adb push" returned with value 1
```

The adb command seems to work.
```
padok@Idris:~/git/scrcpy/x$ adb push server/scrcpy-server.jar /data/local/tmp/scrcpy-server.jar
server/scrcpy-server.jar: 1 file pushed. 0.7 MB/s (19038 bytes in 0.025s)
```

My phone is an Oneplus One (bacon) running LineageOS 14.1-20180128

**Comment by rom1v** [comment]
Currently, it [does not work](https://github.com/Genymobile/scrcpy/issues/5) over `adb connect`.

What if you use it over usb instead?

**Comment by stek29** [comment]
> exec: No such file or directory

Are you sure that adb is in PATH?

**Comment by aarmea** [comment]
More specifically, the issue causing  is that [exec expects your PATH to be fully expanded](https://github.com/torvalds/linux/blob/v4.12/arch/um/os-Linux/execvp.c#L71). Apparently, tilde expansion [is a feature of the shell](https://stackoverflow.com/questions/17609732/expand-tilde-to-home-directory).

Here are two workarounds that work for me:

* Manually expand the tildes in your PATH: `PATH="$PATH:$HOME/Android/Sdk/platform-tools" scrcpy`
* Set the ADB environment variable before calling scrcpy: `ADB=$(which adb) scrcpy`

**Comment by rom1v** [comment]
> Apparently, tilde expansion is a feature of the shell.

Absolutely.

> Manually expand the tildes in your PATH

Yes, that's a requirement.

> Set the ADB environment variable before calling scrcpy: `ADB=$(which adb) scrcpy`

I think this should not change anything: if `which adb` gives a result, then it's in `PATH`, so `scrcpy` would find it.

**Comment by aarmea** [comment]
On my machine (whose PATH contains "~/Android/Sdk/platform-tools") `scrcpy` does not work but `ADB=$(which adb) scrpy` does. I think this is because exec doesn't do tilde expansion, while [`which` does](https://cvs.savannah.gnu.org/viewvc/which/which/tilde/tilde.c?revision=1.2&view=markup).

**Comment by aarmea** [comment]
Yeah - my point is that `which` will implicitly do the tilde expansion as expected, but calls to `execvp` ([like this one in scrcpy](https://github.com/Genymobile/scrcpy/blob/master/app/src/sys/unix/command.c#L15)) do not.

**Comment by rom1v** [comment]
> Yeah - my point is that `which` will implicitly do the tilde expansion

Yes, but this surprises me.

>  as expected

IMO `which` should not expand `~` in `PATH` (and it does not on my _Debian_, cf my previous message) for consistency, since `exec` does not not expand it.

**Comment by aarmea** [comment]
> it does not on my Debian

TIL. I just tried this out on Debian and I'm getting the same result as you. It looks like this is because Debian uses its own implementation of `which` while Arch uses `which` from coreutils.
