### ISSUE TITLE
Setting Window Title

### ISSUE THREAD

**Issue by SamuraiWaffle** [Genymobile/scrcpy#120]
It would be nice to have a command option to set the window title. That way having multiple windows isn't so troublesome to look through/organize on your desktop.

**Comment by tomasv01** [comment]
Hi Rom1v, this would be perfect. I'm testing many devices with the same model number. Just add new parameter to set name for specific serial-number.
Let me say  - your application is absolutely astoshing.
Thank you very much.

**Comment by beango1** [comment]
Hi Rom1v,

how about we just put this in line 368 to from 'device_name' to '(options->serial ? options->serial : device_name)' ?

**Comment by rom1v** [comment]
@beango1 I don't think so, IMO selecting the device by serial (because there are several) should not impact the window title.

**Comment by rom1v** [comment]
Implemented by #614.
