### ISSUE TITLE
Segfault on certain device

### ISSUE THREAD

**Issue by abvgeej** [Genymobile/scrcpy#1204]
[logcat](https://gist.github.com/abvgeej/df47dcb219ad5cc569c770ef1dd288a7)
[build.prop](https://gist.github.com/abvgeej/4abe4bc698246a642894671344eb5d97)

**Comment by rom1v** [comment]
>     I/dalvikvm(11929): Unable to open or create cache for /data/local/tmp/scrcpy-server.jar (/data/dalvik-cache/data@local@tmp@scrcpy-server.jar@classes.dex)

Which Android version?

```
adb shell ls -l /data/local/tmp
adb shell ls /data/local/tmp
```

Could you write a file in `/data/local/tmp`?

**Comment by abvgeej** [comment]
Pardon my ignorance, but I just read that anything below API 21 is not supported, and I am on Android 4.2 (API 17).
