### ISSUE TITLE
Fails with more than one device or emulator.. even if theres only one device

### ISSUE THREAD

**Issue by cswl** [Genymobile/scrcpy#121]
```
adb devices
List of devices attached
192.168.100.5:5555      device
```

```
 scrcpy                      
/usr/share/scrcpy/scrcpy-server.jar: 1 file pushed. 0.3 MB/s (19334 bytes in 0.070s)
error: more than one device/emulator
ERROR: "adb reverse" returned with value 1
WARN: 'adb reverse' failed, fallback to 'adb forward'
```

Version:
```
 scrcpy -v
scrcpy v1.1

dependencies:
 - SDL 2.0.8
 - libavcodec 57.107.100
 - libavformat 57.83.100
 - libavutil 55.78.100
```

**Comment by rom1v** [comment]
Thank you for your report.

>     error: more than one device/emulator
>     ERROR: "adb reverse" returned with value 1

This is "expected", that's why a _fallback_ to `adb forward` has been implemented. See https://github.com/Genymobile/scrcpy/issues/5.

>     WARN: 'adb reverse' failed, fallback to 'adb forward'

If after that _scrcpy_ stops without displaying the device, this is probably that the number of connection attempts for `adb forward` is too low (see [discussion](https://github.com/Genymobile/scrcpy/issues/5#issuecomment-373696794)). It has been [fixed](https://github.com/Genymobile/scrcpy/commit/c65cb36d3b32d9c4f42d7886a58c9c76a78732f5) on `master` (not released yet).

**Comment by rom1v** [comment]
Could you try with v1.2, please?

**Comment by rom1v** [comment]
> but the error (impt?) still shows up.

That's expected (https://github.com/Genymobile/scrcpy/issues/5). :+1:

**Comment by pablitok** [comment]
Same error with v1.6 here

```
scrcpy -v
scrcpy 1.6

dependencies:
 - SDL 2.0.8
 - libavcodec 58.18.100
 - libavformat 58.12.100
 - libavutil 56.14.100
```

**Comment by rom1v** [comment]
@pablitok This "error" is expected over TCPIP (and harmless, since there is a fallback). Do you use it over wifi?

**Comment by pablitok** [comment]
Sorry, I misunderstand that the expected error was the one about the fallback, not the one about multiple devices.
Yeah, I use it over wifi
Thanks!

**Comment by rom1v** [comment]
@pablitok So it works? (if it does not, please paste the whole scrcpy output)

**Comment by pablitok** [comment]
yeah, it works,!

**Comment by carstenhag** [comment]
Hey @rom1v, I'm hitting this issue too on 1.10:

```
 chag0709  Carstens-MacBook  ~  $  scrcpy -t
2019-09-13 13:16:43.146 scrcpy[29062:450094] INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: more than one device/emulator
2019-09-13 13:16:43.163 scrcpy[29062:450094] ERROR: "adb push" returned with value 1
```

I've got an emulator running and a device.

**Comment by rom1v** [comment]
> I've got an emulator running and a device.

Then use `scrcpy -s SERIAL`, with the serial as printed by `adb devices`.

**Comment by aminukano585** [comment]
@rom1v I really need your help on this, I've tried all the workarounds but it still fails.

Here is my `scrcpy` version:
```bash
$ scrcpy -v
scrcpy 1.11

dependencies:
 - SDL 2.0.8
 - libavcodec 57.107.100
 - libavformat 57.83.100
 - libavutil 55.78.100
```

Here is my device, you can see it's just one:
```bash
$ adb devices
List of devices attached
192.168.43.1:5555	device
```

But after runniny `scrcpy` command, the error persists
```bash
$ scrcpy
INFO: scrcpy 1.11 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server:...shed. 0.6 MB/s (25454 bytes in 0.038s)
adb: error: more than one device/emulator
ERROR: "adb reverse" returned with value 1
WARN: 'adb reverse' failed, fallback to 'adb forward'
27183
Aborted 
```

**Comment by rom1v** [comment]
> ````
> adb: error: more than one device/emulator
> ERROR: "adb reverse" returned with value 1
> ```

This is an expected error message (see #5), but then it fallbacks to `adb forward`, so this is not the problem.

> ```
> Aborted
> ```

Probably #944. Try `v1.10` or `dev` branch instead.
Could also be #268 (see #956).

**Comment by aminukano585** [comment]
Thanks a lot @rom1v it now works with `v1.10`.. 

But there's one little issue, the device appears upside down :)

**Comment by rom1v** [comment]
@aminukano585 Please open a new issue for that, with more details (device, android version, does it always happen, screenshot...). Thank you.

**Comment by aminukano585** [comment]
Thanks, @rom1v, I just created #972 to this effect.
