### ISSUE TITLE
Infinite loop in Instagram app

### ISSUE THREAD

**Issue by Vxider** [Genymobile/scrcpy#1213]
Mouse scroll in instagram app will cause an infinite loop, scroll works fine when I directly swap on phone's screen. 

By the way, can I have a shortcut to simulate a scroll gesture like page up/down in computer?

![ins](https://user-images.githubusercontent.com/6134315/76685726-ed20fb80-6650-11ea-8ee1-0dfca9eb9e79.gif)

**Comment by rom1v** [comment]
Mouse scrolling is different from a "swipe" (click, move, release): it generates an [`ACTION_SCROLL`](https://developer.android.com/reference/android/view/MotionEvent#ACTION_SCROLL).

Do you have the problem only on the instagram app, or is it broken everywhere for you (in Android settings, etc.)?

> By the way, can I have a shortcut to simulate a scroll gesture like page up/down in computer?

Simulate a scroll gesture, no. You can "reproduce" the scroll gesture. Or press page up/down (for example it works in Firefox) :)

**Comment by Vxider** [comment]
Thanks, I have the problem only in instagram app, works fine in all other apps.

**Comment by rom1v** [comment]
OK, then probably instagram does not handle scroll events correctly :confused:

**Comment by Vxider** [comment]
@rom1v thanks for your help, solved by using `adb shell input swipe`
