### ISSUE TITLE
Is it commercially available?

### ISSUE THREAD

**Issue by innotestdm** [Genymobile/scrcpy#1218]
I want to modify this source code and apply it to my program.
I intend to use it commercially.
Can I use it?

**Comment by rom1v** [comment]
Yes, _scrcpy_ is released under Apache License 2.0:
 - https://github.com/Genymobile/scrcpy/blob/master/LICENSE
 - https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)

Of course, if your modifications are not specific to your use case and can benefit the project, contributions are welcome :wink:
