### ISSUE TITLE
Copy&Paste does not work anymore

### ISSUE THREAD

**Issue by Chavell3** [Genymobile/scrcpy#1219]
I used the new version of scrcpy(1.12.1) with Windows 10 and unfortunatly detected that the copy&paste feature is not working anymore.
I than restored the 1.10 version of scrcpy and copy&paste is working fine again.

Seems to something with the new release.

BR
Chavell3

**Comment by rom1v** [comment]
> that the copy&paste feature is not working anymore

Which one? [copy-paste](https://github.com/Genymobile/scrcpy#copy-paste)
 - from device to computer with `Ctrl`+`c`?
 - from computer to device with `Ctrl`+`Shift`+`v`?
 - from computer to device with `Ctrl`+`v`?

> I used the new version of scrcpy(1.12.1) with Windows 10
> I than restored the 1.10 version of scrcpy

Could you test with v1.11, please?

**Comment by Chavell3** [comment]
I mean from computer to device.
BUT I used CTRL + C on the computer and hold "button" or cursor  and "insert" to import the content. That actually works e.g. for Whatsapp but not for the phone app.
Now I tried it with CTRL + V and it works how it should work(pasting the right content...
sorry for the false message

**Comment by xcodebin** [comment]
the same question

**Comment by xcodebin** [comment]
the copy/paste can work in v1.1

**Comment by xcodebin** [comment]
the copy/paste can work in v1.11

**Comment by rom1v** [comment]
So in v1.11 it works with all apps, but in v1.12 it does not work with the phone app? :confused:

**Comment by Chavell3** [comment]
no no, it works fine, if I use it correctly, also with v1.12.1
I just tried to us the "insert" function within Android... but that does not work.
CTRL + C &  CTRL + V  works fine.
sorry the wrong usage

**Comment by rom1v** [comment]
@Chavell3 It should also work with `Ctrl`+`c` on the computer, `Ctrl`+`Shift`+`v` in the scrcpy window (it should print `Device clipboard set`), then long-click in a text field on the device, "paste".

I just tested on Windows 10 with v1.12.1, it works for me.
