### ISSUE TITLE
Is there any way to connect Android for different LANs in WiFi

### ISSUE THREAD

**Issue by fangyuanrui** [Genymobile/scrcpy#1228]
Is there any way to connect Android for different LANs in WiFi

**Comment by Lucaacer** [comment]
If you are asking if there is a way of connecting your pc and your phone via scrcpy while they are connected to different wifi networks, the answer is yes. You just have to connect both devices to the same virtual private network, I use zerotier, for instance.

**Comment by fangyuanrui** [comment]
> If you are asking if there is a way of connecting your pc and your phone via scrcpy while they are connected to different wifi networks, the answer is yes. You just have to connect both devices to the same virtual private network, I use zerotier, for instance.

Thanks，that's what I need

**Comment by alan0048** [comment]
How did you two pull it off? I'm connected through ZeroTier on both devices at different networks. But when I run the adb commands it just says device are offline?
