### ISSUE TITLE
Remember Window Position (per device serial number)

### ISSUE THREAD

**Issue by Grisgram** [Genymobile/scrcpy#1229]
Would be great if there were a keyboard shortcut to remember the current position of the window for a currently mirrored device (per serial#).
I am constantly mirroring 2 or 3 devices during development and I need to re-arrange them every time I start the mirroring.

**Comment by dedosmedia** [comment]
You can launch scrcpy from the command line with different window position values:
scrcpy -s AAAA --window-x 100 --window-y 100
scrcpy -s BBBB --window-x 900 --window-y 100
scrcpy -s CCCC --window-x 100 --window-y 700

Does it not work for you?

**Comment by Grisgram** [comment]
oh. wow, sorry I didn't recognize those options - thanks!
