### ISSUE TITLE
Windows: adb over tcp/ip dose not work, command prompt dosen't show log

### ISSUE THREAD

**Issue by Parthib24** [Genymobile/scrcpy#123]
it dosen't work with ADB over wifi in windows. Its working on linux but its not working on windows.
i get this output when i execute scrcpy.exe from Mingw with adb over wifi.
> ![screenshot 309](https://user-images.githubusercontent.com/22051980/38819264-bdbca39a-41bc-11e8-9861-a5be8d69ed53.png)

> $ ./scrcpy
ERROR: "adb reverse" returned with value 1
WARN: 'adb reverse' failed, fallback to 'adb forward'

And when i execute scrcpy.exe from command prompt or powershell it dosen't show any output in the terminal(scrcpy works though) even when i add --help flag. but it shows output when i execute it from Mingw.

> Command prompt
![screenshot 314](https://user-images.githubusercontent.com/22051980/38819613-a9959c90-41bd-11e8-8f9e-10018bfa3d47.png)

> Mingw
![screenshot 315](https://user-images.githubusercontent.com/22051980/38819958-940367bc-41be-11e8-89d2-aadbc388e0b5.png)

scrcpy version : 
<pre>
$ ./scrcpy --version
scrcpy v1.1

dependencies:
 - SDL 2.0.7
 - libavcodec 57.107.100
 - libavformat 57.83.100
 - libavutil 55.78.100`
</pre>

OS : Windows 10 - 1703

**Comment by rom1v** [comment]
Thank you for your report.

The missing output on Windows is a [known problem](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#on-windows-i-have-no-output-in-the-console) (but unknown solution).

The failure over `adb connect` is probably due to a small number of attempts. Cf https://github.com/Genymobile/scrcpy/issues/121#issuecomment-381328203.

**Comment by Parthib24** [comment]
@rom1v Okay.
But can you make the app to show logs on a new window? just a for a temporary solution?

**Comment by rom1v** [comment]
> But can you make the app to show logs on a new window?

SDL does not provide widgets (e.g. a TextBox), so it would require too much work for this. The current [workaround](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#on-windows-i-have-no-output-in-the-console) consists in redirecting the output and error streams to files, and read the files.

**Comment by Parthib24** [comment]
Oh ok.

**Comment by rom1v** [comment]
Should be fixed by v1.2. Please reopen otherwise.
