### ISSUE TITLE
Enabling or disabling tethering disconnects the device

### ISSUE THREAD

**Issue by arthursantana** [Genymobile/scrcpy#1234]
Tested both on Windows 10 and Manjaro Linux.

My guess is that Android kills the connection to change USB mode, maybe the server could have some kind of automatic retry.

**Comment by rom1v** [comment]
If `adb` is disconnected, yes, scrcpy is stopped.

You can run it via [AutoAdb](https://github.com/rom1v/autoadb) if you want to start scrcpy when a new device is connected.

**Comment by arthursantana** [comment]
Thank you for your answer. I guess this is more of an Android bug, then. Closing the issue.
