### ISSUE TITLE
Android 8.0 (Oreo) mouse cursor control is not working

### ISSUE THREAD

**Issue by wfecus** [Genymobile/scrcpy#124]
Hi,

I've tried using scrcpy from windows on Android 8.0 (Oreo) LG-G7, but the mouse cursor and clicking is not working.
Only the following keys were working, and the device was lagging so much:
ctrl+b (BACK)
ctrl+h (HOEM)
ctr+m (APP_SWITCH)

Is this issue known and there is a fix for it already?
If not, is there a plan for this bug?

Thanks,
wfecus

**Comment by rom1v** [comment]
Do you use v1.1 or v1.0? This [issue] with LG devices has been fixed in v1.1.

**Comment by wfecus** [comment]
Thanks Romain!
I was using v1.0.
