### ISSUE TITLE
Scrcpy not working after tablet shutdown

### ISSUE THREAD

**Issue by jtrogdon-pre** [Genymobile/scrcpy#1240]
I have a Samsung S6 tablet and I have been able to get scrcpy to work over wifi after plugging it into my notebook.  The problem I need to see if it can be solved is after the tablet is shutdown or restarted, I have to reconnect the tablet to my PC and run the commands again.  Is there a way to store something on the tablet so it will run on startup or maybe a server apk for the android tablet? I have given the tablet a static IP on my wifi.   

This is a very cool program and I hope to use it by allowing somebody on a PC to use the tablet to take a picture using the tablet's camera.  Thanks!

**Comment by rom1v** [comment]
Without root, a device does not listen on a TCP port after a reboot.

**Comment by jtrogdon-pre** [comment]
So I'm assuming there's not a way to send the listen command over wifi to the tablet if you know the IP address?

**Comment by rom1v** [comment]
Without root, no :(
