### ISSUE TITLE
--window-x & --window-y ranges

### ISSUE THREAD

**Issue by GaPhi** [Genymobile/scrcpy#1242]
When using multiple PC displays, coordinates of each can have a huge range of values.
(0,0) coordinates determines the (top,left) corner of the primary display, all other displays are relative to this point (with positive or negative values)

Today, scrcpy 1.12.1 only considers positive values and reject negative ones.

Negative values shall be accepted too.

**Comment by rom1v** [comment]
On my computer, if I pass negative values to SDL, it does not work (it behaves as if I passed 0). That's why I did not authorize negative values, it's not supported by the underlying framework.

https://github.com/Genymobile/scrcpy/issues/1183#issuecomment-592182530

However, this limitation maybe only apply to some window managers. Could you try passing a negative value here:

https://github.com/Genymobile/scrcpy/blob/7bb91638ad80ba20700529cf336ea533d8f058e7/app/src/screen.c#L189-L193

**Comment by GaPhi** [comment]
Using the following code, it gives the expected result on Windows 10 :

    int x = window_x != -1 ? window_x : (int) SDL_WINDOWPOS_UNDEFINED;
    int y = window_y != -1 ? window_y : (int) SDL_WINDOWPOS_UNDEFINED;
x = 4370;
y = -350;
    screen->window = SDL_CreateWindow(window_title, x, y,
                                      window_size.width, window_size.height,
                                      window_flags);


I try to go upward to the command options line now...

Le jeu. 26 mars 2020 à 10:50, Romain Vimont <notifications@github.com> a
écrit :

**Comment by GaPhi** [comment]
I suggest this fix/patch in cli.c that works perfectly for me, *but the
"-1" special value should be changed probably as it becomes a valid value
too* :

static bool
> parse_window_position(const char *s, int16_t *position) {
>     long value;
>     bool ok = parse_integer_arg(s, &value, false, *INT_MIN, INT_MAX*,
>                                 "window position");
>     if (!ok) {
>         return false;
>     }
>     *position = (int16_t) value;
>     return true;
> }

**Comment by rom1v** [comment]
> Using the following code, it gives the expected result on Windows 10

Oh, that was a limitation of my window manager then. Cool :+1:

In that case, I agree that `window-x` and `window-y` should accept negative values.

**Comment by rom1v** [comment]
> *but the "-1" special value should be changed probably as it becomes a valid value too*

Yes, when I initially implemented it with negative values, I used -32768 as the special value instead :)

**Comment by GaPhi** [comment]
Ok, -32768 is an acceptable value (even if INT_MIN has probably 32 bits and
is then much lower)

Can you please fix the code and regenerate a new release ?
I did not succeed in generating a release acceptable for Windows deployment
with :

> rm -rf x && meson x --buildtype release --strip -Db_lto=true
> -Dprebuilt_server=scrcpy-server -Dportable=true -Dwindows_noconsole=true &&
> ninja -Cx
>
It works under MinGW64 (this is how I did my tests) but it is not when
overwriting scrcpy-noconsole.exe of the 1.12.1 release and launching with
Windows Explorer...

(Yes, it is the first time I heard about meson and ninja)

Thanks in advance !

Le jeu. 26 mars 2020 à 12:29, Romain Vimont <notifications@github.com> a
écrit :

**Comment by rom1v** [comment]
Could you test the branch `negativepos`, please?

https://github.com/Genymobile/scrcpy/commit/cd4e74da4b4a5cc9926e76c3841238250b39de9c

If it works for you, I'll merge into `dev` (and it will be in the next release).

**Comment by rom1v** [comment]
Fixed by dc7c677728cdeb7471745a2aff9f63ebe8d14f53.

**Comment by rom1v** [comment]
Released in v1.13.
