### ISSUE TITLE
Error in to connect phone in ubuntu 

### ISSUE THREAD

**Issue by MarcusXavierr** [Genymobile/scrcpy#1250]
INFO: scrcpy 1.12 <https://github.com/Genymobile/scrcpy>
adb server version (41) doesn't match this client (39); killing...
ADB server didn't ACK
Full server startup log: /tmp/adb.1001.log
Server had pid: 12773
--- adb starting (pid 12773) ---
adb I 03-28 20:50:01 12773 12773 main.cpp:57] Android Debug Bridge version 1.0.39
adb I 03-28 20:50:01 12773 12773 main.cpp:57] Version 1:8.1.0+r23-5~18.04
adb I 03-28 20:50:01 12773 12773 main.cpp:57] Installed as /snap/scrcpy/211/usr/lib/android-sdk/platform-tools/adb
adb I 03-28 20:50:01 12773 12773 main.cpp:57] 
adb I 03-28 20:50:01 12773 12773 adb_auth_host.cpp:416] adb_auth_init...
adb I 03-28 20:50:01 12773 12773 adb_auth_host.cpp:174] read_key_file '/home/marcus/snap/scrcpy/211/.android/adbkey'...
adb I 03-28 20:50:01 12773 12773 adb_auth_host.cpp:391] adb_auth_inotify_init...
adb I 03-28 20:50:01 12773 12773 adb_auth_host.cpp:467] Calling send_auth_response
adb server killed by remote request

* failed to start daemon
adb: error: failed to get feature set: cannot connect to daemon
ERROR: "adb push" returned with value 1

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#conflicts-between-adb-versions

**Comment by rom1v** [comment]
#527
