### ISSUE TITLE
ninja: error: loading 'build.ninja': No such file or directory

### ISSUE THREAD

**Issue by varunchandran333** [Genymobile/scrcpy#126]
ninja: error: loading 'build.ninja': No such file or directory

**Comment by rom1v** [comment]
Not enough information. What system, what did you execute exactly?

**Comment by varunchandran333** [comment]
**Followed these setps mentioned in the wiki** 

[sudo apt install ffmpeg libsdl2-2.0.0](url)

[# client build dependencies
sudo apt install make gcc pkg-config meson \
                 libavcodec-dev libavformat-dev libavutil-dev \
                 libsdl2-dev](url)

[# server build dependencies
sudo apt install openjdk-8-jdk](url)


**Clone the project:**

[](git clone https://github.com/Genymobile/scrcpy)
[cd scrcpy](url)

**Then, build:**

[meson x --buildtype release --strip -Db_lto=true](url)
[cd x](url)
[ninja](url) --> **gives this error**


ninja run

**Comment by rom1v** [comment]
What was the output of:

    meson x --buildtype release --strip -Db_lto=true

What is the content of the `x` directory after this command?

    ls x

**Comment by varunchandran333** [comment]
`ls x` ---> meson-logs  meson-private
`meson x --buildtype release --strip -Db_lto=true` ---->**Meson version is 0.29.0 but project requires >= 0.37.**
its not worked that way so i used 
 `pip3 install meson`

**Comment by rom1v** [comment]
> its not worked that way so i used `pip3 install meson`

Then, it worked?

**Comment by varunchandran333** [comment]
No... now i am facing this issue....

**Comment by rom1v** [comment]
Once you installed a newer `meson` via `pip3`, what was the result of:

    meson x --buildtype release --strip -Db_lto=true

?

**Comment by rom1v** [comment]
The version from `pip3` should not be 0.29.

    sudo apt-get remove meson
    sudo pip3 install meson

**Comment by varunchandran333** [comment]
sudo apt-get remove meson
sudo pip3 install meson

after this
if we do -------->meson x --buildtype release --strip -Db_lto=true 
gives this error
![pip](https://user-images.githubusercontent.com/24404413/38980803-6b8eeb66-43db-11e8-9082-64337833d125.png)
If we do -----> cd x----------> ninja      gives this error
![pip1](https://user-images.githubusercontent.com/24404413/38980989-e29202fc-43db-11e8-8323-abf99037892f.png)

**Comment by rom1v** [comment]
If `meson` fails, this is a problem, do not even try to execute the next commands.

So you installed `meson` via `pip3`, but `meson` does not exist… Did `pip3 install meson` worked as expected?

Does `meson.py` exists instead?

    meson.py x --buildtype release --strip -Db_lto=true

**Comment by varunchandran333** [comment]
Did pip3 install meson worked as expected?  **I dont Know** **I have shown already what i got as result...**

**meson.py: command not found**

Does meson.py exists instead? **NO**

**Comment by rom1v** [comment]
> Did pip3 install meson worked as expected? I dont Know I have shown already what i got as result

I think you did not post the output of:

    sudo pip3 install meson

**Comment by varunchandran333** [comment]
The directory '/home/varun/.cache/pip/http' or its parent directory is not
owned by the current user and the cache has been disabled. Please check the
permissions and owner of that directory. If executing pip with sudo, you
may want sudo's -H flag.
The directory '/home/varun/.cache/pip' or its parent directory is not owned
by the current user and caching wheels has been disabled. check the
permissions and owner of that directory. If executing pip with sudo, you
may want sudo's -H flag.
Requirement already satisfied (use --upgrade to upgrade): meson in
/usr/local/lib/python3.5/dist-packages
You are using pip version 8.1.1, however version 10.0.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


*This is what getting now..*

**Comment by anborc** [comment]
try
$ sudo ninja 
instead of 
$ ninja

**Comment by johnsie** [comment]
Any luck with this procedure. I'm planning to do an Ubuntu build tonight

**Comment by rom1v** [comment]
Do you still have the problem?
