### ISSUE TITLE
text is not rendering propely.

### ISSUE THREAD

**Issue by walkeratmind** [Genymobile/scrcpy#1265]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Elementary OS 5.1 Hera
 - scrcpy version: 1.12.1
 - installation method: manual build
 - device model: Samsung M40
 - Android version: 10

When I run scrcpy normally everythings works fine but text is not rendering properly. Here's the output of the toool.
![scrcpy](https://user-images.githubusercontent.com/27734069/78457310-086bad80-76c9-11ea-99e5-efb6a5e27487.png)

I'm unable to find any options to resize the whole screen or to fix this 🙂️🙂️.

**Comment by rom1v** [comment]
If your computer definition is far smaller than your device definition, then you'll get poor quality.

See #40.
