### ISSUE TITLE
adb devices command : failed to start daemon !!

### ISSUE THREAD

**Issue by ayoub099** [Genymobile/scrcpy#1266]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).
Format them between code blocks (delimited by ```).
Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by ayoub099** [comment]
![Screenshot from 2020-04-05 21-27-05](https://user-images.githubusercontent.com/50072475/78509226-92c51780-7784-11ea-981f-faf2573e505b.png)

**Comment by lancerXXXX** [comment]
I had the same problem , but I have solved it
I am not familiar to adb.exe,
I just wanna give you an idea through my experience,
I found there is another application's adb.exe occupied the port which is 5037 on windows that the adb.exe needs, it's an another application which have familiar features with scrcpy,
so I just uninstalled that application ,this one is better , and then I solved it
