### ISSUE TITLE
 Ctrl + L command for Locking your mouse Request 

### ISSUE THREAD

**Issue by Littlemac123** [Genymobile/scrcpy#1267]
when in landscape mode on phone and full screen mode in app you can have big boarders on the sides for when playing games and its annoying to have to move the mouse left or right fast and then you cant click the screen from it going out of bounce, all so would be nice for it to be in window mode as well so you cant leave the window by mistake.

**Comment by rom1v** [comment]
#269 ?

**Comment by Littlemac123** [comment]
> 
> 
> #269 ?

no thats not it at all, I am asking for your mouse to not escape the app and go out the boundaries of the app when you press Ctrl + L

**Comment by rom1v** [comment]
(The only way for the mouse not to escape the app is to "capture" it, like in #269.)

**Comment by Littlemac123** [comment]
ohh I thought it meant capture mouse as in the recording mode to see the mouse in the recording woops

**Comment by rom1v** [comment]
OK. I agree with the feature, but I'm closing as duplicate.
