### ISSUE TITLE
scrcpy --version might be showing incorrect version

### ISSUE THREAD

**Issue by Bradzer** [Genymobile/scrcpy#1268]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Linux Mint
 - scrcpy version: 1.12
 - installation method: snap
 - device model: Samsung Galaxy A50
 - Android version: 9

**Describe the bug**
It is not a bug but actually a question I would like to ask. 

Is it normal to install scrcpy version 1.12 and then get the version 1.5 after doing ``scrcpy --version`` ?
![aaa](https://user-images.githubusercontent.com/23164913/78513387-260d4580-77a3-11ea-8035-a9e4af58b899.png)

**Comment by rom1v** [comment]
You have 2 versions installed (probably v1.5 built and installed manually and v1.12 via snap), and when you run `scrcpy` it runs v1.5.

```
which scrcpy
```
will tell you where is the executable you run.

**Comment by Bradzer** [comment]
Okay. Now is there a way to get rid of the version 1.5 so I can keep the 1.12 only @rom1v ?

**Comment by rom1v** [comment]
If you built and install v1.5 manually, remove the binary manually (probably in `/usr/bin/scrcpy`, `/usr/share/scrcpy/scrcpy-server.jar`).

**Comment by Bradzer** [comment]
The binary ``scrcpy`` was in ``/usr/local/bin/``. I removed it and now the correct snap version 1.12 took over.
