### ISSUE TITLE
scrcpy Aborted

### ISSUE THREAD

**Issue by surya432** [Genymobile/scrcpy#1269]
![image](https://user-images.githubusercontent.com/30190408/78527614-99e13980-7807-11ea-939b-c801c91994a3.png)
error in android 10.

**Comment by rom1v** [comment]
_Please follow the issue template._

What is the output of `adb logcat` when you execute scrcpy?

Also:
```
adb shell ls -l /data/local/tmp/
```
?

**Comment by surya432** [comment]
![image](https://user-images.githubusercontent.com/30190408/78621205-470d8d80-78ac-11ea-97d4-e68d6d91ea6f.png)
this

**Comment by rom1v** [comment]
```
adb server version (41) doesn't match this client (39); killing...
```

You probably have several adb versions, one killing the other.
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#conflicts-between-adb-versions
