### ISSUE TITLE
Repeating keys

### ISSUE THREAD

**Issue by pete1414** [Genymobile/scrcpy#127]
When holding down an alphabet key, multiple key down / key up events are sent.  (Undesired action..)

When holding down the "Arrow" keys, key up is not sent until the key is released.  (Desired action for all keys.. )

I am using the app "KeyEvent Display" to display key events.

**Comment by pete1414** [comment]
Looks like in  inputmanager.c   'send_keycode', The key up event is sent immediately after the key down event.

**Comment by pete1414** [comment]
I did another test using the android app 'KeyEvent display" with scrcpy and bluetooth keyboard

Scrcopy sends repeated up / down for holding down alpha key.
Bluetooth keyboard sends Single down with incrementing 'repeat' value.  Key up is not sent until the key is released.

**Comment by pete1414** [comment]
Top half is Scrcpy, bottom half is bluetooth keyboard.
![image](https://user-images.githubusercontent.com/6015306/39228649-26cb20ac-482d-11e8-8a4f-3cdc1545081e.png)

**Comment by pete1414** [comment]
(accidentally hit 'closed')

See screenshot below, top half is ScrCpy holding key down.  Bottom half is bluetooth keyboard holding keyd own.

![image](https://user-images.githubusercontent.com/6015306/39228727-8bca4ff0-482d-11e8-908a-f14b519dc55c.png)

**Comment by pete1414** [comment]
Sorry seems to be a duplicate of #87 and #109

**Comment by rom1v** [comment]
Thank you for your report and your investigations.

You're right, this is probably the cause of the problem.

However, this is not easy to solve: up and down are related to key events, but text input must be handled via text input events ([handle text input](https://blog.rom1v.com/2018/03/introducing-scrcpy/#handle-text-input)).

So either we handle text correctly according to the keyboard layout, either we handle up and down key events for characters keys, but then the layout will not match. I don't know how to get both.

**Comment by pete1414** [comment]
Would it be easier to have the user switch between modes? .. ie,  press Ctrl G to enter 'game' mode.   Press again to use text mode.

**Comment by pete1414** [comment]
There is a bug filed in bugzilla with SDL, 2.0.5..  I don't know how to tell if this was fixed in 2.0.8 which is what I have.   Looks like it might be related?

https://bugzilla.libsdl.org/show_bug.cgi?id=3472
