### ISSUE TITLE
scrcpy-server' does not exit or is not a regular file

### ISSUE THREAD

**Issue by ChanggeChaos** [Genymobile/scrcpy#1273]
When I run scrcpy on windows 10, encountered the following problem:

G:\Scrcpy\1.12.1>scrcpy.exe
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
stat: No such file or directory
ERROR: 'G:\Scrcpy\1.12.1\scrcpy-server' does not exist or is not a regular file
Press any key to continue...

How can I solve this? 
Thanks.

G:\Scrcpy\1.12.1>scrcpy.exe -v
scrcpy 1.12.1

dependencies:
 - SDL 2.0.10
 - libavcodec 58.54.100
 - libavformat 58.29.100
 - libavutil 56.31.100

**Comment by rom1v** [comment]
Is `scrcpy-server` present in this directory?

**Comment by cheng-wk** [comment]
> `scrcpy-server`该目录中是否存在？

yes, it exists,and i dont konw how to download the supplement

**Comment by rom1v** [comment]
> G:\Scrcpy\1.12.1

Is it your real path?
Or does your path contain chinese characters?

#1002

**Comment by cheng-wk** [comment]
yeah，i konw how to do，thank you very very very much




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Romain Vimont"<notifications@github.com&gt;; 
发送时间: 2020年4月9日(星期四) 下午2:56
收件人: "Genymobile/scrcpy"<scrcpy@noreply.github.com&gt;; 
抄送: "调儿啷当"<179571261@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Genymobile/scrcpy] scrcpy-server&#39; does not exit or is not a regular file (#1273)





  
G:\Scrcpy\1.12.1
  
Is it your real path?
 Or does your path contain chinese characters?
 
#1002

**Comment by ChanggeChaos** [comment]
> Is `scrcpy-server` present in this directory?

yes, but the original `scrcpy-server` file has no extension. Whether I rename the file as `scrcpy-server.jar` or not, the error exits.

**Comment by ChanggeChaos** [comment]
> > G:\Scrcpy\1.12.1
> 
> Is it your real path?
> Or does your path contain chinese characters?
> 
> #1002

yes, it is the real path. I read the #1002 issue and copy all the file into a new path without any Chinese characters. The error exits still.
Thanks!

**Comment by rom1v** [comment]
Could you please test a build from the `dev` branch (where the utf-8 issue is fixed)? https://github.com/Genymobile/scrcpy/issues/898#issuecomment-610932491

**Comment by ChanggeChaos** [comment]
> Could you please test a build from the `dev` branch (where the utf-8 issue is fixed)? [#898 (comment)](https://github.com/Genymobile/scrcpy/issues/898#issuecomment-610932491)

Thanks! I will do my best to try. I am new to code so I don't know whether I could make it. I will report my progress here the other day. Thank you again.

**Comment by ChanggeChaos** [comment]
> Could you please test a build from the `dev` branch (where the utf-8 issue is fixed)? [#898 (comment)](https://github.com/Genymobile/scrcpy/issues/898#issuecomment-610932491)

That works!
I download these two files and replace the original two files. It works when I double click `scrcpy.exe`.
Thanks!
