### ISSUE TITLE
Move files between PC and device

### ISSUE THREAD

**Issue by RedMoonOTInetwork** [Genymobile/scrcpy#128]
possibility to move files from the mobile phone to PC and From PC to mobile phone

**Comment by alexanderbystander** [comment]
When enabling MTP, scrcpy disconnects and you have to relaunch it. Either fixing that or allowing drag n drop for files would make this tool way more useful.

**Comment by rom1v** [comment]
## from PC to device

 - how would you select the target destination?
 - there is already a [drag&drop feature](https://github.com/Genymobile/scrcpy/pull/133) to install APK: what if you want to copy an apk to the device?

## from device to PC

 - how would you select the file at all?
 - how would you select the target destination?

**Comment by RedMoonOTInetwork** [comment]
I do not know how easy it is. I would simply like to be able to move files bi-directionally

**Comment by rom1v** [comment]
Transferring file from PC to device is implemented by https://github.com/Genymobile/scrcpy/pull/226.

I see no way to do the reverse (how to select the file on the device?), so I think I can close this issue.

**Comment by khallaghi** [comment]
> Transferring file from PC to device is implemented by #226.
> 
> I see no way to do the reverse (how to select the file on the device?), so I think I can close this issue.

to select the file on the device simply you could use an external application to select the files from it and transfer them to computer. 
transferring files from device to host through wireless would be much easier than some other applications which need so many handshakes like Samsung flow or Airdroid (which is I don't trust them at all) so it's completely a cool feature.

**Comment by wickyhu** [comment]
Hi, I really like scrcpy. I find several topics to request file transfer feature from device to PC, and I also like this idea.

How about operate like this: 
1. user press a hot key
2. popup a android file explorer, which looks like windows file explorer, and shows folders and files from device
3. drag & drop files from android file explorer to PC
4. the selected files are pulled from device to PC

Thank you for your great job on scrcpy!

**Comment by Aryan1304** [comment]
> Hi, I really like scrcpy. I find several topics to request file transfer feature from device to PC, and I also like this idea.
> 
> How about operate like this:
> 
> 1. user press a hot key
> 2. popup a android file explorer, which looks like windows file explorer, and shows folders and files from device
> 3. drag & drop files from android file explorer to PC
> 4. the selected files are pulled from device to PC
> 
> Thank you for your great job on scrcpy!

yes

**Comment by AhmedGodaa** [comment]
### From Mobile To PC
To transfer files from mobile to pc you can use  android studio.
-> in the right conrner click tap devices and files explorer in this tab you will find all your device files system

<img width="960" alt="Screenshot 2022-02-10 142955" src="https://user-images.githubusercontent.com/73083104/153409006-323aa574-76b8-418c-b7b1-1f9abc72f316.png">

**Comment by necros2k7** [comment]
Simple GUI file manager will be fine like in Myphoneexplorer or like in https://www.tightvnc.com/download.php

**Comment by SuggonM** [comment]
or just a simple set of CLI commands because they alone could get a lot of things done

**Comment by k-tomaszewski** [comment]
So it looks scrcpy has only support for "drag & drop file to device /sdcard" and no support for copying files from a device to a PC but still this issue was closed (prematurely?) 

Answering earlier questions:
- Where to copy files from a device? I think a good option is to do what "KDE Connect" is doing: copying files into a "Download" folder in user's home directory.
- Where to copy files from a PC? At least on Samsung smartphones there is "Download" folder as well. Files downloaded by a web browser on a mobile are saved in this location.
