### ISSUE TITLE
I can't run scrcpy

### ISSUE THREAD

**Issue by Anry-Hu** [Genymobile/scrcpy#1280]
1.process
(scrawler) root@slave97:/data1/hgq/scrcpy# adb devices
* daemon not running; starting now at tcp:5037
* daemon started successfully
List of devices attached
5TR855HY99999999        device
CI9TWWPJ99999999        device
L7INNR6999999999        device

(scrawler) root@slave97:/data1/hgq/scrcpy# scrcpy -s CI9TWWPJ99999999
INFO: scrcpy 1.12 <https://github.com/Genymobile/scrcpy>
* daemon not running; starting now at tcp:5037
ADB server didn't ACK
Full server startup log: /tmp/adb.0.log
Server had pid: 19486
--- adb starting (pid 19486) ---
adb I 04-10 09:11:43 19486 19486 main.cpp:57] Android Debug Bridge version 1.0.39
adb I 04-10 09:11:43 19486 19486 main.cpp:57] Version 1:8.1.0+r23-5~18.04
adb I 04-10 09:11:43 19486 19486 main.cpp:57] Installed as /snap/scrcpy/211/usr/lib/android-sdk/platform-tools/adb
adb I 04-10 09:11:43 19486 19486 main.cpp:57]
error: could not install *smartsocket* listener: Permission denied

* failed to start daemon
adb: error: failed to get feature set: cannot connect to daemon
ERROR: "adb push" returned with value 1

2.png
![image](https://user-images.githubusercontent.com/28347656/78953632-217ebf00-7b0c-11ea-8a1d-1e0e2b43a6cf.png)

**Comment by rom1v** [comment]
It seems something on your computer is killing your adb daemon.

If you execute `adb devices`, wait few seconds, and execute `adb devices` again, do you see `daemon not running; starting now at tcp:5037`?

**Comment by Anry-Hu** [comment]
> It seems something on your computer is killing your adb daemon.
> 
> If you execute `adb devices`, wait few seconds, and execute `adb devices` again, do you see `daemon not running; starting now at tcp:5037`?

Thanks for your reply.
I followed your instructions and I didn't see "daemon not running; starting now at tcp:5037". I think it's the environmental variables that make the mistake but I don't know how to solve.

Here is the png.
![image](https://user-images.githubusercontent.com/28347656/78976644-2dd53d00-7b49-11ea-9bcf-ae013cdfb6fc.png)

**Comment by Anry-Hu** [comment]
> It seems something on your computer is killing your adb daemon.
> 
> If you execute `adb devices`, wait few seconds, and execute `adb devices` again, do you see `daemon not running; starting now at tcp:5037`?

There was an error when I run scrcpy.adb
![image](https://user-images.githubusercontent.com/28347656/79036593-3c306100-7bfc-11ea-8ccd-51f73d8f168e.png)

**Comment by alengYuan** [comment]
> > It seems something on your computer is killing your adb daemon.
> > If you execute `adb devices`, wait few seconds, and execute `adb devices` again, do you see `daemon not running; starting now at tcp:5037`?
> 
> There was an error when I run scrcpy.adb
> ![image](https://user-images.githubusercontent.com/28347656/79036593-3c306100-7bfc-11ea-8ccd-51f73d8f168e.png)

~~It seems that you need run the command under root permission, or some necessary components in your system have not been set to "executable".~~

Maybe you should find who is using the port 5037 first. Search for "adb smartsocket" and you could learn more about this problem.

**Comment by Anry-Hu** [comment]
> > > It seems something on your computer is killing your adb daemon.
> > > If you execute `adb devices`, wait few seconds, and execute `adb devices` again, do you see `daemon not running; starting now at tcp:5037`?
> > 
> > 
> > There was an error when I run scrcpy.adb
> > ![image](https://user-images.githubusercontent.com/28347656/79036593-3c306100-7bfc-11ea-8ccd-51f73d8f168e.png)
> 
> ~It seems that you need run the command under root permission, or some necessary components in your system have not been set to "executable".~
> 
> Maybe you should find who is using the port 5037 first. Search for "adb smartsocket" and you could learn more about this problem.

Thanks for your reply.
I'm sure that no process is using the port 5037 and the bug also exists, I can't fix it up finally.
I have to build the app manually but it works.
