### ISSUE TITLE
Unusable when screen is removed

### ISSUE THREAD

**Issue by crowbargel** [Genymobile/scrcpy#1285]
**Environment**
 - OS: Windows
 - scrcpy version: 1.12.1
 - installation method: Windows release
 - device model: Google Pixel 3A
 - Android version: 10

The control and frame rate was pretty smooth when the screen was working properly. However, after the screen was completely broken (equivalent to no screen connecting to the phone), the frame rate drops to 1-2 FPS at most with seconds of lags. Lowering the resolution has no improvement.

**Comment by rom1v** [comment]
Hardware issue due to broken screen?

**Comment by crowbargel** [comment]
> Hardware issue due to broken screen?

Actually I had a chance to troubleshoot this possibility. I ordered a replacement screen and when I installed the new screen, everything was smooth again. However the new screen's panel was defective so I had to return it. And now without a screen it became unusable once more.

**Comment by rom1v** [comment]
How does screenrecord behave?

```
adb shell screenrecord /sdcard/file.mp4
adb pull /sdcard/file.mp4
```
?

**Comment by crowbargel** [comment]
> How does screenrecord behave?
> 
> ```
> adb shell screenrecord /sdcard/file.mp4
> adb pull /sdcard/file.mp4
> ```
> 
> ?

The captured screen record is lagging as well. 
Thanks for your help, I think I figured it out. The problem is with the phone itself. I restarted the phone while keeping it connected to the computer. Now the control and frame rate are back to normal. However, the resolution is messed up. Is there anyway to define the resolution output with Scrcpy?
![Annotation 2020-04-12 182645](https://user-images.githubusercontent.com/22359365/79084918-4da46680-7ceb-11ea-9342-0ad8c367f0b8.png)

**Comment by crowbargel** [comment]
> How does screenrecord behave?
> 
> ```
> adb shell screenrecord /sdcard/file.mp4
> adb pull /sdcard/file.mp4
> ```
> 
> ?

After looking up some tutorials, I figured it out. Again, thanks for your help!

**Comment by saikrishna279** [comment]
Pulled a log and found this out:

`05-16 16:15:04.512   687   687 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 1
05-16 16:15:04.515  2667  2667 I Choreographer: Skipped 40 frames!  The application may be doing too much work on its main thread.
05-16 16:15:04.708   663   739 I SDM     : HWCSession::UEventHandler: Uevent FB0 = change@/devices/virtual/graphics/fb0
05-16 16:15:04.713   663   663 W SDM     : HWCSession::ValidateDisplay: panel is in bad state, resetting the panel
05-16 16:15:04.714   663   663 I SDM     : HWCSession::ResetPanel: Powering off primary
05-16 16:15:04.714   663   663 I SDM     : DisplayBase::SetDisplayState: Set state = 0, display 0
05-16 16:15:04.719  2667  2719 I OpenGLRenderer: Davey! duration=838ms; Flags=0, IntendedVsync=1723234961002, Vsync=1723851627644, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=1723867587403, AnimationStart=1723867658132, PerformTraversalsStart=1723868382091, DrawStart=1723868501049, SyncQueued=1723868630580, SyncStart=1724560341587, IssueDrawCommandsStart=1724560639920, SwapBuffers=1724763297180, FrameCompleted=1724765348013, DequeueBufferDuration=198255000, QueueBufferDuration=943000,
05-16 16:15:04.948   663   739 I SDM     : HWCSession::UEventHandler: Uevent FB0 = change@/devices/virtual/graphics/fb0
05-16 16:15:05.364   663   663 I SDM     : HWCSession::ResetPanel: Restoring power mode on primary
05-16 16:15:05.364   663   663 I SDM     : DisplayBase::SetDisplayState: Set state = 1, display 0`

HWC keeps turning the display 0 ON and OFF again and again as the display isn't connected. The happens in the ValidateDisplay() of the HWC [hwc_session.cpp](https://android.googlesource.com/platform/hardware/qcom/display/+/android-7.1.2_r4/msm8996/sdm/libs/hwc2/hwc_session.cpp#570).

And also, the SystemUI giving frequent davey's might be the cause of the lag ( < 1 FPS ).

Disabling the Display 0 as a whole may solve the issue. Need help of someone with this tho.

**Comment by kedestin** [comment]
> 
> ### Pulled a log and found this out:
> 
> ```
> 05-16 16:15:04.512   687   687 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 1
> 05-16 16:15:04.515  2667  2667 I Choreographer: Skipped 40 frames!  The application may be doing too much work on its main thread.
> 05-16 16:15:04.708   663   739 I SDM     : HWCSession::UEventHandler: Uevent FB0 = change@/devices/virtual/graphics/fb0
> 05-16 16:15:04.713   663   663 W SDM     : HWCSession::ValidateDisplay: panel is in bad state, resetting the panel
> 05-16 16:15:04.714   663   663 I SDM     : HWCSession::ResetPanel: Powering off primary
> 05-16 16:15:04.714   663   663 I SDM     : DisplayBase::SetDisplayState: Set state = 0, display 0
> 05-16 16:15:04.719  2667  2719 I OpenGLRenderer: Davey! duration=838ms; Flags=0, IntendedVsync=1723234961002, Vsync=1723851627644, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=1723867587403, AnimationStart=1723867658132, PerformTraversalsStart=1723868382091, DrawStart=1723868501049, SyncQueued=1723868630580, SyncStart=1724560341587, IssueDrawCommandsStart=1724560639920, SwapBuffers=1724763297180, FrameCompleted=1724765348013, DequeueBufferDuration=198255000, QueueBufferDuration=943000,
> 05-16 16:15:04.948   663   739 I SDM     : HWCSession::UEventHandler: Uevent FB0 = change@/devices/virtual/graphics/fb0
> 05-16 16:15:05.364   663   663 I SDM     : HWCSession::ResetPanel: Restoring power mode on primary
> 05-16 16:15:05.364   663   663 I SDM     : DisplayBase::SetDisplayState: Set state = 1, display 0
> ```
> 
> HWC keeps turning the display 0 ON and OFF again and again as the display isn't connected. The happens in the ValidateDisplay() of the HWC [hwc_session.cpp](https://android.googlesource.com/platform/hardware/qcom/display/+/android-7.1.2_r4/msm8996/sdm/libs/hwc2/hwc_session.cpp#570).
> 
> And also, the SystemUI giving frequent davey's might be the cause of the lag ( < 1 FPS ).
> 
> Disabling the Display 0 as a whole may solve the issue. Need help of someone with this tho.


---

Running `scrcpy --turn-screen-off` seems to rectify the  issue, and allows scrcpy to run at a normal framerate.

**Comment by r10r10r** [comment]
i have the same issue , how to fix it without installing new screen?
