### ISSUE TITLE
ERROR: Could not send video packet: -1094995529

### ISSUE THREAD

**Issue by huizichin** [Genymobile/scrcpy#1287]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Lubuntu
 - scrcpy version: 1.12
 - installation method: snap
 - device model:
 - Android version: 5.1.1

```
INFO: scrcpy 1.12 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server:...shed. 3.6 MB/s (26196 bytes in 0.007s)
error: closed
ERROR: "adb reverse" returned with value 1
WARN: 'adb reverse' failed, fallback to 'adb forward'
INFO: Initial texture: 720x1280
ERROR: Could not send video packet: -1094995529
ERROR: Could not process frame
WARN: Device disconnected
```
How do I fix this?

**Comment by rom1v** [comment]
> Android version: 5.1.1

Hmm, are you sure? The error suggests the device runs Android 4.

**Comment by huizichin** [comment]
uhh
yes it is android 5.1.1

**Comment by rom1v** [comment]
Oh, is scrcpy connected to your device over wifi?

If this is the case, could you test over USB please?

**Comment by huizichin** [comment]
no it is over usb

**Comment by huizichin** [comment]
so uhhh
my phone lastest version is only 4.3.3 so i installed a custom rom
could this be the reason?
would it work if i switch to other rom, i meant stock rom only 4.3.3 so it wont work
and would it work if i switched to other custom rom?

**Comment by rom1v** [comment]
What is the result of:

    adb reverse localabstract:scrcpy tcp:27100

?

**Comment by huizichin** [comment]
i flashed another rom and it is working now
it might be because i dint wipe the system before flashing rom
Thanks for your help.

**Comment by nalakawula** [comment]
Sorry for bumping closed issued, because it happen to me.

```
┌─[sumar][x240][~]
└─▪ scrcpy
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 116.5 MB/s (33622 bytes in 0.000s)
[server] INFO: Device: Xiaomi Redmi 5 Plus (Android 10)
INFO: Renderer: opengl
INFO: OpenGL version: 3.0 Mesa 20.2.3
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x2160
ERROR: Could not send video packet: -1094995529
ERROR: Could not process frame
WARN: Device disconnected
```

ADB over USB

**Comment by rom1v** [comment]
>     ERROR: Could not send video packet: -1094995529

```console
$ printf '%x' 1094995529 | xxd -r -p | rev
INDA
```

The error is [`AVERROR_INVALIDDATA`](https://github.com/FFmpeg/FFmpeg/blob/628d02a6116ce5401a626254be7bfc0e68756c1d/libavutil/error.h#L59). It seems that device encoder does not produce valid data :/

What if you just record and play the file with VLC?

```bash
scrcpy --no-display --record file.mkv
```

Also try with another encoder (take this version: https://github.com/Genymobile/scrcpy/pull/1827#issuecomment-725933512).

**Comment by nalakawula** [comment]
> What if you just record and play the file with VLC?

```
┌─[sumar][x240][~]
└─▪ scrcpy --no-display --record file.mkv
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 149.0 MB/s (33622 bytes in 0.000s)
[server] INFO: Device: Xiaomi Redmi 5 Plus (Android 10)
INFO: Recording started to matroska file: file.mkv
ERROR: The first packet is not a config packet
ERROR: Could not record packet
ERROR: Could not send packet to recorder
ERROR: Could not process frame
INFO: Finishing recording...
ERROR: Recording failed to file.mkv
WARN: Device disconnected
```

> Also try with another encoder (take this version: #1827 (comment)).

```
┌─[sumar][x240][~]
└─▪ scrcpy --encoder _
scrcpy: unrecognized option '--encoder'
┌─[sumar][x240][~]
└─▪ scrcpy --version
scrcpy 1.16

dependencies:
 - SDL 2.0.12
 - libavcodec 58.91.100
 - libavformat 58.45.100
 - libavutil 56.51.100
```

**Comment by rom1v** [comment]
> unrecognized option '--encoder'

You need to download the version from the comment.

**Comment by nalakawula** [comment]
```
┌─[sumar][x240][~]
└─▪ SCRCPY_SERVER_PATH=/home/sumar/Downloads/scrcpy-server scrcpy --encoder _
scrcpy: unrecognized option '--encoder'
┌─[sumar][x240][~]
└─▪ 
```

**Comment by francoscarpa** [comment]
I continue to get the `ERROR: Could not send video packet: -1094995529` error. I already read the [crashes](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#crashes) section:

```
ERROR: Could not send video packet: -1094995529
ERROR: Could not send config packet to sink 0
ERROR: Could not process packet
WARN: Device disconnected
```
Installation details shown by `scrcpy -v`:
```
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>

Dependencies (compiled / linked):
 - SDL: 2.0.22 / 2.0.22
 - libavcodec: 59.18.100 / 59.18.100
 - libavformat: 59.16.100 / 59.16.100
 - libavutil: 57.17.100 / 57.17.100
 - libusb: - / 1.0.26
```

**Comment by rom1v** [comment]
The device encoder does not produce a valid stream. Try with another encoder: https://github.com/Genymobile/scrcpy#encoder

**Comment by francoscarpa** [comment]
> The device encoder does not produce a valid stream. Try with another encoder: https://github.com/Genymobile/scrcpy#encoder

Running `scrcpy --encoder _` or `scrcpy --encoder OMX.qcom.video.encoder.avc` outputs this:

```
[server] ERROR: Exception on thread Thread[main,5,main]
com.genymobile.scrcpy.InvalidEncoderException: There is no encoder having name '_"
	at com.genymobile.scrcpy.ScreenEncoder.createCodec(ScreenEncoder.java:222)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:83)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)2022-07-31 23:01:40.300 scrcpy[3161:4473247] WARN: Device disconnected

	at com.genymobile.scrcpy.Server.scrcpy(Server.java:101)
	at com.genymobile.scrcpy.Server.main(Server.java:335)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
[server] ERROR: Try to use one of the available encoders:
[server] ERROR:     scrcpy --encoder 'OMX.amlogic.video.encoder.avc'
```

However, even running the suggested one (`scrcpy --encoder 'OMX.amlogic.video.encoder.avc'`) brings to tha same crashes.

**Comment by Pycoder0901** [comment]
how fix this issue

**Comment by TheKidRock** [comment]
> > The device encoder does not produce a valid stream. Try with another encoder: https://github.com/Genymobile/scrcpy#encoder
> 
> Running `scrcpy --encoder _` or `scrcpy --encoder OMX.qcom.video.encoder.avc` outputs this:
> 
> ```
> [server] ERROR: Exception on thread Thread[main,5,main]
> com.genymobile.scrcpy.InvalidEncoderException: There is no encoder having name '_"
> 	at com.genymobile.scrcpy.ScreenEncoder.createCodec(ScreenEncoder.java:222)
> 	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:83)
> 	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)2022-07-31 23:01:40.300 scrcpy[3161:4473247] WARN: Device disconnected
> 
> 	at com.genymobile.scrcpy.Server.scrcpy(Server.java:101)
> 	at com.genymobile.scrcpy.Server.main(Server.java:335)
> 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
> 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
> [server] ERROR: Try to use one of the available encoders:
> [server] ERROR:     scrcpy --encoder 'OMX.amlogic.video.encoder.avc'
> ```
> 
> However, even running the suggested one (`scrcpy --encoder 'OMX.amlogic.video.encoder.avc'`) brings to same crashes.

For me, running following cmd worked:
scrcpy --encoder 'OMX.MTK.VIDEO.ENCODER.AVC'
scrcpy --encoder 'OMX.google.h264.encoder'
