### ISSUE TITLE
Cannot start scrcpy (exec: no such file or directory)

### ISSUE THREAD

**Issue by wiisportsresort** [Genymobile/scrcpy#1292]
When I try to start scrcpy (using either `scrcpy` or `ADB=$(which adb) scrcpy`, I get this error:
```
$ ADB=$(which adb) scrcpy
INFO: scrcpy 1.12 <https://github.com/Genymobile/scrcpy>
exec: No such file or directory
ERROR: Command not found: [/usr/lib/android-sdk/platform-tools/adb], [push], [/usr/local/share/scrcpy/scrcpy-server], [/data/local/tmp/scrcpy-server.jar]
ERROR: (make 'adb' accessible from your PATH or define its fullpath in the ADB environment variable)
ERROR: Could not execute "adb push"
```
If I run adb (using `adb`, `$ADB`, `/usr/lib/android-sdk/platform-tools/adb`, or `/usr/bin/adb`), it works fine.
```
$ adb --version
Android Debug Bridge version 1.0.41
Version 29.0.6-6198805
Installed as /usr/lib/android-sdk/platform-tools/adb
```
What does scrcpy actually try to do to execute adb? Is there something else I need to change?

OS: Ubuntu 19.10
scrcpy version: 1.12, installed as snap (apt package was not found)

**Comment by rom1v** [comment]
`/usr/lib/android-sdk/platform-tools/adb` is not accessible from the snap container.

You need to use `scrcpy.adb` (or use a non-snap version of scrcpy).

**Comment by wiisportsresort** [comment]
The version of `scrcpy.adb` is 39, but scrcpy wants version 41. How should I upgrade it?
```
INFO: scrcpy 1.12 <https://github.com/Genymobile/scrcpy>
adb server version (41) doesn't match this client (39); killing...
```

**Comment by rom1v** [comment]
`scrcpy` does not expect a specific version. It's just that you have an `adb` v41 daemon started (and maybe restarted again and again by some software if it keeps happening).

I don't know how to update `adb` from snap. Use a non-snap version if you need to.

**Comment by rom1v** [comment]
cc @sisco311

**Comment by wiisportsresort** [comment]
I'd use the apt package if I could, but it doesn't exist for me. Maybe because I'm on Ubuntu 19.10?
```
$ sudo apt install scrcpy                   
Reading package lists... Done
Building dependency tree       
Reading state information... Done

No apt package "scrcpy", but there is a snap with that name.
Try "snap install scrcpy"

E: Unable to locate package scrcpy
```

**Comment by rom1v** [comment]
Yes, unfortunately, that means you need to [BUILD](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md) it.

**Comment by wiisportsresort** [comment]
Cool, I built it and it works now.
