### ISSUE TITLE
how to check scrcpy-server active 

### ISSUE THREAD

**Issue by dilbert168** [Genymobile/scrcpy#1295]
- [x ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows]
 - scrcpy version: [1.12.1]
 - installation method: [Windows release]
 - device model:custom build project
 - Android version: [9]

**Describe the Question**
I got the scrcpy loaded and working nicely.
Would like to know any method on 
1. Android side (from App level) to check whether scrcpy-server is running by checking the process?
2. Window side using ADB command to check scrcpy-server is running ?

Thank you.

**Comment by rom1v** [comment]
See #575.

For now there is no real solution.

From `adb` you can `adb shell ps app_process` (if `app_process` is listed, it's probably _scrcpy_).
