### ISSUE TITLE
mouse input not detected on MIUI ROM (Mi Mix 2)

### ISSUE THREAD

**Issue by nabeelmoeen** [Genymobile/scrcpy#130]
hi, 
I am using a Mi Mix 2 device with official global MIUI 9.5.6 Oreo ROM. 
running scrcpy.exe does display the device screen on the laptop/PC but neither the right nor left mouse click are working.

I have tried the following but the issue persists. not sure if this is because of MIUI:
1. downloaded source (master and dev branch) to build and confirm the fix for LG devices is in place (where left click wasn't working but right click was on the devices).
2. built the server without hidpi support

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-clicks-do-not-work

**Comment by nabeelmoeen** [comment]
Awesome. thanks a lot!!!
With all the searches I did, I would expect this should have popped up on google ... but thank you for pointing it out
