### ISSUE TITLE
No APP icon

### ISSUE THREAD

**Issue by FYUN-42** [Genymobile/scrcpy#1301]
Environment
 - OS: Windows
 - scrcpy version: 1.12.1
 - installation method: Windows release
 - device model: Redmi K20 PRO (Mi 9T PRO)
 - Android version: 10 (MIUI11)

**Describe the bug**
If I type ctrl+o, My app icon will disappear when my phone screen is turned off

![无标题](https://user-images.githubusercontent.com/59155602/79691110-56b7a980-8290-11ea-903e-f4738fde3a54.png)

**Comment by FYUN-42** [comment]
Environment

OS: Windows, Ubuntu 1804
scrcpy version: 1.12.1
installation method: Windows release, snap
device model: Redmi K20 PRO (Mi 9T PRO)
Android version: 10 (MIUI11)

**Comment by FYUN-42** [comment]
This problem also appears in my ubuntu system.

**Comment by rom1v** [comment]
Which app icon? You mean scrcpy closes itself?

Please do the following steps:
 - clean your logcat: `adb logcat -c`
 - run scrcpy from the console
 - press ctrl+o to produce your problem
 - run `adb logcat -d > logcat.txt`

Then:
 - paste the output from the console here (between ```)
 - post your `logcat.txt`

**Comment by rom1v** [comment]
Ah no ok it makes your launcher crash. Post your `logcat.txt` to confirm.

**Comment by FYUN-42** [comment]
I'm sorry I didn't make my problem clear. There are bug videos and logcat.txt in this zip.
[Bug_record.zip](https://github.com/Genymobile/scrcpy/files/4499483/Bug_record.zip)

**Comment by rom1v** [comment]
If you switch the screen on again (Power off then power on), are the icons back?

Might be the same problem as #836 for chrome (the app does not draw if it thinks there is no display).

**Comment by FYUN-42** [comment]
Yes, If the screen is on, I can see the icons.
So, I think scrcpy cannot solved this issue.
