### ISSUE TITLE
Disable shortcuts, especially mouse's shortcuts

### ISSUE THREAD

**Issue by phootip** [Genymobile/scrcpy#1302]
- [x] I have checked that a similar feature request does not already exist.

**Is your feature request related to a problem? Please describe.**
I can't play a game ([mindustry](https://mindustrygame.github.io/)) without remapping button

**Describe the solution you'd like**
Disable shortcuts, especially for mouse, so that right-clicking does correct things in-game.

**Describe alternatives you've considered**
The game supports remapping buttons, but I feel like disable shortcuts should be useful in other games, too.

**Additional context**
Here is the [mindustry github](https://github.com/Anuken/Mindustry)

Also, I think this feature might not be that hard, I've never used `adb`, but if you're too busy could you guide me? I might be able to have a look, learn them, and create a PR for this. Thank you!

**Comment by rom1v** [comment]
Another reason to forward right-click: https://github.com/Genymobile/scrcpy/issues/898#issuecomment-610998474

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/issues/712#issuecomment-692936122

**Comment by rom1v** [comment]
I suggest adding the following options:

 - `--right-click=XXX`
 - `--middle-click=XXX`

with `XXX` either:
 - `inject` (inject right-click)
 - `home`
 - `back`
 - `switch_app`

I'm a bit annoyed because by default, right-click injects <kbd>BACK</kbd> if screen is on, but <kbd>POWER</kbd> if screen is off. I don't know how to expose this feature with the configuration.

Should I make it possible for any configuration? Even for middle key? With an explicit configuration (`back_or_power`, `back+`, `back?`, `home_or_power`…)? Any idea?

**Comment by xcjs** [comment]
@rom1v I don't like the idea of home being an option as Android maps the Home button already. Ideally I'd like scrcpy to simply passthrough keyboard and mouse events as if they were bluetooth devices connected directly to the device.

You might be able to do additional remapping through Android itself and applications like Physical Keyboard Helper.

**Comment by rom1v** [comment]
> I don't like the idea of Home being an option as Android maps the Home button already.

But it's convenient to have it accessible from the mouse (less than right-click for BACK, but still). Currently, right-click is mapped to BACK and middle-click to HOME.

> Ideally I'd like scrcpy to simply passthrough keyboard and mouse events as if they were bluetooth devices connected directly to the device.

The goal of the option I'd like to add is to forward right and middle clicks to the device. (Unfortunately, event injection does not behave as a bluetooth device though, it's not at the same level.)

> Regarding your word choice, I'd prefer "passthrough" to "inject".

:+1:

If right-click is forwarded, do you think it should still power on the device if it is off?

**Comment by rom1v** [comment]
Or maybe we could keep things simple: `--no-mouse-shortcuts` (to forward all mouse buttons to the device)

**Comment by rom1v** [comment]
I just implemented an option on a separate branch ([`forward_all_clicks`](https://github.com/Genymobile/scrcpy/commit/forward_all_clicks)):

```
scrcpy --forward-all-clicks
```

Could you please test it?

For windows users, take both `scrcpy.exe` and `scrcpy-server`, and replace them in your scrcpy v1.16 release.

For other platforms, take `scrcpy-server` and [build](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#prebuilt-server) only the client.

 - [`scrcpy.exe`](https://tmp.rom1v.com/scrcpy/1302/1/scrcpy.exe)
  _SHA256: 50d2cc8ef996dcc6cc5447b1cecabaf4d66587ee6217a95198a19a2b439118c6_
 - [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/1302/1/scrcpy-server)
  _SHA256: 15c69bd3b0c16ddb525d6f9b4217a40ec5b9f27fdfd4ae1e32a4c1584d730909_

**Comment by rom1v** [comment]
Merged into `dev`: adc547fa6e8e6167cd9633a97d98de6665b8c23a.

**Comment by iamnotoo** [comment]
> I've just implemented an option on a separate branch ([`forward_all_clicks`](https://github.com/Genymobile/scrcpy/commit/forward_all_clicks)):
> 
> ```
> scrcpy --forward-all-clicks
> ```
> 
> Could you please test it?
> 
> For windows users, take both `scrcpy.exe` and `scrcpy-server`, and replace them in your scrcpy v1.16 release.
> 
> For other platforms, take `scrcpy-server` and [build](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#prebuilt-server) only the client.
> 
> * [`scrcpy.exe`](https://tmp.rom1v.com/scrcpy/1302/1/scrcpy.exe)
>   _SHA256: 50d2cc8ef996dcc6cc5447b1cecabaf4d66587ee6217a95198a19a2b439118c6_
> * [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/1302/1/scrcpy-server)
>   _SHA256: 15c69bd3b0c16ddb525d6f9b4217a40ec5b9f27fdfd4ae1e32a4c1584d730909_

it don't work on --otg srry about my english i'm brasilian and still learning

**Comment by rom1v** [comment]
On OTG mode, all clicks are always forwarded.
