### ISSUE TITLE
Double Input - Text when typing using desktop keyboard

### ISSUE THREAD

**Issue by divmonkey** [Genymobile/scrcpy#1305]
**Environment**
 - OS: Win 10 build 1909
 - scrcpy version: v1.12.1
 - installation method: Manual using ADB(platform-tools_r28.0.0-windows)
 - device model: OPPO F5
 - Android version: 7.1.1

**Describe the bug**
Whenever I type in using my desktop keyboard or even  the windows on-screen keyboard, **text got DOUBLED**.

But the app is running fine and smooth except the doubled input. (English text)

**Comment by rom1v** [comment]
Which keys are doubled? Letters? Non-letters? All?

What if you run `scrcpy --prefer-text`?

**Comment by divmonkey** [comment]
Letters only(en). The numbers are not doubled.

**What if you run scrcpy --prefer-text?**
It says... 
[0x7FFE09218E00] ANOMALY: meaningless REX prefix used

**Comment by rom1v** [comment]
WAT!?

(after some googling: do you use AVG antivirus? https://support.avg.com/answers?id=906b0000000D4GzAAK)

**Comment by divmonkey** [comment]
Yes, I DONT use AVG, I have Avast.

**Comment by Abner77** [comment]
For what I have seen,, it happens also to me, but only with tildes, so á, é,í, ó, ú, for instance create a double input in this way (aá, eé, ií... and so on).

**Comment by rom1v** [comment]
@Abner77 `scrcpy --prefer-text`

**Comment by Abner77** [comment]
> @Abner77 `scrcpy --prefer-text`

It works! thank you very much
