### ISSUE TITLE
Virus detected

### ISSUE THREAD

**Issue by aviel142634** [Genymobile/scrcpy#1309]
**Environment**
 - OS: Windows 10 build 19041.84
 - scrcpy version: 1.12.1
 - installation method: Windows release
 - device model: Xiaomi Mi A2 Lite
 - Android version: 9

**Describe the bug**
When I turn on my PC, scrcpy.exe is missing and Windows notify me that scrcpy.exe is virus. And it same with scrcpy-noconsole.exe

**Comment by rom1v** [comment]
It's a false positive. See #1102. Take the 64 bits version.
