### ISSUE TITLE
Unable to build with Java 14 OpenJDK

### ISSUE THREAD

**Issue by eku** [Genymobile/scrcpy#1311]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Fedora 31
 - scrcpy version: HEAD
 - installation method: manual build
 - device model: any
 - Android version: 7

**Describe the bug**

Because of a [bug in older Gradle versions](https://github.com/gradle/gradle/issues/10248) I'm unable to build ```scrcpy``` with Java 14 OpenJDK. Would you mind to upgrade the build scripts to use latest available Gradle?

```
[15/26] Generating scrcpy-server with a custom command.

FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class org.codehaus.groovy.runtime.InvokerHelper
```

**Comment by rom1v** [comment]
Could you test on branch `dev` instead of `master`, please?

**Comment by eku** [comment]
@rom1v thanks for pointing me to te ```dev``` branch. Is there already a schedule when ```dev``` is merged to ```master```?

**Comment by rom1v** [comment]
When a new version is released :smile: 

I plan to release v1.13 soon, when issues reported for #1307 are fixed.
