### ISSUE TITLE
How do I delete scrcpy

### ISSUE THREAD

**Issue by HowDoIDeleteScrcpy** [Genymobile/scrcpy#1312]
I don't want to sound rude but how do I delete scrcpy. When I try to delete the folder it says that it's in use pls help.

**Comment by rom1v** [comment]
I guess you're on Windows.

Windows filesystem has an annoying limitation: it cannot delete a file if a program using this file is running.

If you closed scrcpy, it's probably the adb daemon. Execute `adb kill-server` from the scrcpy directory, then try again.

**Comment by HowDoIDeleteScrcpy** [comment]
I'm not really into this cmd stuff. Where do I find the scrcpy directory and what's it called.

**Comment by rom1v** [comment]
Open a terminal (`Win`+`r`, then type `cmd.exe` and press enter).

In the terminal, type `cd YOUR_SCRCPY_DIRECTORY`. This is the directory where you extracted the scrcpy zip archive.

Then type `adb kill-server`.

Otherwise, just reboot your computer, `adb` will not be in used and you wlil be able to delete the folder :)

**Comment by HowDoIDeleteScrcpy** [comment]
It says system cannot find the specified parh

**Comment by HowDoIDeleteScrcpy** [comment]
Oh wait I'm a moron nevermind

**Comment by HowDoIDeleteScrcpy** [comment]
I wrote cd YOUR_SCRCPY_DIRECTORY I'm such an idiot lol

**Comment by HowDoIDeleteScrcpy** [comment]
Thank you for your help :)

**Comment by noizrapbit** [comment]
um hi sorry but can u teach me cuz i cant delete it too. I followed all the steps but still cant delete the program

**Comment by rom1v** [comment]
How did you install it?

**Comment by noizrapbit** [comment]
i just download the file n clicked on scrcpy file.I followed a tutorial on youtube but it didnt seem to work for me for some reasons so i decided to delete it

**Comment by rom1v** [comment]
Then just remove the files.

>  followed a tutorial on youtube but it didnt seem to work for me

Sometimes, youtube tutorials about scrcpy installation are not correct.

Just enable USB debugging and double-click on scrcpy.exe.

If there is an error message related to adb, read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).

**Comment by mirreyaz1111** [comment]
**Verified solution**
1. Open Task Manager
2. End the task named "adb"
3. Try deleting the folder now.

**Comment by amanbadola411** [comment]
> **Verified solution**
> 
> 1. Open Task Manager
> 2. End the task named "adb"
> 3. Try deleting the folder now.

this one helped me
