### ISSUE TITLE
Chromebook

### ISSUE THREAD

**Issue by wolfy01** [Genymobile/scrcpy#1314]
```
INFO: scrcpy 1.12 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: no devices/emulators found
ERROR: "adb push" returned with value 1
```
`adb devices` returns this:

```
adb server version (39) doesn't match this client (41); killing...
* daemon started successfully
List of devices attached
VS9888252e1b    device
```

**Comment by wolfy01** [comment]
```
adb shell screenrecord --output-format=h264 - | ffplay -
``` 
Seems to work, so I don't think its an adb issue?

**Comment by wolfy01** [comment]
Looking into this a bit more, It looks like scrcpy is not detecting any devices, although 1 is connected.

**Comment by rom1v** [comment]
> adb server version (39) doesn't match this client (41); killing...

You don't use the same adb in both cases.

How did you install scrcpy?

See #1297 if you use the snap version.

**Comment by wolfy01** [comment]
> 
> How did you install scrcpy?
> 
I used snap. I ended up just building it from the source and that worked flawlessly.
