### ISSUE TITLE
can not install with sudo apt install scrcpy

### ISSUE THREAD

**Issue by ride4sun** [Genymobile/scrcpy#1317]
The documentation says that I can install scrcpy as a package like 
`sudo apt install scrcpy`

```
jay@leny:~$ sudo apt install scrcpy
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package scrcpy
```

System: 
```
Operating System: Kubuntu 19.10
KDE Plasma Version: 5.16.5
KDE Frameworks Version: 5.62.0
Qt Version: 5.12.4
Kernel Version: 5.3.0-46-generic
OS Type: 64-bit
Processors: 4 × Intel® Core™ i7-6500U CPU @ 2.50GHz
Memory: 15.5 GiB of RAM
```

**Comment by rom1v** [comment]
Since Ubuntu 20.04.

**Comment by ride4sun** [comment]
Could u pleas update the documentation? Is there an alternative besides snap?

**Comment by rom1v** [comment]
> Could u please update the documentation?

It's already up to date, it says that you can apt install since Ubuntu 20.04.

> Is there an alternative besides snap?

Update your distrib, or build from sources.

**Comment by KushtrimPacaj** [comment]
I am using Ubuntu 20.04 and can't install. Do I have to add some ppa ?

**Comment by rom1v** [comment]
> I am using Ubuntu 20.04 and can't install.

Why? What's the problem and error message?

**Comment by KushtrimPacaj** [comment]
Cannot find package. That's why I asked if it's in the public package repository, or should I add a ppa first.

```
kushtrim@kushtrim-Legion-Y545:rk3399$ sudo apt install scrcpy
Reading package lists... Done
Building dependency tree       
Reading state information... Done

No apt package "scrcpy", but there is a snap with that name.
Try "snap install scrcpy"

E: Unable to locate package scrcpy
kushtrim@kushtrim-Legion-Y545:rk3399$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
kushtrim@kushtrim-Legion-Y545:rk3399$ 
```

**Comment by rom1v** [comment]
It's in **universe** ([`scrcpy`](https://packages.ubuntu.com/search?keywords=scrcpy)). You need to enable universe packages in Ubuntu.

**Comment by KushtrimPacaj** [comment]
Oh. My bad. Yeah, now it's finding it. Thank you.


Also thanks for the super quick reply 😁

**Comment by azrea** [comment]
@rom1v i'm using zorinos latest version and i get this same error https://github.com/Genymobile/scrcpy/issues/1317#issuecomment-636885284
It use ubuntu bionic universe `deb http://id.archive.ubuntu.com/ubuntu/ bionic universe`

If i add `focal` or `groovy` then get below notification
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
```
i dont want to install snap or build from source then how can i solve this problem?

**Comment by azrea** [comment]
this also not helpful https://github.com/Genymobile/scrcpy/issues/263
```
sudo aptitude install scrcpy
Couldn't find any package whose name or description matched "scrcpy"
Unable to apply some actions, aborting
```

**Comment by azrea** [comment]
It looks like take time for hear from @rom1v 
then i installed `sudo snap install scrcpy` and set `export PATH=$PATH:/snap/bin`
(adb drivers already installed and device authorized. no adb instance running)

sudo scrcpy then below result
```
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 0.6 MB/s (33622 bytes in 0.054s)
No protocol specified
Segmentation fault
```
again tested, below result
```
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
* daemon not running; starting now at tcp:5037
* daemon started successfully
adb: error: failed to get feature set: no devices/emulators found
ERROR: "adb push" returned with value 1
```
that's why i like for common installation instead snap or other :(

**Comment by azrea** [comment]
I also manually tested below,
```
sudo scrcpy.adb devices
[sudo] password for store:  
List of devices attached
CCMBBCB6A1004388	unauthorized

(revoked and authorized again)
$ sudo scrcpy.adb devices
List of devices attached
CCMBBCB6A1004388	device
```
```
sudo scrcpy
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 2.9 MB/s (33622 bytes in 0.011s)
No protocol specified
Segmentation fault
$ [server] INFO: Device: (Android 5.1)
```

I have another computer running ubuntu 20.04.01 and installed scrcpy using `sudo apt install scrcpy` the same device works perfectly in it but i need this get running on zorinos 15.2 device

**Comment by rom1v** [comment]
> Couldn't find any package whose name or description matched "scrcpy"

It's only packaged in Ubuntu since 20.04.
https://repology.org/project/scrcpy/versions

>     adb: error: failed to get feature set: no devices/emulators found

Your device is not detected via `adb`.

>     No protocol specified

Looks like an error from X11.

Anyway, you should never run `scrcpy` as root!

**Comment by azrea** [comment]
@rom1v 

>Looks like an error from X11.

Not sure. i guess due no enough privilege due snap. 

>Anyway, you should never run scrcpy as root!

why? i have a 20.04 device. (installed using apt) then if i didnt run with sudo then return same error
```
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
* daemon not running; starting now at tcp:5037
* daemon started successfully
adb: error: failed to get feature set: no devices/emulators found
ERROR: "adb push" returned with value 1
```

**Comment by rom1v** [comment]
> > Anyway, you should never run scrcpy as root!
> why?

1. you should never give root access to a program which don't need it.
2. it could cause other permissions issues.

> adb: error: failed to get feature set: no devices/emulators found

Your first problem is making your device detected by `adb devices` (independently of scrcpy).

Just to be sure, I guess you correctly enabled USB debugging on the device?

Where does your `adb` come from (the distro or manually installed)?
If your device is not detected, it's probably due to missing [udev rules](https://askubuntu.com/questions/461729/ubuntu-is-not-detecting-my-android-device), but in 20.04 with the `adb` packet it should work out-of-the-box I guess.

**Comment by azrea** [comment]
adb installed using apt however i found this might be related adb because if i run `adb devices` without sudo then even daemon started but doesn't show devices list. (using non root account)

**Comment by 78ksc** [comment]
> It's in **universe** ([`scrcpy`](https://packages.ubuntu.com/search?keywords=scrcpy)). You need to enable universe packages in Ubuntu.

sir i am using kali linux and i am also facing the same issue will you please help me . it is also showing that 

sudo apt install scrcpy                                                                                                                                       100 ⨯
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package scrcpy

sir what to do for kali linux .
it was haning after upgrade the system  ,that was not happning before update , there was another error at that time

please help me

**Comment by robertozh29** [comment]
Had the same issue, i tried lots of commands and updates that i found on the internet none of them works.
Then i figure it out that the repository needed for the package wasn't on the source.list , in my case the repository missing was deb http://http.kali.org/kali kali-last-snapshot main contrib non-free and deb http://http.kali.org/kali kali-rolling main contrib non-free

**Comment by clement66666** [comment]
i dont werk

**Comment by clement66666** [comment]
het werkt niet bij mij

**Comment by kocoman2** [comment]
> It's in **universe** ([`scrcpy`](https://packages.ubuntu.com/search?keywords=scrcpy)). You need to enable universe packages in Ubuntu.

how to add for debian thx

**Comment by paul1149** [comment]
I'm on MX Linux 23 (Debian 12) and also getting missing dependencies.

So there's no straightforward way to make this work?

**Comment by rom1v** [comment]
Don't install the package (it's obsolete anyway), use this method instead: https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md#latest-version

**Comment by paul1149** [comment]
That's the very instruction I was installing from. It led to this:

``ffmpeg is already the newest version (7:6.1-5~mx23+1).
libsdl2-2.0-0 is already the newest version (2.26.5+dfsg-1).
libsdl2-2.0-0 set to manually installed.
wget is already the newest version (1.21.3-1+b2).
wget set to manually installed.
gcc is already the newest version (4:12.2.0-3).
gcc set to manually installed.
git is already the newest version (1:2.39.2-1.1).
pkg-config is already the newest version (1.8.1-1).
pkg-config set to manually installed.
libusb-1.0-0 is already the newest version (2:1.0.26-1).
libusb-1.0-0 set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libswresample-dev : Depends: libswresample4 (= 7:5.1.4-0+deb12u1) but 7:6.1-5~mx23+1 is to be installed
``

**Comment by paul1149** [comment]
Thanks. I ran the update again, looking for the feedback:

```
W: https://repos.azul.com/zulu/deb/dists/stable/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: http://repos.azulsystems.com/debian/dists/stable/Release.gpg: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.

```
I think that's pretty benign.

`/etc/apt/sources.list1 is empty, but over at `/etc/apt/sources.list.d` I have:

```
brave-browser-release.list  mx.list		   zulu-openjdk.list
debian.list		    nextdns.list	   zulu-openJDK.list
debian-stable-updates.list  opera-stable.list
megasync.list		    vivaldi-snapshot.list
```

which I also think is pretty normal.

But I still get the same error, the crux of which seems to be a version problem with libswresample4.

> No, just run on the computer, it takes care of pushing a server on the device to communicate.

Very cool. I hope I can get this working.

**Comment by rom1v** [comment]
That's a lot of external repositories (my `sources.list.d` is empty).

What is the result of `apt show libswresample-dev` and `apt show libswresample4`?

**Comment by paul1149** [comment]
Neat command. Here's what I got, I've removed some fluff:

```
sudo apt show -a libswresample*
Package: libswresample4
Version: 7:6.1-5~mx23+1
Status: install ok installed
Priority: optional
Section: libs
Source: ffmpeg
Maintainer: Steven Pusser <stevep@mxlinux.org>
Original-Maintainer: Debian Multimedia Maintainers <debian-multimedia@lists.debian.org>
Installed-Size: 225 kB
Depends: libavutil58 (>= 7:6.1), libc6 (>= 2.29), libsoxr0 (>= 0.1.0)
Homepage: https://ffmpeg.org/
Download-Size: unknown
APT-Manual-Installed: no
APT-Sources: /var/lib/dpkg/status
This package contains the runtime files.

Package: libswresample4
Version: 7:5.1.4-0+deb12u1
Priority: optional
Section: libs
Source: ffmpeg
Maintainer: Debian Multimedia Maintainers <debian-multimedia@lists.debian.org>
Installed-Size: 229 kB
Depends: libavutil57 (>= 7:5.1), libc6 (>= 2.29), libsoxr0 (>= 0.1.0)
Homepage: https://ffmpeg.org/
Tag: role::shared-lib
Download-Size: 94.5 kB
APT-Sources: http://deb.debian.org/debian bookworm/main amd64 Packages
Description: FFmpeg library for audio resampling, rematrixing etc. - runtime files
 FFmpeg is the leading multimedia framework, able to decode, encode, transcode,
 mux, demux, stream, filter and play pretty much anything that humans and
 machines have created. It supports the most obscure ancient formats up to the
 cutting edge.
 This package contains the runtime files.

Package: libswresample-dev
Version: 7:5.1.4-0+deb12u1
Priority: optional
Section: libdevel
Source: ffmpeg
Maintainer: Debian Multimedia Maintainers <debian-multimedia@lists.debian.org>
Installed-Size: 354 kB
Depends: libavutil-dev (= 7:5.1.4-0+deb12u1), libswresample4 (= 7:5.1.4-0+deb12u1)
Homepage: https://ffmpeg.org/
Tag: devel::library, role::devel-lib
Download-Size: 108 kB
APT-Sources: http://deb.debian.org/debian bookworm/main amd64 Packages
Description: FFmpeg library for audio resampling, rematrixing etc. - development files
 FFmpeg is the leading multimedia framework, able to decode, encode, transcode,
 mux, demux, stream, filter and play pretty much anything that humans and
 machines have created. It supports the most obscure ancient formats up to the
 cutting edge.
 This package contains the development files.
```

Is the problem that some package installed a later version of ibswresample4?

```
sudo apt list -i libswresample*
libswresample4/now 7:6.1-5~mx23+1 amd64 [installed,local]
libswresample4/now 7:6.1-5~mx23+1 i386 [installed,local]

```

**Comment by paul1149** [comment]
I removed libswresample4 5.1.6..., and didn't look closely at what would happen. Now it appears I've done a good job really screwing up my entire system:

```
Removing kde-servicemenu-rootactions (2.7.3+p8+git20160617.0159-1mx23) ...
Removing kde-servicemenu-kim5 (0.9.6-1mx23+1) ...
Removing ffmpeg (7:6.1-5~mx23+1) ...
Removing ffmpegthumbnailer (2.2.2+git20220218+dfsg-1+b1) ...
Removing ffmpegthumbs (4:22.12.3-1) ...
Removing gimp-gmic (2.9.4-4+b4) ...
Removing gimp (2.10.34-1+deb12u2) ...
Removing handbrake (1.7.1+ds1-1~mx23+1) ...
Removing gstreamer1.0-libav:amd64 (1.22.0-2) ...
Removing gstreamer1.0-plugins-bad:amd64 (1.22.0-4+deb12u5) ...
Removing guvcview (2.0.8-2) ...
Removing kde-servicemenu-checkhash-installdebs (1.3mx23) ...
Removing kde-servicemenu-extract-and-compress (1.4.4-3mx23) ...
Removing winehq-staging (8.12-1mx23+1) ...
Removing wine-staging (8.12-1mx23+1) ...
Removing wine-staging-amd64 (8.12-1mx23+1) ...
Removing libasound2-plugins:amd64 (1.2.7.1-1) ...
Removing webcamoid (9.1.1-1~mx23+1) ...
Removing webcamoid-plugins:amd64 (9.1.1-1~mx23+1) ...
Removing obs-studio (30.0.0-0.1~mx23+2) ...
Removing libavdevice60:amd64 (7:6.1-5~mx23+1) ...
Removing obs-plugins (30.0.0-0.1~mx23+2) ...
Removing libobs0:amd64 (30.0.0-0.1~mx23+2) ...
Removing libffmpegthumbnailer4v5:amd64 (2.2.2+git20220218+dfsg-1+b1) ...
Removing libavfilter9:amd64 (7:6.1-5~mx23+1) ...
Removing vlc (3.0.20-0+deb12u1) ...
Removing vlc-plugin-base:amd64 (3.0.20-0+deb12u1) ...
Removing unpaper (7.0.0-0.1) ...
Removing libavformat60:amd64 (7:6.1-5~mx23+1) ...
Removing strawberry (1.0.23-1~mx23+1) ...
Removing libgimp2.0:amd64 (2.10.34-1+deb12u2) ...
Removing libgegl-0.4-0:amd64 (1:0.4.42-2) ...
Removing libgmic1:amd64 (2.9.4-4+b4) ...
Removing libguvcview-2.1-2:amd64 (2.0.8-2) ...
Removing mx-apps-kde (24.05.01) ...
Removing mx-system-kde (20.09.01) ...
Removing libkf5baloowidgets-bin (4:22.12.3-1) ...
Removing libopencv-videoio406:amd64 (4.6.0+dfsg-12) ...
Removing simplescreenrecorder (0.4.4-3) ...
Removing vlc-plugin-video-output:amd64 (3.0.20-0+deb12u1) ...
Removing dolphin (4:22.12.3-1) ...
Removing libavcodec60:amd64 (7:6.1-5~mx23+1) ...
Removing libkf5baloowidgets5:amd64 (4:22.12.3-1) ...
Removing libkf5filemetadata-bin:amd64 (5.103.0-1) ...
Removing smplayer (23.6.0-0.1~mx23+1) ...
Removing mpv (0.36.0-1~mx23+1) ...
Removing libavdevice59:amd64 (7:5.1.4-0+deb12u1) ...
Removing libavfilter8:amd64 (7:5.1.4-0+deb12u1) ...
Removing libavformat59:amd64 (7:5.1.4-0+deb12u1) ...
Removing libchromaprint1:amd64 (1.5.1-2+b1) ...
Removing smplayer-themes (1:20.11.0-1) ...
Removing smplayer-l10n (23.6.0-0.1~mx23+1) ...
Removing libavcodec59:amd64 (7:5.1.4-0+deb12u1) ...
Removing libswresample4:amd64 (7:6.1-5~mx23+1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for libc-bin (2.36-9+deb12u7) ...
Processing triggers for man-db (2.11.2-2) ...
Processing triggers for libvlc-bin:amd64 (3.0.20-0+deb12u1) ...
Processing triggers for mailcap (3.70+nmu1) ...
Processing triggers for desktop-file-utils (0.26-1) ..
```

**Comment by rom1v** [comment]
Since you have the list, just reinstall them :)

Having several repos with conflicting packages versions/dependencies is often a source of problems…

**Comment by paul1149** [comment]
The problem is that trying to reinstall them leads to a snake nest of unmet dependencies. Even apt-get build-dep does the same. I have no idea how to get out of this jam at this point.

**Comment by paul1149** [comment]
Ok, I found a basic building block that would install to work from, and am in the process of restoring hopefully everything.

**Comment by paul1149** [comment]
The beauty of this fiasco is that that purge got rid of the problem! There were four items that wouldn't install, and they all were inappropriate for debian bookworm. So now - after taking a fresh full-system backup image - I'm running scrcpy and so far it's been wonderful! 

Thanks.
