### ISSUE TITLE
IllegalArgumentException.   Which server should I use to bulid dev?

### ISSUE THREAD

**Issue by lishiyuwhu** [Genymobile/scrcpy#1318]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: macos
 - scrcpy version: [e.g. 1.12.1]
 - installation method: manual build
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**
```
%scrcpy
2020-04-25 10:48:59.087 scrcpy[35241:14362391] INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 1.3 MB/s (26202 bytes in 0.020s)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: Expecting 8 parameters
	at com.genymobile.scrcpy.Server.createOptions(Server.java:83)
	at com.genymobile.scrcpy.Server.main(Server.java:162)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:362)
```

https://github.com/Genymobile/scrcpy/issues/630#issuecomment-507134952

Maybe same problem as this. But which server verison fits the dev branch?  
I'm now using `scrcpy-server-v1.12.1`, but get IllegalArgumentException. I tried `scrcpy-server-v1.11` but got `server client not match`.

**Comment by rom1v** [comment]
There is no prebuilt server for the `dev` branch, the server may come incompatible from one commit to the next.

They are only provided for stable releases.

You have to build it yourself.
