### ISSUE TITLE
Only video working in scrcpy

### ISSUE THREAD

**Issue by anandisrocking007** [Genymobile/scrcpy#132]
Hello sir i have used scrcpy on my phone which is Redmi Note 4 but only the video gets streamed i can not control the phone with my mouse i know this is a problem of my phone since it works fine with my other mobile phone and tablets hope you can help me. My device uses android nougat MIUI version.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-clicks-do-not-work
