### ISSUE TITLE
Oppo F7 Ghost Pictures Still on

### ISSUE THREAD

**Issue by vYDv** [Genymobile/scrcpy#1320]
OS: Windows 10 pro
scrcpy version: 1.12.1
installation method: Windows release
device model: Oppo F7
Android version: 9
Describe the bug : when opened pubg mobile , it has ghost pictures/mixed colors active , how to fix it?

**Comment by rom1v** [comment]
Screenshot?

**Comment by vYDv** [comment]
i fix it i just change the max size to 1280 its works fine

**Comment by albaihaqiMF** [comment]
> OS: Windows 10 pro
> scrcpy version: 1.12.1
> installation method: Windows release
> device model: Oppo F7
> Android version: 9
> Describe the bug : when opened pubg mobile , it has ghost pictures/mixed colors active , how to fix it?

You should open the scrcpy folder in cmd,
Than enter syntax "scrcpy -m1920 -b25m" and run this
