### ISSUE TITLE
Support multi-language input method.

### ISSUE THREAD

**Issue by laichiaheng** [Genymobile/scrcpy#1321]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
I can't input anything when my input method on my PC is enabled.

**Describe the solution you'd like**
I can input other languages in scrcpy.

**Describe alternatives you've considered**
I have no idea.

**Additional context**
No.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#special-characters-do-not-work
