### ISSUE TITLE
Malwarebytes Premium says it's malware

### ISSUE THREAD

**Issue by Go5egK** [Genymobile/scrcpy#1322]
I've been using scrcpy on and off for about a month.  Today clicked on my shortcut to launch the app and MWB refused it (never happened before).
Downloaded Windows version again scrcpy-win64-v1.12.1.zip, Unzipped, renamed Folder holding unzipped files as scrscy (to agree with existing Path definition); created shortcut to scrcpy.exe on Desktop.
Then used MWB to scan scrcpy.exe giving result shown on attched snip.  On the Custom Scan results clicking on the Malware name 'Malware...3065435 opened this webpage https://blog.malwarebytes.com/detections/malware-generic/ where, for info, it states 'These generic malware detections are due to our new automated signature system called BytesTotal and DDS engine that are based on Machine Learning technology with 100% autonomous learning which don’t require any human interaction to correctly identify malware.'
![MWB Custom Scan result](https://user-images.githubusercontent.com/35999774/80286620-674ea080-8724-11ea-95b1-c23c120a4530.JPG)

**Comment by Go5egK** [comment]
I've just submitted the problem to MWB support

**Comment by rom1v** [comment]
Thank you for your report.

See #1102. Some other anti-virus only report the 32 bits version.

(I'm closing as a duplicate)

**Comment by Go5egK** [comment]
Hi being new to all this I  by mistake closed this issue (see above)

**Comment by masityvarse** [comment]
> I've just submitted the problem to MWB support

Hi Go5egK, could you provide an update once MWB support responds back to your submission?

I am in the exact same situation as you.

Thanks in advance!

**Comment by Go5egK** [comment]
Hi – Please see your request below – yes will do but do I submit the details under the closed 1322 (which is within 1102) or under 1102

Thanks for the help

 

PS

My support request to MWB included the link to scrcpy with me saying that it was legit.  Subsequent to that on Saturday MWB stopped rejecting scrcpy.  OK on Sunday and ok now again today.

 

Tehn Saturday evening I had request form MWB to send a diagnostic which I’ve done

 

Additionally on the same day as MWB started rejecting scrcpy so did W Defender later that day (I accepted and have not had any frm Defender since)
