### ISSUE TITLE
Simple Full screen mode

### ISSUE THREAD

**Issue by BoQsc** [Genymobile/scrcpy#1329]
- [ ] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
I tried to use Phone as my cloud gaming console.
I downloaded Geforce Now for Android, it is not available on Linux.
I successfully launched and used it with the Android phone.
I connected the Android phone and mirrored the screen.
However couldn't find a way to make scrcpy fullscreen. 
This is neccessary if you are using your phone as a cloud gaming provider.

**Describe the solution you'd like**
I'd like to see a way to just press F11 keyboard button and toggle in scrcpy into fullscreen mode without application borders.

**Describe alternatives you've considered**

Installing **wmctrl** package/application and binding `wmctrl -r :ACTIVE: -b toggle,fullscreen` to a keyboard shortcut, helped me out to make scrcpy in full screen mode.

https://www.reddit.com/r/gnome/comments/3p57op/how_to_fullscreen_an_application_in_gnome/cw385tp/

**Additional context**
![Screenshot from 2020-04-27 09-43-44](https://user-images.githubusercontent.com/21064622/80341722-a2a7b700-886b-11ea-8f30-f2685e1826cb.png)

**Comment by rom1v** [comment]
Ctrl+f

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/README.md#fullscreen

**Comment by generalvimal** [comment]
> Ctrl+f

For people who are wondering why " Ctrl + f " didn't work, its " ALT + f " in the recent versions of SCRCPY.
