### ISSUE TITLE
Video not showing in scrcpy 

### ISSUE THREAD

**Issue by Mrcubix** [Genymobile/scrcpy#1331]
- [Y] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [Y] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Win 8.1 64x
 - scrcpy version: 1.12.1
 - installation method: win release
 - device model: J600FN (galaxy J6 2018)
 - Android version: 8.0

**Describe the bug**
video is displaying on the device using a streaming app, but does not output to pc via scrcpy
normal video work, youtube work. Name of the app: Wakanim

https://youtu.be/GZBUtGHePY0

**Comment by rom1v** [comment]
That's expected if the app uses hardware DRM.
