### ISSUE TITLE
How can I reopen this issue as I couldnt get a response to my points and I dont know why it is closed..

### ISSUE THREAD

**Issue by ceyhun242** [Genymobile/scrcpy#1335]
I'm looking for answers to the points I posted as my last reply in the issue below. I'd appreciate it if you could share your responses either there (if you know how to reopen the issue) or here

Thank you 

https://github.com/Genymobile/scrcpy/issues/1310

**Comment by rom1v** [comment]
Please don't open a new issue for this. You already requested this in the issue itself. I will try to answer when I have some time.

**Comment by ceyhun242** [comment]
I wouldnt like to open a new issue, when I didnt receive a response and saw the thread closed I thought this could be the only way to receive answers.

I would love to have your responses soon

Thank you Romain

Ceyhun

________________________________
