### ISSUE TITLE
Tunnel with adb -H

### ISSUE THREAD

**Issue by hoasis2** [Genymobile/scrcpy#1339]
Is there a workaround to use `adb -H` instead of a SSH Tunnel?

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/issues/144#issuecomment-387765711

**Comment by hoasis2** [comment]
Local adb with `-H` option wouldn't work and a SSH tunnel is the only way to connect to a remote adb server, isn't it?

**Comment by rom1v** [comment]
> Local adb with -H option wouldn't work

I guess it works, just use the environment variable `ADB_SERVER_SOCKET` instead of `adb -H` like in https://github.com/Genymobile/scrcpy/issues/144#issuecomment-387765711

**Comment by hoasis2** [comment]
> > Local adb with -H option wouldn't work
> 
> I guess it works, just use the environment variable `ADB_SERVER_SOCKET` instead of `adb -H` like in [#144 (comment)](https://github.com/Genymobile/scrcpy/issues/144#issuecomment-387765711)

Thank you.
Unfortunately `ADB_SERVER_SOCKET` doesn't seem to work  on a Windows client.

**Comment by rom1v** [comment]
What did you execute exactly?
