### ISSUE TITLE
Trouble compiling on Ubuntu 18.04 Failed :Meson-install 

### ISSUE THREAD

**Issue by Avditvs** [Genymobile/scrcpy#134]
Hi, It worked perfectly on Ubuntu 17.10 but Meson-install failed since I upgraded to Ubuntu 18.04.
I've already tried reinstalling meson but it didn't change anything.

Thank you for your help.

Here are the logs : 

```
[22/31] Generating scrcpy-server with a custom command.
(not invoking gradle, since we are root)
[30/31] Installing files.
Installing app/scrcpy to /usr/local/bin/scrcpy
Stripping target 'app/scrcpy'
Installing server/scrcpy-server.jar to /usr/local/share/scrcpy/scrcpy-server.jar
Traceback (most recent call last):
  File "/usr/bin/meson", line 26, in <module>
    sys.exit(main())
  File "/usr/bin/meson", line 23, in main
    return mesonmain.run(sys.argv[1:], launcher)
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 318, in run
    sys.exit(run_script_command(args[1:]))
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 274, in run_script_command
    return cmdfunc(cmdargs)
  File "/usr/share/meson/mesonbuild/scripts/meson_install.py", line 393, in run
    do_install(datafilename)
  File "/usr/share/meson/mesonbuild/scripts/meson_install.py", line 212, in do_install
    install_targets(d)
  File "/usr/share/meson/mesonbuild/scripts/meson_install.py", line 332, in install_targets
    raise RuntimeError('File {!r} could not be found'.format(fname))
RuntimeError: File 'server/scrcpy-server.jar' could not be found
FAILED: meson-install 
/usr/bin/python3 /usr/bin/meson --internal install /home/louis/scrcpy/x/meson-private/install.dat
ninja: build stopped: subcommand failed.
```

**Comment by rom1v** [comment]
> RuntimeError: File 'server/scrcpy-server.jar' could not be found

Did you correctly execute:

    cd x
    ninja    # <-- without sudo (no root)
    sudo ninja install

The compilation step must not be run as root.

**Comment by Avditvs** [comment]
Sure, the compilation is not run as root.
Now another thing happen
https://pastebin.com/bRtRm5Zz

**Comment by rom1v** [comment]
Could you post the result of:

    meson configure x

please?

**Comment by Avditvs** [comment]
Here is the result of  `meson configure x`  : 
https://pastebin.com/j3i8Xw20

**Comment by rom1v** [comment]
> ```
> Exception in thread "main" javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
> ```

Do you use jdk 9? https://github.com/keeganwitt/docker-gradle/issues/27
Could you try with jdk 8?

**Comment by Avditvs** [comment]
In fact I was running open Java SE 10, it worked with version 8, thank you for your help.

**Comment by rom1v** [comment]
https://github.com/mikaelhg/broken-docker-jdk9-cacerts
