### ISSUE TITLE
scrcpy --turn-screen-off doesnt work

### ISSUE THREAD

**Issue by talk2g** [Genymobile/scrcpy#1340]
C:\Users\Gaurav\Desktop\scrcpy-win64>scrcpy --turn-screen-off
scrcpy: unknown option -- turn-screen-off

I m getting this when i try to use this command. 
am i doing something wrong , since scrcpy --show-touches
works perfectly
EDIT- doesnt work on windows cmd or powershell

However i installed it thru scoop and it works

**Comment by rom1v** [comment]
The reason is just that you used an old version instead of the latest release.

**Comment by talk2g** [comment]
I will check that and report to u tomorrow

**Comment by talk2g** [comment]
yes u were right..thanks for taking the time to help me..Cheers
