### ISSUE TITLE
How can I change default setting to use scrcpy with autoadb

### ISSUE THREAD

**Issue by screwyse** [Genymobile/scrcpy#1351]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Ubuntu20.04
 - scrcpy version: 1.13
 - installation method: snap
 - device model: Samsung SM-A500FU
 - Android version: 5.0.2

**Comment by screwyse** [comment]
Hi, Thank you for your App,

Everything is in the title. I can't find the way to change scrcpy's default setting to use it with autoadb.
Could you help me please ?

**Comment by rom1v** [comment]
In fact, you don't "configure" scrcpy to use autoadb, you execute autoadb so that it executes a new instance of scrcpy when a new device is detected:

```bash
autoadb scrcpy -s '{}'
```

https://github.com/rom1v/autoadb/blob/master/README.md

**Comment by screwyse** [comment]
Thanx for your answer.
Ok, I understand, it seems that it doesn't possible to add an argument to scrcpy with this command. When I change "-s" to another argument i've got an "ERROR: Unexpected additional argument:"
Do you confirm that there is no way to change or add an argument ?

Maybe I have to "configure" autoadb ?

**Comment by rom1v** [comment]
```bash
autoadb scrcpy scrcpy -s `{}` -m 1024
```

**Comment by screwyse** [comment]
Thank you, I'm an idiot....

**Comment by rom1v** [comment]
TIn your defense, the documentation is very light. :wink:
