### ISSUE TITLE
有人告诉我这是什么错误吗？

### ISSUE THREAD

**Issue by StephenWu5** [Genymobile/scrcpy#1354]
![image](https://user-images.githubusercontent.com/32475322/80969417-26553b00-8e4c-11ea-95b7-e08893d9f272.png)

有人告诉我这是什么错误吗？

**Comment by rom1v** [comment]
Hi,

1. please ask in English
2. please follow the issue template
3. please post text directly instead of screenshot of text
4. what to do is explained in the error message: `Try with a lower definition: scrcpy -m 1024` ([FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception)).
