### ISSUE TITLE
adb command not found executing scrcpy.exe

### ISSUE THREAD

**Issue by Trisolarian** [Genymobile/scrcpy#1357]
OS: Windows 10 1909
```
INFO: scrcpy 1.13 <https://github.com/Genymobile/scrcpy>
ERROR: Command not found: [D:\Android\SDK\platform-tools;], [push], ["D:\Downloads\scrcpy-win64-v1.13\scrcpy-server"], ["/data/local/tmp/scrcpy-server.jar"]
ERROR: (make 'adb' accessible from your PATH or define its fullpath in the ADB environment variable)
INFO: You may download and install 'adb' from https://developer.android.com/studio/releases/platform-tools
ERROR: Could not execute "adb push"
Press any key to continue...
```
If i execute `set ADB=path`, it works, but only in that `cmd` session.

**Comment by rom1v** [comment]
Your `ADB` env variable is set (globally) to `D:\Android\SDK\platform-tools;`.
You should set it to `D:\Android\SDK\platform-tools\adb.exe`.

**Comment by Trisolarian** [comment]
> Your `ADB` env variable is set (globally) to `D:\Android\SDK\platform-tools;`.
> You should set it to `D:\Android\SDK\platform-tools\adb.exe`.

I forgot to mention ADB works just fine globally. 
```
D:\Downloads\scrcpy-win64-v1.13>scrcpy.exe
INFO: scrcpy 1.13 <https://github.com/Genymobile/scrcpy>
ERROR: Command not found: [D:\Android\SDK\platform-tools;], [push], ["D:\Downloads\scrcpy-win64-v1.13\scrcpy-server"], ["/data/local/tmp/scrcpy-server.jar"]
ERROR: (make 'adb' accessible from your PATH or define its fullpath in the ADB environment variable)
INFO: You may download and install 'adb' from https://developer.android.com/studio/releases/platform-tools
ERROR: Could not execute "adb push"
Press any key to continue...

D:\Downloads\scrcpy-win64-v1.13>adb version
Android Debug Bridge version 1.0.41
Version 29.0.5-5949299
Installed as D:\Downloads\scrcpy-win64-v1.13\adb.exe

D:\Downloads\scrcpy-win64-v1.13>cd ..

D:\Downloads>adb version
Android Debug Bridge version 1.0.41
Version 29.0.6-6198805
Installed as D:\Android\SDK\platform-tools\adb.exe
```

Anyway, i tried your suggestion, still doesn't work. 
And `ADB` outside scrcpy directory doesn't work anymore.

```
D:\Downloads\scrcpy-win64-v1.13>scrcpy.exe
INFO: scrcpy 1.13 <https://github.com/Genymobile/scrcpy>
ERROR: Command not found: [D:\Android\SDK\platform-tools\adb.exe;], [push], ["D:\Downloads\scrcpy-win64-v1.13\scrcpy-server"], ["/data/local/tmp/scrcpy-server.jar"]
ERROR: (make 'adb' accessible from your PATH or define its fullpath in the ADB environment variable)
INFO: You may download and install 'adb' from https://developer.android.com/studio/releases/platform-tools
ERROR: Could not execute "adb push"
Press any key to continue...
```

**Comment by rom1v** [comment]
> I forgot to mention ADB works just fine globally.

That's expected, if you set a wrong `ADB` env variable, `scrcpy` will use the one provided instead of the one accessible from your path.

> ERROR: Command not found: [D:\Android\SDK\platform-tools\adb.exe;]

You put an additional `;` at the end. Remove it. Or just remove the `ADB` variable if `adb` is accessible from your path.

**Comment by Trisolarian** [comment]
> You put an additional `;` at the end. Remove it. Or just remove the `ADB` variable if `adb` is accessible from your path.

It worked, althrogh i have to add an additional `D:\Android\SDK\platform-tools` path to make `adb` work globally.
Thank you very much !!!
