### ISSUE TITLE
Pass server arguments over socket

### ISSUE THREAD

**Issue by rom1v** [Genymobile/scrcpy#1358]
I tried to improve readability/robustness of configuration passed from the client ot the server: 870ced088ef469829722678f71a05412db34e88d (branch `name_params`)

But on Windows, it failed:

```
ERROR: Command too long (255 chars)
ERROR: Failed to execute: [adb], [shell], [CLASSPATH=/data/local/tmp/scrcpy-server.jar], [app_process], [/], [com.genymobile.scrcpy.Server], [1.13], [max_size=0], [bit_rate=8000000], [max_fps=0], [lock_video_orientation=-1], [tunnel_forward=false], [crop=], [send_frame_meta=true], [control=true], [display_id=0], [show_touches=false], [stay_awake=false] 
```

I think many of these key=value pairs should be passed over the socket (not `tunnel_forward` because the socket creation depends on it).

Or maybe you have a better idea?

**Comment by Biswa96** [comment]
Do you mean using some kind of JSON, XML or INI file?

**Comment by berniegp** [comment]
I got redirected here by this Google search: "scrcpy Command too long (255 chars)"

My problem is that I set this
```
ADB="C:\Program Files\Unity\Hub\Editor\2020.2.1f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platform-tools\adb.exe"
```

and got this:
```
C:\Builds>scrcpy --max-size 720 --bit-rate 1M --max-fps 30 --show-touches --always-on-top
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
C:\ProgramData\chocolatey\lib\scrcpy\tools\scrcpy-server: 1 file pushed. 2.3 MB/s (34930 bytes in 0.014s)
ERROR: Command too long (255 chars)
ERROR: Failed to execute: [C:\Program Files\Unity\Hub\Editor\2020.2.1f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platform-tools\adb.exe], [shell], [CLASSPATH=/data/local/tmp/scrcpy-server.jar], [app_process], [/], [com.genymobile.scrcpy.Server], [1.17], [info], [720], [1000000], [30], [-1], [false], [-], [true], [true], [0], [true], [false], [-], [-]
```

I get this error even if I enable long path support in Windows 10 via
```
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled
```

I was able to get around this problem with `subst`:
```
subst x: "C:\Program Files\Unity\Hub\Editor\2020.2.1f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platform-tools"
ADB="x:\adb.exe"

# to unmap x: drive
subst x: /D
```

So it looks like something in the scrcpy pipeline is limiting the path length.

**Comment by rom1v** [comment]
It's only limited on Windows releases by mingw. If you know a solution to extand this limit on mingw, please help.

Refs https://github.com/Genymobile/scrcpy/issues/1358

**Comment by Biswa96** [comment]
Though it will be a misery to deal with, did you try using Unicode Win32 functions i.e. [`CreateProcessW`][1]? Also try with _prepending_ `\\?\` before the command line, e.g. `L"\\\\?\\MyFiles\\adb.exe"`. [`CreateFileW`][2] has that kind of trickery.

[1]: https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw
[2]: https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilew

**Comment by berniegp** [comment]
I don't know the actual solution unfortunately. I mostly wanted to post the workaround as reference.

However, I did a bit of digging based on how Git for Windows (it uses mingw) handles long paths (the `core.longpaths` option) and found interesting sources that match what @Biswa96 mentions:

`handle_long_path()` in
https://github.com/git-for-windows/git/blob/main/compat/mingw.h
https://github.com/git-for-windows/git/blob/main/compat/mingw.c

A blog that discusses this: 
https://www.brycevandyk.com/of-too-long-file-names-in-windows-and-git/

Hopefully this can help!

**Comment by rom1v** [comment]
Thank you for the links.

Note that here the problem is that the command (including the arguments) is too long, not the path of the executable.

**Comment by Biswa96** [comment]
If I compile the 'name_params' branch can I reproduce this issue? Can you provide a prebuilt binary of Android side server? I can compile the C program but Android SDK is in Gigs.

**Comment by Biswa96** [comment]
Yes, I also mean the command line, the second argument in `CreateProcessW`, the `lpCommandLine`. Off-topic, see my little experiment [here][1] as an example.

[1]: https://github.com/Biswa96/XConPty/blob/master/src/PseudoConsole.c

**Comment by rom1v** [comment]
Oh, but I'm stupid, the error `Command too long` comes from scrcpy:

https://github.com/Genymobile/scrcpy/blob/a1f2094787cf6267d9913dcf32e1782002a76729/app/src/sys/win/process.c#L17
https://github.com/Genymobile/scrcpy/blob/a1f2094787cf6267d9913dcf32e1782002a76729/app/src/sys/win/process.c#L30

:facepalm:

**Comment by rom1v** [comment]
Not relevant anymore. See a9d9cbf8b502cb537a1c7caaf2689be9eca3af60.

Also refs:
- 2eb881c5f13ae2c3a8c9ca68188c1abce77b48bd
- 04e5537f8ce21dbae365dcd980efda911188c945
- 7b29f5fd2de8f302e03365013093f5665efd3cfd
