### ISSUE TITLE
macOS: app:layout_scrollFlags is not working with two finger scroll in scrcpy, Toolbar no response

### ISSUE THREAD

**Issue by atychang** [Genymobile/scrcpy#136]
Hi!

`app:layout_scrollFlags="scroll|enterAlways|snap"` is not working with two finger scroll in scrcpy, Toolbar no response, but if scroll the screen with one finger click and drag, the Toolbar is working properly

It seems that the behavior of two finger scroll and one finger click and drag is not the same?

Thanks a lot!!

**Comment by rom1v** [comment]
Does it still happen?

**Comment by atychang** [comment]
It is working for me with the latest version. Thank you.
