### ISSUE TITLE
Scrcpy = keyboard not support ą , ę , ł , ż

### ISSUE THREAD

**Issue by alienos** [Genymobile/scrcpy#1360]
ą 
[server] WARN: Could not inject char u+0105
ę
[server] WARN: Could not inject char u+0119
ó 
working
ł
[server] WARN: Could not inject char u+0142
ż
[server] WARN: Could not inject char u+017c
ź
working
ć
working
ń
working
ś
working

Is it possible to implement this in the program. These are Polish diacritical marks.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#special-characters-do-not-work
