### ISSUE TITLE
mouse scroll makes main component focused

### ISSUE THREAD

**Issue by alexandre-janniaux** [Genymobile/scrcpy#1362]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Archlinux
 - scrcpy version: 12.1
 - installation method: archlinux package
 - device model: Mi A1
 - Android version: 9

**Describe the bug**

When scrolling with the mouse, if no element is focused, the main element gets focused, preventing scrolling to the end and coloring the whole UI with focus color. It does work correctly with drag scrolling or arrow, and works correctly if an element is already focused.

See attached screenshot:

![scrn-2020-05-07-10-53-04](https://user-images.githubusercontent.com/413037/81297769-0c963c80-9074-11ea-8c3f-d674d577b38b.png)

**Comment by rom1v** [comment]
Thank you for the report! :+1:

Fixed by e2d5f0e7fc98af97f3785ce492b7e8f87b109df1.

**Comment by thebigsmileXD** [comment]
This was heavily occurring on Reddit, many thanks for the patch!

**Comment by metayan** [comment]
The focus behavior is still (or maybe again) present. (Both before and after the recent fractional scroll changes.)

When holding mouse button and dragging, input is "touch", and it behaves correctly.
Using touchpad or mouse scroll wheel, input is "scroll".
Whenever input is "scroll", at first one item is selected, but after a few positions all the items in the current area are selected.
Scrolling with keyboard behaves fine, selecting one item at a time, both upwards and downwards.
Tested on a Mac.

**Comment by rom1v** [comment]
Is the behavior similar with HID mouse/keyboard (`scrcpy -KM`)?

**Comment by metayan** [comment]
Yes, quite similar. All the items get focused, but additionally the item under the mouse pointer is highlighted.

(Also, one has to click in the `scrcpy` window once after switching to it from another application. But that's probably a different issue.)

**Comment by rom1v** [comment]
> Yes, quite similar. All the items get focused

Then the behavior comes from the Android app or system. HID mouse is expected to behave the same way as a real mouse plugged via OTG or bluetooth (you can try a real mouse).

**Comment by metayan** [comment]
Ha. Indeed. Same with mouse via OTG.
Thanks for the lesson and patience.
