### ISSUE TITLE
Scrcpy ERR：Can't open Scrcpy v1.13

### ISSUE THREAD

**Issue by TremblingFool** [Genymobile/scrcpy#1365]
INFO: scrcpy 1.13 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: device offline
ERROR: "adb push" returned with value 1
Press any key to continue...

**Comment by TremblingFool** [comment]
Yesterday I was still using it normally,but this error occurred today

**Comment by rom1v** [comment]
https://stackoverflow.com/questions/8162581/why-does-adb-return-offline-after-the-device-string

**Comment by TremblingFool** [comment]
The cause of my problem is I was open the USB network cooperation. Is there any way I can share the USB network while casting a screen

**Comment by rom1v** [comment]
I don't know what it is. Scrcpy uses adb for the connection.

If `adb devices` shows that your device is connected, it will work. If it shows that your device is offline, it won't work.
