### ISSUE TITLE
apt: Package not found

### ISSUE THREAD

**Issue by Nikilauz** [Genymobile/scrcpy#1366]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Linux Mint 19.3 Tricia, Desktop: Xfce 4.14.1
 - scrcpy version: none
 - installation method: apt
 - device model: Lenovo Z50-70
 - Android version: doesn't matter

**Describe the bug**
When I type `apt install scrcpy`, I get a 'package not found' error (original message: `E: Paket scrcpy kann nicht gefunden werden.`). I already did `apt update`. Also in Synaptic I get no search results for `scrcpy`.

**Thank you very much for your response!**

**Comment by rom1v** [comment]
It's available in Ubuntu 20.04 and Debian testing/sid. Probably not in your distribution.

**Comment by Nikilauz** [comment]
Ok thanks. AFAIK there is a high chance that debian packages for Ubuntu are compatible with Mint.
Is it possible to somehow add it via external ppa or directly download the deb archive?

**Comment by ajgringo619** [comment]
I run the same OS/DE as you. I've been using the snap version for a few weeks now with no issues (USB only; no WiFi on my PC at the moment).

**Comment by Nikilauz** [comment]
That works fine, thanks.

**Comment by Nikilauz** [comment]
> Ok thanks. AFAIK there is a high chance that debian packages for Ubuntu are compatible with Mint.
> Is it possible to somehow add it via external ppa or directly download the deb archive?

I've tried this myself and although it's theoretically possible, I absolutely don't recommend going this way - you could easily end up not being able to boot your OS anymore ;)

**Comment by kptawesome** [comment]
Can confirm the same issue on eOS - package not found. Grabbing the deb from the internet gets me nowhere too

> kptawesome@kptawesome-desk:~/Downloads$ sudo dpkg -i scrcpy_1.12.1+ds-1_arm64.deb
> [sudo] password for kptawesome:       
> (Reading database ... 211859 files and directories currently installed.)
> Preparing to unpack scrcpy_1.12.1+ds-1_adb64.deb ...
> Unpacking scrcpy (1.12.1+ds-1) over (1.12.1+ds-1) ...
> dpkg: dependency problems prevent configuration of scrcpy:
>  scrcpy depends on libavcodec58 (>= 7:4.2); however:
>   Package libavcodec58 is not installed.
>  scrcpy depends on libavformat58 (>= 7:4.2); however:
>   Package libavformat58 is not installed.
>  scrcpy depends on libavutil56 (>= 7:4.0); however:
>   Package libavutil56 is not installed.
>  scrcpy depends on libc6 (>= 2.28); however:
>   Version of libc6:amd64 on system is 2.27-3ubuntu1.
>  scrcpy depends on libsdl2-2.0-0 (>= 2.0.10); however:
>   Package libsdl2-2.0-0 is not installed.
>  scrcpy depends on scrcpy-server; however:
>   Package scrcpy-server is not installed.
> 
> dpkg: error processing package scrcpy (--install):
>  dependency problems - leaving unconfigured
> Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
> Errors were encountered while processing:
>  scrcpy
>

**Comment by rom1v** [comment]
If it's not packaged, you must build it manually.

**Comment by kptawesome** [comment]
I just went ahead and downloaded the appimage of guiscrcpy to get my job done. I appreciate your quick response tho :)

**Comment by ajgringo619** [comment]
> Can confirm the same issue on eOS - package not found. Grabbing the deb from the internet gets me nowhere too
> 
> > kptawesome@kptawesome-desk:~/Downloads$ sudo dpkg -i scrcpy_1.12.1+ds-1_amd64.deb
> > [sudo] password for kptawesome:
> > (Reading database ... 211859 files and directories currently installed.)
> > Preparing to unpack scrcpy_1.12.1+ds-1_amd64.deb ...
> > Unpacking scrcpy (1.12.1+ds-1) over (1.12.1+ds-1) ...
> > dpkg: dependency problems prevent configuration of scrcpy:
> > scrcpy depends on libavcodec58 (>= 7:4.2); however:
> > Package libavcodec58 is not installed.
> > scrcpy depends on libavformat58 (>= 7:4.2); however:
> > Package libavformat58 is not installed.
> > scrcpy depends on libavutil56 (>= 7:4.0); however:
> > Package libavutil56 is not installed.
> > scrcpy depends on libc6 (>= 2.28); however:
> > Version of libc6:amd64 on system is 2.27-3ubuntu1.
> > scrcpy depends on libsdl2-2.0-0 (>= 2.0.10); however:
> > Package libsdl2-2.0-0 is not installed.
> > scrcpy depends on scrcpy-server; however:
> > Package scrcpy-server is not installed.
> > dpkg: error processing package scrcpy (--install):
> > dependency problems - leaving unconfigured
> > Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
> > Errors were encountered while processing:
> > scrcpy

Dpkg does not look for package dependencies, so you'll have to install them beforehand; kinda a catch-22 if you don't know what they are, right? You should uninstall the partially installed scrcpy and then you can go through the dependencies one at a time. This is exactly why I installed the snap version.
