### ISSUE TITLE
#bug alt gr on keyboard with Italian layout does not enter the characters located at the bottom right

### ISSUE THREAD

**Issue by telegramcore** [Genymobile/scrcpy#137]

**Comment by RedMoonOTInetwork** [comment]
For example: I do not want to insert @

**Comment by tgbetauser** [comment]
@rom1v have you create a shortcut for @ or have you fix it ?

**Comment by rom1v** [comment]
Could you apply this patch to get more logs about what is received by SDL on the client app, please?
https://github.com/Genymobile/scrcpy/issues/547#issuecomment-496291279

**Comment by tgbetauser** [comment]
I should copy and paste it in terminal?

**Comment by rom1v** [comment]
> should i copy and paste it in terminal in scrcpy folder?

Not really :wink:

Nevermind, I just remembered that I built a patched version: https://github.com/Genymobile/scrcpy/issues/547#issuecomment-496383958. (it's based on v1.8, so download v1.8 and replace `scrcpy.exe`).

**Comment by tgbetauser** [comment]
Not 1.9? I have already 1.8

**Comment by rom1v** [comment]
When I built it, it was based on 1.8, so you need the server 1.8.

**Comment by tgbetauser** [comment]
Wait: so, should I use 1.8 or 1.9?

**Comment by rom1v** [comment]
Download 1.8 release. Replace `scrcpy.exe` by [this one](https://github.com/Genymobile/scrcpy/issues/547#issuecomment-496383958).

**Comment by tgbetauser** [comment]
https://tmp.rom1v.com/scrcpy/issue547/1/scrcpy.exe 

This?

**Comment by rom1v** [comment]
Yes

**Comment by tgbetauser** [comment]
Thanks, very kind

**Comment by tgbetauser** [comment]
It works, thanks
