### ISSUE TITLE
Prevent sleep when scrcpy is fullscreen on Linux

### ISSUE THREAD

**Issue by NusryNizam** [Genymobile/scrcpy#1370]
Whenever I watch a video using scrcpy on Ubuntu (20.04), the screen dims and turns off. I would like to make it be on while scrcpy is fullscreen.
Is it possible to implement at software level?

**Comment by char101** [comment]
You can create a script that

1. check if `scrcpy` is running
2. run `adb shell input keyevent mouse` to prevent the screen from turning off
3. sleep for 30 seconds or longer depends on your screen timeout setting
4. go to 1.

**Comment by rom1v** [comment]
The feature `--stay-awake` is implemented on development branch: https://github.com/Genymobile/scrcpy/issues/631#issuecomment-622621215

**Comment by NusryNizam** [comment]
@rom1v I mean to prevent Linux from sleeping

**Comment by rom1v** [comment]
Oh ok, it's the reverse of #380 then :)

**Comment by rom1v** [comment]
Fixed by #1502.
