### ISSUE TITLE
“WARN: Trilinear filtering disabled (not an OpenGL renderer)”

### ISSUE THREAD

**Issue by nr1995** [Genymobile/scrcpy#1371]
“WARN: Trilinear filtering disabled (not an OpenGL renderer)”

I'm not a tech guy.
What can I do about this?

**Comment by rom1v** [comment]
On Windows, this is expected unless you force OpenGL rendering (`--render-driver=opengl`).

See v1.13 release notes: https://github.com/Genymobile/scrcpy/releases/tag/v1.13

**Comment by nr1995** [comment]
> On Windows, this is expected unless you force OpenGL rendering (`--render-driver=opengl`).
> 

Do you recommend it?
It's assume it's not the default for a reason.

**Comment by rom1v** [comment]
In https://github.com/Genymobile/scrcpy/pull/1284, I said:
> I'm hesitant to set opengl as the default render driver on Windows and macOS. I'm afraid that it could cause problems.

If you want trilinear filtering (for better downscale quality), enable this option. Otherwise, just keep the default.
