### ISSUE TITLE
Error when running scrcpy // Mac

### ISSUE THREAD

**Issue by ajaymen0n** [Genymobile/scrcpy#1375]
- OS: Mac
 - scrcpy version: 1.13
 - installation method: Brew
 - device model: S7 (Exy)
 
Following error when running scrcpy (ADB installed and device recognized, using low resolution and bit rate doesn't help either)

```
2020-05-09 22:36:46.284 scrcpy[10860:71450] INFO: scrcpy 1.13 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server:...ped. 36.7 MB/s (19038 bytes in 0.000s)
ERROR: Exception on thread Thread[main,5,main]
java.lang.NumberFormatException: For input string: "1.13"
	at java.lang.Integer.parseInt(Integer.java:608)
	at java.lang.Integer.parseInt(Integer.java:643)
	at com.genymobile.scrcpy.Server.createOptions(Server.java:49)
	at com.genymobile.scrcpy.Server.main(Server.java:69)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:287)
```

**Comment by rom1v** [comment]
I guess you're using an old scrcpy-server, maybe because you force a specific one via the env variable `SCRCPY_SERVER_PATH`.

What is the result of:

```bash
echo $SCRCPY_SERVER_PATH
```

?

**Comment by ajaymen0n** [comment]
Thank you for your reply, I'm really grateful for your app :)
The variable seems to be empty, the command does not output anything.

**Comment by ajaymen0n** [comment]
Hey! Seems like the problem was potentially from brew's side.
I uninstalled scrcpy with brew (`brew uninstall --force scrcpy`), manually removed the files from /usr/local/share and /usr/local/bin and /use/local/share/man/man1, installed scrcpy with brew again (`brew install scrcpy`), and re-linked it again (`brew unlink scrcpy && brew link scrcpy`)

This seems to have solved the problem!
Thanks for the help and good luck!

**Comment by rom1v** [comment]
If you have `aapt`, execute:

```
aapt d badging /usr/local/share/scrcpy/scrcpy-server | grep versionName
```

Otherwise, you could share `/usr/local/share/scrcpy/scrcpy-server` so that I can check.
