### ISSUE TITLE
rotate window option not available

### ISSUE THREAD

**Issue by raul-rb** [Genymobile/scrcpy#1376]
I am running Kubuntu 20.04, and installed scrcpy using the package manager. 
```
myself@mymachine:~$ scrcpy --version
scrcpy 1.12.1
```
But, when I try to rotate the window (something I use A LOT):
```
myself@mymachine:~$ scrcpy --rotation 1
scrcpy: unrecognized option '--rotation'
```
Indeed, scrcpy --help does not show that option. Shortcuts crtl+left / crtl+right do not work either.
I truly hope I can get back to use it...
Thanks

**Comment by rom1v** [comment]
Rotation features have been introduced in v1.13 (not packaged in Debian yet, and a specific version of Ubuntu won't upgrade until the next release anyway).

If you want v1.13 now, either [build](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md) manually or use the snap package.
