### ISSUE TITLE
Could not inject char : question mark and Emoji

### ISSUE THREAD

**Issue by jeanluc243** [Genymobile/scrcpy#1377]
**Environment**
 - OS: [e.g. Ubuntu 20.04]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: snap
 - device model: SAMSUNG
 - Android vesion : Android 8.1

** Bug Description **

When i use my computer keyboard and i try to copy *?* *question mark*

The output of the console

```bash
[server] WARN: Could not inject char u+00a7

```

When i try to copy an emoji from my Computer Virtual Keyboard 

The output of the console 

```bash
[server] WARN: Could not inject char u+df0c
```

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#special-characters-do-not-work
