### ISSUE TITLE
Is it possible to maintain a process id during opening and call it to front at some time?

### ISSUE THREAD

**Issue by Litchilitchy** [Genymobile/scrcpy#1379]
Hi, as suggested in a previous issue, I found scrcpy could open multiple android screen in one pc.

Then, could we maintain something like id, which would allow us to call it to front of the screen when we need?

A possible scenario would be we need to auto some operations using some other auto-control lib. And sometimes we want to do it for a specific android device, but it is covered by other program on the screen.

Is it a useful feature? Or any similar one existed?

**Comment by rom1v** [comment]
> Is it a useful feature?

IMO not in the scope of scrcpy.

Moreover, to automate clicks, it's probably better to fork and send events to the scrcpy server directly (instead of sending events to the scrcpy window).

**Comment by Litchilitchy** [comment]
> > Is it a useful feature?
> 
> IMO not in the scope of scrcpy.
> 
> Moreover, to automate clicks, it's probably better to fork and send events to the scrcpy server directly (instead of sending events to the scrcpy window).

Thanks for your suggestion, it is a better strategy to automate. In this case, only a screen id is required instead of calling to front, these multiple interactions.

So a possible way could be use (if python automate), `scrcpy --device_id` and send events to this server? But if we have multiple devices running, does it have multiple server? how do we send to the server we need?

**Comment by rom1v** [comment]
> But if we have multiple devices running, does it have multiple server? how do we send to the server we need?

Each device runs a `scrcpy-server` while scrcpy is running (they communicate via a socket, see [DEVELOP](https://github.com/Genymobile/scrcpy/blob/master/DEVELOP.md).

How you want to expose that in your automation stuff is up to you.

**Comment by Litchilitchy** [comment]
@rom1v great, thx! closed.
