### ISSUE TITLE
Transferring video to a Windows PC

### ISSUE THREAD

**Issue by keva1** [Genymobile/scrcpy#1381]
-  I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 -  I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS:  Windows
 - scrcpy version: 1.13
 - installation method: Windows release
 - device model: Android TV Box X96S
 - Android version: 9

The image of the played video from Android TV Box X96S on Windows PC is not broadcast. At this moment I see a black screen. Other management functions, printing text, transferring files, installing .apk files work fine. If I use my Android phone, managing and transferring video to a Windows PC works well.

**Comment by rom1v** [comment]
Some TV probably use either DRM or hardware-specific stuff for rendering which prevent screen capture. You probably have the same problem with `adb shell screenrecord /sdcard/file.mp4`.

**Comment by keva1** [comment]
When recording from adb shell screenrecord /sdcard/file.mp4 there is also no video. I do not think there is any DRM protection. This is a simple Chinese prefix. But the same files with my Android phone transferring video are good. Also, videos from the IPTV player and YouTube are not played. Maybe there are some solutions to the problem? Thank.

**Comment by rom1v** [comment]
No, I have no solution. If the video is black, then we cannot capture it (at least the way scrcpy works, and I don't know any other solution to avoid this). :/

**Comment by keva1** [comment]
Thanks for the responsiveness.
