### ISSUE TITLE
Exiting full screen doesn't restore the correct window size

### ISSUE THREAD

**Issue by Tyf0x** [Genymobile/scrcpy#1384]
**Environment**
 - OS: Windows 10
 - scrcpy version: 1.13
 - installation method: Windows release
 - device model: pixel 3 XL
 - Android version: 10

I run scrcpy using the following parameters: `--always-on-top --turn-screen-off --max-size 800`
When I go fullscreen (ctrl+f) then back to windowed, the initial size of the window is lost (ie. the resolution is still correct but the window takes the whole screen).

```
INFO: scrcpy 1.13 <https://github.com/Genymobile/scrcpy>
<snip>\scrcpy-server: 1 file pushed. 6.3 MB/s (27694 bytes in 0.004s)
[server] INFO: Device: Google Pixel 3 XL (Android 10)
INFO: Renderer: direct3d
WARN: Trilinear filtering disabled (not an OpenGL renderer)
INFO: Initial texture: 800x392
[server] INFO: Device screen turned off
```

Sceenshot before fullscreen (for scale)
![image](https://user-images.githubusercontent.com/6980921/81630069-01faef00-9448-11ea-8048-44ee2328b8cf.png)

Screenshot after entering then exiting fullscreen:
![image](https://user-images.githubusercontent.com/6980921/81630104-1808af80-9448-11ea-9d23-9765a6bb415f.png)

**Comment by rom1v** [comment]
Thank you for the detailed report.

This bug has been introduced in v1.13 on Windows and is fixed on development branch.

See #1346 (there is a link to Windows binaries in the comments).

**Comment by Tyf0x** [comment]
No worries, and sorry for the dup' (I didn't use the right keywords to find the other bug).
