### ISSUE TITLE
Scrcpy not working with Honor 10

### ISSUE THREAD

**Issue by corminat** [Genymobile/scrcpy#1385]
Hello,
I used Scrcpy with my previous phone ASUS Zenfone 3 ZE520KL and it worked very well. I changed my smartphone to Honor 10 and now it is not working. I activated the USB debugging but when I try to run SCRCPY but it is not working.
Anyone can help me?
Best regards,
José Marques

 - [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
> but it is not working

What is the error message?

**Comment by corminat** [comment]
[errormessage.pdf](https://github.com/Genymobile/scrcpy/files/4617630/errormessage.pdf)

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#device-not-detected

**Comment by corminat** [comment]
Problem solved.  In addition to USB debugging, I also had to activate ADB debugging in charging mode and now it works.
