### ISSUE TITLE
Map more keyboard characters

### ISSUE THREAD

**Issue by jimnordb** [Genymobile/scrcpy#139]
Being a norwegian. ÆØÅ is useful.

**Comment by rom1v** [comment]
Maybe this is [possible](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/view/KeyCharacterMap.java#189) for `Å`, but I have no solutions for the others.

See https://blog.rom1v.com/2018/03/introducing-scrcpy/#handling-accented-characters

**Comment by KeronCyst** [comment]
How about right-click to simulate the Back button?

**Comment by rom1v** [comment]
@KeronCyst Right-click already simulates the Back button.

**Comment by KeronCyst** [comment]
That's odd. Right-clicking doesn't do anything for me on my Windows 10 Home.

**Comment by KeronCyst** [comment]
Now I am seeing that it does not recognize NumPad Enter as Return.

**Comment by rom1v** [comment]
> Now I am seeing that it does not recognize NumPad Enter as Return.

See https://github.com/Genymobile/scrcpy/issues/117.
