### ISSUE TITLE
Run multi scrcpy screens with 1 command

### ISSUE THREAD

**Issue by quancayda** [Genymobile/scrcpy#1391]
Hello,

I need to use scrcpy test many android devices simultaneously on same game to compare quality each device.. When input adb devices command, I retrieve device ids as below:

```
D:\scrcpy-win64-v1.13>adb devices
List of devices attached
8CFX1NYFN       device
ce10160a22d05a1704      device
```
How to run scrcpy of those devices at same time **with only 1 command**?

Currently I have to input each command with specific android id on different windows to execute it.
**scrcpy -s 8CFX1NYFN** in 1st windows
**scrcpy -s ce10160a22d05a1704**  in 2nd windows

If I run 5 devices, I have to open 5 console windows and input 5 times :(. Any suggestion to run only 1 console windows / 1 command for 5 devices simultaneously?

I tried this 1 command for 2 devices: _scrcpy -s 8CFX1NYFN -s ce10160a22d05a1704_ , but it did't work.

Thanks for your support!

**Comment by rom1v** [comment]
https://superuser.com/questions/198525/how-can-i-execute-a-windows-command-line-in-background/591084#591084

```
start /B scrcpy -s ...
```

**Comment by quancayda** [comment]
Tested, but it just run 1 scrcpy windows for 1 device:

```
D:\scrcpy-win64-v1.13>**start /B scrcpy -s 8CFX1NYFN -s ce10160a22d05a1704**

D:\scrcpy-win64-v1.13>INFO: scrcpy 1.13 <https://github.com/Genymobile/scrcpy>
D:\scrcpy-win64-v1.13\scrcpy-server: 1 file pushed. 1.9 MB/s (27694 bytes in 0.014s)
[server] INFO: Device: samsung SM-G930F (Android 8.0.0)
INFO: Renderer: direct3d
WARN: Trilinear filtering disabled (not an OpenGL renderer)
INFO: Initial texture: 1080x1920
```
it can't run 2 scrcpy screens for 2 devices at same time with only 1 command.

**Comment by rom1v** [comment]
`start /B` just excutes the process in the background, so that you can immediately execute another process.

Create a .bat containing:

```
start /B scrcpy -s serial1
start /B scrcpy -s serial2
```
and execute it.

**Comment by quancayda** [comment]
Thanks for suggestion, it works with .bat file.

**Comment by James4Ever0** [comment]
You can run and manage multiple windows for multiple devices with SWM.

Check out the repo here: https://github.com/james4ever0/swm
