### ISSUE TITLE
No mouse and keyboard control

### ISSUE THREAD

**Issue by Jonathanr67** [Genymobile/scrcpy#1392]
Hi, i didn't have any mouse and keyboard control on my smartphone. Is there a option to change on it ?
I have an xiaomo pocophone

thank you

jonathan

- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
I recently added the issue template to avoid issues asking the same questions again and again.

There is an explicit entry "I have read the FAQ", which should be done before opening an issue.

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work
