### ISSUE TITLE
could not execute adb push

### ISSUE THREAD

**Issue by Leg0Las16** [Genymobile/scrcpy#1397]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: scrcpy-win64-v.1.13
 - installation method: instal adb with platform-tool
 - device model: realme RMX1921
 - Android version: 10

**Describe the bug**
when I click to run scrcpy-noconsole, nothing happen. My phone already connected to pc and listed in adb devices.

```
Please paste terminal output in a code block.
INFO: scrcpy 1.13 <https://github.com/Genymobile/scrcpy>
ERROR: Command not found: [C:\Windows\System32;], [push], ["C:\Users\Adelbertus Rumapea\Downloads\Compressed\scrcpy-win64-v1.13\scrcpy-server"], ["/data/local/tmp/scrcpy-server.jar"]
ERROR: (make 'adb' accessible from your PATH or define its fullpath in the ADB environment variable)
INFO: You may download and install 'adb' from https://developer.android.com/studio/releases/platform-tools
ERROR: Could not execute "adb push"
Press any key to continue...

```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by Leg0Las16** [comment]
Already get the solution. I just deleted the ADB path from environment variables. Thankyou...

**Comment by SandroPacella** [comment]
> Already get the solution. I just deleted the ADB path from environment variables. Thankyou...

mind if I ask how? :)

**Comment by Leg0Las16** [comment]
> > Already get the solution. I just deleted the ADB path from environment variables. Thankyou...
> 
> mind if I ask how? :)

From MyComputer->RightClick->Properties
Click Advanced System Settings->go to Advanced tab->Environment Variables.

and I deleted ADB path from there.
