### ISSUE TITLE
Turn screen on after Ctrl+o

### ISSUE THREAD

**Issue by 2244131632** [Genymobile/scrcpy#1399]
(google translated)

Hello there! When I use Ctrl + o to hold the phone during the scrcpy operation, the phone screen does not know how to light up. It needs to be restarted every time to solve the problem. (Mobile phone: Xiaomi 8 System: Android10 MIUI12 20.5.7 development board)

---

你好！我在使用scrcpy过程中使用Ctrl+o手机息屏操作时手机屏幕不知如何点亮需要每次重启手机才能解决。（手机：小米8 系统：Android10 MIUI12 20.5.7开发板）

**Comment by hsingll** [comment]
按下电源键就亮了，或者ctrl+p

**Comment by gdh1995** [comment]
遇到了同样的问题，没有稳定的办法重新显示屏幕。有时候Ctrl+P, Backspace 一通乱按可以，刚刚发现息屏后有时候按 Ctrl+H 有时候可以。

还有个问题是在桌面上按Ctrl+O的话会造成图标丢失，只剩一个动态地球背景，但还是能操作的。

**Comment by rom1v** [comment]
Please post in English.

Ctrl+p once will switch the screen off. Wait few seconds, then Ctrl+p (or POWER) should turn it on again.

**Comment by gdh1995** [comment]
Um, I think the `a few seconds` is unknown for new users like me.

I've searched in the source code, and in `.c` files there seems no input action (`keycode`) to call `set_screen_power_mode` with `SCREEN_POWER_MODE_NORMAL`. Therefore, I suggests a new combined key to do send it. What about <kbd>Ctrl+Shift+O</kbd>?

**Comment by rom1v** [comment]
The reason is here: 8c8649cfcd710859ce18eab557ed2af8cedb9a42.

**Comment by rom1v** [comment]
I just reactivated the shortcut, in practice it works: dcde578a50ffb9d2594c4764a067e9dd328bf55c
