### ISSUE TITLE
Export to GIF feature

### ISSUE THREAD

**Issue by viktor1190** [Genymobile/scrcpy#140]
Hey Thanks a lot for this wonderful tool!

This tool is great for developers, and there is many scenarios where is necesary to export a screen record to GIF format, in many cases is more useful than a heavy video file. So would be great to have a direct feature for that!

**Comment by rom1v** [comment]
Depends on https://github.com/Genymobile/scrcpy/issues/21.

**Comment by rom1v** [comment]
The new version (1.5) allows to record to mp4:

    scrcpy --record file.mp4

You can then convert your mp4 to gif using FFmpeg: https://superuser.com/a/556031/310383

**Comment by viktor1190** [comment]
Great!! That will help us a lot. Thanks
