### ISSUE TITLE
Wifi connection issue: No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by apdd2003** [Genymobile/scrcpy#1400]
Since few days I get this error when trying to connect via wifi. It was working earlier with same setup.

Connection via usb works fine but I want to use wifi connection.

Trying to use following steps 

```
1. Connect the device to the same Wi-Fi as your computer.
2. Get your device IP address (in Settings → About phone → Status).
3. Enable adb over TCP/IP on your device: adb tcpip 5555.
4. Unplug your device.
5. Connect to your device: adb connect 192.168.2.104:555 (replace DEVICE_IP).
```
step 3 gives "* daemon started successfully                                                                                                                                                                                                   restarting in TCP mode port: 555  "
step 5 gives this error "cannot connect to 192.168.2.104:555: No connection could be made because the target machine actively refused it. (10061)"

**Comment by rom1v** [comment]
https://stackoverflow.com/questions/37267335/android-studio-wireless-adb-error-10061

I don't know if this is a rypo, but in your message, you connected to port 555 instead of 5555.

**Comment by apdd2003** [comment]
my bad. you are right. since 3 days I was making same typo :(.. It is working now. closing
