### ISSUE TITLE
Xperia C Segmentation fault

### ISSUE THREAD

**Issue by carlosdelfino** [Genymobile/scrcpy#1402]
- [ x ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ x ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: 1.13
 - installation method: choco
 - device model: Sony C3
 - Android version: 4.2.2

**Describe the bug**

Simple: run scrcpy

```
INFO: scrcpy 1.13 <https://github.com/Genymobile/scrcpy>
C:\ProgramData\chocolatey\lib\scrcpy\tools\scrcpy-server: 1 file pushed. 2.6 MB/s (27694 bytes in 0.010s)
adb.exe: error: closed
ERROR: "adb reverse" returned with value 1
WARN: 'adb reverse' failed, fallback to 'adb forward'
27183
Segmentation fault
Press any key to continue...
```

**Comment by rom1v** [comment]
Android >= 5 is required.
