### ISSUE TITLE
can't turn screen back on with Ctrl+ O on Windows build

### ISSUE THREAD

**Issue by arthurgeron** [Genymobile/scrcpy#1404]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - Windows
 - scrcpy version: 1.12.1
 - installation method: Windows release
 - device model: Xiaomi MI 9T Pro
 - Android version: 11

**Describe the bug**
After turning my phone's screen off with `ctrl+o` I'm not able to turn it back on using the same shortcut

```
server] INFO: Device screen turned off
[server] INFO: Device screen turned off
[server] INFO: Device screen turned off
[server] INFO: Device screen turned off
[server] INFO: Device screen turned off
[server] INFO: Device screen turned off
[server] INFO: Device screen turned off
INFO: New texture: 2336x1080
INFO: New texture: 1080x2336
INFO: New texture: 2336x1080
[server] INFO: Device screen turned off
[server] INFO: Device screen turned off
[server] INFO: Device screen turned off
[server] INFO: Device screen turned off
[server] INFO: Device screen turned off
[server] INFO: Device screen turned off
[server] INFO: Device screen turned off
```

**Comment by rom1v** [comment]
You can only turn it back on with the power button.

Initially, there was another shortcut, but it caused issues: https://github.com/Genymobile/scrcpy/issues/175#issuecomment-498191274

**Comment by arthurgeron** [comment]
@rom1v I see! Makes sense now, maybe thst should be properly pointed out in the docs, I'll open a MR. Thanks!

**Comment by rom1v** [comment]
I just reactivated the shortcut (`Ctrl`+`Shift`+`o`), in practice it works: dcde578a50ffb9d2594c4764a067e9dd328bf55c
