### ISSUE TITLE
How to create a wireless connection in ubuntu

### ISSUE THREAD

**Issue by bsde1234** [Genymobile/scrcpy#1405]
I connect pc and mobile to same wifi, then issued `adb tcpip 5555`. I get the error `error: no devices/emulators found`. Do I need to plug my mobile to pc first?

**Comment by rom1v** [comment]
> Do I need to plug my mobile to pc first?

Yes.

The device must be listed in `adb devices`.

**Comment by bsde1234** [comment]
Thank you.
