### ISSUE TITLE
Bug: snappying to full screen and then back, it switches to huge size

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Genymobile/scrcpy#1410]
- [V ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ V] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
Windows
 - scrcpy version: [e.g. 1.12.1]
1.13

 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
Extraction of zipped file
 - device model:
Pixel 4
 - Android version: [e.g. 10]
10

**Describe the bug**
1. Run this:
C:\android\scrcpy\scrcpy-noconsole.exe -T
2. Snap the window to the top, making it snap to largest size.
3. Un-snap the window, which should return it to the previous size.

The bug is that for a tiny amount of time it will indeed switch back to previous size, but then gets to be large size.

See here:
[2020-05-20_11-06-54.zip](https://github.com/Genymobile/scrcpy/files/4655475/2020-05-20_11-06-54.zip)

**Comment by rom1v** [comment]
This is the same as bug #1346 and #1384.

**Comment by AndroidDeveloperLB** [comment]
OK sorry. It got harder and harder to search for existing issues here.
