### ISSUE TITLE
Download link not working

### ISSUE THREAD

**Issue by wincelee** [Genymobile/scrcpy#1432]
The download link for windows is not working its showing an error

**Comment by rom1v** [comment]
Which error? It's working here.

**Comment by wincelee** [comment]
![image](https://user-images.githubusercontent.com/36560385/82871637-91210000-9f3a-11ea-91ce-32164df120cb.png)

**Comment by wincelee** [comment]
![image](https://user-images.githubusercontent.com/36560385/82871791-c3326200-9f3a-11ea-8f68-c85b83d0da9a.png)

**Comment by rom1v** [comment]
Since it works for everyone else, it's probably a problem on your side (proxy settings, internet connection, browser issue, etc.).

**Comment by wincelee** [comment]
okay let me try on another browser

**Comment by wincelee** [comment]
thanks it is working

**Comment by laksh225** [comment]
Close #1432

**Comment by Arash4567** [comment]
why is it not working scrspy?

yoshhacker@yoshhacker:~$ scrcpy
INFO: scrcpy 1.14 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: no devices/emulators found
ERROR: "adb push" returned with value 1

**Comment by rom1v** [comment]
> adb: error: failed to get feature set: no devices/emulators found

`adb devices`?

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#adb-issues
