### ISSUE TITLE
Use software rendering fallback when driver not availble

### ISSUE THREAD

**Issue by bpsib** [Genymobile/scrcpy#1434]
I get this when trying it on Ubuntu over TightVNC:
```
INFO: scrcpy 1.13 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 0.7 MB/s (27694 bytes in 0.040s)
Xlib:  extension "RANDR" missing on display ":1.0".
[server] INFO: Device: HUAWEI CLT-L09 (Android 9)CRITICAL: Could not create renderer: Couldn't find matching render driver
```
The majority of other programs including video players work over VNC as they fallback to software rendering. So why not this? I rather it work with a bit of a lag than it not work at all.

**Comment by rom1v** [comment]
Does it work with:

    scrcpy --render-driver=software

?

**Comment by bpsib** [comment]
> 
> 
> Does it work with:
> 
> ```
> scrcpy --render-driver=software
> ```
> 
> ?

Yes. Solved my problem. That option doesn't seem to be documented anywhere.

**Comment by rom1v** [comment]
```
$ scrcpy --help
...
    --render-driver name
        Request SDL to use the given render driver (this is just a
        hint).
        Supported names are currently "direct3d", "opengl",
        "opengles2", "opengles", "metal" and "software".
        <https://wiki.libsdl.org/SDL_HINT_RENDER_DRIVER>
```

```
$ man scrcpy
...
       --render-driver name
              Request SDL to use the given render driver (this is just a hint).

              Supported names are currently "direct3d", "opengl", "opengles2", "opengles", "metal" and "software".  ⟨https://wiki.libsdl.org/SDL_HINT_RENDER_DRIVER⟩
```

But yes, it's not detailed in the README, too specific.

**Comment by rom1v** [comment]
If it's too slow, I would also suggest `-m800 --max-fps 15` (or other values) to reduce frame size and frame rate.

**Comment by techroy23** [comment]
@rom1v  where can i get the correct dll for opengles2 and opengles. it always defaults back to direct3d when i use --render-driver opengles
