### ISSUE TITLE
Stay Awake not functioning

### ISSUE THREAD

**Issue by Stokstaart** [Genymobile/scrcpy#1439]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
Windows 8.1
Huawei P30 Pro 
scrcpy 1.14

**Describe the bug**
Upon issueing "scrcpy -Sw -m 800" from commandline new window pops up, it powers down the display on my phone, but after 15 sec (of inactivity)  the popup also 'shuts down' (black screen). Right-click on the windows activates both windows and phone display.

```
INFO: scrcpy 1.14 <https://github.com/Genymobile/scrcpy>
C:\StackSync\Portable_Apps\Unmanaged\s...ped. 28.0 MB/s (33142 bytes in 0.001s)
[server] INFO: Device: HUAWEI VOG-L29 (Android 10)
INFO: Created renderer: direct3d
INFO: Renderer: direct3d
INFO: Initial texture: 368x800
[server] INFO: Device screen turned off
```

EDIT) added "(of inactivity) "

**Comment by rom1v** [comment]
Could you please give the result of:

```
adb shell settings get global stay_on_while_plugged_in
```

 - before your start scrcpy with `-w`
 - while `scrcpy -w` is running
 - after you closed scrcpy

**Comment by Stokstaart** [comment]
All commands reply with '7'

**Comment by Stokstaart** [comment]
I see where this is going, i use the phone for work aswell and the device policy doesn't allow the phone to stay awake during charging, my bad!

**Comment by Stokstaart** [comment]
Company device policy doesn't allow to change the "Stay awake while charging" setting.
