### ISSUE TITLE
Stay awake function is not working

### ISSUE THREAD

**Issue by dacs6** [Genymobile/scrcpy#1442]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Win10]
 - scrcpy version: [1.14]
 - installation method: [Win64-v1.14]
 - device model: OnePlus GM1910
 - Android version: [Android 10]

**Describe the bug**
Parameter ''-w" is set while running the script, however after running out of the predefined screen lock time, the display in Win10 still turns into black.

On errors, please provide the output of the console (and `adb logcat` if relevant).

INFO: scrcpy 1.14 <https://github.com/Genymobile/scrcpy>
G:\My Documents\OneDrive - FreeShadow\App\scrcpy-win64\scr... file pushed, 0 skipped. 18.7 MB/s (33142 bytes in 0.002s)
[server] INFO: Device: OnePlus GM1910 (Android 10)
INFO: Created renderer: direct3d
INFO: Renderer: direct3d
INFO: Initial texture: 1440x3120
ERROR: SDL failed to get a vertex buffer for this Direct3D 9 rendering batch!
ERROR: Dropping back to a slower method.
ERROR: This might be a brief hiccup, but if performance is bad, this is probably why.
ERROR: This error will not be logged again for this renderer.

**Comment by rom1v** [comment]
Same question as: https://github.com/Genymobile/scrcpy/issues/1439#issuecomment-635262503

Could you please give the result of:

```
adb shell settings get global stay_on_while_plugged_in
```

 - before your start scrcpy with `-w`
 - while `scrcpy -w` is running
 - after you closed scrcpy

Do you have some device policy enabled?

**Comment by dacs6** [comment]
I just saw another thread reporting same issue, and the output of 'adb shell settings get global stay_on_while_plugged_in' is also '7'.

My company also forced some security policy onto this cell, probably that's the reason why stay awake is not working, please confirm. Thx.

**Comment by rom1v** [comment]
> My company also forced some security policy onto this cell, probably that's the reason why stay awake is not working, please confirm.

It seems so.

I'm curious to know why a company would *forbid* to enable "stay awake while plugged in" though. Maybe it's a default setting in their policy configuration?

**Comment by dacs6** [comment]
I am in a telecommunication company and strong security policy is imposed, eg, all data is wiped off after 10 unsuccessful login, etc. 
It's clear that's the reason, thanks for your prompt response.

**Comment by dacs6** [comment]
BTW, currently I am using 'Screen On' app to keep the display on, just don't know why it can bypass the security setting.

**Comment by rom1v** [comment]
Because it just acquires a wake lock. But it requires to be a "real" Android application.
