### ISSUE TITLE
stay-awake flag doesn't work when device isn't charging

### ISSUE THREAD

**Issue by Matthbo** [Genymobile/scrcpy#1445]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: 1.14
 - installation method: Windows x64 zip
 - device model: Xiaomi Mi A1
 - Android version: 9

**Describe the bug**
The screen won't stay awake as the flag suggests, unless the device is charging

Using commands:
```
./scrcpy -Sw
# or
./scrcpy -w
# or
./scrcpy --stay-awake
```

Expected behaviour: \
The screen will stay awake, even if the device isn't charging

**Comment by rom1v** [comment]
That is correct. Btw, the Android option is called `stay_on_while_plugged_in`.

I just added this limitation to the documentation: 0e4a6f462bcc628af00896eea38aa883d68acc88

AFAIK, there is no way to "stay awake" while the device is unplugged with an Android setting (without a separate app taking a wake lock, with its own limitations).

**Comment by Matthbo** [comment]
Ah okay, that makes sense

**Comment by jsuelwald** [comment]
I'd like to re-open this ticket and would like to have "stay awake even while not charging" as a feature.

Reason: If other apps can do this, why can't scrcpy do this as well?

**Comment by rom1v** [comment]
> Reason: If other apps can do this, why can't scrcpy do this as well?

Because (at least [for now](https://github.com/Genymobile/scrcpy/issues/1880#issuecomment-725655830)) the device side of scrcpy is not an Android app. But even if it was, I'm not sure you can hold a wakelock if you are not the app with an activity in the background.

**Comment by ahmed98Osama** [comment]
https://github.com/Genymobile/scrcpy/issues/1445#issuecomment-950140429

a Very good trick from @Pawloland 
i love it and it is working 😍
