### ISSUE TITLE
Stutter/lag if using Bluetooth to stream audio

### ISSUE THREAD

**Issue by rizaumami** [Genymobile/scrcpy#1450]
To get sound while mirroring, I use bluetooth dongle to stream audio from smartphone to laptop.
Without streaming audio via bluetooth the mirrored screen is displayed normally, but if bluetooth used to stream the audio the mirrored display is laggy/stutter.

scrcpy v1.14
Laptop OS: Ubuntu 20.04
Phone: Xiaomi Redmi Note 5 AI
ROM: MiRoom 20.5.14. MIUI 12 based on Android 9.0.
BT dongle: Ugreen USB BT 4.0. aptX capable.

**Comment by rom1v** [comment]
Probably some conflicts on USB? Unfortunately, I'm not sure scrcpy can do anything about that.

**Comment by rizaumami** [comment]
I think you're right. I've changed the USB BT dongle with BT receiver and the lag is less noticeable.

Thanx.

**Comment by rizaumami** [comment]
I might wasn't clear about this. But the lag happens when scrcpy connected via wifi adb. If the smartphone connected to laptop through USB cable there is no lag.
