### ISSUE TITLE
CRITICAL: Could not create texture: Texture dimensions are limited to 2048x2048

### ISSUE THREAD

**Issue by maximousblk** [Genymobile/scrcpy#1451]
I didn't know if this was a bug. I get the following error when I run `scrcpy`:

```
C:\Users\maximousblk\scrcpy
λ scrcpy
INFO: scrcpy 1.14 <https://github.com/Genymobile/scrcpy>
C:\Users\maximousblk\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 18.1 MB/s (33142 bytes in 0.002s)
[server] INFO: Device: samsung SM-XXXXX (Android 10)
INFO: Created renderer: direct3d
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2336
CRITICAL: Could not create texture: Texture dimensions are limited to 2048x2048
Press any key to continue...
```

I'm on windows 10 pro, if that means anything.

**Comment by rom1v** [comment]
Your graphics driver do not allow to create textures at the size of your phone.

Reduce the definition:

    scrcpy -m2048

You might also try another renderer (but I guess it will not work better):

    scrcpy --render-driver=opengl

**Comment by maximousblk** [comment]
> Reduce the definition:
> ```
> scrcpy -m 2048
> ```

Thank you so much. This works flawlessly.

---

P.S. As soon as the screen popped up I started to miss the home and back button. I wonder if there are keyboard shortcuts for the android 10 gestures. It was easy to control the device till android 9 but you guys need to add some workaround for the Android 10 gestures. If you agree, I can open a new issue for it.

**Comment by rom1v** [comment]
Right-click is BACK, Middle-click is HOME.

https://github.com/Genymobile/scrcpy/blob/master/README.md#shortcuts

**Comment by rom1v** [comment]
I'm interested to know if this works for you:

    scrcpy --render-driver=opengl

**Comment by maximousblk** [comment]
> I'm interested to know if this works for you:
> 
> ```
> scrcpy --render-driver=opengl
> ```

Nope. I get this:

```
C:\Users\maximousblk
λ scrcpy --render-driver=opengl
INFO: scrcpy 1.14 <https://github.com/Genymobile/scrcpy>
C:\bin\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 18.4 MB/s (33142 bytes in 0.002s)
[server] INFO: Device: samsung SM-XXXXX (Android 10)
INFO: Created renderer: direct3d
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2336
CRITICAL: Could not create texture: Texture dimensions are limited to 2048x2048
Press any key to continue...
```

**Comment by rom1v** [comment]
> scrcpy -m 2055

In fact, the number you give is rounded down to a multiple of 8, so in practice it's the same as 2048 :wink:

**Comment by Getrichero** [comment]
Hi
When I write 'scrcpy -m2048' and press enter, scrcpy shuts down. What can I do? 
I'm using Windows 7 32-bit. 
[I wrote it in translation]

**Comment by rom1v** [comment]
> When I write 'scrcpy -m2048' and press enter, scrcpy shuts down.

What's the output in the console?

**Comment by Getrichero** [comment]
Scrcpy won't open. When I type the code and press enter, the console closes. Thank you for answering. ❤️

**Comment by rom1v** [comment]
> Scrcpy won't open.

Could you copy-paste the text you see in the whole console, please?

> When I type the code and press enter, the console closes.

You open a console with `cmd.exe`, go to your scrcpy directory, and type `scrcpy -m2048`, and the console closes? :thinking:

**Comment by Getrichero** [comment]
I can't run scrcpy in cmd.exe. I'm getting the following error 'C:\Users\user\scrcpy.exe is not a valid Win32 application.'
I get this error when I run the console myself. 
`INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
C:\Users\user\Desktop\Scrcpy\screpy-se...pped. 1.8 MB/s <33622 bytes in 0.018s>
[server] INFO: Device: Xiaomi Mi A2 Lite <Android 10>
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2280
CRITICAL: Could not create texture: Texture dimensions are limited to 2048x2848
Press any key to continue...`

**Comment by rom1v** [comment]
> 'C:\Users\user\scrcpy.exe is not a valid Win32 application.'

> C:\Users\user\Desktop\Scrcpy\...

It seems you have several scrcpy installed, and you put one of them in your PATH. Try:

```
# from cmd.exe
cd C:\Users\user\Desktop\Scrcpy\
scrcpy.exe
```

**Comment by PURGE-DAY** [comment]
Is there any shortcut way to directly just click one .exe file and it all done itself, I mean "opening cmd then typeing scrcpy -m2048 then hit enter" . My sister can't do all this manually please if anyone know the trick to just click one file and all done  share it.

**Comment by Biswa96** [comment]
Just make a batch script for her.

**Comment by rom1v** [comment]
Create a file `myscrcpy.bat` containing the commands, and double-click on it.

**Comment by PURGE-DAY** [comment]
> Just make a batch script for her.

Thank you! @Biswa96 it worked :)

**Comment by PURGE-DAY** [comment]
> Create a file `myscrcpy.bat` containing the commands, and double-click on it.

Thanks! @rom1v this method worked :)

**Comment by PURGE-DAY** [comment]
With help of you guys I have created a .bat file to open scrcpy directly. But I want to add one more command inside bat file to make cmd window invisible and only mobile mirror screen window should open on double click of .bat file.

**Comment by rom1v** [comment]
Call `scrcpy-noconsole` instead of `scrcpy`.

**Comment by AngelFxxK** [comment]
Can you send me this .bat file to download?

**Comment by AngelFxxK** [comment]
Hello comrades, so I go straight to the point, I have the same problem because of the resolution of my smartphone which is 1080x2400 and I was trying several ways to fix this problem, I even followed the steps you said just above  but i'm really not understand that, i'm desperate.

**Comment by rom1v** [comment]
Using the [command line on Windows](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows), execute `scrcpy -m2048`.

**Comment by AngelFxxK** [comment]
I opened the cdm and put the command, it just opened the file directory.

**Comment by AngelFxxK** [comment]
I managed to put the correct command now, it worked thanks.

**Comment by dancingbirdie** [comment]
> Your graphics driver do not allow to create textures at the size of your phone.
> 
> Reduce the definition:
> 
> ```
> scrcpy -m2048
> ```
> 
> You might also try another renderer (but I guess it will not work better):
> 
> ```
> scrcpy --render-driver=opengl
> ```

Thank you so much for the help. I can now run my screen smoothly.

**Comment by insanegaming2805** [comment]
> Create a file `myscrcpy.bat` containing the commands, and double-click on it.

hey there,

**Comment by rom1v** [comment]
> how can i create this file

Right-click in the scrcpy folder, create new file…

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows

**Comment by dagdae** [comment]
ok so.....after 3 years with no updates of Virtualbox, i decided to update it....and EVERYTHING stopped working..... I had to reinstall windows 7 and got all sort of missing usb drivers for my old samsung s9+....in the end I managed to solve all, except the Could not create texture D3DPOOL_DEFAULT invalid call..... I tried to use the scrcpy --render-driver=opengl command that kind of worked, but the app was acting broken, opening the window but showing a hole in the screen, dragging around the render of what was UNDER the window....i guess because there is no open gl in virtualbox...so, its a graphic rendering problem....how can i try to solve it?

**Comment by kunalupadhyay70** [comment]
it realy works bro thanks
