### ISSUE TITLE
Does the latency of scrcpy is related to whether the screen of mobile phone is damaged

### ISSUE THREAD

**Issue by YxGHB** [Genymobile/scrcpy#1456]
My device is mi8se(miui11,android 10,1080x2240)

### There are three situations when using scrcpy:

  1. When the undamaged mobile screen is installed on the mobile phone, scrcpy can display smoothly without delay, and the resolution is 1080x2240
 2. When the damaged mobile screen is installed on the mobile phone, there will be a big delay in scrcpy (using "scrcpy-m" or other parameters still exist), and the resolution is still 1080x2240
 3. When the screen is unplugged from the phone, there will be no delay in running scrcpy directly, but only a part of the screen can be displayed at this time

 I wonder why this happens?

**Comment by rom1v** [comment]
> Does the latency of scrcpy is related to whether the screen of mobile phone is damaged

Yes, it seems so: #1285 #1353

**Comment by YxGHB** [comment]
> > Does the latency of scrcpy is related to whether the screen of mobile phone is damaged
> 
> Yes, it seems so: #1285 #1353

I'm just a user to scrcpy and like this app ,thank you for your reply! by the way,  can i change the  resolution of above situation of third  to 1080x2240 manually?

**Comment by YxGHB** [comment]
I've been resolved the problem for the situation three (Initial texture:640x480).
type the following command in adb:
adb shell wm size 512x960
adb shell wm density 256
scrcpy
Now ,i can smoothly using it without latency when the  screen is  unplugged from my phone,and hope that this may be helpful to you who has the same problem

**Comment by ShantanuNair** [comment]
> > Does the latency of scrcpy is related to whether the screen of mobile phone is damaged
> 
> Yes, it seems so: #1285 #1353

Hey @rom1v, really appreciate you being so active on issues. Any idea why screen damage would impact? Seems like as my (broken) screen became progressively worse, my scrcpy has also become unusable.

**Comment by rom1v** [comment]
> Any idea why screen damage would impact?

No, I don't know.

**Comment by ShantanuNair** [comment]
> > Any idea why screen damage would impact?
> 
> No, I don't know.

I see. Very interestingly, after about 2 weeks of not working well at all (not even in a screen recording, <1fps while reporting in the app fps counter ~11fps), it seems that it is now working perfectly again. I was starting to think it might have been something to do with the dependency version but now it seems more likely something to do with circumstance such as the screen damage i guess?

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/issues/1285#issuecomment-917513993
