### ISSUE TITLE
Please support multi-display feature for Mac 

### ISSUE THREAD

**Issue by Sandboxcn** [Genymobile/scrcpy#1461]

**Comment by rom1v** [comment]
What do you mean?

**Comment by Sandboxcn** [comment]
> What do you mean?

I mean that the scrcpy --display option

**Comment by rom1v** [comment]
It's implemented. What's the problem?

**Comment by Sandboxcn** [comment]
> It's implemented. What's the problem?

But I cannot use the option on Mac.

**Comment by Sandboxcn** [comment]
I found that I just use the old version scrcpy...
