### ISSUE TITLE
Please support recording audio using aux

### ISSUE THREAD

**Issue by edsulaiman** [Genymobile/scrcpy#1462]
please add an audio record feature using an **aux cable**, when the recorder starts, it also records **input from a computer microphone** connected to the aux cable. 

Most people use the alternative to record using obs, but that **requires a lot of RAM and CPU**

**Comment by rom1v** [comment]
#1104 

As a workaround, you could record line-in separately (with any audio recording software) then mux them with the video-only file recorded with scrcpy (the tricky part will be video-audio synchronization though).
