### ISSUE TITLE
Can't access sdcard (marked as read-only)

### ISSUE THREAD

**Issue by ajgringo619** [Genymobile/scrcpy#1463]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Linux Mint 19.3 XFCE]
 - scrcpy version: [v1.14]
 - installation method: [snap]
 - device model: Nokia 3.1a
 - Android version: [9]

**Describe the bug**
I want to change the default download location when I pass files to my phone, either via CLI or drag-and-drop via Thunar. I can do this on the default internal storage device, but any directory I select on my microSD card is marked as read-only. Is this a setting I need to change on the phone or is it one on scrcpy?

**Comment by rom1v** [comment]
What is the output in the console when you drag&drop a file to the scrcpy window?

**Comment by ajgringo619** [comment]
I'll have to try to recreate the exact message later (watching something on my phone for the next few hours). It basically complained that the directory I set in the command-line was read-only and the file could not be copied. I know the command-line switch works, because I changed the default to /sdcard/Download/ (my main memory) and it works perfectly. I just wanted to use the other device because it had so more more free space.

**Comment by ajgringo619** [comment]
OK, here's what I get when starting the command like this (2BA1-1BFA is the name of the microSD card):
`scrcpy --push-target=/2BA1-1BFA/Downloads/`

```
INFO: Request to push /home/me/Pictures/Bowazon_Skill_Tree.jpg
INFO: Pushing /home/me/Pictures/Bowazon_Skill_Tree.jpg...
adb: error: failed to copy '/home/me/Pictures/Bowazon_Skill_Tree.jpg' to '/2BA1-1BFA/Downloads/': remote secure_mkdirs failed: Read-only file system
/home/me/Pictures/Bowazon_Skill_...shed. 1.2 MB/s (62127 bytes in 0.049s)
ERROR: "adb push" returned with value 1
ERROR: Failed to push /home/me/Pictures/Bowazon_Skill_Tree.jpg to /2BA1-1BFA/Downloads/
```

Changing the directory makes no difference.

**Comment by rom1v** [comment]
I would be surprised if the microSD card was mounted in `/`. I would expect something under `/storage/` or something like that.

What is the result of:

    adb shell ls /2BA1-1BFA/

?

**Comment by ajgringo619** [comment]
You're guess was perfect! I added /storage/ in front of the directory and it works, with one caveat: there seems to be an issue with permissions, at least on Linux, if the file does not have the execute bit set. Here's the output of trying to copy over my .bashrc (0644):

```
INFO: Request to push /home/me/.bashrc
INFO: Pushing /home/summersd/.bashrc...
adb: error: failed to read all of '/home/me/.bashrc': Permission denied
/home/summersd/.bashrc: 0 files pushed.
ERROR: "adb push" returned with value 1
ERROR: Failed to push /home/me/.bashrc to /storage/2BA1-1BFA/Podcasts/
```

Tried the same thing with another file (0750), and it copied just fine.

UPDATE: just tried another test, this time with my local mail file (0600) and it worked. I think I've got this down to all files work, unless they're hidden by default (even if my File Explorer sees them just fine). This is not a big deal; glad the rest is working.

**Comment by rom1v** [comment]
Are you using the snap version? (which adds specific authorization restrictions)

**Comment by ajgringo619** [comment]
I thought this would be enough, but it's no big deal:
`snap connections scrcpy | grep home`
`home            scrcpy:home            :home`

I will close this for now; if I find something that makes the snap version work on every file under /home, then add another comment.
