### ISSUE TITLE
homebrew still at 1.13_1 but 1.14 has been released for almost a week

### ISSUE THREAD

**Issue by BartmanEH** [Genymobile/scrcpy#1464]
how do we get homebrew updated to 1.14?

**Comment by rom1v** [comment]
It seems homebrew provides v1.14: https://github.com/Homebrew/homebrew-core/blob/master/Formula/scrcpy.rb

**Comment by BartmanEH** [comment]
`brew info scrcpy` returns 1.13_1 but `brew outdated` returns nothing

**Comment by BartmanEH** [comment]
ugh, I did `brew upgrade scrcpy` and it's upgrading now... I don't know why that didn't work after multiple attempts last week.
