### ISSUE TITLE
support different adb servers

### ISSUE THREAD

**Issue by alonstern** [Genymobile/scrcpy#147]
add the ability to pass the adb server ip and port so this will also work with adb servers not only on localhost and 5037
Thanks :)

**Comment by rom1v** [comment]
I tag it as a feature request.

Meanwhile, as a workaround, you can set the `ADB` env variable to a custom script:

Here is `/usr/local/bin/myadb`:
```bash
#!/bin/sh
adb -P5038 "$@"
```
(make it executable)

```bash
ADB=/usr/local/bin/myadb scrcpy
```

(but not very convenient)

**Comment by rom1v** [comment]
Also see https://github.com/Genymobile/scrcpy/issues/144.
