### ISSUE TITLE
phone doesn't have earphone jack, how can I connect sound to pc?

### ISSUE THREAD

**Issue by srjbs11** [Genymobile/scrcpy#1471]
I heard that sound can be tranferred to pc using aux cable but just found that my galaxy note 10+ has no earphone hole..

how can I connect audio to pc in this case?

**Comment by rom1v** [comment]
> how can I connect audio to pc in this case?

Wait until audio forwarding is implemented (I don't know when) #14.
Or use some bluetooth transmitter/receiver.
