### ISSUE TITLE
full screen still has much empty space in all sides

### ISSUE THREAD

**Issue by srjbs11** [Genymobile/scrcpy#1473]
it supposed to be full of the screen when goes to full screen but there is still much empty space in all sides left, right, up and down

how can I make it fit really full of the screen?

**Comment by rom1v** [comment]
Could you post a screenshot please?

**Comment by srjbs11** [comment]
![image](https://user-images.githubusercontent.com/51525949/83808982-05a52d00-a6f9-11ea-9b3a-ca3f452560cf.png)

monitor size: 1920x1080
phone: galaxy note 10 plus 2280x1080

**Comment by rom1v** [comment]
I guess that the left and right black borders also appear on the device, right?

So to display the device screen at the correct aspect-ratio, scrcpy adds top and bottom black borders.

In other words, your device is correctly displayed fullscreen (from left to right), but your device screen contains black borders, which are mirrored.

**Comment by srjbs11** [comment]
if I buy bigger screen resolution monitor then it can mirror full 1920 width on the monitor right?

**Comment by rom1v** [comment]
The important parameter to avoid black borders is to have the same aspect ratio on the device and on the computer. Put your device in portrait mode, this is even more obvious.

**Comment by rom1v** [comment]
Note that you can [crop](https://github.com/Genymobile/scrcpy/blob/master/README.md#crop):

```bash
scrcpy --crop 1920:1080:180:0
```

**Comment by Peter2oo1** [comment]
> ![image](https://user-images.githubusercontent.com/51525949/83808982-05a52d00-a6f9-11ea-9b3a-ca3f452560cf.png)
> 
> monitor size: 1920x1080 phone: galaxy note 10 plus 2280x1080

That also happened to me, and Idk if it's only me but when I open the notification shade scrcpy shows the full screen, which confused me even more
