### ISSUE TITLE
How to turn off the function of "Ctrl + O" on the screen?

### ISSUE THREAD

**Issue by shanlanCoding** [Genymobile/scrcpy#1475]
How to turn off the function of "Ctrl + O" on the screen?

I want to turn off the screen when the video is playing on my phone so that I can hear the video. 

So I need to know how you do it.

Thank you for your reply.

**Comment by rom1v** [comment]
I'm not sure to understand the question.

Pressing `Ctrl`+`o` (or launching scrcpy with `--turn-screen-off`) turns the device screen off.

What is your scrcpy version? (why didn't you use the issue template?)

**Comment by shanlanCoding** [comment]
> I'm not sure to understand the question.
> 
> Pressing `Ctrl`+`o` (or launching scrcpy with `--turn-screen-off`) turns the device screen off.
> 
> What is your scrcpy version? (why didn't you use the issue template?)
How to realize the function of "Ctrl + O" to close the screen?
Is it a function that comes with the ADB tool?

**Comment by rom1v** [comment]
> How to realize the function of "Ctrl + O" to close the screen?

When scrcpy is running, press `Ctrl`, keep it pressed, and press `o`.

**Comment by shanlanCoding** [comment]
> > How to realize the function of "Ctrl + O" to close the screen?
> 
> When scrcpy is running, press `Ctrl`, keep it pressed, and press `o`.


I know what you mean. But my problem is how the code is implemented.

**Comment by shanlanCoding** [comment]
> > How to realize the function of "Ctrl + O" to close the screen?
> 
> When scrcpy is running, press `Ctrl`, keep it pressed, and press `o`.

how the "Turn device screen off" is impleated ?

this is my question. 

Thanks you.

**Comment by shanlanCoding** [comment]
> https://github.com/Genymobile/scrcpy/blob/0e4a6f462bcc628af00896eea38aa883d68acc88/server/src/main/java/com/genymobile/scrcpy/Controller.java#L118-L122
> 
> https://github.com/Genymobile/scrcpy/blob/0e4a6f462bcc628af00896eea38aa883d68acc88/server/src/main/java/com/genymobile/scrcpy/Device.java#L225
> 
> https://github.com/Genymobile/scrcpy/blob/0e4a6f462bcc628af00896eea38aa883d68acc88/server/src/main/java/com/genymobile/scrcpy/wrappers/SurfaceControl.java#L117-L133

Yes, thank you. I'll study it carefully.

**Comment by shanlanCoding** [comment]
Hi firend：
I tried to implement the function of "Ctrl + O", but it didn't work.
The program runs normally without error. Through debugging, hidden methods can be obtained. Where did I write wrong?
thank you.

![image](https://user-images.githubusercontent.com/44717382/83983308-ba408800-a95f-11ea-90a6-d296b2952254.png)

**Comment by shanlanCoding** [comment]
@rom1v Help me ，thank you .

**Comment by rom1v** [comment]
You probably can't do that from an app without system permissions. Check for `SecurityException` in your logs.

**Comment by shanlanCoding** [comment]
> You probably can't do that from an app without system permissions. Check for `SecurityException` in your logs.

You are right !
# logcat:
 >06-08 20:25:09.898   779   835 E SurfaceFlinger: Permission Denial: can't access SurfaceFlinger pid=19927, uid=10283

**Comment by brunoais** [comment]
@rom1v What does scrcpy do so it can run with system permissions?

**Comment by Leesoar** [comment]
Hello,

I am using this reflection to turn off the screen in the Android app, but it doesn't work.

I created a popup menu called "Turn-off Screen", after clicking and then executed this code:
`SurfaceControl.setDisplayPowerMode(SurfaceControl.getBuiltInDisplay(), SurfaceControl.POWER_MODE_OFF);`

logcat:
`xxx V/ViewRootImpl: debug enqueueInputEvent: event = MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=321.25812, y[0]=206.86533, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=3406074194, downTime=3406074194, deviceId=2, source=0x1002 },processImmediately = true,mProcessInputEventsScheduled = false, this = ViewRoot{fc54c40 PopupWindow:ad07b72,ident = 1}
xxx V/ViewRootImpl: debug enqueueInputEvent: event = MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=321.25812, y[0]=206.86533, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=3406074247, downTime=3406074194, deviceId=2, source=0x1002 },processImmediately = true,mProcessInputEventsScheduled = false, this = ViewRoot{fc54c40 PopupWindow:ad07b72,ident = 1}
xxx D/SettingsInterface:  from settings cache , name = sound_effects_enabled,  value = 0
xxx D/SurfaceControl: Gionee Suspend/Resume Flow Step 8 --> SurfaceControl  nativeSetDisplayPowerMode!!!
xxx D/OpenGLRenderer: ProgramCache.generateProgram: 1
xxx D/InputMethodManager: onPostViewType : no update
xxx V/InputMethodManager: onAmigoWindowFocus: androidx.recyclerview.widget.RecyclerView{818575e VFED..... .F.....D 18,0-1062,1776 #7f09004a app:id/app_list} softInputMode=16 first=false flags=#81810100
xxx V/AmigoInputMethodManager: onAmigoWindowFocus: androidx.recyclerview.widget.RecyclerView{818575e VFED..... .F.....D 18,0-1062,1776 #7f09004a app:id/app_list} softInputMode=16 first=false flags=#81810100
xxx D/Surface: Surface::disconnect(this=0x78b4bf8c00,api=1)
xxx D/OpenGLRenderer: endAllActiveAnimators on 0x78b3d82800 (MenuPopupWindow$MenuDropDownListView) with handle 0x78a6afd980
xxx D/WindowClient: Remove from mViews: android.widget.PopupWindow$PopupDecorView{c8d7bc3 V.E...... ......ID 0,0-588,432}, this = android.view.WindowManagerGlobal@1be68b0
`

**Comment by Leesoar** [comment]
Hello,

I am using this reflection to turn off the screen in the Android app, but it doesn't work.

I created a popup menu called "Turn-off Screen", after clicking and then executed this code:
`SurfaceControl.setDisplayPowerMode(SurfaceControl.getBuiltInDisplay(), SurfaceControl.POWER_MODE_OFF);`

logcat:
`xxx V/ViewRootImpl: debug enqueueInputEvent: event = MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=321.25812, y[0]=206.86533, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=3406074194, downTime=3406074194, deviceId=2, source=0x1002 },processImmediately = true,mProcessInputEventsScheduled = false, this = ViewRoot{fc54c40 PopupWindow:ad07b72,ident = 1}`
`xxx V/ViewRootImpl: debug enqueueInputEvent: event = MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=321.25812, y[0]=206.86533, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=3406074247, downTime=3406074194, deviceId=2, source=0x1002 },processImmediately = true,mProcessInputEventsScheduled = false, this = ViewRoot{fc54c40 PopupWindow:ad07b72,ident = 1}`
`xxx D/SettingsInterface:  from settings cache , name = sound_effects_enabled,  value = 0`
`xxx D/SurfaceControl: Gionee Suspend/Resume Flow Step 8 --> SurfaceControl  nativeSetDisplayPowerMode!!!`
`xxx D/OpenGLRenderer: ProgramCache.generateProgram: 1`
`xxx D/InputMethodManager: onPostViewType : no update`
`xxx V/InputMethodManager: onAmigoWindowFocus: androidx.recyclerview.widget.RecyclerView{818575e VFED..... .F.....D 18,0-1062,1776 #7f09004a app:id/app_list} softInputMode=16 first=false flags=#81810100`
`xxx V/AmigoInputMethodManager: onAmigoWindowFocus: androidx.recyclerview.widget.RecyclerView{818575e VFED..... .F.....D 18,0-1062,1776 #7f09004a app:id/app_list} softInputMode=16 first=false flags=#81810100`
`xxx D/Surface: Surface::disconnect(this=0x78b4bf8c00,api=1)`
`xxx D/OpenGLRenderer: endAllActiveAnimators on 0x78b3d82800 (MenuPopupWindow$MenuDropDownListView) with handle 0x78a6afd980`
`xxx D/WindowClient: Remove from mViews: android.widget.PopupWindow$PopupDecorView{c8d7bc3 V.E...... ......ID 0,0-588,432}, this = android.view.WindowManagerGlobal@1be68b0`

**Comment by Leesoar** [comment]
Hello,

I am using this reflection to turn off the screen in the Android app, but it doesn't work.

I created a popup menu called "Turn-off Screen", after clicking and then executed this code:
`SurfaceControl.setDisplayPowerMode(SurfaceControl.getBuiltInDisplay(), SurfaceControl.POWER_MODE_OFF);`

logcat:
`V/ViewRootImpl: debug enqueueInputEvent: event = MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=321.25812, y[0]=206.86533, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=3406074194, downTime=3406074194, deviceId=2, source=0x1002 },processImmediately = true,mProcessInputEventsScheduled = false, this = ViewRoot{fc54c40 PopupWindow:ad07b72,ident = 1}`

`V/ViewRootImpl: debug enqueueInputEvent: event = MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=321.25812, y[0]=206.86533, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=3406074247, downTime=3406074194, deviceId=2, source=0x1002 },processImmediately = true,mProcessInputEventsScheduled = false, this = ViewRoot{fc54c40 PopupWindow:ad07b72,ident = 1}`

`D/SettingsInterface:  from settings cache , name = sound_effects_enabled,  value = 0`

`D/SurfaceControl: Gionee Suspend/Resume Flow Step 8 --> SurfaceControl  nativeSetDisplayPowerMode!!!`

`D/OpenGLRenderer: ProgramCache.generateProgram: 1`

`D/InputMethodManager: onPostViewType : no update`

`V/InputMethodManager: onAmigoWindowFocus: androidx.recyclerview.widget.RecyclerView{818575e VFED..... .F.....D 18,0-1062,1776 #7f09004a app:id/app_list} softInputMode=16 first=false flags=#81810100`

`V/AmigoInputMethodManager: onAmigoWindowFocus: androidx.recyclerview.widget.RecyclerView{818575e VFED..... .F.....D 18,0-1062,1776 #7f09004a app:id/app_list} softInputMode=16 first=false flags=#81810100`

`D/Surface: Surface::disconnect(this=0x78b4bf8c00,api=1)`

`D/OpenGLRenderer: endAllActiveAnimators on 0x78b3d82800 (MenuPopupWindow$MenuDropDownListView) with handle 0x78a6afd980`

`D/WindowClient: Remove from mViews: android.widget.PopupWindow$PopupDecorView{c8d7bc3 V.E...... ......ID 0,0-588,432}, this = android.view.WindowManagerGlobal@1be68b0`

**Comment by Leesoar** [comment]
@rom1v please help, it didn't report anything wrong.

**Comment by rom1v** [comment]
From an Android app, it won't work.

**Comment by Leesoar** [comment]
thanks, I know "``` ", mainly I want you to see the separation clearly.

So is there any good way on the Android app to not lock the screen?

Thank you.
