### ISSUE TITLE
Launch with "No Console, Always awake, Screen off"

### ISSUE THREAD

**Issue by That1GuyTy** [Genymobile/scrcpy#1476]
Just as the title says, Is there a way to launch SCRCPY using the "No Console" launcher, and also have it run the "Always awake" and "Screen off" command?

**Comment by rom1v** [comment]
Create a bat file (`myscrcpy.bat`) containing:
```
scrcpy-noconsole -Sw
```

**Comment by That1GuyTy** [comment]
Thank you! I knew it was easy, just didn't realize how easy.
