### ISSUE TITLE
Question: what version of ADB is needed for 1.14?

### ISSUE THREAD

**Issue by herrenP** [Genymobile/scrcpy#1477]
Sorry to post a bug report when it's actually a question. I couldn't find where I could post a question. :)

In 1.14 you say:

> Upgrade platform-tools to 30.0.0 (adb) in Windows releases

Will I be able to use Scrcpy 1.14 with an older version of ADB? Say version 1.0.36? Unfortunately I have a need to use that version of ADB.

If not, should I stay at my current version of Scrcpy which is 1.12 or can I upgrade to 1.13?

**Comment by rom1v** [comment]
> Will I be able to use Scrcpy 1.14 with an older version of ADB? Say version 1.0.36? Unfortunately I have a need to use that version of ADB.

Yes, you can use the version you want.

Just replace `adb.exe` in the scrcpy folder, or set the environement variable `ADB=C:\path\to\your\adb.exe`.

**Comment by herrenP** [comment]
Thank you!
