### ISSUE TITLE
Can't connect after phone reboot

### ISSUE THREAD

**Issue by fireFerry** [Genymobile/scrcpy#1479]
Hello!

I want to use the wireless connection with adb over TCP to connect my phone so I connected my phone with USB, did `adb tcpip 5555` and unplugged my device and then with `adb connect ip:5555` I can connect to my device fine. But when I reboot my phone I'm no longer able to connect to it until I plug it into usb and to the tcpip thing again. Is there any way to not do this on every reboot?

**Comment by rom1v** [comment]
Not with root. It will probably be possible in Android 11.
