### ISSUE TITLE
No keyboard input on Android. Wired ADB

### ISSUE THREAD

**Issue by calumnious** [Genymobile/scrcpy#148]
What a great little app. Built & loving it. However I am having trouble getting any keyboard response on my phone. The mouse or trackpad work flawlessly. Here is an example of what spits out after I try to type a few letters, long-press any key, or CTRL-V content in.

**calum@calum-XPS-15-9530**:~$ scrcpy
265 KB/s (19038 bytes in 0.069s)
INFO: Initial texture: 1440x2880
**WARN: Unknown event type: 102
WARN: Unknown event type: 102
WARN: Unknown event type: 102
WARN: Unknown event type: 102
WARN: Unknown event type: 102
WARN: Unknown event type: 102
WARN: Unknown event type: 102
WARN: Unknown event type: 102
WARN: Unknown event type: 102
WARN: Unknown event type: 102
WARN: Unknown event type: 102
WARN: Unknown event type: 102
WARN: Unknown event type: 102
ERROR: Exception on thread Thread[Thread-1,5,main]
java.lang.IllegalStateException: Buffer full, call next() to consume
	at com.genymobile.scrcpy.ControlEventReader.readFrom(ControlEventReader.java:34)
	at com.genymobile.scrcpy.DesktopConnection.receiveControlEvent(DesktopConnection.java:74)
	at com.genymobile.scrcpy.EventController.handleEvent(EventController.java:70)
	at com.genymobile.scrcpy.EventController.control(EventController.java:65)
	at com.genymobile.scrcpy.Server$1.run(Server.java:34)
	at java.lang.Thread.run(Thread.java:764)**

I am a very inexperienced Linux/Terminal/ADB (and Git :disappointed: ) user, but I'm learning quick. If anyone has a solution, please break it down by commands.

**Comment by rom1v** [comment]
I think it may happen if you use a different version between the server and the client (typically, you use the server v1.1 with current `master` or `dev` branch). Is it the case?

**Comment by calumnious** [comment]
Aha! That mended it. My server v1.1 prebuilt binaries was installed over the old version of the client. [The CDX article about your app](https://www.cnx-software.com/2018/03/10/scrcpy-open-source-software-let-you-control-an-android-phone-via-a-windows-mac-os-or-linux-pc/) was what I followed to install it, but it calls for old targets. Should've came here for the latest readme. Fresh install with adjustments works beautifully. Thank you for the expeditious dev support, Romain! :smiley:
