### ISSUE TITLE
Some characters don't work

### ISSUE THREAD

**Issue by DerryPlaysXd** [Genymobile/scrcpy#1487]
Hi, I have already seen a thread #37 and my issue is simmilar. I still didn't find the solution though. The product works very well as expected and I thank you for that, but some characters don't work. I can write: ýáíé, but characters such as ěščřž don't.  SCRCPY writes: "Could not inject char u+017e". Is there a working solution for this? Thank you in advance! :)

**Comment by rom1v** [comment]
> I can write: ýáíé, but characters such as ěščřž don't. SCRCPY writes: "Could not inject char u+017e".

Yes, that's expected: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#special-characters-do-not-work

> Is there a working solution for this?

Not for now.
