### ISSUE TITLE
scrcpy + gnirehtet @ the same time?

### ISSUE THREAD

**Issue by nr1995** [Genymobile/scrcpy#1494]
Hey,
Sorry maybe this isn't the right place for this,
but how would I use scrcpy and gnirehtet at the same time?
Because I live in China now, gnirehtet is more of a godsend than you might realise,
but I'd really like to be able to use it from my computer screen.
I'm a bit of a noob though,
and it seems like you can't run two things like this at the same time.
Any help would be greatly appreciated.
Thanks!

**Comment by nr1995** [comment]
> > and it seems like you can't run two things like this at the same time.
> 
> Why not?
> 
> Btw, on the scrcpy screenshot in the README, you could see the "key" in the status bar: it's gnirehtet running ;-)

Oh... you're right.
I tried it again today and it's working.
Maybe the first time I already had an instance running or something,
it told me something like, “only one instance at a time allowed.”
No problem then.
Oh another thing I'd like to ask while I'm here.
KDE Connect on both my computer and phone can't see each other,
while I'm sharing a connection through gnirehtet.
Is there any easy way around this?

**Comment by rom1v** [comment]
> KDE Connect on both my computer and phone can't see each other,
> while I'm sharing a connection through gnirehtet.
> Is there any easy way around this?

That's expected, the device and the computer are not on the same network. There is no easy way around this AFAIK.

**Comment by nr1995** [comment]
> > KDE Connect on both my computer and phone can't see each other,
> > while I'm sharing a connection through gnirehtet.
> > Is there any easy way around this?
> 
> That's expected, the device and the computer are not on the same network. There is no easy way around this AFAIK.

Hmm... that's disappointing.
It seems kind of silly that KDE Connect can't just recognise that I'm physically plugged in
and handle all the data transfer like that, the same way scrcpy does.
Ah well.  I have my computer's VPN working seamlessly on my phone.  Can't complain.
