### ISSUE TITLE
Run the scrcpy directly in Android Studio

### ISSUE THREAD

**Issue by VenomVendor** [Genymobile/scrcpy#1498]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
&dash;

**Describe the solution you'd like**
Create scrcpy plugin for Android Studio that can run "**scrcpy window directly in Android Studio**". This is similar to newly introduced feature to "[Run the Android Emulator directly in Android Studio](https://androidstudio.googleblog.com/2020/04/android-studio-41-canary-8-available.html)"

**Describe alternatives you've considered**
`scrcpy --always-on-top`

**Additional context**
https://developer.android.com/studio/preview/features/#run-emulator-studio

<img src="https://developer.android.com/studio/preview/features/images/emulator-tool-window.gif" />

**Comment by radoyankov** [comment]
Could be an AS plugin.
 
https://github.com/Genymobile/scrcpy/issues/1073
This issue is about an external application using scrcpy's stream, which is kinda related. If anyone here has the skill/time it's probably possible.

**Comment by qaisbayabani** [comment]
what will be the price of this assignment? as already  https://github.com/qaisbayabani/SCRCPY-C-Sharp-Client is a gift for those who will spend more time to search converting H264 stream. i have checked it with java output and its working there too if you put an port listener at java you can receive 100% perfect movie at canvas. i will soon upload it.

**Comment by shripal17** [comment]
I have been working on the same, and have achieved it successfully, checkout https://github.com/shripal17/ScrcpyController

For installation and downloads, check the releases page

**Comment by Computr0n** [comment]
+1 for this request

**Comment by NishuTyagi2** [comment]
I don't know how to ask any question about scrcpy, pls copy it somewhere else where it should be.
I was able to mirror my mobile even without unzipping platform tools folder in window 10. Then what is the use of these extra files. And how to assign arrow keys in a game.

**Comment by rom1v** [comment]
> I don't know how to ask any question about scrcpy

A new issue, typically.

> I was able to mirror my mobile even without unzipping platform tools folder in window 10.

Yes, the Windows release .zip is sufficient.

> Then what is the use of these extra files. 

Why did you download the platform tools folder in the first place? It's not needed by scrcpy, `adb` and its dependencies are included.

> And how to assign arrow keys in a game.

Key arrows inject key arrows on the device. You can't map them. See #712

**Comment by NishuTyagi2** [comment]
THis is my starting on the github and you are my first one. I m impressed. you are quite active.

**Comment by dector** [comment]
This might be an awesome improvement! ❤️
