### ISSUE TITLE
windows 8 error

### ISSUE THREAD

**Issue by LauralHill** [Genymobile/scrcpy#150]
C:\oneplus>scrcpy-windows-v1.1\scrcpy.exe

This version of C:\oneplus\scrcpy-windows-v1.1\scrcpy.exe is not compatible with
 the version of Windows you're running. Check your computer's system information
 and then contact the software publisher.

**Comment by rom1v** [comment]
See https://github.com/Genymobile/scrcpy/issues/108.

Either build it manually for 32 bits, or wait for v1.2 :wink:

**Comment by LauralHill** [comment]
Ah, it's not clear from README.MD. I think I will attempt the recompile,
but I like living dangerously. 😁
