### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by zhoudaqiang** [Genymobile/scrcpy#1500]
Hi ,first i think scrcpy is a very good job.but i have some questions about scrcpy! below is:
what‘s  the function of pointerId and buttons （in Controller.java）when scrcpy create MotionEvent;
Can i alaway set pointerId=0 and buttons =0? or how we can understand it?Look forward to your favourable reply,thanks and best wishes!!

**Comment by rom1v** [comment]
`pointerId` is used to distinguish several pointers for multitouch (for example, if your computer has a touchscreen, you can use several fingers at the same time).

`buttons` gives the buttons state: https://developer.android.com/reference/android/view/MotionEvent#getButtonState()
For example, if you right-click and move, the `BUTTON_SECONDARY` bit will be set on the mouse event. It is converted/forwarded from the state received by SDL:

https://github.com/Genymobile/scrcpy/blob/3c0fc8f54f42bf6e7eca35b352a7d343749b65c4/app/src/event_converter.c#L155-L174
