### ISSUE TITLE
Any effect on Tethering Quotas?

### ISSUE THREAD

**Issue by cusco-travel-services** [Genymobile/scrcpy#1501]
Bonjour Romain,

This is not an issue but I could not find any other way to contact you.

Am I correct in thinking that by using **scrcpy** that I can circumvent restrictions on the use of Tethering?

The idea that I have is that I can view the Browser of my Cell Phone via my Laptop and download whatever files, I need to download, to the Cell Phone and then later transfer the files to my Laptop without using Tethering.

Merci beaucoup!, Michael.

**Comment by rom1v** [comment]
Scrcpy just mirrors the screen, everything you do occurs on the device, so yes your phone browser opens connections from the device.
