### ISSUE TITLE
Support for foreign diactric signs when typing

### ISSUE THREAD

**Issue by junglized** [Genymobile/scrcpy#1505]
Hello,

Thanks for such a great app! There is one thing which could be added though, if time and software/hardware limitations allow to: support for foreign diactric signs when typing, such as (in my case): ą, ć, ń, ó, ż, ź, ę, ł, etc. Whenever I try to type any of those I get "[server] WARN: Could not inject char..." error.

Thanks in advance, best regards, Dan.

**Comment by rom1v** [comment]
Yes, this is a known limitation: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#special-characters-do-not-work

See #37.

**Comment by junglized** [comment]
Ah, sorry, I missed it in the FAQ. Right, I'll live with that. App's qualities greatly outweights it's limitations. Thank you!
