### ISSUE TITLE
scrcpy is not working, I cant control only mirror

### ISSUE THREAD

**Issue by robindronath** [Genymobile/scrcpy#1508]
INFO: scrcpy 1.14 <https://github.com/Genymobile/scrcpy>
C:\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 31.1 MB/s (33142 bytes in 0.001s)
[server] INFO: Device: Xiaomi Redmi Note 4 (Android 7.0)
INFO: Created renderer: direct3d
INFO: Renderer: direct3d
INFO: Initial texture: 1080x1920
ERROR: SDL failed to get a vertex buffer for this Direct3D 9 rendering batch!
ERROR: Dropping back to a slower method.
ERROR: This might be a brief hiccup, but if performance is bad, this is probably why.
ERROR: This error will not be logged again for this renderer.

This is what cmd shows

**Comment by rom1v** [comment]
This "error" in unrelated (#1441).

See https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work
