### ISSUE TITLE
scrcpy won't show android device

### ISSUE THREAD

**Issue by gmakacap** [Genymobile/scrcpy#151]
hi sir,
Whenever i double click the scrcpy.exe it wont show anything i tried several times by just clicking on it but nothing happens.
![screenshot 1](https://user-images.githubusercontent.com/34020024/40248724-467c2f98-5aea-11e8-94ea-d848ee77291b.png)

I have installed adb drivers and my device is shown as authorized when typing **adb devices**.
I don;t know which error is stopping it to load....please help

**Comment by rom1v** [comment]
See [here](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#on-windows-i-have-no-output-in-the-console) to retrieve the output/error. This will help to know the issue.

**Comment by rom1v** [comment]
Any news?

**Comment by rom1v** [comment]
Please try v1.2.

**Comment by olbb** [comment]
Same problem here with v1.2
After
>scrcpy-server.jar: 1 file pushed. 1.4 MB/s (19342 bytes in 0.013s)
>INFO: Initial texture: 1440x2560
didn't show anything.

**Comment by rom1v** [comment]
Are you connected over USB or TCP?

What if you decrease the définition:

    scrcpy -m 1024

?

**Comment by rom1v** [comment]
If it still does not work, are there any relevant logs in `adb logcat`?

**Comment by olbb** [comment]
I'm use USB,
I try it with '-m 1024',but it does not work.
I fount something may be useful in log.

>06-01 02:55:27.916 18278 18278 E Surface : Could not create instance of Surface from IGraphicBufferProducer.
06-01 02:55:27.918 18278 18278 E Surface : java.lang.NullPointerException: Attempt to read from field 'boolean com.meizu.nightmode.MzNightModeManager.mHaveInit' on a null object reference
06-01 02:55:27.918 18278 18278 E Surface : 	at com.meizu.nightmode.MzNightModeManager.getDefault(MzNightModeManager.java:240)
06-01 02:55:27.918 18278 18278 E Surface : 	at android.graphics.Canvas.<init>(Canvas.java:2606)
06-01 02:55:27.918 18278 18278 E Surface : 	at android.view.Surface$CompatibleCanvas.<init>(Surface.java:595)
06-01 02:55:27.918 18278 18278 E Surface : 	at android.view.Surface.<init>(Surface.java:93)
06-01 02:55:27.918 18278 18278 E Surface : 	at android.media.MediaCodec.createInputSurface(Native Method)
06-01 02:55:27.918 18278 18278 E Surface : 	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:63)
06-01 02:55:27.918 18278 18278 E Surface : 	at com.genymobile.scrcpy.Server.scrcpy(Server.java:22)
06-01 02:55:27.918 18278 18278 E Surface : 	at com.genymobile.scrcpy.Server.main(Server.java:78)
06-01 02:55:27.918 18278 18278 E Surface : 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
06-01 02:55:27.918 18278 18278 E Surface : 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:308)
06-01 02:55:27.922   390   390 I BufferQueue: [unnamed-390-1524](this:0x75c4c1f000,id:1524,api:0,p:-1,c:-1) BufferQueue core=(390:/system/bin/surfaceflinger)

Seems the system has crashed.

**Comment by rom1v** [comment]
Does screen recording work:

    adb shell screenrecord /sdcard/test.mp4
    adb pull /sdcard/test.mp4

?

**Comment by olbb** [comment]
Yes, screenrecord is OK.
I got a test.mp4 with content after that.

**Comment by rom1v** [comment]
> 06-01 02:55:27.916 18278 18278 E Surface : Could not create instance of Surface from IGraphicBufferProducer.
> 06-01 02:55:27.918 18278 18278 E Surface : java.lang.NullPointerException: Attempt to read from field 'boolean com.meizu.nightmode.MzNightModeManager.mHaveInit' on a null object reference
> 06-01 02:55:27.918 18278 18278 E Surface : at com.meizu.nightmode.MzNightModeManager.getDefault(MzNightModeManager.java:240)
> 06-01 02:55:27.918 18278 18278 E Surface : at android.graphics.Canvas.(Canvas.java:2606)
> 06-01 02:55:27.918 18278 18278 E Surface : at android.view.Surface$CompatibleCanvas.(Surface.java:595)
> 06-01 02:55:27.918 18278 18278 E Surface : at android.view.Surface.(Surface.java:93)
> 06-01 02:55:27.918 18278 18278 E Surface : at android.media.MediaCodec.createInputSurface(Native Method)

It seems there is a bug in your ROM, related to some "night mode".

**Comment by olbb** [comment]
It seems the OS developer made a mistake lets the crash.

**Comment by olbb** [comment]
Yes,I will try to contact with the developer to resolve this problem, thank you.

**Comment by voloshanenko** [comment]
@olbb can you give me advice re issue? I recompiled scrcpy with your's patch and even install Flyme Lab + quickshortcut to Enable Night mode (not China firmware) .- but still receive null pointer error  (
https://github.com/Genymobile/scrcpy/issues/565

**Comment by olbb** [comment]
@voloshanenko This NPE is not the same problem I encountered. 
It seems like the developer made another mistake in international edition. 
I think you can try init the scrcpy in android's main thread, that maybe useful.

**Comment by voloshanenko** [comment]
@olbb you mean run main function inside main thread?

private static void scrcpy(Options options) throws IOException {
        final Device device = new Device(options);
        boolean tunnelForward = options.isTunnelForward();
        try (DesktopConnection connection = DesktopConnection.open(device, tunnelForward)) {
            ScreenEncoder screenEncoder = new ScreenEncoder(options.getSendFrameMeta(), options.getBitRate());

            Controller controller = new Controller(device, connection);

            // asynchronous
            startController(controller);
            startDeviceMessageSender(controller.getSender());

            try {
                // synchronous
                screenEncoder.streamScreen(device, connection.getVideoFd());
            } catch (IOException e) {
                // this is expected on close
                Ln.d("Screen streaming stopped");
            }
        }
    }

**Comment by olbb** [comment]
No, if you run this method in main thread, it will lead deadlock.
I am talking about the ''MediaCodec codec = createCodec()" method, which calls the "MediaCodec.createInputSurface" method and causes a null pointer exception.

**Comment by voloshanenko** [comment]
Got it.
So instead of 
                Surface surface = codec.createInputSurface();
use 

Handler handler = new Handler(Looper.getMainLooper());
handler.post(new Runnable() {
     public void run() {
          Surface surface = codec.createInputSurface();
     }
});

? but I hope in this I need to run all in same thread

**Comment by olbb** [comment]
You can create two handler, one is in main thread, and another is in other thread.
But this is troublesome and does not necessarily solve the problem.

I remember this question, I have feedback with the Meizu developers, they fixed it. 
It may not be a branch of the international version.
Then I faced another problem, which is https://github.com/olbb/scrcpy/issues/1.

**Comment by voloshanenko** [comment]
@olbb probably you remember at which point they fix it? At least Flyme version/revision?

then I will be able to extract diff from new firmware and patch old one (

**Comment by olbb** [comment]
Version after 19 Feb

**Comment by rom1v** [comment]
Could you try this (on v1.10), please? https://github.com/Genymobile/scrcpy/issues/921#issuecomment-552102176

**Comment by deadshot1301** [comment]
plz someone help me i am using realme 2 device . when i try to mirror my screen with scrcpy it detects my phone but mirroring window doesnt shows up. i tried same with samsung and it worked .

**Comment by rom1v** [comment]
@deadshot1301 Which version of scrcpy do you use?

**Comment by Tyny** [comment]
Disabling night mode and running `scrcpy -m 1024` fixed the issue for me, thanks!

**Comment by rom1v** [comment]
@Tyny Do you still have a problem with NightMode in v1.16?

**Comment by chamod-clw** [comment]
I can't be extracting file why

**Comment by j7507187-jpg** [comment]
@rom1v, Скачал вашу, программу не работает. Что делать?
