### ISSUE TITLE
how to update - Windows 10

### ISSUE THREAD

**Issue by piloro** [Genymobile/scrcpy#1510]
Hi,
I don't quite understand how to update: I downloaded the "scrcpy-win64-v1.14.zip" file... Now I just replace the content of the previous version's folder? 
Excuse me for the dumb question (and yes, this is a question, not a bug report: I don't know how to label it)

Thank you

**Comment by rom1v** [comment]
> Now I just replace the content of the previous version's folder?

Yes.

In general, just remove the old folder and extract the new one (old files may have been deleted in a newer release).

**Comment by piloro** [comment]
thank you.
