### ISSUE TITLE
usb connection keeps on disconnecting 

### ISSUE THREAD

**Issue by flawrrie** [Genymobile/scrcpy#1511]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
Test with another cable/USB port (#281 #283).

**Comment by rom1v** [comment]
Or try with a lower definition: https://github.com/Genymobile/scrcpy/issues/283#issuecomment-672939254

**Comment by PranshuTG** [comment]
I have a solution

Auto.bat

> :loop
> scrcpy
> goto loop

**Comment by PranshuTG** [comment]
you didn't close it?

**Comment by PranshuTG** [comment]
:-)

**Comment by cutebunnygaming10** [comment]
i keep having issues like these similar issue
