### ISSUE TITLE
Add option to prevent screensaver 

### ISSUE THREAD

**Issue by vaxul** [Genymobile/scrcpy#1514]
I first submitted this issue for [SideQuest](https://github.com/the-expanse/SideQuest/issues/576).

Like any other video media, when streaming my Oculus Quest headset to the PC, I would like to have an option to disable the screensaver (from Windows). At least in fullscreen mode.

This could be an option for users and integrators as well.

**Comment by rom1v** [comment]
There is already an issue (#1370) and a PR (#1502) that I should merge before the next release.

**Comment by vaxul** [comment]
Thanks.  Sorry I didn't found it. I looked for screensaver.

**Comment by rom1v** [comment]
Fixed by #1502.
