### ISSUE TITLE
how to keep it awake if the device is connected over TCP/IP 

### ISSUE THREAD

**Issue by BIGMONK** [Genymobile/scrcpy#1517]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [ Windows]
 - scrcpy version: 1.14
 - installation method:  Windows release
 - Android version: 10

**Describe the bug**
Really great application!! Small, fast, simple, functional!
No bug! 
I just want to  keep it awake when the device is connected over TCP/IP .
How ?

**Comment by rom1v** [comment]
> I just want to keep it awake when the device is connected over TCP/IP .
> How ?

Android does not provide such an option for that, so except sending a mouse (or keyboard) event every x seconds, there is no good solution.: (

**Comment by BIGMONK** [comment]
> > I just want to keep it awake when the device is connected over TCP/IP .
> > How ?
> 
> Android does not provide such an option for when the device is not plugged, so except sending a mouse (or keyboard) event every x seconds, there is no good solution. :(

Thanks
