### ISSUE TITLE
Mouse/Keyboard Doesn't Work

### ISSUE THREAD

**Issue by FurqanSaeed** [Genymobile/scrcpy#152]
Installed as instructed. New window opens and shows display of my phone Xiaomi Redmi Note 4 but mouse and keyboard not working. I use my mobile and it reflects on computer very efficiently but on computer can't use mouse/keyboard to control my phone.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-clicks-do-not-work ?

**Comment by FurqanSaeed** [comment]
Wow. Thanks buddy. Now its working great. Bundle of thanks for making such a useful app. You made my day. Great Job. Thanks again.

**Comment by mgt-lya** [comment]
Hi I have the same issue, the mouse can work but the keyboard can't.

**Comment by rom1v** [comment]
> Hi I have the same issue, the mouse can work but the keyboard can't.

If you run `scrcpy -Vverbose`, what is the output in the console when you press a key?

**Comment by mgt-lya** [comment]
Thank you for replying me, I'm a total beginner😭 
It says the ADB device founded
