### ISSUE TITLE
does not support more than 60fps

### ISSUE THREAD

**Issue by masterchiang** [Genymobile/scrcpy#1524]
although i add up the --max fps command.but it still work on 60fps.

but i can set less than 60fps,such 30 ,15,else.it seems not work over 60fps.

my pc monitor asus PG278QR,165HZ refresh rate

phone:iqoo neo3 ,144hz refresh rate,and set locked on this mode, android 10

hope next version can fix this problem, cause more and more high refresh rate phone need you support

**Comment by masterchiang** [comment]
i guest it may  a adapt problem

**Comment by rom1v** [comment]
What app do you run when you check the framerate?

One frame is sent every time the surface changes, no more. So if you run an app that renders at 60 fps, you'll get 60 fps. If you play a 25 fps video, you'll get 25 fps.

On my device, if you move quickly the notification menu, I get 90 fps:
```
INFO: Initial texture: 1440x3120
INFO: FPS counter started
INFO: 88 fps
INFO: 87 fps (+3 frames skipped)
INFO: 90 fps
INFO: 90 fps
INFO: 90 fps
INFO: 83 fps
INFO: 54 fps
INFO: 90 fps
INFO: 90 fps
INFO: 56 fps
INFO: 10 fps
INFO: 0 fps
INFO: 8 fps
INFO: 8 fps
INFO: 0 fps
```

**Comment by masterchiang** [comment]
> What app do you run when you check the framerate?
> 
> One frame is sent every time the surface changes, no more. So if you run an app that renders at 60 fps, you'll get 60 fps. If you play a 25 fps video, you'll get 25 fps.
> 
> On my device, if you move quickly the notification menu, I get 90 fps:
> 
> ```
> INFO: Initial texture: 1440x3120
> INFO: FPS counter started
> INFO: 88 fps
> INFO: 87 fps (+3 frames skipped)
> INFO: 90 fps
> INFO: 90 fps
> INFO: 90 fps
> INFO: 83 fps
> INFO: 54 fps
> INFO: 90 fps
> INFO: 90 fps
> INFO: 56 fps
> INFO: 10 fps
> INFO: 0 fps
> INFO: 8 fps
> INFO: 8 fps
> INFO: 0 fps
> ```

thanks you ,i has been found out the problem

**Comment by masterchiang** [comment]
Os software problem ,not the phone and scrcpy,

i had change another phone,iqoo neo 3 144hz to red magic 144hz
