### ISSUE TITLE
ERROR: SDL failed to get a vertex buffer for this Direct3D 9 rendering batch!

### ISSUE THREAD

**Issue by Eduardo499** [Genymobile/scrcpy#1526]
Quando o dispositivo aparece aparece ERRO: O SDL falhou ao obter um buffer de vértice para este lote de renderização do Direct3D 9!
Meu celular é um A30 e meu Sistema Operacional é Windows 10.

**Comment by rom1v** [comment]
Please post in English.

Duplicate of #1441.
