### ISSUE TITLE
Querying SCRCPY session in progress?

### ISSUE THREAD

**Issue by leaskovski** [Genymobile/scrcpy#153]
First off, thanks for this awesome app!  Its great!  The performance is brilliant!

Now for my question, is there a way to query if a SCRCPY session is in progress?

I would like to hook tasker up to detect that one is running and then set the screen brightness level to low, disable auto brightness and keep the screen on for longer.

**Comment by rom1v** [comment]
Why not simply run scrcpy from a script that set these values, start scrcpy, then restore the values back? (see discussion https://github.com/Genymobile/scrcpy/issues/96)

Otherwise, I don't know. `ps | grep app_process`, but may not be reliable.

**Comment by leaskovski** [comment]
Thanks.  You have pointed me to this:
https://github.com/Genymobile/scrcpy/issues/101#issuecomment-377455548

This gives me what I need.
