### ISSUE TITLE
performance factors

### ISSUE THREAD

**Issue by flyingduck234** [Genymobile/scrcpy#1537]
I wonder what are the factors that plays role in performance

In terms of  no of frames, resolution, bit rate and latency .

why does FHD resolution has more latency than 800? is it the cpu on mobile or desktop or its limited due to adb speed?

**Comment by rom1v** [comment]
It takes a bit more time to encode/decode a big video than a small one. And the bandwidth is also not the same (more data to transmit, to parse, etc).

So in practice, when mirroring in 1920×1080, the latency is about twice as high as when mirroring in 800×448: #646.

**Comment by flyingduck234** [comment]
Why does it take 2x more time to transmit FHD frame compared to 800?

Is it the CPU , GPU or code?

**Comment by rom1v** [comment]
I think the main latency increase is the encoder (on the device) and the hardware decoder (on the computer).

**Comment by flyingduck234** [comment]
How can we improve the encoder and decoder performance?

**Comment by rom1v** [comment]
Your encoder and decoder are probably hardware components (independent of CPU) dedicated to H.264 encoding/decoding.

The only possible ways to decrease latency is to decrease encoding complexity, by changing encoding parameters.

The most obvious are width and height, but you could play with others, especially profile/level. You could custom these options using `scrcpy --codec-options ...`. See `Advanced codec options` in [v1.14 highlights](https://github.com/Genymobile/scrcpy/releases/tag/v1.14).

**Comment by flyingduck234** [comment]
If it's independent of CPU and GPU the scrcpy struggles to maintain 60fps when there is a 3d application running on the device.

Also why does scrcpy is capped at 60fps? Why can't it go beyond 60 FPS?

Does usb 3.1  port on mobile improve performance compared to usb 2.0?

**Comment by rom1v** [comment]
> the scrcpy struggles to maintain 60fps when there is a 3d application running on the device.

The encoding is done on the device side. One frame is sent every time the surface changes, no more. So if you run an app that renders at 60 fps, you'll get 60 fps. If you play a 25 fps video, you'll get 25 fps.

If you don't get more than 60 fps, the device does not render more than 60 frames per second (many devices displays are limited to 60Hz).

https://github.com/Genymobile/scrcpy/issues/1524#issuecomment-646494736

> Does usb 3.1 port on mobile improve performance compared to usb 2.0?

No, the bandwidth of USB 2.0 is enough to transmit the video stream, it should not change anything.

**Comment by flyingduck234** [comment]
Thank you once again.
One final question , what can I do if I wanna achieve low latency without reducing resolution. Does high end chipset like sd865 helps?

**Comment by rom1v** [comment]
> Does high end chipset like sd865 helps?

High end chipsets are probably better (but they are "more" better on low definition).

> what can I do if I wanna achieve low latency without reducing resolution?

Did you try changing the profile/level? https://github.com/Genymobile/scrcpy/issues/1537#issuecomment-647964867

**Comment by masterchiang** [comment]
@rom1v @flyingduck234 



i think is a cpu performance no enough, not the usb2.0 cable bandwidth problem,. see my issue

[https://github.com/Genymobile/scrcpy/issues/1553](url)

**Comment by flyingduck234** [comment]
under right circumstances scrcpy can achieve very low latency. 
A high end chipset
A good computer
Try lowering resolution 

You should be seeing low latecy
