### ISSUE TITLE
Getting 'ERROR: Could not execute "adb push"'

### ISSUE THREAD

**Issue by MycroftHolmes1989** [Genymobile/scrcpy#154]
After successfully building and installing scrcpy, every time I try to run it, I get the error message `ERROR: Could not execute "adb push"`.

I have checked the adb server and tried to push scrcpy-server.jar to `/data/local/tmp` manually, and it worked. But still, I get the error message.

If it's of any help, I am using a Windows 10 x64 Professional and a Xiaomi Redmi Note 4 Snapdragon Variant running on unrooted MIUI (Nougat).

**Comment by rom1v** [comment]
How do you run it? Is `adb.exe` and the dll accessible from your `PATH` (or in the _scrcpy_ directory, like in the prebuilt archive)?

**Comment by fyormat** [comment]
Adb.exe should be in the scrcpy directory 

--
Securely sent with Tutanota.


27. May 2018 13:57 by notifications@github.com <mailto:notifications@github.com>:

**Comment by MycroftHolmes1989** [comment]
It is in the scrcpy directory.

**Comment by MycroftHolmes1989** [comment]
Using your prebuilt archive resolved the issue.
