### ISSUE TITLE
  segmentation fault

### ISSUE THREAD

**Issue by assscia** [Genymobile/scrcpy#1541]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by assscia** [comment]
通过cmd输入scrcpy 显示segmentation fault

**Comment by rom1v** [comment]
Please fill the issue template (which version, which os, which device...).

**Comment by rom1v** [comment]
#1414?

**Comment by assscia** [comment]
> [＃1414](https://github.com/Genymobile/scrcpy/issues/1414)吗？



> 请填写问题模板（哪个版本，哪个操作系统，哪个设备...）。

window10

**Comment by assscia** [comment]
> > [＃1414](https://github.com/Genymobile/scrcpy/issues/1414)吗？
> 
> > 请填写问题模板（哪个版本，其中操作系统，其中设备...）。
> 
> 窗口10

win10家庭版

**Comment by assscia** [comment]
> > [＃1414](https://github.com/Genymobile/scrcpy/issues/1414)吗？
> 
> > 请填写问题模板（哪个版本，其中操作系统，其中设备...）。
> 
> 窗口10

连接的手机是小米3s，之前可以投屏的，我把手机恢复了出厂设置

**Comment by npes87184** [comment]
Can you provide your console log here?

**Comment by assscia** [comment]
> 您可以在此处提供控制台日志吗？
抱歉，我尝试把文件删除然后到github重新下载，之后就没事了，我怀疑是我是环境配置问题
