### ISSUE TITLE
Increasing Video Quality On Windows

### ISSUE THREAD

**Issue by FreshPancakes** [Genymobile/scrcpy#1544]
Hi!

First off, I want to thank you for creating this code. I'm brand new to this and was able to get my Pixel 3 XL to show up on my Windows 10 PC! I downloaded scrcpy, connected my phone via usb-c and ran scrcpy.exe. 

Because I have no knowledge of coding and unsure how to modify any existing files, I was wondering how I can increase the video quality on my PC. Sometimes it looks great and then the quality will dip, it isn't consistent. Can someone point me in the right direction?

![SCRCPY Reference](https://user-images.githubusercontent.com/67448804/85814462-d774a500-b71a-11ea-83f0-f38755bf6076.png)

**Comment by rom1v** [comment]
The screenshot shows encoding artifacts. You could try to increase th ebitrate:

```
scrcpy -b16M
```

(default is 8M)

**Comment by FreshPancakes** [comment]
> 
> 
> The screenshot shows encoding compression artifacts. You could try to increase the bitrate:
> 
> ```
> scrcpy -b16M
> ```
> 
> (default is 8M)

Thanks for the reply! How do I adjust that code? I'm very new to this. Is there a program I need to modify that code?

**Comment by rom1v** [comment]
It's not code, just a command line parameter.

On Windows, press Windows+R, and type `cmd.exe`. It opens a terminal.

In that terminal, type `cd C:\the\path\to\your\scrcpy-win64` (adapt the path, depending on where you extracted the release), then press Enter.

Then type `scrcpy -b16M`, then press Enter.

**Comment by FreshPancakes** [comment]
> 
> 
> It's not code, just a command line parameter.
> 
> On Windows, press Windows+R, and type `cmd.exe`. It opens a terminal.
> 
> In that terminal, type `cd C:\the\path\to\your\scrcpy-win64` (adapt the path, depending on where you extracted the release), then press Enter.
> 
> Then type `scrcpy -b16M`, then press Enter.

Thank you! This worked perfectly. I appreciate your help.

**Comment by rom1v** [comment]
Note that you can create a file `myscrcpy.bat` in the scrcpy folder, containing:

```
scrcpy -b16M
```

Then you could just double-click on it from the file browser.
