### ISSUE TITLE
[question] how to run scrcpy without a cmd prompt

### ISSUE THREAD

**Issue by onichandame** [Genymobile/scrcpy#1546]
no matter how to start scrcpy, either by running `scrcpy.exe` from command prompt, or run `ScrCpy` from menu, a command prompt is always opended in addition to the main window.

It would be more user friendly if a *quite* mode where the command prompt is suppressed is available.

I have checked FAQ and searched in issues but cannot find a related discussion.

**Comment by rom1v** [comment]
Use `scrcpy-noconsole.exe`.

**Comment by onichandame** [comment]
@rom1v Thanks! `scrcpy-noconsole.exe` is exactly what I wanted.
