### ISSUE TITLE
Needs Info: connecting on tcpip

### ISSUE THREAD

**Issue by sajjadjaved01** [Genymobile/scrcpy#155]
I have connect my phone on network to Android Studio, & successfully deploy apk & other stuff.
But can u tell me the process how to connect it with scrcpy ....
`I appreciate you'r work, thanks for this awesome soft.`

**Comment by rom1v** [comment]
https://www.genymotion.com/blog/open-source-project-scrcpy-now-works-wirelessly/

**Comment by sajjadjaved01** [comment]
i can be able to connect with my device wireless via adb, when connected, i'm unable to launch scrcpy, not opening.
![image](https://user-images.githubusercontent.com/10374846/40609797-3a411990-6289-11e8-922e-271f17bf6478.png)

**Comment by rom1v** [comment]
OK, then it will probably work on `master`: https://github.com/Genymobile/scrcpy/issues/5#issuecomment-373721710

Either compile it yourself, or wait for the next release :wink:

**Comment by rom1v** [comment]
Should be fixed in v1.2.

Please reopen otherwise.
