### ISSUE TITLE
Cannot launch scrcpy on Debian 10

### ISSUE THREAD

**Issue by CrazyFinnGmbH** [Genymobile/scrcpy#1552]
I installed scrcpy with `apt-get install scrcpy` on linux Debian 10. (It's an new installation)
Everything worked but when Im trying to start `scrcpy` it just says this:

> INFO: scrcpy 1.14 <https://github.com/Genymobile/scrcpy>
stat: No such file or directory
ERROR: '/usr/local/share/scrcpy/scrcpy-server' does not exist or is not a regular file

The folder share does NOT contain a scrcpy/scrcpy-server folder/file. I reinstalled scrcpy but that did not help.
Thx for your help!

**Comment by rom1v** [comment]
```
which scrcpy
echo $SCRCPY_SERVER_PATH
```
