### ISSUE TITLE
Resolution lowers when any sort of animation is playing.

### ISSUE THREAD

**Issue by Bloknama** [Genymobile/scrcpy#1555]
I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md) and I have searched in existing issues (https://github.com/Genymobile/scrcpy/issues)).)

First of all, thank you for this great tool! This is really helpful! So... Thank you for this!

**Environment**
 - OS: Windows 10
 - scrcpy version: 1.14
 - installation method: prebuilt
 - device model: Infinix X603
 - Android version: 7

The problem is that the resolution noticeably lowers whenever some sort of animation is playing on the phone screen. Example: when opening folders, playing games, or changing to full-screen while watching video.

```
I do not know what a terminal output is (I have zero knowledge on this field). I assume that the cmd is what "Terminal" is referring to.

INFO: scrcpy 1.14 <https://github.com/Genymobile/scrcpy>
C:\adb\Scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 37.7 MB/s (33142 bytes in 0.001s)
[server] INFO: Device: Infinix Infinix X603 (Android 7.0)
INFO: Created renderer: direct3d
INFO: Renderer: direct3d
INFO: Initial texture: 1920x1080
ERROR: SDL failed to get a vertex buffer for this Direct3D 9 rendering batch!
ERROR: Dropping back to a slower method.
ERROR: This might be a brief hiccup, but if performance is bad, this is probably why.
ERROR: This error will not be logged again for this renderer.
```

**Comment by rom1v** [comment]
It's not the resolution, it's compression artefacts, more visible on fast motion 

Try to increase the bitrate:

     scrcpy -b20M

**Comment by Bloknama** [comment]
Ah... I see. Thank you for your answer! Speaking of which, I want to ask a question. Do I have to run the tool using cmd every time if I want to use the prebuilt scrcpy with the increased bitrate and reduced resolution?

**Comment by rom1v** [comment]
No, you can create a file `myscrcpy.bat`, containing:

```
scrcpy -b20m
```

and double-click on it.

**Comment by Bloknama** [comment]
Is there some kind of tutorial online where I could learn on how to make that .bat file? I'm sorry for the many questions. I really do not know my left or right in this field.

**Comment by SamiurRahman1** [comment]
> 
> 
> Is there some kind of tutorial online where I could learn on how to make that .bat file? I'm sorry for the many questions. I really do not know my left or right in this field.

just open a notepad file, write what ever you need to write and save it. Then assuming your file extension are not hidden, rename the file to "myfile.bat" . That would do the trick. If your file extension are hidden by default, just google how to unhide the file extension. Hope that helps. 

https://support.winzip.com/hc/en-us/articles/115011457948-How-to-configure-Windows-to-show-file-extensions-and-hidden-files

this link would give you a rough idea on how to unhide file extension.

**Comment by Bloknama** [comment]
Thank you very much! Thank you~!
