### ISSUE TITLE
MIUI12 opacity problem while casting with screen OFF/ON

### ISSUE THREAD

**Issue by shugo-chara** [Genymobile/scrcpy#1557]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Macos 10.15
 - scrcpy version: new
 - installation method: brew
 - device model: k20 pp MIUI12
 - Android version: 10

**Describe the bug**

I have a similar problem, but the difference is that I can't get around it with #1301 and #1306.

Entering the desktop with "Turn screen off" enabled doesn't show any icons. The difference is that all the icons are completely gone, and clicking on any area or sliding the desktop will have no effect. Closing the screen and opening it again won't fix it either. But other functions (notification bar, etc.) are still working.
Disable "Turn screen off" and it will be back to normal.

**Comment by rom1v** [comment]
> I have a similar problem, but the difference is that I can't get around it with #1301 and #1306.

Yes, that's the exact same problem, and there's nothing scrcpy can do about this (it's the device behavior): https://github.com/Genymobile/scrcpy/issues/1301#issuecomment-616318495
