### ISSUE TITLE
Can't install with apt install scrcpy

### ISSUE THREAD

**Issue by robert5800** [Genymobile/scrcpy#1558]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Elementary OS
 - scrcpy version: -
 - installation method: apt
 - device model: -
 - Android version: -

**Describe the bug**
I am trying to install scrcpy using apt, but it doesn't work.

```
Please paste terminal output in a code block.

$ sudo apt install scrcpy
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package scrcpy

```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
So Elementary OS does not provide the scrcpy package in their repositories.

You could [build](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md) manually.
