### ISSUE TITLE
ERROR: Could not execute "adb push"

### ISSUE THREAD

**Issue by Kaiju-A** [Genymobile/scrcpy#156]
scrcpy.exe does not open. instantly closes. this is ver1.2 32bit
would previously set environment variables for a older version affect anything

**Comment by rom1v** [comment]
Open `cmd.exe`, go to the `scrcpy` directory, and execute `scrcpy`. The app will close, but the console will stay, so that you will be able to read the output.

**Comment by Kaiju-A** [comment]
C:\Users\ADMIN\Desktop\scrcpy-win32-v1.2\scrcpy-win32>scrcpy
ERROR: Could not execute "adb push"

**Comment by rom1v** [comment]
What is the result of:

    adb devices

?

**Comment by Kaiju-A** [comment]
C:\Users\ADMIN\Desktop\scrcpy-win32-v1.2\scrcpy-win32>adb devices
List of devices attached
adb server version (32) doesn't match this client (39); killing...
* daemon started successfully
HT4C2WM02087    device


C:\Users\ADMIN\Desktop\scrcpy-win32-v1.2\scrcpy-win32>adb devices
List of devices attached
HT4C2WM02087    device

**Comment by rom1v** [comment]
> adb server version (32)

You have something else using an old adb version?

**Comment by Kaiju-A** [comment]
no, first time seeing it so i ran adb devices again

**Comment by rom1v** [comment]
And after a successful `adb devices`, the problem still occurs?

**Comment by Kaiju-A** [comment]
yes

**Comment by Kaiju-A** [comment]
found the problem.
there was conflicting environment variables.
fixed by deleting them.
