### ISSUE TITLE
Working great on Ubuntu 18.04LTS and Thank You!

### ISSUE THREAD

**Issue by valeriupredoi** [Genymobile/scrcpy#1563]
Hey guys, first off big thank you for putting this together!! I can now watch Formula 1 on my Linux computer with my Android phone streaming it (since I am using NowTV that has absolutely zero support for Linux and you need to install their annoying proprietary player, which I can only do on my Android phone; if you guys are from the UK you know what I'm on about :grin: ). So cheers again :beer: 

A few comments, if I may:
- I put together a short guide how to make it work (on Ubuntu 18.04LTS) [here](https://github.com/valeriupredoi/Android_to_Linux_Stream) if it's of any use to you;
- I would recommend telling your users to not even try installing it on older, unsupported OS's (see my last section in the guide I wrote) - it's not your package at fault but rather all the mess from having to manually upgrade old libraries; I managed to do it on Ubuntu 14.04LTS (`scrcpy` built from source) but it wasn't fun and I am a software engineer for my day job, others would probably shy away right away;

Anyhoo, feel free to close this (not an issue per-se, just a heads up) and keep up the great work! :beer:

**Comment by rom1v** [comment]
Glad you like it, thank you for your comment.

> I would recommend telling your users to not even try installing it on older

It's difficult to say where it will work easily and where newer packages will be required. But nobody should run Ubuntu 14.04 anymore (scrcpy or not), it's not supported :wink:

**Comment by nikhil-dabhade** [comment]
@valeriupredoi Good read. Any chance you documented steps for Ubuntu 14.04 ? That would be really helpful. We have a plan to upgrade but not until few months.
