### ISSUE TITLE
E: Unable to locate package scrcpy

### ISSUE THREAD

**Issue by cloningpc** [Genymobile/scrcpy#1566]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Kali linux (2020.2]
 - scrcpy version: []
 - installation method: [sudo apt-get install scrcpy]
 - device model:

**Describe the bug**
E: Unable to locate package scrcpy (kali 2020.2)

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package scrcpy
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
So Kali linux does not provide the scrcpy package in their repositories.

You could [build](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md) manually.
