### ISSUE TITLE
Chocolatey install script broken

### ISSUE THREAD

**Issue by SvbZ3r0** [Genymobile/scrcpy#1569]
**Environment**
 - OS: Windows
 - scrcpy version: 1.14.0, 1.13.0, haven't tested the others
 - installation method: Chocolatey

**The bug**
The Chocolatey install script fails as it is unable to download an icon file from https://www.iconfinder.com/icons/3185263/download/ico/512. The icon '3185263' does not currently exist on iconfinder.com.

**Console output**
```
C:\Users\{}>choco install scrcpy -y
Chocolatey v0.10.15
Installing the following packages:
scrcpy
By installing you accept licenses for the packages.
Progress: Downloading scrcpy 1.14.0... 100%

scrcpy v1.14.0 [Approved]
scrcpy package files install completed. Performing other installation steps.
Downloading scrcpy
  from 'https://github.com/Genymobile/scrcpy/releases/download/v1.14/scrcpy-win64-v1.14.zip'
Progress: 100% - Completed download of C:\Users\{}\AppData\Local\Temp\chocolatey\scrcpy\1.14.0\scrcpy-win64-v1.14.zip (21.68 MB).
Download of scrcpy-win64-v1.14.zip (21.68 MB) completed.
Hashes match.
Extracting C:\Users\{}\AppData\Local\Temp\chocolatey\scrcpy\1.14.0\scrcpy-win64-v1.14.zip to C:\ProgramData\chocolatey\lib\scrcpy\tools...
C:\ProgramData\chocolatey\lib\scrcpy\tools
Attempt to get headers for https://www.iconfinder.com/icons/3185263/download/ico/512 failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://www.iconfinder.com/icons/3185263/download/ico/512'. Exception calling
"GetResponse" with "0" argument(s): "The operation has timed out"
Downloading android.ico
  from 'https://www.iconfinder.com/icons/3185263/download/ico/512'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://www.iconfinder.com/icons/3185263/download/ico/512'. Exception calling "GetResponse" with "0" argument(s): "The operation has timed out"
This package is likely not broken for licensed users - see https://chocolatey.org/docs/features-private-cdn.
The install of scrcpy was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\scrcpy\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - scrcpy (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\scrcpy\tools\chocolateyinstall.ps1'.
 See log for details.

```

**Comment by rom1v** [comment]
Ref #1144 cc @equiman 

(should be reported to chocolatey instead)

**Comment by SvbZ3r0** [comment]
I'm sorry. How do I do that? I looked up their website and there's no way provided to report bugs about specific packages.

**Comment by rom1v** [comment]
(I don't know, I don't really know chocolatey)

**Comment by equiman** [comment]
Sorry, I just see it on Choco and add it to documentation, but I don't create his installation script.

**Comment by n3rd4i** [comment]
The original problem of this is that I could not find an `.ico` file for the application itself. Hence the choco installer downloads an android `.ico` from somewhere (resource which now does not exist anymore). 

I can fix/patch this in various ways:
1. loosen up the installer, if `.ico` download fails (for whatever reason), skip that and install anyway but there will be no `.ico`
2. download `.ico` from another valid location (ideally, from `scrcpy` original sources)
3. convert to `.ico` from `.png` with tools like png2ico (ideally, from `scrcpy` original sources)

Recommendations are welcome. Not sure what is best.
For now (quick fix), I'm just going to go with 3.
