### ISSUE TITLE
Scrcpy does not support non english keyboard input 

### ISSUE THREAD

**Issue by Modi34** [Genymobile/scrcpy#1570]
**Environment**
 - OS: macOS 10.15.5
 - scrcpy version: 1.14
 - installation method: brew
 - device model: skylake based hackintosh
 - Android version: 5.0.2

**Describe the bug**
When I type in english everything is ok but when I start typing in other languages (russian for example) scrcpy does not do anything

cmd+v also does not work for other langs
https://yadi.sk/d/ifAy2MZnVSiXZg - this a .gif preview

**Comment by Modi34** [comment]
just found out that I had https://play.google.com/store/apps/details?id=com.floriandraschbacher.deskdock.pro 
desk dock pro purchased years ago - it solves this issue for me

**Comment by tyePhDCandy** [comment]
Eh, this is hardly a solution. Maybe, it works but the issue should not be closed since solving it costs money.
