### ISSUE TITLE
When the screen is off, if the screen turns on from a command in the PC, order it to turn back off

### ISSUE THREAD

**Issue by brunoais** [Genymobile/scrcpy#1573]
**Is your feature request related to a problem? Please describe.**
Sometimes I get distracted by my phone when the screen turns back on and I'm working on it.
I have attention problems from flashing lights and moving things which atract me too much and the phone screen turning on and me having to act because of that is part of an issue to me.

**Describe the solution you'd like**

1. If these are true:
1.1 `Ctrl+o` or `--screen-off` (command line option) is more recent than `Ctrl+Shift+o`
1.2. A command is sent to the phone, through `scrcpy` that is known to turn the screen on.
1.3. The screen tries to turn on in the following X (maybe 5) seconds.
1.3.1. 1.1. is still true
---> Turn the screen back off ASAP

**Describe alternatives you've considered**
I tried to use an automation tool that detects right clicks and `Ctrl+p` on the desktop app but it works like a terrible hack. Sometimes the command goes too early, other times the second command is mixed together with something else I'm trying to do.
In those cases, I have already ended up giving orders for things I didn't mean to.

Extra:
I intent to implement this myself. It can also allow me to familiarize with these workings of android.
This issue is to confirm if I have green light for such feature in scrcpy

**Comment by rom1v** [comment]
> Sometimes I disconnect my phone from the PC and the screen if left off.

This is related to #1572, right?

> A command is sent to the phone that is known to turn the screen on.

You can't know, the user could press the physical power button for example.

Trying to work around the Android behavior, which is to reset the power mode to NORMAL when pressing the power button, with time-based heuristics looks very hacky/unreliable to me.

Ref: https://github.com/Genymobile/scrcpy/issues/618#issuecomment-504957990
Ref: #760

**Comment by brunoais** [comment]
> You can't know, the user could press the physical power button for example.
That is a problem outside the scope of this issue.
I guess I wasn't clear in the first comment, sorry. I'll try to change it.

**Comment by brunoais** [comment]
I just noticed the first part in this issue is the same as the other one. I think this was the automatic draft saving from the other issue and I was blinded from seeing it properly. I removed that part now.

**Comment by brunoais** [comment]
@rom1v Do you know any way to know whether the screen is on or off?
All ways I got to find can't detect the screen off by changing the screen power mode, which is how scrcpy.
Maybe whatever solution I get may not use that.

**Comment by rom1v** [comment]
Merged cf9d4497
