### ISSUE TITLE
'Stay awake' not working

### ISSUE THREAD

**Issue by wassupjg** [Genymobile/scrcpy#1579]
- OS: [macOS]
 - scrcpy version: [1.14]
 - installation method: [Homebrew]
 - device model: Xiaomi Mi A2 Lite
 - Android version: [9]

Hi, I connect wirelessly and while the program seems to work smoothly so far, the '--stay-awake' command doesn't appear to work; when running scrcpy using 'scrcpy -s 192.168.0.5:5555 -Sw -b2M -m800', the screen off, bit-rate and size commands all execute successfully, but the scrcpy window soon goes to sleep/black and I must right click wake and unlock the phone every time to continue.

Any way to keep the scrcpy window from going black? Appreciate any suggestions, thanks for a great program.

**Comment by rom1v** [comment]
#1445 

Unfortunately, Android only provides this option when the device is plugged in.

**Comment by stefanov-stefan** [comment]
scrcpy does not accept the stay-awake command. What I am doing wrong?

![image](https://user-images.githubusercontent.com/1288402/87392854-ecc04f00-c5b5-11ea-80ee-647c7f180586.png)

**Comment by rom1v** [comment]
@stefanov-stefan Just use the latest version.

**Comment by Riztard** [comment]
also can use the builtin caffein qs to keeping it on
just in case anyone need it
