### ISSUE TITLE
【scrcpy-win64-v1.2】Version 1.2 runs abnormally

### ISSUE THREAD

**Issue by feiser2016** [Genymobile/scrcpy#158]
Version 1.2 runs abnormally， but 1.1 runs ok

![default](https://user-images.githubusercontent.com/20484538/40694143-b032ff3c-63ed-11e8-81f9-077334466243.png)

**Comment by rom1v** [comment]
Could you translate the relevant text on the screenshot for me, please?

**Comment by rom1v** [comment]
OK, it seems your screenshot shows the Windows "program crash dialog" (https://img.raymond.cc/blog/wp-content/uploads/2009/08/program_has_stopped_working_error.png) (sorry, I am not familiar with Windows at all).

So, does it happen on every launch? Which version (Windows 10, 8… and 32 or 64 bits)?

**Comment by feiser2016** [comment]
yes. Every time it crashes. I use window 7 sp1 x86-64

**Comment by feiser2016** [comment]
问题事件名称:	BEX64
  应用程序名:	scrcpy.exe
  应用程序版本:	0.0.0.0
  应用程序时间戳:	5b0c67df
  故障模块名称:	StackHash_1dc2
  故障模块版本:	0.0.0.0
  故障模块时间戳:	00000000
  异常偏移:	0000000000000000
  异常代码:	c0000005
  异常数据:	0000000000000008
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	1dc2
  其他信息 2:	1dc22fb1de37d348f27e54dbb5278e7d
  其他信息 3:	eae3
  其他信息 4:	eae36a4b5ffb27c9d33117f4125a75c2

**Comment by rom1v** [comment]
OK, I suspect an incompatibility between your system and the prebuilt dll for ffmpeg/sdl.

Could you try [building it manually in MSYS2](https://github.com/Genymobile/scrcpy#in-msys2), so you won't use these prebuilt dll, please?

**Comment by feiser2016** [comment]
ok, i'll try it

**Comment by feiser2016** [comment]
I finally found the root cause.  it's the graphics card driver issue. After I update my video card drive, the problem solved.  thank you for your tools and your efforts.
