### ISSUE TITLE
adb: error: failed to get feature set: more than one device/emulator

### ISSUE THREAD

**Issue by AhmedKamalA** [Genymobile/scrcpy#1583]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**
IN case try to connect using wireless
On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste the terminal output in a code block.
```
INFO: scrcpy 1.14 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: more than one device/emulator
ERROR: "adb push" returned with value 1
Press any key to continue...
Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#several-devices-connected

**Comment by AhmedKamalA** [comment]
C:\Users\Family For Ever\Downloads\Compressed\Scrcpy\scrcpy-windows-v1.1>adb kill-server

C:\Users\Family For Ever\Downloads\Compressed\Scrcpy\scrcpy-windows-v1.1>adb devices
List of devices attached
* daemon not running; starting now at tcp:5037
* daemon started successfully


C:\Users\Family For Ever\Downloads\Compressed\Scrcpy\scrcpy-windows-v1.1>adb tcpip 9999
restarting in TCP mode port: 9999

C:\Users\Family For Ever\Downloads\Compressed\Scrcpy\scrcpy-windows-v1.1>scrcpy

C:\Users\Family For Ever\Downloads\Compressed\Scrcpy\scrcpy-windows-v1.1>adb connect 192.168.1.2:9999
connected to 192.168.1.2:9999

C:\Users\Family For Ever\Downloads\Compressed\Scrcpy\scrcpy-windows-v1.1>scrcpy

C:\Users\Family For Ever\Downloads\Compressed\Scrcpy\scrcpy-windows-v1.1>
in case of wifi not working 
please can you send your version files for scrcpy on any upload site to testing

**Comment by rom1v** [comment]
> `scrcpy-windows-v1.1`

v1.1 is more than 2 years old. Use the latest version.
