### ISSUE TITLE
how to go back to wired mirroring?

### ISSUE THREAD

**Issue by xJigs** [Genymobile/scrcpy#1586]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by xJigs** [comment]
how to go back to wired mirroring?

**Comment by rom1v** [comment]
What did you do? What is the result of `adb devices`?

Try `adb usb` (simple guess).

**Comment by xJigs** [comment]
ok thanks

**Comment by xJigs** [comment]
not working

**Comment by xJigs** [comment]
C:\Windows\system32>adb usb
error: more than one device/emulator

C:\Windows\system32>adb usb
error: more than one device/emulator

C:\Windows\system32>scrcpy
INFO: scrcpy 1.14 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: more than one device/emulator
ERROR: "adb push" returned with value 1
Press any key to continue...

**Comment by xJigs** [comment]
i mean im using adb now, but i want to go back to wired mirroring, its not working even if i restart my pc

**Comment by rom1v** [comment]
```
adb disconnect
```

**Comment by xJigs** [comment]
nevermind, i uninstall & install it again, already solve my problem, but thankyou rom1v

**Comment by rom1v** [comment]
The problem was just that you had two devices listed in `adb devices` (one over USB and one over wifi).

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#several-devices-connected
