### ISSUE TITLE
Exempt certain activities from showing.

### ISSUE THREAD

**Issue by qymspace** [Genymobile/scrcpy#159]
Is there a way to exempt an activity from showing.  
For example, I have an overlay in my phone that I don't want it showing in srcpy.

**Comment by rom1v** [comment]
No. For an app you develop, you can use [`FLAG_SECURE`](https://developer.android.com/reference/android/view/WindowManager.LayoutParams#FLAG_SECURE) (like [Silence](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#i-get-a-black-screen-for-some-applications-like-silence)).

**Comment by qymspace** [comment]
Thanks, Yes its for an app I own.  Will try that. 
So the overlay wont receive any click events and the events will pass on to the views below it?

**Comment by rom1v** [comment]
> So the overlay wont receive any click events and the events will pass on to the views below it?

No, I don't think so.
