### ISSUE TITLE
Screen not waking up

### ISSUE THREAD

**Issue by Fusseldieb** [Genymobile/scrcpy#1590]
Hi, I'm using a S10e running Stock Android 10 and the device won't wake up from sleep.
Please refer to the screenshot:

![image](https://user-images.githubusercontent.com/4715129/87298001-c92ad500-c4df-11ea-903e-1dcb4aec7735.png)

Btw, thanks for the awesome software!

**Comment by Fusseldieb** [comment]
Sorry I didn't do --help earlier!

The screen can be turned on using Ctrl+h.

**Comment by rom1v** [comment]
Ctrl+Shift+o only turns the screen on as the reverse of Ctrl+o (which keeps the device on but turns the physical  screen off).

Once the device is off, you need to power it on with Ctrl+p (power).
