### ISSUE TITLE
Screen No longer pop up

### ISSUE THREAD

**Issue by NickSei** [Genymobile/scrcpy#1591]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: windows
 - scrcpy version: 1.14
 - installation method: window
 - device model: oppo a3s
 - Android version: 8

**Describe the bug**
the screen no longer pops out after running.
```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
Does it work with v1.13?

Are there any errors in `adb logcat`?

_It might be a regression introduced by 62c0c1321feec0a673329cb6771efeefb6dc9657 (for initial issue #151)._

**Comment by NickSei** [comment]
[server] INFO: Device: OPPO CPH1803 (Android 8.1.0)
INFO: Created renderer: direct3d
INFO: Renderer: direct3d
INFO: Initial texture: 720x1520
ERROR: SDL failed to get a vertex buffer for this Direct3D 9 rendering batch!
ERROR: Dropping back to a slower method.
ERROR: This might be a brief hiccup, but if performance is bad, this is probably why.
ERROR: This error will not be logged again for this renderer. 

Help

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/issues/1591#issuecomment-657975170

**Comment by NickSei** [comment]
To solve my problem i delete the files in my drive and replace it with a new one.
