### ISSUE TITLE
Fail ffmpeg.so.56 on Ubuntu 20.04 

### ISSUE THREAD

**Issue by fbvictorhugo** [Genymobile/scrcpy#1595]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Ubuntu 20.04 64 bits
 - scrcpy version: last in apt
 - installation method: `apt install scrcpy`

**Describe the bug**
When executing the command `scrcpy` the error occurs as shown below.
_When ubuntu 16.04 worked normal, however in 20.04 with the recent version it doesn't work anymore._

```
USER:~$ scrcpy 
scrcpy: error while loading shared libraries: libavformat-ffmpeg.so.56: cannot open shared object file: No such file or directory

```

**Comment by rom1v** [comment]
Because you used a version compiled against libs in an old Ubuntu. You should delete/rebuild.

**Comment by fbvictorhugo** [comment]
I delete scrcpy:
`sudo apt remove scrcpy`

and instal again:
`sudo apt install scrcpy`

The error remains the same.

But I think `apt` installed version **1.12**
see the terminal: 
```
~$ sudo apt-get install scrcpy

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  scrcpy-server
The following NEW packages will be installed:
  scrcpy scrcpy-server
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 56,4 kB of archives.
After this operation, 132 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://archive.ubuntu.com/ubuntu focal/universe amd64 scrcpy-server all 1.12.1+ds-1 [27,0 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal/universe amd64 scrcpy amd64 1.12.1+ds-1 [29,4 kB]
Fetched 56,4 kB in 1s (46,3 kB/s)
Selecting previously unselected package scrcpy-server.
(Reading database ... 269770 files and directories currently installed.)
Preparing to unpack .../scrcpy-server_1.12.1+ds-1_all.deb ...
Unpacking scrcpy-server (1.12.1+ds-1) ...
Selecting previously unselected package scrcpy.
Preparing to unpack .../scrcpy_1.12.1+ds-1_amd64.deb ...
Unpacking scrcpy (1.12.1+ds-1) ...
Setting up scrcpy-server (1.12.1+ds-1) ...
Setting up scrcpy (1.12.1+ds-1) ...
Processing triggers for man-db (2.9.1-1) ...

```

**Comment by rom1v** [comment]
You probably have some binary in `/usr/local`.

```
which scrcpy
```

**Comment by fbvictorhugo** [comment]
**GREAT, that's works !**
Deleted the file and did it again.

Thanks! 

_but I still think apt is using version 1.12,_ 

```
~$ scrcpy 
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed. 5.2 MB/s (24773 bytes in 0.005s)
INFO: Initial texture: 720x1440
```
But it's working now!

**Comment by rom1v** [comment]
Yes, for the latest version, I suggest you [build](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md) from sources :)

Even better, if you could build from the version in #1598, then you could beta-test the future version and give feedbacks :)
