### ISSUE TITLE
"Show taps" does not work when controlling through scrcpy

### ISSUE THREAD

**Issue by hasansidd** [Genymobile/scrcpy#1599]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [macOS]
 - scrcpy version: [1.12.1]
 - installation method: [brew]
 - device model: Pixel 2xl, samsung s9+
 - Android version: [9, 10]

**Describe the bug**
In the past, when turning on "Show taps" in developer options, I was able to see my taps while controlling my phone with scrcpy. I have not noticed this for about a year now, but recently tried to do the same thing and the phone doesn't register scrcpy's clicks as tap events. If i use the actual touch screen I see the tap marker, but when using scrcpy, I do not.

**Comment by rom1v** [comment]
> In the past, when turning on "Show taps" in developer options, I was able to see my taps while controlling my phone with scrcpy.

Are you sure? It is not expected to work from scrcpy.

https://github.com/Genymobile/scrcpy#show-touches

> Note that it only shows physical touches (with the finger on the device).

It's an Android option, and for some reason it applies only on physical touches (not on injected events).

**Comment by hasansidd** [comment]
I see. I could have sworn it had worked in the past through scrcpy, but you know how memory can be. I assume nothing can be done about this to simulate physical touches? If so, feel free to close this issue and thanks for the prompt reply.

**Comment by rom1v** [comment]
> I assume nothing can be done about this to simulate physical touches?

Not that I am aware of. If someone find one easy way, we will implement it anyway, so I'm closing :)
