### ISSUE TITLE
screen recording command not working

### ISSUE THREAD

**Issue by GamerGeekNL** [Genymobile/scrcpy#1610]
So i installed scrcpy to record my phone screen because my phone itself doesnt have an option for that (i think atleast because i cant find it) and i typed in the screen recording command scrcpy --record file.mp4 but when i do that nothing happens. When i close scrcpy, i go to my folder with all my videos and nothing is in it. Can someone pls help?

**Comment by rom1v** [comment]
You must type these commands in a terminal.See https://github.com/Genymobile/scrcpy/issues/385#issuecomment-451903274
