### ISSUE TITLE
more than one device/emulator With Bluestacks and only one device connected to the host machine.

### ISSUE THREAD

**Issue by zFerry98** [Genymobile/scrcpy#1612]
- [y ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ y] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: 14
 - installation method: Windows release
 - device model: Galaxy S5 4g
 - Android version: LineageOS 16

**Describe the bug**
If bluestack is active, by connecting a real android phone, this error "more than one device / emulator" is displayed and I cannot specify which one to use. I have to copy the settings of an app from an android phone with a broken screen in bluestacks and I wanted to do everything from windwos, instead of using the broken phone.

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
INFO: scrcpy 1.14 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: more than one device/emulator
ERROR: "adb push" returned with value 1
Press any key to continue...
```

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#several-devices-connected

**Comment by zFerry98** [comment]
After a good bit of turnarounds he left, thanks anyway (the faq doesn't work I had to do more)
