### ISSUE TITLE
Long Press as right click

### ISSUE THREAD

**Issue by MichaelD45** [Genymobile/scrcpy#1613]
I'm controlling the google chrome remote desktop app on a galaxy note 4 running android 6 using scrcpy 1.14.  The remote desktop app on android mimicks a right click via a long press. The long press causes a rectangle to appear and on release the right click context menu on the remote computer becomes visible. When using scrcpy with mouse or touchpad a long click does not result in the rectangle and there doesn't seem to be a way for scrcpy to send the long press to the android phone that will make the google chrome remote desktop app display the windows right click context menu?

**Comment by MichaelD45** [comment]
Oh and thanks for making scrcpy!

**Comment by rom1v** [comment]
Does long press work in other contexts? (for example, long press on a text in your browser, it should select a word... or any other long press action in other contexts)

**Comment by MichaelD45** [comment]
Thanks for coming back. Yes. Long press works fine on a browser. Tried it on a word in the chrome browser on the phone as controlled by Scrcpy and a full word was selected fine. As a further test I connected a bluetooth mouse to my phone directly and tried a long press in the chrome remote desktop app . It presented the same problem - the long mouse left press did not generate the right click menu. I do get the right click menu in chrome remote desktop on the phone if I long press on the phone with my finger. Also checked with the s-pen and a long press will also open the right click context menu. So seems there is maybe a difference between a mouse long click and a finger long press in general? So I suppose this means to control chrome remote desktop on the phone with a mouse there needs to be a way for the mouse to mimick some subtelty of a long finger press which is signalled maybe slightly differently to holding down the left mouse button.

**Comment by MichaelD45** [comment]
Just a little more investigation here in case this helps.
Working only in chrome remote desktop directly on phone with finger it
seems when I long press the chrome app - Recognises a  press with circular
notif at finger. This then changes to a rectangle and stays as rectangle.
When finger released then rectange disappears and context menu appears.

Working with laptop and scrcpy using my touch sensitive screen on laptop
with chrome remote desktop: long finger press on laptop screen Recognises
a  press with circular notif at finger. This then changes to a rectangle
and stays as rectangle. When finger released then rectangle disappears but
NO context menu appears.

Working with laptop and scrcpy using mouse on laptop with chrome remote
desktop: long  press on mouse left button - screen recognises a  press with
circular notif at finger. This then fades away. No rectangle.  NO context
menu appears.

**Comment by rom1v** [comment]
@xcjs #1302

**Comment by rom1v** [comment]
@xcjs https://github.com/Genymobile/scrcpy/issues/1302#issuecomment-692951693

**Comment by rom1v** [comment]
I've just implemented an option: https://github.com/Genymobile/scrcpy/issues/1302#issuecomment-703822889

Could you please test it?

**Comment by rom1v** [comment]
Merged into `dev`: adc547fa6e8e6167cd9633a97d98de6665b8c23a.

**Comment by luke-jr** [comment]
Many apps don't work with a literal forwarded right-click action. Would it be possible to have actually simulating the longpress be an option? I wonder if it could be as simple as "backdating" the downTime parameter to MotionEvent.obtain...

**Comment by DanEdens** [comment]
> 

I actually love scrcpy because it does exactly that.. toggle option please if you change it!
