### ISSUE TITLE
sudden scrcpy closes

### ISSUE THREAD

**Issue by teja14312** [Genymobile/scrcpy#1616]
**Environment**
 - OS: Windows
 - scrcpy version: 1.14
 - installation method: manual
 - device model: one plus 3t
 - Android version: 9

Actually using scrcpy for a while now but it seems to have an issue, out of nowhere it closes the mirroring window when I minimized and only the cmd prompt was available.

After closing it says like this:
INFO: scrcpy 1.14 <https://github.com/Genymobile/scrcpy>
C:\adb\scrcpy-server: 1 file pushed, 0 skipped. 29.0 MB/s (33142 bytes in 0.001s)
[server] INFO: Device: OnePlus ONEPLUS A3003 (Android 9)
INFO: Created renderer: direct3d
INFO: Renderer: direct3d
INFO: Initial texture: 1080x1920
ERROR: SDL failed to get a vertex buffer for this Direct3D 9 rendering batch!
ERROR: Dropping back to a slower method.
ERROR: This might be a brief hiccup, but if performance is bad, this is probably why.
ERROR: This error will not be logged again for this renderer.
[server] INFO: Device screen turned off
WARN: Device disconnected
Press any key to continue...

**Comment by rom1v** [comment]
>     WARN: Device disconnected

The device is disconnected from adb.

If that happens while the device is still correctly plugged, you should try with another USB cable or USB port (see #281 #283).
