### ISSUE TITLE
System Error on windows 10

### ISSUE THREAD

**Issue by Omi231** [Genymobile/scrcpy#1617]
- [* ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ *] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows]
 - scrcpy version: [e.g. 1.4.1]
 - installation method: [Windows release]
 - device model: Realme 5
 - Android version: [9]

**Describe the bug**
When i double click to open start QtScrcpy.exe i am getting this error:

![image](https://user-images.githubusercontent.com/44071105/88328533-03973c00-cd42-11ea-895e-ed2d519923b4.png)

**Comment by rom1v** [comment]
Hi,

QtScrcpy is another independant project (based on scrcpy). Please report/ask to them.

**Comment by rom1v** [comment]
#612 cc @barry-ran

**Comment by yateendra** [comment]
same error here
