### ISSUE TITLE
Touch working without click when make full screen

### ISSUE THREAD

**Issue by Izar111** [Genymobile/scrcpy#162]
When I make scrcpy full screen by double click title bar, touch is working once under mouse with no click.

Enviroment is  Window10 x64, android 5pin.
Video link : [https://drive.google.com/file/d/1mCEHBE6QeHa-HxHd4hghD-7nr71bCBXU/view](https://drive.google.com/file/d/1mCEHBE6QeHa-HxHd4hghD-7nr71bCBXU/view)

**Comment by rom1v** [comment]
Thank you for your report.

I already observed similar behavior on X11 (linux), SDL sometime sends unexpected clicks or key events.

IMO this is a SDL problem (but it still results in a bug in _scrcpy_).

**Comment by Izar111** [comment]
I think about this problem in a week. 
Maybe it can be solved by doing not react while window size change.

Can you check this??

**Comment by rom1v** [comment]
I think it does not happen for me anymore, so I'm closing. Feel free to reopen if it still happens.
