### ISSUE TITLE
Trying to send custom touch commands through your server

### ISSUE THREAD

**Issue by rxydenxd** [Genymobile/scrcpy#1622]
When I type `adb shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 0 8000000 true` using platform-tools  , `Aborted` gets displayed? How can I make it work?

Thanks.

**Comment by rom1v** [comment]
Why removing the content? Just keep it and add a reference to the anwser yoj (probably) found in another issue?
