### ISSUE TITLE
I can't record video to my PC (Windows 10)

### ISSUE THREAD

**Issue by Icarus3000** [Genymobile/scrcpy#1627]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - Windows 10
 - scrcpy version: 1.14
 - installation method: windows release
 - device model: Google Pixel 2 XL
 - Android version: 11 Beta 2.5 (but had same issue running Android 10)

**Describe the bug**
I can't record video.  I get these errors:

```
C:\Program Files\scrcpy>scrcpy --record file.mp4
INFO: scrcpy 1.14 <https://github.com/Genymobile/scrcpy>
C:\Program Files\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 4.1 MB/s (33142 bytes in 0.008s)
[server] INFO: Device: Google Pixel 2 XL (Android 11)
ERROR: Failed to open output file: file.mp4
ERROR: Could not open recorder
INFO: Created renderer: direct3d
INFO: Renderer: direct3d
INFO: Initial texture: 1440x2880
WARN: Device disconnected
```

**Comment by rom1v** [comment]
> ERROR: Failed to open output file: file.mp4

Do you have write access to `C:\Program Files\scrcpy`? Try to create some file here (without scrcpy).

Use a path you have write access.

**Comment by Icarus3000** [comment]
That was an easy fix! Thank you
