### ISSUE TITLE
SMN950(samsung galaxy note 8), AOD and backscreen error

### ISSUE THREAD

**Issue by LYHyoung** [Genymobile/scrcpy#163]
I'm using the SMN950(samsung galaxy note 8). When I entered the app menu, I found an error in the backscreen that couldn't copy the backscreen. Also, the aod screen was not displayed.

AOD problem:
![kakaotalk_20180531_154848336](https://user-images.githubusercontent.com/37611500/40766369-34b00aaa-64ea-11e8-8b18-9b39afec5e70.jpg)

![kakaotalk_20180531_154650511](https://user-images.githubusercontent.com/37611500/40766363-31cb770c-64ea-11e8-9add-5cfcec0f71f3.jpg)

backscreen problem:
[https://drive.google.com/file/d/1UXNQmoU7aO7dNMUt67VMqWYq6nyTVcgr/view?usp=drivesdk](https://drive.google.com/file/d/1UXNQmoU7aO7dNMUt67VMqWYq6nyTVcgr/view?usp=drivesdk)

**Comment by rom1v** [comment]
Probably https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#i-get-a-black-screen-for-some-applications-like-silence

**Comment by LYHyoung** [comment]
Those phones have same os, same UI(samsung experience 9.0). But the phone at the bottom can display the screen. Does this matter with the phone itself?

**Comment by LYHyoung** [comment]
I've tried your solution, but it failed. T.T
