### ISSUE TITLE
After the control socket is established, how to make the server recognize the sent ADB command?

### ISSUE THREAD

**Issue by Helaer** [Genymobile/scrcpy#1631]
I have set up the scrcpy-server control socket, but after sending the ADB command, it shows: [server] WARN: Unknown event type: 49, what should I do to make the server recognize my ADB command?

**Comment by Helaer** [comment]
Command line return information: [server] WARN: Unknown event type: 49

**Comment by rom1v** [comment]
_Please don't open a new issue every time, continue on #1625._

You must serialize events exactly the same way as scrcpy does:

https://github.com/Genymobile/scrcpy/blob/master/app/src/control_msg.chttps://github.com/Genymobile/scrcpy/blob/master/app/tests/test_control_msg_serialize.c

**Comment by rxydenxd** [comment]
@Helaer any updates?
