### ISSUE TITLE
Pause and resume screen mirroring using a shortcut

### ISSUE THREAD

**Issue by AlyMoh** [Genymobile/scrcpy#1632]
- [X] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
Oftentimes, I find myself wanting to take a temporary screenshot of the tablet display to work with something I've written on my tablet, such as notes or annotations. However, it seems apparent to me that such a feature currently does not exist.

**Describe the solution you'd like**
It would be great if there was a *shortcut that "freezes" the current display of the Android device, i.e. pauses mirroring. When entering the shortcut again, mirroring would be resumed*.

**Describe alternatives you've considered**
As mentioned above, taking temporary screenshots seemed to be the most feasible, yet cumbersome, alternative. Soon enough, there's a bunch of clutter on disk due to the several screenshots that one could take for temporary use only to delete them afterwards, which is, quite frankly, a banal task.

Once _could_ simply record whatever notes one may use, but this would not take into account any content that comes to mind after recording. Furthermore, the issue of removing the recording when done still stands analogously to deleting temporary screenshots.

**Additional context**
I'm not sure if additional context is warranted, as I believe the above explanation was pretty sufficient. However, further discussion on the matter is more than welcome. If this feature request has already been suggested before (despite my best efforts in looking for a similar one) then a link to it would be greatly appreciated.

**Comment by rom1v** [comment]
Yes, why not. Would you like to work on it?

**Comment by AlyMoh** [comment]
Sure. I haven't worked with C in a while (although Java is no big deal for me) and due to increasing work and stress, it may take me a while before I understand the code enough to start working on the feature request.

**Comment by rom1v** [comment]
> it may take me a while before I understand the code enough to start working on the feature request.

Basically, the texture must not be updated when pause is enabled:

https://github.com/Genymobile/scrcpy/blob/0870d8620f327768249214a5ba6a7bee7a8a75ec/app/src/screen.c#L443-L444

Instead, if paused is enabled, the last `AVFrame` must be kept (and `av_frame_ref`-ed), until pause is disabled (in that case, the texture must be updated with the last `AVFrame`, which can be discarded).

**Comment by Zockerzimmer** [comment]
Even simpler than holding the last frame you could keep a black frame till you continue i guess. Waiting on that feature as well.

**Comment by psychowood** [comment]
Just my 2 cents, probably disabling the streaming from the server could be more network/energy efficient

**Comment by ttschnz** [comment]
Is there any progress on this?

I'd really like this feature. I would, however veto @Zockerzimmer on the black frame: For me the primary use-cases would be using this to "extend" the screen of my tablet, i.e. scroll to  a part in a pdf, freeze, scroll to a different part and still have the first part on my laptops screen.

If @AlyMoh won't be doing it any time soon, maybe I could have a look at it?
I should generally be fine with C, and as far as I've seen the changes would be made on the client-side?

**Comment by rom1v** [comment]
> For me the primary use-cases would be using this to "extend" the screen of my tablet, i.e. scroll to a part in a pdf, freeze, scroll to a different part and still have the first part on my laptops screen.

I like the use case. I implemented a shortcut to pause/unpause the display (<kbd>MOD</kbd>+<kbd>Shift</kbd>+<kbd>p</kbd>, because <kbd>MOD</kbd>+<kbd>p</kbd> was already used for POWER): #4748 

It only impacts rendering, the device is still captured, the video stream transmitted to the device, and recorded (if recording is enabled).

One benefit is that "unpausing" is instantaneous.

> maybe I could have a look at it?
> I should generally be fine with C, and as far as I've seen the changes would be made on the client-side?

I'm very sorry, I read the message quickly from my phone, I liked the use case and implemented it. I did not read the message until the end, I would have let you implement it :disappointed:

**Comment by ttschnz** [comment]
I've quickly tested it and I am convinced!

Two things that could be discussed:
- Interaction: During pause, I can still (blindly) control the screen with mouse and keyboard. Is this a feature or a bug?
- Shortcut: Personally, I'd choose <kbd>mod</kbd>+<kbd>space</kbd>, but your choice makes sense too.

**Comment by rom1v** [comment]
Thank you for your tests.

> Interaction: During pause, I can still (blindly) control the screen with mouse and keyboard. Is this a feature or a bug?

Bug. I disabled the shortcuts interacting with the device during pause, but forgot to disable mouse and keyboard 🤦 (I haven't tested intensively :wink:)

> Shortcut: Personally, I'd choose mod+space, but your choice makes sense too.

MOD+space may conflict with other OS or Android shortcuts (e.g. to change the keyboard layout).
