### ISSUE TITLE
Port Numbers

### ISSUE THREAD

**Issue by keya-s** [Genymobile/scrcpy#1635]
Hi! Sorry if this sounds like a dumb issue, but I am not very well-versed with command prompts and things. I have been using scrcpy for casting from multiple Oculus Go's for an art-performance. So far we haven't had too many issues but I was wondering about the port number that's suggested to use on most scrcpy guides/info pages: 5555. What exactly does this common/general port number do? Since we are using multiple computers and multiple headsets at once and we'd like to stay connected to all of them for 8-9 hours continuously, is it helpful to switch port numbers on the different computers? I just want to understand if it would affect the performance of the stream in any way.

**Comment by rom1v** [comment]
> I was wondering about the port number that's suggested to use on most scrcpy guides/info pages: 5555.

It's the port documented in the official doc:
https://developer.android.com/studio/command-line/adb#wireless

and it used to be the default one on `adb connect` when none was specified.

> is it helpful to switch port numbers on the different computers?

No. Each device will have a different IP address anyway.

> I just want to understand if it would affect the performance of the stream in any way.

No.

However, I'm not sure your wifi network will be sufficient to support several dcrcpy instances without lag :/ (sometimes, even only one device does not work well without reducing bitrate). Of course, USB would be better for performance.
