### ISSUE TITLE
Cannot open the file when click scrcpy-noconsole

### ISSUE THREAD

**Issue by chrstiangio** [Genymobile/scrcpy#1637]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: windows 10
 - scrcpy version: 1.14
 - installation method: download - install
 - device model: Huawei Nova 3i
 - Android version: EMUI 9.10.296

**Describe the bug**
cannot open the file when click scrcpy-noconsole, then try with scrcpy then they open cmd windows
''INFO: scrcpy 1.14 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: no devices/emulators found
ERROR: "adb push" returned with value 1
Press any key to continue...''

please how to solve this, i need to stream my phone to pc.

thankyou

chrstiangio

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#adb-issues

**Comment by chrstiangio** [comment]
thanks, what is path?

it is still not solved, then i repair the adb and doing the usb debugging after i plug in the usb. the scrcpy-nonconsole still not open, But it gives another problem when open using scrcpy with result=

**Describe the bug**
"INFO: scrcpy 1.14 <https://github.com/Genymobile/scrcpy>
adb server version (36) doesn't match this client (41); killing...
* daemon started successfully
C:\Users\KOMPUTER\Downloads\scrcpy-win64-v1.14\scrcpy-serv... file pushed, 0 skipped. 52.2 MB/s (33142 bytes in 0.001s)
[server] INFO: Device: HUAWEI INE-LX2 (Android 9)
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1967)
        at android.media.MediaCodec.configure(MediaCodec.java:1896)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:205)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:84)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
        at com.genymobile.scrcpy.Server.main(Server.java:225)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:371)
[server] ERROR: The hardware encoder is not able to encode at the given definition.
[server] ERROR: Try with a lower definition:
[server] ERROR:     scrcpy -m 1024
Exit due to uncaughtException in main thread:
INFO: Created renderer: direct3d
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2336
WARN: Device disconnected
Press any key to continue..."

need your help sir.

thankyou Mr Rom1v

chrstiangio

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception
