### ISSUE TITLE
[windows] Black screen when minimize

### ISSUE THREAD

**Issue by luanfernandes** [Genymobile/scrcpy#164]
Hi! First, of all, I love this! I'm using it to stream my games (and gnirehtet) to twitch and it's the best solution so far. I just need it to keep capturing the game when I minimize the window (black when full screen, frozen when window mode), which now turns black. Any workaround or implementation coming? 
Thanks!

**Comment by rom1v** [comment]
Hmmm. I'm not sure I understand what you observe.

Could you make a video of the problem, please? What is your OS (Windows, Linux…)?

**Comment by luanfernandes** [comment]
Sorry, I'm on Windows 10 (April update) and OBS (open broadcast software) Window Capture to stream. I'm not sure how I'm gonna record it to you, since I'm both using my phone and PC to showcase the problem, will return here if I find a way.

**Comment by rom1v** [comment]
How to reproduce? Just start scrcpy on Windows and minimize then "unminimize"?

**Comment by luanfernandes** [comment]
Capture the window with OBS so you can see it happen. Then either minimize while in window mode or alt+tab while in fullscreen mode, You will see that the capture will either freeze or black out

**Comment by rom1v** [comment]
> You will see that the capture will either freeze or black out

Does _scrcpy_ freeze/blackout, or _OBS_?

If OBS freezes, it seems to be a bug in OBS, doesn't it?

**Comment by luanfernandes** [comment]
[https://www.youtube.com/watch?v=aYCxJ0uMGVk](https://www.youtube.com/watch?v=aYCxJ0uMGVk)

**Comment by rom1v** [comment]
Thank you for the video.

What if you do the same with a video player instead of _scrcpy_ (capture and minimize VLC for example)?

**Comment by luanfernandes** [comment]
With VLC, if I use fullscreen I can alt-tab and it wont turn black but if I
minimize while windowed it will freeze yes. There's something called
windowed full screen, it probably use this 'feature'. I'm actually using
'borderless gaming' which is a open-source software to make any window
borderless fullscreen. Just remembered it. Anyways, hopefully you can
implement it on code some day :)
You can close this if you want
