### ISSUE TITLE
Allow disabling / remapping of display rotation hotkeys

### ISSUE THREAD

**Issue by jonnybrooks** [Genymobile/scrcpy#1641]
Please allow us to disable the screen rotation hotkeys `ctrl + ->` and `ctrl + <-`
On Windows (and in my custom Linux config) the hotkey for changing virtual desktops is `ctrl+windows+<left or right>`, so every time I switch virtual desktops the display rotates. This is super aggravating!

**Comment by rom1v** [comment]
Could you test #1598 (future v1.15), please? The modifier key is changed (and can be changed).

**Comment by jonnybrooks** [comment]
> Could you test #1598 (future v1.15), please? The modifier key is changed (and can be changed).

Fantastic! I'll test it today.

**Comment by jonnybrooks** [comment]
Tested #1598 today, works exactly as I'd like it to. Thanks for your work! I'll close this issue.
