### ISSUE TITLE
Ctrl-S (app switch) doesn't work on 1.15 on Galaxy S7

### ISSUE THREAD

**Issue by wimg** [Genymobile/scrcpy#1642]
- [ x ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ x ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 8.1
 - scrcpy version: 1.15
 - installation method: Windows release
 - device model: Samsung Galaxy S7
 - Android version: 9

**Describe the bug**
The previous version I had installed was 1.12.1 - after upgrading to 1.15, the Ctrl-S shortcut (app switch) is not working anymore. 

```
No output in console, even when using -V debug
```

**Comment by rom1v** [comment]
v1.15 now forwards <kbd>Ctrl</kbd> (and <kbd>Shift</kbd>) to the device, so the shortcut modifier (<kbd>MOD</kbd>) had to be changed. By default, it's <kbd>Alt</kbd> or <kbd>Super</kbd>. See https://github.com/Genymobile/scrcpy/releases/tag/v1.15

So just use <kbd>Alt</kbd>+<kbd>s</kbd> or <kbd>Super</kbd>+<kbd>s</kbd> instead.

**Comment by wimg** [comment]
Thanks for the very fast response.
That works perfectly !
