### ISSUE TITLE
Ignore touch event, it was generated for a different device size

### ISSUE THREAD

**Issue by swamikamal** [Genymobile/scrcpy#1645]
Ignore touch event, it was generated for a different device size
-v 1.15 not recognizing my click as touch on screen
please help me 
![Screenshot (423)](https://user-images.githubusercontent.com/49489982/89632868-8f6fa300-d8c0-11ea-87cc-f60940423de8.png)

**Comment by rom1v** [comment]
Ah, great, it was a good idea to add the log a973757fd141fc07ef81314d350bd4f4de64f59c
See https://github.com/Genymobile/scrcpy/issues/1518#issuecomment-655517010

The reason is that on some devices, the video encoder on the device does not respect the requested size, and we can't detect this change on the server side.

To avoid the problem, check the first lines in scrcpy output:

```
INFO: Initial texture: 1080x2336
INFO: New texture: 888x1920
```

And limit the size to what the encoder actually produces. Here:

```
scrcpy -m1920
```

(take the greatest value of the second line)

**Comment by swamikamal** [comment]
![Screenshot (424)](https://user-images.githubusercontent.com/49489982/89634952-df039e00-d8c3-11ea-8ffe-da54ab0ba4f0.png)

**Comment by rom1v** [comment]
_(please post output as text instead of a screenshot)_

Then just run `scrcpy -m1920` as I explained above.

**Comment by swamikamal** [comment]
INFO: Initial texture: 1080x2336
INFO: New texture: 888x1920 
...................................................................
now what i have to do

**Comment by swamikamal** [comment]
Sorry!! And Thank you very much Sir.

**Comment by xrobb30** [comment]
thank you so much, master. it works for my oppo F7 hihi

**Comment by skivox52** [comment]
Same issue on MI9SE.
I tried using different  "-m XXXX" option, but still doesn't work.

How to know which value to use please ? 
Here is the output while launching scrcpy without "-m" option : 

[server] INFO: Device: Xiaomi Mi 9 SE (Android 10)INFO: Renderer: opengl
INFO: OpenGL version: 3.0 Mesa 20.0.8
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x2336

Merci

**Comment by skivox52** [comment]
I do not have these two lines.
Only the lines I shown you.

I do not get any error message, but the mouse event doesn't work.
if i open app touching phisically my phone, i can see it on scrcpy but i cannot interact with it using the mouse.

Sorry if I posted in the wrong thread.
Thanks

**Comment by rom1v** [comment]
@skivox52 https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work

**Comment by skivox52** [comment]
> @skivox52 https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work

Thanks a lot, going to check this

**Comment by mjwaghmare** [comment]
> _(please post output as text instead of a screenshot)_
> 
> Then just run `scrcpy -m1920` as I explained above.

how to set it permanently??

**Comment by rom1v** [comment]
> how to set it permanently??

You could create a script: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows

(currently, there is no config file)

**Comment by mjwaghmare** [comment]
@rom1v How to set it this in the Mac OS?

**Comment by rom1v** [comment]
Create a file `myscrcpy` containing:

```bash
#!/bin/bash
scrcpy -m1920
```

Make it ewecutable (`chmod +x myscrcmy`), and execute (`./myscript`).

**Comment by anszom** [comment]
I'm encountering a similar problem on a lenovo tablet. For some reasons the encoder returned a smaller texture no matter what values of -m were supplied.

Native resolution:
```
INFO: Initial texture: 1024x600
INFO: New texture: 1024x592
```

With -m800
```
INFO: Initial texture: 800x472
INFO: New texture: 800x464
````

My work-around is to crop the few pixels off the edge of the screen with --crop=592:1024:0:0
Surely there must be a better way

**Comment by 14790897** [comment]
thanks

**Comment by bksubhuti** [comment]
It does work.. but there must be a user friendly way.  Linux way of googling the error, jumping to github issues and applying a 2 year old fix.. is well.. why linux is not so popular.  Can there be a way to auto detect a resolution change and fix it?

**Comment by rom1v** [comment]
> why linux is not so popular

What does this have to do with Linux? It is a device encoder misbehavior, which breaks some assumption made by scrcpy. The problem is the same on the Windows or macOS version of scrcpy.

> Can there be a way to auto detect a resolution change and fix it?

That's not straightforward: the wrong encoded size happens on the device, but it is detected by the client, so it would require a specific mechanism to communicate the mismatch and reconfigure everything. And it impacts only a few devices in practice, and there's a workaround, so it's not done.

**Comment by bksubhuti** [comment]
well.. if there is a detected resolution change.. is that sent to the client (assuming scrcpy) is the client?  
At least an message can be thrown to the terminal output that launches it upon resolution change detection?

**Comment by rom1v** [comment]
> At least a message can be thrown to the terminal output that launches it upon resolution change detection?

The device knows the requested capture size, the client (on the computer) knows the actual video size. No one knows both.

This might change with #5894 #5918 in the future.

**Comment by bksubhuti** [comment]
do you want me to metoo these closed issues?

**Comment by bksubhuti** [comment]
I see this is open and merged.   https://github.com/Genymobile/scrcpy/pull/5918
