### ISSUE TITLE
minor screen-tear-like issue with 16:9 phone

### ISSUE THREAD

**Issue by Remyy11** [Genymobile/scrcpy#1646]
I dont really have a serious issue but I seem to have seperating lines at the right side of my screen when using landscape mode, i have tried changing bitrate unprofessionally and it doesnt seem to show any effect.

It's like screen tearing but it isn't, it has parts of the right hand side of the screen duplicated at the left hand side in skipping lines, i don't know what it is called. Ill post a link to the image in case my description sucks to be understood

Device : Samsung SM A315G(Android 10)
Aspect ratio : 16:9 (2400x1080)

Pardon if there was a similar question that i missed because i didnt see any questions like my problem.

Image link: 
https://cdn.discordapp.com/attachments/481821360427892757/741269930124771379/Tos_send.jpg

**Comment by rom1v** [comment]
It looks like an encoder issue (which probably does not support a width of 2400). Try to reduce the definition:

```
scrcpy -m2048
```

**Comment by rom1v** [comment]
Also, does it happens if you record the device and play the video with some player?

```
scrcpy --record file.mkv
```

**Comment by Remyy11** [comment]
> Also, does it happens if you record the device and play the video with some player?
> 
> ```
> scrcpy --record file.mkv
> ```

I'll try to do it later, ill update when i do

**Comment by Remyy11** [comment]
> It looks like an encoder issue (which probably does not support a width of 2400). Try to reduce the definition:
> 
> ```
> scrcpy -m2048
> ```

Ah, this worked! Thank you for the help :))

**Comment by rom1v** [comment]
Great :+1:

Could you still test to record to a file, to determine if the problem is on the device or computer side, please?

**Comment by Remyy11** [comment]
> Great 👍
> 
> Could you still test to record to a file, to determine if the problem is on the device or computer side, please?

I just tried it, when using the original, the screen problem still persist in the recording, and when using the m2048, it was alright. Sorry for late response

**Comment by rom1v** [comment]
> So maybe it's a device problem itself?

Exactly. The screen encoding is corrupted before being sent to the computer :)
