### ISSUE TITLE
snap install still at 1.14

### ISSUE THREAD

**Issue by ManFarang** [Genymobile/scrcpy#1649]
tried to upgrade my scrcpy installation (via snap) to the current version 1.15.1

but:

$snap info scrcpy
name:      scrcpy
summary:   Display and control your Android device
publisher: sisco311
store-url: https://snapcraft.io/scrcpy
contact:   https://github.com/sisco311/scrcpy-snap/issues
license:   Apache-2.0
description: |
  This application provides display and control of Android devices connected on USB (or over
  TCP/IP). It does not require any root access.  It works on GNU/Linux, Windows and MacOS.
  
  This is an unofficial snap. The code of scrcpy can be found at:
  https://github.com/Genymobile/scrcpy
commands:
  - scrcpy.adb
  - scrcpy
snap-id:      M7yvgnqOvyQj64bolfpawIAEwHv7dQ5G
tracking:     latest/stable
refresh-date: 40 days ago, at 12:27 +07
channels:
  latest/stable:    v1.14            2020-06-17 (233) 85MB -
  latest/candidate: ↑                                      
  latest/beta:      v1.14-5-g3c0fc8f 2020-06-17 (231) 85MB -
  latest/edge:      v1.12-1-g71df317 2019-12-10 (202) 81MB -
installed:          v1.14                       (233) 85MB -

please supply the snap install package for the latest version.
Thanks

**Comment by rom1v** [comment]
cc @sisco311 :wink:

**Comment by sisco311** [comment]
Done. v1.15.1 is in the snap store.
