### ISSUE TITLE
1.2 broke crosscompilation to arm

### ISSUE THREAD

**Issue by SolitudeSF** [Genymobile/scrcpy#165]
https://travis-ci.org/voidlinux/void-packages/jobs/388355557#L901

**Comment by SolitudeSF** [comment]
reverting `app/meson.build` fixes the issue, so i guess all the crosscompilation quirks there should be also limited to windows

**Comment by rom1v** [comment]
Thank you for your report. :+1:

It should now be fixed on `dev` branch.

**Comment by SolitudeSF** [comment]
thank you for prompt fix
