### ISSUE TITLE
[server] WARN: Could not inject char u+0151 Missing Hungaryan ő (u+0151) and Ő (u+0150) letters 

### ISSUE THREAD

**Issue by morfyum** [Genymobile/scrcpy#1651]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**

 - OS: [e.g. Debian, Windows, macOS...]
    Fedora 32 with gnome 3.36.X + Wayland

 - scrcpy version: [e.g. 1.12.1]
scrcpy 1.15.1

dependencies:
 - SDL 2.0.12
 - libavcodec 58.54.100
 - libavformat 58.29.100
 - libavutil 56.31.100

 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
sudo dnf copr enable zeno/scrcpy

 - device model:
Galaxy S6 - SM-G920F

 - Android version: [e.g. 10]
android 7.0

**Describe the bug**
Error message from terminal, if i push  ő  letter in my pc keyboard:
[server] WARN: Could not inject char u+0151
Similar as a big  Ő letter:
[server] WARN: Could not inject char u+0150

On errors, please provide the output of the console (and `adb logcat` if relevant).
```
[server] WARN: Could not inject char u+0151
[server] WARN: Could not inject char u+0150
```

BTW scrcpy is amazing! :D Wow! Thanks man!
I hope to continuous developement is possible to launch android apps as a single app, similar as a Microsoft new tool for Galaxy S20 and newer devices.

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
That's "expected": https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#special-characters-do-not-work

> BTW scrcpy is amazing! :D Wow! Thanks man!

Thanks :blush: 

> I hope to continuous developement is possible to launch android apps as a single app, similar as a Microsoft new tool for Galaxy S20 and newer devices.

For now, I don't know technical solution for this (they probably develop some software in the device ROM itself to give more controls).
