### ISSUE TITLE
Mod should be CTRL by default on windows

### ISSUE THREAD

**Issue by riexn** [Genymobile/scrcpy#1654]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
As of version 1.5.1, on windows, the shortcuts switched from `ctrl+[key]` to `alt+[key]` due to the ability to change the `mod` key.
It makes sense for Mac since `cmd` is located where `alt` is, but in windows the shortcuts are usually `ctrl`.

This can be quickly solved with 
```
scrcpy --shortcut-mod=lctrl
```
but, I believe having it the default for windows would be good so it wouldn't confuse new users.

**Describe the solution you'd like**
By default, `mod` for windows would be `ctrl`.

**Describe alternatives you've considered**
changing the mod key in `scrcpy` arguments

```
scrcpy --shortcut-mod=lctrl
```

**Comment by rom1v** [comment]
The whole point of this change is to forward <kbd>Ctrl</kbd> to the device to use it for device shortcuts. For example <kbd>Ctrl</kbd>+<kbd>a</kbd> to select all text, <kbd>Ctrl</kbd>+<kbd>t</kbd> to open a new browser tab, etc.

So _scrcpy_ itself must use another key for its own shortcuts.

See #1598 and [highlights](https://github.com/Genymobile/scrcpy/releases/tag/v1.15).

**Comment by riexn** [comment]
Makes sense in this case then!
