### ISSUE TITLE
Screen off improvements: Make it optional

### ISSUE THREAD

**Issue by dedosmedia** [Genymobile/scrcpy#1661]
Sometimes I connect to a device with the screen off and using -S parameter, since 1.15 once I disconnect from the device the screen will turn on always. It does not matter the initial screen state, that is not cool sometimes. So I would like to have this feature as optional, maybe enabling/disabling it with a command line parameter.

(Before 1.15, when using -S, sometimes before disconnecting from the device I sent MOD+p, so after disconnection to turn the screen on from the device, you just needed to press ONE time the POWER button.)

**Comment by rom1v** [comment]
> since 1.15 once I disconnect from the device the screen will turn on always.

It just restores the "power mode" to normal. If the screen was off (i.e. it was also black in the mirrored screen), then it will not turn on.

> sometimes before disconnecting from the device I sent MOD+p, so after disconnection to turn the screen on from the device,

On v1.15/v1.16, if I sent <kbd>MOD</kbd>+<kbd>p</kbd> to turn the device off, then disconnect, then the screen remains off on disconnect (tested on several devices).

**Comment by dedosmedia** [comment]
So, what I understand it's that now mirroring screen state and device screen state will be synced after disconnection, so when I disconnect scrcpy the device screen will take the last state the mirroring screen had before disconnection.
Makes sense.  Thanks for your answer.

**Comment by rom1v** [comment]
Yes, what it does is basically <kbd>MOD</kbd>+<kbd>Shift</kbd>+<kbd>o</kbd> on disconnection.

**Comment by fefo-dev** [comment]
@rom1v any way to mimic the old behaviour outside of staying on 1.14? It was a decent workaround for privacy (no way to touch/turn the screen on without pressing the power button, thus locking the device) which is practical for leaving the phone unatended, like in your workplace while you use it through a laptop for example.
