### ISSUE TITLE
Found Malware in v1.5 version

### ISSUE THREAD

**Issue by Hasan-Uddin** [Genymobile/scrcpy#1664]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal
![Screenshot - 8_12_2020 , 1_32_04 PM](https://user-images.githubusercontent.com/60354359/89987851-83108f00-dca0-11ea-99a9-92ae66bf0515.png)
, just post the content as text instead.

**Comment by Hasan-Uddin** [comment]
![Screenshot - 8_12_2020 , 1_32_04 PM](https://user-images.githubusercontent.com/60354359/89987902-97548c00-dca0-11ea-8bb6-24bc96cdc678.png)

**Comment by rom1v** [comment]
See #1648 and #1102.

**Comment by Hasan-Uddin** [comment]
Ok... Going to use v1.6

**Comment by rom1v** [comment]
Oh, maybe you mean v1.15 and v1.16, not v1.5 and v1.6?

**Comment by Hasan-Uddin** [comment]
What did you say ? 😁
