### ISSUE TITLE
Add "(auto)updater" for windows version

### ISSUE THREAD

**Issue by barfin** [Genymobile/scrcpy#1676]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Comment by rom1v** [comment]
Hi,

I understand the need of updating automatically, and acknowledge that nothing is provided on Windows to do that, but it's the role of package managers. TBH, I won't spend time on this feature (moreover, an updater requires a lot of care about security).

I suggest you install scrcpy via Chocolatey or scoop, they will take care of the auto-update: https://github.com/Genymobile/scrcpy#windows

**Comment by barfin** [comment]
thanks that'll do the job i think
