### ISSUE TITLE
Can't connect with wire after wireless

### ISSUE THREAD

**Issue by Kumagie** [Genymobile/scrcpy#1679]
Greetings, I would like to ask about how to mirroring again with wire after mirroring wirelessly? 

Because when I use wire again, on cmd it says 

```
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>`
adb: error: failed to get feature set: more than one device/emulator`
ERROR: "adb push" returned with value 1`
Press any key to continue...
```

And I don't know how to mirroring again with wire without adding _serial_

Thanks in advance.

**Comment by rom1v** [comment]
If several devices are connected (= listed by `adb devices`), then you need either to provide the serial (`scrcpy -s SERIAL`) or disconnect one of them.

If the two devices connected is the same physical device (once over USB, once over WIFI), and you want to disconnect the connection over wifi, just `adb disconnect`.

**Comment by Kumagie** [comment]
Ok. I'll try to disconnect the connection over wifi because it's only 1 device..

I'll inform you more if there's a problem again. 
Thank for the advice.

**Comment by Kumagie** [comment]
It's automatically disconnected when the computer turned off. I'll keep the steps when can't connect again over USB.

Thank you so much!
