### ISSUE TITLE
Refer to --shortcut-mod above the Shortcuts: list

### ISSUE THREAD

**Issue by schokotets** [Genymobile/scrcpy#1681]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**The problem**
I first learned about available keyboard shortcuts when running `scrcpy --help`. At the top of the list "Shortcuts:", it says "...but it can be configured by `--shortcut-mod`."  So in order to use the right alt key as a modifier, I tried
- `--shortcut-mod 'RightAlt'`
- `--shortcut-mod 'Right Alt'`
- `--shortcut-mod 'AltGr'` 

and because I was frustrated (none of these worked and I had no info which would, or so I thought), I went to the GitHub repo and stumbled upon the line further up in the help section, which of course clarified it for me. I didn't look further up in the help section because I didn't look up high enough in my terminal screen.

**A solution I'd like**
- A simple referral in the `---help` text and man page, so it says "...but it can be configured by --shortcut-mod *(see above)*."
- A list of available shortcuts when running the command, as the current error messages `WARN: Unknown modifier key: altgr` and `ERROR: Invalid modifier keys: altgr` are barely useful.

I hope that this small frustration can be resolved for users like me. I would work on a pull request myself, unless somebody else is up to it.

**Comment by Helaer** [comment]
The input parameter is wrong, it should be: scrcpy --shortcut-mod =ralt, by default it is lalt.

**Comment by schokotets** [comment]
Yup, I eventually found out it would be `ralt`, but this is not what my issue is about. It's about communicating it better to a first-time user.

**Comment by rom1v** [comment]
:+1:

> A simple referral in the `--help` text and man page, so it says "...but it can be configured by --shortcut-mod _(see above)_."

6cc22e1c5b370baecee9072f52c44fdd13ba9634

> A list of available shortcuts when running the command, as the current error messages `WARN: Unknown modifier key: altgr` and `ERROR: Invalid modifier keys: altgr` are barely useful.

d02789ce21a183682f968cc95dcd88c98efba0f0

```
$ scrcpy --shortcut-mod=rctrl+abc,lctrl
ERROR: Unknown modifier key: abc (must be one of: lctrl, rctrl, lalt, ralt, lsuper, rsuper)
ERROR: Invalid modifier keys: rctrl+abc
```

Please review, if it's ok I'll merge them.

> I would work on a pull request myself

Oh, sorry, I saw this after I already wrote the commits :confused:

**Comment by schokotets** [comment]
No worries, I sincerely appreciate how quickly you got back to me!  
Actually, you have a better solution to the second problem than the one I implemented: I thought it would be best to refer to the help section, as it als specifies the ability to have multiple modifier keys, and I was afraid to duplicate information between code and the help section.  
However, seeing your solution as being way more straight-forward and user-friendly, I'm glad you put in the work ^^

So yes, LGTM! Thanks for checking back.
