### ISSUE TITLE
adb: error: failed to get feature set: device '192.168.1.87:5555' not found

### ISSUE THREAD

**Issue by x011** [Genymobile/scrcpy#1682]
Version: scrcpy-win64-v1.16
ADB debug enabled.

I can connect to my device via tcp using:

`adb connect 192.168.1.87:5555`

but

`./scrcpy -s 192.168.1.87:5555`

Throws an error:

```
PS C:\Users\x\Desktop\portables\scrcpy-win64-v1.16> ./scrcpy --serial 192.168.1.87:5555
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: device '192.168.1.87:5555' not found
ERROR: "adb push" returned with value 1
Press any key to continue...
```

I follow [these instructions](https://www.genymotion.com/blog/open-source-project-scrcpy-now-works-wirelessly/), but I cannot connect the device to my computer with a cable because it's an android TV box.

Any idea how to solve this?

**Comment by rom1v** [comment]
What is the result of `adb devices`?

**Comment by x011** [comment]
After restarting the WIFI ADB app and the ADB daemon on windows, it does work as intended.

**Comment by x011** [comment]
Your program rocks, thank you so much.

**Comment by x011** [comment]
I don't know how to consistently connect to the several devices alternately. 
It worked well once after restarting everything as stated above, but now, again, I cannot connect to any device.

```
C:\Users\0x>adb devices
List of devices attached
192.168.1.87:5555       device
```

but when i try to connect:

```
C:\Users\0x\Desktop\portables\scrcpy-win64-v1.16>scrcpy --serial 192.168.1.87:5555
adb: error: failed to get feature set: device '192.168.1.87:5555' not found
ERROR: "adb push" returned with value 1
Press any key to continue...
```


Do you have any tip to make `scrcpy `work consistently?

**Comment by x011** [comment]
I already add `adb` on my windows path and after removing the `adb` inside of the `scrcpy` folder, forcing `scrcpy` to use the one on `path`, `scrcpy` worked properly.

Here's what worked for me:

```
adb kill-server
adb connect 192.168.1.87:5555
adb connect 192.168.1.82:5555
scrcpy --serial 192.168.1.87:5555
scrcpy --serial 192.168.1.82:5555
```

**Comment by rom1v** [comment]
> I already add adb on my windows path and after removing the adb inside of the scrcpy folder

What is the result of `adb --version` (using the one from your path)?

**Comment by zizouqi** [comment]
I have the same issue, have to use `adb connect` first.
My `adb --version` is:
```
Android Debug Bridge version 1.0.41
Version 30.0.4-6686687
Installed as C:\Software\adb\adb.exe
```
