### ISSUE TITLE
How can i use mapping screen for creating a custom gaming adb?

### ISSUE THREAD

**Issue by hugonh** [Genymobile/scrcpy#1686]
- [ ] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rom1v** [comment]
#712
