### ISSUE TITLE
Mouse clicks not working on one app

### ISSUE THREAD

**Issue by Stopperan** [Genymobile/scrcpy#1688]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Win10
 - scrcpy version: 1.8
 - installation method: Windows release
 - device model: Redmi 5 plus (Vince)
 - Android version: AEX 10

**Describe the bug**
Mouse clicks works fine except in one app (android game mindustry). The rest of android and apps (atleast some of- i haven't checked all of them) works fine in window, but not in this app. Keyboard also works fine. I have enabled USB Debugging, I don't have an option to enable simulate touch.

```
Please paste terminal output in a code block.

Nothing unusual in the terminal

**Comment by rom1v** [comment]
> scrcpy version: 1.8

Use the latest version.

**Comment by Stopperan** [comment]
Whoops, seems like I downloaded wrong version by accident, now everything works flawlessly, sorry for taking your time.
