### ISSUE TITLE
ERROR: 'scrcpy-server' does not exist or is not a regular file (Aug 20,2020)

### ISSUE THREAD

**Issue by MINEJHAZZ** [Genymobile/scrcpy#1692]
- OS: Windows 10
 - scrcpy version: 1.16
 - installation method: Chocolatey
 - device model: N/A
 - Android version: 10

Scrcpy was working fine for me but after i deleted the old version folder(Installed it manually) and installed the new version via chocolatey it wont work anymore and it shows the directory of the old scrcpy that i deleted

The error i was getting:
```
C:\Windows\system32>scrcpy
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
stat: No such file or directory
ERROR: 'C:\scrcpy-win64-v1.14\scrcpy-server' does not exist or is not a regular file
Press any key to continue...
```

Already read issue #1002 and the other issues that is related to this, but one thing is different.
The directory that scrcpy is looking at is "wrong"

*btw im still fairly new to github and command excecutions, only started learning basic java recently-*

**Comment by rom1v** [comment]
You probably set `SCRCPY_SERVER_PATH` environment variable with an old value. Just unset it.

**Comment by MINEJHAZZ** [comment]
how do i do that?

**Comment by MINEJHAZZ** [comment]
Found a quick fix to it.
just move all the new version resources to the old scrcpy folder and it all works fine now.

**Comment by rom1v** [comment]
> how do i do that?

Random links:
https://docs.oracle.com/en/database/oracle/r-enterprise/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html
https://support.shotgunsoftware.com/hc/en-us/articles/114094235653-Setting-global-environment-variables-on-Windows

**Comment by hwpoison** [comment]
check if "/ usr / local / share / scrcpy / scrcpy-server" is not a folder.

Copy "scrcpy-server" to "/ usr / local / share / scrcpy /" as a file.

I had the same problem and I solved it that way
