### ISSUE TITLE
FPS fluctuates and drops massively when playing game

### ISSUE THREAD

**Issue by KuroChloe** [Genymobile/scrcpy#1697]
Tried using couple of different settings:
Changing renderer, smaller display size, higher bit-rate.
None help and after a while game starts chugging to no end.

Maybe unrelated but in Samsung S9 settings you can selected "USB Controlled by" and it's set to "This device" rather than connected one, is this correct setting or makes no difference?

Could this FPS issue stem from USB port or cable? Maybe if the USB port is not USB3.0 or something?

![Clipboard01](https://user-images.githubusercontent.com/43561950/90968311-7f2c0a80-e4f3-11ea-9cb0-081825a18cab.png)

**Comment by milanisop** [comment]
how to change the default fps to 30 or 60 
can someone please help me

**Comment by rom1v** [comment]
You can limit the fps with `scrcpy --max-fps 30` for example.

If no limit is set, then the encoder produces (if it can) a new frame every time the screen surface changes.
