### ISSUE TITLE
Works perfectly but closes after a few seconds

### ISSUE THREAD

**Issue by allokrv** [Genymobile/scrcpy#1699]
**Environment**
 - OS: Manjaro
 - scrcpy version: 1.16
 - installation method: yay / pacman
 - Android version: 10

Works for like 30 seconds, can't see any errors
and quits just like that
[Screenshot](https://imgur.com/a/FAR8fMk)

**Comment by rom1v** [comment]
`adb` gets discknnected (as if you unplugged the device).

Try with another USB port/cable.

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#device-disconnected

**Comment by allokrv** [comment]
> `adb` gets discknnected (as if you unplugged the device).
> 
> Try with another USB port/cable.
> 
> https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#device-disconnected

well now i know why my internet keeps disappearing as well (usb tethering) 
thanks the usb port's the problem
