### ISSUE TITLE
Using scrcpy without ADB

### ISSUE THREAD

**Issue by Namorzyny** [Genymobile/scrcpy#1706]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
Some games disallow ADB and emulators. They will stop working. I want to play them on PC.

**Describe the solution you'd like**
A way to use root privileges to connect to the PC (Magisk Hide can bypass the check mechanism of the games). I tried socat and hacking adb.exe, but I failed.

**Comment by Namorzyny** [comment]
After some technical adjustment, this problem has been solved perfectly.

**Comment by Benjamin-Loison** [comment]
> some technical adjustment

Can you elaborate on that? I also face this problem.

Personal notes: [Benjamin_Loison/Voice_assistant/issues/114#issuecomment-13009425](https://codeberg.org/Benjamin_Loison/Voice_assistant/issues/114#issuecomment-13009425)
