### ISSUE TITLE
right Alt not working?

### ISSUE THREAD

**Issue by GetCurious** [Genymobile/scrcpy#1712]
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
x/server/scrcpy-server: 1 file pushed,...ed. 103.8 MB/s (33622 bytes in 0.000s)
[server] INFO: Device: OPPO CPH1969 (Android 10)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6.0 NVIDIA 435.21
INFO: Trilinear filtering enabled
INFO: Initial texture: 880x1912

previously i was using right side Ctrl... 
for some reason it was changed to Alt/Super?
Either way left Alt/Super works fine but not the right Alt/Super. Is this intended?

**Comment by rom1v** [comment]
> for some reason it was changed to Alt/Super?

Yes, everything is explained in [highlights from v1.15](https://github.com/Genymobile/scrcpy/releases/tag/v1.15) and #1702 

> previously i was using right side Ctrl...

If you still want this behavior:
```
scrcpy --shortcut-mod=rctrl
```
(but then, right-Ctrl would not be forwarded to the device)

> Either way left Alt/Super works fine but not the right Alt/Super.

Yes, default is `--shortcut-mod=lalt,lsuper`. `ralt` is <kbd>AltGr</kbd> on some keyboards, and `rsuper` is sometimes a special key too.
