### ISSUE TITLE
Clipboard machine -> device is not working

### ISSUE THREAD

**Issue by Lautenschlager-id** [Genymobile/scrcpy#1715]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Ubuntu
 - scrcpy version: 1.16
 - installation method: snap
 - device model: Samsung J8
 - Android version: 9

**Describe the bug**
It's been a while since I could paste on my applications content that I had in my machine's clipboard.

Now, whenever I try to CTRL+V in any textbox of any app, it simply doesn't work. No logs in my terminal either. Curiously enough, I was able to do that a few weeks ago and I hadn't updated scrcpy. I just installed it again to make sure and the problem is still happening.

Curiously enough², I wasn't able to CTRL+C any content from the device to use on my machine by the time I could use the clipboard from my machine in the device, and now I can. It feels like the bridge has switched from machine->device to device->machine (if that makes any sense?).

**Comment by rom1v** [comment]
Does <kbd>Alt</kbd>+</kbd>v</kbd> work?
Does <kbd>Alt</kbd>+<kbd>Shift</kbd>+</kbd>v</kbd> work?

https://github.com/Genymobile/scrcpy#copy-paste

There have been a lot of changes regarding copy-paste recently. Check v1.15 highlights: https://github.com/Genymobile/scrcpy/releases/tag/v1.15

**Comment by Lautenschlager-id** [comment]
Oh, it worked! I have no idea how I missed those points haha. Thank you so much! Interesting, now we have access to both clipboards.
