### ISSUE TITLE
A more easy app

### ISSUE THREAD

**Issue by Aaxiruz** [Genymobile/scrcpy#1719]
I just want to ask that are you going to make scrcpy more easy to use and a little user-friendly interface like apowermirror or vysor, thanks

**Comment by LightStorm12345** [comment]
I think scrcpygui is a gui alternative to scrcpy.

**Comment by BloodPHamtOm** [comment]
> I think guiscrcpy is a gui alternative to scrcpy.
> https://github.com/srevinsaju/guiscrcpy

Thank you soooo much!

**Comment by AndroidDeveloperLB** [comment]
Why is it GNU license though?

Odd. Scrcpy is apache...
