### ISSUE TITLE
scrcpy-killed it self

### ISSUE THREAD

**Issue by zulfi0** [Genymobile/scrcpy#1721]
i face a problem that scrcpy doesn't mirror the phone and suddenly killed it self when connected wirelessly

```
scrcpy
INFO: scrcpy 1.14 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed. 2.3 MB/s (31693 bytes in 0.013s)
killed
```

i tried with usb but scrcpy keep won't mirroring
i use adb version 1:8.1.0+r23-7
and scrcpy version 1.14
android version 8.1

**Comment by rom1v** [comment]
> adb version 1:8.1.0+r23-7

Hmmm, what? What is the result of:

```
adb --version
```

On which platform? How did you install it?

> suddenly killed it self when connected wirelessly

> i tried with usb but scrcpy keep won't mirroring

So it also prints `killed` over USB?

**Comment by zulfi0** [comment]
Thank you for respond

> adb --version
Android Debug Bridge version 1.0.39
Version 1:8.1.0+r23-7
Installed as /usr/lib/android-sdk/platform-tools/adb

i use kali linux and i install it with apt install scrcpy


> So it also prints killed over USB?

unfortunately yess

> Any errors in adb logcat?

i don't know but i will see the logcat now and send it to you

**Comment by zulfi0** [comment]
here's the logcat 
[https://drive.google.com/file/d/1RYVnZaQJBCkBf54uAELtV1_5cJXQOo3X/view?usp=sharing](url)

**Comment by zulfi0** [comment]
here's the logcat 
https://drive.google.com/file/d/1RYVnZaQJBCkBf54uAELtV1_5cJXQOo3X/view?usp=sharing

**Comment by rom1v** [comment]
```
08-29 23:32:11.292 25990 25990 I /system/bin/adbd: type=1400 audit(0.0:4175): avc: denied { write } for comm=73796E6320737663203232 name="tmp" dev="mmcblk0p50" ino=1483223 scontext=u:r:adbd:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
08-29 23:32:11.292 25990 25990 I /system/bin/adbd: type=1400 audit(0.0:4176): avc: denied { add_name } for comm=73796E6320737663203232 name="scrcpy-server.jar" scontext=u:r:adbd:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
08-29 23:32:11.292 25990 25990 I /system/bin/adbd: type=1400 audit(0.0:4177): avc: denied { create } for comm=73796E6320737663203232 name="scrcpy-server.jar" scontext=u:r:adbd:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
08-29 23:32:11.292 25990 25990 I /system/bin/adbd: type=1400 audit(0.0:4178): avc: denied { write open } for comm=73796E6320737663203232 path="/data/local/tmp/scrcpy-server.jar" dev="mmcblk0p50" ino=1483224 scontext=u:r:adbd:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
08-29 23:32:11.312 25990 25990 I /system/bin/adbd: type=1400 audit(0.0:4179): avc: denied { getattr } for comm=73796E6320737663203232 path="/data/local/tmp/scrcpy-server.jar" dev="mmcblk0p50" ino=1483224 scontext=u:r:adbd:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
08-29 23:32:11.312 25990 25990 I /system/bin/adbd: type=1400 audit(0.0:4180): avc: denied { relabelfrom } for comm=73796E6320737663203232 name="scrcpy-server.jar" dev="mmcblk0p50" ino=1483224 scontext=u:r:adbd:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
08-29 23:32:11.312 25990 25990 I /system/bin/adbd: type=1400 audit(0.0:4181): avc: denied { relabelto } for comm=73796E6320737663203232 name="scrcpy-server.jar" dev="mmcblk0p50" ino=1483224 scontext=u:r:adbd:s0 tcontext=u:object_r:shell_data_file:s0 tclass=file permissive=1
```

It seems `shell` does not have the permissions to write to `/data/local/tmp/` on your device.

```
$ adb shell touch /data/local/tmp/a
$ adb shell ls -ld /data/local/tmp
```

**Comment by zulfi0** [comment]
> $ adb shell ls -ld /data/local/tmp
drwxrwxrwx 3 root root 4096 2020-08-30 00:59 /data/local/tmp

the output has write permission now but still get same error

**Comment by rom1v** [comment]
If you still get permission denied in the logs, then there is a permission issue. Maybe restrictions defined by selinux.

**Comment by rom1v** [comment]
Can you create a file in /data/local/tmp from `adb shell`?

**Comment by zulfi0** [comment]
> Can you create a file in /data/local/tmp from adb shell?

yes i can there is `a` file after i ran this command 

> $ adb shell touch /data/local/tmp/a

**Comment by zulfi0** [comment]
> If you still get permission denied in the logs, then there is a permission issue. Maybe restrictions defined by selinux.

hmm i don't think so because it went perfectly normal before i reinstall scrcpy, i was removing scrcpy with `apt` and i tried install it again manually with `prebuilt server `in your README but it's fail after i ran `ninja -Cx`. because it fail so i remove manually all scrcpy in my `/usr` file and install it again with scrcpy and suddenly that is happen to me.

**Comment by rom1v** [comment]
What is the result of `adb shell ls -l /data/local/tmp`?

In particular, is there some `scrcpy-server.jar`? What are its permissions? Is it a directory or a file?

**Comment by zulfi0** [comment]
>$ ls -l /data/local/tmp
-rw-rw-rw- 1 shell   shell       0 2020-08-30 00:59 a
-rw-rw-rw- 1 shell   shell   31693 2020-07-01 14:59 scrcpy-server.jar

it's a file sir, tried to remove `scrcpy-server.jar` and rerun scrcpy still got the same error..
scrcpy can make directory `tmp` by it self right ? if so, i tried remove `tmp` directory and rerun scrcpy again show me this error 

> $ scrcpy
INFO: scrcpy 1.14 <https://github.com/Genymobile/scrcpy>
adb: error: failed to copy '/usr/share/scrcpy/scrcpy-server' to '/data/local/tmp/scrcpy-server.jar': remote secure_mkdirs failed: Permission denied
/usr/share/scrcpy/scrcpy-server: 0 files pushed. 1.8 MB/s (31693 bytes in 0.017s)
ERROR: "adb push" returned with value 1

**Comment by zulfi0** [comment]
i reboot my device and try scrcpy and it works, i don't know what happen to my phone.. so weird
thank u for your advice sir.
