### ISSUE TITLE
I get an error when calling C:/msys64/mingw64/bin/ninja.EXE

### ISSUE THREAD

**Issue by AVTurovskiy** [Genymobile/scrcpy#1732]
Good day.

Thanks for your project.

I am trying to build it from Windows 10, but has an error when i run `C:/msys64/mingw64/bin/ninja.exe` command:
```
1@MyPC MSYS /c/Development/AndroidControl/scrcpy/scrcpy-master/x
$ C:/msys64/mingw64/bin/ninja.EXE
[1/26] Compiling C object app/a172ced@@scrcpy@exe/src_command.c.obj
FAILED: app/a172ced@@scrcpy@exe/src_command.c.obj
cc @app/a172ced@@scrcpy@exe/src_command.c.obj.rsp
cc: fatal error: cannot execute 'cc1': CreateProcess: No such file or directory
compilation terminated.
[2/26] Compiling C object app/a172ced@@scrcpy@exe/src_main.c.obj
FAILED: app/a172ced@@scrcpy@exe/src_main.c.obj
cc @app/a172ced@@scrcpy@exe/src_main.c.obj.rsp
cc: fatal error: cannot execute 'cc1': CreateProcess: No such file or directory
compilation terminated.
[3/26] Compiling C object app/a172ced@@scrcpy@exe/src_util_str_util.c.obj
FAILED: app/a172ced@@scrcpy@exe/src_util_str_util.c.obj
cc @app/a172ced@@scrcpy@exe/src_util_str_util.c.obj.rsp
cc: fatal error: cannot execute 'cc1': CreateProcess: No such file or directory
compilation terminated.
[4/26] Compiling C object app/a172ced@@scrcpy@exe/src_util_net.c.obj
FAILED: app/a172ced@@scrcpy@exe/src_util_net.c.obj
cc @app/a172ced@@scrcpy@exe/src_util_net.c.obj.rsp
cc: fatal error: cannot execute 'cc1': CreateProcess: No such file or directory
compilation terminated.
[5/26] Compiling C object app/a172ced@@scrcpy@exe/src_video_buffer.c.obj
FAILED: app/a172ced@@scrcpy@exe/src_video_buffer.c.obj
cc @app/a172ced@@scrcpy@exe/src_video_buffer.c.obj.rsp
cc: fatal error: cannot execute 'cc1': CreateProcess: No such file or directory
compilation terminated.
[6/26] Compiling C object app/a172ced@@scrcpy@exe/src_sys_win_command.c.obj
FAILED: app/a172ced@@scrcpy@exe/src_sys_win_command.c.obj
cc @app/a172ced@@scrcpy@exe/src_sys_win_command.c.obj.rsp
cc: fatal error: cannot execute 'cc1': CreateProcess: No such file or directory
compilation terminated.
ninja: build stopped: subcommand failed.
```

The following steps were taken:
1. Previously installed AndroidStudio and Jdk
2. Console MSYS2 installed
3. Dependencies installed:
```
pacman -S mingw-w64-x86_64-SDL2 \
          mingw-w64-x86_64-ffmpeg
pacman -S mingw-w64-x86_64-make \
          mingw-w64-x86_64-gcc \
          mingw-w64-x86_64-pkg-config \
          mingw-w64-x86_64-meson
```
4. Then the following commands are executed:
`cd c:/Development/scrcpy/scrcpy-master`
`c:/msys64/mingw64/bin/meson.exe c:/Development/scrcpy/scrcpy-master/x --buildtype release --strip -Db_lto=true`

folders appear in directory x:
![image](https://user-images.githubusercontent.com/58735038/92143005-57a33f00-ee1d-11ea-952e-ce6be463a814.png)

and scrcpy-server appear too in server folder:
![image](https://user-images.githubusercontent.com/58735038/92143242-a8b33300-ee1d-11ea-8f47-b2c1d742aec0.png)

but, after run
`cd x`
and
`C:/msys64/mingw64/bin/ninja.exe`
here the above error appears.

in 'app' directory appears follow files:
![image](https://user-images.githubusercontent.com/58735038/92143784-6b02da00-ee1e-11ea-98d6-5bc2744b3e6b.png)
in 'a172ced@@scrcpy@exe' directory appears follow files:
![image](https://user-images.githubusercontent.com/58735038/92143871-8b329900-ee1e-11ea-918f-83ccb75fd742.png)

Please, tell me, what could be the problem?

**Comment by rom1v** [comment]
> cc: fatal error: cannot execute 'cc1': CreateProcess: No such file or directory
> compilation terminated.

So it does not find `cc` or `cc1`. I don't know what `cc1` is.
Maybe try to `export CC=gcc` before running `ninja`?

**Comment by Biswa96** [comment]
Use the MinGW32 or MinGW64 environment. See the prompt text, yours is MSYS.

**Comment by rom1v** [comment]
Thanks @Biswa96 :+1: It's been a long time since I used msys/mingw on Windows :)

**Comment by AVTurovskiy** [comment]
> Use the MinGW32 or MinGW64 environment. See the prompt text, yours is MSYS.

Not sure if I understand. How i can to do this?

**Comment by AVTurovskiy** [comment]
> Maybe try to `export CC=gcc` before running `ninja`?

I try to run `export CC=gcc`.
Now, every few launches, I have an even stranger result
![image](https://user-images.githubusercontent.com/58735038/92147748-342fc280-ee24-11ea-89ba-9116f656f292.png)

**Comment by Biswa96** [comment]
If you have installed MSYS2 properly then there will be three icons in Start Menu. Blue one is Mingw64. Or if you want to open the MinGW64 environment in Command Prompt then run this command `C:\msys64\msys2_shell.cmd -defterm -no-start -mingw64`. Replace `-mingw64` with `-mingw32` for MinGW32 environment i.e. i686-w64-mingw32 triplet.

I was thinking about adding the MSYS2 GitHub Actions in scrcpy and gnirehtet (and other projects if you want). This may speed up things and provide both x86_64 and i686 PE binaries. But I am not familiar with the other Java part.

**Comment by rom1v** [comment]
> I was thinking about adding the MSYS2 GitHub Actions

cf #1709

**Comment by AVTurovskiy** [comment]
> If you have installed MSYS2 properly then there will be three icons in Start Menu. Blue one is Mingw64. Or if you want to open the MinGW64 environment in Command Prompt then run this command `C:\msys64\msys2_shell.cmd -defterm -no-start -mingw64`. Replace `-mingw64` with `-mingw32` for MinGW32 environment i.e. i686-w64-mingw32 triplet.

It is realy worked! Thank you.
