### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by guanzhangrtk** [Genymobile/scrcpy#1739]
Would it be possible to port this to iOS? Thanks!

**Comment by rom1v** [comment]
See #1691

**Comment by guanzhangrtk** [comment]
Sorry, I should be more clear with my feature request. I do not mean to use scrcpy to control iOS devices, I mean directly porting scrcpy so that I can use it on iOS devices to control an Android device, much like how you are currently able to use scrcpy to control an Android device on Mac, Windows and Linux. Thanks again and great work BTW. I used to use Genymotion Personal quite a bit in the past :-)

**Comment by guanzhangrtk** [comment]
#2467
