### ISSUE TITLE
Segmentation fault 

### ISSUE THREAD

**Issue by eku** [Genymobile/scrcpy#174]
Compiled and running scrcpy on Fedora 28 against an M3 SM10 device. scrcpy crashes with

```
$ ninja run
[0/1] Running external command run.
/home/.../scrcpy/x/server/scrcpy-server.jar: 1 file pushed. 1.2 MB/s (19342 bytes in 0.016s)
error: closed
ERROR: "adb reverse" returned with value 1
WARN: 'adb reverse' failed, fallback to 'adb forward'
Segmentation fault 
```
I did not find any coredump, even Fedora's ```coredumpctl``` did not list any.

**Comment by rom1v** [comment]
What is your Android version? Is it at least Android 5?

**Comment by eku** [comment]
It's running Android 4.3. I know ```scrcpy```'s device component requires at least ```Lollipop```.  Anyway, a hint instead of a segmentation fault would be helpful. Feel free to close this issue.

**Comment by rom1v** [comment]
> Anyway, a hint instead of a segmentation fault would be helpful.

The segmentation fault occurs on the device, not in _scrcpy_ (the client).

Avoiding it would require to check the Android version before starting the server… Why not, but don't know if it is worth it.

**Comment by eku** [comment]
Min API 21 - what requires it? Is lowering the API possible?

**Comment by rom1v** [comment]
See discussion for API 19: https://github.com/Genymobile/scrcpy/issues/98

**Comment by eku** [comment]
ty

**Comment by Lokawn** [comment]
My device is running Android 7.0 and still scrcpy crashed 2 times back to back.
Device is Moto G5 Plus 4GB variant

**Comment by rom1v** [comment]
> My device is running Android 7.0 and still scrcpy crashed 2 times back to back.

Interesting. How did it crash (which error messages)?

`Segmentation fault`? Error logs in `adb logcat`?
