### ISSUE TITLE
Bug: completely white window content

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Genymobile/scrcpy#1740]
- [V] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [V ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
Windows
 - scrcpy version: [e.g. 1.12.1]
scrcpy v1.16
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
Zipped file (64bit)
 - device model:
Pixel 4 (Android 11 beta 3) and Galaxy Note 8 (Android 8)
 - Android version: [e.g. 10]
Written above.
**Describe the bug**
I launch it, and I see a white window. It does support controlling, but it keeps being white:

![image](https://user-images.githubusercontent.com/5357526/92324182-f14e3480-f047-11ea-9eca-4ba39b131a39.png)

I tried to restart the PC, I tried to restart the device. I tried to connect via Wifi (adb connect).
Also tried to disable developer options and re-enable it (with USB debugging).

If you know of a workaround, please let me know. :(

**Comment by rom1v** [comment]
If you record, is it white?

```
scrcpy -r file.mkv
```

**Comment by AndroidDeveloperLB** [comment]
@rom1v No idea if it should be this way, but this video might have some glitches (maybe because now I'm on Wifi and not USB), and works only on VLC for me, and not on MPC (on MPC it is shown as complete black).

Other than that, seems to be fine.

Example video:

[file.zip](https://github.com/Genymobile/scrcpy/files/5179511/file.zip)

I also tried to take a screenshot using Android Studio. Works fine. However, when trying to take a video, it produces something similar to ScrCpy: a file that can be opened via VLC but not via MPC:

[device-2020-09-06-135825.zip](https://github.com/Genymobile/scrcpy/files/5179513/device-2020-09-06-135825.zip)

Could it be a codec issue on Windows OS ?

**Comment by AndroidDeveloperLB** [comment]
OK I think I know when this occurs, just don't know why.
It also occurs for the emulator, BTW.

I have a remote control of the laptop that has ScrCpy running on. I use "NoMachine" app for it.
And, since I don't need the laptop to have its lid opened (because of remote control), I close it.

When this occurs, I see white content on the emulator and on ScrCpy. When I open the lid, it works fine.

Might be an issue with Windows or NoMachine, no?

**Comment by AndroidDeveloperLB** [comment]
Seems so. Reported here:
https://issuetracker.google.com/issues/167880509

And closing here.
Sorry for the false report. Seems this affects both ScrCpy and emulator.
