### ISSUE TITLE
scrcpy doen't start

### ISSUE THREAD

**Issue by SrError** [Genymobile/scrcpy#1742]
If I run scrcpy I get the following error:

* daemon not running; start now at tcp:5037
adb: CreateFile@ 'nul' failed: The System can not find the specific archive. <2>
* failed to start daemon
adb: error: failed to get feature set: cannot connect to daemon
ERROR: "adb push" returned with value 1

How to fix it?

**Comment by da-danrley** [comment]
como corrigi-lo esse erro?

**Comment by rom1v** [comment]
This is an `adb` issue.

What is the result of `adb devices`?

**Comment by da-danrley** [comment]
![image](https://user-images.githubusercontent.com/70914611/92415277-92171f80-f12e-11ea-9693-cfea5c58230f.png)

**Comment by da-danrley** [comment]
o que posso fazer ?

**Comment by rom1v** [comment]
Did you enable USB debugging?

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#device-not-detected

**Comment by da-danrley** [comment]
não, não consigo habilitar a depuração USB, pois o dispositivo estar com o display quebrado !

**Comment by rom1v** [comment]
OK but without USB debugging you can't connect to adb, so scrcpy can't work.
