### ISSUE TITLE
Unable to start scrcpy - message "Aborted"

### ISSUE THREAD

**Issue by devmoksh** [Genymobile/scrcpy#1746]
- [✓ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [✓ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: 1.16
 - installation method: Windows release
 - device model: Swift 2 Plus
 - Android version: 8.1.0

**Describe the bug**
I downloaded the Windows release from the Genymobile/scrcpy page and it was working perfectly before but at that time it was connected by USB.
I wanted for it to work wirelessly so I restarted ADB in TCP/IP by running the command ```$ adb tcpip 5555``` and after trying that it was working wirelessly as well.
Then, I came across this warning: ``` adb server version (41) doesn't match this client (40); killing... ``` but it was carrying on well.
So because my Android Studio version of ADB was before scrcpy in the PATH, I moved it up and then whenever I ran it from anywhere except the directory where I installed scrcpy, it would give me the error ``` adb: error: cannot stat 'scrcpy-server.jar': No such file or directory ```.
I looked up that I would need to set the environment variable SCRCPY_SERVER_PATH to the full path of the scrcpy-server.jar file and I did so.
Then I ran scrcpy after restarting Command Prompt and then it started to download something (I think) and then it stopped working. Then, I removed the environment variable and now, no matter if the environment variable is there or not, it gives me this error ``` path-to-my-scrcpy-folder\scrcpy-server: 1 file pushed, 0 skipped. 9.6 MB/s (33622 bytes in 0.003s)
Aborted```.
I am unable to fix this. I have already tried re-installing the program but that hasn't worked out for me. I would appreciate any help given. If you need anymore details, be sure to ask.

**Comment by rom1v** [comment]
> I moved it up and then whenever I ran it from anywhere except the directory where I installed scrcpy, it would give me the error `adb: error: cannot stat 'scrcpy-server.jar': No such file or directory`.

That's not expected on recent versions. Did you always used v1.16?

I guess at some time you passed a wrong `SCRCPY_SERVER_PATH` (pointing to a directory), so it ended up create a directory `/data/local/tmp/scrcpy-server.jar` (which, again, should not happen anymore in recent versions).

What is the result of:
```
adb shell ls -l /data/local/tmp
```
?

**Comment by devmoksh** [comment]
Hello @rom1v,
> Did you always used v1.16?

I'm sure I did always use v1.16, this is only a week ago when I got these errors.

The result of `adb shell ls -l /data/local/tmp` is 

**`drwx--x--x 3 shell shell 4096 2020-09-04 20:00 oat`
`drwxrwxrwx 3 shell shell 4096 2020-07-07 18:34 perfd`
`drwxrwxrwx 3 shell shell 4096 2020-09-08 19:48 scrcpy-server.jar`
`-rw-rw-rw- 1 shell shell   40 2020-07-01 14:49 sky.com.example.app_widgets.sha1`
`-rw-rw-rw- 1 shell shell   40 2020-09-01 19:46 sky.com.example.shop_app.sha1`
`-rw-rw-rw- 1 shell shell   40 2020-09-01 20:11 sky.com.example.startup_namer.sha1`**
. (The bottom three are the apps I was developing a few months ago)

**Comment by rom1v** [comment]
> The files showing up in the scrcpy-server.jar directory are attached

Ok so the cause of your problem is that in a previous version (v1.8), you wrongly set `SCRCPY_SERVER_PATH` to your scrcpy directory (instead of the full path to the *file* `scrcpy-server`). As a result, it executed `adb shell push /your/directory /data/local/tmp/scrcpy-server.jar` (to avoid this problem, recent versions do a sanity check that the variable does not point to a directory). As a consequence, it attempts to execute `scrcpy-server.jar` via `app_process`, but it's a directory, so it fails and abort.

You should unset `SCRCPY_SERVER_PATH`, and remove the directory from the device:
```
adb shell rm -rf /data/local/tmp/scrcpy-server.jar
```

Then, scrcpy should work as expected.

**Comment by devmoksh** [comment]
Dear @rom1v, 

Yes, that worked fine and now I am able to run scrcpy without any issues. Thank you for the support and the prompt replies to my comments. You have developed a very good application and it is very useful. 

Thank you again,

devmoksh
