### ISSUE TITLE
copy paste from pc to device is not working

### ISSUE THREAD

**Issue by kingk110** [Genymobile/scrcpy#1750]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: win10
 - scrcpy version: 1.16
 - installation method: Windows release
 - device model: samsung s7 edge
 - Android version: 8

I am trying to copy paste from the pc to the device but it working only with MOD+Shift+v which sometimes take long time and is limited to 300 characters as I noticed. the copy from the device to PC is working well. When I was writing the bug I noticed that MOD+v is working on chrome app on android but on whatsapp or memo or other app will not work. what could be the reason?

**Comment by rom1v** [comment]
> When I was writing the bug I noticed that MOD+v is working on chrome app on android but on whatsapp or memo or other app will not work. what could be the reason?

<kbd>MOD</kbd>+<kbd>v</kbd> just inject the keycode <kbd>PASTE</kbd>. You can reproduce manually with:

```
adb shell input keyevent PASTE
```

If it does not work on some apps with that key (once you copied some text on the device), then it is not handled correctly by the device or app.

Did you try <kbd>Ctrl</kbd>+<kbd>v</kbd>?

https://github.com/Genymobile/scrcpy#copy-paste

**Comment by kingk110** [comment]
> > When I was writing the bug I noticed that MOD+v is working on chrome app on android but on whatsapp or memo or other app will not work. what could be the reason?
> 
> MOD+v just inject the keycode PASTE. You can reproduce manually with:
> 
> ```
> adb shell input keyevent PASTE
> ```
> 
> If it does not work on some apps with that key (once you copied some text on the device), then it is not handled correctly by the device or app.
> 
> Did you try Ctrl+v?
> 
> https://github.com/Genymobile/scrcpy#copy-paste

Yes the Ctrl+v will always paste what is in the device clipboard and what was copied from the pc. is there some shortcut to force sync the new copied text on pc to the android clipboard. because I also noticed that when you are typing in chrome the show clipboard option is disabled and if you use Ctrl+c Ctrl+v it will work with no problems.

**Comment by rom1v** [comment]
> Yes the Ctrl+v will always paste what is in the device clipboard and not what was copied from the pc

In theory, pressing <kbd>Ctrl</kbd>+<kbd>v</kbd> first synchronizes the computer clipboard to the device clipboard: 7683be8159c7372c7def0b868ba76a426fa7426e

So it seems that for some reason setting the device clipboard is "broken" on your device.

Is your device root? See #1678

**Comment by kingk110** [comment]
> In theory, pressing Ctrl+v first synchronizes the computer clipboard to the device clipboard

you mean it should show something in the adb window that text was copied or something like 

> INFO: Device clipboard copied
 that i ma getting when I copy from device

> Is your device rooted? See #1678

no my device is not rooted

**Comment by rom1v** [comment]
> you mean it should show something in the adb window that text was copied or something like
> > INFO: Device clipboard copied

Yes, exactly:

> INFO: Device clipboard set

https://github.com/Genymobile/scrcpy/blob/0be766e71a30eec1709da7b24999b6df2b40dc65/server/src/main/java/com/genymobile/scrcpy/Controller.java#L259-L262

**Comment by kingk110** [comment]
> > you mean it should show something in the adb window that text was copied or something like
> > > INFO: Device clipboard copied
> 
> Yes, exactly:
> 
> > INFO: Device clipboard set
> 
> https://github.com/Genymobile/scrcpy/blob/0be766e71a30eec1709da7b24999b6df2b40dc65/server/src/main/java/com/genymobile/scrcpy/Controller.java#L259-L262

but when I am pressing ctrl+c on the pc no info is shown on the adb window.

**Comment by rom1v** [comment]
> but when I am pressing ctrl+c on the pc no info is shown on the adb window.

That's expected (even if confusing).

<kbd>Ctrl</kbd>+<kbd>c</kbd> is injected to the device, as <kbd>Ctrl</kbd> and <kbd>c</kbd>, scrcpy has "no idea" that it will copy (sometimes, for example in Termux, it does something else). It's the system/app which decide what to do on this key combination.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/issues/1771#issuecomment-704507891

**Comment by rom1v** [comment]
`--legacy-paste` option merged in `dev`: d5f059c7cbef7d13889086670716d9f33f805dc4
