### ISSUE TITLE
when running scrcpy in RPi terminal it gives "bash: scrcpy: command not found"

### ISSUE THREAD

**Issue by sidrah20** [Genymobile/scrcpy#1763]
following are the steps i followed
1) pi@pi:~/Desktop $ git clone https://github.com/Genymobile/scrcpy.git

2) pi@pi:~/Desktop $ sudo apt install ffmpeg libsdl2-2.0-0 adb

3) pi@pi:~/Desktop $sudo apt install gcc git pkg-config meson ninja-build \
                 libavcodec-dev libavformat-dev libavutil-dev \
                 libsdl2-dev

4) pi@pi:~/Desktop $ wget -c https://github.com/Genymobile/scrcpy/releases/download/v1.16/scrcpy-server-v1.16

5) pi@pi:~/Desktop$ mv scrcpy-server-v1.16 scrcpy-server-v1.16.jar 

6) pi@pi:~ /Desktop$ sudo cp scrcpy-server-v1.16.jar /usr/local/bin

7) pi@pi:~ /Desktop$ cd scrcpy

8) pi@pi:~ /Desktop/scrcpy$  meson x --buildtype release --strip -Db_lto=true     -Dprebuilt_server=../scrcpy-server-v1.16.jar

9) pi@pi:~ /Desktop/scrcpy$ ninja -Cx

10) pi@pi:~$ adb devices

***all went well till here*** 
but after 

11) pi@pi:~$ scrcpy

bash: scrcpy: command not found

please help!

**Comment by rom1v** [comment]
After `ninja -Cx`, it is just built but not installed.

You can run it with `./run x`.

But then you probably want to install: `sudo ninja -Cx install`.

Btw, I don't get why all this renamings and copies of `scrcpy-server-v1.16`. You could remove steps 5 and 6, and do not put `.jar` in step 8.

**Comment by sidrah20** [comment]
thank u so much it works!
but its really slow even its connected with a wire and i want to run it wireless is there anyway to get rid of the lagging problem.
and how can i start it automatically when my RPi boots up, so that i don't have to run scrcpy every time.

**Comment by rom1v** [comment]
> but its really slow

rpi 3 or 4?

**Comment by sidrah20** [comment]
rpi 3

**Comment by rom1v** [comment]
OK, that's "expected" then, the HW acceleration won't work. On rpi 4 it should work.

**Comment by sidrah20** [comment]
ok...
and is there any way that it runs automatically every time whe rpi 3 boots up??

**Comment by rom1v** [comment]
Check on your distrib how to start a program on start.

You could also check [`autoadb`](https://github.com/rom1v/autoadb) to start scrcpy whenever a device is connected.
