### ISSUE TITLE
All browsers freeze until I close Scrcpy / disconnect phone

### ISSUE THREAD

**Issue by tordenflesk** [Genymobile/scrcpy#1766]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: 1.16
 - installation method: Chocolatey
 - device model: Moto G5 Plus / XT1685 (Potter)
 - Android version: 10, HavocOS

**Describe the bug**
All browsers (Chrome, Firefox, Vivaldi) freeze until I close Scrcpy / disconnect phone. Navigating to a URL the site "loads" but the contents of the previous page remains. menus etc. work.

**Comment by rom1v** [comment]
Did you turn the screen off on the physical device? #836

**Comment by tordenflesk** [comment]
Yup. That's annoying. Guess I'll look for a browser that's not affected by this, or keep the screen on in the meantime..

**Comment by rom1v** [comment]
OK, then I'm closing as a duplicate.

**Comment by gnumoksha** [comment]
> Yup. That's annoying. Guess I'll look for a browser that's not affected by this, or keep the screen on in the meantime..

Firefox beta works
