### ISSUE TITLE
Gamepad support

### ISSUE THREAD

**Issue by hsyn006** [Genymobile/scrcpy#1769]
Hi ! I want help from you about a problem about scrcpy. my problem is that when i enter pubg with panda (also when i enter normally) only a, w, s, d keys work on the keyboard. I can't use or key with panda, is there a solution to this? If so, could you please write?

**Comment by rom1v** [comment]
I don't know what is panda :panda_face:

**Comment by hsyn006** [comment]
> I don't know what is panda

octopus-like gamepad program, panda gamepad pro write google

**Comment by rom1v** [comment]
OK Game controllers are not managed.

https://wiki.libsdl.org/CategoryJoystick

**Comment by rom1v** [comment]
Duplicate of #99
