### ISSUE TITLE
Mixed colors (ghost pictures) on Android 8.0

### ISSUE THREAD

**Issue by manfred-mp** [Genymobile/scrcpy#177]
Great tool! However after updated some devices to Oreo colors started to be scrambled. Here is a picture how it looks like. Device used is Nokia 3. And this is happening on both scrcpy versions, 1.1 and 1.2.
![nokia-3_api-26](https://user-images.githubusercontent.com/1030705/41524721-0e6375e8-72e7-11e8-8684-daa20178244c.jpg)

**Comment by manfred-mp** [comment]
Looks ok when recorded.
[test.zip](https://github.com/Genymobile/scrcpy/files/2110498/test.zip)

**Comment by SamuraiWaffle** [comment]
This happens to me as well on a specific tablet. However the tablet is cracked and I assumed it is more of a hardware issue.

However there is one time I loaded it up and it worked fine.

**Comment by manfred-mp** [comment]
After update to Android 8.1 it works again. Must be something in 8.0 only.

**Comment by manfred-mp** [comment]
Hi, good news is that v1.4 fixed this. Can be closed, thx!

**Comment by rom1v** [comment]
Cool, it's probably related to the update of FFmpeg, then.

**Comment by jokboy15** [comment]
why my screen in scrcpy when landscaping always mixed color.

**Comment by soodsid** [comment]
@jokboy15 same problem... the device is realme 1 running on android 9 ... in portrait everything works great but in landscape color become ghost same as @manfred-mp screenshot (but in landscape) ... also tried using scrcpy -r to record... same result in that recording

**Comment by shanu2000** [comment]
Any solution For Realme 1 mixed colour issue. Please Reply

**Comment by ketan-agrawal1** [comment]
Same problem on my Realme 1 too.

**Comment by habibsyuhada** [comment]
same here, in oppo

**Comment by dopheideb** [comment]
I have the same problems with both scrcpy 1.14 and screenrecord on Blackview BV9000Pro (Android 8.0). The workaround I use, is to request a somewhat smaller screen size (resized at device).

My touch screen is 1080x2180 (portrait).
max OK: `scrcpy  --max-size 1920`
max OK: `adb exec-out screenrecord --output=h264 --size=1920x960 /proc/self/fd/1 | ffplay -`
min NOT OK: `scrcpy  --max-size 1928`
min NOT OK: `adb exec-out screenrecord --output=h264 --size=1920x960 /proc/self/fd/1 | ffplay -`

So I'm guessing it is not an scrncpy issue. I'm hoping my workaround is use for others too.

**Comment by jokboy15** [comment]
mine is ok.
scrcpy: -m 1280

output-ok

**Comment by yatotz** [comment]
https://www.youtube.com/watch?v=nasWevxa3p4

it works
