### ISSUE TITLE
Mutex stay locked after return.

### ISSUE THREAD

**Issue by lordnn** [Genymobile/scrcpy#1770]
https://github.com/Genymobile/scrcpy/blob/c136edf09d54b4f61e27577622e7ba93f72acb0f/app/src/recorder.c#L364
https://github.com/Genymobile/scrcpy/blob/c136edf09d54b4f61e27577622e7ba93f72acb0f/app/src/recorder.c#L370

Looks like a bug.

**Comment by rom1v** [comment]
:+1: Yes, it might deadlock on error.

Do you want to open a PR to fix it?

Thank you
