### ISSUE TITLE
adb: error: failed to get feature set: more than one device/emulator. How do I fix this?

### ISSUE THREAD

**Issue by TheCrystalAssassin** [Genymobile/scrcpy#1772]
- [yes] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [yes] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: 1.16
 - installation method: Manual
 - Android version: 10

Every time I try to open scrcpy I get this error: adb: error: failed to get feature set: more than one device/emulator. even though the only device i ever used is my Android phone and it one day started giving me this error. I looked at a post about it and it didn't help me at all. does anybody know how I can fix this?

**Comment by rom1v** [comment]
What is the result of `adb devices`?

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#several-devices-connected

**Comment by TheCrystalAssassin** [comment]
I tried using that and it told me the command abd does not exist

**Comment by rom1v** [comment]
Press Windows+r, open `cmd.exe`.

In the terminal, go to thebscrcpy directory:

    cd C:\.....your\scrcpy\directory

Then execute `adb devices`.

**Comment by cylee0909** [comment]
> I tried using that and it told me the command abd does not exist

emm , it's 'adb devices' , but you type 'abd'.

**Comment by TheCrystalAssassin** [comment]
> > I tried using that and it told me the command abd does not exist
> 
> emm , it's 'adb devices' , but you type 'abd'.

It just told me the command type abd does not exist

**Comment by rom1v** [comment]
adb not abd

**Comment by char101** [comment]
In the scrcpy folder there is an executable file named `adb.exe`. You need to run command prompt, `cd` to the scrcpy folder, then run `adb.exe devices`.

**Comment by firex726** [comment]
I'm having the same issue...

`C:\Users\firex\Downloads\scrcpy-win64-v1.16>scrcpy.exe
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: no devices/emulators found
ERROR: "adb push" returned with value 1
Press any key to continue...


C:\Users\firex\Downloads\scrcpy-win64-v1.16>adb devices
List of devices attached


C:\Users\firex\Downloads\scrcpy-win64-v1.16>`

**Comment by rom1v** [comment]
Your device is not detected by adb: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#device-not-detected

**Comment by kolox-afk** [comment]
I'm having the same issue...
d:scrcpy>scrcpy.exe -sw
INFO:scrcpy 1.16 <https:github.com/Genymobile/scrcpy>
*daemon not running; starting now at tcp:5037
*daemon started succesfully
adb: eror: failer to get  features set: device unautorize.
this adb server's $ADB_VENDOR_KEYS is not set
Otherwise check for a confirmation dialog on your device.
EROR: "adb push" returned with value 1
press any key to continue ...

**Comment by rom1v** [comment]
again: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#device-not-detected

**Comment by iammultiman** [comment]
Got the same error when more than one phone was connected.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#several-devices-connected

**Comment by Orion-wmk** [comment]
I had the same problem recently.
The solution I found was to not run other android emulators like bluestacks.
I noticed I had this problem whenever I had bluestacks running so closing any android emulator should fix the problem.
It did for me
