### ISSUE TITLE
Append title to window

### ISSUE THREAD

**Issue by fefo-dev** [Genymobile/scrcpy#1774]
There's a number of features that don't play together well and I'm using a shortcut for each as a profile, but it gets confusing as most don't change the window in any way.

A quick solution I thought was appending a description over/with the device name. Dunno if this can be easily done through each OS or another flag is required, but an --append-title "My gaming profile" doesn't sound too damaging in my head.

Thanks as always.

**Comment by rom1v** [comment]
One solution could be to introduce variable replacement in the title (replaced on the server side). See #606

```
scrcpy --window-title '%n My gaming profile'
```

But it's not implemented.

A workaround is to first retrieve the device name via `adb` then use it in the title:

```bash
scrcpy --window-title "$(adb shell getprop ro.product.model) My gaming profile"
```

**Comment by fefo-dev** [comment]
So... the flag already exists? lol

The append part was a what if scenario, for those who want to keep the model (multiple phones, etc). The --window-title is exactly what I needed, so I'm closing it since I don't see much beyond the referenced issue. Thanks a lot, had no luck with the search and might glossed over an important thing or two.
