### ISSUE TITLE
Record with audio

### ISSUE THREAD

**Issue by HexTr0n** [Genymobile/scrcpy#1778]
I have tried scrcpy. I WORK PERFECT for me but I wanted to record some of the clip but it lag with audio .

SO PLEASE Add recording with audio too.

**Comment by rom1v** [comment]
See https://github.com/Genymobile/scrcpy#audio-forwarding and #14.

**Comment by DiSavi** [comment]
Waiting for device...
Performing Streamed Install
adb: failed to install sndcpy.apk: Security exception: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag

java.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag
        at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:548)
        at com.android.server.pm.PackageInstallerService.createSession(PackageUninstalling existing version first...
Success
Performing Streamed Install
adb: failed to install sndcpy.apk: Security exception: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag

java.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag
        at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:548)
        at com.android.server.pm.PackageInstallerService.createSession(PackageFailed with error #1.
Press any key to continue . . .

is this how should be>?

**Comment by rom1v** [comment]
See https://github.com/rom1v/sndcpy/issues/39.
