### ISSUE TITLE
Accents sending double letters

### ISSUE THREAD

**Issue by Tokolino** [Genymobile/scrcpy#1779]
When typing a letter that is composed by first typing some kind of modification (´, `, ^,...) and then the letter to modify (mostly e, a, o and u) to get é, è, à and so on, the result I get when I type this is eè, eé, aà and so on - so there is one letter too much.

I am using Version 1.16 on Windows 10 (1909) and Sony G8441 (Android 9)

**Comment by rom1v** [comment]
Use `scrcpy --prefer-text`.

See c916af0984f72a60301d13fa8ef9a85112f54202 and #650

**Comment by Tokolino** [comment]
Thanks a lot! I was searching for one like this but did not find it.
