### ISSUE TITLE
If connected wireless need to disconnect via usb

### ISSUE THREAD

**Issue by VarunSaiTeja** [Genymobile/scrcpy#178]
First i connected my mobile to pc with usb and opened this tool, its working
but  when i connected my mobile wireless i need to disconnect my mobile from pc via usb to use this tool

**Comment by rom1v** [comment]
What is the result of `adb devices`?

If the same device appears several times, you need to specify the one you want:

    scrcpy -s 192.168.0.42:5555

**Comment by VarunSaiTeja** [comment]
yeah its showing multiple times
i mentioned device serial there
you can close this issue
