### ISSUE TITLE
Installation problem on RPi4B Raspios

### ISSUE THREAD

**Issue by frankgould** [Genymobile/scrcpy#1780]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Raspios 5.4.51-v7l+ #1333
 - scrcpy version: 1.16
 - installation method: manual build
 - device model: 4B
 - Android version: 6 (Not applicable)

**Describe the bug**
SCRCPY Installation on RPi4B does not appear to work with the instructions provided. I downloaded and saved the prebuilt server. I then cloned scrcpy and executed the following commands to build a version with the prebuilt server. Then copied the prebuilt server into the scrcpy folder.

```
git clone https://github.com/Genymobile/scrcpy
cd scrcpy
meson x --buildtype release --strip -Db_lto=true -Dprebuilt_server=/home/fgould/build/scrcpy/scrcpy-server
Directory already configured.

Just run your build command (e.g. ninja) and Meson will regenerate as necessary.
If ninja fails, run "ninja reconfigure" or "meson --reconfigure"
to force Meson to regenerate.

If build failures persist, run "meson setup --wipe" to rebuild from scratch
using the same options as passed when configuring the build.
To change option values, run "meson configure" instead.
```
On errors, please provide the output of the console (and `adb logcat` if relevant).
None of the suggestions following the 'already configured' message. When I try to run the app, I get the following error:
```
./run x
./run: line 23: x/app/scrcpy: No such file or directory
```

**Comment by rom1v** [comment]
`-Dprebuilt_server=~/build` is incorrect. `-Dprebuilt_server=/home/fgould/build/scrcpy/scrcpy-server` is better.

```bash
cd scrcpy
meson x --buildtype release --strip -Db_lto=true -Dprebuilt_server=~/build
sudo ninja -Cx install
```

You must execute `ninja -Cx` as non-root before calling `sudo ninja -Cx install`:

> Note: `ninja` [must](https://github.com/Genymobile/scrcpy/commit/4c49b27e9f6be02b8e63b508b60535426bd0291a) be run as a non-root user (only `ninja install` must be run as root).

https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#common-steps

> Directory already configured.

```bash
rm -rf x
```

and restart.

**Comment by frankgould** [comment]
Thanks for the quick response. I pasted too much of my notes into the original post and I've corrected it. I tried your suggestion with `ninja -Cx` and got the following response:
```
ninja: Entering directory `x'
ninja: error: '/home/fgould/build/scrcpy/~/build', needed by 'server/scrcpy-server', missing and no known rule to make it
```

**Comment by frankgould** [comment]
That worked after I deleted and rebuilt using meson. Thank you.
