### ISSUE TITLE
No sound on the windows version of scrcpy

### ISSUE THREAD

**Issue by MODAKUNE** [Genymobile/scrcpy#1781]
Hello, I am having an issue with the sound. 
I am trying to use scrcpy, and the screen part works fine, but there is no sound at all, how can I fix this? 
I am on a Windows 10 PC using the USB Debugging mode on my tablet, and my tablet is an Android 9 Samsung tab A. 
Thanks in advance!

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy#audio-forwarding
