### ISSUE TITLE
brew install scrcpy says no available formula with the name "scrcpy"

### ISSUE THREAD

**Issue by mahdi-jafaree** [Genymobile/scrcpy#1782]
Hi, i just installed brew using 

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
```

 and what i see as output is:
```
Updating Homebrew...
Error: No available formula with the name "scrcpy" 
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

I dont know why am i getting this while this (scrcpy) is on the brew website.

**Comment by babu1998** [comment]
install brew properly. I just installed everything by copy pasting from readme in my MacOs

**Comment by mahdi-jafaree** [comment]
Yes, the problem was with brew, but Idk what was wrong. btw I upgraded to Catalina MacOs and everything is fine! ;)

**Comment by 18518933040** [comment]
why close.I have the question.

**Comment by mahdi-jafaree** [comment]
which MacOs you are using and which brew are you working?
re-install the brew and try again.

**Comment by nzynb** [comment]
Hello! I'm having the same problem, I've installed and re-installed but nothing changed. My mac has been updated to macOS Monterey and my homebrew is ver. Homebrew 3.5.2-53-gd23dba6. I'm a newbie at this and was wondering if I'm doing something wrong and if there is anything I could do to fix this problem.

**Comment by uditshoprtv** [comment]
I am also facing same issue, currently I am macOs Monterey.

No available formula with the name "scrcpy".
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

**Comment by Sibz23** [comment]
I am also facing this issue. 
On MacOS Monterey.
Homebrew 3.6.3-16-g76b87c4
I am trying to install scrcpy.
Uninstalled the brew and re installed it. What could be the issue?

**Comment by nickyvo8910** [comment]
I'm getting this from "brew doctor".
```
Warning: Homebrew/homebrew-core was not tapped properly! Run:
  rm -rf "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core"
  brew tap homebrew/core
```
=> Retapping the core helped.
