### ISSUE TITLE
prebuilt-deps Makefile

### ISSUE THREAD

**Issue by igolf-plat** [Genymobile/scrcpy#1784]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Ubuntu 18.04

**Describe the bug**
I want to  cross-compile scrcpy to win32 on my Ubuntu host, and I find that in prebuilt-deps/Makefile the domain **ffmpeg.zeranoe.com** does not exist any longer. And the build job fails to download win32 shared lib.

**Comment by npes87184** [comment]
Same problem as #1753
