### ISSUE TITLE
preloading public library dlopen failed.

### ISSUE THREAD

**Issue by DubuDubu** [Genymobile/scrcpy#1785]
Hi, I try to run scrcpy,

Output is below.

INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
D:\scrcpy\scrcpy-server: 1 file pushed. 7.3 MB/s (26202 bytes in 0.003s)
Error preloading public library libcrypto.solibsvrapi.so: dlopen failed: library "libcrypto.solibsvrapi.so" not found
Aborted (core dumped)

**Comment by rom1v** [comment]
Which platform? How did you install it? Why an old version?

It looks a problem on the device side. Do you see the message in `adb logcat`?

**Comment by DubuDubu** [comment]
it was my device error.
Sorry.
