### ISSUE TITLE
[server] WARN: Could not inject char u+597d

### ISSUE THREAD

**Issue by lygstate** [Genymobile/scrcpy#1786]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
Windows
 - scrcpy version: [e.g. 1.12.1]
1.16
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
Windows release
 - device model:
Xiaomi 8
 - Android version: [e.g. 10]

**Describe the bug**
Can not input chinese directly

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#special-characters-do-not-work

**Comment by zhudada-1994** [comment]
PS C:\Users\zhuhaizhou> scrcpy
scrcpy 2.1.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)              1255b76b            device  2211133C
C:\Users\zhuhaizhou\AppData\Local\Microsoft\WinGet\Package... file pushed, 0 skipped. 21.8 MB/s (56995 bytes in 0.002s)
[server] INFO: Device: [Xiaomi] Xiaomi 2211133C (Android 13)
INFO: Renderer: direct3d
INFO: Texture: 1080x2400
[server] INFO: Device screen turned off
[server] WARN: Could not inject char u+4e0b
[server] WARN: Could not inject char u+5076
[server] WARN: Could not inject char u+89c1
