### ISSUE TITLE
Pressing tab behavior

### ISSUE THREAD

**Issue by sabitm** [Genymobile/scrcpy#1793]
First, i want to say thank you so much for developing this great app. It has been my life saver since. Controlling distant android device never been easier. Thanks!

I'm using scrcpy for pretty much all things. And i use it heavily for chatting with people (through whatsapp, line, etc.). When i have to chat with people using whatsapp, i'm used to write a message and press **tab twice** to reach send button and then press enter to send the message. In this case, tab key behave like a navigation between widget (or View?) on android application, and it's the same with arrow key. Lately (Sorry i forget the exact timing. Maybe two to four weeks ago), the behavior changed. Now pressing tab will give you literal tab character (Like when you pressing tab when editing text through notepad). So, i have to click send button using mouse each time i want to send a reply.

This is the screenshot.
[![wa-tab.png](https://i.postimg.cc/Mpzt2Ys3/wa-tab.png)](https://postimg.cc/hf3VVVRV)

Is it intended change on this tab and arrow key behavior? Can i have the old behavior back?

**Comment by rom1v** [comment]
<kbd>Tab</kbd> is just injected to the device, and the system/app on the device handles it.

**Comment by sabitm** [comment]
Ahh... right. Why i'm not thinking about this. So, maybe this is whatsapp's issue then. Thanks for your answer
