### ISSUE TITLE
Oppo F9 touch doesn't work

### ISSUE THREAD

**Issue by Souravgoswami** [Genymobile/scrcpy#1796]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Arch linux x86-64
 - scrcpy version: 1.16
 - installation method: AUR
 - device model: Oppo F9
 - Android version: 10

**Describe the bug**
Most of the controls including back button works, but I can't control my phone using the cursor (touch from scrcpy doesn't work).
I have tried another phone, Moto C, which works just fine.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work

**Comment by Souravgoswami** [comment]
Sorry, I can't test for now. The reason being the phone not mine but of one of my neighbours!!  What I can remember is that I was unable to find the settings "USB Debugging (Security Settings)" on the phone. Tried other options, too, but failed to make the keyboard and mouse working!

This issue can be closed, because I can't post logs, etc.
I can find a similar issue [here:  Scrcpy interaction with OPPO Phone is not working #1518](https://github.com/Genymobile/scrcpy/issues/1518)
