### ISSUE TITLE
adb process not closing

### ISSUE THREAD

**Issue by Martinligabue** [Genymobile/scrcpy#1800]
- [ * ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ * ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: [e.g. 1.16]
 - installation method:  Windows release...
 - device model: Mi A2 Lite
 - Android version: 9

**Describe the bug**
After closing scrcpy, adb.exe process remains active in background using no cpu

**Comment by rom1v** [comment]
That's expected. See #205.
