### ISSUE TITLE
TCP/IP connection super-slow after initial setup.

### ISSUE THREAD

**Issue by ajgringo619** [Genymobile/scrcpy#1811]
**Environment**
 - OS: [Linux Mint 19.3 XFCE]
 - scrcpy version: [1.14, 1.16]
 - installation method: [manual build]
 - device model: Nokia 3.1a
 - Android version: [9]

**Describe the bug**
I tried connecting to my phone via TCP/IP a week ago. The first time I connected, it was very fast (almost as fast as when connected via USB). Now, the screen redraws are so slow that it's become unusable. I moved to v1.16 yesterday - that didn't help. As far as actually connecting, that always works.

I'm wondering if the problem is that my PC is on 5G while my phone is on 2.4G; they're on separate SSIDs, but the same TCP/IP network (dual-band router).

**Comment by rom1v** [comment]
Does it work better if you reduce the bitrate (to 2Mbps for example):

```
scrcpy -m1024 -b2M
```

**Comment by ajgringo619** [comment]
That is definitely faster, but the screen quality really suffers. I think I will stick with the USB connection; I can watch streaming services with it and the lag is insignificant.

**Comment by rom1v** [comment]
The wireless performance depends both on your wireless connection and on the device model/software.
