### ISSUE TITLE
adb push issue

### ISSUE THREAD

**Issue by SecretAgentAgentX** [Genymobile/scrcpy#1812]
I'm running a Arch based distro and just installed Scrcpy from AUR and when I attempt to launch it I get the below. I have developer mode turned on on the phone.

```
[alienprober@TheMotrhership ~]$ scrcpy
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
* daemon not running; starting now at tcp:5037
* daemon started successfully
adb: error: failed to get feature set: no devices/emulators found
ERROR: "adb push" returned with value 1
[alienprober@TheMotrhership ~]$ sudo su
[sudo] password for alienprober: 
[root@TheMotrhership alienprober]# scrcpy
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: no devices/emulators found
ERROR: "adb push" returned with value 1
[root@TheMotrhership alienprober]# 

```

**Comment by rom1v** [comment]
Your device is not detected by `adb`. Check `adb devices`.

This is probably related to udev rules: https://wiki.archlinux.org/index.php/Android_Debug_Bridge#Adding_udev_rules

**Comment by SecretAgentAgentX** [comment]
Decided to check debugging and some how it was turned off. Have to figure the last update, cause I noticed the day before yesterday WiFi was turned off.
