### ISSUE TITLE
PC mic not working on Discord when using scrcpy

### ISSUE THREAD

**Issue by alv09** [Genymobile/scrcpy#1814]
I'm mirroring my android screen to my PC and sharing my PC screen through Discord while talking with my friends. The PC mic stops workings when doing that.

Update: when I'm in a Discord voice chat and I launch scrcpy my mic stops working and I can't talk. But if I leave the channel and re-enter mic starts working again. I use Discord a lot with a lot of different games and this only happens when using scrcpy.

Any ideas?

**Comment by rom1v** [comment]
scrcpy does not do audio at all, so it's weird.

**Comment by fusionneur** [comment]
it s unrelated with scrcpy. looks like something in discord to me or your audio settings

**Comment by alv09** [comment]
Update: when I'm in a Discord voice chat and I launch scrcpy my mic stops working and I can't talk. But if I leave the channel and re-enter mic starts working again. I use Discord a lot with a lot of different games and this only happens when using scrcpy.

**Comment by rom1v** [comment]
Might be caused by the SDL initialization?

https://github.com/Genymobile/scrcpy/blob/25aff0093500c95c90192bc7e78f40ec3f617519/app/src/scrcpy.c#L78

Could you just add a `sleep()` after this call to see if your micro stops working after that.

**Comment by fusionneur** [comment]
> Update: when I'm in a Discord voice chat and I launch scrcpy my mic stops working and I can't talk. But if I leave the channel and re-enter mic starts working again. I use Discord a lot with a lot of different games and this only happens when using scrcpy.

I tried the same and for me mic continues working after I start sndcpy while I am in a discord voice chat.
You could try going to discord settings> voice & video> Input device > and selecting your microhpone from the list instead of leaving the Default one

**Comment by alv09** [comment]
First, thank you all for your answers. 

I have download and tried Samsung Flow, it also mirror my phone screen via USB and I have the same problem, so it must be something related with my USB ports. When I mirror the phone via Wifi I dont have any problem. Sorry and thank you :)

**Comment by Weebs4235632** [comment]
Hi, I know this post is already completed, but i was hoping someone can help me with my problem. 
![Screenshot 2024-03-11 013620](https://github.com/Genymobile/scrcpy/assets/162979595/bd15049f-4ab1-4c06-9888-8c20f812b644)
I am using Scrcpy 2.4 <android 14>. When I hop off voice call, audio forwarding to my headset works again. Please and thank you.

**Comment by Weebs4235632** [comment]
Thanks for the response, just went and check the other post you mention. So does that mean theres no way to audio forward voice calls?
