### ISSUE TITLE
Scrcpy ends the session if not started from terminal

### ISSUE THREAD

**Issue by maiconandsilva** [Genymobile/scrcpy#182]
I tried to make a desktop entry to start the program from the toolbar, but when I close it or unplug the USB cable it simply ends the session I am currently in (Ubuntu 17.10).

**Comment by rom1v** [comment]
Possibly related: https://github.com/Genymobile/scrcpy/issues/52

**Comment by rom1v** [comment]
Could you try with current `master`, I just fixed a bug that might explain the issue: https://github.com/Genymobile/scrcpy/commit/1a0139321b86cb42df66b134868643a0b572cecc
