### ISSUE TITLE
when Chinese path is too long

### ISSUE THREAD

**Issue by maryXielee** [Genymobile/scrcpy#1820]
I use the release version 1.16 and find that  when my Chinese path is a little long, it encountered the following problem:
ERROR: 'D:\Program Files\我的研究内容\我的投屏\platform-tools\sc\scrcpy-server' does not exist or is not a regular file
Press any key to continue...

But ,my file true path is 'D:\Program Files\我的研究内容\我的投屏\platform-tools\scrcpy\scrcpy-server'
Why the folder name 'scrcpy' changed to 'sc' in error message ?

It is support how long path? Could you support longer path?

Thanks.

**Comment by rom1v** [comment]
#1819
