### ISSUE TITLE
Move window when --window-borderless is passed

### ISSUE THREAD

**Issue by fusionneur** [Genymobile/scrcpy#1825]
Right now the windows seem to be stuck in place. How can one move it?

**Comment by rom1v** [comment]
It depends on your window manager.

On Linux with XFCE, it's <kbd>Alt</kbd>+click and move.

If your window manager (or windows) does not support moving and you want to move, do not use `--window-borderless`.

**Comment by shodanx2** [comment]
Hello,
I have a solution for this problem that could have a "curb cut" effect

scrcpy "mywindowtitle" 100 200 400 800

Send signal to scrcpy window with title mywindowtitle to move to position x=100 y=200 width=400 height=800

I'm trying to move a BUNCH of scrcpy window, but so far I have failed.
I am starting to think that scrcpy does not respond to normal window signals to move the window

I have been trying fruitlessly for a while now using commands like

nircmdc win move find title "cam1.lan" 100, 250, 300, 800

nircmdc win move find handle 00960B8A 100, 250, 300, 800

The command does not fail but also has no effect

**Comment by skygate2012** [comment]
@rom1v Care to implement this for Windows? It can be done simply by sending a message on mouse down: [Make a borderless form movable?](https://stackoverflow.com/questions/1592876/make-a-borderless-form-movable)
