### ISSUE TITLE
Getting Scrcpy to work with my Boox Nova 2

### ISSUE THREAD

**Issue by JewleZi** [Genymobile/scrcpy#1831]
Hello there folks, I'd be delighted to see if scrcpy could manage to work with e-Ink Tablets such as the Boox Nova 2. Ive tried to make it work but i think, the program just doesnt work that well with e-Ink as a whole. If it should work please inform me. The Tablet has Android 9 with enabled usb debugging, but when you start scrcpy up, you just get an endless loading session.

**Comment by rom1v** [comment]
See #1293.
