### ISSUE TITLE
dev branch server - Android 11

### ISSUE THREAD

**Issue by Mathew-D** [Genymobile/scrcpy#1832]
The server for 1.16 has the Android 11 Adapt call() on ContentProvider for error that was fixed on commit ae758f99d6af81123bb6b74d307d798c2c17acf3 in the dev branch but I can't seem to get it to build.  

Does anyone have the server with that commit built that can be posted for download or can that commit be added to the main server download.

Thanks.

**Comment by npes87184** [comment]
#1468 @rom1v has provided a server with the fixed commit.
