### ISSUE TITLE
Missing Turkish chars?

### ISSUE THREAD

**Issue by omerakgoz34** [Genymobile/scrcpy#1835]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10 v2004
 - scrcpy version: 1.16
 - installation method: Windows release via [scoop installer](https://scoop.sh)
 - device model: GM 5 Plus (shamrock) Android One Third Generation
 - Android version: 10 (LineageOS 17.1)

**Describe the bug**
Missing chars?
```
[server] WARN: Could not inject char u+0131 --> I
[server] WARN: Could not inject char u+011f --> ğ
[server] WARN: Could not inject char u+011e --> Ğ
[server] WARN: Could not inject char u+015f --> ş
[server] WARN: Could not inject char u+015e --> Ş
[server] WARN: Could not inject char u+0130 --> İ
```

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#special-characters-do-not-work

**Comment by omerakgoz34** [comment]
Oh, sorry.
