### ISSUE TITLE
Connect 2 devices at once one via usb one via wifi

### ISSUE THREAD

**Issue by LucaGabi** [Genymobile/scrcpy#1839]
- [ x ] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.
-----
**Is your feature request related to a problem? Please describe.**
.....
Connect 2 devices at once one via usb one via wifi
.......
......
**Describe alternatives you've considered**

**Additional context**

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#several-devices-connected

**Comment by GregoireMilliez** [comment]
I have the same issue, I can't connect to the wifi one, even with serial.

INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: device 'SERIAL' not found
ERROR: "adb push" returned with value 1
Press any key to continue...

It works fine when I have only 1 device with just "scrcpy" command

**Comment by rom1v** [comment]
You must pass the device as it is printed via `adb devices`. If it's connected by wifi, it's probably something like `scrcpy -s 192.168.x.x:5555`.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy#multi-devices
