### ISSUE TITLE
Request: avoid cancelling "show taps" when closing app

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Genymobile/scrcpy#184]
I like to have this option always turned on.
When I open the PC app scrcpy, and then close it later, it turns this feature off without asking.

Please don't modify this setting without asking.

**Comment by AndroidDeveloperLB** [comment]
I've enabled this parameter to affect other devices...

**Comment by rom1v** [comment]
Fixed: 4668638ee10764e8341c0770d548c0b74de69a8d

**Comment by AndroidDeveloperLB** [comment]
So how was it fixed?
It knows if it's enabled already, and then doesn't disable it when closing in case was already enabled?

**Comment by rom1v** [comment]
Yes.

**Comment by AndroidDeveloperLB** [comment]
Nice! Thank you!
