### ISSUE TITLE
Can you add a config file,so we can use scrcpy-noconsole with other parameter?

### ISSUE THREAD

**Issue by adasqg** [Genymobile/scrcpy#1840]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rom1v** [comment]
You could just create a `.bat` file containing for example:
```batch
scrcpy-noconsole -m800
```

**Comment by adasqg** [comment]
> You could just create a `.bat` file containing for example:
> 
> ```batchfile
> scrcpy-noconsole -m800
> ```

Thanks

**Comment by adasqg** [comment]
> You could just create a `.bat` file containing for example:
> 
> ```batchfile
> scrcpy-noconsole -m800
> ```

I try it. But find it still show a cmd window. What can I do for it?

**Comment by rom1v** [comment]
```
start scrcpy-noconsole.exe -m800
```

**Comment by adasqg** [comment]
> ```
> start scrcpy-noconsole.exe -m800
> ```

It works well, ths
