### ISSUE TITLE
It doesn't type Arabic letters

### ISSUE THREAD

**Issue by EgyptianM** [Genymobile/scrcpy#1841]
Does this program support typing in Arabic?

I tried it but it always type the English letter associated with the key of keyboard not the Arabic one even I switched language to Arabic in Windows and phone(which I think doesn't have anything to do in this case).

**Comment by rom1v** [comment]
No: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#special-characters-do-not-work

Duplicate of #37.
