### ISSUE TITLE
Can't control my CPH1861 device with windos

### ISSUE THREAD

**Issue by bhavyarbhatt** [Genymobile/scrcpy#1843]
Screen Mirroring is done but i can able to control my device with windos mouse or keyboard

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work

**Comment by bhavyarbhatt** [comment]
I had done USB Deb but then also can't able use it show error in cmd like 

[server] WARN: Ignore touch event, it was generated for a different device size

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/issues/1645#issuecomment-670433990

**Comment by bhavyarbhatt** [comment]
Using this command i can control with mouse and keyboard

scrcpy --max-size 1024
scrcpy -m1920
