### ISSUE TITLE
MSYS2 never installs dependencies successfully 

### ISSUE THREAD

**Issue by EgyptianM** [Genymobile/scrcpy#1847]
I'm struggling for 2 days now to get MSYS to install dependencies successfully with no luck

Always gives errors that the server returns error 404 for some files or any other errors

Is there any other way to build the code?

Can I use Code::Blocks or any other IDE to build and run the code?

I'm using windows 10 system.

**Comment by Biswa96** [comment]
This issue is related to MSYS2. Please open an issue [there][1]. FYI, there was an incident with main MSYS2 repo server ~1 month ago. But everything is stable now in MSYS2.

[1]: https://github.com/msys2/MINGW-packages/issues

**Comment by EgyptianM** [comment]
@Biswa96  Thank you very much

Is there any chance to use any IDE to build and run the code?

**Comment by Biswa96** [comment]
IDE does not matter. Here, scrcpy, there is an discussion about using GitHub Actions for Continuous Integration. If it is added then you will just need to fork this repository and click a button to trigger builds automatically.

**Comment by Biswa96** [comment]
IDE does not matter for building a project. Here, scrcpy, there is an discussion about using GitHub Actions for Continuous Integration. If it is added then you will just need to fork this repository and click a button to trigger builds automatically.

**Comment by EgyptianM** [comment]
Downloading latest version solved the problem.
