### ISSUE TITLE
How to use scrcpy to see the device from STF

### ISSUE THREAD

**Issue by chaooe** [Genymobile/scrcpy#1862]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

I have a stf server which have lots of android device. The android device is plugin to a machine and port adb server to the STF server. so all the device will have the same IP with different port.
1. adb connect 192.168.33.100:7451
2. scrcpy -Vdebug

2020-10-27 20:33:27.219 scrcpy[12148:436467] DEBUG: Using server: /usr/local/Cellar/scrcpy/1.14_1/share/scrcpy/scrcpy-server
/usr/local/Cellar/scrcpy/1.14_1/share/scrcpy/scrcpy-server: 1 file pushed. 0.7 MB/s (33142 bytes in 0.045s)
[server] INFO: Device: samsung SM-G9650 (Android 9)
[server] DEBUG: Screen streaming stopped
[server] DEBUG: Controller stopped

**Describe alternatives you've considered**

**Additional context**

**Comment by rom1v** [comment]
Check the output of `adb logcat` to get more info.

**Comment by chaooe** [comment]
[1.txt](https://github.com/Genymobile/scrcpy/files/5445539/1.txt)

**Comment by chaooe** [comment]
Add logcat file 
[1.txt](https://github.com/Genymobile/scrcpy/files/5445541/1.txt)

**Comment by rom1v** [comment]
Does the same device work directly (without STF as a "proxy")?

**Comment by chaooe** [comment]
Yes. if i plugin with usb or wireless. it works

**Comment by rom1v** [comment]
OK so it's probably related to how STF "proxifies" connections. I don't know how it works.

Maybe try `scrcpy --force-adb-forward`.

**Comment by chaooe** [comment]
Nice, works. Thanks.
