### ISSUE TITLE
Injecting to another application requires INJECT_EVENTS permission

### ISSUE THREAD

**Issue by Artem-Z86** [Genymobile/scrcpy#1865]
Hello! Help please! How avoid ``java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission`` when use only wrappers from scrcpy. How get permissions INJECT_EVENTS ?
Thanks!

**Comment by rom1v** [comment]
You can't from an Android app. That's one of the reasons scrcpy is run from shell with shell permissions.

**Comment by rom1v** [comment]
@ameaninglessname What if you enable "Security settings"? https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work

**Comment by nikdiklic** [comment]
What if I can't enable that option, since the screen is broken?
