### ISSUE TITLE
Build failed on Ubuntu 20.04

### ISSUE THREAD

**Issue by zhouji3x** [Genymobile/scrcpy#1866]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS:  Ubuntu 20.04
 - scrcpy version:  latest code

Error message:
```
 make -f Makefile.CrossWindows
./gradlew clean

> Configure project :server
Internal API constructor DefaultDomainObjectSet(Class<T>) has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use ObjectFactory.domainObjectSet(Class<T>) instead. See https://docs.gradle.org/6.3/userguide/custom_gradle_types.html#domainobjectset for more details.
        at build_bwftqy63rfxvetwtyiplnrsb8.run(/home/test/scrcpy/server/build.gradle:1)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)

FAILURE: Build failed with an exception.

* Where:
Build file '/home/test/scrcpy/server/build.gradle' line: 1

*** What went wrong:
A problem occurred evaluating project ':server'.
> Could not initialize class com.android.build.gradle.internal.VariantManager**

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 604ms
make: *** [Makefile.CrossWindows:40: clean] Error 1
```

**Comment by rom1v** [comment]
Looks like a gradle issue when building the server.

Do you really want to build the Windows version (from Ubuintu 20.04)?

**Comment by zhouji3x** [comment]
@rom1v   I need windows version.
any host that can build the windows version is OK for me, Ubuntu 20.04, Ubuntu 18.04, Ubuntu 16.04, Centos.

I tried scrcpy v1.16 for windows,   it support Android Q  system.
But it can't support Android R system,  no GUI showed,   and no error message found.    

We are working on Android R system now.

**Comment by rom1v** [comment]
> But it can't support Android R system, no GUI showed, and no error message found.

Even in `adb logcat`?

What's the output of `scrcpy` when you run on Android R?

**Comment by zhouji3x** [comment]
scrcpy log:

> scrcpy -V debug
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
DEBUG: Using server (portable): c:\hyper-v\scrcpy\scrcpy-server
c:\hyper-v\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 10.8 MB/s (33622 bytes in 0.003s)
DEBUG: Screensaver enabled
[server] INFO: Device: Intel AOSP on Intel Platform (Android 11)
DEBUG: Starting stream thread
DEBUG: Starting controller thread
DEBUG: Starting receiver thread
INFO: Renderer: direct3d
DEBUG: Trilinear filtering disabled (not an OpenGL renderer)
INFO: Initial texture: 1152x864

**Comment by zhouji3x** [comment]
tried several times and pulled /data/logs  

scrcpy log:
grep -nri scrcpy
aplogs/aplog:12114:11-11 23:45:46.902900  3691  3691 D AndroidRuntime: Calling main entry com.genymobile.scrcpy.Server
aplogs/aplog:12115:11-11 23:45:46.903859  3691  3691 I scrcpy  : Device: Intel AOSP on Intel Platform (Android 11)
aplogs/aplog:12244:11-11 23:45:47.335647  3701  3701 D AndroidRuntime: Calling main entry com.genymobile.scrcpy.CleanUp
aplogs/aplog:12335:11-11 23:45:50.711689  3701  3701 I scrcpy  : Cleaning up
aplogs/aplog:12336:11-11 23:45:50.712109  3701  3701 I scrcpy  : Restoring normal power mode
aplogs/aplog.001:14551:11-11 23:41:18.902245  3082  3082 D AndroidRuntime: Calling main entry com.genymobile.scrcpy.Server
aplogs/aplog.001:14552:11-11 23:41:18.902943  3082  3082 I scrcpy  : Device: Intel AOSP on Intel Platform (Android 11)
aplogs/aplog.001:14676:11-11 23:41:19.231385  3096  3096 D AndroidRuntime: Calling main entry com.genymobile.scrcpy.CleanUp
aplogs/aplog.001:17793:11-11 23:42:13.043605  3096  3096 I scrcpy  : Cleaning up
aplogs/aplog.001:17794:11-11 23:42:13.044685  3096  3096 I scrcpy  : Restoring normal power mode
aplogs/aplog.002:6344:11-11 23:32:17.307306  1891  1891 D AndroidRuntime: Calling main entry com.genymobile.scrcpy.Server
aplogs/aplog.002:6345:11-11 23:32:17.307981  1891  1891 I scrcpy  : Device: Intel AOSP on Intel Platform (Android 11)
aplogs/aplog.002:6506:11-11 23:32:17.824962  1903  1903 D AndroidRuntime: Calling main entry com.genymobile.scrcpy.CleanUp
aplogs/aplog.002:9321:11-11 23:32:39.588242  1903  1903 I scrcpy  : Cleaning up
aplogs/aplog.002:9322:11-11 23:32:39.588513  1903  1903 I scrcpy  : Restoring normal power mode

**Comment by rom1v** [comment]
Could you provide the full logs (often the errors are related to the hardware encoder, not scrcpy itself)?

```bash
adb logcat -c
scrcpy
adb logcat -d > log.txt
```

Could you checkout the `dev` branch, which supports a new option `--encoder` (#1827), and try with a different encoder:

```bash
scrcpy --encoder _  # will list the available encoders in the error message
scrcpy --encoder ENCODER_NAME
```

**Comment by zhouji3x** [comment]
this is full logs:
[log.txt](https://github.com/Genymobile/scrcpy/files/5528998/log.txt)

**Comment by rom1v** [comment]
```
C2SoftAvcEnc: Params width 1152 height 864 level 41 colorFormat 0 bframes 0
Gralloc4: mapper 4.x is not supported
Gralloc3: mapper 3.x is not supported
C2AllocatorGralloc: failed transaction: lockYCbCr
C2SoftAvcEnc: graphic view map err = 14
```

Looks like a hardware encoder error, try with another encoder (like explained in the previous comment).

**Comment by zhouji3x** [comment]
which version support  option --encoder?
I can't build it from source code :-(

**Comment by rom1v** [comment]
Here are binaries: https://github.com/Genymobile/scrcpy/pull/1827#issuecomment-725933512

**Comment by zhouji3x** [comment]
@rom1v thanks a lot for your help
please close this issue

**Comment by rom1v** [comment]
Did it work with a different encoder?

**Comment by zhouji3x** [comment]
no encoder works now.
since it is not scrcpy issue,  this issue can be closed.
