### ISSUE TITLE
无线连接

### ISSUE THREAD

**Issue by jixiang-wang** [Genymobile/scrcpy#1869]
无线连接不支持安卓手机连接mac吗？一直连不上

![image](https://user-images.githubusercontent.com/31286734/97776212-2aff6f80-1ba1-11eb-9a3c-336efc16d0da.png)

**Comment by rom1v** [comment]
1. Please post issues in English
2. Follow these steps: https://github.com/Genymobile/scrcpy#wireless
3. If it still does not connect, it's an adb connection issue, check stackoverflow.
