### ISSUE TITLE
FPS drops and Image jittering (2 different issues)

### ISSUE THREAD

**Issue by luanfernandes** [Genymobile/scrcpy#187]
Hi, is there a way to force the FPS stay fixed on 60? I have constant drops to 50-55, as I use it to stream games it's a little bad for viewers.
I'm already pushing 8mbps and full HD resolution through commands using a windows shortcut as follows on 'target' option:
D:\android-tools\scrcpy.exe -m 1920 -b 8M

Maybe change codecs or something?
----

Also, another issue that I'm having sometimes is image jittering:
NO JITTER (check text)
![scrcpy-no-jitter](https://user-images.githubusercontent.com/1331720/42117242-eda90dec-7bd1-11e8-936d-698ee85a450c.jpg)
JITTERING
![scrcpy-jitter](https://user-images.githubusercontent.com/1331720/42117243-edcf3f6c-7bd1-11e8-9584-b3c31908020b.jpg)

I can try to make a screenshot in the same window sample (since it's a game I can't make it exactly the same)

I'm not sure when it happens, I believe mostly when my screen goes to vertical and then comes back to horizontal but I think it's a bug. I'm trying to replicate but sometimes it doesn't happen and when it does happen, even if I restart the app the problem persists

**Comment by rom1v** [comment]
> Hi, is there a way to force the FPS stay fixed on 60?

The device may probably not keep encoding at 60fps. Maybe if you lower the definition (`-m 800`, just to test).

> Also, another issue that I'm having sometimes is image jittering

What do you mean by "image jittering"? The fact that it looks pixelated?

What is the native definition of the screen? 1920?
Is it also visible directly on the tablet (without scrcpy)?

**Comment by luanfernandes** [comment]
Will try lower the definition and respond back.
About the jitter, yes it pixelates a bit.. both my phone and my screen are
1920x1080 (though my monitor is 144hz) and no, it doesn't happen on my
phone's screen only on scrcpy.

**Comment by rom1v** [comment]
> About the jitter, yes it pixelates a bit.. both my phone and my screen are 1920x1080 (though my monitor is 144hz) and no, it doesn't happen on my phone's screen only on scrcpy.

What if you take a screenshot of your device screen directly:

    adb exec-out screencap -p > image.png

?

**Comment by Luis945** [comment]
I have the same issue :c, I just try to use my phone and show some gameplay on my computer, but when I start to play scrcpy get slow and also it started to drop some frames :/, can someone help me
my phone its a Moto Z play gen 1

**Comment by rom1v** [comment]
The device is probably not performant enough to both render a game and encode the screen video stream.
