### ISSUE TITLE
wireless connection

### ISSUE THREAD

**Issue by jixiang-wang** [Genymobile/scrcpy#1871]
Operating environment:
Android 10
macbookpro
When connecting to usb, everything works smoothly and the wireless connection is set up;

![image](https://user-images.githubusercontent.com/31286734/97780560-59407780-1bc0-11eb-9663-26f9e09fb3e6.png)

But when I unplug the usb and check the connected device again, the connection status of the device is displayed as offline；

![image](https://user-images.githubusercontent.com/31286734/97780598-8e4cca00-1bc0-11eb-8b87-47d8f8399969.png)

The phone that tried android5.0 does not have this problem, I don’t know if it is related to the phone system；

**Comment by fusionneur** [comment]
I created this tool to ease wireless connectivity. Check it out and let me know of your experience.

https://github.com/fusionneur/ethernally

**Comment by jixiang-wang** [comment]
> I created this tool to ease wireless connectivity. Check it out and let me know of your experience.
> 
> https://github.com/fusionneur/ethernally

Hello, I have used this tool, but as I described the problem, it is not the problem of your tool, it should be the problem of my mobile phone system. First of all, my mobile phone is android10 and not rooted mobile phone, I feel the problem should be it's here;
In terms of normal logic, I use commands to set up wireless and use your tool to set up wireless, the results should be the same;
Summarize my question: the wireless connection setting before unplugging the usb is successful, 
and the wireless connection fails after unplugging the usb. At this time, viewing the device status directly shows offline

**Comment by fusionneur** [comment]
you can try:
```
adb disconnect
adb kill-server
adb connect 192.168.1.8:5555
adb shell
````

see if that works for you

**Comment by jixiang-wang** [comment]
> you can try:
> 
> ```
> adb disconnect
> adb kill-server
> adb connect 192.168.1.8:5555
> adb shell
> ```
> 
> see if that works for you.
> 
> Edit: also try switching from USB 3.0 to USB 2.0, or even change cable and try different USB ports. Also better not to use any USB extension cables or USB hubs

According to your operation, I tried it again, but it still didn't work;
My Operating environment:
Android 10
macbookpro 2019 16 inch
I use the macbookpro power cord to connect the laptop and mobile phone directly with usb, both of which are type-c interfaces.
If it is convenient, you can use this environment to see if the problem can be reproduced, thanks 🙏

**Comment by fusionneur** [comment]
> > you can try:
> > ```
> > adb disconnect
> > adb kill-server
> > adb connect 192.168.1.8:5555
> > adb shell
> > ```
> > 
> > 
> > see if that works for you.
> > Edit: also try switching from USB 3.0 to USB 2.0, or even change cable and try different USB ports. Also better not to use any USB extension cables or USB hubs
> 
> According to your operation, I tried it again, but it still didn't work;
> My Operating environment:
> Android 10
> macbookpro 2019 16 inch
> I use the macbookpro power cord to connect the laptop and mobile phone directly with usb, both of which are type-c interfaces.
> If it is convenient, you can use this environment to see if the problem can be reproduced, thanks 🙏

Which is the error message it gives you ?

**Comment by jixiang-wang** [comment]
> > > you can try:
> > > ```
> > > adb disconnect
> > > adb kill-server
> > > adb connect 192.168.1.8:5555
> > > adb shell
> > > ```
> > > 
> > > 
> > > see if that works for you.
> > > Edit: also try switching from USB 3.0 to USB 2.0, or even change cable and try different USB ports. Also better not to use any USB extension cables or USB hubs
> > 
> > 
> > According to your operation, I tried it again, but it still didn't work;
> > My Operating environment:
> > Android 10
> > macbookpro 2019 16 inch
> > I use the macbookpro power cord to connect the laptop and mobile phone directly with usb, both of which are type-c interfaces.
> > If it is convenient, you can use this environment to see if the problem can be reproduced, thanks 🙏
> 
> Which is the error message it gives you ?

The hint information I mentioned in the first comment of this question:
It is the information shown in the red line below；
when I unplug the usb and check the connected device again, the connection status of the device is displayed as offline；
![image](https://user-images.githubusercontent.com/31286734/97801986-666e6c80-1c7b-11eb-97ed-963608a5e71a.png)

**Comment by fusionneur** [comment]
i mean what error it gives when you try `adb connect 192.168.1.8:5555` and after `adb shell` ?

**Comment by rom1v** [comment]
What if you unplug before `adb connect`?

**Comment by jixiang-wang** [comment]
> 我的意思是，当您尝试拔出USB电缆后`adb connect 192.168.1.8:5555`以及在`adb shell`拔出USB电缆后会出现什么错误？

**Comment by jixiang-wang** [comment]
> i mean what error it gives when you try `adb connect 192.168.1.8:5555` and after `adb shell` after you unplug the usb cable ?

When I unplug the USB device, I try to connect 192.168.1.8:5555, but it fails, because the device is offline after unplugging the USB device.
If you have the operating environment I described above, you'd better try it yourself, you should be able to understand the problem I'm talking about.
