### ISSUE TITLE
Protocol Information 

### ISSUE THREAD

**Issue by DottiestDuke47** [Genymobile/scrcpy#1873]
- [ ] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
I want to be able to decode the stream from the phone in my own program 
**Describe the solution you'd like**
Please could someone tell me how the protocol for receiving frames and sending inputs is structured. I tried looking in the source, but since I'm not familiar with java, I can't figure it out. Any help would be very appreciated :)

**Comment by rom1v** [comment]
Some refs:
 - https://github.com/Genymobile/scrcpy/blob/master/DEVELOP.md
 - https://github.com/Genymobile/scrcpy/issues/673#issuecomment-516360374
 - https://github.com/Genymobile/scrcpy/issues/129#issuecomment-384547383

**Comment by DottiestDuke47** [comment]
Thanks, I think the python examples should be of great help :)
