### ISSUE TITLE
[Question] Run scrcpy from an Android device

### ISSUE THREAD

**Issue by 7wells** [Genymobile/scrcpy#1874]
Hello!

Would it be possible to create a release for Android devices? Then one could connect from an Android device via adb-over-ip to another Android device, e.g. from a mobile phone. Prerequisite: adb works on that device (it does e.g. on a Samsung S7, from which I can connect to my Amazon Fire TV via adb-over-ip).

If there is already another/better way to do something with another method as equally cool as  scrcpy between 2 Android devices (which I doubt), I would be happy to learn about it.

Thanks for your kind consideration and feedback.

**Comment by rom1v** [comment]
See #100.

**Comment by 7wells** [comment]
@rom1v
Thank you so much for your hint and your scrcpy tool, which is really a great daily helper.

@tailcode (Anwar Mohammad Abdul in GitLab)
Thank you so much for your Android port of scrcpy. This opens so many additional possibilities for scrcpy.
