### ISSUE TITLE
No Command Line Option to Disable "Press any key to continue..."

### ISSUE THREAD

**Issue by dbareis** [Genymobile/scrcpy#1875]
- [Yes ] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
Want to automate it's use, this prevents that (retry)

**Describe the solution you'd like**
A command line to make the pause optional

**Describe alternatives you've considered**
Not practical in a batch file.

**Additional context**
This is an example of where I don't want the pause:
```
adb: error: failed to get feature set: no devices/emulators found
ERROR: "adb push" returned with value 1
Press any key to continue...
```
Of course, not all keys will make it continue, I can put up with that as Windows has the same bug.

**Comment by rom1v** [comment]
Indeed, this is problematic (on Windows).

This pause is a hack to avoid the following problem (140b1ef6a5f2de489f99c6f7f63dc2a49bc404f6): users start scrcpy by double-clicking on `scrcpy.exe`, this opens a console while scrcpy but closes immediately once scrcpy is closed, so users can't see the error message.

I'm not in favor of adding a command-line parameter for this, maybe it would be better to remove this pause from scrcpy, and handle this from a `.bat` wrapper? (cc @npes87184)

(Btw, it would also be great if there was a way to easily handle both normal and "no console" version without producing two different binaries.)

**Comment by npes87184** [comment]
> Indeed, this is problematic (on Windows).
> 
> This pause is a hack to avoid the following problem ([140b1ef](https://github.com/Genymobile/scrcpy/commit/140b1ef6a5f2de489f99c6f7f63dc2a49bc404f6)): users start scrcpy by double-clicking on `scrcpy.exe`, this opens a console while scrcpy but closes immediately once scrcpy is closed, so users can't see the error message.
> 
> I'm not in favor of adding a command-line parameter for this, maybe it would be better to remove this pause from scrcpy, and handle this from a `.bat` wrapper? (cc @npes87184)

From my point of view, I don't think we need to add this option.

> 
> (Btw, it would also be great if there was a way to easily handle both normal and "no console" version without producing two different binaries.)

To remove the pause, there are some methods to do it,

For example, we can write the log into a file, in this case we don't need the console version as well as the pause.
However, when some problem happens, in this time, if user double click the icon and it doesn't show anything is a good feedback or not (IMO, it is not).
Maybe we can show the actual error log into dialog but it also violates the retry in automate.

Another possible method is we can write a wrapper `.bat`. Depends on the return value of `scrcpy` it can determine whether to pause or not.

**Comment by dbareis** [comment]
I don't see the issue with an extra switch to turn off the pause and I do see the need for the pause if someone just starts the app from Explorer.  

Without a switch to turn off the pause then I'd suggest turning the pause of if there are any command-line parameters (as that implies they didn't just start the app by double-clicking it).

I'm creating a batch file which logs and performs retries (if pause solved anyway), I would like it to have some basic profile support.

**Comment by rom1v** [comment]
@dbareis @npes87184 I disabled the pause from `scrcpy.exe`, and provided `scrcpy-console.bat`: 904d47057987fcd2bc2bb9494758a611fa6ab2bc (not merged yet).

What do you think?

**Comment by npes87184** [comment]
> @dbareis @npes87184 I disabled the pause from `scrcpy.exe`, and provided `scrcpy-console.bat`: [904d470](https://github.com/Genymobile/scrcpy/commit/904d47057987fcd2bc2bb9494758a611fa6ab2bc) (not merged yet).
> 
> What do you think?

This commit looks good to me.

**Comment by dbareis** [comment]
It will be earliest mid Jan before I can try this

**Comment by rom1v** [comment]
> This commit looks good to me.

Thank you for your feedback. :+1: I will merge it before a new release.

**Comment by rom1v** [comment]
Merged into `dev`.
