### ISSUE TITLE
/sbin/sh: app_process: not found

### ISSUE THREAD

**Issue by Steffen777** [Genymobile/scrcpy#188]
I’ve a broken Nexus 4 without touch functionality but with a working display. 
- TWRP 3.2.1-0 and LineageOS 15.1 with Android Oreo is installed
- The device is encrypted and secured with a PIN, but I can’t enter the PIN with the broken phone.
- USB debugging is enabled and I have ADB access to the device in recovery mode
- My aim is to unlock the LineageOS start with my PIN or to unlock TWRP with my PIN to get access to my data.

I got following failure:
scrcpy-server.jar: 1 file pushed. 2.0 MB/s (19342 bytes in 0.009s)
/sbin/sh: app_process: not found

What can I do?

**Comment by rom1v** [comment]
adb shell ls /system/bin/app_*

?

**Comment by Steffen777** [comment]
```
adb shell ls /system/bin/app_*
ls: /system/bin/app_*: No such file or directory
```

**Comment by Parthib24** [comment]
check in /vendor/bin

**Comment by Steffen777** [comment]
```
adb shell ls /vendor/bin/app_*
ls: /vendor/bin/app_*: No such file or directory
```

```
adb shell ls /system/bin/app_*
ls: /system/bin/app_*: No such file or directory
```

```
adb shell ls /storage/bin/app_*
ls: /storage/bin/app_*: No such file or directory
```

```
adb shell ls /sbin/app_*
ls: /sbin/app_*: No such file or directory
```

```
adb shell ls vendor/bin
ls: vendor/bin: No such file or directory
```


What we are looking for?

**Comment by Hoyuyhnhnm** [comment]
I'm experiencing the same problem, also on Lineage OS 15.1 with a broken screen Redmi Note 4. Any workaround for this?

**Comment by Steffen777** [comment]
I could unlock TWRP from command line and after that I got access with windows explorer to my data partition.

- start recovery mode
- unlock data partition from command line
```
adb devices
adb shell
twrp decrypt PASSWORD
```
PASSWORD = your login password
[TWRP Commandline Guide](https://twrp.me/faq/openrecoveryscript.html)

**Comment by zeerd** [comment]
What the app_process is? Where should I find it's binary or source-code if it's missed from my system?
