### ISSUE TITLE
ScrCpy Should Support Android Shortcut Keys

### ISSUE THREAD

**Issue by xcjs** [Genymobile/scrcpy#1881]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

There are requests for custom keymaps, but I feel that these mappings should just work.

**Is your feature request related to a problem? Please describe.**

I'm frustrated that keys on my keyboard don't map to Android the same way that bluetooth keyboards do. 

**Describe the solution you'd like**

Certain keys on Android trigger specific actions:

Home: Navigates to the default configured Android launcher
Esc: Equivalent to the Back button
Media keys: My keyboard has a dedicated set of volume keys (up, down, and mute) that typically work on Android keyboards. Some keyboards also have dedicated key codes for play/pause, skip, and previous track that should also work in Android. It would be nice if these work as expected.

I would like these key codes to work as they normally would if passed forward to an Android device.

**Describe alternatives you've considered**

The alternative is not having the feature as I don't see any other way to get this to work.

**Additional context**

**Comment by rom1v** [comment]
> Home: Navigates to the default configured Android launcher

Home is now bound to `MOVE_HOME` to be consistent with `MOVE_END`: 5d473efeb5c4f42a75aad6ab5892e2813358c0c9 (#555).

<kbd>MOD</kbd>+<kbd>h</kbd> or middle-click pressed `HOME`.

> Esc: Equivalent to the Back button

Esc injects `ESCAPE` (like `adb shell input keyevent ESCAPE`). It often has the same effect as `BACK`, but not always.

> Media keys: My keyboard has a dedicated set of volume keys (up, down, and mute) that typically work on Android keyboards. Some keyboards also have dedicated key codes for play/pause, skip, and previous track that should also work in Android. It would be nice if these work as expected.

Refs #1824

If you want to work on it, please add the mapping here (on `dev` branch): https://github.com/Genymobile/scrcpy/blob/adc547fa6e8e6167cd9633a97d98de6665b8c23a/app/src/event_converter.c#L80-L99

**Comment by guanzhangrtk** [comment]
Do these shortcut keys work on the Mac? Command-H seems to be able to bring you back to HOME however these shortcut keys seems to conflict with Mac internal shortcut keys (for instance command-H is hide program).

Thanks!

**Comment by rom1v** [comment]
> Actually on the Mac seems the MOD button is alt/option instead of command, so it is actually working as intended

Both Alt/Super trigger shortcuts, unless the system capture them before transmitting the key to scrcpy.

https://github.com/Genymobile/scrcpy#shortcuts
