### ISSUE TITLE
Scrcpy run and close on its own in few sec

### ISSUE THREAD

**Issue by harsh2501** [Genymobile/scrcpy#1888]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows]
 - scrcpy version: [1.16]
 - installation method: [scoop]
 - device model:redmi note 7 pro
 - Android version: [ 10]

**Describe the bug**
Help me my scrcpy is not working it open and close in few sec and now I am not getting response from your side please help me to run this program

On errors, please provide the output of the console (and `adb logcat` if relevant).
No error is displayed
```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
Please stop opening new duplicates.

**Comment by harsh2501** [comment]
So please help me please for god
