### ISSUE TITLE
In wifi mode "--stay-awake" parameter fails

### ISSUE THREAD

**Issue by Mr-Coffee666** [Genymobile/scrcpy#1889]
- [ yes] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ yes] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [ Windows10]
 - scrcpy version: [1.16]
 - installation method: [Windows release...]
 - device model: RedMi k30s ultra
 - Android version: [10]

**Describe the bug**
When using "--stay-awake" in wifi mode, the device will still lock the screen

**Comment by rom1v** [comment]
Yes, see #1445.

**Comment by Mr-Coffee666** [comment]
> 是的，请参见[＃1445](https://github.com/Genymobile/scrcpy/issues/1445)。

I see. Thank you
