### ISSUE TITLE
Skipped frames over wifi

### ISSUE THREAD

**Issue by AndMort** [Genymobile/scrcpy#1891]
- [Y] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [Y] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: 1.16
 - installation method: Windows release
 - device model: Samsung Galaxy S7 SM-G930F
 - Android version: 8.0.0

**Describe the bug**

When connecting via wifi, some frames are doubled/tripled (and possibly the adjacent frames are lost). Lowering the resolution and/or bitrate and/or using --render-expired-frames flag does not change anything.
When connected via usb, frames are doubled much less frequently
Recording --record file.mkv output is perfectly smooth, so theoretically all frames are being timestamped and received correctly.

Output of the console:
```
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
C:\Program Files\scrcpy\scrcpy-server: 1 file pushed. 0.3 MB/s (33622 bytes in 0.095s)
adb.exe: error: more than one device/emulator
ERROR: "adb reverse" returned with value 1
WARN: 'adb reverse' failed, fallback to 'adb forward'
27183
[server] INFO: Device: samsung SM-G930F (Android 8.0.0)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x1920
```

I attach a adb logcat and --record file.mkv and obs recording showing this bug.
[adb_logcat.txt](https://github.com/Genymobile/scrcpy/files/5506580/adb_logcat.txt)
--record file.mkv [https://drive.google.com/file/d/1-1I4R6Z2lnYlZEMZ9CRZEIbMWWxm6Zdb/view?usp=sharing]
screen capture [https://drive.google.com/file/d/1kPwLftRYEUJufq9kj3ODRuKWPUZROG1W/view?usp=sharing]

**Comment by rom1v** [comment]
That's not surprising, if wifi packets are lost, they are delayed.

**Comment by AndMort** [comment]
Is it possible to wait for delayed packets and obtain a smooth stream (just like recording) at the expense of increasing the overall latency?

**Comment by rom1v** [comment]
No, scrcpy does not support this, the main goal is minimal latency without additional buffering.

**Comment by rom1v** [comment]
To elaborate a bit more, such a feature would have an important impact on the architecture/codebase, with minimal benefit IMO.

Btw, VLC has the opposite issue: everything must have a PTS, so it could not totally disable buffering.
