### ISSUE TITLE
Rotation not working when using camera

### ISSUE THREAD

**Issue by ynobry** [Genymobile/scrcpy#1895]
Hi

I have a Samsung Galaxy S10 and Ctrl+R/←/→/ isn't working when I'm using the Camera app. I've tried the commands but I get errors such as `scrcpy: unknown option -- rotation` (I might just be being stupid here and using the terminal wrong).

I'm using the following version:
```
scrcpy 1.12.1

dependencies:
 - SDL 2.0.10
 - libavcodec 58.54.100
 - libavformat 58.29.100
 - libavutil 56.31.100
```

Any ideas? Thanks!

**Comment by rom1v** [comment]
Rotation shortcuts have been added in v1.13.

Just use the latest version (1.16).

https://github.com/Genymobile/scrcpy#rotation

**Comment by ynobry** [comment]
Ahh my bad, I had downloaded the new version but was using the commands in the old version! Thanks!
