### ISSUE TITLE
reuse existing adb

### ISSUE THREAD

**Issue by lollita** [Genymobile/scrcpy#1897]
Why scrcpy when start create new adb process also if have a existing?

**Comment by rom1v** [comment]
`scrcpy` just executes `adb`, and `adb` uses the existing daemon if it is already started (and is the same version).

**Comment by lollita** [comment]
It not work so for me.
With task manager I see a adb.exe proces in root and a adb.exe sub scrcpy-noconsole.exe.
When I close scrcpy remain only the initial adb.exe in root.

**Comment by rom1v** [comment]
Looks like https://github.com/Genymobile/scrcpy/pull/1852#issuecomment-717766456.

> Do you mean that have a adb.exe deamon and a adb.exe client?

Yes.

On my system:

```bash
$ ps -ef | grep adb
... adb -L tcp:5037 fork-server server --reply-fd 7
... adb shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 1.16 info 0 8000000 0 -1 false - true true 0 false false -
```

**Comment by lollita** [comment]
Do it is possible to use a tcp connection to deamon instead of a adb.exe client process?

**Comment by rom1v** [comment]
Why?

`adb.exe` is expected to work that way.
