### ISSUE TITLE
Device Control

### ISSUE THREAD

**Issue by MrPriyanshu** [Genymobile/scrcpy#1902]
I found a problem while controlling my Redmi Note 7 Pro from my desktop. It is not able to control my phone when connected. And keyboard emulator controls can be added to it, so that one can easily use phone apps using the desktop.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work

**Comment by Gitcode2501** [comment]
I had the same problem but gladly I solved it as indicated in the link. Thank you.
