### ISSUE TITLE
"adb push" always returns with a value of 1

### ISSUE THREAD

**Issue by studboy1114** [Genymobile/scrcpy#1904]
**Environment**
 - OS: Windows 10
 - scrcpy version: v1.16
 - installation method: manual build
 - device model: LG L322DL
 - Android version: 9

**Describe the bug**
Even if I have USB debugging on, it still doesn't connect, responding with this:
```
adb: error: failed to get feature set: no devices/emulators found
ERROR: "adb push" returned with value 1
```
The only options I have for USB debugging are:
Turn on USB debugging (on)
Verify apps over USB (off, to possible prevent my phone from rejecting it)

I tried running all 3 of the .exe files with no success. Any help?

**Comment by rom1v** [comment]
`adb` does not detect your device. Check `adb devices`.

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#device-not-detected

**Comment by studboy1114** [comment]
This helped, but now I'm having some problems with my phone carrier where I can't find my phone model for the USB drivers, I'll ask around a little bit but thank you!
