### ISSUE TITLE
smooth on phone, low fps on cast screen

### ISSUE THREAD

**Issue by Maliciousrean** [Genymobile/scrcpy#1906]
- [*] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [*] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: android / win10
 - scrcpy version: 1.16
 - installation method: manual
 - device model: xiaomi note 9s
 - Android version: 10

**Describe the bug**
casting screen of epic7, phone connected to pc through usb cable.
on my phone picture is smooth but on the cast screen its choppy.
phone tool shows 50% cpu/gpu load, changing bitrate, encoding to opengl, resolution does nothing. i dont understand what may cause this.
fps tool shows 45-48fps, my phone shows 50fps in game. but while phone image is very smooth, cast is choppy and staggering every few seconds.
video recorded through scrcpy is smooth, so i guess its a codec issue? but how do i even fix it? i have no idea where to look. my gpu is 2070 super and i have LAV installed because i have VR. so everything should be in place for it to work properly.

**Comment by rom1v** [comment]
> fps tool shows 45-48fps, my phone shows 50fps in game. but while phone image is very smooth, cast is choppy and staggering every few seconds.

Any "skipped frames" reported?

> video recorded through scrcpy is smooth, so i guess its a codec issue?

A decoder issue on the computer side I guess.

Out of curiosity, OBS is not capturing the scrcpy window?

**Comment by Maliciousrean** [comment]
i dont have OBS launched, not streaming. there are no skipped frames either. i tried no frame skip mode and it only got worse.
any idea what i can do about this situation?

**Comment by rom1v** [comment]
> resolution does nothing

Even a tiny definition like `scrcpy -400`?

**Comment by Maliciousrean** [comment]
> > resolution does nothing
> 
> Even a tiny definition like `scrcpy -m400`?

yep, still choppy

**Comment by rom1v** [comment]
OK, it's unexpected.

Could you please run `scrcpy -r file.mkv` and also capture a video of your computer screen, and post both video files?

**Comment by Maliciousrean** [comment]
[file.zip](https://github.com/Genymobile/scrcpy/files/5541593/file.zip)
file is attached, screen cap is on youtube https://www.youtube.com/watch?v=Iwua4KxDbLs&feature=youtu.be&ab_channel=Rean2000
you can see choppy animation that isnt present in local recording.

**Comment by rom1v** [comment]
Thank you. I got it: it's probably due to the variation of decoding time between frames. This could be confirmed by adding logs to print the decoding time.

On purpose, to minimize latency, scrcpy displays a frame as soon as it is available. But if the decoder decodes one frame in 5ms and another in 25ms (which would not be surprising, not all frames have the same complexity), then the second will be displayed 20ms too late compared to the previous one. For me, it was just a theoretical problem, since in practice I never noticed the problem (when playing a video for example).

It is a design choice to ignore network lag (since over USB it's not a problem) to optimize for latency. But it might make sense to add an option to compensate for decoder "jitter" (at the cost of increased average latency). I will think about it.

**Comment by Maliciousrean** [comment]
so for now its unavoidable? got it.
regardless, very cool software, thanks for all the hard work. 
if you'll come up with the beta solution or smth hit me up, i'll be glad to test it for you on my end.

**Comment by rom1v** [comment]
Could you apply this patch to log the decoding time of each frame, please?

```diff
diff --git a/app/src/decoder.c b/app/src/decoder.c
index 49d4ce86..b3cf91e7 100644
--- a/app/src/decoder.c
+++ b/app/src/decoder.c
@@ -5,6 +5,7 @@
 #include <SDL2/SDL_events.h>
 #include <SDL2/SDL_mutex.h>
 #include <SDL2/SDL_thread.h>
+#include <SDL2/SDL_timer.h>
 #include <unistd.h>
 
 #include "config.h"
@@ -63,6 +64,8 @@ bool
 decoder_push(struct decoder *decoder, const AVPacket *packet) {
 // the new decoding/encoding API has been introduced by:
 // <http://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=7fc329e2dd6226dfecaa4a1d7adf353bf2773726>
+    static unsigned i;
+    uint32_t start = SDL_GetTicks();
 #ifdef SCRCPY_LAVF_HAS_NEW_ENCODING_DECODING_API
     int ret;
     if ((ret = avcodec_send_packet(decoder->codec_ctx, packet)) < 0) {
@@ -92,6 +95,9 @@ decoder_push(struct decoder *decoder, const AVPacket *packet) {
         push_frame(decoder);
     }
 #endif
+    uint32_t end = SDL_GetTicks();
+    LOGD("packet %d decoding: %" PRIu32 "ms", i++, end - start);
+
     return true;
 }
 
```

**Comment by Maliciousrean** [comment]
uh, i dont really have git installed or know how it works.
is it possible to just send me the compiled files? :<
if not i'll get to figuring it out after i wake up, shouldnt be too hard

**Comment by rom1v** [comment]
Replace in v1.16 release:

- [`scrcpy.exe`](https://tmp.rom1v.com/scrcpy/1906/1/scrcpy.exe)
  _SHA256: 5a60c9decba62bdfb6a8d62702cde7d906a4f6f186949a624082d250631b13d8_

**Comment by Maliciousrean** [comment]
it seems much better
log of about a minute in attach
[log.txt](https://github.com/Genymobile/scrcpy/files/5542842/log.txt)

**Comment by rom1v** [comment]
OK, so the problem probably does not come from the decoder, your results are even better than on my laptop.

So it lags somewhere else.

Are you able to test on the same computer (or even another computer) on Linux?

**Comment by Maliciousrean** [comment]
wait but it doesnt stutter anymore. fps went down to 20s on that same screen i made video of earlier, but its no longer jittering. i am totally fine with lower fps but stable framerate rather than higher fps and jitters.
here is a short vid 
[Desktop 2020.11.15 - 21.01.47.03.DVR.mp4.zip](https://github.com/Genymobile/scrcpy/files/5542863/Desktop.2020.11.15.-.21.01.47.03.DVR.mp4.zip)

dont have linux unfortunately.

**Comment by rom1v** [comment]
> wait but it doesnt stutter anymore

That's not expected, I didn't change anything (except adding a log).

**Comment by Maliciousrean** [comment]
okay i went back to old exe and its the same behavior, its not jittering anymore.
i'm not sure what change.
i did update graphics drivers out of desperation yesterday but didnt reboot since then (it was shortly before i made the ticket).
maybe that fixed it?
idk, i'll keep an eye on it. maybe it was buggy nvidia driver?

**Comment by rom1v** [comment]
Yes, if the same binary now works correctly, I think it was related to graphics drivers.

**Comment by Maliciousrean** [comment]
deeply apologize for sending you on a goose chase. i guess issue is resolved then, i'll let you know if i see similar behavior again

**Comment by rom1v** [comment]
No problem, that was a legitimate issue to report 😉 (and I'm glad that it's finally just a driver issue 😄).

**Comment by Maliciousrean** [comment]
> No problem, that was a legitimate issue to report 😉 (and I'm glad that it's finally just a driver issue 😄).

i restarted the game and its back. was not gpu drivers. i'm trying to mess with it for now wondering if there is any connection between when cast/program is launched, here is the video of a picture with the logging enabled. even logging is stuttering
[Desktop 2020.11.16 - 01.33.17.05.DVR.mp4.zip](https://github.com/Genymobile/scrcpy/files/5543246/Desktop.2020.11.16.-.01.33.17.05.DVR.mp4.zip)

i wonder if it could be just a software issue with the phone or the game? anyway i'm tinkering with it for now trying to figure out what did i do to make it work smooth

**Comment by Maliciousrean** [comment]
okay to recap the entire thing:
after i went to sleep i left phone with the game on and turned off pc.
i woke up, saw your comment, changed exe and hooked up my phone to pc (i unplugged it from usb for the night).
it was working fine and that screen with the dude was showing 20fps but not stuttering.
then i restarted the game and stuttering was back and alt+i now shows 45+fps again at that same exact screen.

i wonder why it was rendering at 20fps back then and without the jitter.

**Comment by rom1v** [comment]
On your video, even your console seems to be lagging (while it shouldn't happen if the video is smooth when recorded).

Could you start an animation at the same time (like a rotating triangle or something) to see if it lags the same way on the desktop?

**Comment by Maliciousrean** [comment]
i'm usually watching twitch and i didnt notice any slowdown. and honeslty i shouldnt have granted i pack ryzen3600/2070super.
randomly, again, seems fine for now. i'll let you know if other stuff is affected if it happens once more

**Comment by Maliciousrean** [comment]
0 slowdown in any other app when this happens. tried youtube and twitch, all working fine
[Desktop 2020.11.18 - 22.13.21.10.DVR.mp4.zip](https://github.com/Genymobile/scrcpy/files/5562215/Desktop.2020.11.18.-.22.13.21.10.DVR.mp4.zip)

shouldnt be related to pc load, i would've noticed that long ago. actually i just noticed, decoding stutters even when window is minimized and gpu isnt drawing anything on screen. 

so far i havent been able to identify why it lags sometimes and other times its fine.

**Comment by rom1v** [comment]
Maybe the lags comes from the encoder on the device (which sets the correct PTS but provide some buffers too late) then.

**Comment by Maliciousrean** [comment]
i am also learning to some kind of issue on the phone itself as the bug seem to happen randomly and may occur when just restarting the app. 
if i'll figure it out i'll let you know

**Comment by Maliciousrean** [comment]
okay i'm at a complete loss.
since last post i didnt touch my phone and it was casting for 7 hours straight while i was playing the game and afk. never switched app or anythng, game was always on.
suddenly frame drops vanished.
at this rate i call random phone shenanigans that are...random. impossible to debug without really digging into phone. so i guess thats it for the ticket.
thanks for all the help, much appreciated.

**Comment by StacktraceException** [comment]
still occurs but on xiaomi 11t here. tried even with 1m bitrate on both usb and wifi and nothing helped.

This is the  best I got actually: adb shell wm size 1440x2560 density 216 && .\scrcpy.exe --print-fps --always-on-top --shortcut-mod=lctrl+lalt --stay-awake --turn-screen-off --render-driver=metal --disable-screensaver --video-bit-rate=1M --max-fps=120 --video-codec=h265 --video-encoder='OMX.MTK.VIDEO.ENCODER.HEVC'

Using these options (especially the different encoder made the fps a lot more stable although still very poor).

**Comment by itzyashh** [comment]
I was having this issue and it got resolved after connecting an hdmi cable to tv and a mouse to operate phone ,during this process it was also connected to scrcpy using tcpip .Maybe connecting to hdmi reset something which removed all the lag .
