### ISSUE TITLE
scrcpy doesn't use opengles on windows 10

### ISSUE THREAD

**Issue by barfin** [Genymobile/scrcpy#1909]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10 20H2 (OS Build 19042.630)
 - scrcpy version: 1.16
 - installation method: Windows release zip file
 - device model: Sony Xperia Tablet Z LTE (sgp321 also known as pollux)
 - Android version: Android 9 (Lineage OS 16 with latest November security android updates)
 - Android Platform tools version: 30.0.5

**Describe the bug**
it reverts back to direct3d
while opengles2 works fine and uses opengles3.2

```
PS C:\Users\barfin> scrcpy -m400 --verbosity debug --render-driver opengles
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
DEBUG: Using server (portable): C:\android\scrcpy-server
C:\android\scrcpy-server: 1 file pushed, 0 skipped. 49.8 MB/s (33622 bytes in 0.001s)
DEBUG: Screensaver enabled
[server] INFO: Device: Sony Xperia Tablet Z LTE (Android 9)
DEBUG: Starting stream thread
DEBUG: Starting controller thread
DEBUG: Starting receiver thread
INFO: Renderer: direct3d
DEBUG: Trilinear filtering disabled (not an OpenGL renderer)
INFO: Initial texture: 400x248
```

**Comment by rom1v** [comment]
```
scrcpy --render-driver opengles2
```
https://wiki.libsdl.org/SDL_HINT_RENDER_DRIVER

**Comment by barfin** [comment]
> 
> 
> ```
> scrcpy --render-driver opengles2
> ```
> 
> https://wiki.libsdl.org/SDL_HINT_RENDER_DRIVER

hmm yeah this one does the job but why "opengles" is there if it doesn't do anything

**Comment by rom1v** [comment]
It was probably for OpenGL ES 1.
