### ISSUE TITLE
dyld: Library not loaded: /usr/local/opt/ffmpeg/lib/libavformat.57.dylib

### ISSUE THREAD

**Issue by tonyyang924** [Genymobile/scrcpy#191]
dyld: Library not loaded: /usr/local/opt/ffmpeg/lib/libavformat.57.dylib
  Referenced from: /usr/local/bin/scrcpy
  Reason: image not found
[1]    7815 abort      scrcpy -s 7b519a310504

**Comment by rom1v** [comment]
cc @stek29 ?

**Comment by brentwatson** [comment]
I'll had the same issue (seeing the exact same error). Might have happened after I did a `brew update` (?). I had originally built from source.  This fixed the problem:

Removed version built from source:
```bash
sudo rm /usr/local/bin/scrcpy
sudo rm /usr/local/share/scrcpy/scrcpy-server.jar
```

Used `brew` version instead:
```base
brew install scrcpy
```

hope that helps!

**Comment by stek29** [comment]
Sorry for late response

Just in case, you can use `install_name_tool` next time to fix up dylib names to be unversioned if needed.

Use brew formula, and if you want to build from source, you can use `--from-source` option, and replace the scrcpy-server.jar afterwards if needed too. Brew does a lot of things for you.

**Comment by pjk291** [comment]
but if i want to use the old version scrcpy, this don't work, because the above method will update scrcpy...cry

**Comment by Moaan** [comment]
For me `brew upgrade` is the only thing that got scrcpy working again!
