### ISSUE TITLE
Option to choose which monitor scrcpy opens on

### ISSUE THREAD

**Issue by mi-ca23** [Genymobile/scrcpy#1915]
**Describe the solution you'd like**
I'm using Scrcpy on my Windows 10 PC, with triple monitors. I've got it set up with Autoadb to start on plugging my phone in, but would like the option to choose which monitor it opens on. I currently have to drag/move the scrcpy window from my primary monitor to my other monitor every time

**Comment by rom1v** [comment]
Did you try playing with `--window-x VALUE --window y VALUE`?

**Comment by mi-ca23** [comment]
i didn't, will do now. i thought that was just for the size of the window

**Comment by mi-ca23** [comment]
That worked, thank you for the super quick help. I used --window-x 3400 --window-y 25 - to open a windowed version of scrcpy in the top right of my second display.
