### ISSUE TITLE
Doesn't sync correctly after use adb shell wm size.

### ISSUE THREAD

**Issue by Sodium-Aluminate** [Genymobile/scrcpy#1918]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Ubuntu 18.04
 - scrcpy version: 1.14
 - installation method: apt
 - device model: Redmi note 8 pro (begonia) <- 1080x2336 default.
 - Android version: 10

**Describe the bug**
1. start scrcpy
2. run `adb shell wm size 1080x2336` or  `adb shell wm size 1080x1920`
3. scrcpy stdout nothing and the copied screen was not fully displayed.

terminal 1(scrcpy):
```
sodiumaluminate@AlsPad:~$ scrcpy
INFO: scrcpy 1.14 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server:...shed. 5.7 MB/s (33142 bytes in 0.006s)
[server] INFO: Device: Xiaomi Redmi Note 8 Pro (Android 10)
INFO: OpenGL shaders: ENABLED
INFO: Created renderer: opengl
INFO: Renderer: opengl
INFO: OpenGL version: 4.6.0 NVIDIA 450.80.02
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x2336
^CWARN: Device disconnected
sodiumaluminate@AlsPad:~$ 
```

terminal 2(adb wm):
```
sodiumaluminate@AlsPad:~$ adb shell 
begonia:/ $ wm 
Window manager (window) commands:
  help
      Print this help text.
  size [reset|WxH|WdpxHdp] [-d DISPLAY_ID]
    Return or override display size.
    width and height in pixels unless suffixed with 'dp'.
  density [reset|DENSITY] [-d DISPLAY_ID]
    Return or override display density.
  folded-area [reset|LEFT,TOP,RIGHT,BOTTOM]
    Return or override folded area.
  overscan [reset|LEFT,TOP,RIGHT,BOTTOM] [-d DISPLAY ID]
    Set overscan area for display.
  scaling [off|auto] [-d DISPLAY_ID]
    Set display scaling mode.
  dismiss-keyguard
    Dismiss the keyguard, prompting user for auth if necessary.
  set-user-rotation [free|lock] [-d DISPLAY_ID] [rotation]
    Set user rotation mode and user rotation.
  set-fix-to-user-rotation [-d DISPLAY_ID] [enabled|disabled]
    Enable or disable rotating display for app requested orientation.
255|begonia:/ $ wm size 1080x1920                                                                                                                    
begonia:/ $ wm size reset                                                                                                                            
begonia:/ $ wm size 1080x1920                                                                                                                        
begonia:/ $ wm size reset                                                
begonia:/ $ 
```

**Comment by rom1v** [comment]
But if you restart scrcpy, does it have the correct size?

AFAIK there is no way to be notified of window size changes.

**Comment by Sodium-Aluminate** [comment]
> But if you restart scrcpy, does it have the correct size?

yes, it can be corrected by restart scrcpy.

> AFAIK there is no way to be notified of window size changes.

but maybe we can check it evey few seconds?

**Comment by rom1v** [comment]
> but maybe we can check it evey few seconds?

Polling is ugly, it's not worth it for a thing which almost never happens in practice.

**Comment by Sodium-Aluminate** [comment]
> > but maybe we can check it evey few seconds?
> 
> Polling is ugly, it's not worth it for a thing which almost never happens in practice.
> 
> If there is a proper way to be notified by a callback, I'll add it, but no polling.

well… you are right, unless we hook the wm or adb, or create an Android activity in front end, there may be no way to watch it.

**Comment by rom1v** [comment]
Refs:
 - https://github.com/aosp-mirror/platform_frameworks_base/blob/e191d8d958307ff182e463c1058a0ac25eb78225/core/java/android/view/IWindowManager.aidl#L477
 - https://github.com/aosp-mirror/platform_frameworks_base/blob/e191d8d958307ff182e463c1058a0ac25eb78225/core/java/android/view/IPinnedStackListener.aidl#L71
