### ISSUE TITLE
Get segmentation fault and not show any mirroring window (v. 1.16)

### ISSUE THREAD

**Issue by narugit** [Genymobile/scrcpy#1921]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Ubuntu 18.04.3 LTS
 - scrcpy version: 1.16
 - installation method: snap
 - device model: Xperia 1 SOV40
 - Android version: 9

**Describe the bug**
When I try scrcpy command, the result is segmentation fault and not output any window which mirrors my Android.
Output is below. XXXXXX is get from `adb devices -l`.

```
$ adb devices -l
List of devices attached
XXXXXX             device usb:1-8 product:SOV40_jp_kdi model:SOV40 device:SOV40 transport_id:4

$ scrcpy --serial XXXXXX
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 6.7 MB/s (33622 bytes in 0.005s)
zsh: segmentation fault (core dumped)  scrcpy --serial XXXXXX
[server] INFO: Device: Sony SOV40 (Android 9)
```

**Comment by narugit** [comment]
Is there verbose mode to check scrcpy output?

**Comment by rom1v** [comment]
Please try with a non-snap version. For example, build the client manually (and take the [prebuilt server](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#prebuilt-server)).

And enable ASAN (with `-Db_sanitize=address`):

```
meson x -Dprebuilt_server=/path/to/scrcpy-server -Db_sanitize=address
ninja -Cx
sudo ninja -Cx install
```

This will give a stack trace.

Also see #1896.

**Comment by narugit** [comment]
@rom1v 
Thank you for your quick response!
This works for me!
```
$ export DISPLAY=:0 && scrcpy --serial XXXXXX
```
