### ISSUE TITLE
Failed to start daemon

### ISSUE THREAD

**Issue by StarGolx** [Genymobile/scrcpy#1922]
How to fix this?
-adb: error: failed to get feature set: cannot connect to daemon
-ERROR: "adb push" returned with value 1
![image](https://user-images.githubusercontent.com/62445523/99791757-5e8d4400-2b26-11eb-82eb-c7d3ce531a32.png)

**Comment by rom1v** [comment]
https://stackoverflow.com/questions/7327147/adb-error-cannot-connect-to-daemon
