### ISSUE TITLE
scrcpy with adb old version on snap causes unnecessary conflicts version

### ISSUE THREAD

**Issue by rios0rios0** [Genymobile/scrcpy#1923]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Ubuntu 18.04.5 LTS (4.15.0-124-generic)
 - scrcpy version: 1.16
 - installation method: snap
 - device model: doesn't matter
 - Android version: doesn't matter

**Describe the bug**

Read here first: https://github.com/Genymobile/scrcpy/issues/464#issuecomment-731352871
```
❯ adb version
Android Debug Bridge version 1.0.41
Version 30.0.5-6877874
Installed as /home/rios0rios0/Android/Sdk/platform-tools/adb
❯ scrcpy.adb version
Android Debug Bridge version 1.0.39
Version 1:8.1.0+r23-5~18.04
Installed as /snap/scrcpy/254/usr/lib/android-sdk/platform-tools/adb
```

These commands above me return versions conflict, as the link above too.
The conflict: `adb server version (41) doesn't match this client (39); killing...`
The file system of Snap is read only... I want so much to remove this old and useless `adb` version installed...

Ps.: looking this:
https://github.com/Genymobile/scrcpy/issues/541#issuecomment-493654189
https://github.com/Genymobile/scrcpy/issues/599#issuecomment-502468736
I can say: just run `ADB=/path/to/correct scrcpy` doesn't work... My correct `adb` was ALWAYS in my PATH.

**Comment by rom1v** [comment]
@sisco311 Would it be possible to remove the `adb` dependency in the snap package (or make it optional)? It causes a lot of problems using snap 😞

**Comment by rom1v** [comment]
> I can say: just run ADB=/path/to/correct scrcpy doesn't work...

What command exactly? What is the exact error message (full output of scrcpy)?

**Comment by rios0rios0** [comment]
> > I can say: just run ADB=/path/to/correct scrcpy doesn't work...
> 
> What command exactly? What is the exact error message (full output of scrcpy)?

Worked!!! With: `ADB=/correct/path/with/**adb** scrcpy`.
Thank you!

**Comment by rom1v** [comment]
> My correct `adb` was ALWAYS in my PATH.

So this command should work too: https://github.com/Genymobile/scrcpy/issues/464#issuecomment-731355129

What is the result of `which adb`?

**Comment by rios0rios0** [comment]
> > My correct `adb` was ALWAYS in my PATH.
> 
> So this command should work too: [#464 (comment)](https://github.com/Genymobile/scrcpy/issues/464#issuecomment-731355129)
> 
> What is the result of `which adb`?

In the past moments, I ran and didn't work. The same behavior occurred... Kill correct and start wrong... After all, thank you... Working now...

**Comment by kcstrom** [comment]
Setting ADB in the environment also does not work for me on Ubuntu18.04.

```
$ ADB=$(which adb) scrcpy
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
exec: No such file or directory
ERROR: Command not found: [/my/path/to/adb], [push], [/usr/local/share/scrcpy/scrcpy-server], [/data/local/tmp/scrcpy-server.jar]
ERROR: (make 'adb' accessible from your PATH or define its fullpath in the ADB environment variable)
INFO: You may install 'adb' by "apt install adb"
ERROR: Could not execute "adb push"
$ echo $?
73
```
Where /my/path/to/adb matches the output of which adb and is where I normally use adb from.

**Comment by rom1v** [comment]
I would suggest to use a non-snap version.

**Comment by doob09** [comment]
Remove snap version
Do a manual build : https://github.com/Genymobile/scrcpy/blob/master/BUILD.md . 
It helps me solve the issue

**Comment by kibugenzaKing** [comment]
I found a simple solution for this issue, simply connect your phone tcpip using scrcpy.adb, and not adb. 

Example: 
When connecting adb for debugging purpose in VSCODE, you normally run in terminal 

Step1: 
NB: this command runs after connecting via a good USB, and by enabling usb debugging and wireless debugging.

`adb tcpip 5555
`
step2: 
`adb connect <ip address>
`usage: `adb connect 103.20.440.22`  // replace these numbers with your phone's ip address. found in settings/about phone/ on android 13. 

when you specifically want to use scrcpy only. 
 
Step1: 
`scrcpy.adb tcpip 5555
`
step2: 
`scrcpy.adb connect <ip address>
`usage: `scrcpy.adb connect 103.20.440.22`  // replace these numbers with your phone's ip address. found in settings/about phone/ on android 13. 

that's all, the key is to use scrcpy.adb for adb purpose and adb only for vscode debugging.
