### ISSUE TITLE
Apt (.deb) package change from "Recommends" to "Suggests" for Android packages

### ISSUE THREAD

**Issue by nognognoggynog** [Genymobile/scrcpy#1926]
Apt (.deb) package change from "Recommends" to "Suggests" for Android packages

Reference bug https://github.com/Genymobile/scrcpy/issues/1925 for the reasoning behind this issue

**Comment by nognognoggynog** [comment]
https://www.debian.org/doc/manuals/debian-faq/pkg-basics.en.html#depends

"Package A suggests Package B if B contains files that are related to (and usually enhance) the functionality of A."

**Comment by rom1v** [comment]
cc @yangfl

**Comment by yangfl** [comment]
What? This ought to be a hard dependency since scrcpy itself actually won't work without adb, and there's only one package in the repository that provides adb. For 90% users pulling adb is a must for a working scrcpy, and it is unfair to mess everything up just because a small portion of people try to bypass dependency mechanism.

Still I'd suggest "hoding" adb to prevent installation in that situation.

**Comment by nognognoggynog** [comment]
I shall remove scrcpy now, thanks for the info, will wait for the AppImage

**Comment by yangfl** [comment]
Well from the distro view Google SDK is the unofficial. The binaries for the Android SDK downloadable from Google have a proprietary license so it will never be part of Debian. It's OK if you want to manage your binaries outside of Debian mechanism.

But hey threatening is not how open source software collaboration is. You'd reminder me of a problem of Recommends handling, and I will talk to other Debian developers about it.

**Comment by nognognoggynog** [comment]
Linux is being fucked up the ass by distros trying to app stores

**Comment by rom1v** [comment]
There are typically 2 types of users for scrcpy:
 - Android developers, who necessarily have `adb` installed from the SDK, so the package dependency is an annoyance (as a developer, I'm in this category);
 - non-Android developers, who want `scrcpy` with all necessary dependencies installed.

I thought `--no-install-recommends` was only necessary on the initial `apt install`, not on every `apt update`, as you seem to suggest in #1925. Is it the case?

> You won't have your scrcpy on my machine unless I use an AppImage now

This is inappropriate. TBH the situation where users threaten open source developers to uninstall their software if they don't comply with whatever they require looks a bit ridiculous. What do they expect? "Oh no, please, don't leave, we will do whatever you want, but please, I beg you, continue to use our software that we provide to you for free!" 😆
