### ISSUE TITLE
Czech accented letters

### ISSUE THREAD

**Issue by a1346054** [Genymobile/scrcpy#193]
Letters like these work:

`ýáíéú`

Still need these to fully support Czech language:

`ěščřžňťďů`

Thank you. The app is awesome.

**Comment by rom1v** [comment]
For reference:
 - the supported accents for composition: https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/view/KeyCharacterMap.java#189
 - the ones implemented in scrcpy: https://github.com/Genymobile/scrcpy/blob/master/server/src/main/java/com/genymobile/scrcpy/KeyComposition.java#L18

**Comment by a1346054** [comment]
Looks like it needs addCombining('\u030C', ACCENT_CARON);

because Caron is the thing needed for Czech https://en.wikipedia.org/wiki/Caron

**Comment by a1346054** [comment]
And also addCombining('\u030A', ACCENT_RING_ABOVE);

for the `ů` character

**Comment by a1346054** [comment]
I don't know how to do programming but I think I understand your code. I will try to make a pull request.

**Comment by a1346054** [comment]
I created #194 but I do not know if it works. Your code is very easy to read though.
