### ISSUE TITLE
Secure display doesn't work on the latest Android build

### ISSUE THREAD

**Issue by wjf3121** [Genymobile/scrcpy#1935]
In the latest Android code, secure display can only be created by UID AID_GRAPHICS or AID_SYSTEM:
https://android.googlesource.com/platform/frameworks/native/+/refs/heads/master/services/surfaceflinger/SurfaceFlinger.cpp#5661

While scrcpy will try to create one by shell user, which will no longer work:
https://github.com/Genymobile/scrcpy/blob/master/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java#L201

I'm not sure if there's any fix other than creating a non-secure display when the OS version is after Q, any thoughts?

**Comment by wjf3121** [comment]
Sorry, the Andoird OS Code I pointed is not corrected. Looks like the code I was looking at is still not merged to the public repo. Closing it.

**Comment by rom1v** [comment]
Oh, that's a bad news :disappointed: 

> I'm not sure if there's any fix other than creating a non-secure display when the OS version is after Q?

I think that we won't have the choice, indeed.

**Comment by rom1v** [comment]
> I'm not sure if there's any fix other than creating a non-secure display when the OS version is after Q, any thoughts?

After R? (Android 12 is S)

Refs #2129

**Comment by wjf3121** [comment]
Yep, should be "after R". Sorry for the confusion.

**Comment by VishalKumarX100** [comment]
How to create a non secure display

**Comment by rom1v** [comment]
Use scrcpy >= 1.18.

**Comment by VishalKumarX100** [comment]
I meant the complete set of steps

**Comment by RiggiG** [comment]
Root users may use [this fork](https://github.com/RiggiG/scrcpy-root/tree/dev) which simply runs the scrcpy-server as the system user: https://github.com/Genymobile/scrcpy/issues/3049#issuecomment-1603612740
