### ISSUE TITLE
Pixel 3 is run at only 1fps or 2fps ？ running so slowly.

### ISSUE THREAD

**Issue by ruinmi** [Genymobile/scrcpy#1942]
Pixel 3 Android 11
cmd code

C:\Users\rmJay\Desktop\a>scrcpy
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
C:\Users\rmJay\Desktop\a\scrcpy-server: 1 file pushed, 0 skipped. 33.5 MB/s (33622 bytes in 0.001s)
[server] INFO: Device: Google Pixel 3 (Android 11)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2160

**Comment by rom1v** [comment]
What if you record and play the file?

```
scrcpy --record file.mkv
```

?

Is the device screen broken?

**Comment by ruinmi** [comment]
The recorded video is also stuck. Yes, the screen of the mobile phone has been broken

**Comment by ruinmi** [comment]
The cable on the screen of the mobile phone is broken，┭┮﹏┭┮

**Comment by rom1v** [comment]
> Yes, the screen of the mobile phone has been broken

That's "expected" then: #1285 #1353 #1456

Out of curiosity, does it work better with another encoder? https://github.com/Genymobile/scrcpy/pull/1827#issuecomment-725933512

**Comment by ruinmi** [comment]
C:\Users\rmJay\Desktop\a>adb shell wm size 1080x2160

C:\Users\rmJay\Desktop\a>adb shell wm size
Physical size: 640x480
Override size: 1080x960

C:\Users\rmJay\Desktop\a>adb shell wm size 128x256

C:\Users\rmJay\Desktop\a>adb shell wm size
Physical size: 640x480
Override size: 200x256

C:\Users\rmJay\Desktop\a>adb shell wm size 500x2000

C:\Users\rmJay\Desktop\a>adb shell wm size
Physical size: 640x480
Override size: 500x960

C:\Users\rmJay\Desktop\a>adb shell wm size 1500x1700

C:\Users\rmJay\Desktop\a>adb shell wm size
Physical size: 640x480
Override size: 1280x960

C:\Users\rmJay\Desktop\a>adb shell wm size 960x1280

C:\Users\rmJay\Desktop\a>adb shell wm size
Physical size: 640x480
Override size: 960x960

C:\Users\rmJay\Desktop\a>adb shell wm size 1280x960

C:\Users\rmJay\Desktop\a>adb shell wm size
Physical size: 640x480
Override size: 1280x960

C:\Users\rmJay\Desktop\a>adb shell wm density
Physical density: 440

**Comment by ruinmi** [comment]
now my  wm height stuck at 960px, can't change it anymore. Is it because I removed the screen

**Comment by ruinmi** [comment]
another problem:
After a period of time, it will become not smooth, need to restart to smooth again

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/issues/1285#issuecomment-917513993
