### ISSUE TITLE
Mod + Shift + o doesn't turn screen on

### ISSUE THREAD

**Issue by rajeshisnepali** [Genymobile/scrcpy#1946]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Ubuntu 20.04
 - scrcpy version: 1.12.1
 - installation method: apt
 - device model: Xiaomi A2 Lite
 - Android version: 10

**Describe the bug**
Normally I use `scrcpy -b2M  -m800` to connect wirelessly. Sometimes I hit `Mod+o` to turn off the screen and it works fine. But hitting `Mod+Shift+o` doesn't turn the screen on. I had to turn it on by clicking the power button on the phone or hitting `Mod+o`.

My Scrcpy logs

```
➜  ~ scrcpy -b2M  -m800 --always-on-top
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed. 1.3 MB/s (24773 bytes in 0.018s)
INFO: Initial texture: 376x800
[server] INFO: Device screen turned off
[server] INFO: Device screen turned off

```
P.S. My MOD is (left)`Ctrl`

**Comment by rom1v** [comment]
Try the latest version (v1.16).

**Comment by rajeshisnepali** [comment]
> Try the latest version (v1.16).

Snap is very buggy for me. I don't see an updated version in apt. Do I have to depend on  `snap` only?

**Comment by rom1v** [comment]
You could build from sources: https://github.com/Genymobile/scrcpy/blob/master/BUILD.md

Use the prebuilt server to avoif building the Android part: https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#prebuilt-server

**Comment by NomadicVoxel** [comment]
Sorry to reopen a dead thread but I'm having this same bug in a modern build. Win11, Chocolatey build, v1.22, Moto G Stylus. Alt-shift-o has no effect on the mirror window or the phone, but the terminal does acknowledge with `[server] INFO: Device screen turned on`

**Comment by rom1v** [comment]
Scrcpy just requests to change the "power mode". How the device behaves/works in reaction is device-dependent.
