### ISSUE TITLE
[HUAWEI BAH-W09] Not showing any mirroring screen

### ISSUE THREAD

**Issue by narugit** [Genymobile/scrcpy#1949]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Ubuntu 18.04.3 LTS (Bionic Beaver)
 - scrcpy version: 1.16
 - installation method: snap
 - device model: HUAWEI BAH-W09
 - Android version: 7

**Describe the bug**
I execute `scrcpy`, but it does not show any mirroring screen.

I also attach logcat log ([scrcpy-logcat.log](https://github.com/Genymobile/scrcpy/files/5633289/scrcpy-logcat.log)).

```console
$ scrcpy
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 3.4 MB/s (33622 bytes in 0.009s)
[server] INFO: Device: HUAWEI BAH-W09 (Android 7.0)
INFO: Renderer: opengl
INFO: OpenGL version: 3.0 Mesa 20.0.8
INFO: Trilinear filtering enabled
INFO: Initial texture: 1920x1200
```

**Comment by rom1v** [comment]
It seems the decoder just blocks.

Could you try with a lower definition: `scrcpy -m1024`?

Or try another encoder: https://github.com/Genymobile/scrcpy/pull/1827#issuecomment-725933512

**Comment by narugit** [comment]
Thank you for quick response!

> Could you try with a lower definition: scrcpy -m1024?

It works! Thank you for a lot!!!
