### ISSUE TITLE
Can't get scrcpy to control android (macOS Big Sur)

### ISSUE THREAD

**Issue by SetuCoder** [Genymobile/scrcpy#1952]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Describe the bug**
Unable to control my android from my mac, got ADB installed too. The screenshare is fine. Please help

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#control-issues

**Comment by deekshithpranav** [comment]
Hello guys, I am a newbie and don't know much about GitHub but I am very interested in this project and would like to contribute as much as possible. (I am good at C programming and JAVA). Please help me get started.

**Comment by SetuCoder** [comment]
Awesome! Thank you 😄
