### ISSUE TITLE
SHowing disconnected

### ISSUE THREAD

**Issue by TechReviews919** [Genymobile/scrcpy#1953]
- [x ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - Windows 10 with Fire Table  10 HD.]
 - scrcpy version: 9.1
 - installation method: [ Windows release...]
 - device model: Window Tablet HD 10 V9
 - Android version: [9]

I followed directions and The Fore Tablet was not showing connected. I then realizes I had to go into the settings and set it to file transfer. Even after doing so is till get not connected error. ADB recognizes the Tablet. see screen below.
 
![image](https://user-images.githubusercontent.com/68554301/101290303-4a587080-37cf-11eb-994e-e6076e4694d8.png)

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

**Comment by TechReviews919** [comment]
Thanks rom1v is says  tri with lower definition. Please excuse my ignorance where would I do this?
scrcpy -m 1920
scrcpy -m 1024
scrcpy -m 800

**Comment by TechReviews919** [comment]
Got figured it out than you so much this is going to be great
