### ISSUE TITLE
java.lang.NumberFormatException: For input string: "1.16"

### ISSUE THREAD

**Issue by MuhammedTaha02** [Genymobile/scrcpy#1955]
- [*] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [*] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Gentoo Linux
 - scrcpy version: 1.16
 - installation method: ebuild
 - device model: SM-G925F
 - Android version: 9

**Describe the bug**
Hello. I installed scrcpy with ebuild file on Gentoo. But it doesn't work. How can I solve the problem?

```
$ scrcpy
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed. 0.8 MB/s (18570 bytes in 0.022s)
ERROR: Exception on thread Thread[main,5,main]
java.lang.NumberFormatException: For input string: "1.16"
	at java.lang.Integer.parseInt(Integer.java:615)
	at java.lang.Integer.parseInt(Integer.java:650)
	at com.genymobile.scrcpy.Server.createOptions(Server.java:52)
	at com.genymobile.scrcpy.Server.main(Server.java:101)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:341)


~$ adb --version
Android Debug Bridge version 1.0.40
Version 9.0.0_r3
Installed as /usr/bin/adb


~$ java -version
openjdk version "1.8.0_272"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_272-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.272-b10, mixed mode)


~$ scrcpy -v
scrcpy 1.16

dependencies:

SDL 2.0.12
libavcodec 58.91.100
libavformat 58.45.100
libavutil 56.51.100


~$ cat /etc/os-release
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo/Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
```

**Comment by rom1v** [comment]
> java.lang.NumberFormatException: For input string: "1.16"

You don't use the same version for the server and the cliebt. If you use the prebuilt server, don't forget to download the version which matches the client version you compile.

**Comment by MuhammedTaha02** [comment]
> You don't use the same version for the server and the cliebt. If you use the prebuilt server, don't forget to download the version which matches the client version you compile.

I understand :/
What should I do?

**Comment by MuhammedTaha02** [comment]
@rom1v

**Comment by rom1v** [comment]
Use the correct [prebuilt server](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#prebuilt-server).

**Comment by MuhammedTaha02** [comment]
> Use the correct [prebuilt server](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#prebuilt-server).

~/D/scrcpy $ meson x --buildtype release --strip -Db_lto=true \
                 -Dprebuilt_server=./scrcpy-server-v1.16

ERROR: Neither directory contains a build file meson.build.

**Comment by rom1v** [comment]
What does your `~/D/scrcpy` contain? It must be the `git clone` of this repository.

```bash
ls
```

**Comment by MuhammedTaha02** [comment]
> What does your `~/D/scrcpy` contain? It must be the `git clone` of this repository.
> 
> ```shell
> ls
> ```

Huh my fault. I ran this command in the wrong folder. This worked. Scrcpy works fine. Thanks for all your help.

**Comment by olea** [comment]
I'm having the same problem than OP.

> Use the correct [prebuilt server](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#prebuilt-server).

I'm using scrcpy in Fedora 33:

```
$ rpm -q scrcpy
scrcpy-1.16-1.x86_64
$ scrcpy -v
scrcpy 1.16

dependencies:
 - SDL 2.0.12
 - libavcodec 58.54.100
 - libavformat 58.29.100
 - libavutil 56.31.100

```
The package comes from the [RPMSphere third repository](https://fedora.pkgs.org/33/rpm-sphere-x86_64/scrcpy-1.16-1.x86_64.rpm.html).

I would suppose the application is fully compiled and bundled and its dependencies satisfied using the install system (DNF).

What could be my problem? Something related with this RPM build?

Thanks.

**Comment by rom1v** [comment]
> scrcpy 1.16

Where is your `scrcpy-server`? Which version? (check with `scrcpy -Vdebug`)

The prebuilt v1.16 is here if you want: https://github.com/Genymobile/scrcpy/blob/479d10dc22b70272187e0963c6ad24d754a669a2/BUILD.md#prebuilt-server

**Comment by olea** [comment]
> Where is your `scrcpy-server`? Which version? (check with `scrcpy -Vdebug`)

``` 
$ scrcpy -Vdebug
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
DEBUG: Using server: /usr/share/scrcpy/scrcpy-server
/usr/share/scrcpy/scrcpy-server: 1 file pushed. 0.8 MB/s (18802 bytes in 0.023s)
DEBUG: Screensaver enabled
ERROR: Exception on thread Thread[main,5,main]
java.lang.NumberFormatException: For input string: "1.16"
	at java.lang.Integer.parseInt(Integer.java:615)
	at java.lang.Integer.parseInt(Integer.java:650)
	at com.genymobile.scrcpy.Server.createOptions(Server.java:52)
	at com.genymobile.scrcpy.Server.main(Server.java:101)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338)
DEBUG: Server terminated
$ rpm -qf /usr/share/scrcpy/scrcpy-server
scrcpy-1.16-1.x86_64
$ ls -l /usr/share/scrcpy/scrcpy-server
-rw-r--r--. 1 root root 18802 ago 24 06:00 /usr/share/scrcpy/scrcpy-server

```

So the server is bundled with the client and supposedly using the same configurations.

**Comment by rom1v** [comment]
The server is obviously not v1.16. There is an issue with your package.

As a workaround, download the prebuilt v1.16 (posted above), then:
```bash
export SCRCPY_SERVER=/path/to/your/scrcpy-server-v1.16
scrcpy
```

or [build the app manually](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md).
