### ISSUE TITLE
"Right click" map to "hold" in mobile device

### ISSUE THREAD

**Issue by rajeshisnepali** [Genymobile/scrcpy#1958]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
Hello, normally, we do right click for additional options on our computer. The same (hold) for additional options in mobile devices. Whenever I've connected to my mobile device, I hit right click to expand options but it goes back. 

**Describe the solution you'd like**
Clicking right click in computer should show additional options on mobile. 

**Additional context**
Apart from my primary request, how to open recent applications with `mod` shortcut key? I didn't find one.

**Comment by rom1v** [comment]
On `dev` branch (not released yet), there is an option `--forward-all-clicks` to inject right-click instead of pressing BACK.

See #1302 #1613.

**Comment by rajeshisnepali** [comment]
> Apart from my primary request, how to open recent applications with `mod` shortcut key? I didn't find one.

And this?

**Comment by rom1v** [comment]
<kbd>MOD</kbd>+<kbd>s>/kbd> (`APP_SWITCH`)

https://github.com/Genymobile/scrcpy#shortcuts

**Comment by rajeshisnepali** [comment]
> MOD+s (`APP_SWITCH`)

Well, in that case, I think I have to open a new bug issue. I'm quite sure I read all through shortcuts. 

It opens recent tabs but it's not constant(stable). Sometimes it works & sometimes it fails. 

My scrcpy 1.16
Android 10

**Comment by rom1v** [comment]
Try with `adb shell input keyevent APP_SWITCH`.

Is the behavior the same?

**Comment by rajeshisnepali** [comment]
> Try with `adb shell input keyevent APP_SWITCH`.

so sorry but how am I supposed to do this? I got no idea. 😔

**Comment by rajeshisnepali** [comment]
> Is the behavior the same?

Yes, the behavior is the same. I noticed that `MOD`+`s` (APP_SWITCH) only worked when I'm on the home screen. And if I'm in any app, and try to hit (APP_SWITCH), I get a blank page (ss down below). 

![Screenshot from 2020-12-09 14-49-17](https://user-images.githubusercontent.com/23610013/101608457-d667d380-3a2d-11eb-8c3d-1cbd7d2c4579.png)

**Comment by rajeshisnepali** [comment]
I'm closing this issue & issuing a new for the above APP_SWITCH in the next issue #1964
