### ISSUE TITLE
Low quality on MacOS Big Sur 11.0.1

### ISSUE THREAD

**Issue by binhodev** [Genymobile/scrcpy#1959]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [macOS 11.0.1]
 - scrcpy version: [1.16]
 - installation method: [brew]
 - device model: [Samsung Galaxy S7 SM-G930F]
 - Android version: [Android 8.0]

**Describe the bug**
On macOS Big Sur i'm having this problem with quality of screen, but no Catalina works flawless.

![Captura de Tela 2020-12-08 às 10 57 46](https://user-images.githubusercontent.com/58571495/101493277-a2fd4a00-3944-11eb-9da6-a1886757fe8a.png)

```
binho@iMac-de-Binho ~ % scrcpy   
2020-12-08 11:02:32.010 scrcpy[15123:89757] INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.16_2/share/...ped. 19.4 MB/s (33622 bytes in 0.002s)
[server] INFO: Device: samsung SM-G930F (Android 8.0.0)
2020-12-08 11:02:32.671 scrcpy[15123:89757] INFO: Renderer: metal
2020-12-08 11:02:32.674 scrcpy[15123:89757] INFO: Initial texture: 1080x1920
binho@iMac-de-Binho ~ % scrcpy -v
scrcpy 1.16

dependencies:
 - SDL 2.0.12
 - libavcodec 58.91.100
 - libavformat 58.45.100
 - libavutil 56.51.100
```

**Comment by rom1v** [comment]
I guess it's basically #40: a high resolution device displayed in a small window.

If you press <kbd>Cmd</kbd>+<kbd>g</kbd> (to resize to 1:1 pixel), is the quality ok?

**Comment by binhodev** [comment]
> I guess it's basically #40: a high resolution device displayed in a small window.
> 
> If you press Cmd+g (to resize to 1:1 pixel), is the quality ok?

Hello, thanks for help-me.
If reduce resolution to 1280x720 continues with same quality poor.
Tried the shortcut, but don't worked too, same quality.

**Comment by binhodev** [comment]
On macOS Catalina 10.15.5

<img width="449" alt="Captura de Tela 2020-12-08 às 11 39 21" src="https://user-images.githubusercontent.com/58571495/101497937-443acf00-394a-11eb-8b72-b98421151082.png">

```
binho@iMac ~ % scrcpy 
2020-12-08 11:42:18.987 scrcpy[1144:10945] INFO: scrcpy 1.14 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.14_1/share/...ped. 18.1 MB/s (33142 bytes in 0.002s)
[server] INFO: Device: samsung SM-G930F (Android 8.0.0)
2020-12-08 11:42:19.572 scrcpy[1144:10945] INFO: Created renderer: metal
2020-12-08 11:42:19.573 scrcpy[1144:10945] INFO: Renderer: metal
2020-12-08 11:42:19.576 scrcpy[1144:10945] INFO: Initial texture: 1080x1920
```

I checked that the version of scrcpy is different, I will try to use the same version.

**Comment by rom1v** [comment]
> If reduce resolution to 1280x720 continues with same quality poor.

If you use `-m1280`, the quality loss occurs before the encoding.

> I just don't understand why Catalina works normally.

The window in the first screenshot (with poor quality) has a low definition: 403×717.
The window in your second screenshot is 816x1459 (hence the difference).

**Comment by binhodev** [comment]
> > If reduce resolution to 1280x720 continues with same quality poor.
> 
> If you use `-m1280`, the quality loss occurs before the encoding.
> 
> > I just don't understand why Catalina works normally.
> 
> The window in the first screenshot (with poor quality) has a low definition: 403×717.
> The window in your second screenshot is 816x1459 (hence the difference).

**Comment by binhodev** [comment]
Ops... I closed without intention.

> > The window in the first screenshot (with poor quality) has a low definition: 403×717.
> > The window in your second screenshot is 816x1459 (hence the difference).

This is what I was observing just now, I found it very strange, it could be something in the system.

**Comment by binhodev** [comment]
I found the problem! 🤦🏾‍♂️
I applied a HiDPI patch for me monitor, now are works flawless.  

Thanks!
