### ISSUE TITLE
MOD+s (APP_SWITCH) doesn't work well

### ISSUE THREAD

**Issue by rajeshisnepali** [Genymobile/scrcpy#1964]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Ubuntu20.04.1 LTS
 - scrcpy version: 1.16
 - installation method: snap
 - device model: Xiaomi Mi A2 Lite
 - Android version: 10

**Describe the bug**
Hitting `MOD`+`s` (APP_SWITCH) doesn't work well. It works only when I'm on the home screen. If I'm on any app and try to hit `MOD`+`s`, it doesn't work. 

`adb shell input keyevent APP_SWITCH` has the same behaviour

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 1.8 MB/s (33622 bytes in 0.018s)
[server] INFO: Device: Xiaomi Mi A2 Lite (Android 10)
INFO: Renderer: opengl
INFO: OpenGL version: 3.0 Mesa 20.0.8
INFO: Trilinear filtering enabled
INFO: Initial texture: 376x800
[server] INFO: Device screen turned off
[server] INFO: Forcing screen off

```

#### Screenshots
I had to post this screenshot. I am getting this blank screen. 
![101608457-d667d380-3a2d-11eb-8c3d-1cbd7d2c4579](https://user-images.githubusercontent.com/23610013/101761148-e7831400-3b03-11eb-9b8f-efe4688ba786.png)

**Comment by rom1v** [comment]
Since you [said](https://github.com/Genymobile/scrcpy/issues/1958#issuecomment-741613990) that:

```
adb shell input keyevent APP_SWITCH
```

causes the same behavior, then this is a bug/feature in your device ROM.

**Comment by rajeshisnepali** [comment]
So, I believe it generally works on the other phone or in major phones.

**Comment by rom1v** [comment]
Yes, it works on all my devices.

**Comment by rajeshisnepali** [comment]
Well, once let me try it on my other device

**Comment by rajeshisnepali** [comment]
Yeah, I confirmed. It's the BUG on my phone.
