### ISSUE TITLE
adb: error: no devices/emulators found

### ISSUE THREAD

**Issue by SMerlock7** [Genymobile/scrcpy#1969]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 8.1 Pro
 - scrcpy version: 1.16
 - installation method: Windows release
 - device model: Realme X2
 - Android version: 10

**Describe the bug**
I get this on starting scrcpy.exe
```
adb: error: failed to get feature set: no devices/emulators found 
ERROR: "adb push" returned with value 1
```
tried running `adb devices` : the list of devices comes up blank
Phone is connected via USB(to transfer files) & USB debugging is enabled.
I read the FAQ for this issue, where it says I may need some drivers for Windows; but I checked in the Device Manager and found that the driver software is up to date. And I'm able to transfer files between the phone and pc as usual.
Can someone help me?

**Comment by SMerlock7** [comment]
I managed to make it work. I found that the driver software for ADP interface was indeed not installed. 
Last time, I was checking for it under "Portable Devices" because it showed the name of my device.
![image](https://user-images.githubusercontent.com/75471109/102021196-18817400-3da4-11eb-9f00-bd98e07d8515.png)
But after some trying, I noticed "ADB Interface" under "Android device", which said driver was not installed.
Then as per [this](https://developer.android.com/studio/run/oem-usb.html), I started searching for the driver software for my device(Realme), but couldn't find any. 
So I downloaded the [Google USB driver](https://developer.android.com/studio/run/win-usb) ,just to give it a try; and installed by [following these steps](https://visualgdb.com/KB/usbdebug-manual/) (without installing android sdk). 
Then it worked :)

**Comment by ping335** [comment]
I have the same problem on Linux Debian

**Comment by rom1v** [comment]
What is the result of `adb devices`?

**Comment by ping335** [comment]
empty.

**Comment by rom1v** [comment]
Probably an issue with your udev rules. (search "adb udev rules" on the internet)

**Comment by ping335** [comment]
I rewrote udev for my device as written [here](https://flutterq.com/solved-adb-devices-no-permissions-user-in-plugdev-group-are-your-udev-rules-wrong/), but it didn't help

**Comment by ayhon** [comment]
+1 for me, but in my case I do not have access to my phone anymore (Screen is broken, cannot see anything)
