### ISSUE TITLE
Blurry icons when window resized

### ISSUE THREAD

**Issue by telegramcore** [Genymobile/scrcpy#197]
hi romain! How can I change the resolution?

**Comment by rom1v** [comment]
scrcpy -m1024

https://github.com/Genymobile/scrcpy/blob/master/README.md#run

**Comment by RedMoonOTInetwork** [comment]
Thanks

**Comment by RedMoonOTInetwork** [comment]
![cattura 000277](https://user-images.githubusercontent.com/37411589/42771389-554814fe-8927-11e8-8ec4-1928e644856b.png)


the notification icons in the status bar are blurry :c how can i to fix it?

**Comment by rom1v** [comment]
If you decrease the resolution/definition, that's expected I guess. Does it happen without changing definition?

**Comment by RedMoonOTInetwork** [comment]
no

**Comment by RedMoonOTInetwork** [comment]
how do I get it back by default?

**Comment by RedMoonOTInetwork** [comment]
Ah and anyway the icons have checked and are blurred in the status bar even without making changes

**Comment by RedMoonOTInetwork** [comment]
Tomorrow i try thanks

**Comment by RedMoonOTInetwork** [comment]
Ok i tried: I'm not blurry if I give that command but it increases the size of the screen too much and I'm forced to reduce the window, so they appear again like [here](https://github.com/Genymobile/scrcpy/issues/197#issuecomment-405309398)

**Comment by gladiatorgiftson** [comment]
I think i found what happening this but i am not sure 
![Screenshot (25)](https://user-images.githubusercontent.com/42843422/75653749-31d98980-5c84-11ea-8e73-cec156d563cd.png)

windows setting the resolution to default computer screen resolution

**Comment by rom1v** [comment]
Duplicate of #40.
