### ISSUE TITLE
I cannot debug this program

### ISSUE THREAD

**Issue by KateLevien** [Genymobile/scrcpy#1972]
Hello, I tried to run your project on Android studio, and I am having a hard time while debugging it.  
I tried to do the remote debugging on android 4.1. Based on your developer's instruction, I tried to run this program at localhost 5005 port.
But I continuously watched this message **"handshake failed - connection prematurally closed"**. (I used the 8.0 apache tomcat to establish the web server. ) 
I will be glad if I can debug this program by myself. Can I get to know the exact steps? Thanks a million.

**Comment by rom1v** [comment]
> Based on your developer's instruction, I tried to run this program at localhost 5005 port.

Did you try with `-Dserver_debugger_method=old`?

https://github.com/Genymobile/scrcpy/blob/master/DEVELOP.md#debug-the-server

> (I used the 8.0 apache tomcat to establish the web server. )

?

Why a web server?

**Comment by KateLevien** [comment]
Oops, I was completely wrong. I thought that it was necessary to build the web server.
I think I have to start the debugging again with meson. But I haven't use the Meson Build System.
According to your explanation, (I mean https://github.com/Genymobile/scrcpy/blob/master/BUILD.md )
I found out that it will need Debian. Is it compulsory to install the another operating system then?
(Sorry to ask you those foolish question. I am baby developer)
