### ISSUE TITLE
Commands not recognized, need help updating

### ISSUE THREAD

**Issue by getcheesed** [Genymobile/scrcpy#1979]
Hey, I installed scrcpy on linux mint 20 using **apt install scrcpy**. Everything works perfectly but some commands are not recognized (ex. scrcpy --rotation 1). Other users have had this problem as well and they were told to update their software but I don't know how to do that on linux. i'm new to the OS and I did not find a clear answer. The --version command says I'm on scrcpy 1.12.1. Any help on getting that command to run?

**Comment by rom1v** [comment]
Follow the build instructions: https://github.com/Genymobile/scrcpy/blob/master/BUILD.md

For simplicity, use the prebuilt server: https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#prebuilt-server

**Comment by getcheesed** [comment]
> Follow the build instructions: https://github.com/Genymobile/scrcpy/blob/master/BUILD.md
> 
> For simplicity, use the prebuilt server: https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#prebuilt-server

yes i did follow that but i gave up. Everytime i try to run the libavcodec-dev etc. commands under system spesific steps for linux it says the command is not found or something along those lines

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#debianubuntu

The `libavcodec-dev` line is the following of the `sudo apt-get install`. You can just copy-paste the whole multiline block.

**Comment by getcheesed** [comment]
> https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#debianubuntu
> 
> The `libavcodec-dev` line is the continuation of the `sudo apt-get install`. You can just copy-paste the whole multiline block.

shit, i thought i already tried that. ANyway now it worked but i have another problem. I copy the code under prebuilt server and i specify the path to the server. Then ninja -cx spits out failure: build failed with an exception " could not determine the dependencies of task 'server:compileReleaseJavaWIthJavac"

SDK location not found define location with an ANDROID_SDK_ENVIRONMENT variable or by setting the sdk.dir path in your project's local properties at '/home/haris/scrcpy/local.propeties'

**Comment by rom1v** [comment]
If you have these server compilation errors, then you didn't pass the `-Dprebuilt_server=/path/to/scrcpy-server` correctly to the meson command.

`rm -rf x` and retry:
```bash
meson x --buildtype release --strip -Db_lto=true -Dprebuilt_server=/bla/bla/bla/scrcpy-server-v1.16
```
(adapt the path)

**Comment by getcheesed** [comment]
> If you have these server compilation errors, then you didn't pass the `-Dprebuilt_server=/path/to/scrcpy-server` correctly to the meson command.
> 
> `rm -rf x` and retry:
> 
> ```shell
> meson x --buildtype release --strip -Db_lto=true -Dprebuilt_server=/bla/bla/bla/scrcpy-server-v1.16
> ```
> 
> (adapt the path)

wait. the server is sitting in my downloads folder. to specify the path i right clicked on it, then properties and then i looked at the location where it says /home/haris/Downloads.
So the command should be meson x --buildtype release --strip -Db_lto=true -Dprebuilt_server=/home/haris/Downloads/scrcpy-server-v1.16
Am I stupid?

**Comment by rom1v** [comment]
> `meson x --buildtype release --strip -Db_lto=true -Dprebuilt_server=/home/haris/Downloads/scrcpy-server-v1.16`

Yes, that's the correct command. What's its output?

**Comment by getcheesed** [comment]
> > `meson x --buildtype release --strip -Db_lto=true -Dprebuilt_server=/home/haris/Downloads/scrcpy-server-v1.16`
> 
> Yes, that's the correct command. What's its output?

dude, a thousand thanks. I got this to work and now it's updated. I was tired and desperate yesterday, i thought i'd never make it . Turns out it was just me being dumb. Thanks
