### ISSUE TITLE
#issue paste pc clipboard  to device it's not work

### ISSUE THREAD

**Issue by RedMoonOTInetwork** [Genymobile/scrcpy#198]
hi, i can't paste pc clipboard to device, command ctrl+v not work. how does it work exactly? but does it also work by copying images? would not it be better to drag files from pc to mobile and vice versa 
as I had already proposed [here](https://github.com/Genymobile/scrcpy/issues/128)?

**Comment by rom1v** [comment]
> how does it work exactly?

It just sends the text as if it was entered on the keyboard ([code](https://github.com/Genymobile/scrcpy/blob/v1.2/app/src/inputmanager.c#L115)).

> does it also work by copying images?

No.

**Comment by RedMoonOTInetwork** [comment]
Ok it work
