### ISSUE TITLE
android.system.ErrnoException: write failed: EBADF (Bad file descriptor)

### ISSUE THREAD

**Issue by Artem-Z86** [Genymobile/scrcpy#1980]
Help, please! I have error android.system.ErrnoException: write failed: EBADF (Bad file descriptor) everytime when run in about 5 minutes . I changed LocalSocket to Socket (java). How fixed it? 
Thanks

**Comment by rom1v** [comment]
You get the error before or after your change to a Socket?

**Comment by Artem-Z86** [comment]
After the changes.

**Comment by rom1v** [comment]
I guess there is a bug in your changes.
