### ISSUE TITLE
device unauthorized (but can't authorize it)

### ISSUE THREAD

**Issue by RobinSchapendonk** [Genymobile/scrcpy#1983]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Arch Linux
 - scrcpy version: 1.16-1
 - installation method: AUR (yay)
 - device model: A3-A20
 - Android version: 4.4

**Describe the bug**
I can connect to my tablet, but I get the message that I need to allow USB debugging, but I can't allow it, because the input of my screen is dead.

I have 1 port, which is either for the keyboard / mouse to control the tablet, or for the cable to connect scrcpy.

Is there a different way to allow it on the tablet?

**Comment by RobinSchapendonk** [comment]
I used synergy to connect, but now I get this:

```
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 252.1 MB/s (33622 bytes in 0.000s)
adb: error: closed
ERROR: "adb reverse" returned with value 1
WARN: 'adb reverse' failed, fallback to 'adb forward'
27183
```

**Comment by rom1v** [comment]
Minimum supported Android version is 5.
