### ISSUE TITLE
Can you please add switch can mirror the display? I mean display this "[" as " ]" like see in the mirror, Thanks

### ISSUE THREAD

**Issue by lnzyc** [Genymobile/scrcpy#1984]
Thanks

**Comment by lnzyc** [comment]
flip 180 degree

**Comment by lnzyc** [comment]
filp left and right

**Comment by rom1v** [comment]
Is it flipped or rotated by 180 degrees?

If it's just rotated, use <kbd>MOD</kbd≥+<kbd>←</kbd≥ and <kbd>MOD</kbd>+<kbd>←</kbd>.

https://github.com/Genymobile/scrcpy#shortcuts

**Comment by lnzyc** [comment]
not rotated, but flip, you know when you see some charactors in the mirror, like this
https://docs.gimp.org/2.10/en/gimp-layer-flip-horizontal.html
can you capture and flip the screen horizontally?
Thanks

**Comment by rom1v** [comment]
See https://github.com/Genymobile/scrcpy/issues/1380#issuecomment-626612709

**Comment by lnzyc** [comment]
many thanks
That is really help,
but I am new to everything, can you detail the steps on how to rebuild with that code？Sorry

**Comment by lnzyc** [comment]
I have download the scrcpy-master and unzip it, Which file to put those code lines into and then do the build?

**Comment by rom1v** [comment]
Follow this guide: https://github.com/Genymobile/scrcpy/blob/master/BUILD.md

> I have download the scrcpy-master and unzip it,

(you should `git clone https://github.com/Genymobile/scrcpy` for simplicity)

**Comment by lnzyc** [comment]
for me, you are too professional, I see everything on your git again and again, but still, fail to build it, and finally, I have to use pikiss to have it a success, so what you mean? what are those code lines to use where? headache

**Comment by lnzyc** [comment]
but I have rotated the screen to 3, should I change the same as b/scr/screen.c as well?
Thanks

**Comment by lnzyc** [comment]
or i have to go to somewhere else in screen.c to modify the same lines?

**Comment by lnzyc** [comment]
Hi, I have great firewall that blocked the access to android SDK, and can not build , can you please build a flip version scrcpy I can download it
Thanks!
