### ISSUE TITLE
Screenshot Hotkey

### ISSUE THREAD

**Issue by Mitsunee** [Genymobile/scrcpy#1999]
**Is your feature request related to a problem? Please describe.**
I'd like for a hotkey to take a screenshot on the device (VolumeDown + Power Button). I'm using screenshots to track loot in a game and organize them using the gallery app on my phone.

**Describe the solution you'd like**
A hotkey to send the VolumeDown+PowerButton inputs to the phone for the requires amount of time would probably be fine

**Describe alternatives you've considered**
Althought such a feature would probably take a lot longer to develop it'd be really nice if this could bypass the usual android screenshot feature and instead take a screenshot immediatly as I press the hotkey.  
My current phone delays by about 1.2s before it actually takes the screenshot and requires holding the two buttons for about 0.5s of that (rough guesses, didn't actually time it).

**Additional context**
With how I'm planning my room setup I might sometimes be a few meters away from my phone, thus taking a screenshot every few minutes would require me to get up or have to turn on my actual desk PC and use scrcpy there.

**Comment by Mitsunee** [comment]
just read through the readme again and taking screenshots is now possible via `MOD + P + ArrowDown` so this feature request is now redundant :)

**Comment by soulflyman** [comment]
Is this still possible?
I can't find anything in the FAQ and `MOD + P + ArrowDown` does not work for me.

**Comment by Mitsunee** [comment]
@soulflyman I just tried it again and it still works for my device. You have to press P and ArrowDown roughly at the same time, just like pressing the physical **p**ower and volume **down** buttons on your phone.

**Comment by soulflyman** [comment]
@Mitsunee you are right, it was just a timing issue
