### ISSUE TITLE
Screen Resolution Issue After Rotation

### ISSUE THREAD

**Issue by Duckinahat** [Genymobile/scrcpy#2]
Hi, I noticed an issue that arises when using the default camera app on my phone.  When I enter my camera in portrait mode it works fine.  If I change to landscape however the viewing window does not follow and instead gets squished.  Upon rotating back to portrait, the window remains in a weird squished state. This continues after closing the app and returning to the home screen.  I have been able to fix this by entering a different app that supports a landscape mode (such as messaging) where the window will correctly resize.  

When first initialized, the terminal shows:
`INFO: Initial texture: 1440x2560`
I have noticed that when changing orientation in most apps the computer recieves a `[h264 @ 0x7fa2140008c0] Reinit context to 1440x2560, pix_fmt: yuv420p` and then reorients the display window accordingly. However, I noticed that when the camera app changes to landscape no reinit message appears in the terminal.  Navigating to a different app and rotating yields a reinit and fixes the issue.

I am sure this is the source of the issue, I don't know how scrcpy gets the signal to reinit the display.  Wondering if there's perhaps a different signal that could be caught?

I built scrcpy on desktop Ubuntu 16.04 64-bit and it seems to be working just fine besides this.  The phone is a stock LG G5 running android 7.0

Let me know if there's any more information that would be helpful.  Thanks for looking.

**Comment by rom1v** [comment]
To avoid flickering, some camera apps are always in portrait mode.

When you rotate them, they manually rotate their components without reinitializing the camera. But this is still a portrait app!

**Comment by Duckinahat** [comment]
Interesting,  I wonder why then it leaves it in an odd state afterwards.  When the phone rotates in the camera app, the scrcpy window rotates the contents inside without resizing.  Does scrcpy get orientation information from the gyroscope as well?  

I took a series of screenshots of the window exactly as it appears.  
Portrait:
![camera_portrait](https://user-images.githubusercontent.com/6315010/37214884-478c941a-236b-11e8-9896-04c0ea4d7131.jpg)
Landscape:
![camera_landscape](https://user-images.githubusercontent.com/6315010/37214894-4de2d478-236b-11e8-837e-5fbdd60c0851.jpg)
Portrait (again):
![camera_portrait_return](https://user-images.githubusercontent.com/6315010/37214898-50aa5492-236b-11e8-8467-91198b08109e.jpg)

It seems to know the phone is horizontal, or else the second photo would simply appear sideways and not squished, correct?

**Comment by rom1v** [comment]
Thank you for the screenshots. Now, this is a bug :D

What's the camera app?

**Comment by Duckinahat** [comment]
It's the LG Camera app version 5.20.15
adb shows it as "com.lge.camera"

**Comment by rom1v** [comment]
Does it still happen with the latest version?

What about the current `dev` branch ([here](https://github.com/Genymobile/scrcpy/issues/898#issuecomment-610932491) is a binary)? With `--lock-video-orientation 1` for example.
