### ISSUE TITLE
Typing results in Russian/Cyrillic characters

### ISSUE THREAD

**Issue by Phoenix616** [Genymobile/scrcpy#20]
When typing into apps via the PC's keyboard it will input Russian/Cyrillic characters instead of "normal" ones. Neither my phone's nor my PC's layout are Russian though. (Phone is English and PC is German)

**Comment by rom1v** [comment]
Wow, that's weird. Even if you only type ASCII characters (`a`, `b`, …).

Could you provide a screenshot please, along with the keys you typed, please?
And the keyboard used in the Android settings (_Language & Input_).

**Comment by Phoenix616** [comment]
Ok, wow, thanks to your hint with the keyboard app used I figured out what the issue is: I use a Neo2 layout for AnySoftKeyboard as my keyboard app which results in the Russian characters. (even though the layout itself uses normal characters) Switching to another layout or keyboard app solves this. As this is most likely an issue with that layout app and nothing you can fix feel free to close it. (Unless you know a way to completely stop that from happening but I doubt it. If you want I can provide you with the apk to test though, not sure where I originally got it from...)
