### ISSUE TITLE
Input only works in English

### ISSUE THREAD

**Issue by Sigeria** [Genymobile/scrcpy#2000]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

 - OS: Windows 10
 - scrcpy version: 1.12.1
 - installation method: Windows release
 - device model: Xiaomi Mi Note 10 Lite
 - Android version: 10

Description:
If I try to type from my PC keyboard in my native language (Russian) I get English chars as a result and following errors:

`[server] WARN: Could not inject char u+0441`

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#special-characters-do-not-work
