### ISSUE TITLE
This adb server's $ADB_VENDOR_KEYS is not set

### ISSUE THREAD

**Issue by AlienProber** [Genymobile/scrcpy#2002]
I'm running the latest AcroLinux with the Plasma desktop and just installed Scrcpy and I get the below. I pressed accept on the phone and that's all I got.  I tried the adb-kill-server and got command not found. Help sorting this would be greatly appreciated. Thanks

```
[alienprober@TheMothership ~]$ scrcpy
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: device unauthorized.
This adb server's $ADB_VENDOR_KEYS is not set
Try 'adb kill-server' if that seems wrong.
Otherwise check for a confirmation dialog on your device.
ERROR: "adb push" returned with value 1
```

**Comment by rom1v** [comment]
Same as https://github.com/Genymobile/scrcpy/issues/1994#issuecomment-752408774 (it's an `adb` issue).

> I tried the adb-kill-server

It's `adb kill-server`.

If it still does not work disable/reenable USB debugging, reboot your device, etc.

**Comment by AlienProber** [comment]
OK that did the trick, thanks

**Comment by iluvatar1** [comment]
Hi @AlienProber , what exactly did the trick? I killed the server, restarted, enabled usb debugging and so on, and I keep getting the same error. Thanks for any advice

**Comment by guktib** [comment]
@iluvatar1, maybe a little late, but I may have the solution.

Just disable/re-enable USB debugging and reboot didn't work for me.
I had to additionally activate the option "USB debugging (Security Settings)".

![usb-debugging_security-settings](https://user-images.githubusercontent.com/66076942/124708341-715c5980-defa-11eb-8b20-779fc417483f.png)

Afterwards, SCRCPY threw an error again, but the mobile device asked if I wanted to allow USB debugging from the device - in this case my PC.

After an OK and restarting SCRCPY, it finally worked.

**Comment by iluvatar1** [comment]
Thank you, finally what worked was what you said + running adb as root with sudo

**Comment by frankleonrose** [comment]
@iluvatar1 That's often because your ~/.android/adbkey & adbkey.pub files are owned by root, as discussed [here](https://stackoverflow.com/a/32672184). `chown` them to your use/group and you won't have to run with elevated priv.

**Comment by iluvatar1** [comment]
Thanks, @frankleonrose !

**Comment by sstruchtrup** [comment]
> @iluvatar1 That's often because your ~/.android/adbkey & adbkey.pub files are owned by root, as discussed [here](https://stackoverflow.com/a/32672184). `chown` them to your use/group and you won't have to run with elevated priv.

The curse of using sudo as a catch-all problem solver.
