### ISSUE TITLE
"Target:"-parameters for scrcpy-noconsole.vbs (v1.17) don't seem to work

### ISSUE THREAD

**Issue by johnny-poncho** [Genymobile/scrcpy#2003]
Hey, through v1.16 I used the noconsole-version of scrcpy by adding a couple of start parameters to the "Start in:"-section of a shortcut of scrcpy-noconsole.exe.
Since the update to v1.17, doing the same thing with a shortcut of the new scrpy-noconsole.vbs doesn't seem to work, it just seems to ignore all these parameters that I added to the "Start in:"-section. Adding the same parameters to a shortcut of the new scrpy.exe works just fine.
What can I do?

**Comment by rom1v** [comment]
I don't know what the `Start in:` section is.

However, you could just edit (a copy of) `scrcpy-noconsole.vbs` with a text editor and add the parameters you want.

**Comment by johnny-poncho** [comment]
sorry, I meant "Target"-section, not "Start in"... (my screenshot is in german, the section that says "Ziel" is "Target".. that's where I added the parameters.
![Screenshot 2021-01-02 171407](https://user-images.githubusercontent.com/11721998/103461352-0f8a1f80-4d1e-11eb-9a0e-56da31237463.jpg)

Ok thanks, I'll try adding them with a text editor.
