### ISSUE TITLE
Possibility of expanding the (0;65535) interval, support larger display id?

### ISSUE THREAD

**Issue by gpdeepblue** [Genymobile/scrcpy#2009]
- [✔] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
My cellphone is Smartisan Pro 3, which is a Chinese brand comes with a desktop mode named TNT(Touch & Talk), so think of it as Samsung DeX. For some time, I was able to use TNT on my PC with '--display' option. After a recent update, they changed the display id of desktop image feeding to adb, starting from 100001:
![image](https://user-images.githubusercontent.com/50772485/103498387-8ab71700-4e7f-11eb-84e7-01ea4d536f01.png)
Clearly Scrcpy doesn't support the oversized display id, it gives a out-of-range(0;65535) error:
![image](https://user-images.githubusercontent.com/50772485/103498884-36149b80-4e81-11eb-9bd9-083ad6c5305d.png)
I did some hacking to cli.c, make Scrcpy accept the display id:
![image](https://user-images.githubusercontent.com/50772485/103499287-7aed0200-4e82-11eb-9706-c80843ef91f3.png)
But nope, the error pointed directly down to Android internal:
![image](https://user-images.githubusercontent.com/50772485/103504059-4896d100-4e91-11eb-9fa8-83af749d939e.png)
34468 looks like a variable overflow(=100004-65536), but I don't know where it happened.
All in all, this feels serious... and beyond my capability.

**Describe the solution you'd like**
Is it possible to enlarge the display id range? Do we have to make some change to Android code?

**Describe alternatives you've considered**
Nothing at all, if it is not quite possible I understand. We are not even clear if Smartisan's action is a violation of Android guidelines or did they made the change on purpose just to block Scrcpy.

**Additional context**
TNT is a pretty potential OS. I'm sure there is a group of people hoping to use it on PC again. And maybe, just maybe, Smartisan is making an application like Samsung Dex to support it. Before that, Scrcpy seems to be our only option.

**Comment by rom1v** [comment]
Please test [`display_id_range`](https://github.com/Genymobile/scrcpy/commit/display_id_range).

**Comment by gpdeepblue** [comment]
> Please test [`display_id_range`](https://github.com/Genymobile/scrcpy/commit/display_id_range).

Wow, that's pretty swift of you! I was wrong about the error tracing.
Scrcpy works fine now, but the result is negative, TNT gives a black screen:
![image](https://user-images.githubusercontent.com/50772485/103519139-f87b3700-4eaf-11eb-9b1e-fe5fc5457a7d.png)
There is another way TNT work, I'll test it accordingly. The way I see it, Smartisan did block Scrcpy on purpose. :-( 
Either way, thank you, Romain. Good job there.

**Comment by rom1v** [comment]
> ```
> [server] WARN: Display doesn't have FLAG_SUPPORTS_PROTECTED_BUFFERS
> ```

See discussion https://github.com/Genymobile/scrcpy/pull/1238.

**Comment by rom1v** [comment]
> Scrcpy works fine now

OK, cool, merged into `dev` aa8b5713896935e2dfe22ab01e21b84d660c22a1.

**Comment by gpdeepblue** [comment]
> > ```
> > [server] WARN: Display doesn't have FLAG_SUPPORTS_PROTECTED_BUFFERS
> > ```
> 
> See discussion #1238.
Actually, I had this warning all along, and I didn't care because if you don't have it, you don't have it, right?
It is not offically supported anyway.
I'll try and solve this warning but with little hope.
