### ISSUE TITLE
choppy/pixely video over USB&TCPIP adb connection.

### ISSUE THREAD

**Issue by Twml1500** [Genymobile/scrcpy#201]
I have a new oneplus 6 and am getting very choppy and pixely video streaming of my phone screen.
using my windows 10 laptop with the phone via usb or tcpip. 

I had a nexus 6p, and both usb & tcpip went smoothly with no pixelation. 
using the same laptop also.

what is the issue here?

**Comment by rom1v** [comment]
Could you post a screenshot, please?

Possibly related: https://github.com/Genymobile/scrcpy/issues/40

**Comment by Twml1500** [comment]
here is how it looks when blurry
![blurry1](https://user-images.githubusercontent.com/25257706/42913105-53c45f4a-8ac9-11e8-8f7c-e9ee4f85aa51.png)

and here is how it looks other times as it should
![clear](https://user-images.githubusercontent.com/25257706/42913121-6d2c5bae-8ac9-11e8-904e-57d50eadef66.png)

and will randomly go blurry even when sitting on a stationary screen.

**Comment by rom1v** [comment]
What command did you execute exactly? Did you pass any `-b` argument?

**Comment by Twml1500** [comment]
ADB tcpip 5555
ADB connect 192.168.2.x:5555
Scrcpy.exe

Then the display window opens on PC of phone screen.

**Comment by rom1v** [comment]
It seems the codec on your device does not understand the bitrate correctly.

What if you use crazy bitrate values:
    scrcpy -b 32m
    scrcpy -b 100m
    scrcpy -b 1000m
?

**Comment by Twml1500** [comment]
the video quality is smooth at 100m but is very slow motion even over my 1gbps link.

will try lower bitrates til i find a happy medium of speed and quality see if i can get it to work.

**Comment by Twml1500** [comment]
`scrcpy.exe -b 20m` seems to be a very happy medium for my device. 
not pixely and smoothly playing video. no delay

**Comment by rom1v** [comment]
It would be interesting to know the _real_ bitrate of the video, because obviously, it does not match the requested value.

Unfortunately, I don't know how to do that on Windows. On Linux, you would start the server manually and use `netcat`+`pv` to measure the bitrate received on the socket.

**Comment by Twml1500** [comment]
@rom1v using wifi. i rarely use my usb actually. just noticed originally it was pixely over both wifi/usb.

for now marking this as fixed, 
and when i get more time i will test usb and see if i can find bitrate actually used. 

thank you for the help.
