### ISSUE TITLE
scrcpy doesnt work for me on wi fi, and sndcpy doesnt work at all

### ISSUE THREAD

**Issue by SyncMaster93** [Genymobile/scrcpy#2010]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
There is absolutely no information in your issue.

What commands did you execute? What was the output?

I'm closing. Feel free to reopen it once you provided more details.
