### ISSUE TITLE
scrcpy Not Opening A View Window

### ISSUE THREAD

**Issue by GetYaArmour** [Genymobile/scrcpy#2012]
So i installed scrcpy and it all worked fine, it 'appears' to have connected to my phone as my phone asled if it wanted USB debug to take place, however running scrcpy.exe opens what appears to be a cmd promt window which promptly closes and does nothing?
No display window is opened or anything?
Can anyone help?

**Comment by rom1v** [comment]
Open `scrcpy-console.bat`, the console will stay open on error. And post the error.

**Comment by GetYaArmour** [comment]
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: no devices/emulators found
ERROR: "adb push" returned with value 1
Press any key to continue . . .

**Comment by GetYaArmour** [comment]
> Open `scrcpy-console.bat`, the console will stay open on error. And post the error.

INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: no devices/emulators found
ERROR: "adb push" returned with value 1
Press any key to continue . . .

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#adb-issues

**Comment by GetYaArmour** [comment]
> https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#adb-issues

tried, it told me the drivers are already upto date

**Comment by rom1v** [comment]
Your device must be detected by `adb devices` for scrcpy to work.

Check stackoverflow for your specific device/platform.

**Comment by rom1v** [comment]
Did you enable USB debugging?

**Comment by GetYaArmour** [comment]
> Did you enable USB debugging on your device?

Yep

**Comment by GetYaArmour** [comment]
Got, it all I had to do was change the USB connection type, I didn't realise I had it on charge only
thanks for the help anyway
