### ISSUE TITLE
Navigation buttons not visible

### ISSUE THREAD

**Issue by vaibhavwa1982** [Genymobile/scrcpy#2015]
Hello All,

Good Evening,

actually, I am using scrcpy on imac  (OS-10.12 (Sierra) after connecting the android device to the mirror image device back and home button is visible.

Requesting you to provide your suggestion.

Thanks,
Vaibhav

**Comment by rom1v** [comment]
I'm not sure to understand the problem.

Could you post a screenshot?

**Comment by vaibhavwa1982** [comment]
actually, i am using scrcpy application on mac to mirror the android devices. I am able to mirror the android device with help of scrcpy application but on the mirror image back or home button not visible.
