### ISSUE TITLE
"Enter" in numeric keypad make a "space"

### ISSUE THREAD

**Issue by lollita** [Genymobile/scrcpy#2018]
When I press "Enter" in numeric keypad I get a "space" instead of "carriage return".
Do it is possible to use then "Enter" likewise?

**Comment by rom1v** [comment]
In all applications?

What if you execute:

```
adb shell input keyevent KEYCODE_NUMPAD_ENTER
```

**Comment by lollita** [comment]
> 
> 
> In all applications?
In all.
> 
> What if you execute:
> 
> ```
> adb shell input keyevent KEYCODE_NUMPAD_ENTER
> ```
The same.

**Comment by rom1v** [comment]
> The same.

Then it's a problem in your system :/
