### ISSUE TITLE
delay issue

### ISSUE THREAD

**Issue by yourivts** [Genymobile/scrcpy#2020]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows 10]
 - scrcpy version: [e.g. 1.17]
 - device model: oneplus 8 pro
 - Android version: [11]

i've been wanting to stream a game on my phone, and this program seems like a great solution. however, i wanted to test out the program, and it works great. except for when im in game, whenever i play a game, i get random lag spikes where the video slows down for like 1-2 seconds, and after it's done slowing down, there is a delay. i was wondering if this would be a problem with the program, my computer or my phone just not being fast enough. i am currently using these parameters: -b 18m --render-driver=opengl
this fixed  most of my issues, because before i was using these it would be very pixelated. however the delay still occurs.

```
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
C:\adbnew\scrcpy-server: 1 file pushed, 0 skipped. 50.5 MB/s (34930 bytes in 0.001s)
[server] INFO: Device: OnePlus IN2023 (Android 11)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6.0 NVIDIA 445.75
INFO: Trilinear filtering enabled
INFO: Initial texture: 3168x1440
```

**Comment by rom1v** [comment]
See #798.

> INFO: Initial texture: 3168x1440

Does it still occur with a lower definition (`scrcpy -m1024` fo example)?

**Comment by yourivts** [comment]
this does fix it, however it greatly decreases the quality. 

i've tried -m2048 now, and this seems to fix the quality as well as the delay, thank you for helping
