### ISSUE TITLE
Can't mirror my android tab to laptop via scrcpy-win64-v1.15.1

### ISSUE THREAD

**Issue by fixthisissue1** [Genymobile/scrcpy#2021]
![Capture](https://user-images.githubusercontent.com/77165327/104041750-2cbd6300-51e2-11eb-8f81-4d683c5dcda1.PNG)

My android Tab is a bit old
version 4.2.2

is it a version issue or something else?
Thank you

**Comment by rom1v** [comment]
Scrcpy requires Android 5.

**Comment by fixthisissue1** [comment]
> Scrcpy requires Android 5.

ok Thank you !
Right now I am using another device 
I am getting this error
![Capture](https://user-images.githubusercontent.com/77165327/104047758-d7398400-51ea-11eb-9ceb-66974ba6fb46.PNG)


I am trying to find about how to fix it through this link:
https://github.com/Genymobile/scrcpy/issues/185

I wish someone can easily tell me what to do

Thank you

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#adb-issues

Also, did you enable USB debugging?

Btw, why v1.15.1 instead of v1.17?

**Comment by fixthisissue1** [comment]
> https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#adb-issues
> 
> Also, did you enable USB debugging?

Yes, yesterday it was working.
Today I tried to mirror my tab and later I tried once again my samsung J7 core and it's not working.
I am even downloading abd drivers after viewing youtube videos
still nothing

any idea?

**Comment by fixthisissue1** [comment]
alright it took me a lot but eventually done!
I was able to fix it!

Thank you so much

**Comment by 19suhail66** [comment]
> alright it took me a lot but eventually done! I was able to fix it!
> 
> Thank you so much

Hi, how you managed to fix scrcpy screen mirroring not working with android 4.2.2 phones and tablets. Same problem with vysor.
