### ISSUE TITLE
scrcpy wont start after Samsung A41 Latest Update

### ISSUE THREAD

**Issue by ScientiaAnalysis** [Genymobile/scrcpy#2025]
After the following update on my samsung A41, the scrcpy 1.17 on windows wont start at all.

Baseband version
A415FXXU1BTK5

Kernel v.
4.14.141-20194519
3 Wed Nov 25

Build Number number
QP1A.190711.020.A415FXXU1BTK5

Knox Version
Knox 3.5
API Level 31
TIMA 4.1.0
HDM 1.0 - 1F

Service Provider SW ver.
SAOMC_SM-A415F_OXM_DBT_QQ_0013
R58N917HM5E
DBT/DBT,DBT/EUX/DBT

Security Soft. version
ASKS v3.1 Rel. 20200806
ADP v3.0 Rel. 20191001
SMR Nov-2020 Rel. 1

Android security patch level
1 November 2020

**Comment by rom1v** [comment]
> After the following update on my samsung A41, the scrcpy 1.17 on windows wont start at all.

Any error message? (start `scrcpy-console.bat`)

**Comment by ScientiaAnalysis** [comment]
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>                                                                C:\Program Files (x86)\scrcpy-win64-v1.17\scrcpy-server: 1 file pushed, 0 skipped. 54.0 MB/s (34930 bytes in 0.001s)    [server] INFO: Device: samsung SM-A415F (Android 10)                                                                    [server] ERROR: Exception on thread Thread[main,5,main]                                                                 java.lang.IllegalStateException                                                                                                 at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)                                                   at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2789)                                                   at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:113)                                                   at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:94)                                      at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)                                              at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)                                                                  at com.genymobile.scrcpy.Server.main(Server.java:252)                                                                   at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)                                                  at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:342)                                               INFO: Renderer: direct3d                                                                                                INFO: Initial texture: 1080x2400                                                                                        WARN: Device disconnected                                                                                               Press any key to continue . . .

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

**Comment by ScientiaAnalysis** [comment]
Thank you very much!
