### ISSUE TITLE
Unable to inject Korean Characters

### ISSUE THREAD

**Issue by BraINstinct0** [Genymobile/scrcpy#2028]
**Environment**
 - OS: [Linux Mint 20.1 Cinnamon]
 - scrcpy version: [1.17. Snap install from Snapcraft]
 - installation method: [Snap]
 - device model:Samsung Galaxy Note 20 Ultra
 - Android version: [10]

**Describe the bug**
When doing an input of Korean characters, (here 'ㅁㄴㅇㄹ') it is not handed over properly.
The connection was done wirelessly, though it doesn't seem to matter much.
IIRC most of this kind of problem arise from error in multibyte-character handling, so that might be a possible place to check.

```
[server] WARN: Could not inject char u+3141
[server] WARN: Could not inject char u+3134
[server] WARN: Could not inject char u+3147
[server] WARN: Could not inject char u+3139
```

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#special-characters-do-not-work

**Comment by BraINstinct0** [comment]
Self-closing as partially answered & partially duplicate. See link above for further progress

**Comment by saleo** [comment]
close and reopen scrcpy  worked for me on this case
