### ISSUE TITLE
Question: Debug scrcpy with Clion

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [Genymobile/scrcpy#2032]
_Originally posted by @Romantic-LiXuefeng in https://github.com/Genymobile/scrcpy/issues/2008#issuecomment-757670617_
@sman2013 Thank you for sharing. As you said, I added the` CMakeList.txt ` ,compile and build works well. 
![image](https://user-images.githubusercontent.com/9837705/104155108-6def8600-5421-11eb-99d2-a2ee06fb9b40.png)

And I configured the Environment variables `ADB` and `SCRCPY_SERVER_PATH`   .
`SCRCPY_SERVER_PATH` is a location of  the prebuild server , downloaded as [BUILD.md](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#prebuilt-server) 

When running `scrcpy`.  the logs like this, there is no mirror on my MacBook. @rom1v  I need some help. I'm not familiar with the underly `adb` socket how to work .Thanks!
```
/Users/lixuefeng/Google_Sample/scrcpy/app/src/cmake-build-debug/scrcpy
2021-01-11 15:25:58.090 scrcpy[14488:570081] INFO: scrcpy V1.16 <https://github.com/Genymobile/scrcpy>
2021-01-11 15:25:58.091 scrcpy[14488:570081] DEBUG: Using SCRCPY_SERVER_PATH: /Users/lixuefeng/Google_Sample/scrcpy/server/prebuild/scrcpy-server-v1.17
/Users/lixuefeng/Google_Sample/scrcpy/server/prebuild/scrcpy-server-v1.17: 1 file pushed. 9.0 MB/s (34930 bytes in 0.004s)
2021-01-11 15:25:58.119 scrcpy[14488:570081] INFO: Server debugger waiting for a client on device port 5005...
2021-01-11 15:25:58.266 scrcpy[14488:570081] DEBUG: Screensaver enabled
```

**Comment by rom1v** [comment]
> INFO: scrcpy V1.16 <https://github.com/Genymobile/scrcpy>

> Using SCRCPY_SERVER_PATH: /Users/lixuefeng/Google_Sample/scrcpy/server/prebuild/scrcpy-server-v1.17

You must use the same version for the client and the server. In theory, the server should throw an exception because the version is not the same (check `adb logcat`).

**Comment by Romantic-LiXuefeng** [comment]
@rom1v I used the least master branch code to compile the `scrcpy client` with CMakeLists.txt(provided by @pullrequest 2008) in CLion. and used the least prebuild server v1.17.

**Comment by Romantic-LiXuefeng** [comment]
The scrcpy server logs in Android Studio:

adb logcat -v threadtime | grep 'scrcpy'
```
01-14 16:24:45.219 23076 23076 I appproc :  app_process  -XjdwpProvider:internal  -XjdwpOptions:transport=dt_socket,suspend=y,server=y,address=5005  /  com.genymobile.scrcpy.Server  V1.17  debug  0  8000000  0  -1  false  -  true  true  0  false  false  -  -  ,ppid=23074
```

The scrcpy client logs in CLion:

```
2021-01-14 16:25:04.577 scrcpy[32454:1331020] INFO: scrcpy V1.17 <https://github.com/Genymobile/scrcpy>
2021-01-14 16:25:04.579 scrcpy[32454:1331020] DEBUG: Using SCRCPY_SERVER_PATH: /Users/lixuefeng/Google_Sample/scrcpy/server/prebuild/scrcpy-server-v1.17
2021-01-14 16:25:04.619 scrcpy[32454:1331020] INFO: Server debugger waiting for a client on device port 5005...
/Users/lixuefeng/Google_Sample/scrcpy/server/prebuild/scrcpy-server-v1.17: 1 file pushed. 2.2 MB/s (34930 bytes in 0.015s)
2021-01-14 16:25:04.764 scrcpy[32454:1331020] DEBUG: Screensaver enabled
2021-01-14 16:25:05.463 scrcpy[32454:1331029] DEBUG: Server terminated
```

**Comment by rom1v** [comment]
What do you want to debug? The client or the server?

You passed an option to debug the server:

> > -XjdwpOptions:transport=dt_socket,suspend=y,server=y,address=5005

(https://github.com/Genymobile/scrcpy/blob/master/DEVELOP.md#debug-the-server)

But you used the prebuilt server (and you probably want to debug the server with CLion).

**Comment by Romantic-LiXuefeng** [comment]
I want to debug the client (written with c)  with CLion.

**Comment by rom1v** [comment]
At least, remove this line from the CMakefile.txt:
```cmake
OPTION(SERVER_DEBUGGER "server debugger" ON)
```

**Comment by Romantic-LiXuefeng** [comment]
Thanks for you help.  @rom1v  It works!

**Comment by Romantic-LiXuefeng** [comment]
@rom1v When I run the scrcpy client compiled by myself. It not behave like the scrcpy installed by `homebrew`.  On Mac book when move on touch pad a little, this is mush sensitive.

**Comment by rom1v** [comment]
Maybe it does not use the same SDL library? I don't know, there is nothing related to move speed in scrcpy.
