### ISSUE TITLE
I have this issue

### ISSUE THREAD

**Issue by Stiven-glitch** [Genymobile/scrcpy#2036]
![Screenshot_1](https://user-images.githubusercontent.com/72848498/104623941-eb550980-5660-11eb-87f3-62f51108a928.png)

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#adb-issues

Note:
 - please use the issue template
 - please read the FAQ before opening an issue
 - please do not post screenshots of a terminal, but the text content directly instead

**Comment by Stiven-glitch** [comment]
Yes, i have the USB debugging enabled, i ussed the latest version and i have the same error

**Comment by Stiven-glitch** [comment]
![Uploading Screenshot_2.png…]()

**Comment by Stiven-glitch** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/72848498/104626499-007f6780-5664-11eb-909b-b272cf5aa411.png)

**Comment by FatihBlackcloud** [comment]
check the drivers on device manager section. Maybe you need to install adb driver for your phone.  "dl.adbdriver.com/upload/adbdriver.zip" and you make sure have RSA key for your pc !!!

also, you can try this method, firstly disable usb debugging, and plug phone to pc and choose file transfer and after that open usb debugging and you can try to run...
