### ISSUE TITLE
Pixel 4 has lots of lag and very low FPS

### ISSUE THREAD

**Issue by wellplayedstudios** [Genymobile/scrcpy#2038]
- [x ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: 1.17, 1.14
 - installation method: Windows release
 - device model: Pixel 4
 - Android version: 11

**Describe the bug**
Like it says in the title. It is very slow and laggy.

I have tried it with the -m1024 option as well.

```
scrcpy.exe -w
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
C:\Users\Brainversation\Downloads\scrcpy-win64-v1.17\scrcpy-server: 1 file pushed, 0 skipped. 67.2 MB/s (34930 bytes in 0.000s)
[server] INFO: Device: Google Pixel 4 (Android 11)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2280

scrcpy.exe --render-driver opengles2 -w
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
C:\Users\Brainversation\Downloads\scrcpy-win64-v1.17\scrcp... file pushed, 0 skipped. 58.9 MB/s (34930 bytes in 0.001s)
[server] INFO: Device: Google Pixel 4 (Android 11)
INFO: Renderer: opengles2
INFO: OpenGL version: OpenGL ES 3.2 NVIDIA 461.09
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x2280
```

**Comment by rom1v** [comment]
If you record, is the recorded file laggy too?

```
scrcpy --record file.mkv
```

**Comment by wellplayedstudios** [comment]
yes

**Comment by rom1v** [comment]
OK.

1. could you post the file?
2. could you press <kbd>Alt</kbd>+<kbd>i</kbd> in the scrcpy window, and post the FPS printed in the console?
3. test `adb shell screenrecord /sdcard/file.mp4` + `adb pull /sdcard/file.mp4`: it the file laggy too?

**Comment by wellplayedstudios** [comment]
1. I rather not, sorry.
2. The average is INFO: 10 fps
3. Can not test well since my phone's screen is broken.

**Comment by rom1v** [comment]
> my phone's screen is broken.

Oh, that's the reason why it's slow: #1285 #1353 #1456 #1942

**Comment by wellplayedstudios** [comment]
@rom1v Thank you so much for your help troubleshooting this issue.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/issues/1285#issuecomment-917513993
