### ISSUE TITLE
ERROR: "adb reverse" returned with value 1

### ISSUE THREAD

**Issue by FlooferLand** [Genymobile/scrcpy#2041]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Linux Mint 20.1
 - scrcpy version: 1.17
 - installation method: manual build
 - device model: SM-G357FZ
 - Android version: 4.4.4

I just recently tried installing scrcpy to control and view my phone's screen (and to mess around in Python with adb more easily) and i'm getting the following errors running `scrcpy` after my device is up and mounted with adb:
`INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 6.3 MB/s (34930 bytes in 0.005s)
error: closed
ERROR: "adb reverse" returned with value 1
WARN: 'adb reverse' failed, fallback to 'adb forward'
`
It might be because it doesn't support Android 4 or anything lower than Android 5 but i can't find any good alternative to scrcpy so could there please be any way of fixing this..?

**Comment by rom1v** [comment]
> It might be because it doesn't support Android 4 or anything lower than Android 5

Exactly.

You can bypass the adb reverse error with `--force-adb-forward`, but mirroring will not work anyway.

**Comment by Artur202030** [comment]
> alternative to scrcpy
CXTouch

**Comment by FlooferLand** [comment]
Closing the issue due to inactivity, as well as the fact I have a much newer phone now.
