### ISSUE TITLE
new in CMD and wants to learn how to operate the SCRCPY

### ISSUE THREAD

**Issue by RyzenPRO** [Genymobile/scrcpy#2046]
![scrcypy issue](https://user-images.githubusercontent.com/77603889/104877414-b9abad80-5994-11eb-8714-c1078a35b190.png)
![scrcypy issue](https://user-images.githubusercontent.com/77603889/104877443-c9c38d00-5994-11eb-86c8-af55f4835f6b.png)

 - [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

i want to know how could i change the resolution/definition and the bitrate and also the encoder. i need to learn it step by step cause i read the FAQ and its kinda confusing me how to do it plsss help.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows

At what step is it confusing for you?

**Comment by RyzenPRO** [comment]
i cant screen mirror my android phone to my windows pc. And its shows this error "ERROR: Exception on thread Thread[main,5,main]". By reading the FAQ many users had experience this and they found the solution tochange the definition of the SCRCPY and the image that i posted it shows that the resolution is 1080x2280 which is reasonable thats why it wont work due to a massive resolution i just want to set that on 720p. according for some users the best way is to reduce the resolution and i want to learn that they were giving encodes in FAQ but i dont know to do them in CMD thats why it confuses me. AND THANK YOU FOR FAST RESPONE <3

**Comment by RyzenPRO** [comment]
> 
> 
> https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows
> 
> At what step is it confusing for you?

I cant screen mirror my android phone to my windows pc. And its shows this error "ERROR: Exception on thread Thread[main,5,main]". By reading the FAQ many users had experience this and they found the solution. is to change the definition of the SCRCPY and the image that i posted it shows that the resolution is 1080x2280 which is reasonable thats why it wont work due to a massive resolution i just want to set that on 720p. according for some users the best way is to reduce the resolution/definition and i want to learn that they were giving encodes in FAQ but i dont know how to use them in CMD thats why it confuses me. AND THANK YOU FOR FAST RESPONE <3

**Comment by RyzenPRO** [comment]
@rom1v I need a response plsss

**Comment by rom1v** [comment]
Follow https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows
At step 4 replace `scrcpy --record file.mkv` by `scrcpy -m800`.

**Comment by RyzenPRO** [comment]
@rom1v THANK YOU SO MUCH BUD.... YOURE A LIFESAVER. I OWE YOU

**Comment by RyzenPRO** [comment]
THANK YOU REALLY THANK YOU
