### ISSUE TITLE
How can i close the window when I start it with scrcpy --window-borderless? There is no close button on the window.

### ISSUE THREAD

**Issue by liyinong6666** [Genymobile/scrcpy#2049]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md). 
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: the latest version
 - installation method: Windows release...
 - device model:
 - Android version: 10

**Describe the bug**
Could you please call me how can i close the window when I start it with scrcpy --window-borderless?
Can I add a button to close the window in this scenario? If so, which code needs to be modified?
Thank you！

**Comment by liyinong6666** [comment]
Now，I can close the window only by pressing Ctrl+C to terminate the running of the scrcpy program in cmd.

**Comment by rom1v** [comment]
Alt+F4 ?

**Comment by liyinong6666** [comment]
It did. Thank you. But is there any other way if i want to do this with code? add a button and invoke SDL_DestroyWindow(win)？

**Comment by rom1v** [comment]
Probably something like:

```c
SDL_Event event;
event.type = SDL_QUIT;
SDL_PushEvent(&event);
```
