### ISSUE TITLE
forward-all-clicks doesn't forward all clicks

### ISSUE THREAD

**Issue by R3troCub3** [Genymobile/scrcpy#2050]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 7
 - scrcpy version: 1.17
 - installation method: Windows release
 - device model: Samsung Galaxy J7 Star
 - Android version: 9

**Describe the bug**
forward-all-clicks should send right clicks as a normal click, correct? so I attempted to turn it on, but right-click still functions as expected from before, as BACK.

**On errors, please provide the output of the console (and `adb logcat` if relevant).**

```
Please paste terminal output in a code block.
```
Does not seem to have output, I checked (if there's a specific thing I need to do to enable logging, please tell me, since I'm not sure where it is.)
**Please do not post screenshots of your terminal, just post the content as text instead.**

**Comment by rom1v** [comment]
> forward-all-clicks should send right clicks as a normal click, correct? so I attempted to turn it on, but right-click still functions as expected from before, as BACK.

For me if I execute `scrcpy --forward-all-clicks` it changes the behavior of right-click.

How did you turn it on?

**Comment by R3troCub3** [comment]
> How did you turn it on?
from the console, unless I'm completely dumb and that's not where I should be using it from.

**Comment by rom1v** [comment]
If it continue to send BACK, then the option is not enabled.

What is the result of `scrcpy --version`?
What is the output in your console when you pass `--forward-all-clicks`?
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows

**Comment by R3troCub3** [comment]
...ok, yeah, that was dumb. for some reason I thought I was supposed to put in the commands in the console that opens from scrcpy.exe, not the actual commandline. gonna close this, I guess.
