### ISSUE TITLE
When I open scrcpy the window closes before I get to write any command

### ISSUE THREAD

**Issue by Elasder123** [Genymobile/scrcpy#2054]
So when I open up scrcpy the window closes right away and I don't get to start scrcpy but on my other pc it works fine without closing itself and it runs smoothly. any help is appreciated

**Comment by rom1v** [comment]
> So when I open up scrcpy the window closes right away and I don't get to start scrcpy

Run `scrcpy-console.bat` so that the console does not close immediately if there is an error. You'll have time to see the error.

**Comment by Elasder123** [comment]
> 
> 
> > So when I open up scrcpy the window closes right away and I don't get to start scrcpy
> 
> Run `scrcpy-console.bat` so that the console does not close immediately if there is an error. You'll have time to see the error.

this is what I got INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: no devices/emulators found
ERROR: "adb push" returned with value 1
Press any key to continue . . .

**Comment by rom1v** [comment]
The device is not detected by adb.
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#adb-issues

**Comment by Elasder123** [comment]
> 
> 
> The device is not detected by adb.
> https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#adb-issues

just saw that my pc doesn't recognize my device so I am trying to troubleshoot it (I have a Samsung a9 2018 )

**Comment by Elasder123** [comment]
Just downloaded Samsung Kies and now my phone is recognized by my pc thank god and everything works fine
