### ISSUE TITLE
Window is not the size specified when --max-size and --window-borderless are used

### ISSUE THREAD

**Issue by ferdinandwinters** [Genymobile/scrcpy#2055]
Hello!

I use scrcpy combined with DisplayFusion to mount my phone as a virtual monitor on my PC whenever I am using it, however there is a bug that I believe is on your end when I use the --max-size and --window-borderless to achieve the effect.

![image](https://user-images.githubusercontent.com/25633642/105508817-8eb8b500-5d18-11eb-81d8-d67567c7f2b3.png)

When specifying the height as 1080 (device has an 18:9 1080 x 2160 display) using 'scrcpy -S --max-size 1080 --window-borderless' scrcpy reports a texture of 544x1080 but actually displays a texture of 540x1074. This happens regardless of DisplayFusion running or not.

**Comment by rom1v** [comment]
`--max-size` limits the maximum video size encoded on the device side (544×1080 in your case).
The video is always uploaded to a texture having the same size.

This size is not necessarily the size it is displayed (typically, if your screen is bigger, or if you resize your window, it's rendered at a lower size).

You can "force" the width/height using `--window-height 1080` for example.

If you don't request a specific width or height, it tries to "best fit". You could log the values it computes and check why it decides to resize to 540×1074:

https://github.com/Genymobile/scrcpy/blob/ce43fad645d4eb30f322dbeb50d5197601564931/app/src/screen.c#L140

**Comment by ferdinandwinters** [comment]
Thank you for the help!
