### ISSUE TITLE
USB Tethering Crashes the Display Window

### ISSUE THREAD

**Issue by hashnimmo** [Genymobile/scrcpy#2057]
**Environment**
OS: Windows 10 20H2 19042.746
scrcpy version: 1.17
Installation method: Windows release (`scrcpy-win64-v1.17.zip`)
Device model: Lenovo A2010-a
Android version: Android Lollipop 5.1

**Describe the bug**
scrcpy display window crashes as soon as I enable USB tethering through Android Settings.

```
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
C:\Program Files\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 44.7 MB/s (34930 bytes in 0.001s)
[server] INFO: Device: LENOVO Lenovo A2010-a (Android 5.1)
INFO: Renderer: direct3d
INFO: Initial texture: 480x848
```

**Comment by rom1v** [comment]
That disconnects `adb`. If you run for example `adb shell` in a separate terminal, enabling USB tethering should also terminate it.

**Comment by hashnimmo** [comment]
Confirmed, scrcpy display window will work again if I restart scrcpy even with USB tethering.
