### ISSUE TITLE
No Phone Display on Closing Display Window

### ISSUE THREAD

**Issue by hashnimmo** [Genymobile/scrcpy#2058]
**Environment**
OS: Windows 10 20H2 19042.746
scrcpy version: 1.17
Installation method: Windows release (`scrcpy-win64-v1.17.zip`)
Device model: Lenovo A2010-a
Android version: Android Lollipop 5.1

**Describe the bug**
I can't wake up the screen of my phone anymore if I close scrcpy display window. However, this won't happen if I close the scrcpy console window instead of the display window. I had to remove the battery and restart the phone to turn on my phone display.

```
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
C:\Program Files\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 44.7 MB/s (34930 bytes in 0.001s)
[server] INFO: Device: LENOVO Lenovo A2010-a (Android 5.1)
INFO: Renderer: direct3d
INFO: Initial texture: 480x848
```

**Comment by rom1v** [comment]
Did you enable `--turn-screen-off` (or <kbd>Alt</kbd>+<kbd>o</kbd>)?

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/issues/1653#issuecomment-672714905

**Comment by hashnimmo** [comment]
Closing this issue as I don't think the scrcpy display window has anything to do with this, but this issue is still happening randomly. I long-pressed the power button to see if that will wake up the phone screen, screen woke up, but the screen started flickering with vertical lines so I restarted the phone and the screen was back to normal.
