### ISSUE TITLE
Error: scrcpy: no bottle available!

### ISSUE THREAD

**Issue by BardsDirge** [Genymobile/scrcpy#2059]
i was trying to update from 1.16 with homebrew and it seems i got hung up at 
`==> Installing scrcpy dependency: rust`
i waited over an hour. my macbook was pushing 100ªc the whole time.
i tried
`brew install scrcpy`
it told me i had 1.16 and, as usual, it told me to change the command to upgrade. i did and it stoped at rust again.
now for the first time ever, homebrew is telling me 
`Error: scrcpy: no bottle available! `

i'm disabled and use scrcpy to access my phone. i'm really screwed right now without it. please advise.

**Environment**
 - OS:  macOS 10.13.6
 - scrcpy version: 1.16_2
 - installation method: brew
 - device model: LG Tribute Dynasty SP200
 - Android version: 7.1.2

**Comment by BardsDirge** [comment]
`==> Installing ffmpeg dependency: rust
==> ./configure --prefix=/usr/local/Cellar/rust/1.49.0_1 --release-channel=stable
==> make`

**Comment by rom1v** [comment]
Hi.

You should report to homebrew, this is totally independant of scrcpy.

**Comment by BardsDirge** [comment]
i'm not the only user that needs to know 1.16_2 is the end of the line.

would it really disrupt the ecosystem if you allowed discussing homebrew _**as it pertains to scrcpy?**_ the entirety of your mac users instructions are "use homebrew", even for compiling it yourself.

macs that can't update their OS beyond 10.13 need to be warned that homebrew doesn't know or care if they try to update scrcpy it will install incompatible ffmpeg dependencies. _**people need to know this**_.

i spent all day sorting out what went wrong and then manually replacing all my old scrcpy components in /usr/local/ from a backup.

**Comment by rom1v** [comment]
> would it really disrupt the ecosystem if you allowed discussing homebrew

You could discuss it, but this is not the better place to get help, since this is a homebrew problem, you have more chances to get answers there I guess. I have no idea what is the cause of your issue.

Btw, I'm surprised that ffmpeg depends on Rust by default (maybe for rav1e).

**Comment by BardsDirge** [comment]
i've spent a long time herding ducklings on message boards. i know you  need to be firm where you draw lines. this really isn't a thing homebrew cares about though. you're either running "big sur" or you're off the radar.

that's why i hope somehow people will be made aware that scrcpy's instructions only apply to OS 10.14+. 

>Btw, I'm surprised that ffmpeg depends on Rust by default (maybe for rav1e).

rav1e and dav1d where among the libraries i needed to roll back when scrcpy 1.16 was asking for them. but they successfully upgraded, while rust's upgrade was what ran n ran til i realized my fans were reaching escape velocity.

**Comment by harens** [comment]
Hi @BardsDirge 👋. Following from #2256, I though I'd let you know that we at MacPorts provide pre-built scrcpy binaries for 10.12+: 

```
sudo port install scrcpy
```

You can install MacPorts from [here](https://www.macports.org/install.php). This should work perfectly out the box with no ffmpeg issue in sight (n.b. we provide ffmpeg binaries all the way back to 10.5 ppc from eleven years ago!) 

> The entirety of your mac users instructions are "use homebrew", even for compiling it yourself.

@rom1v if it's ok with you, I'll send a PR to update the macOS instructions to include MacPorts. This should hopefully answer these sorts of issues.

If there are any questions about this, please ask and I'd be more than happy to answer them :)

**Comment by rom1v** [comment]
> @rom1v if it's ok with you, I'll send a PR to update the macOS instructions to include MacPorts.

:+1:

(Please keep the instructions as short as possible)

**Comment by Coool** [comment]
[scrcpy](https://github.com/Coool/scrcpy-macOS-Binaries) for macOS
