### ISSUE TITLE
when I build and run the client in Windows system， where is the log output?

### ISSUE THREAD

**Issue by liyinong6666** [Genymobile/scrcpy#2060]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 -  - scrcpy version: the latest
 - installation method: 
 - device model:
 - Android version: 

Could u tell me when I build and run the client in Windows system， where is the log console？or where is the log files？Thank u

**Comment by rom1v** [comment]
How did you build? How did you run?

**Comment by liyinong6666** [comment]
I did what in the BUILD.md with MYSYS2:
meson z --buildtype release --strip -Db_lto=true -Dprebuilt_server=server/scrcpy-server
 ./run z

**Comment by liyinong6666** [comment]
I did what in the BUILD.md with MYSYS2:
meson z --buildtype release --strip -Db_lto=true -Dprebuilt_server=server/scrcpy-server
ninja -Cz
./run z

**Comment by liyinong6666** [comment]
I got it, Just the LOGD is not printed.Thank you for your answer

**Comment by rom1v** [comment]
> Just the LOGD is not printed.

Either don't pass `--buildtype release`, or run with `./run z -Vdebug`.
