### ISSUE TITLE
can not push scrcpy-server to device 

### ISSUE THREAD

**Issue by Peng-sky** [Genymobile/scrcpy#2061]
usb debugging is  openning
but when i run scrcpy.exe at cmd it will give below infos 

Failed to execute: [C:\Android\platform-tools], [push], ["D:\Android\scrcpy-win64\scrcpy-server.jar"], ["/data/local/tmp/scrcpy-server.jar"]
ERROR: Could not execute "adb push"

**Comment by Peng-sky** [comment]
when i execute [adb push a.txt /data/local/tmp/a.txt]  it will success, just like this problem 
https://www.gitmemory.com/issue/Genymobile/scrcpy/769/528893732

**Comment by rom1v** [comment]
> Failed to execute: [C:\Android\platform-tools], [push]

You set the ADB env variable to a wro'g valur, it must point to the adb executable, not a directory.

**Comment by Peng-sky** [comment]
> > Failed to execute: [C:\Android\platform-tools], [push]
> 
> You set the ADB env variable to a wro'g valur, it must point to the adb executable, not a directory.

But when I point to this path [D:\Android\platform-tools\adb.exe], the adb can not be recognized at cmd, I run it at windows
Could you please help to upload the adb env variable configs at your computer,Thanks

**Comment by rom1v** [comment]
If you use the scrcpy release, don't set the ADB envariable at all, it will use the one from scrcpu folder.

> D:\Android\platform-tools\adb.exe

What is the result of:

```
D:\Android\platform-tools\adb.exe devices
```

**Comment by Peng-sky** [comment]
> If you use the scrcpy release, don't set the ADB envariable at all, it will use the one from scrcpu folder.
> 
> > D:\Android\platform-tools\adb.exe
> 
> What is the result of:
> 
> ```
> D:\Android\platform-tools\adb.exe devices
> ```

It can recognize my device and adb version is below 
```
C:\Users\xxx>adb version
Android Debug Bridge version 1.0.41
Version 30.0.5-6877874
Installed as D:\Android\platform-tools\adb.exe
```

**Comment by Peng-sky** [comment]
> > If you use the scrcpy release, don't set the ADB envariable at all, it will use the one from scrcpu folder.
> > > D:\Android\platform-tools\adb.exe
> > 
> > 
> > What is the result of:
> > ```
> > D:\Android\platform-tools\adb.exe devices
> > ```
> 
> It can recognize my device and adb version is below
> 
> ```
> C:\Users\xxx>adb version
> Android Debug Bridge version 1.0.41
> Version 30.0.5-6877874
> Installed as D:\Android\platform-tools\adb.exe
> ```

I also tried `adb root` first then `adb push` but it dosen't work too

**Comment by rom1v** [comment]
> But when I point to this path [D:\Android\platform-tools\adb.exe], the adb can not be recognized at cmd,

Set ADB to `D:\Android\platform-tools\adb.exe`, execute `scrcpy`, and post the exact error message.

**Comment by Peng-sky** [comment]
> > But when I point to this path [D:\Android\platform-tools\adb.exe], the adb can not be recognized at cmd,
> 
> Set ADB to `D:\Android\platform-tools\adb.exe`, execute `scrcpy`, and post the exact error message.

When I disable the windows env variable to use the adb at scrcpy, it works , thank you for your help
