### ISSUE TITLE
Would be pretty nice if we had better controls for the program, basic stuff like WASD,Arrow keys etc etc to control games.

### ISSUE THREAD

**Issue by Matt-The-Aviator** [Genymobile/scrcpy#2063]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by GalaxyLinus** [comment]
I agree

**Comment by GalaxyLinus** [comment]
for the time u can search for a python script fo this

**Comment by rom1v** [comment]
WASD and arrow keys should work, don't they?

**Comment by Matt-The-Aviator** [comment]
> 
> 
> WASD and arrow keys should work, don't they?

I'm not aware of such feature existing nor it ever working, can you please show me how they work?

**Comment by rom1v** [comment]
Hmmm… press an arrow key on your computer keyboard in the scrcpy window, it will inject the corresponding key events.

Some games may ignore them however (if they just expect you to press some widgets buttons in the UI). In that case, what you want is keymapping, which is not implemented in scrcpy (#712).

**Comment by Matt-The-Aviator** [comment]
> Hmmm… press an arrow key on your computer keyboard in the scrcpy window, it will inject the corresponding key events.
> 
> Some games may ignore them however (if they just expect you to press some widgets buttons in the UI). In that case, what you want is keymapping, which is not implemented in scrcpy (#712).

OK, I actually tried it out in some programs actually did something, However are there any plans to add keymapping without doing a complicated command?

**Comment by rom1v** [comment]
> However are there any plans to add keymapping without doing a complicated command?

Currently, no. It would be easier with another UI framework to do something more interactive.

**Comment by Matt-The-Aviator** [comment]
> > However are there any plans to add keymapping without doing a complicated command?
> 
> Currently, no. It would be easier with another UI framework to do something more interactive.

Ah, okay, hopefully it can be implemented in the future!

**Comment by HanzMcs** [comment]
help me , i play pes mobile in scrcpy , but movement (WASD and arrow) not work, give me solution please

**Comment by rom1v** [comment]
WASD injects WASD keys. If the game handle these keys, then it works, otherwise it does not.
