### ISSUE TITLE
Bug: can't rotate screen using CTRL+R anymore?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Genymobile/scrcpy#2072]
- [V ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ V] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 Windows OS.
 - scrcpy version: [e.g. 1.12.1]
1.17
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
Here:
https://github.com/Genymobile/scrcpy/releases/download/v1.17/scrcpy-win64-v1.17.zip
 - device model:
Pixel 4
 - Android version: [e.g. 10]
11

**Describe the bug**
In the past I could use CTRL+R to change orientation. Now for some reason it doesn't do it, no matter where I try (and changing orientation is possible if I rotate the device).

It's not a crash so I don't think bug report or logs will help.

Was it removed, perhaps?

**Comment by rom1v** [comment]
It's Alt+r by default.

https://github.com/Genymobile/scrcpy#shortcuts

**Comment by AndroidDeveloperLB** [comment]
@rom1v Oh sorry for that. 
Why isn't it CTRL though? Usually for commands, it's CTRL (CTRL+C, CTRL+V,...)...

**Comment by rom1v** [comment]
Because <kbd>Ctrl</kbd> is now forwarded to the device.

See highlights of [v1.15 release notes](https://github.com/Genymobile/scrcpy/releases/tag/v1.15).

**Comment by AndroidDeveloperLB** [comment]
@rom1v So it's a bit new? It wasn't as such before?
