### ISSUE TITLE
ERROR: Exception on thread Thread on Huawei devices

### ISSUE THREAD

**Issue by Ap0k4L1p5** [Genymobile/scrcpy#2076]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: v1.17
 - installation method: Windows release
 - device model: Huawei Y7p & Huawei Nova 5i
 - Android version: 9

**Describe the bug**
It work fine with my other devices but not for this Huawei devices, is it because the devices using HMS Core? I did try using the server fix from previous comment which the Meizu one but still same problem occurred. It appeared error as can be seen in the screenshot below.

![Screenshot_1](https://user-images.githubusercontent.com/45856014/106439330-86980c80-64b2-11eb-9a95-bfe2d2d54fc4.png)

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

**Comment by Ap0k4L1p5** [comment]
ok cool! Thanks.
