### ISSUE TITLE
stay-awake does not prevent the device from sleeping

### ISSUE THREAD

**Issue by ofury** [Genymobile/scrcpy#2078]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version:  1.17
 - installation method: chocolatey
 - device model: Xiaomi Mi 9 SE
 - Android version: 10

**Describe the bug**
I`m using Wireless connection.
Launching scrcpy with stay-awake does not prevent the device from sleeping.

```
λ scrcpy --turn-screen-off --stay-awake --always-on-top --bit-rate 1M --max-size 576 --serial 192.168.0.8:5555
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
C:\ProgramData\chocolatey\lib\scrcpy\too...ipped. 51.6 MB/s (34930 bytes in 0.001s) [server] INFO: Device: Xiaomi Mi 9 SE (Android 10)
INFO: Renderer: direct3d
INFO: Initial texture: 264x576
[server] INFO: Device screen turned off
```

**Comment by rom1v** [comment]
It only works when the device is plugged in, not over wifi: https://github.com/Genymobile/scrcpy#stay-awake

#1445

**Comment by ofury** [comment]
@rom1v, missed it. thanks.
Have a nice day.
