### ISSUE TITLE
Landscape prob

### ISSUE THREAD

**Issue by MULTidll** [Genymobile/scrcpy#2080]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model: Realme 1
 - Android version: 9
**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```
Please do not post screenshots of your terminal, just post the content as text instead.
I have a problem in REALME 1 that is if i screen mirror any game or using the phone in landscape mode it is looking like blue and red with a line and its looks like 3D

**Comment by rom1v** [comment]
Please screenshot.

**Comment by vintotal** [comment]
I also have a problem when rotating. For example, if I am in Firefox in portrait mode, but left-click to go back to the « desktop » of the phone, then the device rotates back to portrait and then crashes. Here is the log:
![imagen](https://user-images.githubusercontent.com/1743914/139533088-e34388e3-7ebf-41dd-a616-6098d5d66c43.png)
