### ISSUE TITLE
Scrcpy stay always on or retriggered by computer keys rather than phone's power switch?

### ISSUE THREAD

**Issue by ceyhun242** [Genymobile/scrcpy#2085]
I dont use lockscreen on my phone. Screen time out is 60 seconds. I open scrcpy with phone  which turns off phone screen as I set it so and then minimize it. but after a while (maybe after screen time out) when I click on it from taskbar, the screen is black and to turn it on I have to click on power button on the phone. Is it possible to either for scrcpy to never go black or even gone black be reactivated by pressing keys of computer keyboard rather than having to press power button of the phone? I hope it is possible.

Thank you

**Comment by rom1v** [comment]
To press power, Alt+p.
If the screen is already off, then right-click is sufficient.
https://github.com/Genymobile/scrcpy#shortcuts

To stay awake (only works if the device is plugged):
https://github.com/Genymobile/scrcpy#stay-awake

**Comment by ceyhun242** [comment]
Thank you it works great
