### ISSUE TITLE
Is there any way to easily drop down notification bar and dismiss notifications more easily than swiping with the mouse from one side to the other?

### ISSUE THREAD

**Issue by ceyhun242** [Genymobile/scrcpy#2087]
Now I swipe with mouse from top to down to open notification bar and swipe from left all the way to the right to dismiss a notification. Is there an easier way to do this with single clicks?

Thanks

**Comment by gaussandhisgun** [comment]
install some apps on the device side that will do it for you. like, i've seen "Notification Shade" that acts as a regular app icon, but on clicked opens your shade. and also some android ROMs open shade when its double-clicked.

**Comment by ceyhun242** [comment]
Thank you

**Comment by lsaranto** [comment]
There's shortcuts:

Expand notification panel   MOD+n

Collapse notification panel   MOD+Shift+n

**Comment by ceyhun242** [comment]
Oh thank you
