### ISSUE TITLE
Can't get debug data from console on crash

### ISSUE THREAD

**Issue by VictorieeMan** [Genymobile/scrcpy#2090]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows 10]
 - scrcpy version: [1.17]
 - installation method: [Windows release win64]
 - device model: Samsung Galaxy 10
 - Android version: [11]

**Describe the bug**
I start scrcpy.exe, it boots and shows the phone screen on the screen. After a random amount of time it will just close out of nowhere. It's not possible to gain any information from the console because it closes along with the screen mirroring.

Any ideas on how to collect debug data?

I haven't been able to run Scrcpy for more than a few minutes so far, the crash is guaranteed. I'm troubleshooting but since I'm not really getting anywhere after a couple of hours I figured I'll post here. Primarily to get some advice on collecting debug data to be able to give a more helpful bug report.

**Comment by rom1v** [comment]
On Windows, run `scrcpy-console.bat` so that the console does not close on error.
