### ISSUE TITLE
Change sound device Mobile to Computer

### ISSUE THREAD

**Issue by Irashad** [Genymobile/scrcpy#2091]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

 **I'm always frustrated when I want to play sounds. when i put on my headphone which is connected to computer. then open scrcpy the sounds coming from phone. This is the minor feature we can make**

**Comment by Irashad** [comment]
this feature doesn't exist

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy#audio-forwarding
