### ISSUE TITLE
[Help Needed] scrcpy-server on Android hangs

### ISSUE THREAD

**Issue by r-luo** [Genymobile/scrcpy#2094]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Ubuntu 20.04
 - scrcpy version: 1.17
 - installation method: linuxbrew
 - device model: Huawei Mate 20 Pro (connected to adb wirelessly via atx-agent)
 - Android version: 10

---
Hi,

I'm trying to stream my phone screen into Python. I found this script https://gist.github.com/Allong12/a752decf49e6c789c2425e35028137a5 from way back in 2019 and tried to modify it. However, the server would freeze whenever I try to receive anything with `sock.recv` in Python.

Things done in Bash (Not even sure if my arguments for scrcpy-server even make sense..):
```bash
wget https://github.com/Genymobile/scrcpy/releases/download/v1.17/scrcpy-server-v1.17
cp scrcpy-server-v1.17 scrcpy-server.jar
adb -s 192.168.50.229:5555 push scrcpy-server.jar /data/local/tmp/
adb -s 192.168.50.229:5555 shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 1.17 info 960 1073741824 60 -1 true - false true 0 false false - -
```
The above would hang at
```
[server] INFO: Device: HUAWEI LYA-L0C (Android 10)
```
And I had to open another shell process to run
```bash
adb -s 192.168.50.229:5555 forward tcp:8080 localabstract:scrcpy
```

Now in Python:
```python

import socket
import struct
import sys
import subprocess
import io

IP = '127.0.0.1'
PORT = 8080

print("Connecting")
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.connect((IP, PORT))


DUMMYBYTE = sock.recv(1)
if not len(DUMMYBYTE):
    print("Failed to connect!")
    exit()
else:
    print("Connected!")

```

It'll print `"Connected!"` as a dummy byte is received. However, any subsequent call to `sock.recv` would hang in python:
```python
deviceName = sock.recv(64)
print("Device Name:",deviceName.decode("utf-8"))
```
^ this hangs.

I'm wondering if anyone can help me understand what's going on / help me make it work... Thanks in advance!

**Comment by rom1v** [comment]
Now, you need to connect 2 sockets (1 for video, 1 for control in both directions): ec71a3f66ab48c2fdd1728753acc09edbd4db570

Refs https://github.com/Genymobile/scrcpy/issues/129#issuecomment-544865465

**Comment by r-luo** [comment]
@rom1v Thanks so much for your response! 

Unfortunately I'm pretty illiterate in networking so I'm not sure what I should do to make it work after reading the links you provided... Would you mind offering some possible changes I can make to the code above in order to receive screenshots from scrcpy-server started on the phone?

**Comment by Bujuhu** [comment]
Hi!

[This is probably what you are looking for](https://github.com/razumeiko/py-android-viewer/blob/83f6170a61b6bbc3f20beb57b95a05c282bad7f1/viewer.py#L62-L88), this should still work.

Or you could use use the class provided by [py-android-viewer](https://github.com/razumeiko/py-android-viewer/tree/83f6170a61b6bbc3f20beb57b95a05c282bad7f1) directly if you don't want program the networking bit yourself

**Comment by r-luo** [comment]
> Hi!
> 
> [This is probably what you are looking for](https://github.com/razumeiko/py-android-viewer/blob/83f6170a61b6bbc3f20beb57b95a05c282bad7f1/viewer.py#L62-L88).
> 
> Or you could use use the class provided by [py-android-viewer](https://github.com/razumeiko/py-android-viewer/tree/83f6170a61b6bbc3f20beb57b95a05c282bad7f1) directly if you don't want program the networking bit yourself

OMG it works perfectly. Thank you so much!!! You just made my day 😁
