### ISSUE TITLE
Screenshot/Record Screen

### ISSUE THREAD

**Issue by DungFu** [Genymobile/scrcpy#21]
Having a keyboard command to take a screenshot and one to start/stop recording the screen into a video would be an extremely useful feature for scrcpy.

scrcpy seems to already be using ffmpeg on the computer side, so saving the input stream to a file/screenshotting the input stream should be very do-able.

**Comment by redwolf2** [comment]
As a workaround for now:

Screenshots: Works on every application:
<kbd>ALT RIGHT</kbd> + <kbd>Print</kbd>
Then paste the image to your favorite image editor.

... or use the Windows Snipping tool.

Video recoring:
Just use [OBS Studio](https://obsproject.com/) and capture the window.

**Comment by rom1v** [comment]
Or:

**Screenshot:**

    adb exec-out screencap -p > file.png

**Video recording:**

    adb shell screenrecord /sdcard/file.mp4
    adb pull /sdcard/file.mp4

**Comment by zaniar** [comment]
I think it is best to leave this kind of feature to other program.

**Comment by rom1v** [comment]
Just to give a bit more details.

The server streams to the client a raw H.264 video stream. This stream does not contain any time information (no timestamps), which is not a problem because it's live. But for recording, we would need to mux the raw stream into a container, with timestamps (especially with a variable-framerate stream).

Ideally, the timestamps would be provided by the server (to be accurate), but this would mean an additional layer to mux on the server + demux on the client, which involves copies, and could increase the lag a bit

Alternatively, the client might mux the stream adding the timestamps according to the date it receives the frames. It could work, but would probably require some dependencies. I'm not sure it's worth it, since `adb shell screenrecord /sdcard/file.mp4` already does the job.

**Comment by shahtapan** [comment]
adb shell screenrecord /sdcard/file.mp4  does only for 180 seconds. I would like to record more than 1 hr. Any idea how can we use scrcpy to get this recording?

**Comment by rom1v** [comment]
@shahtapan Some work have been done to support recording in _scrcpy_, so hopefully it will be supported in a future version: https://github.com/Genymobile/scrcpy/pull/292.

**Comment by katieisnell** [comment]
Does the OBS Studio solution record the audio outputting from the device? If not then I think if this feature needs to be implemented into the strcpy with consideration to implement audio recording too 😄

**Comment by emartynov** [comment]
It would be great! I'm trying to use QuickTime player, but it is quite hassling to start, select area, be quick to remove mouse pointer, and don't forget to stop recording without passing mouse pointer through the recorded area.

**Comment by rom1v** [comment]
If you are interested, you can test the WiP branch [`record`](https://github.com/Genymobile/scrcpy/commits/record) (see https://github.com/Genymobile/scrcpy/pull/292).

**Comment by rom1v** [comment]
This is implemented in v1.5:

    scrcpy --record file.mp4

:tada:

**Comment by RedTgUser** [comment]
@rom1v and screenshot?

**Comment by rom1v** [comment]
> @rom1v and screenshot?

    adb exec-out screencap -p > screenshot.png

:trollface:

**Comment by RedTgUser** [comment]
Thanks:smiley:

**Comment by Noob567** [comment]
And do you know how to stop screen recording?

**Comment by rom1v** [comment]
@Noob567 https://github.com/Genymobile/scrcpy/issues/116#issuecomment-441238552

**Comment by wchargin** [comment]
Screen recording works great, but `adb exec-out screencap` does not work
for apps that prevent taking a screenshot on device. It would be nice to
have something like `scrcpy --screenshot file.png` that uses `scrcpy`’s
recording mechanism to capture a single *lossless* frame.

**Comment by rom1v** [comment]
@wchargin Capturing a lossless frame is a totally different process on the server-side. And it would take several seconds.

Refs #684 #1951

> Screen recording works great, but `adb exec-out screencap` does not work for apps that prevent taking a screenshot on device.

For now, Android 12 removed this possibility for screen recording too: #2129.

**Comment by BrunoFischerGermany** [comment]
Hey. I use 
adb exec-out screencap -p >> Screenshot__%date:~-4,4%%date:~-10,2%%date:~-7,2%_%time:~0,2%%time:~3,2%%time:~6,2%.png 

It create an png in the scrcpy.exe folder. 
I Think an key combination like ctrl + print in the scrcpy window would be great 👍

**Comment by TehRaccoon** [comment]
Screenshot using scrcpy could be useful in cases where you want to bypass screenshot protection of some apps. The "adb exec-out" command does not work in such cases
