### ISSUE TITLE
Android 6.0.1 only partially working

### ISSUE THREAD

**Issue by Froster2406** [Genymobile/scrcpy#210]
I followed the steps and so far I can clearly see my screen and also see it change while I navigate on my phones touchscreen, but it doesn't take any mouse input (ctrl + f, +x, +g work, the other commands don't).

I am using V1.2 64 Bit, but have also tried using V1.2 32 Bit and V1.1. And there is no error or whatsoever in the console.

Tried to apply the fix shown under [https://github.com/Genymobile/scrcpy/issues/70], but there is no option like it available

**Comment by rom1v** [comment]
Which device? Are there relevant logs in`adb logcat` when you click?

**Comment by Froster2406** [comment]
The device is a Yotaphone 2 aka. YD201 EU (does no longer receive official updates from the manufacturer).
What exactly do you mean with "adb logcat"? 

A screenshot with the output of the console can be found [here](https://imgur.com/a/UKO6bgm)

**Comment by Froster2406** [comment]
Allright, thank you for taking a look at it. I think you can close this issue then.

**Comment by jaboto** [comment]
Same issue with my Yotaphone. Was good finding this so I don't break my head for hours. Thanks!
