### ISSUE TITLE
How can I have scrcpy insert Turkish characters writing on computer's keyboard?

### ISSUE THREAD

**Issue by ceyhun242** [Genymobile/scrcpy#2105]
Currently when I write on computer's keyboard, turkish letters are not written. pressing "ğ" inserts no character and pressing "ı" creates an "I" 

This still holds true even tough swiftkey on android and my computer keyboard has Turkish layout..

What could be a fix or workaround to this?

Thank you

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#special-characters-do-not-work

**Comment by ceyhun242** [comment]
Is there a plan for implementing keyboard support anytime soon? I hope there is
Thank you

**Comment by rom1v** [comment]
> Is there a plan for implementing keyboard support anytime soon?

https://github.com/Genymobile/scrcpy/issues/1880#issuecomment-725655830

But probably not "anytime soon" :)
