### ISSUE TITLE
How can view "recent apps" as well as switch to "last viewed app"

### ISSUE THREAD

**Issue by ceyhun242** [Genymobile/scrcpy#2106]
Is there a shortcut for scrcpy to show recent apps and secondly a shortcut to switch to last viewed app just like pressing left bottom on Samsung s7 shows recent apps and double-tapping on the same button takes the user to the last viewed app?

**Comment by rom1v** [comment]
Alt+s

https://github.com/Genymobile/scrcpy#shortcuts

**Comment by ceyhun242** [comment]
Thank you
