### ISSUE TITLE
Which version supports android 4.4?

### ISSUE THREAD

**Issue by abuakram** [Genymobile/scrcpy#2115]
thanks

**Comment by rom1v** [comment]
None. Scrcpy requires Android 5.

**Comment by abuakram** [comment]
THANKS ... So sad... can you please tell me another way to mirror my device on ubuntu? My device's screen is broken :(

**Comment by HusseinDTS** [comment]
You may can use vysor, but it's not open source and you have to pay for full features. but at least you can mirror your device screen.
