### ISSUE TITLE
error: closed, ERROR: "adb reverse" returned with value 1

### ISSUE THREAD

**Issue by chalkos** [Genymobile/scrcpy#212]
I got abd via `brew cask install android-platform-tools` and scrcpy also from brew, but when running I get these errors, that don't really mean much to me...

```
▶ ADB=$(which adb) scrcpy
/usr/local/Cellar/scrcpy/1.2_1/share/scrcpy/scrcpy-server.jar: 1 file pushed. 4.8 MB/s (19342 bytes in 0.004s)
error: closed
2018-07-28 19:27:42.850 scrcpy[29698:20022786] ERROR: "adb reverse" returned with value 1
2018-07-28 19:27:42.851 scrcpy[29698:20022786] WARN: 'adb reverse' failed, fallback to 'adb forward'
WARNING: linker: app_process has text relocations. This is wasting memory and is a security risk. Please fix.
WARNING: linker: app_process has text relocations. This is wasting memory and is a security risk. Please fix.
Aborted
```

My device has not been updated in while. It is on 4.4.4, could that be the problem?

**Comment by rom1v** [comment]
The warning is related to your `app_process` binary on your device.

The _Aborted_ is because _scrcpy_ requires stuff available only since Android 5, so it may not work on Android 4.4.4.

**Comment by chalkos** [comment]
Thanks for clearing that up. I just noticed it was right on the readme :sweat_smile:
> The Android part requires at least API 21 (Android 5.0).

I guess I'll go update my android :)

**Comment by GregHilston** [comment]
This was my problem as well! Using Android 4.4.4 bummer
