### ISSUE TITLE
Error: scrcpy -m 1024

### ISSUE THREAD

**Issue by Chickeninja** [Genymobile/scrcpy#2120]
![Untitled](https://user-images.githubusercontent.com/38824195/107883184-63e10b80-6f28-11eb-9833-4e0f59858e4b.jpg)
Hi i don't really know how to code i was trying to find solutions over the net, but im not really getting how to edit scrcpy log. Im having an error that is caused by my phone not able to open or play with 1080 reso's could i get a little help sorry. 

The error is [ ERROR: Try with a lower definition: ERROR:       scrcpy -m 1024]

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows

**Comment by Chickeninja** [comment]
Thank you soo much.

**Comment by Chickeninja** [comment]
Just one issue though, is there a available options on where I could forward my audio to my pc? My phone is only android 9 and sndcpy is for android 10.

**Comment by rom1v** [comment]
No :(

**Comment by Chickeninja** [comment]
Awww thats okay i'll try to find something on the web but thanks tho. :)
