### ISSUE TITLE
There is color shift when viewing in landscape mode which makes the screen viewing dull..
Is there a fix for this..??🙏

### ISSUE THREAD

**Issue by moxzie** [Genymobile/scrcpy#2126]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
Please post the terminal output when you run scrcpy.

Probably related: https://github.com/Genymobile/scrcpy/issues/177#issuecomment-572875043

**Comment by moxzie** [comment]
here is the screenshot..
![Screenshot from 2021-02-19 20-16-26](https://user-images.githubusercontent.com/10766623/108488004-e15ca100-72c5-11eb-9436-1ac1e5d5208b.png)

![Screenshot from 2021-02-19 20-15-57](https://user-images.githubusercontent.com/10766623/108487987-dace2980-72c5-11eb-9f54-72018b1da818.png)

**Comment by moxzie** [comment]
Clearly visible here

![Screenshot from 2021-02-19 20-18-08](https://user-images.githubusercontent.com/10766623/108488119-03eeba00-72c6-11eb-97ff-5b8b848cc1a2.png)

**Comment by rom1v** [comment]
OK so this is a device encoder bug like #177.

Try with a lower definition (`scrcpy -m1024`) or with another encoder: https://github.com/Genymobile/scrcpy#encoder

**Comment by moxzie** [comment]
Even the recording play with color shift..

**Comment by moxzie** [comment]
> OK so this is a device encoder bug like #177.
> 
> Try with a lower definition (`scrcpy -m1024`) or with another encoder: https://github.com/Genymobile/scrcpy#encoder

Thanks for #177..
Problem fixed.
I ran scrcpy with --max-size 1920 and now all color shift problem seems to be properly fixed.
![Uploading screenshot3.png…]()

**Comment by moxzie** [comment]
This not only fixed my color shift problem but also my mouse-click problem.
Previously i could directly click on the screen using my mouse.
But After reducing the max-size to 1920 on my realme 1 device,
the problem of mouse click has also been solved..
Hurray ! i was facing this problem from last year. i Wish i had come here before.
![Screenshot from 2021-02-19 20-31-04](https://user-images.githubusercontent.com/10766623/108490165-71034f00-72c8-11eb-98f8-26120f2beb24.png)

**Comment by moxzie** [comment]
![Screenshot from 2021-02-19 20-27-23](https://user-images.githubusercontent.com/10766623/108490617-ef5ff100-72c8-11eb-8e93-1439d48a5455.png)

No more color shift..Problem fixed. Thanks a lot !
