### ISSUE TITLE
Unable to connect via ADB over TCPIP

### ISSUE THREAD

**Issue by ZizzyDizzyMC** [Genymobile/scrcpy#213]
I can complete a connection to my android device over ADB including opening a shell.  I cannot get scrcpy to work over wifi however.

I believe it might be related to the retry attempts.  I know it's 50 retries at a 100ms wait time as per the code, and was wondering if there would be a way to test and see if a higher retry count would fix my issue.

Basically a carbon copy of #121 but with the no connection of #5 's issue of timing out before the phone server starts.  

Edit: The phone I was orginally trying the adb over wifi connection was a ZTE ZFive 2, that didn't work.  It has Android 6.0.1  

I tried it with my Samsung S7 which is also running Android 6.0.1.   This worked quickly and has worked a few more times after closing and reopening again.

I highly suspect now that the slower ZTE just couldn't start the server fast enough.  Perhaps change this into a feature request to make a start-up flag that allows us to set the connection attempts to a higher value in the case that our devices can't connect fast enough.

**Comment by rom1v** [comment]
Thank you for your report.

You can increase the number of attempts to confirm the problem. See https://github.com/Genymobile/scrcpy/issues/5#issuecomment-373703801

Basically, change [this line](https://github.com/Genymobile/scrcpy/blob/v1.2/app/src/server.c#L210) and recompile.

**Comment by KeronCyst** [comment]
Would you be willing to give an exact step-by-step procedure of what you're doing, from the very beginning all the way to the error? Maybe we can pinpoint what's going on with such further detail.

**Comment by rom1v** [comment]
Please retry with v1.3.
