### ISSUE TITLE
No .exe file

### ISSUE THREAD

**Issue by ChristianBarette** [Genymobile/scrcpy#2134]
I have installed  today the latest release on my Windows 10 computer and I don't find the scrcpy.exe

How can I start the application ?

**Comment by npes87184** [comment]
How do you install scrcpy?

**Comment by ChristianBarette** [comment]
I have just unzip the .zip file

**Comment by rom1v** [comment]
Could you list all the files you see?

Maybe some anti-virus detected it as a virus (a false-positive, see #1102) and removed the `.exe`.

**Comment by daniel11609** [comment]
![grafik](https://user-images.githubusercontent.com/19250367/108624238-fd864c80-7443-11eb-96a9-c6813c56eeb2.png)
this is how it should look on win10

**Comment by ChristianBarette** [comment]
I have got the .zip file by clicking green Code button, then Download ZIP and I got the following file: scrcpy-master.zip  but the right file is scrcpy-win64-v1.17.zip (as described in Github Readme section). 
So now, I get an .exe file
Sorry, I have just signed in for Github

**Comment by daniel11609** [comment]
> 
> 
> I have got the .zip file by clicking green Code button, then Download ZIP and I got the following file: scrcpy-master.zip but the right file is scrcpy-win64-v1.17.zip (as described in Github Readme section).
> So now, I get an .exe file
> Sorry, I have just signed in for Github

dont worry, you usually do not click on the "Code" Button, only if you really want to get the source code. The final programs are usually found as "release".
