### ISSUE TITLE
Screen tearing and tilting on custom system(5.1.1).

### ISSUE THREAD

**Issue by qwwuyu** [Genymobile/scrcpy#2138]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows]
 - scrcpy version: [1.17]
 - installation method: [Windows]
 - device model: customize
 - Android version: [5.1.1]

**Describe the bug**
I have a custom system(5.1.1),  It can control the rotation direction of the screen.
When set to landscape, it displays normally.
When set to vertical screen, it will a blurred screen. Screen tearing and tilting, No abnormal output.
I think display size may be error(width and height reversed), but I don't know how to deal with it.
Whether similar problems arise, thanks.

```
Please paste terminal output in a code block. 
```
No abnormal output.

**Comment by rom1v** [comment]
> When set to vertical screen, it will a blurred screen.

#40 ?

> Screen tearing and tilting,

Is there still tearing if you record and play the file?

```
scrcpy --record file.mkv
```

**Comment by qwwuyu** [comment]
> > When set to vertical screen, it will a blurred screen.
> 
> #40 ?
> 
> > Screen tearing and tilting,
> 
> Is there still tearing if you record and play the file?
> 
> ```
> scrcpy --record file.mkv
> ```

The recording also has this problem, which is not the same as the #40 problem.

![1](https://user-images.githubusercontent.com/8111079/108690983-f0e22100-7535-11eb-99be-e2d9f564eb08.png)
![2](https://user-images.githubusercontent.com/8111079/108690994-f50e3e80-7535-11eb-999f-49f3fb20fc82.png)

file.mkv the same as above

adb shell screencap -p /sdcard/screenshot.png
adb pull /sdcard/screenshot.png

landscape screen screencap command Will get the following picture
![screenshot](https://user-images.githubusercontent.com/8111079/108691645-af05aa80-7536-11eb-9c05-5d511f97687d.png)

vertical screen screencap command Will get the following picture
![screenshot](https://user-images.githubusercontent.com/8111079/108691260-47e7f600-7536-11eb-833b-229e81f233e2.png)

**Comment by rom1v** [comment]
Oh, that kind of tearing!

It's #777 then (a device encoder issue).

Try reducing the definition (`scrcpy -m600` or more if it works), or test with [another encoder](https://github.com/Genymobile/scrcpy#encoder).

**Comment by qwwuyu** [comment]
solved, thanks.
