### ISSUE TITLE
Using "crop" also crops on the device

### ISSUE THREAD

**Issue by markwmuller** [Genymobile/scrcpy#2140]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Ubuntu 20.04]
 - scrcpy version: [1.17]
 - installation method: [snap]
 - device model: Samsung Tab S7+
 - Android version: [11]

**Describe the bug**
Connection is via USB. The specific command I run is `scrcpy --crop 1752:2800:50:0`. The issue is that the "crop" command also blacks out the corresponding region of the device display. I have 3 android devices, and it happens on two that run android 11, but not on the one that runs android 10. 

What I want: tablet display shows the full (normal) tablet display. The window on my computer is cropped to only show a part of the display.

I'm copying the text output FWIW below. For the Tab S7+, which has the issue. 
```
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 1.0 MB/s (34930 bytes in 0.032s)
[server] INFO: Device: samsung SM-T970 (Android 11)
INFO: Renderer: opengl
INFO: OpenGL version: 3.0 Mesa 20.0.8
INFO: Trilinear filtering enabled
INFO: Initial texture: 2800x1696
```

For the other tablet, which does not have the issue (android 10):
```
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 4.0 MB/s (34930 bytes in 0.008s)
[server] INFO: Device: samsung SM-P610 (Android 10)
INFO: Renderer: opengl
INFO: OpenGL version: 3.0 Mesa 20.0.8
INFO: Trilinear filtering enabled
INFO: Initial texture: 2000x1144
```

**Comment by rom1v** [comment]
Probably an "optimization" in the system when the device thinks that only a part of the screen is used (similar to #836).

What happens if you start two instance of scrcpy for the same device with different crop regions?

**Comment by markwmuller** [comment]
Running two instances I get the below, but it's not consistent.
Start first version: `scrcpy --crop 1752:2800:500:0`
* Device has big black bar across top. Scrcpy window is as expected.
Start second version: `scrcpy --crop 1752:2800:0:500`
* First scrcpy window is unchanged. 
* Device display is unchanged. 
* Second scrcpy window has big black bar across top.

**Comment by markwmuller** [comment]
Just for completeness, my workaround currently is the following bash script. It seems to work around 50% of the time (but that's OK for my use case). The first window is deliberately made small (width of 1) so it effectively disappears from your desktop. The script kills the first window when you close the main window of scrcpy.

```
#!/usr/bin/bash

# hack needed to show full display: https://github.com/Genymobile/scrcpy/issues/2140
scrcpy -m 256 --max-fps 1 --crop 1752:2800:0:0 --window-width 1 -n & 

sleep 1

scrcpy --show-touches --window-borderless --max-fps 30 --crop 1752:2800:170:0 --no-control


# Kill the background process:
kill $!
```

**Comment by rom1v** [comment]
There is a (non-static) method [`SurfaceControl.setTransparentRegionHint()`](https://android.googlesource.com/platform/frameworks/base.git/+/57a0af04c5354bfebfbdf82be31526f9dcbf6aef/core/java/android/view/SurfaceControl.java#2519) and [`Transaction.setTransparentRegionHint()`](https://android.googlesource.com/platform/frameworks/base.git/+/57a0af04c5354bfebfbdf82be31526f9dcbf6aef/core/java/android/view/SurfaceControl.java#2519), if someone wants to investigate.

**Comment by markwmuller** [comment]
Just for completeness sake, another note -- I've noticed that this problem now no longer appears, and I can't seem to recreate it anymore. I'm not sure what's changed, except that maybe I've had my tablet update its software (still Android 11 though).

**Comment by Zombie-dev-1** [comment]
I found a workaround in windows 

First  open a scrcpy window with your desired resolution (the mobile screen crops)
` scrcpy --crop 1224:1440:0:0` for example

Then open a scrcpy window without any cropping (the mobile screen restores)
`scrcpy`
Don't close the 2nd windows because the screen will revert back to crop res.

I Hope this works
