### ISSUE TITLE
Adding translation README into japanese

### ISSUE THREAD

**Issue by aruko-210** [Genymobile/scrcpy#2150]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

I think this project is really nice. 
It will be more convenient for japanese people if this is written in japanese.
If you don't mind, I'd like to contribute to this project by translating into japanese.

**Comment by rom1v** [comment]
You mean translating the README?

Yes, please do, and submit a PR (like #934, #1626 or #1723 for example) :)

**Comment by aruko-210** [comment]
@rom1v 
Thank you for your replying.
I will start translating the README into japanese.

**Comment by aruko-210** [comment]
@rom1v 
Could you check the PR I posted #2195 ?

**Comment by aruko-210** [comment]
#2195  merged.
