### ISSUE TITLE
where the Then Makefile.CrossWindows in master?

### ISSUE THREAD

**Issue by lfjking** [Genymobile/scrcpy#2151]
as like as title: where the file:Makefile.CrossWindows?
I download the master zip , Cross-compile from Linux. at last, I can't find the Makefile.CrossWindows...
may I know what had changed?

**Comment by rom1v** [comment]
It's release.mk now. The doc must be updated, sorry.

**Comment by rom1v** [comment]
> The doc must be updated, sorry.

Done: a2919b3ef2d3b08f426ac53ff1999c0f7f925e9f
