### ISSUE TITLE
May I only built the client with Cross-compile from Linux?

### ISSUE THREAD

**Issue by lfjking** [Genymobile/scrcpy#2154]
thanks for help. I run app well on linux.
I just built client enough, and I want to built it on window, with Cross-compile from Linux. ( I only want to built client)
How can I do ?

**Comment by rom1v** [comment]
There is already a prebuilt release for Windows.

But you can `make -f release.mk build-win64`.

**Comment by lfjking** [comment]
`/scrcpy-master$ make -f release.mk build-win64
fatal: Not a Git repository (or any parent directory)：.git
make -C prebuilt-deps prepare-win64
make[1]: into“/home/debian/down/scrcpy-master/prebuilt-deps”
SDL2-2.0.14: found
ffmpeg-4.3.1-win64-shared: found
ffmpeg-4.3.1-win64-dev: found
platform-tools: found
make[1]: leave“/home/debian/down/scrcpy-master/prebuilt-deps”
[ -d "build-win64" ] || ( mkdir "build-win64" && \
	meson "build-win64" \
		--cross-file cross_win64.txt \
		--buildtype release --strip -Db_lto=true \
		-Dcrossbuild_windows=true \
		-Dcompile_server=false \
		-Dportable=true )
ninja -C "build-win64"
ninja: Entering directory `build-win64'
ninja: error: loading 'build.ninja': No such file or directory
make: *** [release.mk:83：build-win64] error 1
`

this error : 'build.ninja': No such file or directory.
it like no folder X. but me not sure.

**Comment by rom1v** [comment]
> I copy the folder x files to build-win64, and do 'make -f release.mk build-win64'.
> then, I delete the build-win64, redo it , and then, everything well, I get the scrcpy.exe.

I don't understand, there is no `x` folder related to building with `release.mk`.

But glad that it works :smile:

**Comment by lfjking** [comment]
> 
> 
> > I copy the folder x files to build-win64, and do 'make -f release.mk build-win64'.
> > then, I delete the build-win64, redo it , and then, everything well, I get the scrcpy.exe.
> 
> I don't understand, there is no `x` folder related to building with `release.mk`.
> 
> But glad that it works smile
------------------------------------------------------------
Me too.

When I first performed  'make -f release.mk build-win64'.
the build-win64 folder have no the build.ninja file.
I remember when Prebuilt server was executed, there was this file in the X folder.
So. I try to copy all the files in the X folder to build-win64,and do 'make -f release.mk build-win64', it run well, but it doesn't get EXE in the app folder.
and then, I delete the build-win64 folder, try to do 'make -f release.mk build-win64'. again.
this time build-win64 have build.ninja file, and I get the exe in app folder.
It was an amazing experience.
Thank you so much for the project. It's great.
