### ISSUE TITLE
Wireless Connection

### ISSUE THREAD

**Issue by MihaiCazac1** [Genymobile/scrcpy#2157]
So i'm tryn to connect my device (Huawei P40 lite) to my pc wirelessly, but everytime i get this error `C:\Users\Mihai Cazac>scrcpy -s 192.168.1.2:5555 -m 1920
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: device offline
ERROR: "adb push" returned with value 1` and it doesnt connect ,but when i plug the usb and try it works,as in image
![Screenshot 2021-03-01 144029](https://user-images.githubusercontent.com/79847699/109498476-2b027400-7a9c-11eb-82ba-5419c0e09217.png)

I tried everything,any ideas? 
Also after i disconnect my device ,when i list adb devices it says my device is offline

**Comment by MihaiCazac1** [comment]
When i unplug the usb before adb connect 
![Screenshot 2021-03-01 144634](https://user-images.githubusercontent.com/79847699/109499010-fcd16400-7a9c-11eb-9e3f-95010e739bc5.png)

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/issues/2097#issuecomment-775915121

**Comment by MihaiCazac1** [comment]
Thanks it worked,i used my phone in file transfer mode previously to get usb debugging
