### ISSUE TITLE
[QN] How to toggle power options?

### ISSUE THREAD

**Issue by pundoo** [Genymobile/scrcpy#216]
Hi,
Is there any way to toggle the power options? When I press (or even hold) `Ctrl` +` P` it only switches on/off the screen, but I wanna toggle the power options (shutdown, reboot etc.)

Thanks!

**Comment by rom1v** [comment]
Build the current `master` branch, which includes a fix for https://github.com/Genymobile/scrcpy/issues/166.

**Comment by pundoo** [comment]
Thanks for quick reply. Will do it soon.. :)

**Comment by pundoo** [comment]
Hello, I tired to build it Linux for Windows 64-bit, but it shows this error : 

![error](https://user-images.githubusercontent.com/26104744/43582767-4db1fc4a-967f-11e8-9004-5883808e7bef.PNG)

I'm not so familiar with Linux, so I don't know what that exactly means. Do I need to setup Android Studio or something else to build it? (I've already installed `mingw `and `jdk`)

**Comment by rom1v** [comment]
For simplicity, use the [prebuilt-server](https://github.com/Genymobile/scrcpy#prebuilt-server) (it still works with the `master` branch, the changes are on the client).

**Comment by rom1v** [comment]
OK, you're cross-compiling for Windows :smile: 

So that's just the `clean` recipe that is the problem. For now, I would suggest to remove `$(GRADLE) clean` from the `clean` recipe to avoid the problem :p

**Comment by rom1v** [comment]
OK, you're cross-compiling for Windows :smile: 

Try:

    make -f Makefile.Crosswindows build-win64

**Comment by pundoo** [comment]
Thanks! It worked 😊
