### ISSUE TITLE
scrcpy-noconsole.vbs still shows the console

### ISSUE THREAD

**Issue by Borgotto** [Genymobile/scrcpy#2160]
`CreateObject("WScript.Shell").Run "cmd /c scrcpy.exe --max-fps 60 --window-title Samsung-Galaxy-Tab-S7 --bit-rate 8M --max-size 1920", 0, false`

When run it shows the console, see screenshot below:

https://imgur.com/weD2BuT

**Comment by rom1v** [comment]
And when you run the original `scrcpy-noconsole.vbs` (without adding argument) too?

**Comment by Borgotto** [comment]
> And when you run the original `scrcpy-noconsole.vbs` (without adding argument) too?

Yeah, same happens with the original

**Comment by rom1v** [comment]
Weird, it works for me. And: https://superuser.com/a/140077/310383

**Comment by rom1v** [comment]
How do you run it? You just double-click on `scrcpy-noconsole.vbs` from the file explorer?

**Comment by Borgotto** [comment]
> How do you run it? You just double-click on `scrcpy-noconsole.vbs` from the file explorer?

Yes, am I supposed to run it some other way?

**Comment by rom1v** [comment]
No, that's how it's supposed to work. Which Windows is it?

**Comment by Borgotto** [comment]
Windows 10
Version 20H2
Build 19042.804

**Comment by Borgotto** [comment]
I **solved it by updating the adb drivers**, since i had an older version it was restarting the daemon every time i ran any adb command, that may have something to do with it.
**With up to date adb drivers the console doesn't show up when running `scrcpy-noconsole.vbs`**

**Comment by rom1v** [comment]
Oh, adb was opening a console, then :confused:
