### ISSUE TITLE
Bigger resolution

### ISSUE THREAD

**Issue by VojtechNiederle** [Genymobile/scrcpy#2161]
Hello is any way to use 1080*2340 texture or higher? I have a smartphone with 2340*1080 and I think that is standard in 2020.

**Comment by rom1v** [comment]
By default (if you don't pass `-mXXXX`), scrcpy uses the native resolution of your device screen.

**Comment by VojtechNiederle** [comment]
![image](https://user-images.githubusercontent.com/78854153/109789891-15fb2180-7c11-11eb-8759-3e087fbabcbc.png)
it works until 1920 in higher resolution it is crashing

**Comment by rom1v** [comment]
OK, then this is a limitation of your device hardware encoder, which is not able to encode at a higher definition: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

**Comment by VojtechNiederle** [comment]
So is it fixable? I am not a programmer so I don't  understand CMD much

**Comment by rom1v** [comment]
> So is it fixable?

No, it seems that your device hardware is not able to encode at a higher definition.

**Comment by VojtechNiederle** [comment]
Thank you
