### ISSUE TITLE
Open other apps from the server

### ISSUE THREAD

**Issue by ozshabat** [Genymobile/scrcpy#2165]
Hey guys,

I wanted to find a way to call a different activity, from a different app (say open Netflix) from the server.

You made the `ServiceManager` class in order to get the relevant services for each action (input, window, display and etc) and I though about implementing the `IActivityManager` and with that, open apps from the server.

I tried:
```
public void getActivityManager() {  
 if (activityManager == null) {
            activityManager = new ActivityManager(getService("activity", "android.app.IActivityManager"));
        }
        return activityManager;
    }
```
but it failed.

Do you have any idea how to implement the service?

By the way, I will be happy to use any other way to open different apps. As I understand it, you gotta have an Activity to open other activities and the server doesn't have one.

Thanks!

**Comment by rom1v** [comment]
To open an app, you must mimic what the SDK API does with [`Context.startActivity(Intent)`](https://developer.android.com/reference/android/content/Context#startActivity(android.content.Intent)), but from an [`IActivityManager`](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/app/IActivityManager.aidl).

Some pointers:
 - https://github.com/aosp-mirror/platform_frameworks_base/commit/2882406de31bd2a60e523253d8794e14af236975
 - `runStartActivity()` https://android.googlesource.com/platform/frameworks/base/+/master/services/core/java/com/android/server/am/ActivityManagerShellCommand.java

**Comment by ozshabat** [comment]
Thanks for the help.

I really don't know if I'm looking in the relevant locations but I did this.

I looked at [Am.java](https://github.com/aosp-mirror/platform_frameworks_base/blob/2882406de31bd2a60e523253d8794e14af236975/cmds/am/src/com/android/commands/am/Am.java) and I understood that `mAm.asBinder().shellCommand()` is the way to fire `adb shell am ...` commands so I tried to build the call via reflection. It looks like so:

```
// get the activity manager native interface
Class<?> cls = Class.forName("android.app.ActivityManagerNative");
Method getDefaultMethod = cls.getDeclaredMethod("getDefault");
IInterface am = (IInterface) getDefaultMethod.invoke(null);
```
```
// get the binder 
Method asBinderMethod = am.getClass().getMethod("asBinder");
Object binderProxy = asBinderMethod.invoke(am);
```

and now I stuck cause I need to get the `ShellCallback.class` for the `"shellCommand"` method and the class is hidden (?)

tried like so (and it couldn't find the class):
```
 Class<?> shellCbClass = Class.forName("android.os.ShellCallback");
            System.out.println("Shell cb: " + shellCbClass);
                Method shellCommandMethod = binderProxy.getClass().getMethod("shellCommand", FileDescriptor.class,
                        FileDescriptor.class,
                        FileDescriptor.class,
                        String[].class,
                        shellCbClass,
                        ResultReceiver.class);
```

BTW I don't think that I'm looking at the right place. Can you point me further?

**Comment by ozshabat** [comment]
Thank you for your help.

I don't need this anymore
