### ISSUE TITLE
no working in sony tv

### ISSUE THREAD

**Issue by NDS7EN** [Genymobile/scrcpy#2168]
[server] INFO: Device: Sony BRAVIA 4K GB (Android 9)
INFO: Renderer: direct3d
INFO: Initial texture: 1920x1080
ERROR: Could not send video packet: -1094995529
ERROR: Could not process frame
WARN: Device disconnected

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/issues/1287#issuecomment-743023526
