### ISSUE TITLE
My keyboard/mouse doesn't work

### ISSUE THREAD

**Issue by vignakke** [Genymobile/scrcpy#2173]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS:  Windows
 - scrcpy version: 1.17
 - installation method: Windows release
 - device model:  Xiaomi M2007J20CG (Android 10) (poco x3 nfc)
 - Android version: 10

**Describe the bug**
My keyboard/mouse doesn't work on the screen, the image of the phone is displayed but I can't control anything from the computer.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work
