### ISSUE TITLE
shortcuts and features suggestions

### ISSUE THREAD

**Issue by JAS-coder** [Genymobile/scrcpy#2176]
* start/stop record when app already running.
* show record icon over render.
* show fps over window render.
* start/stop audio record.

**Comment by rom1v** [comment]
> start/stop record when app already running.

#475 #1032 https://github.com/Genymobile/scrcpy/issues/1186#issuecomment-592386916

> show fps over window render.

https://github.com/Genymobile/scrcpy/issues/274#issuecomment-423934442

> start/stop audio record.

https://github.com/Genymobile/scrcpy#audio-forwarding
https://blog.rom1v.com/2020/06/audio-forwarding-on-android-10/#integration-in-scrcpy
