### ISSUE TITLE
No apt package "scrcpy"

### ISSUE THREAD

**Issue by Chetan-Goyal** [Genymobile/scrcpy#2177]
**Environment**
 - OS: Linux Mint 19.2
 - installation method: apt

**Describe the bug**
apt package "scrcpy" is not available.

```
chetan@chetan-pc:~$ apt install scrcpy
[sudo] password for chetan:          
Reading package lists... Done
Building dependency tree       
Reading state information... Done

No apt package "scrcpy", but there is a snap with that name.
Try "snap install scrcpy"

E: Unable to locate package scrcpy
```

**Comment by rom1v** [comment]
The package `scrcpy` exists in Ubuntu since 20.04, so it was not available in 2019. If you don't want to upgrade your distrib, you can either use the snap package or [BUILD](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md) manually.
