### ISSUE TITLE
adb error 

### ISSUE THREAD

**Issue by devanshish** [Genymobile/scrcpy#2187]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: windows 8.1
 - scrcpy version:1.17
 - installation method: windows release
 - device model:
 - Android version: 9

**Describe the bug**
unable to mirror phone  screen
my terminal result after executing the run:

info: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
*daemon not running; starting now at tcp:5037
*daemon started successfully 
adb: error: failed to get feature set: no devices/emulators found
ERROR: "adb push" returned with value 1

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#device-not-detected

**Comment by devanshish** [comment]
Reinstalling and restarting the drivers worked, thanks.
