### ISSUE TITLE
Error Working with SideQuest.

### ISSUE THREAD

**Issue by KDLN** [Genymobile/scrcpy#2192]
- [x ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...] macOS
 - scrcpy version: [e.g. 1.12.1] 1.17.1
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...] Brew
 - device model: Quest 2
 - Android version: [e.g. 10]

**Describe the bug**
Using SideQuest it does not connect. 

On errors, please provide the output of the console (and `adb logcat` if relevant).
ScrCpy Error: {"killed":false,"code":127,"signal":null,"cmd":"scrcpy -v"}

```
Please paste terminal output in a code block.
```
Terminal keeps going no end. 
Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
Try to run scrcpy manually (without side quest). What is the error message?

**Comment by KDLN** [comment]
It opens and streams.

**Comment by rom1v** [comment]
:+1:

Then you should report the issue to SideQuest (this is a totally separate project).

**Comment by KDLN** [comment]
So sorry about that thank you.
