### ISSUE TITLE
[Win10 / Puxel 4XL (Android 11)] Connecting wirelessly?

### ISSUE THREAD

**Issue by bellyrose** [Genymobile/scrcpy#2193]
I've tried what the readme says and multiple guides online and cannot get wireless connection to work; could someone explain it to me like I'm an old person that needs help getting to their email?

**Comment by rom1v** [comment]
Tell us which problem you encounter (and at which [step](https://github.com/Genymobile/scrcpy#wireless)).

**Comment by bellyrose** [comment]
I repeated all the steps the same way I did yesterday and it's working fine now, I didn't change anything so I'm not sure what changed.
