### ISSUE TITLE
SDL2.dll error

### ISSUE THREAD

**Issue by AbdelrahmanAli** [Genymobile/scrcpy#2196]
Hi I'm trying to connect a tablet to Windows 10 using scrcpy and I'm getting this error 

![image](https://user-images.githubusercontent.com/9371556/111066835-1aa5bc80-84d2-11eb-95b2-c3e2c90ab05b.png)

Any help?

**Comment by rom1v** [comment]
Is your system 64bits? If not, download the 32-bit version of scrcpy: https://github.com/Genymobile/scrcpy/releases/download/v1.17/scrcpy-win32-v1.17.zip

**Comment by AbdelrahmanAli** [comment]
It is 64 bit
![image](https://user-images.githubusercontent.com/9371556/111068784-411c2580-84db-11eb-9636-8dd2923808e3.png)

**Comment by Biswa96** [comment]
The error status `0xC0000022` means STATUS_ACCESS_DENIED. Is there any admin in your system? Also after downloading the zip file, right click on that file, unblock the following thing:

![Capture](https://user-images.githubusercontent.com/31443074/111069943-703f9080-84f5-11eb-9ffd-ed124534f013.PNG)

**Comment by AbdelrahmanAli** [comment]
Yes, there is an admin on my system.

I don't have this checkbox
![image](https://user-images.githubusercontent.com/9371556/111071596-f359ea00-84e7-11eb-83b0-a3542ae0af27.png)

**Comment by AbdelrahmanAli** [comment]
I tried it on my personal laptop now, it's working fine.

So it seems I don't have permission to run it on my other Laptop.
