### ISSUE TITLE
config.h doesn't exist

### ISSUE THREAD

**Issue by thecodedoctorr** [Genymobile/scrcpy#2202]
I just cloned this project to my computer (Windows), my setup is fine, I installed all the extra packages needed and it all looks good apart from this: In the `main.c` as well as some other files, there is this `#include "config.h" ` but I don't seem to see any file called config.h in this project... am I wrong or what is happening? 
I also also work on  windows  but  the code includes some linux libraries!

**Comment by rom1v** [comment]
`config.h` is generated by meson:

```bash
meson build
ls build/app/config.h
```

> I also have installed the windows version the code includes some linux libraries!

Which ones?

**Comment by thecodedoctorr** [comment]
I verbed my question a bit weirdly there. I am saying, I am working with windows but the code includes <unistd.h>

**Comment by rom1v** [comment]
`<unistd.h> is available on Windows.

You must use meson+ninja to build scrcpy.

**Comment by thecodedoctorr** [comment]
ok.´, got it
