### ISSUE TITLE
Mirror window/tab doesn't show up on PC

### ISSUE THREAD

**Issue by Shadi1337** [Genymobile/scrcpy#2203]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Android
 - scrcpy version: Tried 2 different ones, but let's stick with the newest: scrcpy-win64-v1.17
 - installation method: Just a windows Zip
 - device model: Xiaomi Redmi9  (M2004J19C)
 - Android version: 10

**Describe the bug**

I have no errors, but the mirror screen/tab/window does not come up on the PC. This is what the console says: 

INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
C:\Users\directory\scrcpy-win64-v1.17\scrcpy-ser... file pushed, 0 skipped. 66.6 MB/s (34930 bytes in 0.001s)
[server] INFO: Device: Xiaomi M2004J19C (Android 10)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2336

Which looks like it's working, I know this coz it works on my Samsung S6 just fine.

**Comment by rom1v** [comment]
Try with a lower definition (`scrcpy -m1024`) or with another [encoder](https://github.com/Genymobile/scrcpy#encoder).

**Comment by Shadi1337** [comment]
> Try with a lower definition (`scrcpy -m1024`) or with another [encoder](https://github.com/Genymobile/scrcpy#encoder).

Where do I type the scrcpy -m1024, coz if I do it after I open scrcpy it doesn't do anything (sorry I'm not familiar with how to do this)

[server] INFO: Device: Xiaomi M2004J19C (Android 10)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2336
scrcpy -m1024

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows

**Comment by Shadi1337** [comment]
> https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows

scrcpy --encoder c2.android.avc.encoder
This one worked, is there any way I can make it default? Not that it's a big issue to do it every time, just convenience. 

And thank you very much for the super prompt and nice answers!

**Comment by Shadi1337** [comment]
Actually wait. I can't use anything in there, clicking or moving anything with my mouse doesn't work.

**Comment by Shadi1337** [comment]
And USB debugging is on (I read FAQ)

**Comment by rom1v** [comment]
> scrcpy --encoder c2.android.avc.encoder
> This one worked, is there any way I can make it default?

Create a batch file with these arguments (see the end of https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows).

> Actually wait. I can't use anything in there, clicking or moving anything with my mouse doesn't work.

"USB debugging (Security settings)"
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work

**Comment by Shadi1337** [comment]
Can't believe that within 30 minutes you have given me all these working solutions. 

Much better than most companies even, and you aren't one. Is there any way to donate a few coins to you? :)

Best regards, 
me

**Comment by rom1v** [comment]
Glad it works for you :)

> Is there any way to donate a few coins to you?

[paypal.me/rom2v](https://paypal.me/rom2v) (referenced from https://blog.rom1v.com/about/) :heart:
