### ISSUE TITLE
Questions about v1.3 changes

### ISSUE THREAD

**Issue by RedMoonOTInetwork** [Genymobile/scrcpy#221]
Hi romain, I did not understand [this new function](https://github.com/Genymobile/scrcpy/issues/166). Also how it works " crop feature"?

**Comment by RedMoonOTInetwork** [comment]
Wait, crop it's for augmented reality?

**Comment by RedMoonOTInetwork** [comment]
Or have a double screen?

**Comment by rom1v** [comment]
> Wait, crop it's for augmented reality?

No, crop is for cropping (to mirror only part of the device screen).

OculusGo runs Android. Its screen displays the content for both eyes side-by-side. It may be useful to mirror only the content for one eye (and possibly removing the borders).

**Comment by RedMoonOTInetwork** [comment]
Ok thanks
