### ISSUE TITLE
I open the scrcpy and then it closes

### ISSUE THREAD

**Issue by diegocrivelaro** [Genymobile/scrcpy#2213]
![image](https://user-images.githubusercontent.com/62905712/112401627-b82a9880-8ce9-11eb-83ec-5a5d2b57a908.png)

After a second it closes

**Comment by rom1v** [comment]
1. please use the issue template for reporting a bug
2. check for errors in `adb logcat`
3. try with another [encoder](https://github.com/Genymobile/scrcpy#encoder)
