### ISSUE TITLE
scrcpy is sending the Error: could not parse the device id: xxxxxxxxxxx

### ISSUE THREAD

**Issue by ravotw** [Genymobile/scrcpy#2220]
Envirionment Ubuntu: 18.04.5 LTS

I have installed scrcpy as indicated in the forums.
I have launched adp device and and getting the ids of my 2 samsung devices connected to the USB ports
I have included the file 51-Android.rules with the following information:
SUBSYSTEM=="usb", ATTR{idVendor}=="04e8", ATTR{idProduct}=="6860", MODE="0666", GROUP="plugdev", SYMLINK+="android%n"
according to the informaion I have got from lsusb command.

And when I launch scrcpy --display "id of my phone from adb devices command" I am getting the error "Could not parse the device id: xxxxxxx"

My devices are nunning Android 7.0 and 8.00 respecively.

I have already tried de-activating re-activating USB debugging in both smartphones, unplugging re-plugging the usb cables, changed the usb cables. I have tried adb kill-server, then adb start-server.

It used to work before, and now I cannot make it work anymore.

I couldn't find the error in any other FAQ.

Thanks for your help;

**Comment by rom1v** [comment]
> And when I launch scrcpy --display "id 

You probably want to pass the device id/serial (as listed by `adb devices`), not the display id:

```
scrcpy -s xxxxxx
```

**Comment by ravotw** [comment]
You are right, this solves the issue. I was mixing up display and Device.

Thank you.

----- Mail original -----
De: "Romain Vimont" ***@***.***>
À: "Genymobile/scrcpy" ***@***.***>
Cc: "ravotw" ***@***.***>, "Author" ***@***.***>
Envoyé: Vendredi 26 Mars 2021 16:50:29
Objet: Re: [Genymobile/scrcpy] scrcpy is sending the Error: could not parse the device id: xxxxxxxxxxx (#2220)







And when I launch scrcpy --display "id 

You probably want to pass the device id/serial (as listed by adb devices ), not the display id: scrcpy -s xxxxxx 

— 
You are receiving this because you authored the thread. 
Reply to this email directly, view it on GitHub , or unsubscribe . 

-- 
Williams Tovar
+33 6 65 23 25 80
