### ISSUE TITLE
Screen blacked out when trying to add new credit card to Google Express app

### ISSUE THREAD

**Issue by KeronCyst** [Genymobile/scrcpy#223]
Is this a security feature in apps or a scrcpy v1.2 bug (sorry, could not update to 1.3 yet)? The moment it went to the page where you add a new credit card to Google Express, everything on the screen except for Gboard blacked out and remained black.

I could still type from my computer keyboard and see the input on my phone, but the screen stayed black for the entire time until I submitted the data. Then when it returned to the checkout page, it showed again as normal.

**Comment by rom1v** [comment]
The app enables screen protextion. See [FAQ](https://github.com/Genymobile/scrcpy/blob/v1.3/FAQ.md#i-get-a-black-screen-for-some-applications-like-silence).

**Comment by KeronCyst** [comment]
Oops, thanks!
