### ISSUE TITLE
adb push and value 1 problem

### ISSUE THREAD

**Issue by sametceyhan** [Genymobile/scrcpy#2230]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows10 32bit ]
 - scrcpy version: [v1.14 ]
 - installation method: [Windows]
 - device model:general mobile 4g
 - Android version: [android 7]

![Ekran Alıntısı](https://user-images.githubusercontent.com/81798131/113390535-9c368f00-939a-11eb-8a22-60154bf7df22.PNG)

I wonder if how I can solve this problem ?

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#device-unauthorized

**Comment by rom1v** [comment]
When you connect the device to the computer, it should open a popup to authorize USB debugging. You must accept.

**Comment by sametceyhan** [comment]
okey thank you
