### ISSUE TITLE
No console + Windows 10 + Shortcut = Similar to launching app or game

### ISSUE THREAD

**Issue by Vijay-Apple-Dev** [Genymobile/scrcpy#2236]
Great Job guys :)  

As of now, I unable to create windows shorcut. Please make it with windows shortcut, so it is easy to use from talk bar icon as other windows app. Thanks :0

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/issues/2159#issuecomment-801898530 ?

**Comment by agnag** [comment]
right-click scrcpy-noconsole.vbs -> send to -> Desktop (create shortcut)

**Comment by Vijay-Apple-Dev** [comment]
> [#2159 (comment)](https://github.com/Genymobile/scrcpy/issues/2159#issuecomment-801898530) ?

It works as expected after followed your steps. Thanks to the team :)
