### ISSUE TITLE
Trilinear filtering doesn't get enabled when using opengles 3.2

### ISSUE THREAD

**Issue by barfin** [Genymobile/scrcpy#2239]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Arch Linux]
 - scrcpy version: [e.g. 1.17]
 - installation method: [AUR, pacman]
 - device model: Redmi note 9T
 - Android version: [10]

**Describe the bug**
Trilinear filtering doesn't get enabled when using opengles even tho the latest version of opengles (3.2) is available to use it says it needs opengles 2.0 or newer to enable Trilinear filtering

```
[barfin@Barfin-Linux ~]$ scrcpy --render-driver opengles2
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 322.3 MB/s (34930 bytes in 0.000s)
[server] INFO: Device: Xiaomi M2007J22G (Android 10)
INFO: Renderer: opengles2
INFO: OpenGL version: OpenGL ES 3.2 NVIDIA 460.67
WARN: Trilinear filtering disabled (OpenGL 3.0+ or ES 2.0+ required)
INFO: Initial texture: 1080x2336
```

**Comment by rom1v** [comment]
Oh, that's bad. Thank you for the report.

But I can't reproduce:

```bash
$ scrcpy --render-driver=opengles2
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server:...pped. 2.2 MB/s (35294 bytes in 0.015s)
[server] INFO: Device: LGE Nexus 5 (Android 6.0.1)
INFO: Renderer: opengles2
INFO: OpenGL version: OpenGL ES 3.2 Mesa 20.3.5
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x1920
```

Even by forcing your OpengGL version (which is used to detect support):

```diff
diff --git a/app/src/opengl.c b/app/src/opengl.c
index da05c082..b41b8895 100644
--- a/app/src/opengl.c
+++ b/app/src/opengl.c
@@ -20,6 +20,9 @@ sc_opengl_init(struct sc_opengl *gl) {
 
     const char *version = (const char *) gl->GetString(GL_VERSION);
     assert(version);
+
+    version = "OpenGL ES 3.2 NVIDIA 460.67";
+
     gl->version = version;
 
 #define OPENGL_ES_PREFIX "OpenGL ES "
```
:thinking:

**Comment by rom1v** [comment]
Please rebuild with these changes and post the output:
```diff
diff --git a/app/src/opengl.c b/app/src/opengl.c
index da05c082..94a2d4b3 100644
--- a/app/src/opengl.c
+++ b/app/src/opengl.c
@@ -3,6 +3,7 @@
 #include <assert.h>
 #include <stdio.h>
 #include "SDL2/SDL.h"
+#include "util/log.h"
 
 void
 sc_opengl_init(struct sc_opengl *gl) {
@@ -37,6 +38,8 @@ sc_opengl_init(struct sc_opengl *gl) {
         gl->version_major = 0;
         gl->version_minor = 0;
     }
+
+    LOGI("[%s] %d %d.%d\n", gl->version, gl->is_opengles, gl->version_major, gl->version_minor);
 }
 
 bool
```

**Comment by barfin** [comment]
hey sorry idk what's wrong with my nvidia gpu but my pc doesn't boot anymore with it, however the same thing happened with my intel igpu

here's the log with that change
╰─ scrcpy --render-driver opengles2 --verbosity debug
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
DEBUG: Using server: /usr/local/share/scrcpy/scrcpy-server
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 174.1 MB/s (34930 bytes in 0.000s)
DEBUG: Screensaver enabled
[server] INFO: Device: Xiaomi M2007J22G (Android 10)
DEBUG: Starting stream thread
DEBUG: Starting controller thread
DEBUG: Starting receiver thread
INFO: Renderer: opengles2
INFO: [OpenGL ES 3.1 Mesa 21.0.1] 1 3.1
INFO: OpenGL version: OpenGL ES 3.1 Mesa 21.0.1
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x2336
[server] DEBUG: Using encoder: 'OMX.MTK.VIDEO.ENCODER.AVC'
```


and here's the log with latest stable version from aur
```
╰─ scrcpy --render-driver opengles2 --verbosity debug                                               
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
DEBUG: Using server: /usr/share/scrcpy/scrcpy-server
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 347.1 MB/s (34930 bytes in 0.000s)
DEBUG: Screensaver enabled
[server] INFO: Device: Xiaomi M2007J22G (Android 10)
DEBUG: Starting stream thread
DEBUG: Starting controller thread
DEBUG: Starting receiver thread
INFO: Renderer: opengles2
INFO: OpenGL version: OpenGL ES 3.1 Mesa 21.0.1
WARN: Trilinear filtering disabled (OpenGL 3.0+ or ES 2.0+ required)
INFO: Initial texture: 1080x2336
[server] DEBUG: Using encoder: 'OMX.MTK.VIDEO.ENCODER.AVC'
```

**Comment by rom1v** [comment]
> and here's the log with latest stable version from aur

Could you try building current master without any change? The behavior you observe on your version from AUR should not be possible with the v1.17 source code (unless I miss something).

**Comment by barfin** [comment]
> > and here's the log with latest stable version from aur
> 
> Could you try building current master without any change? The behavior you observe on your version from AUR should not be possible with the v1.17 source code (unless I miss something).

okay i built it from master everything seems to be okay 
```
╰─ scrcpy --render-driver opengles2 --verbosity debug
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
DEBUG: Using server: /usr/local/share/scrcpy/scrcpy-server
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 224.0 MB/s (34930 bytes in 0.000s)
DEBUG: Screensaver enabled
[server] INFO: Device: Xiaomi M2007J22G (Android 10)
DEBUG: Starting stream thread
DEBUG: Starting controller thread
DEBUG: Starting receiver thread
INFO: Renderer: opengles2
INFO: OpenGL version: OpenGL ES 3.1 Mesa 21.0.1
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x2336
[server] DEBUG: Using encoder: 'OMX.MTK.VIDEO.ENCODER.AVC'
```

**Comment by rom1v** [comment]
@nvllsvm Do you know why this difference between the AUR package and the master?

**Comment by apandada1** [comment]
I have an old computer running Manjaro, with scrcpy from AUR, `scrcpy` works with the modified command
```
scrcpy --render-driver=opengles2
```

**Comment by barfin** [comment]
fixed somehow
