### ISSUE TITLE
Accentuation prints char without accentuation + char with accentuation

### ISSUE THREAD

**Issue by FrancisTCE** [Genymobile/scrcpy#2241]
**Describe the bug**

When inputting a char with accentuation it prints the char concatenated with the char with accentuation, example below.

à -> aá
â -> aâ

Keyboard Layout: PT-PT

**Environment**
 - OS: Arch Linux
 - scrcpy version: 1.17
 - installation method: pamac
 - device model: Huawei Nova 5T
 - Android version: 10

**Comment by FrancisTCE** [comment]
I believe the issue is on the keyboard read and not on receive since copy-pasting accentuated char has no issue.

**Comment by FrancisTCE** [comment]
I need to correct the description, I can note that it prints the unaccented char and later it prints the char again accentuated meaning it is not printing them concatenated but sequencing them.

**Comment by rom1v** [comment]
```
scrcpy --prefer-text
```

https://github.com/Genymobile/scrcpy#text-injection-preference

**Comment by FrancisTCE** [comment]
thank you
