### ISSUE TITLE
Play sound on android

### ISSUE THREAD

**Issue by dpaniukov** [Genymobile/scrcpy#2244]
Hello, how can I play a sound on Android? Either a sound from the internet or a standard sound will do. I need to send a command from scrcpy to Android and play the sound.
Thank you for any suggestions!

**Comment by LBensman** [comment]
See #14 and https://github.com/rom1v/sndcpy

**Comment by dpaniukov** [comment]
Those discussions are on how to forward the audio from Android to a PC. What I'm asking is how to trigger a sound on the Android from a PC.

**Comment by guanzhangrtk** [comment]
> Those discussions are on how to forward the audio from Android to a PC. What I'm asking is how to trigger a sound on the Android from a PC.

This doesn't sound like it has anything to do with `scrcpy`. You'd probably have better lucky looking up internal Android commands via `adb` or something for what you wanted to do.

**Comment by dpaniukov** [comment]
Got it, thank you for pointing to the right direction!
