### ISSUE TITLE
Does not open

### ISSUE THREAD

**Issue by DarkGamer209788** [Genymobile/scrcpy#2246]
![image](https://user-images.githubusercontent.com/82377601/114379833-a7749080-9bcc-11eb-82a4-f7adc9e965eb.png)
Every time I open the .exe file, it justs quickly closes while displaying the message. I have already tried opening abd.exe but nothing happens too. Can someone please explain how I can fix this because none of the tutorials or videos have this problem.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

**Comment by DarkGamer209788** [comment]
> 
> 
> https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

How exactly do I do that, I opened the scrcpy.exe file and that automatically is typed.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows

(btw, if you run `scrcpy-console.bat`, the console will not be closed on error, that would leave time to leave the error message :wink:)

**Comment by DarkGamer209788** [comment]
I'm just stupid and stuff
Can you please tell me exactly what to do.

**Comment by DarkGamer209788** [comment]
> 
> 
> https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows
> 
> (btw, if you run `scrcpy-console.bat`, the console will not be closed on error, that would leave time to leave the error message 😉)

I'm just stupid and stuff
Can you please tell me exactly what to do.

**Comment by DarkGamer209788** [comment]
I solved the problem. It was really easy. I just had to go to the unzipped scrcpy folder, and in the path area, I clicked it and typed cmd. Then I typed one of the lines that are given in https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception and pressed enter. It worked perfectly fine. I found this resolution at this link.
https://github.com/Genymobile/scrcpy/issues/445
