### ISSUE TITLE
adb connection shut down after rebooting / restart

### ISSUE THREAD

**Issue by hermes6236** [Genymobile/scrcpy#227]
Hi, 

scrcpy is a very good app ,

and the wireless is good,

but wirelesss adb connection shut down after rebooting / restart ,

if the phone is no rooted , we can't keep alive wirelesss adb connection .

the problem has already been mentioned, but I am not enough expert to understand if there is a solution or not

https://www.b4x.com/android/forum/threads/adb-over-wireless-without-usb-cable-at-all.87977/

https://stackoverflow.com/questions/31327839/adb-over-wireless-without-usb-cable-at-all-for-not-rooted-phones

https://stackoverflow.com/questions/26213954/how-to-solve-adb-device-unauthorized-in-android-adb-host-device

**Comment by rom1v** [comment]
Yes, this is a known limitation on Android devices.

**Comment by Nach18** [comment]
And can anything be done with wireless debugging (android 11)?
