### ISSUE TITLE
shutdown in 20 seconds in the scrcpy on the phone Xiaomi Redmi 3s

### ISSUE THREAD

**Issue by xArTeMkAgx** [Genymobile/scrcpy#2271]
I start the program, I scroll through the screen for about 10 - 20 seconds and the program closes

INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
* daemon not running; starting now at tcp:5037
* daemon started successfully
C:\Users\artem\Desktop\Genymobile Screen 1.17\scrcpy-serve... file pushed, 0 skipped. 25.6 MB/s (34930 bytes in 0.001s)
[server] INFO: Device: Xiaomi Redmi 3S (Android 6.0.1)
INFO: Renderer: direct3d
INFO: Initial texture: 720x1280
WARN: Device disconnected 

if you re-run then the adb error even though I installed adb

INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: device offline
ERROR: "adb push" returned with value 1

How to fix it

**Comment by rom1v** [comment]
Your device gets disconnected from `adb`.

You should try with another USB cable / USB port.

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#device-disconnected

**Comment by xArTeMkAgx** [comment]
> Ваше устройство отключается от `adb`.
> 
> Вам следует попробовать использовать другой USB-кабель / USB-порт.
> 
> https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#device-disconnected

thanks for the answer, the reason was in the connector of my phone, if I do not move the cable a lot, then it disconnects
