### ISSUE TITLE
scrcpy + gnirehtet = fail (video in Instagram?)

### ISSUE THREAD

**Issue by svladimirs** [Genymobile/scrcpy#228]
Hello. Thank you for your app!
1) I start gnirehtet and after that scrcpy.
2) Both works normally until Instagram. I roll mouse down and watch same fotos and videos. After several minutes scrcpy crash and gnirehtet write "client disconnected".

**Comment by rom1v** [comment]
You probably lost the `adb` connection. What is the result of `adb device` when this happens?

**Comment by rom1v** [comment]
Are there any relevant logs in `adb logcat`?

**Comment by rom1v** [comment]
>    4d44d2aa7cf4 offline

OK, so for some reason, you lose the `adb` connection to the device.

Maybe you could try with the latest adb (0.40) available since 1 month or 2.

**Comment by svladimirs** [comment]
sorry, not any video.
Mp4 size like 14 Mb ~4 minutes works normal (may be we should wait longer).
But 168 Mb ~55 min - fail about few seconds.

**Comment by rom1v** [comment]
adb or usb probably fail on your machine when the bitrate over usb is too high. Maybe a bug in your usb driver (or in adb).

Could you try the very same scenario on Linux?

**Comment by svladimirs** [comment]
> Could you try the very same scenario on Linux?
No, I have not Linux. It takes too much time to find or install or live-cd...

**Comment by svladimirs** [comment]
scrcpy-win64-v1.4 + gnirehtet-rust-win64-v2.3 (with new adb from scrcpy-win64-v1.4) works perfectly!
Thank you!

**Comment by svladimirs** [comment]
Again this problem.
scrcpy-win64-v1.5 or v1.6 + gnirehtet-rust-win64-v2.3 after few seconds = stop scrcpy and client disconnected in gnirehtet. Latest adb 28.0.1 (September 2018) from https://developer.android.com/studio/releases/platform-tools
I tried scrcpy-win64-v1.4 + gnirehtet-rust-win64-v2.3 = again this problem too.

**Comment by rom1v** [comment]
>     4d44d2aa7cf4    offline

I'm closing since it's an `adb`/USB issue (not directly related to scrcpy or gnirehtet).
