### ISSUE TITLE
libGL error: No matching fbConfigs or visuals found

### ISSUE THREAD

**Issue by rumit311** [Genymobile/scrcpy#2280]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Ubuntu 18]
 - scrcpy version: [e.g. 1.12.1]
**scrcpy** 1.17

**dependencies**:
   - **SDL** 2.0.8
   - **libavcodec** 57.107.100
   - **libavformat** 57.83.100
   - **libavutil** 55.78.100

 - installation method: [snap]
 - device model: Asus
 - Android version: [API 28]

**Describe the bug**
Not sure what happened over the week end, but I get below message in the terminal when try to connect to the device.

```
scrcpy -s 192.168.1.238
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 14.2 MB/s (34930 bytes in 0.002s)
adb: error: more than one device/emulator
ERROR: "adb reverse" returned with value 1
WARN: 'adb reverse' failed, fallback to 'adb forward'
27183
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error:  GLXBadContext
  Request Major code 151 (GLX)
  Request Minor code 6 ()
  Error Serial #112
  Current Serial #111
[server] INFO: Device: Amazon CRGVS (Android 7.1.2)
```

- I can do **adb shell** and other basic adb operations just fine. The android version/OS has not changed since it was working last time.
- I have tried reinstalling scrcpy but that did not help. Also tried rebooting my android device, my ubuntu, adb kill-server, adb start-server etc but none helped.
- Also, followed some articles for this issue such as https://github.com/Genymobile/scrcpy/issues/1071, https://github.com/Genymobile/scrcpy/issues/5, https://github.com/Genymobile/scrcpy/issues/2041, https://www.reddit.com/r/androidapps/comments/acdpdn/cannot_get_scrpy_to_work_with_wireless_adb/ and https://raw.githubusercontent.com/Genymobile/scrcpy/master/FAQ.md and did not help either and hence filing a new issue.

**Comment by rom1v** [comment]
The `adb reverse` error is not a problem (a fallback is used immediately after). The issue is the libGL error, probably related to graphics drivers/permissions.

I suggest you try a non-snap version.

See #624.

**Comment by rumit311** [comment]
Okay https://github.com/Genymobile/scrcpy/issues/624 kind of helped, but not directly. There was a reference to https://forum.snapcraft.io/t/nvidia-beta-drivers-completely-break-snaps/12392/5 in one of the comments (i just went by all of it onee by one) which suggested to run `sudo add-apt-repository ppa:graphics-drivers/ppa` which fixed the issue on my end.
