### ISSUE TITLE
How to run scrcpy without any output on terminal?

### ISSUE THREAD

**Issue by mzfr** [Genymobile/scrcpy#2282]
When we run `scrcpy` we get the following output on the terminal:

```
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
C:\scrcpy\tools\scrcpy-server: 1 file pushed, 0 skipped. 65.5 MB/s (34930 bytes in 0.001s)
[server] INFO: Device: <DEVICE_NAME_HERE>
INFO: Renderer: direct3d
INFO: Initial texture: 1080x1920
```

Because of this, we have to keep that terminal windows open. Now on Linux we could run this in a `tmux` and just put that tmux window in the background. But how can I run scrcpy so that I don't have to keep terminal window open?

**Comment by rom1v** [comment]
There are two separate things: stdout and "detached".

To silent any output:
```bash
scrcpy >& /dev/null
```

But what you want is probably to detach the app from the terminal, not silent the output:
```bash
scrcpy &
```
Then you can just execute `exit` (or <kbd>Ctrl</kbd>+<kbd>d</kbd>) in your terminal.

```bash
scrcpy & exit
```

Or even do not start it from a terminal at all (for example I created a keyboard shortcut in XFCE which starts scrcpy).

**Comment by mzfr** [comment]
@rom1v This is for Linux right? I am asking how to do it in a windows system.

**Comment by rom1v** [comment]
Ah, on Windows, double click ob `scrcpy-noconsole.vbs`.

**Comment by mzfr** [comment]
oh, that works. Thanks a lot :)
