### ISSUE TITLE
Option to remove the title bar

### ISSUE THREAD

**Issue by preIdiot** [Genymobile/scrcpy#2290]
Scrcpy has a title bar on which it shows the connected device name and control buttons. It would be more helpful if I can remove the title bar to see my mobile entire screen at desktop fullscreen.

Thank you 🙂

**Comment by rom1v** [comment]
`scrcpy --fullscreen` or <kbd>Alt</kbd>+<kbd>f</kbd>.

**Comment by ThyZlayer** [comment]
> `scrcpy --fullscreen` or Alt+f.

Is there a possible line of code to make the title bar to disappear after not getting hovered by the mouse for awhile?
