### ISSUE TITLE
scrcpy installed from apt does not work

### ISSUE THREAD

**Issue by dyc3** [Genymobile/scrcpy#2291]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Ubuntu 20.04.2
 - scrcpy version: unknown, unable to view
 - installation method: apt
 - device model: oneplus 6t
 - Android version: 10

**Describe the bug**
scrcpy immediately exits with the following text.

```
scrcpy: error while loading shared libraries: libavformat.so.57: cannot open shared object file: No such file or directory
```

**Comment by rom1v** [comment]
Did you attempt to also install it manually?

```
which scrcpy
```

**Comment by dyc3** [comment]
```
$ which scrcpy
/usr/local/bin/scrcpy
```

I did have it installed manually before, but I assumed it would be overwritten.

**Comment by rom1v** [comment]
The manually installed version is in `/usr/local` while the package installs into `/usr/`, so it's not averwritten.

**Comment by dyc3** [comment]
I see, removing that version fixed it. Thanks!
