### ISSUE TITLE
exit with no error

### ISSUE THREAD

**Issue by suezz** [Genymobile/scrcpy#2295]
- [ X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

tried available codecs and various resolutions

**Environment**
 - OS: Mint
 - scrcpy version: 1.17
 - installation method: snap
 - device model: redmi go
 - Android version: go

**Describe the bug**
exit with no error after info device:

INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
975 KB/s (34930 bytes in 0.034s)
[server] INFO: Device: Xiaomi Redmi Go (Android 8.1.0)

it seem some color related error in log ??
thanks!

[logs.txt](https://github.com/Genymobile/scrcpy/files/6418420/logs.txt)

**Comment by rom1v** [comment]
What is the result with some debug logs enabled?
```
scrcpy -Vdebug
```

**Comment by rom1v** [comment]
Also, does `screenrecord` work?

```
adb shell screenrecord /sdcard/file.mp4
adb pull /sdcard/file.mp4
```

**Comment by suezz** [comment]
scrcpy -Vdebug

INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
DEBUG: Using server: /usr/local/share/scrcpy/scrcpy-server
925 KB/s (34930 bytes in 0.036s)
DEBUG: Screensaver enabled
[server] INFO: Device: Xiaomi Redmi Go (Android 8.1.0)
[server] DEBUG: Controller stopped
[server] DEBUG: Using encoder: 'OMX.qcom.video.encoder.avc'
[server] DEBUG: Screen streaming stopped
[server] DEBUG: Device message sender stopped
DEBUG: Server terminated

and yes, screenrecorder work

**Comment by rom1v** [comment]
> [server] DEBUG: Using encoder: 'OMX.qcom.video.encoder.avc'
> [server] DEBUG: Screen streaming stopped
> [server] DEBUG: Device message sender stopped

Hmmm, it would require some debugging on the device.

If you are comfortable with this, could you find where it leaves the encoding loop?

https://github.com/Genymobile/scrcpy/blob/master/DEVELOP.md#debug-the-server

**Comment by suezz** [comment]
no, above my ability :)

for completeness I'm connecting to an adb server on a remote pc vis ssh tunnel, but I don't think that's the problem ...

**Comment by rom1v** [comment]
Oh, could you try locally, please?

**Comment by suezz** [comment]
ok, not right now, I'll let you know

**Comment by suezz** [comment]
I'm sorry!, my fault
it need a tunnel also for port 27183

**Comment by rom1v** [comment]
Indeed https://github.com/Genymobile/scrcpy#ssh-tunnel

**Comment by suezz** [comment]
yes, I had not seen, I apologize
thanks!
