### ISSUE TITLE
can I use my pc for internet browsing and mirror my mobile phone.. will it work team

### ISSUE THREAD

**Issue by Vijay-Apple-Dev** [Genymobile/scrcpy#2296]
Sorry to ask you..

I have old PC. which doesn't have wifi on it. planning to buy USB wifi adapter. so I can have wifi enabled pc.

I use my mobile for internet connection to pc.

So can i do so...

1. Plug USB wifi apdapter in PC. 
2. Enable mobile data in my phone
3. then enable wifi tethering in my mobile phone,so my mobile internet is shared with pc
4. Can scrcpy work wirelessly?

so I can use my pc for internet browsing and mirror my mobile phone.. will it work team. Thanks for your time and help :)

**Comment by rom1v** [comment]
> will it work

Yes.

I just tested to enable tethering via wifi, I can `adb connect my_device_ip:5555` from my computer connected to the device via wifi and run scrcpy.

**Comment by Vijay-Apple-Dev** [comment]
@rom1v THanks a lot. should I run the command whenever I lunch the scrcpy? or it is one time set up? Thanks for your help..

**Comment by Vijay-Apple-Dev** [comment]
@rom1v i have ordered the usb, will soon test them.. Thanks for your answers :)

**Comment by nawazalwas** [comment]
can I mirror the same device which I use as a wifi hotspot for connecting my pc?
