### ISSUE TITLE
> @rom1v Here is the code. Thanks in advance.

### ISSUE THREAD

**Issue by nwazuo** [Genymobile/scrcpy#2297]
> @rom1v Here is the code. Thanks in advance.
> https://gitlab.com/las2mile/scrcpy-android

Don't working on my devices, when i hit start the app hangs and don't connect.
I tried on android 7, 8 and 10

_Originally posted by @sevenleo in https://github.com/Genymobile/scrcpy/issues/100#issuecomment-803649341_

It's not working here too. Same issue

**Comment by rom1v** [comment]
No need to open a separate issue, just answer there https://github.com/Genymobile/scrcpy/issues/100#issuecomment-803649341
