### ISSUE TITLE
Control Nvidia Shield (Android TV)

### ISSUE THREAD

**Issue by milesian01** [Genymobile/scrcpy#230]
This is possibly an issue, but a feature request all the same.  I'm able to connect to Nvidia Shield TV and get a video feed, but none of my keyboard/mouse actions work.  Please advise, thanks.

**Comment by rom1v** [comment]
Are there any relevant logs in `adb logcat` when you press a key?

**Comment by rom1v** [comment]
I just came across this video: https://www.youtube.com/watch?v=jrkWTl3KHB0
It seems to work…

Do you use a Mac? (could it be #15?)
