### ISSUE TITLE
Scrcpy not opening any window. [ XDG_RUNTIME_DIR not set in the environment ]

### ISSUE THREAD

**Issue by daniarla** [Genymobile/scrcpy#2300]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Fedora 34
 - scrcpy version: 1.17
 - installation method: Corp package [https://copr.fedorainfracloud.org/coprs/zeno/scrcpy/]
 - device model: OnePlus 3T
 - Android version: 10

**Describe the bug**
Upon updating to fedora 34 scrcpy executes normally, but no window is shown.
The terminal output is normal.
```
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 fil...shed. 2.7 MB/s (34930 bytes in 0.012s)
error: XDG_RUNTIME_DIR not set in the environment.
[server] INFO: Device: OnePlus ONEPLUS A3003 (Android 10)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 21.0.3
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x1920
```
I executed scrcpy without any flags.

**Comment by rom1v** [comment]
Not so normal:

> error: XDG_RUNTIME_DIR not set in the environment.

Just for info, did you execute it as root? (you shouldn't).

Could you try another [encoder](https://github.com/Genymobile/scrcpy#encoder)?

**Comment by daniarla** [comment]
Thanks for the repose!

I did not executed as root, I literally just typed : `scrcpy`

 I tried different encoders but with the same result:
```
[fedora34]$ scrcpy --encoder  c2.android.avc.encoder
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed. 2.7 MB/s (34930 bytes in 0.012s)
error: XDG_RUNTIME_DIR not set in the environment.
[server] INFO: Device: OnePlus ONEPLUS A3003 (Android 10)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 21.0.3
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x1920
 ```
```
[fedora34]$ scrcpy --encoder OMX.qcom.video.encoder.avc
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed. 2.6 MB/s (34930 bytes in 0.013s)
error: XDG_RUNTIME_DIR not set in the environment.
[server] INFO: Device: OnePlus ONEPLUS A3003 (Android 10)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 21.0.3
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x1920

```
```
[fedora34]$ scrcpy --encoder OMX.google.h264.encoder
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed. 2.7 MB/s (34930 bytes in 0.012s)
error: XDG_RUNTIME_DIR not set in the environment.
[server] INFO: Device: OnePlus ONEPLUS A3003 (Android 10)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 21.0.3
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x1920
```

**Comment by rom1v** [comment]
Try:

```
scrcpy -no-display --record file.mkv
```
Then after few seconds <kbd>Ctrl</kbd>+<kbd>c</kbd> to stop.

Is the file correctly recorded and play correctly?

**Comment by daniarla** [comment]
That seems to work, the file is a bit weird as it was terminated unexpectedly, but works.

**Comment by daniarla** [comment]
Seems like someone had a similar problem in https://github.com/Genymobile/scrcpy/issues/1896#issuecomment-724235895
And they fixed it with 

> export DISPLAY=:1

But I don't known how to set it or even if it even related

**Comment by rom1v** [comment]
> I don't known how to set it

```bash
export DISPLAY=:1
scrcpy
```

(also try with `export DISPLAY=:0`)
