### ISSUE TITLE
Help required with documentation to create node app

### ISSUE THREAD

**Issue by krishtoautomate** [Genymobile/scrcpy#2306]
scrcpy forwarding video is port in h264 format is understood. didn't get how touches are sent --

Which method or api is sending touches?
is touches sent to same port video is sent?
Which request body the scrcpy jar accepts for touch or keyboard events.

Thank you

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/DEVELOP.md#input-events-injection

> is touches sent to same port video is sent?

It's on another socket: https://github.com/Genymobile/scrcpy/blob/644a5ef14ae9559ca72365c37d8f6b63edbdbd6f/server/src/main/java/com/genymobile/scrcpy/DesktopConnection.java#L54

See ec71a3f66ab48c2fdd1728753acc09edbd4db570.

> Which request body the scrcpy jar accepts for touch or keyboard events.

https://github.com/Genymobile/scrcpy/issues/673#issuecomment-516360374

**Comment by tulasikrishan89** [comment]
where i do i find latest scrcpy-server.jar file?
