### ISSUE TITLE
Why your adb shell cmd execute so fast?

### ISSUE THREAD

**Issue by SSSANTON** [Genymobile/scrcpy#231]
While I execute an adb comand like("adb shell input tap 100 100") in Command prompt window, it almost have 1 second delay in my phone.

So could you tell me the key to improve the execution speed? Thanks.

**Comment by rom1v** [comment]
> Why your adb shell cmd execute so fast?

Because I don't use `adb shell` commands for input events :wink:

When you execute `adb shell input ...`:
 1. it executes a new process locally
 2. it connects to the local adb daemon
 3. the request is forwarded to the adb server on the device
 4. a shell is started
 5. the [`input`](https://android.googlesource.com/platform/frameworks/base/+/oreo-release/cmds/input/input) command script is executed
 6. this starts a new java process to execute the `public static void main()` method of [`Input.java`](https://android.googlesource.com/platform/frameworks/base/+/oreo-release/cmds/input/src/com/android/commands/input/Input.java)
 7. the arguments are parsed
 8. the events are injected by a simple method call (e.g. [`injectKeyEvent()`](https://android.googlesource.com/platform/frameworks/base/+/oreo-release/cmds/input/src/com/android/commands/input/Input.java#270))

All of this is executed for every `adb shell input ...` command. The main delay is step 6 (starting the Java process).

In _scrcpy_, only 1 Java process is [started](https://github.com/Genymobile/scrcpy/blob/v1.3/app/src/server.c#L86-L96) (the server) for the whole session. This process opens a [socket](https://github.com/Genymobile/scrcpy/blob/v1.3/server/src/main/java/com/genymobile/scrcpy/DesktopConnection.java#L46-L60) to communicate with the client.

The client [sends](https://github.com/Genymobile/scrcpy/blob/v1.3/app/src/controller.c#L44-L52) every input event over this socket (using a [custom](https://github.com/Genymobile/scrcpy/blob/v1.3/app/src/controlevent.c#L28) protocol). The server [receives and handle](https://github.com/Genymobile/scrcpy/blob/v1.3/server/src/main/java/com/genymobile/scrcpy/EventController.java#L65-L86) these events immediately.

**Comment by SSSANTON** [comment]
@rom1v 
Thanks! I will learn more details from your achievement.

**Comment by MemoryAndDream** [comment]
> > Why your adb shell cmd execute so fast?
> 
> Because I don't use `adb shell` commands for input events 
> 
> When you execute `adb shell input ...`:
> 
> 1. it executes a new process locally
> 2. it connects to the local adb daemon
> 3. the request is forwarded to the adb server on the device
> 4. a shell is started
> 5. the [`input`](https://android.googlesource.com/platform/frameworks/base/+/oreo-release/cmds/input/input) command script is executed
> 6. this starts a new java process to execute the `public static void main()` method of [`Input.java`](https://android.googlesource.com/platform/frameworks/base/+/oreo-release/cmds/input/src/com/android/commands/input/Input.java)
> 7. the arguments are parsed
> 8. the events are injected by a simple method call (e.g. [`injectKeyEvent()`](https://android.googlesource.com/platform/frameworks/base/+/oreo-release/cmds/input/src/com/android/commands/input/Input.java#270))
> 
> All of this is executed for every `adb shell input ...` command. The main delay is step 6 (starting the Java process).
> 
> In _scrcpy_, only 1 Java process is [started](https://github.com/Genymobile/scrcpy/blob/v1.3/app/src/server.c#L86-L96) (the server) for the whole session. This process opens a [socket](https://github.com/Genymobile/scrcpy/blob/v1.3/server/src/main/java/com/genymobile/scrcpy/DesktopConnection.java#L46-L60) to communicate with the client.
> 
> The client [sends](https://github.com/Genymobile/scrcpy/blob/v1.3/app/src/controller.c#L44-L52) every input event over this socket (using a [custom](https://github.com/Genymobile/scrcpy/blob/v1.3/app/src/controlevent.c#L28) protocol). The server [receives and handle](https://github.com/Genymobile/scrcpy/blob/v1.3/server/src/main/java/com/genymobile/scrcpy/EventController.java#L65-L86) these events immediately.

So how can I use ADB command to reuse the java process  for the whole session ? I am using python to execute adb command and I search for a long time to solve the delay problem with ADB.

**Comment by npes87184** [comment]
> > > Why your adb shell cmd execute so fast?
> > 
> > 
> > Because I don't use `adb shell` commands for input events
> > When you execute `adb shell input ...`:
> > 
> > 1. it executes a new process locally
> > 2. it connects to the local adb daemon
> > 3. the request is forwarded to the adb server on the device
> > 4. a shell is started
> > 5. the [`input`](https://android.googlesource.com/platform/frameworks/base/+/oreo-release/cmds/input/input) command script is executed
> > 6. this starts a new java process to execute the `public static void main()` method of [`Input.java`](https://android.googlesource.com/platform/frameworks/base/+/oreo-release/cmds/input/src/com/android/commands/input/Input.java)
> > 7. the arguments are parsed
> > 8. the events are injected by a simple method call (e.g. [`injectKeyEvent()`](https://android.googlesource.com/platform/frameworks/base/+/oreo-release/cmds/input/src/com/android/commands/input/Input.java#270))
> > 
> > All of this is executed for every `adb shell input ...` command. The main delay is step 6 (starting the Java process).
> > In _scrcpy_, only 1 Java process is [started](https://github.com/Genymobile/scrcpy/blob/v1.3/app/src/server.c#L86-L96) (the server) for the whole session. This process opens a [socket](https://github.com/Genymobile/scrcpy/blob/v1.3/server/src/main/java/com/genymobile/scrcpy/DesktopConnection.java#L46-L60) to communicate with the client.
> > The client [sends](https://github.com/Genymobile/scrcpy/blob/v1.3/app/src/controller.c#L44-L52) every input event over this socket (using a [custom](https://github.com/Genymobile/scrcpy/blob/v1.3/app/src/controlevent.c#L28) protocol). The server [receives and handle](https://github.com/Genymobile/scrcpy/blob/v1.3/server/src/main/java/com/genymobile/scrcpy/EventController.java#L65-L86) these events immediately.
> 
> So how can I use ADB command to reuse the java process for the whole session ? I am using python to execute adb command and I search for a long time to solve the delay problem with ADB.

You should use `adb forward` or `adb reverse` to create a tunnel between PC and Android. After it, create a process in Android which always live, listen to this tunnel and handle the request from PC.

**Comment by eetrukhan** [comment]
> > > > Why your adb shell cmd execute so fast?
> > > 
> > > 
> > > Because I don't use `adb shell` commands for input events
> > > When you execute `adb shell input ...`:
> > > 
> > > 1. it executes a new process locally
> > > 2. it connects to the local adb daemon
> > > 3. the request is forwarded to the adb server on the device
> > > 4. a shell is started
> > > 5. the [`input`](https://android.googlesource.com/platform/frameworks/base/+/oreo-release/cmds/input/input) command script is executed
> > > 6. this starts a new java process to execute the `public static void main()` method of [`Input.java`](https://android.googlesource.com/platform/frameworks/base/+/oreo-release/cmds/input/src/com/android/commands/input/Input.java)
> > > 7. the arguments are parsed
> > > 8. the events are injected by a simple method call (e.g. [`injectKeyEvent()`](https://android.googlesource.com/platform/frameworks/base/+/oreo-release/cmds/input/src/com/android/commands/input/Input.java#270))
> > > 
> > > All of this is executed for every `adb shell input ...` command. The main delay is step 6 (starting the Java process).
> > > In _scrcpy_, only 1 Java process is [started](https://github.com/Genymobile/scrcpy/blob/v1.3/app/src/server.c#L86-L96) (the server) for the whole session. This process opens a [socket](https://github.com/Genymobile/scrcpy/blob/v1.3/server/src/main/java/com/genymobile/scrcpy/DesktopConnection.java#L46-L60) to communicate with the client.
> > > The client [sends](https://github.com/Genymobile/scrcpy/blob/v1.3/app/src/controller.c#L44-L52) every input event over this socket (using a [custom](https://github.com/Genymobile/scrcpy/blob/v1.3/app/src/controlevent.c#L28) protocol). The server [receives and handle](https://github.com/Genymobile/scrcpy/blob/v1.3/server/src/main/java/com/genymobile/scrcpy/EventController.java#L65-L86) these events immediately.
> > 
> > 
> > So how can I use ADB command to reuse the java process for the whole session ? I am using python to execute adb command and I search for a long time to solve the delay problem with ADB.
> 
> You can use `adb forward` or `adb reverse` to create a tunnel between PC and Android. After it, create a process in Android which always live, listen to this tunnel and handle the request from PC.

Сan you say more specifically, please, how to start new process by adb exactly?

**Comment by deniznehlyadyuk** [comment]
> > > > Why your adb shell cmd execute so fast?
> > > 
> > > 
> > > Because I don't use `adb shell` commands for input events
> > > When you execute `adb shell input ...`:
> > > 
> > > 1. it executes a new process locally
> > > 2. it connects to the local adb daemon
> > > 3. the request is forwarded to the adb server on the device
> > > 4. a shell is started
> > > 5. the [`input`](https://android.googlesource.com/platform/frameworks/base/+/oreo-release/cmds/input/input) command script is executed
> > > 6. this starts a new java process to execute the `public static void main()` method of [`Input.java`](https://android.googlesource.com/platform/frameworks/base/+/oreo-release/cmds/input/src/com/android/commands/input/Input.java)
> > > 7. the arguments are parsed
> > > 8. the events are injected by a simple method call (e.g. [`injectKeyEvent()`](https://android.googlesource.com/platform/frameworks/base/+/oreo-release/cmds/input/src/com/android/commands/input/Input.java#270))
> > > 
> > > All of this is executed for every `adb shell input ...` command. The main delay is step 6 (starting the Java process).
> > > In _scrcpy_, only 1 Java process is [started](https://github.com/Genymobile/scrcpy/blob/v1.3/app/src/server.c#L86-L96) (the server) for the whole session. This process opens a [socket](https://github.com/Genymobile/scrcpy/blob/v1.3/server/src/main/java/com/genymobile/scrcpy/DesktopConnection.java#L46-L60) to communicate with the client.
> > > The client [sends](https://github.com/Genymobile/scrcpy/blob/v1.3/app/src/controller.c#L44-L52) every input event over this socket (using a [custom](https://github.com/Genymobile/scrcpy/blob/v1.3/app/src/controlevent.c#L28) protocol). The server [receives and handle](https://github.com/Genymobile/scrcpy/blob/v1.3/server/src/main/java/com/genymobile/scrcpy/EventController.java#L65-L86) these events immediately.
> > 
> > 
> > So how can I use ADB command to reuse the java process for the whole session ? I am using python to execute adb command and I search for a long time to solve the delay problem with ADB.
> 
> You can use `adb forward` or `adb reverse` to create a tunnel between PC and Android. After it, create a process in Android which always live, listen to this tunnel and handle the request from PC.

Can you please share code? Or some referances?
