### ISSUE TITLE
java.io.ioexception connection refused

### ISSUE THREAD

**Issue by dudufcb1** [Genymobile/scrcpy#2314]
I have a weird problem when i try to connect, is it random somedays it works, some other it doesn't. I formatted the phone and nothing changed, so i think the issue is in my pc.

i would like to paste the content of error, but i can't run scrcpy.exe into the cmd window because when i do pops like 4 windows very fast and the one in the image is the end, which is closed very fast.

Im trying to connect by USB. after this issue started to happen, i tried another software like vysor or powermirror and they works with no issues, but i like scrcpy and i want to know if you guys can help me.

![image](https://user-images.githubusercontent.com/84204579/118322653-193e4380-b4c5-11eb-8c57-212a1fcb787d.png)

**Comment by rom1v** [comment]
> i would like to paste the content of error, but i can't run scrcpy.exe into the cmd window

Double-click on `scrcpy-console.bat`.

For your conneection refused error, it might be related to some firewall blocking the connection.

**Comment by dudufcb1** [comment]
> > i would like to paste the content of error, but i can't run scrcpy.exe into the cmd window
> 
> Double-click on `scrcpy-console.bat`.
> 
> For your conneection refused error, it might be related to some firewall blocking the connection.

Also didn't work, indeed now i can run scrcpy.exe and works, i deleted adb file from the inside of its folder, and works, but i can't run without cmd close, idk why.
