### ISSUE TITLE
Unable to use command codes.

### ISSUE THREAD

**Issue by zkhan3-github** [Genymobile/scrcpy#2319]
Hi, I just installed the latest versions of Scrcpy & Sndcpy today. Both are working perfectly except the commands.
As you have provided many commands to configure resolution, bitrate, FPS, touch dots.

When I open Scrcpy two windows open, 1- Scrcpy phone screen, 2- cmd terminal window.
I tried using the command codes in this terminal window but none of them actually changes anything. ASAP I press enter after writing command it just take and no message shown and prompt to write next command.

I tried using these commands from main terminal cmd windows of the folder path but that also didn't worked!
Whether I enter right command or wrong it's just the same result (it doesn't do anything just prompt to write next one).
I've attached a picture after entering a command.
Edit:- Image removed! (Privacy reason).

Can you give me an idea or solution about these problem.
I will be really thankful to you!
Waiting for your response!

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows

**Comment by zkhan3-github** [comment]
Haha!! I am so fool and confused in a small thing.
I was pushing the commands through the application's opened terminal window till yet instead of sending them through another terminal window.

Anyway, it's working perfectly know!
Thank you so much for the help! :)

**Comment by rom1v** [comment]
> I was pushing the commands through the application's opened terminal window till yet instead of sending them through another terminal window.

You're not the first one to do that, that's the reason why I wrote the FAQ entry :)
