### ISSUE TITLE
Camera not shared to PC

### ISSUE THREAD

**Issue by srirangan** [Genymobile/scrcpy#232]
I discovered scrcpy while looking for an Android alternative for iPhone + QuickTime sharing of phone screen on laptop.

Things worked great until I realized that my phone's camera is not being displayed on the laptop. Is this out of scope for this project, or is it a bug?

**Comment by srirangan** [comment]
PS: Great work btw, loved the simplicity of it!

**Comment by rom1v** [comment]
> Things worked great until I realized that my phone's camera is not being displayed on the laptop.

_scrcpy_ only mirrors the screen, not the camera (unless you open your camera app on your screen :wink:)

> Is this out of scope for this project

It is not planned, but technically it should not be too difficult. What's the use case?

**Comment by srirangan** [comment]
The company I work for has an SDK that replaces the camera with one that provides hints and tips as users take photos of IDs, documents etc.

My specific use-case here is to create webcasts where I use the SDK to create a sample app and demo a scan of a European ID document.

**Comment by rom1v** [comment]
In this use-case, isn't the camera displayed on the device screen?

**Comment by srirangan** [comment]
The camera launched via the sample app is displayed on my phone, but it's not displayed on my laptop. 

The default camera app shows up fine on the laptop though.

**Comment by rom1v** [comment]
> The camera launched via the sample app is displayed on my phone, but it's not displayed on my laptop.

Do you see a black screen in _scrcpy_ instead?

Did you enable [`FLAG_SECURE`](https://developer.android.com/reference/android/view/WindowManager.LayoutParams#FLAG_SECURE) for this window?

**Comment by srirangan** [comment]
Yes, I see a black screen.

Quite possible. Let me check with the relevant dev team.

**Comment by srirangan** [comment]
That was it actually. Sorry for the trouble and thanks for the quick response.

**Comment by dedosmedia** [comment]
> It is not planned, but technically it should not be too difficult (to display the camera instead of the device screen). What's the use case?

Any hint how could I achieve it? I know is not into your priorities so I will try to do it by myself.

This is for an interactive installation on a Museum. My phone is USB connected to a PC, I need to display the Front Camera onto the PC's display, at the same time I will have another app running on the phone where the user will be interacting with.

Thanks in advanced
