### ISSUE TITLE
Could not execute adb push on windows

### ISSUE THREAD

**Issue by igorpk10** [Genymobile/scrcpy#2323]
Hello guys, for many mounths i have used this app, but after cleaned my notebook i received this error on run scrcpy.

My SO is Windows 10.
My adb is working.

INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
ERROR: Failed to execute: [C:\Users\igor.costa\AppData\Local\Android\Sdk\platform-tools], [push], ["C:\scrcpy-win64-v1.16\scrcpy-server"], ["/data/local/tmp/scrcpy-server.jar"]
ERROR: Could not execute "adb push"
Press any key to continue...

Someone can help me??

**Comment by rom1v** [comment]
You set your `ADB` variable to `C:\Users\igor.costa\AppData\Local\Android\Sdk\platform-tools`.
You probably want `C:\Users\igor.costa\AppData\Local\Android\Sdk\platform-tools\adb.exe` instead.

**Comment by igorpk10** [comment]
Thanks bro, a conflict was really going on. When i removed the patch to old adb variable its worked.
