### ISSUE TITLE
Scrcpy crashes after building branch android12_nosecure

### ISSUE THREAD

**Issue by axtloss** [Genymobile/scrcpy#2324]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS:Arch Linux
 - scrcpy version: 1.17 branch android12_nosecure
 - installation method: manual build
 - device model: google pixel 4a
 - Android version: 12 beta1

scrcpy crashes with error "[server] ERROR: Exception on thread Thread[main,5,main]"

I had the issues mentioned in https://github.com/Genymobile/scrcpy/issues/2129 so I built the android12_nosecure branch, build worked without any issues. I used the prebuilt server also posted in that issue
```
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
x/server/scrcpy-server: 1 file pushed, 0 skipped. 151.8 MB/s (35730 bytes in 0.000s)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: Expecting 16 parameters
	at com.genymobile.scrcpy.Server.createOptions(Server.java:140)
	at com.genymobile.scrcpy.Server.main(Server.java:251)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
WARN: Killing the server...
```

**Comment by rom1v** [comment]
The branch matching the prebuilt server posted there is `nosecureflag_quickfix`, not `android12_nosecure`: https://github.com/Genymobile/scrcpy/issues/2129#issuecomment-826542365

**Comment by axtloss** [comment]
Ah, thanks for the quick reply, must've missed that
