### ISSUE TITLE
Error executing 'scrcpy' after a successful build and install on Debian

### ISSUE THREAD

**Issue by santi-gonzalez** [Genymobile/scrcpy#233]
Thanks for this awesome program. I've been using it extenssively at work under Windows, Mac and Ubuntu, always flawlesly. However, I've got a new laptop recently with a Debian distribution, and it doesn't work there.

This is what `/proc/version` gives:
```
Linux version 4.9.0-7-amd64 (debian-kernel@lists.debian.org) (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) ) #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13)
```

I've been able to prepare everything as usual, but when I try to run the program (either by `./run x` or using the installed `scrcpy`) I get an error of kind:
```
exec: No such file or directory
ERROR: "adb push" returned with value 1
```

What I've done and tried:

- I've installed all dependencies with `apt-get` successfully.

- I've built the server with Mason and Ninja successfully (I've also tried using the provided built server).

- I've (also) installed the app successfully with `sudo ninja install`.

- I have `adb` set to PATH, so I can invoke `adb devices` and get a single device connected, for example.

- I can manually push the compiled `scrcpy-server.jar` using `adb push scrcpy-server.jar /data/local/tmp`.

Any suggestion would be appreciated.

Thank you very much!

**Comment by rom1v** [comment]
What os the result of:

    which adb
    echo "$PATH"

(from the terminal where scrcpy fails)

**Comment by santi-gonzalez** [comment]
Hi! The comment you made between parentheses rang the bell. Certainly it was a bad configuration related to different shells. I've just been able to get it to work, finally. Thank you very much! :smiley:
