### ISSUE TITLE
Resizing the screen mirroring window

### ISSUE THREAD

**Issue by Mobasheera** [Genymobile/scrcpy#2334]
- [ ] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

I'm always frustrated when I have to resize the screen mirroring window every time to fit my desktop display

It would be awesome to get an option to remember the layout of the window just like in the layout tab of Comand Prompt under the properties option

![image](https://user-images.githubusercontent.com/83943245/119258145-14287500-bbe6-11eb-9cf8-bb4dd24ef1c8.png)
How it is (default):
![Screenshot (439)](https://user-images.githubusercontent.com/83943245/119258226-6a95b380-bbe6-11eb-862e-28be37e1104b.png)
How I like it:
![Screenshot (440)](https://user-images.githubusercontent.com/83943245/119258240-7d0fed00-bbe6-11eb-8cc6-9ef46f19eb47.png)

**Comment by rom1v** [comment]
Did you try these options: https://github.com/Genymobile/scrcpy#position-and-size ?

**Comment by Mobasheera** [comment]
Thank you. Can you please tell me where to enter these commands? I'm a newbie.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows

**Comment by Mobasheera** [comment]
Thank you so much. :)
