### ISSUE TITLE
Scrcpy coredumps multiple times before connecting (TCP/IP)

### ISSUE THREAD

**Issue by ajgringo619** [Genymobile/scrcpy#2344]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Linux Mint 20.1]
 - scrcpy version: [1.17]
 - installation method: [manual build]
 - device model: Samsung A11
 - Android version: [11]

**Describe the bug**
I have (2) scripts that start **scrcpy** - one for USB (which always works) and one for TCP/IP. Here is the TCP/IP version:
```#!/usr/bin/bash

adb tcpip 5555
adb connect samsung-phone:5555
scrcpy -s samsung-phone:5555 --bit-rate 2m --max-fps 5 --prefer-text --window-width 475 --window-height 1000 --window-title 'Samsung A11 [TCP/IP]'
```

Here is the output when the script fails (and coredumps, even though it connects):
```restarting in TCP mode port: 5555
connected to samsung-phone:5555
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: device 'samsung-phone:5555' not found
ERROR: "adb push" returned with value 1
free(): double free detected in tcache 2
```

Sometimes, the connection doesn't even complete:
```restarting in TCP mode port: 5555
unable to connect to samsung-phone:5555: Connection refused
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: device 'samsung-phone:5555' not found
ERROR: "adb push" returned with value 1
free(): double free detected in tcache 2
```

There is no consistency with how many times I have to retry before the connection completes. By the way, this was also happening with Android 10 (just got the upgrade a couple of days ago) and with LM's stock v1.12 version.

**Comment by rom1v** [comment]
For the double free() on error, could you test the `dev` branch, which contains this commit: https://github.com/Genymobile/scrcpy/commit/1b9dcce23c8f52aa1ba97fe30fad83930c60578d ?

**Comment by rom1v** [comment]
You must wait a bit after `adb connect`, it seems the device is not listed immediately in `adb devices`?

**Comment by ajgringo619** [comment]
OK, we're getting closer. The dev branch fixed the coredump, but now the server won't start (USB or TCP/IP):
```error: more than one device/emulator
already connected to samsung-phone:5555
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 1.4 MB/s (34930 bytes in 0.024s)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: Expecting 15 parameters
	at com.genymobile.scrcpy.Server.createOptions(Server.java:140)
	at com.genymobile.scrcpy.Server.main(Server.java:248)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:409)
WARN: Killing the server...
```
I also had to install another package - libavdevice-dev - before I could complete the build. Do I need a different version of the pre-built server as well?

**Comment by rom1v** [comment]
Yes, there is a prebuilt server only for releases, not for `dev` branch (it would always change).

If you just want the commit fixing the double free, just cherry-pick it on `master`, so that you can use the prebuilt server of the latest release.

**Comment by rom1v** [comment]
> I also had to install another package - libavdevice-dev - before I could complete the build

Yes: #2268

**Comment by ajgringo619** [comment]
That's what I did (already had the v1.17 pre-built server downloaded). Not sure what else to try now.

**Comment by rom1v** [comment]
The error message suggest you didn't build the `master` branch (with possibly the fix cherry-picked from `dev`).

**Comment by ajgringo619** [comment]
Yep - exactly what I did. I'll give this another try.

**Comment by ajgringo619** [comment]
Can't build it with just updating the server.c file; keep getting missing header errors:

```$ ninja -Cx
ninja: Entering directory `x'
[1/2] Compiling C object 'app/a172ced@@scrcpy@exe/src_server.c.o'.
FAILED: app/a172ced@@scrcpy@exe/src_server.c.o 
cc -Iapp/a172ced@@scrcpy@exe -Iapp -I../app -I../app/src -I/usr/include/x86_64-linux-gnu -I/usr/include/SDL2 -flto -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c11 -O3 -D_REENTRANT -MD -MQ 'app/a172ced@@scrcpy@exe/src_server.c.o' -MF 'app/a172ced@@scrcpy@exe/src_server.c.o.d' -o 'app/a172ced@@scrcpy@exe/src_server.c.o' -c ../app/src/server.c
../app/src/server.c:11:10: fatal error: adb.h: No such file or directory
   11 | #include "adb.h"
      |          ^~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
```
Then this:
```$ ninja -Cx
ninja: Entering directory `x'
[1/2] Compiling C object 'app/a172ced@@scrcpy@exe/src_server.c.o'.
FAILED: app/a172ced@@scrcpy@exe/src_server.c.o 
cc -Iapp/a172ced@@scrcpy@exe -Iapp -I../app -I../app/src -I/usr/include/x86_64-linux-gnu -I/usr/include/SDL2 -flto -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c11 -O3 -D_REENTRANT -MD -MQ 'app/a172ced@@scrcpy@exe/src_server.c.o' -MF 'app/a172ced@@scrcpy@exe/src_server.c.o.d' -o 'app/a172ced@@scrcpy@exe/src_server.c.o' -c ../app/src/server.c
In file included from ../app/src/server.c:11:
../app/src/adb.h:9:10: fatal error: util/process.h: No such file or directory
    9 | #include "util/process.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
```

I'll try this again later on this evening.

**Comment by rom1v** [comment]
On `dev`, `adb.h` and `util/process.h` don't exist, and `server.c` don't include them.

On `master`, they exist, and `server.c` include them. Clean up your local worktree.

**Comment by ajgringo619** [comment]
Hmmm...I just re-downloaded the master branch (using git clone https://github.com/Genymobile/scrcpy.git) and neither header file exists. What am I doing wrong?

**Comment by rom1v** [comment]
Sorry, I reversed `dev` and `master`: they exist on `dev`, but not on `master`. But anyway, the `server.c` from the right branch includes the right files. Everything builds correctly on both branches.

**Comment by ajgringo619** [comment]
OK - success! I decided to build everything from the `dev` branch (including the server); now it works as advertised. Thanks for all the help!
