### ISSUE TITLE
video is only five seconds

### ISSUE THREAD

**Issue by xxxxxxH** [Genymobile/scrcpy#2345]
pls help me ths

**Comment by rom1v** [comment]
What is the output in the console?

**Comment by xxxxxxH** [comment]
INFO: Recording started to matroska file: c:\users\v_xhan~1\appdata\local\temp\tmpex6_pz.mkv   like this

**Comment by xxxxxxH** [comment]
![4s](https://user-images.githubusercontent.com/20770054/120157242-62142d00-c225-11eb-80a1-26f3e23d6f4b.png)
a lot of this   just 4s or 5s

**Comment by rom1v** [comment]
Coild you post the video?

Does it work with another player?

#2346?

**Comment by xxxxxxH** [comment]
https://user-images.githubusercontent.com/20770054/120179911-c3e09100-c23d-11eb-8c87-e584066954ba.mp4

**Comment by xxxxxxH** [comment]
I haven't tried any other player

**Comment by xxxxxxH** [comment]
I don’t think it’s the player’s problem

**Comment by rom1v** [comment]
(Your file is a matroska, why did you name it `.mp4`?)

Anyway, the file plays correctly in VLC or mpv (for example).

**Comment by xxxxxxH** [comment]
The original file is .mkv and copied to another path

**Comment by xxxxxxH** [comment]
I changed a player and it can play, but the progress bar doesn’t show anything
![5s](https://user-images.githubusercontent.com/20770054/120181366-867d0300-c23f-11eb-99df-9b6f9a1ea246.png)

**Comment by xxxxxxH** [comment]
I changed another player. After 1 second, the progress bar did not move. After 3 seconds, it became 4 seconds.  
From Figure 1 to Figure 2 directly, the screen is no problem, but the progress bar is stuck.
![微信图片_20210531184541](https://user-images.githubusercontent.com/20770054/120182133-947f5380-c240-11eb-910a-04e2a182a781.png)
![微信图片_20210531184553](https://user-images.githubusercontent.com/20770054/120182143-977a4400-c240-11eb-8bf3-145e88d14621.png)

**Comment by rom1v** [comment]
Recording only produces a new frame when the screen changes. If nothing changes for seconds, no new frames are produced, so the framerate is very variable. This confuses some players. For example, VLC3 progress bar does not progress, but VLC4 (in development), does work correctly.

**Comment by xxxxxxH** [comment]
I know what you mean   thank u
