### ISSUE TITLE
Could it install on Chrome OS by "crew install scrcpy" ?

### ISSUE THREAD

**Issue by 1457384613gh** [Genymobile/scrcpy#2347]
Could it install on Chrome OS by `crew intall scrcpy` ?
If only there would be `crew intall scrcpy` by [Chromebrew](https://github.com/skycocker/chromebrew) on Chrome OS !
If only it could work well on Chromebook !
Package manager is [Chromebrew](https://github.com/skycocker/chromebrew)
![Screenshot 2021-05-28 18.12.02.png](https://user-images.githubusercontent.com/69227436/119968666-4e2bb980-bfe0-11eb-8e98-100a0fcb74ff.png)

**Comment by Lucaacer** [comment]
Install scrcpy in crostini, you just have to add the proper repo, since it's not in Buster.

I did it some time ago, but I can't remember exactly, though there should be an old post of mine floating around.

**Comment by Lucaacer** [comment]
Here it is https://github.com/Genymobile/scrcpy/issues/1176
