### ISSUE TITLE
Support -H or -L like adb to specify hostname

### ISSUE THREAD

**Issue by jeanlego** [Genymobile/scrcpy#2348]
## Setup

- The device is connected via usb (no internet access possible)
- I am running an adb server on a remote machine
- I am getting an adb shell on my dev machine using  `adb -H <hostname> shell` succesfully.

```
[ android ] -- usb --- [ adb server ] ---  Lan  --- [ dev machine ]
```

## Request 

I was wondering if there was anyway to specify the hostname of the adb server to reproduce the same behavior without requiring an SSH tunnel with port fowarding as others have used.

```
 -H         name of adb server host [default=localhost]
 -L SOCKET  listen on given socket for adb server [default=tcp:localhost:5037]
```

**Comment by eadmaster** [comment]
why this was closed?

**Comment by jeanlego** [comment]
The tunnel does work the same, so, while this is still valid, I don't think there is much value to it after thinking it through.
I don't know how much work it would be to connect to a specified host vs localhost.
I'd be willing to give it a shot if someone knows it wouldn't be too too involved

**Comment by rom1v** [comment]
You can do the equivalent of `-H` with `ADB_SERVER_SOCKET`. See https://github.com/Genymobile/scrcpy/issues/144#issuecomment-387765711

**Comment by jeanlego** [comment]
ah! this is awesome thanks :)
