### ISSUE TITLE
Troubleshooting why some events are not being registered on Android device

### ISSUE THREAD

**Issue by guanzhangrtk** [Genymobile/scrcpy#2350]
Hi, I was trying to check to see if scrcpy provides an option to log interactions with Android device, such as taps, swipes etc. on the console. The reason I ask is that some clicks/taps are not registered and I'm not sure the issue is with the Android device, my computer or scrcpy.

On my MacBook Pro I have tap to click enabled on my Trackpad and some times when I tap it's completely missed so I need to tap it a few times in order for it to register, however if I physically click on the trackpad I believe it's working, so somehow I'm not sure why taps are not registered.

Also, I was wondering would you consider adding "Discussions" to GitHub? This is mostly a question for other scrcpy users as it's not technically an issue (yet) nor a feature request (could already have existing workarounds).

Thanks for any feedback!

**Comment by Lucaacer** [comment]
It will be a little bit slow bit will workshop  https://github.com/Genymobile/scrcpy/issues/733

**Comment by guanzhangrtk** [comment]
I tested qtscrcpy and it actually shows the coordinates when you tap and I discovered that taps are indeed missed. It's quite possible that I tap "too quickly" so while qt/scrcpy registered the tap, it wasn't held long enough for the app to register it as a "click".

I'm not exactly sure how this should be solved though.

**Comment by rom1v** [comment]
You could add some logs in this function:

https://github.com/Genymobile/scrcpy/blob/d3d955f67b92d08bbee21bebce40fa072eea38f6/app/src/input_manager.c#L596-L605

> I tested qtscrcpy and it actually shows the coordinates when you tap

qtscrcpy is a totally separate project, and I guess it receives input events via Qt (while scrcpy receives it via SDL). So if you have the problem with both, then I think the issue is either on your system or hardware.

**Comment by guanzhangrtk** [comment]
@rom1v I think #2410 is probably the same feature request as this, in which case this ticket can probably be closed, thanks! Would still be nice to be able to have "Discussions" though :-)

**Comment by guanzhangrtk** [comment]
@rom1v With v1.18, I am able to see verbose logging of events and I found something interesting. I'm not sure if it's normal but for some reason I can trigger 0ms delay events as follows:

```
2021-06-23 19:02:44.409 scrcpy[3838:62736] VERBOSE: input: touch [id=mouse] down position=604,390 pressure=1 buttons=000001
2021-06-23 19:02:44.409 scrcpy[3838:62736] VERBOSE: input: touch [id=mouse] up   position=604,390 pressure=0 buttons=000001
```

This particular event was not registered as a tap, whereas the follow is registered, and it has 6ms delay between events:

```
2021-06-23 19:14:26.113 scrcpy[3838:62736] VERBOSE: input: touch [id=mouse] down position=256,461 pressure=1 buttons=000001
2021-06-23 19:14:26.119 scrcpy[3838:62736] VERBOSE: input: touch [id=mouse] up   position=256,461 pressure=0 buttons=000001
```
Does this help troubleshoot why some events are not being registered? Thanks!

**Comment by rom1v** [comment]
Maybe your device does not generate a tap when down and up are too close.

Could you test another Android device on the same computer?

**Comment by guanzhangrtk** [comment]
Confirmed issue to be on Android device end, closing.
