### ISSUE TITLE
Error: Failed to download resource "theora"

### ISSUE THREAD

**Issue by Luiz-Otavio-Dorigon** [Genymobile/scrcpy#2353]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [macOS 10.13.6]
 - scrcpy version: [1.17]
 - installation method: [brew]
 - device model:
 - Android version:

**Describe the bug**
Whenever I try to install scrcpy using the ```brew install scrcpy``` command the following error occurs

```
curl: (35) error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Error: Failed to download resource "theora"
Download failed: https://downloads.xiph.org/releases/theora/libtheora-1.1.1.tar.bz2
```

**Comment by rom1v** [comment]
This is a brew issue I guess. See #2247.

**Comment by Luiz-Otavio-Dorigon** [comment]
> This is a brew issue I guess. See #2247.

Unfortunately that didn't fix it, the problem still persists.

**Comment by rom1v** [comment]
You could try with macports: https://github.com/Genymobile/scrcpy#macos

**Comment by Luiz-Otavio-Dorigon** [comment]
> You could try with macports: https://github.com/Genymobile/scrcpy#macos

Ok, it worked.
