### ISSUE TITLE
HATA YARDIM

### ISSUE THREAD

**Issue by UysalMuzaffer** [Genymobile/scrcpy#2354]
TR: Merhaba, aşağıdaki hatayı almaktayım. Çok araştırdım fakat yapamadım.
EN: Hello, I am located here. I searched a lot and couldn't.

![image](https://user-images.githubusercontent.com/85217193/120436597-c9e28900-c387-11eb-929b-748f942586ad.png)

**Comment by rom1v** [comment]
In English, please.

And https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception
