### ISSUE TITLE
Mouse control not working on Poco X3 Pro

### ISSUE THREAD

**Issue by momokaze** [Genymobile/scrcpy#2363]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Android 11, MIUI 12
 - scrcpy version: 1.17 (Latest)
 - installation method: Window Release
 - device model: Poco X3 Pro
 - Android version: 11

**Describe the bug**
Mouse control not working on Poco X3 Pro

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work
