### ISSUE TITLE
Poderia gravar, também, o áudio do dispositivo...

### ISSUE THREAD

**Issue by MatheusTotal** [Genymobile/scrcpy#2365]
- [ ] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
Gravar áudio interno e Externo do dispositivo, funcionando quase como uma placa de captura...

**Describe the solution you'd like**
Simplismente gravar e transmitir o áudio.

**Describe alternatives you've considered**
Interno ou externo, qualquer um.

**Additional context**
Seria muito útil para transmissões...

**Comment by rom1v** [comment]
In English, please.

> áudio

See #14. And https://github.com/Genymobile/scrcpy#audio-forwarding
