### ISSUE TITLE
Want to embed scrcpy in .net

### ISSUE THREAD

**Issue by VarunSaiTeja** [Genymobile/scrcpy#237]
i want to use your scrcpy in my vb.net project to mirror mobile
how can i do it?
please help me

**Comment by rom1v** [comment]
No idea, sorry. And I don't know vb.net at all.

**Comment by VarunSaiTeja** [comment]
What about c#

**Comment by johnsie** [comment]
I think you could probably port the client from Java to C#. The current version uses adb so you'd need a version of adb that works with .net

This might be useful. https://www.xda-developers.com/cooladb-adb-client-c-net-projects/

I don't think this project would take quite a but of work and would take a reasonably skilled programmer.

**Comment by VarunSaiTeja** [comment]
> I think you could probably port most of the client code from Java to C#. However the current version uses adb, so you'd need a version of adb that works with .net
> 
> This might be useful. https://www.xda-developers.com/cooladb-adb-client-c-net-projects/
> 
> I don't think this project would take quite a but of work and would take a reasonably/highly skilled programmer.

No this was cilent
We can use without this cilent also
The thing require is to embed his scrcpy in my win form app
