### ISSUE TITLE
Android 12 is not working

### ISSUE THREAD

**Issue by jiduqingqian** [Genymobile/scrcpy#2372]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Android 
 - scrcpy version: 1.17.1
 - installation method: brew
 - device model: Pixel 3a
 - Android version: 12(s)

**Describe the bug**
![image](https://user-images.githubusercontent.com/9583596/121285456-01fe4480-c911-11eb-91fe-170a8089a66c.png)

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
#2129
