### ISSUE TITLE
Backspace and Delete key in physical keyboard don't work (NumLock)

### ISSUE THREAD

**Issue by binhodev** [Genymobile/scrcpy#2373]
- [ x ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ x ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [ Ubuntu 20.04 ]
 - scrcpy version: [ 1.17 ]
 - installation method: [ snap ]
 - device model: SM-G930F
 - Android version: [ Android 8.1.0 ]

**Describe the bug**

Hi everyone,
I have a problem running scrcpy on Ubuntu 20.04 (on notebook), can't work the keys Backspace and Delete in physical keyboard can't remove any characters in device. Clipboard also not working, using MacOS scrcpy works flawless.

**Comment by binhodev** [comment]
Closed, i'm found the problem.

**Comment by rom1v** [comment]
What was the problem?

**Comment by binhodev** [comment]
> What was the problem?
Sorry, I thought it worked, when I came back the problem persists. I need reopen.

**Comment by rom1v** [comment]
If you position your cursor after a character to delete, then execute:

```
adb shell input keyevent DEL
```

Does it delete the character?

**Comment by binhodev** [comment]
> If you position your cursor after a character to delete, then execute:
> 
> ```
> adb shell input keyevent DEL
> ```
> 
> Does it delete the character?

Yes, can delete.

**Comment by rom1v** [comment]
> installation method: [ snap ]

Could you test a non-snap version?

https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple

**Comment by binhodev** [comment]
> > installation method: [ snap ]
> 
> Could you test a non-snap version?
> 
> https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple

Oki, I'll test now, a moment please.

**Comment by binhodev** [comment]
> > installation method: [ snap ]
> 
> Could you test a non-snap version?
> 
> https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple

Same problem, can't delete character,

**Comment by rom1v** [comment]
To debug, please apply this change on master, then rebuild:

```diff
diff --git a/app/src/input_manager.c b/app/src/input_manager.c
index bab85660..c368682c 100644
--- a/app/src/input_manager.c
+++ b/app/src/input_manager.c
@@ -370,6 +370,8 @@ input_manager_process_key(struct input_manager *im,
     bool shift = event->keysym.mod & KMOD_SHIFT;
     bool repeat = event->repeat;
 
+    LOGI("event: %x %x %x\n", (int) keycode, (unsigned) event->type, (unsigned) event->keysym.mod);
+
     // The shortcut modifier is pressed
     if (smod) {
         int action = down ? ACTION_DOWN : ACTION_UP;
```

Run the modified version. When you press backspace, what does it print in the console?

It should print something like:

```
INFO: event: 8 300 0
INFO: event: 8 301 0
```

**Comment by binhodev** [comment]
> To debug, please apply this change on master, then rebuild:
> 
> ```diff
> diff --git a/app/src/input_manager.c b/app/src/input_manager.c
> index bab85660..c368682c 100644
> --- a/app/src/input_manager.c
> +++ b/app/src/input_manager.c
> @@ -370,6 +370,8 @@ input_manager_process_key(struct input_manager *im,
>      bool shift = event->keysym.mod & KMOD_SHIFT;
>      bool repeat = event->repeat;
>  
> +    LOGI("event: %x %x %x\n", (int) keycode, (unsigned) event->type, (unsigned) event->keysym.mod);
> +
>      // The shortcut modifier is pressed
>      if (smod) {
>          int action = down ? ACTION_DOWN : ACTION_UP;
> ```
> 
> Run the modified version. When you press backspace, what does it print in the console?
> 
> It should print something like:
> 
> ```
> INFO: event: 8 300 0
> INFO: event: 8 301 0
> ```

Printed:
INFO: event: 8 300 1000
INFO: event: 8 301 1000

**Comment by rom1v** [comment]
What if you disable your NUM key?

**Comment by binhodev** [comment]
> What if you disable your NumLock key?

WoW it worked! Crazy... What happiness?

**Comment by rom1v** [comment]
When injecting a key to the device, scrcpy also injects the _metastate_ (the set of active modifiers, among <kbd>Ctrl</kbd>, <kbd>Shift</kbd>, but also <kbd>CapsLock</kbd>, <kbd>NumLock</kbd> and others). This is useful so that Android injects the correct key (for example, if <kbd>CapsLock</kbd> is enabled, pressing `KEYCODE_A` generates `A`, otherwise it generates `a`). I'm pretty sure that <kbd>NumLock</kbd> is useful, even if I have no concrete example in mind.

In `INFO: event: 8 300 1000`, 1000 is [`KMOD_NUM`](https://github.com/libsdl-org/SDL/blob/56e96254c23105d7c7657f32d50661435d838b6a/include/SDL_keycode.h#L338). It is converted to the Android version of this modifier (`AMETA_NUM_LOCK_ON`):

https://github.com/Genymobile/scrcpy/blob/d3d955f67b92d08bbee21bebce40fa072eea38f6/app/src/event_converter.c#L63-L65

But it seems that on your device, enabling the NumLock modifier prevent some keys to work as expected. This is a bug on your device, I could not reproduce (even on a device quite similar: `samsung SM-A320FL (Android 8.0.0)`).

**Comment by rom1v** [comment]
If you have an OTG cable and a USB keyboard, I would be curious if the problem also occurs with a physical keyboard (I think it would not).

**Comment by binhodev** [comment]
> When injecting a key to the device, scrcpy also injects the _metastate_ (the set of active modifiers, among Ctrl, Shift, but also CapsLock, NumLock and others). This is useful so that Android injects the correct key (for example, if CapsLock is enabled, pressing `KEYCODE_A` generates `A`, otherwise it generates `a`). I'm pretty sure that NumLock is useful to differentiate the value generated by some keys, even if I have no concrete example in mind.
> 
> In `INFO: event: 8 300 1000`, 1000 is [`KMOD_NUM`](https://github.com/libsdl-org/SDL/blob/56e96254c23105d7c7657f32d50661435d838b6a/include/SDL_keycode.h#L338). It is converted to the Android version of this modifier (`AMETA_NUM_LOCK_ON`):
> 
> https://github.com/Genymobile/scrcpy/blob/d3d955f67b92d08bbee21bebce40fa072eea38f6/app/src/event_converter.c#L63-L65

Hmm, very interesting that. 

> 
> But it seems that on your device, enabling the NumLock modifier prevents some keys to work as expected. This is a bug on your device, I could not reproduce (even on a device quite similar: `samsung SM-A320FL (Android 8.0.0)`).

It is, it may be, strange that this did not happen with MacOS using the same device.

**Comment by binhodev** [comment]
> If you have an OTG cable and a USB keyboard, I would be curious if the problem also occurs with a physical keyboard plugged directly in the device (I think it would not).

I have, I'll test and comment here soon.

**Comment by binhodev** [comment]
> If you have an OTG cable and a USB keyboard, I would be curious if the problem also occurs with a physical keyboard plugged directly in the device (I think it would not).

I have, I'll test and comment here soon.

**Comment by rom1v** [comment]
> It is, it may be, strange that this did not happen with MacOS using the same device.

What are the logs with [this change](https://github.com/Genymobile/scrcpy/issues/2373#issuecomment-857838671) on macOS?
