### ISSUE TITLE
how can i sync audio to pc (windows)

### ISSUE THREAD

**Issue by VarunSaiTeja** [Genymobile/scrcpy#238]
I am using windows in my pc
when i mirroring my mobile with tool
its awesome speed , no lag (wired)
but no audio in pc, its coming from mobile
any idea or suggestion how can i also stream audio in my pc (windows)

**Comment by rom1v** [comment]
See https://github.com/Genymobile/scrcpy/issues/14.

TL;DR: not working on windows.

You can plug a cable (jack) instead.
