### ISSUE TITLE
"This app can't run on your pc"

### ISSUE THREAD

**Issue by Roshrach** [Genymobile/scrcpy#2380]
I'm new, so I apologize if I did something wrong. 
I just downloaded the zip file, ran adb.exe and scrcpy.exe, both didn't run, I restarted my laptop, ran both files again, still didn't run but this time, scrcpy.exe's cmd window opened for less than a split second but something was written there and it closes too fast for me to take a screenshot. so I went to FAQ , and I tried to open both using cmd.exe, then this happened 
![image](https://user-images.githubusercontent.com/78736351/121803815-d616f200-cc75-11eb-8544-fe54c29e1753.png)

**Comment by rom1v** [comment]
> If you are seeing This app can't run on your PC error, this is probably because you're trying to run 64-bit version of a certain application on 32-bit version of Windows 10. ... Another solution is to switch to a 64-bit version of Windows 10.

You should try the 32-bit version. Take `scrcpy-win32-v1.17.zip` from https://github.com/Genymobile/scrcpy/releases

**Comment by Roshrach** [comment]
i got 64-bit ver of windows. it worked now. i just clicked scrcpy-noconsole.vbs. weird actually
also, i have a new question, where do i put this ?

![image](https://user-images.githubusercontent.com/78736351/121804802-bb934780-cc7a-11eb-9259-ed386059f71e.png)

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows

**Comment by Roshrach** [comment]
![image](https://user-images.githubusercontent.com/78736351/121805087-298c3e80-cc7c-11eb-934c-664fe75ac281.png)
this one's supposed to do something, right?

**Comment by Roshrach** [comment]
aight this one's a new issue. gonna make a new thread
