### ISSUE TITLE
Cannot compile the server with the given instructions anymore.

### ISSUE THREAD

**Issue by brunoais** [Genymobile/scrcpy#2382]
Since commit `84f17fdeab518cbe9f9c1a5fdf7dc50981c01806`. Cannot compile with the given instructions anymore.
Apparently, now there's a new requirement `libavdevice-dev` to install not mentioned in `BUILD.md`.
I didn't make a PR yet because, even then, I can't compile.
Apparently the version of `libavformat` is incompatible.

```
../../scrcpy/app/src/v4l2_sink.c: In function 'sc_v4l2_sink_open':
../../scrcpy/app/src/v4l2_sink.c:183:19: error: 'AVFormatContext {aka struct AVFormatContext}' has no member named 'url'
     vs->format_ctx->url = strdup(vs->device_name);
                   ^~
../../scrcpy/app/src/v4l2_sink.c:184:24: error: 'AVFormatContext {aka struct AVFormatContext}' has no member named 'url'
     if (!vs->format_ctx->url) {
                        ^~
```
I'll try to figure out how this can be worked with.
I'm leaving here in case someone has an idea.

**Comment by rom1v** [comment]
Thank you for the report.

Could you please test branch [`fix2382`](https://github.com/Genymobile/scrcpy/commits/fix2382)?

> Since commit 84f17fdeab518cbe9f9c1a5fdf7dc50981c01806.

Probably since d39161f7539b9d335e38385ffff5c3b4c21c7122 in fact.

> Apparently, now there's a new requirement `libavdevice-dev` to install

Yes.

> not mentioned in BUILD.md

On `dev`, it is mentioned: 8fb5715740e52bcb2ba8d4bac1e53f4ef76ef688.

**Comment by rom1v** [comment]
Oops, no, the fix is obviously wrong for older version. Will fix it later.

**Comment by rom1v** [comment]
Fixed: [`fix2382.2`](https://github.com/Genymobile/scrcpy/commits/fix2382.2)

**Comment by brunoais** [comment]
Meanwhile, I finished a workaround. I was coming to tell now. I'll keep it just in case.
BTW, Yep. [`fix2382.2`](https://github.com/Genymobile/scrcpy/commits/fix2382.2) fixed!
I'll keep my local workaround around, though inactive, just in case. 

Thank you!

**Comment by rom1v** [comment]
> Yep. `fix2382.2` fixed!

Thanks, pushed to `dev`.
