### ISSUE TITLE
Mirrored screen doesn't resize after increasing the border of app to fit the border of app

### ISSUE THREAD

**Issue by kazemcodes** [Genymobile/scrcpy#2389]
- [ ✓] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ✓] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: windows 10
 - scrcpy version: 1.17
 - device model: Xiaomi mi 9t pro
 - Android version: 10 and 11

**Describe the bug**
I can't increase the mirrored screen of my phone after a certain screen aspect which is still small for me ,the extra screen become black and mirror screen doesn't resize to fit the scrcpy app screen . I also tried the same thing with Samsung A51 android 11 and I reached the same result

![Screenshot (30)](https://user-images.githubusercontent.com/76521159/121952519-95040800-cd71-11eb-8429-b88d6770e6cb.png)

**Comment by rom1v** [comment]
Please post a screenshot, and the console logs.

**Comment by kazemcodes** [comment]
Sorry , I didn't Explain well Here is my screen shot of my screen, if possible make the app ,delete these black screen section
 after resizing the app border
![Screenshot (30)](https://user-images.githubusercontent.com/76521159/121952799-f4621800-cd71-11eb-9475-62cbad0e7e56.png)

**Comment by rom1v** [comment]
<kbd>Alt</kbd>+<kbd>w</kbd>, or double-click on the black borders.

https://github.com/Genymobile/scrcpy#shortcuts

**Comment by kazemcodes** [comment]
> Please post a screenshot, and the console logs.



> To remove the borders, Alt+w, or double-click on the black borders.
> 
> https://github.com/Genymobile/scrcpy#shortcuts
> 
> EDIT: in fact you want to fill that space? But this would not respect the aspect ratio, so scrcpy does not do that.

Thanks for your answer , it would be better if that ratio was changeable

**Comment by rom1v** [comment]
> if that ratio was changeable

But that would distort the device :confused:
