### ISSUE TITLE
black mobile screen

### ISSUE THREAD

**Issue by aianshume** [Genymobile/scrcpy#2392]
**Environment**
 - OS: [xubuntu 20.04 lts]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [apt]
 - device model: smasung
 - Android version: [e.g. 8]

**Describe the bug**
its actually i problem of graphics driver, i have opengl version 1.4 installed in my system and the scrcpy works fine but letter i update the opengl gaphics driver to OpenGL version string: 1.4 Mesa 21.2.0-devel (git-639579d 2021-06-15 focal-oibaf-ppa) to improve some gaming experience but when i run scrcpy command the mobile mirrored successfully but the screen is black completely and the touch works fine

![Screenshot_2021-06-15_21-09-36](https://user-images.githubusercontent.com/68537640/122083294-5ed09200-ce1e-11eb-8a2e-54839e6ca586.png)

**Comment by rom1v** [comment]
In any application on the device? Or just some of them?

Is it black if you record and play the file?

```
scrcpy --record file.mp4
```

If yes, is it black if you record with screenrecord?

```
adb shell screenrecord /sdcard/file.mp4
adb pull /sdcard/file.mp4
```

**Comment by aianshume** [comment]
no its not black when i record

**Comment by aianshume** [comment]
in recording screen is working fine

**Comment by aianshume** [comment]
but when i reopen the scrcpy the screen remain black

**Comment by rom1v** [comment]
Then as you said, it's a driver issue. :/

**Comment by aianshume** [comment]
yes it's driver issue but how i fix that

**Comment by aianshume** [comment]
thanks to snapcraft.io the problem is there is `scrcpy 1.12` install in my system and then i update the `graphic driver` and its create problem the the simple solution for this problem is to update the `scrcpy` version to latest stable `scrcpy 1.17` and its work

**Comment by Practicalbutterfly5** [comment]
Sorry to reopen the issue. But I am facing the exact same issue. 

* Black Screen of scrcpy window
* Touch Works
* `scrcpy --record file.mp4` work perfectly and is able to record screen
 
I am on Android 12 and have installed scrcpy on arch32 with `yam -S scrcpy`
```INFO: Renderer: opengl
INFO: OpenGL version: 1.4 Mesa 21.2.1
WARN: Trilinear filtering disabled (OpenGL 3.0+ or ES 2.0+ required)
INFO: Initial texture: 256x512
WARN: Killing the server...
```
