### ISSUE TITLE
Pinch-to-zoom feature not working

### ISSUE THREAD

**Issue by raisen** [Genymobile/scrcpy#2396]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Ubuntu 20.04
 - scrcpy version: 1.12.1
 - installation method: apt
 - device model: Pixel 5
 - Android version: 11

**Describe the bug**
The pinch to zoom feature isn't working on my system. I hold ctrl while pressing the left-click button, move the mouse, but scrcpy seems to act like ctrl isn't being pressed.
I am also using a Mac keyboard with the alt <> command keys switched, but I tried without switching the keys and same behavior happens.
I'm not sure how to troubleshoot this further so please let me know how/if I can get more info from scrcpy to figure out what's going on.

**Comment by rom1v** [comment]
> scrcpy version: 1.12.1

Pinch-to-zoom has been added in v1.16.
