### ISSUE TITLE
Add option to use wireless and with usb cable

### ISSUE THREAD

**Issue by Minionguyjpro** [Genymobile/scrcpy#2399]
Add an option to use remote wireless and with usb cable like once.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy#wireless

**Comment by Minionguyjpro** [comment]
But it dont work if i put cable in

**Comment by rom1v** [comment]
Please don't just say "don't work", explain what you observe, what are the error messages in the console, etc.

**Comment by r00p35h** [comment]
Adb connect IP:5555 connection timed out

**Comment by r00p35h** [comment]
Adb connect IP:5555 no route to ip

**Comment by fusionneur** [comment]
Just updated ethernally script which facilitates wireless mirroring
https://github.com/fusionneur/ethernally

Let me know if you encounter any issue. Thank you

**Comment by Minionguyjpro** [comment]
Waiti think i done it
