### ISSUE TITLE
After upgrading into the 1.18, the server version (1.17) does not match the client (1.18)

### ISSUE THREAD

**Issue by Onemaeus97** [Genymobile/scrcpy#2409]
Hi, after upgraded into the newest version of 1.18 (which i build under instructions of [https://github.com/Genymobile/scrcpy/blob/master/BUILD.md](url). I have a java exception of the server version (1.17) does not match the client (1.18):

INFO: scrcpy 1.18 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server:...shed. 3.0 MB/s (34930 bytes in 0.011s)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: The server version (1.17) does not match the client (1.18)
	at com.genymobile.scrcpy.Server.createOptions(Server.java:134)
	at com.genymobile.scrcpy.Server.main(Server.java:248)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338)
WARN: Killing the server...

Can somebody tell me what i might have done wrong during the process? Thanks!

**Comment by rom1v** [comment]
Did you build using the [prebuilt server](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#option-2-use-prebuilt-server)? If so, you need the new prebuilt server v1.18 too :)

**Comment by rom1v** [comment]
Oh, I forgot to update `install_release.sh` :facepalm:

**Comment by rom1v** [comment]
Fixed, please `git pull` and retry :wink:

**Comment by Onemaeus97** [comment]
Thank you buddy! @rom1v
