### ISSUE TITLE
Add package to winget

### ISSUE THREAD

**Issue by DestroyerXyz** [Genymobile/scrcpy#2413]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Create and submit a package to Winget (Microsoft's new package manager for Windows) [community repo](https://github.com/microsoft/winget-pkgs)

**Comment by rom1v** [comment]
Duplicate of #1444.
