### ISSUE TITLE
Increasing Latency

### ISSUE THREAD

**Issue by marshalsim96** [Genymobile/scrcpy#2417]
Is there a way to increase latency? Weird question but mainly because I dont need low latency, but instead smooth gameplay with minimal lag spikes. Since I will be streaming, I can always adjust audio to sync in OBS afterwards.

Thanks.

**Comment by rom1v** [comment]
No, there is no setting to increase latency, there is no buffering at all (to get the smallest latency possible).

> instead smooth gameplay with minimal lag spikes

Do you use it over USB?

On OBS, do you capture the scrcpy window (which might add more lags), or the new [V4L2 feature](https://github.com/Genymobile/scrcpy#v4l2loopback) (on Linux)?

Note that if you record (`scrcpy --record file.mkv`), the timestamps recorded are the one captured on the device, so there is no jitter (but not appropriate for streaming, unless you manage to play the recorded `mkv` file few seconds after recording started).

**Comment by marshalsim96** [comment]
I typically use scrcpy with usb, works extremely well over USB. Unfortunately I do not own nor use Linux, so I cant try this V4L2 feature.

But ever since buying my new phone, it does not have an audio jack. So I have been using a bluetooth audio receiver, which apparently has a big latency issue. sndcpy sadly does not work too for my game.

So the idea is to prioritize audio latency, using the type-c port for audio, and wireless for screen sharing, in theory anyways. kinda like PTZ cameras.

But no biggie if this does not work, its just something I will have to get used too. Thanks!

**Comment by rom1v** [comment]
Do you also notice "lag spikes" if you just run scrcpy without OBS? Or is it just when OBS is capturing the window?

Are there "lag spikes" in the recorded file? (`scrcpy --record file.mkv`) (it would mean that the lag is on the device itself)

> Unfortunately I do not own nor use Linux

You could try a LiveUSB ([Ubuntu](https://ubuntu.com/download/desktop/thank-you?version=21.04&architecture=amd64) for example)) :wink:

> But no biggie if this does not work

The feature might make sense (it has already been requested btw), but currently there is no way to add buffering.

**Comment by marshalsim96** [comment]
> Do you also notice "lag spikes" if you just run scrcpy without OBS? Or is it just when OBS is capturing the window?
Yup, there is noticeable lag spikes with scrcpy running without OBS. At lower bitrate and resolution too albeit lesser.

> Are there "lag spikes" in the recorded file? (`scrcpy --record file.mkv`) (it would mean that the lag is on the device itself)
No spikes in the recorded file.

> The feature might make sense (it has already been requested btw), but currently there is no way to add buffering.
Ah I see. Probably best to consider a phone with a headphone jack, much easier fix in this situation haha.

**Comment by rom1v** [comment]
> Ah I see. Probably best to consider a phone with a headphone jack, much easier fix in this situation haha.

I don't understand, video jitter is independent of audio, so why would a phone with a headphone jack would fix your issue?

**Comment by marshalsim96** [comment]
> I don't understand, video jitter is independent of audio, so why would a phone with a headphone jack would fix your issue?

Ah. Then I could use scrcpy via type-c, which would eliminate any lag spikes if it was wireless. And also fix the Bluetooth latency issue, since I can use the headphone jack for audio line-in into my PC. All would be in-sync without sacrificing visual quality. 

Since my current phone does not have headphone jack, the type-c can only be used for scrcpy or audio. So it's dealing with either Bluetooth latency or lag spikes. Hopefully that makes sense.

**Comment by rom1v** [comment]
> Then I could use scrcpy via type-c, which would eliminate any lag spikes

Oh, so currently over USB, it works well without this issue for you?

**Comment by marshalsim96** [comment]
Yes, works really good via USB. Probably should have clarified that part in my original post. My bad haha, totally missed that part out.

**Comment by SLAPaper** [comment]
Same feature request (ability to manual add latency) but with different reason:
I'm using Bluetooth Audio Receiver (a Windows 10 App) to forward the audio to PC, while using Scrcpy to stream the video, but Bluetooth audio has a significantly more latency (maybe ~200ms or more) than Scrcpy (even over TCP/IP), so I often experience strange slightly video-audio out-of-sync.

Implementing a configurable setting to add latency would be much help, so that I can manual sync the video and audio.

**Comment by rom1v** [comment]
I plan to implement this feature in v1.19.

This avoids the slight "laggy" effect due to incorrect presentation timing (on video playback for example). This is important for streaming quality.

**Comment by rom1v** [comment]
Implemented by #2464

**Comment by rom1v** [comment]
Merged into `dev`.
