### ISSUE TITLE
lock-video-orientation flag doesn't recognize arguments

### ISSUE THREAD

**Issue by aojea** [Genymobile/scrcpy#2424]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Fedora 34
 - scrcpy version: 
 ```
 scrcpy -v
scrcpy 1.18

dependencies:
 - SDL 2.0.14
 - libavcodec 58.134.100
 - libavformat 58.76.100
 - libavutil 56.70.100
 - libavdevice 58.13.100
```
 - installation method: 
 ```
sudo rpm -qa | grep scrc
scrcpy-1.18-1.fc34.x86_64
```
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**
Since latest upgrade, version 1.18, the flag `--lock-video-orientation` stopped accepting arguments. It does work without any argument.

```
$ scrcpy --lock-video-orientation initial 
ERROR: Unexpected additional argument: initial
$ scrcpy --lock-video-orientation 0
ERROR: Unexpected additional argument: 0

```

**Comment by aojea** [comment]
duh, https://github.com/Genymobile/scrcpy/commit/f76fe2c0d4847d0e40d8708f97591abf3fa22ea5
The syntax has changed :smile:

**Comment by rom1v** [comment]
Yes that's a quirk of `getopt_long()`.
