### ISSUE TITLE
Unable to use --no-display --turn-screen-off at the same time

### ISSUE THREAD

**Issue by mukheshpugal** [Genymobile/scrcpy#2426]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Ubuntu 18.04
 - scrcpy version: 1.18
 - installation method: linux-brew
 - device model: ONEPLUS A6003
 - Android version: 11

**Describe the bug**

I'm trying to stream the video to a v4l2 loopback device. Everything seems to work fine except when using  the options `--no-display` `--turn-screen-off` at the same. There is no windowed display as expected, however the phone screen does not get turned off.

On using the options one at a time everything works as expected.

I've tried it with another device (PANASONIC ELUGA Turbo (Android 5.1)). Still the same issue persists.

**Comment by rom1v** [comment]
Indeed, the controller is not started if there is no display:

https://github.com/Genymobile/scrcpy/blob/ab12b6c981d62aac2c4c86c5436378970723cc38/app/src/scrcpy.c#L346-L357

The reason was that initially controls could only be initiated by input events (captured by the window). This might be changed now.

**Comment by mukheshpugal** [comment]
Will I be able to run an adb command from another terminal to turn the screen off? If I can, please let me know of the command.

**Comment by rom1v** [comment]
Unfortunately, in the current state, no.

**Comment by mukheshpugal** [comment]
Alright. Looking forward for the fix! Thanks.

**Comment by rom1v** [comment]
Out of curiosity, what is the use case?

If your device screen is off and you pass `--no-display`, you can't control it at all?

**Comment by mukheshpugal** [comment]
Well, there's this game called Mortal Kombat mobile and in the game, you can recieve extra coins by logging in every hour and completing a few tasks. I want to automate it so that I can run it through the night. Obviously I don't want the phone display to be on all the time.

Since I'll be running the controlling program headlessly on an rpi, I don't want a window.

With the screen off, I am able to sent inputs using the `adb shell input`  command independently.

**Comment by mukheshpugal** [comment]
I just realised that the backlight is still on on my non amoled device while using `--turn-screen-off`. Is this normal?

**Comment by rom1v** [comment]
Fixed on `dev`.

> I just realised that the backlight is still on on my non amoled device while using `--turn-screen-off`. Is this normal?

Scrcpy just request the device to change the "power mode", how the action is done is device-dependent.

**Comment by mukheshpugal** [comment]
Great!
