### ISSUE TITLE
Control phone using keyboard

### ISSUE THREAD

**Issue by MesterPerfect** [Genymobile/scrcpy#2427]
**Is your feature request related to a problem? Please describe.**

Hello
I am a blind user
I used your program and it's great
But I can't control my phone with the keyboard
I have to use the mouse
Is there a possibility to control my phone by keyboard?

**Describe the solution you'd like**
I need to be able to control my phone with the keyboard
Example when I access phone display window from computer I want if I press a shortcut from the keyboard that takes me inside the phone and then I can move inside the phone using the computer keyboard 

**Describe alternatives you've considered**

**Additional context**

**Comment by rom1v** [comment]
Hi,

Key inputs are forwarded to the device, so if you press <kbd>TAB</kbd>, you should be able to navigate (using <kbd>TAB</kbd>/<kbd>Shift</kbd>+<kbd>TAB</kbd> or key arrows).

**Comment by MesterPerfect** [comment]
This is really successful
But I can't go back to the previous screen or go back to the main screen

**Comment by rom1v** [comment]
<kbd>Alt</kbd>+<kbd>b<kbd> for BACK, <kbd>Alt</kbd>+<kbd>h<kbd> for HOME.

**Comment by MesterPerfect** [comment]
> Alt+b for BACK, Alt+h for HOME.

Thank you
That's okay
Is there a possibility to see all the shortcuts that can be used?

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy#shortcuts

**Comment by MesterPerfect** [comment]
> https://github.com/Genymobile/scrcpy#shortcuts
thank you

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy#shortcuts
