### ISSUE TITLE
How to achieve multiply control?

### ISSUE THREAD

**Issue by SSSANTON** [Genymobile/scrcpy#243]
I want to use scrcpy to play a shooting type mobile game in PC.While I finished mapping the controls from SDL2 events to this game(Mainly by modifying the file inputmanager.c). I found out it can't send different events in same time, for example mouse move event will block the key event, key event will break the mouse move event. I need to tap two or more different location points in same time. 

So does SDL2 support multiply control and which part of source code should I change to make it support multiply control,  just the client or both the client and the server?

**Comment by rom1v** [comment]
> I want to use scrcpy to play a shooting type mobile game in PC.

Just for info, did you try the `rawkeyevents` branch (https://github.com/Genymobile/scrcpy/issues/87)?

> I found out it can't send different events in same time, for example mouse move event will block the key event, key event will break the mouse move event.

Sending an event is instantaneous, so a key event should not block a mouse event and vice versa. For exemple, here is a possible sequence of events:
 - press key Return
 - move mouse to 100,100
 - press mouse button Left
 - release key Return
 - move mouse to 105,102
 - release mouse button Left

> I need to tap two or more different location points in same time.

Multitouch is not supported (https://github.com/Genymobile/scrcpy/issues/59).

> which part of source code should I change to make it support multiply control

You need to capture the SDL events (https://github.com/Genymobile/scrcpy/issues/22#issuecomment-372023433, [`SDL_TouchFingerEvent`](https://wiki.libsdl.org/SDL_TouchFingerEvent)`, [`SDL_MultiGestureEvent`](https://wiki.libsdl.org/SDL_MultiGestureEvent)), modify `control_event.h`/`ControlEvent.java` to support a new type of events, then parse (`ControlEventReader.java`) and handle them (`EventController.java`) on the server-side.

**Comment by SSSANTON** [comment]
@rom1v 
Thanks for your explanation and suggestion.

**Comment by m4heshd** [comment]
Any chance this works by now?

**Comment by rom1v** [comment]
Multitouch has been implemented (#22).
