### ISSUE TITLE
Display the cursor on the mobile device

### ISSUE THREAD

**Issue by parrot125** [Genymobile/scrcpy#2433]
- [ ] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
Nope
**Describe the solution you'd like**
It would be good if we can see the live location of the cursor on a mobile device as well so that the device can be used as a second screen

**Describe alternatives you've considered**
I tried using deskdock (https://play.google.com/store/apps/details?id=com.floriandraschbacher.deskdock.free&hl=en_IN&gl=US) which does this but it makes the device on purely second screen and I cannot see the screen on pc, also it is laggy and does not support keyboard inputs.

**Comment by rom1v** [comment]
#1129?

**Comment by parrot125** [comment]
> #1129?

Yes, Something like that. Is it possible now?
Sorry for the repost.

**Comment by rom1v** [comment]
Currently, no.

Closing as duplicate.
