### ISSUE TITLE
Livestream from app blank screen

### ISSUE THREAD

**Issue by fordquent** [Genymobile/scrcpy#2436]
- [yes ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).

 - [ yes] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: windows
 - scrcpy version: 1.18
 - installation method: windows release
 - device model: Samsung Galaxy A30
 - Android version: 9

**Describe the bug**
When mirroring the phone screen the livestream video from an app (dialog viu) ends up as a black screen. Everything else on the app is mirrored just fine. Bit of a noob here so any suggestions would be appreciated. Tried changing video encoders and bit rates but didnt work.

**Comment by rom1v** [comment]
If it uses DRM, like Netflix, that's expected unfortunately.

**Comment by fordquent** [comment]
> 
> 
> If it uses DRM, like Netflix, that's expected unfortunately.

Oh okay, that explains it. Thanks!
