### ISSUE TITLE
adb push 1

### ISSUE THREAD

**Issue by knightwanter** [Genymobile/scrcpy#2439]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: 1.18
 - installation method: from the site itself
 - device model: poco c3
 - Android version: 10

**Describe the bug**
everything is on debugging etc when i open scrcpy it wont start 

On errors, please provide the output of the console (and `adb logcat` if relevant).

"adb push" returned with value 1

Please paste terminal output in a code block.

INFO: scrcpy 1.18 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: no devices/emulators found
ERROR: "adb push" returned with value 1
Press any key to continue . . .

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#device-not-detected
