### ISSUE TITLE
How to reduce skipped frames?

### ISSUE THREAD

**Issue by kenken890922** [Genymobile/scrcpy#244]
I want to stream my phone screen to live streaming platform at 60fps with OBS, but there're too many skipped frames making it looks like 30fps. I have tried to close all software(include OBS) except for scrcpy, but still skipped a lot of frames(see screenshot below). Is there any ways to solve it? Thanks.
![screenshot](https://user-images.githubusercontent.com/38998202/44566471-59eb5100-a7a0-11e8-8b69-99f7299dbc53.png)

**Comment by rom1v** [comment]
> there're too many skipped frames making it looks like 30fps

You still have ~50fps yet :wink:

When the decoder produces a frame, it makes it available for the "renderer". If the renderer didn't consume the previous frame yet (i.e. it would now have two frames to renderer), by default, the decoder "skips" the old one. That way, the renderer always display the very last available frame. This minimizes lag when the renderer cannot display images fast enough.

This behavior is controlled by a compilation flag (`SKIP_FRAME`), though. If you disable it, the decoder will wait for the renderer to consume the previous frame before offering a new one: https://github.com/Genymobile/scrcpy/blob/v1.3/app/src/frames.c#L65-L75.

If you want to test without skipping frames, configure with:

    meson x -Dskip_frames=false

Then compile.

But if your CPU/GPU is not fast enough, it won't do magic.

**Comment by kenken890922** [comment]
Sorry, I'm not familiar with android developing, could you help me to build a non-skipped-frames version? Thank you.

**Comment by guiguijke** [comment]
Hi ,
First your app is awesome !
Then, I'm joining this issue because I'm not able to build an app without skipping frames.
Is it possible (please) for you to compile a version without  skipping frames ?
I would be very thankful
(Plus, is there a way to capture the video directly by OBS instead capturing the window ?)

**Comment by rom1v** [comment]
@guiguijke: [`scrcpy.exe`](https://tmp.rom1v.com/scrcpy/issue244/1/scrcpy.exe), v1.6 for win64, compiled with `skip_frames=false`.
_SHA256: d5a96b03a8709c7c87cdb5d21654c10438efffab4138ec201ab1468020a14706_

(download v1.6 win64, and replace the .exe)

> (Plus, is there a way to capture the video directly by OBS instead capturing the window ?)

Apparently: https://www.reddit.com/r/OculusGo/comments/94yl4w/screen_casting_the_oculus_go_howto/
Just out of curiosity, why?

**Comment by guiguijke** [comment]
Hi !
Thanks for your quick answer =)
First -> the scrcpy.exe you game me is working great [Image](https://ibb.co/c6xMZB6)  ! I'll try it tomorrow or after tomorrow
Second, I'm streaming PUBG Mobile : here a stream with your solution https://www.twitch.tv/videos/367140403
I'll try with 1.6 and 1.6 No Skipped Frames =)
Regards

**Comment by xaoc37rus** [comment]
Good day
I want to say a big thank you for your great program.
I use it to create FPS charts. I am currently using version 1.6, since that version **without skipped frames**. Please compile version 1.8 **without skipped frames**. Unfortunately, I do not understand how to make it out of windows.

With love Dmitry Romanov.

**Comment by rom1v** [comment]
> I use it to create FPS charts. I am currently using version 1.6, since that version without skipped frames.

Do you see any difference in practice?

(If you add the fps value and the number of skipped frames, you get the fps output by the device.)

**Comment by xaoc37rus** [comment]
Thanks for quick answer
I can not tell the difference, because I use only the version without skipped frames.
I understand that if you add up these two values, you get real fps.
It is just not very convenient.
I just copy the data in the console and paste it into Notepad ++ then delete everything except the numbers (ctrl + F replace)

**Comment by rom1v** [comment]
> I use it to create FPS charts

Also note that the framerate is updated on every frame (not every unit of time), so for example if there are no frames for 3 seconds, then you won't get 0 fps (just missing values), then the first frame will be counted as 1 fps.

And also that a frame is produced only when the device screen change, so the result may be perfect at 10 fps, but laggy at 40fps.

**Comment by xaoc37rus** [comment]
Thank you for explaining

**Comment by rom1v** [comment]
Note that the compile time flag `SKIP_FRAMES` had been replaced by a runtime option `--render-expired-frames`.

**Comment by DarkKnight0715** [comment]
Hi 
I just wanted to say that the lastest version of SCRCPY Is still skipping frames. 
Pls help me with this.
I had commented here earlier. I think it's got deleted. If it has not. Just ignore this but pls reply

**Comment by rom1v** [comment]
@DarkKnight0715 https://github.com/Genymobile/scrcpy/issues/670#issuecomment-785916813

**Comment by DarkKnight0715** [comment]
So is there nothing I can do to reduce this? If there is, can u pls tell me? Cuz I know nothing abt cmd

**Comment by rom1v** [comment]
If it skips frame (and prints `+XX skipped frames` when you enable framerate logging in the console by pressing Alt+i in the scrcpy window), then your computer is probably not fast enough. Try reducing the resolution (`scrcpy -m800`).

**Comment by naveen-97-97** [comment]
> If it skips frame (and prints `+XX skipped frames` when you enable framerate logging in the console by pressing Alt+i in the scrcpy window), then your computer is probably not fast enough. Try reducing the resolution (`scrcpy -m800`).

I am on the latest version of scrcpy from at least last 2 months at 1st it's all working fine but from last few days I am having a issue that's lagging while using scrcpy I don't know it's a frame skipping problem or what please solve my issue quickly .I have to watch some of my classes on a big screen.

**Comment by naveen-97-97** [comment]
> Did you reduce framerate/resolution? Did you try over USB or is it over wifi?

Yes I tried . Try over usb

**Comment by naveen-97-97** [comment]
It was just like one day I slept at night and wake up at morning and just boom there is a lagging issue before that it's all working fine

**Comment by rom1v** [comment]
Reboot the device.

**Comment by naveen-97-97** [comment]
Bro I tried this also .Even I shifted HDD to SSD but still facing this issue .Please help me out please

**Comment by naveen-97-97** [comment]
Let me explain in detail it's just like that if I make screen very small then it's working when I shift to full screen maximize the screen on laptop it's just get slow

**Comment by rom1v** [comment]
Then the lag is on your computer. A driver issue probably.

If you record (`scrcpy --record file.mkv`) then play the file, is it ok?

**Comment by naveen-97-97** [comment]
I will try it later now I don't have my laptop with me. I don't know what is the problem but it just came overnight . All drivers are updated perfectly. I tried the old version 1.16 then the key ctrl + i and checked the frame rate it was just like skipping frames

**Comment by naveen-97-97** [comment]
Do you tell me any code for skipping frames issue solution on the latest version 1.17

**Comment by rom1v** [comment]
This is no a "skipping frame" issue, this is a performance issue either on your device or the computer.

**Comment by naveen-97-97** [comment]
Ya May be . Let me make try about  the skipping frame issue please tell me code to reduce skipping frames

**Comment by naveen-97-97** [comment]
You was right bro that was an issue of performance.
