### ISSUE TITLE
.iam a gamer and i use scrcpy and obs. But after buying a new phone when i connect with scrcpy via usb its all ok but when i start recording in obs, it lags and delays and the fps is very low.Please help me

### ISSUE THREAD

**Issue by Arghaop71** [Genymobile/scrcpy#2442]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
You could use OBS and scrcpy on Linux, and the new v4l2 feature in v1.18: https://github.com/Genymobile/scrcpy/releases/tag/v1.18

**Comment by Arghaop71** [comment]
> You could use OBS and scrcpy on Linux, and the new v4l2 feature in v1.18: https://github.com/Genymobile/scrcpy/releases/tag/v1.18

I use windows

**Comment by rom1v** [comment]
> I use windows

I'm sorry for you :troll:

More seriously, I have no solution for Windows, if OBS window capturing makes everything lag.

Note that you can try linux on your computer, for example: https://ubuntu.com/#download (make a LiveUSB) :wink:

**Comment by Arghaop71** [comment]
> > I use windows
> 
> I'm sorry for you :troll:
> 
> More seriously, I have no solution for Windows, if OBS window capturing makes everything lag.
> 
> Note that you can try linux on your computer, for example: https://ubuntu.com/#download (make a LiveUSB) 😉

Will ot fix the lags and delays?

**Comment by rom1v** [comment]
If OBS slows down scrcpy due to the window capture, yes, if you use v4l2, it couldn't happen.

However, if everything is slowed down because video encoding by OBS takes 100% of the CPU, that should not fix the problem.

**Comment by Arghaop71** [comment]
M

> If OBS slows down scrcpy due to the window capture, yes, if you use v4l2, it couldn't happen.
> 
> However, if everything is slowed down because video encoding by OBS takes 100% of the CPU, that should not fix the problem.

Will linux fix this issues?

**Comment by rom1v** [comment]
> Will linux fix this issues?

In the first case (if the slowdown is due to window capture), yes.
In the second case (if the slowdown is due to video encoding by OBS which takes 100% CPU), no.

**Comment by Arghaop71** [comment]
> > Will linux fix this issues?
> 
> In the first case (if the slowdown is due to window capture), yes.
> In the second case (if the slowdown is due to video encoding by OBS which takes 100% CPU), no.

So isnt there any confirmed solution?
And how i can know how much cpu obs do takes?
