### ISSUE TITLE
Black lockscreen

### ISSUE THREAD

**Issue by dasistkeintest** [Genymobile/scrcpy#2455]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: 1.18
 - installation method: Windows release
 - device model: Huawei P smart Z
 - Android version: 10

**Describe the bug**
My display broke and I am no longer able to use the touchscreen. scrcpy worked well, but I restarted the phone and now I am stuck at the lockscreen. After swiping up, the screen turns black, presumably because the pattern input is protected for privacy reasons. Is there some way to get around this?

**Comment by rom1v** [comment]
Alt+m will unlock if there is no PIN/pattern security.
If a PIN is requested on lock screen, press Alt+m then enter the PIN then enter.
A pattern without seeing the content is more complicated.

**Comment by dasistkeintest** [comment]
Okay, thanks. 
Unfortunately I am using a pattern.
So there is no way to get around the protection?

**Comment by Udhayarajan** [comment]
@dasistkeintest just press right mouse button while connected. It will behave like we press power button on android.

**Comment by dasistkeintest** [comment]
After some trial and error, I managed to unlock the phone by drawing the pattern on the black screen.

**Comment by DamianoMura** [comment]
> Alt+m will unlock if there is no PIN/pattern security. If a PIN is requested on lock screen, press Alt+m then enter the PIN then enter. A pattern without seeing the content is more complicated.

i have the same issue but with alphanumerical password... should i see a textfield when pressing 'alt+m'???

**Comment by welpdx** [comment]
> > Alt+m will unlock if there is no PIN/pattern security. If a PIN is requested on lock screen, press Alt+m then enter the PIN then enter. A pattern without seeing the content is more complicated.
> 
> i have the same issue but with alphanumerical password... should i see a textfield when pressing 'alt+m'???

For my phone, the first `alt + m` turns my screen on from sleep. The second `alt + m` swipes my screen up to show a keypad to enter the pin. If the device is connected from scrcpy before it feel asleep, you can enter the pin via pc keyboard just like if you had a bluetooth keyboard attached to it. Press enter after typing in the pin and device will unlock with no problems. 

(If the phone screen turns on, just press `alt + o` to turn phone screen off while maintaining control through scrcpy. )

Tested on Huawei P20 Pro Android 8.1.0

**Comment by ThreeMinutesFix** [comment]
great it work very well

**Comment by KandarLubis** [comment]
you can use your keyboard sir after swipe up, and I also just found out

**Comment by VincentChalnot** [comment]
I'm surprised no one mentioned the possibility to clear the pattern lock with adb:
```shell
$ adb locksettings clear --old XXXXXX
```
Where XXXX is corresponds to the list of "cells" of your pattern.

**Comment by rom1v** [comment]
@VincentChalnot Ah yes :+1: Often I don't mention it because people try to bypass the lock screen when USB debugging is disabled (in OTG mode), but here this is not the case.

https://nerdschalk.com/change-remove-lockscreen-pattern-pin-password-adb-android-oreo/
