### ISSUE TITLE
Why for scrcpy to work wirelessly everytime i need to once plugin my phone to laptop

### ISSUE THREAD

**Issue by saas07842** [Genymobile/scrcpy#2459]
Every time i start my laptop and try to connect to scrcpy wirelessly, it is not able to connect
First i change my directory in command prompt and then i run "abc tcpip 5555" and then it shows :-

daemon not running; starting now at tcp:5037
daemon started successfully
error: no devices/emulators found
then i try adb connect ip-address:5555 and then also it shows the error:-
cannot connect to ip-address:5555: No connection could be made because the target machine actively refused it. (10061)

After that i connect my phone to the laptop via usb cable and then again run "adb tcpip 5555" and it gets executed this time.
After that i discoonect my phone from the laptop and then run the command "adb connect ip-address" and then it gets connected to the device and then typing scrcpy lets me connect to my phone.

Is it that everytime i need to connect my phone once and then only i can access the phone wirelessly?

**Comment by rom1v** [comment]
You need to execute `adb tcpip 5555` (with device plugged in) after each reboot of your Android device.
You need to execute `adb connect 5555` every time your device is disconnected from `adb` (e.g. if you adb daemon is stopped, after a reboot of the computer for example).
