### ISSUE TITLE
Insert mouse and give an option to turn off the screen

### ISSUE THREAD

**Issue by ssoufi-code** [Genymobile/scrcpy#2462]
I decided today to run Minecraft Java on Android, which is admittedly a niche case. I was somewhat annoyed that scrcpy doesn't have an option to route the mouse into the phone and instead requires you to emulate touch. As a result, I can't pan around like normal Minecraft. I also noticed that with 4GB(USB-C2.0)(Snapdragon678)(1080*2400) I was getting latency that can be measured in seconds when I was in-game. It would be helpful to have an option to disable the screen and just use the laptop as a USB hub.

**Comment by rom1v** [comment]
> I was somewhat annoyed that scrcpy doesn't have an option to route the mouse into the phone and instead requires you to emulate touch

Feature request #269.

> I was getting latency that can be measured in seconds when I was in-game.

See #1773.

> It would be helpful to have an option to disable the screen and just use the laptop as a USB hub

https://github.com/Genymobile/scrcpy#turn-screen-off
