### ISSUE TITLE
ERROR: Could not listen/forward on any port in range

### ISSUE THREAD

**Issue by andregs** [Genymobile/scrcpy#2468]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10 Pro Version 20H2 OS build 19042.1052
 - scrcpy version: scrcpy-win64-v1.18
 - installation method: Windows zip release
 - device model: moto g9 play
 - Android version: 11

**Describe the bug**
I've been using scrcpy via USB for some time with no issues, but at some point it's no longer working. I believe that's because I recently upgraded from Android 10 to 11, but I'm not sure.

```
11:43 andre> adb logcat -c
11:43 andre> C:\Apps\scrcpy-win64-v1.18\scrcpy.exe --stay-awake --turn-screen-off --prefer-text
INFO: scrcpy 1.18 <https://github.com/Genymobile/scrcpy>
C:\Apps\scrcpy-win64-v1.18\scrcpy-server: 1 file pushed, 0 skipped. 32.1 MB/s (37330 bytes in 0.001s)
bind: No error
WARN: Could not listen on port 27183, retrying on 27184
bind: No error
WARN: Could not listen on port 27184, retrying on 27185
bind: No error
                     (...)
WARN: Could not listen on port 27198, retrying on 27199
bind: No error
ERROR: Could not listen on any port in range 27183:27199
WARN: 'adb reverse' failed, fallback to 'adb forward'
WARN: Could not forward port 27183, retrying on 27184
adb.exe: error: cannot bind listener: cannot bind to 127.0.0.1:27184: An attempt was made to access a socket in a way forbidden by its access permissions. (10013)
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27184, retrying on 27185
adb.exe: error: cannot bind listener: cannot bind to 127.0.0.1:27185: An attempt was made to access a socket in a way forbidden by its access permissions. (10013)
ERROR: "adb forward" returned with value 1
                     (...)
WARN: Could not forward port 27198, retrying on 27199
adb.exe: error: cannot bind listener: cannot bind to 127.0.0.1:27199: An attempt was made to access a socket in a way forbidden by its access permissions. (10013)
ERROR: "adb forward" returned with value 1
ERROR: Could not forward any port in range 27183:27199
11:43 andre> adb logcat -d > logcat.txt
```

See also attached [logcat.txt](https://github.com/Genymobile/scrcpy/files/6785448/logcat.txt).

Thanks for the great app, by the way. I really love it!

**Comment by rom1v** [comment]
Probably a firewall which prevents you to listen on a port?

**Comment by andregs** [comment]
Hmm, I don't think so. I have only standard Windows Defender firewall, and I just disabled it but I still get the same error.

<img src="https://user-images.githubusercontent.com/712092/124966019-25440e80-dff9-11eb-947d-065314b00044.png" width="450px" />

**Comment by rom1v** [comment]
You have a permission problem to listen on a port, I don't know why.

**Comment by andregs** [comment]
Yeah, it really seems to be unrelated to scrcpy, right? I cannot even connect to my device via tcpip
```
14:40 andre> adb.exe tcpip 5555
14:41 andre> adb connect 192.168.1.105:5555
cannot connect to 192.168.1.105:5555: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (10060)
```

**Comment by KalanjaliParikisetty** [comment]
C:\Users\Admin\Downloads\scrcpy-win64-v1.18>scrcpy
INFO: scrcpy 1.18 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: no devices/emulators found
ERROR: "adb push" returned with value 1

C:\Users\Admin\Downloads\scrcpy-win64-v1.18>

**Comment by andregs** [comment]
Nevermind. After applying latest windows updates and restarting both the phone and the laptop, the issue was fixed. Thanks for the help!

**Comment by vnaz** [comment]
> netsh interface ipv4 show excludedportrange protocol=tcp

Protocol tcp Port Exclusion Ranges
Start Port    End Port
----------    --------
     26505       26604
     26605       26704
     26705       26804
     26805       26904
     26905       27004
     27005       27104
     27105       27204
     50000       50059     *
* - Administered port exclusions.

to resolve an issue I did use following command:
> scrcpy --tcpip -p 27206:27220
