### ISSUE TITLE
Bug: adb-wireless + scrcpy + using some script of adb to simulate touches -> scrcpy closes

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Genymobile/scrcpy#2469]
- [ V] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [V ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 Windows

 - scrcpy version: [e.g. 1.12.1]
v1.18

 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
Simple release and I extracted it.

 - device model:
Pixel 4

 - Android version: [e.g. 10]
Android 12 beta 2.1

**Describe the bug**
1. Connect to device using adb-wireless in the developer settings, while having the device connected to a charger.
2. Use scrcpy, by using this script 

```
CreateObject("Wscript.Shell").Run "cmd /c scrcpy.exe -S --always-on-top", 0, false
```

3. Run some long script to simulate a lot of touches. Example:

```
for /l %%t in (1, 1, 16) do (

	adb shell input tap 518 1230
	
	timeout /t 0.5
	adb shell input tap 574 2180

	for /l %%x in (1, 1, 78) do (
		adb shell input swipe 70 2200 960 2200
		timeout /t 1
		adb shell input swipe 960 2200 70 2200
		timeout /t 1
	)

	timeout /t 7

	adb shell input tap 574 2180
	timeout /t 5
)
```
4. Wait for about 3 minutes.

The bug is that even though the device is still connected and the touch-script still runs, scrcpy window closes itself.

**Comment by rom1v** [comment]
> scrcpy window closes itself

What is the console output when it closes (use `scrcpy-console.bat` to keep the console open)?

**Comment by AndroidDeveloperLB** [comment]
@rom1v 
Just this:

```
INFO: scrcpy 1.18 <https://github.com/Genymobile/scrcpy>
C:\android\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 42.4 MB/s (37330 bytes in 0.001s)
[server] INFO: Device: Google Pixel 4 (Android 11)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2280
WARN: Device disconnected
WARN: Killing the server...
Press any key to continue . . .
```

I think sometimes it also sometimes turns on the screen while still mirroring (the special flag that I use has it turned off, while still mirroring it, which is a cool feature)

**Comment by rom1v** [comment]
> WARN: Device disconnected

The device gets disconnected from `adb`.

Run `adb logcat` in another terminal, it will terminate at the same time.

Not an scrcpy issue.

**Comment by AndroidDeveloperLB** [comment]
@rom1v But it's not disconnected from adb. I can still see it on Android Studio, for example.
And I can re-launch ScrCpy without any issue.

**Comment by rom1v** [comment]
Yes, but the adb connections are still closed. Check `adb logcat` or `adb shell` which will be disconnected at the same time.

**Comment by AndroidDeveloperLB** [comment]
@rom1v How could you say it's closed, when the adb is still connected via Wifi ? 
I don't understand what you say I should try, and how it helps.

**Comment by rom1v** [comment]
Open a separate terminal witj `adb shell` or `adb logcat`. When scrcpy get closed unexpectedly, check that the command in that other terminal is also closed.

**Comment by AndroidDeveloperLB** [comment]
@rom1v Please explain the steps. 
What to do first? What to observe? 
Note that the batch file itself is calling adb, too, and it didn't stop working while ScrCpy closed itself.

**Comment by AndroidDeveloperLB** [comment]
@rom1v I think it also occurs without using a batch file of simulating touches.

**Comment by AndroidDeveloperLB** [comment]
@rom1v Why did you close it? The issue still occurs.
It actually doesn't matter if I interact with the device (either really me or a batch file).
It occurs on its own.

**Comment by rom1v** [comment]
It's not related to scrcpy, the adb server closes the connection for some reason, there is nothing scrcpy can do.

**Comment by AndroidDeveloperLB** [comment]
@rom1v But it hasn't closed the connection. Trying to re-connect via adb again says that it's already connected.
The adb-wireless hasn't lost the connection to the PC.

**Comment by rom1v** [comment]
The socket has been closed.

**Comment by AndroidDeveloperLB** [comment]
@rom1v Why? Bug on Android?
Have you tried to reproduce it on previous version of the OS (Android 11)?
How can I check that it's a bug on Android 12? Maybe I should report it.

**Comment by AndroidDeveloperLB** [comment]
@rom1v ok reported :
https://issuetracker.google.com/issues/199180658
