### ISSUE TITLE
In miui 9 (redmi4x) cannot control with mouse 

### ISSUE THREAD

**Issue by ranjithran** [Genymobile/scrcpy#247]
controls not working in miui 9

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-clicks-do-not-work

**Comment by ranjithran** [comment]
thanks for help but nav bar missing
![1](https://user-images.githubusercontent.com/36547960/44849209-0a60c580-ac77-11e8-91b1-a93dea1e838b.png)

**Comment by rom1v** [comment]
Your device does not display a navbar because they are physical touches.

There is no "virtual navbar" in _scrcpy_, so you have to use [shortcuts](https://github.com/Genymobile/scrcpy/blob/master/README.md#shortcuts) (mainly, left-click for BACK and middle-click for HOME).

**Comment by johnsie** [comment]
I can confirm that controls are working in MIUI once the simulated inputs are enabled on the device
