### ISSUE TITLE
Doesn't work with Tablet Samsung A7 and Android 11

### ISSUE THREAD

**Issue by ssaguiar** [Genymobile/scrcpy#2470]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**

I tried to use it using my tablet (Samsung A7) and got error.
To test if it was some problem with my system (windows 10), I tried the same with my Samsung J5 and it worked fine.

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

This is the error I got when testing with the tablet:

```
scrcpy.exe
INFO: scrcpy 1.18 <https://github.com/Genymobile/scrcpy>
C:\ProgramData\chocolatey\lib\scrcpy\tools\scrcpy-server: 1 file pushed, 0 skipped. 30.1 MB/s (37330 bytes in 0.001s)
[server] INFO: Device: samsung SM-T505 (Android 11)
INFO: Renderer: direct3d
INFO: Initial texture: 2000x1200
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffff4
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2127)
        at android.media.MediaCodec.configure(MediaCodec.java:2043)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:237)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:90)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:255)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:409)
WARN: Killing the server...
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
Does it work if you record with `screenrecord`?

```bash
adb shell screenrecord /sdcard/file.mp4
adb pull /sdcard/file.mp4
```

?

**Comment by ssaguiar** [comment]
> Does it work if you record with `screenrecord`?
> 
> ```shell
> adb shell screenrecord /sdcard/file.mp4
> adb pull /sdcard/file.mp4
> ```
> 
> ?

I tried as you asked.
It creates the mp4 video file but it's all black.

**Comment by rom1v** [comment]
OK, so it seems there is an encoder issue on the device.

You could try to reduce the definition (`scrcpy -m600`), or another [encoder](https://github.com/Genymobile/scrcpy#encoder).

**Comment by ssaguiar** [comment]
> OK, so it seems there is an encoder issue on the device.
> 
> You could try to reduce the definition (`scrcpy -m600`), or another [encoder](https://github.com/Genymobile/scrcpy#encoder).

I tried:
scrcpy -m960
and it worked fine.

Thank you very much for your help and support.
