### ISSUE TITLE
Mouse pointer hide on pc

### ISSUE THREAD

**Issue by parakramsinhr** [Genymobile/scrcpy#2478]
I have connected mouse to my android device. Is it possible to hide mouse pointer on pc?

**Comment by rom1v** [comment]
No, see #269.

**Comment by parakramsinhr** [comment]
Its different, am talking about android device's mouse pointer. I am ok with pc's mouse pointer.

**Comment by rom1v** [comment]
Ah no, it's not possible: if the mouse pointer is visible on your Android device, it will be visible in the screen capture.

**Comment by parakramsinhr** [comment]
Thank for reply btw great work, thanks for amazing solution
