### ISSUE TITLE
Choco Install failed due to bad checksum

### ISSUE THREAD

**Issue by 08wckster08** [Genymobile/scrcpy#2479]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: windows
 - scrcpy version: 1.18
 - installation method: choco
 - device model:n/a
 - Android version: n/a

Failed to install package. Failed to install package "scrcpy•, version "1.18". Error: ERROR: Checksum for android.png did not meet 'B2FE913ED202C908DIOACDID602CCDB24E2E79F3009570E2CADAF22694FFA4DA' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore- checksums if necessary. The install of scrcpy was NOT Successful. Error while running See log for details. Chocolatey installed 0/1 packages. 1 packages failed. See the log for details.

**Comment by rom1v** [comment]
Ref #1144 cc @equiman 

(should be reported to chocolatey instead)

**Comment by 08wckster08** [comment]
I also made a report there but I wanted you as the author to be aware. Maybe I was wrong \o/

**Comment by shinayser** [comment]
Hey folks, what should I do to fix that error?

**Comment by 08wckster08** [comment]
Choco stated they would get to it but if I trusted the source I could just
use --ignore-checksums
