### ISSUE TITLE
Server running with Black border even with same aspect ration of the monitor

### ISSUE THREAD

**Issue by vfransant** [Genymobile/scrcpy#2481]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: 1.18
 - installation method: just use the .exe in the zip file (sorry, I don't know how to name this)
 - device model: Xiaomi Redmi Note 5
 - Android version: 9

**Describe the bug**

My device has a 18:9 screen while my monitor is 16:10. So, when I get to really use my cellphone, I run adb
`adb shell wm size 1350x2160` with some resolutions, but always 16:10
`adb shell wm density 220` when I need it to work better with my monitor size

The problem is that at most resolutions, the server always cuts about 2-3 pixels from the top and the bottom. When I try to add these 4p in the height, then the black border appears on the sides...

It is really a problem for me because my phone has some gestures: 
- pull op from the very bottom: go to home
- pull from the very side: go back
- pull from the very side and mantain: switch apps

With the borders, I can't use them. Even though my android is running at true 16:10 (ex. 2160x1350), the server does the following:

INFO: scrcpy 1.18 <https://github.com/Genymobile/scrcpy>
C:\Users\vfran\OneDrive\Documentos\Android Tools\scrcpy-wi... file pushed, 0 skipped. 28.2 MB/s (37330 bytes in 0.001s)
[server] INFO: Device: Xiaomi Redmi Note 5 (Android 9)
INFO: Renderer: direct3d
INFO: Initial texture: 1344x2160

I tried to crop (or downscale, don't really know how it is called) the client, like `scrcpy  --max-size 1800` or any other, like 1440 (my monitor height), but didn't work. I also tried to run with OpenGl, but same thing.

What could I do? thanks for the attention

![image](https://user-images.githubusercontent.com/68281581/125332347-571de380-e31f-11eb-8d4d-8f06407dc39f.png)

I don't really know why it didn't show the mouse above the border, but the border is there
(It is not showing just half of the screen, just my phone launcher that doesn't really support this forced landscape mode)

**Comment by rom1v** [comment]
> The problem is that at most resolutions, the server always cuts about 2-3 pixels from the top and the bottom

Scrcpy always rounds the size to a multiple of 8, because it's required by most video encoders.

But it slightly stretches or shrinks the content, it should not add padding or crop.

This is obvious by rounding to a multiple of 512 instead:

```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/ScreenInfo.java b/server/src/main/java/com/genymobile/scrcpy/ScreenInfo.java
index c27322ef..0d2e9cc8 100644
--- a/server/src/main/java/com/genymobile/scrcpy/ScreenInfo.java
+++ b/server/src/main/java/com/genymobile/scrcpy/ScreenInfo.java
@@ -116,8 +116,8 @@ public final class ScreenInfo {
         // - scale down the great side of the screen to maxSize (if necessary);
         // - scale down the other side so that the aspect ratio is preserved;
         // - round this value to the nearest multiple of 8 (H.264 only accepts multiples of 8)
-        w &= ~7; // in case it's not a multiple of 8
-        h &= ~7;
+        w &= ~511; // in case it's not a multiple of 512
+        h &= ~511;
         if (maxSize > 0) {
             if (BuildConfig.DEBUG && maxSize % 8 != 0) {
                 throw new AssertionError("Max size must be a multiple of 8");
```

> `adb shell wm size 1350x2160` with some resolutions, but always 16:10

Try 1200x1920 (both dimensions are multiple of 8).

**Comment by vfransant** [comment]
Thank you! That makes sense, now it is working great on 8x based numbers.

**Comment by Leuhan76** [comment]
Hello, I was reading and from what I understood, the screen of your smartphone is 18:9 but you could adapt it to your 16:9 monitor using a command, could you explain to me how this works? I have a 21:9 smartphone and I also want to adapt it to my 16:9 screen

**Comment by rom1v** [comment]
@Leuhan76 You can change the size of your device:

```bash
adb shell wm size …
adb shell wm density …
```

https://stackoverflow.com/questions/18500611/android-how-to-use-adb-shell-wm-to-simulate-other-devices

If you don't want to change your device size but want to make an image fit into a rectangle having a different aspect ratio, theoretically, you have only 2 solutions: stretch the image and/or crop.

Scrcpy does not support stretching the image (it always preserves aspect ratio), so you can only [crop](https://github.com/Genymobile/scrcpy#crop).

**Comment by Leuhan76** [comment]
Ok, I can change the size of my device, the screen of my smartphone is 720x1600 and the one of my monitor is 1366x768, what resolution should I put? Sorry but I hardly understand this and thanks for answering so quickly

**Comment by rom1v** [comment]
> Ok, I can change the size of my device, the screen of my smartphone is 720x1600 and the one of my monitor is 1366x768, what resolution should I put?

Try 1366x768, so they'll have exactly the same resolution.

**Comment by Leuhan76** [comment]
ok i will try this adb shell wm size 1366x768

**Comment by Leuhan76** [comment]
I already tried it, if the resolution changes, but the window on the monitor continues to be seen with the same black borders and does not fit the entire screen
