### ISSUE TITLE
backspace doesn't work

### ISSUE THREAD

**Issue by R4F43Lv** [Genymobile/scrcpy#2483]
- OS: [Windows]
 - scrcpy version: [v1.18]
 - installation method: [scrcpy.zip]
 - device model: [Xiaomi Note 8 Pro]
 - Android version: [Android 10]

I can't delete the characters typed in the text fields (backspace doesn't work).

**Comment by rom1v** [comment]
If you position the cursor in a text field, and execute this command:

```
adb shell input keyevent DEL
```

Does this work?

**Comment by R4F43Lv** [comment]
It worked!! Thank you..
