### ISSUE TITLE
Error: Failed to download resource "unbound_bottle_manifest"

### ISSUE THREAD

**Issue by puke3615** [Genymobile/scrcpy#2484]
==> Downloading https://ghcr.io/v2/homebrew/core/unbound/manifests/1.13.1
#=#=#                                                                         
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to ghcr.io:443 
Error: Failed to download resource "unbound_bottle_manifest"
Download failed: https://ghcr.io/v2/homebrew/core/unbound/manifests/1.13.1

**Comment by rom1v** [comment]
#2247 might help.
