### ISSUE TITLE
start problem for signed apks

### ISSUE THREAD

**Issue by dilekyldrm** [Genymobile/scrcpy#2486]
Hello,
 I have a problem, when starting of the Appium on real device. 

I faced with this Error after click Start Sessions.

Error
An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\25200038\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s TQC000200003470401 install -r 'C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v4.21.1.apk'' exited with code 1'; Stderr: 'adb: failed to install C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.21.1.apk: Failure [INSTALL_FAILED_VERIFICATION_FAILURE]'; Code: '1'

 My real device doesn't accept unsigned apk files or something because of security. 
When I realized that, I just signed all of the files below to solve the problem.

     settings_apk-debug.apk
     app-debug-androidTest.apk , 
     appium-uiautomator2-server-debug-androidTest.apk
     appium-uiautomator2-server-v4.21.1.apk

and then, I replaced them with the unsigned ones. After that I wrote  'adb install' on Windows Power Shell to check them if they were correct or not. 

The Windows Power Shell showed me : 

      ''Performing Streamed Install
      Success''

I thought 'this time I succeed on it.' But it was not happened.
When I clicked Start Session with correct information which Appium need ( deviceName, appActivity, appPackage, platformName).
Same Error occurred again. 

Error
An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\25200038\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s TQC000200003470401 install -r 'C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v4.21.1.apk'' exited with code 1'; Stderr: 'adb: failed to install C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.21.1.apk: Failure [INSTALL_FAILED_VERIFICATION_FAILURE]'; Code: '1'

Like I didn't sign any apk. or I didn't change anything. 
After got the same error I checked the Windows Power Shell to see the differences. I faced with the same failed massage at the beginning.
 I realized that Appium change the signed files with the beginning ones. It replaced files with the unsigned ones.
 It didn't let me make some changings.
 I don't know why ?????

HOW CAN I FİX THİS PROBLEM?
 IS THERE ANYONE COME ACROSS A PROBLEM LİKE THAT ?

screenshots below,

![Screenshot (21)](https://user-images.githubusercontent.com/87432156/125646713-35846809-09d9-498f-8638-e83aaf799445.png)
![Screenshot (23)](https://user-images.githubusercontent.com/87432156/125646727-e5419bef-fd56-4f69-b195-0e6c466d8bdf.png)

**Comment by rom1v** [comment]
Is it related to scrcpy in any way?

**Comment by dilekyldrm** [comment]
How can I get that it is related to scrcpy or not ?

> Is it related to scrcpy in any way?

**Comment by rom1v** [comment]
> How can I get that it is related to scrcpy or not ?

You're asking a random question as an issue on the scrcpy repo. If it's not about scrcpy, this is not the good place to ask your question.

**Comment by SelcukYolcu** [comment]
Hi I am Dilek's colleagues. 
Actually it is not about the scrcpy, the problem is about signed/not signed apps. Appium install some applications when start session. The device rejects to install unsigned apps, all apps must be signed by our team. Even if Dilek changes the all apps with signed ones, When Session is started, Appium overwrites files  by unsigned ones and this causes to installation problem.

**Comment by craftersshaft** [comment]
this is more of an adb issue, because dragging and dropping an apk just does it directly through adb's install command, but try seeing if any of these solutions work https://stackoverflow.com/questions/15014519/apk-installation-failed-install-failed-verification-failure
