### ISSUE TITLE
SideSync causes screen to be oriented -90 deg

### ISSUE THREAD

**Issue by pbrackin** [Genymobile/scrcpy#249]
This issue is for a Samsung S6 & probably applicable to any Samsung:

In windows, if you use the Samsung SideSync app:  Sidesync appears to kill scrcpy when I fire it up, which is fine to me (why run both?).   BUT when I have Sidesync closed (not in use), it still has a background service (you can see it in the tray), an odd problem occurs:   scrcpy will orient the display -90 degrees (see image attachment).  Rotating phone by hand can give you desired orientation, but then the layout is opposite (landscape when you want portrait & vice versa).  A fix is to kill Sidesync service & restart scrcpy, then things are oriented properly. 

![image](https://user-images.githubusercontent.com/7493469/44867683-627ad600-ac3d-11e8-8a6d-c266cd818862.png)

**Comment by rom1v** [comment]
When this happens, could you execute:

    adb shell screenrecord /sdcard/file.mp4
    adb pull /sdcard/file.mp4

Is the video correctly oriented?

**Comment by pbrackin** [comment]
Yes. The video is properly oriented.  To be clear:  I ran scrcpy at one command prompt & then opened another to do the screenrecord & pull commands.

**Comment by rom1v** [comment]
Related: https://www.reddit.com/r/GalaxyNote9/comments/9md011/sidesync_screen_is_rotated_touch_input_is/

**Comment by rom1v** [comment]
A priori, nothing scrcpy can do :confused: I'm closing.
