### ISSUE TITLE
Forward all clicks option issue (Right Click)

### ISSUE THREAD

**Issue by vfransant** [Genymobile/scrcpy#2492]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: 1.18
 - installation method: Zip containing .exe
 - device model: Xiaomi Redmi Note 5
 - Android version: 9

Hello! As I would like to use mouse right-click to open context menu instead of Back button, I've been trying to read

[https://github.com/Genymobile/scrcpy/issues/1958](url)
[https://github.com/Genymobile/scrcpy/issues/1613](url)
[https://github.com/Genymobile/scrcpy/issues/1302](url)

I saw that there is a option `--forward-all-clicks` and tried to launch with it, but then every mouse clicks change to a normal click, even middle-button... I also saw that `--right-click=XXX` in #1302 and change XXX to inject, but I didn't really understand if it was implemented.

Am I doing something wrong? Or, is there any other way to work with this right-click?

**Comment by rom1v** [comment]
> I saw that there is a option `--forward-all-clicks` and tried to launch with it, but then every mouse clicks change to a normal click, even middle-button... 

Actually, if you press right-click or middle-click, it correctly injects right-click or middle-click. Just your device reacts the same way on these clicks (Android apps initially were not intended to handle right clicks).

It still differs slightly on some components. For example, a right-click on a textfield/textarea should open a contextual menu (at least, on my device, that's what it does).

**Comment by vfransant** [comment]
Well, apparently my device really don't support right-click context menu, via this tool at least, but I don't think it would via OTG either :/

Indeed, if I click and hold with right click at text, the action of menu context doesn't appear, showing that the system indeed interpetates it differently from left-click, but not the right way... Thank you for the help though
