### ISSUE TITLE
Can't Control Device

### ISSUE THREAD

**Issue by AssassinAguilar** [Genymobile/scrcpy#2496]
I am having a problem that I can't control my device from my dekstop which is connect wirelessly. Anything I do in device appears properly on dekstop but can't control it

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work

**Comment by Davizun** [comment]
> https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work

I tried this on my redmi note 8 pro and it still doesnt work

**Comment by pickfire** [comment]
> I tried this on my redmi note 8 pro and it still doesnt work

I tried this on china developer rom on redmi note 8 pro but it works.
