### ISSUE TITLE
Per-app windows

### ISSUE THREAD

**Issue by luke-jr** [Genymobile/scrcpy#2499]
It would be nice if scrcpy could open multiple windows, for different apps on the phone, and automatically switch between them as needed.

For example, one could have a Twitter window, and when that window gets focus, open the Twitter app on the phone; and at the same time, a Conversations window which switches to Conversations (bonus if there's a way to put each individual conversation in its own window and handle XDG notifications nicely)

To avoid showing the wrong content in other windows, scrcpy could "dim" the last-seen contents and cease updating that window until it is open on the phone again.

**Comment by thebigsmileXD** [comment]
https://github.com/Genymobile/scrcpy/issues/1887?
