### ISSUE TITLE
Start in fullscreen mode

### ISSUE THREAD

**Issue by philippsandhaus** [Genymobile/scrcpy#250]
Hello,

I am planning to use scrappy as part of a kiosk system where the scrcpy should appear in fullscreen mode. The computer should boot up automatically and scrcpy should start in fullscreen mode. I did find the option to hit ctrl-f to enter fullscreen while running, but is there also a way to already start in fullscreen mode? I did not find a respective command-line option. AM I missing something here? I am using a windows 10 system.

Best,

Philipp

**Comment by rom1v** [comment]
There is currently no command-line option.

**Comment by philippsandhaus** [comment]
I have opened a pull request #252
