### ISSUE TITLE
No protocol specified, Segmentation fault (core dumped)!!!

### ISSUE THREAD

**Issue by nonnon-creator** [Genymobile/scrcpy#2501]
- OS: Linux 
 - scrcpy version: latest
 - installation method: snap
 - device model: 
 - Android version: 9

INFO: scrcpy 1.18 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server:...shed. 1.9 MB/s (37330 bytes in 0.019s)
No protocol specified
[server] INFO: Device: MY DEVICE (Android 9)Segmentation fault (core dumped)

**Comment by nonnon-creator** [comment]
Found the solution

**Comment by nonnon-creator** [comment]
xhost +

**Comment by rom1v** [comment]
Could you please build with sanitizer enabled and run (without `xhost +` so that it crashes):

```
meson d -Db_sanitize=address
ninja -Cd
./run d
```

If you use the [prebuilt-server](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#option-2-use-prebuilt-server):

```
meson d -Db_sanitize=address -Dprebuilt_server=/path/to/scrcpy-server # adapt the path
ninja -Cd
./run d
```

And post the stacktrace when it crashes, please.

**Comment by TE-N-ElvenWang** [comment]
I use "sudo scrcpy" fixed this issue in my end.
