### ISSUE TITLE
can not work on windows 11

### ISSUE THREAD

**Issue by w359405949** [Genymobile/scrcpy#2505]
can not work on windows 11

**Comment by rom1v** [comment]
Please fill an issue with all information requested in the issue template. "can not work" gives no information.

**Comment by w359405949** [comment]
@rom1v can not open, nothing shown.

**Comment by rom1v** [comment]
Run scrcpy-console.bat. What's the output?

**Comment by w359405949** [comment]
@rom1v it work now. maybe some mistake before i made.
