### ISSUE TITLE
It runs well, but I can't find scrcpy-server.jar

### ISSUE THREAD

**Issue by unity3dhansen** [Genymobile/scrcpy#2506]
I download the release on Windows and run it with my android phone. 
From the developer document and source code. I know the scrcpy-server.jar will be push to the device folder /data/local/tmp/. Therefore, I use adb shell to find this jar file.  There is no jar file exist but with libcompress.so and libturbojpeg.so. I'd like to know how to run the jar and where it is.

What's more, it seems using adb forward and adb reverse to communicate with client and server.  I have tried to use command "./adb forward  --list" and "./adb reverse --list" (use the same adb in scrcpy folder), and nothing will be return to me. 

Can you answer something about my question?

**Comment by rom1v** [comment]
> Therefore, I use adb shell to find this jar file.

The server (cleanup process) removes itself on start:

https://github.com/Genymobile/scrcpy/blob/ab12b6c981d62aac2c4c86c5436378970723cc38/server/src/main/java/com/genymobile/scrcpy/CleanUp.java#L154

But this "jar" file is `scrcpy-server` in the release, so you already have it on your computer. It must be named `.jar` on the device to avoid issues: 83ace842809034f8076296a338c017e49519f068

> What's more, it seems using adb forward and adb reverse to communicate with client and server. I have tried to use command "./adb forward --list" and "./adb reverse --list" (use the same adb in scrcpy folder), and nothing will be return to me.

These commands just enable port redirection, they don't do anything else.

**Comment by airhandsome** [comment]
I want to know how the client and port connect.  I thought the sever application in device reverse to client device port, and the client  connect to local port. However as mentioned above, it returns nothing when execute "./adb reverse --list". Is there some other operation?

**Comment by mutexz** [comment]
> I want to know how the client and port connect. I thought the sever application in device reverse to client device port, and the client connect to local port. However as mentioned above, it returns nothing when execute "./adb reverse --list". Is there some other operation?

hello, see the explanation here: [4071](https://github.com/Genymobile/scrcpy/issues/4071)
