### ISSUE TITLE
My phone has been rooted,but why did push-target had been changed?

### ISSUE THREAD

**Issue by greenhandzdl** [Genymobile/scrcpy#2509]
Problems:
`PS C:\Users\20292> scrcpy
INFO: scrcpy 1.18 <https://github.com/Genymobile/scrcpy>
ERROR: Failed to execute: [D:\GitHub\scrcpy-win64-v1], [push], ["D:\GitHub\scrcpy-win64-v1\scrcpy-server"], ["/data/local/tmp/scrcpy-server.jar"]
ERROR: Could not execute "adb push"`

**Comment by rom1v** [comment]
> Failed to execute: [D:\GitHub\scrcpy-win64-v1], [push],

You set the ADB env varriable to `D:\GitHub\scrcpy-win64-v1`. You should unset it (or set it to `D:\GitHub\scrcpy-win64-v1\adb.exe`).

**Comment by greenhandzdl** [comment]
> > Failed to execute: [D:\GitHub\scrcpy-win64-v1], [push],
> 
> You set the ADB env varriable to `D:\GitHub\scrcpy-win64-v1`. You should unset it (or set it to `D:\GitHub\scrcpy-win64-v1\adb.exe`).

In fact, some web(such:https://www.incredigeek.com/home/add-adb-to-windows-environment-variables) set the ADB env to folder instead of files, and ADB is normally worked on my Windows10 pwsh.

**Comment by greenhandzdl** [comment]
I try to use scrcpy on a non-root phone, and scrcpy works. Therefore, I suspect that the root phone may involve some permission-requiring operations, such as reading and writing to the root instead of the SD card

**Comment by rom1v** [comment]
> In fact, some web(such:https://www.incredigeek.com/home/add-adb-to-windows-environment-variables) set the ADB env to folder instead of files, and ADB is normally worked on my Windows10 pwsh.

No, they add the adb folder to the `PATH` env variable, not to the `ADB` env variable.

**Comment by greenhandzdl** [comment]
It's my problems. I created ADB  env variable and set `%ADB%` to path. Thanks!
I Worked up by set `D:\GitHub\scrcpy-win64-v1` to path.
