### ISSUE TITLE
The Android device cannot turn off the screen automatically after 30 seconds after disconnected with scrcpy

### ISSUE THREAD

**Issue by taicaile** [Genymobile/scrcpy#2513]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Ubuntu20.04
 - scrcpy version: 1.18
 - installation method: snap
 - device model: huawei honer 8
 - Android version: 8.0

**Describe the bug**

Hello, I just tried out `scrcpy`, and disconnected with Android device. Then the Phone cannot turn off the display automatically after 30 seconds like before. May I know how I can fix it? 

I am using the following command to connect my device.
```bash
scrcpy --turn-screen-off --stay-awake
```

**Comment by rom1v** [comment]
What is the result of:

    adb shell settings get global stay_on_while_plugged_in

?

**Comment by taicaile** [comment]
> What is the result of:
> 
> ```
> adb shell settings get global stay_on_while_plugged_in
> ```
> 
> ?

Hello, the output is 
```bash
7
```

**Comment by rom1v** [comment]
OK, so the initial value was not restored.

I think this may happen in two cases:
 - you run two instances of scrcpy with `--stay-awake` simultaneously, with interlaced start/stop (start 1, start 2, stop 1, stop 2)
 - some devices kill the cleanup process after ~1 second after the main process terminates (this is a bug on the device, I have one device with this issue), so it does not have time to restore the initial value.

You could restore the value manually from your device settings (I don't remembet where exactly), or you can execute:

    adb shell settings put global stay_on_while_plugged_in 0

**Comment by taicaile** [comment]
> OK, so the initial value was not restored.
> 
> I think this may happen in two cases:
> 
> * you run two instances of scrcpy with `--stay-awake` simultaneously, with interlaced start/stop (start 1, start 2, stop 1, stop 2)
> * some devices kill the cleanup process after ~1 second after the main process terminates (this is a bug on the device, I have one device with this issue), so it does not have time to restore the initial value.
> 
> You could restore the value manually from your device settings (I don't remembet where exactly), or you can execute:
> 
> ```
> adb shell settings put global stay_on_while_plugged_in 0
> ```

Thank you. Now it backs to normal.
