### ISSUE TITLE
WASD keyboard not working with Minecraft pocket edition

### ISSUE THREAD

**Issue by xcloudx12345** [Genymobile/scrcpy#2520]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: 1.18
 - installation method:Windows release
 - device model: Mi MIX 3
 - Android version: Android 11

**Describe the bug**
keyboard not working with Minecraft pocket edition, input when chating working fine, but i can't move with WASD, so i found the solution by using wifi keyboard app from CH play, and it working, the mouse control are OK 
```

**Comment by xcloudx12345** [comment]
it just working now =|

**Comment by Pancakes0** [comment]
i have this exact issue, can you share a detailed solution?
