### ISSUE TITLE
[Feature Request] Paste device clipboard (ASCII) to computer

### ISSUE THREAD

**Issue by pundoo** [Genymobile/scrcpy#253]
Would this be possible to implement?

**Comment by rom1v** [comment]
This is a duplicate of https://github.com/Genymobile/scrcpy/issues/145 (so I'm closing this one).

> Would this be possible to implement?

It has the same implications as https://github.com/Genymobile/scrcpy/issues/8#issuecomment-371819839.

**Comment by rom1v** [comment]
Implemented on `dev` branch. See https://github.com/Genymobile/scrcpy/issues/145#issuecomment-497484917.
