### ISSUE TITLE
Android Support (for the viewer)

### ISSUE THREAD

**Issue by MartenvanWezel** [Genymobile/scrcpy#2534]
- [X] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
My Android TV is often used without screen (playing music). To see what's going on it would be great to view the screen.

**Describe the solution you'd like**
Android apk/binary

**Describe alternatives you've considered**
None exist, as far as I know.

**Comment by rom1v** [comment]
Duplicate of #100.
