### ISSUE TITLE
scrcpy -S parameter have BUG!!!

### ISSUE THREAD

**Issue by hsiayuchih** [Genymobile/scrcpy#2542]
After starting with the scrcpy -S parameter, the screen can be turned off to start, but the screen will go black after about four or five minutes, and then the phone must be on to display it in real time...

**Comment by rom1v** [comment]
> but the screen will go black after about four or five minutes,

It goes black because it goes to sleep (whether the screen is turned off or not), doesn't it?

**Comment by hsiayuchih** [comment]
> > 但是大约四五分钟后屏幕会变黑，
> 
> 它变黑是因为它进入睡眠状态（无论屏幕是否关闭），不是吗？

This is indeed the case, thank you!
