### ISSUE TITLE
add support for Arabic characters 

### ISSUE THREAD

**Issue by Fighteros** [Genymobile/scrcpy#2548]
hey there i have noticed that Arabic characters aren't identified by the server 
would you please add Arabic support for input characters 

![image](https://user-images.githubusercontent.com/59248007/128609697-aaa73342-4b1e-48a5-8118-8e489309303e.png)

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#special-characters-do-not-work

See #37.
