### ISSUE TITLE
Scandinavian keyboard layout support.

### ISSUE THREAD

**Issue by telometto** [Genymobile/scrcpy#2549]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
When I try to use the letters æ, ø, å, I get the errors `Could not inject char u+00e6`, `Could not inject char u+00f8`, `Could not inject char u+00e5`, respectively.

**Describe the solution you'd like**
Not a problem per sé, but it would be nice to add support for Scandinavian/Norwegian keyboard layout.

**Describe alternatives you've considered**
The alternative is to press these letters on the virtual keyboard using the mouse.

**Additional context**
x

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#special-characters-do-not-work

See #37.
