### ISSUE TITLE
shortcut for expand notifications panel doesn't work

### ISSUE THREAD

**Issue by Peter-maximus** [Genymobile/scrcpy#2551]
unfortunately doesn't work on oneplus 3, Android 8.0, Windows ADB, scrcpy 1.18

```
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: expandNotificationsPanel []
        at java.lang.Class.getMethod(Class.java:2068)
        at java.lang.Class.getMethod(Class.java:1690)
        at com.genymobile.scrcpy.wrappers.StatusBarManager.getExpandNotificationsPanelMethod(StatusBarManager.java:24)
        at com.genymobile.scrcpy.wrappers.StatusBarManager.expandNotificationsPanel(StatusBarManager.java:52)
        at com.genymobile.scrcpy.Device.expandNotificationPanel(Device.java:215)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:108)
        at com.genymobile.scrcpy.Controller.control(Controller.java:71)
        at com.genymobile.scrcpy.Server$2.run(Server.java:100)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by rom1v** [comment]
They probably customized the method in their private ROM. Could you add a log to find the existing methods if you know how to?

**Comment by Peter-maximus** [comment]
i provided the output from console.
how can i create such a log?

**Comment by Peter-maximus** [comment]
Any update please?

**Comment by rom1v** [comment]
Take this file, replace it in the v1.19:

[`scrcpy-server`](https://tmp.rom1v.com/scrcpy/2551/1/scrcpy-server) _sha256:d770434cc519d7fe26efe247788200a07c7c2c4bd087c8c81a52247d1284e4ce_

Then run `scrcpy`, then press `Alt`+`n` once. It will output many things in the console. Please post the result.

<details><summary>diff</summary>

```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/wrappers/StatusBarManager.java b/server/src/main/java/com/genymobile/scrcpy/wrappers/StatusBarManager.java
index 5b1e5f5e..52b1a90e 100644
--- a/server/src/main/java/com/genymobile/scrcpy/wrappers/StatusBarManager.java
+++ b/server/src/main/java/com/genymobile/scrcpy/wrappers/StatusBarManager.java
@@ -20,6 +20,8 @@ public class StatusBarManager {
     }
 
     private Method getExpandNotificationsPanelMethod() throws NoSuchMethodException {
+        for (Method method : manager.getClass().getMethods())
+            System.err.println("=== " + method);
         if (expandNotificationsPanelMethod == null) {
             expandNotificationsPanelMethod = manager.getClass().getMethod("expandNotificationsPanel");
         }
```

</details>

**Comment by Peter-maximus** [comment]
here you go:

--------------

 

 

[server] INFO: Device: OnePlus ONEPLUS A3003 (Android 8.0.0)

INFO: Renderer: direct3d

INFO: Initial texture: 576x1024

=== public void
com.android.internal.statusbar.IStatusBarService$Stub$Proxy.addT

ile(android.content.ComponentName) throws android.os.RemoteException

=== public android.os.IBinder
com.android.internal.statusbar.IStatusBarService$S

tub$Proxy.asBinder()

=== public void
com.android.internal.statusbar.IStatusBarService$Stub$Proxy.clea

rNotificationEffects() throws android.os.RemoteException

=== public void
com.android.internal.statusbar.IStatusBarService$Stub$Proxy.clic

kTile(android.content.ComponentName) throws android.os.RemoteException

=== public void
com.android.internal.statusbar.IStatusBarService$Stub$Proxy.coll

apsePanels() throws android.os.RemoteException

=== public void
com.android.internal.statusbar.IStatusBarService$Stub$Proxy.disa

ble(int,android.os.IBinder,java.lang.String) throws
android.os.RemoteException

=== public void
com.android.internal.statusbar.IStatusBarService$Stub$Proxy.disa

ble2(int,android.os.IBinder,java.lang.String) throws
android.os.RemoteException

=== public void
com.android.internal.statusbar.IStatusBarService$Stub$Proxy.disa

ble2ForUser(int,android.os.IBinder,java.lang.String,int) throws
android.os.Remot

eException

=== public void
com.android.internal.statusbar.IStatusBarService$Stub$Proxy.disa

bleForUser(int,android.os.IBinder,java.lang.String,int) throws
android.os.Remote

Exception

=== public boolean java.lang.Object.equals(java.lang.Object)

=== public void
com.android.internal.statusbar.IStatusBarService$Stub$Proxy.expa

ndNotificationsPanel(int) throws android.os.RemoteException

=== public void
com.android.internal.statusbar.IStatusBarService$Stub$Proxy.expa

ndSettingsPanel(java.lang.String) throws android.os.RemoteException

=== public final java.lang.Class java.lang.Object.getClass()

=== public java.lang.String
com.android.internal.statusbar.IStatusBarService$Stu

b$Proxy.getInterfaceDescriptor()

=== public java.util.List
com.android.internal.statusbar.IStatusBarService$Stub$

Proxy.getLockedPackageList() throws android.os.RemoteException

=== public void
com.android.internal.statusbar.IStatusBarService$Stub$Proxy.hand

leSystemNavigationKey(int) throws android.os.RemoteException

=== public int java.lang.Object.hashCode()

=== public final native void java.lang.Object.notify()

=== public final native void java.lang.Object.notifyAll()

=== public void
com.android.internal.statusbar.IStatusBarService$Stub$Proxy.noti

fyNavBarColorChanged(int,java.lang.String) throws android.os.RemoteException

=== public void
com.android.internal.statusbar.IStatusBarService$Stub$Proxy.onCl

earAllNotifications(int) throws android.os.RemoteException

=== public void
com.android.internal.statusbar.IStatusBarService$Stub$Proxy.onGl

obalActionsHidden() throws android.os.RemoteException

=== public void
com.android.internal.statusbar.IStatusBarService$Stub$Proxy.onGl

obalActionsShown() throws android.os.RemoteException

=== public void
com.android.internal.statusbar.IStatusBarService$Stub$Proxy.onNo

tificationActionClick(java.lang.String,int) throws
android.os.RemoteException

=== public void
com.android.internal.statusbar.IStatusBarService$Stub$Proxy.onNo

tificationClear(java.lang.String,java.lang.String,int,int) throws
android.os.Rem

oteException

=== public void
com.android.internal.statusbar.IStatusBarService$Stub$Proxy.onNo

tificationClick(java.lang.String) throws android.os.RemoteException

=== public void
com.android.internal.statusbar.IStatusBarService$Stub$Proxy.onNo

tificationError(java.lang.String,java.lang.String,int,int,int,java.lang.Stri
ng,i

nt) throws android.os.RemoteException

=== public void
com.android.internal.statusbar.IStatusBarService$Stub$Proxy.onNo

tificationExpansionChanged(java.lang.String,boolean,boolean) throws
android.os.R

emoteException

=== public void
com.android.internal.statusbar.IStatusBarService$Stub$Proxy.onNo

tificationVisibilityChanged(com.android.internal.statusbar.NotificationVisib
ilit

y[],com.android.internal.statusbar.NotificationVisibility[]) throws
android.os.R

emoteException

=== public void
com.android.internal.statusbar.IStatusBarService$Stub$Proxy.onPa

nelHidden() throws android.os.RemoteException

=== public void
com.android.internal.statusbar.IStatusBarService$Stub$Proxy.onPa

nelRevealed(boolean,int) throws android.os.RemoteException

=== public void
com.android.internal.statusbar.IStatusBarService$Stub$Proxy.rebo

ot(boolean) throws android.os.RemoteException

=== public void
com.android.internal.statusbar.IStatusBarService$Stub$Proxy.regi

sterStatusBar(com.android.internal.statusbar.IStatusBar,java.util.List,java.
util

.List,int[],java.util.List,android.graphics.Rect,android.graphics.Rect)
throws a

ndroid.os.RemoteException

=== public void
com.android.internal.statusbar.IStatusBarService$Stub$Proxy.remT

ile(android.content.ComponentName) throws android.os.RemoteException

=== public void
com.android.internal.statusbar.IStatusBarService$Stub$Proxy.remo

veIcon(java.lang.String) throws android.os.RemoteException

=== public void
com.android.internal.statusbar.IStatusBarService$Stub$Proxy.setI

con(java.lang.String,java.lang.String,int,int,java.lang.String) throws
android.o

s.RemoteException

=== public void
com.android.internal.statusbar.IStatusBarService$Stub$Proxy.setI

conVisibility(java.lang.String,boolean) throws android.os.RemoteException

=== public void
com.android.internal.statusbar.IStatusBarService$Stub$Proxy.setI

meWindowStatus(android.os.IBinder,int,int,boolean) throws
android.os.RemoteExcep

tion

=== public void
com.android.internal.statusbar.IStatusBarService$Stub$Proxy.setS

ystemUiVisibility(int,int,java.lang.String) throws
android.os.RemoteException

=== public void
com.android.internal.statusbar.IStatusBarService$Stub$Proxy.shut

down() throws android.os.RemoteException

=== public java.lang.String java.lang.Object.toString()

=== public final native void java.lang.Object.wait() throws
java.lang.Interrupte

dException

=== public final void java.lang.Object.wait(long) throws
java.lang.InterruptedEx

ception

=== public final native void java.lang.Object.wait(long,int) throws
java.lang.In

terruptedException

[server] ERROR: Could not invoke method

java.lang.NoSuchMethodException: expandNotificationsPanel []

        at java.lang.Class.getMethod(Class.java:2068)

        at java.lang.Class.getMethod(Class.java:1690)

        at
com.genymobile.scrcpy.wrappers.StatusBarManager.getExpandNotification

sPanelMethod(StatusBarManager.java:26)

        at
com.genymobile.scrcpy.wrappers.StatusBarManager.expandNotificationsPa

nel(StatusBarManager.java:54)

        at
com.genymobile.scrcpy.Device.expandNotificationPanel(Device.java:215)

 

        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:108)

        at com.genymobile.scrcpy.Controller.control(Controller.java:71)

        at com.genymobile.scrcpy.Server$2.run(Server.java:100)

        at java.lang.Thread.run(Thread.java:764)

 

Dakujem.

 

S pozdravom

 

Peter Ivan

**Comment by Peter-maximus** [comment]
[server] INFO: Device: OnePlus ONEPLUS A3003 (Android 8.0.0)
INFO: Renderer: direct3d
INFO: Initial texture: 576x1024
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.addT
ile(android.content.ComponentName) throws android.os.RemoteException
=== public android.os.IBinder com.android.internal.statusbar.IStatusBarService$S
tub$Proxy.asBinder()
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.clea
rNotificationEffects() throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.clic
kTile(android.content.ComponentName) throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.coll
apsePanels() throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.disa
ble(int,android.os.IBinder,java.lang.String) throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.disa
ble2(int,android.os.IBinder,java.lang.String) throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.disa
ble2ForUser(int,android.os.IBinder,java.lang.String,int) throws android.os.Remot
eException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.disa
bleForUser(int,android.os.IBinder,java.lang.String,int) throws android.os.Remote
Exception
=== public boolean java.lang.Object.equals(java.lang.Object)
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.expa
ndNotificationsPanel(int) throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.expa
ndSettingsPanel(java.lang.String) throws android.os.RemoteException
=== public final java.lang.Class java.lang.Object.getClass()
=== public java.lang.String com.android.internal.statusbar.IStatusBarService$Stu
b$Proxy.getInterfaceDescriptor()
=== public java.util.List com.android.internal.statusbar.IStatusBarService$Stub$
Proxy.getLockedPackageList() throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.hand
leSystemNavigationKey(int) throws android.os.RemoteException
=== public int java.lang.Object.hashCode()
=== public final native void java.lang.Object.notify()
=== public final native void java.lang.Object.notifyAll()
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.noti
fyNavBarColorChanged(int,java.lang.String) throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.onCl
earAllNotifications(int) throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.onGl
obalActionsHidden() throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.onGl
obalActionsShown() throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.onNo
tificationActionClick(java.lang.String,int) throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.onNo
tificationClear(java.lang.String,java.lang.String,int,int) throws android.os.Rem
oteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.onNo
tificationClick(java.lang.String) throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.onNo
tificationError(java.lang.String,java.lang.String,int,int,int,java.lang.String,i
nt) throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.onNo
tificationExpansionChanged(java.lang.String,boolean,boolean) throws android.os.R
emoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.onNo
tificationVisibilityChanged(com.android.internal.statusbar.NotificationVisibilit
y[],com.android.internal.statusbar.NotificationVisibility[]) throws android.os.R
emoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.onPa
nelHidden() throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.onPa
nelRevealed(boolean,int) throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.rebo
ot(boolean) throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.regi
sterStatusBar(com.android.internal.statusbar.IStatusBar,java.util.List,java.util
.List,int[],java.util.List,android.graphics.Rect,android.graphics.Rect) throws a
ndroid.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.remT
ile(android.content.ComponentName) throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.remo
veIcon(java.lang.String) throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.setI
con(java.lang.String,java.lang.String,int,int,java.lang.String) throws android.o
s.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.setI
conVisibility(java.lang.String,boolean) throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.setI
meWindowStatus(android.os.IBinder,int,int,boolean) throws android.os.RemoteExcep
tion
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.setS
ystemUiVisibility(int,int,java.lang.String) throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.shut
down() throws android.os.RemoteException
=== public java.lang.String java.lang.Object.toString()
=== public final native void java.lang.Object.wait() throws java.lang.Interrupte
dException
=== public final void java.lang.Object.wait(long) throws java.lang.InterruptedEx
ception
=== public final native void java.lang.Object.wait(long,int) throws java.lang.In
terruptedException
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: expandNotificationsPanel []
        at java.lang.Class.getMethod(Class.java:2068)
        at java.lang.Class.getMethod(Class.java:1690)
        at com.genymobile.scrcpy.wrappers.StatusBarManager.getExpandNotification
sPanelMethod(StatusBarManager.java:26)
        at com.genymobile.scrcpy.wrappers.StatusBarManager.expandNotificationsPa
nel(StatusBarManager.java:54)
        at com.genymobile.scrcpy.Device.expandNotificationPanel(Device.java:215)

        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:108)
        at com.genymobile.scrcpy.Controller.control(Controller.java:71)
        at com.genymobile.scrcpy.Server$2.run(Server.java:100)
        at java.lang.Thread.run(Thread.java:764)

**Comment by Peter-maximus** [comment]
[server] INFO: Device: OnePlus ONEPLUS A3003 (Android 8.0.0)
INFO: Renderer: direct3d
INFO: Initial texture: 576x1024
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.addT
ile(android.content.ComponentName) throws android.os.RemoteException
=== public android.os.IBinder com.android.internal.statusbar.IStatusBarService$S
tub$Proxy.asBinder()
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.clea
rNotificationEffects() throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.clic
kTile(android.content.ComponentName) throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.coll
apsePanels() throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.disa
ble(int,android.os.IBinder,java.lang.String) throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.disa
ble2(int,android.os.IBinder,java.lang.String) throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.disa
ble2ForUser(int,android.os.IBinder,java.lang.String,int) throws android.os.Remot
eException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.disa
bleForUser(int,android.os.IBinder,java.lang.String,int) throws android.os.Remote
Exception
=== public boolean java.lang.Object.equals(java.lang.Object)
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.expa
ndNotificationsPanel(int) throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.expa
ndSettingsPanel(java.lang.String) throws android.os.RemoteException
=== public final java.lang.Class java.lang.Object.getClass()
=== public java.lang.String com.android.internal.statusbar.IStatusBarService$Stu
b$Proxy.getInterfaceDescriptor()
=== public java.util.List com.android.internal.statusbar.IStatusBarService$Stub$
Proxy.getLockedPackageList() throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.hand
leSystemNavigationKey(int) throws android.os.RemoteException
=== public int java.lang.Object.hashCode()
=== public final native void java.lang.Object.notify()
=== public final native void java.lang.Object.notifyAll()
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.noti
fyNavBarColorChanged(int,java.lang.String) throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.onCl
earAllNotifications(int) throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.onGl
obalActionsHidden() throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.onGl
obalActionsShown() throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.onNo
tificationActionClick(java.lang.String,int) throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.onNo
tificationClear(java.lang.String,java.lang.String,int,int) throws android.os.Rem
oteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.onNo
tificationClick(java.lang.String) throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.onNo
tificationError(java.lang.String,java.lang.String,int,int,int,java.lang.String,i
nt) throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.onNo
tificationExpansionChanged(java.lang.String,boolean,boolean) throws android.os.R
emoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.onNo
tificationVisibilityChanged(com.android.internal.statusbar.NotificationVisibilit
y[],com.android.internal.statusbar.NotificationVisibility[]) throws android.os.R
emoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.onPa
nelHidden() throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.onPa
nelRevealed(boolean,int) throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.rebo
ot(boolean) throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.regi
sterStatusBar(com.android.internal.statusbar.IStatusBar,java.util.List,java.util
.List,int[],java.util.List,android.graphics.Rect,android.graphics.Rect) throws a
ndroid.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.remT
ile(android.content.ComponentName) throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.remo
veIcon(java.lang.String) throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.setI
con(java.lang.String,java.lang.String,int,int,java.lang.String) throws android.o
s.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.setI
conVisibility(java.lang.String,boolean) throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.setI
meWindowStatus(android.os.IBinder,int,int,boolean) throws android.os.RemoteExcep
tion
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.setS
ystemUiVisibility(int,int,java.lang.String) throws android.os.RemoteException
=== public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.shut
down() throws android.os.RemoteException
=== public java.lang.String java.lang.Object.toString()
=== public final native void java.lang.Object.wait() throws java.lang.Interrupte
dException
=== public final void java.lang.Object.wait(long) throws java.lang.InterruptedEx
ception
=== public final native void java.lang.Object.wait(long,int) throws java.lang.In
terruptedException
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: expandNotificationsPanel []
        at java.lang.Class.getMethod(Class.java:2068)
        at java.lang.Class.getMethod(Class.java:1690)
        at com.genymobile.scrcpy.wrappers.StatusBarManager.getExpandNotification
sPanelMethod(StatusBarManager.java:26)
        at com.genymobile.scrcpy.wrappers.StatusBarManager.expandNotificationsPa
nel(StatusBarManager.java:54)
        at com.genymobile.scrcpy.Device.expandNotificationPanel(Device.java:215)

        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:108)
        at com.genymobile.scrcpy.Controller.control(Controller.java:71)
        at com.genymobile.scrcpy.Server$2.run(Server.java:100)
        at java.lang.Thread.run(Thread.java:764)

**Comment by rom1v** [comment]
>     public void com.android.internal.statusbar.IStatusBarService$Stub$Proxy.expandNotificationsPanel(int) throws android.os.RemoteException

As expected, they modified the method in the custom ROM (they added an `int` parameter, but I don't know what it is).

Let's try to just pass 0:

[`scrcpy-server`](https://tmp.rom1v.com/scrcpy/2551/2/scrcpy-server) _sha256:df8c2075769796c7b12801bfc89b381dabfdfe91199c7aa413c5ed8e0533acb1_

<details><summary>diff</summary>

```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/wrappers/StatusBarManager.java b/server/src/main/java/com/genymobile/scrcpy/wrappers/StatusBarManager.java
index 5b1e5f5e..0ddd8311 100644
--- a/server/src/main/java/com/genymobile/scrcpy/wrappers/StatusBarManager.java
+++ b/server/src/main/java/com/genymobile/scrcpy/wrappers/StatusBarManager.java
@@ -11,6 +11,7 @@ public class StatusBarManager {
 
     private final IInterface manager;
     private Method expandNotificationsPanelMethod;
+    private boolean expandNotificationPanelMethodCustomVersion;
     private Method expandSettingsPanelMethod;
     private boolean expandSettingsPanelMethodNewVersion = true;
     private Method collapsePanelsMethod;
@@ -21,7 +22,13 @@ public class StatusBarManager {
 
     private Method getExpandNotificationsPanelMethod() throws NoSuchMethodException {
         if (expandNotificationsPanelMethod == null) {
-            expandNotificationsPanelMethod = manager.getClass().getMethod("expandNotificationsPanel");
+            try {
+                expandNotificationsPanelMethod = manager.getClass().getMethod("expandNotificationsPanel");
+            } catch (NoSuchMethodException e) {
+                // https://github.com/Genymobile/scrcpy/issues/2551
+                expandNotificationsPanelMethod = manager.getClass().getMethod("expandNotificationsPanel", int.class);
+                expandNotificationPanelMethodCustomVersion = true;
+            }
         }
         return expandNotificationsPanelMethod;
     }
@@ -50,7 +57,11 @@ public class StatusBarManager {
     public void expandNotificationsPanel() {
         try {
             Method method = getExpandNotificationsPanelMethod();
-            method.invoke(manager);
+            if (expandNotificationPanelMethodCustomVersion) {
+                method.invoke(manager, 0);
+            } else {
+                method.invoke(manager);
+            }
         } catch (InvocationTargetException | IllegalAccessException | NoSuchMethodException e) {
             Ln.e("Could not invoke method", e);
         }
```

</details>

**Comment by Peter-maximus** [comment]
great! it works.
what can i do to have it working also in the next versions of the app?
is iti possible to somehow implement it into scrcpy-server bundled with regular version of the app?

**Comment by rom1v** [comment]
> great! it works.

:+1:

> what can i do to have it working also in the next versions of the app?
> is it possible to somehow implement it into scrcpy-server bundled with regular version of the app?

I just merged in into `dev`, so it will be in the next release: fa100b814b0d1866dbf30efbcfd24334dc8ddce2
