### ISSUE TITLE
Full swipe doesn' work

### ISSUE THREAD

**Issue by Peter-maximus** [Genymobile/scrcpy#2552]
oneplus 3, Android 8.0, Windows ADB, scrcpy 1.18

Swipe to the very left on application switch screen doesn't work.
It moves the app just to the very left and then place it back.
It doesn't work even in fullscreen (alt+f)

However swipe notification (remove it) in notification panel works without any issues.

**Comment by Peter-maximus** [comment]
Any update?

**Comment by rom1v** [comment]
The mouse events are forwarded to the device, what they do on the device is managed by the device, so I don't think scrcpy could do anything about it.

Just for info, could you make a video of your problem (what it should do VS what it does)?

**Comment by Peter-maximus** [comment]
here it is. it should swipe (close the app), however it just spring back...
if i do it by thumb on phone it works without any issues.

https://user-images.githubusercontent.com/73565689/132917618-1d03a1f4-111c-4050-8506-006190e89a23.mp4

**Comment by rom1v** [comment]
OK, thank you for the video. I don't know, maybe the ROM does not rely only on mouse events to trigger the swipe (maybe some sensors on the borders). I really don't know.

**Comment by Peter-maximus** [comment]
just to remind.
Swipe notification from notification panel works without any issues even in scrcpy...
so it is definitely something related to recent applications list.

**Comment by Peter-maximus** [comment]
any update?

**Comment by Peter-maximus** [comment]
any update please?

**Comment by Peter-maximus** [comment]
.
