### ISSUE TITLE
Make the render window a native Wayland window

### ISSUE THREAD

**Issue by PatrickJosh** [Genymobile/scrcpy#2559]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
Currently, when using fractional scaling in GNOME with Wayland, the render window is slightly blurry. This happens to all applications that use XWayland instead of native Wayland as display server.

**Describe the solution you'd like**
Make the render window a native Wayland window so that it does not use the XWayland server anymore.

**Describe alternatives you've considered**
An alternative for me would be not to use Wayland or fractional scaling, but I do not consider both as sensible options. I have not thought about other options, I do not know if there are any.

**Additional context**
A screenshot to show the slight blurriness. You can see it best if you compare the text of the terminal with the headline of the render window.
![grafik](https://user-images.githubusercontent.com/32456639/129202856-b2f0387f-3ad0-4025-937f-1bb039247714.png)

**Comment by rom1v** [comment]
I guess this should be handled by SDL, could you please also report the problem to them?

**Comment by PatrickJosh** [comment]
Sure, sorry. I did not know that.

**Comment by PatrickJosh** [comment]
With a bit of search, I found [this pull request](https://github.com/libsdl-org/SDL/pull/4306) in SDL's repository. With `SDL_VIDEODRIVER=wayland scrcpy`, it is indeed possible to run scrcpy with Wayland. However, the window does not have any decorations then, but the [corresponding pull request](https://github.com/libsdl-org/SDL/pull/4068) is merged. Is this still an issue with SDL or now with scrcpy?

**Comment by PatrickJosh** [comment]
I manually fixed it by building scrcpy myself with having `libdecor` development files installed. Now the window has decorations. Maybe future versions of scrcpy could include `libdecor` as a requirement so that decorations are available with the prebuild binaries as well?

**Comment by PatrickJosh** [comment]
I noticed, directly after I have written this, that the decorations are also available with the prebuild version, at least on Fedora, when `libdecor` is installed. So, `libdecor` should maybe be a dependency for the installation of scrcpy on Linux, at least on the distros that use Wayland by default now (Fedora, Ubuntu)? If this is not an option, in my opinion at least a note in the FAQ should be added.

**Comment by rom1v** [comment]
d6aaa5bf9aa3710660c683b6e3e0ed971ee44af5

**Comment by zenofile** [comment]
I added `libdecor` as runtime dependency for https://copr.fedorainfracloud.org/coprs/zeno/scrcpy/.

**Comment by rom1v** [comment]
@zenofile Thanks.

May I remove:

> On some distributions (at least Fedora), the package `libdecor` must be installed manually.

from the FAQ then?

**Comment by zenofile** [comment]
> @zenofile Thanks.
> 
> May I remove:
> 
> > On some distributions (at least Fedora), the package `libdecor` must be installed manually.
> 
> from the FAQ then?

If the user decides to use the prebuilt binaries instead of the copr repository (or when using other distributions?), it might still be necessary to install `libdecor` manually. So I would recommend altering the text to something like:

> On distributions that do not include `libdecor` as a runtime dependency when installing scrcpy via the package manager or when using the prebuilt binaries, it may need to be installed manually.

instead of removing it completly.

**Comment by xerpi** [comment]
> With a bit of search, I found [this pull request](https://github.com/libsdl-org/SDL/pull/4306) in SDL's repository. With `SDL_VIDEODRIVER=wayland scrcpy`, it is indeed possible to run scrcpy with Wayland. However, the window does not have any decorations then, but the [corresponding pull request](https://github.com/libsdl-org/SDL/pull/4068) is merged. Is this still an issue with SDL or now with scrcpy?

You can override the SDL an executable is linked to (scrcpy in your case) and provide your own SDL .so:
```
SDL_VIDEODRIVER=wayland SDL_DYNAMIC_API=/path/to/your/SDL/build/.libs/libSDL2-2.0.so.0
```
It might be useful while waiting until the latest SDL version reaches the repos of the distros.
