### ISSUE TITLE
Facing a weird issue with wireless adb

### ISSUE THREAD

**Issue by peterge1998** [Genymobile/scrcpy#2565]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Fedora 34
 - scrcpy version: 1.18
 - installation method: snap
 - device model: OnePlus 8 LineageOS
 - Android version: 11

**Describe the bug**

I can not run scrcpy via wireless adb. I ran the export command because it was posted in one of the issues:
```
➜  ~ adb connect 10.0.8.50:5555
connected to 10.0.8.50:5555
➜  ~ adb devices               
List of devices attached
10.0.8.50:5555	device
➜  ~ export ADB=$(which adb)
➜  ~ echo $ADB              
/usr/bin/adb
➜  ~ scrcpy
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
INFO: scrcpy 1.18 <https://github.com/Genymobile/scrcpy>
exec: No such file or directory
ERROR: Command not found: [/usr/bin/adb], [push], [/usr/local/share/scrcpy/scrcpy-server], [/data/local/tmp/scrcpy-server.jar]
ERROR: (make 'adb' accessible from your PATH or define its fullpath in the ADB environment variable)
INFO: You may install 'adb' by "apt install adb"
ERROR: Could not execute "adb push"
```

**Comment by rom1v** [comment]
Try a non snap version, snap runs in a container with chroots.

**Comment by peterge1998** [comment]
thank you, oneplus='adb connect 10.0.8.50:5555 && scrcpy' in my .zshrc works!
