### ISSUE TITLE
Scrcpy crashes in win7 64bit unhandled win32 exception

### ISSUE THREAD

**Issue by josuesoto1** [Genymobile/scrcpy#257]
Scrcpy used to work fine in win7 64 bit. Recently I only get a windows crash warning and application does not start. 
First the following message is displayed in CMD
scrcpy-server.jar: 1 file pushed. 1.2 MB/s (19342 bytes in 0.016s)

After that the next message is displayed by windows:
scrcpy.exe has stopped working. A problem caused the program to stop working correctly. 
An unhandled win32 exception ocurred in scrcpy.exe [16656] [16360]

I had reinstalled the drivers, adb is working fine (adb devices). I also tested different scrcpy versions without any success. 

I also tested changing resolution option for scrcpy. 

any ideas how to solve this problem?

**Comment by rom1v** [comment]
Did you take the 32 bits version?

https://github.com/Genymobile/scrcpy/blob/master/README.md#windows

**Comment by josuesoto1** [comment]
Is there a log file where I can check where in the process is the failure?
how can I get additional details of this problem?

**Comment by rom1v** [comment]
> Is there a log file where I can check where in the process is the failure?
> how can I get additional details of this problem?

I don't know, it's probably a crash in the video drivers or something (see https://github.com/Genymobile/scrcpy/issues/158).

Does it work with older versions?

**Comment by josuesoto1** [comment]
I had Updated the video driver but issue has not been solved.
I tried previous versions both 32 adn 64 bit with the same message.

**Comment by eleetsrelyt** [comment]
I have this same issue. Win 7 64 bit, scrcpy v1.4 32 bit and 64 bit, pixel 2 XL. 

adb devices shows my pixel is connected, but when I run scrcpy I get a crash dialoge after the server jar push on the console.

**Comment by eleetsrelyt** [comment]
I've never used scrcpy before. It turned out to be a video driver issue. When my pc goes to sleep it messes with the video driver. A PC restart fixed the issue.

**Comment by josuesoto1** [comment]
I tested my phone in a HP computer with windows 10 and works fine. I had upgraded my windows 7 to windows 10 in a Dell laptop but the error still present. 
Seems that is an issue with the USB connection. Is there a command to verify proper communication between PC and mobile? any idea to verify read/write or access permissions?
Note that when I write ADB devices my phone is properly detected.

**Comment by rom1v** [comment]
Does it still happen?

**Comment by MetalGearSolidNerd** [comment]
I faced a similiar issue on my Win 10 PC and the culprit seems to be enterprise software from Digital Guardian which blocks the software. The only way to get around this is to have the Enterpise IT team create a whitelist for scrcpy in Digital Guardian.
