### ISSUE TITLE
Support Older Android Phone: Samsung GT-S7275

### ISSUE THREAD

**Issue by franva** [Genymobile/scrcpy#2576]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rom1v** [comment]
If it's Android >= 5, it is supported. If it's Android < 5, it's not and will never be: https://github.com/Genymobile/scrcpy/issues/98#issuecomment-379046536
