### ISSUE TITLE
The picture is blurred.

### ISSUE THREAD

**Issue by drc5521** [Genymobile/scrcpy#2577]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
When the zoom of the computer is not 100%, the picture is very blurry. You need to manually adjust the zoom of the computer to 100% to make the picture clear. It is very troublesome to adjust it every time you use it.

**Describe the solution you'd like**
Can it be repaired so that it will automatically make the picture clear even if it is not 100%.

**Describe alternatives you've considered**

**Additional context**
![display](https://user-images.githubusercontent.com/55195642/130315742-87318a50-e33f-4856-b081-cab9d2ff96a2.png)

**Comment by rom1v** [comment]
On Windows?

See https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#the-quality-is-low

If you press Alt-g, the quality is perfect, correct?

**Comment by drc5521** [comment]
> On Windows?
> 
> See https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#the-quality-is-low
> 
> If you press Alt-g, the quality is perfect, correct?

If press Alt-g,the quality is perfect，but the window is big so that cannot see other parts. 

"scrcpy.exe > Properties > Compatibility > Change high DPI settings > Override high DPI scaling behavior > Scaling performed by: Application." This way solution my problem. Thank you rom1v.

**Comment by ApexStealer33** [comment]
How can i override high dpi scaling behaviour in linux (zorin os)?

**Comment by rom1v** [comment]
Do you experience any problem on Linux?

**Comment by rom1v** [comment]
How do you know that it is related to dpi scaling?

Could you please post a screenshot?

**Comment by ApexStealer33** [comment]
I will post the screenshot tommorow. 
I have tried almost everything and only some of the possible solutions are remaining. 
I have tried going back to old version(tested on v1.24 and v1.12), tried compiling without hidpi support (got some error in the process), tried all the encoders, tried disabling trilinear filtering
Probably, Only this one is remaining as the possible solution.

**Comment by ApexStealer33** [comment]
I have used scrcpy earlier (probably 1 year back) and it was working great that time idk why it is not working now.

**Comment by ApexStealer33** [comment]
Also i am using android 13 and zorin os 16.3 based on ubuntu 22.04

**Comment by rom1v** [comment]
If you record (`scrcpy --record=file.mp4`), is the recorded file ok?

**Comment by rom1v** [comment]
What is the full terminal output when you run `scrcpy`?

**Comment by ApexStealer33** [comment]
Problem solved 
I used `scrcpy --video-bit-rate 20M --max-fps 15 --render-driver=opengles2 -m1250`
Graphics were more clear in this although not crystal clear in fullscreen but i can manage
