### ISSUE TITLE
There is a bug that is When I try to open Scrcpy it crashes ! It's not my laptop fault but in fact there is a bug that's so annoying ! 
Laptop Specs : 

Ram : 2 GB 
Processor : AMD A4 VISION 
PLATFORM : WINDOWS 10 ENTERPRISE 

PLEASE 🙏 🙏🙏 FIX IT!

### ISSUE THREAD

**Issue by SHITIJHALDER** [Genymobile/scrcpy#2578]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
What do you mean by "crash"? What is the output in the console when you run `scrcpy-console.bat` (I guess you are on Windows)?

**Comment by SHITIJHALDER** [comment]
> What do you mean by "crash"? What is the output in the console when you run `scrcpy-console.bat` (I guess you are on Windows)?

Yes I am on Windows and the crash means : When I click open it shows a black screen for a second and then it crashes ! 1 Month ago it was running fine and so smooth but now it's not even opening ! 

Please help;

**Comment by rom1v** [comment]
> Please help;

I did. Please re-read my previous comment and answer the 2nd question :wink:

**Comment by SHITIJHALDER** [comment]
> > What do you mean by "crash"? What is the output in the console when you run `scrcpy-console.bat` (I guess you are on Windows)?
> 
> Yes I am on Windows and the crash means : When I click open it shows a black screen for a second and then it crashes ! 1 Month ago it was running fine and so smooth but now it's not even opening ! 
> 
> Please help;

When I run `scrcpy-console.bat` the output is `ERROR : Could not execute "adb push"

This is the output ! Help me!

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#adb-issues

**Comment by SHITIJHALDER** [comment]
> https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#adb-issues

I didn't get my problem there !

**Comment by SHITIJHALDER** [comment]
> https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#adb-issues

I got this error 
![Screenshot (41)](https://user-images.githubusercontent.com/89300443/130400224-e87f013c-a731-4178-bb71-a07fcbb35d41.png)
See this and then suggest me something !

**Comment by SHITIJHALDER** [comment]
> > https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#adb-issues
> 
> I got this error
> ![Screenshot (41)](https://user-images.githubusercontent.com/89300443/130400224-e87f013c-a731-4178-bb71-a07fcbb35d41.png)
> See this and then suggest me something !

Help me1

**Comment by SHITIJHALDER** [comment]
> > https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#adb-issues
> 
> I got this error
> ![Screenshot (41)](https://user-images.githubusercontent.com/89300443/130400224-e87f013c-a731-4178-bb71-a07fcbb35d41.png)
> See this and then suggest me something !

Help me!

**Comment by rom1v** [comment]
You set the ADB environment variable to a wrong vzlue: it must not point to the directory (`C:\platform-tools`), but to the `adb` executable (`C:\platform-tools\adb.exe` in your case I guess).

But if you just use scrcpy without Android development (using another `adb`), you don't need to set the `ADB` environment variable at all.

Also, please do not post screenshots of terminal, just copy-paste the text.

**Comment by SHITIJHALDER** [comment]
> You set the ADB environment variable to a wrong vzlue: it must not point to the directory (`C:\platform-tools`), but to the `adb` executable (`C:\platform-tools\adb.exe` in your case I guess).
> 
> But if you just use scrcpy without Android development (using another `adb`), you don't need to set the `ADB` environment variable at all.
> 
> Also, please do not post screenshots of terminal, just copy-paste the text.

But I don't know how to do that ! Please explain step by step !

**Comment by SHITIJHALDER** [comment]
Everytime I am getting this :
ERROR: Failed to execute: [C:\platform-tools], [push], ["C:\platform-tools\platform-tools\scrcpy-server"], ["/data/local/tmp/scrcpy-server.jar"]
ERROR: Could not execute "adb push"
Press any key to continue . . .

**Comment by rom1v** [comment]
> Everytime I am getting this :
> ERROR: Failed to execute: [C:\platform-tools],

Your `ADB` environment variable is still wrong. Just remove it.

https://www.google.com/search?q=windows+set+environment+variable

**Comment by SHITIJHALDER** [comment]
Now I have edited my Environment Variables but now there is a problem :
ERROR: Command not found: [C:\platform-tools], [push], ["C:\Android\platform-tools\platform-tools\scrcpy-server"], ["/data/local/tmp/scrcpy-server.jar"]
ERROR: (make 'adb' accessible from your PATH or define its fullpath in the ADB environment variable)
INFO: You may download and install 'adb' from https://developer.android.com/studio/releases/platform-tools
ERROR: Could not execute "adb push"
Press any key to continue . . .

**Comment by rom1v** [comment]
> Now I have edited my Environment Variables but now there is a problem :
ERROR: Command not found: [C:\platform-tools],

You didn't edit your `ADB` variable. It's still `C:\platform-tools`, which is incorrect. Just remove `ADB`.

**Comment by rom1v** [comment]
> ERROR: Command not found: [C:\platform-tools], [push], ["C:\Android\platform-tools\platform-tools\scrcpy-server"]

And your `SCRCPY_SERVER` env variable is probably wrong too, why did you edit these variables?

On Windows, you just have to download the release, extract it and run. You changed a lot of things you shouldn't have changed.

**Comment by SHITIJHALDER** [comment]
> > Now I have edited my Environment Variables but now there is a problem :
> > ERROR: Command not found: [C:\platform-tools],
> 
> You didn't edit your `ADB` variable. It's still `C:\platform-tools`, which is incorrect. Just remove `ADB`.

How to edit ADB variable?

**Comment by SHITIJHALDER** [comment]
> > ERROR: Command not found: [C:\platform-tools], [push], ["C:\Android\platform-tools\platform-tools\scrcpy-server"]
> 
> And your `SCRCPY_SERVER` env variable is probably wrong too, why did you edit these variables?
> 
> On Windows, you just have to download the release, extract it and run. You changed a lot of things you shouldn't have changed.

Now I am having this problem :
INFO: scrcpy 1.18 <https://github.com/Genymobile/scrcpy>
stat: No such file or directory
ERROR: 'C:\platform-tools\scrcpy-server' does not exist or is not a regular file
Press any key to continue . . .

**Comment by SHITIJHALDER** [comment]
> > ERROR: Command not found: [C:\platform-tools], [push], ["C:\Android\platform-tools\platform-tools\scrcpy-server"]
> 
> And your `SCRCPY_SERVER` env variable is probably wrong too, why did you edit these variables?
> 
> On Windows, you just have to download the release, extract it and run. You changed a lot of things you shouldn't have changed.

This problem :
INFO: scrcpy 1.18 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: device unauthorized.
This adb server's $ADB_VENDOR_KEYS is not set
Try 'adb kill-server' if that seems wrong.
Otherwise check for a confirmation dialog on your device.
ERROR: "adb push" returned with value 1
Press any key to continue . . .

**Comment by SHITIJHALDER** [comment]
> > ERROR: Command not found: [C:\platform-tools], [push], ["C:\Android\platform-tools\platform-tools\scrcpy-server"]
> 
> And your `SCRCPY_SERVER` env variable is probably wrong too, why did you edit these variables?
> 
> On Windows, you just have to download the release, extract it and run. You changed a lot of things you shouldn't have changed.

Hey , Thank you ! My Issue is solved 💯 
It's finally working ! 

INFO: scrcpy 1.18 <https://github.com/Genymobile/scrcpy>
adb server version (39) doesn't match this client (41); killing...
* daemon started successfully
C:\platform-tools\scrcpy-server: 1 file pushed, 0 skipped. 6.1 MB/s (37330 bytes in 0.006s)
[server] INFO: Device: Xiaomi Redmi 8A (Android 10)
INFO: Renderer: direct3d
INFO: Initial texture: 720x1520
