### ISSUE TITLE
adb connection closed

### ISSUE THREAD

**Issue by sajjadjaved01** [Genymobile/scrcpy#258]
hi, while using Android Studio running app on my phone, in that when ever i launch scrpy this kills on going adb connection to create a new one that stops executions.

Can this be solved, like when i launch scrpy this checks for current ongoing connection & use that.

**Comment by rom1v** [comment]
The version used by _scrcpy_ is probably different from the one from Android Studio.

If you use Windows, the version included in _scrcpy_ archive is not the latest (see https://github.com/Genymobile/scrcpy/issues/224). In that case, just remove `adb.exe` and `Adb*.dll` from the _scrcpy_ folder, and make sure your _adb_ is accessible from `PATH` (or download the latest _adb_ and replace the files in _scrcpy_ folder).

**Comment by sajjadjaved01** [comment]
Okay Thanks man 👌

**Comment by sajjadjaved01** [comment]
Can we have a plugin for Android Studio...
