### ISSUE TITLE
Kill adb.exe on exit

### ISSUE THREAD

**Issue by FatheredPuma81** [Genymobile/scrcpy#2580]
Really hard to search for this so sorry if it's a duplicate.

Issue: adb.exe is still in task manager after program exits/closes.
Solution: Kill adb.exe on program exit.

Not a big deal but it would be nice.

**Comment by npes87184** [comment]
There is a possible that other processes are using adb. If scrcpy kill adb when it exists, it will cause some problem in other processes.

**Comment by FatheredPuma81** [comment]
How about the option to automatically kill it then?

**Comment by gaussandhisgun** [comment]
why not just run it like `scrcpy && adb kill-server`, so adb will be killed the moment scrcpy successfully finishes its work?

**Comment by rom1v** [comment]
Implemented option `--kill-adb-on-close`: a3cdf1a6b86ea22786e1f7d09b9c202feabc6949
