### ISSUE TITLE
How you compiled ScrCpy-noConsole.exe from .C files

### ISSUE THREAD

**Issue by VarunSaiTeja** [Genymobile/scrcpy#259]

**Comment by VarunSaiTeja** [comment]
Try to provide CodeBlocks project file if possible

**Comment by VarunSaiTeja** [comment]
I want to know how you converted total source code to executable file

**Comment by rom1v** [comment]
> I want to know how you converted total source code to executable file

It is cross-compoled from linux with the command:

    make -f Makefile.CrossWindows

See [`Makefile.CrossWindows`](https://github.com/Genymobile/scrcpy/blob/master/Makefile.CrossWindows).

You can also build it "natively" in MSYS2 (see [`BUILD.md`](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md).

**Comment by VarunSaiTeja** [comment]
I using Windows os
So how can I compile in it
