### ISSUE TITLE
how do you get this app running

### ISSUE THREAD

**Issue by MegaSardines** [Genymobile/scrcpy#2596]
im very confuse pls some help
  also there is so much missing dll flies

**Comment by Aadi2001** [comment]
> im very confuse pls some help
→ To Run, [download](https://github.com/Genymobile/scrcpy/releases/download/v1.18/scrcpy-win64-v1.18.zip) the release and extract to C:/ or anywhere. Go to that directory and press Shift+Right Click and open with open PowerShell then attach your device run `adb devices` or `scrcpy.exe` rest you'll find in feature section of [Repo](https://github.com/Genymobile/scrcpy) README file
> also there is so much missing dll flies
→ I don't face any issue.? With the app

**Comment by MegaSardines** [comment]
thanks i got the app running.
