### ISSUE TITLE
Scroll not working in LazyColumn for Android Jetpack compose.

### ISSUE THREAD

**Issue by Abhimanyu14** [Genymobile/scrcpy#2598]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Max OS
 - scrcpy version: 1.18
 - installation method: not sure. mostly I guess brew
 - device model: Redmi 4 (Xiomi)
 - Android version: Nougat

**Describe the bug**

Unable to scroll using scroll wheel in LazyColumn in Android jetpack compose.

Works when using Views.

More info : https://stackoverflow.com/questions/68954790/why-is-lazycolumn-not-scrollable-using-mouse-but-recycler-view-is?noredirect=1#comment121864131_68954790

**Comment by rom1v** [comment]
Oops, I missed it, sorry for opening a duplicate. I keep the other though, since this is where the discussion happened.
