### ISSUE TITLE
BLACKSCREEN ONLY :( 

### ISSUE THREAD

**Issue by Meowmete** [Genymobile/scrcpy#2599]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: HP Chrome OS
 - scrcpy version: 1.18
 - installation method: Snap 
 - device model:Oppo A5s CPHP 1909
 - Android version: 8.1.0

Hello  I am using Chrome Os I installed scrcpy but when I run it is just black screen 

Can anyone help me?
![Screenshot 2021-08-28 16 33 25](https://user-images.githubusercontent.com/89684608/131211904-0c0db554-701e-416e-9d72-0e0136ea5df7.png)

**Comment by rom1v** [comment]
In any app on the device?

What is the "Google grunt" device?

**Comment by Meowmete** [comment]
> In any app on the device?
> 
> What is the "Google grunt" device?

Good Day Nevermind Sir I Just Reinstalled it and it works.
