### ISSUE TITLE
High RAM usage

### ISSUE THREAD

**Issue by igormp** [Genymobile/scrcpy#26]
After around 1 hour of usage, I've noticed high RAM usage (see attached pic). Maybe that's due to a memory leak somewhere?
![memoryleak](https://user-images.githubusercontent.com/5247904/37237601-3d0f6b64-23f4-11e8-93fe-75de17c38a72.png)

If any further info is needed, I'll be glad to handle them.

**Comment by rom1v** [comment]
It has been fixed just after the release: https://github.com/Genymobile/scrcpy/commit/a34fbd23e99bc149f195888c6656c61e7274c7c9.

So if you build from `master`, it should be ok :)
Only the windows prebuilt archive is affected.

Except if there is another memory leak somewhere… Please let me know.

**Comment by igormp** [comment]
Oops, my bad.
I grabbed a version based off on your releases and didn't notice that master had already fixed it.

Thanks for your time :)

**Comment by rom1v** [comment]
> Oops, my bad.

Not your fault ;) Thank you for reporting this (this is a huge problem).

I wait a bit to fix other problems before publishing a new release.

**Comment by nvllsvm** [comment]
For the sake of documentation, it looks like both https://github.com/Genymobile/scrcpy/commit/a34fbd23e99bc149f195888c6656c61e7274c7c9 **and** https://github.com/Genymobile/scrcpy/commit/f9562f537ae9a1fa4949256d44f0ce9a06837edf fix this, correct?

**Comment by rom1v** [comment]
Yes, but the second is not as important: it fixes the leak of at most one packet, on error.

**Comment by nvllsvm** [comment]
Thanks. I've backported both to the [Arch Linux package](https://aur.archlinux.org/packages/scrcpy/)

**Comment by rom1v** [comment]
@nvllsvm Thank you for maintaining the Arch Linux Package! That helps a lot :+1:
