### ISSUE TITLE
scrcpy.exe has stopped working

### ISSUE THREAD

**Issue by ostgardh** [Genymobile/scrcpy#260]
I try to run scrcpy on win 7 32
And scrcpy crash when i try to open..

adb is workig. (eg . adb shell)
how can I troubleshoot.

**Comment by rom1v** [comment]
See https://github.com/Genymobile/scrcpy/issues/158.

> how can I troubleshoot.

Try [compiling it manually](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#in-msys2) and debug it to get a stacktrace (but I have no idea how to debug on Windows).

**Comment by josuesoto1** [comment]
I have the same issue. #257 
It used to work fine, now I had no success to run scrcpy.

**Comment by ostgardh** [comment]
I running windows 7 on VMware and remote Desktop to that windows.
And I have no video drive to update to... 

Is look is not working when you are using RemoteDesktop and scrcpy

**Comment by rom1v** [comment]
Could you get a stacktrace when it crashes, please?

(sorry, I don't know Windows well, so I don't really know how to do that, but check https://stackoverflow.com/questions/24208767/get-stack-trace-of-a-crash-on-windows-without-installing-visual-studio-c)

Here is a debug version, to have all symbols (replace it in _scrcpy_ directory): [`scrcpy.exe`](https://tmp.rom1v.com/scrcpy/win32-debug-78d5a4d/scrcpy.exe).
_SHA-256: 8450851b06252761f723a825db308450a973ddb682b4b59b4d24008717fef0f3_

**Comment by ostgardh** [comment]
![capture](https://user-images.githubusercontent.com/30891357/45810655-6a251c00-bccb-11e8-8d42-07c6be21afef.JPG)

**Comment by rom1v** [comment]
Thank you for the logs.

>     DEBUG: Failed loading SHCORE.DLL: The specified module could not be found.

It seems this is not a problem: https://discourse.libsdl.org/t/sdl-image-2-0-1-tries-to-load-shcore-dll-in-windows-7/22796/2

> That error message gets set by SDL2. The windows video driver checks for the DLL and loads some functions if it is present. The initialization does not fail if it is not.

The log `CreateDevice()` comes from SDL: [`SDL_render_d3d.c`](https://hg.libsdl.org/SDL/file/f1084c419f33/src/render/direct3d/SDL_render_d3d.c#l547).

It does not explain why it make _scrcpy_ crash though. When this happens, it returns `NULL`, and [`SDL_CreateRenderer()`](https://hg.libsdl.org/SDL/file/f1084c419f33/src/render/SDL_render.c#l349) handles it correctly. In turn, _scrcpy_ handle the error: [`screen.c`](https://github.com/Genymobile/scrcpy/blob/v1.3/app/src/screen.c#L159).

**Comment by ostgardh** [comment]
![2](https://user-images.githubusercontent.com/30891357/45812975-a5c2e480-bcd1-11e8-9b13-afec1e49bba9.JPG)
If i start in RemoteDesktop is look like this,
But I start i VM host console is look normal..

Strange.

**Comment by rom1v** [comment]
It seems there is a problem with your drivers.

What if you disable hardware acceleration (but it can be slow):

```diff
diff --git a/app/src/screen.c b/app/src/screen.c
index 5d7a400..6469b15 100644
--- a/app/src/screen.c
+++ b/app/src/screen.c
@@ -156,7 +156,7 @@ SDL_bool screen_init_rendering(struct screen *screen, const char *device_name, s
         return SDL_FALSE;
     }
 
-    screen->renderer = SDL_CreateRenderer(screen->window, -1, SDL_RENDERER_ACCELERATED);
+    screen->renderer = SDL_CreateRenderer(screen->window, -1, 0);
     if (!screen->renderer) {
         LOGC("Could not create renderer: %s", SDL_GetError());
         screen_destroy(screen);
```

**Comment by ostgardh** [comment]
I have problem to build the software.
Can you pleas build scrcpy with disable hardware acceleration..

Please..

**Comment by npes87184** [comment]
Hi, @ostgardh 

Here you are! [scrcpy-win64-v1.3-13-g78d5a4d.zip](https://drive.google.com/file/d/1lKX3rlOO6V9fD1tGgOuP8hZfoDF4wTX2/view?usp=sharing).
The latest master branch with the patch of @rom1v .

Thanks.

**Comment by josuesoto1** [comment]
I tested my phone in a HP computer with windows 10 and works fine. I had upgraded my windows 7 to windows 10 in a Dell laptop but the error still present.
Seems that is an issue with the USB connection. Is there a command to verify proper communication between PC and mobile? any idea to verify read/write or access permissions?
Note that when I write ADB devices my phone is properly detected.

**Comment by rom1v** [comment]
@josuesoto1 If it crashes like this, it is probably related to your graphic driver.

**Comment by josuesoto1** [comment]
Thanks, Is there a way to override this or bypass with lower resolution?

**Comment by rom1v** [comment]
I don't know. I'm closing since there is probably nothing scrcpy can do if it's related to graphic drivers.

**Comment by Antimonit** [comment]
It seems like it might not be a graphic driver issue. In my case, Windows' Event Viewer reports the `dgapi64.dll` is liable for the crash.

Apparently, 
> This file is part of Verdasys Digital Guardian and is installed by many companies to protect corporate confidential data.
> ...
> As an example it can block file all writes to removable media, or just block specific files according to preset criteria. It can block applications starting, either a particular application, or the other way around only allowing preset white listed applications to be run.

Source: https://www.file.net/process/dgapi.dll.html

Devs and testers in my company with company laptops have the same issue. It works on my personal laptop fine as it does not have the offending DLL under `c:\windows\system32\`.

Scrcpy probably uses some calls that our company policy deems insecure. It might be just our overprotective policy but it might be worth investigating a little bit more.
