### ISSUE TITLE
v4l2 output bad when I adjust scrcpy by using `-m`

### ISSUE THREAD

**Issue by codedetermination** [Genymobile/scrcpy#2600]
It is normal when I use scrcpy without any change as example .
[server] INFO: Device: LGE LM-G820 (Android 10)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6.0 NVIDIA 460.91.03
INFO: Trilinear filtering enabled
INFO: Initial texture: 1440x3120

but I want to adjust to get a fluent capture.
using 
`scrcpy  -m 1560 --v4l2-sink=/dev/video2
`
![picture](https://github.com/codedetermination/my_issues/blob/main/2021-08-28%2022-39-52%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png)

when I use `ffplay -i /dev/video2` to show It reports error like this
[video4linux2,v4l2 @ 0x7f3ca0000bc0] Dequeued v4l2 buffer contains 2557440 bytes, but 6739200 were expected. Flags: 0x00000001.
and it display like this

I want to know how can I adjust it to make it display normal.
Thank you!

**Comment by rom1v** [comment]
The v4l2 buffer size is defined on the first use, until all producer and consumers close the connection.

So if you started a v4l2 stream at 1440×3120, then it's the size for the whole "session".

To start a new session, close all your `ffplay` and `scrcpy`, then start a new `scrcpy -m 1560 --v4l2-sink=/dev/video2`, then start a new `ffplay -i /dev/video2`.

If this is not sufficient (it would be surprising), you could `sudo rmmod v4l2loopback` then restart from scratch, directly with the correct `-m` size.

**Comment by codedetermination** [comment]
OK!Thank you very mush ！
