### ISSUE TITLE
black screen , android tv 

### ISSUE THREAD

**Issue by notelev** [Genymobile/scrcpy#2601]
**Environment**
 - OS: Windows 10 2H21
 - scrcpy version: V1.18
 - installation method: Windows Release
 - device model: TCL Android TV
 - Android version: Android Pie 9

**Describe the bug**
UI Only showing in scrcpy , i do adb wireless with my android tv anything was fine mouse & keyboard but when i play a video on youtube or goes to HDMI inputs nothing shows only a black screen but when i click at settings button or trying to down or up the volume the ui shows without the video ( like backgroud ) on scrcpy only but in tv is fine

**Comment by rom1v** [comment]
That's expected. The video may not be captured due to hardware restrictions (either DRM or just due to the architecture).

**Comment by gb18030** [comment]
but when I use live app,It not work for me(black screen without UI)
I guess it not work on SurfaceView(or TextureView?)
but it working fine on my phone.

**Comment by lucasZero** [comment]
with magiconnect is possible to take a screenshot.
