### ISSUE TITLE
WIN7 X64 

### ISSUE THREAD

**Issue by l072818** [Genymobile/scrcpy#2609]
![04055b68782004e5b4d917d7a9e5be3](https://user-images.githubusercontent.com/68995821/131987398-f73eb300-76f4-47aa-87aa-44264f1a2c65.png)
这个报错导致，鼠标的操作无效，怎么维护下，使用的版本是：scrcpy-win64-v1.18

**Comment by rom1v** [comment]
```
scrcpy -m 1920
```

#2031
https://github.com/Genymobile/scrcpy/issues/1518#issuecomment-655519163

**Comment by l072818** [comment]
This bug has been resolved and win7 x64 can be used normally. Thank.
