### ISSUE TITLE
No audio in recording even with sndcpy running

### ISSUE THREAD

**Issue by Deepesh008** [Genymobile/scrcpy#2621]
I want to record mobile gameplay with scrcpy and sndcpy for both video and audio, I use the following commands
scrcpy -b 32m -r 1.mp4
the file is recorded in excellent quality but no audio in rec.
Alternatively I used OBS for recording the quality is a lot lower and it puts heavy strain on my cpu so choppy recording but it records with game sounds.
Is there any command in scrcpy that lets me have internal audio as well

**Comment by rom1v** [comment]
> Is there any command in scrcpy that lets me have internal audio as well

No.
