### ISSUE TITLE
How to install with contos?

### ISSUE THREAD

**Issue by xxxxxxH** [Genymobile/scrcpy#2634]
How to install with contos?
![image](https://user-images.githubusercontent.com/20770054/133540271-a703ee10-31ea-435f-af53-64bbea2be36d.png)

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple

**Comment by xxxxxxH** [comment]
![image](https://user-images.githubusercontent.com/20770054/133561067-5adf42ad-94ec-4454-93b6-f7ab0099515f.png)
It didn't solve my problem

**Comment by rom1v** [comment]
(Please post the text as text instead of a screenshot)

It seems your ffmpeg is installed in `/usr/local/`, so you must adapt your `PKG_CONFIG_PATH`: https://askubuntu.com/questions/210210/pkg-config-path-environment-variable

**Comment by xxxxxxH** [comment]
[scrcpy] Verifying prebuilt server...
scrcpy-server: OK
[scrcpy] Building client...
The Meson build system
Version: 0.52.1
Source dir: /scrcpy
Build dir: /scrcpy/build-auto
Build type: native build
Project name: scrcpy
Project version: 1.19
C compiler for the host machine: cc (gcc 4.8.5 "cc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)")
C linker for the host machine: GNU ld.bfd 2.23.52.0.1-55
Host machine cpu family: x86_64
Host machine cpu: x86_64
Library libavformat found: YES
Library libavcodec found: YES
Library libavutil found: YES
Library SDL2 found: YES
Library libavdevice found: YES
Checking for function "strdup" : YES 
Configuring config.h using configuration
Build targets in project: 3
Found ninja-1.10.2 at /usr/bin/ninja
[2/33] Compiling C object 'app/a172ced@@scrcpy@exe/src_compat.c.o'.
FAILED: app/a172ced@@scrcpy@exe/src_compat.c.o 
cc -Iapp/a172ced@@scrcpy@exe -Iapp -I../app -I/usr/lib/ffmpeg/include/ -I/usr/lib/sdl/include/ -I../app/src -flto -DNDEBUG -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c11 -O3 -MD -MQ 'app/a172ced@@scrcpy@exe/src_compat.c.o' -MF 'app/a172ced@@scrcpy@exe/src_compat.c.o.d' -o 'app/a172ced@@scrcpy@exe/src_compat.c.o' -c ../app/src/compat.c
In file included from /usr/include/string.h:633:0,
                 from /usr/lib/sdl/include/SDL2/SDL_stdinc.h:66,
                 from /usr/lib/sdl/include/SDL2/SDL_version.h:31,
                 from ../app/src/compat.h:12,
                 from ../app/src/compat.c:1:
../app/src/compat.h:52:7: error: expected identifier or ‘(’ before ‘__extension__’
 char *strdup(const char *s);
       ^
[6/33] Compiling C object 'app/a172ced@@scrcpy@exe/src_main.c.o'.
In file included from /usr/lib/ffmpeg/include/libavutil/avutil.h:296:0,
                 from /usr/lib/ffmpeg/include/libavutil/samplefmt.h:24,
                 from /usr/lib/ffmpeg/include/libavcodec/avcodec.h:31,
                 from /usr/lib/ffmpeg/include/libavformat/avformat.h:312,
                 from ../app/src/main.c:8:
/usr/lib/ffmpeg/include/libavutil/common.h: In function ‘av_sat_add64_c’:
/usr/lib/ffmpeg/include/libavutil/common.h:380:20: warning: suggest parentheses around arithmetic in operand of ‘|’ [-Wparentheses]
     if ((int64_t)(a^b | ~s^b) >= 0)
                    ^
[8/33] Compiling C object 'app/a172ced@@scrcpy@exe/src_controller.c.o'.
FAILED: app/a172ced@@scrcpy@exe/src_controller.c.o 
cc -Iapp/a172ced@@scrcpy@exe -Iapp -I../app -I/usr/lib/ffmpeg/include/ -I/usr/lib/sdl/include/ -I../app/src -flto -DNDEBUG -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c11 -O3 -MD -MQ 'app/a172ced@@scrcpy@exe/src_controller.c.o' -MF 'app/a172ced@@scrcpy@exe/src_controller.c.o.d' -o 'app/a172ced@@scrcpy@exe/src_controller.c.o' -c ../app/src/controller.c
In file included from ../app/src/receiver.h:9:0,
                 from ../app/src/controller.h:9,
                 from ../app/src/controller.c:1:
../app/src/util/thread.h:6:23: fatal error: stdatomic.h: No such file or directory
 #include <stdatomic.h>
                       ^
compilation terminated.
[10/33] Compiling C object 'app/a172ced@@scrcpy@exe/src_file_handler.c.o'.
FAILED: app/a172ced@@scrcpy@exe/src_file_handler.c.o 
cc -Iapp/a172ced@@scrcpy@exe -Iapp -I../app -I/usr/lib/ffmpeg/include/ -I/usr/lib/sdl/include/ -I../app/src -flto -DNDEBUG -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c11 -O3 -MD -MQ 'app/a172ced@@scrcpy@exe/src_file_handler.c.o' -MF 'app/a172ced@@scrcpy@exe/src_file_handler.c.o.d' -o 'app/a172ced@@scrcpy@exe/src_file_handler.c.o' -c ../app/src/file_handler.c
In file included from ../app/src/file_handler.h:10:0,
                 from ../app/src/file_handler.c:1:
../app/src/util/thread.h:6:23: fatal error: stdatomic.h: No such file or directory
 #include <stdatomic.h>
                       ^
compilation terminated.
[11/33] Compiling C object 'app/a172ced@@scrcpy@exe/src_decoder.c.o'.
FAILED: app/a172ced@@scrcpy@exe/src_decoder.c.o 
cc -Iapp/a172ced@@scrcpy@exe -Iapp -I../app -I/usr/lib/ffmpeg/include/ -I/usr/lib/sdl/include/ -I../app/src -flto -DNDEBUG -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c11 -O3 -MD -MQ 'app/a172ced@@scrcpy@exe/src_decoder.c.o' -MF 'app/a172ced@@scrcpy@exe/src_decoder.c.o.d' -o 'app/a172ced@@scrcpy@exe/src_decoder.c.o' -c ../app/src/decoder.c
In file included from /usr/lib/ffmpeg/include/libavutil/avutil.h:296:0,
                 from /usr/lib/ffmpeg/include/libavutil/samplefmt.h:24,
                 from /usr/lib/ffmpeg/include/libavcodec/avcodec.h:31,
                 from /usr/lib/ffmpeg/include/libavformat/avformat.h:312,
                 from ../app/src/decoder.h:9,
                 from ../app/src/decoder.c:1:
/usr/lib/ffmpeg/include/libavutil/common.h: In function ‘av_sat_add64_c’:
/usr/lib/ffmpeg/include/libavutil/common.h:380:20: warning: suggest parentheses around arithmetic in operand of ‘|’ [-Wparentheses]
     if ((int64_t)(a^b | ~s^b) >= 0)
                    ^
In file included from ../app/src/frame_buffer.h:8:0,
                 from ../app/src/video_buffer.h:9,
                 from ../app/src/decoder.c:6:
../app/src/util/thread.h: At top level:
../app/src/util/thread.h:6:23: fatal error: stdatomic.h: No such file or directory
 #include <stdatomic.h>
                       ^
compilation terminated.
ninja: build stopped: subcommand failed.

**Comment by rom1v** [comment]
> C compiler for the host machine: cc (gcc 4.8.5 "cc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)")

>     ../app/src/util/thread.h:6:23: fatal error: stdatomic.h: No such file or directory
>    #include <stdatomic.h>
>    ^

https://stackoverflow.com/questions/20326604/stdatomic-h-in-gcc-4-8

> ../app/src/compat.h:52:7: error: expected identifier or ‘(’ before ‘extension’

I don't understand this one.

**Comment by xxxxxxH** [comment]
maybe update my system?

**Comment by xxxxxxH** [comment]
FAILED: app/scrcpy 
cc  -o app/scrcpy 'app/a172ced@@scrcpy@exe/src_main.c.o' 'app/a172ced@@scrcpy@exe/src_adb.c.o' 'app/a172ced@@scrcpy@exe/src_cli.c.o' 'app/a172ced@@scrcpy@exe/src_clock.c.o' 'app/a172ced@@scrcpy@exe/src_compat.c.o' 'app/a172ced@@scrcpy@exe/src_control_msg.c.o' 'app/a172ced@@scrcpy@exe/src_controller.c.o' 'app/a172ced@@scrcpy@exe/src_decoder.c.o' 'app/a172ced@@scrcpy@exe/src_device_msg.c.o' 'app/a172ced@@scrcpy@exe/src_event_converter.c.o' 'app/a172ced@@scrcpy@exe/src_file_handler.c.o' 'app/a172ced@@scrcpy@exe/src_fps_counter.c.o' 'app/a172ced@@scrcpy@exe/src_frame_buffer.c.o' 'app/a172ced@@scrcpy@exe/src_input_manager.c.o' 'app/a172ced@@scrcpy@exe/src_opengl.c.o' 'app/a172ced@@scrcpy@exe/src_receiver.c.o' 'app/a172ced@@scrcpy@exe/src_recorder.c.o' 'app/a172ced@@scrcpy@exe/src_scrcpy.c.o' 'app/a172ced@@scrcpy@exe/src_screen.c.o' 'app/a172ced@@scrcpy@exe/src_server.c.o' 'app/a172ced@@scrcpy@exe/src_stream.c.o' 'app/a172ced@@scrcpy@exe/src_tiny_xpm.c.o' 'app/a172ced@@scrcpy@exe/src_video_buffer.c.o' 'app/a172ced@@scrcpy@exe/src_util_log.c.o' 'app/a172ced@@scrcpy@exe/src_util_net.c.o' 'app/a172ced@@scrcpy@exe/src_util_process.c.o' 'app/a172ced@@scrcpy@exe/src_util_str_util.c.o' 'app/a172ced@@scrcpy@exe/src_util_thread.c.o' 'app/a172ced@@scrcpy@exe/src_util_tick.c.o' 'app/a172ced@@scrcpy@exe/src_sys_unix_process.c.o' 'app/a172ced@@scrcpy@exe/src_v4l2_sink.c.o' -flto -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -Wl,--start-group /usr/lib/ffmpeg/lib/libavformat.a /usr/lib/ffmpeg/lib/libavcodec.a /usr/lib/ffmpeg/lib/libavutil.a /usr/lib/sdl/lib/libSDL2.so /usr/lib/ffmpeg/lib/libavdevice.a -Wl,--end-group -Wl,-rpath,/usr/lib/sdl/lib -Wl,-rpath-link,/usr/lib/sdl/lib
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /usr/lib/ffmpeg/lib/libavformat.a(mov.o): undefined reference to symbol 'hypot@@GLIBC_2.2.5'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /lib64/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.  
so many questions =.=
