### ISSUE TITLE
Does it use minicap

### ISSUE THREAD

**Issue by YurieCo** [Genymobile/scrcpy#264]
HI, 
I am curiously just if it does use minicap to capture the screen from phone?

**Comment by npes87184** [comment]
No, it does not use minicap.
It uses Android hidden class to capture and MediaCodec to encode the frame.
All the treasure is in [ScreenEncoder](https://github.com/Genymobile/scrcpy/blob/master/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java).

**Comment by rom1v** [comment]
You can also get more details in [DEVELOP](https://github.com/Genymobile/scrcpy/blob/master/DEVELOP.md).

**Comment by YurieCo** [comment]
Thanks a lot

**Comment by cmlanche** [comment]
which one is better?

**Comment by wchensc** [comment]
> which one is better?

Anyone can answer this question?
