### ISSUE TITLE
Unable to view Android 12 using scrcpy

### ISSUE THREAD

**Issue by steven0224** [Genymobile/scrcpy#2647]
- [*] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [*] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Ubuntu 18]
 - scrcpy version: [e.g. 1.19.1]
 - installation method: manual build, apt, snap
 - device model: Intel AOSP on Intel Platform (Android 12)
 - Android version: [12]

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).
NA
```
Please paste terminal output in a code block.
```
![image](https://user-images.githubusercontent.com/26128400/133980208-55331ff8-86dd-4e6b-8e6d-c6767e716e33.png)

Please do not post screenshots of your terminal, just post the content as text instead.
```
android@GIO-840f23c82c9:~$ scrcpy -m 1024 -s R1J56L7cb31581
INFO: scrcpy 1.19 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 7.2 MB/s (37330 bytes in 0.005s)
[server] INFO: Device: Intel AOSP on Intel Platform (Android 12)
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2145)
        at android.media.MediaCodec.configure(MediaCodec.java:2061)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:237)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:90)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:255)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
[server] ERROR: The hardware encoder is not able to encode at the given definition.
[server] ERROR: Try with a lower definition:
[server] ERROR:     scrcpy -m 1024
INFO: Renderer: opengl
INFO: OpenGL version: 3.1 Mesa 20.0.8
INFO: Trilinear filtering enabled
INFO: Initial texture: 1024x576
WARN: Device disconnected
WARN: Killing the server...
android@GIO-840f23c82c9:~$
```

**Comment by rom1v** [comment]
Reduce the definition more, try `scrcpy -m800` or `scrcpy -m600`…

**Comment by steven0224** [comment]
I've tried both 800 & 600 & still face the same issue. I suspect scrcpy is not compatible yet with Android 12.
However, Android 11 is working properly. 
Anyway, thanks for your quick response.

![image](https://user-images.githubusercontent.com/26128400/133981899-5b0ee9b5-8e8b-40d4-bede-1b3a4008eeda.png)

**Comment by rom1v** [comment]
> I suspect scrcpy is not compatible yet with Android 12.

Yes, it is.

0xfffffc0e is an error reported by MediaCodec when the encoder is not able to encode with the given parameters (typica(ly the size).

Does screenrecord work on this device?

```
adb shell screenrecord /sdcard/file.mp4
adb pull /sdcard/file.mp4
```

**Comment by steven0224** [comment]
![image](https://user-images.githubusercontent.com/26128400/133985398-ede3ec51-6fe4-461d-b32c-ed6f7a2f3fe5.png)

**Comment by rom1v** [comment]
_Please post the text directly between ``` rather than posting a screenshot of text._

Does the generated flie.mp4 work properly?

The logs suggest that it failed both at 1920x1080 and 1280x720.

**Comment by steven0224** [comment]
Does the generated flie.mp4 work properly? it is not working properly.


a screenshot of text below:
android@GIO-840f23c82c9:~$ adb -s R1J56L7cb31581 shell screenrecord /sdcard/file.mp4

Output format == FORMAT_MP4

VideoMimeTypeString == video/avc
ERROR: unable to configure video/avc codec at 1920x1080 (err=-1010)
WARNING: failed at 1920x1080, retrying at 1280x720
ERROR: unable to configure video/avc codec at 1280x720 (err=-1010)
android@GIO-840f23c82c9:~$ adb -s R1J56L7cb31581 root
adbd is already running as root
android@GIO-840f23c82c9:~$ adb -s R1J56L7cb31581 shell
gordon_peak:/ # ls
acct        cache        debug_ramdisk      init.environ.rc               metadata  postinstall             sepolicy    vendor
adb_keys    config       dev                init.recovery.gordon_peak.rc  mnt       proc                    storage     vendor_dlkm
apex        d            etc                init.zygote64_32.rc           odm       product                 sys
bin         data         file_contexts.bin  linkerconfig                  odm_dlkm  sdcard                  system
bugreports  data_mirror  init               lost+found                    oem       second_stage_resources  system_ext
gordon_peak:/ # cd sdcard/
gordon_peak:/sdcard # ls
Alarms   Audiobooks  Documents  Movies  Notifications  Podcasts    Ringtones
Android  DCIM        Download   Music   Pictures       Recordings  file.mp4
gordon_peak:/sdcard #
gordon_peak:/sdcard #
gordon_peak:/sdcard # exit
android@GIO-840f23c82c9:~$ adb -s R1J56L7cb31581 pull /sdcard/file.mp4
/sdcard/file.mp4: 1 file pulled.
android@GIO-840f23c82c9:~$

**Comment by rom1v** [comment]
> it is not working properly.

OK, so there is a problem with the encoder on the device (if it does not work even with the "built-in" screen recorder).

**Comment by steven0224** [comment]
Yes. Please advice. Thank you

**Comment by steven0224** [comment]
scrcpy supports Android 12, but Google restricts its capabilities. 
https://androidcommunity.com/scrcpy-supports-android-12-but-google-restricts-its-capabilities-20210622/

note: Hope scrcpy able resolve it. :)

Keep it the up the good works!

**Comment by rom1v** [comment]
This article is about a restriction fixed by #2129. Now it works.

This is really a problem with your device encoder (independent of scrcpy since screenrecorder also fails).

**Comment by steven0224** [comment]
I see. So, how can I resolved the device encoder? Any clue please? Thanks

**Comment by rom1v** [comment]
I don't know. Is it the official ROM for the device? Did you install another ROM?

**Comment by steven0224** [comment]
This is not an official ROM for this device yet by the company & still under engineering candidate (EC). But the previous ROM like Android 11 is working well with SCRCPY application. :(

**Comment by rom1v** [comment]
Then their ROM "Android 12" has a bug, report to them.

**Comment by steven0224** [comment]
noted. thanks for you advice.

**Comment by steven0224** [comment]
Hi, i am able to view the Android 12 device using scrcpy v1.19 with the commands below:

android@GIO-840f23c82c9:~$ scrcpy --encoder c2.android.avc.encoder -s R1J56L48fa4a14
INFO: scrcpy 1.19 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 7.9 MB/s (37330 bytes in 0.004s)
[server] INFO: Device: Intel AOSP on Intel Platform (Android 12)
INFO: Renderer: opengl
INFO: OpenGL version: 3.1 Mesa 20.0.8
INFO: Trilinear filtering enabled
INFO: Initial texture: 1920x1080
WARN: Killing the server...

**Comment by krishtoautomate** [comment]
Fixed

**Comment by DigitalAdeel** [comment]
> Hi, i am able to view the Android 12 device using scrcpy v1.19 with the commands below:
> 
> android@GIO-840f23c82c9:~$ scrcpy --encoder c2.android.avc.encoder -s R1J56L48fa4a14 INFO: scrcpy 1.19 https://github.com/Genymobile/scrcpy /usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 7.9 MB/s (37330 bytes in 0.004s) [server] INFO: Device: Intel AOSP on Intel Platform (Android 12) INFO: Renderer: opengl INFO: OpenGL version: 3.1 Mesa 20.0.8 INFO: Trilinear filtering enabled INFO: Initial texture: 1920x1080 WARN: Killing the server...

Just tested it on Ancient OS 6.1 Android 12 for Redmi 9/Prime and for the first time, I'm able to view it properly :)
Thanks to you and Scrcpy team, obviously :D
Vanilla Scrcpy command
![image](https://github.com/user-attachments/assets/a5338c1c-79a5-4c19-b39e-7b6ba4fbbb79)
With c2.android.avc.encoder encoder
![image](https://github.com/user-attachments/assets/2012777c-22a3-4a40-8340-61103f9a1d8f)

**Comment by DigitalAdeel** [comment]
Just tested with all the encoders and it's showing proper display/video with but
Android(**c2.android.avc.encoder**) and Google(**OMX.google.h264.encoder**) H.264 Encoders.
**OMX.MTK.VIDEO.ENCODER.AVC** command works but video output is not.

**OMX.MTK.VIDEO.ENCODER.HEVC** throws this error:
scrcpy 2.6.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  90e6f24e0404                    device  Redmi_9
[server] INFO: Device: [xiaomi] Redmi Redmi 9 (Android 12)
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0xffffffc3
[server] INFO: Retrying with -m1920...
[server] INFO: Retrying...
[server] INFO: Retrying with -m1600...
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0xffffffc3
[server] INFO: Retrying...
INFO: Renderer: direct3d
INFO: Texture: 1080x2336
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0xffffffc3
[server] INFO: Retrying with -m1280...
[server] INFO: Retrying...
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0xffffffc3
[server] INFO: Retrying with -m1024...
[server] INFO: Retrying...
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0xffffffc3
[server] INFO: Retrying with -m800...
[server] INFO: Retrying...
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0xffffffc3
WARN: Device discon[server] ERROR: Exception on thread Thread[video,5,main]
nected
ERROR: Demuxer 'audio': streaandroid.media.MediaCodec$CodecException: Error 0xffffffc3
        at android.media.MediaCodec.native_configure(Native Method)m
        at android.media.MediaCodec.configure(MediaCodec.java:2176)d
i       at android.media.MediaCodec.configure(MediaCodec.java:2092)
        at com.genymobile.scrcpy.video.SurfaceEncoder.streamCapture(SurfaceEncoder.java:81)
sa      at com.genymobile.scrcpy.video.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-video-SurfaceEncoder(SurfaceEncoder.java:268)
b       at com.genymobile.scrcpy.video.SurfaceEncoder$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)l
        at java.lang.Thread.run(Thread.java:920)
ed due to connection error

**Comment by BugfinderPro135** [comment]
I'm using V2.7 of scrcpy and it seems the command --encoder has now been replaced with --video-encoder

So now type  "scrcpy --tcpip=192.168.0.xxx --video-encoder c2.android.avc.encoder"  where xxx is in my case is the Android TV DQ06's ip address.

It does seem a bit laggy displaying the video though.

**Comment by DigitalAdeel** [comment]
> I'm using V2.7 of scrcpy and it seems the command "--encoder" has now been replaced with "--video-encoder"
> 
> So now type "scrcpy --tcpip=192.168.0.xxx --video-encoder c2.android.avc.encoder" where xxx is in my case is the Android TV DQ06's ip address, for it to work on Android 12.
> 
> It does seem a bit laggy displaying the video though.
> 
> Does this mean there is an encoder in scrcpy that no longer works from Android 12 onwards?
> 
> How do you choose the default encoder to use so you don't have to keep adding which encoder to use on the command line?
> 
> Or better still, how do you tell the Android TV box to use a different encoder and permanently remember that choice?

Just use AnLink.
![image](https://github.com/user-attachments/assets/e0d31535-4dde-49df-935d-553ca1c81707)
