### ISSUE TITLE
Lag when controlling device with computer mouse

### ISSUE THREAD

**Issue by CodeAck** [Genymobile/scrcpy#265]
Hi, completely new to this kind of stuff, only used these before (Andy, Nox, BlueStacks, Vysor, Mobizen). Just installed homebrew and adb and Scrycpy!

There is a bit of lag between my android device and controlling with a computer mouse. Not able to play games this way and wondering if there is a way to lessen the leg or get rid of it altogether?
Just to clarify, the android device itself has no lag when controlling from computer with computer mouse. It's the device screen on the computer that has to delay.
 
Any help would be great.
Added screenshot of terminal If it helps

Moto G5 = Android 7.0
iMac (Retina 5K, 27-inch, Late 2015) = macOS High Sierra v10.13.6

<img width="594" alt="screen shot 2018-09-17 at 7 11 14 pm" src="https://user-images.githubusercontent.com/43360701/45660456-b5fa7a00-baad-11e8-9015-512a0cacb4fe.png">

**Comment by rom1v** [comment]
Do you use it over USB or WiFi? (use USB for lower delay)

When you say there is lag, it's like 70ms~100ms, or more about 1 second?

You can get a lower lag if you decrease resolution (definition):

    scrcpy -m 800

**Comment by CodeAck** [comment]
Thank you that fixed it. I have a plug-in with USB, and was getting between 500 ms and 1s of lag. Even lowering it down to -m 1200 worked!

**Comment by rom1v** [comment]
> and was getting between 500 ms and 1s of lag

Wow, that's not expected.

Are some frame dropped? (Ctrl+i to enable printing fps in the console) Maybe the device or computer is not fast enough to encode or decode the full HD stream.

**Comment by CodeAck** [comment]
Oh sorry I might've put that in the wrong order…I was just answering your question about the USB and lag time.
What you recommended fix that.
Thanks again
