### ISSUE TITLE
Low FPS on Chromecast with Google TV

### ISSUE THREAD

**Issue by Ufinexa** [Genymobile/scrcpy#2652]
- [ ✓] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ✓] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: Latest
 - installation method: Windows Release
 - device model: Chromecast With Google TV
 - Android version: 10

**Describe the bug**
Connecting wirelessly to the Chromecast seems to show low FPS regardless of any additional flags or encoder changes I add before starting it. 

[Video output after recording](https://ufihost.xyz/i/iAyXN.mp4)

**Comment by rom1v** [comment]
Since the "low framerate" persists in the recorded file, the "low framerate" comes from the device.

(if you press <kbd>Alt</kbd>+<kbd>i</kbd>, it will print fps and frame skipped in the console)

What if you reduce the definition (`scrcpy -m800`)?

Is it smoother on the TV than in the recorded file?

What if you record with screenrecord:

```
adb shell screenrecord /sdcard/file.mp4
adb pull /sdcard/file.mp4
```

**Comment by Ufinexa** [comment]
Doing Alt+I in the normal 1920x1080 resolution gives out 15fps constantly, with -m800 I get between 45 to 60

It is smoother on the TV than the recorded file still

doing it with screenrecord still gives me around 15fps

**Comment by rom1v** [comment]
So I'd say that the hardware encoder on the chromecast is not able to encode at this definition at 60fps.

**Comment by Ufinexa** [comment]
Curses, hopefully, that changes in an update or something. Thank you so much anyway though!

**Comment by parkerlreed** [comment]
Chromecast HD with -m 720 is 30 FS.

800 is 25 and doing full 1080 is 5 FPS. Seems like it got MUCH worse :(
