### ISSUE TITLE
Black squares flickering on Linux

### ISSUE THREAD

**Issue by kidney715** [Genymobile/scrcpy#2657]
Hello, the issue is best explained with a video. Recorded it with `scrcpy --record file.mkv`. [Link to the video file](https://mega.nz/file/CtYzwYZZ#9SvSNemxs2hURiF17lvsZWv93sJzPZkIIrHoPd9iXso)

I'm running it on Zorin OS 16 Pro via Wayland. Phone: Xiaomi Mi 9T Pro with Android 12 beta 5.

**Comment by rom1v** [comment]
And with screenrecord?

```
adb shell screenrecord /sdcard/file.mp4
adb pull /sdcard/file.mp4
```

**Comment by kidney715** [comment]
> And with screenrecord?
> 
> ```
> adb shell screenrecord /sdcard/file.mp4
> adb pull /sdcard/file.mp4
> ```
> 
> > Recorded it with `scrcpy --record file.mkv`
> 
> Since the flickering is "recorded", it's captured like this on the device (so it's independent of Linux/Wayland).

Yes it is flickering with screenrecord too. Thanks for the quick reply, so the issue is with the device. Just as a shot in the dark disabled HW overlays and the flickering is gone.
