### ISSUE TITLE
Respect existing "Show taps" setting.

### ISSUE THREAD

**Issue by mikroskeem** [Genymobile/scrcpy#266]
I am one of the few who cannot use phone without that white tap thingy. Just simply cannot.

Could scrcpy respect existing setting and not touch it by default? It's bit annoying to turn that on every time after using scrcpy :smile:

I'm not sure if Android API allows this, but just sharing a food for thought.

**Comment by rom1v** [comment]
This option enables it on start and disable it on stop.

If you let it enabled on your phone all the time, do not use the option at all, it won't touch it.

Remembering the initial state of the option to restore it would work, unless the user changes the option manually while scrcpy is running. But what is the use case: why using this option if it is already enabled?

**Comment by mikroskeem** [comment]
scrcpy turned my taps settings off for some reason when I closed it. I didn't use `-t` flag.

Version info (built from AUR using `scrcpy` package):
```
scrcpy v1.3

dependencies:
 - SDL 2.0.8
 - libavcodec 58.18.100
 - libavformat 58.12.100
 - libavutil 56.14.100
```

**Comment by rom1v** [comment]
@mikroskeem any news?

**Comment by mikroskeem** [comment]
Sorry I've been busy. I'll try to reproduce this again and provide the info ASAP.

**Comment by mikroskeem** [comment]
This issue is completely invalid. Indeed, `-t` shouldn't used in that case and I must've been really tired when I reported this. Sorry :smile:

**Comment by rom1v** [comment]
Now, if it was enabled, it is kept 4668638ee10764e8341c0770d548c0b74de69a8d
