### ISSUE TITLE
Remove Title Bar; How?

### ISSUE THREAD

**Issue by ThyZlayer** [Genymobile/scrcpy#2660]
Is there a possible option or line of code for the title bar to temporarily minimize/not be seen when windowed if not hovered on by the mouse for awhile?

**Comment by rom1v** [comment]
Hmm… no. It looks like a very specific/odd need to me :thinking: 

If you don't want borders, run `scrcpy --window-borderless`.

**Comment by ThyZlayer** [comment]
> Hmm… no. It looks like a very specific/odd need to me 🤔
> 
> If you don't want borders, run `scrcpy --window-borderless`.

Thanks, I'll check it out
