### ISSUE TITLE
is it possible to run scrcpy on different network?

### ISSUE THREAD

**Issue by hackrx** [Genymobile/scrcpy#2661]
Thanks for such a great open source project, I am using this from the last few months. 
But now I have an issue, I want to know if I can connect to a device that is not in the same network? 
Maybe through port forwarding or ssh tunnel, please correct me if I am missing something.
IDK if this is already implemented.
I think it can be done by installing a terminal like termux and then open a port on the remote device (android), then maybe on our desktop, we can use remote device public IP with that port to connect.
Note: Remote android device is not connected to any computer and don't even have access, but for one time we can connect it to computer to execute some commands, but I think we can do this using termux </>.
Thanks.

**Comment by rom1v** [comment]
> Maybe through port forwarding or ssh tunnel, please correct me if I am missing something.

https://github.com/Genymobile/scrcpy#ssh-tunnel

> Remote android device is not connected to any computer and don't even have access, but for one time we can connect it to computer to execute some commands

Scrcpy relies on `adb`, so the device must be connected with `adb`. Typically, what works well is to connect the device to a computer (via USB or `adb connect`), and use SSH port forwarding to access the device remotely.

**Comment by hackrx** [comment]
Thanks, @rom1v, I read about the ssh tunnel connect feature, I have few more doubts, can you please guide me?
so that means the device should be all-time connected to a computer or should be in the same network as the local computer? 
Is there any way to create an ADB server on android using the root terminal (my device is rooted)? 
Thanks for the reply.

**Comment by rom1v** [comment]
> so that means the device should be all-time connected to a computer or should be in the same network as the local computer?

The device should be connected to a computer (either via USB or wirelessly in the same LAN).
This computer can be connected from a remote computer (via SSH), and scrcpy can be used from this remote computer.

> Is there any way to create an ADB server on android using the root terminal (my device is rooted)?

Once your device adb server listens to a port (`adb tcpip 5555`), you can expose it on the internet (open the port on your NAT), so that you can `adb connect` from a remote computer. However, the communication is not encrypted.

You could probably run a service (like a SSH server) on the device directly, which would connect to `adb` locally.

**Comment by hackrx** [comment]
@rom1v Thanks for the answer, is there any way to create adb server without connecting to pc? Maybe using a terminal like termux by installing any package?

**Comment by maya-56** [comment]
@hackrx Are you got answer ? How we can connect remote devices .. ?

**Comment by Avengers27** [comment]
> @rom1v Thanks for the answer, is there any way to create adb server without connecting to pc? Maybe using a terminal like termux by installing any package?

Refer to this page. https://stackoverflow.com/questions/2604727/how-can-i-connect-to-android-with-adb-over-tcp

If you are rooted you can enable adb from any terminal on Android or via app also
