### ISSUE TITLE
zsh: command not found: scrcpy

### ISSUE THREAD

**Issue by thilan65** [Genymobile/scrcpy#2662]
I installed brew and installed scrcpy above guidelines but i type scrcpy in terminal. I have a question look like this "zsh: command not found: scrcpy" What can i do please help me!

**Comment by npes87184** [comment]
Try logout and login again?

**Comment by thilan65** [comment]
> Try logout and login again?

where do I am want to log out?

**Comment by thilan65** [comment]
![Screenshot 2021-09-25 at 20 51 21](https://user-images.githubusercontent.com/66767511/134776672-a8bee1c2-db82-40ac-a5e8-5a88aa899f9a.png)

**Comment by rom1v** [comment]
You installed adb/platform-tools, but did you install scrcpy?

**Comment by thilan65** [comment]
> You installed adb/platform-tools, but did you install scrcpy?
![Screenshot 2021-09-25 at 23 25 49](https://user-images.githubusercontent.com/66767511/134781369-63ad4af4-4199-4311-ae3d-744a24260758.png)

**Comment by thilan65** [comment]
Thanks mate I resolved all issues
