### ISSUE TITLE
Connection Fail when device restarts

### ISSUE THREAD

**Issue by MrTeeXD** [Genymobile/scrcpy#2664]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10 64bit
 - scrcpy version: 1.19.0
 - installation method: Release Builds
 - device model: SM-A115F/DS
 - Android version: Android 11

**Describe the bug**
When the user restarts his/her device/phone and then attempts to reconnect scrcpy, the connection will fail and will result in a "Machine refused connection" error message.

On errors, please provide the output of the console (and `adb logcat` if relevant).
```

Please paste terminal output in a code block.
```cannot connect to 10.0.0.8:5555: No connection could be made because the target machine actively refused it. (10061)

**Comment by rom1v** [comment]
> When the user restarts his/her device/phone and then attempts to reconnect scrcpy

That's expected, this is the behavior from `adb`.

This is the same if you execute `adb logcat` or `adb shell` for example.

**Comment by MrTeeXD** [comment]
I see. I tried connecting my Phone via USB and so far, it fixed the connection. Shall I close this issue?

**Comment by fusionneur** [comment]
Just updated ethernally script which facilitates wireless mirroring
https://github.com/fusionneur/ethernally

Let me know if you encounter any issue. Thank you
