### ISSUE TITLE
Moving the mobile mirror instance without the borders.

### ISSUE THREAD

**Issue by ThyZlayer** [Genymobile/scrcpy#2666]
When I do --window-borderless, it's the center of the screen, how do I move it around without needing the titlebar?
Is it possible to move it with commands?

**Comment by rom1v** [comment]
It depends on your window manager. On XFCE, Alt + move allows to move. On Windows, I have no idea.

**Comment by ThyZlayer** [comment]
> It depends on your window manager. On XFCE, Alt + move allows to move. On Windows, I have no idea.

on scrcpy, when you do alt+move keys, it just rotates it sadly.

**Comment by ThyZlayer** [comment]
> It depends on your window manager. On XFCE, Alt + move allows to move. On Windows, I have no idea.

Also been trying to search around for the solution can't seem to find it, so I went here lol.
