### ISSUE TITLE
Nothing happens when running

### ISSUE THREAD

**Issue by lil-ty** [Genymobile/scrcpy#267]
cmd output:
* daemon not running; starting now at tcp:5037
* daemon started successfully
scrcpy-server.jar: 1 file pushed. 1.0 MB/s (18570 bytes in 0.017s)

Then nothing else happens, enabled usb debugging on the phone (Samsung Galaxy S5 rooted)

**Comment by rom1v** [comment]
Over USB?

Are there any relevant logs in the output of `adb logcat`?

**Comment by lil-ty** [comment]
No idea how to do that but i fixed it by enabling the setting "Authorize wireless display devices" in developer options

**Comment by JeromeGsq** [comment]
@josuesoto1 @rom1v 
Hello, the same thing happened to me
I had to install "adb" on Windows and everything worked out later.

Like rom1v said, does "adb logcat" work in your command prompt?

**Comment by rom1v** [comment]
> I had to install "adb" on Windows and everything worked out later.

That's weird, you don't need to install it, it is included in the _scrcpy_ archive.

**Comment by SilenceDN** [comment]
Hi, the same problem
```
D:\scrcpy-win64>adb devices
List of devices attached
621QACQC38G7Y   device

D:\scrcpy-win64>scrcpy --bit-rate 2M --max-size 800
scrcpy-server.jar: 1 file pushed. 3.7 MB/s (19346 bytes in 0.005s)
INFO: Initial texture: 448x800
```
nothing happened !

**Comment by rom1v** [comment]
And `adb logcat`?

**Comment by SilenceDN** [comment]
@rom1v It seems that there is nothing particularly unusual in the logcat.

**Comment by rom1v** [comment]
Does it still happen?
