### ISSUE TITLE
Changing Bitrate/width has no effect.

### ISSUE THREAD

**Issue by JustinDBruce** [Genymobile/scrcpy#2674]
- [ x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows 10.]
 - scrcpy server version: [1.18]
 - installation method: [manual build]
 - device model: Samsung TabS7
 - Android version: [11]

**Describe the bug**
I am using the following block of code to call on the scrcpy server to mirror my device. My problem is the quality I have tried several different bitrate options(16M,32M, 64M, 128M), but nothing seems to change the quality. I have also tried to change the max_width, but that seems to have no effect either. 

    def __deploy_server(self) -> None:
        """
        Deploy server to android device
        """
        server_root = os.path.abspath(os.path.dirname(__file__))
        server_file_path = server_root + "\\scrcpy-server.jar"
        self.device.push(server_file_path, "/data/local/tmp/")
        self.__server_stream = self.device.shell(
            [
                "CLASSPATH=/data/local/tmp/scrcpy-server.jar",
                "app_process",
                "/",
                "com.genymobile.scrcpy.Server",
                "1.18",  # Scrcpy server version
                "info",  # Log level: info, verbose...
                f"{self.max_width}",  # Max screen width (long side)
                f"{self.bitrate}",  # Bitrate of video
                f"{self.max_fps}",  # Max frame per second
                f"{self.lock_screen_orientation}",  # Lock screen orientation: LOCK_SCREEN_ORIENTATION
                "true",  # Tunnel forward
                "-",  # Crop screen
                "false",  # Send frame rate to client
                "true",  # Control enabled
                "0",  # Display id
                "false",  # Show touches
                "true" if self.stay_awake else "false",  # Stay awake
                "-",  # Codec (video encoding) options
                "-",  # Encoder name
                "false",  # Power off screen after server closed
            ],
            stream=True,
        )
 
Thanks for any help.

**Comment by rom1v** [comment]
If you run scrcpy manually, do these options have effects?

**Comment by JustinDBruce** [comment]
I assume you mean when I run scrcpy through the cmd? I played around with that a bit and found something odd. When I run scrcpy in the cmd I get the default screen size that seems to be around 1600(as if I would run scrcpy -m 1600) I can change it though (scrcpy -m 800) and it takes effect. 

I want to clarify that the above code block is from a python program(https://github.com/leng-yue/py-scrcpy-client) I used pyinstaller to make it an exe and when I hard code 1600 in for the frame width it is not taking effect.

**Comment by rom1v** [comment]
> I assume you mean when I run scrcpy through the cmd? I played around with that a bit and found something odd. When I run scrcpy in the cmd I get the default screen size that seems to be around 1600 (as if I would run scrcpy -m 1600) I can change it though (scrcpy -m 800) and it takes effect.

So what is odd?

> seems to be around 1600 

The actual texture size is printed in the console.

> I used pyinstaller to make it an exe and when I hard code 1600 in for the frame width it is not taking effect.

Hmm… ok, so there is a problem with your code which run scrcpy with the correct arguments?

**Comment by JustinDBruce** [comment]
Thank you for the help. I found where the issue is in my code, although I am unsure why. I am able to fix it though.
