### ISSUE TITLE
prevent top bar with device name

### ISSUE THREAD

**Issue by ee-diary** [Genymobile/scrcpy#2678]
hi,
first of scrcpy is great project. thumbs up.

i wanted know if it is possible to prevent top bar which shows device name from appearing? in full screen view it does not show but i wanted to record video with small screen from scrcpy and if doable i don't want to show the top bar when resized. 
![1](https://user-images.githubusercontent.com/91747305/135649538-9ecc9bed-36e9-44c0-9449-1eaf257069f3.png)
also how can i make the screen stick when i have a background window such that when i click the background window the scrcpy window does not minimize. those who make tutorial videos have a sticky small screen video screen i wanted to scrcpy to work like that if possible.

thank you

**Comment by rom1v** [comment]
> i wanted know if it is possible to prevent top bar which shows device name from appearing?

To change the title:

```
scrcpy --window-title "My title"
```

To disable window decorations:
```
scrcpy --window-borderless
```

> also how can i make the screen stick when i have a background window such that when i click the background window the scrcpy window does not minimize. 

```
scrcpy --always-on-top
```

More generally, read the README or `scrcpy --help`.

**Comment by ee-diary** [comment]
hi,
thanks for quick support. worked perfectly. One question, I am using windows 7 and when I use scrcpy --window-borderless how to drag and resize the window?looks like it is not possible in windows, i read https://github.com/Genymobile/scrcpy/issues/1825 or is there a way?

**Comment by rom1v** [comment]
Indeed I think it's not possible on Windows.
