### ISSUE TITLE
Green screen when full screen

### ISSUE THREAD

**Issue by tosankrisna** [Genymobile/scrcpy#2682]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: 1.19
 - installation method: manual build
 - device model: Xiaomi Redmi Note 5
 - Android version: 9

**Describe the bug**
Hello I have problem when I try to maximize scrcpy screen using scrcpy -f command and the screen looks green, How can I fix this?

The screen looks like this:

![image](https://user-images.githubusercontent.com/31754768/135758213-3a194192-e459-4f85-9d74-ac0521177540.png)

**Comment by stranno** [comment]
Yes, fullscreen (-f) is also broken for me using Quest 2 and scrcpy 1.19.

**Comment by rom1v** [comment]
Try with an old version of SDL (SDL2.dll in old releases of scrcpy).

**Comment by FilispinCZ** [comment]
Nahradil jsem SDL2.dll verzi z 1.10. Problém vyřešen 👍

**Comment by rgabbo** [comment]
I have the same issue on Android 10

**Comment by rom1v** [comment]
It's a SDL issue, not Android/scrcpy issue. Replace your SDL2.dll by an older version (from an old scrcpy release for example).
