### ISSUE TITLE
unrecognized option '--render-driver=opengl' on Linux Mint 20.2

### ISSUE THREAD

**Issue by lluishi93** [Genymobile/scrcpy#2683]
**Environment**

 - OS: Linux Mint 20.2
 - scrcpy version: 1.12.1
 - installation method: apt
 - device model: 
 - Android version: 10

**Describe the bug**

The **--render-driver** option is not available and I can't figure out why.

```bash
scrcpy: unrecognized option '--render-driver=opengl'
```

**Comment by rom1v** [comment]
> scrcpy version: 1.12.1

Because it's an old version.

You can build/install the latest version manually: https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple
