### ISSUE TITLE
What is lowest API support

### ISSUE THREAD

**Issue by YurieCo** [Genymobile/scrcpy#270]
what is the lowest API that it supports, I tried on old android phone fly 40, and it doesn't work. could u please confirm that and tell me why?

**Comment by rom1v** [comment]
> The Android part requires at least API 21 (Android 5.0).

https://github.com/Genymobile/scrcpy#requirements

See https://github.com/Genymobile/scrcpy/issues/98.

**Comment by YurieCo** [comment]
@rom1v  thanks a lot
