### ISSUE TITLE
Shortcut buttons do not work on Android devices after v1.18 and 1.19 (but other key inputs work normally)

### ISSUE THREAD

**Issue by jaytyk** [Genymobile/scrcpy#2704]
**Environment**
 - OS: Windows
 - scrcpy version:  1.19
 - installation method: Windows release
 - device model:android all device
 - Android version: all os

**Describe the bug**
Shortcut buttons do not work on Android devices after v1.18 and 1.19 (but other key inputs work normally)

Control keys such as CTRL+P do not work at all in Windows. (Check normal operation until version 1.12)

Can you tell me why?

It is a function that must be operated normally for operations such as process movement in lower-level devices with physical buttons.
(ex-CTRL+S)

**Comment by rom1v** [comment]
See the highlights of the change introduced in v1.15: https://github.com/Genymobile/scrcpy/releases/tag/v1.15
