### ISSUE TITLE
Issue while using scrcpy in kali linux 2021.3

### ISSUE THREAD

**Issue by anishkumarroy** [Genymobile/scrcpy#2706]
I am using scrcpy with kali linux 2021.3 and Realme 7......but I am facing this issue- 
![IMG_20211014_162654](https://user-images.githubusercontent.com/90998431/137304682-8af10a97-b682-42b3-bcad-e708d8a3f814.png)
Please help me to resolve it

**Comment by anishkumarroy** [comment]
> What is the result of:
> 
> ```shell
> echo $SCRCPY_SERVER_PATH
> ```
> 
> ?

The command is just running without any error, and is giving no outputs

**Comment by rom1v** [comment]
```bash
which scrcpy
```

**Comment by rom1v** [comment]
If it's 1.17, then `/usr/bin/scrcpy` is v1.17, but `/usr/share/scrcpy/scrcpy-server` is v1.19. This is a problem.

I don't know how you get there, maybe the kali package is broken. But you need the same version for the client and the server.
