### ISSUE TITLE
Pasting: Ctrl+V works but not Shift+Insert

### ISSUE THREAD

**Issue by KeronCyst** [Genymobile/scrcpy#271]
The "v" key on a certain device that I have is busted and hard to press (I am using a typing shortcut to access "v" through another key"), so I can't paste because Shift+Insert doesn't seem to do anything. Could scrcpy be configured to do this? That'd be sweet.

**Comment by rom1v** [comment]
No, shortcuts are hardcoded. I'm closing as duplicate of https://github.com/Genymobile/scrcpy/issues/149.
