### ISSUE TITLE
adb version dosen't match this client

### ISSUE THREAD

**Issue by akshajsingla** [Genymobile/scrcpy#2733]
- [yes ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ yes] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS:Ubuntu 21.10 
  - scrcpy version: [1.19.1]
 - installation method: apt installation
  - device model:Xiaomi , Redmi 9 power
 - Android version: [10]

```
ubuntu@linux:~$ adb tcpip 5555
restarting in TCP mode port: 5555
ubuntu@linux:~$ adb connect xxxxx:5555
connected to xxxxxx.5555
ubuntu@linux:~$ scrcpy
INFO: scrcpy 1.19 <https://github.com/Genymobile/scrcpy>
adb server version (41) doesn't match this client (39); killing...
* daemon started successfully
adb: error: failed to get feature set: no devices/emulators found
ERROR: "adb push" returned with value 1
```

ADB version
```
adb version
Android Debug Bridge version 1.0.41
Version 28.0.2-debian
Installed as /usr/lib/android-sdk/platform-tools/adb
```
Tried almost everything .

BTW scrcpy when in usb debugging doesn't work unless i specify resolution -m 1024

I tried running scrcpy wireless with that command too (scrcpy -m 1024) but resulted in same error

**Comment by elmicha** [comment]
If you are using the snap version, you could also run `adb` from the snap:

    alias adb="LD_LIBRARY_PATH=/snap/scrcpy/current/usr/lib/x86_64-linux-gnu/android/ /snap/scrcpy/current/usr/bin/adb"
    adb connect your_device
    scrcpy
