### ISSUE TITLE
Simulate mouse hover?

### ISSUE THREAD

**Issue by ghost** [Genymobile/scrcpy#2743]
That would be very useful to have, although maybe it is impossible since you seem to replicate finger taps instead of a real android mouse connected through usb?

**Comment by robertkirkman** [comment]
[this](https://github.com/Genymobile/scrcpy/blob/master/doc/mouse.md#physical-mouse-simulation) documents several modes that I believe can do what you want. Unfortunately in my experience with them, I would say it's difficult for a beginner to understand how to control using those modes, so ask me for help if you need it.

**Comment by rom1v** [comment]
Implemented by #5039.
