### ISSUE TITLE
(request) prebuilt kitkat binaries for macOS

### ISSUE THREAD

**Issue by jkrosado** [Genymobile/scrcpy#2745]
**Is your feature request related to a problem? Please describe.**
branch api19 has prebuilt binaries for windows, but not macOS. it won't compile since jdk is too new and downgrading causes other problems, and i just can't compile it

**Describe the solution you'd like**
add precompiled macOS binaries to the guide for the api19 branch

**Describe alternatives you've considered**
checking for other versions of scrcpy with kitkat and macOS support

**Comment by rom1v** [comment]
It does not work for kitkat. Min required version is Android 5.

The branch api19 was just an experimebt. It does not work.
