### ISSUE TITLE
Scrcpy screen disappear like old vhs screen

### ISSUE THREAD

**Issue by shadoso** [Genymobile/scrcpy#2746]
- [Yes] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [Yes] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Linux Mint
 - scrcpy version: scrcpy 1.12.1
 - installation method: sudo apt-get install scrcpy
 - device model: Samsung Galaxy Note10 Lite
 - Android version: Android 11

**Bug**
The scrcpy screen disappear like those old VHS screens from the top to the bottom, but this is just visible if you take a screenshot in the perfect time it occurs, I noticed it because I made a program to take screenshot each 125ms.
I did some tests I will make a list.

**Tests**
- Higher ms: 150, 200, 250, 300 even 500ms. Note increasing the ms don't end this problem just delay it
- Different bit rate, fps and resolution: Highest tried = 14M, 30 fps, standard resolution 1080x2400. Lowest tried = 7M, 12 fps, half resolution 540x1200. I did many attempts until reach the lowest. Note the lowest just delayed the problem
- Turn on and off --always-on-top. Note no changes

I took some screenshots to show the glitch, but just in 1 screenshot I was fast enough to see the scrcpy screen itself glitch, others screenshots just show old captures from the glitch made by the program.
To make it easier to catch those glitches I used 100ms

**Screenshot link:** https://docs.google.com/document/d/1D9tdl50g83z6ww_nsU6T0kJkq9JEtsIZhD9P9yVHYKA/edit?usp=sharing

How I start scrcpy on pycharm
```
os.system("scrcpy --always-on-top --window-x 10 --window-y 10 --bit-rate 7M --max-fps 12 &")
```
Is this a bug or a normal thing, there is any solution ?

**Comment by rom1v** [comment]
Looks like an encoding/decoding issue.

Try with another encoder: https://github.com/Genymobile/scrcpy#encoder
Or upgrade your distrib/ffmpeg on the computer (for the decoder).

**Comment by rom1v** [comment]
> scrcpy: unrecognized option '--encoder'

Use a newer scrcpy version.

**Comment by shadoso** [comment]
Sorry about that I didn't notice that apt-get just allow me to get the old version of scrcpy, I had to use snap to get the new.

- scrcpy --encoder OMX.Exynos.AVC.Encoder **"Have glitch but the display image have no delay"**
- scrcpy --encoder c2.android.avc.encoder **"It took 4 minutes to get the first glitch and have a really big delay"**
- scrcpy --encoder OMX.google.h264.encoder **"It took a lot to display the first glitch, and the delay is massive"**

There are more things that I can do ?

I would like to know your opinion on something.
If this glitch can't be solved, what do you think about emulator would it be a good option ? because I really need the maximum amount of RAM and CPU to run the code, so scrcpy is a perfect option because all the apps run on my smartphone, and I almost have sure that in a old post you said that you had a work on genymotion, so if I had no options maybe emulator ?

**Comment by rom1v** [comment]
> scrcpy --encoder OMX.Exynos.AVC.Encoder "Have glitch but the display image have no delay"

OK, it's a bug in the encoder then. Is it the official ROM?
Either wait for an update or try another device :/

> what do you think about emulator would it be a good option ?

You probably won't get hardware encoder with an emulator (but I don't know).

**Comment by shadoso** [comment]
Yes is the official ROM, I will try others devices tomorrow, I will try on 2 different Motorola and 1 different Samsung.
I can only do this tomorrow because I have to ask for permission to use my parents smartphones (And I also have explain to them that doing these I won't explode or make their phone insecure hahaha)

I will try on windows too, I have dual boot, I have enough time to make some tests. So if you want to suggest any other tests feel free.

So see you tomorrow :D
And thanks a lot for the support rom1v

**Comment by shadoso** [comment]
I did many tests until 5 am here in Brazil, until I discovered the problem, I was really tired so I slept, what I have to tell, isn't a scrcpy bug, is a Linux Mint bug.

I started taking screenshot of others programs screens, like Pycharm, Firefox, Discord, Blender, and none of them made a glitch, BUT when I did this to Linux Mint panel and it showed the glitch, the same happened with videos that I have on my computer, my video card driver is updated, So I remembered the problem that I had trying to make Pillow display image.

**Description**
Linux Mint by default use eog command to display image, and most of other things uses xv and display commands.

So I have almost sure that this problem is because they choose eog, but I'm doing the programming part on windows now, is harder because I really don't know how to use PowerShell like I know on Linux, but is everything fine now.

And rom1v thanks for the help and support, scrcpy is amazing!  <3

**Comment by rom1v** [comment]
Oh, I should have suggested to record:

```
scrcpy --record file.mp4
```
And play the record (to see if the glitch happens in the recorded file too).

According to your last message, I guess it does not appear on the video even if it appears on the screen.

**Comment by shadoso** [comment]
The recording occurs with no problems, I have like 5 hours + recorded to train the AI to use the program, but to decrease the amount of data it needs, I use just the screenshot as input data, just that part that glitches, but the videos is in perfect condition
