### ISSUE TITLE
Certain apps only show a black screen with Android 12

### ISSUE THREAD

**Issue by christoph-kp** [Genymobile/scrcpy#2747]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: 1.19
 - installation method: Windows release
 - device model: Google Pixel 5
 - Android version: 12

**Describe the bug**
After upgrading to Android 12 certain apps only show a black screen when viewed via scrcpy. The apps display fine when viewed directly on the device. Affected apps so far:
Google Authenticator: https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2
Austrian Green Pass app: https://play.google.com/store/apps/details?id=at.gv.brz.wallet
Bank Austria banking app: https://play.google.com/store/apps/details?id=com.bankaustria.android.olb

For all three apps the loading screen is still displayed correctly but the screen turns to black once you can interact with the app.

**Comment by rom1v** [comment]
Yes, that's expected. Android 12 does not allow to create a display with secure flag enabled from shell anymore. See #2129.

**Comment by christoph-kp** [comment]
Thanks, and sorry for not seeing the related issues, looks like I made my search parameters too narrow.

One question though, is there anything I can do to make it work? Using the modified 1.17 binaries did not make a difference for me.

**Comment by rom1v** [comment]
> is there anything I can do to make it work?

No, I don't think so. If you find one, please submit a PR :D

**Comment by sid8840** [comment]
install disable secure flag apk.
