### ISSUE TITLE
Arguments to dbus_message_new_method_call() were incorrect error.

### ISSUE THREAD

**Issue by shivanshu-semwal** [Genymobile/scrcpy#2748]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Debian ( OS: Ubuntu 20.04.3 LTS x86_64)
 - scrcpy version: v1.12.1 (system package) and v1.19 (github simple build using prebuilt server)
 - installation method: `apt` and `./install_release.sh`
 - device model: vivo 1901
 - Android version: 11

**Describe the bug**

Same error on both versions v1.12.1 (system package `apt`) and v1.19 (github simple build using prebuilt server)

```
INFO: scrcpy 1.19 <https://github.com/Genymobile/scrcpy>
* daemon not running; starting now at tcp:5037
* daemon started successfully
/usr/local/share/scrcpy/scrcpy-server:...shed. 1.1 MB/s (37330 bytes in 0.032s
dbus[173261]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../../dbus/dbus-message.c line 1362.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
zsh: abort (core dumped)  scrcpy
```

**Comment by rom1v** [comment]
Looks like an issue in one of the dependencies (sdl?), because scrcpy does not use dbus directly.

https://forum.odroid.com/viewtopic.php?t=30652

**Comment by shivanshu-semwal** [comment]
Thanks for the fast response. Using this solves the issue - `DBUS_FATAL_WARNINGS=0 scrcpy`.

Also, `sudo killall ibus-daemon` does nothing for me. It gives - `ibus-daemon: no process found`.
I'm not using any destop environment, I use `ig-gaps` wm.
