### ISSUE TITLE
scrcpy : command not found

### ISSUE THREAD

**Issue by FranckSCTV** [Genymobile/scrcpy#275]
I'm running scrcpy with no problem on Windows 7 but I can't get it work on MacOS High Sierra.
The device is detected via "adb devices" but when I type "scrcpy" on the command prompt I get a "command not found". I've installed scrcpy via homebrew exactly the way it's explained on the github front page.
I'm pretty sure there is some basic concept that I'm simply missing.
Any help would be highly appreciated!
Thanks!

**Comment by AdoPi** [comment]
I think you have a wrong PATH variable.
Can you please print the result of this command: 
`echo $PATH`

Also check your  /usr/local/opt/ and /usr/local/Cellar/ folders to find any scrcpy folder or binary installed.

**Comment by FranckSCTV** [comment]
> 
> 
> I think you have a wrong PATH variable.
> Can you please print the result of this command:
> `echo $PATH`
> 
> Also check your /usr/local/opt/ and /usr/local/Cellar/ folders to find any scrcpy folder or binary installed.

Here is what I get after doing an echo $PATH:
/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

Also, both  /usr/local/opt/ and /usr/local/Cellar/ are empty of any folder.

Does it mean that something went wrong during the installation?

**Comment by rom1v** [comment]
Is `scrcpy` binary in any of these folders?

**Comment by FranckSCTV** [comment]
> 
> 
> Is `scrcpy` binary in any of these folders?

Both /usr/local/opt/ and /usr/local/Cellar/ are totally empty indeed ( checked with a LS on each one ).

**Comment by numbermaniac** [comment]
@FranckSCTV those two folders aren't in your path though. Did you check if `scrcpy` is in any of the folders that are in your path?

**Comment by rom1v** [comment]
Do you still encounter the problem?

**Comment by Mukeshsinghbankoti** [comment]
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by jadhavrupesh** [comment]
Just Remove Scrcpy by following the cmd
brew remove scrcpy
Then Reinstall scrcpy
brew install scrcpy
