### ISSUE TITLE
mac scrcpy crash

### ISSUE THREAD

**Issue by zhong1158414332** [Genymobile/scrcpy#2756]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: MacOs
 - scrcpy version: 1.19
 - installation method: brew
 - device model: Xiaomi Mi 10
 - Android version: 11

**Describe the bug**
It crashes after about 10 minutes of use

On errors, please provide the output of the console (and `adb logcat` if relevant).

➜  ~ scrcpy --stay-awake --turn-screen-off  --prefer-text
2021-11-04 14:29:25.056 scrcpy[16687:266730] INFO: scrcpy 1.19 <https://github.com/Genymobile/scrcpy>
* daemon not running; starting now at tcp:5037
* daemon started successfully
adb: error: failed to get feature set: no devices/emulators found
2021-11-04 14:29:25.648 scrcpy[16687:266730] ERROR: "adb push" returned with value 1
➜  ~ scrcpy --stay-awake --turn-screen-off  --prefer-text
2021-11-04 14:29:44.297 scrcpy[16693:266962] INFO: scrcpy 1.19 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.19/share/sc...ped. 17.6 MB/s (37330 bytes in 0.002s)
[server] INFO: Device: Xiaomi Mi 10 (Android 11)
[server] INFO: Device screen turned off
2021-11-04 14:29:44.765 scrcpy[16693:266962] INFO: Renderer: metal
2021-11-04 14:29:44.769 scrcpy[16693:266962] INFO: Initial texture: 1080x2336
2021-11-04 14:30:00.153 scrcpy[16693:266962] INFO: New texture: 2336x1080
2021-11-04 14:32:14.996 scrcpy[16693:266962] [CAMetalLayer nextDrawable] returning nil due to 1 second timeout. Set allowsNextDrawableTimeout to keep retrying.
-[_MTLCommandBuffer presentDrawable:]:660: failed assertion `drawable must not be nil.'
[1]    16693 abort      scrcpy --stay-awake --turn-screen-off --prefer-text

```
Please paste terminal output in a code block.
```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               scrcpy [16693]
Path:                  /usr/local/bin/scrcpy
Identifier:            scrcpy
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        zsh [6539]
Responsible:           iTerm2 [6536]
User ID:               501

Date/Time:             2021-11-04 14:32:15.1270 +0800
OS Version:            macOS 12.0.1 (21A559)
Report Version:        12
Bridge OS Version:     6.0 (19P548)
Anonymous UUID:        C90DD713-789F-5738-010C-7F0C781A751D

Sleep/Wake UUID:       7633AC97-A57D-4F5B-A6B4-98405D9824A9

Time Awake Since Boot: 21000 seconds
Time Since Wake:       15455 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
-[_MTLCommandBuffer presentDrawable:]:660: failed assertion `drawable must not be nil.'

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	    0x7ff816d99112 __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7ff816dcf233 pthread_kill + 263
2   libsystem_c.dylib             	    0x7ff816d1bd10 abort + 123
3   libsystem_c.dylib             	    0x7ff816d1b0be __assert_rtn + 314
4   Metal                         	    0x7ff81f7c9732 MTLReportFailure.cold.1 + 43
5   Metal                         	    0x7ff81f7b3fe7 MTLReportFailure + 539
6   Metal                         	    0x7ff81f7c30a7 -[_MTLCommandBuffer presentDrawable:] + 228
7   AMDRadeonX6000MTLDriver       	    0x7ffa3209a0d3 -[GFXAAMD_MtlCmdBuffer presentDrawable:] + 93
8   libSDL2-2.0.0.dylib           	       0x1021b1f45 METAL_RenderPresent + 216
9   scrcpy                        	       0x101909d8c screen_render + 316
10  scrcpy                        	       0x10190a326 screen_handle_event + 710
11  scrcpy                        	       0x101908f99 scrcpy + 1721
12  scrcpy                        	       0x1019031c9 main + 345
13  dyld                          	       0x10a8ba4fe start + 462

Thread 1:: wait-server
0   libsystem_kernel.dylib        	    0x7ff816db7236 waitid + 10
1   scrcpy                        	       0x10190cd98 process_wait + 40
2   scrcpy                        	       0x10190ae94 run_wait_server + 20
3   libSDL2-2.0.0.dylib           	       0x10214c58b SDL_RunThread + 53
4   libSDL2-2.0.0.dylib           	       0x1021b2e7c RunThread + 9
5   libsystem_pthread.dylib       	    0x7ff816dcf514 _pthread_start + 125
6   libsystem_pthread.dylib       	    0x7ff816dcb02f thread_start + 15

Thread 2:
0   libsystem_pthread.dylib       	    0x7ff816dcb00c start_wqthread + 0

Thread 3:: controller
0   libsystem_kernel.dylib        	    0x7ff816d95506 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	    0x7ff816dcfa89 _pthread_cond_wait + 1224
2   libSDL2-2.0.0.dylib           	       0x1021b35cb SDL_CondWait_REAL + 14
3   scrcpy                        	       0x10190531c run_controller + 108
4   libSDL2-2.0.0.dylib           	       0x10214c58b SDL_RunThread + 53
5   libSDL2-2.0.0.dylib           	       0x1021b2e7c RunThread + 9
6   libsystem_pthread.dylib       	    0x7ff816dcf514 _pthread_start + 125
7   libsystem_pthread.dylib       	    0x7ff816dcb02f thread_start + 15

Thread 4:: receiver
0   libsystem_kernel.dylib        	    0x7ff816d96022 __recvfrom + 10
1   scrcpy                        	       0x101907ff8 run_receiver + 40
2   libSDL2-2.0.0.dylib           	       0x10214c58b SDL_RunThread + 53
3   libSDL2-2.0.0.dylib           	       0x1021b2e7c RunThread + 9
4   libsystem_pthread.dylib       	    0x7ff816dcf514 _pthread_start + 125
5   libsystem_pthread.dylib       	    0x7ff816dcb02f thread_start + 15

Thread 5:: stream
0   libsystem_kernel.dylib        	    0x7ff816d96022 __recvfrom + 10
1   scrcpy                        	       0x10190b69d run_stream + 765
2   libSDL2-2.0.0.dylib           	       0x10214c58b SDL_RunThread + 53
3   libSDL2-2.0.0.dylib           	       0x1021b2e7c RunThread + 9
4   libsystem_pthread.dylib       	    0x7ff816dcf514 _pthread_start + 125
5   libsystem_pthread.dylib       	    0x7ff816dcb02f thread_start + 15

Thread 6:
0   libsystem_pthread.dylib       	    0x7ff816dcb00c start_wqthread + 0

Thread 7:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	    0x7ff816d92aba mach_msg_trap + 10
1   libsystem_kernel.dylib        	    0x7ff816d92e2b mach_msg + 59
2   CoreFoundation                	    0x7ff816e96a42 __CFRunLoopServiceMachPort + 319
3   CoreFoundation                	    0x7ff816e9511b __CFRunLoopRun + 1325
4   CoreFoundation                	    0x7ff816e9452d CFRunLoopRunSpecific + 563
5   AppKit                        	    0x7ff819a2dcec _NSEventThread + 132
6   libsystem_pthread.dylib       	    0x7ff816dcf514 _pthread_start + 125
7   libsystem_pthread.dylib       	    0x7ff816dcb02f thread_start + 15

Thread 8:
0   libsystem_pthread.dylib       	    0x7ff816dcb00c start_wqthread + 0

Thread 9:
0   libsystem_pthread.dylib       	    0x7ff816dcb00c start_wqthread + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x000000010a92d600  rcx: 0x00007ff7be6011f8  rdx: 0x0000000000000000
  rdi: 0x0000000000000103  rsi: 0x0000000000000006  rbp: 0x00007ff7be601220  rsp: 0x00007ff7be6011f8
   r8: 0x0000000000000294   r9: 0xcccccccccccccccd  r10: 0x0000000000000000  r11: 0x0000000000200246
  r12: 0x0000000000000103  r13: 0x0000000000000010  r14: 0x0000000000000006  r15: 0x0000000000000016
  rip: 0x00007ff816d99112  rfl: 0x0000000000200246  cr2: 0x00000001060db000
  
Logical CPU:     0
Error Code:      0x02000148 
Trap Number:     133

Binary Images:
    0x7ff816d92000 -     0x7ff816dc8fff libsystem_kernel.dylib (*) <12bd6f13-c452-35ee-9069-51befef29f1a> /usr/lib/system/libsystem_kernel.dylib
    0x7ff816dc9000 -     0x7ff816dd4fff libsystem_pthread.dylib (*) <29a2750e-f31b-3630-8761-242a6bc3e99e> /usr/lib/system/libsystem_pthread.dylib
    0x7ff816c9a000 -     0x7ff816d22fff libsystem_c.dylib (*) <991f58b7-b4c0-3c3a-84a8-c9c571de5a27> /usr/lib/system/libsystem_c.dylib
    0x7ff81f6f0000 -     0x7ff81f826fff com.apple.Metal (258.13) <e8e48b19-b8db-3ed2-830b-01e242f09e0f> /System/Library/Frameworks/Metal.framework/Versions/A/Metal
    0x7ffa32000000 -     0x7ffa324cbfff com.apple.AMDRadeonX6000MTLDriver (4.7.29) <f8f15fff-3f4c-3ac6-b782-54807b5fe258> /System/Library/Extensions/AMDRadeonX6000MTLDriver.bundle/Contents/MacOS/AMDRadeonX6000MTLDriver
       0x1020f2000 -        0x1021f1fff libSDL2-2.0.0.dylib (*) <a8969562-7d7b-3cca-84a4-6a1bd6c2ea5f> /usr/local/Cellar/sdl2/2.0.16/lib/libSDL2-2.0.0.dylib
       0x1018fe000 -        0x101911fff scrcpy (*) <8b9b4033-c30e-3553-aaf7-3524da58dc3c> /usr/local/Cellar/scrcpy/1.19/bin/scrcpy
       0x10a8b5000 -        0x10a920fff dyld (*) <1a6ae033-9438-33c0-8077-988fd885250a> /usr/lib/dyld
    0x7ff816e16000 -     0x7ff817318fff com.apple.CoreFoundation (6.9) <3002b545-6841-3fc8-91a2-bcfbe5872465> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7ff819881000 -     0x7ff81a70dfff com.apple.AppKit (6.9) <dd0028a3-78e3-3a8a-a51b-ddd68123adef> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=971.2M resident=0K(0%) swapped_out_or_unallocated=971.2M(100%)
Writable regions: Total=692.3M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=692.3M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework              1024K        8 
Activity Tracing                   256K        1 
CG backing stores                 3648K        8 
CG image                           160K        6 
ColorSync                          224K       25 
CoreAnimation                       84K        9 
CoreGraphics                        16K        3 
CoreUI image data                 1092K        8 
Foundation                          16K        1 
IOKit                             23.3M        3 
Kernel Alloc Once                    8K        1 
MALLOC                           279.2M      105 
MALLOC guard page                   32K        7 
MALLOC_LARGE (reserved)            248K        1         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
STACK GUARD                       56.0M       10 
Stack                             12.6M       10 
VM_ALLOCATE                        352K       21 
__DATA                            32.4M      409 
__DATA_CONST                      16.8M      260 
__DATA_DIRTY                       668K      119 
__FONT_DATA                          4K        1 
__LINKEDIT                       643.1M       60 
__OBJC_RO                         81.5M        1 
__OBJC_RW                         3120K        2 
__TEXT                           328.1M      419 
__UNICODE                          588K        1 
dyld private memory               1024K        1 
mapped file                      147.6M       21 
shared memory                      796K       21 
===========                     =======  ======= 
TOTAL                              2.0G     1543 
TOTAL, minus reserved VM space     1.6G     1543 

-----------
Full Report
-----------

{"app_name":"scrcpy","timestamp":"2021-11-04 14:32:22.00 +0800","app_version":"","slice_uuid":"8b9b4033-c30e-3553-aaf7-3524da58dc3c","build_version":"","platform":1,"share_with_app_devs":0,"is_first_party":1,"bug_type":"309","os_version":"macOS 12.0.1 (21A559)","incident_id":"F18D3469-0CD8-4234-AA27-D948D44E4A21","name":"scrcpy"}
{
  "uptime" : 21000,
  "procLaunch" : "2021-11-04 14:29:44.2314 +0800",
  "procRole" : "Background",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro16,1",
  "procStartAbsTime" : 21322806099220,
  "coalitionID" : 3462,
  "osVersion" : {
    "train" : "macOS 12.0.1",
    "build" : "21A559",
    "releaseType" : "User"
  },
  "captureTime" : "2021-11-04 14:32:15.1270 +0800",
  "incident" : "F18D3469-0CD8-4234-AA27-D948D44E4A21",
  "bug_type" : "309",
  "pid" : 16693,
  "procExitAbsTime" : 21473690587710,
  "cpuType" : "X86-64",
  "procName" : "scrcpy",
  "procPath" : "\/usr\/local\/bin\/scrcpy",
  "parentProc" : "zsh",
  "parentPid" : 6539,
  "coalitionName" : "com.googlecode.iterm2",
  "crashReporterKey" : "C90DD713-789F-5738-010C-7F0C781A751D",
  "responsiblePid" : 6536,
  "responsibleProc" : "iTerm2",
  "wakeTime" : 15455,
  "bridgeVersion" : {"build":"19P548","train":"6.0"},
  "sleepWakeUUID" : "7633AC97-A57D-4F5B-A6B4-98405D9824A9",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "asi" : {"libsystem_c.dylib":["-[_MTLCommandBuffer presentDrawable:]:660: failed assertion `drawable must not be nil.'"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":266962,"threadState":{"r13":{"value":16},"rax":{"value":0},"rflags":{"value":2097734},"cpu":{"value":0},"r14":{"value":6},"rsi":{"value":6},"r8":{"value":660},"cr2":{"value":4396527616},"rdx":{"value":0},"r10":{"value":0},"r9":{"value":14757395258967641293},"r15":{"value":22},"rbx":{"value":4472362496,"symbolLocation":0,"symbol":"_main_thread"},"trap":{"value":133},"err":{"value":33554760},"r11":{"value":2097734},"rip":{"value":140703511974162,"matchesCrashFrame":1},"rbp":{"value":140702027616800},"rsp":{"value":140702027616760},"r12":{"value":259},"rcx":{"value":140702027616760},"flavor":"x86_THREAD_STATE","rdi":{"value":259}},"queue":"com.apple.main-thread","frames":[{"imageOffset":28946,"symbol":"__pthread_kill","symbolLocation":10,"imageIndex":0},{"imageOffset":25139,"symbol":"pthread_kill","symbolLocation":263,"imageIndex":1},{"imageOffset":531728,"symbol":"abort","symbolLocation":123,"imageIndex":2},{"imageOffset":528574,"symbol":"__assert_rtn","symbolLocation":314,"imageIndex":2},{"imageOffset":890674,"symbol":"MTLReportFailure.cold.1","symbolLocation":43,"imageIndex":3},{"imageOffset":802791,"symbol":"MTLReportFailure","symbolLocation":539,"imageIndex":3},{"imageOffset":864423,"symbol":"-[_MTLCommandBuffer presentDrawable:]","symbolLocation":228,"imageIndex":3},{"imageOffset":630995,"symbol":"-[GFXAAMD_MtlCmdBuffer presentDrawable:]","symbolLocation":93,"imageIndex":4},{"imageOffset":786245,"symbol":"METAL_RenderPresent","symbolLocation":216,"imageIndex":5},{"imageOffset":48524,"symbol":"screen_render","symbolLocation":316,"imageIndex":6},{"imageOffset":49958,"symbol":"screen_handle_event","symbolLocation":710,"imageIndex":6},{"imageOffset":44953,"symbol":"scrcpy","symbolLocation":1721,"imageIndex":6},{"imageOffset":20937,"symbol":"main","symbolLocation":345,"imageIndex":6},{"imageOffset":21758,"symbol":"start","symbolLocation":462,"imageIndex":7}]},{"id":266972,"name":"wait-server","frames":[{"imageOffset":152118,"symbol":"waitid","symbolLocation":10,"imageIndex":0},{"imageOffset":60824,"symbol":"process_wait","symbolLocation":40,"imageIndex":6},{"imageOffset":52884,"symbol":"run_wait_server","symbolLocation":20,"imageIndex":6},{"imageOffset":370059,"symbol":"SDL_RunThread","symbolLocation":53,"imageIndex":5},{"imageOffset":790140,"symbol":"RunThread","symbolLocation":9,"imageIndex":5},{"imageOffset":25876,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":1},{"imageOffset":8239,"symbol":"thread_start","symbolLocation":15,"imageIndex":1}]},{"id":266974,"frames":[{"imageOffset":8204,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":267002,"name":"controller","frames":[{"imageOffset":13574,"symbol":"__psynch_cvwait","symbolLocation":10,"imageIndex":0},{"imageOffset":27273,"symbol":"_pthread_cond_wait","symbolLocation":1224,"imageIndex":1},{"imageOffset":792011,"symbol":"SDL_CondWait_REAL","symbolLocation":14,"imageIndex":5},{"imageOffset":29468,"symbol":"run_controller","symbolLocation":108,"imageIndex":6},{"imageOffset":370059,"symbol":"SDL_RunThread","symbolLocation":53,"imageIndex":5},{"imageOffset":790140,"symbol":"RunThread","symbolLocation":9,"imageIndex":5},{"imageOffset":25876,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":1},{"imageOffset":8239,"symbol":"thread_start","symbolLocation":15,"imageIndex":1}]},{"id":267003,"name":"receiver","frames":[{"imageOffset":16418,"symbol":"__recvfrom","symbolLocation":10,"imageIndex":0},{"imageOffset":40952,"symbol":"run_receiver","symbolLocation":40,"imageIndex":6},{"imageOffset":370059,"symbol":"SDL_RunThread","symbolLocation":53,"imageIndex":5},{"imageOffset":790140,"symbol":"RunThread","symbolLocation":9,"imageIndex":5},{"imageOffset":25876,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":1},{"imageOffset":8239,"symbol":"thread_start","symbolLocation":15,"imageIndex":1}]},{"id":267019,"name":"stream","frames":[{"imageOffset":16418,"symbol":"__recvfrom","symbolLocation":10,"imageIndex":0},{"imageOffset":54941,"symbol":"run_stream","symbolLocation":765,"imageIndex":6},{"imageOffset":370059,"symbol":"SDL_RunThread","symbolLocation":53,"imageIndex":5},{"imageOffset":790140,"symbol":"RunThread","symbolLocation":9,"imageIndex":5},{"imageOffset":25876,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":1},{"imageOffset":8239,"symbol":"thread_start","symbolLocation":15,"imageIndex":1}]},{"id":267024,"frames":[{"imageOffset":8204,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":267039,"name":"com.apple.NSEventThread","frames":[{"imageOffset":2746,"symbol":"mach_msg_trap","symbolLocation":10,"imageIndex":0},{"imageOffset":3627,"symbol":"mach_msg","symbolLocation":59,"imageIndex":0},{"imageOffset":526914,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":319,"imageIndex":8},{"imageOffset":520475,"symbol":"__CFRunLoopRun","symbolLocation":1325,"imageIndex":8},{"imageOffset":517421,"symbol":"CFRunLoopRunSpecific","symbolLocation":563,"imageIndex":8},{"imageOffset":1756396,"symbol":"_NSEventThread","symbolLocation":132,"imageIndex":9},{"imageOffset":25876,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":1},{"imageOffset":8239,"symbol":"thread_start","symbolLocation":15,"imageIndex":1}]},{"id":267141,"frames":[{"imageOffset":8204,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":268436,"frames":[{"imageOffset":8204,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703511945216,
    "size" : 225280,
    "uuid" : "12bd6f13-c452-35ee-9069-51befef29f1a",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703512170496,
    "size" : 49152,
    "uuid" : "29a2750e-f31b-3630-8761-242a6bc3e99e",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703510929408,
    "size" : 561152,
    "uuid" : "991f58b7-b4c0-3c3a-84a8-c9c571de5a27",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703655985152,
    "CFBundleShortVersionString" : "258.13",
    "CFBundleIdentifier" : "com.apple.Metal",
    "size" : 1273856,
    "uuid" : "e8e48b19-b8db-3ed2-830b-01e242f09e0f",
    "path" : "\/System\/Library\/Frameworks\/Metal.framework\/Versions\/A\/Metal",
    "name" : "Metal",
    "CFBundleVersion" : "258.13"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140712557412352,
    "CFBundleShortVersionString" : "4.7.29",
    "CFBundleIdentifier" : "com.apple.AMDRadeonX6000MTLDriver",
    "size" : 5029888,
    "uuid" : "f8f15fff-3f4c-3ac6-b782-54807b5fe258",
    "path" : "\/System\/Library\/Extensions\/AMDRadeonX6000MTLDriver.bundle\/Contents\/MacOS\/AMDRadeonX6000MTLDriver",
    "name" : "AMDRadeonX6000MTLDriver",
    "CFBundleVersion" : "4.0.7"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4329512960,
    "size" : 1048576,
    "uuid" : "a8969562-7d7b-3cca-84a4-6a1bd6c2ea5f",
    "path" : "\/usr\/local\/Cellar\/sdl2\/2.0.16\/lib\/libSDL2-2.0.0.dylib",
    "name" : "libSDL2-2.0.0.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4321173504,
    "size" : 81920,
    "uuid" : "8b9b4033-c30e-3553-aaf7-3524da58dc3c",
    "path" : "\/usr\/local\/Cellar\/scrcpy\/1.19\/bin\/scrcpy",
    "name" : "scrcpy"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4471869440,
    "size" : 442368,
    "uuid" : "1a6ae033-9438-33c0-8077-988fd885250a",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "x86_64h",
    "base" : 140703512485888,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5255168,
    "uuid" : "3002b545-6841-3fc8-91a2-bcfbe5872465",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1855.105"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703556964352,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15257600,
    "uuid" : "dd0028a3-78e3-3a8a-a51b-ddd68123adef",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2113"
  }
],
  "sharedCache" : {
  "base" : 140703508942848,
  "size" : 15213641728,
  "uuid" : "3d05845f-3f65-358f-9ebf-2236e772ac01"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=971.2M resident=0K(0%) swapped_out_or_unallocated=971.2M(100%)\nWritable regions: Total=692.3M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=692.3M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework              1024K        8 \nActivity Tracing                   256K        1 \nCG backing stores                 3648K        8 \nCG image                           160K        6 \nColorSync                          224K       25 \nCoreAnimation                       84K        9 \nCoreGraphics                        16K        3 \nCoreUI image data                 1092K        8 \nFoundation                          16K        1 \nIOKit                             23.3M        3 \nKernel Alloc Once                    8K        1 \nMALLOC                           279.2M      105 \nMALLOC guard page                   32K        7 \nMALLOC_LARGE (reserved)            248K        1         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nSTACK GUARD                       56.0M       10 \nStack                             12.6M       10 \nVM_ALLOCATE                        352K       21 \n__DATA                            32.4M      409 \n__DATA_CONST                      16.8M      260 \n__DATA_DIRTY                       668K      119 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       643.1M       60 \n__OBJC_RO                         81.5M        1 \n__OBJC_RW                         3120K        2 \n__TEXT                           328.1M      419 \n__UNICODE                          588K        1 \ndyld private memory               1024K        1 \nmapped file                      147.6M       21 \nshared memory                      796K       21 \n===========                     =======  ======= \nTOTAL                              2.0G     1543 \nTOTAL, minus reserved VM space     1.6G     1543 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "601d9415f79519000ccd4b69",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "618057de778e4b2a1cf6a5d5"
      },
      "deploymentId" : 240000299
    },
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000153
    },
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    },
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000068
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    },
    {
      "rolloutId" : "602ad4dac86151000cf27e46",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "6182cb1b8763315b96047852"
      },
      "deploymentId" : 240000254
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro16,1, BootROM 1715.40.15.0.0 (iBridge: 19.16.10548.0.0,0), 6 processors, 6-Core Intel Core i7, 2.6 GHz, 16 GB, SMC 
Graphics: Intel UHD Graphics 630, Intel UHD Graphics 630, Built-In
Graphics: AMD Radeon Pro 5300M, AMD Radeon Pro 5300M, PCIe, 4 GB
Display: Color LCD, 3072 x 1920 Retina, Main, MirrorOff, Online
Display: DELL D2421DS, 2560 x 1440 (QHD/WQHD - Wide Quad High Definition), MirrorOff, Online
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, DDR4, 2667 MHz, SK Hynix, HMA81GS6CJR8N-VK
Memory Module: BANK 2/ChannelB-DIMM0, 8 GB, DDR4, 2667 MHz, SK Hynix, HMA81GS6CJR8N-VK
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x7BF), wl0: Jul 12 2021 18:02:56 version 9.30.464.0.32.5.76 FWID 01-c081cfed
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB3.0 Hub
USB Device: USB31Bus
USB Device: USB2.0 Hub
USB Device: Keychron C1
USB Device: Mi 10
USB Device: USB Optical Mouse
USB Device: T2Bus
USB Device: composite_device
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 63.5
Thunderbolt Bus: MacBook Pro, Apple Inc., 63.5

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
Thank you for the detailed report.

Looks like a SDL bug related to metal.

> failed assertion `drawable must not be nil.'

This is the same as #2698.
