### ISSUE TITLE
Ubuntu 18.0.4 can not install 

### ISSUE THREAD

**Issue by LiLeiAndroid** [Genymobile/scrcpy#2758]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.
~$ snap install scrcpy
error: cannot perform the following tasks:
- Download snap "scrcpy" (296) from channel "stable" (Get https://canonical-lcy01.cdn.snapcraftcontent.com/download-origin/canonical-lgw01/M7yvgnqOvyQj64bolfpawIAEwHv7dQ5G_296.snap?interactive=1&token=1636196400_84acf329b31f19aa39c51f3f6bd9f2982ca03afe: read tcp 10.4.12.76:59994->91.189.88.178:443: read: connection reset by peer)

**Comment by rom1v** [comment]
It looks like a snap/server issue.
