### ISSUE TITLE
4K display not working very good with scrcpy

### ISSUE THREAD

**Issue by rullskidan** [Genymobile/scrcpy#276]
What can I do to make it look better? Are you working on better support for 4k screens? Or is this as good as it gets?
![scrcpy](https://user-images.githubusercontent.com/12127465/46029173-ff247c80-c0f2-11e8-86c9-b05d4219a838.png)

**Comment by rom1v** [comment]
If you resize to "pixel perfect" (Ctrl+g), is the quality still bad?

**Comment by rullskidan** [comment]
It is much better but then I only see a small portion of the phone display vertically.
![11](https://user-images.githubusercontent.com/12127465/46033813-65af9780-c0ff-11e8-8248-0e7fe16596cd.png)

**Comment by rom1v** [comment]
Closing as duplicate of #40.

**Comment by Seerddfsd** [comment]
Hi everyone,

I’ve been experiencing some issues with scrcpy when using it on a 4K display. The performance doesn’t seem to be up to par. Has anyone else faced this problem? Any tips or fixes would be appreciated!

Additionally, I’m also interested in finding the [bitlife god mode apk](https://thebitliifeapk.com/). If anyone knows where to get it or has any advice, please let me know.

Thanks!
