### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by Lisboa129** [Genymobile/scrcpy#2764]
Good Morning
Motorola moto G9 power usb C cell phone

notebook vaio fe 14 usb 3.0

hello i would like an executable with commands that allow me to run the program lighter it doesn't consume cpu gpu anything like that but the delay and the video quality is horrible and i don't have the ability to change the scripts.

**Comment by rom1v** [comment]
> the video quality is horrible

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#the-quality-is-low

i don't have the ability to change the scripts

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows
