### ISSUE TITLE
Is have run time like adb time-limit ?

### ISSUE THREAD

**Issue by ShenJiaojiao** [Genymobile/scrcpy#2767]
now scrcpy run command :  scrcpy --record file1.mp4 will be run 3mins.  
the run time can set long or not ?

**Comment by rom1v** [comment]
It is not limited.

If it stops, then you lost your adb connection for some reason (and you should see `WARN: Device disconnected` in the logs).

**Comment by ShenJiaojiao** [comment]
> It is not limited.
> 
> If it stops, then you lost your adb connection for some reason (and you should see `WARN: Device disconnected` in the logs).

a? ubuntu run scrcpy 3mins will be stoped automatic。。。

**Comment by ShenJiaojiao** [comment]
> It is not limited.
> 
> If it stops, then you lost your adb connection for some reason (and you should see `WARN: Device disconnected` in the logs).

OK， i know
