### ISSUE TITLE
scrcpy.exe 1.20 print adb help

### ISSUE THREAD

**Issue by lollita** [Genymobile/scrcpy#2775]
scrcpy.exe 1.20 print adb help

**Comment by rom1v** [comment]
What command do you execute exactly? Could you please copy-paste the whole scrcpy terminal output?

**Comment by lollita** [comment]
Any command.
![scr](https://user-images.githubusercontent.com/720237/141674731-3330a344-44cc-4cb2-a206-e0fd5b6e2aad.png)

**Comment by rom1v** [comment]
1.0.31 is very old. You don't use `adb` from the scrcpy release.

You probably set the `ADB` environment variable to another adb, unset it.

**Comment by lollita** [comment]
Solved, ty.
