### ISSUE TITLE
build fails after Nov 13 2021

### ISSUE THREAD

**Issue by mgrouch** [Genymobile/scrcpy#2777]
```
Found ninja-1.10.1 at /usr/bin/ninja
[11/45] Compiling C object app/scrcpy.p/src_icon.c.oter.c.o
FAILED: app/scrcpy.p/src_icon.c.o 
cc -Iapp/scrcpy.p -Iapp -I../app -I../app/src -I/usr/include/arm-linux-gnueabihf -I/usr/include/SDL2 -I/opt/vc/include -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux -I/usr/include/libusb-1.0 -flto -fdiagnostics-color=always -DNDEBUG -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c11 -O3 -D_REENTRANT -MD -MQ app/scrcpy.p/src_icon.c.o -MF app/scrcpy.p/src_icon.c.o.d -o app/scrcpy.p/src_icon.c.o -c ../app/src/icon.c
../app/src/icon.c:161:8: error: unknown type name 'SDL_PixelFormatEnum'
 static SDL_PixelFormatEnum
        ^~~~~~~~~~~~~~~~~~~
../app/src/icon.c: In function 'to_sdl_pixel_format':
../app/src/icon.c:175:42: error: 'SDL_PIXELFORMAT_BGR444' undeclared (first use in this function); did you mean 'SDL_PIXELFORMAT_BGR24'?
         case AV_PIX_FMT_BGR444BE: return SDL_PIXELFORMAT_BGR444;
                                          ^~~~~~~~~~~~~~~~~~~~~~
                                          SDL_PIXELFORMAT_BGR24
../app/src/icon.c:175:42: note: each undeclared identifier is reported only once for each function it appears in
../app/src/icon.c: In function 'load_from_path':
../app/src/icon.c:200:5: error: unknown type name 'SDL_PixelFormatEnum'; did you mean 'SDL_PixelFormat'?
     SDL_PixelFormatEnum format = to_sdl_pixel_format(frame->format);
     ^~~~~~~~~~~~~~~~~~~
     SDL_PixelFormat
[13/45] Compiling C object app/scrcpy.p/src_fps_counter.c.oo
ninja: build stopped: subcommand failed.

Exited with code exit status 1

CircleCI received exit code 1
```

**Comment by npes87184** [comment]
Same problem

```
dpkg -l | grep sdl 
  
ii  libsdl1.2debian:amd64                      1.2.15+dfsg2-0.1ubuntu0.1                       amd64        Simple DirectMedia Layer
ii  libsdl2-2.0-0:amd64                        2.0.8+dfsg1-1ubuntu1.18.04.4                    amd64        Simple DirectMedia Layer
ii  libsdl2-dev:amd64                          2.0.8+dfsg1-1ubuntu1.18.04.4                    amd64        Simple DirectMedia Layer development files
```

**Comment by rom1v** [comment]
Thank you for the report :+1:

`SDL_PIXELFORMAT_BGR444` has been introduced in SDL 1.0.12 by https://github.com/libsdl-org/SDL/commit/a1c11854f28b7186a744df412aa6273862459c31.

We need to ifdef the version: https://github.com/Genymobile/scrcpy/blob/65b023ac6d586593193fd5290f65e25603b68e02/app/src/compat.h#L37-L54

or even just remove the lines containing `SDL_PIXELFORMAT_BGR444` (we don't care about this format in practice):
https://github.com/Genymobile/scrcpy/blob/65b023ac6d586593193fd5290f65e25603b68e02/app/src/icon.c#L174-L175

Will do it soon.

**Comment by rom1v** [comment]
> Manual build and install libsdl by this method which then produces version 2.0.17 works for me.

Could you please uninstall your SDL 2.0.17, confirm that build fails, then apply this patch:

```diff
diff --git a/app/src/icon.c b/app/src/icon.c
index a3efbb01..e50c5bb2 100644
--- a/app/src/icon.c
+++ b/app/src/icon.c
@@ -172,7 +172,9 @@ to_sdl_pixel_format(enum AVPixelFormat fmt) {
         case AV_PIX_FMT_BGR565BE: return SDL_PIXELFORMAT_BGR565;
         case AV_PIX_FMT_BGR555BE: return SDL_PIXELFORMAT_BGR555;
         case AV_PIX_FMT_RGB444BE: return SDL_PIXELFORMAT_RGB444;
+#if SDL_VERSION_ATLEAST(2, 0, 12)
         case AV_PIX_FMT_BGR444BE: return SDL_PIXELFORMAT_BGR444;
+#endif
         case AV_PIX_FMT_PAL8: return SDL_PIXELFORMAT_INDEX8;
         default: return SDL_PIXELFORMAT_UNKNOWN;
     }
```

And confirm that it works?

Thank you

**Comment by npes87184** [comment]
> > Manual build and install libsdl by this method which then produces version 2.0.17 works for me.
> 
> Could you please uninstall your SDL 2.0.17, confirm that build fails, then apply this patch:
> 
> ```diff
> diff --git a/app/src/icon.c b/app/src/icon.c
> index a3efbb01..e50c5bb2 100644
> --- a/app/src/icon.c
> +++ b/app/src/icon.c
> @@ -172,7 +172,9 @@ to_sdl_pixel_format(enum AVPixelFormat fmt) {
>          case AV_PIX_FMT_BGR565BE: return SDL_PIXELFORMAT_BGR565;
>          case AV_PIX_FMT_BGR555BE: return SDL_PIXELFORMAT_BGR555;
>          case AV_PIX_FMT_RGB444BE: return SDL_PIXELFORMAT_RGB444;
> +#if SDL_VERSION_ATLEAST(2, 0, 12)
>          case AV_PIX_FMT_BGR444BE: return SDL_PIXELFORMAT_BGR444;
> +#endif
>          case AV_PIX_FMT_PAL8: return SDL_PIXELFORMAT_INDEX8;
>          default: return SDL_PIXELFORMAT_UNKNOWN;
>      }
> ```
> 
> And confirm that it works?
> 
> Thank you

I can confirm this patch fixes the problem about `SDL_PIXELFORMAT_BGR444`. However, there is another problem need to be solved, `SDL_PixelFormatEnum`.

Maybe simply `define` it as `int`?

**Comment by rom1v** [comment]
@npes87184 :+1: I opened PR #2781.
