### ISSUE TITLE
Crash on Windows when closing the terminal itself

### ISSUE THREAD

**Issue by rom1v** [Genymobile/scrcpy#2780]
**Environment**
 - OS: Windows 10 in a virtualbox (on Debian)
 - scrcpy version: v1.20, but also happens on previous version (e.g. 1.12.1)
 - installation method: release
 - device model: Nexus 5, connected wirelessly
 - Android version: 6

**Describe the bug**
I run scrcpy from a terminal (either manually from a `cmd.exe`, or double-click on `scrcpy-console.bat`).
If I close the terminal itself (not the scrcpy window), scrcpy crashes:

![crash](https://user-images.githubusercontent.com/543275/141680859-c260bebf-bfa2-4034-90ad-7285c8af0236.png)

We should never close the terminal itself (for example it would break recording), but scrcpy should not crash.

I don't know what Windows does to the program when we close the terminal (it just kills it? is there something to catch?)

I noticed this in v1.20 today, but I am able to reproduce even on v1.12.1. I don't know how it has not been noticed earlier.

Could you reproduce? If yes, are you able to get a stacktrace? (my Windows knowledge is limited)

(@npes87184 your help would be appreciated :wink:)

**Comment by npes87184** [comment]
I am not able to reproduce this problem using following environment.

```
OS: win10 20h2 on surface pro 7
Phone: samsung galaxy s7
Android version: 8.0
Tested terminal: GIT bash, cmd, powershell
```

Testing steps:

1. Open terminal
2. Execute scrcpy.exe
3. Close terminal

**Comment by rom1v** [comment]
Thank you for your tests 👍 

Probably a problem with my Windows in a VM (maybe due to recent automatic updates).

Moreover, I think that closing the window just kills the process (scrcpy), so the program has no opportunity to react or do something wrong.

So I'm closing for now. Thank you.
