### ISSUE TITLE
ERROR: Server Connection Failed

### ISSUE THREAD

**Issue by Akslaton** [Genymobile/scrcpy#2789]
- [x ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: win64-v1.20
 - installation method: Windows release
 - device model: Pixel 4a (Running GrapheneOS)
 - Android version: 12

**Describe the bug**

Over USB Cable, ADB and SCRCPY sees my phone, pushes the SCRCPY Server file, and then fails to connect to the server.

```
PS C:\platform-tools> ./scrcpy
INFO: scrcpy 1.20 <https://github.com/Genymobile/scrcpy>
C:\platform-tools\scrcpy-server: 1 file pushed, 0 skipped. 94.2 MB/s (37139 bytes in 0.000s)
[server] INFO: Device: Google Pixel 4a (Android 12)
ERROR: Server connection failed
```

Thank you

**Comment by rom1v** [comment]
Is another scrcpy instance running at the same time? (#2779)

Could you run `scrcpy -Vdebug`?

**Comment by Akslaton** [comment]
I don't think there are any other Scrcpy instances running.

PS C:\platform-tools> ./scrcpy -Vdebug
INFO: scrcpy 1.20 <https://github.com/Genymobile/scrcpy>
DEBUG: Using server (portable): C:\platform-tools\scrcpy-server
DEBUG: Screensaver enabled
C:\platform-tools\scrcpy-server: 1 file pu...skipped. 79.9 MB/s (37139 bytes in 0.000s)
[server] INFO: Device: Google Pixel 4a (Android 12)
[server] DEBUG: Controller stopped
[server] DEBUG: Using encoder: 'c2.qti.avc.encoder'
[server] DEBUG: Screen streaming stopped
[server] DEBUG: Device message sender stopped
DEBUG: Interrupting socket
DEBUG: Server disconnected
DEBUG: Server terminated
ERROR: Server connection failed

**Comment by rom1v** [comment]
Try with another encoder: https://github.com/Genymobile/scrcpy#encoder

**Comment by rom1v** [comment]
Also, could you test the version from #2783 and see if the console output is different?

**Comment by Akslaton** [comment]
Yesterday after work, I seem to have gotten SCRCPY working.
I tried closing a few programs that run in the system tray... I closed Discord, Syncthing and I disconnected my ExpressVPN. 
Unfortunately I closed them all at once and then tried SCRCPY, so I have no idea which one was causing the server connection  fail error.

I've tried turning those programs back on one at a time to see if the issue returned and it has not, which is king of frustrating from a troubleshooting perspective.

**Comment by rom1v** [comment]
If that happen again, switch to the version from #2783, I'm pretty sure that it is related if you're on Windows.

**Comment by bsudhanva** [comment]
same issue coming up
scrcpy -Vdebug gives

C:\Users\>scrcpy -Vdebug
scrcpy 3.2 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     --> (tcpip)  192.168.1.1:5555               device 
DEBUG: Device serial: 192.168.1.1:5555
DEBUG: Using server (portable): \scrcpy-win64-v3.2\scrcpy-server
D:\scrcpy-win64-v3.2\scrcpy-se...1 file pushed, 0 skipped. 7.0 MB/s (90888 bytes in 0.012s)
[server] INFO: Device: [OnePlus] OnePlus AC2001 (Android 12)
[server] DEBUG: Using video encoder: 'OMX.qcom.video.encoder.avc'
[server] DEBUG: Using audio encoder: 'c2.android.opus.encoder'
[server] ERROR: Capture/encoding error: android.media.MediaCodec$CodecException: Error 0xfffffff4
[server] INFO: Retrying with -m1920...
[server] ERROR: Capture/encoding error: android.media.MediaCodec$CodecException: Error 0xfffffff4
DEBUG: Serv[server] INFO: Retrying with -m1600...
er connected
DEBUG: Starting controller thread
DEBUG: Starting receiver thread
[server] ERROR: Capture/encoding error: android.media.MediaCodec$CodecException: Error 0xfffffff4
[server] INFO: Retrying with -m1280...
DEBUG: Using icon (porta[server] INFO: Retrying with -m1024...
b[server] ERROR: Capture/encoding error: android.media.MediaCodec$CodecException: Error 0xfffffff4
le): D:\scrcpy-win64-v3.2\ic[server] ERROR: Capture/encoding error: android.media.MediaCodec$CodecException: Error 0xfffffff4
on.png[server] INFO: Retrying with -m800...

[server] ERROR: Capture/encoding error: android.media.MediaCodec$CodecException: Error 0xfffffff4
[server] DEBUG: Screen streaming stopped
D[server] DEBUG: Device message sender stopped
E[server] ERROR: Exception on thread Thread[video,5,main]
Bandroid.media.MediaCodec$CodecException: Error 0xfffffff4
U       at android.media.MediaCodec.native_configure(Native Method)
G       at android.media.MediaCodec.configure(MediaCodec.java:2176)
:       at android.media.MediaCodec.configure(MediaCodec.java:2092)
        at com.genymobile.scrcpy.video.SurfaceEncoder.streamCapture(SurfaceEncoder.java:92)
R[server] DEBUG: Controller stopped
e       at com.genymobile.scrcpy.video.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-video-SurfaceEncoder(SurfaceEncoder.java:296)
c       at com.genymobile.scrcpy.video.SurfaceEncoder$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
e       at java.lang.Thread.run(Thread.java:1012)
iver stopped
[server] DEBUG: Audio encoder stopped
DEBUG: Server disconnected
DEBUG: Server terminated
INFO: Renderer: direct3d
DEBUG: Trilinear filtering disabled (not an OpenGL renderer)
DEBUG: Demuxer 'video': starting thread
DEBUG: Demuxer 'audio': starting thread
DEBUG: Demuxer 'video': end of frames
WARN: Device disconnected
DEBUG: quit...
DEBUG: Controller stopped
DEBUG: Demuxer 'audio': end of frames

**Comment by thejuicyroma** [comment]
This is an old thread, but just adding that I followed the tip @Akslaton mentioned about closing apps running in the tray bar. For me the issue was that I had DroidCam Client running. Once I quit it, scrcpy worked no problem.
