### ISSUE TITLE
The server version (1.19) does not match the client (1.20)

### ISSUE THREAD

**Issue by wchensc** [Genymobile/scrcpy#2791]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: macOS
 - scrcpy version: 1.20
 - installation method: manual build
 - device model: SM-G920F
 - Android version: 7

**Describe the bug**
Running latest code on 1.20 resulted into

```
java.lang.IllegalArgumentException: The server version (1.19) does not match the client (1.20)
	at com.genymobile.scrcpy.Server.createOptions(Server.java:134)
	at com.genymobile.scrcpy.Server.main(Server.java:251)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:316)

```
I also tried copying the 1.20 prebuilt server to the path but it showed the same error message.

**Comment by rom1v** [comment]
Either you had set SCRCPY_SERVER_PATH to the path of the server v1.19, or you built using prebuilt server v1.19.

If you run `scrcpy -Vdebug`, it will print the path of the server it uses.
