### ISSUE TITLE
1.2.0 Multiple devices cannot be connected at the same time

### ISSUE THREAD

**Issue by 302633** [Genymobile/scrcpy#2794]
-  I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 -  I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS:  Windows
 - scrcpy version: [1.2.0]
 - installation method: [manual build]
 - device model:Xiaomi8 and oneplus9R
 - Android version: [10 and 11]

**Describe the bug**
In version 1.1.9, I can connect two devices normally. After updating to 1.2.0, I found that two devices cannot be connected at the same time, only one device can be connected, which makes multi-device users uncomfortable. I returned to version 1.19 and can be used normally

**Comment by rom1v** [comment]
Thank you for the report.

It is fixed by #2783 on `dev`.
