### ISSUE TITLE
Can not compile the scrcoy.exe

### ISSUE THREAD

**Issue by wentiancanye** [Genymobile/scrcpy#2795]
Hi. I have read the BUILD.md carefully and  installed  all the required packages.
However, when I run the following commands to compile, it fails.
`cd prebuilt-deps/`
`make prepare-win64`
`cd ..`
`meson x --buildtype release --strip -Db_lto=true -Dcrossbuild_windows=true --cross-file=cross_win64.txt -Dcompile_server=false -Dcompile_app=true -Dportable=true`
`ninja -Cx`

The error message is as follows：

![compile error](https://user-images.githubusercontent.com/34967997/141981104-e85c97c9-bb6b-43ae-a9e7-e099846e4287.png)

Can you help me?

**Comment by rom1v** [comment]
(Please post the terminal output as text instead of screenshot)

It has been fixed on `dev` branch by 52cebe1597cef201f28dc3c6122dc022616362c2. Checkout the `dev` branch and it will work.

I don't understand why I don't have link issues on v1.20 on my machine.

**Comment by wentiancanye** [comment]
You rock! I compiled it successfully now!
(I will post the terminal output as text on next issue. ^_^)
