### ISSUE TITLE
Display corruption in Blue Archive

### ISSUE THREAD

**Issue by Renari** [Genymobile/scrcpy#2797]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: 1.20
 - installation method: Windows release
 - device model: ROG Phone 3
 - Android version: 11

**Describe the bug**
Display corruption happening while playing the game Blue Archive. This does not happen while not connected via scrcpy.

Examples: (seizure warning)
https://drive.google.com/file/d/1kP0qu7XYKhp0tchirLHxoQq588FR6TDC/view?usp=sharing
https://drive.google.com/file/d/1Y6qUO6wW9hdNoXkH2ALvYc_UQ2tb5JLO/view?usp=sharing

On errors, please provide the output of the console (and `adb logcat` if relevant)

https://gist.github.com/Renari/26495b59559606ddd89562e8dc935328

**Comment by rom1v** [comment]
Looks like a device/encoder issue.

The game and the encoder probably share some hardware resource, and it is not managed correctly.

Does it also happen with `screenrecord`:

```bash
adb shell screenrecord /sdcard/file.mp4
adb pull /sdcard/file.mp4
```
?

**Comment by Renari** [comment]
Yeah it seems to happen with built in recording functionality as well, basically if anything is recording the screen it happens, I'm not sure scrcpy can do anything at this point.

The issue is replicated on two devices (S10, ROG Phone 3) and without scrcpy via using the Samsung Record feature and the Armory Crate record feature on both phones.

**Comment by Renari** [comment]
Going to go ahead and close this since it appears not to be a scrcpy issue.

**Comment by axionl** [comment]
@Renari Hi, I seem to be experiencing this problem, have you found a solution?

https://user-images.githubusercontent.com/8396456/152275859-59819873-8583-4945-97ad-2e40287d0e9a.mp4

**Comment by Renari** [comment]
ASUS released a patch for my device and that game specifically.
