### ISSUE TITLE
V1.20 version can only open one device window when multiple devices are connected.

### ISSUE THREAD

**Issue by 302633** [Genymobile/scrcpy#2800]
Please release a new patch version (1.20.1) as soon as possible. Multiple devices of version 1.2.0 can only start one mirror. Regarding #2783, I am a novice and cannot understand, I can only ask you to update it as soon as possible. thanks

**Comment by rom1v** [comment]
Hi,

I plan to release a new version soon (before the end of the week) for this bug: https://github.com/Genymobile/scrcpy/issues/2779#issuecomment-968644656

I have still other few things to fix before the release.

But meanwhile, you can just replace `scrcpy.exe` and `scrcpy-server` published in #2783, and you'll get a working v1.20.

**Comment by min969** [comment]
> ကျေးဇူးပြု၍ patch ဗားရှင်းအသစ် (1.20.1) ကို တတ်နိုင်သမျှ အမြန်ဆုံးထုတ်ပါ။ ဗားရှင်း 1.2.0 ၏ စက်အများအပြားသည် မှန်တစ်ခုသာ စတင်နိုင်သည်။ [နံပါတ် 2783](https://github.com/Genymobile/scrcpy/pull/2783) နှင့် ပတ်သက်၍ [ကျွန်ုပ်သည်](https://github.com/Genymobile/scrcpy/pull/2783) အတွေ့အကြုံမရှိသေးသူဖြစ်ပြီး နားမလည်နိုင်ပါ၊ တတ်နိုင်သမျှ အမြန်ဆုံး အပ်ဒိတ်လုပ်ရန်သာ တောင်းဆိုနိုင်ပါသည်။ ကျေးဇူးတင်ပါတယ်

**Comment by 302633** [comment]
> 你好，
> 
> 我计划很快（在本周末之前）针对此错误发布新版本：[#2779（评论）](https://github.com/Genymobile/scrcpy/issues/2779#issuecomment-968644656)
> 
> 在发布之前我还有其他几件事要做。
> 
> 但与此同时，您只需替换`scrcpy.exe`并`scrcpy-server`发布在[#2783 中](https://github.com/Genymobile/scrcpy/pull/2783)，您就会得到一个有效的 v1.20。

Thank you. I understood you when you said to replace the file. Now I can use it normally

**Comment by 302633** [comment]
> Hi,
> 
> I plan to release a new version soon (before the end of the week) for this bug: [#2779 (comment)](https://github.com/Genymobile/scrcpy/issues/2779#issuecomment-968644656)
> 
> I have still other few things to do before the release.
> 
> But meanwhile, you can just replace `scrcpy.exe` and `scrcpy-server` published in #2783, and you'll get a working v1.20.

Thank you. I understood you when you said to replace the file. Now I can use it normally
