### ISSUE TITLE
Black Screen on Linux, works fine on Windows. 

### ISSUE THREAD

**Issue by Practicalbutterfly5** [Genymobile/scrcpy#2803]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Arch32
 - scrcpy version: 1.20
 - installation method: `yay -S scrcpy`
 - device model: Redmi Note 5 pro
 - Android version: 12

**Describe the bug**

* Black Screen of scrcpy window
* Touch Works
* `scrcpy --record file.mp4` works perfectly and is able to record screen
 

```
~ scrcpy -m 1024
INFO: scrcpy 1.20 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 fil...pped. 2.0 MB/s (37139 bytes in 0.018s)
[server] INFO: Device: Xiaomi Redmi Note 5 Pro (Android 12)
INFO: Renderer: opengl
INFO: OpenGL version: 1.4 Mesa 21.2.1
WARN: Trilinear filtering disabled (OpenGL 3.0+ or ES 2.0+ required)
INFO: Initial texture: 512x1024

```

I have tried all the available codecs, but still same black screen.

scrcpy worked perfectly in Windows 10 on the same pc.

**Comment by rom1v** [comment]
Probably a driver issue :/

**Comment by Practicalbutterfly5** [comment]
> Probably a driver issue :/

So is it a device(custom rom) side driver issue or linux side issue?

**Comment by rom1v** [comment]
> So is it a device(custom rom) side driver issue or linux side issue?

Linux-side issue.

You could try running with a software renderer (not recommended, but just to debug):

```
scrcpy --render-driver=software
```

If it works with a software renderer but not an opengl renderer, then there is an issue with your graphics drivers.

**Comment by Practicalbutterfly5** [comment]
> > So is it a device(custom rom) side driver issue or linux side issue?
> 
> Linux-side issue.
> 
> You could try running with a software renderer (not recommended, but just to debug):
> 
> ```
> scrcpy --render-driver=software
> ```
> 
> If it works with a software renderer but not an opengl renderer, then there is an issue with your graphics drivers.

I tried all the available render driver.

software, opengles, opengles2, direct3d all work perfectly.

opengl, metal show black screen.

So out of the one's working which one should I prefer.

**Comment by rom1v** [comment]
> software, opengles, opengles2, direct3d all work perfectly.

The render driver is just an int for SDL, you must check in the console output which renderer is actually used:

```
INFO: Renderer: opengl
```

For example, I'm pretty sure that `direct3d` does not work on Linux :smile:

**Comment by Practicalbutterfly5** [comment]
Finally got it working with opengles2.
Thanks. Closing the issue.

**Comment by Andrio-Codes** [comment]
> Finally got it working with opengles2. Thanks. Closing the issue.

Can you please explain how you fixed it?
https://github.com/Genymobile/scrcpy/issues/2281#issuecomment-1204861773

**Comment by Practicalbutterfly5** [comment]
> Can you please explain how you fixed it? [#2281 (comment)](https://github.com/Genymobile/scrcpy/issues/2281#issuecomment-1204861773)

Try other render drivers.

**Comment by Andrio-Codes** [comment]
> > Can you please explain how you fixed it? [#2281 (comment)](https://github.com/Genymobile/scrcpy/issues/2281#issuecomment-1204861773)
> 
> Try other render drivers.

I do not see the option --render-driver in the --help of scrcpy. Is it removed?

**Comment by Practicalbutterfly5** [comment]
> I do not see the option --render-driver in the --help of scrcpy. Is it removed?

You must be using really old version of scrcpy.

**Comment by Andrio-Codes** [comment]
> > I do not see the option --render-driver in the --help of scrcpy. Is it removed?
> 
> You must be using really old version of scrcpy.

I installed it using snap and apt. Both had old versions. Now as suggested, I complied latest and is working fine. Thanks.

**Comment by Practicalbutterfly5** [comment]
> Both had old versions. Now as suggested

Did you remove the apt version first before installing snap version? Snap is always the latest no matter the distribution.

**Comment by Andrio-Codes** [comment]
> > Both had old versions. Now as suggested
> 
> Did you remove the apt version first before installing snap version? Snap is always the latest no matter the distribution.

😅 I didn't know that I already had the apt version installed and I installed snap version on top of it.
