### ISSUE TITLE
ERROR: Could not open image codec

### ISSUE THREAD

**Issue by cadchup** [Genymobile/scrcpy#2804]
Trying to get this promising scrcpy command running I met this message. Any ideas? I've installed it as snap package in Xubuntu 20.04.

`scrcpy
INFO: scrcpy 1.20 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 1.0 MB/s (37139 bytes in 0.037s)
[server] INFO: Device: HMD Global Nokia X10 (Android 11)
INFO: Renderer: opengl
INFO: OpenGL version: 3.1 Mesa 20.0.8
INFO: Trilinear filtering enabled
ERROR: Could not open image codec: /usr/local/share/icons/hicolor/256x256/apps/scrcpy.png
WARN: Could not load icon
INFO: Initial texture: 1080x2400
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:2127)
	at android.media.MediaCodec.configure(MediaCodec.java:2043)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:233)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:86)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:65)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
	at com.genymobile.scrcpy.Server.main(Server.java:255)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
WARN: Killing the server...
`

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

**Comment by cadchup** [comment]
Thanks! I've tried:
`scrcpy -m 1920`
`scrcpy -m 1024`
`scrcpy -m 800`
It works... However, it disconnects unexpected withing a period of 1 s to 1 minute with the following:
`scrcpy -m 1024`
`INFO: scrcpy 1.20 <https://github.com/Genymobile/scrcpy>`
`/usr/local/share/scrcpy/scrcpy-server:...shed. 5.0 MB/s (37139 bytes in 0.007s)`
`[server] INFO: Device: HMD Global Nokia X10 (Android 11)`
`INFO: Renderer: opengl`
`INFO: OpenGL version: 3.1 Mesa 20.0.8`
`INFO: Trilinear filtering enabled`
`ERROR: Could not open image codec: /usr/local/share/icons/hicolor/256x256/apps/scrcpy.png`
`WARN: Could not load icon`
`INFO: Initial texture: 464x1024`
`WARN: Device disconnected`
Probably not of critical importance:
`locate scrcpy.png`
`/snap/scrcpy/308/usr/local/share/icons/hicolor/256x256/apps/scrcpy.png`

**Comment by rom1v** [comment]
> WARN: Device disconnected

The adb connection is closed: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#device-disconnected

You can observe this by running a separate `adb shell`: it will be closed at the very same time.

> ERROR: Could not open image codec: /usr/local/share/icons/hicolor/256x256/apps/scrcpy.png

Probably an issue in the snap package.

You could try a non-snap version.

**Comment by cadchup** [comment]
Thank you very much for clarifying. Really appreciated. I've got it running.
