### ISSUE TITLE
lockscreen disconnect and power button 

### ISSUE THREAD

**Issue by br0ze** [Genymobile/scrcpy#2805]
when i unlock my phone with pattern lock then it disconnected
when i press power button to turn phone screen off, i got disconnected too
My phone at android 10
And what resolution with bitrate give me lowest latency through wifi

**Comment by rom1v** [comment]
> when i unlock my phone with pattern lock then it disconnected
> when i press power button to turn phone screen off, i got disconnected too

See https://github.com/Genymobile/scrcpy/issues/1382#issuecomment-627591729

> And what resolution with bitrate give me lowest latency through wifi

The lower the definition, the lower the bitrate, the lower will be the latency.

For example, `scrcpy -m400 -b1M` should give you a better latency, but you probably don't want that.

If you have a recent phone and your wifi is at 5GHz, then your latency should be small even at full definition. This was not the case with old/low-end devices or less performant wifi.

**Comment by br0ze** [comment]
thanks, how to bind key on the screen for play game like pubg?

**Comment by rom1v** [comment]
You can't. #702.

**Comment by rom1v** [comment]
You can't. #712.
