### ISSUE TITLE
Cannot paste using the Windows clipboard

### ISSUE THREAD

**Issue by 302633** [Genymobile/scrcpy#2806]
Cannot use shortcut key Win+V clipboard，When I use the Windows clipboard to paste, nothing happens

**Comment by rom1v** [comment]
Which scrcpy version?
Which Android version?

Please follow the issue template to post an issue, this would avoid such round-trips.

**Comment by 302633** [comment]
> 哪个 scrcpy 版本？ 哪个安卓版本？
> 
> 请按照问题模板发布问题，这将避免此类往返。

1.20 And 1.19

**Comment by 302633** [comment]
> 哪个scrcpy版本？ 哪个安卓版本？
> 
> 请按照问题模板问题，这将避免出现问题。



> Which scrcpy version? Which Android version?
> 
> Please follow the issue template to post an issue, this would avoid such round-trips.

Scrcpy 1.20 And 1.19
Android 11 and 10

> Which scrcpy version? Which Android version?
> 
> Please follow the issue template to post an issue, this would avoid such round-trips.

**Comment by rom1v** [comment]
Does Ctrl+v work?

Also: https://github.com/Genymobile/scrcpy/pull/1423#issuecomment-967771961

**Comment by 302633** [comment]
> Ctrl+v

Ctrl+v works, but I want to use the WIN+V system clipboard, which allows me to use history more effectively

> Does Ctrl+v work?
> 
> Also: [#1423 (comment)](https://github.com/Genymobile/scrcpy/pull/1423#issuecomment-967771961)

Ctrl+v works, but I want to use the WIN+V system clipboard, which allows me to use history more effectively

**Comment by rom1v** [comment]
> Ctrl+v works, but I want to use the WIN+V

In theory, it should do the very same thing, unless your device does not behave as expected when setting the device clipboard programmatically. For this problem, there is `--legacy-paste`. Which device is it?

Please read: https://github.com/Genymobile/scrcpy#copy-paste

And apparently, there is an option to change on some device to make it work (https://github.com/Genymobile/scrcpy/pull/1423#issuecomment-967771961).

**Comment by 302633** [comment]
> > Ctrl+v works, but I want to use the WIN+V
> 
> In theory, it should do the very same thing, unless your device does not behave as expected when setting the device clipboard programmatically. For this problem, there is `--legacy-paste`. Which device is it?
> 
> Please read: https://github.com/Genymobile/scrcpy#copy-paste
> 
> And apparently, there is an option to change on some device to make it work ([#1423 (comment)](https://github.com/Genymobile/scrcpy/pull/1423#issuecomment-967771961)).

It doesn't suit me, I am OnePlus 9R of Android 11 and want to use the Windows system clipboard. The situation is inconsistent

**Comment by 302633** [comment]
> > Ctrl+v works, but I want to use the WIN+V
> 
> In theory, it should do the very same thing, unless your device does not behave as expected when setting the device clipboard programmatically. For this problem, there is `--legacy-paste`. Which device is it?
> 
> Please read: https://github.com/Genymobile/scrcpy#copy-paste
> 
> And apparently, there is an option to change on some device to make it work ([#1423 (comment)](https://github.com/Genymobile/scrcpy/pull/1423#issuecomment-967771961)).

Can you use it, paste it from the Windows clipboard into the phone？

**Comment by rom1v** [comment]
That is the expected behavior, yes.
