### ISSUE TITLE
Mouse clicks not working with phone Poco X3 Pro

### ISSUE THREAD

**Issue by Thorsterr** [Genymobile/scrcpy#2808]
Any idea how to make it work, please? Pretty please?

It worked perfectly fine for me with my old phone. But not with this new one. Any idea why? And how to fix it?

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work

**Comment by Thorsterr** [comment]
> https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work

I saw this and I have USB debugging allowed... what else can I do? Please help me I am not good in programming etc, just need to make it work, thanks!

**Comment by rom1v** [comment]
> I saw this and I have USB debugging allowed

It's not only USB debugging, but Security Settings.
