### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by lauris0910** [Genymobile/scrcpy#2810]
- OS: Windows
 - scrcpy version: win64 v1.20
 - installation method: Windows release 
 - device model: Redmi Note 7
 - Android version: 11 (custom rom)

Commands dont do anything (there doesnt seem to be any response from imputting a command in cmd) and ive already tried running it as administrator.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows

**Comment by lauris0910** [comment]
The command only works once, what else should i do?

**Comment by rom1v** [comment]
On Windows, there is a bug in v1.20. It is fixed by #2783 on development branch, and binaries are available.
Replace your `scrcpy.exe` and `scrcpy-server` by the ones from #2783.

**Comment by lauris0910** [comment]
ive replaced the files, how do i confirm that this works?

**Comment by rom1v** [comment]
How do you execute the commands? What happens when they "donnt work"? What heppens when they "work"?

**Comment by lauris0910** [comment]
I open scrcpy.exe with my phone plugged in with USB debugging enabled, and i can see the screen of my phone, but every time I try to execute a command on the other window that isn't the screen that was launched by scrcpy.exe, it doesn't seem to work at all.

**Comment by rom1v** [comment]
That's not how it works. Did you read https://github.com/Genymobile/scrcpy/issues/2810#issuecomment-972968305 ?

**Comment by lauris0910** [comment]
Yes i have, but that only seems to work for 1 command only, after that command executes the thing launches and the rest of commands that i might want to type won't work, i will re-try doing that but for now that's all the info i have.

**Comment by rom1v** [comment]
You must pass all the parameters in one line. For example:

```
scrcpy --max-size 1024 --max-fps 5
```

**Comment by lauris0910** [comment]
Ohh, i didn't knew that was possible, il do that then, thanks for informing me about that possibility.
