### ISSUE TITLE
ERROR: Failed to enable HID over AOA, fallback to default keyboard injection method (-K/--hid-keyboard ignored)

### ISSUE THREAD

**Issue by entodoays** [Genymobile/scrcpy#2820]
- [ x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Ubuntu 21.10
 - scrcpy version 1.20
 - installation method: snap
 - device model: Moto G4 Plus
 - Android 9

**Describe the bug**
The title says it all. Running scrcpy with the -K option churns out this error.
```
ERROR: Failed to enable HID over AOA, fallback to default keyboard injection method (-K/--hid-keyboard ignored)
```

**Comment by rom1v** [comment]
> installation method: snap

Try a non-snap install.

**Comment by jaron-l** [comment]
I just tested this with the source install method and it works (while still breaking with snap). Probably the containerization with snaps to be the issue. Also, noting here that the source install is the only method to test this with Debian derivatives because the apt repo is at 1.12.

There's probably a way to request permission to usb devices with snap packages that could be investigated.

**Comment by rom1v** [comment]
> Also, noting here that the source install is the only method to test this with Debian derivatives because the apt repo is at 1.12.

Yes, Debian currently packages 1.19, and depending on the version of your derivative, you could have 1.12: https://repology.org/project/scrcpy/versions

That's one of the reason I added this install script :wink:

**Comment by jaron-l** [comment]
@entodoays, looks like this is a issue with the snapcraft.yaml file on [scrcpy-snap](https://github.com/sisco311/scrcpy-snap) and this issue should probably be moved there.

**Comment by entodoays** [comment]
https://github.com/sisco311/scrcpy-snap/issues/29#issue-1061683563

**Comment by entodoays** [comment]
Physical keyboard simulation works only when connected through USB and not through TCP/IP. I had connected through the latter pathway. When I tested it with a physical USB connection it worked.
