### ISSUE TITLE
scrcpy can not run. zsh: killed     scrcpy

### ISSUE THREAD

**Issue by AndyZhuAZ** [Genymobile/scrcpy#2823]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: macOS 12.0.1 (21A559)
 - scrcpy version: 1.20
 - installation method: brew
 - device model: G8142
 - Android version: 9

**Describe the bug**
scrcpy always be killed on m1 mac, reinstall adb and scrcpy not work.

```
 ~ % adb --version
Android Debug Bridge version 1.0.41
Version 31.0.3-7562133
Installed as /Users/andy/Developer/platform-tools/adb
~ % brew reinstall scrcpy
==> Downloading https://ghcr.io/v2/homebrew/core/scrcpy/manifests/1.20
Already downloaded: /Users/andy/Library/Caches/Homebrew/downloads/58fcf67a7d07ab3ee2c4e1b2ce2ce654e52b8f0c917254f19d9d35873f514301--scrcpy-1.20.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/scrcpy/blobs/sha256:2a586a677ed73bfa4ff34cc7cf67ad662973120f7e00e9ccf26913ee3e3778fd
Already downloaded: /Users/andy/Library/Caches/Homebrew/downloads/dc7718c4d3c3e56145e26b1961c4303910c28d588306b109df940882e636b6c5--scrcpy--1.20.arm64_monterey.bottle.tar.gz
==> Reinstalling scrcpy
==> Pouring scrcpy--1.20.arm64_monterey.bottle.tar.gz
==> Caveats
At runtime, adb must be accessible from your PATH.

You can install adb from Homebrew Cask:
  brew install --cask android-platform-tools
==> Summary
🍺  /opt/homebrew/Cellar/scrcpy/1.20: 8 files, 254.2KB
 ~ % adb devices
List of devices attached
192.168.31.120:5555	device

 ~ % scrcpy
zsh: killed     scrcpy
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
Maybe: https://stackoverflow.com/questions/66119081/why-does-zsh-kills-my-process-every-time-i-enter-a-git-command

**Comment by AndyZhuAZ** [comment]
> Maybe: https://stackoverflow.com/questions/66119081/why-does-zsh-kills-my-process-every-time-i-enter-a-git-command

useful, after reinstall gettext and pcre2, scrcpy worked
