### ISSUE TITLE
SCRCPY in slow motion

### ISSUE THREAD

**Issue by cleycley** [Genymobile/scrcpy#2824]
Windowns 10
lasted version of scrcpy
android 11
Galaxy A51 

Hi, I'm a new SCRCPY user, when I'm transmitting the game screen from my cell phone to my notebook (via wifi), after a while the transmission starts to slow down, even though I'm using commands to reduce the quality, this it gets in the way a lot because I'm trying to livestream, someone can help me for God's sake

**Comment by rom1v** [comment]
Does the lag increase? Or the framerate decrease?

What is the framerate printed in the console if you press Alt+i in the scrcpy windows?

Is it the same over USB?

If you record, is the recorded file impacted?

**Comment by cleycley** [comment]
> 

there is no fps reduction, it just looks like it's in slow motion, at the same time there are delays in the transmission from cell phone to PC

**Comment by cleycley** [comment]
@rom1v pls i need help

**Comment by cleycley** [comment]
> 

@rom1v 
Does the lag increase? Or the framerate decrease?
R: framerate

What is the framerate printed in the console if you press Alt+i in the scrcpy windows?
R:26

Is it the same over USB?
R: i dont know

If you record, is the recorded file impacted?
R:no

**Comment by cleycley** [comment]
https://user-images.githubusercontent.com/94766648/143282026-20e61bb2-527e-451d-852d-e894f84f1d3c.mp4

slow motion and cuting the video

**Comment by rom1v** [comment]
> > What is the framerate printed in the console if you press Alt+i in the scrcpy windows?
>
> R:26

Please post 20~30 lines of framerate output.

> > Is it the same over USB?
>
> R: i dont know

Please test. If it works over USB, then your wifi network is not able to transmit the video stream in real time…

**Comment by cleycley** [comment]
> > > What is the framerate printed in the console if you press Alt+i in the scrcpy windows?
> > 
> > 
> > R:26
> 
> Please post 20~30 lines of framerate output.
R: How??
> 
> > > Is it the same over USB?
> > 
> > 
> > R: i dont know
> 
> Please test. If it works over USB, then your wifi network is not able to transmit the video stream in real time…
R:
yes via USB it's better this was to be expected, but I don't like to transmit via USB, my wifi is good, 50mb

**Comment by cleycley** [comment]
tested via usb and the problem remains bro

**Comment by rom1v** [comment]
> my wifi is good, 50mb

It seems it is not.

**Comment by rom1v** [comment]
To be fair, the wifi performance also depends a lot on the device (I have devices which I could barely mirror at 2M, while others perfectly work at 16M).

**Comment by cleycley** [comment]
@rom1v Tell me, is there a way to apply more than one command simultaneously in Powershell? because when I use a command, for example: I use -M 720 press Enter, and then -b 2m, the first is canceled, and only the second command is active

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows
