### ISSUE TITLE
Multiple phone not working anymore on my PC

### ISSUE THREAD

**Issue by Xgamerz** [Genymobile/scrcpy#2828]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: 1.20
 - installation method: Windows release zip
 - device model: Samsung S3, S5, S6 and S7
 - Android version: between 6 to 8

**Describe the bug**
just few days ago i was able to start multiple instance of scrcpy to mirror all phones simultaneous.
when i tested today, it allow me to launch only one instance, and all others stuck in console and close it after few seconds.
is there any way to get trace log ?

Please paste terminal output in a code block. (output of second phone)
`D:\Tools\scrcpy>scrcpy -s 04160448d7283c02
INFO: scrcpy 1.20 <https://github.com/Genymobile/scrcpy>
D:\Tools\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 34.8 MB/s (37139 bytes in 0.001s)
[server] INFO: Device: samsung SM-G920F (Android 7.0)`

**Comment by rom1v** [comment]
Thank you for your report.

This is fixed by #2783.
