### ISSUE TITLE
Scrcpy on SailfishOS

### ISSUE THREAD

**Issue by serifpersia** [Genymobile/scrcpy#2832]
Can i build scrcpy in SailfishOS?
Its linux os based on Mer Core fork of MeeGo distro
It uses .rpm files and pkcon to install stuff for example sudo in the terminal.
Is there a way to build scrcpy in this linux os? 
Let me know if its possible

**Comment by rom1v** [comment]
I don't know. Try to follow build instructions: https://github.com/Genymobile/scrcpy/blob/master/BUILD.md
