### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by NAVY7771** [Genymobile/scrcpy#2833]
Ok so first of all I am a plain man who is not so familiar with technical things but here let me put it.
So I used scrpy after a long time and what I noticed is the commands doesn't seem to work on the command prompt. Whenever I type a command for
 eg scrcpy -f 
it doesn't work and there is no response to it at all.
Pls Help me with this!!

 - [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows

**Comment by NAVY7771** [comment]
I appreciate that you noticed my problem.
But sadly I didn't get any help from it.

Let me explain my problem again.
Whenever I connect my device with scrcpy it works and the screen sharing also runs smoothly but the problem is after that if I want to write any command on the command prompt it doesn't recognise them(no response at all).
Its like I can write anything on it and it doesn't do anything.

Let me know if I should give more details on my problem. Thanks.

**Comment by rom1v** [comment]
> but the problem is after that if I want to write any command on the command prompt

Yes, that's not how you the commands must be entered. Please read the link above and follow the steps.

**Comment by NAVY7771** [comment]
I got you buddy. Thanks for the help!
I am so thankful for your application , it is so good. 

Thanks. 🙃
