### ISSUE TITLE
Unusable performance on Pico Neo 3

### ISSUE THREAD

**Issue by supermutant36** [Genymobile/scrcpy#2835]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version:1.20
 - installation method:Windows release
 - device model: Pico Neo 3
 - Android version: 10

**Describe the bug**
On the Pico Neo 3 I get like 1 or 3 fps with very high latency. I tried lowering the resolution, bitrate, framerate and cropped the image but even on something like 480 p screen resolution, the Screencast is unusable. I tried same cables, same ports and same settings on my Pixel 6 to verify and performance and latency are very good there. 
```
C:\Users\BlumiOffice\Downloads\scrcpy-win64-v1.20>scrcpy.exe
INFO: scrcpy 1.20 <https://github.com/Genymobile/scrcpy>
C:\Users\BlumiOffice\Downloads\scrcpy-win64-v1.20\scrcpy-server: 1 file pushed, 0 skipped. 53.2 MB/s (37139 bytes in 0.001s)
[server] INFO: Device: Pico Pico Neo 3 (Android 10)
INFO: Renderer: direct3d
INFO: Initial texture: 3664x1920
WARN: Killing the server...

C:\Users\BlumiOffice\Downloads\scrcpy-win64-v1.20>
```

https://user-images.githubusercontent.com/21087962/143855298-1879274b-ec7a-4d56-ae28-2801f7d0115b.mp4

**Comment by rom1v** [comment]
> INFO: Initial texture: 3664x1920

>  I tried lowering the resolution […] but even on something like 480 p screen resolution

What command did you execute exactly? `scrcpy -m800` for example?

Is it over USB?

Did you try another [encoder](https://github.com/Genymobile/scrcpy#encoder)?

**Comment by rom1v** [comment]
Oh, in fact, it's the same device as #2819.

Closing as duplicate (you could post on that other thread).
