### ISSUE TITLE
1.21 failed to execute error on Windows 7

### ISSUE THREAD

**Issue by awksed** [Genymobile/scrcpy#2838]
- [ Y] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [Y ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: WIN7 64
 - scrcpy version: 1.21
 - installation method: release
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**
 run scrcpy-console.bat without any params, it seems no serial was gotten. at the same time, 1.20 is working fine.
any suggestion is appreciated, thx.
![scrcpy1 21error](https://user-images.githubusercontent.com/12236503/143987742-8ff752c7-631b-4dc7-b701-dde7ae17d2ed.png)

```
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
ERROR: Failed to execute: [adb], [get-serialno]
ERROR: Could not execute "adb get-serialno"
ERROR: Could not get device serial
ERROR: Server connection failed
```

**Comment by rom1v** [comment]
What is the result of `adb get-serial-no` if you execute manually?

**Comment by rom1v** [comment]
I added some logs, please replace this binary in v1.21 release then post the output:

- [`scrcpy.exe`](https://tmp.rom1v.com/scrcpy/2838/1/scrcpy.exe) _sha256:de91898be9e946cac473e4f9c5ed5f29280851c8a162d7c1c151e01c4b8608d1_


<details><summary>diff</summary>

```diff
diff --git a/app/src/sys/win/process.c b/app/src/sys/win/process.c
index bed98479..3f99dad8 100644
--- a/app/src/sys/win/process.c
+++ b/app/src/sys/win/process.c
@@ -46,6 +46,7 @@ sc_process_execute_p(const char *const argv[], HANDLE *handle, unsigned flags,
     HANDLE stderr_write_handle;
     if (pin) {
         if (!CreatePipe(&stdin_read_handle, pin, &sa, 0)) {
+            LOGE("Create pipe stdin failed");
             perror("pipe");
             return SC_PROCESS_ERROR_GENERIC;
         }
@@ -56,6 +57,7 @@ sc_process_execute_p(const char *const argv[], HANDLE *handle, unsigned flags,
     }
     if (pout) {
         if (!CreatePipe(pout, &stdout_write_handle, &sa, 0)) {
+            LOGE("Create pipe stdout failed");
             perror("pipe");
             goto error_close_stdin;
         }
@@ -66,6 +68,7 @@ sc_process_execute_p(const char *const argv[], HANDLE *handle, unsigned flags,
     }
     if (perr) {
         if (!CreatePipe(perr, &stderr_write_handle, &sa, 0)) {
+            LOGE("Create pipe stderr failed");
             perror("pipe");
             goto error_close_stdout;
         }
@@ -107,6 +110,7 @@ sc_process_execute_p(const char *const argv[], HANDLE *handle, unsigned flags,
             InitializeProcThreadAttributeList(NULL, 1, 0, &size)
                 || GetLastError() == ERROR_INSUFFICIENT_BUFFER;
         if (!ok) {
+            LOGE("InitializeProcThreadAttributeList failed");
             goto error_close_stderr;
         }
 
@@ -118,6 +122,7 @@ sc_process_execute_p(const char *const argv[], HANDLE *handle, unsigned flags,
 
         ok = InitializeProcThreadAttributeList(lpAttributeList, 1, 0, &size);
         if (!ok) {
+            LOGE("InitializeProcThreadAttributeList failed");
             free(lpAttributeList);
             goto error_close_stderr;
         }
@@ -127,6 +132,7 @@ sc_process_execute_p(const char *const argv[], HANDLE *handle, unsigned flags,
                                        handles, handle_count * sizeof(HANDLE),
                                        NULL, NULL);
         if (!ok) {
+            LOGE("UpdateProcThreadAttribute failed");
             goto error_free_attribute_list;
         }
 
@@ -154,6 +160,7 @@ sc_process_execute_p(const char *const argv[], HANDLE *handle, unsigned flags,
                              dwCreationFlags, NULL, NULL, &si.StartupInfo, &pi);
     free(wide);
     if (!ok) {
+        LOGE("CreateProcessW failed");
         if (GetLastError() == ERROR_FILE_NOT_FOUND) {
             ret = SC_PROCESS_ERROR_MISSING_BINARY;
         }
```

</details>

**Comment by Bonoboo** [comment]
Here you are.
P.S. Huge thanks for this awesome software.
```
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
ERROR: CreateProcessW failed
ERROR: Failed to execute: [adb], [get-serialno]
ERROR: Could not execute "adb get-serialno"
ERROR: Could not get device serial
ERROR: Server connection failed
```

**Comment by rom1v** [comment]
Thank you. I forgot to print the error code. Could you do the same with this one, please:

- [`scrcpy.exe`](https://tmp.rom1v.com/scrcpy/2838/2/scrcpy.exe) _sha256:fedf4b7afa2e214fda1268c05d08554d7e7dac15e206ce559aae83272aaa607b

<details><summary>diff</summary>

```diff
diff --git a/app/src/sys/win/process.c b/app/src/sys/win/process.c
index bed98479..6ed9cb0d 100644
--- a/app/src/sys/win/process.c
+++ b/app/src/sys/win/process.c
@@ -46,6 +46,7 @@ sc_process_execute_p(const char *const argv[], HANDLE *handle, unsigned flags,
     HANDLE stderr_write_handle;
     if (pin) {
         if (!CreatePipe(&stdin_read_handle, pin, &sa, 0)) {
+            LOGE("Create pipe stdin failed");
             perror("pipe");
             return SC_PROCESS_ERROR_GENERIC;
         }
@@ -56,6 +57,7 @@ sc_process_execute_p(const char *const argv[], HANDLE *handle, unsigned flags,
     }
     if (pout) {
         if (!CreatePipe(pout, &stdout_write_handle, &sa, 0)) {
+            LOGE("Create pipe stdout failed");
             perror("pipe");
             goto error_close_stdin;
         }
@@ -66,6 +68,7 @@ sc_process_execute_p(const char *const argv[], HANDLE *handle, unsigned flags,
     }
     if (perr) {
         if (!CreatePipe(perr, &stderr_write_handle, &sa, 0)) {
+            LOGE("Create pipe stderr failed");
             perror("pipe");
             goto error_close_stdout;
         }
@@ -107,6 +110,7 @@ sc_process_execute_p(const char *const argv[], HANDLE *handle, unsigned flags,
             InitializeProcThreadAttributeList(NULL, 1, 0, &size)
                 || GetLastError() == ERROR_INSUFFICIENT_BUFFER;
         if (!ok) {
+            LOGE("InitializeProcThreadAttributeList failed");
             goto error_close_stderr;
         }
 
@@ -118,6 +122,7 @@ sc_process_execute_p(const char *const argv[], HANDLE *handle, unsigned flags,
 
         ok = InitializeProcThreadAttributeList(lpAttributeList, 1, 0, &size);
         if (!ok) {
+            LOGE("InitializeProcThreadAttributeList failed");
             free(lpAttributeList);
             goto error_close_stderr;
         }
@@ -127,6 +132,7 @@ sc_process_execute_p(const char *const argv[], HANDLE *handle, unsigned flags,
                                        handles, handle_count * sizeof(HANDLE),
                                        NULL, NULL);
         if (!ok) {
+            LOGE("UpdateProcThreadAttribute failed");
             goto error_free_attribute_list;
         }
 
@@ -154,7 +160,9 @@ sc_process_execute_p(const char *const argv[], HANDLE *handle, unsigned flags,
                              dwCreationFlags, NULL, NULL, &si.StartupInfo, &pi);
     free(wide);
     if (!ok) {
-        if (GetLastError() == ERROR_FILE_NOT_FOUND) {
+        int err = GetLastError();
+        LOGE("CreateProcessW failed: %d", err);
+        if (err == ERROR_FILE_NOT_FOUND) {
             ret = SC_PROCESS_ERROR_MISSING_BINARY;
         }
         goto error_free_attribute_list;
```

</details>

**Comment by awksed** [comment]
> What is the result of `adb get-serialno` if you execute manually?
> 
> Which device is it?
> 
> Which Android version?
> 
> Do yoou use another `adb` than the provided one?

Hi Rom,
It's Mi mobile phone, with Android 11.
I didn't set other adb.exe,  I directly run the bat file so i think it is using its own adb.  
![scrcpy1 21error](https://user-images.githubusercontent.com/12236503/144011906-4cccf0e7-5ce5-4557-b435-46b29516a5e2.png)

**Comment by Bonoboo** [comment]
```
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
ERROR: CreateProcessW failed: 1450
ERROR: Failed to execute: [adb], [get-serialno]
ERROR: Could not execute "adb get-serialno"
ERROR: Could not get device serial
ERROR: Server connection failed
```

**Comment by rom1v** [comment]
> ERROR: CreateProcessW failed: 1450

https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--1300-1699-

> ERROR_NO_SYSTEM_RESOURCES
> 1450 (0x5AA)
> Insufficient system resources exist to complete the requested service

:thinking:

**Comment by rom1v** [comment]
This is a Windows 7 specific problem it seems: https://bugzilla.mozilla.org/show_bug.cgi?id=1460995

**Comment by awksed** [comment]
> 

scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
ERROR: CreateProcessW failed: 1450
ERROR: Failed to execute: [adb], [get-serialno]
ERROR: Could not execute "adb get-serialno"
ERROR: Could not get device serial
ERROR: Server connection failed

after replaced the scrcpy.exe, output is above messages.
besides, I built the source code 1.21 in ubuntu and it DO run correctly in ubuntu.
I'm tring to built it to Win64 in ubuntu, but haven't finished yet due to the built environment of Win needs to be set.

**Comment by Bonoboo** [comment]
> This is a Windows 7 specific problem it seems

All was fine on v1.20
I'm not code expert, but maybe some of this commits cause bug?
- [Fix adb get-serialno error handling](https://github.com/Genymobile/scrcpy/commit/b0eb1a55d6f1180df2d19fda91d08290dff4f687) 
- [Check process success locally for adb commands](https://github.com/Genymobile/scrcpy/commit/904f0ae61e7902973e862a6151ef972877fc3380)
- [Simplify Windows process inheritance configuration](https://github.com/Genymobile/scrcpy/commit/b9b8b6aab828e0f1ca899171ecf5c7bfcaf9df46)

**Comment by rom1v** [comment]
More probably 9cb14b51663d61c6f0b41da3c5699de418d633aa.

**Comment by rom1v** [comment]
Could you please test this one?

 - [`scrcpy.exe`](https://tmp.rom1v.com/scrcpy/2838/3/scrcpy.exe) _sha256:8c41744d76ba9003d4a5e5ac7c0e4d42bc136349076b4db099888fdc06f0bb5a_

**Comment by Bonoboo** [comment]
It works, thanks.

**Comment by rom1v** [comment]
I submitted a (#2840) and referenced it from the [release page](https://github.com/Genymobile/scrcpy/releases/tag/v1.21).

I probably won't publish a new (minor) version just for this (it would increment the version for everyone, whereas only Windows 7 is affected), I will wait more changes. Windows 7 users could just download the binary from #2840 :wink:

**Comment by FinlayDaG33k** [comment]
> Could you please test this one?
> 
>     * [`scrcpy.exe`](https://tmp.rom1v.com/scrcpy/2838/3/scrcpy.exe) _sha256:8c41744d76ba9003d4a5e5ac7c0e4d42bc136349076b4db099888fdc06f0bb5a_

I ran into a similar issue, which would also be solved by this patch.
```
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
ERROR: Failed to execute: [adb], [-s], [5e0ed092], [push], ["J:\Toolkit\srcrpy\bin\scrcpy\scrcpy-server"], ["/data/local/tmp/scrcpy-server.jar"]
ERROR: Could not execute "adb push"
ERROR: Server connection failed
```

**Comment by guadeifel** [comment]
I have the same issue, but on Windows 11.

scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
ERROR: CreateProcessW() error 5
ERROR: Failed to execute: [C:\Users\gusta\AppData\Local\Android\Sdk\platform-tools], [get-serialno]
ERROR: Could not execute "adb get-serialno"
ERROR: Could not get device serial
ERROR: Server connection failed

**Comment by Leuhan77** [comment]
> Could you please test this one?
> 
> * [`scrcpy.exe`](https://tmp.rom1v.com/scrcpy/2838/3/scrcpy.exe) _sha256:8c41744d76ba9003d4a5e5ac7c0e4d42bc136349076b4db099888fdc06f0bb5a_

for windows 7 32 bits?

**Comment by awksed** [comment]
> I submitted a PR (#2840) and referenced it from the [release page](https://github.com/Genymobile/scrcpy/releases/tag/v1.21).
> 
> I probably won't publish a new (minor) version just for this (it would increment the version for everyone, whereas only Windows 7 is impacted), I will wait more changes (or at least a few days or more). Windows 7 users could just download the binary from #2840 wink

it works. thks!

**Comment by rom1v** [comment]
@guadeifel Your problem is different:

> ERROR: Failed to execute: [C:\Users\gusta\AppData\Local\Android\Sdk\platform-tools], [get-serialno]

You set the ADB environment variable to a wrong value: it must point to the `adb.exe` executable, not its directory (`C:\Users\gusta\AppData\Local\Android\Sdk\platform-tools\adb.exe`).

**Comment by rom1v** [comment]
> for windows 7 32 bits?

I just updated #2840 with a link to a 32 bits version.

**Comment by Leuhan77** [comment]
> > para windows 7 32 bits?
> 
> Acabo de actualizar [# 2840](https://github.com/Genymobile/scrcpy/pull/2840) con un enlace a una versión de 32 bits.

Thanks

**Comment by guadeifel** [comment]
> @guadeifel Your problem is different:
> 
> > ERROR: Failed to execute: [C:\Users\gusta\AppData\Local\Android\Sdk\platform-tools], [get-serialno]
> 
> You set the ADB environment variable to a wrong value: it must point to the `adb.exe` executable, not its directory (`C:\Users\gusta\AppData\Local\Android\Sdk\platform-tools\adb.exe`).

Thanks for the answer @rom1v, I made this change. After that, I just turns off and on the permission USB Debugging, and works. 🤘🏻

**Comment by fusionneur** [comment]
I start getting similar error since 1.21 when running from cygwin on windows (it worked fine until now):

$ scrcpy
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
ERROR: Failed to execute: [adb], [-s], [<my_device_IP>:5555], [push], ["C:\Downloads\scrcpy-win64\scrcpy-server"], ["/data/local/tmp/scrcpy-server.jar"]
ERROR: Could not execute "adb push"
ERROR: Server connection failed

$ adb get-serialno
<my_device_IP>:5555  ----------- this is ok

**Comment by rom1v** [comment]
@fusionneur Did you read the issue and the answers of this thread?

**Comment by fusionneur** [comment]
Yes, get to the point. I just wanted to share my experience even if it is not related to Win 7.

**Comment by rom1v** [comment]
@fusionneur Oh ok, I didn't understand that it was not on Windows 7. Does #2840 (or `dev` branch) also fix the problel for you?

**Comment by fusionneur** [comment]
yes, overwriting [scrpcy.exe](https://tmp.rom1v.com/scrcpy/2838/3/scrcpy.exe) with the one from #2840 makes it work again under Win 11 via cygwin

**Comment by huy-ffd** [comment]
For Windows 10 via cygwin, overwriting scrcpy.exe with the one from [#2840](https://github.com/Genymobile/scrcpy/pull/2840) like **fusioneur** said also fixed this problem for me. It doesn't only happen on Windows 7 or Windows 11.

**Comment by dragongyke** [comment]
Hi, I got a similar issue, after overwriting #2840 scrcpy.exe, I got the following result.

C:\Tools\scrcpy-win64-v1.21>scrcpy.exe
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
ERROR: CreateProcessW() error 5
ERROR: Failed to execute: [C:\Android\SDK\platform-tools], [get-serialno]
ERROR: Could not execute "adb get-serialno"
ERROR: Could not get device serial
ERROR: Server connection failed

C:\Tools\scrcpy-win64-v1.21>adb get-serialno
PA7F40OGE8290158B

**Comment by rom1v** [comment]
@dragongyke https://github.com/Genymobile/scrcpy/issues/2838#issuecomment-983331810

**Comment by dragongyke** [comment]
@rom1v Thank you very much. But if I set my system environment parameter for ADB to C:\Android\SDK\platform-tools\adb.exe, the global ADB will not work any more. Seems scrcpy will use the one within its same folder.
So the issue now is either the global ADB can work (with the value of "C:\Android\SDK\platform-tools\"), or the Scrcpy can work.

**Comment by rom1v** [comment]
> But if I set my system environment parameter for ADB to C:\Android\SDK\platform-tools\adb.exe, [...] Seems scrcpy will use the one within its same folder.

No, it will use the one you provide in ADB.

**Comment by Gabriel4927** [comment]
Hi, I got a similar issue, after overwriting with #2840 scrcpy.exe, I got the following result.

scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
C:\Users\Gabriel\Downloads\scrcpy-win3...ped. 33.9 MB/s (40067 bytes in 0.001s)
[server] INFO: Device: samsung SM-A325M (Android 11)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:110)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncode
r.java:91)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:6
5)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:93)
        at com.genymobile.scrcpy.Server.main(Server.java:309)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:409)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
WARN: Device disconnected
WARN: Killing the server...


OS: Windows 7 32 bits

**Comment by fusionneur** [comment]
how you solved it?

**Comment by fusionneur** [comment]
i am getting disconnections when locking/unlocking phone with the replaced exe

**Comment by rom1v** [comment]
> i am getting disconnections when locking/unlocking phone

@fusionneur #597

**Comment by fusionneur** [comment]
Thank you @rom1v that fixed it for me. I wrote more details on #597

**Comment by Gabriel4927** [comment]
> how you solved it?

I just lowered the quality, the program doesn't accept the full quality of the screen

**Comment by gurvinderbini** [comment]
Can anyone help me with this?
I am using windows 11

scrcpy 1.23 <https://github.com/Genymobile/scrcpy>
ERROR: CreateProcessW() error 2
ERROR: Command not found: [C:\Program Files (x86)\Android\android-sdk\platform-tools], [start-server]
ERROR: (make 'adb' accessible from your PATH or define its fullpath in the ADB environment variable)
ERROR: Could not execute "adb start-server"
ERROR: Could not start adb daemon
ERROR: Server connection failed
Press any key to continue . . .

**Comment by rom1v** [comment]
> ERROR: Command not found: [C:\Program Files (x86)\Android\android-sdk\platform-tools], [start-server]

You set the ADB environment to a wrong value (it must point to the adb.exe executable, not its parent directory).

But you should remove this environment variable unless you absolutely need to use a custom adb.

**Comment by rom1v** [comment]
Can you execute `C:\Users\Adil Parwez\Desktop\scrcpy\adb.exe`?
