### ISSUE TITLE
ERROR: No format specified (for mp4)

### ISSUE THREAD

**Issue by PapaWhiskey65** [Genymobile/scrcpy#2842]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows]
 - scrcpy version: [1.19]
 - installation method: Windows release...]
 - device model: (custom android tablet)
 - Android version: [6.0.1]

**Describe the bug**
Went to record new mp4 video this morning, which has worked reliably until this morning. When typing scrcpy --record <filename>.mp4, scrcpy reports "ERROR: no format specified for "<filename>.mp4" (try with --record-format=mkv)

On errors, please provide the output of the console (and `adb logcat` if relevant).
see above
```
Please paste terminal output in a code block.
PWeeks@PWEEKS-US-LE MINGW64 ~/src/AG/amaethon (AGAM-18585)
$ scrcpy --record AGAM-18585
ERROR: No format specified for "AGAM-18585" (try with --record-format=mkv)
`

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
> ```
> $ scrcpy --record AGAM-18585
> ```

Either you must name the file with extension `.mp4` or `.mkv`:

```
scrcpy --record AGAM-18585.mp4
```

Or pass an explicit format if you don't want your filename to end with `.mp4` or `.mkv`:

```
scrcpy --record AGAM-18585 --record-format=mp4
```

**Comment by rom1v** [comment]
> i just tried again with --record filename --record-format=mp4 and that worked and then tried--record filename.mp4 and that worked...so dont know what the glitch wash

Probably a typo, so the filename did not end with `.mp4` exactly.
