### ISSUE TITLE
latest version (1.21) not available via Brew

### ISSUE THREAD

**Issue by jpage4500** [Genymobile/scrcpy#2845]
This isn't a bug but I am having some issues with scrcpy on an Android 12 device and wanted to make sure I had the latest version.

I see there's a 1.21 version available but not via brew. I figured I'd ask if there's another way to get this via brew before trying to build it myself

```
$ brew info scrcpy
scrcpy: stable 1.20 (bottled)
Display and control your Android device
https://github.com/Genymobile/scrcpy
/usr/local/Cellar/scrcpy/1.20 (8 files, 236KB) *
  Poured from bottle on 2021-11-30 at 10:36:39
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/scrcpy.rb
```

**Comment by rom1v** [comment]
It seems v1.21 is now in Homebrew.
