### ISSUE TITLE
No Numbers or Punctuation

### ISSUE THREAD

**Issue by qzwongo** [Genymobile/scrcpy#2846]
When typing using the computer keyboard, I get no numbers or punctuation (comma, bang, apostrophe, quote, etc). Capital letters work. None of the symbols above the number key.  I can get the missing characters by clicking on the phone's on-screen keyboard.

Running on Debian testing.
scrcpy 1.19
Same behavior on OnePlus 6t (A6013) AND Samsung Galaxy S20 5G (SM-G981V)

Don't see this issue with the same phones when running scrcpy on Windows 10.

**Comment by rom1v** [comment]
Run with `scrcpy -Vverbose`, and post the output when you press `1` (for example). (Please test on v1.21)

**Comment by qzwongo** [comment]
Thanks for the quick reply.  Upgrading to 1.21 did the trick, apologies for not having done that before asking the question.

**Comment by rom1v** [comment]
Great 👍  (I'm not sure this is related to v1.21 though, I guess if you retest v1.19 it will work.)
