### ISSUE TITLE
crop to get black edges

### ISSUE THREAD

**Issue by Leuhan77** [Genymobile/scrcpy#2848]
Hi, I wanted to know if someone could help me crop the image so that black edges do not appear my screen is 720x1600
Thanks

**Comment by rom1v** [comment]
Refs https://github.com/Genymobile/scrcpy/issues/548#issuecomment-984598064

What you want is the mirrored content to have the same aspect ratio as your computer size. To know the crop rectangle, you must know both the device size and your computer screen size.

**Comment by Leuhan77** [comment]
the resolution of my pc screen is 1280x720

**Comment by rom1v** [comment]
So you want to crop the device width of 1600 to 1280, i.e. crop 320 pixels, 160 on the left, 160 on the right:

```bash
scrcpy --crop 1280:720:160:0   # 1280x720 at offset (160,0)
```

**Comment by Leuhan77** [comment]
![Captura](https://user-images.githubusercontent.com/95325666/144451238-f05a15b9-fdb7-4db3-9414-0406f1503640.PNG)

**Comment by Leuhan77** [comment]
so I remain :(

**Comment by rom1v** [comment]
Your device is not 1600×720. Is it portrait (720×1600)?

It makes no sense to crop the mirroring so that your _portrait_ device match your _landscape_ computer screen.

**Comment by Leuhan77** [comment]
![85](https://user-images.githubusercontent.com/95325666/144454357-3edfc20c-8be4-4810-9e0d-f706c0051c59.PNG)

**Comment by Leuhan77** [comment]
This?

**Comment by rom1v** [comment]
OK, so it's 720x1600. It makes no sense to crop 720x1600 it so that it fits in your 1280x720 screen, you'll get only a tiny part of your screen.

Scrcpy just mirrors the device, which is rendered on the phone at phone screen dimensions. You can then crop, but that just crops what is rendered on the phone, it will not magically render at your device dimensions.

What you want is probably a secondary display: https://github.com/Genymobile/scrcpy/issues/1413#issuecomment-640273175

**Comment by Leuhan77** [comment]
> Bien, entonces es 720x1600. No tiene sentido recortarlo a 720x1600 para que quepa en su pantalla de 1280x720, realmente solo una pequeña parte de su pantalla.
> 
> Scrcpy solo refleja el dispositivo, que se representa en el teléfono con las dimensiones de la pantalla del teléfono. Luego puede recortar, pero eso solo recorta lo que se renderiza en el teléfono, no se renderizará mágicamente en las dimensiones de su computadora.
> 
> Lo que desea es probablemente una pantalla secundaria: [# 1413 (comentario)](https://github.com/Genymobile/scrcpy/issues/1413#issuecomment-640273175)

exactly that I tried, but when I start a mock screen and try to open it with scrcpy I only get a black screen

**Comment by rom1v** [comment]
OK, it's often the case on Android 9 (and sometimes on Android 10). So desktop mode will probably not work on your device.

**Comment by rom1v** [comment]
> is there no way for this to work?

I don't think so.

**Comment by Leuhan77** [comment]
Well, thanks for the help
