### ISSUE TITLE
Galaxy Z Fold 3 5G Incompatible

### ISSUE THREAD

**Issue by Dragonstorm305** [Genymobile/scrcpy#2851]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: 1.21
 - installation method: Windows Release 1.21
 - device model: Galaxy Z Fold 3 5G
 - Android version: 11

When I click scrcpy.exe it just closes instantly, I used this before with my Galaxy s10+ the same method and all but no luck with this phone. That's pretty much it, please fix soon if you can.

**Comment by rom1v** [comment]
> When I click scrcpy.exe it just closes instantly

Open `scrcpy-console.bat` so that the console remains open on error, the copy-paste the console output here.

**Comment by Dragonstorm305** [comment]
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
* daemon not running; starting now at tcp:5037
* daemon started successfully
error: device unauthorized.
This adb server's $ADB_VENDOR_KEYS is not set
Try 'adb kill-server' if that seems wrong.
Otherwise check for a confirmation dialog on your device.
ERROR: "adb get-serialno" returned with value 1
ERROR: Could not get device serial
ERROR: Server connection failed
Press any key to continue . . .

Sorry for the late reply I went on vacation but it looks like this already closed @rom1v

**Comment by Dragonstorm305** [comment]
Nevermind I got it working again I had to disable then reenable USB Debugging

**Comment by Marlerman** [comment]
I can confirm the Galaxy Z Fold3 works with scrcpy 1.21

**Comment by chdenizard** [comment]
> I can confirm the Galaxy Z Fold3 works with scrcpy 1.21

Yes, it does indeed. But I found an issue. Suddenly, MOD-O (Mirroring with Display OFF) stopped working. I tried to update the cell phone, reinstall guiscrcpy, nothing worked. Then I realized that when you connect to phone with fold opened, it works flawlesly. But if you connect to it with fold closed, it does not work.
