### ISSUE TITLE
Support in landscape mode in tablets

### ISSUE THREAD

**Issue by srinikesh2929** [Genymobile/scrcpy#2852]
- [ ] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
Scrcpy is not supporting landscape mode in Tablets
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rom1v** [comment]
I don't understand the issue. Scrcpy rotates automatically according to the device orientation.

And there is absolutely zero explanation in this issue, so I'm closing. Feel free to reopen with more information.
