### ISSUE TITLE
[Help]Creating NodeJs Client with android12 support

### ISSUE THREAD

**Issue by jithingangadharan** [Genymobile/scrcpy#2855]
Nodejs Client:
======================
```
async start() {
    const devices = await this.adbClient.listDevices()
      .catch(e => {
        debug('Impossible to list devices:', e);
        throw e;
      });

    const device = this._config.deviceId ? devices.find(d => d.id === this._config.deviceId) : devices[0];
    if (!device) {
      throw new Error(this._config.deviceId ?
        `Device ${this._config.deviceId} not found in adb` : 'No device present in adb server');
    }

    // Transfer server...
    await this.adbClient.push(device.id, path.join(__dirname, 'scrcpy-server.jar'), '/data/local/tmp/scrcpy-server.jar')
      .then(transfer => new Promise(((resolve, reject) => {
        transfer.on('progress', (stats) => {
          debug('[%s] Pushed %d bytes so far',
            device.id,
            stats.bytesTransferred);
        });
        transfer.on('end', () => {
          debug('[%s] Push complete', device.id);
          resolve();
        });
        transfer.on('error', reject);
      })))
      .catch(e => {
        debug('Impossible to transfer server file:', e);
        throw e;
      });

    // Run server
    await this.adbClient.shell(device.id, 'CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / ' +
      `com.genymobile.scrcpy.Server 1.18 info 0 80000000 0 1 true - true true 0 false false - - false}`)
      .catch(e => {
        debug('Impossible to run server:', e);
        throw e;
      });

    await this.adbClient.forward(device.id, `tcp:${this._config.port}`, 'localabstract:scrcpy')
      .catch(e => {
        debug(`Impossible to forward port ${this._config.port}:`, e);
        throw e;
      });

    this.socket = new PromiseSocket(new net.Socket());

    // Wait 1 sec to forward to work
    await Promise.delay(this._config.tunnelDelay);

    // Connect
    await this.socket.connect(this._config.port, '127.0.0.1')
      .catch(e => {
        debug(`Impossible to connect "127.0.0.1:${this._config.port}":`, e);
        throw e;
      });


    // First chunk is 69 bytes length -> 1 dummy byte, 64 bytes for deviceName, 2 bytes for width & 2 bytes for height
    const firstChunk = await this.socket.read(69)
      .catch(e => {
        debug('Impossible to read first chunk:', e);
        throw e;
      });

    const name = firstChunk.slice(1, 65).toString('utf8');
    const width = firstChunk.readUInt16BE(65);
    const height = firstChunk.readUInt16BE(67);

    if(this._config.sendFrameMeta) {
      this._startStreamWithMeta();
    } else {
      this._startStreamRaw();
    }

    return { name, width, height };
  }

  stop() {
    if (this.socket) {
      this.socket.destroy();
    }
  }

  _startStreamRaw() {
    this.socket.stream.on('data', d => this.emit('data', d));
  }

  _startStreamWithMeta() {
    this.socket.stream.pause();
    let header = null;
    this.socket.stream.on('readable', () => {
      debug('Readeable');
      while (true) {
        if (header === null) {
          const chunk = this.socket.stream.read(12);
          if (!chunk) { break; }
          header = {
            pts: chunk.slice(0, 8),
            len: chunk.readUInt32BE(8)
          };
          debug('\tHeader');
          debug(`\t\tPTS = ${header.pts}`);
          debug(`\t\tlen = ${header.len}`);
        }
        const chunk = this.socket.stream.read(header.len);
        if (!chunk) { break; }
        debug('\tPacket');
        debug(`\t\tlength = ${chunk.length}`);
        this.emit('data', header.pts, chunk);
        header = null;
      }
    });
```

Server:
-------------------
https://github.com/Genymobile/scrcpy/releases/download/v1.18/scrcpy-server-v1.18 (prebuild)

android logs
--------------------
AndroidRuntime: Calling main entry com.genymobile.scrcpy.Server
scrcpy  : Device: samsung SM-G615F (Android 8.1.0)
AndroidRuntime: Calling main entry com.genymobile.scrcpy.CleanUp

Note: - I am not able to receive buffer , any help highly appreciated... Thanks

**Comment by jithingangadharan** [comment]
Added one more socket for device control and it worked...

class Scrcpy extends EventEmitter {
  constructor(config) {
    super();
    this._config = Object.assign({
      adbHost: 'localhost',
      adbPort: 5037,
      deviceId: null,
      port: 8099,
      maxSize: 600,
      bitrate: 999999999,
      tunnelForward: true,
      tunnelDelay: 3000,
      crop: '9999:9999:0:0',
      sendFrameMeta: true
    }, config);

    this.adbClient = adb.createClient({ host: this._config.adbHost, port: this._config.adbPort});
  }

  /**
   * Will connect to the android device, send & run the server and return deviceName, width and height.
   * After that data will be offered as a 'data' event.
   */
  async start() {
    const devices = await this.adbClient.listDevices()
      .catch(e => {
        debug('Impossible to list devices:', e);
        throw e;
      });

    const device = this._config.deviceId ? devices.find(d => d.id === this._config.deviceId) : devices[0];
    if (!device) {
      throw new Error(this._config.deviceId ?
        `Device ${this._config.deviceId} not found in adb` : 'No device present in adb server');
    }

    // Transfer server...
    await this.adbClient.push(device.id, path.join(__dirname, 'scrcpy-server.jar'), '/data/local/tmp/scrcpy-server.jar')
      .then(transfer => new Promise(((resolve, reject) => {
        transfer.on('progress', (stats) => {
          debug('[%s] Pushed %d bytes so far',
            device.id,
            stats.bytesTransferred);
         });
        transfer.on('end', () => {
          debug('[%s] Push complete', device.id);
          resolve();
        });
        transfer.on('error', reject);
      })))
      .catch(e => {
        debug('Impossible to transfer server file:', e);
        throw e;
      });

    // Run server
    await this.adbClient.shell(device.id, 'CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / ' +
      `com.genymobile.scrcpy.Server 1.18 debug 600 999999999 0 0 true 9999:9999:0:0 true false 0 false false - - false}`)
      .catch(e => {
        debug('Impossible to run server:', e);
        throw e;
      });

    await this.adbClient.forward(device.id, `tcp:${this._config.port}`, 'localabstract:scrcpy')
      .catch(e => {
        debug(`Impossible to forward port ${this._config.port}:`, e);
        throw e;
      });

    this.socket = new PromiseSocket(new net.Socket());
    this.control_socket = new PromiseSocket(new net.Socket());

    // Wait 1 sec to forward to work
    await Promise.delay(this._config.tunnelDelay);

    // Connect
    await this.socket.connect(this._config.port, '127.0.0.1')
      .catch(e => {
        debug(`Impossible to connect "127.0.0.1:${this._config.port}":`, e);
        throw e;
      });

        // Connect
    await this.control_socket.connect(this._config.port, '127.0.0.1')
    .catch(e => {
      debug(`Impossible to connect "127.0.0.1:${this._config.port}":`, e);
      throw e;
    });

    // First chunk is 69 bytes length -> 1 dummy byte, 64 bytes for deviceName, 2 bytes for width & 2 bytes for height
    const firstChunk = await this.socket.read(69)
      .catch(e => {
        debug('Impossible to read first chunk:', e);
        throw e;
      });

    console.log(firstChunk);
    const name = firstChunk.slice(1, 65).toString('utf8');
    const width = firstChunk.readUInt16BE(65);
    const height = firstChunk.readUInt16BE(67);

    if(this._config.sendFrameMeta) {
      this._startStreamWithMeta();
    } else {
      this._startStreamRaw();
    }

    return { name, width, height };
  }

  stop() {
    if (this.socket) {
      this.socket.destroy();
    }
  }

  _startStreamRaw() {
    this.socket.stream.on('data', d => this.emit('data', d));
  }

  _startStreamWithMeta() {
    this.socket.stream.pause();
    let header = null;
    this.socket.stream.on('readable', () => {
      debug('Readeable');
      while (true) {
        if (header === null) {
          const chunk = this.socket.stream.read(12);
          if (!chunk) { break; }
          header = {
            pts: chunk.slice(0, 8),
            len: chunk.readUInt32BE(8)
          };
          debug('\tHeader');
          debug(`\t\tPTS = ${header.pts}`);
          debug(`\t\tlen = ${header.len}`);
        }
        const chunk = this.socket.stream.read(header.len);
        if (!chunk) { break; }
        debug('\tPacket');
        debug(`\t\tlength = ${chunk.length}`);
        this.emit('data', header.pts, chunk);
        header = null;
      }
    });
  }
}

**Comment by texPvtLtd** [comment]
I have modified the script according to the latest node version, but I getting the buffer only one time(screenshot attached).. Can you please help. Thanks in advance.

![image](https://user-images.githubusercontent.com/16334668/150668715-2c49ab0a-58c3-4835-85f4-c9da20ee65e4.png)

`var EventEmitter = require('events');
var adb = require('adbkit');
var path = require('path');
var Promise = require("node-promise").Promise;
const {PromiseSocket, TimeoutError} = require("promise-socket")


//var adb = adb.createClient();

class Scrcpy extends EventEmitter {
  constructor(config) {
    super();
    this._config = Object.assign({
      adbHost: 'localhost',
      adbPort: 5037,
      deviceId: null,
      port: 8099,
      maxSize: 600,
      bitrate: 999999999,
      tunnelForward: true,
      tunnelDelay: 3000,
      crop: '9999:9999:0:0',
      sendFrameMeta: true
    }, config);

    this.adbClient = adb.createClient({ host: this._config.adbHost, port: this._config.adbPort});
  }

  /**
   * Will connect to the android device, send & run the server and return deviceName, width and height.
   * After that data will be offered as a 'data' event.
   */
  async start() {
    const devices = await this.adbClient.listDevices()
      .catch(e => {
        console.log('Impossible to list devices:', e);
        throw e;
      });

    const device = this._config.deviceId ? devices.find(d => d.id === this._config.deviceId) : devices[0];
    if (!device) {
      throw new Error(this._config.deviceId ?
        `Device ${this._config.deviceId} not found in adb` : 'No device present in adb server');
    } else{
      console.log("Device found  "+device.id );
    }

    
    // Run server
    await this.adbClient.shell(device.id, 'CLASSPATH=/data/local/tmp/scrcpy-server1.jar app_process / ' 
	+`com.genymobile.scrcpy.Server 1.18 debug 600 999999999 0 0 true 9999:9999:0:0 true false 0 false false - - false}`)
      .catch(e => {
        console.log('Impossible to run server:', e);
        throw e;
      });

    await this.adbClient.forward(device.id, `tcp:${this._config.port}`, 'localabstract:scrcpy')
      .catch(e => {
        console.log(`Impossible to forward port ${this._config.port}:`, e);
        throw e;
      });
    
	const net = require("net")
const {PromiseSocket} = require("promise-socket")

const socket = new net.Socket();
    this.socket = new PromiseSocket(socket);
    this.control_socket = new PromiseSocket(new net.Socket());

    // Wait 1 sec to forward to work
   // await Promise.delay(this._config.tunnelDelay);
 new Promise((resolve) => {
    setTimeout(resolve, this._config.tunnelDelay);
  });
    // Connect
    await this.socket.connect(this._config.port, '127.0.0.1')
      .catch(e => {
        console.log(`Impossible to connect "127.0.0.1:${this._config.port}":`, e);
        throw e;
      });

        // Connect
    await this.control_socket.connect(this._config.port, '127.0.0.1') 
    .catch(e => {
      console.log(`Impossible to connect "127.0.0.1:${this._config.port}":`, e);
      throw e;
    });

    // First chunk is 69 bytes length -> 1 dummy byte, 64 bytes for deviceName, 2 bytes for width & 2 bytes for height
    const firstChunk = await this.socket.read(69)
      .catch(e => {
        console.log('Impossible to read first chunk:', e);
        throw e;
      });

    console.log(firstChunk);
    const name = firstChunk.slice(1, 65).toString('utf8');
    const width = firstChunk.readUInt16BE(65);
    const height = firstChunk.readUInt16BE(67);

    if(this._config.sendFrameMeta) {
      console.log('Hello start streamwin Meta');

      this._startStreamWithMeta();
    } else {
      this._startStreamRaw();
    }

    return { name, width, height };
  }

  stop() {
    if (this.socket) {
       
      this.socket.destroy();
    }
  }

  _startStreamRaw() {
    this.socket.stream.on('data', d => this.emit('data', d));
    console.log('Hello start streamwin Meta');

  }

  _startStreamWithMeta() {

    this.socket.stream.pause();
    let header = null;
    this.socket.stream.on('readable', () => {
      console.log('Readeable');
      while (true) {
	    if (header === null) {
	      const chunk = this.socket.stream.read(12);
          if (!chunk) { break; }
          header = {
            pts: chunk.slice(0, 8),
            len: chunk.readUInt32BE(8)
          };
          console.log('\tHeader');
          console.log(`\t\tPTS = ${header.pts}`);
          console.log(`\t\tlen = ${header.len}`);
        }
        const chunk = this.socket.stream.read(header.len);
        if (!chunk) { break; }
        console.log('\tPacket');
        console.log(`\t\tlength = ${chunk.length}`);
        this.emit('data', header.pts, chunk);
        header = null;
      }
    });
  }
}

module.exports = Scrcpy // 
`

Device - Redmi Note 7 Pro

**Comment by jithingangadharan** [comment]
> I have modified the script according to the latest node version, but I getting the buffer only one time(screenshot attached).. Can you please help. Thanks in advance.
> 
> ![image](https://user-images.githubusercontent.com/16334668/150668715-2c49ab0a-58c3-4835-85f4-c9da20ee65e4.png)
> 
> `var EventEmitter = require('events'); var adb = require('adbkit'); var path = require('path'); var Promise = require("node-promise").Promise; const {PromiseSocket, TimeoutError} = require("promise-socket")
> 
> //var adb = adb.createClient();
> 
> class Scrcpy extends EventEmitter { constructor(config) { super(); this._config = Object.assign({ adbHost: 'localhost', adbPort: 5037, deviceId: null, port: 8099, maxSize: 600, bitrate: 999999999, tunnelForward: true, tunnelDelay: 3000, crop: '9999:9999:0:0', sendFrameMeta: true }, config);
> 
> ```
> this.adbClient = adb.createClient({ host: this._config.adbHost, port: this._config.adbPort});
> ```
> 
> }
> 
> /**
> 
> * Will connect to the android device, send & run the server and return deviceName, width and height.
> * After that data will be offered as a 'data' event.
>   */
>   async start() {
>   const devices = await this.adbClient.listDevices()
>   .catch(e => {
>   console.log('Impossible to list devices:', e);
>   throw e;
>   });
> 
> ```
> const device = this._config.deviceId ? devices.find(d => d.id === this._config.deviceId) : devices[0];
> if (!device) {
>   throw new Error(this._config.deviceId ?
>     `Device ${this._config.deviceId} not found in adb` : 'No device present in adb server');
> } else{
>   console.log("Device found  "+device.id );
> }
> 
> 
> // Run server
> await this.adbClient.shell(device.id, 'CLASSPATH=/data/local/tmp/scrcpy-server1.jar app_process / ' 
> +`com.genymobile.scrcpy.Server 1.18 debug 600 999999999 0 0 true 9999:9999:0:0 true false 0 false false - - false}`)
>   .catch(e => {
>     console.log('Impossible to run server:', e);
>     throw e;
>   });
> 
> await this.adbClient.forward(device.id, `tcp:${this._config.port}`, 'localabstract:scrcpy')
>   .catch(e => {
>     console.log(`Impossible to forward port ${this._config.port}:`, e);
>     throw e;
>   });
> 
> const net = require("net")
> ```
> 
> const {PromiseSocket} = require("promise-socket")
> 
> const socket = new net.Socket(); this.socket = new PromiseSocket(socket); this.control_socket = new PromiseSocket(new net.Socket());
> 
> ```
> // Wait 1 sec to forward to work
> ```
> 
> // await Promise.delay(this._config.tunnelDelay); new Promise((resolve) => { setTimeout(resolve, this._config.tunnelDelay); }); // Connect await this.socket.connect(this._config.port, '127.0.0.1') .catch(e => { console.log(`Impossible to connect "127.0.0.1:${this._config.port}":`, e); throw e; });
> 
> ```
>     // Connect
> await this.control_socket.connect(this._config.port, '127.0.0.1') 
> .catch(e => {
>   console.log(`Impossible to connect "127.0.0.1:${this._config.port}":`, e);
>   throw e;
> });
> 
> // First chunk is 69 bytes length -> 1 dummy byte, 64 bytes for deviceName, 2 bytes for width & 2 bytes for height
> const firstChunk = await this.socket.read(69)
>   .catch(e => {
>     console.log('Impossible to read first chunk:', e);
>     throw e;
>   });
> 
> console.log(firstChunk);
> const name = firstChunk.slice(1, 65).toString('utf8');
> const width = firstChunk.readUInt16BE(65);
> const height = firstChunk.readUInt16BE(67);
> 
> if(this._config.sendFrameMeta) {
>   console.log('Hello start streamwin Meta');
> 
>   this._startStreamWithMeta();
> } else {
>   this._startStreamRaw();
> }
> 
> return { name, width, height };
> ```
> 
> }
> 
> stop() { if (this.socket) {
> 
> ```
>   this.socket.destroy();
> }
> ```
> 
> }
> 
> _startStreamRaw() { this.socket.stream.on('data', d => this.emit('data', d)); console.log('Hello start streamwin Meta');
> 
> }
> 
> _startStreamWithMeta() {
> 
> ```
> this.socket.stream.pause();
> let header = null;
> this.socket.stream.on('readable', () => {
>   console.log('Readeable');
>   while (true) {
>     if (header === null) {
>       const chunk = this.socket.stream.read(12);
>       if (!chunk) { break; }
>       header = {
>         pts: chunk.slice(0, 8),
>         len: chunk.readUInt32BE(8)
>       };
>       console.log('\tHeader');
>       console.log(`\t\tPTS = ${header.pts}`);
>       console.log(`\t\tlen = ${header.len}`);
>     }
>     const chunk = this.socket.stream.read(header.len);
>     if (!chunk) { break; }
>     console.log('\tPacket');
>     console.log(`\t\tlength = ${chunk.length}`);
>     this.emit('data', header.pts, chunk);
>     header = null;
>   }
> });
> ```
> 
> } }
> 
> module.exports = Scrcpy // `
> 
> Device - Redmi Note 7 Pro

Please highlight the changes you made for latest node and please mention the server version which you are using.

**Comment by ribbon-amgu** [comment]
> 

I am using server V 1.18 given in this code 
https://github.com/Genymobile/scrcpy/releases/download/v1.18/scrcpy-server-v1.18

There are not much in the code.
Changes the method of Promise method from

await Promise.delay(this._config.tunnelDelay);

to
 
new Promise((resolve) => {
setTimeout(resolve, this._config.tunnelDelay);
});

**Comment by texPvtLtd** [comment]
> > I have modified the script according to the latest node version, but I getting the buffer only one time(screenshot attached).. Can you please help. Thanks in advance.
> > ![image](https://user-images.githubusercontent.com/16334668/150668715-2c49ab0a-58c3-4835-85f4-c9da20ee65e4.png)
> > `var EventEmitter = require('events'); var adb = require('adbkit'); var path = require('path'); var Promise = require("node-promise").Promise; const {PromiseSocket, TimeoutError} = require("promise-socket")
> > //var adb = adb.createClient();
> > class Scrcpy extends EventEmitter { constructor(config) { super(); this._config = Object.assign({ adbHost: 'localhost', adbPort: 5037, deviceId: null, port: 8099, maxSize: 600, bitrate: 999999999, tunnelForward: true, tunnelDelay: 3000, crop: '9999:9999:0:0', sendFrameMeta: true }, config);
> > ```
> > this.adbClient = adb.createClient({ host: this._config.adbHost, port: this._config.adbPort});
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }
> > /**
> > 
> > * Will connect to the android device, send & run the server and return deviceName, width and height.
> > * After that data will be offered as a 'data' event.
> >   */
> >   async start() {
> >   const devices = await this.adbClient.listDevices()
> >   .catch(e => {
> >   console.log('Impossible to list devices:', e);
> >   throw e;
> >   });
> > 
> > ```
> > const device = this._config.deviceId ? devices.find(d => d.id === this._config.deviceId) : devices[0];
> > if (!device) {
> >   throw new Error(this._config.deviceId ?
> >     `Device ${this._config.deviceId} not found in adb` : 'No device present in adb server');
> > } else{
> >   console.log("Device found  "+device.id );
> > }
> > 
> > 
> > // Run server
> > await this.adbClient.shell(device.id, 'CLASSPATH=/data/local/tmp/scrcpy-server1.jar app_process / ' 
> > +`com.genymobile.scrcpy.Server 1.18 debug 600 999999999 0 0 true 9999:9999:0:0 true false 0 false false - - false}`)
> >   .catch(e => {
> >     console.log('Impossible to run server:', e);
> >     throw e;
> >   });
> > 
> > await this.adbClient.forward(device.id, `tcp:${this._config.port}`, 'localabstract:scrcpy')
> >   .catch(e => {
> >     console.log(`Impossible to forward port ${this._config.port}:`, e);
> >     throw e;
> >   });
> > 
> > const net = require("net")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > const {PromiseSocket} = require("promise-socket")
> > const socket = new net.Socket(); this.socket = new PromiseSocket(socket); this.control_socket = new PromiseSocket(new net.Socket());
> > ```
> > // Wait 1 sec to forward to work
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > // await Promise.delay(this._config.tunnelDelay); new Promise((resolve) => { setTimeout(resolve, this._config.tunnelDelay); }); // Connect await this.socket.connect(this._config.port, '127.0.0.1') .catch(e => { console.log(`Impossible to connect "127.0.0.1:${this._config.port}":`, e); throw e; });
> > ```
> >     // Connect
> > await this.control_socket.connect(this._config.port, '127.0.0.1') 
> > .catch(e => {
> >   console.log(`Impossible to connect "127.0.0.1:${this._config.port}":`, e);
> >   throw e;
> > });
> > 
> > // First chunk is 69 bytes length -> 1 dummy byte, 64 bytes for deviceName, 2 bytes for width & 2 bytes for height
> > const firstChunk = await this.socket.read(69)
> >   .catch(e => {
> >     console.log('Impossible to read first chunk:', e);
> >     throw e;
> >   });
> > 
> > console.log(firstChunk);
> > const name = firstChunk.slice(1, 65).toString('utf8');
> > const width = firstChunk.readUInt16BE(65);
> > const height = firstChunk.readUInt16BE(67);
> > 
> > if(this._config.sendFrameMeta) {
> >   console.log('Hello start streamwin Meta');
> > 
> >   this._startStreamWithMeta();
> > } else {
> >   this._startStreamRaw();
> > }
> > 
> > return { name, width, height };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }
> > stop() { if (this.socket) {
> > ```
> >   this.socket.destroy();
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }
> > _startStreamRaw() { this.socket.stream.on('data', d => this.emit('data', d)); console.log('Hello start streamwin Meta');
> > }
> > _startStreamWithMeta() {
> > ```
> > this.socket.stream.pause();
> > let header = null;
> > this.socket.stream.on('readable', () => {
> >   console.log('Readeable');
> >   while (true) {
> >     if (header === null) {
> >       const chunk = this.socket.stream.read(12);
> >       if (!chunk) { break; }
> >       header = {
> >         pts: chunk.slice(0, 8),
> >         len: chunk.readUInt32BE(8)
> >       };
> >       console.log('\tHeader');
> >       console.log(`\t\tPTS = ${header.pts}`);
> >       console.log(`\t\tlen = ${header.len}`);
> >     }
> >     const chunk = this.socket.stream.read(header.len);
> >     if (!chunk) { break; }
> >     console.log('\tPacket');
> >     console.log(`\t\tlength = ${chunk.length}`);
> >     this.emit('data', header.pts, chunk);
> >     header = null;
> >   }
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > } }
> > module.exports = Scrcpy // `
> > Device - Redmi Note 7 Pro
> 
> Please highlight the changes you made for latest node and please mention the server version which you are using.

I am using server V 1.18 given in this code
https://github.com/Genymobile/scrcpy/releases/download/v1.18/scrcpy-server-v1.18

There are not much in the code.
Changes the method of Promise method from

await Promise.delay(this._config.tunnelDelay);

to

new Promise((resolve) => {
setTimeout(resolve, this._config.tunnelDelay);
});

**Comment by jithingangadharan** [comment]
> > > I have modified the script according to the latest node version, but I getting the buffer only one time(screenshot attached).. Can you please help. Thanks in advance.
> > > ![image](https://user-images.githubusercontent.com/16334668/150668715-2c49ab0a-58c3-4835-85f4-c9da20ee65e4.png)
> > > `var EventEmitter = require('events'); var adb = require('adbkit'); var path = require('path'); var Promise = require("node-promise").Promise; const {PromiseSocket, TimeoutError} = require("promise-socket")
> > > //var adb = adb.createClient();
> > > class Scrcpy extends EventEmitter { constructor(config) { super(); this._config = Object.assign({ adbHost: 'localhost', adbPort: 5037, deviceId: null, port: 8099, maxSize: 600, bitrate: 999999999, tunnelForward: true, tunnelDelay: 3000, crop: '9999:9999:0:0', sendFrameMeta: true }, config);
> > > ```
> > > this.adbClient = adb.createClient({ host: this._config.adbHost, port: this._config.adbPort});
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > }
> > > /**
> > > 
> > > * Will connect to the android device, send & run the server and return deviceName, width and height.
> > > * After that data will be offered as a 'data' event.
> > >   */
> > >   async start() {
> > >   const devices = await this.adbClient.listDevices()
> > >   .catch(e => {
> > >   console.log('Impossible to list devices:', e);
> > >   throw e;
> > >   });
> > > 
> > > ```
> > > const device = this._config.deviceId ? devices.find(d => d.id === this._config.deviceId) : devices[0];
> > > if (!device) {
> > >   throw new Error(this._config.deviceId ?
> > >     `Device ${this._config.deviceId} not found in adb` : 'No device present in adb server');
> > > } else{
> > >   console.log("Device found  "+device.id );
> > > }
> > > 
> > > 
> > > // Run server
> > > await this.adbClient.shell(device.id, 'CLASSPATH=/data/local/tmp/scrcpy-server1.jar app_process / ' 
> > > +`com.genymobile.scrcpy.Server 1.18 debug 600 999999999 0 0 true 9999:9999:0:0 true false 0 false false - - false}`)
> > >   .catch(e => {
> > >     console.log('Impossible to run server:', e);
> > >     throw e;
> > >   });
> > > 
> > > await this.adbClient.forward(device.id, `tcp:${this._config.port}`, 'localabstract:scrcpy')
> > >   .catch(e => {
> > >     console.log(`Impossible to forward port ${this._config.port}:`, e);
> > >     throw e;
> > >   });
> > > 
> > > const net = require("net")
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > const {PromiseSocket} = require("promise-socket")
> > > const socket = new net.Socket(); this.socket = new PromiseSocket(socket); this.control_socket = new PromiseSocket(new net.Socket());
> > > ```
> > > // Wait 1 sec to forward to work
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > // await Promise.delay(this._config.tunnelDelay); new Promise((resolve) => { setTimeout(resolve, this._config.tunnelDelay); }); // Connect await this.socket.connect(this._config.port, '127.0.0.1') .catch(e => { console.log(`Impossible to connect "127.0.0.1:${this._config.port}":`, e); throw e; });
> > > ```
> > >     // Connect
> > > await this.control_socket.connect(this._config.port, '127.0.0.1') 
> > > .catch(e => {
> > >   console.log(`Impossible to connect "127.0.0.1:${this._config.port}":`, e);
> > >   throw e;
> > > });
> > > 
> > > // First chunk is 69 bytes length -> 1 dummy byte, 64 bytes for deviceName, 2 bytes for width & 2 bytes for height
> > > const firstChunk = await this.socket.read(69)
> > >   .catch(e => {
> > >     console.log('Impossible to read first chunk:', e);
> > >     throw e;
> > >   });
> > > 
> > > console.log(firstChunk);
> > > const name = firstChunk.slice(1, 65).toString('utf8');
> > > const width = firstChunk.readUInt16BE(65);
> > > const height = firstChunk.readUInt16BE(67);
> > > 
> > > if(this._config.sendFrameMeta) {
> > >   console.log('Hello start streamwin Meta');
> > > 
> > >   this._startStreamWithMeta();
> > > } else {
> > >   this._startStreamRaw();
> > > }
> > > 
> > > return { name, width, height };
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > }
> > > stop() { if (this.socket) {
> > > ```
> > >   this.socket.destroy();
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > }
> > > _startStreamRaw() { this.socket.stream.on('data', d => this.emit('data', d)); console.log('Hello start streamwin Meta');
> > > }
> > > _startStreamWithMeta() {
> > > ```
> > > this.socket.stream.pause();
> > > let header = null;
> > > this.socket.stream.on('readable', () => {
> > >   console.log('Readeable');
> > >   while (true) {
> > >     if (header === null) {
> > >       const chunk = this.socket.stream.read(12);
> > >       if (!chunk) { break; }
> > >       header = {
> > >         pts: chunk.slice(0, 8),
> > >         len: chunk.readUInt32BE(8)
> > >       };
> > >       console.log('\tHeader');
> > >       console.log(`\t\tPTS = ${header.pts}`);
> > >       console.log(`\t\tlen = ${header.len}`);
> > >     }
> > >     const chunk = this.socket.stream.read(header.len);
> > >     if (!chunk) { break; }
> > >     console.log('\tPacket');
> > >     console.log(`\t\tlength = ${chunk.length}`);
> > >     this.emit('data', header.pts, chunk);
> > >     header = null;
> > >   }
> > > });
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > } }
> > > module.exports = Scrcpy // `
> > > Device - Redmi Note 7 Pro
> > 
> > 
> > Please highlight the changes you made for latest node and please mention the server version which you are using.
> 
> I am using server V 1.18 given in this code https://github.com/Genymobile/scrcpy/releases/download/v1.18/scrcpy-server-v1.18
> 
> There are not much in the code. Changes the method of Promise method from
> 
> await Promise.delay(this._config.tunnelDelay);
> 
> to
> 
> new Promise((resolve) => { setTimeout(resolve, this._config.tunnelDelay); });

This client code is configured to support server version 1.21. Please replace your server. Jar file version to 1.21 then it should work as expected.

**Comment by texPvtLtd** [comment]
[Script.txt](https://github.com/Genymobile/scrcpy/files/7997612/Script.txt)
I have attached the script file we are using... After updating the version to 1.21, now we are not getting the firstChunk even. Can you please guide. Thanks in advance.

**Comment by texPvtLtd** [comment]
> [Script.txt](https://github.com/Genymobile/scrcpy/files/7997612/Script.txt) I have attached the script file we are using... After updating the version to 1.21, now we are not getting the firstChunk even. Can you please guide. Thanks in advance.

Any update on this?
