### ISSUE TITLE
Keyboard Mapping

### ISSUE THREAD

**Issue by Jinghao1209** [Genymobile/scrcpy#2857]
ouo, i see it, in #712 , someone is talking about `scrcpy --map 'w=click:300:300'`
i means, this is good, and better then i want to install other "extension".

I really hope developers can dev <Keymapping> to us, this will help us a lot....thanks...

**Comment by rom1v** [comment]
Thank you for your interest. However, I'm closing as a duplicate of #712 (there is no need to have several issues for the same feature request).
