### ISSUE TITLE
Mac: some way to distinguish multiple running versions of scrcpy

### ISSUE THREAD

**Issue by jpage4500** [Genymobile/scrcpy#2858]
I don't really know how feasible this one is -- but it seems like something that would be nice to have at least for Mac users (not sure about Windows or others)

I will sometimes have multiple instances of scrcpy running which work great. But, switching to the right one is a little hit or miss because the application switcher (mac) shows the same icon and name for both (see image).

I imagine most mac apps don't have this issue because they have 1 main application and multiple windows that can be created for each.. and this isn't a multi-window app. But, if there was some way to change the icon and/or title via the command line that would let me maybe assign the device name to the app or at least a different icon

![image](https://user-images.githubusercontent.com/1895553/144668233-8f46f41e-1ac9-4d36-9355-8985dd60726c.png)

anyway - not a huge deal of course but I've thought about it enough times to wonder if it's even feasible

---

FWIW - I'm talking about the list of apps that shows up when you hit CMD+TAB.. Windows has something similar but not sure if it's called the same thing
![image](https://user-images.githubusercontent.com/1895553/144668797-d65c84ee-f54d-49a2-8f6b-c4d56037d5e7.png)

**Comment by rom1v** [comment]
The window title is the device model by default (and can be changed with `--window-title`), but it seems this menu uses the program name, not the window title, so I'm not sure it can be changed. Maybe using a symlink with a different name?

You could use a different icon using the environment variable `SCRCPY_ICON_PATH`:

```bash
SCRCPY_ICON_PATH=myicon.png scrcpy
```

**Comment by jpage4500** [comment]
Excellent! that icon env variable worked great.. 

I already have a script that will prompt me which device to connect to and I now have it pick 1 of 3 different icons based on how many instances of scrcpy are already running

![image](https://user-images.githubusercontent.com/1895553/144676386-26591137-153e-4af6-af5c-882c1cad7fce.png)

**Comment by rom1v** [comment]
Note that the official icon is available in svg (if you want to create variants for each device): https://github.com/Genymobile/scrcpy/blob/master/data/icon.svg
