### ISSUE TITLE
Scrcpy on Android

### ISSUE THREAD

**Issue by eGit** [Genymobile/scrcpy#2860]
**Describe the solution you'd like**
I have a beefy Android tablet. 4GB of RAM, 64GB HDD. I runs both Android and Linux (Andronix) perfectly. It's a full Linux desktop with bluetooth mouse and keyboard. The problem is, the screen is rather small. The tablet cannot be connected to a big screen via HDMI (no chip support).

I have a FireTV 4k Stick that is connected via HDMI to a big monitor. I can use VNC to connect to the Android tablet which is then displayed on the big monitor. Since the connection is over Wifi the "picture quality" is not good and slightly choppy. Just not a pleasant experience.

I would like to connect the tablet via USB to the FireTV stick and run scrcpy on the FireTV stick to display the tablet on the big monitor. I already tested it by connecting it to my Windows laptop and using scrcpy the "picture quality" is excellent. No choppyness.

Many android devices like FireTV sticks are inexpensive (unlike laptops). They would be perfect "intermediaries" between an Android device without HDMI support and a big HDMI monitor. For that one would need to be able to run scrcpy on Android!

**Comment by rom1v** [comment]
See #100 (closing as duplicate).
