### ISSUE TITLE
ninja error

### ISSUE THREAD

**Issue by illa-illa** [Genymobile/scrcpy#2862]
- [yes ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ yes] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...] ubuntu 16.04
 - scrcpy version: [e.g. 1.12.1]  1.12.1
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...] manual build
 - device model:huawei p40
 - Android version: [e.g. 10] 11

**Describe the bug**
ninja error
On errors, please provide the output of the console (and `adb logcat` if relevant).
build error
```
Please paste terminal output in a code block.
```
dell@softdell:/home/Data/scrcpy/x$ ninja
[0/3] Generating server/scrcpy-server with a custom command

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 463ms
35 actionable tasks: 35 up-to-date
[1/3] Compiling C object app/scrcpy.p/src_icon.c.o
FAILED: app/scrcpy.p/src_icon.c.o 
ccache cc -Iapp/scrcpy.p -Iapp -I../app -I../app/src -I/usr/include/x86_64-linux-gnu -I/usr/include/SDL2 -I/usr/include/libusb-1.0 -flto=16 -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c11 -O3 -D_REENTRANT -MD -MQ app/scrcpy.p/src_icon.c.o -MF app/scrcpy.p/src_icon.c.o.d -o app/scrcpy.p/src_icon.c.o -c ../app/src/icon.c
../app/src/icon.c: In function ‘to_sdl_pixel_format’:
../app/src/icon.c:172:38: error: ‘SDL_PIXELFORMAT_ARGB32’ undeclared (first use in this function)
         case AV_PIX_FMT_ARGB: return SDL_PIXELFORMAT_ARGB32;
                                      ^
../app/src/icon.c:172:38: note: each undeclared identifier is reported only once for each function it appears in
../app/src/icon.c:173:38: error: ‘SDL_PIXELFORMAT_RGBA32’ undeclared (first use in this function)
         case AV_PIX_FMT_RGBA: return SDL_PIXELFORMAT_RGBA32;
                                      ^
../app/src/icon.c:174:38: error: ‘SDL_PIXELFORMAT_ABGR32’ undeclared (first use in this function)
         case AV_PIX_FMT_ABGR: return SDL_PIXELFORMAT_ABGR32;
                                      ^
../app/src/icon.c:175:38: error: ‘SDL_PIXELFORMAT_BGRA32’ undeclared (first use in this function)
         case AV_PIX_FMT_BGRA: return SDL_PIXELFORMAT_BGRA32;
                                      ^
../app/src/icon.c: In function ‘load_from_path’:
../app/src/icon.c:217:9: warning: implicit declaration of function ‘SDL_CreateRGBSurfaceWithFormatFrom’ [-Wimplicit-function-declaration]
         SDL_CreateRGBSurfaceWithFormatFrom(frame->data[0],
         ^
../app/src/icon.c:217:9: warning: initialization makes pointer from integer without a cast [-Wint-conversion]

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
Does it still happen on current `master` (see https://github.com/Genymobile/scrcpy/pull/2781).

What is your SDL version?

**Comment by illa-illa** [comment]
sudo apt install ffmpeg libsdl2-2.0.0

# client build dependencies
sudo apt install make gcc pkg-config meson \
                 libavcodec-dev libavformat-dev libavutil-dev \
                 libsdl2-dev
I installed it with the above command

**Comment by illa-illa** [comment]
thank you for you reply

**Comment by illa-illa** [comment]
thank you for your reply

**Comment by illa-illa** [comment]
Is this version wrong?

**Comment by rom1v** [comment]
The problem is that Ubuntu 16.04 is very very old (16.04 is not even supported anymore by Ubuntu I think), and packages a very old version of SDL.

Since recent changes, scrcpy uses SDL functions which were not available back then. It might be possible to fix compilation issues, either by disabling some features or rewriting them differently with old APIs (will check later).

In any case (and independently of scrcpy), you should really consider to upgrade your distribution.

**Comment by illa-illa** [comment]
ok,this is my work pc，Upgrading the system is a difficult thing，do you have time to fix this problem?

**Comment by oldclock** [comment]
I have similar situation on Ubuntu 16.04
I can build scrcpy success before version 1.17, and there are errors since 1.18.
@illa-illa if you do not need recent scrcpy features, maybe you could rollback and build scrcpy 1.17 for Ubuntu 16.04 PC.

**Comment by illa-illa** [comment]
This will solve the problem，thanks

**Comment by illa-illa** [comment]
FAILED: app/scrcpy 
cc  -o app/scrcpy app/scrcpy.p/src_main.c.o app/scrcpy.p/src_cli.c.o app/scrcpy.p/src_command.c.o app/scrcpy.p/src_control_msg.c.o app/scrcpy.p/src_controller.c.o app/scrcpy.p/src_decoder.c.o app/scrcpy.p/src_device.c.o app/scrcpy.p/src_device_msg.c.o app/scrcpy.p/src_event_converter.c.o app/scrcpy.p/src_file_handler.c.o app/scrcpy.p/src_fps_counter.c.o app/scrcpy.p/src_input_manager.c.o app/scrcpy.p/src_opengl.c.o app/scrcpy.p/src_receiver.c.o app/scrcpy.p/src_recorder.c.o app/scrcpy.p/src_scrcpy.c.o app/scrcpy.p/src_screen.c.o app/scrcpy.p/src_server.c.o app/scrcpy.p/src_stream.c.o app/scrcpy.p/src_tiny_xpm.c.o app/scrcpy.p/src_video_buffer.c.o app/scrcpy.p/src_util_net.c.o app/scrcpy.p/src_util_str_util.c.o app/scrcpy.p/src_sys_unix_command.c.o -flto -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -Wl,--start-group /usr/lib/x86_64-linux-gnu/libavformat-ffmpeg.so /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so /usr/lib/x86_64-linux-gnu/libavutil-ffmpeg.so /usr/lib/x86_64-linux-gnu/libSDL2.so -Wl,--end-group
/tmp/cceajUAg.ltrans2.ltrans.o：在函数‘run_stream.lto_priv.97’中：
<artificial>:(.text+0xd7)：对‘av_muxer_iterate’未定义的引用
<artificial>:(.text+0x497)：对‘avcodec_send_packet’未定义的引用
<artificial>:(.text+0x4af)：对‘avcodec_receive_frame’未定义的引用

**Comment by illa-illa** [comment]
new error,Is this a problem with the ffmpeg version?

**Comment by illa-illa** [comment]
@oldclock

**Comment by illa-illa** [comment]
25/26] Linking target app/scrcpy
FAILED: app/scrcpy
cc -o app/scrcpy app/scrcpy.p/src_main.co app/scrcpy.p/src_cli.co app/scrcpy.p/src_command.co app/scrcpy.p/src_control_msg.co app/scrcpy.p/src_controller. co app/scrcpy.p/src_decoder.co app/scrcpy.p/src_device.co app/scrcpy.p/src_device_msg.co app/scrcpy.p/src_event_converter.co app/scrcpy.p/src_file_handler.co app/scrcpy. p/src_fps_counter.co app/scrcpy.p/src_input_manager.co app/scrcpy.p/src_opengl.co app/scrcpy.p/src_receiver.co app/scrcpy.p/src_recorder.co app/scrcpy.p/src_scrcpy.co app/scrcpy.p/src_screen.co app/scrcpy.p/src_server.co app/scrcpy.p/src_stream.co app/scrcpy.p/src_tiny_xpm.co app/scrcpy.p/src_video_buffer.co app/scrcpy.p /src_util_net.co app/scrcpy.p/src_util_str_util.co app/scrcpy.p/src_sys_unix_command.co -flto -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -Wl,-- start-group /usr/lib/x86_64-linux-gnu/libavformat-ffmpeg.so /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so /usr/lib/x86_64-linux-gnu/libavutil-ffmpeg. so /usr/lib/x86_64-linux-gnu/libSDL2. so -Wl,--end-group
/tmp/cceajUAg.ltrans2.ltrans.o: In the function ‘run_stream.lto_priv.97’:
<artificial>:(.text+0xd7): Undefined reference to ‘av_muxer_iterate’
<artificial>:(.text+0x497): undefined reference to ‘avcodec_send_packet’
<artificial>:(.text+0x4af): Undefined reference to ‘avcodec_receive_frame’
collect2: error: ld returned 1 exit status
FAILED: server/scrcpy-server
/home/Data/scrcpy/server/./scripts/build-wrapper.sh /home/Data/scrcpy/server server/scrcpy-server release
ninja: build stopped: subcommand failed.

**Comment by rom1v** [comment]
For these FFmpeg errors, you must use a version prior to: https://github.com/Genymobile/scrcpy/commit/5d9e96dc4eaa41b185c41e8a6df6191762764b1c (v1.17 should work I guess, I'm on phone so it's not easy to check).

**Comment by illa-illa** [comment]
Can't solve，i guess FFmpeg maybe misconfigured，

**Comment by illa-illa** [comment]
I tried to check to dev.wip, but there are still errors

**Comment by illa-illa** [comment]
Run-time dependency libavformat found: YES 58.76.100
Run-time dependency libavcodec found: YES 58.134.100
Dependency libavutil found: YES 54.31.100 (cached)
Dependency sdl2 found: NO found 2.0.4 but need: '>= 2.0.5'
sdl2-config found: NO found '2.0.4' but need ['>= 2.0.5']
Run-time dependency sdl2 found: NO (tried config-tool)

../app/meson.build:86:4: ERROR: Invalid version of dependency, need 'sdl2' ['>= 2.0.5'] found '2.0.4'.

A full log can be found at /home/Data/scrcpy/x/meson-logs/meson-log.txt
FAILED: build.ninja 
/home/dell/.local/bin/meson --internal regenerate /home/Data/scrcpy /home/Data/scrcpy/x --backend ninja
ninja: error: rebuilding 'build.ninja': subcommand failed

**Comment by illa-illa** [comment]
It looks like you set some restrictions on the version

**Comment by illa-illa** [comment]
I successfully ran scrcpy
I did the following steps
clone a new sdl code
make 
install
Can now build successfully

**Comment by illa-illa** [comment]
thank you for your support
