### ISSUE TITLE
The image is blurred on android 11

### ISSUE THREAD

**Issue by rutherford0602** [Genymobile/scrcpy#2863]
**Environment**
 - OS: [e.g. Windows10]
 - scrcpy version: [e.g. 1.19]
 - installation method: [Windows release]
 - device model: Rockchip PX30
 - Android version: [e.g. Android  11]

I upgraded my Evaluation Board(RK PX30) to android 11.
The image is blurred.
I can’t read the words, it’s very unclear.
It is very fine on android 8.
I modified some parameters ( --bit-rate) ,but it still didn't work.
I ran QtScrcpy and it was clear.

Thank you for your help.

**Comment by rom1v** [comment]
Is it more clear if youbresize to pixel-perfect by pressing Alt+g?

Also see https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#the-quality-is-low

**Comment by rutherford0602** [comment]
I appreciate your help very much.

**Comment by rom1v** [comment]
Did this fix your issue:

> scrcpy.exe > Properties > Compatibility > Change high DPI settings > Override high DPI scaling behavior > Scaling performed by: Application

?
