### ISSUE TITLE
System zoom issue

### ISSUE THREAD

**Issue by BraveHL** [Genymobile/scrcpy#2865]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

The resolution of my computer is very high, so the zoom ratio of the system is enlarged to 175%. At this time, the screen projection interface opened by scrcpy does not zoom with the system. This problem makes me very uncomfortable. Please repair and optimize it as soon as possible

**Comment by rom1v** [comment]
Please post a screenshot, I'm not sure to understand the problem.

**Comment by BraveHL** [comment]
> Please post a screenshot, I'm not sure to understand the problem.

![0OND%}RLKF)2PY150X}M{}7](https://user-images.githubusercontent.com/22335503/144987562-65fb30a6-c887-431f-a91f-2148ef635a62.png)

**Comment by BraveHL** [comment]
> Please post a screenshot, I'm not sure to understand the problem.

![O QF74MB4@62~KKQ7PVT(S1](https://user-images.githubusercontent.com/22335503/144987644-85e7c3d6-bdc6-4fe7-bb6f-f360bdae6780.png)

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#the-quality-is-low

> scrcpy.exe > Properties > Compatibility > Change high DPI settings > Override high DPI scaling behavior > Scaling performed by: Application.

**Comment by BraveHL** [comment]
> https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#the-quality-is-low
> 
> > scrcpy.exe > Properties > Compatibility > Change high DPI settings > Override high DPI scaling behavior > Scaling performed by: Application.

This is indeed a way, but every time I download a new version of scrcpy, I need to reset these things. It's very uncomfortable. It's best that the software itself can adapt to the scaling of resolution

**Comment by rom1v** [comment]
Sure. But I don't know how to do it.

The solutions often talk about some "manifest", but they assume the app is built with VisualStudio: https://stackoverflow.com/a/46433887/1987178

I also found: https://stackoverflow.com/a/51748836/1987178

But I have no real Windows to test this. Help welcome.

**Comment by rom1v** [comment]
> It is recommended that you set the process-default DPI awareness via application manifest. See [Setting the default DPI awareness for a process](https://docs.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process) for more information. Setting the process-default DPI awareness via API call can lead to unexpected application behavior.

https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setprocessdpiawarenesscontext

Is it possible to use this "application manifest" (whatever it is) the way scrcpy is built? Or is it specific to microsoft tools?

Otherwise, maybe we can still call `SetProcessDpiAwarenessContext()` and see if it works.

(cc @Biswa96 and @npes87184, as Windows users+developers you might have a clue :wink:)

**Comment by Biswa96** [comment]
> Is it possible to use this "application manifest" the way scrcpy is built?

It is possible to use tools in gcc or llvm. I know some projects that uses DPI awareness
* MS terminal: https://github.com/microsoft/terminal/blob/main/src/cascadia/WindowsTerminal/WindowsTerminal.manifest
* ProcessHacker: https://github.com/processhacker/processhacker/blob/master/ProcessHacker/ProcessHacker.manifest

Let me reproduce the issue like OP.

**Comment by rom1v** [comment]
Thank you, now I think I know how to do it: [`windows_dpi_awareness`](https://github.com/Genymobile/scrcpy/commits/windows_dpi_awareness) (6312ea9c9873824e0fbf375ddf3a5c9faa5041b8)

@BraveHL Could you please test this binary:
- [`scrcpy.exe`](https://tmp.rom1v.com/scrcpy/2865/1/scrcpy.exe) _sha256:0d60faa4ada0fa3a25e320babc21d5daa475218dc5fb9c8fceaa5ac2afba0ec3_

**Comment by Helaer** [comment]
> Thank you, now I think I know how to do it: [`windows_dpi_awareness`](https://github.com/Genymobile/scrcpy/commits/windows_dpi_awareness) ([6312ea9](https://github.com/Genymobile/scrcpy/commit/6312ea9c9873824e0fbf375ddf3a5c9faa5041b8))
> 
> @BraveHL Could you please test this binary:
> 
> * [`scrcpy.exe`](https://tmp.rom1v.com/scrcpy/2865/1/scrcpy.exe) _sha256:0d60faa4ada0fa3a25e320babc21d5daa475218dc5fb9c8fceaa5ac2afba0ec3_

@rom1v I did the test for you and it worked very well.

**Comment by rom1v** [comment]
Thank you @Helaer :+1:

After your message, I was wondering how to test in practice, but I finally found: in my Windows VM I set scaling to 150% in Settings > System > Display, then I run scrcpy, and it works correctly :tada: Indeed, without the fix, the result is awful :scream:

**Comment by rom1v** [comment]
ad11c5babb0ff89647dd606392ed7907a20277c7 merged into `dev`.
