### ISSUE TITLE
Why not support audio transmission?

### ISSUE THREAD

**Issue by BraveHL** [Genymobile/scrcpy#2866]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

Why not support audio transmission? Although others have made branches, they still hope that the main branch can support audio transmission, which can greatly facilitate developers

**Comment by rom1v** [comment]
There is already an issue about audio: #14.

For the explanation why it's not integrated in scrcpy: https://www.reddit.com/r/Android/comments/o4pdxt/comment/h2ipu7y/
