### ISSUE TITLE
scrcpy cannot restart or stop

### ISSUE THREAD

**Issue by TheprofessionalKhaled** [Genymobile/scrcpy#2868]
i tried to emulate my mobile using scrcpy and VScode but when i found an error on the app and modified it on Ide and i want to track the change ....the stop and restart button cannot operate and I tried pressing them alot and also nothing happen....so what is the problem?

**Comment by rom1v** [comment]
I don't use VSCode, so I have no idea.

The official way to build is to use meson+ninja: https://github.com/Genymobile/scrcpy/blob/master/BUILD.md
