### ISSUE TITLE
OPPO Reno 2f Warn Ignore touch event  v1.21

### ISSUE THREAD

**Issue by EmiliaaKy** [Genymobile/scrcpy#2869]
I keep finding solutions but i still have no idea how to fix it
![Screenshot 2021-12-08 183155](https://user-images.githubusercontent.com/95748975/145193203-cd2924ad-9a28-48f1-bee5-678454bf6f18.png)
.

**Comment by rom1v** [comment]
```
scrcpy -m1920
```

Also, please do not post screenshot of text, just post the text.
