### ISSUE TITLE
Snap or Flatpack Package?

### ISSUE THREAD

**Issue by fernandofreamunde** [Genymobile/scrcpy#287]
Hi this is an amazing piece of software, it would be nice to have a easy way to install it under linux...

.deb/.rpm are in the past, the future is with Flatpak and Snaps, which run in every distribution as long as snapd/flatpack is installed.(or windows apparently)

And you only have to support one of those formats that give you full control on the update distribution... 

please take a look at the official websites:
https://www.flatpak.org/
https://snapcraft.io/

Thanks in advance hope to see one of those packages soon on my laptop :)

**Comment by jackTaw88** [comment]
appimage, snap or flatpack would be perfect :+1:

**Comment by rom1v** [comment]
See:
https://snapstats.org/snaps/scrcpy
https://github.com/sisco311/scrcpy-snap

and:
https://github.com/12wk34/scrcpy-flatpak

**Comment by karam72** [comment]
> See: https://snapstats.org/snaps/scrcpy https://github.com/sisco311/scrcpy-snap
> 
> and: https://github.com/12wk34/scrcpy-flatpak

Can we trust 3rd parties? :/
