### ISSUE TITLE
Drag n' Drop not working if filename has empty space

### ISSUE THREAD

**Issue by eikaramba** [Genymobile/scrcpy#288]
I tested to drag and drop a file to the device in version 1.4 - does not work if file has an whitespace in its filename. However works if i remove the whitespace.
Tested on windows 10 x64
![grafik](https://user-images.githubusercontent.com/1320525/46485668-6e3d5780-c7fc-11e8-8654-3ff6c15d858d.png)

**Comment by rom1v** [comment]
Thank you for the report.

([command-line parsing is WTF on Windows](https://github.com/Genymobile/scrcpy/blob/v1.4/app/src/sys/win/command.c#L13))

ping @npes87184 https://github.com/Genymobile/scrcpy/pull/226

We [workarounded](https://github.com/Genymobile/scrcpy/blob/v1.4/app/src/command.c#L97-L106) the same problem for APK installation (see end-of-comment https://github.com/Genymobile/scrcpy/pull/133#issuecomment-392262121).

We should do the same for `adb push`.

**Comment by rom1v** [comment]
Fixed on `master`.

[`scrcpy.exe`](https://github.com/Genymobile/scrcpy/issues/288) (to replace in v1.4 directory).
_SHA-256: e02ae03122a92993077332330c908c79d5082cd3d3b88889fe16af971fd4e0f8_

**Comment by rom1v** [comment]
> unfortunately the binary file you linked is linking to this issue and not some exe file.

Oops. Fixed.

**Comment by npes87184** [comment]
@rom1v Thank you for your help!
