### ISSUE TITLE
Error on exception thread

### ISSUE THREAD

**Issue by yazkamal** [Genymobile/scrcpy#2882]
I try on Poco M3 phone, keep says error on exception thread, then warn device disconnected and killing the server
![2021-12-15 19_11_27-Window](https://user-images.githubusercontent.com/80443834/146184495-0fa2a189-5bd4-4721-b55c-aaa8303aef82.png)
I've been trying update driver, and change usb port, didn't works, im using usb type C

**Comment by rom1v** [comment]
Duplicate of #833.

_(Please do not post screenshots of text, just post the text instead.)_
