### ISSUE TITLE
Extreme lag and stuttering S7 FLAT

### ISSUE THREAD

**Issue by andresgonz13** [Genymobile/scrcpy#2884]
- OS: Windows 10
 - scrcpy version: 1.20
 - installation method: Windows release
 - device model: Samsung Galaxy S7 FLAT (32GB)(SNAPDRAGON)
 - Android version: 8

There are some extreme lag and stuttering when using SCRCPY in my galaxy S7 making it nearly unusable, i tried with other devices (A51) and work very fine, there is any config that i can set in my device to improve scrcpy performance?, i have a decent PC so i don't think that is the problem.

I tried the following commands, nothing of these actually worked for me:
scrcpy --max-size 1024
scrcpy --bit-rate 2M
scrcpy --bit-rate 2M
scrcpy --encoder OMX.qcom.video.encoder.avc
scrcpy --display-buffer=50 

I take that video to show how slow it is:

https://user-images.githubusercontent.com/51380821/146284945-f5da99d2-4b95-4642-b73a-640d0aa6b082.mp4

**Comment by rom1v** [comment]
And with `screenrecord`?

```bash
adb shell screenrecord /sdcard/file.mp4
adb pull /sdcard/file.mp4
```

**Comment by andresgonz13** [comment]
The video shown has been taken with screenrecord command

**Comment by rom1v** [comment]
> The video shown has been taken with screenrecord command

No, the video above has been recorded with scrcpy (`scrcpy --record file.mp4`).

`screenrecord` is a program totally independent of `scrcpy`, available natively on Android devices, to record the screen to a file on the device storage.

```
adb shell screenrecord /sdcard/file.mp4
adb pull /sdcard/file.mp4
```

**Comment by andresgonz13** [comment]
Is slow with that command too, but my problem is not recording the screen, i have no interest in recording the screen,it is just that my phone screen is totally unusable and i use SCRCPY to reply to messages and see google authenticator until i get a new phone

**Comment by rom1v** [comment]
> but my problem is not recording the screen, i have no interest in recording the screen

I understand that, but it allows to determine if the problem is related to screen capture and encoding (so it is).

> my phone screen is totally unusable

Oh, so your phone screen is broken? That's probably the reason: #1456.

You could try:

```
scrcoy --turn-screen-off
```

**Comment by andresgonz13** [comment]
That worked for me thanks your very much for your help
