### ISSUE TITLE
Question about how can scrcpy tool can control a phone even its screen is turned off

### ISSUE THREAD

**Issue by huynhtanloc2612** [Genymobile/scrcpy#2888]
Hi scrcpy developers,
Thanks for creating the great tool for android phones. Your tool help me save two of my dead screen phones and then I could make use of them for other helpful purposes. I love scrcpy tool.
Recently, I have made my other old phones with the same purposes. But in this cases their screens are still ok (working), so I wonder how I can control them even with their screens are turned off (like scrcpy -S) to save their battery life. So, may I ask how you can did it for scrcpy tool or if there is any adb commands that can do the same (control the phone even its screen is turned off)?
Thanks,

**Comment by rom1v** [comment]
To turn the screen off, scrcpy calls the private API [`setDisplayPowerMode()`](https://github.com/aosp-mirror/platform_frameworks_base/blob/db0515696f63bf4a4652c7c0f69e69dea932e481/core/java/android/view/SurfaceControl.java#L1874-L1879) by introspection [here](https://github.com/Genymobile/scrcpy/blob/5704ec6967c03510dd7d206e5f59c1e4fd6e10a0/server/src/main/java/com/genymobile/scrcpy/wrappers/SurfaceControl.java#L126-L127).

To execute such Java code from shell:
 - https://blog.rom1v.com/2018/03/introducing-scrcpy/#run-a-java-main-on-android
 - https://github.com/Genymobile/scrcpy/blob/master/DEVELOP.md#privileges

AFAIK there is command to do the same via `adb` only.

**Comment by huynhtanloc2612** [comment]
Hi @rom1v,
Thanks you very much for your guideline. I have successfully made it work with Java code.

**Comment by rom1v** [comment]
:+1:

Is your code available somewhere publicly? (some people tried to change the power mode independently of scrcpy in the past).

**Comment by huynhtanloc2612** [comment]
> 👍
> 
> Is your code available somewhere publicly? (some people tried to change the power mode independently of scrcpy in the past).
Yes, I will publish my code to share with others. (Almost coming from your guideline and code)
Let me study the way to publish this code on github. (I have not tried publishing code on github before)

**Comment by Tonio1987fr** [comment]
@huynhtanloc2612 Did you send your code? I am also trying to turn off the screen of my tablet without cutting my game. thank you

**Comment by rom1v** [comment]
Note that in the latest version you can ask scrcpy not to "cleanup", including restoring the power mode.

Concretely:

```bash
scrcpy --turn-screen-off --no-cleanup
```

Then close scrcpy, the device screen will remain off.

See #1764 #3020.

**Comment by Tonio1987fr** [comment]
thanks @rom1v but I need to turn off the screen from adb for my code

**Comment by puterboy** [comment]
> @huynhtanloc2612 Did you send your code? I am also trying to turn off the screen of my tablet without cutting my game. thank you

I too am interested in the ability to turn the screen on and off... Can you please share code? Thanks

**Comment by CheerfulPianissimo** [comment]
Cobbling together the relevant pieces from *scrcpy*, this appears to do the job  @puterboy  @Tonio1987fr 
```import android.os.IBinder;
import android.os.Build;
import java.lang.reflect.Method;
import java.lang.reflect.InvocationTargetException;
public class DisplayToggle {

    private static final Class<?> CLASS;
	static {
        	try {
            		CLASS = Class.forName("android.view.SurfaceControl");
		} catch (ClassNotFoundException e) {
        	throw new AssertionError(e);
     	 }
    }

    public static void main(String... args) throws Exception {
	System.out.print("Display mode: "+args[0]);
	Method method = CLASS.getMethod("setDisplayPowerMode", IBinder.class, int.class);
	try {
            method.invoke(null, getBuiltInDisplay(),Integer.parseInt(args[0]));
        } catch (InvocationTargetException | IllegalAccessException e) {
	    e.printStackTrace();
        }
    }

    private static Method getGetBuiltInDisplayMethod() throws NoSuchMethodException {
       Method getBuiltInDisplayMethod;
            // the method signature has changed in Android Q
            // <https://github.com/Genymobile/scrcpy/issues/586>
            if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q) {
                getBuiltInDisplayMethod = CLASS.getMethod("getBuiltInDisplay", int.class);
            } else {
                getBuiltInDisplayMethod = CLASS.getMethod("getInternalDisplayToken");
            }
        return getBuiltInDisplayMethod;
    }

    public static IBinder getBuiltInDisplay() {
        try {
            Method method = getGetBuiltInDisplayMethod();
            if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q) {
                // call getBuiltInDisplay(0)
                return (IBinder) method.invoke(null, 0);
            }
            // call getInternalDisplayToken()
            return (IBinder) method.invoke(null);
           } catch (InvocationTargetException | IllegalAccessException | NoSuchMethodException e) {
            e.printStackTrace();
            return null;
        }
    }
}
```
Run it using the method described in [https://blog.rom1v.com/2018/03/introducing-scrcpy/#run-a-java-main-on-android](https://blog.rom1v.com/2018/03/introducing-scrcpy/#run-a-java-main-on-android) while passing the display mode as the argument - 0 for screen off and 2 for screen on, 1 appears to cause my display to turn sluggish.

**Comment by George-Seven** [comment]
@Tonio1987fr @puterboy @xdesniy @ibboacidburn

https://github.com/HunterXProgrammer/DisplayToggle

**Comment by LorenzoBe** [comment]
> Cobbling together the relevant pieces from _scrcpy_, this appears to do the job @puterboy @Tonio1987fr
> 
> ```
> import android.os.Build;
> import java.lang.reflect.Method;
> import java.lang.reflect.InvocationTargetException;
> public class DisplayToggle {
> 
>     private static final Class<?> CLASS;
> 	static {
>         	try {
>             		CLASS = Class.forName("android.view.SurfaceControl");
> 		} catch (ClassNotFoundException e) {
>         	throw new AssertionError(e);
>      	 }
>     }
> 
>     public static void main(String... args) throws Exception {
> 	System.out.print("Display mode: "+args[0]);
> 	Method method = CLASS.getMethod("setDisplayPowerMode", IBinder.class, int.class);
> 	try {
>             method.invoke(null, getBuiltInDisplay(),Integer.parseInt(args[0]));
>         } catch (InvocationTargetException | IllegalAccessException e) {
> 	    e.printStackTrace();
>         }
>     }
> 
>     private static Method getGetBuiltInDisplayMethod() throws NoSuchMethodException {
>        Method getBuiltInDisplayMethod;
>             // the method signature has changed in Android Q
>             // <https://github.com/Genymobile/scrcpy/issues/586>
>             if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q) {
>                 getBuiltInDisplayMethod = CLASS.getMethod("getBuiltInDisplay", int.class);
>             } else {
>                 getBuiltInDisplayMethod = CLASS.getMethod("getInternalDisplayToken");
>             }
>         return getBuiltInDisplayMethod;
>     }
> 
>     public static IBinder getBuiltInDisplay() {
>         try {
>             Method method = getGetBuiltInDisplayMethod();
>             if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q) {
>                 // call getBuiltInDisplay(0)
>                 return (IBinder) method.invoke(null, 0);
>             }
>             // call getInternalDisplayToken()
>             return (IBinder) method.invoke(null);
>            } catch (InvocationTargetException | IllegalAccessException | NoSuchMethodException e) {
>             e.printStackTrace();
>             return null;
>         }
>     }
> }
> ```
> 
> Run it using the method described in https://blog.rom1v.com/2018/03/introducing-scrcpy/#run-a-java-main-on-android while passing the display mode as the argument - 0 for screen off and 2 for screen on, 1 appears to cause my display to turn sluggish.

Thanks @CheerfulPianissimo for the code!
To compile this you need to add a missing import:
`import android.os.IBinder;`

Then you can compile with:
`javac -source 1.8 -target 1.8 DisplayToggle.java -cp "$ANDROID_HOME"/platforms/android-33/android.jar`

And create the Dalvik file with:
`"$ANDROID_HOME"/build-tools/27.0.3/dx --dex --output classes.dex DisplayToggle.class`

**Comment by AnatolyIliev** [comment]
> Cobbling together the relevant pieces from _scrcpy_, this appears to do the job @puterboy @Tonio1987fr
> 
> ```
> import android.os.Build;
> import java.lang.reflect.Method;
> import java.lang.reflect.InvocationTargetException;
> public class DisplayToggle {
> 
>     private static final Class<?> CLASS;
> 	static {
>         	try {
>             		CLASS = Class.forName("android.view.SurfaceControl");
> 		} catch (ClassNotFoundException e) {
>         	throw new AssertionError(e);
>      	 }
>     }
> 
>     public static void main(String... args) throws Exception {
> 	System.out.print("Display mode: "+args[0]);
> 	Method method = CLASS.getMethod("setDisplayPowerMode", IBinder.class, int.class);
> 	try {
>             method.invoke(null, getBuiltInDisplay(),Integer.parseInt(args[0]));
>         } catch (InvocationTargetException | IllegalAccessException e) {
> 	    e.printStackTrace();
>         }
>     }
> 
>     private static Method getGetBuiltInDisplayMethod() throws NoSuchMethodException {
>        Method getBuiltInDisplayMethod;
>             // the method signature has changed in Android Q
>             // <https://github.com/Genymobile/scrcpy/issues/586>
>             if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q) {
>                 getBuiltInDisplayMethod = CLASS.getMethod("getBuiltInDisplay", int.class);
>             } else {
>                 getBuiltInDisplayMethod = CLASS.getMethod("getInternalDisplayToken");
>             }
>         return getBuiltInDisplayMethod;
>     }
> 
>     public static IBinder getBuiltInDisplay() {
>         try {
>             Method method = getGetBuiltInDisplayMethod();
>             if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q) {
>                 // call getBuiltInDisplay(0)
>                 return (IBinder) method.invoke(null, 0);
>             }
>             // call getInternalDisplayToken()
>             return (IBinder) method.invoke(null);
>            } catch (InvocationTargetException | IllegalAccessException | NoSuchMethodException e) {
>             e.printStackTrace();
>             return null;
>         }
>     }
> }
> ```
> 
> Run it using the method described in https://blog.rom1v.com/2018/03/introducing-scrcpy/#run-a-java-main-on-android while passing the display mode as the argument - 0 for screen off and 2 for screen on, 1 appears to cause my display to turn sluggish.

When I "run it using the method" (`adb shell CLASSPATH=/data/local/tmp/DisplayToggle.dex app_process`) I get `Error changing dalvik cache ownership: Permission denied`. Help?

**Comment by AnatolyIliev** [comment]
@George-Seven @LorenzoBe @CheerfulPianissimo @HunterXProgrammer

When I run `adb shell CLASSPATH=/storage/emulated/0/DisplayToggle.dex app_process / DisplayToggle 0` (or DisplayToggle 2) I just get the error "Aborted". Help?

**Comment by MABO1154820123** [comment]
🥳🥳🥳 Pretty Good!

The function of turning off the phone screen without sleeping is very useful, especially for phones without a screen. It allows us to mirror such phones without lag. Without this function, when mirroring such a phone, the screen would pause every now and then, and this periodic lag greatly affects the viewing experience!
