### ISSUE TITLE
Using Scrcpy wirelessly on another network

### ISSUE THREAD

**Issue by earkhun** [Genymobile/scrcpy#289]
The instructions are always mentioned as the **_same network._** Is there another way? Because I want to connect to my distant friend and help like T..mviewer. 

This may be possible with forwarding port but our ISPs are using Carrier-grade NAT so we can't open port, plus, why do the users need to do?

P.S. Our devices are rooted so we can enable ADB over Wi-Fi without plugging.

Thank you

**Comment by rom1v** [comment]
_scrcpy_ just relies on `adb` connection, it does not use any "external service" to connect a client and a server behind NATs. The only way is to use tunnels:
https://github.com/Genymobile/scrcpy/issues/144
https://github.com/Genymobile/scrcpy/issues/242

**Comment by rom1v** [comment]
If the "SSH for Magisk" (whatever it is) supports local and remote port redirection, yes, it should be possible to replace adb calls by ssh.

**Comment by hy-l** [comment]
wow, so fast, thank you for your reply. :)

It's openssh compiled for arm/arm64 architectures (with some start-up scripts), so it should support port forwarding. Could you please share some more details? Since I completely have no idea how it works in adb mode.

**Comment by imran-abbas1** [comment]
Anyone successful in running scrcpy wirelessly on another network?
