### ISSUE TITLE
The scrcpy gets the screen height information incorrectly?

### ISSUE THREAD

**Issue by atfeel** [Genymobile/scrcpy#2894]
The real screen resolution of my device is 960x540, and the information obtained through scrcpy is 960x536, which is 4 pixels less in height, which causes the image returned by scrcpy to be deformed. What should I do?

**Comment by rom1v** [comment]
> The real screen resolution of my device is 960x540, and the information obtained through scrcpy is 960x536

640 is not a multiple of 8, and most video encoders require the input dimensions to be a multiple of 8. That's why scrcpy rounds to the nearest multiple of 8.

> which causes the image returned by scrcpy to be deformed

Is it noticeable?

**Comment by atfeel** [comment]
thanks for your reminder
