### ISSUE TITLE
unrecognized option '--tcpip'

### ISSUE THREAD

**Issue by Edo78** [Genymobile/scrcpy#2895]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Ubuntu 20.04.3
 - scrcpy version: 1.12.1
 - installation method: apt

**Describe the bug**
The `tpcip` option is not recognized
```
❯ scrcpy --tcpip
scrcpy: unrecognized option '--tcpip'
```

**Comment by docop** [comment]
It's because the apt install do only provide v1.17  will have to wait for it. As there is no .deb, it could be quite great to get an appimage for this super nice soft.
 as the tcpip option : in windows it said target device refuse it.. but no firewall or so present .

**Comment by Edo78** [comment]
I installed the v1.21 through snap https://snapcraft.io/scrcpy
