### ISSUE TITLE
connecting to 2 phones

### ISSUE THREAD

**Issue by konn-neko** [Genymobile/scrcpy#2898]
- [🗸] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [🗸] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Win 10 64 bit
 - scrcpy version: 1.20
 - installation method: windows release
 - device model: motorola moto e5 play (Android 8.0.0) and TINNO U304AC (Android 9)
 - Android version: 8 and 9

**Describe the bug**
When I want to connect to 2 phones, it wont let me, screenshot down below
![image](https://files.catbox.moe/zi4106.png)

```
C:\Users\fortw\Downloads\scrcpy>scrcpy -s ZY323HL4WT
INFO: scrcpy 1.20 <https://github.com/Genymobile/scrcpy>
C:\Users\fortw\Downloads\scrcpy\scrcpy-server:..., 0 skipped. 35.2 MB/s (37139 bytes in 0.001s)
[server] INFO: Device: motorola moto e5 play (Android 8.0.0)
INFO: Renderer: direct3d
INFO: Initial texture: 720x1280
```
```
C:\Users\fortw\Downloads\scrcpy>scrcpy -s LNAAGUZ9DE9LD6JJ
INFO: scrcpy 1.20 <https://github.com/Genymobile/scrcpy>
C:\Users\fortw\Downloads\scrcpy\scrcpy-server:..., 0 skipped. 31.6 MB/s (37139 bytes in 0.001s)
[server] INFO: Device: TINNO U304AC (Android 9)
```

**Comment by ANDImur** [comment]
https://github.com/Genymobile/scrcpy/issues/2779

**Comment by rom1v** [comment]
Use v1.21.
