### ISSUE TITLE
Exception Error on Windows 8.1

### ISSUE THREAD

**Issue by Discipl4** [Genymobile/scrcpy#2905]
I never got scrcpy to work on windows 8.1 because of this exception error and from searching existing Issues I did not find any windows 8.1 issue related (or I probably missed it sorry).

> C:\scrcpy>scrcpy
> scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
> C:\scrcpy\scrcpy-server: 1 file pushed...ped. 44.9 MB/s (40067 bytes in 0.001s)
> [server] INFO: Device: Xiaomi Redmi 5 Plus (Android 11)
> INFO: Renderer: direct3d
> INFO: Initial texture: 1080x2160
> WARN: Device disconnected
> [server] ERROR: Exception on thread Thread[main,5,main]
> java.lang.IllegalStateException
>         at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
>         at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
>         at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:110)
>         at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncode
> r.java:91)
>         at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:6
> 5)
>         at com.genymobile.scrcpy.Server.scrcpy(Server.java:93)
>         at com.genymobile.scrcpy.Server.main(Server.java:309)
>         at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
>         at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:401)
> WARN: Killing the server...
> 
> 

I tried using different encoder, different resolution and nothing solve it. However if I use different encoder except 

> OMX.qcom.video.encoder.avc

I got no error but nothing show up (the windows that shows android screen).

![image](https://user-images.githubusercontent.com/96577465/147526677-0dfdabfb-1222-4616-bbcc-a90434aa6cdb.png)

I always got it to work on windows 10 so I think I know what I'm doing, but on windows 8.1 I really have no idea lol
I'm really sorry if someone already create similar issue. Also thank you for responding :)

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

**Comment by Discipl4** [comment]
> https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

Yeah I said I did all of those changing resolution and changing encoder but still no luck. 
I also tried changing different resolution and encoder at the same time using-

> scrcpy -m 1080 --encoder 'OMX.google.h264.encoder' 

and like I said there's no error but the android screen didn't show up

**Comment by rom1v** [comment]
`android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)` is due to an encoder problem, try reducing the resolution even more:

```
scrcpy -m 400
```

Does it work or still fail?

What if you record with `screenrecord` instead?

```
adb shell screenrecord /sdcard/file.mp4
adb pull /sdcard/file.mp4
```

Does it work?

**Comment by Discipl4** [comment]
Reducing the resolution still didn't work.

But `screenrecord` worked well, the video is perfect. 

Now what to do so I can control the screen? Because that's literally what I need.

Thank you for responding this much :)

**Comment by rom1v** [comment]
> Reducing the resolution still didn't work.
>
> But `screenrecord` worked well, the video is perfect.

OK, so it seems that your encoder has a problem with the specific encoding parameters requested from scrcpy.
You could attempt to find which one (with which value) causes the problem: https://github.com/Genymobile/scrcpy/issues/2819#issuecomment-976380273

**Comment by Discipl4** [comment]
I change the bitrate and fps but still no luck, is there a chance that the problem might be the phone itself?
I have arch linux and try running it there and got the same error. I also run it on windows 10 on virtual machine and got the same error.

**Comment by rom1v** [comment]
> is there a chance that the problem might be the phone itself?

Yes, it's definitely on the phone, a problem with the encoder.

**Comment by Discipl4** [comment]
Alright so I guess I'm closing this issue? Thank you
