### ISSUE TITLE
visual artifacts on default encoder

### ISSUE THREAD

**Issue by IllidanStormrag3** [Genymobile/scrcpy#2910]
-  I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: OxygenOs 11
 - scrcpy version: 1.21
 - installation method: chocolatey
 - device model: IN2023
 - Android version: 11

having visual artifacts from the default encoder, the other two encoders have no graphical glitches but have extreme input delay that makes them unusable 

```
error is visual in nature.
```

**Comment by rom1v** [comment]
Use the default encoder, but increase the bitrate:

```
scrcpy -b20M
```

**Comment by IllidanStormrag3** [comment]
> 

just tried that, it's still happening; should mention that this only occurs in one application so far, all other applications work fine except for this one.

**Comment by rom1v** [comment]
Please post a recording (`scrcpy --record file.mp4`).

Visual artifacts are expected when encoding a video, but at higher bitrate they should be minimal.

**Comment by IllidanStormrag3** [comment]
> Please post a recording (`scrcpy --record file.mp4`).
> 
> Visual artifacts are expected when encoding a video, but at higher bitrate they should be minimal.

https://imgur.com/rmulYNZ

**Comment by rom1v** [comment]
Oh, ok, definitely an encoder bug then.

Do these bugs also appear with a lower defintion? (`scrcpy -m1024`)?

**Comment by IllidanStormrag3** [comment]
> 



> Oh, ok, definitely an encoder bug then.
> 
> Do these bugs also appear with a lower defintion? (`scrcpy -m1024`)?

sorry about the late reply; but yes it does still happen with a lower definition.

**Comment by IllidanStormrag3** [comment]
Updates may have fixed the issue or potentially hardware upgrade fixed it.
