### ISSUE TITLE
device disconnected

### ISSUE THREAD

**Issue by theissueguy112** [Genymobile/scrcpy#2921]
i have read the FAQ and all this stuff but il took 3 charger and when i plug my phone with the 3 of them it still gets the same error they put disconnected device and i tried older and newer versions but it didn't work idk if there is way to fix but please help

**Comment by rom1v** [comment]
Post the full console output.

**Comment by theissueguy112** [comment]
![Capture d’écran 2022-01-04 112232](https://user-images.githubusercontent.com/97064436/148037272-ee6f5f47-4a7c-40d7-8c54-30286a580c53.png)
the red is my name and that's what im getting

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#exception

**Comment by theissueguy112** [comment]
what's that i don't see my error in this page

**Comment by rom1v** [comment]
> what's that i don't see my error in this page

On your screenshot, `at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)`

**Comment by rom1v** [comment]
> how can we put a lower definition

It's explained in the FAQ.

```
scrcpy -m 1024
```

If you don't know how command line works on Windows, it's also explained in the FAQ: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows

**Comment by theissueguy112** [comment]
It works thanks but can i put a higher resolution but not so high because i want to stream with a good quality

**Comment by theissueguy112** [comment]
thanks
