### ISSUE TITLE
Scrcpy cannot run simultaneously with the Android emulator

### ISSUE THREAD

**Issue by 302633** [Genymobile/scrcpy#2927]
There will be conflicts when using Scrcpy and NOX or LD Android emulator to run at the same time, and both Scrcpy and Android emulator will crash.

**Comment by 302633** [comment]
I haven’t tried other emulators, but I think it should be the same

**Comment by rom1v** [comment]
It's probably just a conflict between several `adb` versions: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#conflicts-between-adb-versions

**Comment by 302633** [comment]
> It's probably just a conflict between several `adb` versions: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#conflicts-between-adb-versions
> 
> If it's not, post the scrcpy console output.

The Android 9 beta version using nox Android emulator can run with Scrcpy at the same time, but if you open a software on the emulator, the image opened by scrcpy will crash

**Comment by rom1v** [comment]
Post the scrcpy console output.

**Comment by 302633** [comment]
Wait a mininute

**Comment by 302633** [comment]
> Post the scrcpy console output.

Sorry i don't know how to find the console output

**Comment by rom1v** [comment]
On Windows, run `scrcpy-console.bat` instead of `scrcpy.exe` for example.

**Comment by 302633** [comment]
> On Windows, run `scrcpy-console.bat` instead of `scrcpy.exe` for example.

scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
error: more than one device/emulator
ERROR: "adb get-serialno" returned with value 1
ERROR: Could not get device serial
ERROR: Server connection failed

**Comment by 302633** [comment]
> > On Windows, run `scrcpy-console.bat` instead of `scrcpy.exe` for example.
> 
> scrcpy 1.21 https://github.com/Genymobile/scrcpy error: more than one device/emulator ERROR: "adb get-serialno" returned with value 1 ERROR: Could not get device serial ERROR: Server connection failed

This is the output when I run at the same time. After opening the software on the simulator, the image opened by Scrcpy will crash

**Comment by 302633** [comment]
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
adb server version (36) doesn't match this client (41); killing...
* daemon started successfully
error: more than one device/emulator
ERROR: "adb get-serialno" returned with value 1
ERROR: Could not get device serial
ERROR: Server connection failed

This is the output I got immediately after the crash

**Comment by rom1v** [comment]
> error: more than one device/emulator

If several devices are connected (as listed by `adb devices`), you must specify which device you want to mirror: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#several-devices-connected

If you don't know how command line works on Windows: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows

> adb server version (36) doesn't match this client (41); killing...

OK, exactly what I supposed in my first message: https://github.com/Genymobile/scrcpy/issues/2927#issuecomment-1007295199

You must use the same `adb` version for everything, not one version for nox (for example), and another for scrcpy.

> Scrcpy will crash

Just for info, it's not a crash, just a device disconnection (if `adb` is killed by another `adb` version, the connection to the device is closed). Scrcpy closes and exits (properly) on device disconnection.

**Comment by 302633** [comment]
> > error: more than one device/emulator
> 
> If several devices are connected (as listed by `adb devices`), you must specify which device you want to mirror: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#several-devices-connected
> 
> If you don't know how command line works on Windows: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows
> 
> > adb server version (36) doesn't match this client (41); killing...
> 
> OK, exactly what I supposed in my first message: [#2927 (comment)](https://github.com/Genymobile/scrcpy/issues/2927#issuecomment-1007295199)
> 
> You must use the same `adb` version for everything, not one version for nox (for example), and another for scrcpy.
> 
> > Scrcpy will crash
> 
> Just for info, it's not a crash, just a device disconnection (if `adb` is killed by another `adb` version, the connection to the device is closed). Scrcpy closes and exits (properly) on device disconnection.

Thanks, I went to the installation directory of NOX and found the ADB of NOX. After replacing the Adb file of Scrcpy, I can run at the same time and use it normally.
