### ISSUE TITLE
How do I disable a wireless connection I created for scrcpy?

### ISSUE THREAD

**Issue by Buzz619** [Genymobile/scrcpy#2928]
- [y ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ y] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: 1.3
 - installation method: manual
 - device model: Google pixel 4a
 - Android version: android 12

I connected to my phone no problem with a usb and then wanted to try out a wireless connection. I followed a guide to set that up. [(this)](https://www.youtube.com/watch?v=O6WX2bxNA5Y&t=191s&ab_channel=Downloadsource.net). 
A summary of the method: 
- Go to system properties > advanced tab > environmental variables > add a location for scrcpy in path.
- open CMD and type in commands:
```
adb tcpip 5555
adb connect (IP address of phone)
```

But now I want to revert back to just a wired connection since a wireless one is very slow for me but it doesn't let me. When I connect via usb and launch scrcpy.exe it just launches cmd for a second then closes that's it. But when I remove the usb and launch it, it connects wirelessly no problem.

Do I need to delete the port I created? How do I do that? I'm not very literate when it comes to this kind of stuff so I could use some help :). Thanks
When I connect wirelessly, this command shows up: (if that's relevant)
```
scrcpy-server.jar: 1 file pushed. 1.5 MB/s (18570 bytes in 0.011s)
INFO: Initial texture: 1080x2336
```

**Comment by rom1v** [comment]
List your devices connected using `adb devices`.

Disconnect the devices connected via tcp/ip using `adb disconnect`.

To disable the possibility to connect to your device via `adb connect`: `adb usb` (this is the opposite of `adb tcpip 5555`).

```
adb disconnect
```

**Comment by Buzz619** [comment]
> List your devices connected using `adb devices`.
> 
> Disconnect the devices connected via tcp/ip using `adb disconnect`.
> 
> To disable the possibility to connect to your device via `adb connect`: `adb usb` (this is the opposite of `adb tcpip 5555`).
> 
> ```
> adb disconnect
> ```

Thanks for the reply.
All the commands you listed yield: 
```
'adb' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by rom1v** [comment]
From the scrcpy directory.

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows

**Comment by Buzz619** [comment]
> From the scrcpy directory.
> 
> https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows

Thank you very much. This has solved my issue.
Thank you, sir.
