### ISSUE TITLE
scrcpy closes itself after few secconds

### ISSUE THREAD

**Issue by BatausAlinAlexandru** [Genymobile/scrcpy#2929]
C:\Mirror>cd c:\Mirror

C:\Mirror>adb devices
List of devices attached
adb server version (41) doesn't match this client (39); killing...
* daemon started successfully
988dd243314646394130    device

C:\Mirror>scrcpy
scrcpy-server.jar: 1 file pushed. 1.2 MB/s (19342 bytes in 0.015s)
INFO: Initial texture: 1440x2960
WARN: Cannot terminate server

C:\Mirror>

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#conflicts-between-adb-versions

Also #2927.
