### ISSUE TITLE
Arabic language support

### ISSUE THREAD

**Issue by goamn** [Genymobile/scrcpy#293]
Hi, I was wondering if it's possible to add Arabic language support?

**Comment by rom1v** [comment]
If someone wants to add internationalization support, why not. Will be difficult to keep translations up-to-date through.

Related: https://github.com/Genymobile/scrcpy/issues/160

**Comment by goamn** [comment]
Oh sorry I meant support for the keyboard via typing on the computer keyboard.

**Comment by rom1v** [comment]
@goamn OK, thank you for the clarification.

Then, this is a duplicate of https://github.com/Genymobile/scrcpy/issues/37. I'm closing this one.

**Comment by mhd1433** [comment]
Hello, is it possible to add the Arabic language to the keyboard?

**Comment by mhd1433** [comment]
Hello, is it possible to add the Arabic language to the keyboard?
