### ISSUE TITLE
Cannot mirror work profile contents in Android 12

### ISSUE THREAD

**Issue by dohanin** [Genymobile/scrcpy#2931]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: v1.21
 - installation method: Windows
 - device model: Asus Zenfone 8
 - Android version: 12

**Describe the bug**
Recently I updated my phone to Android 12, and since then work profile contents are not mirrorred in scrcpy.  Nothing is broken, but just black areas are shown and as soon as I switched back to personal profile, everything resumes normal.  I'm not sure if anything can be done as it may be a new restriction in Android 12, but anyway I would like to seek your comments.

**Comment by rom1v** [comment]
It's expected. See #2129.
