### ISSUE TITLE
Garbled characters appear when setting Chinese title

### ISSUE THREAD

**Issue by BabyCY** [Genymobile/scrcpy#2932]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: 1.21
 - installation method: Windows release
 - device model: Pixel 2 XL
 - Android version: 11

**Describe the bug**
Garbled characters appear when setting Chinese title

![微信截图_20220110093928](https://user-images.githubusercontent.com/5268512/148710219-b49773cb-c873-4b75-a0a0-7c6480f2f69d.png)
![微信截图_20220110094428](https://user-images.githubusercontent.com/5268512/148710234-a9d65c2f-344a-4f6c-92e8-01426e5dc913.png)

PS D:\soft\scrcpy-win64-v1.21>  .\scrcpy.exe -s 806KPSL1950254 --window-title 中文标题hello
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
D:\soft\scrcpy-win64-v1.21\scrcpy-server: 1 file pushed, 0 skipped. 63.2 MB/s (40067 bytes in 0.001s)
[server] INFO: Device: Google Pixel 2 XL (Android 11)
INFO: Renderer: direct3d
INFO: Initial texture: 1440x2880

**Comment by rom1v** [comment]
Thank you for your report.

On Windows, command line arguments should probably be read by [`GetCommandLineW()`](https://docs.microsoft.com/en-us/windows/win32/api/processenv/nf-processenv-getcommandlinew), then converted to argv style using [`CommandLineToArgvW()`](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-commandlinetoargvw), then each argument should be converted from `wchar_t` to UTF-8. Unless there is a simpler solution? (@npes87184, any clue?)

**Comment by Mapaler** [comment]
I have the same problem.
![1664615030261_WindowsTerminal](https://user-images.githubusercontent.com/6565860/193402338-ea0047f0-85e1-408b-a457-049be35fe246.png)

The current solution is:
Use UTF-8 to save text first.
![1664615672872_explorer](https://user-images.githubusercontent.com/6565860/193402343-b441e0d4-9b80-4690-8eb4-f908412727fd.png)
Open this text file using ANSI (GBK encoding).
![1664615687890_explorer](https://user-images.githubusercontent.com/6565860/193402345-108e7881-32db-4c99-953a-e524ccb94443.png)
Using these garbled character in the console can get the correct Chinese characters.
![1664615708923_WindowsTerminal](https://user-images.githubusercontent.com/6565860/193402346-b0e89c97-2ba9-47df-9111-e2fbee805ddf.png)

**Comment by npes87184** [comment]
> On Windows, command line arguments should probably be read by [GetCommandLineW()](https://docs.microsoft.com/en-us/windows/win32/api/processenv/nf-processenv-getcommandlinew), then converted to argv style using [CommandLineToArgvW()](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-commandlinetoargvw), then each argument should be converted from wchar_t to UTF-8

![image](https://user-images.githubusercontent.com/5494432/197377369-95533342-113f-484d-9928-7fe7a0ccc496.png)

Use of the way you suggested worked well. I also tried using `wmain` with the link flag `-municode`, but that way didn't work.
