### ISSUE TITLE
make phone think it's been rotated?

### ISSUE THREAD

**Issue by nr1995** [Genymobile/scrcpy#2938]
Is there a way
to make the phone think it's been physically rotated?
While it's sitting flat on my desk?
Thanks

**Comment by rom1v** [comment]
There are 3 rotation features:
 - <kbd>MOD</kbd>+<kbd>r</kbd>: switch between portrait and landscape (if the current foreground app supports it, overridden by the actual acceleration/gravity)
 - [`--lock-video-orientation`](https://github.com/Genymobile/scrcpy#lock-video-orientation) (force a specific orientation for the video stream)
 - [client rotation](https://github.com/Genymobile/scrcpy#rotation) (`--rotation` or <kbd>MOD</kbd>+<kbd>→</kbd>/<kbd>MOD</kbd>+<kbd>←</kbd>)

**Comment by nr1995** [comment]
Yeah Mod+R is the  one I was looking for.
Don't know why I didn't see it in the list.
Thanks.
