### ISSUE TITLE
scrcpy audio version---Compile error

### ISSUE THREAD

**Issue by xiaozhi1995** [Genymobile/scrcpy#294]
system:linux
custom:ubuntu 
I want compile acrcpy -a argument,also is audio.But no scrcpy.jar documents.

ninja install:
  error:
```
_[32/33] Generating scrcpy-server with a custom command.
FAILED: server/scrcpy-server.jar 
/home/ubuntu/project/scrcpy-audio/server/./scripts/build-wrapper.sh ../server/. server/scrcpy-server.jar release
IOException: https://dl.google.com/android/repository/addons_list-3.xml
java.nio.file.AccessDeniedException: /home/ubuntu/.android/cache/sdkbin-1_d29da320-addons_list-3_xml
IOException: https://dl.google.com/android/repository/addons_list-2.xml
java.nio.file.AccessDeniedException: /home/ubuntu/.android/cache/sdkbin-1_d28f8b9f-addons_list-2_xml
IOException: https://dl.google.com/android/repository/addons_list-1.xml
java.nio.file.AccessDeniedException: /home/ubuntu/.android/cache/sdkbin-1_d281741e-addons_list-1_xml
Failed to download any source lists!
java.nio.file.AccessDeniedException: /home/ubuntu/.android/cache/sdkbin-1_b735609c-repository2-1_xml

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':server'.
> Failed to find Build Tools revision 26.0.2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
ninja: build stopped: subcommand failed_
```
Please help me out.thank you

**Comment by rom1v** [comment]
> Build Tools revision 26.0.2

You need to install the right version of the Android build tools (from Android studio, now).

Or you can just use the [prebuilt server](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#prebuilt-server), so you don't need Android SDK at all. (probably the v1.1, since I didn't rebase the audio branch yet)

**Comment by xiaozhi1995** [comment]
ok,thanks

**Comment by xiaozhi1995** [comment]
` adb devices
List of devices attached
8TF4C18816004759	device`


```
**./scrcpy -s 8TF4C18816004759 -a
INFO: Audio accessory enabled
Home directory not accessible: Permission denied
INFO: Waiting 2s for USB reconfiguration...
Home directory not accessible: Permission denied
ERROR: No audio input source found
ERROR: Cannot find USB device having serial 8TF4C18816004759
WARN: Cannot disable audio forwarding
**
```

scrcpy -a ,cannot find device?How did this happen?

**Comment by rom1v** [comment]
>     Home directory not accessible: Permission denied

:open_mouth: 

> ERROR: Cannot find USB device having serial 8TF4C18816004759

What is the result of `lsusb`?

**Comment by rom1v** [comment]
> I try lsusb […] all success.

That's great, but I was interested by the _output_ of libusb :smiley: 

Once you have fonud the vendorid:deviceid for your Android device, execute:

    lsusb -vd <vid>:<pid>

**Comment by xiaozhi1995** [comment]
ok,I can get the correspondence between serial and pid vid.There's nothing wrong with it right now.

**Comment by hexstia** [comment]
>           ok,I can get the correspondence between serial and pid vid.There's nothing wrong with it right now.
I hava the same question as you,What did you do?

**Comment by xiaozhi1995** [comment]
What phone are you using?brand?os version?

**Comment by hexstia** [comment]
MTK Android8.0

**Comment by hexstia** [comment]
are you running on Windows or unbuntu?

**Comment by rom1v** [comment]
Try [USBaudio](https://github.com/rom1v/usbaudio) instead.
