### ISSUE TITLE
Connection WiFi falied

### ISSUE THREAD

**Issue by TheOppaiDragon** [Genymobile/scrcpy#2940]
When i try connect WiFi say me this

A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (10060)

How can fix this?

**Comment by rom1v** [comment]
What did you execute exactly?

**Comment by TheOppaiDragon** [comment]
> 

I connect my phone with usb on the computer 
i open cmd with administrator 
i do: adb tcpip 5555
and: adb connect my ip and click enter. I wait a second and say me phrase i write to make this post

**Comment by TheOppaiDragon** [comment]
Yes

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: bond0: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 2e:c7:69:ee:32:6b brd ff:ff:ff:ff:ff:ff
3: dummy0: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 9e:eb:b9:77:da:1e brd ff:ff:ff:ff:ff:ff
    inet6 fe80::9ceb:b9ff:fe77:da1e/64 scope link
       valid_lft forever preferred_lft forever
4: imq0: <NOARP> mtu 16000 qdisc noop state DOWN group default qlen 1000
    link/void
5: imq1: <NOARP> mtu 16000 qdisc noop state DOWN group default qlen 1000
    link/void
6: ip_vti0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
7: ip6_vti0@NONE: <NOARP> mtu 1364 qdisc noop state DOWN group default qlen 1000
    link/tunnel6 :: brd ::
8: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
9: ip6tnl0@NONE: <NOARP> mtu 1452 qdisc noop state DOWN group default qlen 1000
    link/tunnel6 :: brd ::
10: rmnet_ipa0: <> mtu 9216 qdisc noop state DOWN group default qlen 1000
    link/[519]
12: rmnet_mhi0: <UP,LOWER_UP> mtu 65535 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/[519]
13: rmnet_data0@rmnet_mhi0: <UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN group default qlen 1000
    link/[519]
    inet6 fe80::a649:189c:2d2:6984/64 scope link
       valid_lft forever preferred_lft forever
14: rmnet_data1@rmnet_mhi0: <> mtu 1550 qdisc mq state DOWN group default qlen 1000
    link/[519]
15: rmnet_data2@rmnet_mhi0: <> mtu 1550 qdisc mq state DOWN group default qlen 1000
    link/[519]
16: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 3000
    link/ether aa:b0:ab:47:7f:87 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.8/24 brd 192.168.1.255 scope global wlan0
       valid_lft forever preferred_lft forever
    inet6 fe80::a8b0:abff:fe47:7f87/64 scope link
       valid_lft forever preferred_lft forever
17: p2p0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 3000
    link/ether b6:49:22:03:3c:b1 brd ff:ff:ff:ff:ff:ff
18: wifi-aware0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 3000
    link/ether b2:c9:52:50:6a:09 brd ff:ff:ff:ff:ff:ff
19: rmnet_data3@rmnet_mhi0: <> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/[519]
20: rmnet_data4@rmnet_mhi0: <> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/[519]
21: rmnet_data5@rmnet_mhi0: <> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/[519]
22: r_rmnet_data0@rmnet_mhi0: <UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN group default qlen 1000
    link/[519]
    inet6 fe80::5c7c:9d43:2318:d2df/64 scope link
       valid_lft forever preferred_lft forever
23: r_rmnet_data1@rmnet_mhi0: <> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/[519]
24: r_rmnet_data2@rmnet_mhi0: <> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/[519]
25: r_rmnet_data3@rmnet_mhi0: <> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/[519]

**Comment by rom1v** [comment]
and `adb connect 192.168.1.8` fails, that's it?

**Comment by TheOppaiDragon** [comment]
yes fails

**Comment by TheOppaiDragon** [comment]
i tried to do what they recommend about stackoverflow but it doesn't work
I also tried to download the script made by the other guy but when I start the file it closes immediately

**Comment by XayUp** [comment]
@TheOppaiDragon , try turning off and on your device's wifi (cell phone)
this worked for me

**Comment by TheOppaiDragon** [comment]
> 

what should i turn off?

**Comment by XayUp** [comment]
Wifi

**Comment by TheOppaiDragon** [comment]
my computer is connected via ethernet
on my phone i already try turn off wifi and turn on but don't work

**Comment by XayUp** [comment]
I understood
have you tried "adb kill-server" and "adb disconnect" after having turned off and on your cell phone?

**Comment by TheOppaiDragon** [comment]
yes, i do now and same issue

**Comment by TheOppaiDragon** [comment]
only with WiFi usb work perfectly
and yes i have adb by wifi in my phone is called: Wirless Debugging

**Comment by XayUp** [comment]
right. is this "wireless debugging" enabled?

**Comment by TheOppaiDragon** [comment]
nope

**Comment by XayUp** [comment]
:)
active dude, wow. this makes it a lot easier and it doesn't depend on you having a USB cable nearby to be connecting your cell phone via WIFI
I even made a "launcher" almost automated so I don't have to do everything, let's say on the "nail"

**Comment by XayUp** [comment]
there complicates
try to revoke usb debug permissions
this option is next to the debug options
then you do the whole process. Turn off and on the wifi and try to restart the cell phone (and the pc, it's never too much)

**Comment by TheOppaiDragon** [comment]
Done but don't work same error.
add me on discord: 👑킹젖가슴드래곤👑#5969
so we can talk faster

**Comment by XayUp** [comment]
I don't use discord
but i can download here

**Comment by TheOppaiDragon** [comment]
btw how can it be solved?
Some time ago I used a samsung and it worked
Now I have an Oppo and it doesn't work

**Comment by TheOppaiDragon** [comment]
i try everithing.

By usb cable work
i do kill-server and disconnect and nothing happen when i retry
i enabled two debugging usb and wifi
i restarted pc and phone
i open port in my router 5555
i try other command in this page: https://github.com/Genymobile/scrcpy/releases/tag/v1.21
i put variable destination scrcpy in my system

and say me SAME AND SAME phrase: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (10060)

I don't know what to do anymore I'm desperate ...

**Comment by TheOppaiDragon** [comment]
I have all firewall disabled
on my samsung galaxy s9 plus work fine wirless

**Comment by rom1v** [comment]
OK, so it's definitely a bug in the device system. The `adb` server does not respond over TCP/IP.

**Comment by TheOppaiDragon** [comment]
> 

how can i resolve this?

**Comment by XayUp** [comment]
try another port other than 5555
it doesn't hurt to try

**Comment by TheOppaiDragon** [comment]
@XayUp don't work

**Comment by XayUp** [comment]
then the business gets much deeper ;-;

**Comment by XayUp** [comment]
try like this (let's try what we can)
go there in the list of wifi networks, select your wifi you are connected to, edit the settings and change from "DHCP" to static (but before that, check what your device's IP is for you to base it on)
put an ip according to what it was before, for example
my cell phone was with IP 192.168.100.101, so I will put 192.168.100.100 or 192.168.100.102

just try

**Comment by TheOppaiDragon** [comment]
@XayUp You are a fucking genius. WORK NOW. 
thankyou

**Comment by XayUp** [comment]
Wow
I'm happy to solve a problem

change to DHCP mode again if there is any problem connecting to your wifi (in case there is only problem or do this to see if adb connects now)

**Comment by XayUp** [comment]
anyway
problem solved
