### ISSUE TITLE
Getting an error on Windows 11.

### ISSUE THREAD

**Issue by kriki200** [Genymobile/scrcpy#2941]
I get this.

![image](https://user-images.githubusercontent.com/13945483/149002322-516eb058-6e7c-442b-8c05-85a4c0c89312.png)

**Comment by rom1v** [comment]
What if you run it from `cmd.exe` instead of powershell?

Did you take the 32 bit or 64 bit release?

**Comment by xlastfire** [comment]
I'm using Windows 11 and Android 11. I can only mirror but I cant do anything else from my pc. What should I do?

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work

(but please don't hijack an unrelated issue)

**Comment by kriki200** [comment]
> What if you run it from `cmd.exe` instead of powershell?
> 
> Did you take the 32 bit or 64 bit release?

It works, thank you :) .
