### ISSUE TITLE
device unauthorized

### ISSUE THREAD

**Issue by AnilaVedavarapu** [Genymobile/scrcpy#2943]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

 - OS: Windows
 - scrcpy version: unknown 
 - installation method: manually downloaded
 - device model: Samsung Galaxy A7(2018)
 - Android version: 10
 
 USB Debugging = on

I Cant access my phone screen through my Pc because the device is unauthorized. im using the adb scrcpy method.

C:\Screen>adb devices
List of devices attached
3200cfXXXXXXXXXX       unauthorized

C:\Screen>scrcpy
adb: error: failed to get feature set: device unauthorized.
This adb server's $ADB_VENDOR_KEYS is not set
Try 'adb kill-server' if that seems wrong.
Otherwise check for a confirmation dialog on your device.
ERROR: "adb push" returned with value 1

I Have seen that you need to click accept on a popup that shows up on your screen but The thing is im trying to access my BROKEN screen display and unfortunately i cant do that :( 
Any Help is appreciated Thank you

**Comment by rom1v** [comment]
If your device is unauthorized, you can't access it via adb without authorizing it first.

**Comment by AnilaVedavarapu** [comment]
> 

My phone touch is working but for some reason when i connect the usb touch is gone. Any solutions for that?

**Comment by srinikesh2929** [comment]
If u can't use touch screen , u can try attaching the keyboard to your phone and use TAB OR UP, DOWN  and Authorize ur device.
U can attach the keyboard via OTG CABLE.

**Comment by AnilaVedavarapu** [comment]
> If u can't use touch screen , u can try attaching the keyboard to your phone and use TAB OR UP, DOWN and Authorize ur device. U can attach the keyboard via OTG CABLE.

Yes thanks

**Comment by Okamari** [comment]
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
ERROR: Device is unauthorized:
ERROR:     -->   (usb)           RF8N10WVWAA      unauthorized
ERROR: A popup should open on the device to request authorization.
ERROR: Check the FAQ: <https://github.com/Genymobile/scrcpy/blob/master/FAQ.md>
ERROR: Server connection failed

This is the error i get and im clueless on how to solve it

**Comment by java-code-former** [comment]
> scrcpy 1.24 https://github.com/Genymobile/scrcpy ERROR: Device is unauthorized: ERROR: --> (usb) RF8N10WVWAA unauthorized ERROR: A popup should open on the device to request authorization. ERROR: Check the FAQ: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md ERROR: Server connection failed
> 
> This is the error i get and im clueless on how to solve it

do you resolve?
