### ISSUE TITLE
Android 12 mirror sensitive apps

### ISSUE THREAD

**Issue by Abdulrahman-Nour** [Genymobile/scrcpy#2944]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Debian, Ubuntu 20.04 LTS]
 - scrcpy version: [Latest (v1.21 I believe) ]
 - installation method: [manual build]
 - device model: Google Pixel 3a XL
 - Android version: [12 (unfortunately)] 

**Describe the bug**
I'm not sure if this counts as a bug or feature request, but, on android 12, apps that prevent screenshots aren't mirrored on the PC :<. 
unfortunately for me, my screen is completely broken, and mirroring my device was my last hope for accessing my device data.

have you investigated this issue? and are there any plans to fix it? 
I'm a (junior) software engineer and I'm willing to work on this issue in case no one already tried or concluded that it's not possible.

just in case you wanted to read the terminal output: 
```
[server] INFO: Device: Google Pixel 3a XL (Android 12)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 21.0.3
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x2160
```

**Comment by rom1v** [comment]
That's expected on Android 12: #2129.
