### ISSUE TITLE
Create desktop entry file for Linux app launchers

### ISSUE THREAD

**Issue by asnelling** [Genymobile/scrcpy#295]
It'd be cool to launch scrcpy from a desktop environment's application menu. All that's needed is a `scrcpy.desktop` file that installs to `/usr/share/applications`.

See [XDG Desktop Entry Specification](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html)

**Comment by Freed-Wu** [comment]
Is there any progress about desktop entry?
