### ISSUE TITLE
Scrcpy does not start

### ISSUE THREAD

**Issue by p6002** [Genymobile/scrcpy#2956]
I have a phone with a broken screen. I ran screen mirroing via teamviewer and accepted the usb connection alert for scrcpy.
Scrcpy works.
After disconnecting the usb cable and reconnecting after some time - it works.
But when I boot the computer the next day, I cannot connect to the phone using scrcpy.
I can connect with teamviewer and then scrcpy starts working. I don't need to accept usb connection, only teamviewer is connected.
This is what the terminal window looks like when I try to connect: 
https://i.ibb.co/fGVfm2Y/Zrzut-ekranu-2022-01-18-o-15-45-07.png

**Comment by rom1v** [comment]
The reason is because scrcpy uses adb 41, but another program on your computer uses adb 37. You must use the same for all, otherwise, they will kill each other on each command: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#conflicts-between-adb-versions

**Comment by p6002** [comment]
Thanks for link. 
You're right. After disabling the ApowerMirror application, the information about the bad adb version disappeared.
