### ISSUE TITLE
scrcpy --v4l2-sink=/dev/video4 --no-display   gives unrecognized option error

### ISSUE THREAD

**Issue by azeek21** [Genymobile/scrcpy#2959]
- OS: Ubuntu
 - scrcpy version:  1.12.1
 - installation method: sudo apt install scrcpy
 - device model: Poco x3 pro
 - Android version: 11

Trying to capture phone screen as a video input from obs. I created video source in ``` /dev/videoN ``` but here's the error when I try to start scrcpy with these arguments.

```
→ ls /dev/video*
/dev/video0  /dev/video1  /dev/video2  /dev/video3  /dev/video4
→ scrcpy --v4l2-sink=/dev/video4 --no-display 
scrcpy: unrecognized option '--v4l2-sink=/dev/video4'

```

**Comment by rom1v** [comment]
> scrcpy version: 1.12.1

This feature has been added in v1.18.

You can install the latest version manually: https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple

**Comment by rom1v** [comment]
> I already install the latest version manually like you said before
>
> from here https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple
>
> I install from master branch
>
> but my scrcpy version still :
>
> scrcpy 1.12.1

Uninstall the one from your distrib:

```
sudo apt remove scrcpy
```
