### ISSUE TITLE
Black Screen On PIN Entry After Android 12 Update

### ISSUE THREAD

**Issue by TheFeloniousMonk** [Genymobile/scrcpy#2965]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: 1.21.
 - installation method: Windows Release
 - device model: OnePlus 9
 - Android version: 12

**Describe the bug**
When accessing the device, the pin entry screen now shows black on the emulation, so I am unable to unlock the device from the desktop. Mouse interactions are still recorded, and all other screens (including accessing the camera from the lock screen shortcut) are working as expected.

**Comment by rom1v** [comment]
That's expected on Android 12 for screens requesting to be "protected", see #2129.
