### ISSUE TITLE
Can not enter commands

### ISSUE THREAD

**Issue by Requiem730** [Genymobile/scrcpy#2968]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10 Pro
 - scrcpy version: 1.12.1
 - installation method: Windows release
 - device model: Xiaomi POCO F3
 - Android version: 11 RKQ1.200826.002

When i run the scrcpy.exe my android screen opens in new windows but when I want to enter new commands in the cmd I can not write any text anymore.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows

**Comment by Requiem730** [comment]
> https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows

Ok but can not add commands in real time while the android windows is open right? since i have to close and write the scrcpy + the command to make it work.

And one last question, Im also running sndcpy but the delay in sound is a bit larger than the video delay, is there a way to sync them? or add more delay to video to make it fit with audio? thanks and sorry for my english.

**Comment by rom1v** [comment]
> but can not add commands in real time while the android windows is open right?

Correct.

Some options could be changed dynamically via shortcuts though (fullscreen, turn screen off, rotation…).

> or add more delay to video to make it fit with audio?

https://github.com/Genymobile/scrcpy#buffering

**Comment by Requiem730** [comment]
> > but can not add commands in real time while the android windows is open right?
> 
> Correct.
> 
> Some options could be changed dynamically via shortcuts though (fullscreen, turn screen off, rotation…).
> 
> > or add more delay to video to make it fit with audio?
> 
> https://github.com/Genymobile/scrcpy#buffering

All is setup perfectly now, thank you very much, I appreciatte your work, you are incredible <3!!
