### ISSUE TITLE
Help！

### ISSUE THREAD

**Issue by gss1173186294** [Genymobile/scrcpy#297]
Hello, first of all, my English is very bad, I hope you understand. I have been researching scrcpy recently and have successfully installed and experienced it on the Windows platform. I am very interested in scrcpy. Now that I'm working on the scrcpy source code, I need some scrcpy build environment and some information on how to debug scrcpy during development. Can you provide some? Thank you! The voice from Beijing Dongcheng District.

**Comment by npes87184** [comment]
Hi, @gss1173186294 

[BUILD.md](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md) and [DEVELOP.md](https://github.com/Genymobile/scrcpy/blob/master/DEVELOP.md) may contain some thing your interesting.

Thanks.

**Comment by rom1v** [comment]
> I need some scrcpy build environment

For the client part in C, just take any editor. For the server part in Java/Android, using Android Studio is probably easier. Then compile with meson/ninja.

You can debug the app part with `gdb`:

```
export SCRCPY_SERVER_PATH="x/server/scrcpy-server.jar"
gdb x/app/scrcpy
```
(to be adapted for Windows, I have no idea how to do anything on Windows)
