### ISSUE TITLE
No signal

### ISSUE THREAD

**Issue by ThEnchanted** [Genymobile/scrcpy#2973]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10]
 - scrcpy version: 1.12.1
 - installation method: Windows release
 - device model: LG G7 ThinQ+
 - Android version: 10

** bug**
Q: A clear and concise description of what the bug is.
A: just opening the exe then it's closing without error without any bad 
On errors, please provide the output of the console (and `adb logcat` if relevant).
don't give any signal, but other app (DroidCam) what connect via usb as work

**Comment by rom1v** [comment]
Run `scrcpy-console.bat` so that the terminal does not close on error. You'll see the error message.

**Comment by ThEnchanted** [comment]
`* daemon not running; starting now at tcp:5037
* daemon started successfully
error: no devices/emulators found
ERROR: "adb get-serialno" returned with value 1
ERROR: Could not get device serial
ERROR: Server connection failed
Press any key to continue . . .
`

**Comment by rom1v** [comment]
> error: no devices/emulators found

What is the result of `adb devices`?

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#device-not-detected

**Comment by ThEnchanted** [comment]
```
List of devices attached
LMG710EAW5df53b07       device
```

**Comment by rom1v** [comment]
Now, could you execute `scrcpy` in the terminal (just after `adb devices`)?

**Comment by ThEnchanted** [comment]
OH i found out after doing this 
adb devices "pinging my phone"
[https://i.imgur.com/HtoIenl.png](screenshot from phone)
> ```
> List of devices attached
> LMG710EAW5df53b07       device
> ```

i got suggestion on my phone
