### ISSUE TITLE
Support for installing scrcpy from macOS12 using brew

### ISSUE THREAD

**Issue by steven754** [Genymobile/scrcpy#2975]
steven@lesetonglijiandeMacBook-Pro  /usr/local  brew install scrcpy
Updating Homebrew...
^CWarning: You are using macOS 12.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
pre-release version.

Error: scrcpy: no bottle available!
You can try to install from source with:
  brew install --build-from-source scrcpy
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.

**Comment by rom1v** [comment]
Please ask/report to Homebrew, this is a homebrew issue.

**Comment by rom1v** [comment]
> Warning: You are using macOS 12.
We do not provide support for this pre-release version.

Or try updating your homebrew first.
