### ISSUE TITLE
[Composition for right eye and left eye][Performance]

### ISSUE THREAD

**Issue by coolcup74** [Genymobile/scrcpy#2977]
Hello I am Eric Park.
I started to develop Oculus application recently.

![Oculus capture](https://user-images.githubusercontent.com/87742462/151477592-5f618f7e-5a60-4ee8-b985-2470fc9bb348.PNG)

As you see the attached capture, Two surfaces are showing with scrcpy.
It can be better to show composition of two or only one surface.
Please add this feature.

Probably, it may cause performance issue. very long delay, couple of seconds.
Can you let me know how to overcome this lagging issue?

Thank you in advance

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy#crop ?

**Comment by coolcup74** [comment]
Very Helpful!!! Thank you!!!
