### ISSUE TITLE
linux apd install uses version 1.17??

### ISSUE THREAD

**Issue by jonneymendoza** [Genymobile/scrcpy#2980]
Hi, i followed the guide to installing this on my linux machine and it only installs the 1.17 version.

THe latest version as of writing this is 1.21.

i used the command below:

sudo apt install scrcpy and below is the output

```Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed
  scrcpy
0 to upgrade, 1 to newly install, 0 to remove and 106 not to upgrade.
Need to get 0 B/36.6 kB of archives.
After this operation, 110 kB of additional disk space will be used.
Selecting previously unselected package scrcpy.
(Reading database ... 530365 files and directories currently installed.)
Preparing to unpack .../scrcpy_1.17-1_amd64.deb ...
Unpacking scrcpy (1.17-1) ...
Setting up scrcpy (1.17-1) ...
Processing triggers for man-db (2.9.4-2) ...```

**Comment by rom1v** [comment]
Yes, some distributions package the version available when they decide to feature-freeze (somz others are rolling-release): https://repology.org/project/scrcpy/versions

You can install the latest manually: https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple
