### ISSUE TITLE
I have macOS High Sierra and its not installing please help 

### ISSUE THREAD

**Issue by Manish-Bandi** [Genymobile/scrcpy#2982]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: macOS High Sierra
 - scrcpy version: [e.g. 1.12.1]
 - installation method: Home brew
 - device model: Asus Max m2
 - Android version: 9
 
**Describe the bug**
I have macOS High Sierra and scrcpy is not installing please help!

```Error: scrcpy: Failed to download resource "theora"      Download failed: Homebrew-installed `curl` is not installed for: https://downloads.xiph.org/releases/theora/libtheora-1.1.1.tar.bz2```

**Comment by rom1v** [comment]
Please ask/report to Homebrew (or try to install curl).
