### ISSUE TITLE
Why so many Open Issues?

### ISSUE THREAD

**Issue by drgkt** [Genymobile/scrcpy#2983]
...and any chance this will ever work over wifi? (https://github.com/Genymobile/scrcpy/issues/839)

**Comment by rom1v** [comment]
> Why so many Open Issues?

Because many people open issues to ask questions which are answered in README :smile: 

> ...and any chance this will ever work over wifi?

[README](https://github.com/Genymobile/scrcpy#tcpip-wireless)

**Comment by drgkt** [comment]
How to search open or closed issues titles for what I want to post, without reading each and every one of them?

I searched README, found no occurrences of wifi

**Comment by rom1v** [comment]
> I searched README, found no occurrences of wifi

I posted the dirext link to the wireless section.

Search "wireless".
