### ISSUE TITLE
Audio issue

### ISSUE THREAD

**Issue by ironmanshub** [Genymobile/scrcpy#2985]
Its great application to mirror screen and control it on pc but audio from mobile cant be given as output to pc. Please help me with this thanks!

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy#audio-forwarding

The best is to connect audio to the compiter via bluetooth.

**Comment by ironmanshub** [comment]
Any application or GitHub source?

**Comment by rom1v** [comment]
Both your computer and Android typically nativelly supports bluetooth. Make the computer listen, and the device connect.

**Comment by ironmanshub** [comment]
Can you be more specific? please

**Comment by rom1v** [comment]
Random video explaining how to do it on Windows: https://www.youtube.com/watch?v=sFrwqXaAGTU (didn't watch)

**Comment by qssq** [comment]
need wifi forward ,bluedevice is conflict with my game  pychincal machine

**Comment by qssq** [comment]
The Bluetooth function has been connected with another game auxiliary hardware, so I cannot intercept through Bluetooth. Could you provide wifi or USB control
