### ISSUE TITLE
Audio issue

### ISSUE THREAD

**Issue by ironmanshub** [Genymobile/scrcpy#2986]
Hello,
 I need multiple audio output ie one on  my headphone and one on pc speaker (obs input)..
Let me get it clear I need to stream game for that i mirror my screen on obs using scrpy as one of the window capture but audio output of game is still on mobile phone so i need audio output on obs stream as well as headphone. Please help me in this regard.
Thank you.

**Comment by rom1v** [comment]
Please don't open multiple issues
#2985

**Comment by ironmanshub** [comment]
Different issue
