### ISSUE TITLE
Is there an API for debugging devices? For example, to get notifications from apps?

### ISSUE THREAD

**Issue by kjxy** [Genymobile/scrcpy#299]
Is there an API for debugging devices? For example, to get notifications from apps?

如果您能理解中文的话：
有调试设备的API吗？比如获取app的通知？

**Comment by rom1v** [comment]
> Is there an API for debugging devices? For example, to get notifications from apps?

In _scrcpy_, no.

**Comment by kjxy** [comment]
> > Is there an API for debugging devices? For example, to get notifications from apps?
> 
> In _scrcpy_, no.

ok , thanks
