### ISSUE TITLE
scrcpy cant find adb although its installed

### ISSUE THREAD

**Issue by Jasoneason132** [Genymobile/scrcpy#2991]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 11
 - scrcpy version: 1.22
 - installation method: windows release
 - device model: Samsung Galaxy s21
 - Android version: 12

**Describe the bug**
this is the error i recieve when i try to run scrcpy after doing everything else. Im not sure where to go from here.

PS C:\Users\(MyName)\Downloads\platform-tools_r32.0.0-windows\platform-tools\scrcpy-win64-v1.22> .\scrcpy
scrcpy 1.22 <https://github.com/Genymobile/scrcpy>
ERROR: CreateProcessW() error 2
ERROR: Command not found: [C:\Users\(MyName)\adb-fastboot\platform-tools], [get-serialno]
ERROR: (make 'adb' accessible from your PATH or define its fullpath in the ADB environment variable)
INFO: You may download and install 'adb' from https://developer.android.com/studio/releases/platform-tools
ERROR: Could not execute "adb get-serialno"
ERROR: Could not get device serial
ERROR: Server connection failed

**Comment by rom1v** [comment]
> ERROR: Command not found: [C:\Users(MyName)\adb-fastboot\platform-tools], [get-serialno]

You set the `ADB` environment variable to a wrong value: it must point to the `adb.exe` executable itself, not its directory:

```bash
C:\Users(MyName)\adb-fastboot\platform-tools         # wrong
C:\Users(MyName)\adb-fastboot\platform-tools\adb.exe # correct
```

If you do not set this environment variable at all, it will just use the one bundled with the release.

**Comment by Jasoneason132** [comment]
> > ERROR: Command not found: [C:\Users(MyName)\adb-fastboot\platform-tools], [get-serialno]
> 
> You set the `ADB` environment variable to a wrong value: it must point to the `adb.exe` executable itself, not its directory:
> 
> ```shell
> C:\Users(MyName)\adb-fastboot\platform-tools         # wrong
> C:\Users(MyName)\adb-fastboot\platform-tools\adb.exe # correct
> ```
> 
> If you do not set this environment variable at all, it will just use the one bundled with the release.

Where do I open the terminal From?

**Comment by rom1v** [comment]
From the scrcpy folder.

Btw, from scrcpy v1.22, there is a file `open_a_terminal_here.bat`, double-click on it.

**Comment by Jasoneason132** [comment]
> From the scrcpy folder.
> 
> Btw, from scrcpy v1.22, there is a file `open_a_terminal_here.bat`, double-click on it.

Thank you that fixed the adb issue. Now the only problem is after i run ./scrcpy it will freeze up and do nothing and not let me type anything either

**Comment by rom1v** [comment]
Once scrcpy is started, why would you want to type something in the console? You may only pass arguments when you execute the command.

**Comment by Jasoneason132** [comment]
> 

nothing pops up in terms of mirroring my phone screen. So i wasnt sure if it was running correctly or not

**Comment by rom1v** [comment]
From the terminal, type `scrcpy -Vdebug` and post the whole output.

**Comment by Jasoneason132** [comment]
C:\Users\(MyName)\Downloads\scrcpy-win64-v1.22>scrcpy -Vdebug
scrcpy 1.22 <https://github.com/Genymobile/scrcpy>
DEBUG: Screensaver enabled

**Comment by rom1v** [comment]
Hmm, that's not normal at all. what is the content of your ADB environment variable?

```
echo %ADB℅
adb devices
```

Do you have the same problem with v1.21 and v1.20?

**Comment by Jasoneason132** [comment]
PS C:\Users\MyName\Downloads\scrcpy-win64-v1.21> .\adb get-serialno
error: more than one device/emulator
PS C:\Users\MyName\Downloads\scrcpy-win64-v1.21> .\adb get-serialno
10.0.0.162:5555
PS C:\Users\MyName\Downloads\scrcpy-win64-v1.21> .\adb devices
List of devices attached
10.0.0.162:5555 device

PS C:\Users\MyName\Downloads\scrcpy-win64-v1.21> .\scrcpy
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
< waiting for any device >

**Comment by rom1v** [comment]
>```echo %ADB%
> "C:\Users\MyName\Downloads\platform-tools_r32.0.0-windows\platform-tools\fastboot.exe""C:\Users\MyName\Downloads\scrcpy-win64-v1.22\scrcpy.exe""C:\Users\MyName\Downloads\scrcpy-win64-v1.22\adb.exe"

This is totally wrong.

Either set it to: `C:\Users\MyName\Downloads\scrcpy-win64-v1.22\adb.exe`
But better, just remove this environment variable.
