### ISSUE TITLE
Could not find any USB device with --otg

### ISSUE THREAD

**Issue by moha0116** [Genymobile/scrcpy#2992]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [ubuntu]
 - scrcpy version: [e.g. 1.22]
 - installation method: [ snap]
 - device model:samsung a12
 - Android version: 11

**Describe the bug**
i use command : scrcpy --otg
terminal show me:
scrcpy 1.22 <https://github.com/Genymobile/scrcpy>
ERROR: Could not find any USB device

**Comment by rom1v** [comment]
Probably a snap permission/restriction issue.

Try a non-snap version: https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple

**Comment by moha0116** [comment]
i do this but i get a another bug
keyboard and mouse not working and not showing on phone

**Comment by rom1v** [comment]
Also when your device is unlocked? What is the output in the console?

Is a scrcpy window open?

**Comment by moha0116** [comment]
now it s working thanks for this app

**Comment by ALKOALSHAN** [comment]
The link https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple shows a 404 error. How do i get a non snap version.

**Comment by rom1v** [comment]
Documentation has been reworked since scrcpy 2.0. Look here: https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md

**Comment by rom1v** [comment]
Of course, I thought you wanted the linux version since you talked about snap.

https://github.com/Genymobile/scrcpy#get-the-app
https://github.com/Genymobile/scrcpy/blob/master/doc/windows.md

**Comment by ALKOALSHAN** [comment]
It still says

scrcpy 2.0 <https://github.com/Genymobile/scrcpy>
INFO: Killing adb daemon (if any)...
ERROR: Could not find any USB device

**Comment by rom1v** [comment]
Yes, on Windows, USB is complicated: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#hidotg-issues-on-windows

**Comment by ALKOALSHAN** [comment]
It works.
Thank you, @rom1v, I appreciate the hard work you put into scrcpy 💖

**Comment by rom1v** [comment]
> It works.

What did you do to make it work?

**Comment by ALKOALSHAN** [comment]
> > It works.
> 
> What did you do to make it work?

I changed the adb driver, and it actually started working, but when you unplug and plug or something else heappens it stops. I think its still a driver issue

**Comment by eduardocintas** [comment]
> Probably a snap permission/restriction issue.
> 
> Try a non-snap version: https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple

You are right, you need to give "raw-usb" permission on snap. The it works.
