### ISSUE TITLE
Could not determine java version from '9.0.4'.

### ISSUE THREAD

**Issue by daurnimator** [Genymobile/scrcpy#3]
Running ninja:

```
Set executable permissions for: /home/myuser/.gradle/wrapper/dists/gradle-4.1-all/bzyivzo6n839fup2jbap0tjew/gradle-4.1/bin/gradle

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '9.0.4'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org
ninja: build stopped: subcommand failed.
```

**Comment by rom1v** [comment]
It seems you use Java 9.

To solve the issue, read: https://github.com/facebook/react-native/issues/16536
(or just switch to Java 8)

_Note that you may use the [prebuilt server](https://github.com/Genymobile/scrcpy#prebuilt-server) instead._

**Comment by stek29** [comment]
Even after fixing gradle properties build still would fail, I'd just recommend to install java8 and switch to it.
