### ISSUE TITLE
Unable to use/install/setup scrcpy

### ISSUE THREAD

**Issue by udit7395** [Genymobile/scrcpy#30]
Hi,
First of all thank you for making this application.

I have never used meson build system before.I tried executing the commands given in the README but i am still unable to setup scrcpy.

I executed this command inside of scrcpy folder. "meson x --buildtype release --strip -Db_lto=true" 
gives the following error.
Error during basic setup:

[Errno 2] No such file or directory: '/home/udit/scrcpy/x'

So I made a folder named 'x' and executed the same command again.
Got this error 
The Meson build system
Version: 0.29.0
Source dir: /home/udit/scrcpy
Build dir: /home/udit/scrcpy/x
Build type: native build
Build machine cpu family: x86_64
Build machine cpu: x86_64

Meson encountered an error in file meson.build, line 1, column 0:
Meson version is 0.29.0 but project requires >= 0.37.

I updated meson using pip3 but still I get the above errors.

Am I  doing something wrong? Please let me know.
 
Thanks.

**Comment by eapen** [comment]
Try following these steps: https://www.cnx-software.com/2018/03/10/scrcpy-open-source-software-let-you-control-an-android-phone-via-a-windows-mac-os-or-linux-pc/

**Comment by udit7395** [comment]
@eapen Thanks.
For anyone else I faced some more issues.
Please make sure to follow/do the steps mentioned in the blog.

The following is for Ubuntu OS.
If you get an issue after updating meson, then just close and open the terminal. 
For some reasons the current terminal session doesn't take the updated meson path.

If you get this error
ERROR: Could not detect Ninja v1.5 or newer
then just sudo apt-get install ninja-build.

**Comment by rom1v** [comment]
>     sudo apt-get install ninja-build

Did you install `meson` from `apt-get` or `pip3`? For `apt-get`, it should automatically install `ninja-build`.

**Comment by udit7395** [comment]
@rom1v , I accidentally removed ninja-build. I installed meson from pip3.
