### ISSUE TITLE
The window flashes by with no output

### ISSUE THREAD

**Issue by 45231hgjkl** [Genymobile/scrcpy#3000]
- [YES] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [YES] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows 10 21H1]
 - scrcpy version: [1.22]
 - installation method: [Windows Realese]
 - device model:Xiaomi Pad 5 Pro 5G
 - Android version:[11]

**Describe the bug**
When I type 'scrcpy' in CMD and run it, it just pops up a window and closes quickly, opens' scrcpy-console.bat 'and says' press any key to continue...' with no output. After input 'ADB Devices', you can find the device. (The above is machine translation. If you don't understand anything, please put forward)

**Comment by 45231hgjkl** [comment]
`ERROR: CreateProcessW() error 5
ERROR: Failed to execute: [C:\Users\Administrator.DESKTOP-0U338PT\AppData\Local\Android\android-sdk\platform-tools], [get-serialno]
ERROR: Could not execute "adb get-serialno"
ERROR: Could not get device serial
ERROR: Server connection failed`

**Comment by 45231hgjkl** [comment]
Running in Windows PowerShell, i got this:
ERROR: CreateProcessW() error 5
ERROR: Failed to execute: [C:\Users\Administrator.DESKTOP-0U338PT\AppData\Local\Android\android-sdk\platform-tools], [get-serialno]
ERROR: Could not execute "adb get-serialno"
ERROR: Could not get device serial
ERROR: Server connection failed

**Comment by rom1v** [comment]
> ERROR: Failed to execute: [C:\Users\Administrator.DESKTOP-0U338PT\AppData\Local\Android\android-sdk\platform-tools], [get-serialno]

You set the `ADB` variable to a wrong value (it must point to the adb executable, not its directory). Remove this environment variable, adb is available in the scrcpy release.

**Comment by 45231hgjkl** [comment]
The problem has been solved, thank you
