### ISSUE TITLE
windows version requesting for authorization to download

### ISSUE THREAD

**Issue by zhafedee** [Genymobile/scrcpy#3007]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
What do you mean?

**Comment by zhafedee** [comment]
I tried downloading the windows version and it asked for password

**Comment by rom1v** [comment]
The problem is on your side (computer or network).

Downloading from the download link does not require any password: https://github.com/Genymobile/scrcpy#summary

**Comment by rom1v** [comment]
> But I have not been able to use it

https://www.chiark.greenend.org.uk/~sgtatham/bugs.html
