### ISSUE TITLE
Cropping Notification and Navigation Bars

### ISSUE THREAD

**Issue by ivantyr** [Genymobile/scrcpy#302]
Using the cropping function to "hide" the notification bar is possible but I can't get the navigation bar to hide
Is there any way to do it?

**Comment by rom1v** [comment]
> Using the cropping function to "hide" the notification bar is possible but I can't get the navigation bar to hide

I'm not sure I understand the question.

Do you want the navigation bar to be cropped, or hidden on the device?

To crop it, suppose you have a device (in portrait) 1080×1920, with a navigation bar of 64px.
You want to remove the 64 top pixels, so you can call:

    scrcpy --crop 1080:1856:0:64

**Comment by rom1v** [comment]
On your screenshot, the notification bar height is 53px, while the navigation bar is 108px (the whole image is 1080×1920).

So your target height is 1080-53-108=919, starting at offset 53:

    scrcpy --crop 1080:919:0:53

> maybe it varies a bit because of the -m 720 

The `-m`/`--max-size` value is computed _after_ the cropping (so you need to crop relative to the original size).
