### ISSUE TITLE
Pass arbitrary extra arguments to ADB

### ISSUE THREAD

**Issue by DarkZeros** [Genymobile/scrcpy#3022]
- [X] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
WIndows ADB fails to read the environment value ADB_SERVER_SOCKET
making connections to remote adb servers impossible right now.

**Describe the solution you'd like**
I want to pass -H to ADB, but right now this means adding another arg all the way through.
Currently passing arguments to ADB is tricky, since they have to be pre parsed by scrcpy and then
forwarded to ADB to be executed. It would be nice and cleaner to have a unified way to build the
parameters passed to adb, and also add any extra user parameter.
ie: scrcpy --adb-arg="-H" --adb-arg="168.0.1.3"

**Describe alternatives you've considered**
Add a new -H argument to scrcpy to be forwarded to ADB like the others.

**Additional context**
Why the WIndows ADB does not respect the environment flag?

**Comment by rom1v** [comment]
> WIndows ADB fails to read the environment value ADB_SERVER_SOCKET

It works perfectly for me. From a virtualbox with Windows 10 (so 10.0.2.2 is the host machine):

```cmd
set ADB_SERVER_SOCKET=tcp:10.0.2.2:5037
scrcpy --tunnel-host=10.0.2.2
```

> It would be nice and cleaner to have a unified way to build the parameters passed to adb, and also add any extra user parameter.

In any case, you could write a wrapper script for adb, for example on Windows `myadb.bat`:

```
adb -something %*
```

and request scrcpy to use this script:

```
set ADB=myadb.bat
scrcpy
```

**Comment by DarkZeros** [comment]
Oh damm it is a powershell issue....
It works as you said in cmd.

Thanks! That closes this feature!
