### ISSUE TITLE
update info of scaling issue in FAQ.md

### ISSUE THREAD

**Issue by NewUserHa** [Genymobile/scrcpy#3028]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#the-quality-is-low seems to be outdated now.

actually, I found when the screen resolution or the window is way smaller than the desktop resolution(like 4k), the upscaling result is not as clear as the scrcpy 1.22 with DPIawareness on.

So the FAQ.md should encourage the users to `update to the least version` as first solution, than `Override high DPI scaling behavior`, then than try `opengl`

**Comment by rom1v** [comment]
Please review #3032.

**Comment by NewUserHa** [comment]
👍

**Comment by NewUserHa** [comment]
Is it possible without `opengl` to use better filters like lanczos3, bicubic, etc. for up/downscaling?

**Comment by rom1v** [comment]
@NewUserHa Basically, no: https://github.com/Genymobile/scrcpy/issues/40#issuecomment-792144693
