### ISSUE TITLE
Error java.lang.IllegalStateException on connect

### ISSUE THREAD

**Issue by jonguim** [Genymobile/scrcpy#3033]
**Environment**
 - OS:Windows 10
 - scrcpy version: 1.22
 - installation method 
 - device model: Xiaomi M2101K6G 
 - Android version: 12

**Describe the bug**
When i connect give me the error java.lang.IllegalStateException:

```
 
`[server] INFO: Device: Xiaomi M2101K6G (Android 12)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
WARN: Device disconnected
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3535)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:147)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:99)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:73)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:100)
        at com.genymobile.scrcpy.Server.main(Server.java:326)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:363)
Press any key to continue . . .`

**Comment by rom1v** [comment]
Try #2990

**Comment by rom1v** [comment]
```
scrcpy -m1024
```

**Comment by jonguim** [comment]
i already try that:
 scrcpy -m 1920
scrcpy -m 1024
scrcpy -m 800
and i try run with different Encoder,i have 3 encoder, two of them run but the image is freezing, the error is with this encoder "OMX.qcom.video.encoder.avc"

**Comment by jonguim** [comment]
i try with that two commands i give me the error

**Comment by scresante** [comment]
I just figured I would chime in here and let you know, I have tested scrcpy versions 1.{17,18,19,22} off of the caches I have from archlinux, as well as a complete server and client build from dev branch I made a night ago.

 They all work if I use `scrcpy -m1920` . 
 
In some way these issues are all inter-related but I know close to nothing about Java to debug the root cause of the issue. 
 
I can do further user testing on which values for the -m flag work, and which don't but I have no further information about the problem.

Thanks for making this excellent software @rom1v

**Comment by Crusnik05** [comment]
I got excatly the same like this one..
Device : Redmi note 10 Pro
Android : 12
MIUI 13

I think it's the problem with the android 12.
before im update, it's work normally.

**Comment by jonguim** [comment]
> I got excatly the same like this one.. Device : Redmi note 10 Pro Android : 12 MIUI 13
> 
> I think it's the problem with the android 12. before im update, it's work normally.

ok thanks

**Comment by Solat-Ali** [comment]
Same issue, Redmi Note 10, MIUI 13, Android 12.. Did you fix this issue??

**Comment by Apihplays** [comment]
here same on mojito(Redmi note 10) miui 13 xiaomi.eu . if solve do reply ..i really miss using scrcpy. i use it alot before upgrade to miui 13 .. so sad

**Comment by kurinoko** [comment]
Facing the same issue on my Xiaomi Mi A1, I just upgraded to LineageOS 18.1 (Android 11) from LineageOS 16 (Android 9). Of course, everything was fine before upgrading :/

**Comment by fulanda-prog** [comment]
hopefully someone will workout a fix soon as looks many are suffering.

**Comment by rom1v** [comment]
#3051
