### ISSUE TITLE
Youtube crash

### ISSUE THREAD

**Issue by Snify89** [Genymobile/scrcpy#3034]
So I was downloading scrcpy and ran the console.bat file (Using Windows 10 Pro).
I have a Mi 10 Lite 5g and scrcpy works (almost) perfectly.

However sometimes during the switch between Fullscreen via Youtube and back, this error occurs and scrcpy closes:

[server] INFO: Device: Xiaomi M2002J9G (Android 11)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0x80001009
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0x80001009
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:2251)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:101)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:73)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:100)
        at com.genymobile.scrcpy.Server.main(Server.java:326)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:463)
WARN: Killing the server...

Just leaving this here for you and hope it's useful :)

**Comment by rom1v** [comment]
Your MediaCodec crashes because your hardware probably can't handle both youtube and screen encoding.

Try to reduce the definition:

```
scrcpy -m 1024
```

**Comment by Snify89** [comment]
> Your MediaCodec crashes because your hardware probably can't handle both youtube and screen encoding.
> 
> Try to reduce the definition:
> 
> ```
> scrcpy -m 1024
> ```

Not sure which hardware you mean...
I was talking about the YouTube Android App.
The crash just occurs sometimes.
Still, I will try to reduce the definition. 
Thank you very much :)

**Comment by rom1v** [comment]
> Not sure which hardware you mean...

Your Android device has an hardware decoder/encoder used to play (for example youtube) or encode videos (for example from your camera, or in this case encoding the device screen to produce a video stream for scrcpy). When there is a bug or the resources are exhausted, it may crash.

**Comment by Snify89** [comment]
I can reproduce this issue now by holding the scrcpy window and drag it around my screen.
Meanwhile the video output of scrcpy is frozen.
So this might flood some buffer(s) in the background or so?!

Maybe this can help?
https://stackoverflow.com/questions/18041622/how-do-i-stop-windows-from-blocking-the-program-during-a-window-drag-or-menu-but

Still, not a big issue. 
Just trying to help and let you know :)

Thank you!
