### ISSUE TITLE
where is the homepage and Task button？

### ISSUE THREAD

**Issue by hentai87** [Genymobile/scrcpy#304]
rightclik is back，but where is the homepage and Task button？

**Comment by Ericgacoki** [comment]
cool

**Comment by otsenreDC** [comment]
Also found in `scrcpy --help`

**Comment by ChaoticNeutralCzech** [comment]
There has been an update and the shortcuts use left Alt/Super by default. Here is a complete list from Help (thanks @otsenreDC):

    --shortcut-mod=key[+...][,...]
        Specify the modifiers to use for scrcpy shortcuts.
        Possible keys are "lctrl", "rctrl", "lalt", "ralt", "lsuper" and "rsuper".
        A shortcut can consist in several keys, separated by '+'. Several shortcuts can be specified, separated by ','.
        For example, to use either LCtrl+LAlt or LSuper for scrcpy shortcuts, pass "lctrl+lalt,lsuper".
        Default is "lalt,lsuper" (left-Alt or left-Super).
    [...]
    Shortcuts:
    In the following list, MOD is the shortcut modifier. By default, it's (left) Alt or (left) Super, but it can be
    configured by --shortcut-mod (see above).
    
    MOD+f
        Switch fullscreen mode
    
    MOD+Left
        Rotate display left
    
    MOD+Right
        Rotate display right
    
    MOD+Shift+Left
    MOD+Shift+Right
        Flip display horizontally
    
    MOD+Shift+Up
    MOD+Shift+Down
        Flip display vertically
    
    MOD+g
        Resize window to 1:1 (pixel-perfect)
    
    MOD+w
    Double-click on black borders
        Resize window to remove black borders
    
    MOD+h
    Middle-click
        Click on HOME
    
    MOD+b
    MOD+Backspace
    Right-click (when screen is on)
        Click on BACK
    
    MOD+s
    4th-click
        Click on APP_SWITCH
    
    MOD+m
        Click on MENU
    
    MOD+Up
        Click on VOLUME_UP
    
    MOD+Down
        Click on VOLUME_DOWN
    
    MOD+p
        Click on POWER (turn screen on/off)
    
    Right-click (when screen is off)
        Power on
    
    MOD+o
        Turn device screen off (keep mirroring)
    
    MOD+Shift+o
        Turn device screen on
    
    MOD+r
        Rotate device screen
    
    MOD+n
    5th-click
        Expand notification panel
    
    MOD+Shift+n
        Collapse notification panel
    
    MOD+c
        Copy to clipboard (inject COPY keycode, Android >= 7 only)
    
    MOD+x
        Cut to clipboard (inject CUT keycode, Android >= 7 only)
    
    MOD+v
        Copy computer clipboard to device, then paste (inject PASTE keycode, Android >= 7 only)
    
    MOD+Shift+v
        Inject computer clipboard text as a sequence of key events
    
    MOD+i
        Enable/disable FPS counter (print frames/second in logs)
    
    Ctrl+click-and-move
        Pinch-to-zoom from the center of the screen
    
    Drag & drop APK file
        Install APK from computer
    
    Drag & drop non-APK file
        Push file to device (see --push-target)
