### ISSUE TITLE
Can't get device serial

### ISSUE THREAD

**Issue by vinir98** [Genymobile/scrcpy#3040]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10 64x
 - scrcpy version: 1.22
 - installation method: Windows release
 - device model: Umidigi A9 pro
 - Android version: 10

**Describe the bug**
Can't initialize after type "scrcpy" 

Output:
ERROR: "adb get-serialno" returned with value 1
ERROR: Could not get device serial
ERROR: Server connection failed

I already read the FAQ and searched in issues tab, my debugging option is active and my USB drivers are up to date. Used to mirror via USB with no problem some releases ago(sorry I dont remember exactly which release)

**Comment by rom1v** [comment]
What is the result of `adb devices`? And `adb get-serialno`?

**Comment by vinir98** [comment]
for `adb devices` is `List of devices attached

` Like no devices are plugged. 

Ande for `adb get-serialno` is `error: no devices/emulators found`

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#device-not-detected

**Comment by vinir98** [comment]
Solution: Unchecked option "verify apps by USB" on developer option

I discovered here: https://stackoverflow.com/questions/45775717/can-not-find-my-xiaomi-mi-6-device-in-android-studio

ty
