### ISSUE TITLE
Bad Quality when moving around.

### ISSUE THREAD

**Issue by Clytax** [Genymobile/scrcpy#3044]
When I try to record games and move around the quality rapidly decreases which makes it inpossible to watch. Any way I can fix that? I can provide videos if you need more information.

dependencies:
 - SDL 2.0.20
 - libavcodec 59.18.100
 - libavformat 59.16.100
 - libavutil 57.17.100

I am using a Samsung s10e with a USB-C Connection.

**Comment by rom1v** [comment]
Increase the bitrate:

```
scrcpy -b20M
```

You could also reduce the definition (more bytes will be used by surface unit for the same bitrate):

```
scrcpy -m1920 -b20M
```

**Comment by Clytax** [comment]
Wow, it works! Thanks for the quick help!
