### ISSUE TITLE
OTG error on Windows 10

### ISSUE THREAD

**Issue by StrikerOnLine** [Genymobile/scrcpy#3045]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: 1.22
 - installation method: windows release
 - device model: Redmi note 8 pro
 - Android version: Android 11
**Describe the bug**
It is impossible to use --otg function in windows 10

On errors, please provide the output of the console (and `adb logcat` if relevant).
scrcpy --otg
scrcpy 1.22 <https://github.com/Genymobile/scrcpy>
ERROR: OTG mode (--otg) is not supported on this platform. It is only available on Linux.
```
scrcpy --otg
scrcpy 1.22 <https://github.com/Genymobile/scrcpy>
ERROR: OTG mode (--otg) is not supported on this platform. It is only available on Linux.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
`--otg` was only available on Linux.

But it will be available in the next release on Windows: #3011. Please test and report any issue.
