### ISSUE TITLE
Possible Bug: Keyboard Override

### ISSUE THREAD

**Issue by shadowguy97** [Genymobile/scrcpy#305]
Noticed that system keyboards does not fully override phone keyboard. some keys are linked to gestures on the phone.

**Comment by rom1v** [comment]
Sorry, I don't understand the issue. What keys are linked to gestures?

**Comment by shadowguy97** [comment]
My phone (Innjoo Halo Plus) has smart gesutures where if a specific character is drawn it performs a command. I noticed that if i press that specified character the command is performed despite the screen am on. Turning off the feautre does not solve the problem

**Comment by rom1v** [comment]
Scrcpy just injects events, I don't know how it may interact with a specific "smart gestures". Sorry.
