### ISSUE TITLE
ERROR: Could not find any ADB device ERROR: Server connection failed 

### ISSUE THREAD

**Issue by martinericksonn** [Genymobile/scrcpy#3054]
**Environment**
 - OS: Ubuntu Zorin OS 16
 - scrcpy version: 1.23
 - installation method: manual build
 - device model: Galaxy A12
 - Android version: 11

**Describe the bug**
Android 12 works fine after updating scrcpy but this android 11 still could not be detected.
Developer option is enabled

```
scrcpy 1.23 <https://github.com/Genymobile/scrcpy>
ERROR: Could not find any ADB device
ERROR: Server connection failed
```

**Comment by rom1v** [comment]
What is the result of `adb devices`?

**Comment by martinericksonn** [comment]
`list of devices attached


`
The device could not be seen

**Comment by rom1v** [comment]
> Developer option is enabled

It's not only "Developer Options", but inside "Developer Options" you must enable USB debugging.

On linux, if it's still not detected, then it's probably related to udev rules.

**Comment by HaveSomeRubicon** [comment]
Are you getting this error: adb: error: failed to get feature set: insufficient permissions for device: user in plugdev group; are your udev rules wrong?
im on zorin too and im getting it.

**Comment by martinericksonn** [comment]
> > Developer option is enabled
> 
> It's not only "Developer Options", but inside "Developer Options" you must enable USB debugging.
> 
> On linux, if it's still not detected, then it's probably related to udev rules.

My bad did I not check twice, forget to enable USB debugging. Thanks

**Comment by lucasbell22** [comment]
Estou com o mesmo problema, pode me ajudar?

**Comment by sdudnic** [comment]
> > > Developer option is enabled
> > 
> > 
> > It's not only "Developer Options", but inside "Developer Options" you must enable USB debugging.
> > On linux, if it's still not detected, then it's probably related to udev rules.
> 
> My bad did I not check twice, forget to enable USB debugging. Thanks

what do you mean "forget", where is written to enable it, and how to enable it? I have a pixel phone

**Comment by HaveSomeRubicon** [comment]
> > > > Developer option is enabled
> > > 
> > > 
> > > It's not only "Developer Options", but inside "Developer Options" you must enable USB debugging.
> > > On Linux, if it's still not detected, then it's probably related to udev rules.
> > 
> > 
> > My bad did I not check twice, forget to enable USB debugging. Thanks
> 
> what do you mean "forget", where is written to enable it, and how to enable it? I have a pixel phone

Step 1: Open settings
Step 2: Open the "about phone" or "about device" section
Step 3: Open the "software information" section or whatever it's called on your device.
Step 4: Click the "build number" 7 or 8 times
Step 5: Go to the main menu of your settings app
Step 6: Open the new "developer options" section
Step 7: Scroll down until you find USB debugging and enable it

**Comment by renatoleffers** [comment]
I have an s21plus and the developer mode with USB debugging is enabled and it still has the same error.

**Comment by kkdas1988** [comment]
I have OPPO A19 and I am facing the same problem. I have switched ON the USB debugging in developer mode but still the problem persists.
Please help me....

**Comment by o-data** [comment]
Hi @kkdas1988 we trying to solve Oppo issue on here as well: #3415

**Comment by samheyman** [comment]
Scrcpy was working fine for me a few weeks ago with my Sony Xperia . Today it won't connect:

```PS C:\Users\sam.heyman> scrcpy.exe
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
ERROR: Could not find any ADB device
ERROR: Server connection failed
PS C:\Users\sam.heyman>
```
I haven't changed anything, connected via USB as a developer as per usual.

**Comment by boxbotteries** [comment]
Having the same issue with an LG Velvet LM-G900UM + Windows 10. Developer options enabled, USB debugging is on, scrcpy still can't see the device. Tried activating "Disable adb authorization timeout" to see if that helped, but nada.

**Comment by OS-DaveThompson** [comment]
Yeah, S22-Ultra fully updated as well as an S6-Lite here.  Scrcpy worked flawlessly a bit ago, but I got them out to do another video presentation with them and neither one has a visible ADB device.  I did a video on this on my new YT channel because it's the bomb-digz.

The phone and tab are fully updated as of today.  I am running fully updated Kubuntu 2004, have ADB v 1.0.39 installed as well as v 1.24 of Scrcpy.

What else can I get to you that might help?

**Comment by Cabralm7** [comment]
i'm facing the same problem, it used to work, but now even with USB debugging enabled it still has the same error.

**Comment by rom1v** [comment]
If the device is not detected, it's an adb/usb issue: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#device-not-detected

In particular, on Windows, it might be necessary to install or upgrade your drivers: https://developer.android.com/studio/run/oem-usb.html

**Comment by aelitangel** [comment]
i am having Galaxy Tab s7 FE and its not connecting 

ERROR: Could not find any ADB device
ERROR: Server connection failed

**Comment by PrzemekSkw** [comment]
Hi, I use OnePlus9pro with Android13 and also have that error. I have usb debugging and wifi debigging enabled.
OS: `Archlinux (Garuda)` 
Kernel: `6.1.21-1-lts`

Regards.

**Comment by rom1v** [comment]
On ArchLinux check your udev rules: https://stackoverflow.com/questions/43771918/how-do-i-set-up-udev-rules-for-debugging-a-physical-android-device-with-android (random link)

**Comment by k7n4n5t3w4rt** [comment]
I'm on Android13 and I had the error. I fiddled with the "Default USB configuration":

System > Developer Options > Default USB configuration

I set it to "USB tethering" and then, when I checked `adb devices`, I saw my device. Then `scrcpy` worked like magic.

**Comment by igormcsouza** [comment]
For some reason, I was having the same exactly issue! And I could fix using the original usb cable! Unbelivable! But yeah!

**Comment by mcknx** [comment]
Hello this is the solution, install this:

`https://developer.android.com/tools/releases/platform-tools`

The full tutorial here (I am not promoting):
`https://youtu.be/8C9S4WfbJyY?list=PLksqz4VrEDuamtupBop2lZO96FDy5vYPP`

**Comment by adityatav1** [comment]
> Hello this is the solution, install this:
> 
> `https://developer.android.com/tools/releases/platform-tools`
> 
> The full tutorial here (I am not promoting): `https://youtu.be/8C9S4WfbJyY?list=PLksqz4VrEDuamtupBop2lZO96FDy5vYPP`

i use Redmi 9A, windows 8.1 and i already follow this video but still not find the device.. when i use write "adb device -l" nothing device to show in command prompt

**Comment by elciodalosto** [comment]
@HaveSomeRubicon, your tips worked nice for me. 
Just turning On the 'USB debugging' option on my Android smartphone. Thanks bro!

**Comment by Waklabu46** [comment]
![image](https://github.com/Genymobile/scrcpy/assets/156927795/ae0e4b66-86e7-4d97-b33f-b43ac7c8a0c9)

mohon bantuan nya. karena layar hp nya tidak tampil ke laptop

**Comment by rom1v** [comment]
#4531

**Comment by rom1v** [comment]
You forgot adb connect. Read https://github.com/Genymobile/scrcpy/blob/master/doc/connection.md#tcpip-wireless

**Comment by Freddymhs** [comment]
Maybe you could revocate the permissions, then try again.

**Comment by novoid** [comment]
For the reference: I, too, did not see my device in "adb devices" until I switched from "USB-C-to-Micro-USB-Adapter + Micro-USB-to-USB-A-cable + USB-hub" to a USB-C cable that was plugged in directly to the host.

So it's not always a software issue.

**Comment by silk-code-github** [comment]
Changed phone and it wouldn't work anymore.

```
scrcpy 2.7 <https://github.com/Genymobile/scrcpy>
ERROR: Could not find any ADB device
ERROR: Server connection failed
```

In the end changing the "Default USB Configuration" (in développer option) to anything other than the first one fixed it.

![fixNoDeviceADB](https://github.com/user-attachments/assets/fa7a9e0e-b918-4b34-9c74-60f68139ef19)

Now I'm not sure Android Auto will work now though.

Hope it helps someone.

**Comment by taquitobytes** [comment]
Dang, for me it was the cord. I had a cheap usb c (on both sides) cord. I switched to a more durable one and I was prompt with "Allow USB Debugging" 🚀 💪 . This might be the root cause to some people's issue here. Thank you @novoid !

**Comment by TheGreatday21** [comment]
what if your screen is completely black and cannot be used and you did not allow usb debugging earlier

**Comment by novoid** [comment]
> > Dang, for me it was the cord. I had a cheap usb c (on both sides) cord. I switched to a more durable one and I was prompt with "Allow USB Debugging" 🚀 💪 . This might be the root cause to some people's issue here. Thank you [@novoid](https://github.com/novoid) !
> 
> Keep in mind that some cord is purely charging/electric only and do not support data. So that might be the cord you were using?

In my case, the cable was able to be used for data transfer in general. But yes, some cables are for charging only, I agree.

**Comment by LevenReverie** [comment]
**If you have yet to enable USB debugging**, you can use the "--otg" for scrcpy. This allows control, **but cannot preview the screen,** so hopefully you still have partial view, at the very least.

Also, **you might face some driver problems that might prevent you from connecting,** in this case, use download and use **zadig**. Open zadig, on you should see a drop down for the devices. If you can't find your phone, check the top left for "Options" and enable "List All Devices". Go check the drop down menu again and select your device. As for the driver, select WinUSB and press replace driver.

After all that, you should be able to connect to your phone as if your keyboard and mouse are otg peripherals.

**If you are having troubles connecting even with USB Debugging enabled,** try connecting your phone through usb cable and enabling USB Tethering, after that you might see a prompt in your phone asking if you wanna allow this device and bla bla bla. Enable that, then try running scrcpy again.

**Comment by Chafalleiro** [comment]
> Changed phone and it wouldn't work anymore.
> 
> ```
> scrcpy 2.7 <https://github.com/Genymobile/scrcpy>
> ERROR: Could not find any ADB device
> ERROR: Server connection failed
> ```
> 
> In the end changing the "Default USB Configuration" (in développer option) to anything other than the first one fixed it.
> 
> ![fixNoDeviceADB](https://github.com/user-attachments/assets/fa7a9e0e-b918-4b34-9c74-60f68139ef19)
> 
> Now I'm not sure Android Auto will work now though.
> 
> Hope it helps someone.

That was it for me.

**Comment by drudolf17** [comment]
> > Changed phone and it wouldn't work anymore.
> > ```
> > scrcpy 2.7 <https://github.com/Genymobile/scrcpy>
> > ERROR: Could not find any ADB device
> > ERROR: Server connection failed
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In the end changing the "Default USB Configuration" (in développer option) to anything other than the first one fixed it.
> > ![fixNoDeviceADB](https://github.com/user-attachments/assets/fa7a9e0e-b918-4b34-9c74-60f68139ef19)
> > Now I'm not sure Android Auto will work now though.
> > Hope it helps someone.
> 
> That was it for me.

Me too.

**Comment by Benewend** [comment]
Mine was cable(cord) related

**Comment by ByKamixD** [comment]
Doing those commands fixed it for me: 
`adb kill-server`
`adb start-server`
