### ISSUE TITLE
Getting 'adb: error: failed to get feature set: insufficient permissions for device: user in plugdev group; are your udev rules wrong?' when runny scrcpy

### ISSUE THREAD

**Issue by HaveSomeRubicon** [Genymobile/scrcpy#3055]
**Environment**
 - OS: Zorin 16 lite(Ubuntu 20.04)
 - scrcpy version: [e.g. 1.12.1]
 - installation method: apt
 - device model: sm-t290
 - Android version: 11

When I run 'scrcpy' in /home/mahdi I get this:
`INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: insufficient permissions for device: user in plugdev group; are your udev rules wrong?
See [http://developer.android.com/tools/device.html] for more information
ERROR: "adb push" returned with value 1
`

Scrcpy was previously working under the exact same conditions and pc on Windows 10 and Zoring 16 lite. However it's not working after I redownloaded Zorin 16.

**Comment by HaveSomeRubicon** [comment]
idk its working after turning off and on usb tethering

**Comment by heyakyra** [comment]
https://github.com/Genymobile/scrcpy/issues/359#issuecomment-4366982830
