### ISSUE TITLE
Scrcpy opens black screen

### ISSUE THREAD

**Issue by HaveSomeRubicon** [Genymobile/scrcpy#3056]
**Environment**
 - OS: Zorin 16 lite(Ubuntu 20.04)
 - scrcpy version: 1.12.1
 - installation method: apt
 - device model: sm-t290
 - Android version: 11

When I run 'scrcpy' it opens a black screen.
It was previously working on the same hardware and android ver on zorin 16 lite and windows 10 but now its not working after reinstalling zorin 16 lite.

`mahdi@mahdis-PC:~$ scrcpy
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 fil...shed. 3.6 MB/s (24773 bytes in 0.007s)
INFO: Initial texture: 1280x800
`

**Comment by HaveSomeRubicon** [comment]
I can still click anywhere on the black screen and it will register, I just cant see anything.

**Comment by rom1v** [comment]
In all apps? Or just the "protected" ones?

**Comment by pmalecka** [comment]
same here, some apps just don't show anything. This is on android 12

**Comment by HaveSomeRubicon** [comment]
It seems like it was a driver issue with my open gl
