### ISSUE TITLE
scrcpy: unrecognized option '--tcpip' on Ubuntu

### ISSUE THREAD

**Issue by sownt** [Genymobile/scrcpy#3057]
I used **scrcpy** on Ubuntu 21.10 and connect successful over TCP/IP by manual instructions. But command ```scrcpy --tcpip``` not working on my machine, it shown
```bash
scrcpy: unrecognized option '--tcpip'
```

**Comment by rom1v** [comment]
Ubuntu 21.10 has v1.17: https://repology.org/project/scrcpy/versions

Uninstall the distrib version and install the latest manually: https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple
