### ISSUE TITLE
unable to execute due to scrcpy error.

### ISSUE THREAD

**Issue by woohahaa** [Genymobile/scrcpy#3059]
hello. 
I want to use this app, but it doesn't work.
It doesn't work even though I connected one device.
Is there another reason?
Thank you for making a useful app.
Below is an error that appears when executing scrcpy.
--------------------------------------------------------------------------------------------------------------------------------------------
scrcpy 1.23 <https://github.com/Genymobile/scrcpy>
ERROR: CreateProcessW() error 5
ERROR: Failed to execute: [D:\adb\platform-tools_r30.0.4-windows\platform-tools\], [start-server]
ERROR: Could not execute "adb start-server"
ERROR: Could not start adb daemon
ERROR: Server connection failed
--------------------------------------------------------------------------------------------------------------------------------------------

**Comment by rom1v** [comment]
> ERROR: Failed to execute: [D:\adb\platform-tools_r30.0.4-windows\platform-tools], [start-server]

You set your ADB environment variable to a wrong value (it must point to the adb executable, not its directory).

But adb is included in the scrcpy release, so just remove the ADB environment variable if you have no reason to.
