### ISSUE TITLE
Upgrade to Ubuntu 18.10 and ffmpeg up version are break scrcpy

### ISSUE THREAD

**Issue by IgorOhrimenko** [Genymobile/scrcpy#306]
After dist-upgrade system 18.04 -> 18.10:
```
scrcpy: error while loading shared libraries: libavformat.so.57: cannot open shared object file: No such file or directory
scrcpy: error while loading shared libraries: libavcodec.so.57: cannot open shared object file: No such file or directory
scrcpy: error while loading shared libraries: libavutil.so.55: cannot open shared object file: No such file or directory
```
After create simlink new lib to old and run scrcpy:
```
scrcpy: /usr/lib/x86_64-linux-gnu/libavutil.so.55: version `LIBAVUTIL_55' not found (required by scrcpy)
scrcpy: /usr/lib/x86_64-linux-gnu/libavformat.so.57: version `LIBAVFORMAT_57' not found (required by scrcpy)
scrcpy: /usr/lib/x86_64-linux-gnu/libavcodec.so.57: version `LIBAVCODEC_57' not found (required by scrcpy)

```

**Comment by rom1v** [comment]
That's not surprising. You need to rebuild scrcpy (with your new ffmpeg packages).

**Comment by shobhitagarwal1612** [comment]
> That's not surprising. You need to rebuild scrcpy (with your new ffmpeg packages).

Yes, I faced a similar issue and rebuilding fixed it for me

**Comment by hunterx9** [comment]
@rom1v 

> That's not surprising. You need to rebuild scrcpy (with your new ffmpeg packages).

Rebuilding does not solve the issue. Reiterating the steps in does not work or am i doing some thing wrong here?
https://github.com/Genymobile/scrcpy/blob/master/BUILD.md
