### ISSUE TITLE
wasd not working roblox

### ISSUE THREAD

**Issue by derryktutt** [Genymobile/scrcpy#3062]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]debian
 - scrcpy version: [e.g. 1.12.1] 1.23
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]manual
 - device model:Samsung SM-T290
 - Android version: [e.g. 10]11, One UI 3.1

**Describe the bug**
When I use WASD to move in roblox, nothein happens. Whe I right click and drag to move camera, the menu opens.
On errors, please provide the output of the console (and `adb logcat` if relevant).

```
scrcpy 1.23 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server:...shed. 0.6 MB/s (41123 bytes in 0.071s)
[server] INFO: Device: samsung SM-T290 (Android 11)
INFO: Renderer: opengl
INFO: OpenGL version: 2.1 Mesa 20.3.5
WARN: Trilinear filtering disabled (OpenGL 3.0+ or ES 2.0+ required)
INFO: Initial texture: 1280x800
INFO: Recording started to mp4 file: video.mp4
INFO: Recording complete to mp4 file: video.mp4
WARN: Killing the server...

```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
If the game does not handle WASD it won't work.

The solution would be to implement key mapping (to inject specific mouse events when you press some keys): #712

**Comment by rom1v** [comment]
If the game does not handle WASD it won't work.

The solution would be to implement key mapping (to inject specific mouse events when you press some keys): #712

**Comment by rom1v** [comment]
If the game does not handle WASD it won't work.

The solution would be to implement key mapping (to inject specific mouse events when you press some keys): #712

**Comment by rom1v** [comment]
Then:
 - `scrcpy --raw-key-events`
or:
 - `scrcpy --keyboard=uhid`

See https://github.com/Genymobile/scrcpy/blob/master/doc/keyboard.md
