### ISSUE TITLE
How does scrcpy turn off the display?

### ISSUE THREAD

**Issue by lmore377** [Genymobile/scrcpy#3068]
My phone's screen is broken and I've been using anydesk on another phone to control it when I need something off of it. Normally when I'm controlling it it's very laggy with a second or 2 delay but when I run scrcpy with --turn-screen-off it becomes very smooth with no lag and I wanted to see if there's a way to keep it in that screen off state so I don't have to be by a computer for scrcpy.

**Comment by rom1v** [comment]
```
scrcpy --turn-screen-off --no-cleanup
```

Since scrcpy v1.23.

**Comment by lmore377** [comment]
I should've looked thru the docs first lol. Thanks!
