### ISSUE TITLE
My phone screen is broken plz help!

### ISSUE THREAD

**Issue by menoob003** [Genymobile/scrcpy#307]
when I try to mirror my android it says

```
adb: error: failed to get feature set: no devices/emulators found
ERROR: "adb push" returned with value 1
Press any key to continue...
```

My phone screen is broken plz help!

**Comment by rom1v** [comment]
Was "USB debugging" enabled in developer options?

**Comment by dondiscaya0531** [comment]
Hi if your phone is OTG capable you can use USB mouse to control your device , then open playstore install teamviewer HOST , open app open menu then click for additional support, you will be prompt to download additional app, create teamviewer account, install teamviewer for PC then log in your account same with the smartphone you want to control.  Therefore once you plugged in your smartphone to PC you can Allow USB authorization wireless.

**Comment by menoob003** [comment]
> Hi if your phone is OTG capable you can use USB mouse to control your device , then open playstore install teamviewer HOST , open app open menu then click for additional support, you will be prompt to download additional app, create teamviewer account, install teamviewer for PC then log in your account same with the smartphone you want to control. Therefore once you plugged in your smartphone to PC you can Allow USB authorization wireless.

What is OTG and I can't see anything on my mobile so can't go to playstore or any where :'(

**Comment by dondiscaya0531** [comment]
What is the exact model of your android phone?

**Comment by menoob003** [comment]
> What is the exact model of your android phone?

how can i find it?

**Comment by numbermaniac** [comment]
You don't know what phone you have?

**Comment by menoob003** [comment]
> You don't know what phone you have?

I have Symphony Xplorer V52

**Comment by dondiscaya0531** [comment]
I've found your device specs. It is OTG capable. 

https://www.gsmmachine.com/symphony-xplorer-v52-4139.html

You must but an OTG adapter like this 


![61teapkjfdl _sx569_](https://user-images.githubusercontent.com/43704988/47621463-558e3c00-db33-11e8-94eb-c6fa1ee8cbc5.jpg)

Once you have this one , get a USB mouse connect it , open your device it must work to serve as your touch for your device. Next thing is go to your " settings" then "about device " , tap/click on " build number " 8 x, then a prompt will pop " congratulations your a developer now". Go back to settings there you will find developer options. Enable it. Look for " USB debugging " enable it. Once done , Go to playstore download " Teamviewer Host " install , open find its settings theres an option to download additional support click and download then install. Get another android device or install Teamviewer Windows on your PC.

Google on how to use teamviewer with your smartphone

Why im telling you this, this is the only option to allow your PC once you connect your smartphone on its USB port. Then you can switch to SCRcPY to control your smartphone.

**Comment by numbermaniac** [comment]
> ext thing is go to your " settings" then "about device " , tap/click on " build number " 8 x, then a prompt will pop " congratulations your a developer now". Go back to settings there you will find developer options. Enable it. Look for " USB debugging " enable it. 

How will they be able to do this if their screen is broken?

**Comment by menoob003** [comment]
> I've found your device specs. It is OTG capable.
> 
> https://www.gsmmachine.com/symphony-xplorer-v52-4139.html
> 
> You must buy an OTG adapter like this
> 
> ![61teapkjfdl sx569](https://user-images.githubusercontent.com/43704988/47621463-558e3c00-db33-11e8-94eb-c6fa1ee8cbc5.jpg)
> 
> Once you have this one , get a USB mouse connect it , open your device it must work to serve as your touch for your device. Next thing is go to your " settings" then "about device " , tap/click on " build number " 8 x, then a prompt will pop " congratulations your a developer now". Go back to settings there you will find developer options. Enable it. Look for " USB debugging " enable it. Once done , Go to playstore download " Teamviewer Host " install , open find its settings theres an option to download additional support click and download then install. Get another android device or install Teamviewer Windows on your PC.
> 
> Google on how to use teamviewer with your smartphone
> 
> Why im telling you this, this is the only option to allow your PC once you connect your smartphone on its USB port. Then you can switch to SCRcPY to control your smartphone.

Thank you soo much for trying to help me.
but #numbermaniac is right I can't see anything on my phone because the display is broken it's fully dark.
but the mobile is ok bcz I get some sounds when I touch on screen.
Again thank u soo much.

**Comment by cristipurdel** [comment]
You could try to find someone with similar phone and OS, and see how they manage to enable adb debugging, and then you have to do the same "blindly"
As a rule, I always enable this setting on every phone I get my hands on :)

**Comment by smartlinkz** [comment]
What happens when my phone's screen is blind, and i want to get an important information from the phone?
secondly what other purpose does the scrcpy serve aside from mirrowing your phone? 
Thanks
