### ISSUE TITLE
Mirroring without ADB please please on Windows

### ISSUE THREAD

**Issue by chldbwnstm** [Genymobile/scrcpy#3071]
Can we please have mirroring without adb on Windows please..
As now we have support for HID on windows, it would be perfect to have mirroring screen without adb,
so we can purely just have screen mirroring + control with mouse/keyboard without ADB.
This is because some apps detect adb.

**Comment by namos-23** [comment]
I believe the documentation and notes has thoroughly explained why that's not possible

**Comment by chldbwnstm** [comment]
> I believe the documentation and notes has thoroughly explained why that's not possible

Oh I thought it would now be possible with libusb support for Windows + AOAv2

**Comment by e1e0** [comment]
[google play store > "mirror screen"](https://play.google.com/store/search?q=mirror%20screen&c=apps)
