### ISSUE TITLE
Black screen on protected apps

### ISSUE THREAD

**Issue by BusyApeach** [Genymobile/scrcpy#3072]
**Environment**
 - OS: Win 10
 - scrcpy version: 1.23
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model: SM-S908N Galaxy S22 Ultra
 - Android version: Android 12, One UI 4.1

**Describe the bug**

is there any way to stream the protected apps on Android 12?

it shows a black screen when I open a screen capture blocked app.

I saw a post about turning off secure screen option but not on Samsung OneUI.

**Comment by rom1v** [comment]
On Android 12, you can't.

#2129
