### ISSUE TITLE
Maybe reflection is unneded here

### ISSUE THREAD

**Issue by twaik** [Genymobile/scrcpy#3073]
Gradle allows us to add our jars to bootClasspath. At least I do not see if there is read-only or public modificator.
```
project.afterEvaluate {
	project.android.bootClasspath += '/path/to/classpath.jar'
}
```
You can try to build a library containing Android classes (parts of them) and use it in main project.

**Comment by twaik** [comment]
I'll just put it here.
https://github.com/RikkaApps/HiddenApiRefinePlugin
https://github.com/LSPosed/AndroidHiddenApiBypass

**Comment by twaik** [comment]
Shizuku uses [this](https://github.com/RikkaW/HiddenApi). Shortly: you can write some stubs for Android classes in some library and use it as `compileOnly` dependency inside a project. This solution will not use any kind of reflection.

**Comment by twaik** [comment]
Stale issue.

**Comment by rom1v** [comment]
Scrcpy already used the android framework API. Reflection is used for hidden APIs (which have not the same signatures on all Android API versions or devices).

**Comment by twaik** [comment]
The sense of the issue is to not use reflection at all. It is possible to use stubs (like [this](https://github.com/termux/termux-x11/blob/master/shell-loader/stub/src/main/java/android/app/ActivityThread.java)) with gradle's `compileOnly`. In this case you are getting much more readable code. In the case if it is not possible (i.e. class is already defined in android.jar) you can use HiddenApiRefine. But this solution does not let you change field protection so reflection will be neede only there.

**Comment by twaik** [comment]
That happens only if you are using new API on old devices, like `View.requestPointerCapture()` that was added in Android 8.0 (api-level 26) and did not exist before this release. So it is possible to check android versions to avoid API incompatibility.

**Comment by rom1v** [comment]
Sometimes, but not always:
 - an internal method might change for the same API version (especially during alpha/beta/preview, but also after)
 - some vendors change methods, so the method is not the same on different devices even if the API version is the same (a recent example: #3885)

**Comment by twaik** [comment]
In the case if you are calling non-existing method you will get the same `NoSuchMethodException`. But code will be much more clear even with this try-catch sequences.
