### ISSUE TITLE
[question] control phone while locked

### ISSUE THREAD

**Issue by irux** [Genymobile/scrcpy#308]
Hello.

I would like to know if it could be possible to control the phone while it is in "sleep" mode.

It could be really useful if you have your phone in your pocket and you want to control it without having false positive touch events or using a lot of battery with the screen on.

Thank you!

**Comment by rom1v** [comment]
Unfortunately, no :(

See https://github.com/Genymobile/scrcpy/issues/175.

**Comment by rom1v** [comment]
Now you can.
