### ISSUE TITLE
Different exit-code if device does not exist vs. device disconnects

### ISSUE THREAD

**Issue by madduck** [Genymobile/scrcpy#3083]
- [X] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Describe the solution you'd like**
If `scrcpy` is started, but it cannot find the specified device, it should exit with a different exit code than if the device is disconnected while `scrcpy` is in use. Currently, it exits 1 for both, and it would be useful to be able to react differently when `scrcpy` stops due to disconnection vs. it never being able to make a connection in the first place.

**Comment by rom1v** [comment]
Why not. PR welcome.
