### ISSUE TITLE
Android 4.1 support

### ISSUE THREAD

**Issue by zzx-the-neptune** [Genymobile/scrcpy#3086]
I have a Xperia E and it runs on jelly bean 4.1 but there is no support for jelly bean. 
I NEED JELLY BEAN SUPPORT because the Xperia E has a broken screen and i have to plug, view image, screenshot, unplug and over and over **AND OVER** and because scrcpy and vysor dont have jelly bean support, this phone is almost useless!

So please add jelly bean support by lowering the api level to 16

**Comment by rom1v** [comment]
No: #98

**Comment by zzx-the-neptune** [comment]
No android 4? this project is worthless for android 4 users
