### ISSUE TITLE
USB/OTG bug 

### ISSUE THREAD

**Issue by Sigmacringe** [Genymobile/scrcpy#3087]
- [x ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues), and only found similar bug on windows.

**Environment**
 - Linux mint 20.3 una 64bit Kernel Linux 5.4.0-100-generic x86_64
 - scrcpy version: 1.23 snap
 - installation method: sudo snap install scrcpy
 - device model: Redmi note 5 pro (whyred)
 - Android version:  9 pie, lineage OS, root

Otg option not working properly, and the -M (--hid-mouse) doesn`t work either.
scrcpy --otg
scrcpy 1.23 <https://github.com/Genymobile/scrcpy>
ERROR: Could not find any USB device

**Comment by rom1v** [comment]
Try with a non-snap version.

**Comment by Sigmacringe** [comment]
well the .deb version avaliable on the store is so old that it doesn`t even have OTG or HID, i actually moved from .dep to snap in order to try this feature.

**Comment by rom1v** [comment]
Install the latest version manually: https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple

**Comment by Sigmacringe** [comment]
It`s working fine, sorry for the incovenience i didn`t knew how to build so i did not even tried. Anyway, thanks.
