### ISSUE TITLE
error while playing video

### ISSUE THREAD

**Issue by bkchn** [Genymobile/scrcpy#309]
Getting below error while playing some videos
"unable to instantiate decoder omx.qcom.video.decoder.avc"

**Comment by rom1v** [comment]
Which device? Which Android version?

**Comment by bkchn** [comment]
> 
> 
> Which device? Which Android version?

Lenovo A6020a46 (Lenovo vibe k5 plus)
Android 5.1.1

**Comment by bkchn** [comment]
> 
> 
> > Which device? Which Android version?
> 
> Lenovo A6020a46 (Lenovo vibe k5 plus)
> Android 5.1.1

If i already run the video on the phone and then start scrcpy ,then below error at command line of windows


D:\Program Files\scrcpy-win64>scrcpy.exe
scrcpy-server.jar: 1 file pushed. 1.1 MB/s (18802 bytes in 0.016s)
ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:580)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:126)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:62)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:24)
        at com.genymobile.scrcpy.Server.main(Server.java:102)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
ERROR: Could not open video stream
INFO: Initial texture: 1920x1080
Press any key to continue...

**Comment by rom1v** [comment]
I guess your hardware is not able to do both (record the screen and play a video).

**Comment by bkchn** [comment]
> 
> 
> Try to reduce the definition:
> 
> ```
> scrcpy -m 1280
> scrcpy -m 800
> ```

Hey ..this worked..Great

**Comment by bkchn** [comment]
Is it possible to play the audio as well on PC?

**Comment by rom1v** [comment]
See https://github.com/Genymobile/scrcpy/issues/14.

**Comment by bkchn** [comment]
> 
> 
> See #14.

Is this available in scrcpy-win32-v1.4.zip or scrcpy-win364-v1.4.zip  version?

**Comment by bkchn** [comment]
> 
> 
> > Try to reduce the definition:
> > ```
> > scrcpy -m 1280
> > scrcpy -m 800
> > ```
> 
> Hey ..this worked..Great

what is the max definition supported?

**Comment by bkchn** [comment]
Closing the issue as reducing the definition worked... Thanks to rom1v
