### ISSUE TITLE
Remote device control

### ISSUE THREAD

**Issue by FlashPlayer13** [Genymobile/scrcpy#3091]
Hi!

I have a problem with setup remote scrcpy access with two Windows 10 machines. I have read readme file and googled  how to configure adb tunnel but no luck and looking for help.

My setup is simple. Two Windows 10 machines in local network. PC1 (192.168.1.1) has connected android device and i want to use scrcpy with it on PC2 (192.168.1.2). I can ping PCs back and forward (all firewalls are off)

I have downloaded scrcpy-win64-v1.23 archive on both PCs.

Now I setup server part like this (everyting like in tutorial):
- Open PowerShell in scrcpy-win64-v1.23 directory from archive
- ./adb kill-server
- ./adb -a nodaemon server start
- Left this console as is

Next is a client side. And here i already have problems:
- Open PowerShell in scrcpy-win64-v1.23 directory from archive
- ./adb kill-server
- export ADB_SERVER_SOCKET=tcp:192.168.1.1:5037      # this line doesn't work as export is unknown command. so i tried to replace 'export' with 'set'
- ./scrcpy --tunnel-host=192.168.1.1

And after this commands on client side i got this output:
```
scrcpy 1.23 <https://github.com/Genymobile/scrcpy>
INFO: Tunnel host/port is set, --force-adb-forward automatically enabled.
* daemon not running; starting now at tcp:5037
* daemon started successfully
ERROR: Could not find any ADB device
ERROR: Server connection failed
```

And that's all. I have no idea where to dig further. Hope for help.

**Comment by rom1v** [comment]
> export ADB_SERVER_SOCKET=tcp:192.168.1.1:5037 # this line doesn't work as export is unknown command. so i tried to replace 'export' with 'set'

```bash
# in bash
export ADB_SERVER_SOCKET=tcp:192.168.1.1:5037
```

```cmd
:: in cmd
set ADB_SERVER_SOCKET=tcp:192.168.1.1:5037
```

```powershell
# in PowerShell
$env:ADB_SERVER_SOCKET = 'tcp:10.0.2.2:5037'
```

(I didn't know about the PowerShell syntax)
