### ISSUE TITLE
I think use hevc encode format is better 

### ISSUE THREAD

**Issue by miku111** [Genymobile/scrcpy#3092]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
Server can use hevc as default encod format. Because it can provide better video quality as same bitrate compare to h.264.

**Comment by slimsymphony** [comment]
Most of Android devices doesn't support HEVC hardware encode, so H.264 is more compatible solution.

**Comment by rom1v** [comment]
Sure, you can.

You could even make it optional and submit a PR :)

**Comment by miku111** [comment]
> 

I think I can edit it and build it for myself,I am wrong,I am too noob to edit it.
Maybe several years after,it can use hevc to be default encod format.

**Comment by berryboy2012** [comment]
I tried monkey-patch the code to use hevc, and it seemed to work quite well. Unfortunately, I don't have much time atm, so I cannot submit a proper PR. For anyone interested, here are the key changes in my attempt:

`server\src\main\java\com\genymobile\scrcpy\ScreenEncoder.java`:
>Change all `MediaFormat.MIMETYPE_VIDEO_AVC` to `MediaFormat.MIMETYPE_VIDEO_HEVC`;

`app\src\demuxer.c`:
>Change all `AV_CODEC_ID_H264` to `AV_CODEC_ID_H265`;

Screenshot:
![图片](https://user-images.githubusercontent.com/1946891/167286742-2b32cc7a-212d-471f-8e36-8e68c32e0921.png)

Cheers.

**Comment by rom1v** [comment]
There should definitely be an option to select the codec (`--codec=h265`). AV1 should also be available (but currently, less devices support it).

I tested with a OnePlus 7 Pro, it works, but the latency is way worse than with H.264 (I started two instances of scrcpy side-by-side, one with h264 and one with h265). It might have improved on newer devices though.

The quality at low bitrate (`-b1M`) is slightly improved, but still not great.

<details><summary>diff</summary>

```diff
diff --git a/app/src/demuxer.c b/app/src/demuxer.c
index 35ea4c06..00f8e5ed 100644
--- a/app/src/demuxer.c
+++ b/app/src/demuxer.c
@@ -173,7 +173,7 @@ static int
 run_demuxer(void *data) {
     struct sc_demuxer *demuxer = data;
 
-    const AVCodec *codec = avcodec_find_decoder(AV_CODEC_ID_H264);
+    const AVCodec *codec = avcodec_find_decoder(AV_CODEC_ID_H265);
     if (!codec) {
         LOGE("H.264 decoder not found");
         goto end;
@@ -190,7 +190,7 @@ run_demuxer(void *data) {
         goto finally_free_codec_ctx;
     }
 
-    demuxer->parser = av_parser_init(AV_CODEC_ID_H264);
+    demuxer->parser = av_parser_init(AV_CODEC_ID_H265);
     if (!demuxer->parser) {
         LOGE("Could not initialize parser");
         goto finally_close_sinks;
diff --git a/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java b/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java
index e95896d3..3924d5de 100644
--- a/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java
+++ b/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java
@@ -205,7 +205,7 @@ public class ScreenEncoder implements Device.RotationListener {
         List<MediaCodecInfo> result = new ArrayList<>();
         MediaCodecList list = new MediaCodecList(MediaCodecList.REGULAR_CODECS);
         for (MediaCodecInfo codecInfo : list.getCodecInfos()) {
-            if (codecInfo.isEncoder() && Arrays.asList(codecInfo.getSupportedTypes()).contains(MediaFormat.MIMETYPE_VIDEO_AVC)) {
+            if (codecInfo.isEncoder() && Arrays.asList(codecInfo.getSupportedTypes()).contains(MediaFormat.MIMETYPE_VIDEO_HEVC)) {
                 result.add(codecInfo);
             }
         }
@@ -222,7 +222,7 @@ public class ScreenEncoder implements Device.RotationListener {
                 throw new InvalidEncoderException(encoderName, encoders);
             }
         }
-        MediaCodec codec = MediaCodec.createEncoderByType(MediaFormat.MIMETYPE_VIDEO_AVC);
+        MediaCodec codec = MediaCodec.createEncoderByType(MediaFormat.MIMETYPE_VIDEO_HEVC);
         Ln.d("Using encoder: '" + codec.getName() + "'");
         return codec;
     }
@@ -246,7 +246,7 @@ public class ScreenEncoder implements Device.RotationListener {
 
     private static MediaFormat createFormat(int bitRate, int maxFps, List<CodecOption> codecOptions) {
         MediaFormat format = new MediaFormat();
-        format.setString(MediaFormat.KEY_MIME, MediaFormat.MIMETYPE_VIDEO_AVC);
+        format.setString(MediaFormat.KEY_MIME, MediaFormat.MIMETYPE_VIDEO_HEVC);
         format.setInteger(MediaFormat.KEY_BIT_RATE, bitRate);
         // must be present to configure the encoder, but does not impact the actual frame rate, which is variable
         format.setInteger(MediaFormat.KEY_FRAME_RATE, 60);
```

</details>
