### ISSUE TITLE
How to run the Scrcpy without attaching it to the Terminal.

### ISSUE THREAD

**Issue by sumanabhi** [Genymobile/scrcpy#3094]
- [x] I have check the already raised issue regarding this. Issue [#2282](https://github.com/Genymobile/scrcpy/issues/2282)

but the same command is not working for the latest MAC.

I tried `scrcpy &` and `scrcpy & exit` as well. but hard luck.

as of current scenario, Any helpful command should be there. if there's any then it should be somewhere in the Readme.md or FAQ.

**Comment by TheRafaelFarias** [comment]
For me on zsh and gnome terminal ``scrcpy >& /dev/null & exit`` works

**Comment by sumanabhi** [comment]
It got worked for me as well.

but I think it should be mentioned somewhere in the Readme file.

**Comment by TheRafaelFarias** [comment]
After some research

``scrcpy >& /dev/null & disown`` works, it still prints the PID but detach the process from the terminal

**Comment by sumanabhi** [comment]
Thanks a lot, It is working as expected.
