### ISSUE TITLE
Delay turning screen on Redmi

### ISSUE THREAD

**Issue by iqfareez** [Genymobile/scrcpy#3097]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 11
 - scrcpy version: 1.23
 - installation method: Windows release
 - device model: Redmi Note 11 - MIUI 13
 - Android version: 11

**Describe the bug**

When turning on screen using keyboard shortcut (<kbd>alt</kbd>+<kbd>shift</kbd>+<kbd>o</kbd>), the device turns on after 10 seconds (approx - no exact timing). The output from the console however shows ouput correctly (`[server] INFO: Device screen turned on`)

Meanwhile, turning screen off is responding instantaneous. 

Only happen with this device, no similar issues on other devices i own.

```
C:\Users\Iqmal>scrcpy -Sw
scrcpy 1.23 <https://github.com/Genymobile/scrcpy>
C:\Program Files\scrcpy-win64\scrcpy-s...pped. 0.7 MB/s (41123 bytes in 0.059s)
[server] INFO: Device: Xiaomi 2201117TG (Android 11)
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0xfffffff4
[server] INFO: Retrying with -m1920...
[server] INFO: Device screen turned off
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
INFO: New texture: 864x1920
[server] INFO: Device screen turned on
[server] INFO: Device screen turned off
[server] INFO: Device screen turned on
[server] INFO: Device screen turned off
[server] INFO: Device screen turned on
[server] INFO: Device screen turned off
[server] INFO: Device screen turned on
```

**Comment by rom1v** [comment]
Scrcpy requests to change the "power mode". How it is handled and implemented is device/rom-specific.

**Comment by rom1v** [comment]
> However, are there any device settings that I can change to fix the issue?

I don't know. ¯\_(ツ)_/¯
