### ISSUE TITLE
--window-height&width don't work with the otg mode window

### ISSUE THREAD

**Issue by nothingshiru** [Genymobile/scrcpy#3099]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: 1.23
 - installation method: Windows release
 - device model: Huawei Matepad 10.4
 - Android version: 10

**Describe the bug**
As the window needs to be on top, I expect it to be small. 
I used `scrcpy --otg --always-on-top --window-width 40 --window-height 40`, and tried different values, but the window size doesn't change at all.

**Comment by rom1v** [comment]
The `--window-width` and `--window-height` options are currently specific to the mirroring window (i.e. not the OTG window, which is always 256×256).

You could submit a PR.

**Comment by nothingshiru** [comment]
> You could submit a PR.

I don't got the skill...

**Comment by nothingshiru** [comment]
What should I do now?
