### ISSUE TITLE
Implement a Substratum Andromeda-like service

### ISSUE THREAD

**Issue by fonix232** [Genymobile/scrcpy#31]
While I understand that this might be a bit out-of-scope, I think the approach the Substratum team took for Andromeda is something that could be implemented for scrcpy.

What Andromeda does is basically launching a service that keeps the `app_process` instance alive, providing a continuously running interface for ADB commands. This of course poses a security risk, but the service itself could be limited to an extent.

This way the screen capturing can be done easily in a controlled environment (the `app_process` service would have two functions, one to start the stream and one to stop), an app could be written that handles connection, and it could work through not just ADB, but through a (local) wireless network connection too.

**Comment by rom1v** [comment]
Thank you for sharing your ideas.

> What Andromeda does is basically launching a service

So it requires to install an APK?

> that keeps the `app_process` instance alive, providing a continuously running interface for ADB commands. This of course poses a security risk

Indeed, it looks very dangerous to me.

> This way the screen capturing can be done easily in a controlled environment

If an APK is required, why not using the [`MediaProjection`](https://developer.android.com/reference/android/media/projection/MediaProjection.html) API, instead? It requests a user permission, but it sounds safer.

And what would be the benefits?

> but through a (local) wireless network connection too

For supporting wireless network connection, I think it is easier to just make it work over [`adb connect`](https://github.com/Genymobile/scrcpy/issues/5).

> this might be a bit out-of-scope

Yes, that's a whole new project. ;-) So I'm closing the issue.

**Comment by fonix232** [comment]
> So it requires to install an APK?

Yes and no. Andromeda does use an installed app and gives it adb shell access by launching a whole new instance of the app:

    pkg=$($ROOT/$ADB pm path projekt.andromeda)
    am force-stop projekt.substratum
    appops set projekt.andromeda RUN_IN_BACKGROUND allow
    appops set projekt.substratum RUN_IN_BACKGROUND allow
    CLASSPATH=$pkg app_process /system/bin --nice-name=andromeda projekt.andromeda.Andromeda

However this can be done via any dex file, including the dex file created by `scrcpy`. This could then keep the service alive until reboot of the device.

> Indeed, it looks very dangerous to me.
>If an APK is required, why not using the MediaProjection API, instead? It requests a user permission, but it sounds safer.
>And what would be the benefits?

As long as you limit the functionality your running "service" can do, it should be safe enough. But yes, safety is a concern, to what the MediaProjection API would be a solution. 

In my experience the MediaProjection API adds lots of overhead compared to your solution, which is not a surprise - it's a managed solution to capture screen data, usually only used for screen recording, and not for live streaming the device screen. There's a reason why Samsung's own SideSync uses a pretty similar approach for casting the screen (albeit doesn't even come close to scrcpy's performance).

Benefits would be considerably better performance, lesser battery usage (due to better performance).

> For supporting wireless network connection, I think it is easier to just make it work over adb connect.

As long as you want to keep the project adb-only, yes. If this solution were to be expanded into a full-fledged solution, I think further, more user-friendly options should be added. However I understand that you might not wish to go this way with scrcpy.
