### ISSUE TITLE
scrcpy --hid-keyboard scrcpy: unrecognized option '--hid-keyboard'

### ISSUE THREAD

**Issue by edgeclock** [Genymobile/scrcpy#3102]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

 - OS: [Ununtu 20.04]
 - scrcpy version: [1.12.1]
 - installation method: [snap]
 - device model: POCO X3 Pro
 - Android version: [11]

The normal scrcpy code when used on terminal functions normally but when I try to access scrcpy --hid-keyboard or scrcpy --hid-mouse it will show unrecognized option. Im new to this anyone can help on what should I do to make it function.

```
scrcpy: unrecognized option '--hid-keyboard'
```

**Comment by rom1v** [comment]
Upgrade to the latest version: https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple
