### ISSUE TITLE
How to stop installing and delete all relevant files

### ISSUE THREAD

**Issue by Ciel2444** [Genymobile/scrcpy#3107]
- [ yes] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [yes ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: macOS
 - scrcpy version:  10.13.6
 - installation method: brew

**Describe the bug**
Hi, I’m sorry for asking how to stop installing but I have installed it for more than 18 hours and is still making Rust, so I wanna stop the process and delete all relevant files, how can I do that?

Thank you

**Comment by Ciel2444** [comment]
It’s stop now,
“Error: You are using macOS 10.13.
We do not provide support for this old version…”
How can I delete and remove all relevant files?
Thank you for you reply

**Comment by Ciel2444** [comment]
Can I just uninstall Homebrew? Will it delete all relevant files about scrcpy?

**Comment by Ciel2444** [comment]
When I using this code “ sudo ninja -Cbuild-auto uninstall”
It says “ninja: fatal: chdir to ‘build-auto’ - No such file or directory”
😞😞😞😞

**Comment by Ciel2444** [comment]
Thank you, I have found the solution

**Comment by rom1v** [comment]
If you (attempted to) install via homebrew, you must uninstall via homebrew (if it failed, it is probably not installed).

It appears that Homebrew compiles the whole world when some conditions are not met, see #2256.

**Comment by rom1v** [comment]
> Thank you, I have found the solution

Then you should explain for the next people having the same problem…

**Comment by Ciel2444** [comment]
> 

Oh yeah, sorry I forgot.

If you want to uninstalling (mac brew), you can simply use command: brew list, and then: brew remove —force $(brew list —formula), after that, uninstall brew
