### ISSUE TITLE
adb: error: failed to get feature set: no devices/emulators found

### ISSUE THREAD

**Issue by bkchn** [Genymobile/scrcpy#311]
E:\Program Files\scrcpy-win32>scrcpy.exe
adb: error: failed to get feature set: no devices/emulators found
ERROR: "adb push" returned with value 1
Press any key to continue...

-----
PC: Windows 7 32 bit.
Mobile: Lenovo A6020a46
Android 5.1.1

**Comment by bkchn** [comment]
Issue resolved after installing the USB/ADB drivers in PC for the particular model of phone

**Comment by HesseSummer** [comment]
I faced the same problem, and solved it by i[nstalling and configuring adb driver](https://blog.csdn.net/ppggxn/article/details/81709350).
Ubuntu 18.04
