### ISSUE TITLE
App Lock screen in android 12 doesn't show in scrcpy

### ISSUE THREAD

**Issue by maijin20menso** [Genymobile/scrcpy#3117]
- OS: Windows 10
 - scrcpy version: 1.23
 - installation method: Windows release
 - device model: Xperia 5 II
 - Android version: 12

When using some application which have inapp security lock (suck as Telegram and Signal) which requires user to unlock before using the app, the screen will become blank in scrcpy, which I need to switch on the mobile screen and perform unlock action. After unlock action in those app, the screen streaming is resume.

The issue didn't occur using Android 11 (Same phone before update) and Android 9 (Xperia XZ1) which I used yesterday.

**Comment by rom1v** [comment]
That's expected, Android 12 removed the permission to capture protected scteens from shell. See #36 #2129.
