### ISSUE TITLE
IRotationWatcher.aidl is not found in Device.java

### ISSUE THREAD

**Issue by qaisbayabani** [Genymobile/scrcpy#3124]
public void registerRotationWatcher(**IRotationWatcher rotationWatcher**, int displayId) {
        serviceManager.getWindowManager().registerRotationWatcher(rotationWatcher, displayId);
    }
cant find irotation watcher

**Comment by rom1v** [comment]
How do you build?

**Comment by qaisbayabani** [comment]
public Device(Options options) {
        displayId = options.getDisplayId();
        DisplayInfo displayInfo = serviceManager.getDisplayManager().getDisplayInfo(displayId);
        if (displayInfo == null) {
            int[] displayIds = serviceManager.getDisplayManager().getDisplayIds();
            throw new InvalidDisplayIdException(displayId, displayIds);
        }

**Comment by qaisbayabani** [comment]
i am trying to merg your project with mine i have already made a modified Screen Capture Grafika Example to stream but it only work with the latest version of mobiles have capture feature your is working without it so this is the last exception i am having.

**Comment by qaisbayabani** [comment]
aganin that is a java file which was missing i have not coppied it thanx Succeeded

**Comment by qaisbayabani** [comment]
but run time assert exception

**Comment by rom1v** [comment]
Hi,

Please stop spamming the issue tracker with problems on your own project/build/fork.

Thank you.

**Comment by qaisbayabani** [comment]
its to rude to live person spam you could have told me that in activity i cant perform it. this can only work with shell app. hugs
