### ISSUE TITLE
Constant disconnects, both USB and TCP/IP modes

### ISSUE THREAD

**Issue by ajgringo619** [Genymobile/scrcpy#3125]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [EndeavourOS]
 - scrcpy version: [1.23]
 - installation method: [pacman]
 - device model: Samsung A13
 - Android version: [11]

**Describe the bug**
Since upgrading to v1.23, I'm getting constant disconnects with no indication as to why.

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
scrcpy 1.23 <https://github.com/Genymobile/scrcpy>
DEBUG: ADB device found:
DEBUG:     --> (tcpip)  samsung-a13:5555                device  SM_A136U1
DEBUG: Device serial: samsung-a13:5555
DEBUG: Using server: /usr/share/scrcpy/scrcpy-server
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 285.3 MB/s (41123 bytes in 0.000s)
[server] INFO: Device: samsung SM-A136U1 (Android 11)
DEBUG: Server connected
DEBUG: Starting controller thread
DEBUG: Starting receiver thread
[server] DEBUG: Using encoder: 'OMX.MTK.VIDEO.ENCODER.AVC'
INFO: Renderer: opengl
INFO: OpenGL version: 4.6.0 NVIDIA 470.103.01
INFO: Trilinear filtering enabled
DEBUG: Using icon: /usr/share/icons/hicolor/256x256/apps/scrcpy.png
INFO: Initial texture: 720x1600
DEBUG: Starting demuxer thread
DEBUG: End of frames
DEBUG: Receiver stopped
WARN: Device disconnected
DEBUG: quit...
DEBUG: Server disconnected
DEBUG: Server terminated
```
When these disconnects happen, I'm not actively using the app.

**Comment by rom1v** [comment]
> WARN: Device disconnected

This happens when the adb connection is closed.

For example, if you run `adb shell` or `adb logcat` in a separate terminal, they probably terminate at the same time.

There might be several causes:
 - a physical disconnection (USB unplug or poor cable for example, but unlikely in your case it also happens over wifi)
 - an adb server crash on the device (ROM bug)
 - an adb daemon disconnection (like `adb kill-server` or another process running another adb version)
 - …

Does it happen with another device?

**Comment by ajgringo619** [comment]
This never happened with my previous phone (Samsung A11). I _did_ find a bad USB cable in the mix, but this does not explain the disconnects with wireless. Overall, though, the disconnects have been less frequent since my last phone reboot.

The only other app that used `adb` was **Android Studio**, but I uninstalled it a while back.

**Comment by rom1v** [comment]
So it's probably a device issue.

**Comment by ajgringo619** [comment]
It could very well be.

How's this for not making sense? Since I changed the USB cable, my wireless connection has not dropped in well over an hour (no, the USB cable is not attached at the moment, either).

**Comment by ajgringo619** [comment]
I tried enabling **Wireless Debugging** (which my Samsung A11 phone did not have) and the connections seem to be more stable now. I think I can close this issue for now.

**Comment by rom1v** [comment]
> I tried enabling Wireless Debugging

A priori, it only changes the authentication part, it should have no impact on the stability of the connection itself.

**Comment by ajgringo619** [comment]
Thanks for that. I'm getting 12+ hours uninterrupted now, so I'll leave it.
