### ISSUE TITLE
Remote connection, multiple devices, error

### ISSUE THREAD

**Issue by Trimanat** [Genymobile/scrcpy#3128]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

 - OS: Server: Debian, Client Windows 10
 - scrcpy version: v1.23
 - installation method: Debian apt install, Windows release
 - device model: Nokia 5.4, Xiaomi 7A
 - Android version: Nokia 11, Xiaomi 12

When any, one device is connected, there are no errors, everything is connected, with the command
```
scrcpy.exe --tunnel-host=192.168.11.102 --window-title '13' -w -S -m 900 --max-fps 15 -s HZQL1849CAL******** --power-off-on-close
```
or
```
scrcpy.exe --tunnel-host=192.168.11.102 --window-title '13' -w -S -m 900 --max-fps 15 -s 048890****** --power-off-on-close
```

but as soon as I connect both devices at once on the server side
on the client, I see both devices
```
c:\scrcpy-win64>adb devices
List of devices attached
048890******    device
HZQL1849CAL********     device
```
but when trying to connect, to any of them errors
```
c:\scrcpy-win64>scrcpy.exe --tunnel-host=192.168.11.102 --window-title '13' -w -S -m 900 --max-fps 15 -s 048890****** --power-off-on-close
scrcpy 1.23 <https://github.com/Genymobile/scrcpy>
INFO: Tunnel host/port is set, --force-adb-forward automatically enabled.
c:\scrcpy-win64\scrcpy-server: 1 file pushed, 0 skipped. 20.9 MB/s (41123 bytes in 0.002s)
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27183, retrying on 27184
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27184, retrying on 27185
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27185, retrying on 27186
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27186, retrying on 27187
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27187, retrying on 27188
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27188, retrying on 27189
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27189, retrying on 27190
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27190, retrying on 27191
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27191, retrying on 27192
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27192, retrying on 27193
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27193, retrying on 27194
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27194, retrying on 27195
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27195, retrying on 27196
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27196, retrying on 27197
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27197, retrying on 27198
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27198, retrying on 27199
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
ERROR: Could not forward any port in range 27183:27199
ERROR: Server connection failed
```

Tried disabling the firewall on windows, didn't work.
Please help

**Comment by rom1v** [comment]
I could not reproduce.

I very surprised by `adb.exe: error: more than one device/emulator` here, since the serial is always passed for `adb forward`.

Could you try with this additional log, please?

```diff
diff --git a/app/src/adb/adb.c b/app/src/adb/adb.c
index 06090b46..eeccc577 100644
--- a/app/src/adb/adb.c
+++ b/app/src/adb/adb.c
@@ -224,6 +224,10 @@ sc_adb_forward(struct sc_intr *intr, const char *serial, uint16_t local_port,
     assert(serial);
     const char *const argv[] =
         SC_ADB_COMMAND("-s", serial, "forward", local, remote);
+    char cmd[1024];
+    sc_str_join(cmd, argv, ' ', sizeof(cmd));
+    cmd[sizeof(cmd)-1] = '\0';
+    LOGI("=== %s", cmd);
 
     sc_pid pid = sc_adb_execute(argv, flags);
     return process_check_success_intr(intr, pid, "adb forward", flags);
```

**Comment by Trimanat** [comment]
Sorry, I'm not that cool)
I don't understand how to apply what you wrote. Sorry

**Comment by rom1v** [comment]
Here is a binary, replace it in your v1.23 release:
 - [`scrcpy.exe`](https://tmp.rom1v.com/scrcpy/3128/1/scrcpy.exe) _sha256:eeec62707698e22dcede45197322151b344c69acba1c36c7607af6fec64f1222_

**Comment by Trimanat** [comment]
Ok, thanks
`
c:\scrcpy-win64>scrcpy.exe --tunnel-host=192.168.11.102 --window-title '13' -w -S -m 900 --max-fps 15 -s 048890****** --power-off-on-close
scrcpy 1.23 <https://github.com/Genymobile/scrcpy>
INFO: Tunnel host/port is set, --force-adb-forward automatically enabled.
c:\scrcpy-win64\scrcpy-server: 1 file pushed, 0 skipped. 0.7 MB/s (41123 bytes in 0.059s)
INFO: === adb -s 048890****** forward tcp:27183 localabstract:scrcpy
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27183, retrying on 27184
INFO: === adb -s 048890****** forward tcp:27184 localabstract:scrcpy
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27184, retrying on 27185
INFO: === adb -s 048890****** forward tcp:27185 localabstract:scrcpy
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27185, retrying on 27186
INFO: === adb -s 048890****** forward tcp:27186 localabstract:scrcpy
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27186, retrying on 27187
INFO: === adb -s 048890****** forward tcp:27187 localabstract:scrcpy
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27187, retrying on 27188
INFO: === adb -s 048890****** forward tcp:27188 localabstract:scrcpy
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27188, retrying on 27189
INFO: === adb -s 048890****** forward tcp:27189 localabstract:scrcpy
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27189, retrying on 27190
INFO: === adb -s 048890****** forward tcp:27190 localabstract:scrcpy
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27190, retrying on 27191
INFO: === adb -s 048890****** forward tcp:27191 localabstract:scrcpy
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27191, retrying on 27192
INFO: === adb -s 048890****** forward tcp:27192 localabstract:scrcpy
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27192, retrying on 27193
INFO: === adb -s 048890****** forward tcp:27193 localabstract:scrcpy
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27193, retrying on 27194
INFO: === adb -s 048890****** forward tcp:27194 localabstract:scrcpy
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27194, retrying on 27195
INFO: === adb -s 048890****** forward tcp:27195 localabstract:scrcpy
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27195, retrying on 27196
INFO: === adb -s 048890****** forward tcp:27196 localabstract:scrcpy
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27196, retrying on 27197
INFO: === adb -s 048890****** forward tcp:27197 localabstract:scrcpy
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27197, retrying on 27198
INFO: === adb -s 048890****** forward tcp:27198 localabstract:scrcpy
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27198, retrying on 27199
INFO: === adb -s 048890****** forward tcp:27199 localabstract:scrcpy
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
ERROR: Could not forward any port in range 27183:27199
ERROR: Server connection failed`

**Comment by rom1v** [comment]
What is the result of:

```
adb -s 048890****** forward tcp:27183 localabstract:scrcpy
```
?

**Comment by Trimanat** [comment]
c:\scrcpy-win64>adb -s 048890****** forward tcp:27183 localabstract:scrcpy  
adb.exe: error: more than one device/emulator

**Comment by rom1v** [comment]
That's the problem. This command should not fail that way, you pass the serial explicitly.

Are you also connected via wifi to this device?

**Comment by Trimanat** [comment]
I don't know if this will help, but this command works
`c:\scrcpy-win64>adb -s 048890****** shell  

pine:/ $ exit`
No, the networks are different, the server is at the other end of the VPN channel.
If the devices did not work individually, I would think about routing. But if one of the devices is turned off, everything still works.

**Comment by rom1v** [comment]
Looks like an adb bug (since you can reproduce without scrcpy), but I could not reproduce, so it's probably a bug in the adb server on your device. Could you try with a completely different device?

**Comment by Trimanat** [comment]
tried downloading the latest version
It was
`c:\scrcpy-win64>adb version  
Android Debug Bridge version 1.0.41  
Version 31.0.3-7562133  
Installed as c:\scrcpy-win64\adb.exe`
became
`c:\scrcpy-win64>adb version  
Android Debug Bridge version 1.0.41  
Version 33.0.1-8253317  
Installed as c:\scrcpy-win64\adb.exe`
result has not changed
Which side is the other device?
Change server or client?

**Comment by Trimanat** [comment]
Thank you very much, I fixed it, thanks to you!
The problem was in the installed version of adb from the Debian repositories, I downloaded the latest ones from the Google site, launched them and everything worked as it should!

**Comment by rom1v** [comment]
> The problem was in the installed version of adb from the Debian repositories

What was the version?

**Comment by Trimanat** [comment]
```
Android Debug Bridge version 1.0.41
Version 28.0.2-debian
```
became
```
Android Debug Bridge version 1.0.41
Version 33.0.1-8253317
```

**Comment by rom1v** [comment]
OK, weird that it did not work correctly.
