### ISSUE TITLE
ERROR: Server connection failed

### ISSUE THREAD

**Issue by vikdevelop** [Genymobile/scrcpy#3129]
Desktop OS: Manjaro Linux
Mobile OS: Android 11
Output:
```bash
~$ scrcpy                                                                            
scrcpy 1.23 <https://github.com/Genymobile/scrcpy>
ERROR: Server connection failed
```
What should I do?

**Comment by rom1v** [comment]
Could you execute `scrcpy -Vdebug`?

What is the result of `adb devices`? How did you install scrcpy?

**Comment by vikdevelop** [comment]
@rom1v 

> Could you execute `scrcpy -Vdebug`?
> 
> What is the result of `adb devices`? How did you install scrcpy?


1. Output is the same as when running command `scrcpy`.
2. Output of command `adb devices` is:
````bash
List of devices attached
OFGUW4RWWSWSMFBI        no permissions; see [http://developer.android.com/tools/device.html]
````
3. I installed scrcpy with Pacman (sudo pacman -S scrcpy)

**Comment by korewaChino** [comment]
Same Issue here, Fedora 36.

**Comment by rom1v** [comment]
> no permissions

That's the problem. Probably udev rules issues.

However, scrcpy should print a relevant error message.

> Have you tried restarting the ADB server as root

(no, you should never run adb or scrcpy as root)

**Comment by rom1v** [comment]
What is the result of `adb devices -l` please?

**Comment by vikdevelop** [comment]
it's working fine now, thanks!  :)

**Comment by ImALoooserOk** [comment]
@vikdevelop how exactly did you get it to work? I'm having the same problem here
