### ISSUE TITLE
While scrcpy is running disable charging option

### ISSUE THREAD

**Issue by n3rd4i** [Genymobile/scrcpy#3138]
**Is your feature request related to a problem? Please describe.**
While using `scrcpy` device is charging up to 100%. This affects battery life.

**Describe the solution you'd like**
While using `scrcpy` (and ofc device is USB-C plugged) allow user [somehow] to stop charging android device and/or @ 80% stop charging for the session duration by command line argument of `scrcpy`.

**Describe alternatives you've considered**
`adb` commands to achieve the same goals, if possible.

**Comment by tschaerni** [comment]
that depends on the phones/tablets firmware
some ROMs have something like that already implemented, but almost all need to be modified and/or rooted to do so.

I wish something like that would be a core feature of android, but sadly it's not :/

**Comment by sportniik** [comment]
Constant current can completely destroy a battery. But from what I found on web, root is required.

**Comment by klutt** [comment]
Bummer. I really wanted this feature.
