### ISSUE TITLE
Can't transfer files using drag and drop

### ISSUE THREAD

**Issue by Zeyadrizk** [Genymobile/scrcpy#314]
I can't transfer files using drag and drop, is there anything I can try to do?

**Comment by npes87184** [comment]
Hi, @Zeyadrizk 

Does your file path contain empty space?

Thanks,
yuchenlin

**Comment by rom1v** [comment]
@Zeyadrizk See https://github.com/Genymobile/scrcpy/issues/288

**Comment by Zeyadrizk** [comment]
@npes87184 @rom1v no it is: C:\Users\me\Desktop\Pdf\baroody2005.pdf

**Comment by rom1v** [comment]
OK, are there some lines in the console when you drag&drop it?

**Comment by Zeyadrizk** [comment]
@rom1v 
INFO: Installing C:\Users\me\Desktop\Pdf\patipa1992.pdf...
adb: usage: filename doesn't end .apk: C:\Users\me\Desktop\Pdf\patipa1992.pdf
ERROR: "adb install" returned with value 1

**Comment by Zeyadrizk** [comment]
Thanks! 💯
