### ISSUE TITLE
Application is turning black on PC

### ISSUE THREAD

**Issue by mdjenni** [Genymobile/scrcpy#3141]
- [x ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10, 20H2 (19042.1526)
 - scrcpy version: 1.21
 - installation method: Windows installation
 - device model: Samsung A52
 - Android version: 12

**Describe the bug**
Mirroring apps in general is working. There is a specific behavior with this app: Field Service (Dynamcis 365).
Mirroring the app on the A52 device, it blacks the app on the PC while on the device it is still running normally.
I've tried the app on other devices, all running well.
Has it to do with the screen resolution of A52 and how it's consumed by this specific app?

```
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
* daemon not running; starting now at tcp:5037
* daemon started successfully
C:\Program Files\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 1.3 MB/s (40067 bytes in 0.029s)
[server] INFO: Device: samsung SM-A525F (Android 12)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
```

<img width="861" alt="Screenshot 2022-03-22 092317" src="https://user-images.githubusercontent.com/102223891/159700969-5f34ef9a-a3a2-434f-9885-0c48f557dd56.png">

**Comment by rom1v** [comment]
This is expected on Android 12 for apps with "protected screen". See #36 and #2129.

**Comment by mdjenni** [comment]
also see https://github.com/Genymobile/scrcpy/issues/3072
