### ISSUE TITLE
Apps with a "disable screenshots" feature on don't display 

### ISSUE THREAD

**Issue by neurodiverseEsoteric** [Genymobile/scrcpy#3143]
This wasn't the case until today...The apps (silence and webapps, in my case) are running, as unplugging the phone reveals, but the scrcpy capture goes blank as soon as they are launched (can still interact with the app and andriod with mouse/keyboard, and the home/launcher screen still shows when backing out of the app)...

**Comment by rom1v** [comment]
This is expected since Android 12. See #36 #2129.

**Comment by neurodiverseEsoteric** [comment]
In other words, google has killed this project
