### ISSUE TITLE
[general] Privacy concerns with Discord

### ISSUE THREAD

**Issue by Lukas2112** [Genymobile/scrcpy#3144]
- [X] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
Privacy concerns. 

Discord scores very badly in terms of compliance with European data protection. 

1. company based in the USA operates the service discord
2. the service is proprietary licensed 
3. server infrastructure seems to be located only in the USA
4. Countless tracking mechanisms are built in.

**Describe the solution you'd like**
The use of decentralised and open source licensed services, such as Matrix or XMPP.

**Describe alternatives you've considered**
Instead of Discord, one could rely on a Matrix / XMPP room that bridges the other (either Matrix or XMPP).

**Additional context**

**Comment by rom1v** [comment]
How is it related to scrcpy?

**Comment by Lukas2112** [comment]
Oh, I just see that I must have made a mistake. Sorry for the inconvenience caused
