### ISSUE TITLE
Friend, hello!

### ISSUE THREAD

**Issue by SokratED** [Genymobile/scrcpy#3145]
Friend, hello!

Our team is working on the Sokrat marketplace - an application for iOS and Android! We are looking for a team of developers, and where to look for them if not in the popular Githab service! )
I won’t write much, if you are interested in becoming a member of a developing project, contact us using one of the links below!

iOS https://redirect.appmetrica.yandex.com/serve/99708109685061445

Android
android: https://redirect.appmetrica.yandex.com/serve/1108514430494260799

site
https://sokratinvest.ru/joboffer

telegram
https://t.me/sokratsupport

If you are not interested, then just download our application and look for knowledge for your skills. If you want to receive a personal grant for education, then write to us in any way that you use Githab and our specialist will agree on a personal grant especially for you!

Sorry to bother you, we didn't mean to invade your space so uninvited)

With best wishes, Sokrat.Team

**Comment by rom1v** [comment]
Sorry, this is not the right place for your advertisement.
