### ISSUE TITLE
Language/unicode 

### ISSUE THREAD

**Issue by lynrayy** [Genymobile/scrcpy#3146]
Can't change keyboard language from english to russian. When i trying to type, it typing english letters and sending errors to console
![image](https://user-images.githubusercontent.com/59417884/159884249-ee303ad3-aaf5-4cb1-8c96-ba1a53618898.png)

**Comment by rom1v** [comment]
Now, that's the correct repo (https://github.com/rom1v/sndcpy/issues/217), but as I answered: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#special-characters-do-not-work
