### ISSUE TITLE
Language/unicode

### ISSUE THREAD

**Issue by lynrayy** [Genymobile/scrcpy#3147]
Can't change keyboard language from english to russian. When i trying to type, it typing english letters and sending errors to console

_Since scrcpy v1.20 on Linux, it is possible to simulate a [physical keyboard](https://github.com/Genymobile/scrcpy/blob/master/README.md#physical-keyboard-simulation-hid) (HID)._
IT'S WINDOWS, NOT LINUX
![image](https://user-images.githubusercontent.com/59417884/159886412-5f4461ae-9563-4033-b912-a3ee039b4600.png)

**Comment by rom1v** [comment]
Please stop opening the same issue again and again. (#3146)

As explained on the FAQ, this is a limitation of Android for character injection.

**Comment by lynrayy** [comment]
Fix is not explained

**Comment by rom1v** [comment]
There is no fix.

**Comment by rom1v** [comment]
(duplicate of #37)

**Comment by lynrayy** [comment]
Lol
It's beause you all using ascii for some reason

**Comment by lynrayy** [comment]
_(duplicate of https://github.com/Genymobile/scrcpy/issues/37)_
Uh ok
