### ISSUE TITLE
Option to power-off at start

### ISSUE THREAD

**Issue by madduck** [Genymobile/scrcpy#3148]
- [X] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

I have a device permanently living next to my computer, and I use the systemd integration from #3101, so basically I always have scrcpy running. Unless I power-off (Alt-P), scrcpy will occupy the CPU all time (#3112). I am looking for an option that automatically hits the power button after connection, similarly to how `--turn-screen-off` just turns the device screen off. This would allow auto-connection, but without involving the CPU too much until I need to interact.

Thanks!

**Comment by rom1v** [comment]
In fact, unless `--no-control` is enabled, the server [explicitly power the device screen on](https://github.com/Genymobile/scrcpy/blob/adbe7908c6e05899d8c4a03cd5cbc10209e3d221/server/src/main/java/com/genymobile/scrcpy/Controller.java#L58-L70) on start. An option `--no-power-on` could be added.

Do you want to work on it?

**Comment by madduck** [comment]
@rom1v this does indeed look like it should be easy to do, but those are famous last words… I haven't done Java in more than 2 decades, and I've never actually developed for Android, I wouldn't even know how to test this… or are there any easy resources I can peruse to get me started?

**Comment by rom1v** [comment]
You need to add a command line option, and propagate it to the server. It's very similar to ccbe370cc52c5cd4315aec0d153b4108e6237498 which adds the `--no-cleanup` option.

In addition, you should also add the option in bash-completion and zsh-completion scripts, which were written after `--no-cleanup`.

**Comment by rom1v** [comment]
I implemented it: #3210. Please review/test.

**Comment by madduck** [comment]
@rom1v Sorry I have not responded earlier. I'm in the process of moving to another country, so there's lot in the air.

I've just tested this, and it seems to work beautifully. Thank you!

**Comment by madduck** [comment]
FYI, it does not work with a Google Pixel 3 with stock ROM. `power_on=false` is correctly sent to the server, but the display does power on…

**Comment by madduck** [comment]
No, if the display is off, then it works. I see where the problem is:

1. Plug in USB;
2. Screen powers on;
3. udev fires scrcpy rule;
4. scrcpy starts, while display is on.

The Samsung Galaxy S7 and the OnePlus 5T do not turn the display on when USB is connected, so that is the difference. Sorry for the noise.
