### ISSUE TITLE
Can't use scrcpy after setting path

### ISSUE THREAD

**Issue by usernamesarelreadytaken** [Genymobile/scrcpy#315]
After I follow this https://github.com/Genymobile/scrcpy/issues/105, I still can't use scrcpy. I will explain it here hope someone can fix it for me. (I use scrcpy-win64-v1.4 prebuilt version for windows to mirror Oculus Go to notebook)
1. I try to set path of scrcpy as shown below 
![1](https://user-images.githubusercontent.com/8075102/47707125-984c3300-dc5d-11e8-909c-11df71e95cd3.png)
2. My directory contain as follows
![2](https://user-images.githubusercontent.com/8075102/47707443-64bdd880-dc5e-11e8-8658-5d917c3d2d89.png)
3. I can run adb and scrcpy -h without problem.
![3](https://user-images.githubusercontent.com/8075102/47707562-c1b98e80-dc5e-11e8-8f96-fce5c1daa79d.png)
![4](https://user-images.githubusercontent.com/8075102/47707632-e4e43e00-dc5e-11e8-8f5c-54f3aa54aef2.png)
5. But when i run scrcpy, it shows as follow
![5](https://user-images.githubusercontent.com/8075102/47707694-0b09de00-dc5f-11e8-8cad-da103ea5a3f9.png)
6. Also when I go scrcpy directory, I can run it without any problem.
![6](https://user-images.githubusercontent.com/8075102/47707824-558b5a80-dc5f-11e8-9327-177a6b324f67.png)

Sorry for messing issue by closing and reopening it, I am newbie about Github.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/issues/278#issuecomment-429330345

**Comment by usernamesarelreadytaken** [comment]
@rom1v  Thanks for your respond.

I am understand what cause the problem now by reading this paragraph.
>The problem is that scrcpy pushes the scrcpy-server.jar that it finds in . (your current directory). If you start scrcpy from PATH, it expects scrcpy-server.jar to be in ., i.e. the current directory, the one from where you call (the Windows version is "portable", it overrides the server path).

But sorry I am dump. I don't know how to set SCRCPY_SERVER_PATH. Does it look like this one (For my case) ??
![8](https://user-images.githubusercontent.com/8075102/47712588-b40a0600-dc6a-11e8-8a2a-b189c3a5d080.png)

**Comment by rom1v** [comment]
The variable value should be `D:\Supavit\scrcpy\scrcpy-server.jra`.

**Comment by usernamesarelreadytaken** [comment]
@rom1v  Thanks I will try it. I don't have that android with me now.

**Comment by usernamesarelreadytaken** [comment]
It is solved now.
