### ISSUE TITLE
Minimum requierments for linux

### ISSUE THREAD

**Issue by andreivlad9001** [Genymobile/scrcpy#3150]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Lubuntu 21.10, windows 10 1511
 - scrcpy version: 1.17.1
 - installation method: apt, from Github(for windows)
 - device model: samsung galaxy s9
 - Android version: 12
 -PC: Packard Bell Dot se 106 it (processor intel atom n450, intel gma 3150(it supports opengl 1.5 but a few things from the 2.1),2gb ram ddr2)

What would the minimum system requirements and drivers support for the computer be?

Such as open gl minimum version, because it doesn't display the phone screen properly, only black, but I can interact with the mouse and keyboard.
Also, I installed it on w10 (because I dualboot it) and it works flawlessly on that.

**Comment by andreivlad9001** [comment]
No, the video recorded is not black.

**Comment by rom1v** [comment]
OK, so indeed there is a problem with your graphics drivers. There are no really minimal requirements.

**Comment by rom1v** [comment]
Does it work with `scrcpy --render-driver=software`? (even if the quality/performance is poor)

**Comment by andreivlad9001** [comment]
Yeah, this igpu should have been better supported on linux, but it is not. Thanks for the help.

**Comment by andreivlad9001** [comment]
> Does it work with `scrcpy --render-driver=software`? (even if the quality/performance is poor)

Yes, it works, sorry i didn't see the question, i'm from the phone.
