### ISSUE TITLE
scrcpy constantly forgets my phone

### ISSUE THREAD

**Issue by Jacob-Darka** [Genymobile/scrcpy#3152]
Hello,

The way I connect scrcpy to my phone is like the following:
1. Connect to USB
2. adb tcpip 5555
3. Remove from USB
4. adb connect 192.168.1.99 [A static IP I made in my phone's wifi settings]

And like that, I can easily connect scrcpy to my phone with these lines without connecting to USB using:
1. adb tcpip 5555
2. scrcpy %Options%

It works fine for a few hours, then when I try to connect again afterwards I get this:

```
D:\Programs\scrcpy>adb tcpip 5555
error: no devices/emulators found

D:\Programs\scrcpy>adb connect 192.168.1.99
cannot connect to 192.168.1.99:5555: A connection attempt failed because the connected party did not properly respond after
a period of time, or established connection failed because connected host has failed to respond. (10060)

D:\Programs\scrcpy>adb devices
List of devices attached
*empty*
```

The only way I found to get around this error and get my phone connected again is by reapplying the steps I mentioned at the beginning, i.e. by connecting to USB again. Of course, this solution only fixes the problem for a few hours until scrcpy forgets my phone again.

Is there a way to make scrcpy remember my phone for a longer period of time?

Thanks.

**Environment**
 - OS: Windows 10
 - scrcpy version: 1.23
 - installation method: Windows release
 - device model: Oppo
 - Android version: 10

**Comment by rom1v** [comment]
It's not scrcpy, it's adb.

However, only the connect step should be performed again, `adb tcpip` should be kept by the device.

Btw, scrcpy has a feature to automate these steps: https://github.com/Genymobile/scrcpy#tcpip-wireless

The first time, plug the device, then:

```
scrcpy --tcpip
```

For further connections:

```
scrcpy --tcpip=192.168.1.99
```

**Comment by Jacob-Darka** [comment]
I'll use that and see how it goes, thanks **rom1v**.

**Comment by Jacob-Darka** [comment]
Hey again @rom1v, I wanted to update this issue and confirm that it's fixed after following your instructions, thank you very much.
