### ISSUE TITLE
are there any way to pipe scrcpy raw data to ffmpeg ? 

### ISSUE THREAD

**Issue by kcubeterm** [Genymobile/scrcpy#3156]

**Comment by rom1v** [comment]
Just use the server to send raw H.264 to a socket. See https://code.videolan.org/rom1v/vlc/-/merge_requests/20

**Comment by kcubeterm** [comment]
Thanks that is what I want

**Comment by hogantan** [comment]
Hi sorry but may I know how exactly to do so? 

I am not so sure how to pipe to ffmpeg after looking at the link.
