### ISSUE TITLE
-Sw not functioning correctly over TCP/IP

### ISSUE THREAD

**Issue by Motordom** [Genymobile/scrcpy#3159]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - **OS:** Windows 10 21H2
 - **scrcpy version:** 1.23
 - **Installation method:** Windows release
 - **Device model:** Samsung Galaxy Note 3 SM-N9005
 - **Android version:** 11

**Describe the bug**
The [-Sw flag](https://github.com/Genymobile/scrcpy#turn-screen-off) to turn the screen off but keep the device awake it not working as expected over TCP/IP.

When connecting over USB the flag turns the screen off and keeps the device awake as expected.
When connecting over TCP/IP the flag turns the screen off but does not keep the device awake (it goes to sleep and displays a black screen after a few seconds).

**Terminal outputs**

Connection via USB
````
C:\>scrcpy -Sw --power-off-on-close
scrcpy 1.23 <https://github.com/Genymobile/scrcpy>
C:\werk\scrcpy-win64-v1.23\scrcpy-server: 1 file pushed, 0 skipped. 47.6 MB/s (41123 bytes in 0.001s)
[server] INFO: Device: samsung SM-N9005 (Android 11)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x1920
[server] INFO: Device screen turned off
````

Connection via TCP/IP
````
C:\>scrcpy -Sw --tcpip=192.168.0.79:33205 --power-off-on-close
scrcpy 1.23 <https://github.com/Genymobile/scrcpy>
INFO: Connecting to 192.168.0.79:33205...
INFO: Connected to 192.168.0.79:33205
C:\werk\scrcpy-win64-v1.23\scrcpy-server: 1 file pushed, 0 skipped. 35.8 MB/s (41123 bytes in 0.001s)
[server] INFO: Device: samsung SM-N9005 (Android 11)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x1920
[server] INFO: Device screen turned off
````

**Comment by rom1v** [comment]
That's "expected". See #1445.
