### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by SyncMaster93** [Genymobile/scrcpy#3161]
i think this never happend to anyone not even me but theres first time for everything!

https://www.tiktok.com/@xwrckrggx/video/7081160974383729925?is_from_webapp=1&sender_device=pc&web_id=7064934178156168709

Can someone tell me whats the issue cuz im clearly stupid

**Comment by rom1v** [comment]
Which issue?

**Comment by SyncMaster93** [comment]
> Which issue?

the sound issue, whys choppy like that.. i use your scrcpy and aux for sound but this morning got all messed up and got me sound like in my tiktok video above

**Comment by rom1v** [comment]
Scrcpy does not forward sound, so the problem is not in scrcpy :smile: I don't know why you have this sound issue.

**Comment by SyncMaster93** [comment]
> Scrcpy does not forward sound, so the problem is not in scrcpy 😄 I don't know why you have this sound issue.

that be sick if **scrcpy** could do sound too, i know it dont..  _thought_ you had some knowledge on my **problem** but thanks 😄
