### ISSUE TITLE
Failed to execute: [adb], [start-server]

### ISSUE THREAD

**Issue by iknow4** [Genymobile/scrcpy#3167]
Hello, thanks for this amazing project.
When I use scrcpy as usual, but suddenly face an error.
Below is an error that appears when executing scrcpy.

**scrcpy 1.23 <https://github.com/Genymobile/scrcpy>
exec: Operation not permitted
2022-04-05 00:13:49.918 scrcpy[98301:1385587] ERROR: Failed to execute: [adb], [start-server]
2022-04-05 00:13:49.918 scrcpy[98301:1385587] ERROR: Could not execute "adb start-server"
2022-04-05 00:13:49.918 scrcpy[98301:1385587] ERROR: Could not start adb daemon
2022-04-05 00:13:50.318 scrcpy[98301:1385578] ERROR: Server connection failed**

And provide additional information:
adb devices -l 
List of devices attached
R5CR41CFS3B            device usb:338690048X product:o1qzcx model:SM_G9910 device:o1q transport_id:1

**Comment by rom1v** [comment]
Which platform? How did you install it?

**Comment by iknow4** [comment]
macOS version 12.2.1
I use Homebrew install it.

**Comment by Chaoyang0201** [comment]
I have same issue ,
macOS version 12.3.1 
brew install it

**Comment by rom1v** [comment]
What if you execute manually `adb start-server`?

**Comment by Chaoyang0201** [comment]
> What if you execute manually `adb start-server`?

Its OK,  all adb command can be execute mannually

**Comment by rom1v** [comment]
So it looks like a system restriction.

Maybe related to:
 - https://appletoolbox.com/seeing-error-operation-not-permitted-in-macos-mojave/
 - https://osxdaily.com/2018/10/09/fix-operation-not-permitted-terminal-error-macos/

?

**Comment by Chaoyang0201** [comment]
In my case , just config WRONG ADB  variable in  PATH  'xxxx/platform-tools/' .
I change to 'xxxx/platform-tools/adb' , its work

**Comment by iknow4** [comment]
> 
which file that you change the WRONG ADB path?

**Comment by iknow4** [comment]
> In my case , just config WRONG ADB variable in PATH 'xxxx/platform-tools/' .
> I change to 'xxxx/platform-tools/adb' , its work

which file that you change the WRONG ADB path?

**Comment by rom1v** [comment]
@iknow4 It seems that @Chaoyang0201 issue was not the same as yours, it assigned a wrong value to the `ADB` environment variable. You can check with `echo $ADB`.

> Failed to execute: [adb], [start-server]

 In you case, it is probably empty (`adb` without explicit path is the default value).

What is the result of `adb start-server` for you?

**Comment by iknow4** [comment]
> @iknow4 It seems that @Chaoyang0201 issue was not the same as yours, it assigned a wrong value to the `ADB` environment variable. You can check with `echo $ADB`.
> 
> > Failed to execute: [adb], [start-server]
> 
> In you case, it is probably empty (`adb` without explicit path is the default value).
> 
> What is the result of `adb start-server` for you?

From my side:
➜  ~ adb $ADB
Android Debug Bridge version 1.0.41
Version 29.0.5-5949299
Installed as /Users/user/Library/Android/sdk/platform-tools//adb

**Comment by iknow4** [comment]
<img width="254" alt="image" src="https://user-images.githubusercontent.com/7391445/161980199-e622e257-c41a-4f0d-9f61-942ec00c242c.png">

command: adb start-server   output nothing.

**Comment by iknow4** [comment]
> > From my side:
> > ➜ ~ adb $ADB
> 
> `echo $ADB`?

Sorry , when i execute  "echo $ADB"   also output nothing.

**Comment by rom1v** [comment]
OK, as expected, so go back to https://github.com/Genymobile/scrcpy/issues/3167#issuecomment-1090031152.

**Comment by Chaoyang0201** [comment]
> > In my case , just config WRONG ADB variable in PATH 'xxxx/platform-tools/' .
> > I change to 'xxxx/platform-tools/adb' , its work
> 
> which file that you change the WRONG ADB path?

I use zsh ，   ~/.zshrc

**Comment by Chaoyang0201** [comment]
> <img alt="image" width="688" src="https://user-images.githubusercontent.com/7391445/162001529-8dee2245-a5ae-4bf4-a2ea-3aedbdadedb4.png">
> 
> I also use zsh, change the config, but unfortunately, it's not work.

Maybe you can try add "adb" after `platform-tools/`

**Comment by iknow4** [comment]
yes, i did it like you say, but it does not work.

**Comment by iknow4** [comment]
Wow, it's work, thank you for you help!!!

**Comment by rom1v** [comment]
@iknow4 I'm surprised that `adb` (without an explicit path) works alone (which means that it's found in your path), but not via scrcpy.

What is the result of `which adb`?

**Comment by iknow4** [comment]
<img width="314" alt="image" src="https://user-images.githubusercontent.com/7391445/162007512-281c01d6-9f49-4bf2-bea4-fab74c3f9066.png">
here you go.

**Comment by rom1v** [comment]
Does it work:
```
ADB=/usr/local/bin/adb scrcpy
```
?

**Comment by iknow4** [comment]
have try, and seem it not work.

**Comment by rom1v** [comment]
If `/usr/local/bin/adb devices` works, then the command above should work too. It not, it's probably a restriction of your system.

**Comment by SNUyi** [comment]
> In my case , just config WRONG ADB variable in PATH 'xxxx/platform-tools/' . I change to 'xxxx/platform-tools/adb' , its work

yes, it works.

**Comment by FranzKafkaYu** [comment]
> In my case , just config WRONG ADB variable in PATH 'xxxx/platform-tools/' . I change to 'xxxx/platform-tools/adb' , its work

I have the same issue in Windows 10,and I fixed the ADB PATH variable by following this,now it works,thanks~

**Comment by rom1v** [comment]
On Windows, unless you want a very specific adb, you should not set the ADB environment variable at all.

**Comment by Fahimrahman582** [comment]
How to solve this problem on windows?

C:\scrcpy-win64-v2.4>scrcpy
scrcpy 2.4 <https://github.com/Genymobile/scrcpy>
ERROR: CreateProcessW() error 5
ERROR: Failed to execute: [C:\ADB], [start-server]
ERROR: Could not execute "adb start-server"
ERROR: Could not start adb server
ERROR: Server connection failed

**Comment by rom1v** [comment]
> ERROR: Failed to execute: [C:\ADB], [start-server]

Remove your `ADB` environment variable. You don't need to set it, and you set it to a wrong value (if t is set, it must point to the adb executable, not to the directory).

**Comment by dom-pan** [comment]
ERROR: CreateProcessW() error 5
ERROR: Failed to execute: [C:\Users\user\AppData\Local\Android\Sdk\platform-tools], [start-server]
ERROR: Could not execute "adb start-server"
ERROR: Could not start adb server
ERROR: Server connection failed

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/issues/3182#issuecomment-1097714741

**Comment by Sky-Sea-IOT** [comment]
> > ERROR: Failed to execute: [C:\ADB], [start-server]
> 
> Remove your `ADB` environment variable. You don't need to set it, and you set it to a wrong value (if t is set, it must point to the adb executable, not to the directory).

This is useful. I removed the environment variable for adb, and scrcpy used its own adb. Everything works fine now.

**Comment by Oyeetobjosh** [comment]
this is useful in 2025 delete variable and scrcpy will create itsown

**Comment by theSkyDown** [comment]
Why not design it to call the adb within the path? Otherwise, wouldn't I have to reconfigure the environment variables whenever I don't use scrcpy?

> > ERROR: Failed to execute: [C:\ADB], [start-server]
> 
> Remove your `ADB` environment variable. You don't need to set it, and you set it to a wrong value (if t is set, it must point to the adb executable, not to the directory).

**Comment by rom1v** [comment]
> Why not design it to call the adb within the path?

That's exactly what scrcpy does if you don't explicitly request to overwrite it using the `ADB` environment variable.

**Comment by MarcoT831** [comment]
Hello, 
i tried to launch scrcpy but got this error messages:
scrcpy 3.3.4 <https://github.com/Genymobile/scrcpy>
ERROR: CreateProcessW() error 2
ERROR: Command not found: [C:\Users\marco\Documents\mirroring schermo], [start-server]
ERROR: (make 'adb' accessible from your PATH or define its fullpath in the ADB environment variable)
ERROR: Could not execute "adb start-server"
ERROR: Could not start adb server
ERROR: Server connection failed

Can you help me? 
I think the adb is set properly

**Comment by theSkyDown** [comment]
> Hello, i tried to launch scrcpy but got this error messages: scrcpy 3.3.4 https://github.com/Genymobile/scrcpy ERROR: CreateProcessW() error 2 ERROR: Command not found: [C:\Users\marco\Documents\mirroring schermo], [start-server] ERROR: (make 'adb' accessible from your PATH or define its fullpath in the ADB environment variable) ERROR: Could not execute "adb start-server" ERROR: Could not start adb server ERROR: Server connection failed
> 
> Can you help me? I think the adb is set properly

This issue might occur if you have the adb path configured in your environment variables; that's what happened to me.

My solution was to run `$env:adb=$null` in PowerShell to temporarily remove adb from the configuration in that terminal, forcing scrcpy to run its own adb.

**Comment by rom1v** [comment]
> I think the adb is set properly

> ERROR: Command not found: [C:\Users\marco\Documents\mirroring schermo], [start-server]

No, it isn't.

Firstly, you should not set it at all. `adb` is shipped with the scrcpy release, and scrcpy uses it by default. So unset the `ADB` variable and it will work.

If you absolutely want to use another `adb` executable, then you must set it using the `ADB` environment variable, but it must set it to the executable, not its parent directly. In your case `C:\Users\marco\Documents\mirroring schermo\adb.exe` probably.

But again, just don't set `ADB`.

**Comment by MarcoT831** [comment]
I removed the adb, but now the error is:
ERROR: Could not find any ADB device
ERROR: Server connection failed

Thank you all for support

**Comment by rom1v** [comment]
> ERROR: Could not find any ADB device

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#device-not-detected

**Comment by MarcoT831** [comment]
> > ERROR: Could not find any ADB device
> 
> https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#device-not-detected

Hello again and thanks for your reply.
The screen of my smartphone got broken, how can I activate the debugging mode? 
Thanks in advance
