### ISSUE TITLE
How to disable Tab key when pressing Alt + Tab in Ubuntu

### ISSUE THREAD

**Issue by adicandra1** [Genymobile/scrcpy#3168]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Ubuntu 20.04
 - scrcpy version: 1.23
 - installation method: manual build
 - device model: Maxtron Genio 10
 - Android version: 9

**Describe the bug**
When I press Alt+Tab key on scrcpy , the actual Tab key is also triggered (e.g. triggering browser navigation by Tab key). This is frustrating, because sometimes when browsing in internet, the Tab key makes the browser scroll to top of the page to focus on the first content.

Is there a way to disable Tab key when pressing Alt+Tab ?

Thanks in advance

**Comment by rom1v** [comment]
I had similar problems in the past. I'd say this is a X11/SDL issue (they should not send the tab keyevent to the application if it's consumed for Alt+tab).

**Comment by adicandra1** [comment]
Ahh okay then.

After few trial and error, I can avoid those behavior by pressing RightAlt + Tab instead.

Thanks for the response.
