### ISSUE TITLE
Problem with frame counter

### ISSUE THREAD

**Issue by Xionghaizi001** [Genymobile/scrcpy#3169]
- [√] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [√] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10 21H2 19044.1586
 - scrcpy version: 1.22
 - installation method: Win release
 - device model: Meizu 18 Pro
 - Android version: 11

**Describe the bug**

(I'm not sure if anyone has reported this problem)
When use Alt+I to open frame counter, it will freeze and stop.

**Comment by rom1v** [comment]
Yeah, it's broken in v1.22. Use v1.23.
