### ISSUE TITLE
Option to set screen brightness to 0

### ISSUE THREAD

**Issue by kyelbek** [Genymobile/scrcpy#317]
Since there's no way to turn off screen completely but it is possible to set screen brightness using
"settings put system screen_brightness 0-255" in shell, it would be nice to have scrcpy setting this parameter to 0 when launching. I think it should be implemented as command line option so people can have a choice.

**Comment by rom1v** [comment]
See https://github.com/Genymobile/scrcpy/issues/101.

**Comment by rom1v** [comment]
A shortcut to turn device screen off is implemented on `dev` by 12a3bb25d39037931f577dc0165b3e517aad92df.
