### ISSUE TITLE
cannot click on screen with lenovo p11

### ISSUE THREAD

**Issue by hien4990** [Genymobile/scrcpy#3171]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: windows 10 20h2
 - scrcpy version: 1.23
 - installation method: download zip file and extract
 - device model: lenovo p11
 - Android version: 11

**Describe the bug**
cannot click on screen with lenovo p11
it keep showing the line: 
"Ignore touch event, it was generated for a different device size " everytime i try to click and nothing happen on app.

**Comment by rom1v** [comment]
See #2031.

> scrcpy version: 1.12.3

This version does not exist :D

**Comment by hien4990** [comment]
sorry my mistake

> See #2031.
> 
> > scrcpy version: 1.12.3
> 
> This version does not exist 😄

sorry my mistake

**Comment by rom1v** [comment]
See #2031 for the solution: reduce the definition.

**Comment by hien4990** [comment]
> See #2031 for the solution: reduce the definition.

i tried that method before i created this thread, doesnt work either

**Comment by rom1v** [comment]
What is the console output when you run `scrcpy` (especially the lines with "Initial texture" and "New texture")?

**Comment by hien4990** [comment]
thaks for reply this is the image i tested:
[[](url)](https://imgur.com/a/6vDXOPP)

**Comment by rom1v** [comment]
Scrcpy requests to the encoder a size of 1920×1152, but the encoder produces 1920×1080.

Try to lower the definition so that the encoder does not do that.

For example:
```
scrcpy -m1800
```

**Comment by hien4990** [comment]
thank you so much it finally work
btw is there a way to make the cmd auto type the command so i dont need to type it by myself every time i this great app

**Comment by rom1v** [comment]
> btw is there a way to make the cmd auto type the command so i dont need to type it by myself every time i this great app

Create a batch script (`myscrcpy.bat`), a simple text field containing the command:

```
scrcpy -m1800
```

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows
