### ISSUE TITLE
App crached on Fedora 35

### ISSUE THREAD

**Issue by gcarmin** [Genymobile/scrcpy#3173]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Fedora release 35  5.16.18-200.fc35.x86_64
 - scrcpy version: scrcpy 1.22
 - installation method: sudo dnf install scrcpy
 - device model: Galaxy S8
 - Android version: 9

```
[guy@gandalf35 07-Apr-2022]$ scrcpy --version
scrcpy 1.22 <https://github.com/Genymobile/scrcpy>

dependencies:
 - SDL 2.0.20
 - libavcodec 58.134.100
 - libavformat 58.76.100
 - libavutil 56.70.100
 - libavdevice 58.13.100
```

**Describe the bug**

```
[guy@gandalf35 07-Apr-2022]$ scrcpy
scrcpy 1.22 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 143.8 MB/s (18802 bytes in 0.000s)
ERROR: Exception on thread Thread[main,5,main]
java.lang.NumberFormatException: For input string: "1.22"
        at java.lang.Integer.parseInt(Integer.java:615)
        at java.lang.Integer.parseInt(Integer.java:650)
        at com.genymobile.scrcpy.Server.createOptions(Server.java:52)
        at com.genymobile.scrcpy.Server.main(Server.java:101)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:341)
ERROR: Server connection failed
```

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
You use a wrong server version. Your install is broken.

**Comment by gcarmin** [comment]
I just installed the package from the fedora repo, where from should I install it?

**Comment by gcarmin** [comment]
Solved by installing from the COPR repo.
tnx.

**Comment by aus10code** [comment]
> Solved by installing from the COPR repo. tnx.

How exactly do you download from the COPR repo? I'm not how to do it and it's not for a lack of trying. Are COPR repo's pulled from differently? I'm used to just doing a simple dnf install
