### ISSUE TITLE
is iOS version possible?

### ISSUE THREAD

**Issue by mailinglists35** [Genymobile/scrcpy#3178]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
Open app on iOS, type the IP address, control an android device

**Describe the solution you'd like**
Open app on iOS, type the IP address, control an android device

**Describe alternatives you've considered**
vnc or remote desktop or teamviewer from iOS to a desktop running scrcpy

**Additional context**

**Comment by rom1v** [comment]
#1691
