### ISSUE TITLE
Cannot compile. Execution failed for task ':server:processReleaseResources'.

### ISSUE THREAD

**Issue by brunoais** [Genymobile/scrcpy#3179]
I'm trying to compile scrcpy on ubuntu 20.04 but I'm getting this output:

```
> Task :server:processReleaseResources FAILED
> Task :server:mergeReleaseNativeLibs NO-SOURCE

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':server:processReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > AAPT2 aapt2-7.0.3-7396180-linux Daemon #0: Daemon startup failed
     This should not happen under normal circumstances, please file an issue if it does.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```
I tried `--info` and `--debug` on ninja and meson but appears like they don't belong to any of them.
Any idea what I may be missing here?

**Comment by rom1v** [comment]
Looks like a gradle/Android gradle plugin: https://stackoverflow.com/questions/55861519/upgraded-to-android-studio-3-4-aapt2internalexception-aapt2-daemon-startup-f

**Comment by brunoais** [comment]
That's weird, because I'm running ninja directly from the command line inside docker... Thank you anyway. I may be able to use some of the answers for myself

**Comment by brunoais** [comment]
Found the problem. **`$HOME/.gradle` needs to be executable** (mount options) but it wasn't due to one of the dependencies to compile java actually being an executable (maybe it's many but I only failed at one of them).
