### ISSUE TITLE
Hi, I am using a xiaomi mi 9t and a logitech master 3. When I click in the side front button when my mouse is

### ISSUE THREAD

**Issue by pfcouto** [Genymobile/scrcpy#3181]
I believe that a similarrequest does not exist.

I'm always frustrated when I click in the side buttons while I am hovering the screen displayed and it changes the screen.

I am using a xiaomi mi 9t and a logitech master 3. When I click in the side front button when my mouse is hovering the screen displayed it opens the control center. Can you please add a option to disable the side buttons?

Thanks.

**Comment by rom1v** [comment]
```
scrcpy --forward-all-clicks
```
