### ISSUE TITLE
help me guys

### ISSUE THREAD

**Issue by SametKecici** [Genymobile/scrcpy#3184]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

![image](https://user-images.githubusercontent.com/47273768/163197608-42020d74-e50f-4a2b-95d7-f7cfd65c203b.png)
guys what is this

**Comment by rom1v** [comment]
What is the result of `adb devices`?

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#device-not-detected
