### ISSUE TITLE
I want to hide the CMD command box when running

### ISSUE THREAD

**Issue by Fly-Felix** [Genymobile/scrcpy#3185]
How to hide the CMD command box or not show the CMD command box when starting scrcpy.exe

**Comment by rom1v** [comment]
Start `scrcpy-noconsole.vbs` instead.

**Comment by Fly-Felix** [comment]
Thank you, I know.




---Original---
From: "Romain ***@***.***&gt;
Date: Thu, Apr 14, 2022 13:16 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Genymobile/scrcpy] I want to hide the CMD command box whenrunning (Issue #3185)




 
Start scrcpy-noconsole.vbs instead.
