### ISSUE TITLE
Window drags automatically

### ISSUE THREAD

**Issue by PembaTamang** [Genymobile/scrcpy#3193]
My windows 11

Edition	Windows 11 Home Single Language
Version	21H2
Installed on	‎14-‎04-‎2022
OS build	22000.613
Serial number	PF34T5WW
Experience	Windows Feature Experience Pack 1000.22000.613.0

My Phone

![image](https://user-images.githubusercontent.com/32651212/163814901-98dacda3-27f3-48a7-9dac-9b201f8699ed.png)

Steps to reproduce
1. add a second screen and extend it.
2. take the emulator on the second extended screen.
3. if you move the cursor near the window bounds the window will move. 

It's quite annoying please fix. Any help is greatly appreciated.

**Comment by rom1v** [comment]
This behavior comes from the window manager (the one from Windows in your case), not the app.

Btw, it's probably the same with other apps (like the file manager or others). It is possibly configurable in Windows settings.

**Comment by PembaTamang** [comment]
Nope, it's just scrcpy , I went though a few other third party apps and the window behavior is fine. This issue is there only on the second screen with scrcpy, everything is fine on my primary screen including scrcpy.

**Comment by PembaTamang** [comment]
@rom1v could you take a look

**Comment by rom1v** [comment]
Scrcpy does not have code to do that, this is the behavior from the window manager.

It uses SDL, and SDL does not expose any related flags: https://wiki.libsdl.org/SDL_WindowFlags

So there is nothing scrcpy can do AFAIK.

**Comment by rom1v** [comment]
Could you post a video capture?

**Comment by PembaTamang** [comment]
here

https://user-images.githubusercontent.com/32651212/164449762-0ea0f258-94e6-42b1-b395-f4bf3be4c59e.mp4

**Comment by PembaTamang** [comment]
I can't see the video. If it's the same for you here is the link to the file https://www.mediafire.com/file/4h7p4vj2wcr3rik/20220421_170041_1_1.mp4/file

**Comment by rom1v** [comment]
Thanks. It looks like your window manager moves it so that it does not overlap the bottom bar.

**Comment by PembaTamang** [comment]
it's just scrcpy. everything else is fine. Is there anything that I can do??

**Comment by rom1v** [comment]
Even if you resize another app (the file browser) to exactly the same size as the scrcpy before moving it to the secondary screen?

**Comment by PembaTamang** [comment]
yes just scrcpy... I don't run into that issue on other apps. File explorer, vlc , skpye works fine.

**Comment by rom1v** [comment]
> Is there anything that I can do??

According to your video, the problem seems to be the window height, which is higher that your secondary screen minus the bottom bar.

Start scrcpy with a lower window height, with `--window-height=…`.

**Comment by PembaTamang** [comment]
@rom1v Hey I am using windows power tools in windows 11 and I use the windows+ctrl+T shortcut to pin the device window and this issue does not happen.

Others facing this issue can use this workaround.
