### ISSUE TITLE
How to convert "codecBuffer" to org.webrtc.VideoFrame?

### ISSUE THREAD

**Issue by hytTony** [Genymobile/scrcpy#3198]
The "**codecBuffer**"  defined here [in ScreenEncode.java]
`ByteBuffer codecBuffer = codec.getOutputBuffer(outputBufferId);`

I send it to another process with socket, then receive it as byte[], and then i try to convert it to **org.webrtc.VideoFrame** like these:
` long timestampNS = TimeUnit.MILLISECONDS.toNanos(SystemClock.elapsedRealtime());`
`NV21Buffer nv21Buffer = new NV21Buffer(receiverByteArray, width, height, null);`
`VideoFrame videoFrame = new VideoFrame(nv21Buffer, 0, timestampNS);`
or
`ByteBuffer byteBuffer = AppRTCUtils.byteArray2byteBuffer(receiverByteArray);`
`VideoFrame.Buffer b = new NV12Buffer(width, height, width, height, byteBuffer, null);`
`VideoFrame videoFrame = new VideoFrame(b, 0, System.nanoTime());`

These two all didn't work!

What is the correct way to convert it to **org.webrtc.VideoFrame**?

**Comment by rom1v** [comment]
The byteBuffer contains a H.264 compressed frame, while WebRTC probably expects a decoded frame.

But sorry, this is not the right place to request help about WebRTC.

**Comment by hytTony** [comment]
> The byteBuffer contains a H.264 compressed frame, while WebRTC probably expects a decoded frame.
> 
> But sorry, this is not the right place to request help about WebRTC.

Thanks and sorry for request help about webRTC at here.
