### ISSUE TITLE
MESON alternative

### ISSUE THREAD

**Issue by NoviceOverHere** [Genymobile/scrcpy#32]
Greetings, 
Windows not recognizing meson as legit.  I've tried .py, .exe, .bat, no use.  Any help appreciated.  Thanks!

![image](https://user-images.githubusercontent.com/37249400/37245359-5d2a44ba-245c-11e8-8ba4-1682504933a7.png)

**Comment by rom1v** [comment]
You must run it from [MSYS2](https://www.msys2.org/). Cf [README](https://github.com/Genymobile/scrcpy/blob/master/README.md#windows).
