### ISSUE TITLE
scrcpy 大佬(dalao), 那个我用QQ没办法拖拽图片，或者文件到电脑上，电脑也没办法拖拽到手机上

### ISSUE THREAD

**Issue by newyorkthink** [Genymobile/scrcpy#3202]
我系统是I3WM 这个环境

**Comment by newyorkthink** [comment]
![image](https://user-images.githubusercontent.com/87791643/164410041-9c3174ea-49e4-4294-a7b4-d85043f665c8.png)

**Comment by rom1v** [comment]
Issue is not in English.
