### ISSUE TITLE
X32 windows 8. AOA otg error.

### ISSUE THREAD

**Issue by retnrernet** [Genymobile/scrcpy#3204]
I can't start --otg mode on my asus x32 bit windows 8 system, because AOA disabled. I can't use relative mouse in some apps:(
Meizu phone, android 7. All needed settings in menu are enabled.

**Comment by retnrernet** [comment]
Please, add new feature to next update - otg In x32 bit windows machines

**Comment by rom1v** [comment]
Please test #3206.
