### ISSUE TITLE
audio forwarding

### ISSUE THREAD

**Issue by eku** [Genymobile/scrcpy#321]
I've just compiled a version from the branch ```audio```.  Unfortunately, I could not find any information about what conditions must all be met.

```
./run x -a -m 800
x/server/scrcpy-server.jar: 1 file pushed. 0.4 MB/s (18826 bytes in 0.048s)
ERROR: Cannot find USB device having serial turrican:5555
ERROR: AOA audio forwarding failed
```

If audio forwarding uses ADB why isn't ADB over Ethernet supported?

**Comment by rom1v** [comment]
Audio forwarding does not use `adb`, but AOA over USB (`adb` is still required for scrcpy).

**Comment by eku** [comment]
Well, for Samsung and rooted devices , there is [another way to record audio](https://similarindex.com/internal-audio-screen-recording-apps/).

**Comment by rom1v** [comment]
- https://blog.rom1v.com/2020/06/audio-forwarding-on-android-10/
 - https://github.com/rom1v/sndcpy
