### ISSUE TITLE
How does OTG mode synchronize the pasteboard of the computer?

### ISSUE THREAD

**Issue by wenliangzhou** [Genymobile/scrcpy#3215]
- [ ] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rom1v** [comment]
With `scrcpy --otg`, the clipboard is not synchronized.

**Comment by wenliangzhou** [comment]
Is this demand theoretically achievable?

**Comment by wenliangzhou** [comment]
Is this demand theoretically achievable?
