### ISSUE TITLE
How to play Pubg mobile on it with preset settings without octopus?

### ISSUE THREAD

**Issue by RDxRahul128** [Genymobile/scrcpy#322]

**Comment by numbermaniac** [comment]
> What is octopus?

Just did a search:
https://play.google.com/store/apps/details?id=com.chaozhuo.gameassistant

Looks like PUBG is banning users for using it:
https://old.reddit.com/r/PUBGMobile/comments/9mgifn/

**Comment by RDxRahul128** [comment]
Bro tell me the solution of it not gettin bannnnned

**Comment by numbermaniac** [comment]
@RDxRahul128 Relax, rom1v asked "what is octopus" so I was explaining it to them.

**Comment by RDxRahul128** [comment]
LEAVE IT I JUST WANT TO PLAYPUBG BY THIS MIRRORING TRICKPLZ HELP

**Comment by numbermaniac** [comment]
What's stopping you? You can still use scrcpy to mirror your screen onto your computer. You can click on the game's buttons using your PC mouse. If you need to press the volume buttons, use Control-Up and Control-Down on your PC's keyboard.

Octopus being banned was PUBG's decision, we can't do anything about that - you'll have to ask Tencent if you want that changed.

**Comment by RDxRahul128** [comment]
Bro their are many controls to do in pubg and. I am just asking that i want. A app like octopus

**Comment by numbermaniac** [comment]
If you're looking for an app like octopus, why are you asking here? We can't help you with that - your issue isn't about scrcpy.

**Comment by cviali** [comment]
> THIS MIRRORING TRICKPLZ

Well, that explains it. Somebody must've been making tutorials on how to play mobile games using scrcpy to mirror the phone screen to PC, and the Octopus app were supposed to remap the keyboard+mouse input as game controls through a preset, basically trying to get the advantage than other players who's using touch input to play.

**Comment by numbermaniac** [comment]
Ahh... Looks like you're right. I searched "YouTube pubg scrcpy" on Google and it comes up with a number of results of people doing exactly that.

https://www.google.com/search?q=YouTube%20pubg%20scrcpy

**Comment by cviali** [comment]
I wonder why this guy doesn't use gaming emulators in the first place. I've realized that Tencent, the developer of the game could detect if the game runs on PC emulator or not, to prevent those unfair advantage than people with touch inputs. The game will match the player on PC emulator with others who's also using PC emulators. And this 'scrcpy + octopus' could get past the system. Long story short, this guy is trying to cheat at games.

**Comment by shashi007** [comment]
> I wonder why this guy doesn't use gaming emulators in the first place. I've realized that Tencent, the developer of the game could detect if the game runs on PC emulator or not, to prevent those unfair advantage than people with touch inputs. The game will match the player on PC emulator with others who's also using PC emulators. And this 'scrcpy + octopus' could get past the system. Long story short, this guy is trying to cheat at games.

That's what i do when I want to play PUBG on PC, Use the official emulator guys! There's a reason why they have it. If people start cheating the game it won't be fun. You could perhaps use scrcpy to make your screen bigger and use mobile as a controller. :-)

**Comment by librewish** [comment]
Those emulator don't support Linux
And on genymotion you can't play pubg.
