### ISSUE TITLE
not reopening after first time:(

### ISSUE THREAD

**Issue by mottyweisfish** [Genymobile/scrcpy#3220]
firstly, i have no clue what im doing when it comes to code...
secondly, i sucsesfully instaled and ran scrcpy (amaizing, i know ; )  but the next time i tried to open it it just flashed open then closes. i tried in between to cast Android screen to laptop using Wi-Fi using step by step instructions. i wonder if that might be the problem. please can you help
![Untitled](https://user-images.githubusercontent.com/104465961/165400704-e3ae9024-8e4f-45de-bb25-6e8b12887508.png)

**Comment by rom1v** [comment]
> it just flashed open then closes

Run `scrcpy-console.bat` so that the console does not close on error, then post the console output (as text, not a screenshot).

**Comment by mottyweisfish** [comment]
this is what i get. am i a total waste of time?

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\User> scrcpy-console.bat
scrcpy-console.bat : The term 'scrcpy-console.bat' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At line:1 char:1
+ scrcpy-console.bat
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (scrcpy-console.bat:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\User>

**Comment by rom1v** [comment]
Don't run it from PowerShell, double-click on it from the browser.

**Comment by mottyweisfish** [comment]
oh. sorry.
 got this:

scrcpy 1.23 <https://github.com/Genymobile/scrcpy>
ERROR: Multiple (2) ADB devices:
ERROR:     -->   (usb)        F21PL219020101            device  F21_Pro
ERROR:     --> (tcpip)   100.89.137.180:5555           offline
ERROR: Select a device via -s (--serial), -d (--select-usb) or -e (--select-tcpip)
ERROR: Server connection failed
Press any key to continue . . .

**Comment by rom1v** [comment]
OK, so you have 2 "devices" connected, when you run scrcpy you must select one, for example:
```
scrcpy -d
```

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows

Btw, your device via TCP/IP appears offline, I don't know why, check: https://stackoverflow.com/questions/17626691/adb-device-offline-with-adb-wireless

**Comment by mottyweisfish** [comment]
IT WORKED!!!!! the usb work straight away when i selected "scrcpy -d". the wifi one worked too after i "kill-server" and reconnected.
thanks so much
