### ISSUE TITLE
Fedora 36, ERROR: Could not open codec

### ISSUE THREAD

**Issue by allco** [Genymobile/scrcpy#3223]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Fedora 36 (wayland + intel CPU)
 - scrcpy version: 1.23
 - installation method: dnf copr zeno/scrcpy
 - device model: Pixel 2
 - Android version: 11

**Describe the bug**
Window does not popup.

```
➜  ~ sudo dnf install libdecor                            
Last metadata expiration check: 0:06:26 ago on Thu 28 Apr 2022 09:35:35 AM CEST.
Package libdecor-0.1.0-2.fc36.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!

➜  ~ SDL_VIDEODRIVER=wayland scrcpy --verbosity=debug
scrcpy 1.23 <https://github.com/Genymobile/scrcpy>
DEBUG: ADB device found:
DEBUG:     -->   (usb)  FA79T1A03801                    device  Pixel_2
DEBUG: Device serial: FA79T1A03801
DEBUG: Using server: /usr/share/scrcpy/scrcpy-server
/usr/share/scrcpy/scrcpy-server: 1 fil...ed. 562.4 MB/s (41123 bytes in 0.000s)
[server] INFO: Device: Google Pixel 2 (Android 11)
DEBUG: Server connected
DEBUG: Starting controller thread
DEBUG: Starting receiver thread
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 22.0.1
INFO: Trilinear filtering enabled
DEBUG: Using icon: /usr/share/icons/hicolor/256x256/apps/scrcpy.png
INFO: Initial texture: 1080x1920
DEBUG: Starting demuxer thread
ERROR: Could not open codec
ERROR: Could not open packet sink 0
ERROR: Could not open demuxer sinks
WARN: Device disconnected
DEBUG: quit...
DEBUG: Receiver stopped
[server] DEBUG: Controller stopped
[server] DEBUG: Using encoder: 'OMX.qcom.video.encoder.avc'
WARN: Killing the server...
DEBUG: Server disconnected
DEBUG: Server terminated
➜  ~ 
```

**Comment by rom1v** [comment]
> ERROR: Could not open codec

So the H.264 codec could not be opened. Something is wrong with your ffmpeg or something :/

Could you try a manual install? -> https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple (adapt the command to install the packages to fedora)

**Comment by allco** [comment]
Fixed!

I have installed ffmpeg as it described here https://computingforgeeks.com/how-to-install-ffmpeg-on-fedora. But before installing ffmpeg I had to remove conflicting `libswscale` with `sudo dnf remove libswscale-free-5.0.1-1.fc36.x86_64`, then reinstiall scrcpy and not it works!

Thanks @rom1v !
