### ISSUE TITLE
Scrcpy opens a black window but i can still click on things.

### ISSUE THREAD

**Issue by HaveSomeRubicon** [Genymobile/scrcpy#3229]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Zorin 16 lite with i3 and no compositor
 - scrcpy version: 1.23
 - installation method: tried manual build and snap
 - device model: SM-T290
 - Android version: 11

**Scrcpy opens a completely blank window but when I click around on the window it still sends input*
Whenever I open scrcpy it opens a blank window except I can click around in the window and it will register the clicks. The command output does not show any signs of anything going 

```
scrcpy 1.23 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server:...shed. 4.1 MB/s (41123 bytes in 0.010s)
[server] INFO: Device: samsung SM-T290 (Android 11)
INFO: Renderer: opengl
INFO: OpenGL version: 1.4 Mesa 21.2.6
WARN: Trilinear filtering disabled (OpenGL 3.0+ or ES 2.0+ required)
INFO: Initial texture: 1280x800
```

**Comment by HaveSomeRubicon** [comment]
Note: ive got scrcpy working fine on linux and windows with the same PC and tablet. I just had a different linux/windows setup

**Comment by rom1v** [comment]
Is the screen black in the recorded file if you record (`scrcpy --record file.mp4`)?

**Comment by HaveSomeRubicon** [comment]
I can see everything crystal clear in the recording

**Comment by rom1v** [comment]
OK, so probably a driver issue.

> INFO: OpenGL version: 1.4 Mesa 21.2.6

OpenGL 1.4 :open_mouth: That's very old and quite unexpected.

You could try with `scrcpy --render-driver=opengles2` (maybe).

**Comment by HaveSomeRubicon** [comment]
My computer is really old(REALLY OLD) so old drivers were expected. `scrcpy --render-driver=opengles2` seemed to work absolutely fine and it rendered everything fine.

**Comment by nachtien** [comment]
I am running into this issue also. 

![image](https://user-images.githubusercontent.com/116726/170787512-a5208ed4-9e9e-4517-8bae-57bd556ab533.png)

OS: MacOS 12.3 m1
scrcpy version: 1.24
installation method: Homebrew
device model: Pixel 4a
Android version: 12

**Comment by rom1v** [comment]
@nachtien On "protected" apps, that's expected on Android 12 (#2129 #36).

**Comment by nachtien** [comment]
It's not a protected app

**Comment by AberuSama** [comment]
> @nachtien On "protected" apps, that's expected on Android 12 (#2129 #36).

I just got my Realme updated to UI 3.0 and I'm having the same problem on "protected" apps.

**Comment by rom1v** [comment]
> It's not a protected app I don't think

Does it work on other apps?

**Comment by AberuSama** [comment]
> 

Yes

**Comment by rom1v** [comment]
OK, so when it's black, it's because the app enabled FLAG_SECURE to prevent capture and screenshots.

**Comment by AberuSama** [comment]
Sorry I didn't read your message before.
The point is that scrcpy worked on the same protected app 2 months ago. Is it possible to make it go through the flag_secure as it used to do?

**Comment by msm-code** [comment]
As far as I know this is android 12 issue. It's possible you've updated your android version to 12+ 2 months ago (or I guess 7 months ago now).

**Comment by azizsayfiddin** [comment]
It was the same for me. After specifying: opengles2, it worked.

It happened on NixOS
