### ISSUE TITLE
Can't control screen

### ISSUE THREAD

**Issue by bibintb** [Genymobile/scrcpy#3236]
I can view copy of mobile screen on laptop. But I can't control from laptop.
Installed available stable version.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work

**Comment by CubanJaco** [comment]
> https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work

That worked for me in Android 12. I think this issue should be closed.

**Comment by bibintb** [comment]
Thank you. Enabling the following worked for me.  
USB debugging (Security settings) >> Allow granting permissions and simulating input via USB debugging.

**Comment by Pete11** [comment]
Hi guys, even after enabling security settings mouse not working. MIUI 14, Android 13 Xiaomi Note 10 Pro.
