### ISSUE TITLE
Version 1.24 gone?

### ISSUE THREAD

**Issue by Helaer** [Genymobile/scrcpy#3253]
Version 1.24 gone?

**Comment by rom1v** [comment]
wtf :scream:

**Comment by rom1v** [comment]
The direct link still works: https://github.com/Genymobile/scrcpy/releases/tag/v1.24
But it does not appear on the releases page: https://github.com/Genymobile/scrcpy/releases

**Comment by Helaer** [comment]
> 直接链接仍然有效：https://github.com/Genymobile/scrcpy/releases/tag/v1.24 但它不会出现在发布页面上：https://github.com/Genymobile/scrcpy/releases

Did you revoke it?

**Comment by rom1v** [comment]
I did nothing. This is probably a GitHub bug related to the releases page.

**Comment by Helaer** [comment]
> 

okay, got it.

**Comment by rom1v** [comment]
I edited the release text (some spacing changes) to trigger an update, and it worked: https://github.com/Genymobile/scrcpy/releases
