### ISSUE TITLE
Android 4.4, libvc1dec_sa.ca7.so wasting memory and a security risk

### ISSUE THREAD

**Issue by pronoy2108** [Genymobile/scrcpy#3256]
**Environment**
 - OS: [Windows 11]
 - Android version: [4.4]

**Describe the bug**
```
adb.exe: error: closed
ERROR: "adb reverse" returned with value 1
WARN: 'adb reverse' failed, fallback to 'adb forward'
27183
WARNING: linker: libvc1dec_sa.ca7.so has text relocations. This is wasting memory and is a security risk. Please fix.
WARNING: linker: libvc1dec_sa.ca7.so has text relocations. This is wasting memory and is a security risk. Please fix.
```

![image](https://user-images.githubusercontent.com/83197609/167633017-39aa07e4-e6bd-4605-84c3-937caec34bfe.png)

**Comment by rom1v** [comment]
Thank you for the report, but it's an error in the ROM, not related to scrcpy.

And scrcpy requires at least Android 5.
