### ISSUE TITLE
Suggestion: create a barebones version of scrcpy?

### ISSUE THREAD

**Issue by minhnguyenhoang** [Genymobile/scrcpy#3257]
So I've been looking for a good screen mirroring application and this is probably the closest thing I've come across. However, there's been something that's nagging me a bit. scrcpy can put some serious load on my phone when I'm trying to game and mirror at the same time. Is it possible to create a version of scrcpy that only has the phone mirroring part? I don't want to control my phone from the computer, all I want is a mirroring window.

**Comment by rom1v** [comment]
> scrcpy can put some serious load on my phone when I'm trying to game and mirror at the same time

That's due the mirroring part: your device renders a game, and at the same time capture the result and encode it to H.264.

> I don't want to control my phone from the computer

```
scrcpy -n
scrcpy --no-control
```

**Comment by minhnguyenhoang** [comment]
Thank you very much, I'll try and see if this makes a different
