### ISSUE TITLE
disable right-click back option

### ISSUE THREAD

**Issue by Leuhan76** [Genymobile/scrcpy#3258]
Hello, I wanted to know how I can disable the right click option with the mouse, while mirroring the screen and at the same time with the otg mode, that is
scrcpy -KM

**Comment by Leuhan76** [comment]
I tried trying with: scrcpy --no-control --hid-keyboard --hid-mouse

but it just disables the control, it doesn't activate the otg mode

**Comment by rom1v** [comment]
```
scrcpy -KM --forward-all-clicks
```

(if I understood the question correctly.)

**Comment by Leuhan76** [comment]
yes exactly that, thank you

**Comment by rom1v** [comment]
> I know mirroring and OTG can't be active at the same time, but with just 'scrcpy --otg --forward-all-clicks' the right click still gets interpreted as back/home.

In OTG mode, it really injects a mouse click event (as if you connected a physical mouse). It is not possible that scrcpy interprets the click and inject HOME/BACK in this case, so if it appears to do so, it your foreground Android app which behaves that way.

**Comment by FlandreS** [comment]
In my case it seems to be Android's kernel that interprets OTG input as home/back. When hardware a hardware mouse is used on my device that's also how it works. Even with apps that have right click support.

For example, RuneScape pulls up the quit/logout menu rather than the intended right click context menu. Less specific is that Steam Link remote play just drops right click inputs as Windows doesn't seem to interpret the input.

I can get those things working via --forward-all-clicks without using --otg, though I'm then missing out on the ability to mouse around desktop apps that are supposed to capture mouse movement.

Might not be possible with the way that Windows handles adb/USB.

**Comment by rom1v** [comment]
> In my case it seems to be Android's kernel that interprets OTG input as home/back.

Are there any relevant errors in `adb logcat`? Maybe the app just crash on right-click, and it appears to behave like HOME.

> Might not be possible with the way that Windows handles adb/USB.

That's entirely on the Android side, the client sends a right-click event over AOA/USB.

**Comment by FlandreS** [comment]
In logcat it shows up as `keyCode=KEYCODE_BACK` as well. I know OTG is at least sort-of kind-of working, as the hardware cursor appears on the display. Plus screen mirroring gets disabled, so it gives me some confidence that the flag is really recognized. 

> 06-15 09:33:55.150  2088  2332 D WindowManager: interceptKeyTq keycode=4 down=true injected=false mDisplayState=2 interactive=true keyguardActive=false flags=0x0 policyFlags=22000001
> 06-15 09:33:55.152  2088  2331 D WindowManager: interceptKeyTi keyCode=4 down=true repeatCount=0 keyguardOn=false canceled=false flags=0x0 keyFromCover=false
> 06-15 09:33:55.153 15020 15020 I ViewRootImpl: ViewRoot's KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x0, repeatCount=0, eventTime=2161839, downTime=2161839, deviceId=12, source=0x2002, displayId=0 } to DecorView@d9ba6a9[MainActivity]
> 06-15 09:33:55.153 15020 15076 E threaded_app: Failure reading next input event: Try again
> 06-15 09:33:55.197  2088  2332 D WindowManager: interceptKeyTq keycode=4 down=false injected=false mDisplayState=2 interactive=true keyguardActive=false flags=0x0 policyFlags=22000000
> 06-15 09:33:55.198 15020 15020 I ViewRootImpl: ViewRoot's Touch Event : ACTION_HOVER_ENTER
> 06-15 09:33:55.199  2088  2331 D WindowManager: interceptKeyTi keyCode=4 down=false repeatCount=0 keyguardOn=false canceled=false flags=0x0 keyFromCover=false
> 06-15 09:33:55.219 15020 15020 I ViewRootImpl: ViewRoot's KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x0, repeatCount=0, eventTime=2161887, downTime=2161887, deviceId=12, source=0x2002, displayId=0 } to DecorView@d9ba6a9[MainActivity]
> 06-15 09:33:55.219 15020 15076 E threaded_app: Failure reading next input event: Try again

Here's a similar situation using just --forward-all-clicks, without --otg

> 06-15 09:58:35.104  2088  2331 V InputDispatcher: Asynchronous input event injection succeeded.
> 06-15 09:58:35.104  2088  2331 D InputTransport: channel '92a7665 com.jagex.runescape.android/com.jagex.android.MainActivity (server)' : action=ACTION_DOWN(0), id=0, tooltype=1, deviceId=0, source=0x2002, flags=0x0, edgeFlags=0x0, metaState=0x0, buttonState=0x2, downTime=3641793000000, eventTime=3641793000000, pointerCount=1
> 06-15 09:58:35.104  2088  2331 D InputTransport: channel 'PointerEventDispatcher0 (server)' : action=ACTION_DOWN(0), id=0, tooltype=1, deviceId=0, source=0x2002, flags=0x0, edgeFlags=0x0, metaState=0x0, buttonState=0x2, downTime=3641793000000, eventTime=3641793000000, pointerCount=1
> 06-15 09:58:35.104 16555 16555 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
> 06-15 09:58:35.105  2088  2138 D SystemGestures: pointer 0 down pointerIndex=0 trackingIndex=0
> 06-15 09:58:35.152  2088  2398 D WifiWatchdogStateMachine: EVENT_CHECK_IMS_CALL_STATE received
> 06-15 09:58:35.152  2088  2398 D WifiWatchdogStateMachine: OnlineWatchState handleRssiChange() imscallstate : 0

**Comment by rom1v** [comment]
> In logcat it shows up as keyCode=KEYCODE_BACK as well. I

Execute `scrcpy -Vverbose`. What's injected by scrcpy?

**Comment by FlandreS** [comment]
With `scrcpy --Vverbose`

> VERBOSE: input: back-or-screen-on down
> VERBOSE: input: back-or-screen-on up

With `scrcpy --Vverbose --otg`

> VERBOSE: HID Event: [2] 02 00 00 00 (right click down)
> VERBOSE: HID Event: [2] 00 00 00 00 (right click up)

With `scrcpy --Vverbose --forward-all-clicks`

> VERBOSE: input: touch [id=mouse] down position=902,1700 pressure= buttons=000000
> VERBOSE: input: touch [id=mouse]   up position=902,1700 pressure= buttons=000000

Combined, `scrcpy --Vverbose --otg --forward-all-clicks`

> VERBOSE: HID Event: [2] 02 00 00 00
> VERBOSE: HID Event: [2] 00 00 00 00

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/doc/mouse.md#mouse-bindings
