### ISSUE TITLE
IDR frame interval support

### ISSUE THREAD

**Issue by wchensc** [Genymobile/scrcpy#3260]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
When the phone screen doesn't change, there will be a big latency for the next IDR frame to be present. 

* I am only using the scrcpy server code(Java), NOT the client code(C).

I have a use case that I want to stream the scrcpy's frames to multiple clients. But the clients might come in different time. So it takes a long time(30-60seconds) for the 2nd client to see the screen when there is no screen movement. The screen will only render when an IDR frame arrives.

**Describe the solution you'd like**
I am not sure how to achieve this but it would be great to provide a parameter for developers to specify the IDR frame interval.

I didn't see the option on Android MediaFormat: https://developer.android.com/reference/android/media/MediaFormat. 
I tried modifying the [KEY_I_FRAME_INTERVAL](https://developer.android.com/reference/android/media/MediaFormat#KEY_I_FRAME_INTERVAL) but it didn't help much and I read the [article](https://malleshamdasari.wordpress.com/2013/07/31/difference-between-i-frame-and-idr-frame) that points out I frame is not necessary IDR frame. I also modified [KEY_INTRA_REFRESH_PERIOD](https://developer.android.com/reference/android/media/MediaFormat#KEY_INTRA_REFRESH_PERIOD) and it had no effect.

**Comment by rom1v** [comment]
> I tried modifying the [KEY_I_FRAME_INTERVAL](https://developer.android.com/reference/android/media/MediaFormat#KEY_I_FRAME_INTERVAL) but it didn't help much

If you change it to a lower value (by default 10 seconds), key frames are more frequent:

```
# request a keyframe every second
scrcpy --codec-options=i-frame-interval=1
```

However, it will still not produce any frame when there is no changes.

You need a new control message "refresh IDR" which restarts the encoding the same way it is done when the screen rotates. Such an option (with a shortcut bind to it) will also be helpful when the display size changes and cannot be detected automatically (e.g. with foldable devices).

**Comment by wchensc** [comment]
Got it..  I forked the repo and made some changes and it worked. Thanks!

**Comment by rom1v** [comment]
Could you submit a proper PR to implement the "refresh IDR" on a shortcut?

**Comment by wchensc** [comment]
I am a bit busy fixing other parts right now. Will come back to submit a pr when I am available. Thanks

**Comment by cuserdzy** [comment]
I'm facing the same issue where some clients may join after the stream has started. During testing (e.g., letting the screen turn off and then waking it up), I noticed that scrcpy-server only seems to output an I-frame when the stream begins.
I’m curious whether KEY_I_FRAME_INTERVAL (https://github.com/Genymobile/scrcpy/blob/c5ed2cfc28ee7c7b59b11eb4db1258ac1c633bff/server/src/main/java/com/genymobile/scrcpy/video/SurfaceEncoder.java#L266) actually works

Adding a “refresh_idr” command sounds like a reliable solution, and I’m interested in implementing it.

**Comment by yume-chan** [comment]
> Adding a “refresh_idr” command sounds like a reliable solution, and I’m interested in implementing it.

#5432

https://github.com/Genymobile/scrcpy/blob/c5ed2cfc28ee7c7b59b11eb4db1258ac1c633bff/server/src/main/java/com/genymobile/scrcpy/control/ControlMessage.java#L27

If you can just tell the encoder to produce a keyframe immediately, that would be better.

**Comment by cuserdzy** [comment]
> > Adding a “refresh_idr” command sounds like a reliable solution, and I’m interested in implementing it.
> 
> [#5432](https://github.com/Genymobile/scrcpy/pull/5432)
> 
> [scrcpy/server/src/main/java/com/genymobile/scrcpy/control/ControlMessage.java](https://github.com/Genymobile/scrcpy/blob/c5ed2cfc28ee7c7b59b11eb4db1258ac1c633bff/server/src/main/java/com/genymobile/scrcpy/control/ControlMessage.java#L27)
> 
> Line 27 in [c5ed2cf](/Genymobile/scrcpy/commit/c5ed2cfc28ee7c7b59b11eb4db1258ac1c633bff)
> 
>  public static final int TYPE_RESET_VIDEO = 17; 
> If you can just tell the encoder to produce a keyframe immediately, that would be better.

Thank you so much for your guidance! It seems to be working now. After sending the RESET_VIDEO message, I successfully received the SPS/PPS/I frame.

I also want to express my gratitude for your awesome work on ya-webadb — it has saved me a lot of time in building control messages.
