### ISSUE TITLE
Videos are playing blank when accessing Android TV from Laptop

### ISSUE THREAD

**Issue by Koushikvij** [Genymobile/scrcpy#3261]
- [Y] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [Y] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows OS with Android TV 9
 - scrcpy version: v1.23
 - installation method: Manual
 - device model: Mi TV 4A 40 inch
 - Android version: 9

**Describe the bug**
Videos are playing blank when accessing Android TV from Laptop. No errors are encountered. I see blank screen in the scrcpy window but the video is playing as expected in the TV.

C:\Users\koush\Downloads\scrcpy-win64-v1.23>scrcpy.exe --select-tcpip -m 1080
scrcpy 1.23 <https://github.com/Genymobile/scrcpy>
C:\Users\koush\Downloads\scrcpy-win64-v1.23\scrcpy-server:... file pushed, 0 skipped. 44.6 MB/s (41123 bytes in 0.001s)
[server] INFO: Device: Xiaomi MiTV-AXSO0 (Android 9)
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
INFO: Renderer: direct3d
[server] INFO: Retrying with -m1024...
INFO: Initial texture: 1080x608
INFO: New texture: 1024x576

**Comment by rom1v** [comment]
That's "expected": it is due either to DRM or some hardware acceleration.

See #1618 #2601.

**Comment by Koushikvij** [comment]
What is the solution to overcome this? DRM or some hardware acceleration at TV end ?

**Comment by rom1v** [comment]
I have no solution.

**Comment by Koushikvij** [comment]
Are you planning to implement it in the upcoming releases? Youtube while played on mobile phone is displayed on the scrcpy screen whereas same youtube on TV is not displayed on scrcpy

**Comment by rom1v** [comment]
No, there is no solution, the device (TV) does not capture these parts of the screen, so they cab't be mirrored.

**Comment by lucasZero** [comment]
With magiconnect is possible to take a screenshot, maybe disable DRM in rooted android TV can work.
