### ISSUE TITLE
Input duplication when writting accents

### ISSUE THREAD

**Issue by XLave** [Genymobile/scrcpy#3271]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Win10
 - scrcpy version: 1.23
 - installation method: Windows release
 - device model: Redmi Note 10 Pro
 - Android version: 12.5

**Describe the bug**
Every time I write any word that uses accents it duplicates that character with itself without an accent (I'm Spanish so I use accents a lot), example: Buenos **diías**

**Comment by rom1v** [comment]
Try `scrcpy --prefer-text`.

**Comment by XLave** [comment]
Wow, that was fast! It works! Thx a lot! It was sooooo annoying.
