### ISSUE TITLE
Set a specific max_size depending on the encoder by default

### ISSUE THREAD

**Issue by Valkhes** [Genymobile/scrcpy#3274]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**

The main problem we seems to see with scrcpy is the encoding problem, forcing people to reduce max_size in order to reach a specific value that is working for the device. Otherwise, scrcpy is crashing. Right now, you implemented a fix client side which is retrying with different sizes. This is however not the case server size, meaning that when you don't use the client to get the frames (I'm using directly a socket to read frames), you don't have access to this fix it seems.
I implemented on my side a "fine tuning maxsize" code that is trying to launch multiple times scrcpy to find the biggest value that is working with my device by dichotomy. But this can take some time.

**Describe the solution you'd like**

After looking at a lot of devices, I saw that depending on the encoder, there is in fact a real max size that seems to be relative to which encoder you are using. For example, when using the OMX.google.h264.encoder, I saw that the value found is always the same in my code, and it is 2560 (I think maybe the real max value for this encoder can be a bit higher but less than 2600 as I used a dichotomy but stopped it when it is iterating too much). It means that for this encoder specifically, you can encode a frame with a max size of 2560, no matter what device you are using. ( I tested it with at least 5 different devices models that have a resolution bigger than this value )

With this information, I suppose that it is possible server side to make a matching table of value for each encoder. Except if you know that this value can change (for example an update on the encoder or something like that?), or if you know that an encoder can have a different behaviour between device (which seems to not be the case with OMX.google.h264.encoder), I suppose you can take this value by default if the device is having a bigger resolution. This could avoid the client to check multiple values, and this could avoid doing code on our side if you are using only the server.

I don't know how easy it is to find the max real value each encoder can have, but maybe it is also something that is given by the encoder somewhere ? It would be even better if the encoder was giving back the info.

Please tell me if you think this can be a feature, I would love to discuss about it :)

**Comment by rom1v** [comment]
> Right now, you implemented a fix client side which is retrying with different sizes

Nope, it's server-side: https://github.com/Genymobile/scrcpy/blob/faf4535487926853250ebe842c76a40e7b5f8ceb/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java#L112

**Comment by Valkhes** [comment]
Oh, indeed.
As it is not falling back to another max size when I launch the server with a max resolution too big, I was thinking it was in the client. It may be a problem on my side then, maybe I'm doing something wrong.

I'm closing the feature request as it is not relevant in fact.

Thanks a lot.
