### ISSUE TITLE
When multiple devices are connected on Windows 11, only one device window can be opened.

### ISSUE THREAD

**Issue by Helaer** [Genymobile/scrcpy#3280]
When two devices are connected at the same time, only one can be turned on, the other cannot be turned on, and vice versa.

Devices that can be turned on.
C:\Users\Administrator\Desktop\scrcpy-win64-v1.24>scrcpy -s N8K7N17821003173 -Vdebug
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
DEBUG: ADB device found:
DEBUG:     -->   (usb)      N8K7N17821003173            device  MHA_AL00
DEBUG:           (usb)      XPUDU17420002120            device  HUAWEI_CAZ_AL10
DEBUG: Device serial: N8K7N17821003173
DEBUG: Using server (portable): C:\Users\Administrator\Desktop\scrcpy-win64-v1.24\scrcpy-server
C:\Users\Administrator\Desktop\scrcpy-win64-v1.24\scrcpy-s... file pushed, 0 skipped. 35.1 MB/s (41159 bytes in 0.001s)
[server] INFO: Device: HUAWEI MHA-AL00 (Android 9)
[server] DEBUG: Using encoder: 'OMX.hisi.video.encoder.avc'
DEBUG: Server connected
DEBUG: Starting controller thread
DEBUG: Starting receiver thread
INFO: Renderer: direct3d
DEBUG: Trilinear filtering disabled (not an OpenGL renderer)
DEBUG: Using icon (portable): C:\Users\Administrator\Desktop\scrcpy-win64-v1.24\icon.png
INFO: Initial texture: 1080x1920
DEBUG: Starting demuxer thread

Devices that cannot be turned on.
C:\Users\Administrator\Desktop\scrcpy-win64-v1.24>scrcpy -s XPUDU17420002120 -Vdebug
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
DEBUG: ADB device found:
DEBUG:           (usb)      N8K7N17821003173            device  MHA_AL00
DEBUG:     -->   (usb)      XPUDU17420002120            device  HUAWEI_CAZ_AL10
DEBUG: Device serial: XPUDU17420002120
DEBUG: Using server (portable): C:\Users\Administrator\Desktop\scrcpy-win64-v1.24\scrcpy-server
C:\Users\Administrator\Desktop\scrcpy-win64-v1.24\scrcpy-s... file pushed, 0 skipped. 33.6 MB/s (41159 bytes in 0.001s)
[server] INFO: Device: HUAWEI HUAWEI CAZ-AL10 (Android 7.0)
[server] DEBUG: Using encoder: 'OMX.qcom.video.encoder.avc'
[server] DEBUG: Screen streaming stopped
[server] DEBUG: Device message sender stopped
[server] DEBUG: Controller stopped
DEBUG: Interrupting socket
DEBUG: Server disconnected
DEBUG: Server terminated
ERROR: Server connection failed

**Comment by rom1v** [comment]
It is probably not related to the number of devices :/

**Comment by Helaer** [comment]
> 它可能与设备数量无关：/

If only one device is turned on, all can be turned on. If it is turned on at the same time, only one device can be turned on. This is the case with two Windows 11 computers.

**Comment by rom1v** [comment]
Can you record two devices simultaneously without mirroring:

```
scrcpy -s <device1> --no-display --record device1.mp4
scrcpy -s <device2> --no-display --record device2.mp4
```

Can you mirror two devixes simultaneously if you reduce the resolution (`-m800`)?
