### ISSUE TITLE
Adb connect _gateway:5555 no longer works with Android 12

### ISSUE THREAD

**Issue by OpenFoam-User** [Genymobile/scrcpy#3287]
Hello,

[x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md)
[x] I have checked if there is already a similar issue.

System info:

* Ubuntu 20.04
```
scrcpy --version
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>

Dependencies (compiled / linked):
 - SDL: 2.0.8 / 2.0.8
 - libavcodec: 57.107.100 / 57.107.100
 - libavformat: 57.83.100 / 57.83.100
 - libavutil: 55.78.100 / 55.78.100
 - libavdevice: 57.10.100 / 57.10.100
 - libusb: - / 1.0.21

```
* Device model: Samsung Galaxy A71
* Installation method: via snap
* Android version: 12

**Note**:  I am using my phone as a hotspot and connecting to it via tcpip

## The issue:
Before upgrading my phone OS to Android 12, I used to connect to it as follows:

```
adb connect _gateway:5555
```

However, yesterday, I have upgraded my phone OS to Android 12 and I can no longer use that command to connect. I get the following error:

```
unable to connect to _gateway:5555: Name or service not known
```

The only workaround I found so far is to go to the Phone settings > About > Status Information  and checking for the IP address.

The IP address is something like: `10.175.221.108` but it keeps changing from time to time. 

Why is `_gateway` is not working as is in previous Android versions? (reminder: I am using the phone as a hotspot, so _gateway should be resolved to the IP address of the phone)

Thanks

**Comment by rom1v** [comment]
I have no idea, I didn't even know about `_gateway`. Since it's about adb, not scrcpy, you should ask somewhere else (stackoverflow?).
