### ISSUE TITLE
--stay-awake no longer working on Android 12

### ISSUE THREAD

**Issue by alphaTECH-Aus** [Genymobile/scrcpy#3288]
- [ X ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ X ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 11
 - scrcpy version: 1.24
 - installation method: Windows
 - device model: Galaxy S20 FE 5G
 - Android version: 12

**Describe the bug**
--stay-awake does not do what it should. It worked fine on my old Galaxy A70, however the phone ignores it and sleeps on my Galaxy S20 FE 5G.

`scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
INFO: Connecting to 192.168.1.7:5555...
INFO: Connected to 192.168.1.7:5555
C:\Program Files, unprotected\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 47.3 MB/s (41159 bytes in 0.001s)
[server] INFO: Device: samsung SM-G781B (Android 12)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
[server] INFO: Device screen turned off
[server] INFO: Forcing screen off
`

App shortcut is: "C:\Program Files, unprotected\scrcpy\scrcpy.exe" --tcpip=192.168.1.7 --max-fps 30 --turn-screen-off --power-off-on-close --stay-awake

**Comment by rom1v** [comment]
Stay awake only works when the device is plugged in: https://github.com/Genymobile/scrcpy#stay-awake

This is the behaviour of the Android option used by scrcpy (named `stay_on_while_plugged_in`).
