### ISSUE TITLE
Cant mirror protected contents in my android 12 phone

### ISSUE THREAD

**Issue by freefire1203** [Genymobile/scrcpy#3290]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version:1.24
 - installation method:Windows release
 - device model: SSamsung galaxy m21 
 - Android version: 12

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
That's expected: #2129
