### ISSUE TITLE
Failed to execute:[E:\sdk\platform-tools],[start-server]

### ISSUE THREAD

**Issue by withyi9223** [Genymobile/scrcpy#3302]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
> E:\sdk\platform-tools

You set the ADB environment variable to a wrong value.

Either don't set it (it will use the adb bundled the scrcpy release), or if you have specific needs to use a custom adb, set ADB to the adb exdcutable path (`E:\sdk\platform-tools\adb.exe` in your case).

**Comment by withyi9223** [comment]
thanks，i had sloved it
