### ISSUE TITLE
[Question] Forcing high FPS

### ISSUE THREAD

**Issue by Roni-Rachmani** [Genymobile/scrcpy#3305]
Is there any way to force high FPS? 

Recordings with low movement come out as ~5fps with skipped frames, especially with animations like button presses

Might `--codec-options=key[:type]=value[,...]` help?

Thank you for all the hard work! This is simply amazing! :)

**Comment by rom1v** [comment]
> Recordings with low movement come out as ~5fps

One new frame is produced whenever the scrzen content changes (i.e. the surface is _damaged_), so if you play a 25 fps video, you'll get 25 fps. If nothing changes on the screen, you'll get 0 fps. If a lot of changes happen quickly, you get high FPS (e.g. 90 fps, depznding on your device).

> with skipped frames

How do you observe these skipped frames?

**Comment by Roni-Rachmani** [comment]
> How do you observe these skipped frames?

That was the question I needed to hear! when editing in **Adobe Premiere Pro**, apparently the user needs to select the following:

Video → MPEG Source Settings → Variable Frame Rate Mode → Smooth Video Motion

Thank you! 

[Premiere Pro 12.0.1 Update: Variable Frame Rate](https://premierebro.com/blog/premiere-pro-1201-update-variable-frame-rate-and-new-features#:~:text=Variable%20Frame%20Rate%20(VFR)%20simply,Rate%20using%20applications%20like%20Handbrake.)
