### ISSUE TITLE
Sound problem

### ISSUE THREAD

**Issue by DamienBuchet** [Genymobile/scrcpy#3308]
I don't know why and how, but when I connected my phone to my PC via TCPIP and with the screen off, it put the volume to the maximum. Pretty embarrassing. I always verify the sound is off by playing some music before class, and it was.
It was a good idea to hide the screen and display it only on the PC, but maybe do the same for the sound.
Anyway, the class have had a few seconds of free music, and it'll be a nice anecdote.

**Comment by rom1v** [comment]
> it put the volume to the maximum

Scrcpy does not touch the volume (unless you press volume shortcuts).

It's probably independent of scrcpy (maybe your music app reacted to some device state change or something).

**Comment by DamienBuchet** [comment]
That's what I was thinking, but I had no apps running when I connected it, and I never had this problem. It was just the first time I used the option to hide the screen.
For just one case, I don't think it's really important to search for a problem, but sound managment could be a good thing to add.
