### ISSUE TITLE
Disabling stay awake after not returning to default state

### ISSUE THREAD

**Issue by erhan-** [Genymobile/scrcpy#3309]
Hey everyone,

Thanks for this great tool and all the effort put into this.

I have used this for a while but now my phone is kind of stuck in the stay awake mode which means that the screen stays on when I am charging the device for example.
What is the ADB command to revert this setting to default Android behaviour?

Thanks for your help

Best regards,

Erhan

**Comment by rom1v** [comment]
```
adb shell settings put global stay_on_while_plugged_in 0
```

There is also an option `Stay awake (screen will never sleep while charging)` in developer options.

Note that in theory, scrcpy should revert this value on close (even if you unplug the device).
But on some devices (like on my Nexus 5), the cleanup process is killed before it has a chance to reset the value when the device is unplugged.

**Comment by erhan-** [comment]
Thank you very much for your help Romain. That did it. Have a nice week and life!
