### ISSUE TITLE
Scrcpy works when using the terminal, but not in a shell script...

### ISSUE THREAD

**Issue by kneckergit** [Genymobile/scrcpy#3311]
Hi everyone,
so, this is less of a bug report, but more of a noob question, I guess? Let's see:

Using scrcpy via WLAN works quite fine, when executing the following commands via terminal: 
```
adb tcpip 5555
adb connect [MY-IP-HERE]:5555
scrcpy -e -b 20M -S
```

Et voila, the screen is mirrored as supposed.
BUT if I put this very command string in an executable shell script:

```
#!/bin/bash
adb tcpip 5555
adb connect [MY-IP-HERE]:5555
scrcpy -e -b 20M -S
```

The scrcpy command replies “ERROR: Server connection failed”

Anyone knows, why this happens? I am a bit confused. The script invokes literally the exact commands, I enter manually…
With regards
Julius

**Comment by rom1v** [comment]
It's probably the difference between script VS non-script, but a timing race condition.

Note that there is a `--tcpip` command line option available: https://github.com/Genymobile/scrcpy#automatic

**Comment by kneckergit** [comment]
You were right about the timing race condition. When I add a sleep of just one second, it works fine:

echo "Opening TCP IP Port for adb. Device must be attached via USB for first time."
adb tcpip 5555
echo "Rooting adb to Android Device via WLAN - make sure, MAC and IP is static!"
adb connect 192.168.0.14:5555
**sleep 1**
echo "Starting scrcpy"
scrcpy --tcpip=192.168.0.14 -b 20M -S

Thanks!
