### ISSUE TITLE
Enter key doesn't work in all apps

### ISSUE THREAD

**Issue by DatafoxChris** [Genymobile/scrcpy#3320]
Inside F1TV Pro app the enter key doesn't press the selected button, but the button does respond by turning slightly darker for a short moment... 

Any suggestions ?

**Comment by DatafoxChris** [comment]
Would it be possible to add a shortcut to press the OK button (the button in the middle of the four direction-buttons on the remote ?

**Comment by rom1v** [comment]
Scrcpy injects the <kbd>Enter</kbd> key, how the app reacts is app-specific (and can sometimes be configured, see https://github.com/Genymobile/scrcpy/issues/3157#issuecomment-1122856362).

> Would it be possible to add a shortcut to press the OK button

Nope, scrcpy injects keys or mouse events, it could not access the app layout (easily and with good performances).
