### ISSUE TITLE
Black screen on secure apps after updating to Android 12

### ISSUE THREAD

**Issue by ksio89** [Genymobile/scrcpy#3323]
**Describe the bug**

I was able to take screenshots/record videos on secure apps on Android 11, but after upgrading my device to 12, all I get is a black screen in them. By secure, I mean the ones which say _**"Can't take screenshot due to security policy."**_ when you attempt to do that. At the moment, is there a workaround to bypass the block on Android 12? 

**Environment**
 - OS: Windows 10 Pro 19044.1741
 - scrcpy version: 1.24
 - installation method: Windows release
 - device model: Samsung Galaxy A71
 - Android version: 12 (One UI 4.1)

**Comment by rom1v** [comment]
That's expected, the restriction has been applied to the _shell_ user in Android 12. See #2129.

**Comment by ksio89** [comment]
That's a shame, I would have stayed on Android 11 if I knew that, screw Google. They blocked call recording as well on 12, so much BS. Thanks anyway.

**Comment by NomarCub** [comment]
@rom1v is there any workaround, with scrcpy or some other method?

**Comment by domasb2005** [comment]
> @rom1v is there any workaround, with scrcpy or some other method?

Need that too.. Have you found something? There is a method with virtualisation, but you have to reinstall the app.
# https://www.ticktechtold.com/fix-record-screen-protected-videos/#method-1-install-restricted-app-on-virtual-space:~:text=Conclusion-,Method%201%3A%20Install%20Restricted%20App%20on%20Virtual%20Space,-We%20use%20this

**Comment by vncastanheira** [comment]
Same here. I understand maybe why they did this but it's a bit annoying. I'll be watching the thread if anyone finds a way to bypass this.

**Comment by RiggiG** [comment]
Root users may also use [this fork](https://github.com/RiggiG/scrcpy-root/tree/dev) which simply runs the scrcpy-server as the system user: https://github.com/Genymobile/scrcpy/issues/3049#issuecomment-1603612740
