### ISSUE TITLE
Some error message when closing window in windows

### ISSUE THREAD

**Issue by npes87184** [Genymobile/scrcpy#333]
Hi,

When I close window in windows, it will show:
```
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
```
There may be some problem in closing resource.

btw, scrcpy works well on windows.

```
PS C:\Users\YuChenLin\Downloads\scrcpy-win64> .\scrcpy.exe
scrcpy-server.jar: 1 file pushed.
INFO: Initial texture: 1080x2280
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
PS C:\Users\YuChenLin\Downloads\scrcpy-win64> .\scrcpy.exe --version
scrcpy v1.5

dependencies:
 - SDL 2.0.9
 - libavcodec 58.18.100
 - libavformat 58.12.100
 - libavutil 56.14.100
PS C:\Users\YuChenLin\Downloads\scrcpy-win64>


windows 10 v1803
```
Thanks,
yuchenlin

**Comment by rom1v** [comment]
Thank you. Fixed on `master`.

**Comment by rom1v** [comment]
@curiousrom it is fixed in `master` so the fix will be included in the next release (https://github.com/Genymobile/scrcpy/commit/2876463d394c3bc4dc239a605e65ebab75598353).

> it does not say how to close scrcpy

Just close the window. You can even unplug the cable or disconnect `adb`.
