### ISSUE TITLE
how to use blank flash on moto g9 play that gave hardbrick

### ISSUE THREAD

**Issue by vc655767** [Genymobile/scrcpy#3330]
when I connect it appears waiting device and I already have the drivers

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md

**Comment by vc655767** [comment]
when I connect it appears waiting device and I already have the drivers?

**Comment by rom1v** [comment]
> I connect it appears waiting device 

Where? When you type which command? What's the whole output?

**Comment by vc655767** [comment]
saya tidak menaip sebarang arahan tidak saya menggunakan denyar blankflash adalah automatik

**Comment by rom1v** [comment]
Please write in English.

google translate:
> i didn't type any commands no i use blankflash flash is automatic

OK, so your problem has nothing to do with scrcpy?

**Comment by rom1v** [comment]
The project on which you are reporting an issue here.

**Comment by vc655767** [comment]
has to do with scrapy
