### ISSUE TITLE
Scrcpy cannot launch with a set environment adb

### ISSUE THREAD

**Issue by EvatsugDnalloR** [Genymobile/scrcpy#3332]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Winsdows 11 21H2 22000.708
 - scrcpy version: 1.24
 - installation method: Windows release
 - device model: Samsung S21 Ultra
 - Android version: 11

**Describe the bug**
With a set environment of adb path scrcpy cannot launch, where adb functions normal
I have tried to use set ADB=path command but it doesn't help for this scenario as the adb environment has alrealdy installed and functioned well
Android Debug Bridge version 1.0.41
Version 33.0.1-8253317
Installed as D:\Android-Development\Android\Sdk\platform-tools\adb.exe

**Terminal Output**
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
ERROR: CreateProcessW() error 5
ERROR: Failed to execute: [D:\Android-Development\Android\Sdk\platform-tools], [start-server]
ERROR: Could not execute "adb start-server"
ERROR: Could not start adb daemon
ERROR: Server connection failed

**Comment by rom1v** [comment]
Set ADB=D:\Android-Development\Android\Sdk\platform-tools\adb.exe

**Comment by EvatsugDnalloR** [comment]
> Set ADB=D:\Android-Development\Android\Sdk\platform-tools\adb.exe

It still doesn't work in powershell, but when i tried in cmd it works...

**Comment by rom1v** [comment]
> It still doesn't work in powershell

The point is that `\adb.exe` was missing. Set it the same wah you did with the wrong path, for example from the settings.

In PowerShell, you could use the syntax:

```powershell
$env:ADB = 'D:\Android-Development\Android\Sdk\platform-tools\adb.exe'
```
