### ISSUE TITLE
Unusably laggy when using wireless debugging

### ISSUE THREAD

**Issue by saikat0511** [Genymobile/scrcpy#3340]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Arch Linux
 - scrcpy version: 1.23
 - installation method: pacman
 - device model: Poco X3
 - Android version: 12.1

**Describe the bug**
Works fine when using adb over USB, but over wireless ADB its laggy and unusable

Attaching a small clip comparing the performance between wired and wireless

https://user-images.githubusercontent.com/57610828/174469851-a96c5a05-5b28-479a-8d6c-de33e6f363b2.mp4

**Comment by rom1v** [comment]
The wifi performance depends on the device and your wifi network. If performance is bad, you could reduce the definition and bitrate (but the quality will be lower):

```bash
scrcpy -b2M
```

On good devices and good networks, the default bitrate (8M, or even above) at full definition (e.g; 3120×1440), it works perfectly. But if either on "poor" devices (e.g. my Nexus 5 or Galaxy A3), or a poor wifi network, it's unusable.

**Comment by saikat0511** [comment]
Its somewhat better after limiting the bitrate. I am guessing my network is trash. Thanks for the tip, closing...
