### ISSUE TITLE
scrcpy freezes when left 'idle' for a few seconds

### ISSUE THREAD

**Issue by Andoumeda** [Genymobile/scrcpy#3343]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).

- [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Kubuntu 22.04 (KDE Plasma 5.24.4)
 - scrcpy version: 1.24
 - installation method: apt
 - device model: Samsung A52 (SM-A525M/DS)
 - Android version: 12

**Describe the bug**

I have scrcpy connected via TCP/IP, and it works relatively well, with low latency; but at the moment of not interacting for about 5 seconds, the mirrored screen of the phone no longer responds.

I used the FPS counter which is activated with _MOD + i_, and when there are about ten successive 0 fps, the freeze happens.

**Comment by Andoumeda** [comment]
> Currently, v1.24 is not packaged on Debian/Ubuntu.

I saw it on the download page, but when I installed the latest version for Ubuntu (v1.21), it also gave me problems connecting wirelessly, and this version no longer give me issues :D

> If you record, is the recorded file also frozen?

Now I tried it, and it turns out that it doesn't freeze at all, but it takes about 5 seconds between each action, using the `--record` argument or without it, still has high latency.

**Comment by rom1v** [comment]
OK so it's just wireless performance. See https://github.com/Genymobile/scrcpy/issues/3340#issuecomment-1159644078.

**Comment by Andoumeda** [comment]
It seems that it was, thank you very much for the help!
