### ISSUE TITLE
Scrcpy closes instanly

### ISSUE THREAD

**Issue by meroz92** [Genymobile/scrcpy#3350]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: 1.24
 - installation method: Windows release
 - device model: Huawei P30 lite
 - Android version: 10

When I launch scrcpy it closes inmediatly after it starts, but it doesn´t appear any code error

```
C:\V1.24>scrcpy
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
C:\V1.24\scrcpy-server: 1 file pushed, 0 skipped. 28.0 MB/s (41159 bytes in 0.001s)
[server] INFO: Device: HUAWEI MAR-LX3Bm (Android 10)
INFO: Renderer: direct3d
INFO: Initial texture: 808x1728
```

**Comment by rom1v** [comment]
Try with another encoder: https://github.com/Genymobile/scrcpy#encoder

**Comment by meroz92** [comment]
I already tried with each one of the three encoder but still happen the same
I show you the list of encoder that are available

C:\V1.24>scrcpy --encoder _
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
C:\V1.24\scrcpy-server: 1 file pushed, 0 skipped. 47.1 MB/s (41159 bytes in 0.001s)
[server] INFO: Device: HUAWEI MAR-LX3Bm (Android 10)
INFO: Renderer: direct3d
INFO: Initial texture: 808x1728
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
com.genymobile.scrcpy.InvalidEncoderException: There is no encoder having name '_"
        at com.genymobile.scrcpy.ScreenEncoder.createCodec(ScreenEncoder.java:222)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:83)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:101)
        at com.genymobile.scrcpy.Server.main(Server.java:335)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
[server] ERROR: Try to use one of the available encoders:
[server] ERROR:     scrcpy --encoder 'OMX.hisi.video.encoder.avc'
[server] ERROR:     scrcpy --encoder 'c2.android.avc.encoder'
[server] ERROR:     scrcpy --encoder 'OMX.google.h264.encoder'

**Comment by meroz92** [comment]
This is what happens when I use scrcpy -Vdebug

C:\V1.24>scrcpy -Vdebug
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
DEBUG: ADB device found:
DEBUG:     -->   (usb)      X9F4C19C10002490            device  MAR_LX3Bm
DEBUG: Device serial: X9F4C19C10002490
DEBUG: Using server (portable): C:\V1.24\scrcpy-server
C:\V1.24\scrcpy-server: 1 file pushed, 0 skipped. 21.6 MB/s (41159 bytes in 0.002s)
[server] INFO: Device: HUAWEI MAR-LX3Bm (Android 10)
DEBUG: Server connected
DEBUG: Starting controller thread
DEBUG: Starting receiver thread
[server] DEBUG: Using encoder: 'OMX.hisi.video.encoder.avc'
INFO: Renderer: direct3d
DEBUG: Trilinear filtering disabled (not an OpenGL renderer)
DEBUG: Using icon (portable): C:\V1.24\icon.png
INFO: Initial texture: 808x1728
DEBUG: Starting demuxer thread
[server] DEBUG: Controller stopped

C:\V1.24>[server] DEBUG: Screen streaming stopped
[server] DEBUG: Device message sender stopped

**Comment by meroz92** [comment]
And this is de adb logcat

C:\V1.24>adb logcat
--------- beginning of crash
06-22 11:22:58.208  5586  5727 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 5727 (bt_main_thread), pid 5586 (droid.bluetooth)
06-22 11:22:58.389 11390 11390 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
06-22 11:22:58.389 11390 11390 F DEBUG   : Build fingerprint: 'HUAWEI/MAR-LX3Bm/HWMAR:10/HUAWEIMAR-L03B/10.0.0.285C212:user/release-keys'
06-22 11:22:58.389 11390 11390 F DEBUG   : Revision: '0'
06-22 11:22:58.389 11390 11390 F DEBUG   : ABI: 'arm64'
06-22 11:22:58.390 11390 11390 F DEBUG   : Timestamp: 2022-06-22 11:22:58-0600
06-22 11:22:58.390 11390 11390 F DEBUG   : pid: 5586, tid: 5727, name: bt_main_thread  >>> com.android.bluetooth <<<
06-22 11:22:58.390 11390 11390 F DEBUG   : uid: 1002
06-22 11:22:58.390 11390 11390 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
06-22 11:22:58.391 11390 11390 F DEBUG   :     x0  0000000000000000  x1  000000000000165f  x2  0000000000000006  x3  00000071d7bfb5a0
06-22 11:22:58.391 11390 11390 F DEBUG   :     x4  7472617473657220  x5  7472617473657220  x6  7472617473657220  x7  6f6f7465756c6220
06-22 11:22:58.391 11390 11390 F DEBUG   :     x8  00000000000000f0  x9  8d52e00f66d55c70  x10 0000000000000001  x11 0000000000000000
06-22 11:22:58.391 11390 11390 F DEBUG   :     x12 fffffff0fffffbdf  x13 797265766f636572  x14 0000000000000010  x15 00000072dbce439a
06-22 11:22:58.391 11390 11390 F DEBUG   :     x16 00000072dbce9908  x17 00000072dbcc91c0  x18 00000071d72c0000  x19 00000000000015d2
06-22 11:22:58.391 11390 11390 F DEBUG   :     x20 000000000000165f  x21 00000000ffffffff  x22 00000071d7bfc020  x23 000000723f051df8
06-22 11:22:58.391 11390 11390 F DEBUG   :     x24 00000071d7bfc020  x25 00000071d7bfbd50  x26 00000071d7bfc020  x27 00000071d8f76020
06-22 11:22:58.391 11390 11390 F DEBUG   :     x28 00000000166f0e18  x29 00000071d7bfb640
06-22 11:22:58.391 11390 11390 F DEBUG   :     sp  00000071d7bfb580  lr  00000072dbc7e040  pc  00000072dbc7e06c
06-22 11:22:58.474 11390 11390 F DEBUG   :
06-22 11:22:58.474 11390 11390 F DEBUG   : backtrace:
06-22 11:22:58.474 11390 11390 F DEBUG   :       #00 pc 000000000006f06c  /apex/com.android.runtime/lib64/bionic/libc.so (abort+160) (BuildId: dd7a905195762d00f4b732c4fa25226a)
06-22 11:22:58.474 11390 11390 F DEBUG   :       #01 pc 00000000003412f8  /system/lib64/libbluetooth.so (hw_hisi_btm_vendor_specific_evt(unsigned char*)+832) (BuildId: 4ab1982c7a33c34e6fcc83a45c41c570)
06-22 11:22:58.474 11390 11390 F DEBUG   :       #02 pc 00000000001d63cc  /system/lib64/libbluetooth.so (btm_vendor_specific_evt(unsigned char*, unsigned char)+64) (BuildId: 4ab1982c7a33c34e6fcc83a45c41c570)
06-22 11:22:58.474 11390 11390 F DEBUG   :       #03 pc 00000000001ead80  /system/lib64/libbluetooth.so (btu_hcif_process_event(unsigned char, BT_HDR*)+264) (BuildId: 4ab1982c7a33c34e6fcc83a45c41c570)
06-22 11:22:58.474 11390 11390 F DEBUG   :       #04 pc 00000000001ed89c  /system/lib64/libbluetooth.so (btu_hci_msg_process(BT_HDR*) [clone .cfi]+68) (BuildId: 4ab1982c7a33c34e6fcc83a45c41c570)
06-22 11:22:58.474 11390 11390 F DEBUG   :       #05 pc 00000000000a05c4  /system/lib64/libchrome.so (base::debug::TaskAnnotator::RunTask(char const*, base::PendingTask*)+188) (BuildId: 06fd6538d165bb63ac115766de18116c)
06-22 11:22:58.475 11390 11390 F DEBUG   :       #06 pc 00000000000bfb88  /system/lib64/libchrome.so (base::MessageLoop::RunTask(base::PendingTask*)+308) (BuildId: 06fd6538d165bb63ac115766de18116c)
06-22 11:22:58.475 11390 11390 F DEBUG   :       #07 pc 00000000000bff30  /system/lib64/libchrome.so (base::MessageLoop::DoWork()+476) (BuildId: 06fd6538d165bb63ac115766de18116c)
06-22 11:22:58.475 11390 11390 F DEBUG   :       #08 pc 00000000000c16a8  /system/lib64/libchrome.so (base::MessagePumpDefault::Run(base::MessagePump::Delegate*)+184) (BuildId: 06fd6538d165bb63ac115766de18116c)
06-22 11:22:58.475 11390 11390 F DEBUG   :       #09 pc 00000000000e32b8  /system/lib64/libchrome.so (base::RunLoop::Run()+84) (BuildId: 06fd6538d165bb63ac115766de18116c)
06-22 11:22:58.478 11390 11390 F DEBUG   :       #10 pc 0000000000154458  /system/lib64/libbluetooth.so (bluetooth::common::MessageLoopThread::Run(std::__1::promise<void>)+264) (BuildId: 4ab1982c7a33c34e6fcc83a45c41c570)
06-22 11:22:58.478 11390 11390 F DEBUG   :       #11 pc 0000000000154238  /system/lib64/libbluetooth.so (bluetooth::common::MessageLoopThread::RunThread(bluetooth::common::MessageLoopThread*, std::__1::promise<void>) [clone .cfi]+44) (BuildId: 4ab1982c7a33c34e6fcc83a45c41c570)
06-22 11:22:58.479 11390 11390 F DEBUG   :       #12 pc 00000000001542c8  /system/lib64/libbluetooth.so (_ZNSt3__114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEPFvPN9bluetooth6common17MessageLoopThreadENS_7promiseIvEEESA_SC_EEEEEPvSG_.cfi+96) (BuildId: 4ab1982c7a33c34e6fcc83a45c41c570)
06-22 11:22:58.479 11390 11390 F DEBUG   :       #13 pc 00000000000ce1c0  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36) (BuildId: dd7a905195762d00f4b732c4fa25226a)
06-22 11:22:58.479 11390 11390 F DEBUG   :       #14 pc 0000000000070ba8  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: dd7a905195762d00f4b732c4fa25226a)
06-25 08:14:51.375 11372 11372 E AndroidRuntime: FATAL EXCEPTION: main
06-25 08:14:51.375 11372 11372 E AndroidRuntime: PID: 11372
06-25 08:14:51.375 11372 11372 E AndroidRuntime: com.genymobile.scrcpy.InvalidEncoderException: There is no encoder having name '_"
06-25 08:14:51.375 11372 11372 E AndroidRuntime:        at com.genymobile.scrcpy.ScreenEncoder.createCodec(ScreenEncoder.java:222)
06-25 08:14:51.375 11372 11372 E AndroidRuntime:        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:83)
06-25 08:14:51.375 11372 11372 E AndroidRuntime:        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
06-25 08:14:51.375 11372 11372 E AndroidRuntime:        at com.genymobile.scrcpy.Server.scrcpy(Server.java:101)
06-25 08:14:51.375 11372 11372 E AndroidRuntime:        at com.genymobile.scrcpy.Server.main(Server.java:335)
06-25 08:14:51.375 11372 11372 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
06-25 08:14:51.375 11372 11372 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
06-25 08:18:50.759 12414 12414 E AndroidRuntime: FATAL EXCEPTION: main
06-25 08:18:50.759 12414 12414 E AndroidRuntime: PID: 12414
06-25 08:18:50.759 12414 12414 E AndroidRuntime: com.genymobile.scrcpy.InvalidEncoderException: There is no encoder having name '_"
06-25 08:18:50.759 12414 12414 E AndroidRuntime:        at com.genymobile.scrcpy.ScreenEncoder.createCodec(ScreenEncoder.java:222)
06-25 08:18:50.759 12414 12414 E AndroidRuntime:        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:83)
06-25 08:18:50.759 12414 12414 E AndroidRuntime:        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
06-25 08:18:50.759 12414 12414 E AndroidRuntime:        at com.genymobile.scrcpy.Server.scrcpy(Server.java:101)
06-25 08:18:50.759 12414 12414 E AndroidRuntime:        at com.genymobile.scrcpy.Server.main(Server.java:335)
06-25 08:18:50.759 12414 12414 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
06-25 08:18:50.759 12414 12414 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
06-25 08:28:08.089 14365 14365 E AndroidRuntime: FATAL EXCEPTION: main
06-25 08:28:08.089 14365 14365 E AndroidRuntime: PID: 14365
06-25 08:28:08.089 14365 14365 E AndroidRuntime: com.genymobile.scrcpy.InvalidEncoderException: There is no encoder having name '_"
06-25 08:28:08.089 14365 14365 E AndroidRuntime:        at com.genymobile.scrcpy.ScreenEncoder.createCodec(ScreenEncoder.java:222)
06-25 08:28:08.089 14365 14365 E AndroidRuntime:        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:83)
06-25 08:28:08.089 14365 14365 E AndroidRuntime:        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
06-25 08:28:08.089 14365 14365 E AndroidRuntime:        at com.genymobile.scrcpy.Server.scrcpy(Server.java:101)
06-25 08:28:08.089 14365 14365 E AndroidRuntime:        at com.genymobile.scrcpy.Server.main(Server.java:335)
06-25 08:28:08.089 14365 14365 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
06-25 08:28:08.089 14365 14365 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
06-25 08:43:26.897 21862 21862 E AndroidRuntime: FATAL EXCEPTION: main
06-25 08:43:26.897 21862 21862 E AndroidRuntime: PID: 21862
06-25 08:43:26.897 21862 21862 E AndroidRuntime: com.genymobile.scrcpy.InvalidEncoderException: There is no encoder having name '_"
06-25 08:43:26.897 21862 21862 E AndroidRuntime:        at com.genymobile.scrcpy.ScreenEncoder.createCodec(ScreenEncoder.java:222)
06-25 08:43:26.897 21862 21862 E AndroidRuntime:        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:83)
06-25 08:43:26.897 21862 21862 E AndroidRuntime:        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
06-25 08:43:26.897 21862 21862 E AndroidRuntime:        at com.genymobile.scrcpy.Server.scrcpy(Server.java:101)
06-25 08:43:26.897 21862 21862 E AndroidRuntime:        at com.genymobile.scrcpy.Server.main(Server.java:335)
06-25 08:43:26.897 21862 21862 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
06-25 08:43:26.897 21862 21862 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
06-25 08:51:54.465 24774 24774 E AndroidRuntime: FATAL EXCEPTION: main
06-25 08:51:54.465 24774 24774 E AndroidRuntime: PID: 24774
06-25 08:51:54.465 24774 24774 E AndroidRuntime: com.genymobile.scrcpy.InvalidEncoderException: There is no encoder having name '_"
06-25 08:51:54.465 24774 24774 E AndroidRuntime:        at com.genymobile.scrcpy.ScreenEncoder.createCodec(ScreenEncoder.java:222)
06-25 08:51:54.465 24774 24774 E AndroidRuntime:        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:83)
06-25 08:51:54.465 24774 24774 E AndroidRuntime:        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
06-25 08:51:54.465 24774 24774 E AndroidRuntime:        at com.genymobile.scrcpy.Server.scrcpy(Server.java:101)
06-25 08:51:54.465 24774 24774 E AndroidRuntime:        at com.genymobile.scrcpy.Server.main(Server.java:335)
06-25 08:51:54.465 24774 24774 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
06-25 08:51:54.465 24774 24774 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
06-25 15:13:57.441 16854 16854 E AndroidRuntime: FATAL EXCEPTION: main
06-25 15:13:57.441 16854 16854 E AndroidRuntime: PID: 16854
06-25 15:13:57.441 16854 16854 E AndroidRuntime: com.genymobile.scrcpy.InvalidEncoderException: There is no encoder having name '_"
06-25 15:13:57.441 16854 16854 E AndroidRuntime:        at com.genymobile.scrcpy.ScreenEncoder.createCodec(ScreenEncoder.java:222)
06-25 15:13:57.441 16854 16854 E AndroidRuntime:        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:83)
06-25 15:13:57.441 16854 16854 E AndroidRuntime:        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
06-25 15:13:57.441 16854 16854 E AndroidRuntime:        at com.genymobile.scrcpy.Server.scrcpy(Server.java:101)
06-25 15:13:57.441 16854 16854 E AndroidRuntime:        at com.genymobile.scrcpy.Server.main(Server.java:335)
06-25 15:13:57.441 16854 16854 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
06-25 15:13:57.441 16854 16854 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

**Comment by meroz92** [comment]
I finally found the problem

First I open my Windows Event Viewer 

![inkerror](https://user-images.githubusercontent.com/108159336/175792590-65021c46-23d9-428e-8a4b-1e65e293832e.jpg)

Then I realize that the error module was d3d9.dll thas is part of DirectX
the only thing that I did whas copy that file (d3d9.dll) from another PC and paste in the folder of scrcpy

And then everything works

I hope this could help more people with this problem
