### ISSUE TITLE
adb: error: connect failed: no devices/emulators found

### ISSUE THREAD

**Issue by dirtygardner** [Genymobile/scrcpy#336]
[TERMINAL]
`uname -a`: Linux debian 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
`lsb_release -a`: Debian GNU/Linux 9.6 (stretch)
`scrcpy -v` : scrcpy 1.5

[DEVICE] `Settings->System->About phone`
Model: SM-G900R4
Android version: 8.1.0
LineageOS version: 15.1-20181113-NIGHTLY-klte

[TERMINAL]
`scrcpy`
`adb: error: connect failed: no devices/emulators found`
`ERROR: "adb push" returned with value 1`

**Comment by dirtygardner** [comment]
Change USB Settings: `Settings->Connected devices->USB->Use USB to: Charge this device`
If it is set to `Transfer files` the above error occurs.

**Comment by dirtygardner** [comment]
`
testing
testing
testing
`

**Comment by rom1v** [comment]
That's still weird, it should work in any of these modes.

**Comment by leandro-lucarella-sociomantic** [comment]
I have this issue using the snap package, and it doesn't go away when changing USB mode (as expected). I guess is some missing permission in the snap.

**Comment by leandro-lucarella-sociomantic** [comment]
`sudo snap connect scrcpy:adb-support :adb-support` this worked for me. Reference: https://github.com/sisco311/scrcpy-snap/issues/4

**Comment by Light--** [comment]
> `sudo snap connect scrcpy:adb-support :adb-support` this worked for me. Reference: [sisco311/scrcpy-snap#4](https://github.com/sisco311/scrcpy-snap/issues/4)

error: snap "scrcpy" has no plug named "adb-support"
