### ISSUE TITLE
CANT CONTROL SCRCPY ON LANDSCAPING APPS

### ISSUE THREAD

**Issue by shmackiii** [Genymobile/scrcpy#3362]
When I watch youtube on fullscreen which is landscape mouse cannot be detected  it tells me this in the command tab                   [server] WARN: Ignore touch event, it was generated for a different device size                                                                                  similar to some other apps                                                                                                                                                                       Hope you see this n help                                                                                                                                                                             I'm using          Device: itel itel W6002E (Android 9)

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/issues/1645
