### ISSUE TITLE
scrcpy only displays green screen when attempting to use with Samsung Galaxy A03

### ISSUE THREAD

**Issue by Ellexium** [Genymobile/scrcpy#3368]
When connecting the device to my computer and running scrcpy.exe the usual window pops up but the screen is completely green. I can control the device, go full screen, etc but it doesn't show anything else except this weird green screen.

This issue doesn't occur with Vysor or Teamviewer. I have previously connected and used several different android devices on the same set of computers with scrcpy and they worked just fine. I have tried several different cables, tried to connect wirelessly, disabled hardware accelerated tethering, adjusted the screen resolution with `scrcpy.exe -m (different numbers)` before starting scrcpy, replacing the SDL2.dll file with older versions of it self from previous releases of scrcpy, tried older releases of scrcpy and also tested it on different computers.

Something else that I also tried was switching between the different encoders available with `scrcpy --encoder (different encoders)` and each time the scrcpy window still remained green.

Here's an image of the problem: 

![green](https://user-images.githubusercontent.com/88605373/177470690-4b08f261-1168-4421-9676-18d1d3ce074b.PNG)

Additional info: scrcpy running on Windows 10 Pro
Android device: Samsung Galaxy A03 (SM-A035F/DS) running on Android 11 (original OS, unmodified rom) 

Any help would be greatly appreciated.

**Comment by rom1v** [comment]
If you record (`scrvpy --record file.mp4`), is the resulting video green?

Also see #3299.

**Comment by Ellexium** [comment]
> If you record (`scrvpy --record file.mp4`), is the resulting video green?
> 
> Also see #3299.

Yeah the resulting video was green. After looking through the other issue you posted I connected the phone to WiFi so I could check for updates in Settings and there actually was one available. After installing the update and restarting the phone the problem went away. Thanks for the help!
