### ISSUE TITLE
WiGig 802.11ad/ay

### ISSUE THREAD

**Issue by creativeedge** [Genymobile/scrcpy#338]
Anyone's guess how this would perform latency wise on WiGig Devices?  Also can encoding be changed to support H265 (HEVC)?

**Comment by rom1v** [comment]
> Also can encoding be changed to support H265 (HEVC)?

No.

Are there any Android device able to hardware-encode to H.265?

When AV1 or H.265 will be widely available in hardware encoding, yes, _scrcpy_ will need it.

**Comment by creativeedge** [comment]
Thanks rom1v.  How about WiGig - do you think that will kill latency when it is available?

**Comment by rom1v** [comment]
> How about WiGig - do you think that will kill latency when it is available?

No idea.

Currently, the big problem with latency over wifi is packet loss for TCP (which blocks everything until the packet is resent). If your wifi is "ok" and you use a reasonable bitrate, the latency is not that high (`scrcpy -m800 -b2M`).

**Comment by creativeedge** [comment]
Thanks rom1v for everything.
