### ISSUE TITLE
Showing strange colors on black screen without mirroring actual image

### ISSUE THREAD

**Issue by robinsrk** [Genymobile/scrcpy#3381]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Arch linux
 - scrcpy version: 1.23
 - installation method: pacman
 - device model: Realme c3
 - Android version: 12.1 (Custom rom)

**Describe the bug**
When starting scrcpy, it shows black screen and strange colors on it. 

![image](https://user-images.githubusercontent.com/50480143/179074763-6bcffae5-73e7-49cc-9fb8-f3ca57ac674b.png)

It dosn't show any error in console

`scrcpy 1.23 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 63.4 MB/s (41123 bytes in 0.001s)
[server] INFO: Device: realme realme Monet (Android 12)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 22.1.3
INFO: Trilinear filtering enabled
INFO: Initial texture: 720x1600
`

**Comment by rom1v** [comment]
Probably an encoder bug. Try with a lower resolution (`scrcpy -m800`) or another [encoder](https://github.com/Genymobile/scrcpy#encoder).

**Comment by robinsrk** [comment]
> Probably an encoder bug. Try with a lower resolution (`scrcpy -m800`) or another [encoder](https://github.com/Genymobile/scrcpy#encoder).

Thansk man. that worked like a charm. just changed the encoder. thanks a lot man
