### ISSUE TITLE
Scrcpy with Pixel 6

### ISSUE THREAD

**Issue by Ren567** [Genymobile/scrcpy#3383]
Hi 
I am not a programmer however I joined here because I need some help to get scrcpy working with my Pixel 6 pro.

I premise that I have used this program so far with various Samsung devices without experiencing any problems, so I assume that scrcpy is installed correctly on my Pc.

On my new Pixel phone I have enabled "USB Debug" in the developer options... maybe I need to enable something else? I don't know so I ask you. The Android version is the 12th

scrcpy when it starts it generally opens and closes instantly so I can't see any error messages generated. If it helps I can tell you that the text lines are much more than normal operation... also only once it gave me the message: 'ERROR: "adb push" returned with value 1'.

I thank you in advance and hope you can help me.

**Comment by rom1v** [comment]
Please post the whole console output.

**Comment by Ren567** [comment]
THX!
How can I do this?

**Comment by rom1v** [comment]
Run `scrcpy-console.bat`, then copy paste the content of the terminal.

**Comment by Ren567** [comment]
I fixed the problem... I installed latest version and now it works perfectly...Sorry, I should have done this first. If I have more problems I will come back. Thanks for the help!

**Comment by Ren567** [comment]
Hi , it's me again.
I am reopening this post because a new problem has occurred. When I open some apps, like Amazon or Revolut bank or other shopping apps, Scrcpy darkens the screen and won't let me interact... trying to click randomly I can hit the buttons but using this is impossible .

**Comment by rom1v** [comment]
The apps which request to protect the screen could not be mirrored (this is enforced since Android 12, see #2129)

**Comment by Ren567** [comment]
Is there any way to disable this?

**Comment by rom1v** [comment]
Nope, unfortunately.
