### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by avboy1337** [Genymobile/scrcpy#3384]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. ubnutn20LTS]
 - scrcpy version: [e.g. Latest]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]

**Describe the bug**
compile error

ERROR: Malformed value in cross file variable prebuilt_libusb.

BUILD SUCCESSFUL in 846ms
35 actionable tasks: 18 executed, 17 up-to-date
platform-tools-33.0.1 found
SDL2-2.0.22 found
ffmpeg-win32-4.3.1 found
libusb-1.0.26 found
[ -d "build-win32" ] || ( mkdir "build-win32" && \
	meson "build-win32" \
		--cross-file cross_win32.txt \
		--buildtype release --strip -Db_lto=true \
		-Dcompile_server=false \
		-Dportable=true )

ERROR: Malformed value in cross file variable prebuilt_libusb.
make: *** [release.mk:78: build-win32] Error 1

**Comment by rom1v** [comment]
What commands did you execute exactly?

**Comment by avboy1337** [comment]
> What commands did you execute exactly?
> 
> On which commit exactly?

the latest commit
and i tried on ubuntu22LTS, the following tips is 
```
app/meson.build:149:4: ERROR: C shared or static library 'msys-usb-1.0' not found
```

**Comment by hjenryin** [comment]
I also encountered the similar issue while executing ```./releash.sh``` in the most recent commit when trying to build the Windows version from my Ubuntu 20.04. The previous logs seems normal until it says
```
[ -d "build-win32" ] || ( mkdir "build-win32" && \
        meson "build-win32" \
                --cross-file cross_win32.txt \
                --buildtype release --strip -Db_lto=true \
                -Dcompile_server=false \
                -Dportable=true )

ERROR: Malformed value in cross file variable prebuilt_libusb.
```

**Comment by hjenryin** [comment]
Now I think it has something to do with the version of ```meson```. I think ```BUILD.md``` can be updated since it wrote:

> On old versions (like Ubuntu 16.04), ```meson``` is too old.

Actually in my Ubuntu 20.04, the newest ```meson``` was 0.53.2, and after I installed the latest version (0.63.0) with ```pip```, this ERROR no longer existed.

**Comment by rom1v** [comment]
> Actually in my Ubuntu 20.04, the newest meson was 0.53.2, and after I installed the latest version (0.63.0) with pip, this ERROR no longer existed.

Oh, the older version probably does not like concatenation in cross-files: https://github.com/Genymobile/scrcpy/blob/ed84e18b1ae3e51d368f8c7bc88ba4db088e6855/cross_win32.txt#L24-L25

Will have to check the meson changelog to find the exact version :)

**Comment by avboy1337** [comment]
yesterday i checked again on ubuntu 20LTS and use pip install meson with sudo to compile
and the final error is also the libusb issue.

**Comment by avboy1337** [comment]
> What commands did you execute exactly?
> 
> On which commit exactly?

the latest commit on ubuntu 20LTS
and error is cannot find libusb when cross compile windows version on ubuntu 20.

**Comment by NarraBhanu** [comment]
> Now I think it has something to do with the version of `meson`. I think `BUILD.md` can be updated since it wrote:
> 
> > On old versions (like Ubuntu 16.04), `meson` is too old.
> 
> Actually in my Ubuntu 20.04, the newest `meson` was 0.53.2, and after I installed the latest version (0.63.0) with `pip`, this ERROR no longer existed.

updated meson to the latest version issue resolved

**Comment by avboy1337** [comment]
> Reference

I am going to try and close this issue.

**Comment by avboy1337** [comment]
the final solution is 

`pip install meson==0.63.0`
