### ISSUE TITLE
SDL_WaitEvent grabs consumed keydown events

### ISSUE THREAD

**Issue by amosbird** [Genymobile/scrcpy#339]
When using scrcpy in bspwm, all hotkeys in sxhkd are still captured in scrcpy's main window. I'm using `Ctrl-Alt-f` to switch to a dedicated workspace and scrcpy gets full screened.

I have to do something like this

https://la.wentropy.com/Cddk.txt

**Comment by rom1v** [comment]
> When using scrcpy in bspwm, all hotkeys in sxhkd are still captured in scrcpy's main window.

Isn't it a bug in bspwm, then, which should not transmit the consumed events to scrcpy?

**Comment by amosbird** [comment]
well it only happens in scrcpy
