### ISSUE TITLE
Screen not appear.

### ISSUE THREAD

**Issue by Nanco300** [Genymobile/scrcpy#3392]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - KDE Neon
 - scrcpy version: 1.24
 - installation method: snap, deb
 - device model: Redmi 9
 - Android version: 12

![image](https://user-images.githubusercontent.com/34143366/180602875-5a025f0d-cc11-4699-a615-3397f972043b.png)

This is how show in Konsole:

scrcpy
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 5.7 MB/s (41159 bytes in 0.007s)
[server] INFO: Device: xiaomi Redmi 9 (Android 12)
INFO: Renderer: opengl
INFO: OpenGL version: 3.0 Mesa 20.0.8
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x2336

**Comment by rom1v** [comment]
See #3381.
