### ISSUE TITLE
SCREEN OPEN AND CLOSE

### ISSUE THREAD

**Issue by apenasumdev** [Genymobile/scrcpy#3394]
My cell phone screen appears on my pc but it doesn't last 2 seconds, it **closes automatically.**

PS: I have ubs debug developer mode and security enabled on my phone

**Comment by rom1v** [comment]
What's the output in the console? (Run `scrcpy-console.bat` on Windows)

**Comment by apenasumdev** [comment]
> What's the output in the console? (Run `scrcpy-console.bat` on Windows)

**I tested it now and it's working normally, maybe I had to restart the phone or enable all other usb debugs in developer mode.**

*THANKSS*
