### ISSUE TITLE
unable to stream amazon prime video

### ISSUE THREAD

**Issue by muvvag** [Genymobile/scrcpy#340]
i can view everything on the phone's screen until i open the amazon prime app and press play video.
After the streaming starts, I can only view the subtitles but not the video

**Comment by rom1v** [comment]
This is expected, the app [protects the screen](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#i-get-a-black-screen-for-some-applications-like-silence).

**Comment by dsdorazio** [comment]
looks like this is back in v1.10, only showing a green screen, while the audio plays and the subtitles shown

**Comment by rom1v** [comment]
This is still expected with hardware DRM.
