### ISSUE TITLE
Mirror screen

### ISSUE THREAD

**Issue by g123k** [Genymobile/scrcpy#3401]
Hello,

I have a (Chinese) device, where the contact is horizontally mirrored.
Is-there an option to flip the two sides?

<img width="720" alt="Screenshot 2022-07-26 at 17 53 22" src="https://user-images.githubusercontent.com/246838/181052788-8abacf1f-175e-4a5e-964b-8d186c12c14f.png">

**Comment by rom1v** [comment]
Nope, but: https://github.com/Genymobile/scrcpy/issues/1380#issuecomment-626612709

**Comment by g123k** [comment]
Thanks for your answer. I will try your fix.
Just in case: is-it normal that the display is shifted, but the clicks on the screen are actually at the right coordinates ?
