### ISSUE TITLE
Error when running scrcpy with MediaPad T1

### ISSUE THREAD

**Issue by BooIMDD** [Genymobile/scrcpy#3407]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 11
 - scrcpy version: 1.24
 - installation method: Windows release
 - device model: Huawei MediaPad T1 8.0 Pro
 - Android version: 4.4.4 H Kitkat

**Describe the bug**
Enabled USB Debugging, Connected my tablet to my PC and launched scrcpy 1.24. Shows the same error everytime I run scrcpy. When I connected my tablet it showed "Do you allow this computer with this key to connect with USB Debugging?" I pressed Yes but it still didn't work. I also put the USB Option as Device File Manager so I could access the files on my PC and that worked but not scrcpy.

```
`scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
C:\Users\User\Desktop\Files\PC Tools\s...ped. 20.2 MB/s (41159 bytes in 0.002s)
adb.exe: error: closed
ERROR: "adb reverse" returned with value 1
WARN: 'adb reverse' failed, fallback to 'adb forward'
open: Permission denied
open: Permission denied
Aborted
ERROR: Server connection failed
Press any key to continue . . .`
```

**Comment by rom1v** [comment]
Scrcpy requires Android 5.

**Comment by BooIMDD** [comment]
> Scrcpy requires Android >= 5.

so when android 4 support?
