### ISSUE TITLE
Cannot input anything 

### ISSUE THREAD

**Issue by sugguy** [Genymobile/scrcpy#3410]
- [ x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Arch Linux
 - scrcpy version: 1.23 
 - installation method: pacman -S scrcpy
 - device model: Redmi Note 11
 - Android version: 11

**Describe the bug**
When running scrcpy I get the screen mirror of the phone but I cannot input anything no mouse or keyboard.
Note: It works well on my other samsung devices running android 11 and 6.0.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work

**Comment by sugguy** [comment]
This worked
