### ISSUE TITLE
Cannot operate on miui13.0.2

### ISSUE THREAD

**Issue by lzb6666** [Genymobile/scrcpy#3417]
**Environment**
 - OS: Windows
 - scrcpy version: 1.24
 - installation method: Windows release
 - device model: Xiaomi M2006J10C (Android 12)
 - Android version: 12

The screen displays normally, but it cannot be operated after upgrading to Android 12 (miui13.0.2). Error message not found. I think MIUI may limit it.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work

**Comment by vintercider** [comment]
I have Xiaomi phone with MIUI 13 and touch input was not working.

Enabling "USB debugging (Security settings)" and rebooting the phone fixed it for me.

**Comment by bholatech** [comment]
same problem on my xiaomi redmi note 10 pro scrcpy disppear after scanning my device processs through usb debugging
os: windows 64 bit
scrcpy version:1.24
installtion: method windows release
android version: 12
device model: M210K6P

**Comment by rom1v** [comment]
What's the output in the console (when you run `scrcpy-console.bat`)?

**Comment by lzb6666** [comment]
> What's the output in the console (when you run `scrcpy-console.bat`)?

![image](https://user-images.githubusercontent.com/31194937/183338302-88563a54-c7b0-46ae-8734-fe91dc86959a.png)
Error message not found

**Comment by lzb6666** [comment]
> I have Xiaomi phone with MIUI 13 and touch input was not working.
> 
> Enabling "USB debugging (Security settings)" and rebooting the phone fixed it for me.

It works,Thank you.

**Comment by bholatech** [comment]
No message .....just Scrcpy process happen then suddenly disappeared

**Comment by rom1v** [comment]
Try with a lower resolution (`scrcpy -m1024`), or with another encoder: https://github.com/Genymobile/scrcpy#encoder

**Comment by digithegreek** [comment]
![scrcpy_error](https://github.com/Genymobile/scrcpy/assets/85275387/eaa48396-edfd-490c-8e7d-036345db68d4)

I can see the screen on my Redmi 12 5G, but no operations are possible. As you see, I tried with lower resolution.
Any help will be appreciated

**Comment by rom1v** [comment]
@digithegreek Update to the latest scrcpy version.

**Comment by digithegreek** [comment]
Thanks rom1v. I will try...

**Comment by digithegreek** [comment]
> Thanks rom1v. I will try...

Thanks man, it works!
