### ISSUE TITLE
After android upgrading, scrcpy stops working

### ISSUE THREAD

**Issue by amosbird** [Genymobile/scrcpy#342]
it never pops out the phone screen, only showing
```
/usr/share/scrcpy/scrcpy-server.jar: 1 file pushed. 1.2 MB/s (18802 bytes in 0.015s)
INFO: Initial texture: 2160x1080
```
on the terminal.

Is there anything I can do to debug this?

**Comment by rom1v** [comment]
adb logcat

And you could try a lower definition:

    scrcpy -m1024

**Comment by amosbird** [comment]
using the master commit, I saw `^CERROR: Could not open video stream` after hitting ctrl-c .  Is this related?  https://github.com/Genymobile/scrcpy/issues/291

**Comment by rom1v** [comment]
> `adb logcat` doesn't generate anything

At all? Then your device has a problem.

What about `adb shell` or `adb devices`?

**Comment by amosbird** [comment]
`adb shell` and `adb devices` work fine.  

> At all? 

It has some outputs but doesn't generate anything new after running `scrcpy`

**Comment by amosbird** [comment]
Hmm, found something suspious. `/data/local/tmp/scrcpy-server.jar` gets removed after I saw `INFO: Initial texture: 2160x1080`

**Comment by amosbird** [comment]
manually running the server

```
 ❯ adb shell
MeizuE3:/ $ CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process com.genymobile.scrcpy.Server
Aborted
134|MeizuE3:/ $ CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server
ERROR: Exception on thread Thread[main,5,main]
java.io.IOException: Connection refused
        at android.net.LocalSocketImpl.connectLocal(Native Method)
        at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:292)
        at android.net.LocalSocket.connect(LocalSocket.java:131)
        at com.genymobile.scrcpy.DesktopConnection.connect(DesktopConnection.java:33)
        at com.genymobile.scrcpy.DesktopConnection.open(DesktopConnection.java:53)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:17)
        at com.genymobile.scrcpy.Server.main(Server.java:109)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:277)
```

**Comment by amosbird** [comment]
OK, do I need to setup some permission configuration to fix the `Connection refused` error?

**Comment by amosbird** [comment]
this `adb exec-out screenrecord --output-format=h264 - | vlc - --demux h264` works as expected

**Comment by rom1v** [comment]
> Is there anything I can do to debug this?

You can use `gdb`:
```
export SCRCPY_SERVER_PATH=x/server/scrcpy-server.jar
gdb x/app/scrcpy
```
(if `x` is your builddir)

Put a breakpoint on `scrcpy()`:
```
(gdb) b scrcpy
```
and run:
```
(gdb) r
```
Then run line-by-line to know where the client "waits":
```
(gdb) n
```

**Comment by amosbird** [comment]
> Ah, so now it starts again?

Nope, only the input events work, no video stream

**Comment by amosbird** [comment]
> Then run line-by-line to know where the client "waits":

The error is obviously come from `avformat_open_input` call which returns :  Invalid data found when processing input

**Comment by amosbird** [comment]
@rom1v the client actually waits at `avformat_open_input` and the syscall is recv

**Comment by amosbird** [comment]
Another progress, android server hangs at https://github.com/Genymobile/scrcpy/blob/master/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java#L92

**Comment by amosbird** [comment]
It seems there is no input for codec after `                setDisplaySurface(display, surface, contentRect, videoRect);`

**Comment by amosbird** [comment]
The only log entry after doing `CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 0 8000000 false '' false` is

```
11-25 18:28:51.064  3330  3330 I Radio-JNI: register_android_hardware_Radio DONE
11-25 18:28:51.085  3330  3348 E SchedPolicy: open of /dev/cpuctl/bg_non_interactive/tasks failed: No such file or directory
```

Is there anything I can do to debug the issue of `setDisplaySurface`?

**Comment by amosbird** [comment]
https://github.com/Genymobile/scrcpy/pull/434
