### ISSUE TITLE
adb still running after scrcpy terminates causes rebuilding failure

### ISSUE THREAD

**Issue by hjenryin** [Genymobile/scrcpy#3427]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: 1.24
 - installation method: manually built from wsl ubuntu 20.04
 - device model: Xiaomi M2011K2C (Android 11)
 - Android version: 11

**Describe the bug**
When _scrcpy_ is initially built using ```./release.sh``` (in which ```DIST``` is modified to ```/mnt/e/Tools/dist```, which should be irrelevant from my perspective), it works fine. After I run _scrcpy_, terminate it, and then rebuild it, it says

```
rm -rf "/mnt/e/Tools/dist" "build-test" "build-server" \
        "build-win32" "build-win64"
rm: cannot remove '/mnt/e/Tools/dist/scrcpy-win64/adb.exe': Input/output error
rm: cannot remove '/mnt/e/Tools/dist/scrcpy-win64/AdbWinApi.dll': Input/output error
rm: cannot remove '/mnt/e/Tools/dist/scrcpy-win64/AdbWinUsbApi.dll': Input/output error
```
It seems to me that this is because _adb.exe_ is still running, and after I kill it using the task manager in Windows, the rebuilding process works perfectly fine.

So I think _adb.exe_ should be killed on exit.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/issues/205#issuecomment-406776834
