### ISSUE TITLE
Scrcpy closes when closing Android Studio project

### ISSUE THREAD

**Issue by Abhimanyu14** [Genymobile/scrcpy#3428]
**Environment**
 - OS: macOS
 - scrcpy version: 1.24

**Describe the bug**
1. Open scrcpy in Terminal using `scrcpy -m1024`
2. Open Android Studio project
3. Close Android Studio Project (To switch projects)

**Actual Result**
Scrcpy closes

**Expected Result**
Scrcpy stays open

```
scrcpy[4277:33347] WARN: Device disconnected
```

**Comment by rom1v** [comment]
Android studio probably uses another adb executable (and version). You MUST use the same adb version, otherwise they kill each other.

You can set the `ADB` environment variable to the full path (filename included) of the adb executable to use: https://github.com/Genymobile/scrcpy#custom-paths

**Comment by Abhimanyu14** [comment]
`adb --version` on both Terminal and Android Studio gives same output.

adb --version
Android Debug Bridge version 1.0.41
Version 31.0.3-7562133
Installed as /opt/homebrew/bin/adb

Also updated ADB in zshrc as below
`export ADB="/opt/homebrew/bin/adb"`

**Comment by rom1v** [comment]
> `adb --version` on both Terminal and Android Studio gives same output.

That does not mean that Android Studio uses this adb internally. I would be surprised that it used the version from homebrew (I think it uses its own). Find the adb used by Android Studio. Maybe in `/Users/$USER/Library/Android/sdk/platform-tols`?

**Comment by Abhimanyu14** [comment]
Found adb from Android Studio in "/Users/$USER/Library/Android/sdk/platform-tools/adb" as mentioned.

Changed the ADB environment variable to "/Users/$USER/Library/Android/sdk/platform-tools/adb".
Still, when I close an Android Studio Project, the scrcpy closes.

Logs for reference

```
abhimanyu@mac platform-tools % pwd            
/Users/abhimanyu/Library/Android/sdk/platform-tools
abhimanyu@mac platform-tools % ./adb --version
Android Debug Bridge version 1.0.41
Version 33.0.2-8557947
Installed as /Users/abhimanyu/Library/Android/sdk/platform-tools/adb
abhimanyu@mac platform-tools % scrcpy -m1024  
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
* daemon not running; starting now at tcp:5037
* daemon started successfully
/opt/homebrew/Cellar/scrcpy/1.24/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 151.8 MB/s (41159 bytes in 0.000s)
[server] INFO: Device: Xiaomi Redmi 8 (Android 10)
2022-08-09 16:45:21.173 scrcpy[8536:134760] INFO: Renderer: metal
2022-08-09 16:45:21.178 scrcpy[8536:134760] INFO: Initial texture: 488x1024
2022-08-09 16:45:37.446 scrcpy[8536:134760] WARN: Device disconnected
abhimanyu@mac platform-tools % echo $ADB
/Users/abhimanyu/Library/Android/sdk/platform-tools/adb
```

**Comment by rom1v** [comment]
If you run `adb shell` or `adb logcat` (keep it open), and start Android Studio, does the adb command close?

**Comment by Abhimanyu14** [comment]
Yes.

Steps

1. Ran `adb logcat` in Terminal.
2. Opened Android Studio (logcat is working)
3. Opened a project in Android Studio (logcat is working)
4. Closed the Android Studio project. Android Studio is still open. (logcat stopped working))

So, this is an Android Studio issue?

**Comment by rom1v** [comment]
Either it explicitly kill the existing adb daemon (but Android Studio does not do that), or it uses another version of adb somewhere (but I don't know), which cause the current daemon to be killed.

**Comment by Abhimanyu14** [comment]
Anyway, this issue is not related to scrcpy. 

Thank You for the support. 

❤️ Scrcpy. A super useful tool I am using every day.
