### ISSUE TITLE
what is the difference between scrcpy and miraclecast

### ISSUE THREAD

**Issue by librewish** [Genymobile/scrcpy#344]
Just wanted to know what's the difference between these two

**Comment by ykzk** [comment]
MiracleCast is an implementation of Miracast, a display protocol over WiFi. It's the equivalent of replacing an HDMI cable with WiFi. Both the device and the display have to support the protocol. It is not supported on Android as of version 6 in favour of Chromecast.
scrcpy streams a video of the Android device's display to a computer, and also lets you control it.

**Comment by NixonNelson** [comment]
@rom1v i think you should close this
