### ISSUE TITLE
scrcpy not working with Briar app

### ISSUE THREAD

**Issue by nsaxiom** [Genymobile/scrcpy#3440]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows Version 10.0.19044 Build 19044
 - scrcpy version: 1.24
 - installation method: scoop
 - device model: Samsung S20 LE 5G
 - Android version: 12

**Bug**
Screen goes blank when using Briar app (Version 1.4.10).  Briar app has a security policy which does not allow taking screenshots, which is my best guess for why it shows as a black screen on scrcpy.  However scrcpy works fine with Briar and Android 7.1.1.  
Other apps and menus work fine.  When using scrcpy on Briar, if menu items are used in Briar, the menu items are displayed correctly on scrcpy, but not the main app.

There is no error text.

**Comment by rom1v** [comment]
That's expected on Android 12. See #2129.
