### ISSUE TITLE
Need help i am newbie..

### ISSUE THREAD

**Issue by norulezzzz** [Genymobile/scrcpy#3441]
I have black screen while using some apps any idea how to fix this I am newbie.. Thanks in advance

![b71821f7-d398-417c-ae59-e6ba257bd713](https://user-images.githubusercontent.com/111191301/184552689-1dd8c648-5cdd-45dd-b3a8-7f6578b44140.jpg)

**Comment by rom1v** [comment]
The app prevents to take screenshot, and this is totally enforced in Android 12. See #2129.
