### ISSUE TITLE
Error while loading shared libraries

### ISSUE THREAD

**Issue by Jimmy-web169** [Genymobile/scrcpy#3445]
it's working last two week. However, now it can't open and jump up scrcpy: error while loading shared libraries: libavformat.so.58: cannot open shared object file: No such file or directory

**Comment by rom1v** [comment]
You probably get an upgrade of ffmpeg to the version 5 from your distro. If you built manually, you must re-compile scrcpy.

**Comment by Jimmy-web169** [comment]
i already re-compile scrcpy and reboot my computer but it not working

**Comment by rom1v** [comment]
You must also re-execute the meson command, not only ninja. Remove your build dir and retry from scratch.

**Comment by Jimmy-web169** [comment]
thank you, it's working now

**Comment by northstars1** [comment]
can u give tell to me the comamand ?

**Comment by bxt1nelox** [comment]
Please write the commands from start to finish

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/doc/build.md#common-steps
