### ISSUE TITLE
Android 13 Release "getDisplayIds" function parameter change, cause scrcpy crash.

### ISSUE THREAD

**Issue by DerekWuYD** [Genymobile/scrcpy#3446]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: macOS
 - scrcpy version: 1.24
 - Android version: Android 13

**Describe the bug**
The function `IDisplayManager.getDisplayIds` use in `DisplayManager.getDisplayIds()`.
No longer exist in Android 13, the new function has a bool parameter.
This function cause scrcpy crash.
Please update the scrcpy to fit this issue.

https://github.com/Genymobile/scrcpy/blob/ed84e18b1ae3e51d368f8c7bc88ba4db088e6855/server/src/main/java/com/genymobile/scrcpy/wrappers/DisplayManager.java#L36

[getDisplayIds detail in android code search](https://cs.android.com/android/platform/superproject/+/android-13.0.0_r1:frameworks/base/core/java/android/hardware/display/IDisplayManager.aidl;l=39;bpv=1)
New method detail :
```
    int[] getDisplayIds(boolean includeDisabled);
```

**Comment by rom1v** [comment]
Thank you for the report.

Do you want to work on it and modify [`DisplayManager`](https://github.com/Genymobile/scrcpy/blob/ed84e18b1ae3e51d368f8c7bc88ba4db088e6855/server/src/main/java/com/genymobile/scrcpy/wrappers/DisplayManager.java)? ([`ClipboardManager`](https://github.com/Genymobile/scrcpy/blob/ed84e18b1ae3e51d368f8c7bc88ba4db088e6855/server/src/main/java/com/genymobile/scrcpy/wrappers/ClipboardManager.java) could be used as an example.)

**Comment by DerekWuYD** [comment]
I have an avaliable workaround using another class [DisplayManagerGlobal.java](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/hardware/display/DisplayManagerGlobal.java;l=146?q=frameworks%2Fbase%2Fcore%2Fjava%2Fandroid%2Fhardware%2Fdisplay%2FDisplayManagerGlobal.java&ss=android%2Fplatform%2Fsuperproject)
This class also is have not change from Android 4.4 to now (Android 13)
Which method you will perfer? Use the `DisplayManagerGlobal.java` or keep the `DisplayManager.aidl` with android version switch?

I put the code here for you reference.
Here is the `DisplayManagerGlobal.java` wrapper class code :
```
public final class DisplayManagerGlobal {
    private final Class<?> managerglobal;
    private final Object managerglobal_instance;

    public DisplayManagerGlobal(Object managerglobal) {
        this.managerglobal = managerglobal.getClass();
        this.managerglobal_instance = managerglobal;
    }

    public DisplayInfo getDisplayInfo(int displayId) {
        try {
            Object displayInfo = managerglobal.getMethod("getDisplayInfo",
                    int.class).invoke(managerglobal_instance, displayId);
            if (displayInfo == null) {
                return null;
            }
            Class<?> cls = displayInfo.getClass();
            // width and height already take the rotation into account
            int width = cls.getDeclaredField("logicalWidth").getInt(displayInfo);
            int height = cls.getDeclaredField("logicalHeight").getInt(displayInfo);
            int rotation = cls.getDeclaredField("rotation").getInt(displayInfo);
            int layerStack = cls.getDeclaredField("layerStack").getInt(displayInfo);
            int flags = cls.getDeclaredField("flags").getInt(displayInfo);
            return new DisplayInfo(displayId, new Size(width, height), rotation, layerStack, flags);
        } catch (Exception e) {
            throw new AssertionError(e);
        }
    }

    public int[] getDisplayIds() {
        try {
            int[] dis = (int[]) managerglobal.getMethod("getDisplayIds").invoke(
                    managerglobal_instance);
            return dis;
        } catch (Exception e) {
            throw new AssertionError(e);
        }
    }
}
```

And here is the change in `ServiceManager.java`
```
    public DisplayManagerGlobal getDisplayManagerGlobal() {
        try {
            if (mDisplayManagerGlobal == null) {
                Object DMG = Class.forName("android.hardware.display.DisplayManagerGlobal")
                        .getMethod("getInstance").invoke(null);
                mDisplayManagerGlobal = new DisplayManagerGlobal(DMG);
                return mDisplayManagerGlobal;
            }
            return mDisplayManagerGlobal;
        } catch (Exception e) {
            throw new AssertionError(e);
        }
    }
```

**Comment by rom1v** [comment]
@DerekWuYD Thank you very much.

I opened a PR: #3448, based on your work. Please test, and also provide a name and e-mail (`Name <email>`) so that I change the ownership of the commit.

**Comment by DerekWuYD** [comment]
This branch works good!
I tested it on the following phones and it all works fine.
```
Pixel 6 / Pixel 6 Pro
Pixel 5
Pixel 4 XL
Pixel 3 XL
Pixel 2
mi12S ultra
mi11 ultra
huawei p50 pro
huawei p40 pro
oppo reno7
sumsang s22 ultra
sumsang s21 ultra
sumsang a52 
vivo x70 pro
```

my name is Derek Wu,
mail is wuderek@google.com

Thank you.

**Comment by rom1v** [comment]
> my name is Derek Wu,
> mail is [wuderek@google.com](mailto:wuderek@google.com)

Thank you, I amended the commit in the PR.

> I tested it on the following phones and it all works fine.
>
> [list of 15 devices]

Awesome, I'd like to have access to so many devices :)

Could you also reproduce issue #3416? If so, does the PR #3448 also fix it?

**Comment by DerekWuYD** [comment]
I can't reproduce issue #3416 in those phone,
But base on this method [getDisplayInfoLocked](https://cs.android.com/android/platform/superproject/+/android-13.0.0_r1:frameworks/base/core/java/android/hardware/display/DisplayManagerGlobal.java;l=190;drc=8f7080eb382ee1851ed106752b1f8054853fb44b;bpv=1;bpt=1) which `getDisplayInfo` method based on.\
It will retrun null under some condition, so I think #3416 may still need to avoid null response.

**Comment by rom1v** [comment]
Thanks :+1: PR merged.

**Comment by cike1949** [comment]
Google Android13.0.0-r16 have reverted the new function DisplayManager.getDisplayIds() with bool parameter and change back to the function without parameter.
So, just need cherry-pick Google revert change, scrcpy 1.24 could work: [https://android.googlesource.com/platform/frameworks/base/+/937ca4b396ebd910b5c9513b09d02b051533bb44](url)

**Comment by Somnambulating** [comment]
> I have an avaliable workaround using another class [DisplayManagerGlobal.java](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/hardware/display/DisplayManagerGlobal.java;l=146?q=frameworks%2Fbase%2Fcore%2Fjava%2Fandroid%2Fhardware%2Fdisplay%2FDisplayManagerGlobal.java&ss=android%2Fplatform%2Fsuperproject) This class also is have not change from Android 4.4 to now (Android 13) Which method you will perfer? Use the `DisplayManagerGlobal.java` or keep the `DisplayManager.aidl` with android version switch?
> 
> I put the code here for you reference. Here is the `DisplayManagerGlobal.java` wrapper class code :
> 
> ```
> public final class DisplayManagerGlobal {
>     private final Class<?> managerglobal;
>     private final Object managerglobal_instance;
> 
>     public DisplayManagerGlobal(Object managerglobal) {
>         this.managerglobal = managerglobal.getClass();
>         this.managerglobal_instance = managerglobal;
>     }
> 
>     public DisplayInfo getDisplayInfo(int displayId) {
>         try {
>             Object displayInfo = managerglobal.getMethod("getDisplayInfo",
>                     int.class).invoke(managerglobal_instance, displayId);
>             if (displayInfo == null) {
>                 return null;
>             }
>             Class<?> cls = displayInfo.getClass();
>             // width and height already take the rotation into account
>             int width = cls.getDeclaredField("logicalWidth").getInt(displayInfo);
>             int height = cls.getDeclaredField("logicalHeight").getInt(displayInfo);
>             int rotation = cls.getDeclaredField("rotation").getInt(displayInfo);
>             int layerStack = cls.getDeclaredField("layerStack").getInt(displayInfo);
>             int flags = cls.getDeclaredField("flags").getInt(displayInfo);
>             return new DisplayInfo(displayId, new Size(width, height), rotation, layerStack, flags);
>         } catch (Exception e) {
>             throw new AssertionError(e);
>         }
>     }
> 
>     public int[] getDisplayIds() {
>         try {
>             int[] dis = (int[]) managerglobal.getMethod("getDisplayIds").invoke(
>                     managerglobal_instance);
>             return dis;
>         } catch (Exception e) {
>             throw new AssertionError(e);
>         }
>     }
> }
> ```
> 
> And here is the change in `ServiceManager.java`
> 
> ```
>     public DisplayManagerGlobal getDisplayManagerGlobal() {
>         try {
>             if (mDisplayManagerGlobal == null) {
>                 Object DMG = Class.forName("android.hardware.display.DisplayManagerGlobal")
>                         .getMethod("getInstance").invoke(null);
>                 mDisplayManagerGlobal = new DisplayManagerGlobal(DMG);
>                 return mDisplayManagerGlobal;
>             }
>             return mDisplayManagerGlobal;
>         } catch (Exception e) {
>             throw new AssertionError(e);
>         }
>     }
> ```

Thank you very much !
