### ISSUE TITLE
Error: No such file or directory ... jpeg-turbo-2.1.3_1.arm64_monterey.bottle.tar.gz

### ISSUE THREAD

**Issue by VectorWen** [Genymobile/scrcpy#3447]
→ brew install scrcpy
....
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/bottles/scrcpy-1.24.arm64_monterey.bottle.tar.gz
Already downloaded: /Users/vector.huang/Library/Caches/Homebrew/downloads/0b767db4c9023ddd7c3d7965a9da22d1257e104d16baf2aa85d01588d472caef--scrcpy-1.24.arm64_monterey.bottle.tar.gz
==> Installing dependencies for scrcpy: jpeg-turbo, libpng, openexr, libtiff, webp, jpeg-xl, libvmaf, aom, dav1d, freetype, fontconfig, frei0r, ca-certificates, gmp, bdw-gc, libffi, m4, libtool, libunistring, pkg-config, readline, guile, libidn2, libtasn1, nettle, p11-kit, openssl@1.1, libevent, libnghttp2, unbound, gnutls, lame, fribidi, pcre, glib, libpthread-stubs, xorgproto, libxau, libxdmcp, libxcb, libx11, libxext, libxrender, lzo, pixman, cairo, graphite2, icu4c, harfbuzz, libass, libbluray, cjson, cmocka, mbedtls, librist, libsoxr, libvidstab, libogg, libvorbis, libvpx, opencore-amr, little-cms2, openjpeg, opus, rav1e, flac, libsndfile, libsamplerate, rubberband, sdl2, snappy, speex, srt, leptonica, libb2, lz4, xz, zstd, libarchive, tesseract, theora, x264, x265, xvid, libsodium, zeromq, zimg, ffmpeg and libusb
==> Installing scrcpy dependency: jpeg-turbo
==> Pouring jpeg-turbo-2.1.3_1.arm64_monterey.bottle.tar.gz
Error: No such file or directory @ rb_sysopen - /Users/vector.huang/Library/Caches/Homebrew/downloads/dbf01af3e06a3b69a6058d18b2eae4a22edc00937ede44d9f9dfedf1f8553b3a--jpeg-turbo-2.1.3_1.arm64_monterey.bottle.tar.gz

<img width="1535" alt="image" src="https://user-images.githubusercontent.com/6134525/184858938-99322e1b-b6bf-49a0-87fb-1e83cc75db6e.png">
<img width="586" alt="image" src="https://user-images.githubusercontent.com/6134525/184859182-e72b5ab4-9538-4c86-bc32-61e4fac8bd44.png">

**Comment by VectorWen** [comment]
fixed
before:
brew install jpeg-turbo
brew install xorgproto
brew install xz

**Comment by rom1v** [comment]
(homebrew "issue")
