### ISSUE TITLE
when scrcpy mirror screen is minimized, Not running for OBS

### ISSUE THREAD

**Issue by alborzmedia** [Genymobile/scrcpy#3456]
Hi,

When scrcpy mirror screen is minimized, Not running anymore so that we can capture for OBS

Is there a way to solve this?

**Comment by rom1v** [comment]
On Linux, you could use v4l2, which exposes the video stream directly as a webcam (this avoids to render on a window then capture a window): https://github.com/Genymobile/scrcpy#v4l2loopback
On other systems, I don't know.

**Comment by alborzmedia** [comment]
In Windows, I figured it out that if the scrcpy is added to OBS via "Game Capture", that would work even when scrcpy screen mirror window is minimized! and that solved the problem!

Thanks a million for creating and sharing this great tool! 🙏
