### ISSUE TITLE
Why my P

### ISSUE THREAD

**Issue by habibullah47** [Genymobile/scrcpy#3466]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows11
 - scrcpy version: v1.24
 - installation method: Windows release
 - device model: HP-15da0xx
 - Android version: 11

**Describe the bug**
When I download this program. I click install to scrcpy application. Suddenly show windows Power Shell blinkly but nothing is happened. My laptop is x64 base. And for me this program is very important. Please help?

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
Run scrcpy-console.bat, the terminal will remain open on errors.

**Comment by habibullah47** [comment]
_> Run scrcpy-console.bat,_ What is it, I don't understand? 
By the way, After that, I tried to install via windows terminal. And scrcpy install successfully with it. 
Thanks for your response and also for giving us such a great app.🙂
