### ISSUE TITLE
Fedora 36: Scrcpy does not display screen

### ISSUE THREAD

**Issue by huang-jy** [Genymobile/scrcpy#3477]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...] Fedora
 - scrcpy version: [e.g. 1.12.1] 1.24
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...] COPR 
 - device model: OnePlus 9Pro
 - Android version: [e.g. 10] 12

**Describe the bug**
I recently upgraded from Fedora 35 to 36 and since the upgrade, scrcpy will not display the screen of the device. It displays all the messages it should do, up until the screen resolution message, but no popup is displayed.

The device DOES wake up, but nothing displays on my computer screen.

There are no errors in console and no obvious errors show up on logcat that I can see.

I can use Vysor (https://www.vysor.io/) instead and that displays my device fine, so my configuration should be correct.

**Comment by rom1v** [comment]
Thank you for your report.

Please see #3431.

**Comment by huang-jy** [comment]
Thanks, I shall try some of the solutions
