### ISSUE TITLE
Until yesterday the software function can be used normally, today suddenly appeared the following error, I do not know what went wrong

### ISSUE THREAD

**Issue by Adolph-Baron** [Genymobile/scrcpy#3483]
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
ERROR: CreateProcessW() error 5
ERROR: Failed to execute: [D:\software\platform-tools], [start-server]
ERROR: Could not execute "adb start-server"
ERROR: Could not start adb daemon
ERROR: Server connection failed

**Comment by rom1v** [comment]
> ERROR: Failed to execute: [D:\software\platform-tools], [start-server]

You set the `ADB` environment variable to a wrong value: if it is defined, it must point to the `adb.exe` executable not its parent directory.

But the scrcpy release already contains adb, so unless you want to use a very specific adb version, just do not define the `ADB` environment variable.

**Comment by Adolph-Baron** [comment]
Thanks for the help, I changed the name of adb to android and successfully solved this problem
