### ISSUE TITLE
Can´t Use Native Resolution 

### ISSUE THREAD

**Issue by oT3DDYo** [Genymobile/scrcpy#3485]
- [x ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: 1.24
 - installation method: Windows Release
 - device model: Huawei P30 Lite
 - Android version: 10

**Describe the bug**
My Phone has a resolution of 2312 x 1080 and if i start scrcpy it says inital texture  2312 x 1080 and then new texture 1920 x 898
i searched an hour how i could get the native res to display but it does´nt work i have a 2530x1440 monitor so it would fit on the desktop i tried using virtual super resolution to get an even higher desktop res but still same message  so i tried to force it to not change the texture with --no-downsize-on-error but then it just crashes 

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
The device hardware encoder is not able to encode at the screen resolution. That's why the resolution is reduced.

You could try another encoder, but this probably won't work: https://github.com/Genymobile/scrcpy#encoder
