### ISSUE TITLE
Stay awake doesn't work on One Plus 5, Android 10

### ISSUE THREAD

**Issue by lpuglia** [Genymobile/scrcpy#3488]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Oxygen OS 10.0.1
 - scrcpy version: 1.24
 - installation method: windows binaries
 - device model: One Plus 5
 - Android version: 10

**Describe the bug**

My phone is correctly plugged into the laptop and it is charging, this is the command i'm using:

```
> .\scrcpy.exe --stay-awake
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
C:\Users\lpuglia\OneDrive - Intel Corporation\Desktop\scrc... file pushed, 0 skipped. 95.0 MB/s (41159 bytes in 0.000s)
[server] INFO: Device: OnePlus ONEPLUS A5000 (Android 10)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x1920
```

The phone doesn't stay awake. I wasn't able to find anyone else having the same problem, is there a workaround?

**Comment by rom1v** [comment]
This feature just enabled the flag `stay_on_while_plugged_in`:

```
adb shell settings put global stay_on_while_plugged_in 7
```

You can read the current value:
```
adb shell settings get global stay_on_while_plugged_in
```

The device is expected to stay on if it is plugged over USB when this flag is set.

**Comment by lpuglia** [comment]
it looks like it is a problem of screen lock, i had a setting to lock the screen 5 seconds after the screen goes blank, changing that to 30 minutes fix the issue. thanks for the help!

**Comment by cool-delete** [comment]
On my OnePlus phone Android 13, I used it
`adb shell settings put global stay_on_while_plugged_in 3` enable
`in 0` disable
