### ISSUE TITLE
exec: Too many levels of symbolic links

### ISSUE THREAD

**Issue by anton-exe** [Genymobile/scrcpy#3492]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Arch Linux
 - scrcpy version:  1.24
 - installation method: pacman
 - device model: Meta Quest 2
 - Android version: ???

**Describe the bug**
The program immediatelly quits with the following output.
adb alone seems to work fine.

```
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
exec: Too many levels of symbolic links
ERROR: Failed to execute: [adb], [start-server]
ERROR: Could not execute "adb start-server"
ERROR: Could not start adb daemon
ERROR: Server connection failed
```

**Comment by anton-exe** [comment]
It seems the issue is with the adb that came installed. Running `export ADB=/usr/bin/adb` fixed the problem since I have my own version.

**Comment by rom1v** [comment]
You probably add `adb` being a symbolic link pointing to `adb`, so infinite recursion.
