### ISSUE TITLE
Quest 2 stuck on black screen

### ISSUE THREAD

**Issue by anton-exe** [Genymobile/scrcpy#3493]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Arch Linux
 - scrcpy version: 1.24
 - installation method: pacman
 - device model: Quest 2
 - Android version: 10

**Describe the bug**
After setting the -w flag the device went to sleep anyways and got stuck on the same image after being awakened. After reboot the screen is black with the backlight on.

On errors, please provide the output of the console (and `adb logcat` if relevant).
N/A

**Comment by rom1v** [comment]
> After setting the -w flag the device went to sleep anyways

Is the device connected over USB? This flag sets the Android setting `stay_on_while_plugged_in`, which prevents the device to sleep only when plugged in.

> got stuck on the same image after being awakened

Which SDL version? Wayland? If you record (`scrcpy --record file.mp4`), is the image also stuck in the recorded file?

**Comment by anton-exe** [comment]
> Is the device connected over USB?
No. I was using tcpip and didn't know it worked like that.
> Which SDL version? Wayland?
Not 100% sure what an SDL is but I use Xorg.

I'll try recording in a moment.

**Comment by anton-exe** [comment]
The recording is blank apart from the 3 loading dots which also appear in the headset but I forgot to mention.

https://user-images.githubusercontent.com/43962111/189379420-0e97dc99-7fa3-477a-a70f-db92d1554b97.mp4

**Comment by rom1v** [comment]
Oh so you probably just run an app with a protected screen (FLAG_SECURE, #36, #2129)

**Comment by anton-exe** [comment]
I think the login menu has that then :/. Do you know how to bypass this since the issues don't seem to mention it.

Also, there might have been a misunderstanding. The device itself has a black screen.

**Comment by anton-exe** [comment]
Do you kow how to fix it though?
I tried googling but noone else had this problem, I don't know where else to ask, and this problem seems to have been caused by using the -w flag.

**Comment by rom1v** [comment]
> this problem seems to have been caused by using the -w flag

Probably not.

Did you pass any other flag?

> Do you kow how to fix it though?

I don't know what the problem is. Your device shows a black screen, it is probably not related to scrcpy.

**Comment by anton-exe** [comment]
i should prob just close this since it was likely a device issue in hindsight
