### ISSUE TITLE
Brazilian portuguese. Letters with accent has been duplicated when typed.

### ISSUE THREAD

**Issue by evanildo-batista** [Genymobile/scrcpy#3495]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows 11]
 - scrcpy version: [1.24]
 - installation method: [Windows release .zip]
 - device model: Samsung J4
 - Android version: [10]

**Describe the bug**
 When you type a character with accent, eg. _á_, it is inputed _aá_. This occurs when you press the **´** and then **a** that should be resulted á in the Portuguese idiom.

Please paste terminal output in a code block.

[server] INFO: Device: samsung SM-J400M (Android 10)
INFO: Renderer: direct3d

**Comment by rom1v** [comment]
Use `scrcpy --prefer-text`.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/issues/3450#issuecomment-1220696213

**Comment by evanildo-batista** [comment]
It just solved the problem. Thanks.
