### ISSUE TITLE
Neither directory contains a build file meson.build.

### ISSUE THREAD

**Issue by SuryaElavazhagan** [Genymobile/scrcpy#35]
I am using elementary OS, Followed all the steps in the document.
when i enter this command, 
```
meson x --buildtype release --strip -Db_lto=true
```
I get,
```
Error during basic setup:

Neither directory contains a build file meson.build.
```

**Comment by plugine** [comment]
you need clone project first, and then cd scrcpy, you can see meson.build file.

**Comment by SuryaElavazhagan** [comment]
My bad. Sorry! @plugine

**Comment by soder82** [comment]
When I shall clone the project, what would be the correct commands then? Also I get the meson.build error...

**Comment by ssmalan94** [comment]
Yes..Sorry it's working fabulous 🤩

**Comment by elijahfischer1** [comment]
I am trying to Run meson to build the project into 'builddir' directory:

$ meson --prefix=/usr builddir

at this command line:
winning@winning-H67MA-USB3-B3:~$ meson --prefix=/usr builddir

and I get the following error message:
ERROR: Neither directory contains a build file meson.build.

Please advise. Thank you.

**Comment by rom1v** [comment]
You must execute this command from the scrcpy repo directory (that you `git clone`d).
