### ISSUE TITLE
Scrcpy multiple input click/keyboard

### ISSUE THREAD

**Issue by richkizent** [Genymobile/scrcpy#3500]
hi , i have 3 same type android devices , and now im using scrcpy for inputing data 
i want to ask , can scrcpy enable mouse and keyboard 3 connected devices input at the same time ? i mean if u click bottom on device 1 so device 2 and 3 doing this too..

**Comment by rom1v** [comment]
Nope, scrcpy does not support this use case.

This is not implemented, and this is complicated from a UX point of view: different devices connected could have different size, etc.
