### ISSUE TITLE
How can i use the lock-video-orientation=1 in scrcpy-server.jar

### ISSUE THREAD

**Issue by uetxaxdatjdv** [Genymobile/scrcpy#3507]
what is the adb start command

adb process (-s emulator-5554 shell CLASSPATH=/data/local/tmp/scrcpy-server.jar nohup app_process / com.genymobile.scrcpy.Server  1.19-ws5 web ERROR 8886 true 2>&1 > /dev/null

**Comment by rom1v** [comment]
Pass [`lock_video_orientation=1`](https://github.com/Genymobile/scrcpy/blob/72ba913324d65cded8672dca7a57415cb82da095/server/src/main/java/com/genymobile/scrcpy/Server.java#L198) as a parameter (at least with the official and current scrcpy-server, maybe your 1.19-ws5 variant behaves differently).
