### ISSUE TITLE
Does not display the Android window

### ISSUE THREAD

**Issue by yangfl** [Genymobile/scrcpy#3510]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Debian
 - scrcpy version: 1.24
 - installation method: apt
 - device model: samsung SM-A730F
 - Android version: 9

**Describe the bug**

Forwarded: https://bugs.debian.org/1020517

After using the "scrcpy" command, everything seems to be normal, but the window with the Android system image does not open. Just for comparison, using the flatpak version of the "guiscrcpy" program, it's working.

After executing the command, the message that appears is:

```
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 1.6 MB/s (40683 bytes in 0.024s)
[server] INFO: Device: samsung SM-A730F (Android 9)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 22.2.0-rc3
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x2216
```

And nothing happens after that.

The window with the Android system should appear. I already checked the "debug mode" and permissions on the device.

```
$ scrcpy -V debug
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
DEBUG: ADB device found:
DEBUG:     -->   (usb)  52008c82b4ba559b                device  SM_A730F
DEBUG: Device serial: 52008c82b4ba559b
DEBUG: Using server: /usr/share/scrcpy/scrcpy-server
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 2.4 MB/s (40683
bytes in 0.016s)
[server] INFO: Device: samsung SM-A730F (Android 9)
DEBUG: Server connected
DEBUG: Starting controller thread
DEBUG: Starting receiver thread
[server] DEBUG: Using encoder: 'OMX.Exynos.AVC.Encoder'
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 22.2.0
INFO: Trilinear filtering enabled
DEBUG: Using icon: /usr/share/icons/hicolor/256x256/apps/scrcpy.png
INFO: Initial texture: 1080x2216
DEBUG: Starting demuxer thread
```

**Comment by rom1v** [comment]
Probably the same issue as #3431 on Fedora related to SDL 2.0.24.

See [this comment](https://github.com/Genymobile/scrcpy/issues/3431#issuecomment-1229917314) and below for workarounds.

**Comment by yangfl** [comment]
Downstream issue gone for no reason. Possibly a mesa lib problem.
