### ISSUE TITLE
Check `$ANDROID_HOME` environment variable for the android data files

### ISSUE THREAD

**Issue by whinee** [Genymobile/scrcpy#3512]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
No. I'm an Arch Linux user, and despite my sedentary and unsanitary lifestyle, I would like to keep my home directory clean. It only has 16 folders and 7 files in its root. One of the folders in the said 16 folders is the `.android`. Upon further inspection, this file is generated by this program. Now, I've set `$ANDROID_HOME` to `"$XDG_DATA_HOME"/android`, and moved `.android` to said directory as per xdg-ninja's suggestion. However, it still appears.

**Describe the solution you'd like**
Make this program check `$ANDROID_HOME` environment variable for the android data files, and use it. 

If the program did not see said environment variable, generate one on the home directory, or much preferably, at `"$XDG_DATA_HOME"/android` if set.

[XDG Base Directory](https://wiki.archlinux.org/title/XDG_Base_Directory) is a specification that defines where files should go. In this specification, it also defines where programs would put the data files, called `XDG_DATA_HOME`, which defaults to `$HOME/.local/share`.

**Describe alternatives you've considered**
None, as this program generates `.android`, and I do not see an option that makes this program read android data files from another directory.

**Rationale**
Standardization, and making `$HOME` less cluttered.

**Additional context**
OS: Linux (Arch distribution)
Kernel: 5.19.11-arch1-1

**Reference**
- https://wiki.archlinux.org/title/XDG_Base_Directory
- https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by rom1v** [comment]
`scrcpy` does not create `.android`. `adb` does, and `scrcpy` calls `adb`.

**Comment by whinee** [comment]
I-i uhh... So... Just take this as a rambling of a 17 year old kid, as I literally do not know anything about this.

Err... Is this unsolvable or not?

**Comment by rom1v** [comment]
The "problem" is not related to scrcpy.

If you really want the directory `.android` to not be created, you should report to the `adb` project (which is part of the AOSP, Android Open Source Project).

**Comment by whinee** [comment]
Ahh! Gotcha, will close this issue, and report it with em. Thank you!
