### ISSUE TITLE
Support autorun when phone is plugged 

### ISSUE THREAD

**Issue by amosbird** [Genymobile/scrcpy#352]
This is a nice feature to have in gnirehtet. I wonder if it's easy to implement in scrcpy.

**Comment by rom1v** [comment]
Something like:

    ./gnirehtet autorun

?

:wink:

**Comment by amosbird** [comment]
exactly, but for scrcpy

**Comment by rom1v** [comment]
Ah, sorry, I read the question too fast :) I added the _feature request_ label.

If it's just for 1 device, you can do something like:

    while :; do adb wait-for-device && scrcpy; done

**Comment by amosbird** [comment]
Cool, thanks

**Comment by npes87184** [comment]
udev rule is another option in Linux.

**Comment by rom1v** [comment]
@npes87184 Yes :+1:

Here is an exemple (for gnirehtet): https://github.com/Genymobile/gnirehtet/issues/49#issuecomment-343525703

**Comment by npes87184** [comment]
I have written a udev rule and systemd.service to achieve this feature.

Below is detail

### requirement:

- Linux system
- udev
- systemd
- root permission

### Step:

1. add `/etc/udev/rules.d/99-scrcpy.rules` as:
```
ACTION=="add" \                                                                                                     
, SUBSYSTEM=="usb" \                                                                                                
, ENV{DEVTYPE}=="usb_device" \                                                                                      
, ATTRS{idVendor}=="XXXX" \                                                                                         
, ATTRS{idProduct}=="XXXX" \                                                                                        
, TAG+="systemd" \                                                                                                  
, ENV{SYSTEMD_WANTS}="scrcpy.service"       
```
where you should specify `idVendor` and `idProduct` for your device (simply use lsusb).

2. `sudo udevadm control --reload-rules` to reload udev.rule
3. add `/etc/systemd/system/scrcpy.service` as:
```
[Unit]                                                                                                              
Description=Start scrcpy when correct usb device is plugged           
                                                                                                                                                                  
[Service]                                                                                                           
Type=simple                                                                                                         Environment=XAUTHORITY=/home/<username>/.Xauthority                                                                  
Environment=DISPLAY=:0                                                                                              
ExecStartPre=/bin/sleep 3                                                                                           
ExecStart=/usr/local/bin/scrcpy                                                                                     
                                                                                                                    
[Install]                                                                                                           
WantedBy=multi-user.target    
```
where you should specify your `username` to get correct cookie. also, you should setup `DISPLAY` environment variable based on your environment.
4. `systemctl daemon-reload` to reload systemd service

That's all!

### FAQ:

#### 1. Why not using `RUN+=` in udev.rule?
it will show `Dec 25 21:52:25 npes87184 systemd-udevd[471]: seq 22149 '/devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.1' is taking a long time` in syslog. In additional, other udev event will be delayed.

#### 2. why `ENV{DEVTYPE}=="usb_device"` in udev.rule?
to prevent triggering more than once.

### Reference:

1. [Proper(-ish) way to start long-running systemd service on udev event (device hotplug)](http://blog.fraggod.net/2012/06/16/proper-ish-way-to-start-long-running-systemd-service-on-udev-event-device-hotplug.html)
2. [Setting DISPLAY in systemd service file](https://unix.stackexchange.com/questions/85244/setting-display-in-systemd-service-file)

**Comment by rom1v** [comment]
Hi,

I just wrote and published a tiny tool to execute a command whenever a device is adb-connected: [autoadb](https://github.com/rom1v/autoadb).

```bash
autoadb scrcpy -s {}
```

_(`{}` is replaced by the serial of the devices)_

Here are binaries (I did not create a release yet, and the Windows version is not tested):
 - [autoadb](https://tmp.rom1v.com/autoadb/0.1.0/autoadb) (Linux 64 bits)  
_SHA256: 54618ae4ffdf725ad603aef3ab546bf9ead43bae15a429770ea9bcb355741efd_
 - [autoadb.exe](https://tmp.rom1v.com/autoadb/0.1.0/autoadb.exe) (Windows 64 bits)  
_SHA256: d367fd842c9a061141cc4a6c82cb444b079f42697306fd7dd39fc082d47b0c51_

Feedbacks welcome.

**Comment by amosbird** [comment]
Great! It works as expected. However I also have a local fork with libusb keyboard support that requires usb id like `18d1:4ee7`. Is it possible to let `autoadb` provide that info?

**Comment by rom1v** [comment]
> Is it possible to let `autoadb` provide that info?

The adb daemon does not provide this info on device connection:

```bash
printf '0012host:track-devices' | nc localhost 5037
```

So you have to resolve it manually from the serial :/

**Comment by amosbird** [comment]
hmm, perhaps rust ecosystem has some usb related stuff which might help?

**Comment by Sitolam** [comment]
> Hi,
> 
> I just wrote and published a tiny tool to execute a command whenever a device is adb-connected: [autoadb](https://github.com/rom1v/autoadb).
> 
> ```shell
> autoadb scrcpy -s {}
> ```
> 
> _(`{}` is replaced by the serial of the devices)_
> 
> Here are binaries (I did not create a release yet, and the Windows version is not tested):
> 
> * [autoadb](https://tmp.rom1v.com/autoadb/0.1.0/autoadb) (Linux 64 bits)
>   _SHA256: 54618ae4ffdf725ad603aef3ab546bf9ead43bae15a429770ea9bcb355741efd_
> * [autoadb.exe](https://tmp.rom1v.com/autoadb/0.1.0/autoadb.exe) (Windows 64 bits)
>   _SHA256: d367fd842c9a061141cc4a6c82cb444b079f42697306fd7dd39fc082d47b0c51_
> 
> Feedbacks welcome.

I have downloaded it but it does nothing

**Comment by rom1v** [comment]
You must execute `autoadb scrcpy -s '{}'`

(here is some help to execute commands from Windows: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows)

**Comment by abautu** [comment]
> ### Step:
> 1. add `/etc/udev/rules.d/99-scrcpy.rules` as:
> 
> ```
> ACTION=="add" \
> , SUBSYSTEM=="usb" \
> , ENV{DEVTYPE}=="usb_device" \
> , ATTRS{idVendor}=="XXXX" \
> , ATTRS{idProduct}=="XXXX" \
> , TAG+="systemd" \
> , ENV{SYSTEMD_WANTS}="scrcpy.service"
> ```

On Ubuntu 21.04, it starts the first time, but when I disconnect and reconnect the phone doesn't start anymore. Therefore, I used this instead:

`ACTION=="add", SUBSYSTEM=="usb", ENV{DEVTYPE}=="usb_device", ATTRS{idVendor}=="XXXX", ATTRS{idProduct}=="XXX", RUN+="/bin/systemctl --no-block start scrcpy.service"`

With this one, scrcpy starts each time I reconnect the phone.

**Comment by JohnnyRico140** [comment]
When I execute autoadb scrcpy -s '{} on the same folder with scrcpy.exe, adb.exe and autoadb.exe inside, I have this error message :
'Deteted device mveuq4twkjg6pn8x
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: device ''{}'' not found
ERROR: "adb push" returned with value 1
ERROR: Server connection failed

**Comment by rom1v** [comment]
Do not add quotes:

```
scrcpy -s {}
```
