### ISSUE TITLE
Deinterlace filter

### ISSUE THREAD

**Issue by eugeny71** [Genymobile/scrcpy#3528]
I see annoying stripes when I transmit interlaced video from my android device to PC trough Scrcpy. 
Please, add ability to switch on/off deinterlace filter via hotkey and command line key. 
I think it is not difficult due to ffmpeg usage in Scrcpy.

**Comment by rom1v** [comment]
A deinterlace filter operates on a source interlaced video, where all (typically 3, Y U V) planes are interlaced separately. As soon as the video is "captured", the result in a progressive (non-interlaced) video, with the "striped" being encoded as the actual content. It could not be "deinterlaced" correctly after this process. In other words, you must deinterlace before capturing.
