### ISSUE TITLE
cant swith mod button while otg 

### ISSUE THREAD

**Issue by shiref11** [Genymobile/scrcpy#3529]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [ Windows 10]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [Windows]
 - device model:xiomi
 - Android version: [12]

**Describe the bug**
i cannot swith the mod key while the otg mod 
On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
There are no such shortcuts at all in OTG mode (their action requires the server to run on the device, no server is running in OTG mode).
