### ISSUE TITLE
Mouse Scroll in full screen bug Win10

### ISSUE THREAD

**Issue by vernzimm** [Genymobile/scrcpy#353]
When I have scrcpy in fullscreen and display is vertical, if I move mouse "out of bounds" into black areas on either side of screen and use the scroll wheel, scrcpy drops out of fullscreen to give me this error...

![scrcpy error](https://user-images.githubusercontent.com/29264909/48952325-ce549e00-ef0f-11e8-8d1c-27dcbecdfb52.png)

It is directly related to the "Scroll inactive windows..." setting (if I turn it off, doesn't happen, when I turn back on, happens 100% repeatable)...

![win10 mouse setting](https://user-images.githubusercontent.com/29264909/48952582-af0a4080-ef10-11e8-88c6-cccaf707f4d5.png)

I like that setting, and it's not a huge bother when I get the error, I click "always ignore". I don't know default behavior for other systems, but with the setting off, I can't scroll the window with mouse out of bounds anyway, so should be ok to just block mouse wheel input unless in bounds (for instance, maybe Mac or Linux can scroll the active window even though mouse is not in bounds?) Other option I guess would be to just suppress the error. It doesn't crash or do anything unexpected, so it would seem the error is notification only.

Thanks!

**Comment by rom1v** [comment]
Thank you for your report.

I fixed this bug 5 days ago on `master`: https://github.com/Genymobile/scrcpy/commit/a7fe9ad779057f7a2698fc1769dce3c3786993ee :wink:

Please recheck with current `master` (and feel free to reopen if there are still problems).

**Comment by vernzimm** [comment]
Great, thanks for fixing, sorry for duplicate report. I didn't see anything
about it. I can't compile from source at the moment, but I will get the win
binary as soon as I can.

**Comment by rom1v** [comment]
> sorry for duplicate report

No problem :wink:

> I didn't see anything about it.

My daughter tried to play a game on her tablet from the computer last week-end, she managed to trigger this bug, so it was not reported in the issues :wink:

**Comment by vernzimm** [comment]
Kids = best beta testers haha
