### ISSUE TITLE
Kali Linux "E: Unable to locate package scrcpy"

### ISSUE THREAD

**Issue by Deadlooks** [Genymobile/scrcpy#3535]
Hello 
I cannot install scrcpy after updating kali linux 

```
cat /proc/version
Linux version 5.15.44-Re4son-v8l+ (root@kali-raspberry-pi) (gcc (Debian 11.2.0-19) 11.2.0, GNU ld (GNU Binutils for Debian) 2.38) #1 SMP PREEMPT Debian kali-pi (2022-07-03)
```
```
lsb_release -a
No LSB modules are available.
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2022.3
Codename:       kali-rolling
```

**Error is :**

```
sudo apt install scrcpy
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package scrcpy
```

Before i updated my kali linux it was working very good i can perform all tasks scrcpy offer

after updating linux it is not even installing it ??

**Comment by raoshaab** [comment]
Hi @Deadlooks ,
Can you share the mirror in this file `/etc/apt/sources.list `  ?

Also try to update the repo with below , this may solve the issue => 

 `deb http://kali.download/kali kali-rolling main contrib non-free`

**Comment by Charanjet** [comment]
No , I am also facing the same issue and tried your solution but it is not working. 
I added your given repo in sources.list and then apt update and then tried installing the but the above error is still there

**Comment by Deadlooks** [comment]
hello @raoshaab ,

Hear is the source list details

```
cat /etc/apt/sources.list
# See https://www.kali.org/docs/general-use/kali-linux-sources-list-repositories/
deb http://http.kali.org/kali kali-rolling main contrib non-free

# Additional line for source packages
# deb-src http://http.kali.org/kali kali-rolling main contrib non-free
```

After adding this line it is installing the scrcpy as usual : 
`deb http://kali.download/kali kali-rolling main contrib non-free`

**Comment by Deadlooks** [comment]
@Charanjet add the line to /etc/apt/sources.list that @raoshaab has refered to

**Comment by raoshaab** [comment]
Hi @Charanjet , 

If you still face error , try this script  but this work only for Kali linux and Ubuntu 

https://github.com/raoshaab/Flash-Repo

**Comment by Crackets** [comment]
I have this problem, have you found a solution?

**Comment by rom1v** [comment]
If there is no package, install manually: https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md

**Comment by m-04** [comment]
So, I tried installing it manually but it gives me this error:
`error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 6993 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
cd: no such file or directory: scrcpy
zsh: no such file or directory: ./install_release.sh
`

**Comment by Maxtyson2148** [comment]
> If there is no package, install manually: https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md

Thank you very much it worked very well
