### ISSUE TITLE
scrcpy reports state as ACM, while the device is in device mode

### ISSUE THREAD

**Issue by Patrosi73** [Genymobile/scrcpy#3545]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: 1.24
 - installation method: Windows release
 - device model: Samsung Galaxy Tab A (2018)
 - Android version: LineageOS 20 (13) from https://forum.xda-developers.com/t/rom-unofficial-13-lineageos-20-0-64-bit-for-galaxy-tab-a-10-5-2018-wifi-sm-t590.4427597/

**Describe the bug**
scrcpy misdetects the state as "ACM" because the device's name shows up as CDC ACM data, adb shell works

Output:
``` 
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
ERROR: Device could not be connected (state=ACM)
ERROR: Server connection failed
```

adb devices output:
``` 
List of devices attached
CDC ACM Data    device 
```

**Comment by Patrosi73** [comment]
Solved, was device issue after all

**Comment by rom1v** [comment]
How did you get the `CDC ADM Data` value in `adb devices`? How did you solve it?

**Comment by Patrosi73** [comment]
I solved it by rebooting the device. Apparently the ``CDC ACM Data`` value was there because the device was started for the first time after a factory reset.

**Comment by aIecxs** [comment]
I prefer to fix this bug anyway as it seems it just need some quotes `"CDC ACM Data"`
