### ISSUE TITLE
Can you support screenshots?

### ISSUE THREAD

**Issue by molixiaoxiao** [Genymobile/scrcpy#3553]
Like `adb shell screencap -p > screen.png`. Hope to support one-click screenshots. Thanks!

**Comment by rom1v** [comment]
Duplicate of #684. Also see #2040.

**Comment by molixiaoxiao** [comment]
I see. But I can't found the relevant screenshot command for scrcpy. Likes `adb shell screencap -p > screen.png`. Thanks!

**Comment by molixiaoxiao** [comment]
> Duplicate of #684. Also see #2040.

I see. But I can't found the relevant screenshot command for scrcpy. Likes adb shell screencap -p > screen.png. Thanks!
