### ISSUE TITLE
WAN: Device Disconnected

### ISSUE THREAD

**Issue by Kelwin2003** [Genymobile/scrcpy#3566]
Hi, I was trying to use scrcpy version 1.24 in windows 10 laptop but everytime I try, it always show wan device disconnected and after searching for a solution everywhere I couldn't find it anywhere thus I came again here and tried to find a solution for that and I found it as what I thought which was using scrcpy version 1.18 for android 12 but it also didn't worked and stayed the same so can you please help me I need to use scrcpy really soon.....
![Screenshot (4)](https://user-images.githubusercontent.com/117476366/200045926-8b4a068c-69ca-4e17-9709-30efc2911cab.png)

**Comment by Kelwin2003** [comment]
Is there is someone who can help me ots urgent

**Comment by rom1v** [comment]
See #3051.

**Comment by Kelwin2003** [comment]
@rom1v is it working for miui 13.0.8

**Comment by rom1v** [comment]
Apparently no, because it is fixed in MIUI 13.0.12.

**Comment by Kelwin2003** [comment]
> Apparently no, because it is fixed in MIUI 13.0.12.

Thanks
