### ISSUE TITLE
Swipe on left side when fullscreen

### ISSUE THREAD

**Issue by ivantyr** [Genymobile/scrcpy#357]
I find this a little hard to describe, but when performing a swipe motion on the left side of the screen only when on fullscreen, the swipe jumps to the other side of the screen, this does not happen on any of the other 3 sides and also doesn't happen while on windowed mode

Here's a short video that might describe it better
https://giant.gfycat.com/AlarmingKindheartedGenet.webm

**Comment by rom1v** [comment]
Thank you for your report.

Could you try again with the current `master` version, please? This issue might be solved by https://github.com/Genymobile/scrcpy/commit/a7fe9ad779057f7a2698fc1769dce3c3786993ee.

**Comment by rom1v** [comment]
> arf, my fix ignores all events outside the device screen, which is not good: a "drop" of a drag&drop outside the screen is not dispatched.

I provided a better fix on the `dev` branch: https://github.com/Genymobile/scrcpy/commit/fefb9816a99e6f8fa59befcfb70ba87112f90a8d.
