### ISSUE TITLE
Black Blank Screen with Google Authentication

### ISSUE THREAD

**Issue by rwp0** [Genymobile/scrcpy#3570]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Debian 11
 - scrcpy version: 1.24
 - installation method: manual build
 - device model: Nokia 3.4
 - Android version: 12

When Google Auth app is launched the screen is dark blank for that app.
Other apps used display fine.
Google Auth screen works fine otherwise (ie. on phone's screen with the cable unplugged).

![image](https://user-images.githubusercontent.com/68062695/200238919-83c68bfc-cdc5-4eb9-a345-fa5e6c68e82c.png)

**Comment by rwp0** [comment]
> > Android version: 11
> 
> Are you sure it Android 11, not Android 12?
> 
> It's expected on Android 12 (see #36 #2129).

I'm sorry, you're right, I updated the description, I have recently upgraded to Android 12.

Why is it expected, what should I do to prevent that as a workaround?

(Didn't get much information from the linked issues)

Thanks

**Comment by rom1v** [comment]
Since Android 12, the system prevent access to "protected" views with "flag secure", even for the shell user.

> what should I do to prevent that as a workaround?

Nothing :disappointed:

**Comment by rwp0** [comment]
Okay, thanks.
