### ISSUE TITLE
Android 13 (Pixel 7) secure content from the phone puts a bank screen on mirrored windows screen.

### ISSUE THREAD

**Issue by santpriv** [Genymobile/scrcpy#3571]
**Environment**
 - OS: [Windows 11]
 - scrcpy version: [e.g. 1.24] Windows 64 bit
 - device model: Pixel 7 Pro
 - Android version: [13]

**Describe the bug**
Initially, the secure screens, such as passwords and one-time content from WhatsApp, and Snapchat, all showed up. But some android updates come up, and then whenever a secure screen is sent, it puts a blank screen.

Rest all the non-secure screen gets mirrored without issue.

**Comment by rom1v** [comment]
> But some android updates come up

Since Android 12: #2129.

There's nothing to do. 😞
