### ISSUE TITLE
dyld[46627]: Library not loaded: /opt/homebrew/opt/rav1e/lib/librav1e.0.5.dylib

### ISSUE THREAD

**Issue by PrajwalRaiKA** [Genymobile/scrcpy#3578]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: macOS
 - scrcpy version: [e.g. 1.12.1]
 - installation method: brew
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**
After installing scrcpy by using brew install scrcpy, when i run the command scrcpy, I am getting an error

dyld[46807]: Library not loaded: /opt/homebrew/opt/rav1e/lib/librav1e.0.5.dylib
  Referenced from: <D8E78893-F144-3845-A719-8CFFB8415DC1> /opt/homebrew/Cellar/ffmpeg/5.1.2/lib/libavformat.59.27.100.dylib
  Reason: tried: '/opt/homebrew/opt/rav1e/lib/librav1e.0.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/rav1e/lib/librav1e.0.5.dylib' (no such file), '/opt/homebrew/opt/rav1e/lib/librav1e.0.5.dylib' (no such file), '/usr/local/lib/librav1e.0.5.dylib' (no such file), '/usr/lib/librav1e.0.5.dylib' (no such file, not in dyld cache), '/opt/homebrew/Cellar/rav1e/0.5.1/lib/librav1e.0.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/rav1e/0.5.1/lib/librav1e.0.5.dylib' (no such file), '/opt/homebrew/Cellar/rav1e/0.5.1/lib/librav1e.0.5.dylib' (no such file), '/usr/local/lib/librav1e.0.5.dylib' (no such file), '/usr/lib/librav1e.0.5.dylib' (no such file, not in dyld cache)Library not loaded: /opt/homebrew/opt/rav1e/lib/librav1e.0.5.dylib
  Referenced from: <D8B40CEE-FD64-33D7-9FBB-D99C076CAE66> /opt/homebrew/Cellar/ffmpeg/5.1.2/lib/libavcodec.59.37.100.dylib
  Reason: tried: '/opt/homebrew/opt/rav1e/lib/librav1e.0.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/rav1e/lib/librav1e.0.5.dylib' (no such file), '/opt/homebrew/opt/rav1e/lib/librav1e.0.5.dylib' (no such file), '/usr/local/lib/librav1e.0.5.dylib' (no such file), '/usr/lib/librav1e.0.5.dylib' (no such file, not in dyld cache), '/opt/homebrew/Cellar/rav1e/0.5.1/lib/librav1e.0.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/rav1e/0.5.1/lib/librav1e.0.5.dylib' (no such file), '/opt/homebrew/Cellar/rav1e/0.5.1/lib/librav1e.0.5.dylib' (no such file), '/usr/local/lib/librav1e.0.5.dylib' (no such file), '/usr/lib/librav1e.0.5.dylib' (no such file, not in dyld cache)
zsh: abort      scrcpy

**Comment by rom1v** [comment]
This is a homebrew issue.

Either reinstall homebrew and scrcpy, or try MacPorts: https://github.com/Genymobile/scrcpy#macos

**Comment by ben-xD** [comment]
I had the same issue today. Running `brew reinstall rav1e` fixed it for me.

**Comment by tozu** [comment]
The suggested solution by @ben-xD worked for me too.

Thank you 😊🙏

**Comment by freebrowser1** [comment]
For me this fix did work as well I run it on macOS Ventura on an M1.

**Comment by PrajwalRaiKA** [comment]
@ben-xD Thank you, your suggestion worked.
Closing this.

**Comment by massaynus** [comment]
> I had the same issue today. Running `brew reinstall rav1e` fixed it for me.

Worked for me!!!

**Comment by Tiago-classy** [comment]
> I had the same issue today. Running `brew reinstall rav1e` fixed it for me.

Also worked for me!

**Comment by pavoltravnik** [comment]
> I had the same issue today. Running `brew reinstall rav1e` fixed it for me.

worked for me, thanks a lot

**Comment by ZL-Asica** [comment]
> Also worked for me!

Work for me!!! Thanks so much!

**Comment by juliofalbo** [comment]
If the reinstall does not work, try to run `brew uninstall --ignore-dependencies ffmpeg` and then `brew reinstall rav1e`.
