### ISSUE TITLE
scrcpy shows window for about 5 minutes, then hangs/stops with no response

### ISSUE THREAD

**Issue by sennight** [Genymobile/scrcpy#358]
## Environment Information:
* Device: Oneplus 6T A6013
* OS/ROM: Stock Oxygen OS Non-rooted 9.0.6, Android Pie
* Previous Device: Oneplus 3
* Previous Device OS/ROM: Stock Oxygen OS, Android Oreo
* PC: Windows 10
(Full Disclaimer: I have only a very basic knowledge of how to use terminal and ADB so please bear with me, sorry!)

## Logs
Cannot generate logs after scrcpy crashes, adb logcat doesn't generate anything. See issues/steps.

## Issue Description:
scrcpy seems to hang/have no response after about 5 minutes of use. This never happened before when I was using my OP3, which had no issues. After switching to this new phone on Android Pie, it seems that, regardless of if I use the console/no-console version of the exe, or if I start the app through command, the window that mirror's my phone will inevitably crash and stop responding.

Furthermore, ending the task through the task manager of the non-responsive window, or closing the window will stop scrcpy, but it will be very laggy when I start the app again. It will appear to not work, but then after a few minutes the mirroring window will appear but again be non-responsive.

I have tried to replicate this issue on my Surface Pro 4, also running windows 10, but the phone, app and mirroring works flawless on my Surface, which means there must be something on my main desktop that is causing the hanging. I did recently install adb drivers to root/flash another phone, so I'm not sure if that may interfere with scrcpy.

## Steps to reproduce:
1. Run scrcpy
2. Functions fine for a few minutes, flawless
3. Stops suddenly and without warning, no lagging beforehand, just stops responding
4. Force quit window through Task Manager or X
5. Try to run scrcpy again but no response, or very delayed response with window opening without response

**Comment by rom1v** [comment]
> it will be very laggy when I start the app again. It will appear to not work, but then after a few minutes the mirroring window will appear but again be non-responsive. […] which means there must be something on my main desktop that is causing the hanging

Maybe graphical drivers?

**Comment by Dragonprovidence** [comment]
@sennight, thanks for the hard work. I was struggling with this issue too. I had a Corsair Utility Engine for my keyboard and disabling that did the trick. Just wanted to say thanks.
