### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by cmx15157571386** [Genymobile/scrcpy#3587]
C:\Windows\system32>scrcpy
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
ERROR: CreateProcessW() error 5
ERROR: Failed to execute: [C:\platform-tools], [start-server]
ERROR: Could not execute "adb start-server"
ERROR: Could not start adb daemon
ERROR: Server connection failed

**Comment by cmx15157571386** [comment]
please help me.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/issues/3483#issuecomment-1236069457

**Comment by cmx15157571386** [comment]
Thank you for your help, I ran the software successfully.
