### ISSUE TITLE
adb: error: failed to get feature set: no devices/emulators found....... Please help me :'(

### ISSUE THREAD

**Issue by mouazvd** [Genymobile/scrcpy#359]
When I try to mirror my android phone it says

adb: error: failed to get feature set: no devices/emulators found
ERROR: "adb push" returned with value 1
Press any key to continue...
Please help me :'(

**Comment by npes87184** [comment]
Hi, @mouazvd 

Do you enable adb debug in your phone?

Thanks.

**Comment by mouazvd** [comment]
yes, i enabled adb debug but the android on my phone is 4.0.3
could be a problem ?

**Comment by rom1v** [comment]
> my phone is 4.0.3
> could be a problem ?

Yes.

> The Android part requires at least API 21 (Android 5.0).

https://github.com/Genymobile/scrcpy#requirements

See https://github.com/Genymobile/scrcpy/issues/98.

**Comment by rom1v** [comment]
If you are on Windows: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#on-windows-my-device-is-not-detected

**Comment by mesabuca** [comment]
Well I have the same issue. Android 7.0 adb enabled everything is fine except the application

**Comment by rom1v** [comment]
> everything is fine

`adb devices`?

**Comment by mesabuca** [comment]
Ok I figure out sorry. I change my cable and it works.

**Comment by jpark006** [comment]
@mesabuca what cable do you use?

I did everything as instructed and still getting the same error.

I'm using usb c to usb c connection instead of usb a. is that a problem?

**Comment by schrodinger72** [comment]
Hi,
Android 9 here and Arch Linux.

This is just to point that for me, it was the package `android-udev` which resolved the problem.


https://github.com/M0Rf30/android-udev-rules

**Comment by NoXXoN123** [comment]
Im getting the same error. im on android 7 and i tested 3 usb b cables

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#device-not-detected

**Comment by WahajAhmedIqbal** [comment]
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: no devices/emulators found
ERROR: "adb push" returned with value 1
Any idea of how to solve this ?

**Comment by accnetdev** [comment]
Hi,
Same here on Kubuntu 20.04.
It worked up to last week, OS updates ?

**Comment by abhaydasah** [comment]
adb kill-server #start clean

plug your device
adb devices #check if the device is connected
or

connect via TCP
adb connect _IP_:_PORT_

export the path to currently used adb or use the same path to adb when you connected to the device, in the previous step
export ADB=$(which adb) scrcpy

run scrpy
scrcpy

**Comment by applicatlat** [comment]
Hi bois. I received this error as well.

INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: more than one device/emulator
ERROR: "adb push" returned with value 1

and I can see my two beloved android phones:

INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: more than one device/emulator
ERROR: "adb push" returned with value 1

Downloads\scrcpy-win64-v1.17>adb devices
List of devices attached
5WHssss     device
10sssss   device

How can I run two emulators at the same time

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#several-devices-connected

**Comment by subhojitdp** [comment]
You might have enabled Developer Options!! But you haven't enabled the USB debugging option. So just go inside the Developer Options and enable it. Your scrcpy.exe will start working.

**Comment by saulsmokeitall** [comment]
He literally said he already checked and made sure it was enabled😂

**Comment by Arun-arbadev** [comment]
If someone still having this error over WiFi - "adb: error: failed to get feature set: no devices/emulators found"
Along with these kinds of warnings -  "adb server version (41) doesn't match this client (39); killing..."

What you need to do is to set the environment variable ADB to the path of real adb binary from your installation.
On Linux, this works beautifully:

Connect USB first and run the following commands: ```
$ adb tcpip 5555
$ adb connect xxx.xxx.xxx.xxx:5555 
Disconnect USB now and run the following command:
$ ADB=`which adb` scrcpy
```
Note that back-quotes are used here: `which adb`. Alternatively, you can give complete path as this:
`$ ADB=/path/to/sdk/adb scrcpy`

**Comment by oopsmaniac** [comment]
adb: error: failed to get feature set: no devices/emulators found
ERROR: "adb push" returned with value 1 
Personaly i solved the problem in downloading "Universal ADB Driver v6.0" here: https://androidmtk.com/download-universal-adb-driver  and in installing it in following the instructions here: https://androidmtk.com/install-universal-adb-driver  After that my Redmi note 8 pro was recognized perfectly by scrcpy and no error messages anymore.

**Comment by syarz** [comment]
I had this issue and here's how I fixed it (Android 10)

Connect the USB cable and from your android device slide down the Notification Bar and select USB for file transfer (USB Debugging must be enabled) -> keep pressing until you see the USB setting-> here in the "USB Controlled by" sub-menu select "connected devices" & in the "Use USB for" -> Transferring files / Android Auto. This should resolve the problem with the USB connection. Make sure you have installed the USB driver for your android device

**Comment by maximedrouhin** [comment]
I had the same issue, and I fixed it simply by changing the cable. Some cables are for charging only, you have to use a cable capable of transferring data.

**Comment by zackiru** [comment]
INFO: scrcpy 1.18 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 0.9 MB/s (37330 bytes in 0.039s)
[server] INFO: Device: vivo V2031 (Android 11)
INFO: Renderer: opengl
INFO: OpenGL version: 3.0 Mesa 20.0.8
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x2408
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffff4
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2127)
        at android.media.MediaCodec.configure(MediaCodec.java:2043)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:237)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:90)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:255)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:433)
WARN: Device disconnected
WARN: Killing the server...

how can i fix this?

**Comment by rom1v** [comment]
> android.media.MediaCodec$CodecException: Error 0xfffffff4

@zackiru #833

**Comment by cc1-a** [comment]
> When I try to mirror my android phone it says
> 
> adb: error: failed to get feature set: no devices/emulators found ERROR: "adb push" returned with value 1 Press any key to continue... Please help me :'(



> Hi bois. I received this error as well.
> 
> INFO: scrcpy 1.17 https://github.com/Genymobile/scrcpy adb: error: failed to get feature set: more than one device/emulator ERROR: "adb push" returned with value 1
> 
> and I can see my two beloved android phones:
> 
> INFO: scrcpy 1.17 https://github.com/Genymobile/scrcpy adb: error: failed to get feature set: more than one device/emulator ERROR: "adb push" returned with value 1
> 
> Downloads\scrcpy-win64-v1.17>adb devices List of devices attached 5WHssss device 10sssss device
> 
> How can I run two emulators at the same time

you have to enable the USB debugging then that will solve the problem

**Comment by PortWhisperer** [comment]
> I had the same issue, and I fixed it simply by changing the cable. Some cables are for charging only, you have to use a cable capable of transferring data.

Just want to confirm this works on windows. It looks like file transfer mode ironically doesn't invoke USB debugging from the connected workstation, but charging mode does.  As soon as I changed to charging mode, I got the expected RSA fingerprint prompt on my android 8.0 device

**Comment by Netinbook** [comment]
Here is the tried and tested solution.
https://stackoverflow.com/questions/18930050/adb-connection-over-tcp-not-working-now

**Comment by samee-ch** [comment]
> Hi, @mouazvd
> 
> Do you enable adb debug in your phone?
> 
> Thanks.

thanks

**Comment by divyadave1205** [comment]
i have he same issue.
and i tried all of the above solutions.
but nothing worked for me.
please help to clear this issue.

**Comment by rom1v** [comment]
Which scrcpy version? What is the result of `adb devices`?

**Comment by giuseppev177** [comment]
I had a similar problem with strcpy on linux mint xfce. Everything worked when I enabled USB_DEBUGGING in my Android phone in developer mode

**Comment by rom1v** [comment]
Wht is the result of `adb devices`?

**Comment by mshahrin** [comment]
> Ok I figure out sorry. I change my cable and it works.

how did you change your cable?

**Comment by mshahrin** [comment]
> 

Can you show how you had done that?

**Comment by giuseppev177** [comment]
I used the latest version of linux mint xfce on my old satellite laptop.

I installed scrcpy through command sudo apt install

I connected my oppo A15 through USB cable and selected in my android phone
the option "USB TRANSFER FILE".

I launched a shell and typed:

> scrcpy

I got a error message

Looking at various forum I learned that in the android phone the option
USB_DEVELOPER should be turned on.

So I turned on on my phone and connected again to my laptop through USB
cable.

I launched a shell and typed:

> scrcpy

This time the screen of my android phone was replicated on PC screen
correctly without error messages.

That's all.

**Comment by Tino-blipblop** [comment]
> > I had the same issue, and I fixed it simply by changing the cable. Some cables are for charging only, you have to use a cable capable of transferring data.
> 
> Just want to confirm this works on windows. It looks like file transfer mode ironically doesn't invoke USB debugging from the connected workstation, but charging mode does. As soon as I changed to charging mode, I got the expected RSA fingerprint prompt on my android 8.0 device

Worked for me too. USB Transfer mode + usb debugging -> didnt't work. Charging mode + usb debugging -> worked

**Comment by heyakyra** [comment]
I got this because I accidentally ran `adb` from within a `toolbox`/`toolbx` environment (`podman`, drop-in F/L/OSS docker replacement) similar to `distrobox`, and then it wouldn't run in the host environment either.

Even `sudo killall adb` suggested in https://github.com/Genymobile/scrcpy/issues/3054#issuecomment-3795425185 (tried in both) didn't free it up. Not sure what needs to be done, since after running that `sudo adb kill-server` just says `cannot connect to daemon at tcp:5037: Connection refused` but a reboot does the trick.
