### ISSUE TITLE
scrcpy --tcpip doesn't setup a connection correctly when wireless debugging runs on a different port than 5555

### ISSUE THREAD

**Issue by Nowaker** [Genymobile/scrcpy#3591]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: MacOS (but it's irrelevant)
 - scrcpy version: 1.24
 - installation method: brew
 - device model: OnePlus LE2125 (OnePlus 9 Pro)
 - Android version: 11

**Describe the bug**

Phone connected via USB, visible by ADB:

```
% adb devices
List of devices attached
8253bf5d	device
```

Running `scrcpy --tcpip` to do the heavy lifting ("It will automatically find the device IP address, enable TCP/IP mode, then connect to the device before starting") for me:

```
% scrcpy --tcpip
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
2022-11-22 16:27:00.398 scrcpy[42003:780512] INFO: Switching device 8253bf5d to TCP/IP...
2022-11-22 16:27:00.492 scrcpy[42003:780512] INFO: Connecting to 172.20.167.222:5555...
failed to connect to '172.20.167.222:5555': Connection refused
2022-11-22 16:27:01.236 scrcpy[42003:780512] ERROR: Could not connect to 172.20.167.222:5555
2022-11-22 16:27:01.237 scrcpy[42003:780511] ERROR: Server connection failed
```

... But it won't succeed because wireless debugging runs on a different port. I had to `adb tcpip 5555` to change wireless debugging port to 5555 and only then would `scrcpy --tcpip` succeed.

# Feature request

```diff
- It will automatically find the device IP address, enable TCP/IP mode, then connect to the device before starting
+ It will automatically find the device IP address, enable TCP/IP mode, find debugging port, then connect to the device before starting
```

**Comment by rom1v** [comment]
> But it won't succeed because wireless debugging runs on a different port.

I'm surprised that it won't succeed, because in that case scrcpy executes `adb tcpip 5555` beforehand. I don't understand why it does not work.

Anyway, I submitted a PR to use the current adb port if any: #3592.

Please review/test.
