### ISSUE TITLE
muti-screen display does not work

### ISSUE THREAD

**Issue by l511809934** [Genymobile/scrcpy#3594]
I hava 2 screens on my android device.displayids is 0 and 2
run scrcpy --display=0  is ok
but run scrcpy --display=2 ,I got a balck window on my laptop screen. and no error

**Comment by krrishdholakia** [comment]
What version of scrcpy are you running? Are you running the same version of Android on both screens? - [Clerkie](https://calendly.com/kdholakia/clerkie-customer-discovery-call)
