### ISSUE TITLE
Mouse wheel only works on left part of window after rotation

### ISSUE THREAD

**Issue by PkmX** [Genymobile/scrcpy#3598]
**Environment**
 - OS: Arch Linux
 - scrcpy version: 1.24
 - Installation method: Arch Linux official repository package
 - Device model: Pixel 7 Pro
 - Android version: 13

**Describe the bug**
Start `scrcpy` in portrait mode and then rotate to landscape orientation via mod+r, the mouse wheel only now works on the left side of the screen (I suppose it is the part where the original portrait mode overlaps). This can be reproduced with various apps like Google Photos, Lightroom Mobile, Chrome, etc.

**Comment by rom1v** [comment]
Thank you for your report.

Unfortunately, I could not reproduce (the mouse wheel works everywhere on the screen for me).

I suspect the coordinates are not correctly calculated when the display is HiDPI. Does it work from the left to *exactly* the middle of the screen?

Could you please run `scrcpy -Vverbose` (so that input events are logged to the console), switch to landscape, and:
 1. click on the very right on the screen
 2. scroll while the mouse is at the same location (on the very right on the screen)

Then, in addition, you could do the same test but at the rightmost location where scroll still works (probably in the middle of the screen).

Thank you.

**Comment by rom1v** [comment]
Thank you for your tests.

> The cutoff point seems to be around x=1004 (x=1005 no longer works)

Weird.

Does it work with a HID mouse (`scrcpy -M`) (or alternatively with a real mouse) after 1004 pixels?

IIUC, click works fine, only scroll does not, correct?

**Comment by PkmX** [comment]
Yeah, no idea how it ended up with 1004 either.

Scrolling with HID mouse simulation works everywhere. Clicking, dragging, pinch to zoom all work fine after 1004 pixels as well.

**Comment by PkmX** [comment]
Some more testing:

Pixel 2 XL (2880x1440): scrolling works fine everywhere in landscape mode
Pixel 7 Pro in 1440p mode (3120x1440): scrolling stops working after 1341 pixels

**Comment by rom1v** [comment]
> Pixel 7 Pro in 1440p mode (3120x1440): scrolling stops working after 1341 pixels

OK, so at the exact same location on the screen: 1341/3120 ≃1004/2336 ≃ 0.4298

Just to confirm this is not a client side issue, what if you reduce the capture resolution (`scrcpy -m800`)?
Or if you crop the left of the device (play with `--crop`)? Is the "breaking point" the same on the device?

Also, what if you mirror the same device from another computer (if you can)?

**Comment by PkmX** [comment]
Mirroring with reduced resolution (800x368), the cut-off point becomes pixel 344, so it is still around the same ratio: 800/344 = 0.43.

Cropping-out the left 1000 pixels on 3120 width display with `scrcpy --crop=1440:2120:0:1000` just subtracts 1K from the breaking point, which is now at x=341.

Don't have another computer to try on right now.

I also found that when scrolling in areas that does not work produces the following output in logcat:

```
11-28 20:34:59.068  1538  1713 W InputDispatcher: Not sending touch gesture to 8c6166f ActivityRecordInputSink com.google.android.apps.photos/.home.HomeActivity because it is not responsive
```

The activity name depends on what is currently shown on the screen, but you get the same message across all apps.

**Comment by rom1v** [comment]
OK, it looks like a bug in the device ROM :/

**Comment by PkmX** [comment]
This seems to be fixed after updating to December security patch. Closing and thanks for the help!
