### ISSUE TITLE
Some Apps are not working(Black screen)

### ISSUE THREAD

**Issue by Leo-SH-Park** [Genymobile/scrcpy#3599]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: 1.24
 - installation method: Windows releas
 - device model: Galaxy Z Flip 3
 - Android version: 12

**Describe the bug**
Some Apps are not working.
I tried reading DRM ebooks on the Naver Series App.
Before I could(maybe 2 month ago). but now I only see a black screen when I read ebooks.

Below is a link to the app.
https://play.google.com/store/apps/details?id=com.nhn.android.nbooks&hl=ko&gl=US&pli=1

**Comment by rom1v** [comment]
Since Android 12, it is not possible to capture "protected" screen from shell: #2129 #36.
