### ISSUE TITLE
Does not work with apps that block screenshots

### ISSUE THREAD

**Issue by nvllsvm** [Genymobile/scrcpy#36]
Apps such as [Bitwarden](https://play.google.com/store/apps/details?id=com.x8bit.bitwarden) and [Silence](https://f-droid.org/en/packages/org.smssecure.smssecure/) block screenshots. Attemtping to take a screenshot on the device results in this error.

![screenshot_kiss_launcher_20180310-224624](https://user-images.githubusercontent.com/6550543/37249431-4a9fda22-24b5-11e8-8df2-b7d046a4e0b2.png)

Using scrcpy, the app functions normally on the device, but scrcpy displays a black background with the status bar visible. No notification or log output indicates anything abnormal. The screenshot notifciation does **not** appear.

![out](https://user-images.githubusercontent.com/6550543/37249403-b282572e-24b4-11e8-8cb5-9bf736e4d929.png)

Strangely enough, LineageOS's built-in screen recording app captures these applications _without problems_. The device is not rooted.

Tested on a OnePlus 3T running LineageOS 15.1 20180305.

**Comment by rom1v** [comment]
You can disable it in Silence, in Silence settings → Privacy → Screen security.

> Strangely enough, LineageOS's built-in screen recording app captures these applications without problems.

They probably modified the feature in the ROM, because on AOSP, even `screenrecord` do not display the screen content.

**Comment by rom1v** [comment]
Since I added an [entry in the FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#i-get-a-black-screen-for-some-applications-like-silence), I'm closing.

**Comment by npes87184** [comment]
> Now you can (on `dev` branch): [1fdde49](https://github.com/Genymobile/scrcpy/commit/1fdde490fd2a0b89680a2b5da5e5274192398023)

After Testing `SafeInCloud` and `Enpass`, I can confirm that it works.

**Comment by thebigsmileXD** [comment]
Very great, thanks for fixing! I now can finally see the unlock pattern of my phone with broken screen :heart:

**Comment by abele17** [comment]
I really enjoy using scrcpy. I think that it's a great product. Unfortunately I am having the black screen issue mentioned above on some specific apps. I am new to coding so I apologize. I was wondering if someone could explain more in details how you  fixed the issue so that I can do it myself.
Thanks for the help!

**Comment by rom1v** [comment]
The apps which remain black could not be mirrored with scrcpy (some drm prevent it to be captured).

**Comment by abele17** [comment]
Thank you. Great app.

**Comment by arekolek** [comment]
@rom1v Do you know if an app is able to detect the case when an app such as `scrcpy` is pretending to be a secure display even though it's not?

The problem I have is that `scrcpy` allows taking screenshots and screen recordings, even though it pretends to be a secure screen, which creates a security vulnerability.

Furthermore, even if `scrcpy` filtered out protected content from screenshots and recordings, it would be possible to record the whole screen on the computer, unless `scrcpy` would filter that too.

But even then, anybody could build `scrcpy` from source as it is currently and use it to take screenshots of content that was supposed to be protected. So do you know if it's possible to detect "fake" secure displays?

(I know that it's always possible to take a photo of the phone with an ordinary camera, but I don't need to worry about that, I just need to prevent taking screenshots)

**Comment by rom1v** [comment]
I don't know.

FWIW, I think that the users should always be able to take screenshots or videos of ther screen (it's their own device). It's ok that app developers provide a hint that some screen should not be captured by default, but device users should always have the possibility to easily bypass this setting. (I know that this is not the current trend from Google or others.)

**Comment by Rajssss** [comment]
I am having the same issue again with some banking app, which prevents taking screenshots too. I am using android 12. Tried the latest dev branch.

**Comment by kwanice** [comment]
any update onhow to bypass that? some Bank app are black..even on v 1.23
thanks for help

**Comment by hmcomer** [comment]
Any updates on this issue? Is there any possibility to bypass it?

**Comment by rom1v** [comment]
Not since Android 12 #2129.

**Comment by CoolSpot** [comment]
> Any updates on this issue? Is there any possibility to bypass it?

You can bypass it by decompiling the APK, disabling FLAG_SECURE for the main view, and recompiling the APK back.
It is very easy to do using "APKLab" extension for Visual Studio Code.
1) Open APK using APKLab, it decompiles it into a folder structure with smali files
2) in the resulting folder structure search for RegExp android/view/Window;->(set|add)Flag
3) Ignore all occurrences in androidx/* or any third-party namespaces
4) find (usually only one per app) occurrence that is preceded by setting register to 0x2000 like this:
```
    .line 143
    invoke-virtual {p0}, Landroid/app/Activity;->getWindow()Landroid/view/Window;

    move-result-object v0

    const/16 v1, 0x2000

    # invoke-virtual {v0, v1, v1}, Landroid/view/Window;->setFlags(II)V
```
5) comment out whole line calling addFlag/setFlags (as shown above)
6) rebuild&sign APK back by right clicking on the "apktool.yml" file and clicking "APKLab: Rebuild the APK"
7) install the APK on your device
8) enjoy

This approach has been tested on both RSA Authenticator and MS Athenticator apps running on Android 12.

**Comment by Ddfulton** [comment]
Addendum to @CoolSpot's comment for **Duo Mobile**

From grepping `android/view/Window;->(set|add)Flag` I got five hits. None of them were prefixed with 0x2000. They were prefixed with other register addresses. 

I just commented out all of them and it worked like a charm.

**Comment by KaKi87** [comment]
Hello,

Rooted users can bypass `FLAG_SECURE` using [this LSPosed plugin](https://github.com/LSPosed/DisableFlagSecure).

Just tested it successfully.

Thanks

**Comment by RiggiG** [comment]
Root users may also use [this fork](https://github.com/RiggiG/scrcpy-root/tree/dev) which simply runs the scrcpy-server as the system user: https://github.com/Genymobile/scrcpy/issues/3049#issuecomment-1603612740

**Comment by ZwieslerLehrer** [comment]
> Root users may also use [this fork](https://github.com/RiggiG/scrcpy-root/tree/dev) which simply runs the scrcpy-server as the system user: [#3049 (comment)](https://github.com/Genymobile/scrcpy/issues/3049#issuecomment-1603612740)

Is there a non root version for some apps which do not run on rooted devices such as banking apps.

**Comment by KaKi87** [comment]
In order to make a banking app work on a rooted device, you just have to add it to Magisk's DenyList.

**Comment by janwilmans** [comment]
This kind of thing is mostly just annoying normal users and not bringing much in terms of actual security. I can just screenshot the screen with a second phone, so there is no reason to make a lot of fuss in trying to prevent screenshots.

**Comment by rom1v** [comment]
> This kind of thing is mostly just annoying normal users and not bringing much in terms of actual security. I can just screenshot the screen with a second phone, so there is no reason to make a lot of fuss in trying to prevent screenshots.

Yes, I agree. But there's nothing scrcpy can do, it's an Android restriction.

**Comment by KaKi87** [comment]
> there is no reason to make a lot of fuss in trying to prevent screenshots

Actually there is : if screenshots are allowed then any app that manages to get permission can capture any app.

But users should be in control of that setting allowing toggling per-app protection.

**Comment by TechnoSparks** [comment]
While I don't face this issue in apps because I am using a custom ROM with a feature to disable the flag secure, I do wonder if anyone else know how to bypass the black screen on screen lock or biometric auth?

**Comment by CoolSpot** [comment]
@brazenCoding , newer androids don't allow srcpy to make fake secure display.
I have described [here](https://github.com/Genymobile/scrcpy/issues/36#issuecomment-1423452461) how you can recompile a single app to remove the secure flag and have it mirrored.
I use scrcpy every day to get MS Auth and RSA Auth codes from apps modified to be unsercure :)

**Comment by brazenCoding** [comment]
> You'd be better off using the website on desktop.

I'm aware of being able to do this. But the web interface and the mobile interface don't properly interact for showing which chapters you've already read. I read a lot of different ones so it's kinda difficult to keep track of what I've already read when switching back and forth.

**Comment by KaKi87** [comment]
Oh yeah, you're also better off using a third-party platform for progress tracking.

**Comment by brazenCoding** [comment]
> Oh yeah, you're also better off using a third-party platform for progress tracking.

What platform do you use to keep track of what chapters you've read?

**Comment by KaKi87** [comment]
> What platform do you use to keep track of what chapters you've read?

I actually manually use my notes app ([Orgzly](https://play.google.com/store/apps/details?id=com.orgzlyrevived), which you'd have no trouble using with scrcpy), but other people recommend https://www.kenmei.co/

**Comment by gom3sr** [comment]
> [@brazenCoding](https://github.com/brazenCoding) , newer androids don't allow srcpy to make fake secure display. I have described [here](https://github.com/Genymobile/scrcpy/issues/36#issuecomment-1423452461) how you can recompile a single app to remove the secure flag and have it mirrored. I use scrcpy every day to get MS Auth and RSA Auth codes from apps modified to be unsercure :)

Android now has [screenshot detection](https://developer.android.com/about/versions/14/features/screenshot-detection) and [screen recording detection](https://developer.android.com/about/versions/15/features#screen-recording-detection) too. 

Would it be possible to disable them before recompilation? What files and text lines should I look for?

**Comment by civiliann** [comment]
> > This kind of thing is mostly just annoying normal users and not bringing much in terms of actual security. I can just screenshot the screen with a second phone, so there is no reason to make a lot of fuss in trying to prevent screenshots.
> 
> Yes, I agree. But there's nothing scrcpy can do, it's an Android restriction.

I have an idea that does not violate the official Android settings. If scrcpy can be set to display with a delay of 5 to 10 seconds, then I can use scrcpy on termux on my Android phone to record applications that cannot record or screenshot (at this point, the application that needs to record and screenshot has already been closed by me, and scrcpy will record and play content from 5 seconds ago in the background)

**Comment by Chriss-17** [comment]
> Now you can (on `dev` branch): [1fdde49](https://github.com/Genymobile/scrcpy/commit/1fdde490fd2a0b89680a2b5da5e5274192398023)

How to apply it?  (in Android 13)
I'm using scrcpy for Windows :
"[scrcpy-win32-v1.5.zip](https://github.com/Genymobile/scrcpy/releases/download/v1.5-fixversion/scrcpy-win32-v1.5.zip)."
https://github.com/Genymobile/scrcpy/tree/1fdde490fd2a0b89680a2b5da5e5274192398023.

**Comment by mohammadazeemwani** [comment]
> > Any updates on this issue? Is there any possibility to bypass it?
> 
> You can bypass it by decompiling the APK, disabling FLAG_SECURE for the main view, and recompiling the APK back. It is very easy to do using "APKLab" extension for Visual Studio Code.
> 
> 1. Open APK using APKLab, it decompiles it into a folder structure with smali files
> 2. in the resulting folder structure search for RegExp android/view/Window;->(set|add)Flag
> 3. Ignore all occurrences in androidx/* or any third-party namespaces
> 4. find (usually only one per app) occurrence that is preceded by setting register to 0x2000 like this:
> 
> ```
>     .line 143
>     invoke-virtual {p0}, Landroid/app/Activity;->getWindow()Landroid/view/Window;
> 
>     move-result-object v0
> 
>     const/16 v1, 0x2000
> 
>     # invoke-virtual {v0, v1, v1}, Landroid/view/Window;->setFlags(II)V
> ```
> 
> 5. comment out whole line calling addFlag/setFlags (as shown above)
> 6. rebuild&sign APK back by right clicking on the "apktool.yml" file and clicking "APKLab: Rebuild the APK"
> 7. install the APK on your device
> 8. enjoy
> 
> This approach has been tested on both RSA Authenticator and MS Athenticator apps running on Android 12.



This is not working for me for WhatsApp ??
