### ISSUE TITLE
Lag is progressive/cumulative

### ISSUE THREAD

**Issue by innat3** [Genymobile/scrcpy#360]
Hi, I'm using a VR device (Oculus GO) and I made a small app that mirrors the device to a very low bugdet PC. 

I have noticed that lag keeps gradually growing as time goes by, as in if 1sec of lag is perceived during the first minute of playback, it will be twice as much a minute later. Another example of this is that if I unplug the cable, the playback keeps going until all the piled up "remaining" time is reproduced.

At first I was experiencing significant lag so I decreased the bitrate to 1M and it felt smooth, but the problem is that the lag keeps piling up, so after 10min it becomes troublesome.  Is there a way to "Refresh" the view every once in a while? 

this is the command I'm using atm:
scrcpy -f  -b 1M -m 800 -c 1224:1440:0:0
(I've also tried without "-m 800")

PC Specs:
OS: Windows 10
Processor: N4200
RAM: 4GB
Playback is always using cable

**Comment by rom1v** [comment]
> if I unplug the cable, the playback keeps going until all the piled up "remaining" time is reproduced.

Is the CPU at 100% on the computer?

> At first I was experiencing significant lag so I decreased the bitrate to 1M and it felt smooth

Which have more effect on the lag: bitrate (`-b 1M`) or definition (`-m 640`)?

**Comment by innat3** [comment]
> Is the CPU at 100% on the computer?

The CPU usage remains around 60%. There may be however spikes occasionally that rise it to 100% cause by background OS processes.

> Which one have the most effect on latency: bitrate (-b 1M) or definition (-m 640)?

I've made more tests with and without `-m 640`, and it seems to only perform well in the long run if I decrease the resolution. Otherwise, as I stated above, it runs smoothly for a few minutes until the lag grows to a point where it becomes unbearable.

In any case, I suppose I will deem this issue as solved, I'm just annoyed that lag is allowed to pile up like that instead of refreshing or re-synchronizing the playback every once in a while to avoid it.

**Comment by rom1v** [comment]
OK, so your computer probably use software decoding, and consumes the whole CPU (which increase with the definition).

In other words, when it lags, it takes (on average) more time to decode a frame than the delay between two frames.

_scrcpy_ always decode all frames (it gives the whole input to ffmpeg), and may drop decoded images if they are not "rendered" fast enough. However, it never drops frames before they are decoded. This would imply to parse the H.264 stream before feeding ffmpeg, and would corrupt future P-frames which depend on the dropped frames. This would allow to compensate the lag, but I think it is ok require a fast-enough decoder, instead of trying to add complexity and provoke other artefacts to compensate slow computers. :(

**Comment by dfmabbas** [comment]
I have this problem in `macOS`.
What's the solution ?

> macbook pro
> cpu : core i5
> gpu : intel hd 6100
> memory : 8g
> storage : ssd

**Comment by innat3** [comment]
Which settings are you using? 
Try lowering the definition (e.g.:  -m 640)
If that doesn't work try decreasing the bitrate (e.g.:  -b 1M)
Other than that, your specs seem decent, maybe it is related to Macs / the graphics card

**Comment by dfmabbas** [comment]
I use the following command to run, but it still lag.
```
scrcpy -b 100k -m 720
```
The `Vysor` software works well on my laptop.
Games like `Call of Duty: Black Ops` run well on my system.

I also use `Android emulators` that work well.

**Comment by rom1v** [comment]
Press Ctrl+i (in the scrcpy window) to enable framerate info (in the console).

What are the results? Are there many frame skipped (e.g. containing `(+2 frames skipped)`)?

**Comment by dfmabbas** [comment]
I tested two types of Wifi and USB connections.
Command : `scrcpy -b 100k -m 720`
Speed : `0.5 MB/s`
```
2019-01-17 16:35:36.566 scrcpy[9950:1428906] INFO: Initial texture: 408x720
2019-01-17 16:35:59.241 scrcpy[9950:1428906] INFO: FPS counter started
2019-01-17 16:36:00.379 scrcpy[9950:1428906] INFO: 3 fps
2019-01-17 16:36:02.322 scrcpy[9950:1428906] INFO: 10 fps
2019-01-17 16:36:04.069 scrcpy[9950:1428906] INFO: 4 fps
2019-01-17 16:36:04.308 scrcpy[9950:1428906] INFO: 2 fps
2019-01-17 16:36:05.328 scrcpy[9950:1428906] INFO: 8 fps
2019-01-17 16:36:06.293 scrcpy[9950:1428906] INFO: 9 fps
2019-01-17 16:36:09.287 scrcpy[9950:1428906] INFO: 9 fps
2019-01-17 16:36:10.274 scrcpy[9950:1428906] INFO: 8 fps
2019-01-17 16:36:11.300 scrcpy[9950:1428906] INFO: 8 fps
2019-01-17 16:36:12.302 scrcpy[9950:1428906] INFO: 8 fps
2019-01-17 16:36:13.325 scrcpy[9950:1428906] INFO: 7 fps
```

Command : `scrcpy`
Speed : `1.5 MB/s`
```
2019-01-17 16:37:17.231 scrcpy[10002:1429552] INFO: Initial texture: 720x1280
2019-01-17 16:37:23.422 scrcpy[10002:1429552] INFO: FPS counter started
2019-01-17 16:37:24.634 scrcpy[10002:1429552] INFO: 4 fps
2019-01-17 16:37:25.586 scrcpy[10002:1429552] INFO: 3 fps
2019-01-17 16:37:26.611 scrcpy[10002:1429552] INFO: 3 fps
2019-01-17 16:37:27.578 scrcpy[10002:1429552] INFO: 3 fps
2019-01-17 16:37:28.528 scrcpy[10002:1429552] INFO: 3 fps
2019-01-17 16:37:29.451 scrcpy[10002:1429552] INFO: 3 fps
2019-01-17 16:37:30.537 scrcpy[10002:1429552] INFO: 3 fps
2019-01-17 16:37:31.675 scrcpy[10002:1429552] INFO: 4 fps
2019-01-17 16:37:32.561 scrcpy[10002:1429552] INFO: 3 fps
```

**Comment by dfmabbas** [comment]
To test, I swapped the Android menu.

**Comment by rom1v** [comment]
I guess your computer decodes the stream in software (not hardware). Is your CPU at 100% while scrcpy is running?

**Comment by rom1v** [comment]
OK. If you record the screen with:

    adb shell screenrecord /sdcard/file.mp4
    adb pull /sdcard/file.mp4

Then play the file. What is it actual framerate?
