### ISSUE TITLE
Cmd manual start stuck

### ISSUE THREAD

**Issue by 916881120** [Genymobile/scrcpy#3601]
Hello consultation, I use

**adb shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 1.24 log_level=info bit_rate=8000000 tunnel_forward=true max_fps=15 control=true stay_awake=true**

After the command starts, he returns the device information to me, and there is no response, and no interface pops up, thank you
I want to start the server through this command, and then transmit it to the ECS through TCP and display it on the web page after processing, is it directly using the forwarding function?

![e5f7ee35ec1e2c20a9d7f83582bc7b4](https://user-images.githubusercontent.com/47199025/204698604-fd3bdc5a-87a7-4127-94cb-bd5108f39031.png)

**Comment by rom1v** [comment]
To get the raw H.264 stream over TCP, there is an example here: https://code.videolan.org/rom1v/vlc/-/merge_requests/20

**Comment by 916881120** [comment]
> 要通过TCP获取原始H.264流，这里有一个例子：https://code.videolan.org/rom1v/vlc/-/merge_requests/20

Thank you
