### ISSUE TITLE
Android Kardia app presents a blank screen in the srcpy device window

### ISSUE THREAD

**Issue by gjpc** [Genymobile/scrcpy#3606]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: 1.24
 - installation method: Windows release
 - device model: Motorola g Power  (2022)
 - Android version: 12

**Describe the bug**
When I open the Kardia application the sign on screen appears but then the application itself presents a blank screen on the window's device screen. The Kardia app appears on the phone's screen.

Though no cursor is shown on the blank srcpy device window. both mouse and keyboard inputs are transmitted to the Kardia app on the phone.

App: https://play.google.com/store/apps/details?id=com.alivecor.aliveecg&gl=US&pli=1

This did not happen with srcpy before I updated to Android 12 and srcpy 1.24

no error is reported

```
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
C:\Users\gjpc\Desktop\srcpy\scrcpy-server: 1 file pushed, 0 skipped. 55.5 MB/s (41159 bytes in 0.001s)
[server] INFO: Device: motorola moto g power (2022) (Android 12)
INFO: Renderer: direct3d
INFO: Initial texture: 720x1600
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
That's expected since Android 12 for protected apps: #36 #2129.
