### ISSUE TITLE
Can't fine my device and i can't enable the usb debugging option

### ISSUE THREAD

**Issue by AbuuMonkey** [Genymobile/scrcpy#3607]
**Environment**
 - OS: Windows 11
 -  scrcpy version: 1.24
 - installation method: Win Release
 - device model: Xiaomi MI A2
 - Android version: not sure, i suppose 10 or 11

Not sure this is a bug.
I have my phone with broken screen. I reboot it, and passed the lockscreen with OTG adapter. I'm sure i passed it, because when i connect my phone, i can see on the usb device in device list (but obviously with the "This folder is empty").
I tried to use scrcpy, but scrcpy return an error (Could not find any ADB device), and adb devices return an empty list.
I suppose the USB debugging option isn't enable.
I tried also scrcpy --odg but give me same error.
Is there a way to fix this?

Thanks a lot for your help and time.

 - [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Comment by kcpr** [comment]
Hi.

I assume You used `adb` command from the console to connect to the device. I think the problem may be that scrcpy uses kind "build-in" version of ADB which may just be different from Yours.  
So after You connect with `adb` You may try the following:
```
ADB=`which adb` scrcpy
```
or replace `\`which adb\`` with path to Your adb executable.

**Comment by kcpr** [comment]
Ah, sorry, I think I think I didn't understand You correctly at first.

If You've never connected with `adb` to You computer before, do You have "developer options" and "remote debugging" enabled on You phone? If that's true You still have to accept a connection on the phone in a dialog like [this one](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fs3.amazonaws.com%2Fcdn.freshdesk.com%2Fdata%2Fhelpdesk%2Fattachments%2Fproduction%2F2043084078885%2Foriginal%2FRfj9XBiw1rJzUvPR5lEckvYnnWhzcBkVMQ.png%3F1580743933&f=1&nofb=1&ipt=d85633622d259e23e16e2f0624415d42a229399b495bc86c43c375f9c68b182b&ipo=images) .

If I'm right it's not really about scrcpy but ADB connection.

**Comment by kcpr** [comment]
Ah, sorry, I think I didn't understand You correctly before.

I think scrcpy requires USB debugging enabled. So if it's disabled You may first need to enable developer options, then USB debugging and after You try to connect You'd still need to accept a connection on the phone in a dialog like [this one](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fs3.amazonaws.com%2Fcdn.freshdesk.com%2Fdata%2Fhelpdesk%2Fattachments%2Fproduction%2F2043084078885%2Foriginal%2FRfj9XBiw1rJzUvPR5lEckvYnnWhzcBkVMQ.png%3F1580743933&f=1&nofb=1&ipt=d85633622d259e23e16e2f0624415d42a229399b495bc86c43c375f9c68b182b&ipo=images) .

If I'm right it's not really about scrcpy but ADB connection.
