### ISSUE TITLE
Record screen

### ISSUE THREAD

**Issue by LZHD** [Genymobile/scrcpy#362]
```
scrcpy -r file.mp4
/usr/local/share/scrcpy/scrcpy-server.jar: 1 file pushed. 0.2 MB/s (19178 bytes in 0.083s)
INFO: Initial texture: 1080x1920
[mp4 @ 0x7fde000491a0] Codec for stream 0 does not use global headers but container format requires global headers
```

```
scrcpy -v
scrcpy v1.5

dependencies:
 - SDL 2.0.4
 - libavcodec 56.60.100
 - libavformat 56.40.101
 - libavutil 54.31.100
```

version:
* Linux version 4.4.0-139-generic 
* gcc version 5.4.0
* Ubuntu 5.4.0-6ubuntu1~16.04.10

**Comment by rom1v** [comment]
Thank you for your report.

This is a bug in old version of FFmpeg: https://video.stackexchange.com/questions/19953/container-format-requires-global-headers/19954#19954

Could you please test with branch `issue362`, please?

**Comment by LZHD** [comment]
The operation is successful, but the video file cannot be opened.
scrcpy -r file.mp4
/usr/local/share/scrcpy/scrcpy-server.jar: 1 file pushed. 4.4 MB/s (19166 bytes in 0.004s)
INFO: Initial texture: 1080x1920

File size is only 262 bytes
