### ISSUE TITLE
Its possible to run scrcpy also use RNDIS USB Reverse Tether at same time. 

### ISSUE THREAD

**Issue by assegaf** [Genymobile/scrcpy#3627]
- [ ] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

I already use the ADB/USB to be an RNDIS reverse tethering. So Any setting to use ADB via TCP IP will make the USB Reverse Tethering device will be gone, and phone get disconnected from network. But I need it to be able to use scrcpy for remote access.

so Its there any possible feathure to use scrcpy without interrupting the RNDIS USB Reverse Tether network (rndis0 still connected.) ?

**Comment by rom1v** [comment]
Does this help? https://github.com/Genymobile/scrcpy/pull/3592

In any case, if you connect with `adb connect` then run `scrcpy` (without `--tcpip`), it should not disconnect anything.

**Comment by Wall995501** [comment]
💗

**Comment by assegaf** [comment]
I am trying to understand what is your explanation, this is not issue with scrcpy, more of issue with android which not able USB Debugging (ADB) via USB and ADB Via Tcp ip at the same time...

So I wonder if scrcpy able to to its work without ADB, but directly via tcp ip (custom protocol/port/etc) ...
