### ISSUE TITLE
using scrcpy, i am unable to control mobile through IP address. I am getting error value : 10060

### ISSUE THREAD

**Issue by PremkumarThotadi** [Genymobile/scrcpy#3632]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: 1.17
 - installation method: from github (https://github.com/Genymobile/scrcpy)
 - device model: Vivo z1 pro
 - Android version: 10

**Describe the bug**
when i am using scrcpy and trying to control mobile using IP address, i am getting error value :10060.

in cmd prompt:
cannot connect to 100.106.32252:5555: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (10060)
![bluetooth error_scrcpy](https://user-images.githubusercontent.com/105772018/209124377-79e6f95b-df04-487e-ada3-b5d0d4d3d62a.PNG)

**Comment by rom1v** [comment]
Looks like a Windows configuration/firewall issue. If you manage to fix it, please tell us.

**Comment by rom1v** [comment]
Is the device on the same LAN as the computer?

**Comment by PremkumarThotadi** [comment]
Yes, it is on same Network . 
Any idea how to resolve this firewall issue?

**Comment by PremkumarThotadi** [comment]
Sorry , i entered the HW ipaddress instead of Network IPaddress. Its working now
