### ISSUE TITLE
1.25 forward-all-clicks doesn't work in Chrome web content

### ISSUE THREAD

**Issue by yume-chan** [Genymobile/scrcpy#3635]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 11
 - scrcpy version: 1.25
 - installation method: Windows release
 - device model: XiaoMi Mi 11
 - Android version: 12

**Describe the bug**

When using `--forward-all-clicks` argument, mouse clicks doesn't work in Chrome web content area. It works fine in Chrome's own UI (address bar, menu, etc.) and other apps.

Comparing the events with a real OTG mouse, Scrcpy is missing events with `MotionEvent.ACTION_BUTTON_PRESS` and `MotionEvent.ACTION_BUTTON_RELEASE` actions. Normally they are delivered between `MotionEvent.ACTION_DOWN` and `MotionEvent.ACTION_UP`.

![image](https://user-images.githubusercontent.com/1330321/209214101-c06c82b5-11fe-4154-bf22-5393eefb01c6.png)

In Chromium source code, it ignores `MotionEvent.ACTION_DOWN` and `MotionEvent.ACTION_UP` events when `toolType` is set to `MotionEvent.TOOL_TYPE_MOUSE` (changed in Scrcpy 1.25):

https://source.chromium.org/chromium/chromium/src/+/main:ui/android/java/src/org/chromium/ui/base/EventForwarder.java;l=323-331;drc=3decef66bc4c08b142a19db9628e9efe68973e64

```
        // For mousedown and mouseup events, we use ACTION_BUTTON_PRESS
        // and ACTION_BUTTON_RELEASE respectively because they provide
        // info about the changed-button.
        if (eventAction == MotionEvent.ACTION_DOWN || eventAction == MotionEvent.ACTION_UP) {
            // While we use the action buttons for the changed state it is important to still
            // consume the down/up events to get the complete stream for a drag gesture, which
            // is provided using ACTION_MOVE touch events.
            return true;
        }
```

**Comment by rom1v** [comment]
Thank you for your report.

Refs https://github.com/Genymobile/scrcpy/issues/3568#issuecomment-1304871139
cc @paweljasinski

**Comment by rom1v** [comment]
I just wrote a quick&dirty test to inject `ACTION_BUTTON_PRESS` and `ACTION_BUTTON_RELEASE`:

```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/Controller.java b/server/src/main/java/com/genymobile/scrcpy/Controller.java
index a8219edd..7a5bbe9a 100644
--- a/server/src/main/java/com/genymobile/scrcpy/Controller.java
+++ b/server/src/main/java/com/genymobile/scrcpy/Controller.java
@@ -198,9 +198,11 @@ public class Controller {
         pointer.setPressure(pressure);
         pointer.setUp(action == MotionEvent.ACTION_UP);
 
+        boolean isMouse = pointerId == POINTER_ID_MOUSE || pointerId == POINTER_ID_VIRTUAL_MOUSE;
+
         int source;
         int pointerCount = pointersState.update(pointerProperties, pointerCoords);
-        if (pointerId == POINTER_ID_MOUSE || pointerId == POINTER_ID_VIRTUAL_MOUSE) {
+        if (isMouse) {
             // real mouse event (forced by the client when --forward-on-click)
             pointerProperties[pointerIndex].toolType = MotionEvent.TOOL_TYPE_MOUSE;
             source = InputDevice.SOURCE_MOUSE;
@@ -225,10 +227,25 @@ public class Controller {
             }
         }
 
+        if (isMouse && action == MotionEvent.ACTION_UP) {
+            Ln.i("release");
+            MotionEvent buttonEvent = MotionEvent.obtain(lastTouchDown, now, MotionEvent.ACTION_BUTTON_RELEASE, pointerCount, pointerProperties, pointerCoords, 0, buttons, 1f, 1f, DEFAULT_DEVICE_ID, 0, source, 0);
+            device.injectEvent(buttonEvent, Device.INJECT_MODE_ASYNC);
+        }
+
+        Ln.i("action=" + (action == MotionEvent.ACTION_UP ? "up" : "down"));
         MotionEvent event = MotionEvent
                 .obtain(lastTouchDown, now, action, pointerCount, pointerProperties, pointerCoords, 0, buttons, 1f, 1f, DEFAULT_DEVICE_ID, 0, source,
                         0);
-        return device.injectEvent(event, Device.INJECT_MODE_ASYNC);
+        boolean ok = device.injectEvent(event, Device.INJECT_MODE_ASYNC);
+
+        if (isMouse && action == MotionEvent.ACTION_DOWN) {
+            Ln.i("press");
+            MotionEvent buttonEvent = MotionEvent.obtain(lastTouchDown, now, MotionEvent.ACTION_BUTTON_PRESS, pointerCount, pointerProperties, pointerCoords, 0, buttons, 1f, 1f, DEFAULT_DEVICE_ID, 0, source, 0);
+            device.injectEvent(buttonEvent, Device.INJECT_MODE_ASYNC);
+        }
+
+        return ok;
     }
 
     private boolean injectScroll(Position position, float hScroll, float vScroll, int buttons) {
```

I respect the order reported from #3568:
 - `ACTION_DOWN`
 - `ACTION_BUTTON_PRESS`
 - `ACTION_BUTTON_RELEASE`
 - `ACTION_UP`

(or in a more general case the order from this comment https://github.com/Genymobile/scrcpy/issues/3568#issuecomment-1304871139)

But it still does not work with Chrome and `--forward-all-clicks` :/

I also attempted the reverse order (press, down, release, up… just in case), but it does not work better.

**Comment by yume-chan** [comment]
I believe Chrome uses [`getActionButton()`](https://developer.android.com/reference/android/view/MotionEvent#getActionButton()) method to retrieve changed buttons, but to my surprise there is no `setActionButton` method.

**Comment by yume-chan** [comment]
https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/view/MotionEvent.java;l=2710-2720;drc=19270f18c5ecba68898fe1ff2f5a65ee3549dd7e

```
    /**
     * Sets the action button for the event.
     *
     * @see #getActionButton()
     * @hide
     */
    @UnsupportedAppUsage
    @TestApi
    public final void setActionButton(int button) {
        nativeSetActionButton(mNativePtr, button);
    }
```

I'm not familiar with Android and Java, not sure why it's not in the documentation.

**Comment by yume-chan** [comment]
1. Press and hold left button
```
ACTION_DOWN getButtonState = 1
ACTIION_BUTTON_PRESS getActionButton = 1, getButtonState = 1
```

2. Press and hold right button
```
ACTION_BUTTON_PRESS getActionButton = 2, getButtonState = 3
```

3. Release left button
```
ACTION_BUTTON_RELEASE getActionButton = 2, getButtonState = 1
```

4. Release right button
```
ACTION_BUTTON_RELEASE getActionButton = 1, getButtonState = 0
ACTION_UP
```

**Comment by yume-chan** [comment]
https://github.com/Genymobile/scrcpy/compare/master...yume-chan:scrcpy:fix-chrome-mouse?expand=1

This works, but I don't like this approach. I might prefer adding the `actionButton` field to Scrcpy protocol and letting the client generate all ACTION_DOWN, ACTION_UP, ACTION_BUTTON_PRESS and ACTION_BUTTON_RELEASE events directly, because usually the GUI library on the client already has the same concept of `actionButton` in their mouse down and mouse up events.

**Comment by rom1v** [comment]
Thank you :+1:

> letting the client generate all ACTION_DOWN, ACTION_UP, ACTION_BUTTON_PRESS and ACTION_BUTTON_RELEASE events directly, because usually the GUI library on the client already has the same concept of actionButton in their mouse down and mouse up events.

Not SDL apparently ([`SDL_MouseButtonEvent`](https://wiki.libsdl.org/SDL2/SDL_MouseButtonEvent)), nor Qt ([`QEvent::Type`](https://doc.qt.io/qt-6/qevent.html#Type-enum)).

**Comment by yume-chan** [comment]
SDL's `button` field maps to Android's `actionButton`, and `state` to `buttons`. It's in your client code, only not sent to server:

https://github.com/Genymobile/scrcpy/blob/c7b1d0ea9af8bb9603ec8f713f1a5fbf3f628b6a/app/src/input_manager.c#L685-L699

https://github.com/Genymobile/scrcpy/blob/c7b1d0ea9af8bb9603ec8f713f1a5fbf3f628b6a/app/src/mouse_inject.c#L89-L97

Qt also has both `button` and `buttons` in its `QGraphicsSceneMouseEvent` (https://doc.qt.io/qt-6/qgraphicsscenemouseevent.html#button).

**Comment by yume-chan** [comment]
Their mouse events maps to Android's `ACTION_BUTTON_PRESS` and `ACTION_BUTTON_RELEASE`, what they really don't have is Android's `ACTION_DOWN` and `ACTION_UP`, which only happen when first button is pressed and last button is released. But those can be easily synthesized by checking `button == buttons` and `buttons == 0`.

**Comment by yume-chan** [comment]
https://github.com/Genymobile/scrcpy/compare/master...yume-chan:scrcpy:fix-chrome-mouse-v2?expand=1

This version generates those events at client side.

**Comment by rom1v** [comment]
Thank you :+1:

I prefer the server-side, because the events are synthesized (they don't come from the client itself). I will read in more details later.

**Comment by rom1v** [comment]
@yume-chan #3704
