### ISSUE TITLE
Not able to build it on a Linux Distro

### ISSUE THREAD

**Issue by dbc2201** [Genymobile/scrcpy#364]
My config is Ubuntu 18.10. 
I have tried all the prescribed methods for building on an Ubuntu machine, but get stuck after the third dependency set-up.
Can anyone help? #

**Comment by rom1v** [comment]
> but get stuck after the third dependency set-up.

By what do you get stuck?

Once you [installed](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#debianubuntu) the required packages with `apt`, download the [prebuilt server](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#prebuilt-server) (so you don't need to build it yourself), and execute the commands listed.

**Comment by rom1v** [comment]
> what am I doing wrong?

The `meson` command must be executed from the `scrcpy` directory you just cloned:

    git clone https://github.com/Genymobile/scrcpy
    cd scrcpy
    meson …

**Comment by dbc2201** [comment]
@dbc2201 oh, alright. I'll try that. Thank you for the help. I'll try to reach out again if I get stuck, is it okay if I do that?

**Comment by dbc2201** [comment]
![screenshot from 2018-12-04 19-26-37](https://user-images.githubusercontent.com/22192936/49446648-aa8c3480-f7fa-11e8-81b4-2ed8c435b6e6.png)
@rom1v Thank you very much, it works like a charm!
Definitely gonna use this from now on. (I used Vysor previously, *honestly* It was better earlier).
Thank you for the awesome project! Kudos to the whole team!
