### ISSUE TITLE
In version 1.25, the screen does not resize in real time when you manually resize the window, but automatically resize when you release the mouse!

### ISSUE THREAD

**Issue by Helaer** [Genymobile/scrcpy#3640]
@rom1v In version 1.25, when you manually resize the window, the phone screen does not resize with the window, only when the mouse is released.

My computer is windows10 system.

**Comment by rom1v** [comment]
Oh, it's due to https://github.com/Genymobile/scrcpy/commit/18082f60697ae8edad2db950637638c8bb6bf0d2 (I removed the workaround for Windows because it didn't work.

I'm surprised that it worked for you before. See #3458

**Comment by Helaer** [comment]
> 哦，这是由于 [18082f6](https://github.com/Genymobile/scrcpy/commit/18082f60697ae8edad2db950637638c8bb6bf0d2)（我删除了 Windows 的解决方法，因为它不起作用。
> 
> 我很惊讶它以前对你有用。参见 #3458

Now, not only will the picture pause when dragging, but also the picture will tear when adjusting

**Comment by rom1v** [comment]
Please confirm that it works again with d8c2fe6ef2279769089fb617e93735217a8668b4 on `dev` branch.

**Comment by Helaer** [comment]
> 请确认它再次适用于分支上的 [d8c2fe6](https://github.com/Genymobile/scrcpy/commit/d8c2fe6ef2279769089fb617e93735217a8668b4)。`dev`

Sorry, I won't compile it into an exe file. Could you help me compile one

**Comment by Helaer** [comment]
@rom1v It should be OK to restore it. I hope you can release a patch version. For users, the tear caused by the adjustment is very unpleasant.

**Comment by rom1v** [comment]
Here is a win64 binary:

 - [`scrcpy.exe`](https://tmp.rom1v.com/scrcpy/3640/1/scrcpy.exe) <sub>`SHA-256: c4f4a0e06870832634957aa6117665887c74b10022b58c5a9744ee00cdfca1ec`</sub>

**Comment by Helaer** [comment]
> Here is a win64 binary:
> 
> * [`scrcpy.exe`](https://tmp.rom1v.com/scrcpy/3640/1/scrcpy.exe) `SHA-256: c4f4a0e06870832634957aa6117665887c74b10022b58c5a9744ee00cdfca1ec`

@rom1v Perfect work. The screen will not tear when adjusting. I hope you can release a patch version.

**Comment by Helaer** [comment]
@rom1v   Didn't you test it? If you adjust the window from different directions on Windows 10, the screen will tear, but the patch version will not. I hope that the original adjustment method will not be deleted. Thank you.

**Comment by rom1v** [comment]
When I tested, the image was just frozen during resize or drag on both version. The workaround did nothing different on my Windows 10 test machine.

**Comment by rom1v** [comment]
Could you please post a video screen capture when you resize with scrcpy v1.25?

**Comment by Helaer** [comment]
> 当您使用 scrcpy v1.25 调整大小时，您能否发布视频屏幕截图？

https://user-images.githubusercontent.com/52807664/211458882-c012ddac-5d23-4c66-bdc4-4f9641fd98c6.mp4


@rom1v

**Comment by rom1v** [comment]
Thank you :+1:

**Comment by Helaer** [comment]
> Thank you 👍

@rom1v   Hopefully it will be incorporated into the development branch so that this issue can be fixed in the next release, thank you!

**Comment by rom1v** [comment]
It is already on `dev` branch: d8c2fe6ef2279769089fb617e93735217a8668b4
