### ISSUE TITLE
sc_adb_execute may be missing Error Handling

### ISSUE THREAD

**Issue by HaoranLiu14** [Genymobile/scrcpy#3641]
- [√] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ √] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - scrcpy version: [1.25]

**Describe the bug**
The function sc_adb_execute_p in adb.c checks whether its return value is equal to SC_PROCESS_NONE every time it is called. However, the function sc_adb_execute calls sc_adb_execute_p directly, but all calls to the sc_adb_execute function in adb.c do not check whether their return value is equal to SC_PROCESS_NONE. Is this a potential Error Handling bug?

**Comment by rom1v** [comment]
> but all calls to the sc_adb_execute function in adb.c do not check whether their return value is equal to SC_PROCESS_NONE

They all immediately call [`process_check_success_intr()`](https://github.com/Genymobile/scrcpy/blob/d8c2fe6ef2279769089fb617e93735217a8668b4/app/src/adb/adb.c#L152) which calls [`process_check_success_internal()`](https://github.com/Genymobile/scrcpy/blob/d8c2fe6ef2279769089fb617e93735217a8668b4/app/src/adb/adb.c#L126), which immediately [checks](https://github.com/Genymobile/scrcpy/blob/d8c2fe6ef2279769089fb617e93735217a8668b4/app/src/adb/adb.c#L130-L135) if `pid == SC_PROCESS_NONE`).

**Comment by HaoranLiu14** [comment]
I understand, thanks!
