### ISSUE TITLE
"Donation" not allowed

### ISSUE THREAD

**Issue by sytosoim** [Genymobile/scrcpy#3642]
Hello, you wrote to someone in the blog as a comment

```
 31 March 2019, 23:00

Glad you like it :)

Thank you very much for your proposal, but I have no Paypal account. I am already paid to work on open source projects (even if scrcpy is on my free time now), I do not need donations :)

Cheers
```

I can't accept it, such a wonderful app that I use nearly 8 hours per day must receive a donation.
Please, provide a link on any website to remove my frustration and give you back gratefulness.

**Comment by rom1v** [comment]
Hi,

Since then, I opened a donation account (I still work on scrcpy on my free time): https://blog.rom1v.com/about/

Thank you for your support 😉

**Comment by sytosoim** [comment]
Thank you for your time and work 😉
