### ISSUE TITLE
Android Java command line application and Java lambda

### ISSUE THREAD

**Issue by 057a3dd61f99517a3afea0051a49cb27994f94d** [Genymobile/scrcpy#3657]
I really like the idea that I can write an Android command line application using Java, specifically I'm following `server/build_without_gradle.sh`, I'm using exactly the same command for compilation, i.e. `javac -bootclasspath platforms/android-33/android.jar -source 1.8 -target 1.8`, but when creating lambdas, e.g. `Function<Object, Class> f = o -> o.getClass();`, I got:
```
Test.java:4: error: cannot find symbol
                Function<Object, Class> f = o -> o.getClass();
                                            ^
  symbol:   method metafactory(Lookup,String,MethodType,MethodType,MethodHandle,MethodType)
  location: interface LambdaMetafactory
1 error
Fatal Error: Unable to find method metafactory
```
I'm using `jdk-17.0.5+8`, the complete source code is:
```
import java.util.function.Function;
public class Test {
        Test() {
                Function<Object, Class> f = o -> o.getClass();
        }
}
```
What am I doing wrong?

**Comment by rom1v** [comment]
For lambdas, you need `core-lambda-stubs.jar` in your classpath:

```diff
diff --git a/server/build_without_gradle.sh b/server/build_without_gradle.sh
index f4fcba10..4a1be10a 100755
--- a/server/build_without_gradle.sh
+++ b/server/build_without_gradle.sh
@@ -23,6 +23,7 @@ CLASSES_DIR="$BUILD_DIR/classes"
 SERVER_DIR=$(dirname "$0")
 SERVER_BINARY=scrcpy-server
 ANDROID_JAR="$ANDROID_HOME/platforms/android-$PLATFORM/android.jar"
+LAMBDA_JAR="$BUILD_TOOLS_DIR/core-lambda-stubs.jar"
 
 echo "Platform: android-$PLATFORM"
 echo "Build-tools: $BUILD_TOOLS"
@@ -48,7 +49,7 @@ cd "$SERVER_DIR/src/main/aidl"
 
 echo "Compiling java sources..."
 cd ../java
-javac -bootclasspath "$ANDROID_JAR" -cp "$CLASSES_DIR" -d "$CLASSES_DIR" \
+javac -bootclasspath "$ANDROID_JAR" -cp "$LAMBDA_JAR:$CLASSES_DIR" -d "$CLASSES_DIR" \
     -source 1.8 -target 1.8 \
     com/genymobile/scrcpy/*.java \
     com/genymobile/scrcpy/wrappers/*.java
```

**Comment by 057a3dd61f99517a3afea0051a49cb27994f94d** [comment]
On Thu, Jan 05, 2023 at 12:01:34AM -0800, Romain Vimont wrote:
> For lambdas, you need `core-lambda-stubs.jar` in your classpath:
> 
> ```diff
> diff --git a/server/build_without_gradle.sh b/server/build_without_gradle.sh
> index f4fcba10..4a1be10a 100755
> --- a/server/build_without_gradle.sh
> +++ b/server/build_without_gradle.sh
> @@ -23,6 +23,7 @@ CLASSES_DIR="$BUILD_DIR/classes"
>  SERVER_DIR=$(dirname "$0")
>  SERVER_BINARY=scrcpy-server
>  ANDROID_JAR="$ANDROID_HOME/platforms/android-$PLATFORM/android.jar"
> +LAMBDA_JAR="$BUILD_TOOLS_DIR/core-lambda-stubs.jar"
>  
>  echo "Platform: android-$PLATFORM"
>  echo "Build-tools: $BUILD_TOOLS"
> @@ -48,7 +49,7 @@ cd "$SERVER_DIR/src/main/aidl"
>  
>  echo "Compiling java sources..."
>  cd ../java
> -javac -bootclasspath "$ANDROID_JAR" -cp "$CLASSES_DIR" -d "$CLASSES_DIR" \
> +javac -bootclasspath "$ANDROID_JAR" -cp "$LAMBDA_JAR:$CLASSES_DIR" -d "$CLASSES_DIR" \
>      -source 1.8 -target 1.8 \
>      com/genymobile/scrcpy/*.java \
>      com/genymobile/scrcpy/wrappers/*.java
> ```

Works like a charm, thanks a lot!
