### ISSUE TITLE
Cannot use scrcpy on phones

### ISSUE THREAD

**Issue by kylegsp** [Genymobile/scrcpy#3661]
Hey guys! I am using a bot for phone emulation and I had it set up well on another server with xiomi phones.

I have now set it up on a mini server and want to use it on a galaxy s8 but scrpy won't open at all. Its very weird.

The mini server is windows 10 standard. The phone is connected and has usb debugging on, its shows up when I enter adb devices. Yet it wont open in Scrcpy.

Any help please? Not sure whats wrong here.

**Comment by rom1v** [comment]
What's the output in the console? (run `scrcpy-console.bat` on Windows)

**Comment by kylegsp** [comment]
So it seems I get a notification that scrcpy can't run on my computer. Could this be the reason?

Its windows 10 home 32bit.
I can upgrade to 10 pro or 11. Its just a mini server I borrowed.

Or should I run an older scrcpy?

How do I run the console? I put in into cmd and it said error. (The developer of the bot is asleep now, he doesn't know whats wrong either).

**Comment by kylegsp** [comment]
Fixed it. It was the 64bit one. So, changed it to 32bit and now works. Thanks
