### ISSUE TITLE
[Question] Any way to use '--otg --hid-mouse' options without a Desktop Environment?

### ISSUE THREAD

**Issue by gurtonbuster** [Genymobile/scrcpy#3662]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Raspberry Pi OS Lite (Legacy)
 - scrcpy version: 1.24
 - installation method: manual build
 - device model: OnePlus 3
 - Android version: 11 (crDroid 7.19)

**Describe the bug**
I'm using Raspberry Pi OS Lite (Legacy) which doesn't have a desktop environment and if I use 'scrcpy --otg --hid-mouse' it doesn't work.

So is there a way to make it work without a desktop environment?

**Comment by rom1v** [comment]
Nope, HID events are generated on mouse events received by SDL from X11/Wayland/…

**Comment by gurtonbuster** [comment]
OK Thanks.
