### ISSUE TITLE
control with mouse didn't work in xiaomi mobile

### ISSUE THREAD

**Issue by Amirheidarix** [Genymobile/scrcpy#3665]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [Windows release...]
 - device model:
 - Android version: [13]

**Describe the bug**

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work
