### ISSUE TITLE
Keep window always on top

### ISSUE THREAD

**Issue by mianaliasjad** [Genymobile/scrcpy#3666]
Hi,

It is a great tool. But kindly add a feature that allows the phone window to stay always on top of other windows. Thanks

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy#always-on-top

**Comment by Metachemix1** [comment]
@rom1v the provided link doesn't work anymore :) 

https://github.com/Genymobile/scrcpy/blob/master/doc/window.md#always-on-top is working
