### ISSUE TITLE
The receiver process stopped immediately

### ISSUE THREAD

**Issue by wzunknown** [Genymobile/scrcpy#3667]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: windows 11
 - scrcpy version: 
 ```
 scrcpy 1.25 <https://github.com/Genymobile/scrcpy>

Dependencies (compiled / linked):
 - SDL: 2.26.1 / 2.26.1
 - libavcodec: 59.37.100 / 59.37.100
 - libavformat: 59.27.100 / 59.27.100
 - libavutil: 57.28.100 / 57.28.100
 - libusb: - / 1.0.26
 ```
 - installation method: scoop
 - device model: 2210132C (not sure)
 - Android version: 13

**Describe the bug**
The process exited immediately and made the phone disconnect at the same time

```
$ scrcpy -V verbose
scrcpy 1.25 <https://github.com/Genymobile/scrcpy>
DEBUG: ADB device found:
DEBUG:     -->   (usb)              c92060c4            device  2210132C
DEBUG: Device serial: c92060c4
DEBUG: Using server (portable): C:\Users\wz906\scoop\apps\scrcpy\current\scrcpy-server
C:\Users\wz906\scoop\apps\scrcpy\current\scrcpy-server: 1 file pushed, 0 skipped. 89.0 MB/s (42151 bytes in 0.000s)
[server] INFO: Device: Xiaomi 2210132C (Android 13)
[server] DEBUG: Using encoder: 'c2.qti.avc.encoder'DEBUG: Server connected
DEBUG: Starting controller thread
DEBUG: Starting receiver thread

DEBUG: Receiver stopped
DEBUG: Server disconnected
DEBUG: Server terminated
INFO: Renderer: direct3d
DEBUG: Trilinear filtering disabled (not an OpenGL renderer)
DEBUG: Using icon (portable): C:\Users\wz906\scoop\apps\scrcpy\current\icon.png
INFO: Initial texture: 1080x2400
DEBUG: Starting demuxer thread
DEBUG: End of frames
WARN: Device disconnected
DEBUG: quit...
```

**Comment by rom1v** [comment]
Please try with another [encoder](https://github.com/Genymobile/scrcpy#encoder).

**Comment by wzunknown** [comment]
I find some new behavior: when I locked my phone and using the 'OMX.google.h264.encoder', a window would appear at a short time.

**Comment by rom1v** [comment]
Does recording work with `screenrecord`?

```
adb shell screenrecord /sdcard/file.mp4
adb pull /sdcard/file.mp4
```

**Comment by wzunknown** [comment]
`screenrecord` worked, and I could find `file.mp4` from the file explorer in my phone. But the `pull` command failed and make my phone disconnect.

**Comment by wzunknown** [comment]
`push` works fine.

**Comment by wzunknown** [comment]
It works if adb connect using wifi.

**Comment by wzunknown** [comment]
I change my usb cable and it works fine. Really thanks for your help.
