### ISSUE TITLE
scrcpy last only few seconds after showing the phone screen

### ISSUE THREAD

**Issue by Ludo-draw** [Genymobile/scrcpy#3670]
- [ X ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ X ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - Windos 10 Pro 21H2
 - scrcpy version: 1.23 , 1.24, 1.25
 - installation method: windows release
 - device model: LG Velvet (LM-G910EMW)
 - Android version: 12 (Kernel 4.9.227)

**Describe the bug**
After start scrcpy.exe it tries to connect, sometings giving a message (below) and killing the process, sometimes it sucessful connects, shows my phone screen, but just close after 2 to 5 seconds.
-Tried other versions.
-My windows have no restrictions, no antivirus (only defender, that i tried activated and deactivated)
-I searched for similar issues, but didint find any solution, or some that is exactly the same case
-My phone have developer options enabled, debugging usb too, i tried check every debugging options, no success

Sometimes this happens: (And works perfectly for some seconds then it closes completely)
```
scrcpy 1.23 <https://github.com/Genymobile/scrcpy>
C:\Users\lrwor\Desktop\Nova pasta (3)\scrcpy-win64-v1.23\s... file pushed, 0 skipped. 74.5 MB/s (41123 bytes in 0.001s)
[server] INFO: Device: LGE LM-G910 (Android 12)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2456
```

and

Somentimes this happens:
```
scrcpy 1.25 <https://github.com/Genymobile/scrcpy>
adb server version (40) doesn't match this client (41); killing...
```

UPDATE:
tried my wife's phone (Galaxy), it works perfectly, only on my lg doesnt work.

**Comment by rom1v** [comment]
> Sometimes this happens: (And works perfectly for some seconds then it closes completely)

Isn't there a line `WARN: Device disconnected`? (run `scrcpy-console.bat` so that the console does not close on error)
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#device-disconnected

> adb server version (40) doesn't match this client (41); killing...

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#conflicts-between-adb-versions
