### ISSUE TITLE
 Write a program that deletes every 5th byte from a file, but without using a  temporary file or allocating a buffer in the memory. 6. WAP in C to implement FCFS CPU scheduling Algorithm.

### ISSUE THREAD

**Issue by shivam7877** [Genymobile/scrcpy#3671]
#include <stdio.h>

int main() {
    // Open the file for reading and writing
    FILE* file = fopen("file.txt", "r+");

    // Get the size of the file
    fseek(file, 0, SEEK_END);
    long size = ftell(file);
    rewind(file);

    // Iterate through the file, deleting every 5th byte
    for (int i = 0; i < size; i++) {
        fseek(file, i, SEEK_SET);
        if ((i + 1) % 5 == 0) {
            fputc(EOF, file);
        }
    }

    // Close the file
    fclose(file);

    return 0;
}

**Comment by rom1v** [comment]
GitHub is not ChatGPT.
