### ISSUE TITLE
Unable to fix low usage fps ??

### ISSUE THREAD

**Issue by Anonymous-any** [Genymobile/scrcpy#3676]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows 7x64 RTX3060]
 - scrcpy version: [1.25]
 - installation method: [Windows release...x64]
 - device model: bq Aquaris X
 - Android version: [8.1.0]

**Describe the bug**

Tried on linux (mint) is very faster as opengl I been surprised.
So i do same setting in my windows7 and it don't render it faster fps. (I was accustomed to use it like this...)
Then I been tried too change driver render and other different option no change it seem ?
Look i have drops...and low fps

On errors, please provide the output of the console (and `adb logcat` if relevant).
--- adb starting (pid 2700) ---
adb I 01-15 11:13:21  2700   144 main.cpp:63] Android Debug Bridge version 1.0.41
adb I 01-15 11:13:21  2700   144 main.cpp:63] Version 33.0.3-8952118
adb I 01-15 11:13:21  2700   144 main.cpp:63] Installed as path:Scrcpy\adb.exe
adb I 01-15 11:13:21  2700   144 main.cpp:63] 
adb I 01-15 11:13:21  2700   144 auth.cpp:417] adb_auth_init...
adb I 01-15 11:13:21  2700   144 auth.cpp:152] loaded new key from 'C:\path\.android\adbkey' with fingerprint
blablablalablablablalablablablalablablablalablablablalablablablalablablablala
adb I 01-15 11:13:21  2700  3236 transport.cpp:335] xxx.xxx.xxx.xxx:5555: read thread spawning
adb I 01-15 11:13:21  2700  4576 transport.cpp:307] xxx.xxx.xxx.xxx:5555: write thread spawning
adb I 01-15 11:13:21  2700   144 transport.cpp:1706] fetching keys for transport xxx.xxx.xxx.xxx:5555
adb I 01-15 11:13:21  2700   144 auth.cpp:469] Calling send_auth_response
adb I 01-15 11:13:21  2700   144 adb.cpp:176] xxx.xxx.xxx.xxx:5555: offline
adb server killed by remote request
adb I 01-15 11:13:35  2700   144 transport.cpp:1137] kicking transport 00485938 xxx.xxx.xxx.xxx:5555
adb I 01-15 11:13:35  2700   144 transport.cpp:407] BlockingConnectionAdapter(xxx.xxx.xxx.xxx:5555): stopping
adb I 01-15 11:13:35  2700  3236 transport.cpp:339] xxx.xxx.xxx.xxx:5555: read failed: Invalid argument
adb I 01-15 11:13:35  2700  3236 transport.cpp:1230] xxx.xxx.xxx.xxx:5555: connection terminated: read failed
adb I 01-15 11:13:35  2700   144 transport.cpp:425] BlockingConnectionAdapter(xxx.xxx.xxx.xxx:5555): stopped

```
`scrcpy.exe -s xxx.xxx.xxx.xxx:5555 --disable-screensaver --power-off-on-close -S`
scrcpy 1.25 <https://github.com/Genymobile/scrcpy>
scrcpy-server: 1 file pushed, 0 skipped. 62.1 MB/s (42151 bytes in 0.001s)
adb.exe: error: more than one device/emulator
ERROR: "adb reverse" returned with value 1
WARN: 'adb reverse' failed, fallback to 'adb forward'
[server] INFO: Device: bq Aquaris X (Android 8.1.0)
[server] INFO: Device screen turned off
INFO: Renderer: direct3d
INFO: Initial texture: 1080x1920
[server] INFO: Forcing screen off
INFO: FPS counter started
INFO: 0 fps
INFO: 0 fps
INFO: 0 fps
INFO: 7 fps
INFO: 19 fps
INFO: 36 fps
INFO: 15 fps
INFO: 51 fps
INFO: 12 fps
INFO: 17 fps
INFO: 0 fps
INFO: 7 fps
INFO: 26 fps
INFO: 36 fps
INFO: 14 fps
INFO: 36 fps
INFO: 9 fps
INFO: 12 fps
INFO: 16 fps
INFO: 21 fps
INFO: 0 fps
INFO: 0 fps
INFO: 6 fps
INFO: 15 fps
INFO: 33 fps
INFO: 0 fps
INFO: 13 fps
INFO: 8 fps
INFO: 7 fps (+33 frames skipped)
INFO: 9 fps
INFO: 0 fps
INFO: 0 fps
INFO: 11 fps (+1 frames skipped)
WARN: Killing the server...
```

Just replaced some simple values for ridiculous secure... thx

**Comment by rom1v** [comment]
And over USB?

**Comment by Anonymous-any** [comment]
Yeah my bad again, it was my deteriorate wifi connection and I improved windows with TCPoptimizer it is much much better now I close good sunday Maestro
