### ISSUE TITLE
'--otg' got unrecognised on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by slavekrouta** [Genymobile/scrcpy#3678]
Everything is working, but --otg is not. Its not even in -h menu!
console output:
```
########@#############:~$ scrcpy --otg --hid-keyboard --hid-mouse
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
scrcpy: unrecognized option '--otg'
```

**Comment by slavekrouta** [comment]
PS: scrcpy and adb installed using `sudo apt install scrcpy`

**Comment by rom1v** [comment]
> scrcpy 1.21 <https://github.com/Genymobile/scrcpy>

The version packaged in Ubuntu 20.04 LTS is too old.

https://repology.org/project/scrcpy/versions

You can uninstall the package, and install it manually: https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple

**Comment by slavekrouta** [comment]
@rom1v oh sorry. it was a typo. i meant 22.04.1

**Comment by rom1v** [comment]
Yeah, same problem, scrcpy 1.21 does not have OTG support. You need a more recent version.

**Comment by slavekrouta** [comment]
@rom1v im so sorry but my english is very bad... recent is like latest? I taught this is latest version. :(

**Comment by yum13241** [comment]
This is why rolling distros should be recommended more often.
