### ISSUE TITLE
ERROR: Server connection failed

### ISSUE THREAD

**Issue by Cicada000** [Genymobile/scrcpy#3685]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10 22H2 19045.2486
 - scrcpy version: 1.25
 - installation method: Windows release
 - device model: Google Pixel 3
 - Android version: 11

When I start this program, it will report the following error: ```ERROR: Server connection failed```

```
PS C:\Users\Cicada000\Desktop\scrcpy-server-v1.25> ./scrcpy.exe
scrcpy 1.25 <https://github.com/Genymobile/scrcpy>
C:\Users\Cicada000\Desktop\scrcpy-serv... file pushed, 0 skipped. 21.0 MB/s (42151 bytes in 0.002s)
Aborted
ERROR: Server connection failed
```
```
PS C:\Users\Cicada000\Desktop\scrcpy-server-v1.25> ./scrcpy.exe -Vdebug
scrcpy 1.25 <https://github.com/Genymobile/scrcpy>
DEBUG: ADB device found:
DEBUG:     -->   (usb)             899X071NQ            device  Pixel
DEBUG: Device serial: 899X071NQ
DEBUG: Using server (portable): C:\Users\Cicada000\Desktop\scrcpy-server-v1.25\scrcpy-server
C:\Users\Cicada000\Desktop\scrcpy-serv... file pushed, 0 skipped. 10.7 MB/s (42151 bytes in 0.004s)
Aborted
DEBUG: Interrupting socket
DEBUG: Server disconnected
DEBUG: Server terminated
ERROR: Server connection failed
```

**Comment by rom1v** [comment]
Run `adb logcat` in a separate terminal, and start scrcpy.exe. Do you see any relevant errors?

(btw, it's surprising that your scrcpy directory is named `scrcpy-server-v1.25`)

**Comment by Cicada000** [comment]
Sorry, I think I must have made a mistake somewhere.This error should be caused by [other projects](https://github.com/kvarenzn/phisap).I deleted the folder ```/data/local/tmp/scrcpy-server.jar``` and reloaded the project to run normally.

(The naming of folders is a personal habit and allows you to see more clearly.🤣)

**Comment by saYRam** [comment]
restart the phone
