### ISSUE TITLE
What are the minimum requirements to use this?

### ISSUE THREAD

**Issue by kkarakk** [Genymobile/scrcpy#369]
Using it on a core i3 with 4gb of RAM leads to a crash after approx 15 minutes of use

**Comment by rom1v** [comment]
What crash? Do you have an error message?

See https://github.com/Genymobile/scrcpy/issues/341.

**Comment by kkarakk** [comment]
i will try another usb cable. just out of interest, are there any minimum requirements?

**Comment by rom1v** [comment]
> are there any minimum requirements?

[Just](https://github.com/Genymobile/scrcpy/blob/master/README.md#requirements) Android 5 for the device. And a computer "fast enough" to decode the video in real time ("fast enough" depends on the video size and framerate). Recent computers should decode it in hardware anyway.
