### ISSUE TITLE
Android ICS support so that it can be used with a Xperia Play [Feature Request]

### ISSUE THREAD

**Issue by RpiDude** [Genymobile/scrcpy#370]
Many people still use the Xperia Play for gaming since it's still one of the best android devices with buttons despite being from 2011, the problem is that anything above 4.4.4 runs like shit on the Xperia Play so it would be awesome if support for 4.0 ICS could be implemented into scrcpy.

Keep up the good work!

**Comment by rom1v** [comment]
Unfortunately, this probably won't happen. I tried to make it work on Android 4.4, but it failed. See https://github.com/Genymobile/scrcpy/issues/98.

**Comment by evilhedrox** [comment]
I don't know how but a time ago I have used scrcpy with android  4.0.4 with my xperia ion, but now it is showing segmentation fault.

**Comment by rom1v** [comment]
> I have used scrcpy with android 4.0.4 with my xperia ion

I doubt it. It does not work on Android 4.

**Comment by evilhedrox** [comment]
It worked, but I think I changed the adb app that comes with scrcpy. This was I long time ago wih other version of scrcpy.
