### ISSUE TITLE
cannot stat ‘build-server/server/scrcpy-server.jar’

### ISSUE THREAD

**Issue by Smallkki** [Genymobile/scrcpy#371]
When I compiled it ， scrcpy-server.jar  no generation.

**Comment by rom1v** [comment]
Did you execute `ninja` as root? If so, don't.

**Comment by Smallkki** [comment]
> Did you execute `ninja` as root? If so, don't.
> 
> See [4c49b27](https://github.com/Genymobile/scrcpy/commit/4c49b27e9f6be02b8e63b508b60535426bd0291a).

Thank you very much.
