### ISSUE TITLE
Having difficulties with the cross-compile build

### ISSUE THREAD

**Issue by chldbwnstm** [Genymobile/scrcpy#3720]
- [ O] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ O] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Debian 10.2
 - scrcpy version: [e.g. 1.12.1]

I have tried to cross-compile scrcpy for two whole days to create an exe for windows but I am having difficulties.
I tried MSYS2 but couldn't get it to work so I installed Debian 10.2 on a VM.
I got the android-sdk installed and that has been solved but..

1) When I do a ./releash.sh this is the result

![image](https://user-images.githubusercontent.com/11438961/216812941-f3e0284c-fde2-4988-8955-2186817f716d.png)

2) When I do a sudo ./releash.sh this is the result

![image](https://user-images.githubusercontent.com/11438961/216813046-9d42bc17-6916-4581-9b33-46f309ea4f28.png)
![image](https://user-images.githubusercontent.com/11438961/216813076-cb4fa381-90dc-478c-894f-4f06c033e065.png)
![image](https://user-images.githubusercontent.com/11438961/216813086-d8cff71e-d5cd-4165-9cbf-d3338e4cc7aa.png)
![image](https://user-images.githubusercontent.com/11438961/216813092-e0a9ca8f-7236-4ad7-9199-1d5b0f0413d0.png)
![image](https://user-images.githubusercontent.com/11438961/216813104-cb1d2e51-7f76-455e-8fbc-4bad90df8c6e.png)

**Comment by rom1v** [comment]
The issue is that you run the script as root. Sudo rm the whole directory and restart without being root.

**Comment by chldbwnstm** [comment]
I did the samething with debian 11 and did a ./release.sh without sudo and it got further.. but a different error.

![image](https://user-images.githubusercontent.com/11438961/216819524-312e0928-bc80-416c-a002-ad821d8b6d23.png)

**Comment by chldbwnstm** [comment]
@rom1v sudo chmod 777 /usr/lib/android-sdk solved the issue and cross-compile was successful.
