### ISSUE TITLE
macos bug with the.ogg file 

### ISSUE THREAD

**Issue by BilalElhssaini** [Genymobile/scrcpy#3723]
Error: scrcpy: SHA256 mismatch
Expected: 379071af4fa77bc7dacf892ad81d3f92040a628367d34a451a2cdcc997ef27b0
  Actual: f57b56d8aae4c847cf01224fb45293610d801cfdac43d932b5eeab1cd318182a
    File: /Users/bilalelhssaini/Library/Caches/Homebrew/downloads/e163886f3d57674f022eb584f07ef6d71dbbf58fb39c481a2c516ce6bfd4af18--Example.ogg

**Comment by rom1v** [comment]
This is a homebrew error. This has nothing to do with scrcpy. Please report to them.
