### ISSUE TITLE
Video not visible on Udemy app

### ISSUE THREAD

**Issue by tommywalks** [Genymobile/scrcpy#3726]
- [ x ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ x ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: 1.25
 - installation method: windows zip
 - device model: Xiaomi pad 5
 - Android version: 12

**Describe the bug**
I wanted to watch videos on Udemy app. But video itself is not visible in my pc. How could I fix this?
![Screenshot_4](https://user-images.githubusercontent.com/122218015/217740776-8b6aed42-d34b-4c13-bddc-eebb4bf47a28.png)

**Comment by rom1v** [comment]
You can't on Android >= 12. #36 #2129
