### ISSUE TITLE
Rename the new `uid` option

### ISSUE THREAD

**Issue by yume-chan** [Genymobile/scrcpy#3729]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

`dev` branch has a new option called `uid`, for differentiating multiple running Scrcpy instances. IMO it should not be called `uid`, because `uid` is a common Linux concept, which might be useful in other cases.

For example, with this little change, I can create a secure display on rooted Android 12+ devices (tested in an emulator):

https://github.com/Genymobile/scrcpy/compare/dev...yume-chan:scrcpy:feat/secure-display?expand=1

Unrooted:

![image](https://user-images.githubusercontent.com/1330321/218240859-4236a4a3-cecf-4c92-8384-e91cecdf2075.png)

Rooted:

![image](https://user-images.githubusercontent.com/1330321/218240870-5f9e2f48-a4be-4a02-b8e9-5b62dad1ffd2.png)

Use `setUid(2000)` instead of `1000` can fix issues like #1606

So, the new option should be renamed, the new name can be `instance_id` or other more descriptive names.

**Comment by rom1v** [comment]
I renamed from `uid` to `scid`: 439a1fd4ed3d7ada4c5098a6d52893dd4e87082a :+1:

_(I want to keep the name short, because on some devices app_process segfaults when the total command length exceeds 256)_

> For example, with this little change, I can create a secure display on rooted Android 12+ devices

Oh, great :+1:

---

I see that you are doing a lot of R&D work (I'm still working on audio integration), that's awesome :+1: 

Do you work on it in the context of [`ya-webadb`](https://github.com/yume-chan/ya-webadb)?

**Comment by yume-chan** [comment]
ya-webadb is my personal open-source side project, which starts at an experiment of WebUSB API. Before that, I had very little experience on C, Java and Android.

I wouldn't say my works on Scrcpy is "for" or "in the context of" that project. I knew and used Scrcpy way before starting ya-webadb. Integration of Scrcpy in ya-webadb is simply because Scrcpy is the best application I know that uses ADB and Android Shell permission.

**Comment by rom1v** [comment]
Thank you for your work anyway, very useful! :+1:
