### ISSUE TITLE
The problem of occupying resources

### ISSUE THREAD

**Issue by adc36545** [Genymobile/scrcpy#3730]
I want to know whether the old version and the new version occupy the same amount of resources. For example, does the version 1.1 and the latest version occupy the same amount of computer resources?

**Comment by rom1v** [comment]
There is no reason why it would occupy more resources. Just test.

**Comment by Hridoy-31** [comment]
Version 1.1 takes about 45MB memory with around 1.5% CPU usage.
On the other hand, version 1.25 takes about 42MB memory with around 1.4% CPU usage.
