### ISSUE TITLE
[Question] Would you appreciate an NSIS installer for the Windows scrcpy client app?

### ISSUE THREAD

**Issue by cyfrost** [Genymobile/scrcpy#374]
Hello,

Scrcpy is great and I'm loving it thus far. I've seen that there are client apps available for Windows, macOS, and Linux as well (which is a great thing). About the Windows scrcpy app, would you guys be interested in a Installer for this client app? If yes, then I will gladly contribute that part and might also help in automatic builds. We can also get into the NSIS vs MSI debate later on. Do you guys think there's such a need?

**Comment by rom1v** [comment]
Hi,

Thank you for your proposal.

> About the Windows scrcpy app, would you guys be interested in a Installer for this client app?

Yes, I think it might be simpler for Windows users.

Is it possible to create such a Windows installer from Linux? (The releases for Windows are [built from Linux](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#cross-compile-from-linux) using [this makefile](https://github.com/Genymobile/scrcpy/blob/master/Makefile.CrossWindows))

**Comment by cyfrost** [comment]
Great then, I’ll start making the installer program then. About the second part, I believe the installer doesn’t have to handle compilation. Binaries generated in the Linux build release sequence get installed on user system in Windows.

**Comment by rom1v** [comment]
> About the second part, I believe the installer doesn’t have to handle compilation.

That's right, but the release should not require one step on Linux and another step on Windows, so the whole release should be released from Linux (if possible).

**Comment by cyfrost** [comment]
Yes the creation of the installer will be a part of the build process conducted on Linux. Although, the same makefile will need to incorporate changes to pull NSIS and build its compiler from source (ala `makensis`) which can then be used to build scrcpy installer program for Windows. I'll begin working on it starting next week. We'll hopefully get it working soon enough.

**Comment by cyfrost** [comment]
Currently, scrcpy doesn't have an icon except the generic program icon that any executable can have. Don't you think we need a good icon for this app?

**Comment by Magneticdud** [comment]
Well, I don't see how easier can be with an installer. It's already easy, just unzip and doubleclick

**Comment by jimnordb** [comment]
some sort of ADB GUI would be nice also for those not that into CLI

maybe some icon like this? using font awesome pro svg

![image](https://user-images.githubusercontent.com/17293360/54439353-e78c8f00-4738-11e9-8d2d-ca71ce2c45b4.png)
