### ISSUE TITLE
OTG isn't detecting the correct HID devices.

### ISSUE THREAD

**Issue by JustinsKittens** [Genymobile/scrcpy#3740]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 11
 - scrcpy version: 1.25
 - installation method: Windows release
 - device model: Sky Elite 465
 - Android version: 11

**Describe the bug**
`scrcpy --otg` isn't detecting my USB mouse nor my USB keyboard.
It only picks up my built-in camera, for some reason, and the phone I'm trying to connect to.
```
C:\MyStuff\scrcpy-win64-v1.25>scrcpy --otg
scrcpy 1.25 <https://github.com/Genymobile/scrcpy>
INFO: Killing adb daemon (if any)...
ERROR: Multiple (2) USB devices:
ERROR:     -->   SKYE652101016699 (1782:4003)  Unisoc Unisoc Phone
ERROR:     -->               0001 (30c9:0039)  DMEDCA1UIFK4C3 HP TrueVision HD Camera
ERROR: Select a device via -s (--serial)
```

**Comment by rom1v** [comment]
The USB device to select is the phone.

You don't even need an actual USB mouse or keyboard: HID events are synthesized from input events received from SDL.

**Comment by JustinsKittens** [comment]
Ohhhhhh, I'm stupid-
Thank you, I'm sorry for bothering you.
I'm going to close this now
