### ISSUE TITLE
devices missing encoders

### ISSUE THREAD

**Issue by comchris** [Genymobile/scrcpy#375]
Currently playing with a SONY SWR-50 "smartwatch 3" on a SDK23 / 6.0.1 build missing ALL encoders...:
`java.lang.IllegalArgumentException: Failed to initialize video/avc, error 0xfffffffe`....
I would like to ask for a lowres/framerate option - maybe streaming jpg screenshots without the need of the .MediaCodec? It's only 320x320 pixel in this case - maybe raw would work aswell ?

**Comment by rom1v** [comment]
Yes, smartwatches don't have hardware encoder.

Adding jpg screenshots adds too much complexity for the benefit (and it would be low quality/framerate).
