### ISSUE TITLE
JPEG frame stream from the server

### ISSUE THREAD

**Issue by wchensc** [Genymobile/scrcpy#3750]
- [x ] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
Currently I am only using the server code to get the h264 video stream and sending the video frames to remote. One of the problem with the h264 is that when the network is not stable, especially when it has packet loss, the video will be laggy and freezing. Because it has to wait for the next IDR frame to render on the receiver side.

Do we support other formats like JPEG frames from the server? It would be super helpful if the server can directly product a stream of JPEG frames. 

**Describe the solution you'd like**
We can set the format/codec we want when we start the server. 

**Describe alternatives you've considered**
Or is there any easy way to transform the h264 frame stream to JPEG on the server side.

**Comment by nnnpa31** [comment]
> * [x ] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?

Here is an identical question to it: #3680

**Comment by wchensc** [comment]
got it. closing right now.
