### ISSUE TITLE
Add time-limit argument

### ISSUE THREAD

**Issue by mattia-lecci** [Genymobile/scrcpy#3752]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

Related but not solving my issue:
* https://github.com/Genymobile/scrcpy/issues/1032
* https://github.com/Genymobile/scrcpy/issues/818
* https://github.com/Genymobile/scrcpy/issues/1032

**Is your feature request related to a problem? Please describe.**
I am trying to automate the acquisition of videos from an android phone which can last for hours.
I know how long the recording should be, so something like `adb screenrecord --time-limit` would be great (see [here](https://adbshell.com/commands/adb-shell-screenrecord))

**Describe the solution you'd like**
Something similar to `adb screenrecord --time-limit=S <file>` would be great (see [here](https://adbshell.com/commands/adb-shell-screenrecord)), where `S` is the amount of time in seconds of the desired recording duration.

**Describe alternatives you've considered**
My automation system is only working on windows, unfortunately.
I tried interrupting the scrcpy process after a fixed amount of time in multiple ways but it is either not stopping or produces a corrupted video file.

Tests:
* `start /B scrcpy -Nr test.mp4 && timeout /t 5 /nobreak >nul && taskkill /im scrcpy.exe /f`: corrupted file
* Python script 
```python
import subprocess, signal, time

proc = subprocess.Popen(["scrcpy", "-Nr", "test.mp4"],
                        creationflags=subprocess.CREATE_NEW_PROCESS_GROUP)
print("sleeping")
time.sleep(5)
print("terminating")
proc.terminate() # also tried proc.send_signal(signal.CTRL_C_EVENT) and proc.send_signal(signal.CTRL_BREAK_EVENT)
```
  * Results: corrupted file with `terminate()` and `CTRL_BREAK_EVENT`, process not terminating with `CTR_C_EVENT`. In any case, no useful output file
* While running scrcpy, send `adb shell pkill <adb process pid>` (see https://github.com/Genymobile/scrcpy/issues/818#issuecomment-535931801). Nothing happens.

**Comment by rom1v** [comment]
As a workaround, did you test https://github.com/Genymobile/scrcpy/issues/818#issuecomment-535931801?

**Comment by rom1v** [comment]
Ah yes, it's your last test

**Comment by rom1v** [comment]
Just to be sure, if you manually press Ctrl+c in the terminal, is the recorded file corrupted?

**Comment by mattia-lecci** [comment]
Yes, pressing pressing Ctrl+c from windows terminal does work as expected. Sorry for not mentioning that!

**Comment by nnnpa31** [comment]
You can refer to this:
https://stackoverflow.com/questions/7085604/sending-c-to-python-subprocess-objects-on-windows

In python's subprocess, when sending CTRL+C command for stdin of a specific process ID, it will wait for the process to finish before sending it. Therefore, you should change the pid to 0 and send CTRL_C_EVENT to the parent process in order to achieve the purpose of interrupting the process.
which mean:
os.kill(**0**, signal.CTRL_C_EVENT)

**Comment by mattia-lecci** [comment]
Thank you @nnnpa31 !
I had to slightly modify the code suggested in [this answer](https://stackoverflow.com/a/7980368/3940929).

The following setup is working for me.
```python
# demo.py
# this script is launched by wrapper.py

import signal, sys, time, subprocess

def signal_handler(signal, frame):
  print('Ctrl+C received in demo.py')
  time.sleep(1)
  sys.exit(0)

signal.signal(signal.SIGINT, signal_handler)

print('demo.py started')
proc = subprocess.Popen(["scrcpy", "-Nr", "test.mp4"]) # simple scrcpy command
```

```python
# wrapper.py

import subprocess, time, signal, sys, os

def signal_handler(signal, frame):
  print('Ctrl+C received in wrapper.py')
  time.sleep(1)

signal.signal(signal.SIGINT, signal_handler)
print("wrapper.py started")
subprocess.Popen("python demo.py")
time.sleep(5) # Run for 5 seconds
os.kill(0, signal.CTRL_C_EVENT)
```

Launching this with `python wrapper.py` record a 5s video as expected.

This is a nice workaround and it works well enough for me, so I'll close the issue.
Having it natively into scrcpy, though, would be even better!

**Comment by nnnpa31** [comment]
> Having it natively into scrcpy, though, would be even better!

I agree.

**Comment by rom1v** [comment]
See #4052
