### ISSUE TITLE
How to achieve USB connection between Android and Android devices to cast screen

### ISSUE THREAD

**Issue by LeonYWang** [Genymobile/scrcpy#3754]
How to achieve USB connection between Android and Android devices to cast screen.

**Comment by LeonYWang** [comment]
How to achieve USB connection between Android and Android devices to cast screen

**Comment by rom1v** [comment]
Duplicate of #100.

**Comment by LeonYWang** [comment]
I looked at #100 and only found "ya-webadb" to enable USB connection to Android and Android, but this is browser-based and must be networked to run.
"scrcpy-android" does not enable USB connection.
I wish there was an Android app that would enable USB connectivity. Do you have a recommended app, thanks!

**Comment by rom1v** [comment]
> Do you have a recommended app

Nope

**Comment by LeonYWang** [comment]
It works on Linux, Windows and macOS.
Why not work on Android?

**Comment by rom1v** [comment]
Because it requires specific developments: several parts of the app need to be rewritten specifically for Android, while the same code may work on Linux Windows and macOS with slight variations.

**Comment by LeonYWang** [comment]
Looking forward to using your app,

**Comment by Monu-debug** [comment]
> Looking forward to using your app,

Did you find something for usb connection?

**Comment by yusuufhayu17** [comment]
i am having issues connecting it with android 15 any solutions
