### ISSUE TITLE
E: Unable to locate package scrcpy

### ISSUE THREAD

**Issue by davechemwetich** [Genymobile/scrcpy#3759]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

Installing fails in debian 
E: Unable to locate package scrcpy  
in debian

**Comment by rom1v** [comment]
Which version is in which distrib is listed here: https://repology.org/project/scrcpy/versions

**Comment by rom1v** [comment]
On testing, it has been removed, see tracker: https://tracker.debian.org/pkg/scrcpy
You need to add the sid repo.

**Comment by tarikgraba** [comment]
@rom1v do you know why the package has been removed from Debian?
That was practical.

**Comment by rom1v** [comment]
@tarikgraba Yes, because [android-framework-23](https://tracker.debian.org/pkg/android-framework-23) is blocked so it has also been removed, so scrcpy could not be built by Debian.

The framework 23 is very old anyway (it's the framework for Android 6, see [API levels](https://apilevels.com/)). Btw, I wrote a branch to adapt scrcpy so that it can be built with the (official) Android SDK 23: https://github.com/Genymobile/scrcpy/commits/android-framework-23

But I get this error:

> An exception has occurred in the compiler (11.0.18). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com/) after checking the Bug Database (http://bugs.java.com/) for duplicates. Include your program and the following diagnostic in your report. Thank you.
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.lang.invoke.MethodHandles$Lookup not found

This does not happen with newer SDKs. (But anyway, even 23 is not in Debian, so…)

**Comment by tarikgraba** [comment]
You mean more recent than SDK 28 ?
https://packages.debian.org/fr/bookworm/android-sdk

**Comment by rom1v** [comment]
```console
$ apt show android-sdk 
Package: android-sdk
Version: 28.0.2+9
Priority: optional
Section: metapackages
Source: android-sdk-meta
Maintainer: Android Tools Maintainers <android-tools-devel@lists.alioth.debian.org>
Installed-Size: 29.7 kB
Depends: android-sdk-build-tools, android-sdk-common (>= 28.0.2+9), android-sdk-platform-tools, proguard-cli
Recommends: gradle, default-jdk-headless
Suggests: android-sdk-platform-23, maven, proguard-gui
Download-Size: 4012 B
APT-Sources: http://ftp.fr.debian.org/debian testing/main amd64 Packages
Description: Software development kit for Android platform
 The Android SDK includes a variety of tools that help you develop mobile
 applications for the Android platform. The tools are classified into 3 groups:
 SDK Tools, Platform-tools and Build-tools.
 .
 SDK Tools are platform independent and are required no matter which Android
 platform you are developing on. It is the base toolset of Android SDK.
 .
 This metapackage pulls the entire Android SDK.
```

This meta-package depends on `android-sdk-platform-23`, which itself has `android-framework-23` as source:

```console
$ apt show android-sdk-platform-23
Package: android-sdk-platform-23
Version: 6.0.1+r72-6
Priority: optional
Section: devel
Source: android-framework-23
Maintainer: Android Tools Maintainers <android-tools-devel@lists.alioth.debian.org>
Installed-Size: 39.8 MB
Depends: libandroid-23-java (>= 6.0.1+r72-6), libandroid-uiautomator-23-java (>= 6.0.1+r72-6)
Homepage: https://android.googlesource.com
Download-Size: 11.6 MB
APT-Sources: http://ftp.fr.debian.org/debian bullseye/main amd64 Packages
Description: Android SDK Platform for API Level 23 (6.0 Marshmallow)
 This package provides the Android SDK Platform for API Level 23
 (6.0 Marshmallow).
 .
 An Android SDK Platform of a specific API Level is required to build any
 Android applications that target this API Level.
```

**Comment by tarikgraba** [comment]
I see
