### ISSUE TITLE
Run without terminal

### ISSUE THREAD

**Issue by vanthien113** [Genymobile/scrcpy#3762]
Hi there, I'm using scrcpy for along time, but when I run scrcpy, I must open a terminal. May I skip it?

**Comment by rom1v** [comment]
On Windows, run `scrcpy-noconsole.vbs` (on other platforms, just run with a `&` and close the terminal).

**Comment by vanthien113** [comment]
> On Windows, run `scrcpy-noconsole.vbs` (on other platforms, just run with a `&` and close the terminal).

Thanks, it worked.
I'm using macos.

I have a command below, how can I auto close opening Terminal - which used for open scrcpy after it ran?

#! /bin/bash
/opt/homebrew/Cellar/scrcpy/1.24/bin/scrcpy & --disable-screensaver --stay-awake --turn-screen-off --always-on-top

**Comment by rom1v** [comment]
```bash
# close terminal after scrcpy is closed
scrcpy; exit
# close terminal after scrcpy is closed successfully (stay open on error, to get time to read the messages for example)
scrcpy && exit
# run scrcpy and close the terminal immediately
scrcpy & exit
```

**Comment by vanthien113** [comment]
> ```shell
> # close terminal after scrcpy is closed
> scrcpy; exit
> # close terminal after scrcpy is closed successfully (stay open on error, to get time to read the messages for example)
> scrcpy && exit
> # run scrcpy and close the terminal immediately
> scrcpy & exit
> ```

Thanks for reply, but I tried there command, but Terminal screen still there. Are there any wrong?.

> #! /bin/bash
> /opt/homebrew/Cellar/scrcpy/1.24/bin/scrcpy --disable-screensaver --stay-awake --turn-screen-off --always-on-top & exit

**Comment by vanthien113** [comment]
<img width="686" alt="image" src="https://user-images.githubusercontent.com/26648983/222510054-b47afdf1-283b-4eb3-83f1-5b4a71fd230e.png">
It worked, Im missing config for allow close terminal screen after done. many thank

**Comment by rom1v** [comment]
On `zsh`, use `scrcpy &! exit`.

https://stackoverflow.com/questions/19302913/exit-zsh-but-leave-running-jobs-open
