### ISSUE TITLE
brew has installed, but run "brew install scrcpy" error

### ISSUE THREAD

**Issue by Wisdozzh** [Genymobile/scrcpy#377]
brew install scrcpy

Error: No available formula with the name "scrcpy" 
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

brew -v
Homebrew 1.8.5-12-gdbc43a7
Homebrew/homebrew-core (git revision dbc43a; last commit 2018-12-11)
Homebrew/homebrew-cask (git revision dbc43a; last commit 2018-12-11)

what's wrong?

**Comment by rom1v** [comment]
Did you find a solution?

**Comment by Wisdozzh** [comment]
No, it could my brew mistake.

**Comment by rom1v** [comment]
Does it work now?
