### ISSUE TITLE
Wireless ADB gives "NoSuchMethodException", and a few minutes later "Warn: Device disconnected"

### ISSUE THREAD

**Issue by e-t-l** [Genymobile/scrcpy#3770]
- [x ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 11
 - scrcpy version: 1.22
 - installation method: Windows release
 - device model: Pixel 7
 - Android version: 13

**Describe the bug**
When connecting ADB over Wifi, scrcpy will usually connect for a few minutes, then disconnect with the `WARN: Device disconnected` message. However, the console outputs some lines with errors before that, so I don't know if there's anything I need to change to make it run better and hopefully stop crashing? I haven't been able to capture logcat for it, but here is the full CMD output:

```
C:\Program Files\SCRCPY\scrcpy-server: 1 file pushed, 0 skipped. 3.4 MB/s (40955 bytes in 0.012s)
[server] INFO: Device: Google Pixel 7 (Android 13)
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, int]
        at java.lang.Class.getMethod(Class.java:2103)
        at java.lang.Class.getMethod(Class.java:1724)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:103)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:111)
        at com.genymobile.scrcpy.Device.<init>(Device.java:103)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:64)
        at com.genymobile.scrcpy.Server.main(Server.java:326)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
WARN: Device disconnected
```

Is there an issue that I can address regarding the NoSuchMethodException?

**Comment by e-t-l** [comment]
Nevermind, just saw #3497. I'll update to v1.25 and only reopen the issue if that doesn't fix it.

**Comment by e-t-l** [comment]
Updating to v1.25 did fix the method error, but I'm still seeing `device disconnected` after a few minutes. Checking with `adb devices`, I can see that my device _is_ still actively connected to ADB. It's just scrcpy that seems to have disconnected for some reason. 

I acknowledge this isn't much info to go on, so I'll reopen this once I have some logcat output to share.

**Comment by rom1v** [comment]
Run `adb shell` or `adb logcat` in a separate terminal while running scrcpy? Does the command terminate at the same time as scrcpy? If so, it's an adb disconnection.
