### ISSUE TITLE
Does not work with apps that block screenshots

### ISSUE THREAD

**Issue by varun-sappa** [Genymobile/scrcpy#3777]
**Environment**
 - OS: [Windows 11]
 - device model: Pixel 7
 - Built using scoop
 - scrcpy version 1.25
 - Android version: Android 13
 
Using scrcpy, the app functions normally on the device, but scrcpy displays a black background with the status bar visible. No notification or log output indicates anything abnormal. Tested on whatsapp on stock stable release of android 13

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
```

**Comment by rom1v** [comment]
#2129 #36
