### ISSUE TITLE
Error: An exception occurred within a child process:   DownloadError: Failed to download resource "opus"

### ISSUE THREAD

**Issue by xavieryang2011** [Genymobile/scrcpy#378]
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "opus"

**Comment by rom1v** [comment]
WAT? Are you sure this happens in scrcpy? :confused:

**Comment by xavieryang2011** [comment]
> WAT? Are you sure this happens in scrcpy? 😕

yes,when i run 'brew install scrcpy'

**Comment by rom1v** [comment]
Ah ok, then it's a problem in _homebrew_, not in _scrcpy_. :wink:

**Comment by xavieryang2011** [comment]
> Ah ok, then it's a problem in _homebrew_, not in _scrcpy_. 😉

so, how to solve this question? now,i can't install scrcpy

**Comment by rom1v** [comment]
@xavieryang2011 Since it's a `DownloadError`, maybe your network is filtering things that homebrew requires. I don't know. Does it work when you try to install packages other than _scrcpy_ from Homebrew? Related: https://github.com/lihaoyi/Ammonite/issues/890

**Comment by sonmio** [comment]
Andreys-MacBook-Pro-2:~ andreyvoronkov$ brew install git
==> Downloading https://homebrew.bintray.com/bottles/git-2.23.0.mojave.bottle.tar.gz

curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to homebrew.bintray.com:443 
Error: Failed to download resource "git"
Download failed: https://homebrew.bintray.com/bottles/git-2.23.0.mojave.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://www.kernel.org/pub/software/scm/git/git-2.23.0.tar.xz

curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.kernel.org:443 
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "git"
Download failed: https://www.kernel.org/pub/software/scm/git/git-2.23.0.tar.xz

Andreys-MacBook-Pro-2:~ andreyvoronkov$
