### ISSUE TITLE
How to use virtual webcam created by v4l2loopback?

### ISSUE THREAD

**Issue by Bitchlinux** [Genymobile/scrcpy#3781]
Hey guys, I created a virtual camera v4l2loopback /dev/video21 in fedora 37, and linked the default webcam of my notebook which is /dev/video1, so far it worked correctly and without problems, but I want to use this one camera that I created /de/video 21 on Android, use to make video call, but I don't know how to do it in a certain way! I ask for help and thank those who help me ;( How do I link virtual camera dev/video 21 on Android?

**Comment by rom1v** [comment]
You can't. Scrcpy can just send the video stream of the captured device screen to a v4l2 sink.
