### ISSUE TITLE
[Wiki] Documents 'compile from source code'  404

### ISSUE THREAD

**Issue by rehack** [Genymobile/scrcpy#3782]
In Wiki :从源代码编译: [构建](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md) ([简化过程](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple)) 404 not found

**Comment by rom1v** [comment]
The whole README and documentation has been reworked for scrcpy 2.0. The page you are looking for is: https://github.com/Genymobile/scrcpy/blob/master/doc/build.md

I only update the official english version, the wiki for translations is not up to date, and is maintained by users.
