### ISSUE TITLE
Build failure on Fedora 36, AV_CH_LAYOUT_STEREO undefined.

### ISSUE THREAD

**Issue by zenofile** [Genymobile/scrcpy#3783]
scrcpy 2.0 doesn't build on Fedora 36, ffmpeg 5.0.2 – probably because of https://github.com/Genymobile/scrcpy/commit/d66b0b3dccc118600b83988173e6631ad661df51.

Including `libavutil/channel_layout.h` in `demuxer.c` seems to fix the issue.

It builds fine on later Fedora versions without any changes.

**Comment by rom1v** [comment]
Thank you :+1: Fixed on master.
