### ISSUE TITLE
Audio as a system input

### ISSUE THREAD

**Issue by JonnyTech** [Genymobile/scrcpy#3788]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
I want to use `scrcpy` as an input to OBS on Windows. The audio currently is "Desktop Audio" and hence captures sound from all apps. Is it possible to have the audio as a capture device so that I can input it cleanly to OBS?

**Describe the solution you'd like**
An option to create the audio stream from `scrcpy` as a separate input device (aka audio capture device in OBS)

**Describe alternatives you've considered**
Using `scrcpy` as a window capture / game capture source in OBS, but audio is not just for the device but rather from all running applications.

**Additional context**
Windows is my primary use-case - it would be great to have this in Linux too.

**Comment by rom1v** [comment]
For Windows, apparently [EarTrumpet](https://github.com/File-New-Project/EarTrumpet) can help.

**Comment by JonnyTech** [comment]
Thank you, I shall try it :)

(is this something that will ever be implemented?)
