### ISSUE TITLE
ERROR: Could not open audio device: WASAPI can't initialize audio client

### ISSUE THREAD

**Issue by hellishvictor** [Genymobile/scrcpy#3799]
**Environment**
 - OS: Win 7 x64
 - scrcpy version: 2.0
 - installation method: Windows release
 - device model: Samsung Galaxy A
 - Android version: 12

Hi, I tried the new v2.0, and after of display the android desktop, it shows:
`ERROR: Could not open audio device: WASAPI can't initialize audio client: No se ha llamado a CoInitialize.`
`ERROR: Demuxer error`
`WARN: Killing the server...`
And then it closes, Disabling the audio with "scrcpy --no-audio" works.
Cheers.

**Comment by rom1v** [comment]
Could you try to force an [audio driver](https://wiki.libsdl.org/SDL2/FAQUsingSDL):

```
set SDL_AUDIODRIVER=directsound
scrcpy
```

Or 

```
set SDL_AUDIODRIVER=winmm
scrcpy
```

?

**Comment by hellishvictor** [comment]
It crashes with both, "winmm" and "directsound" :(

**Comment by hellishvictor** [comment]
Ok it works, but it sounds very "robotic".

**Comment by rom1v** [comment]
#3793?

**Comment by hellishvictor** [comment]
> #3793?

Yeah, the [new scrcpy](https://tmp.rom1v.com/scrcpy/3793/2/scrcpy.exe) worked like a charm; **you fucking rule!**
Cheers.

**Comment by rom1v** [comment]
Does #3793 fixes the problem with directsound or winmm?

**Comment by hellishvictor** [comment]
directsound

**Comment by brownstem** [comment]
Why do I need an audio driver? All I'm trying to do is use this app to mirror my phone screen to Windows to take a screenshot.

**Comment by Huang930918** [comment]
请问下这个问题怎么解决的？我现在也遇到这个问题，谢谢！

**Comment by Huang930918** [comment]
Hi，Could you tell me how to solve this problem? I have the same problem now, thank you!

**Comment by Felindril** [comment]
Hi,
This erreor is back here w/ new v2.3

`Microsoft Windows [version 10.0.19045.3570]
(c) Microsoft Corporation. Tous droits réservés.

scrcpy 2.3 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)        2C171FDH200BEE            device  Pixel_7
D:\SCRCpy\scrcpy-server: 1 file pushed, 0 skipped. 41.7 MB/s (65851 bytes in 0.002s)
[server] INFO: Device: [Google] google Pixel 7 (Android 14)
INFO: Renderer: direct3d
INFO: Texture: 1080x2400
[server] INFO: Device screen turned off
ERROR: Could not open audio device: WASAPI can't find requested audio endpoint: ├ël├®ment introuvable.
ERROR: Demuxer error
WARN: Killing the server...

`
SCRCpy works fine with --no-audio added

Have a nice day.

**Comment by rom1v** [comment]
> This errer is back here w/ new v2.3

Could you please replace SDL2.dll in your scrcpy 2.3 directory by the one in scrcpy 2.2, please?

**Comment by Felindril** [comment]
> > This errer is back here w/ new v2.3
> 
> Could you please replace SDL2.dll in your scrcpy 2.3 directory by the one in scrcpy 2.2, please?

I just tried, same result.
I also tried with the one in SCRCpy v2.1 to no avail.

Thanks for your time and work,

Chers !

**Comment by rom1v** [comment]
On which version did it work for you? (a full scrcpy release)

**Comment by wine2siri** [comment]
> On which version did it work for you? (a full scrcpy release)

**FYI** 

Just got the same error on **v2.3.1**
**Android 13**
`Microsoft Windows [version 10.0.19045.3570]`

I tried the previous versions one by one till v2.0, the error kept showing up.
Then I tried to replaced the SDL2.dll with other versions, nothing changed.

Finally, I have to use this command for now, `scrcpy --no-audio`.


Thanks for your work, bro. Hope there will be a real solution soon!

![image](https://github.com/Genymobile/scrcpy/assets/67748189/86e652e0-c1a4-4e35-b3dc-d4544dd82217)

**Comment by rom1v** [comment]
Does this workaround work? https://github.com/Genymobile/scrcpy/issues/3856#issuecomment-1482911664

**Comment by wine2siri** [comment]
Thx a lot for your help, it works well for me.

**Comment by wine2siri** [comment]
> Does this workaround work? [#3856 (comment)](https://github.com/Genymobile/scrcpy/issues/3856#issuecomment-1482911664)

Thx a lot for your help, it works well for me!
