### ISSUE TITLE
scrcpy will prevent windows turning off screen after some time

### ISSUE THREAD

**Issue by NewUserHa** [Genymobile/scrcpy#380]
win10 17134.
windows cant turn off screen/display after the time user setted.
```
DISPLAY:
[PROCESS] \Device\HarddiskVolume5\scrcpy-win64\scrcpy.exe

SYSTEM:
[DRIVER] NVIDIA High Definition Audio (HDAUDIO\FUNC_01&VEN_10DE&DEV_0083&SUBSYS_73771121&REV_1001\5&12d02362&0&0001)
An audio stream is currently in use.
```
hope fix

**Comment by rom1v** [comment]
Thank you for your report.

For reference, I think it will be sufficient to enable [`SDL_HINT_VIDEO_ALLOW_SCREENSAVER`](https://wiki.libsdl.org/SDL_HINT_VIDEO_ALLOW_SCREENSAVER) [here](https://github.com/Genymobile/scrcpy/blob/v1.5/app/src/screen.c#L21).

**Comment by antmurph** [comment]
See the same thing, Its unfortunate that `powercfg /requestsoverride process scrcpy.exe` doesnt seem to work either.

Windows 10 Pro
1809

**Comment by rom1v** [comment]
Fixed on `dev`.
