### ISSUE TITLE
Cannot download scrcpy 2.0 from source

### ISSUE THREAD

**Issue by eklebanow** [Genymobile/scrcpy#3802]
Trying to download scrcpy 2.0 on Linux from GitHub... Via source code to use in Linux... Only version 1.25 available

**Comment by rom1v** [comment]
`git pull`

**Comment by eklebanow** [comment]
Tried that already... Only scrcpy 1.25

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rom1v** [comment]
What are the exact command your execute? What is the current commit you are on?

**Comment by eklebanow** [comment]
Here is what I get after executing command

[https://bpa.st/ARBZQ](url)

**Comment by eklebanow** [comment]
Invoking scrcpy works....2.0 with audio loads

Great work! Thanks for this!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
