### ISSUE TITLE
Is --otg supposed to work over tcpip?

### ISSUE THREAD

**Issue by soopacrucial** [Genymobile/scrcpy#3803]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Window 10
 - scrcpy version: 2.0
 - installation method: manual
 - device model: Xiaomi Redmi Note 4
 - Android version: 9

**Describe the bug**
Confused about " It may only work over USB." in the help for the --otg switch.
Is the --otg mode supposed to work over tcpip? I'm getting the following errors:
 
scrcpy --otg
scrcpy 2.0 <https://github.com/Genymobile/scrcpy>
INFO: Killing adb daemon (if any)...
INFO: USB device:  (1f4d:a803)
WARN: On this platform, libusb does not have hotplug capability; device disconnection will not be detected properly
ERROR: REGISTER_HID: libusb error: Entity not found
WARN: Register HID keyboard failed

**Comment by rom1v** [comment]
It could not work over TCP/IP. It can only detect USB devices connected via… USB.

**Comment by soopacrucial** [comment]
Ok, thanks. Sorry if this is a silly question, but since remote control works over tcpip, wouldn't it be trivial to offer the option to turn off the video mirroring of that code to provide a keyboard/mouse-only functionality over tcpip?

**Comment by rom1v** [comment]
> wouldn't it be trivial to offer the option to turn off the video mirroring of that code to provide a keyboard/mouse-only functionality over tcpip?

In OTG mode, the mouse is relative and the cursor appears on the device.

In normal control mode, only click positions are injected, so you need to see where you click. Without video, you can't.

**Comment by soopacrucial** [comment]
Sorry, I may be misunderstanding and this will therefore be another silly question: "so you need to see where you click. Without video, you can't" ...Do you mean the user has to see where to click? In case it wasn't clear, I'm talking about a scenario where you'd be looking at the actual screen of the android device but you'd be controlling it, over tcpip, using a mouse and keyboard physically attached to the controlling device.

**Comment by rom1v** [comment]
> Do you mean the user has to see where to click?

Yes. With the default control mode (without `--hid-mouse` or `--otg`), you have no mouse pointer on the device. The position where the click must be injected is computed from the mirroring window size and the computer mouse pointer location. Without mirroring window, there is no location to click.

**Comment by soopacrucial** [comment]
I think I get it now: the controlling side computes the position of the mouse from the actual incoming video stream data?...I guess you could not actually display that video stream but it wouldn't save on bandwidth, which would be my main goal. Thanks.

**Comment by rom1v** [comment]
In other words, when you move your mouse:
 - in HID/OTG mode (USB only), it moves the cursor on the Android device
 - in "default" injection mode, it moves the cursor on the computer.

In the second case (when the cursor moves on the computer), you need to see something to click on (the device video stream), otherwise, where would you click?

**Comment by WuDi-ZhanShen** [comment]
> 

Using Linux uhid may solve this problem
