### ISSUE TITLE
Can't connect to my phone after upgrade scrcpy 1.25 to 2.0

### ISSUE THREAD

**Issue by sakylian** [Genymobile/scrcpy#3804]
Run under Debian 
uname -a
Linux cool-lily 6.0.0-kali6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1kali1 (2022-12-19) x86_64 GNU/Linux

─$ scrcpy
scrcpy 2.0 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 2.2 MB/s (42151 bytes in 0.019s)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: The server version (1.25) does not match the client (2.0)
	at com.genymobile.scrcpy.Server.createOptions(Server.java:166)
	at com.genymobile.scrcpy.Server.main(Server.java:330)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:392)
ERROR: Server connection failed

**Comment by rom1v** [comment]
> java.lang.IllegalArgumentException: The server version (1.25) does not match the client (2.0)

You're still using the old scrcpy-server in `/usr/local/share/scrcpy/scrcpy-server`.

How did you install the new one?

**Comment by sakylian** [comment]
I manually build the new release source code. How to push the new scrcpy-server to my phone?

**Comment by rom1v** [comment]
You didn't build the new server (or did not install it to your local machine).

Use `install_release.sh` for simplicity: https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md#latest-version

**Comment by sakylian** [comment]
Thanks, it solved. I pull the newest source code and rebuild the app, it works.
