### ISSUE TITLE
Can audio forwarding be added to the documentation for developers

### ISSUE THREAD

**Issue by sbfkcel** [Genymobile/scrcpy#3811]
Now will three sockets be started, one of which is used to forward audio?

**Comment by rom1v** [comment]
Yes, I planned to rewrite `develop.md` when I have some time, it's based on a very old version currently (v1.8 IIRC).

**Comment by rom1v** [comment]
I started to update the developer documentation for the future release (2.1): [branch](https://github.com/Genymobile/scrcpy/commits/develop) | [rendered](https://github.com/Genymobile/scrcpy/blob/develop/doc/develop.md).

It's not exhaustive, and can probably be improved, but at least it's up to date :)

It's not merged yet, please report any error (typo or grammar or anything) in the page.
