### ISSUE TITLE
Add Command-Line-Option to flip horizontal (Feature Request)

### ISSUE THREAD

**Issue by Wonko52** [Genymobile/scrcpy#3819]
A command line option to mirror the output horizontally would be helpful.

Use case:
I use a tablet with a teleprompter app. The app displays the text mirrored, so that it is displayed correctly in the teleprompter mirror.

With a laptop I control the app via scrcpy (text speed, pause, etc.). The text is displayed mirrored in scrcpy - because it is in the app. 

Workaround: I compiled myself a version in which I applied the bugfix described here.
https://github.com/Genymobile/scrcpy/issues/1380#issuecomment-626612709

It would be better if I could simply set this via a parameter at startup.

**Comment by rom1v** [comment]
I understand that it could be convenient, but I'm quite reticent to add this feature, which is not very useful in general cases (only to workaround few buggy devices, and your specific use case your describe here). Here are some reasons.

There are two rotation level in scrcpy (if it ignore the device rotation itself): https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#rotation
 - `--lock-video-orientation`
 - `--rotation`

Both support the 4 possible rotations. However, flip is not possible on the capture side, so it would only be possible for the dynamic orientation.

This parameter (`--rotation`) can also be changed at runtime, so with an additional flip, it would be less intuitive/consistent.

And it would also complexity (i.e. bugs) in the display/screen code (which is already not very pretty).

**Comment by KnIfER** [comment]
or consider a local service for web browser , so that others can do anyting to the video output (using css) ?

**Comment by rom1v** [comment]
Please test #4441.

**Comment by rom1v** [comment]
Implemented in v2.3.
