### ISSUE TITLE
ERROR: Could not open audio device: WASAPI can't initialize audio client: CoInitialize has not been called on Windows 7

### ISSUE THREAD

**Issue by Falcosoft** [Genymobile/scrcpy#3825]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 7 x86/x64
 - scrcpy version: 2.0
 - installation method:  Windows release
 - device model: Model independent error. 
 - Android version: 12

After starting scrcpy-console on Windows 7 x86 or Windows 7 x64 the following error is written to console and the client is closed:
ERROR: Could not open audio device: WASAPI can't initialize audio client: CoInitialize has not been called.
ERROR: Demuxer error
WARN: Killing the server...

It seems to be an SDL2 error. The workaround to use other SDL2 audio driver like winmm or directsound does not work with srccpy since regardless of the buffer size you only get static/garbled audio. 
The solution could be to add CoInitialize() call to the client.

**Comment by rom1v** [comment]
> The workaround to use other SDL2 audio driver like winmm or directsound does not work with srccpy since regardless of the buffer size you only get static/garbled audio.

Even with the new option `--audio-output-buffer=10` on the dev branch (not to be confused with `--audio-buffer=`)? See https://github.com/Genymobile/scrcpy/issues/3793#issuecomment-1465713098

**Comment by Falcosoft** [comment]
> > The workaround to use other SDL2 audio driver like winmm or directsound does not work with srccpy since regardless of the buffer size you only get static/garbled audio.
> 
> Even with the new option `--audio-output-buffer=10` on the dev branch (not to be confused with `--audio-buffer=`)?
> 
> See [#3793 (comment)](https://github.com/Genymobile/scrcpy/issues/3793#issuecomment-1465713098)

Can you provide an x86 Windows binary so I can test it? I cannot test the x64 Windows version at the moment.

**Comment by rom1v** [comment]
Here is a x86 build for the current `dev` branch:

- [`scrcpy-win32-v2.0-18-gd7841664f.zip`](https://tmp.rom1v.com/scrcpy/3825/1/scrcpy-win32-v2.0-18-gd7841664f.zip) <sub>`SHA-256: 5cc35108118c94aa43e39c689dfa7701067c37e2b23662d83eb06ca1e60a8c45`</sub>

**Comment by rom1v** [comment]
See https://github.com/Genymobile/scrcpy/issues/3856#issuecomment-1482911664

**Comment by rom1v** [comment]
> ERROR: Could not open audio device: WASAPI can't initialize audio client: CoInitialize has not been called.

So it's presumably fixed in SDL 2.28 (see https://github.com/libsdl-org/SDL/issues/7478).
[SDL 2.28 RC1](https://github.com/libsdl-org/SDL/releases/tag/prerelease-2.27.1) has just been released, so let's try (branch [`sdl_2_27_1`](https://github.com/Genymobile/scrcpy/commits/sdl_2_27_1)).

Please test this version and confirm that the WASAPI issue is fixed (or not):

- [`scrcpy-win64-sdl228rc1.zip`](https://tmp.rom1v.com/scrcpy/3825/2/scrcpy-win64-sdl228rc1.zip) <sub>`SHA-256: 0f73993c66e46b8956e2dd155e7497f880ee51976c04b11a6db8802c4c4aec55`</sub>

**Comment by vashviS** [comment]
not working on my andriod 13 iqoo z6

**Comment by rom1v** [comment]
@vashviS What is the full output in the console when you run scrcpy?

**Comment by rom1v** [comment]
@Falcosoft I didn't ask, but does it still work for you in the final scrcpy v2.1?

**Comment by vashviS** [comment]
os windows 10 64bit

**Comment by vashviS** [comment]
> > ERROR: Could not open audio device: WASAPI can't initialize audio client: CoInitialize has not been called.
> 
> So it's presumably fixed in SDL 2.28 (see [libsdl-org/SDL#7478](https://github.com/libsdl-org/SDL/issues/7478)). [SDL 2.28 RC1](https://github.com/libsdl-org/SDL/releases/tag/prerelease-2.27.1) has just been released, so let's try (branch [`sdl_2_27_1`](https://github.com/Genymobile/scrcpy/commits/sdl_2_27_1)).
> 
> Please test this version and confirm that the WASAPI issue is fixed (or not):
> 
> * [`scrcpy-win64-sdl228rc1.zip`](https://tmp.rom1v.com/scrcpy/3825/2/scrcpy-win64-sdl228rc1.zip) `SHA-256: 0f73993c66e46b8956e2dd155e7497f880ee51976c04b11a6db8802c4c4aec55`

did not worked just crashes after 10 sec

**Comment by rom1v** [comment]
> did not worked just crashes after 10 sec

Oh, so initially it worked, but then it failed?

Could you please try with audio only (and on scrcpy v2.1 please):

```
scrcpy --no-video
```

**Comment by vashviS** [comment]
sure

**Comment by Falcosoft** [comment]
> @Falcosoft I didn't ask, but does it still work for you in the final scrcpy v2.1?

Yes, it is also working in the final v2.1.
