### ISSUE TITLE
scrcpy2.0 version does not work with 2.0.14 version of SDL2.dll mouse wheel

### ISSUE THREAD

**Issue by Helaer** [Genymobile/scrcpy#3828]
scrcpy2.0 version does not work with 2.0.14 version of SDL2.dll mouse wheel, hope to fix, I need to use 2.0.14 version of SDL2, thank you.

**Comment by Helaer** [comment]
> 这可能是从那时起修复的 SDL 错误？

In scrcpy1.24, the mouse wheel works with SDL2 2.0.14.

**Comment by Helaer** [comment]
@rom1v   Why is it OK to use the old SDL2 version in scrcpy1.24 or lower?

**Comment by rom1v** [comment]
I have no idea. You should bisect both scrcpy and SDL to find out the cause on your machine I guess. I don't have this problem.

**Comment by Helaer** [comment]
@rom1v   May be I did not describe clearly, accurately say so, in scrcpy2.0 if the use of SDL2.0.14 old version, then the mouse wheel scroll page invalid, the premise is that the page supports scrolling, and in scrcpy1.24 use SDL2.0.14 version, then the mouse wheel can normally scroll the page. This issue should be related to the high precision mouse supported in version 1.25, this is just my guess, I hope you can fix it, thank you!

**Comment by rom1v** [comment]
> This problem should be related to 'Add support for high-precision scrolling' added in version 1.25.

Oh, 57056d078ddcac73fe10fcb41395ed21f3d486b6 introduced in v1.25 adds high-precision scrolling, and it calls another API.

But the scrcpy v2.0 release is compiled against SDL 2.26.3, so it uses the new API. If you replaces the old .dll, things will go wrong. If you absolutely want to use SDL 2.0.14, then you must compile scrcpy 2.0 against SDL 2.0.14.

**Comment by Helaer** [comment]
> > 此问题应与版本 1.25 中添加的“添加对高精度滚动的支持”有关。
> 
> 哦，v57056.0 中引入的 [1d25](https://github.com/Genymobile/scrcpy/commit/57056d078ddcac73fe10fcb41395ed21f3d486b6) 增加了高精度滚动，并调用了更新的 SDL API。
> 
> 但是 scrcpy v2.0 版本是针对 SDL 2.26.3 编译的，因此它使用新的 API。如果您更换旧.dll，事情就会出错。如果您绝对想使用 SDL 2.0.14，则必须针对 SDL 2.0.2 编译 scrcpy 0.14。

I need to use the old version SDL2, can you guide me how to do it? Thank you very much.

**Comment by Helaer** [comment]
@rom1v Thank you. I've taken care of it.

**Comment by rom1v** [comment]
Just for my own curiousity, why couldn't you use SDL > 2.0.14?

**Comment by Helaer** [comment]
> 只是出于我自己的好奇心，为什么不能使用 SDL > 2.0.14？

Because I have other software based on SDL2 version 2.0.14 to use with SCRCPY,Now I've recompiled scrcpy2.0 based on SDL2.0.14, and the mouse wheel is working.

**Comment by rom1v** [comment]
> I have other software based on SDL2 version 2.0.14

You can't just upgrade their SDL2.dll to the latest? In that direction, it should work.

**Comment by Helaer** [comment]
> > I have other software based on SDL2 version 2.0.14
> 
> You can't just upgrade their SDL2.dll to the latest? In that direction, it should work.

I don't have the compiled code for this software, which comes bundled with SDL2.0.14, so I can't upgrade SDL2.You provided the solution, thank you very much! Hats off to you!
