### ISSUE TITLE
Scrcpy open and close immediately 

### ISSUE THREAD

**Issue by Bangar237** [Genymobile/scrcpy#3829]
![Capture](https://user-images.githubusercontent.com/68433428/225888499-5482fd23-18e2-4b1b-ac7c-61d3ca04c72d.PNG)

**Comment by Bangar237** [comment]
I did what you just said, but I am getting the same error

**Comment by rom1v** [comment]
Then your new environment variable is not taken into account. What is the result of `echo %ADB%`?

**Comment by Bangar237** [comment]
PS C:\scrcpy> echo %ADB%
%ADB%
PS C:\scrcpy>

**Comment by yume-chan** [comment]
For PowerShell run `$env:ADB`

**Comment by Bangar237** [comment]
PS C:\scrcpy> $env:ADB
c:\adb
ps c:\scrcpy>

**Comment by rom1v** [comment]
^ then in this terminal, run `scrcpy -Vdebug`.

**Comment by rom1v** [comment]
```
PS C:\scrcpy> $env:ADB
c:\adb
```

That's the problem. This `ADB` environment variable must not be set (or if absolutely necessary, it must be set to a correct value).

**Comment by Bangar237** [comment]
PS C:\scrcpy>scrcpy -Vdebug
scrcpy 2.0 <htt://guthub.com/Genymobile/scrcpy>
ERROR: Could not parse bit-rate:  urg

**Comment by Bangar237** [comment]
> ```
> PS C:\scrcpy> $env:ADB
> c:\adb
> ```
> 
> That's the problem. This `ADB` environment variable must not be set (or if absolutely necessary, it must be set to a correct value).

Oh thank you right... it's waking now.
You're the best 👌 👍
