### ISSUE TITLE
Hmm

### ISSUE THREAD

**Issue by SyncMaster93** [Genymobile/scrcpy#3831]
I'm just curious.. if there's option To disable controls how to enable them?

**Comment by rom1v** [comment]
They're enabled by default.

If it does not work by default on your device (Xiaomi?), read https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work or https://github.com/Genymobile/scrcpy#prerequisites.

**Comment by SyncMaster93** [comment]
Weird.. I have both, USB debugging and security one.. I'll try again
