### ISSUE TITLE
aAdbWinApi.dll missing

### ISSUE THREAD

**Issue by ls4ava** [Genymobile/scrcpy#3834]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by ls4ava** [comment]
OS: Windows 10
scrcpy version: 2.0
Instalation method: Downloaded and unziped
Device: PC

Bug: AdbWinApi.dll is missing.

**Comment by anirbandey303** [comment]
I just downloaded the zip file, and the specified file (AdbWinApi.dll) exists.

![image](https://user-images.githubusercontent.com/29774651/226093113-43d1a746-c4e1-42bf-af05-880f54637659.png)

**Comment by rom1v** [comment]
Yes, the file is in the release archive.
