### ISSUE TITLE
Unable to watch video streaming apps like hotstar, jiocinema etc.

### ISSUE THREAD

**Issue by ggguitarg31** [Genymobile/scrcpy#384]
Please help me because I am Unable to watch video streaming apps like hotstar, jiocinema etc. using scrcpy in mac

**Comment by rom1v** [comment]
If you get a black screen, these apps probably [protect the screen](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#i-get-a-black-screen-for-some-applications-like-silence).

**Comment by Magneticdud** [comment]
it's not a bug, it's intentional, otherwise people could pirate the movie

**Comment by rom1v** [comment]
Might work with v1.6 or v1.7?
