### ISSUE TITLE
Low framerate after screen was physically disconnected

### ISSUE THREAD

**Issue by benitofettuccine** [Genymobile/scrcpy#3840]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: W10 64-bit
 - scrcpy version: 2.0 64-bit
 - installation method: straight from the zip file 
 - device model: Pixel 4A
 - Android version: 13 (TQ1A.230205.002)

I had received water damage on my Pixel 4A which prevented me from using the screen but I was still able to use it perfectly fine with scrcpy (only wired). I took it in to a shop for an exact diagnosis of whatever damages could have occurred and they disconnected the screen from the motherboard but reassembled my device afterwards (so there is no image output). Now when I connect to scrcpy my framerate is excruciatingly slow, but still technically usable.

How could disconnecting the LCD panel affect framerate through the renderer? Is there a fix for this?

**Comment by rom1v** [comment]
Disconnectednor broken screen causes vsync rendering issues. Often, it could be avoided by:

```
scrcpy --turn-screen-off
```

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/issues/1285#issuecomment-917513993

**Comment by benitofettuccine** [comment]
Thank you.
