### ISSUE TITLE
support for non-android phones

### ISSUE THREAD

**Issue by mathew-dennis** [Genymobile/scrcpy#3841]
- [ ] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
Now a days popularity of non-android mobile devices are increasing, there are linux phones like pine-phone and ones from librum5 which run  mainline Linux oses like pmos, along with them there are a multitude of hybris devices running oses like Ubuntu-touch and Droidian. But as far as I see scrcpy only support android devices as source.

**Describe the solution you'd like**
It would be great to see scrcpy support such Linux phones and let them share the screen to a laptop.imagining the possibility of plugging the Linux phone to any laptop/ desktop and imminently it becomes my PC, that would be amazing.

**Additional context**
https://droidian.org/
https://ubuntu-touch.io/

**Comment by rom1v** [comment]
That would be great, but it's a different project. scrcpy is very-specific to Android in many ways.
