### ISSUE TITLE
Add an option to mirror audio only

### ISSUE THREAD

**Issue by Piripe** [Genymobile/scrcpy#3842]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
I would like to share the audio of my device without the display window.

**Describe the solution you'd like**
Allow the `--no-display` argument without a record or v4l2 to receive only the audio of the device.

**Describe alternatives you've considered**
Add another command argument (like `--only-audio`) to transmit only the audio of the device.

**Comment by rom1v** [comment]
Please test #3978.
