### ISSUE TITLE
I can't use my cell phone

### ISSUE THREAD

**Issue by eduardo-eller** [Genymobile/scrcpy#3849]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows]
 - scrcpy version: [2.0]
 - installation method: [download release 2.0 64x]
 - device model: Mi 11 PRO
 - Android version: [12]

**Describe the bug**
I can make the connection and see the cell phone screen, but I can't move anything.

```
scrcpy 2.0 <https://github.com/Genymobile/scrcpy>
C:\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 63.3 MB/s (52867 bytes in 0.001s)
[server] INFO: Device: Xiaomi M2102K1AC (Android 12)
INFO: Renderer: direct3d
INFO: Initial texture: 1440x3200

```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work
https://github.com/Genymobile/scrcpy#prerequisites
