### ISSUE TITLE
Commands not working??

### ISSUE THREAD

**Issue by shaveyliam** [Genymobile/scrcpy#385]
Hi, Why the commands are not working i am trying to change the bitrate and resolution. ??

i tried typing in the scrcpy cmd the command but nothing happened thanks.

**Comment by rom1v** [comment]
What do you type exactly, and what is the result?

    scrcpy -m 800 -b 2m

**Comment by Y2Grs** [comment]
I'm having the exact same issue. I type the commands perfectly fine, tried it 100 times. I don't know anything about this stuff but to describe it, it's as if my laptop can't send anything to my phone. Literally nothing happens no matter what I type into the command prompt. My phone's screen does show up on my laptop though, perfectly fine. I can also use my mouse and keyboard from my laptop and it functions on my phone. Keyboard shortcuts work such as ctrl-f makes it fullscreen, stuff like that works, just not any manually typed commands. I just wanted to turn bitrate lower or resolution lower so my laptop could handle it.

**Comment by rom1v** [comment]
> just not any manually typed commands

Just to be sure, do you pass the commands as command-line arguments? (not in the console open once _scrcpy_ is already started)

**Comment by Y2Grs** [comment]
Im not sure I follow what you're asking. I have no experience with this stuff. I'm just typing stuff like this: "scrcpy --bit-rate 2M". Like the example command you gave above, I'm just typing commands like that into the command prompt that opens once I open up scrcpy.exe

**Comment by fbartels** [comment]
@Y2Grs you cannot type in the prompt once the session has started. you need to pass these arguments when initially launching scrcpy, like:
- open cmd prompt
- navigate to folder where scrcpy is stored
- call scrcpy.exe -m 800 -b 2M

this could of course be simplified with a batch script that executes the above commands.

**Comment by fbartels** [comment]
just type scrcpy.exe and press enter

**Comment by Y2Grs** [comment]
oh wow this actually works. thank you guys, helped a lot I was so lost if you couldn't tell lol

**Comment by lologacela** [comment]
I still have my problem, when I use the exe file I don't have problems, but when I use the comand I have this error
![2019-10-07 13_37_53-I can't use commands in windows · Issue #845 · Genymobile_scrcpy2](https://user-images.githubusercontent.com/33681450/66339300-78f76480-e908-11e9-99af-f31a6eb8a934.png)

**Comment by rom1v** [comment]
Use v1.10.

**Comment by CreatorB** [comment]
> 

![image](https://user-images.githubusercontent.com/6529730/179398799-ecaf5be6-8d59-492e-9242-79a0a4e7ef37.png)

I've same issue even with `-m 800 -b 2M` and new scrcpy version.
