### ISSUE TITLE
Screen laggy while it's connected wirelessly

### ISSUE THREAD

**Issue by BeingNoAbility** [Genymobile/scrcpy#3860]
- [ √ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ √ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: 2.0
 - installation method: Windows release
 - device model: Redmi K50 Pro
 - Android version: 13

**Describe the bug**

Extremely laggy while device is connected wirelessly.Stdout reported many frames skipped.No errors.

Here are the videos.
https://user-images.githubusercontent.com/105844676/227729878-c7e9c780-2a44-41c8-845c-6b622313c6f4.mp4
https://user-images.githubusercontent.com/105844676/227729884-040d6b03-5837-47bd-a9f1-a9904166dc57.mp4

```
INFO: 7 fps (+7 frames skipped)
INFO: 9 fps (+4 frames skipped)
INFO: 0 fps
INFO: 7 fps (+15 frames skipped)
INFO: 6 fps
INFO: 9 fps (+7 frames skipped)
INFO: 9 fps
INFO: 6 fps (+7 frames skipped)
INFO: 7 fps (+3 frames skipped)
```

Tried lowering the resolution,bitrates and fps by adding "-m1024 -b2M --max-fps=30", which didn't help.

I'm using Wi-Fi 6 router and Redmi K50 Pro reports its Wi-Fi speed as 2400Mbps. 
While it's connected wirelessly, I noticed that my download/upload speed indicator on status bar didn't even reach above 1M/s, which is strange beacause transmitting video data should cost lots of bandwidth.

While it's connected via usb, its smooth and there isn't frames skipped.

**Comment by rom1v** [comment]
There are two factors to get smooth mirroring on wifi:
 - a good wifi (e.g. 5GHz) without interference
 - a good device (modern devices should work fine, but some may have poor wifi performance, for example I have such problems on an old Samsung Galaxy A4)

Try with another device or the same device on another wifi to know which one is the problem in your case.

I'm closing since this is not a scrcpy problem.

**Comment by BeingNoAbility** [comment]
> There are two factors to get smooth mirroring on wifi:
> 
>     * a good wifi (e.g. 5GHz) without interference
> 
>     * a good device (modern devices should work fine, but some may have poor wifi performance, for example I have such problems on an old Samsung Galaxy A4)
> 
> 
> Try with another device or the same device on another wifi to know which one is the problem in your case.
> 
> I'm closing since this is not a scrcpy problem.

Strangely,switching WiFi-6 from 5Ghz to 2.4Ghz makes scrcpy smoother. What's even more stranger is that my phone is now connected to a father router and connection speed is only 286Mbps. And it's smoother than when it's connected to 5Ghz's 2400Mbps.
There shouldn't be much interference in my room as I can only find my Wi-Fi name . And I'm using 5Ghz. not 2.4Ghz
Maybe it's problem of my router's 5Ghz or 5Ghz is poorly implemented on my phone? But both are quite new models...
