### ISSUE TITLE
 to save the battery of phone. .How to switch off The phone screen when mirroring??

### ISSUE THREAD

**Issue by tarkatsur** [Genymobile/scrcpy#3861]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/doc/device.md#turn-screen-off

**Comment by tarkatsur** [comment]
Thank You Boss
