### ISSUE TITLE
Cannot connect to videoStream server from scrcpy ...

### ISSUE THREAD

**Issue by tiennguyen12g** [Genymobile/scrcpy#3866]
Hello everyone, I am building a project on nodejs and scrcpy. I try to get the video stream from scrcpy by running a socket: 
```
adb forward tcp:8000 localabstract:scrcpy
adb push C:/ProgramData/scrcpy-win64-v2.0/scrcpy-server-v2.0 /data/local/tmp/scrcpy-server-v2.0.jar
adb shell CLASSPATH=/data/local/tmp/scrcpy-server-v2.0.jar app_process / com.genymobile.scrcpy.Server 2.0 tunnel_forward=true max_fps=30 cleanup=false max_size=1600 raw_video_stream=true

```
```
const WebSocket = require('ws');
const {spawn} = require('child_process');
const fs = require('fs');
const {Buffer} = require('buffer');

const ws = new WebSocket('ws://127.0.0.1:8000');

ws.on('message', (data) => {
    console.log(`data:`, data); // Nothing log in here
    const dataEncode = new Uint8Array(Buffer.from('data'));
    fs.writeFile('ws.txt', dataEncode, (err) =>{
      if(err) throw err;
      console.log('Write Successed');
    })
});
```
the localhost:8000 running, i use html try to display the video stream, but nothing display. I try some button (increase voulme, decrease volume..) to control the device, it works fine. And then I know this is server control-socket, not server return h264 data. 
Please give me a code or guideline that i can open server video-socket.
Thank eveyone...

**Comment by rom1v** [comment]
Try to add `control=false audio=false`, otherwise it waits for other socket connections.

**Comment by tiennguyen12g** [comment]
> Try to add `control=false audio=false`, otherwise it waits for other socket connections.

Thank bro, i spent one day do find a way. But i with this way I can connect only one device. How can i connect and get multiple video stream from multiple device? Do you have any document about this case?
Thank bro.
