### ISSUE TITLE
Demuxer 'audio'

### ISSUE THREAD

**Issue by prasunyadav** [Genymobile/scrcpy#3869]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: WINDOWS 10
 - scrcpy version: 2.0
 - installation method: USB
 - device model:VIVO Z1 PRO
 - Android version: 11 
While running scrcpy my phone isn't forwarding audio in the terminal there is a line:

Warn: Demuxer 'audio' : stream explicitly disabled by the device.

Help me to fix it i cant stream my audio to scrcpy

**Comment by rom1v** [comment]
Please stop opening several issues for the same question: #3868.

**Comment by prasunyadav** [comment]
> Please stop opening several issues for the same question: #3868.

I have that after putting code it's still not working (adb shell am start -n com.android.shell/.HeapDumpActivity)

**Comment by prasunyadav** [comment]
I have tried that it's still not working demuxer audio i have Android 11 vivo Z1 pro

**Comment by rom1v** [comment]
This version? https://github.com/Genymobile/scrcpy/issues/3796#issuecomment-1472879886

What is the full console output?

**Comment by rom1v** [comment]
> Android 11 vivo Z1 pro

Ah! Vivo!

See #3805.
