### ISSUE TITLE
get hardware sensor data wirelessly

### ISSUE THREAD

**Issue by cristipurdel** [Genymobile/scrcpy#387]
This is more of a complex feature containing:
1. I would like to have scrcpy managing a lot of android devices (I have a small 20 devices used for boinc) via wireless, something like teamviewer does but with hardware data additionally.
2. All this should be inside a special menu, and for each android device, I would like to see the CPU total load, RAM utilization, CPU frequency, and other hardware data
For reference you can have a look over https://github.com/BOINC/boinc/issues/1699

**Comment by rom1v** [comment]
I think it's out-of-scope for scrcpy.
