### ISSUE TITLE
Unable to input in Chinese and reported an error

### ISSUE THREAD

**Issue by roulen100** [Genymobile/scrcpy#3873]
Sorry to disturb you. I encountered the following error using the Chinese input method of "Sogou Input method,or Baidu Input method". I hope it can be fixed. Thank you.".
[server] WARN: Could not inject char u+5927
[server] WARN: Could not inject char u+5728
[server] WARN: Could not inject char u+57ce
[server] WARN: Could not inject char u+971c

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/tmp/FAQ.md#special-characters-do-not-work

**Comment by roulen100** [comment]
> https://github.com/Genymobile/scrcpy/blob/tmp/FAQ.md#special-characters-do-not-work

Oh, I'm sorry, but thank you very much
