### ISSUE TITLE
Black screen 

### ISSUE THREAD

**Issue by Sourav667678** [Genymobile/scrcpy#3882]
Android version 12
 
Device : Redmi note 11

Some app black screen problem 

How can i solve it?

**Comment by Sourav667678** [comment]
See this video

**Comment by Sourav667678** [comment]
![Uploading IMG_20230331_114217.jpg…]()

**Comment by rom1v** [comment]
On Android 12, views with FLAG_SECURE may not be mirrored. See #36 #2129.

**Comment by Sourav667678** [comment]
I can't understand..please tell me how can i solved it

**Comment by rom1v** [comment]
It can't. Don't use apps which request to the Android system not to be captured.
