### ISSUE TITLE
Screen of SCRCPY freeze

### ISSUE THREAD

**Issue by BomjNarik** [Genymobile/scrcpy#3883]
**Environment**
 - OS: [Windows 10]
 - scrcpy version: [scrcpy 2.0]
 - installation method: [Windows release...]
 - device model: any devices
 - Android version: [any]

**Describe the bug**
I connected to some devices with this command:scrcpy --stay-awake -s "serial of each devices"
I placed the all (7-8 devices) windows of SCRCPY at the work space of Windows 10 (all windows are placed and displayed at work space)
Binded the all SCRSPY windows to OSB to recording
The all SCRCPY windows works and recording properly while my monitor is power ON, but
when I turn off the monitor, the windows of SCRCPY are frozen (no any actions not performed, the picture just paused)
after powered ON of monitor the all windows of SCRSCPY remain frozen until to the next action.

I checked this issue with youtube video and games.
The record always displayed without pauses/freezes.

So, how i can record screen of  SCRSCPY windows even when you turn off  the monitor?
Maybe i should use the specific conditions -- for SCRCPY ?

Thanks for your help in advance

**Comment by rom1v** [comment]
> Binded the all SCRSPY windows to OSB to recording

For information, does it also happen if you don't record via OBS?

As a sde note, you can [record](https://github.com/Genymobile/scrcpy/blob/master/doc/recording.md) with scrcpy directly (you'll get the original capture timings, so it is better than rendering into a window and capturing the window).

**Comment by BomjNarik** [comment]
>For information, does it also happen if you don't record via OBS?"
Yes it the same. 

>you can [record](https://github.com/Genymobile/scrcpy/blob/master/doc/recording.md) with scrcpy
That’s not exactly what need to me. 
It's used the internal space of device to recording and the record can be damaged if the device fallen down or has the some exception.

I think that this way [Video4Linux](https://github.com/Genymobile/scrcpy/blob/master/doc/v4l2.md#video4linux) would solve my problem, but it provided only for Linux =(

I have the some ideas for solve.
I want to try to launch the SCRCPY via sandbox or the background of the "game" or some dynamic scene.

**Comment by BomjNarik** [comment]
I found some interesting case:

I launched SCRCPY for some devices. Launched the call app in devices and entered any  digits.
Input cursor constantly flashing. 

When I turn off the monitor the all windows of scrcpy are freezing. 
After this i connected to PC via remote screen and scrcpy remain frozen even when I interact with them.
But...
All activities are sent to the device and performed but are not rendered on the PC.

scrcpy windows "repair" until to the last performed action only after the monitor screen is on.

**Comment by BomjNarik** [comment]
[(actions_via_remote)_2023-04-01 13-08-25.zip](https://github.com/Genymobile/scrcpy/files/11128627/actions_via_remote._2023-04-01.13-08-25.zip)
Please check the video record for previous comment

>I found some interesting case:

**Comment by rom1v** [comment]
> It's used the internal space of device to recording

No, it is recorded directly on the computer.

> and the record can be damaged if the device fallen down

Nope, try to record and unplug your device at any time, the recording file should be correct.

> or has the some exception.

If the scrcpy client _crashes_ (e.g. segfault), indeed, but that should never happen, and if you ever see such a crash, it's a major issue you should report immediately.


About your freeze, it's either an issue in SDL or in your graphic drivers (scrcpy just calls the function to render, it has no control about the actual rendering when the monitor is on or off).

**Comment by BomjNarik** [comment]
>https://github.com/Genymobile/scrcpy/issues/3883#issuecomment-1492850259

It's works also with win+L combination.
I will check this this cases at another PCs and share result of this.

Did you check this from your side ?

**Comment by BomjNarik** [comment]
Checked at another PC it works good.

I’ll look for reason on first PC.

**Comment by BomjNarik** [comment]
It was Windows 1809 issue.
The issue not reproduced after use another version
