### ISSUE TITLE
cant stream audio on my device

### ISSUE THREAD

**Issue by netflexs** [Genymobile/scrcpy#3886]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: windows 7 sp 1
 - scrcpy version: 2.0
 - installation method: Release EXE 64bit
 - device model: V2403 / Vivo Y20 2021
 - Android version: 11

**Describe the bug**
this is bug from vivo or scrcpy ?
![Capture](https://user-images.githubusercontent.com/112264339/229280484-44df321e-a71f-479f-af50-b07b3898bf88.PNG)

**Comment by rom1v** [comment]
See #3805 and PR #3886;
