### ISSUE TITLE
Notification audio not being forwarded (e.g. Phone call or message)

### ISSUE THREAD

**Issue by Azel-S** [Genymobile/scrcpy#3897]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows 11 22H2]
 - scrcpy version: [2.0]
 - Installation method: [Windows Release]
 - Device model: Pixel 6
 - Android version: 13

**Describe the bug**
Whenever a call is received, the ringtone is played through the phone's speakers and not the windows playback device.

**Questions**
Is this intended behavior?
Is the API capable of handling such events?

**Possible Solution**
If the API is incapable, I would not be opposed to having an optional notification. The notification could just show up natively on windows stating "You have received a notification" and then clicking it would take you to strcpy (possibly even open the notification window).

**Final Note**
Thank you for creating this, it is an amazing tool!

**Comment by sshekh7** [comment]
Were you able to find any solution for the phone call audio issue?

My setup includes a rooted Pixel 4a. I am running some research experiments and want to run an analysis on phone call audio, and for now, I am using the Phone Link application by Microsoft. However, the Phone Link application has problems keeping a persistent connection with the phone and disconnects randomly.

If there is any other solution to forward voice call audio, even if it requires root, that would be much appreciated. I tried looking at different Magisk modules, but still have no luck finding a robust alternative to the Phone LInk (or Intel Unison) application.

**Comment by Azel-S** [comment]
> Were you able to find any solution for the phone call audio issue?
> 
> My setup includes a rooted Pixel 4a. I am running some research experiments and want to run an analysis on phone call audio, and for now, I am using the Phone Link application by Microsoft. However, the Phone Link application has problems keeping a persistent connection with the phone and disconnects randomly.
> 
> If there is any other solution to forward voice call audio, even if it requires root, that would be much appreciated. I tried looking at different Magisk modules, but still have no luck finding a robust alternative to the Phone LInk (or Intel Unison) application.

I ended up going back to Phone Link. There were a few apps that let you forward notifications, but none were as seamless as Phone Link unfortunately.
