### ISSUE TITLE
Request: add command line parameter to let the window stay on top

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Genymobile/scrcpy#391]
I see that's it's hard to do it at runtime (written here: https://github.com/Genymobile/scrcpy/issues/60 ) , so maybe it's easier to do it using a command line parameter instead?

Please consider this.

**Comment by rom1v** [comment]
Fixed by #412.

**Comment by AndroidDeveloperLB** [comment]
@rom1v Fixed? You consider it as a bug?
:)
Is it possible to use it now?
If so, how?

**Comment by npes87184** [comment]
@AndroidDeveloperLB 

For testing, you can build the app manually. See [BUILD.md](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md).

**Comment by AndroidDeveloperLB** [comment]
@npes87184 Thank you, but I don't think I will do it anytime soon. Sorry for that
