### ISSUE TITLE
Shortcut to access notification window

### ISSUE THREAD

**Issue by refekt** [Genymobile/scrcpy#392]
This would be a quick way to open the notification window

**Comment by rom1v** [comment]
Is there any keyevent which opens it?

**Comment by refekt** [comment]
I'm not entirely sure. I am not an avid programmer, but I have seen it done on emulators like Nox Player.

**Comment by rom1v** [comment]
Thanks for the commands.

Programmatically :
https://stackoverflow.com/questions/7021310/how-to-open-or-expand-status-bar-through-intent/51616031#51616031
https://stackoverflow.com/questions/34836652/how-can-i-programmatically-expand-status-bar-on-samsung-lollipop-devices

**Comment by rom1v** [comment]
I just implemented it on `dev` branch.

**Comment by npes87184** [comment]
@rom1v 

Well, it isn't a great idea to implement this shortcut, IMO. Unlike power button, volume button, etc, notification panel can simply be expanded by pull down the top area through mouse. This shortcut will make protocol more complex and not elegant. If someone in the future request a shortcut for turning on and turning off bluetooth, wifi, etc. We still keep implementing it?

Sorry for the differing views.

Sincerely,
Yu-Chen

**Comment by rom1v** [comment]
@npes87184

Thank you for your feedback.

The idea is not to implement every shortcuts requested by any people. The notification panel is often used, and bringing it down with the mouse is "costly". I faced the problem recently (I don't use scrcpy that much), and remembered that feature request, so I implemented it.

I see this shortcut for expanding the notification panel a bit like `Ctrl`+`s` for `APP_SWITCH`: you can do it with the mouse (at least when the buttons are not physical) but it's a useful to have a direct access (for me, direct access to notification panel is even more useful than `APP_SWITCH`).

Cheers

**Comment by npes87184** [comment]
@rom1v 

Good point!

Thanks

**Comment by pundoo** [comment]
Sorry for reopening but, this isn't working when on Lock Screen. (or was that intended?)

**Comment by pundoo** [comment]
Sorry for bumping on a closed thread but, this isn't working when on Lock Screen. (or was that intended?)

**Comment by rom1v** [comment]
_scrcpy_ just calls the AOSP `StatusBarManager.expandNotificationsPanel()`. If this function does not expand the notification panel on lock screen, it is probably intended.

**Comment by Peter-maximus** [comment]
unfortunately doesn't work on oneplus 3:

error: could not invoke mehtod
