### ISSUE TITLE
Display 2 now shows black screen.

### ISSUE THREAD

**Issue by 31337-4554551n** [Genymobile/scrcpy#3925]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS:pop os 22.04 
 - scrcpy version: scrcpy 2.0
 - installation method:git pull,  ./install_release.sh 
 - device model: Galaxy fold 4
 - Android version:13

**Describe the bug**
After connecting to adb and running
/usr/local/bin/scrcpy --video-bit-rate 2m --display 2 --window-title 'DexOnLinux' --turn-screen-off --stay-awake
I get a black screen and 
[server] WARN: Display doesn't have FLAG_SUPPORTS_PROTECTED_BUFFERS flag, mirroring can be restricted
Which I didn't get before.

/usr/local/bin/scrcpy --video-bit-rate 2m --display 0 --window-title 'DexOnLinux' --turn-screen-off --stay-awake

Works fine, so it's just the actual dex output having problems
But display 0 doesn't respect the screen off option, so the phone display is always on. Whereas 

/usr/local/bin/scrcpy --video-bit-rate 2m --display 2 --window-title 'DexOnLinux' --turn-screen-off --stay-awake

Used to let me use dex and keep the phone off.

I am using a USB c dock with an HDMI display terminator-I believe that is still necessary.

**Comment by rom1v** [comment]
> But display 0 doesn't respect the screen off option, so the phone display is always on.

That's unexpected. If you just run `scrcpy --turn-screen-off`, you don't get the main screen off?

Refs #3716.

> [server] WARN: Display doesn't have FLAG_SUPPORTS_PROTECTED_BUFFERS flag, mirroring can be restricted
> Which I didn't get before.

Probably due to a change in the device system. Refs #1238.

**Comment by 31337-4554551n** [comment]
> > But display 0 doesn't respect the screen off option, so the phone display is always on.
> 
> That's unexpected. If you just run `scrcpy --turn-screen-off`, you don't get the main screen off?
> 
> Refs #3716.
> 
> > [server] WARN: Display doesn't have FLAG_SUPPORTS_PROTECTED_BUFFERS flag, mirroring can be restricted
> > Which I didn't get before.
> 
> Probably due to a change in the device system. Refs #1238.

If I just do scrcpy --turn-screen-off it does the display, and turns off the screen. But if the screen is off to begin with, I get a the lock screen, and swiping up gives me a black screen I can't interact with.

**Comment by 31337-4554551n** [comment]
Nevermind, I just have to start dex with the screen initially on.
