### ISSUE TITLE
Issue with meson on Debian Jessie

### ISSUE THREAD

**Issue by a2t2** [Genymobile/scrcpy#394]
I have meson 0.21 on Debian Jessie. When I run the following command, I get an error:

`meson x --buildtype release --strip -Db_lto=true`

Meson encountered an error in file meson.build, line 1, column 0:
Project() does not take keyword arguments.

How do you suggest I resolve this issue ? Thanks.

**Comment by rom1v** [comment]
> How do you suggest I resolve this issue ?

Upgrade your Debian :trollface: 

Or install a newer _meson_ via `pip`/`pip3`:

    sudo apt install python3-pip
    pip3 install meson
