### ISSUE TITLE
(NodeJS) Terminating Scrcpy Recording Process Does Not Stop Recording

### ISSUE THREAD

**Issue by jpnws** [Genymobile/scrcpy#3941]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10/11
 - scrcpy version: 2.0
 - installation method: scrcpy-win64-v2.0.zip
 - device model: TCL T608DL
 - Android version: 13

**Notes**

I'm building an Electron app, but the below code should still work on any NodeJS environment (even without Electron related packages), except `log`, which is from a package called `electron-log`, but we can replace it with `console.log` as well.

**Describe the bug**

Following JS code (NodeJS) spawns scrcpy process to initiate screen recording and then kills the process after about five seconds.

```TypeScript
const scrcpyPath = "path-to-scrcpy-exe-file";
const adb_serial = "adb-serial-of-device";
const videoFilePath = "where-to-save-recorded-video";

const vproc = spawn(
  scrcpyPath,
  [
    '-s',
    adb_serial,
    '--no-display',
    '--no-audio',
    `--record=${videoFilePath}`,
  ],
);

setTimeout(() => {
  vproc.kill();
}, 5000);

vproc.on('spawn', () => {
  log.info('spawning vproc.');
});

vproc.stdout.setEncoding('utf8');
vproc.stdout.on('data', (data) => {
  log.info(data);
});

vproc.stderr.setEncoding('utf8');
vproc.stderr.on('data', (data) => {
  log.info(data);
});

vproc.on('error', (err) => {
  log.error('[video] [runScreenRecorder] [error]', err);
});

vproc.on('exit', (code: number, signal: string) => {
  log.info(`[video] [runScreenRecorder] [vproc] [exit] Code: ${code} Signal: ${signal}`);
});
```

**Expected**

The screen recording stops and the fully recorded 5sec video file gets saved in `videoFilePath`.

**Actual**

The screen recording fails to stop and the video file remains at 0kb.

**Analysis**

When the above code is executed, I see a scrcpy process running (on Task Manager).

![image](https://user-images.githubusercontent.com/61026408/233813472-725aa5d1-aeaf-4617-945d-f751952c5d62.png)

When the scrcpy is killed with `vproc.kill()`, the scrcpy process entry disappears from the Task Manager, as expected.

However, an adb command that runs scrcpy-server.jar/com.genymobile.scrcpy.Server is still running.

![image](https://user-images.githubusercontent.com/61026408/233813412-1d7f7944-f566-4b39-ac4e-290d2c607a80.png)

scrcpy-server.jar/com.genymobile.scrcpy.Server is still running even after killing the scrcpy process.

The video file at `videoFilePath` is still at 0kb, and as expected, it does not play.

![image](https://user-images.githubusercontent.com/61026408/233813854-9737e7fd-b436-4f8d-929a-7c014ce9a229.png)

**Vscode Debug Console Output**
```
17:27:52.044 > spawning vproc.
17:27:52.064 > scrcpy 2.0 <https://github.com/Genymobile/scrcpy>
17:27:52.118 > C:\Users\uname\Projects\TAT\bin\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 104.1 MB/s (52867 bytes in 0.000s)
17:27:52.985 > [server] INFO: Device: TCL T608DL (Android 13)
17:27:53.548 > INFO: Recording started to mp4 file: C:\tatlogs\JNT8PV5LFM6TZXQC\2023-04-22_17-27-52-029\video_MDevice_2023-04-22_17-27-52-035.mp4
17:27:57.039 > [video] [runScreenRecorder] [vproc] [exit] Code: null Signal: SIGTERM
```

**Notes**

Manually typing in and executing the equivalent command `scrcpy.exe -s JNT8PV5LFM6TZXQC --no-display --no-audio --record=video.mp4` directly on Command Prompt and then Ctrl+C,  successfully records and saves the full video.

**Comment by rom1v** [comment]
You must not kill the app, because then it will not write file trailer. On Linux you must send SIGINT signal, on Windows you must send Ctrl+c.

**Comment by Tryanks** [comment]
Also see #3752 .

**Comment by jpnws** [comment]
Thank you all for your input. As this issue report is essentially a duplicate of #3752, I will close this.
