### ISSUE TITLE
Audio stutters when connected through WiFi

### ISSUE THREAD

**Issue by webian** [Genymobile/scrcpy#3943]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 11 Pro 22H2 OS build 22621.1555
 - scrcpy version: 2.0
 - installation method: Windows release
 - device model: Samsung Galaxy S10e SM-G970F
 - Android version: 12

**Describe the bug**
When connecting over WiFi, every 1 minute, the audio stutters for 4/5 seconds.

I tried different combinations of --video-* and --audio-* parameters but the stutter still happens.
The only parameter that helps is to set --audio-buffer very high, like 1000/2000 where the stutter is still a bit noticeable, it sounds less like a stutter and more like the audio is slowed for some seconds.

This problem does not occur if I connect via USB.

Is there something else that I could try to avoid this problem?

P.S.: Thanks for scrcpy and in particular for this new audio feature!

**Comment by rom1v** [comment]
> When connecting over WiFi, every 1 minute, the audio stutters for 4/5 seconds.

Does video also stutters at the same time?

If you record (`scrcpy --record=file.mp4`), does it also happen in the recorded file?

Could you please run `scrcpy -Vverbose` and post the logs when it stutters?

**Comment by webian** [comment]
> Does video also stutters at the same time?

Yes

> If you record (`scrcpy --record=file.mp4`), does it also happen in the recorded file?

No

> Could you please run `scrcpy -Vverbose` and post the logs when it stutters?

When I run `scrcpy -Vverbose`, when audio is normal I get messages like:
`VERBOSE: [Audio] Buffering: target=2400 avg=2445.538085 cur=2711 compensation=0`
instead, when the audio stutters I get a lot of:
`DEBUG: [Audio] Buffer underflow, inserting silence: 240 samples`
or
`DEBUG: [Audio] Buffering threshold exceeded, skipping 720 samples`

[Here is the full log](https://pastebin.com/LEWhkpX3)

Thanks!

**Comment by rom1v** [comment]
> > Does video also stutters at the same time?
> 
> Yes

Oh ok, that's just a problem on the wifi connection then (packets are lost/delayed).

**Comment by webian** [comment]
Ok, I just noticed that it happens to the video also with `--no-audio`.
And it happens also with scrcpy 1.24.

I close this since it's not a scrcpy bug.
Thanks a lot and sorry for the noise.
