### ISSUE TITLE
scrcpy 2.0 does not work with Xiaomi MI 12

### ISSUE THREAD

**Issue by XTStarry** [Genymobile/scrcpy#3946]
- [√ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ √] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: 2.0
 - installation method: Windows release
 - device model:Xiaomi MI 12
 - Android version: 13

**Describe the bug**
When I tried to connect Xiaomi 12 (Android 13) using scrcpy, it showed the following log and did not respond. As a comparison, I also used scrpy to connect my Huawei Mate 40 Pro (Android 10) and it worked fine.
The following is the log:
```
D:\scrcpy-win64-v2.0>scrcpy. exe
sercpy 2.0 <https://github. com/Genymobile/scrcpy>
D:\scrcpy-win64-v2.0>sc... file pushed, 0 skipped, 79.4MB/s (52867 bytes in 0.001s)
[server]  INFO: Device: Xiaomi 2201123C (Android 13)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
ERROR: Could not open audio device: WASAPI can't find requested audio endpoint: xxxxxx(Because of the encoding format, this part is garbled)
ERROR: Demuxer error
WARN: Killing the server...

```

**Comment by rom1v** [comment]
See https://github.com/Genymobile/scrcpy/issues/3856#issuecomment-1482911664

**Comment by XTStarry** [comment]
> See [#3856 (comment)](https://github.com/Genymobile/scrcpy/issues/3856#issuecomment-1482911664)

Thank you very much. I'll try it later.

**Comment by XTStarry** [comment]
> See [#3856 (comment)](https://github.com/Genymobile/scrcpy/issues/3856#issuecomment-1482911664)

I tried the operation in # 3856 and replaced the binary, but it didn't work:
```
D:\00522582\00TOOLS\scrcpy-win64-v2.0\scrcpy-win64-v2.0>set SDL_AUDIODRIVER=directsound

D:\00522582\00TOOLS\scrcpy-win64-v2.0\scrcpy-win64-v2.0>scrcpy --audio-output-buffer=10
scrcpy 2.0 <https://github.com/Genymobile/scrcpy>
D:\00522582\00TOOLS\scrcpy-win64-v2.0\scrcpy-win64-v2.0\sc... file pushed, 0 skipped. 46.8 MB/s (52867 bytes in 0.001s)
[server] INFO: Device: Xiaomi 2201123C (Android 13)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
ERROR: Could not open audio device: DirectSoundCreate8: No audio device found (0x88780078)
ERROR: Demuxer error
WARN: Killing the server...

D:\00522582\00TOOLS\scrcpy-win64-v2.0\scrcpy-win64-v2.0>scrcpy --audio-output-buffer=10
scrcpy 2.0 <https://github.com/Genymobile/scrcpy>
D:\00522582\00TOOLS\scrcpy-win64-v2.0\scrcpy-win64-v2.0\sc... file pushed, 0 skipped. 54.0 MB/s (52867 bytes in 0.001s)
[server] INFO: Device: Xiaomi 2201123C (Android 13)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
ERROR: Could not open audio device: DirectSoundCreate8: No audio device found (0x88780078)
ERROR: Demuxer error
WARN: Killing the server...
```
Is there a problem with my operation?

**Comment by rom1v** [comment]
OK, so it seems directsound does not work either for you.

So for audio, you should wait for the next version of SDL (it will be included in the next version of scrcpy).

Meanwhile, you should disable audio (`scrcpy --no-audio`).

**Comment by XTStarry** [comment]
> OK, so it seems directsound does not work either for you.
> 
> So for audio, you should wait for the next version of SDL (it will be included in the next version of scrcpy).
> 
> Meanwhile, you should disable audio (`scrcpy --no-audio`).
Okay, thank you for your reply.
