### ISSUE TITLE
Black Screen when using an app (PosteID) to authenticate my login.

### ISSUE THREAD

**Issue by cypherinfo** [Genymobile/scrcpy#3964]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...] Windows 11 94 bit
 - scrcpy version: [e.g. 1.12.1] 2.0
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...] Windows release 
 - device model: Nokia XR20
 - Android version: [e.g. 10] 13

**Describe the bug**
I get a black screen just when using the PosteID [](https://play.google.com/store/apps/details?id=posteitaliane.posteapp.appposteid&gl=IT)  app for my SPID authentication.

**Comment by rom1v** [comment]
That's expected for apps which enable secure flag for Android 12+. See #2129 #36
