### ISSUE TITLE
Device Disconnects every 2-5seconds later / sometime doesnt start

### ISSUE THREAD

**Issue by nahid6970** [Genymobile/scrcpy#3966]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - Windows
 - scrcpy version 2.0
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:  Xiaomi Mi9T
 - Android version: 11

**Describe the bug**
device keeps disconnecting  after 2-3 second

On errors, please provide the output of the console (and `adb logcat` if relevant).

scrcpy 2.0 <https://github.com/Genymobile/scrcpy>
adb server version (40) doesn't match this client (41); killing...
* daemon started successfully
D:\OneDrive\Desktop\scrcpy.../s (52867 bytes in 0.002s)
[server] INFO: Device: Xiaomi Mi 9T (Android 11)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2336
WARN: Device disconnected
Press any key to continue . . .
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
> adb server version (40) doesn't match this client (41); killing...

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#conflicts-between-adb-versions
