### ISSUE TITLE
Can it support another screenshot stream on android - secondary screen

### ISSUE THREAD

**Issue by chaooe** [Genymobile/scrcpy#397]
1. Normaly we can capture screen 0 by 'adb shell screencap -p -d 0 /sdcard/sc.png', so if we have two or more display, we can use 'adb shell screencap -p -d ${displayid} /sdcard/sc.png', so can we have this supported?

**Comment by chaooe** [comment]
Yes, i want to mirror a secondary screen. I am a QA to test Android Device, and we have some future running on another screen.. we can just use screenshot to capture another screen. It is slowly and unstable.

**Comment by webian** [comment]
I'm another one that will find this feature precious to command Samsung Dex from my linux box without the need to switch mouse/keyboard/monitor.

I'm not an android dev but I found some little things that I hope can help:
1. if I run this apk https://github.com/mportuesisf/ScreenInfo starting from the smartphone display it returns me the smartphone display resolution, if I run it from the Dex monitor it gives me the resolution of the monitor. So, maybe in the code of ScreenInfo there are some hints on how to achieve this.
2. AnyDesk can reproduce Dex screen but only if started from the Dex monitor, if started from the smartphone monitor it reproduce the smartphone's one. Also, mouse click are always made on the smartphone even if started from the Dex monitor.

**Comment by webian** [comment]
Is there maybe a way to make Android to think that the scrcpy server is started on the external (Dex) monitor?

**Comment by webian** [comment]
Other info that maybe can help (see "Detect Samsung DeX"):
https://developer.samsung.com/samsung-dex/modify-optimizing

**Comment by tchangeme** [comment]
请问，这个怎么实现呢，手机上有另外一个屏幕的时候

**Comment by nakele** [comment]
@rom1v  btw, if the server was wrapped in an apk, and the apk was launched in Samsung Dex mode, it might mirror the second display.

**Comment by chaooe** [comment]
@rom1v  I found minitouch have soultion to touch on second screen. before it use, we need to setup minitouch server on device.
`minitouch -d /dev/input/event0` /dev/input/event0 is the first screen id. and `minitouch -d /dev/input/event1` is the second display id
Does this scrcpy use minitouch to touch the screen?

**Comment by rom1v** [comment]
No, it does not use minitouch. I guess it requires root access on the device to write to `/dev/input/event*`?

**Comment by chaooe** [comment]
No, the /dev/input/event is the display id. I don't know where to configure the /dev/input/event*
1. When i copy minitouch and add execution permission to android folder. /tmp/data/minitouch.
2. /tmp/data/minitouch , it will show the display id. 
3. /tmp/data/minitouch -d /dev/input/event0 to start the minitouch server

**Comment by rom1v** [comment]
Could you test #1177 please?

**Comment by chaooe** [comment]
Ok. I will have a try for this. and reply to ASAP.

**Comment by chaooe** [comment]
For https://github.com/Genymobile/scrcpy/pull/1177 , it should be ok to mirror the display 1 screen on ubuntu 18.04. But i can't do some touch or text commands.
Add `adb shell dumpsys display` for reference.
![image](https://user-images.githubusercontent.com/12910117/75257112-6f22bf00-581f-11ea-95e8-b3bf4a6d2b1a.png)

**Comment by peanutwolf** [comment]
@rom1v @chaooe Thank you for testing. I think i've missed the touch functionality for the second screen cause my second screen is not touchable. I'll investigate how it could be supported and will make commit to my PR.

**Comment by chaooe** [comment]
Thanks @peanutwolf , And i have 3 display for this. The default id 0 and display id 1 can be touched. but display id 2 is only for view. just some information, i am not sure if this is helpful for you. And thanks again

**Comment by webian** [comment]
Thanks @peanutwolf !
I tested #1177 too and it's working except for clicks.
I can see the Dex screen (secondary monitor) but the clicks that I make on scrcpy window are sent to the smartphone instead of Dex, so I guess that a small step is missing.

**Comment by peanutwolf** [comment]
@chaooe  @webian  what android API does your devices have? (`$ adb shell getprop ro.build.version.sdk | tr -d '\r'`)
It seems that input events for multiple displays can't be supported for android 9 and lower. 
Or maybe you have custom InputFlinger patched for your devices?

**Comment by webian** [comment]
Mine is a Samsung Galaxy S10e with Android 10:
`$ adb shell getprop ro.build.version.sdk | tr -d '\r'`
29

No custom InputFlinger as far as I know.

**Comment by webian** [comment]
Please, also note n.2 of my https://github.com/Genymobile/scrcpy/issues/397#issuecomment-482964379 I had the same problem about clicking with AnyDesk.

**Comment by chaooe** [comment]
@peanutwolf My version is 27
`$ adb shell getprop ro.build.version.sdk | tr -d '\r'
27
`

**Comment by chaooe** [comment]
Another things for display id 1 which can be input. for my automation test. we found we can use minitouch for touch the second screen. 
setup minitouch server on device.
`minitouch -d /dev/input/event0 `
/dev/input/event0 is the first screen id. and `minitouch -d /dev/input/event1 `is the second display id

**Comment by chaooe** [comment]
Add more information from my devices
`$ adb shell
msm8996_gvmq:/ # cat /sys
sys/     system/
msm8996_gvmq:/ # cat /sys/class/input/                                                                                                                                                                                                       
event0/  event1/  input0/  input1/  mice/`
And i found this define on this page 
http://newandroidbook.com/Book/Input.html?r

**Comment by peanutwolf** [comment]
Hi @webian. I've made a small extension for my pull request. I've added support for input events for secondary display. But it could work only for android 10 and higher. Can you check me theory and test https://github.com/Genymobile/scrcpy/pull/1177 againg
Hi @chaooe. I've examined mini-touch util. Unfortunately that solution is not suitable for every android device. Some of them require root privileges: https://www.pocketmagic.net/programmatically-injecting-events-on-android-part-2/

**Comment by webian** [comment]
Hi @peanutwolf I tested #1177 and mouse interactions work perfectly now, good job! Thank you!

Just side note FYI...
I had to use option "-d 2" to display second monitor (Dex) not "-d 1" that instead returns this error:
```
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at com.genymobile.scrcpy.wrappers.DisplayManager.getDisplayInfo(DisplayManager.java:26)
        at com.genymobile.scrcpy.Device.computeScreenInfo(Device.java:52)
        at com.genymobile.scrcpy.Device.<init>(Device.java:31)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:19)
        at com.genymobile.scrcpy.Server.main(Server.java:166)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:339)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at com.genymobile.scrcpy.wrappers.DisplayManager.getDisplayInfo(DisplayManager.java:18)
        ... 6 more
```

**Comment by webian** [comment]
It could also be useful to trigger Samsung Dex or similar desktop modes without have to physically attach the monitor. Do you know if it is possible?

**Comment by chaooe** [comment]
@peanutwolf Our device have root permission , Can you help to add the minitouch solution for me to have a try? I don't know how to  add in this. Thanks very much.
Next monday i will ask developer from our SW team how they deal with the event even though we are using Android 8.

**Comment by rom1v** [comment]
Could you test the new `--display` option on `dev` (the development branch), please?

**Comment by rom1v** [comment]
Here is a win64 release for the current `dev` branch:
 - [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/dev/6295c1a1/scrcpy-server)
 - [`scrcpy.exe`](https://tmp.rom1v.com/scrcpy/dev/6295c1a1/scrcpy.exe)

<details>
<summary>SHA256</summary>

```
09489ac673ed3b0bb7aba7e0858c43137a7480d1a2d4f8a51f698acbc49be735  scrcpy-server
c9be0cd73651a376932ca0e4ca1c07275aa776a5e5520b5b184fcff943affdd5  scrcpy.exe
```
</details>

(replace these two files in the v1.12.1 release)

**Comment by chaooe** [comment]
@rom1v Ok. I will have a try and response ASAP

**Comment by chaooe** [comment]
@rom1v It works nice on windows 10. And have an message when using display 1 with android API 27
![image](https://user-images.githubusercontent.com/12910117/78788740-c69b7980-79de-11ea-9291-7b761c29ea6f.png)

**Comment by rom1v** [comment]
OK so you can mirror but not control if all conditions are not met. That's expected :+1:

What happens if you click?

**Comment by chaooe** [comment]
Nothing happened on both display 0 and display 1

**Comment by chaooe** [comment]
Is that possible to add minitouch solution to support this?

**Comment by webian** [comment]
Hi @rom1v, I tested dev replacing the 2 files and launching with "--display 2" and it works both display and input.
Windows 10 LTSC 1809 + Samsung Galaxy S10e SM-G970F Android 10

**Comment by rom1v** [comment]
@webian Cool :tada: Thank you for your test.

(How do you get multiple displays in practice with your phone?)

**Comment by webian** [comment]
> @webian Cool 🎉 Thank you for your test.

You don't need to thank me... I thank you a lot for the amazing scrcpy!

> (How do you get multiple displays in practice with your phone?)

see https://github.com/Genymobile/scrcpy/issues/898#issuecomment-610996513
I add that in practice I use an [USB to HDMI adapter](https://www.amazon.it/gp/product/B07L3DZ125) and connect it to a monitor with an HDMI cable. This way I can mirror the phone screen. To start Dex on the external screen I also have to power the adapter with an external USB charger.

**Comment by rom1v** [comment]
I guess this issue can be closed with the new `--display` option implemented on dev branch.

**Comment by rom1v** [comment]
Released in v1.13.

**Comment by tchangeme** [comment]
The second screen can be displayed normally, but the mouse and keyboard cannot be used。

**Comment by tchangeme** [comment]
In addition, the screen cannot be fully displayed

**Comment by rom1v** [comment]
> but the mouse and keyboard cannot be used

That's expected before Android 10.
https://github.com/Genymobile/scrcpy/releases/tag/v1.13

> In addition, the screen cannot be fully displayed

What do you mean?

**Comment by jvisser99** [comment]
Greetings,

Thanks for the great program, I use it daily.  

I  can't get DeX to work.  I tried the --display option, and for anything other than 0 i get an error of this form:
$ scrcpy --display 1
INFO: scrcpy 1.13 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1...pushed. 3.1 MB/s (27694 bytes in 0.009s)
[server] INFO: Device: samsung SM-G960U1 (Android 10)
[server] ERROR: Exception on thread Thread[main,5,main]
com.genymobile.scrcpy.InvalidDisplayIdException: There is no display having id 1
	at com.genymobile.scrcpy.Device.<init>(Device.java:46)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:20)
	at com.genymobile.scrcpy.Server.main(Server.java:177)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:339)
[server] ERROR: Try to use one of the available display ids:
[server] ERROR:     scrcpy --display 0

I'm running Red Hat Enterprise Linux Workstation 7.6, Samsung Galaxy 9, Android 10.  Connected via a Lenovo Thunderbolt doc to a Lenovo X1 Carbon Gen. 6, 2 displayport-connected monitors.  

Any help appreciated.  Happy to test.

jv

**Comment by rom1v** [comment]
Is DeX running when you execute this command?

**Comment by jvisser99** [comment]
Thanks for the quick reply.  
I don't know. I get a notification that says "you can use Sasung DeX on your computer.  I searched for DeX, and found four apps, DeX for PC, Samsung DeX, Samsung DeX home, and Samsung DeX System UI, all installed, but no indication that they are running.

**Comment by rom1v** [comment]
AFAIK, DeX can only be enabled when you plug your device to some HDMI monitor.

**Comment by jvisser99** [comment]
> AFAIK, DeX can only be enabled when you plug your device to some HDMI monitor.
If you do this, how do you run scrcpy?  And, scrcpy 1.13 supports DeX screen mirroring.

**Comment by nakele** [comment]
@jvisser99 if u want to run Dex on PC you need to install Dex appliaction on your pc as well, plug the cable to phone, wait to say it's connected and you should get a window dex on your pc monitor. No needed for for anythingelse. HoWEVER scrcpy could be used to mirror dex on devices that don't support Dex on PC like the S8/Note8 line + S9/Note9 on Android 9.

First you need to trigger Dex via HDMI cable or HDMI dummy plug (my case), then use scrcpy via WiFi (because your port will be used for the HDMI)
In your case you don't need scrcpy, the samsung app "Dex on Window", also available on Mac.

**Comment by rom1v** [comment]
> scrcpy 1.13 supports DeX screen mirroring.

It supports mirroring a secondary display.

On devices supporting DeX, a secondary display is created when DeX is enabled. And DeX is enabled when you plug the device via HDMI.

**Comment by jvisser99** [comment]
> @jvisser99 if u want to run Dex on PC you need to install Dex appliaction on your pc as well, plug the cable to phone, wait to say it's connected and you should get a window dex on your pc monitor. No needed for for anythingelse. HoWEVER scrcpy could be used to mirror dex on devices that don't support Dex on PC like the S8/Note8 line + S9/Note9 on Android 9.
> 
> First you need to trigger Dex via HDMI cable or HDMI dummy plug (my case), then use scrcpy via WiFi (because your port will be used for the HDMI)
> In your case you don't need scrcpy, the samsung app "Dex on Window", also available on Mac.

I'm running linux on my laptop

**Comment by rom1v** [comment]
> In your case you don't need scrcpy, the samsung app "Dex on Window", also available on Mac.

IIUC, this app allows to enable DeX without plugging the device via HDMI?

If this is the case, then it shows that it is possible to enable DeX programmatically. If someone knows how, it could be implemented in scrcpy :wink:

**Comment by jvisser99** [comment]
> > In your case you don't need scrcpy, the samsung app "Dex on Window", also available on Mac.
> 
> IIUC, this app allows to enable DeX without plugging the device via HDMI?
> 
> If this is the case, then it shows that it is possible to enable DeX programmatically. If someone knows how, it could be implemented in scrcpy


I thought it was implemented in 1.13

**Comment by rom1v** [comment]
No, in scrcpy 1.13, a new option has been added to mirror a display other than the one having id 0.

It occurs that DeX creates such a secondary display when enabled, so scrcpy can mirror it.

**Comment by nakele** [comment]
> > @jvisser99 if u want to run Dex on PC you need to install Dex appliaction on your pc as well, plug the cable to phone, wait to say it's connected and you should get a window dex on your pc monitor. No needed for for anythingelse. HoWEVER scrcpy could be used to mirror dex on devices that don't support Dex on PC like the S8/Note8 line + S9/Note9 on Android 9.
> > First you need to trigger Dex via HDMI cable or HDMI dummy plug (my case), then use scrcpy via WiFi (because your port will be used for the HDMI)
> > In your case you don't need scrcpy, the samsung app "Dex on Window", also available on Mac.
> 
> I'm running linux on my laptop

Ah, I suspected that. I believe wine won't work with Samsung Dex on PC.

**Comment by nakele** [comment]
> > In your case you don't need scrcpy, the samsung app "Dex on Window", also available on Mac.
> 
> IIUC, this app allows to enable DeX without plugging the device via HDMI?
> 
> If this is the case, then it shows that it is possible to enable DeX programmatically. If someone knows how, it could be implemented in scrcpy 😉

It's possible, definitely. 
2 things comes to mind, if not 3: Dex on PC will trigger dex programmatically, Dex on a Tab has a toggle to show DeX on the tablet itself, so no hdmi required.  Lastly someone has seen Dex Wireless options (might be a thing in the future)

**Comment by webian** [comment]
There's also [this thread in Samsung forum](https://eu.community.samsung.com/t5/Galaxy-Note9/Why-is-DEX-not-being-made-wireless/m-p/694161#M574) where a moderator says, in October 2018, that they are "working on a wireless connection for DEX but a few improvements need to be made first". If you want you can add your post to the thread so they know how much this feature is requested.

**Comment by rom1v** [comment]
I don't have any DeX device. Could you check if enabling dex with "Dex on Windows" changes settings:

```bash
# with dex disabled
adb shell "settings list global | sort" > global.txt
adb shell "settings list secure | sort" > secure.txt
adb shell "settings list system | sort" > system.txt
# with dex enabled
adb shell "settings list global | sort" > global_dex.txt
adb shell "settings list secure | sort" > secure_dex.txt
adb shell "settings list system | sort" > system_dex.txt
# compare
diff -U3 global.txt global_dex.txt
diff -U3 secure.txt secure_dex.txt
diff -U3 system.txt system_dex.txt
```

**Comment by webian** [comment]
These are the diffs before/after connecting my Galaxy S10e with USB cable and starting Dex on PC:
- global: no diff
- [secure](https://pastebin.com/WgtAsph6)
- [system](https://pastebin.com/udkUq71d)
