### ISSUE TITLE
ERROR: Could not invoke method 

### ISSUE THREAD

**Issue by nicovdd** [Genymobile/scrcpy#3972]
- [Y] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [Y] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [11]
 - scrcpy version: [scrcpy 2.0]
 - Windows Release 64 Bit.
 - device model:  Xiaomi M2101K6G (Android 13)
 - Android version: [e.g. 13]

**Describe the bug**
the terminal connects and the mobile screen appears,  When clicking on the Android screen, errors as below appear.

```
E:\PortableApps\scrcpy-win64-v2.0>scrcpy -d
scrcpy 2.0 <https://github.com/Genymobile/scrcpy>
E:\PortableApps\scrcpy-win64-v2.0\scrcpy-server: 1 file pushed, 0 skipped. 76.1 MB/s (52867 bytes in 0.001s)
[server] INFO: Device: Xiaomi M2101K6G (Android 13)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:37)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:192)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:196)
        at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:320)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:134)
        at com.genymobile.scrcpy.Controller.control(Controller.java:83)
        at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:90)
        at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
        at android.os.Parcel.createException(Parcel.java:2995)
        at android.os.Parcel.readException(Parcel.java:2978)
        at android.os.Parcel.readException(Parcel.java:2920)
        at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1294)
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1153)
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1182)
        ... 10 more
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
Did you enable `USB debugging (Security Settings)` and reboot your device? https://github.com/Genymobile/scrcpy#prerequisites

**Comment by nicovdd** [comment]
That was the issue - had all USB debugging activated but missed this one.  Thanks for the fast feedback!

On Xiaomi MIUI 14 you need to set:

To enter developer mode  - got to about phone and tap MIUI version 7 times
The search for developer options, and activate, on the same screen activate USB Debugging and USB Debugging (Security Settings)

**Comment by Yaoojq** [comment]
> * [Y] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
> * [Y] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).
> 
> **Environment**
> 
> * OS: [11]
> * scrcpy version: [scrcpy 2.0]
> * Windows Release 64 Bit.
> * device model:  Xiaomi M2101K6G (Android 13)
> * Android version: [e.g. 13]
> 
> **Describe the bug** the terminal connects and the mobile screen appears, When clicking on the Android screen, errors as below appear.
> 
> ```
> E:\PortableApps\scrcpy-win64-v2.0>scrcpy -d
> scrcpy 2.0 <https://github.com/Genymobile/scrcpy>
> E:\PortableApps\scrcpy-win64-v2.0\scrcpy-server: 1 file pushed, 0 skipped. 76.1 MB/s (52867 bytes in 0.001s)
> [server] INFO: Device: Xiaomi M2101K6G (Android 13)
> INFO: Renderer: direct3d
> INFO: Initial texture: 1080x2400
> [server] ERROR: Could not invoke method
> java.lang.reflect.InvocationTargetException
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:37)
>         at com.genymobile.scrcpy.Device.injectEvent(Device.java:192)
>         at com.genymobile.scrcpy.Device.injectEvent(Device.java:196)
>         at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:320)
>         at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:134)
>         at com.genymobile.scrcpy.Controller.control(Controller.java:83)
>         at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:90)
>         at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda0.run(Unknown Source:2)
>         at java.lang.Thread.run(Thread.java:1012)
> Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
>         at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
>         at android.os.Parcel.createException(Parcel.java:2995)
>         at android.os.Parcel.readException(Parcel.java:2978)
>         at android.os.Parcel.readException(Parcel.java:2920)
>         at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1294)
>         at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1153)
>         at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1182)
>         ... 10 more
> ```
> 
> Please do not post screenshots of your terminal, just post the content as text instead.

I also have such an appearance

**Comment by manolomarti** [comment]
Solution "developer options" Xiaomi Redmi Note 11 Android 13. In addition to "USB debugging" you must activate "USB debugging (security settings)" allows the granting of permissions and input simulation through USB debugging; IM account must be added.
![IMAGEN](https://github.com/Genymobile/scrcpy/assets/138311627/62e6b88f-a364-4600-9978-c7fac8bed5eb)

**Comment by Eben-com** [comment]
it is displaying the same error... cannot invoke method and it mirrors my phone but can't navigate my phone with my mouse or keyboard

**Comment by rom1v** [comment]
Use the latest version.

**Comment by jidaominglong** [comment]
> 我已经下载了最新版本。我不得不重新启动手机。谢谢

I'm having the same issue today, you need activate USB Debugging and USB Debugging (Security Settings)，Restart your phone and reopen scrcpy.exe
