### ISSUE TITLE
Why re-set a new encoder after encode one frame?

### ISSUE THREAD

**Issue by wnpllrzodiac** [Genymobile/scrcpy#3976]
(https://github.com/Genymobile/scrcpy/blob/cb20bcb16f4ca191e237c8744a7c2e6d29701d60/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java#L97)

**Comment by rom1v** [comment]
It's not after encoding one frame, check the content of the `encode()` method. It returns only on rotation change or EOF.
