### ISSUE TITLE
Phone is getting really hot

### ISSUE THREAD

**Issue by CrepesPisang** [Genymobile/scrcpy#3980]
- [o] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [o] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [Windows release...]
 - device model: Xiaomi 11t and Asus zenfone max pro m1
 - Android version: [13]

**Describe the bug**
I don't know if this is a bug or not, but my phone is getting hot every time I watch a video on the device using scrcpy in the fullscreen mode. usually, my phone gets hot after 30 minutes of being plugged into the computer (scrcpy). I don't have adb logcat, because I was afraid that my phone will blow up, it was super hot on both of my devices. thanks

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
Encoding the screen capture needs work, done by an hardware encoder on the device (and also a bit of CPU). The properties of these components (how they become hot) is out of control of scrcpy.

Maybe try to turn the physical screen off (`--turn-screen-off`), the screen typically heats up if turned on forna long time.
