### ISSUE TITLE
No video (black screen) with Now TV Android app v0.36.0

### ISSUE THREAD

**Issue by valeriupredoi** [Genymobile/scrcpy#3982]
Hey guys, first off let me thank you very, very much for a great software package I have been using for more than three years! My way of using `scrcpy` was (unfortunately in the past tense now) to connect my Android phone to my Linux laptop, and have the Formula 1 race, that I'd watch using the Now TV app, on a nice big external screen. Now TV (the only official way to stream Formula 1 in the UK) have a ridiculous approach not to support streaming over the browser, and they make you use their silly player (which is very brittle, and has zero support for Linux); the only alternative is to use the mobile Android app (which used to work very well with `scrcpy` before `nowtv=36.0`) and get the video on a big external monitor. Unfortunately this has stopped working with `scrcpy`, and it's clearly a setting in their new version of the app, nothing to do with your software, but am wondering if you could give me a few pointers, if it can be fixed, please. See below for problem description:

**Problem summary**

(live) video stream from Android app Now TV appears black (is not shown) on the laptop hooked to the phone with `scrcpy`. Everything else in-app (Now TV app) and off phone appears fine on the laptop, the only thing that is not transferred over is the actual video. See screenshots (first showing all is fine when connecting phone to laptop, second showing the actual stream window, missing the video)

![gen1](https://user-images.githubusercontent.com/28983971/236815761-7c76e53e-3c39-4b6f-9e8c-95d6db6d8863.png)
![gen2](https://user-images.githubusercontent.com/28983971/236815787-c71a0975-2138-4f0b-a2c2-589347f3ea1b.png)

**Versions tried and debug info**

Problem first appeared when Now TV released their latest version of the app 36.0, before that `scrcpy=1.25` and `nowtv=35.0` and earlier worked very well. I also tested with `scrcpy=2.0` and it's the same problem, also tested with two different Android devices (phones), see below for debug output:

```
on Moto G4 (that has worked like a charm until nowtv=0.36.0)

valeriu@valeriu-PORTEGE-Z30-C:~$ scrcpy --verbosity=debug
scrcpy 2.0 <https://github.com/Genymobile/scrcpy>
DEBUG: ADB device found:
DEBUG:     -->   (usb)  ZY223RDG7D                      device  Moto_G__4_
DEBUG: Device serial: ZY223RDG7D
DEBUG: Using server: /usr/local/share/scrcpy/scrcpy-server
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 8.5 MB/s (52867 bytes in 0.006s)
[server] INFO: Device: motorola Moto G (4) (Android 7.0)
DEBUG: Server connected
DEBUG: Starting controller thread
DEBUG: Starting receiver thread
[server] WARN: Audio disabled: it is not supported before Android 11
[server] DEBUG: Audio encoder stopped
[server] DEBUG: Using encoder: 'OMX.qcom.video.encoder.avc'
INFO: Renderer: opengl
INFO: OpenGL version: 3.0 Mesa 20.0.8
INFO: Trilinear filtering enabled
DEBUG: Using icon: /usr/local/share/icons/hicolor/256x256/apps/scrcpy.png
DEBUG: Demuxer 'video': starting thread
DEBUG: Demuxer 'audio': starting thread
WARN: Demuxer 'audio': stream explicitly disabled by the device
INFO: Initial texture: 1080x1920
INFO: New texture: 1920x1080
INFO: New texture: 1080x1920
DEBUG: User requested to quit
DEBUG: quit...
DEBUG: Demuxer 'video': end of frames
DEBUG: Receiver stopped
[server] DEBUG: Controller stopped
WARN: Killing the server...
DEBUG: Server disconnected
DEBUG: Server terminated
```
and

```
on another Motorola phone Moto G7

valeriu@valeriu-PORTEGE-Z30-C:~$ scrcpy --verbosity=debug
scrcpy 2.0 <https://github.com/Genymobile/scrcpy>
DEBUG: ADB device found:
DEBUG:     -->   (usb)  ZY326JNMPQ                      device  moto_g_7__power
DEBUG: Device serial: ZY326JNMPQ
DEBUG: Using server: /usr/local/share/scrcpy/scrcpy-server
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 6.7 MB/s (52867 bytes in 0.008s)
[server] INFO: Device: motorola moto g(7) power (Android 10)
[server] WARN: Audio disabled: it is not supported before Android 11
[server] DEBUG: Audio encoder stopped
DEBUG: Server connected
DEBUG: Starting controller thread
DEBUG: Starting receiver thread
[server] DEBUG: Using encoder: 'OMX.qcom.video.encoder.avc'
INFO: Renderer: opengl
INFO: OpenGL version: 3.0 Mesa 20.0.8
INFO: Trilinear filtering enabled
DEBUG: Using icon: /usr/local/share/icons/hicolor/256x256/apps/scrcpy.png
DEBUG: Demuxer 'video': starting thread
DEBUG: Demuxer 'audio': starting thread
WARN: Demuxer 'audio': stream explicitly disabled by the device
INFO: Initial texture: 720x1520
INFO: New texture: 1520x720
DEBUG: Demuxer 'video': end of frames
DEBUG: Receiver stopped
DEBUG: Server disconnected
DEBUG: Server terminated
WARN: Device disconnected
DEBUG: quit...
```

I frankly can't see anything from the debug logs, all seems to be interpreted correctly by `scrcpy`. Very many thanks in advance, and I hope you can help me a bit here; also, please let me know if you need more debugging from me (it'll have to be with `scrcpy=2.0` since I've nuked the old 1.25 installation now). Cheers :beer:

**Comment by rom1v** [comment]
They probably use some DRM and the video takes "a different path". There is probably no way to capture it with scrcpy.

**Comment by valeriupredoi** [comment]
@rom1v you are absolutely right - DRM they use indeed, see the Mickey Mouse reply in this thread https://community.nowtv.com/t5/Off-Topic-Chat/NowTV-on-Linux/m-p/365933#M9233 - cheers, guess there's nothing else to do than to wait see if their next app release fixes it? 🍺 Am gonna close this, not to clutter your space. Very many thanks again, for your great work on scrcpy 👍
