### ISSUE TITLE
How did your program achieve such fast response time?

### ISSUE THREAD

**Issue by Titlehhhh** [Genymobile/scrcpy#3988]
Hello,

I noticed that when using your Scrcpy program, the interaction with the Android device through ADB is very fast, without any noticeable delays. I'm using the AdvancedSharpAdbClient library in my C# project to interact with an Android device through ADB, but I've noticed a significant delay and not as much responsiveness as in Scrcpy.

I would like to know how your program achieved such a fast response time and responsiveness when working with an Android device through ADB. I would be grateful if you could share your knowledge and experience in this area and offer any recommendations or advice for optimizing the ADB interaction in my project using the AdvancedSharpAdbClient library.

**Comment by Titlehhhh** [comment]
I don't have to broadcast the video. Clicks and swipes are enough.

**Comment by rom1v** [comment]
See https://github.com/Genymobile/scrcpy/issues/231#issuecomment-414111753

**Comment by rom1v** [comment]
Input injection is not part of the adb protocol. If you execute `adb shell input …`, then you're just executing the command `input` from adb shell, with the performance issues mentioned in my comment.

So you have to implement some server code running on the device with shell permissions, that you run once and communicate the commands over a socket.

**Comment by Titlehhhh** [comment]
I think I got it. You only use ADB to download the server.jar to your phone, and then you interact with it. Am I right?
