### ISSUE TITLE
how to cook v4l2 with a sound

### ISSUE THREAD

**Issue by slr** [Genymobile/scrcpy#3989]
https://github.com/Genymobile/scrcpy/blob/master/doc/v4l2.md works like a charm but I have no clue how to get a sound in this case

**Comment by rom1v** [comment]
Related: https://github.com/Genymobile/scrcpy/pull/3978#issuecomment-1546044049

**Comment by slr** [comment]
I've checked again and it seems it got handled nowadays.

    scrcpy --v4l2-sink=/dev/video2 --no-window

it simply works, so cool.

keep on bringing the awesome! many thanks
