### ISSUE TITLE
OTG mode mouse input doesn't work on some apps

### ISSUE THREAD

**Issue by john-basilio** [Genymobile/scrcpy#3990]
- [ /] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ]/ I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows]
 - scrcpy version: [e.g. 2.0]
 - installation method: [Windows release]
 - device model: infinix hot 20
 - Android version: [12]

**Describe the bug**

So I was fascinated with the new update, specifically the OTG mode because it works perfectly with minecraft, so of course i tried it also on another apps and they seem to be working fine but the problem is:

When I tried it on a game called "Mobile Legends: Bang Bang" (aka MLBB) no mouse inputs are accepted. Scroll, clicks, hovering, none worked, be reminded that before and after encountering this issue I tried to use it on other apps and they were working good so I'm wondering if is this an app-specific bug or what.

Edit 1:
- On the mirroring mode, it does accept input, idk maybe it's interpreted as a touch input or something

Please paste terminal output in a code block.

 `scrcpy.exe --otg -M -K`

**Comment by rom1v** [comment]
The app probably just does not react to mouse events, only to touch screen events.

**Comment by prog-pogger** [comment]
> 

Say that's the case, is it possible to be fixed in future updates?

**Comment by rom1v** [comment]
Nope, it's out of control of scrcpy. It may be fixed by future updates of that game though.
