### ISSUE TITLE
Nintendo hinders the development of scrcpy

### ISSUE THREAD

**Issue by rom1v** [Genymobile/scrcpy#3996]
![totk](https://github.com/Genymobile/scrcpy/assets/543275/902e3588-0583-40e0-ac9c-6bb120bc84be)

Where is my remaining free time to work on scrcpy now?

_Don't worry, I'll figure it out (once the princess is safe)._

![link_small](https://github.com/Genymobile/scrcpy/assets/543275/e6ff1022-2dd0-4701-a38a-f853ae4c5fe1)

**Comment by kevsestrella** [comment]
Tears of the android users

**Comment by lukaskretzschmer** [comment]
Enjoy it man, you deserve the time!

**Comment by 8MiYile** [comment]
Haha, do not forget to combine work and rest Oh, remember to update the program code

**Comment by DazeCake** [comment]
By the way, why the durian be deleted😭
I find it in rainforest for 2 hours yesterday!😭😭😭

**Comment by GeekDuanLian** [comment]
玩塞尔达玩的

**Comment by rom1v** [comment]
The issue can be closed, the princess is saved. _#nodragon_

![totk_complete](https://github.com/Genymobile/scrcpy/assets/543275/17784248-46ff-4c20-a864-b5bc861b3861)

Completed:
 - all 152 shrines
 - all 120 lightroots
 - all 20 Sage's will

Sorry Koroks, I won't find you all.
