### ISSUE TITLE
I can't control the device on my pc even tho i have usb debugging enabled

### ISSUE THREAD

**Issue by ImSzymcioYoutube** [Genymobile/scrcpy#3997]
There also isn't any error and i have tried many things but none of them worked, my phone is a redmi 9, can someone help me?

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy#prerequisites
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work

**Comment by ImSzymcioYoutube** [comment]
Thanks, i have android 11 as i checked and i dont really have a popup and my screen is unlocked, so idk what to do?
