### ISSUE TITLE
Feature request: Mimic Power button

### ISSUE THREAD

**Issue by patelnishantk** [Genymobile/scrcpy#4]
First of all, kudos for the utility. Appreciate your efforts. 

It would be great if you could provide a feature where once can mimic click of the power button. This would come quite handy if someone wants keep the device always connected and control it from the laptop altogether. At the moment, it is a manual task to first unlock via physical button.

**Comment by patelnishantk** [comment]
Found the shortcut. It is Ctrl + p. Thanks again!

**Comment by rom1v** [comment]
And right-click to switch the screen on :)

**Comment by KeronCyst** [comment]
It would be really cool if holding Ctrl+P mimicked holding the power button.

**Comment by rom1v** [comment]
Yes, could you create a separate issue, please?
