### ISSUE TITLE
Connecting Multiple Devices

### ISSUE THREAD

**Issue by Mailman74** [Genymobile/scrcpy#400]
I just starting using this app and tried connecting multiple phones to pc via USB. I get this error when trying to run.
adb: error: failed to get feature set: more than one device/emulator
ERROR: "adb push" returned with value 1

Sorry if its a noob question but I am not the best at running command lines and stuff

**Comment by rom1v** [comment]
adb devices

gives you a list of connected devices, with their serial number.

Use:

    scrcpy -s your_device_serial_number

to start scrcpy for a specific device.

**Comment by npes87184** [comment]
Maybe we can provide an interactive interface or a hint for multiple device case.

For example:
```
There are more than one device connected.
    1. b23b92cc
    2. XXXXXX
    ...
Please select a specific device for continuing start scrcpy [1]:
```
Or:
```
There are more than one device connected.
    1. b23b92cc
    2. XXXXXX
    ...
Please start scrcpy with -s and specify the device serial number.
```

How do you feel?

**Comment by Mailman74** [comment]
I actually got it now, thanks so much. Another question is when I mimimize I can not locate the phone anymore, only the cmd window.,

**Comment by rom1v** [comment]
> How do you feel?

I don't know. It may help, but it's inherently racy (and we have to parse adb output to get more details).

**Comment by rom1v** [comment]
> Another question is when I mimimize I can not locate the phone anymore

It should still be on your desktop, at the other end of your USB cable :troll:

More seriously, could you send a screenshot?

**Comment by npes87184** [comment]
> I don't know. It may help, but it's inherently racy (and we have to parse adb output to get more details).

Or just give a sexy response, for example:
```
There are more than one device connected.
Please get the correct device serial number by adb devices and start the scrcpy with --serial.
```

**Comment by rom1v** [comment]
> There are more than one device connected.

OK, but it still requires to parse the output of adb (to detect the cause).

**Comment by npes87184** [comment]
> > There are more than one device connected.
> 
> OK, but it still requires to parse the output of adb (to detect the cause).
> And this error is "expected" over wifi.

So sad.

**Comment by tieorange** [comment]
`sudo` did the job for me:
1. scrcpy -s 234324fsdfasdf4r 
2. sudo scrcpy -s 6058ediba07c4f8c4 -p 114

**Comment by rom1v** [comment]
@tieorange `sudo` is not necessary for ports >= 1024.

https://www.w3.org/Daemon/User/Installation/PrivilegedPorts.html

**Comment by AlexanderCxPx** [comment]
@tieorange Where I write that? pls

**Comment by Oneniknem** [comment]
any video tutorials?
