### ISSUE TITLE
CMD cannot be entered

### ISSUE THREAD

**Issue by Benjamin-Watson0** [Genymobile/scrcpy#4009]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

I'm not a programmer, I'm just a technology enthusiast, forgive me if I make a low-level mistake, thank you very much.

**Environment**
 - OS: Windows
 - scrcpy version: 2.0
 - installation method: Windows release
 - device model: vivo
 - Android version: 10

**Describe the bug**
CMD cannot be entered.
![image](https://github.com/Genymobile/scrcpy/assets/112467275/daa3dce9-24dc-414b-b421-98b887edb3a2)

**Comment by rom1v** [comment]
Please read https://github.com/Genymobile/scrcpy/blob/master/doc/windows.md#run

Double click on `open_a_terminal_here.bat` if you want to execute commands.

**Comment by rom1v** [comment]
Clicked on what? `open_a_terminal_here.bat`? Youbmust not double-click on `scrcpy.exe`.

**Comment by rom1v** [comment]
In that "black box", type `scrcpy` then enter. You could also pass other parameters (scrcpy --record=file.mp4` to record the capture for example).

**Comment by rom1v** [comment]
Yes, that's expected, you pass all parameters to start scrcpy.

So do not just type `scrcpy`, but `scrcpy --record=file.mp4` before pressing Enter if you want to record.
