### ISSUE TITLE
Android 14 beta lock orientation doesn't work as expected when the device goes into landscape mode.

### ISSUE THREAD

**Issue by ssalenik** [Genymobile/scrcpy#4011]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: macOS
 - scrcpy version: 2.0
 - installation method: brew
 - device model: Pixel 7, 
 - Android version: Android 14 Beta (UpsideDownCake)

**Describe the bug**
Android 14 beta lock orientation doesn't work as expected when the device goes into landscape mode.
eg: if you launch: `scrcpy --lock-video-orientation=0` then go into landscape in an app, you get this:
![image](https://github.com/Genymobile/scrcpy/assets/1129490/302b3db9-0094-443a-bf88-7c2a6264d0da)

Looks like it no longer rotates the display output to fit the surface of the codec, but instead it keeps it in its orientation and scales it. Not clear if its a "bug" which will be fixed in the release, but seems possibly unlikely since its already in beta.

**Comment by vikingden8** [comment]
me too, I think this is a problem on new Android 14

**Comment by ssalenik** [comment]
OK, so now that the 14 source is released, I think the issue is due to this change in the `SurfaceControl.setDisplayProjection` fn:
Android 13: https://android.googlesource.com/platform/frameworks/base.git/+/refs/heads/android13-dev/core/java/android/view/SurfaceControl.java#2355

Android 14: https://android.googlesource.com/platform/frameworks/base.git/+/refs/tags/android-14.0.0_r2/core/java/android/view/SurfaceControl.java#2331

This fn now ignores the orientation param:
```
/**
--
  | * Because this API is now going through {@link DisplayManager}, orientation and displayRect
  | * will automatically be computed based on configuration changes. Because of this, the params
  | * orientation and displayRect are ignored
  | *
  | * @hide
  | */
  ```

**Comment by rom1v** [comment]
@ssalenik Thank you :+1:

Reported [here](https://issuetracker.google.com/issues/303565669#comment2).

**Comment by ssalenik** [comment]
Thanks. I think it may be possible to find a work around by re-implementing this `public static VirtualDisplay createVirtualDisplay` fn here:
https://android.googlesource.com/platform/frameworks/base.git/+/refs/tags/android-14.0.0_r2/core/java/android/hardware/display/DisplayManager.java#1567

which is what is called by `SurfaceControl.createDisplay` fn here:
https://android.googlesource.com/platform/frameworks/base.git/+/refs/tags/android-14.0.0_r2/core/java/android/view/SurfaceControl.java#2385

And possibly adding this hidden display flag `VIRTUAL_DISPLAY_FLAG_ROTATES_WITH_CONTENT`: https://android.googlesource.com/platform/frameworks/base.git/+/refs/tags/android-14.0.0_r2/core/java/android/hardware/display/DisplayManager.java#372

To the `VirtualDisplayConfig` here:
https://android.googlesource.com/platform/frameworks/base.git/+/refs/tags/android-14.0.0_r2/core/java/android/hardware/display/DisplayManager.java#1577

I've used this hidden flag before with the MediaProjection api to accomplish the same thing.

**Comment by ssalenik** [comment]
FYI, I tried doing what I suggested above, but it didn't work.
I was able to re-implement the `public static VirtualDisplay createVirtualDisplay` fn in `DisplayManager` and add passing the `VIRTUAL_DISPLAY_FLAG_ROTATES_WITH_CONTENT` flag to the `VirtualDisplayConfig`, but it did not change the behaviour.

**Comment by ssalenik** [comment]
@rom1v fyi, in my own code I was able to create a work around for this by manually rotating the surface myself.
This requires to create a 2nd "intermediate" surface which the display writes to, then using opengl code to rotate it before outputting to the encoder surface.
I used this fairly old but still working google grafika library to help me do it so I didn't really have to write any opengl code., specifically the `Sprite2d` to do the rotation:
https://github.com/google/grafika/blob/master/app/src/main/java/com/android/grafika/gles/Sprite2d.java

**Comment by rom1v** [comment]
> This requires to create a 2nd "intermediate" surface which the display writes to, then using opengl code to rotate it before outputting to the encoder surface.

@ssalenik Do you have a public branch which does this?

**Comment by ssalenik** [comment]
No, unfortunately that code is not open source. But I'll see if maybe I can make a patch, or at least write out the concept better with the scrcpy code.

**Comment by rom1v** [comment]
> But I'll see if maybe I can make a patch, or at least write out the concept better with the scrcpy code.

Indeed, a base branch in the scrcpy codebase would help a lot :wink: Setting a surface from a `SurfaceTexture` to capture the display, executing a simple hardcoded shader (using a simple swizzle to just swap the color channels for example) and encoding the result to produce the video stream would be absolutely perfect (without additional libraries) :sunglasses:

Otherwise, I'll probably investigate in the future (at first glance, this [sample](https://github.com/PhilLab/Android-MediaCodec-Examples/blob/master/CameraToMpegTest.java) should help).

**Comment by rom1v** [comment]
> But I'll see if maybe I can make a patch, or at least write out the concept better with the scrcpy code.

@ssalenik Indeed, a base branch in the scrcpy codebase would help a lot :wink: Setting a surface from a `SurfaceTexture` to capture the display, executing a simple hardcoded shader (using a simple swizzle to just swap the color channels for example) and encoding the result to produce the video stream would be absolutely perfect (without additional libraries) :sunglasses:

Otherwise, I'll probably investigate in the future (at first glance, this [sample](https://github.com/PhilLab/Android-MediaCodec-Examples/blob/master/CameraToMpegTest.java) should help).

**Comment by eiyooooo** [comment]
It seems that the "virtualDisplay" created by this method (introduced in Android 14)

https://github.com/Genymobile/scrcpy/blob/206809a99affad9a7aa58fcf7593cea71f48954d/server/src/main/java/com/genymobile/scrcpy/ScreenCapture.java#L54-L55

can rotate by

https://github.com/Genymobile/scrcpy/blob/206809a99affad9a7aa58fcf7593cea71f48954d/server/src/main/java/com/genymobile/scrcpy/wrappers/WindowManager.java#L104-L120

I don't have any device running Android 14, so it's hard for me to test.

You can try to rotate the "virtualDisplay" for this issue, it might be a solution.

**Comment by gassion** [comment]
I have also encountered this problem, is there any good solution to solve it now? Thank you very much.

**Comment by sbfkcel** [comment]
Encountered the same problem

**Comment by rom1v** [comment]
Please test a new version in #5455, a binary is provided.
