### ISSUE TITLE
Pixelated and blurry

### ISSUE THREAD

**Issue by Aydanill** [Genymobile/scrcpy#4012]
When i try to connect my tablet to my PC it keeps coming up pixelated and blurry. Does anyone know a fix?

**Comment by Aydanill** [comment]
![image](https://github.com/Genymobile/scrcpy/assets/49328173/88eb0055-ae99-4e1a-a1f8-957ab5b2cdf2)

**Comment by nnnpa31** [comment]
Try providing the following parameter: scrcpy --bit-rate=20M
It increases the video bitrate of the scrcpy from the default 8M to 20M, which may help to improve the video quality.
If blurring is still a problem, consider whether your device's USB communication rate has reached its upper limit. The speed can be measured by transferring a large file and estimating the time used.

**Comment by rom1v** [comment]
As suggested, increase the bitrate. But it's surprising to get such a low quality with the default settings. Dis you pass any parameters to scrcpy?

You could alsobtry another encoder (see `scrcpy --list-encoders`).

**Comment by Aydanill** [comment]
it doesn't work but I feel like my device will continue not to work with the program as its a modified version of android 10.

**Comment by Aydanill** [comment]
I did `scrcpy --encoder OMX.google.h264.encoder`
