### ISSUE TITLE
Audio not recording when capturing

### ISSUE THREAD

**Issue by donflack** [Genymobile/scrcpy#4014]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: Latest as of March 18th, 2023
 - installation method: Windows 64bit
 - device model: EC211001
 - Android version: 11

Recording video works fine but no audio.

**Comment by rom1v** [comment]
> Android version: 11

Did you read carefully https://github.com/Genymobile/scrcpy/blob/master/doc/audio.md for Android 11?

What is the output in the console?
