### ISSUE TITLE
Java client for scrcpy 

### ISSUE THREAD

**Issue by TimKieu** [Genymobile/scrcpy#4025]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist for a Java client to render and control scrcpy on Mac/Linux/Windows.

**Is your feature request related to a problem? Please describe.**
Seems nowhere having a Java client for scrcpy. The current SDL&FFMPEG C/C++ client is hard to make digital transform solution. 

**Describe the solution you'd like**
I'd like to use Java Libs ffmpeg, sdl, opencv etc for automation and interaction app on PC.

**Describe alternatives you've considered**
I need a clear and concise description & Specs  of scrcpy-server to start. Current documents is litle simple.

Please help me to kickoff this Java client soon.

**Comment by nnnpa31** [comment]
If you are sure that you have sufficient level of Java, then you will easily start from here [Server.java#L186](https://github.com/Genymobile/scrcpy/blob/958f22490b3ab86677bd8b6126ddaa4de4082798/server/src/main/java/com/genymobile/scrcpy/Server.java#L186)

Start tracing from program initialization and feed some of the byte stream assembly code into ChatGPT and you will get the complete stack for the Java Client implementation.

**Comment by TimKieu** [comment]
Thanks much @nnnpa31 for your advice.
I will try.
