### ISSUE TITLE
How to get rid of Performance Overlay

### ISSUE THREAD

**Issue by StraatLigMot** [Genymobile/scrcpy#4026]
When Screen Mirroring to PC (WIndows 11) OSD shows up with now way to remove this.
This does Not Show on my Windows 10 Laptop

No setting changed phone.

Using v2.0

How do I disable this overlay?
<img width="194" alt="Overlay" src="https://github.com/Genymobile/scrcpy/assets/39587328/e784e7d9-e22e-42b4-bc35-2b6d81401bed">

**Comment by rom1v** [comment]
Scrcpy does not add any overlay, that's your graphics drivers.

Check your graphics drivers settings.
