### ISSUE TITLE
My Galaxy J1 SM-J100h isnt detected by my pc and even tho sometimes it gets recognized as a device, SCRCPY just doesnt connect to it

### ISSUE THREAD

**Issue by ShrekTheRealOne** [Genymobile/scrcpy#4031]

**Comment by rom1v** [comment]
What is the result of `adb devices`?

What is the scrcpy console output?

**Comment by ShrekTheRealOne** [comment]
> What is the result of `adb devices`?
> What do you mean by adb devices
> What is the scrcpy console output?
> 
![scrcpy](https://github.com/Genymobile/scrcpy/assets/97811650/92fba951-4d17-4b1c-b8ef-e5774f6c7f08)

**Comment by ShrekTheRealOne** [comment]
> It looks like the device is running Android < 5 (like Android 4). This is not supported by scrcpy.

well that's sad, will that change in the future?

**Comment by rom1v** [comment]
No, see #98.
