### ISSUE TITLE
Add an option to keep the adb daemon alive in OTG mode

### ISSUE THREAD

**Issue by wh201906** [Genymobile/scrcpy#4032]
- [x] ~~I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.~~

**Is your feature request related to a problem? Please describe.**
According to the [doc](https://github.com/Genymobile/scrcpy/blob/2d3059e1ab687a18123636784f1e98ac653d3469/doc/hid-otg.md#physical-keyboard-simulation), users cannot use keyboard simulation with mirroring over the same USB connection on Windows. To monitor the phone and control it at the same time, I need to use adb over TCP and keyboard simulation in OTG mode.
However, If I start scrcpy for monitoring first and start another instance in otg mode for keyboard simulation, the latter will kill the adb daemon. So I have to start the scrcpy in otg mode first, then start scrcpy for monitoring.

**Describe the solution you'd like**
To start the two instances mentioned above in any sequence, I'd like to add an option to prevent killing adb daemon in otg mode([code there](https://github.com/Genymobile/scrcpy/blob/2d3059e1ab687a18123636784f1e98ac653d3469/app/src/usb/scrcpy_otg.c#L83-L90)).

**Describe alternatives you've considered**
+ For users like me, start the instances in specified order.
+ Kill the adb daemon only if the target device is connected via USB.
+ #4028 (I haven't test it yet.)

**Additional context**
I know the code for killing the adb daemon is for accessing the device via otg. However, a running adb daemon doesn't means that the target device is connected via USB. I think adding an extra option is easy to be implemented without changing the current behavior. I'm also ready to implement this if you'd like to.

**Comment by rom1v** [comment]
Thank you for your suggestion.

I'm closing to avoid several threads, the discussion continues here: https://github.com/Genymobile/scrcpy/issues/4028#issuecomment-1562390025
