### ISSUE TITLE
xiaomi 13 cannot unlock screen on boot

### ISSUE THREAD

**Issue by adminxp** [Genymobile/scrcpy#4036]
**Environment**
 - Android 13
 - scrcpy version: 2.0
 - Windows release
 - Xiaomi 12
 - Android version: [13]

**Describe the bug**
If finger print security is on when I boot phone and press it - phone asks for a security number no matter if fingerprint is ok but scrcpy displays only black screen(whole screen is black) instead of code input area

```
Please paste terminal output in a code block.
Nothing new in terminal - 
[server] INFO: Device: Xiaomi 2201123G (Android 13)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
Because your lock screen app enabled secure flag. See #36 #2129.

You can still interact with the device though to enter your pin (even if you don't see the content).
