### ISSUE TITLE
Video Encoding Request

### ISSUE THREAD

**Issue by tacssuki** [Genymobile/scrcpy#4048]
**Is your feature request related to a problem? Please describe.**
~ use the built-in/bloatware screen recorder of any or popular brand/manufacturer as video encoding
example: Xiaomi (phone brand/manufacturer) = MIUI Recorder (com.miui.recorder) so use the com.miui.recorder as video encoding

I just think this thing is better if added in video encoding because it will provide better quality on both video, audio and recording on android devices. These built-in apps are optimized for their purpose on each phone.

ths project is great and helpful! thanks devs.
sorry for poor grammar.

**Comment by rom1v** [comment]
> Xiaomi (phone brand/manufacturer) = MIUI Recorder (com.miui.recorder) so use the com.miui.recorder as video encoding

These are just apps with an UI which use MediaCodec internally to encode the video. Scrcpy uses MediaCodec directly.

You can change the bitrate/codec to adjust the quality: https://github.com/Genymobile/scrcpy/blob/master/doc/video.md
