### ISSUE TITLE
Add option to terminate dependency adb.

### ISSUE THREAD

**Issue by TimmyP777** [Genymobile/scrcpy#4049]
nt

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/issues/205#issuecomment-406776834
https://github.com/Genymobile/scrcpy/issues/2580

**Comment by rom1v** [comment]
Implemented option `--kill-adb-on-close`: a3cdf1a6b86ea22786e1f7d09b9c202feabc6949

**Comment by TimmyP777** [comment]
Nice! Thank you!
