### ISSUE TITLE
Green screen in landscape mode

### ISSUE THREAD

**Issue by seniorivn** [Genymobile/scrcpy#405]
[video illustration](https://i.imgur.com/b38lN9e.mp4)
The moment when the screen turns green is when i rotate the phone into landscape mode. and after i rotate it back, it shows the screen content normally even before animation(as you can see on the video)

stdout: 
```bash
/usr/share/scrcpy/scrcpy-server.jar: 1 file pushed. 2.9 MB/s (19346 bytes in 0.006s)
INFO: Initial texture: 1080x2160
The key you just pressed is not recognized by SDL. To help get this fixed, please report this to the SDL forums/mailing list <https://discourse.libsdl.org/> X11 KeyCode 159 (151), X11 KeySym 0x1008FF5A (XF86DOS).
The key you just pressed is not recognized by SDL. To help get this fixed, please report this to the SDL forums/mailing list <https://discourse.libsdl.org/> X11 KeyCode 159 (151), X11 KeySym 0x1008FF5A (XF86DOS).
```
I don't think i've pressed xf86dos key, though

**Comment by Sounak9434** [comment]
I have the same issue on my device running Android 9.0 Pie. The stdout doesn't shows any error for me though.
`scrcpy-server.jar: 1 file pushed. 0.6 MB/s (19734 bytes in 0.031s)
INFO: Initial texture: 1080x2160
INFO: New texture: 2160x1080
`

I have attached the logcat of the issue.
[logs.txt](https://github.com/Genymobile/scrcpy/files/2969488/logs.txt)

Whats unique in my case is that75% of the time my device screen stays black and scrcpy on desktop stays green. As soon as I exit scrcpy or rotate the device to portrait mode everything is back to normal.

**Comment by rom1v** [comment]
Does it work better with a lower definition?

    scrcpy -m1024

**Comment by Sounak9434** [comment]
@rom1v Surprisingly yes! Using a lower resolution fixes the issue. The video quality hampers a little but everything else works fine.

Is this a device side issue?

**Comment by rom1v** [comment]
> The video quality hampers a little but everything else works fine.

You could try with values higher than 1024 (and lower than 2160).

> Is this a device side issue?

Execute:

    scrcpy -r file.mkv

(with the full definition)

Then open this video file on another computer (or even try on the same computer): if it works, then it's not a device-side issue.

**Comment by Sounak9434** [comment]
@rom1v Tried with 'scrcpy -r file.mkv' and still same issue occurs. I guess it's device side, I'll report to the maintainer.

**Comment by rom1v** [comment]
Try with a power of two: https://github.com/Genymobile/scrcpy/issues/869#issuecomment-582949384

**Comment by JxM-92** [comment]
> Try with a power of two: [#869 (comment)](https://github.com/Genymobile/scrcpy/issues/869#issuecomment-582949384)

I recommend to investigate about your phone's maximum or default resolution, and use a value of 512*2ˆx, x>0... try to not go further than your phone's resolution, or else it won't work... 
I don't know why is it like this, but it is...

**Comment by JxM-92** [comment]
> I have the same issue on my device running Android 9.0 Pie. The stdout doesn't shows any error for me though.
> 
> ```
> scrcpy-server.jar: 1 file pushed. 0.6 MB/s (19734 bytes in 0.031s)
> INFO: Initial texture: 1080x2160
> INFO: New texture: 2160x1080
> ```
> 
> I have attached the logcat of the issue.
> [logs.txt](https://github.com/Genymobile/scrcpy/files/2969488/logs.txt)
> 
> Whats unique in my case is that75% of the time my device screen stays black and scrcpy on desktop stays green. As soon as I exit scrcpy or rotate the device to portrait mode everything is back to normal.

try 2048, that's not so lower...
