### ISSUE TITLE
Can't turn on display after --turn-screen-off or shortcut

### ISSUE THREAD

**Issue by CarloHD** [Genymobile/scrcpy#4058]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: 2.0
 - installation method: windows release
 - device model: Huawei Mediapad M3 ( EMUI 5.0.3 )
 - Android version: 7.0

**Describe the bug**

After the display is off with `--turn-screen-off`  or with <kbd>MOD</kbd>+<kbd>o</kbd>
I can't turn on the screen with <kbd>MOD</kbd>+<kbd>Shift</kbd>+<kbd>o</kbd>.

If i try to turn on the device with double pressing <kbd>MOD</kbd>+<kbd>p</kbd> (one time for lock the device, and the second for turn on) the display turn on for some milliseconds and turn off again.

The only way to turn on the screen is pressing the <kbd>MOD</kbd>+<kbd>Shift</kbd>+<kbd>o</kbd> even is doesn't work, and now press two times <kbd>MOD</kbd>+<kbd>p</kbd>

If i don't set `--stay-awake` and the screen is off, when the timeout screen timer is near to ended (exaclty 5 second before) the screen turn on to make a slight dimming.
For better explaining: Screen timeout is setted to 30secs, at 25secs the screen make a slight dimming. If the screen is off with `--turn-screen-off`, that slight dimming trigger the screen to turn on

**Comment by rom1v** [comment]
Yes, on some old devices turning the screen on does not work properly (scrcpy just requests to turn off/on, how the device handles it depends on the device/rom). It used to be even worse that what you observe (see 8c8649cfcd710859ce18eab557ed2af8cedb9a42 dcde578a50ffb9d2594c4764a067e9dd328bf55c).

> If i try to turn on the device with double pressing <kbd>MOD</kbd>+<kbd>p</kbd> (one time for lock the device, and the second for turn on) the display turn on for some milliseconds and turn off again.

If power on is done via scrcpy, it automatically turns back the screen off: #1577

Sorry, it is device specific, there is probably nothing scrcpy can do.

**Comment by CarloHD** [comment]
Ok, thanks for the response. 

For my purpose I've found a """"""workaround""""" to turn on the screen remotely, with sending an intent to Tasker from ADB that triggers an action that it double presses the power button, swipes up to show the pin input, inserts the pin (not a safe handling of course) and automatically unlocks the device. Better than nothing...

Anyway, I close this issue accepting your response, thanks again.

> Sorry, it is device specific, there is probably nothing scrcpy can do.
