### ISSUE TITLE
Unable to install on Python 3.11

### ISSUE THREAD

**Issue by iamnarendrasingh** [Genymobile/scrcpy#4065]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows 10]
 - scrcpy version: [e.g. 1.12.1]
 - device model:
 - Android version: [e.g. 12]

**Describe the bug**
I have Python 3.11 and wanted to install scrcpy. But unable to install it. As this version install on python version 3.7-3.10.

Please paste terminal output in a code block.
Below is command prompt output
ERROR: Ignored the following versions that require a different python version: 0.0.1 Requires-Python >=3.7,<3.10; 0.0.3 Requires-Python >=3.7,<3.10; 0.0.4 Requires-Python >=3.7,<3.10
ERROR: Could not find a version that satisfies the requirement scrcpy (from versions: none)
ERROR: No matching distribution found for scrcpy

**Comment by nnnpa31** [comment]
Scrcpy is not developed for Python, does not provide Python bindings, and does not rely on Python for compilation.

So I guess you seem to be asking questions in the wrong repo?
