### ISSUE TITLE
Add games section

### ISSUE THREAD

**Issue by ElNoperi** [Genymobile/scrcpy#4067]
You could add buttons to map and use the app as an emulator to play mobile games from your computer.

**Comment by rom1v** [comment]
Duplicate of #712.

**Comment by ElNoperi** [comment]
So I would have to adapt it manually So I would have to adapt it manually, the command in scrcpy does not exist as such

**Comment by ElNoperi** [comment]
So I would have to adapt it manually, the command in scrcpy does not exist as such
