### ISSUE TITLE
scrcpy win64 dont run, console runs, but say many errors!

### ISSUE THREAD

**Issue by TomsenCRX** [Genymobile/scrcpy#4070]
Hello,
i have the following problem- i want to connect my samsung phone to my pc. And then launch a game on the Samsung to play it on the PC. When I try to start Scrcpy Win64, no window opens. If I start the console below, I get the following message:

ERROR: Command not found: [adb], [start-server]
ERROR: (make 'adb' accessible from your PATH or define its fullpath in the ADB environment variable)
ERROR: Could not execute "adb start-server"
ERROR: Could not start adb daemon
ERROR: Server connection failed

What can i do?

**Comment by TomsenCRX** [comment]
If i start v2,0 win 64 console, that comes: 
scrcpy 2.0 <https://github.com/Genymobile/scrcpy>
ERROR: Could not find any ADB device
ERROR: Server connection failed
Drücken Sie eine beliebige Taste . . .

**Comment by rom1v** [comment]
> ERROR: Could not find any ADB device

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#device-not-detected

**Comment by TomsenCRX** [comment]
theres nothing for help

**Comment by rom1v** [comment]
> theres nothing for help

1. Did you enable USB debugging on your phone?
2. Did you install the drivers on Windows, as said in the link I posted?

**Comment by TomsenCRX** [comment]
yes sir.

**Comment by TomsenCRX** [comment]
Found issue: The Cabel was not the right one!

thx
