### ISSUE TITLE
Help：Auto lock screen disconnect

### ISSUE THREAD

**Issue by Qing-JiuJiu** [Genymobile/scrcpy#4073]
After I use a wireless connection to connect to the device, the screen will be blacked out and locked automatically after a period of time without operating the screen. After the screen is locked, the device will automatically disconnect. How can I solve this problem?

Console:
D:\Program Files\scrcpy-win64-v2.0>scrcpy --tcpip=10.10.10.125:5555 --turn-screen-off --stay-awake
scrcpy 2.0 https://github.com/Genymobile/scrcpy
INFO: Connecting to 10.10.10.125:5555...
INFO: Connected to 10.10.10.125:5555
D:\Program Files\scrcpy-win64-v2.0\scrcpy-server: 1 file pushed, 0 skipped. 62.9 MB/s (52867 bytes in 0.001s)
[server] INFO: Device: Xiaomi M2011K2C (Android 13)
INFO: Renderer: direct3d
INFO: Initial texture: 1440x3200
[server] INFO: Device screen turned off
WARN: Device disconnected

**Comment by Qing-JiuJiu** [comment]
Console:
D:\Program Files\scrcpy-win64-v2.0>scrcpy --tcpip=10.10.10.125:5555 --turn-screen-off --stay-awake
scrcpy 2.0 <https://github.com/Genymobile/scrcpy>
INFO: Connecting to 10.10.10.125:5555...
INFO: Connected to 10.10.10.125:5555
D:\Program Files\scrcpy-win64-v2.0\scrcpy-server: 1 file pushed, 0 skipped. 62.9 MB/s (52867 bytes in 0.001s)
[server] INFO: Device: Xiaomi M2011K2C (Android 13)
INFO: Renderer: direct3d
INFO: Initial texture: 1440x3200
[server] INFO: Device screen turned off
WARN: Device disconnected

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/issues/2995#issuecomment-1029114499
https://github.com/Genymobile/scrcpy/issues/1382#issuecomment-627591729

**Comment by Qing-JiuJiu** [comment]
> [#2995（评论）](https://github.com/Genymobile/scrcpy/issues/2995#issuecomment-1029114499) [#1382（评论）](https://github.com/Genymobile/scrcpy/issues/1382#issuecomment-627591729)

Thank you, I changed the default configuration of USB to charging only, and the above problems did not appear.
