### ISSUE TITLE
audio forwarding stops whenever i try to use phone mic

### ISSUE THREAD

**Issue by K4RMA29** [Genymobile/scrcpy#4084]
OKAY....so first of all its working like butter,,,,thank you for making this.....i am using scrcpy v2.0 on my PC...while casting a online game
(BGMI) i am getting all the sound of game. in my pc headset...but whenever i try to use the mic it stops audio forwarding in pc headset,,,can anyone help me....I tried watching for solution but did not get any ,,,Thank You In advance....My phone is Samsung M52

**Comment by rom1v** [comment]
Could you please try #5102 with `scrcpy --audio-source=playback` (on a device with at least Android 13)?

**Comment by almaftuchin** [comment]
> Could you please try [#5102](https://github.com/Genymobile/scrcpy/pull/5102) with `scrcpy --audio-source=playback` (on a device with at least Android 13)?

this is not working, the audio still on phone but not direct into my pc

**Comment by rom1v** [comment]
> this is not working, the audio still on phone but not direct into my pc

With playback audio source, it depends on the app. Try with VLC for Android for instance, does it work?

**Comment by almaftuchin** [comment]
> With playback audio source, it depends on the app. Try with VLC for Android for instance, does it work?

i use "--audio-source=mic" its working but how to mute the audio on the phone but only play audio into my pc. also not capture my voice from microphone from the phone but capture the voice from team microphone. i hope you understand what i mean

**Comment by almaftuchin** [comment]
i already use --audio-source=mic but how to mute audio on device but still forwarded on pc?
