### ISSUE TITLE
install_release.sh from release 2.1 installs wrong scrcpy-server version (2.0)

### ISSUE THREAD

**Issue by weisswieschwarz** [Genymobile/scrcpy#4121]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Debian 12
 - scrcpy version: 2.1
 - installation method: manual build from release 2.1
 - device model: irrelevant
 - Android version: irrelevant

**Describe the bug**
Installation prodecure with install_release.sh (release 2.1) downloads scrcpy-server 2.0. Resulting installation will not work due to mismatch between scrcpy (2.1) and scrcpy-server (2.0)

```
grep ^PREBUILT_SERVER_URL scrcpy-2.1/install_release.sh
PREBUILT_SERVER_URL=https://github.com/Genymobile/scrcpy/releases/download/v2.0/scrcpy-server-v2.0
```

```
scrcpy 2.1 <https://github.com/Genymobile/scrcpy>
scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 7.6 MB/s (52867 bytes in 0.007s)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: The server version (2.0) does not match the client (2.1)
        at com.genymobile.scrcpy.Server.createOptions(Server.java:172)
        at com.genymobile.scrcpy.Server.main(Server.java:360)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
ERROR: Server connection failed
```

One workaround is to manually download scrcpy-server 2.1 from the release page but perhaps this could be fixed.

**Comment by rom1v** [comment]
Please read explanation in #4098.

You should not execute `./install_release.sh` from tag `v2.0`, but one commit after (in practice, it is intended to be called from current `master` only).

**Comment by weisswieschwarz** [comment]
Thanks for the explanation. Sorry I did not find that issue, I searched for issues including "2.1".

Will close this issue then.
