### ISSUE TITLE
When I upgraded from scrcpy-server v1.25 to v2.1，I can't get video size and control screen

### ISSUE THREAD

**Issue by yangwutong** [Genymobile/scrcpy#4124]
### Env
windows11
jdk17
Android12
### Problem
**when i use v1.25,the start command is**
`adb shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 1.25 log_level=info max_size=1920 max_fps=%s tunnel_forward=true send_frame_meta=false control=true show_touches=false stay_awake=false power_off_on_close=false clipboard_autosync=false`
**and the parsing code is**
Socket screenSocket = new Socket("127.0.0.1", 4723);
InputStream screenIs = screenSocket.getInputStream();
if (screenIs.read() != 0){
    throw new RuntimeException(String.format("[%s]scrcpy connection error", serialNo));
}
for (int i = 0;i < 64;i++){
    screenIs.read();
}
int width = screenIs.read() << 8 | screenIs.read();
int height = screenIs.read() << 8 | screenIs.read();
int readLength;
int naLuIndex;
int bufferLength = 0;
byte[] buffer = new byte[1024 * 1024 * 10];
while (isRunMap.get(serialNo)){
    try {
        readLength = screenIs.read(buffer, bufferLength, 1024 * 5);
        if (readLength > 0) {
            bufferLength += readLength;
            for (int i = 5; i < bufferLength - 4; i++) {
                if (buffer[i] == 0x00 &&
                        buffer[i + 1] == 0x00 &&
                        buffer[i + 2] == 0x00 &&
                        buffer[i + 3] == 0x01
                ) {
                    naLuIndex = i;
                    byte[] naluBuffer = new byte[naLuIndex];
                    System.arraycopy(buffer, 0, naluBuffer, 0, naLuIndex);
                    dataQueue.add(naluBuffer);
                    bufferLength -= naLuIndex;
                    System.arraycopy(buffer, naLuIndex, buffer, 0, bufferLength);
                    i = 5;
                }
            }
        }
    }catch (Exception ignored){}
}
**when i use v2.1,the start command is**
`adb shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 2.1 log_level=info max_size=1920 max_fps=%s tunnel_forward=true send_frame_meta=false control=true show_touches=false stay_awake=false power_off_on_close=false clipboard_autosync=false audio=false send_codec_meta=true`
**i can't get the video's width and height,and can't control screen**
**somebody please help me,thanks very much**

**Comment by rom1v** [comment]
The video size is now passed as codec metadata (it is not sent with the device name anymore).

See:
 - 238ab872ba0ea18c2553dfe3c2202d64d67d8960
 - https://github.com/Genymobile/scrcpy/blob/master/doc/develop.md#protocol

**Comment by yangwutong** [comment]
thank you, bug what is the format of codec metadata and how should use Java parse it？
