### ISSUE TITLE
The audio volume is weak

### ISSUE THREAD

**Issue by plia7** [Genymobile/scrcpy#4133]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 11
 - scrcpy version: 2.0-2.1
 - installation method: Windows release...
 - device model: Motorola G Pure (2001)
 - Android version: 11

**Describe the bug**
The audio volume is weak for example when you run a game called Candy Crush my pc audio is at full volume but I can barely hear anything. When I run the same test using RustDesk 1.1.9 the audio is then loud as expected. 

Second issue is if I start a call, I can’t hear the ringing or when answered I can’t hear the sound. I have the same issue with RustDesk.

Do you have this issue too or does it work for you? Is this a bug?

No errors in the command line log window.
```
C:\adb\scrcpy-win64-v2.1\scrcpy.exe --tcpip=XXXXX:YYYY -b 2M -m 1024 --max-fps=15 --legacy-paste
C:\scrcpy-win64-v2.1\scrcpy-server: 1 file pushed, 0 skipped. 194.8 MB/s (56955 bytes in 0.000s)
[server] INFO: Device: [motorola] motorola moto g pure (Android 11)
INFO: Renderer: direct3d
INFO: Texture: 464x1024
```

Thank you.

**Comment by rom1v** [comment]
> The audio volume is weak

How is the volume on both your phone and the computer? On the computer, there might be a volume per application. On Windows, check for example https://pureinfotech.com/adjust-app-sound-windows-10/

> Second issue is if I start a call, I can’t hear the ringing or when answered I can’t hear the sound

Yes, it's expected. Audio calls could not be captured.

**Comment by plia7** [comment]
> 

Ok, the Media Volume wasn't at 100% on the phone, now it's working, thanks
Any reason why audio calls could not be captured and are there any workarounds for that so they can be somehow captured or heard?

**Comment by plia7** [comment]
It's working as expected.

**Comment by mieaw** [comment]
adb shell input keyevent 24 # volume up
adb shell input keyevent 25 # volume down

![image](https://github.com/user-attachments/assets/799fdc98-3b22-4c38-ac29-deb5bb567109)

**Comment by girng** [comment]
> Or Alt+up / Alt+down in the scrcpy window.

ty
