### ISSUE TITLE
When casting Oculus Quest Pro to Windows, the screen content is rotated approximately 30 degrees.

### ISSUE THREAD

**Issue by zhang-1999** [Genymobile/scrcpy#4135]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 11
 - scrcpy version: 2.1
 - installation method: Window Release from GitHub Release
 - device model:
 - Android version:  Android 12 ( Oculus Quest Pro ）

**Describe the bug**
When casting Oculus Quest Pro to Windows, the screen content is rotated approximately 30 degrees.

BTW,Oculus Quest 2 works well.

```
scrcpy --no-audio --crop 1730:974:1934:450
```

![img_v2_7d326f7b-9854-4896-8c0e-e21117c896fg](https://github.com/Genymobile/scrcpy/assets/33936981/218ecce2-7dcf-4133-a784-02eb55dd64a2)

**Comment by rom1v** [comment]
This is how the content is rendered on Android.

**Comment by zhang-1999** [comment]
Sorry, I didn't quite understand what you meant. Did you meant that the content is rendered on Oculus Quest Pro is correctly ? If yes,you saying that scrcpy cannot solve this problem?

Did scrcpy provide a cli arg to rotate the video stream ?

**Comment by rom1v** [comment]
Scrcpy captures what is rendered on the "surface". How the screen content is "transformed" by the Oculus device to display correctly for each eye is out of control of scrcpy. In theory, it could be possible to apply the same "warp" transformation, but it must be known (estimated), and scrcpy does not support such a feature anyway.

It can only rotate by multiples of 90°: https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#rotation

**Comment by zhang-1999** [comment]
Thanks for you reply . Could you provide a more granular cli argument about "rotation",for example : 
```
scrcpy --lock-video-orientation=0 
scrcpy --video-rotation=30
```

**Comment by zhang-1999** [comment]
If you think this feature should not be added to scrcpy , I wanto to know did the proposal is feasible in techonology ? I can try to fork this project to make custom changes if possible

**Comment by rom1v** [comment]
> I wanto to know did the proposal is feasible in techonology ?

Oh, actually [`SDL_RenderCopyEx()`](https://wiki.libsdl.org/SDL2/SDL_RenderCopyEx) accepts an arbitrary angle, so you can play with that:

https://github.com/Genymobile/scrcpy/blob/625934fb1b078a5d66bc4864e8082840d57d4557/app/src/display.c#L275-L276

**Comment by zhang-1999** [comment]
thanks, I will try it

**Comment by nnnpa31** [comment]
> Sorry, I didn't quite understand what you meant.

(just a speculation, I do not have any evidence)
I think the Oculus Quest Pro's display is physically rotated by 30 degrees (or 45 degrees) to the point where the display needs to be reversed by a certain angle to properly display the binoculars.

**Comment by Mar2ck** [comment]
It's a trick to prevent the screen door effect. The screens for each eye in the Quest Pro are rotated 30 degrees in opposite directions which means the pixel grid for each eye no longer lines up and therefore isn't as visible.

**Comment by rolandwellinger** [comment]
@zhang-1999 Do you got any success rotating the image for Quest Pro / Quest 3?

**Comment by polyzium** [comment]
I have a Quest 3 and Meta did the exact same trick with the panels. I wonder if this is possible to do via SDL_gfx or OpenGL, or possibly a homegrown transformation algorithm. Possibly could learn something from OBS since it has transforms as essential functionality.

**Comment by rolandwellinger** [comment]
Hi All. Thank you so much for addressing this issue. When is this comming to release? I like to use scrcpy and hopefully later on SideQuest to Stream Again from the HMD.

**Comment by rom1v** [comment]
Please test #5455 and the new `--angle` option.
