### ISSUE TITLE
click actions do not take effect on certain pages

### ISSUE THREAD

**Issue by yangwutong** [Genymobile/scrcpy#4138]
### Environment
OS: Windows 11
scrcpy version: 1.25
device model: Sony Xperia5 
Android version: Android 12
### Describe the Problem
I built a cloud mobile device platform based on Scrcpy， and the start command is:
`adb shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 1.25 log_level=info max_size=1920 max_fps=60 tunnel_forward=true send_frame_meta=false control=true show_touches=false stay_awake=false power_off_on_close=false clipboard_autosync=false`
in some google advertising page，none of my actions are taking effect, when I open Developer options->Show taps and Pointer location, I can clearly see that the click operations are being displayed on the phone，but I don't know why is it not having any actual effect
![image](https://github.com/Genymobile/scrcpy/assets/52696124/48322d52-0ba8-44ad-ba5a-a3ef917e7d8e)
and I use the scrcpy-win64-v1.25 is normal
![image](https://github.com/Genymobile/scrcpy/assets/52696124/83400c78-f96b-43b7-80c6-8b8fc9b057bb)
Is my start command incorrect？Is it caused by other reasons?

**Comment by rom1v** [comment]
Then your custom client probably does not send the same control messages to the server as the scrcpy client does.

**Comment by nnnpa31** [comment]
Recommendation: Open source a minimal implementation that reproduces the problem for reviewers to check the code for possible causes of the problem.

**Comment by yangwutong** [comment]
> Then your custom client probably does not send the same control messages to the server as the scrcpy client does.

the control messages is send normal，and when I open Developer options->Show taps and Pointer location, I can clearly see that the click operations are being displayed on the phone，but it didn't actually take effect
![image](https://github.com/Genymobile/scrcpy/assets/52696124/8b7904c2-d312-4a35-a398-66abf51787a1)

**Comment by rom1v** [comment]
But if it works with scrcpy but not in your custom client, then this is probably a problem with your custom client. I could not guess.

**Comment by yuyiqilin** [comment]
Did you solve it? I had the same problem. Version 1.25 can be used normally

**Comment by yangwutong** [comment]
> Did you solve it? I had the same problem. Version 1.25 can be used normally

I did not find the reason for the issue, so I gave up using scrcpy to control phone，
and I wrote a APK based on [sonic-android-apk](https://github.com/SonicCloudOrg/sonic-android-apk) to control phone

**Comment by rom1v** [comment]
Might be related: https://github.com/Genymobile/scrcpy/pull/3704

**Comment by yuyiqilin** [comment]
> Might be related: https://github.com/Genymobile/scrcpy/pull/3704

I don't know if I understand this correctly. The mouse click execution process is changed to 4 steps（ACTION_DOWN,ACTION_BUTTON_PRESS,ACTION_BUTTON_RELEASE,ACTION_UP）。Is that right？

**Comment by yuyiqilin** [comment]
I solve it。

**Comment by rom1v** [comment]
> I solve it

How?

**Comment by yuyiqilin** [comment]
> > I solve it
> 
> How?

I sent the wrong bytes to the control thread.I figured this out by analyzing the source code
