### ISSUE TITLE
ERROR: CreateProcessW() error 2 Command not found

### ISSUE THREAD

**Issue by muyangpiaoliang** [Genymobile/scrcpy#4139]
ERROR: CreateProcessW() error 2
ERROR: Command not found: [%android_adb%], [start-server]
ERROR: (make 'adb' accessible from your PATH or define its fullpath in the ADB environment variable)
ERROR: Could not execute "adb start-server"
ERROR: Could not start adb server
ERROR: Server connection failed

**Comment by rom1v** [comment]
Because you set the `ADB` environment variable to `%android_adb%` which is not an executable.

Just unset the variable, the scrcpy release embeds an adb executable.

**Comment by muyangpiaoliang** [comment]
May I ask if there is a problem with the phone or the computer

**Comment by muyangpiaoliang** [comment]
Thank you very much for solving the problem. Just delete the environment variables from the computer
