### ISSUE TITLE
Bug: when leaving the window of srcpy, it might become black 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Genymobile/scrcpy#414]
I don't know on which other cases it occurs, but if I have srccpy opened , and I go to a game as "Heroes of the storm", when I get back to srccpy, it is black even though the device's screen is turned on.
Clicking on the window actually does touching on the screen...

**Comment by rom1v** [comment]
Thank you for the report.

To be investigated.

**Comment by AndroidDeveloperLB** [comment]
@rom1v Thank you. 
Say, what is the avatar you are using? A reference to Linux penguin?

**Comment by rom1v** [comment]
> Say, what is the avatar you are using? A reference to Linux penguin?

Yes : https://www.gnu.org/graphics/3dbabygnutux.en.html

**Comment by AndroidDeveloperLB** [comment]
Ohhhh... OK.

**Comment by rom1v** [comment]
I guess it's some graphic driver or SDL issue. Probably nothing we can do in scrcpy.

**Comment by AndroidDeveloperLB** [comment]
@rom1v 
I actually haven't seen the issue for a long time.
I think you fixed it. Maybe by refreshing the content when focusing on it?
