### ISSUE TITLE
How can disallow mirroring in my android app with this method?

### ISSUE THREAD

**Issue by pawan2601** [Genymobile/scrcpy#415]
Hi,

This script is great for the purpose built for. However, due to security reasons I need to stop mirroring of my app via this method. Can you suggest me any code/resource for my android app, which can prevent mirroring of my app.

I shall be very grateful.

**Comment by rom1v** [comment]
Hi,

Sorry, I don't know.

> due to security reasons

Out of curiosity, could you explain what these security reasons are?

**Comment by pawan2601** [comment]
Security as per se, DRM protection. If we are delivering some videos which we do not want to get recorded, we need to employ some method to stop this.

**Comment by Qormix** [comment]
@pawan2601 I suggest checking if usb debugging is enabled.

https://stackoverflow.com/questions/18716808/how-to-check-usb-debugging-enabled-programmatically
