### ISSUE TITLE
Support for automatically resizing between multiple displays

### ISSUE THREAD

**Issue by LuminarySage** [Genymobile/scrcpy#4152]
**Environment**
 - OS: Windows 11
 - scrcpy version:  v2.1
 - installation method: Windows release
 - device model: Google Pixel Fold
 - Android version: 13

**Describe the bug**
Right now if I switch between displays on something like a foldable phone, the screen capture won't scale to the correct aspect ratio at all

Transitioning from the outer display to the inner display
![scrcpy_47Mmbwv6nN](https://github.com/Genymobile/scrcpy/assets/24306400/2e3bad31-0327-40f4-aa30-f5b3bec407af)

Transitioning from the inner display to the outer display
![ezgif com-optimize](https://github.com/Genymobile/scrcpy/assets/24306400/54789884-8cc4-4980-b41a-0648186cbafd)

**Comment by rom1v** [comment]
@AdoPi (as the author of #3979): could you reproduce?

**Comment by AdoPi** [comment]
Sorry I can't reproduce. It works with the latest version available on master, on a Samsung Z Fold 4.
Note that I'm testing on Linux, Currently I don't have Windows.

**Comment by AdoPi** [comment]
@Jnss98b Could you please add this little patch to help debugging this issue?

```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/Device.java b/server/src/main/java/com/genymobile/scrcpy/Device.java
index f817a3ce..e9da6742 100644
--- a/server/src/main/java/com/genymobile/scrcpy/Device.java
+++ b/server/src/main/java/com/genymobile/scrcpy/Device.java
@@ -103,6 +103,7 @@ public final class Device {
             ServiceManager.getWindowManager().registerDisplayFoldListener(new IDisplayFoldListener.Stub() {
                 @Override
                 public void onDisplayFoldChanged(int displayId, boolean folded) {
+                    Ln.i("==== onDisplayFoldChanged(" + displayId + ", " + folded + ")");
                     synchronized (Device.this) {
                         DisplayInfo displayInfo = ServiceManager.getDisplayManager().getDisplayInfo(displayId);
                         if (displayInfo == null) {

```

Thanks!

**Comment by Jnss98b** [comment]
Will test it tomorrow when I get back. Currently out of town at the moment

**Comment by Jnss98b** [comment]
@AdoPi Could you do me a favor and build a 64-bit windows release with the patch please? I'm having trouble building from source with msys2

**Comment by rom1v** [comment]
@Jnss98b:
- [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/4152/1/scrcpy-server) <sub>`SHA-256: 783d4b65f31eb3b7162c97de6d7b1aa11b154140540b5bf2b0aadf8b210e9d05`</sub>

(to be replaced in your v2.1 release)

**Comment by Jnss98b** [comment]
Just tested with the patched server and the issue is still happening

**Comment by Jnss98b** [comment]
Any update on this? @AdoPi

**Comment by AdoPi** [comment]
Does your window size change when you fold your phone or not at all?

If possible for you, could you please try on Linux or Mac? I suspect it is an issue with the window and not with events sent from your device.

**Comment by Jnss98b** [comment]
> Does your window size change when you fold your phone or not at all?

Yeah it doesn't at all. Both when folding and unfolding

> If possible for you, could you please try on Linux or Mac? I suspect it is an issue with the window and not with events sent from your device.

I could try it on linux. Does it matter if I test it on a VM?

**Comment by Jnss98b** [comment]
Set up a ubuntu vm just to find out afterward that the latest packaged version for ubuntu is 1.25 lol fml

**Comment by Jnss98b** [comment]
Just tested with scrcpy 2.1.1 on ubuntu 22.0.4.3 lts and I can still reproduce the issue

**Comment by Jnss98b** [comment]
Looks like the window does resize automatically...but not in an intended way
https://github.com/Genymobile/scrcpy/assets/24306400/36c7a1e3-185d-4991-83b2-9c6d2ba7243c

**Comment by AdoPi** [comment]
Thank you for your video! 
So it seems like your device sends the good fold event. 
@rom1v any idea of what's going on?

**Comment by AdoPi** [comment]
I guess rotating your screen doesnt work too?

**Comment by Jnss98b** [comment]
Actually, that works well haha. I've never had any issue with that, even with previous devices

**Comment by Jnss98b** [comment]
Also, the demos I did today were on a different pc from the one I first discovered the issue on so I suppose it's reproducible on multiple hosts?

**Comment by Jnss98b** [comment]
Outer display

https://github.com/Genymobile/scrcpy/assets/24306400/1474b40d-b3cd-40a4-b649-a2f0a1e14975

Inner display

https://github.com/Genymobile/scrcpy/assets/24306400/3c000bf1-1e88-4acd-a37c-591fc46ab8fd

**Comment by Jnss98b** [comment]
Not sure if anything changed but on v2.1.1 it seems to handle changing between displays a little bit better but still isn't really ideal. The inner display size will always be limited by the width of the outer display regardless of what display is in use when scrcpy was launched with folding events. The one time the inner display will be full size is if scrcpy was started with the inner display in use and the screen wasn't folded at all.

**Starting scrcpy on the cover display:**

https://github.com/Genymobile/scrcpy/assets/24306400/bd07f816-01a0-44d3-a999-be4dfa3a441f

**Starting scrcpy from the inner display:**

https://github.com/Genymobile/scrcpy/assets/24306400/7f37a763-e732-48b9-acea-4c28f29d67ae

**Comment by j0hnm4r5** [comment]
Any movement on this by chance? I can also confirm the same exact issue with a Pixel Fold on macOS.
