### ISSUE TITLE
Dex is not filling the Scrcpy window

### ISSUE THREAD

**Issue by Obsidiannite21** [Genymobile/scrcpy#4157]
![Screenshot 2023-07-11 at 11 17 13 AM](https://github.com/Genymobile/scrcpy/assets/28603530/8716772c-6d04-4657-b42e-7f126483e7f8)
 - [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...] macOS
 - scrcpy version: [e.g. 1.12.1] 2.1
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...] brew
 - device model: S23 Ultra
 - Android version: [e.g. 10] 13

**Describe the bug**
After upgrading to 2.1, when I launch scrcpy --display 2, it gives the following WARN: Display doesn't have FLAG_SUPPORTS_PROTECTED_BUFFERS flag, mirroring can be restricted
INFO: Renderer: metal

The window is able to be resized but the Dex desktop is much smaller the the actual window. It's easier to understand if you check out the attached screenshot. It is likely related to issue: #4120 but it looks like that was resolved. Am I missing something? 

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.

scrcpy 2.1 <https://github.com/Genymobile/scrcpy>
/opt/homebrew/Cellar/scrcpy/2.1/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 48.2 MB/s (56955 bytes in 0.001s)
[server] INFO: Device: [samsung] samsung SM-S918U1 (Android 13)
[server] WARN: Display doesn't have FLAG_SUPPORTS_PROTECTED_BUFFERS flag, mirroring can be restricted
INFO: Renderer: metal
INFO: Texture: 3088x1440

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
> After upgrading to 2.1

Did you have the same problem with earlier versions?

As a workaround, does [cropping](https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#crop) work correctly?

**Comment by Obsidiannite21** [comment]
@rom1v No, but to be fair this is the first upgrade I've done since I installed it.

Yes the recorded video contains the black padding like the screenshot.

Yes scrcpy --display 2 --crop=1080:1920:0:0 -e fixes the issue, thank you for the work around!! I was looking for one but didn't see crop.

**Comment by nikp123** [comment]
I also have the "same-ish" issue it seems, but manifested when using the simulated display mode.

**Comment by nikp123** [comment]
The issue seems that scrcpy is grabbing the wrong texture size. It takes the resolution of the primary display (aka the phones) rather than of the the display that you're targeting.

**Comment by rom1v** [comment]
> It takes the resolution of the primary display (aka the phones) rather than of the the display that you're targeting.

Could you please test on `dev` branch? #4120 has been fixed since scrcpy v2.1 (808bd14e301351ce63b4fc45ac54d3bf34423e94)

**Comment by rom1v** [comment]
> Do I need to build the scrcpy-server part

Yes, the change impacts scrcpy-server. You don't need the Android NDK to build scrcpy (just the Android SDK).

Anyway, here is a release of the current `dev` branch:

- [`scrcpy-win64-v2.1-6-g01d785d9a.zip`](https://tmp.rom1v.com/scrcpy/4157/1/scrcpy-win64-v2.1-6-g01d785d9a.zip) <sub>`SHA-256: 9b07defe03291d39b89daff9f26667abac2ca342393b63e076de3f6b54a418f4`</sub>

**Comment by nikp123** [comment]
> > Do I need to build the scrcpy-server part
> 
> Yes, the change impacts scrcpy-server. You don't need the Android NDK to build scrcpy (just the Android SDK).
> 
> Anyway, here is a release of the current `dev` branch:
> 
>     * [`scrcpy-win64-v2.1-6-g01d785d9a.zip`](https://tmp.rom1v.com/scrcpy/4157/1/scrcpy-win64-v2.1-6-g01d785d9a.zip) `SHA-256: 9b07defe03291d39b89daff9f26667abac2ca342393b63e076de3f6b54a418f4`

Thanks, will test when I get home on my Windows PC (in about 3-4 hours), sorry for the delay

**Comment by nikp123** [comment]
@rom1v sorry for the additional delay, yes the issue has been fixed.

**Comment by rom1v** [comment]
@Obsidiannite21 Is the issue also fixed for you?

**Comment by Obsidiannite21** [comment]
How would I install the dev branch using Brew on MacOS?

**Comment by rom1v** [comment]
Take `scrcpy-server` from the zip (I guess the client changes are not important), and execute:

```bash
export SCRCPY_SERVER_PATH=/the/path/to/the/downloaded/scrcpy-server
scrcpy
```

**Comment by yougg** [comment]
> > Do I need to build the scrcpy-server part
> 
> Yes, the change impacts scrcpy-server. You don't need the Android NDK to build scrcpy (just the Android SDK).
> 
> Anyway, here is a release of the current `dev` branch:
> 
> * [`scrcpy-win64-v2.1-6-g01d785d9a.zip`](https://tmp.rom1v.com/scrcpy/4157/1/scrcpy-win64-v2.1-6-g01d785d9a.zip) `SHA-256: 9b07defe03291d39b89daff9f26667abac2ca342393b63e076de3f6b54a418f4`

I'm using Arch Linux and got the same display problem
after got the scrcpy-server extract from the above zip file
and run with it `SCRCPY_SERVER_PATH=~/Downloads/scrcpy-win64-v2.1-6-g01d785d9a/scrcpy-server scrcpy --display=2`
finally it display correct. thanks so much.

**Comment by rom1v** [comment]
:+1: The fix has been released in scrcpy v2.1.1.

**Comment by carcinocron** [comment]
how are you activating Samsung Dex (or Android Desktop)? mine just stays in cellphone mode.

**Comment by Obsidiannite21** [comment]
I connect my S23 to a hub that has a monitor attached. That allows me to mirror OR run dex, depending on how you run Scrcpy. Some use fake HDMI dongles. I haven't found a "software" solution to run Dex using Scrcpy but if in your search find one, please let me know.
