### ISSUE TITLE
Record screen produces video that appears black in Quicktime

### ISSUE THREAD

**Issue by LouisCAD** [Genymobile/scrcpy#416]
Here's the command I ran on version 1.6:
`scrcpy -m 1280 -r Desktop/some-file.mp4 -t`

Here are the logs for my recording attempt:
```console
/usr/local/Cellar/scrcpy/1.6/share/scr...shed. 1.2 MB/s (19464 bytes in 0.015s)
2019-01-30 17:30:33.950 scrcpy[21276:1317781] INFO: Enable show_touches
2019-01-30 17:30:34.673 scrcpy[21276:1317781] INFO: Initial texture: 720x1280
2019-01-30 17:30:41.662 scrcpy[21276:1317781] INFO: Disable show_touches
```

Here's the output of `scrcpy --version`:
```console
scrcpy 1.6

dependencies:
 - SDL 2.0.9
 - libavcodec 58.35.100
 - libavformat 58.20.100
 - libavutil 56.22.100
```

OS: MacOS Mojave 10.14 (18A391)

While the command was running (until I clicked the close button on the window), the screen was displayed correctly on my computer, but the output file, results in black footage when viewed from Quicktime.

**Comment by rom1v** [comment]
Might be related to #351.

**Comment by rom1v** [comment]
Fixed on `dev`.
