### ISSUE TITLE
2.1 BUG，scrcpy --tcpip --disable-screensaver --prefer-text --turn-screen-off --stay-awake

### ISSUE THREAD

**Issue by hbfight** [Genymobile/scrcpy#4161]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows]
 - scrcpy version: [2.1]
 - installation method: [Windows release]
 - device model:huawei navo 7
 - Android version: [harmonyos 3.0]

**Describe the bug**

I used this command to start, but my phone still goes into sleep mode. Every time I need to operate, I need to enter a lock screen password to operate. Do I need to add any startup parameters to ensure that the screen runs continuously?
Do you need to set your phone to always light up? It's very troublesome to set me not to connect to the computer like this.

**Comment by rom1v** [comment]
`--stay-awake` actually means "stay awake while plugged in": https://github.com/Genymobile/scrcpy/blob/master/doc/device.md#stay-awake

**Comment by hbfight** [comment]
> `--stay-awake` actually means "stay awake while plugged in": https://github.com/Genymobile/scrcpy/blob/master/doc/device.md#stay-awake

If I want my device to not lock the screen, I can only set it on my phone and cannot achieve it through "scrcpy"?

**Comment by rom1v** [comment]
On your phone, you can change the delay after which the screen is turned off (up to 30 minutes), but AFAIK you cannot disable the screen turning off if the device is not plugged in.

**Comment by hbfight** [comment]
> 

thanks, once question , In pc.How to input directly into mobile phone with Microsoft input method?
