### ISSUE TITLE
Complete Audio Distortion (Static Noise)

### ISSUE THREAD

**Issue by Minesh25** [Genymobile/scrcpy#4163]
It's had been about a month since I last used the program and the last time I used it; it was working perfectly. So today I was using it to cast my phone on my laptop and when I played an audio it started distorting. When I say distorting, I mean when there should be some audio playing, I only hear static noise. I use a **GUI** called '**guiscrcpy**' so I ran the program without the GUI and the results were the same. I was also screen recording the shared window on my laptop and while rewatching the recorded video, there was no distortion. 
So, I started searching if there was a new version and found out that **scrcpy-v2.1** was out about 3 weeks ago. So, I downloaded the zip file, extracted it and ran the program, but the audio is still distorted.
Any suggestion on how to solve this issue?
If needed, my phone is "**Realme 9 pro+**" and it is currently running **Stable Android 13**.

**This was recorded from my phone and you can hear the level of audio distortion.** _(Forward to 6 seconds)_
https://github.com/Genymobile/scrcpy/assets/117034077/ae45f12f-2256-4607-9a59-f0e3c1e47193

**This is the recorded screen of my phone from my laptop and you can hear that there is no distortion.** _(Forward to 3 Seconds)_
https://github.com/Genymobile/scrcpy/assets/117034077/fbb1601e-8fcb-47f4-b91e-b83ae4d59adb

**Comment by rom1v** [comment]
Is it better with `scrcpy --audio-output-buffer=10`? (#3793)

**Comment by Minesh25** [comment]
> Is it better with `scrcpy --audio-output-buffer=10`? (#3793)

Thanks that solved the issue.

> Because the video is in H.265 that your browser cannot play. However, if you download the video and play it with a player with H.265 support, it works.

Thanks, I didn't know that so I re-uploaded the video in H.264.
