### ISSUE TITLE
Add `device_server_path` and `port` to verbose debug level

### ISSUE THREAD

**Issue by NewUserHa** [Genymobile/scrcpy#4164]
- [X] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
I want to know where the 'scrcpy' pushed the 'scrcpy-server.jar' and what 'ports' it's using.

I have checked path "/data/local/tmp/scrcpy-server.jar" and even `find / -name "scrcpy*"` and `ss -l` with root user, but got nothing. ( the former path comes from github.com/Genymobile/scrcpy/blob/625934fb1b078a5d66bc4864e8082840d57d4557/app/src/server.c#L21)

**Describe the solution you'd like**
print device_server_path and port when scrcpy.exe start with `-V debug` argument

**Describe alternatives you've considered**
or add it to readme.md?

**Additional context**
N/A

**Comment by yume-chan** [comment]
The path is correct, however, the server deletes itself on start, unless `--no-cleanup` is specified.

https://github.com/Genymobile/scrcpy/blob/9196dc156376760eb637024d5c0448ceeaa2a8ff/server/src/main/java/com/genymobile/scrcpy/CleanUp.java#L142-L148

https://github.com/Genymobile/scrcpy/blob/744312ec64d2552271fd2918abce2e14b6137843/app/src/cli.c#L388-L393

**Comment by NewUserHa** [comment]
Ok.
But it still can't find the port scrcpy is using for the port forward.

And those mostly exist only in the code, what about adding them to debug level log?

**Comment by rom1v** [comment]
```
    -p, --port=port[:port]
        Set the TCP port (range) used by the client to listen.
        Default is 27183:27199.
```

**Comment by NewUserHa** [comment]
Ok. didn't find that via search.

This issue could probably be closed since seems those in the help msg.
