### ISSUE TITLE
Touchscree Freeze During Game

### ISSUE THREAD

**Issue by guiguijke** [Genymobile/scrcpy#417]
Hi,
While I'm streaming games, I remarked that touchscreen can freeze while scrcpy is running
Is there a way do disable this function ?
Regards

**Comment by rom1v** [comment]
By "touchscreen", do you mean mouse and keyboard events from _scrcpy_?
By freeze, do you mean that they stop working, or that it also freeze the video stream?
Do you have any error message in the console when it happens? (or in the output of `adb logcat`)

> Is there a way do disable this function ?

It is not possible to disable input events forwarding for now.

**Comment by rom1v** [comment]
> I do not touch my keyboard

OK, so it's not related to input events forwarding.

> the screen of my OP6T is not responding for few ms and comes back normal

So there is a lag on the device-side.

>     scrcpy-noframeskip.exe -m 1000 -b 12M

Does it also happen with the "standard" version (with frame skip enabled)? And with lower definition or bitrate?

**Comment by guiguijke** [comment]
> the screen of my OP6T is not responding for few ms and comes back normal
> 
> So there is a lag on the device-side.

I'm not so sure, It's not a device lag, my touchscreen becomes unresponsive while the framerate is smooth, and everything is normal ...

> Does it also happen with the "standard" version (with frame skip enabled)? And with lower definition or bitrate?

I'll try that.

**Comment by rom1v** [comment]
> I'm not so sure, It's not a device lag, my touchscreen becomes unresponsive while the framerate is smooth, and everything is normal ...

_scrcpy_ does not handle touch screen on the device, so it's a side effect. The device takes time to process input events from the touchscreen for some reason…

**Comment by rom1v** [comment]
> > Does it also happen with the "standard" version (with frame skip enabled)? And with lower definition or bitrate?
>
> I'll try that.

Did you try?

**Comment by guiguijke** [comment]
I tryed without streaming and it appears that it happens when I use my triggers on the screen

So, problem closed , your software isn't the cause :)
