### ISSUE TITLE
USB Mic Audio Routing

### ISSUE THREAD

**Issue by ItsJustTee** [Genymobile/scrcpy#4176]
I wonder...............how possible it would be if I can route my USB Mic to my Phone? I have zero idea if this is supported by the Android OS.

For reference:
- On Linux, audio routing is done using Carla and JACK

I wonder if the same is possible for Android Devices as a way for improved audio quality.

**Comment by yume-chan** [comment]
#3880

**Comment by ItsJustTee** [comment]
Closing as not possible
