### ISSUE TITLE
screen unlock

### ISSUE THREAD

**Issue by Rui1007** [Genymobile/scrcpy#4178]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: windows 11
 - scrcpy version: 2.1.1
 - installation method: Windows release
 - device model: huawei p20pro
 - Android version: 9

When unlocking the screen lock with scrcpy, only a black screen is displayed on the screen of scrcpy, and it is not possible to operate on scrcpy.
Also, my smartphone is currently broken and I can't display the screen. Is there a way to make the screen visible and unlock it with scrcpy?

**Comment by rom1v** [comment]
If your lock screen sets the secure flag, you cannot mirror it from Android 12+ (#36, #2129).

However, you can change/disable your lock password with adb: https://nerdschalk.com/change-remove-lockscreen-pattern-pin-password-adb-android-oreo/

**Comment by wangdeshan** [comment]
unlock.sh
``` 
SCREEN_STATE=`dumpsys window policy | grep 'screenState=' | cut -d '=' -f2`

if [  "$SCREEN_STATE" == "SCREEN_STATE_ON"  ];
then
    echo "SCREEN_STATE_ON"
else
    echo "SCREEN_STATE_OFF"
	input keyboard keyevent 26
fi

KEYGUARD_STATE=`dumpsys window policy | grep 'showing=' | cut -d '=' -f2`

if [  "$KEYGUARD_STATE" == "true"  ];
then
    echo "KEYGUARD_SHOWING"
	input keyboard keyevent 62
	input keyboard text [PASSWORD]
else
    echo "KEYGUARD_NOTSHOWING"
fi
```

adb -s push unlock.sh /data/local/tmp/unlock
adb -s shell chmod 0700 /data/local/tmp/unlock
adb -s shell /data/local/tmp/unlock

Replace [PASSWORD] with your password
将 [PASSWORD] 替换为你的密码

**Comment by Rui1007** [comment]
I was able to resolve the issue using adb.
thanks a lot!

**Comment by e-t-l** [comment]
> I was able to resolve the issue using adb.

@Rui1007 How did you resolve the issue? Did you use the unlock.sh script in the previous comment, or some other way?

**Comment by Rui1007** [comment]
It was two years ago so my memory is a bit hazy, but I remember that I disabled the pattern lock with this way: https://nerdschalk.com/change-remove-lockscreen-pattern-pin-password-adb-android-oreo/
and I re-setting pin code. then you can use keyboard to unlock.
