### ISSUE TITLE
Add UI for changing launch commands

### ISSUE THREAD

**Issue by jakob30061** [Genymobile/scrcpy#4182]
There are several options launching scrcpy like "--turn-screen-off" or "--no-control". I often switch between them and always search in the terminal history.
Would be nice having a small UI for this. Like a small settings gear icon in the top right corner opening a small popover with basic settings.

I could try implement this feature, but I'm a beginner in C and especially in SDL (if I'm not mistaken this is used for rendering the window).
Is this feature wanted?

**Comment by CheerfulPianissimo** [comment]
Note that [QtScrcpy](https://github.com/barry-ran/QtScrcpy) exists

**Comment by jakob30061** [comment]
> Note that [QtScrcpy](https://github.com/barry-ran/QtScrcpy) exists

Oh I didn't know. Thank you

**Comment by rom1v** [comment]
Note that it is a separate project independant of scrcpy, which reimplements the features using Qt, it is not just an UI for scrcpy.
