### ISSUE TITLE
Scrcpy with two usb devices on remote host (more than one device/emulator)

### ISSUE THREAD

**Issue by FlashPlayer13** [Genymobile/scrcpy#4188]
I know that this problem is pretty old and there was lot of issues with it that was solved. But mine looks like new one as my enviropment is slighter different.
I have two PCs in local network. PC1 (with local ip 192.168.50.45) has two phones connected via usb and I want to connect with scrcpy from PC2 to both of this phones.
So I started `adb -a nodaemon server` on PC1 and can see device list from PC2. 
It looks like this (both phones has same model):
```
(usb)               p000000            device  Mi_A2
(usb)               p000001            device  Mi_A2
```

But when I try to connect with this command `scrcpy --tunnel-host=192.168.50.45 --serial=p000000` I get lot of same errors in a row (with different ports):
```
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27183, retrying on 27184
```

If I disconnect one phone from PC1 (only this change) - I can connect to another phone with same command as above without problem.
As you can see - in my case it doesn't help to write `--serial=p000000` as I still getting errors with two connected phones.

Any ideas what could be wrong?

**Comment by rom1v** [comment]
Don't use `--tunnel-port` in your case (it's not the adb server port), it's the port to communicate with the server via the tunnel). See https://github.com/Genymobile/scrcpy/blob/master/doc/tunnels.md#remote-adb-server for your use case.

**Comment by FlashPlayer13** [comment]
I am very sorry - I played with params and one of my attempts looks like jumped into this issue.
Long story short - in my tests I didn't use `--tunnel-port` param. I will edit first post to remove this param.

**Comment by rom1v** [comment]
How did you declare `ADB_SERVER_SOCKET`?

**Comment by FlashPlayer13** [comment]
Yes, I declared. Here is output after all commands (with two phones):
```
C:\scrcpy>set ADB_SERVER_SOCKET=tcp:192.168.50.45:5037

C:\scrcpy>adb devices
List of devices attached
p000000 device
p000001 device


C:\scrcpy>scrcpy --tunnel-host=192.168.50.45 --serial=p000000
scrcpy 2.1 <https://github.com/Genymobile/scrcpy>
INFO: Tunnel host/port is set, --force-adb-forward automatically enabled.
C:\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 5.5 MB/s (56955 bytes in 0.010s)
adb.exe: error: more than one device/emulator
ERROR: "adb forward" returned with value 1
WARN: Could not forward port 27183, retrying on 27184
.
.
.
```

But if I unplug one phone from PC1, same commands return this and all OK:
```
C:\scrcpy>set ADB_SERVER_SOCKET=tcp:192.168.50.45:5037

C:\scrcpy>adb devices
List of devices attached
p000000 device


C:\scrcpy>scrcpy --tunnel-host=192.168.50.45 --serial=p000000
scrcpy 2.1 <https://github.com/Genymobile/scrcpy>
INFO: Tunnel host/port is set, --force-adb-forward automatically enabled.
C:\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 85.0 MB/s (56955 bytes in 0.001s)
[server] INFO: Device: [Xiaomi] xiaomi Mi A2 (Android 9)
[server] WARN: Audio disabled: it is not supported before Android 11
INFO: Renderer: direct3d
WARN: Demuxer 'audio': stream explicitly disabled by the device
INFO: Texture: 1080x2160
```

**Comment by rom1v** [comment]
Once you see your 2 remote devices in the result of `adb devices`, what is the result of:

```
adb -s p000000 forward tcp:27183 localabstract:scrcpy
```

?

**Comment by FlashPlayer13** [comment]
Same error about more than one device. Here is a full output:

```
C:\scrcpy>set ADB_SERVER_SOCKET=tcp:192.168.50.45:5037

C:\scrcpy>adb devices
List of devices attached
p000000 device
p000001 device


C:\scrcpy>adb -s p000000 forward tcp:27183 localabstract:scrcpy
adb.exe: error: more than one device/emulator
```

**Comment by rom1v** [comment]
That's the problem. This result from adb is not expected.

**Comment by FlashPlayer13** [comment]
I tried `adb -s p000000 forward tcp:27183 localabstract:scrcpy` also with latest release (2.1.1) - same result. How can I help here to understand what is wrong? Any logging maybe?

**Comment by rom1v** [comment]
When you type an adb command directly, it's totally independant of scrcpy, so upgrading would change nothing.

I don't know why you get this error with two different devices having different serial numbers. Does it happen with other devices?

**Comment by FlashPlayer13** [comment]
> What about `adb -s p000000 shell`?

I am entering into shell. No errors here

**Comment by FlashPlayer13** [comment]
Fixed like was posted here: https://github.com/Genymobile/scrcpy/issues/3128
Thanks!

**Comment by rom1v** [comment]
:tada: (sorry, I did not remember)
