### ISSUE TITLE
Program Freezes With External Recording Devices

### ISSUE THREAD

**Issue by bruddakirby** [Genymobile/scrcpy#419]
I've tried recording the window via OBS, Bandicam, and Camtasia Studio and whenever I start the recording, the program just freezes and stops responding.

**Comment by rom1v** [comment]
I have no idea. It seemed to work though: https://www.reddit.com/r/OculusGo/comments/94yl4w/screen_casting_the_oculus_go_howto/

(also note that scrcpy may record the stream to a file)
