### ISSUE TITLE
windows: otg + tcpip = hid support

### ISSUE THREAD

**Issue by qwertykid** [Genymobile/scrcpy#4192]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist. edit: not hard enough.

**Is your feature request related to a problem? Please describe.**
On windows, the hid keyboard and mouse only works on otg mode.
Because you can only have one device at a time connected via usb on windows. (As said in the docs)

**Describe the solution you'd like**
I think, if you combine the tcpip feature, so the usb is not used.
And otg, so the keyboard and mouse connect.
it could have hid support, with lag, to windows!

**Describe alternatives you've considered**
You can recreate a similar effect, by:
1. open a console
2. run `scrcpy --otg` (you may need to use the `-s` flag)
3. when it runs, tab off
4. create another console window
5. In that window, connect to the phone wirelessly. (with the `wireless debugging` option in settings)
6. have the otg window next to the other window
7. click on the otg window
8. Have fun!

https://github.com/Genymobile/scrcpy/assets/64162703/c86af807-1159-480c-93c3-ee215cf7bb9d

**Additional context**

**Comment by rom1v** [comment]
Refs #4028 #4032 #4035

**Comment by qwertykid** [comment]
Just realized I should close this, as its a duplicate.
