### ISSUE TITLE
Scrcpy doesn't display tall screens properly

### ISSUE THREAD

**Issue by aluyama** [Genymobile/scrcpy#4195]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).
 (i searched for some keywords and there're many opened/closed issues then hard to read them all however i couldn't find any matching bug (bug label). Also, the bug exist on latest version so i guess its okey to open this issue)

**Environment**
 - OS: Ubuntu 22.04.2
 - scrcpy version: 2.1.1
 - installation method: https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md
 - device model: ZTE
 - Android version: 11
 
The bug exist on both scrcpy 1.21 and 2.1.1

**Describe the bug**

I tested following devices and scrcpy display them properly

(a) Huawei - Android 5.1 (EMUI 3.1)
Size: 5.0 inches, 68.9 cm2 (~66.6% screen-to-body ratio)
Resolution: 720 x 1280 pixels, 16:9 ratio (~294 ppi density)

(b) ZTE - Android 11
Size: 6.09 inches, 91.0 cm2 (~80.0% screen-to-body ratio)
Resolution: 720 x 1560 pixels, 19.5:9 ratio (~282 ppi density)

I tested this device and scrcpy doesn't display it properly. I mean i can't see a part of bottom screen and display a top part for it but i still can tap and use bottom control buttons blindly.  ( | <  |  o  |  >  |)

(a) ZTE - Android 11
Size: 6.67 inches, 107.4 cm2 (~83.3% screen-to-body ratio)
Resolution: 1080 x 2400 pixels, 20:9 ratio (~395 ppi density)

Scrcpy

![image](https://github.com/Genymobile/scrcpy/assets/125848045/ef3978c2-05c4-4f02-a4e3-6a6cb034d6c4)

Actual (device screenshot)

![Screenshot_20230728_110950](https://github.com/Genymobile/scrcpy/assets/125848045/b122d966-b503-4980-bfd5-e72d2530e7db)

---

 **Other problem**
 
```
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 22.2.5-0ubuntu0.1~22.04.3
INFO: Trilinear filtering enabled
INFO: Texture: 1080x2400
ALSA lib pcm.c:8568:(snd_pcm_recover) underrun occurred
```
_note:  i didn't see this error message `ALSA lib pcm.c:8568:(snd_pcm_recover) underrun occurred` in scrcpy 1.21 so hope a solution for it too._

**Comment by rom1v** [comment]
It looks like a device encoder issue.

Does it happen with screenrecord:

```
adb shell screenrecord /sdcard/file.mp4
adb pull /sdcard/file.mp4
```

And with another [encoder](https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#encoder)?

**Comment by aluyama** [comment]
>Does it happen with screenrecord:

```
adb shell screenrecord /sdcard/file.mp4
adb pull /sdcard/file.mp4
```

Yes. but no issues with built-in android screen recorder.

>And with another [encoder](https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#encoder)?

Available encoders

```
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 1.4 MB/s (56995 bytes in 0.040s)
[server] INFO: List of video encoders:
    --video-codec=h264 --video-encoder='OMX.sprd.h264.encoder'
    --video-codec=h264 --video-encoder='c2.android.avc.encoder'
    --video-codec=h264 --video-encoder='OMX.google.h264.encoder'
[server] INFO: List of audio encoders:
    --audio-codec=opus --audio-encoder='c2.android.opus.encoder'
    --audio-codec=aac --audio-encoder='c2.android.aac.encoder'
    --audio-codec=aac --audio-encoder='OMX.google.aac.encoder'

```

I tested them all (3). The problem happens with `OMX.sprd.h264.encoder` and i can see the full screen with another two but scrcpy preview slow (1 sec or less delay), so that two encoders are useless to me. that's a new device so what should i do to fix / solve this?

**Comment by rom1v** [comment]
Does it happen with a lower resolution?

```
scrcpy -m1024
```

**Comment by aluyama** [comment]
Another problem; i forgot to say this in previous comments. After updated to 2.1.1; when i run the scrcpy command, i always see a white flash on the entire phone screen before appear the scrcpy window on the PC. If it doesn't make negative effect to the device with time, i can ignore it.

---

> Does it happen with a lower resolution?
> 
> ```
> scrcpy -m1024
> ```

Thanks. No, now no problem. I also tested 1280, 1560, 1920 and no problem too. If tried e.g. 2000, 2400 (device res.), 3840 then the problem comes. Note: but people don't know to try with different resolutions like this to solve the problem :(

I played with different resolution levels and now i have **New** problem. **I always need to turn off the screen before run scrcpy command** (default command or with any resolution levels). Otherwise, scrcpy window appear and disappear immediately with error message on the terminal.  I already restarted the phone several times and killed pc adb process but no luck. (Unfortunately, i can't restart the PC today)

```
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 22.2.5-0ubuntu0.1~22.04.3
INFO: Trilinear filtering enabled
INFO: Texture: 464x1024
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
ERROR: Could not open audio device: ALSA: Couldn't open audio device: Device or resource busy
ERROR: Demuxer error

```

Then, i plugged an another ZTE phone model and ran `scrcpy` command. the same thing appear for it. Today i plugged it for the first time after updated to scrcpy 2.1.1. So this is definitely a scrcpy bug then i can try to restart PC later and test or reinstall scrcpy

```
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
ERROR: Could not open audio device: ALSA: Couldn't open audio device: Device or resource busy
ERROR: Demuxer error
```

Meanwhile, i tested it with different resolution levels; 1024, 1280, 1560 (device res.), 1920, 2000, 2400, 3840 and i can see full screen properly with all

**Comment by rom1v** [comment]
> when i run the scrcpy command, i always see a white flash on the entire phone screen before appear the scrcpy window on the PC

This is probably a bug on the device.

> I also tested 1280, 1560, 1920 and no problem too. If tried e.g. 2000, 2400 (device res.), 3840 then the problem comes. Note: but people don't know to try with different resolutions like this to solve the problem :(

Sure, but this is a device bug. The encoder should fail if it does not support the resolution, it should not produce garbage. If it failed, scrcpy would fallback to a lower resolution automatically.

> ERROR: Could not open audio device: ALSA: Couldn't open audio device: Device or resource busy

This is an error on the client side (independent of the device). It comes from a limitation from ALSA, and I reported to SDL that alsa should maybe not have a higher priority than pipewire: https://github.com/libsdl-org/SDL/issues/7541

**Comment by aluyama** [comment]
>when i run the scrcpy command, i always see a white flash on the entire phone screen before appear the scrcpy window on the PC
>
>>This is probably a bug on the device.

I'm seeing this after updated to 2.1.1 (from 1.21)

---

Thank you. Now i can use scrcpy well with workrounds. So i can consider as my problems solved.

**Comment by rom1v** [comment]
>     when i run the scrcpy command, i always see a white flash on the entire phone screen before appear the scrcpy window on the PC

> I'm seeing this after updated to 2.1.1 (from 1.21)

Oh, that's the hacky workaround to make audio work on Android 11:

> For Android 11, you'll need to ensure that the device screen is unlocked when starting scrcpy. A fake popup will briefly appear to make the system think that the shell app is in the foreground. Without this, audio capture will fail.

https://github.com/Genymobile/scrcpy/blob/master/doc/audio.md

You should not have this with `scrcpy --no-audio`.
