### ISSUE TITLE
Lineage os no audio fowarding

### ISSUE THREAD

**Issue by FredericVincent0** [Genymobile/scrcpy#4196]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows 10]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [Windows release]
 - device model:SM-T813
 - Android version: [7.0 lineageos 20]

**Describe the bug**
Non audio forwarding

**Comment by rom1v** [comment]
What is the output in the console?

**Comment by FredericVincent0** [comment]
I dont know I can't, I should reinstall lineageos because I reverted to
stock firmware, it might take a while

Le ven. 28 juill. 2023, 12 h 26, Romain Vimont ***@***.***> a
écrit :

**Comment by FredericVincent0** [comment]
i will as soon as i get home it's either today or tomorrow

**Comment by FredericVincent0** [comment]
scrcpy 2.1.1 <https://github.com/Genymobile/scrcpy>
* daemon not running; starting now at tcp:5037
* daemon started successfully
INFO: ADB device found:
INFO:     -->   (usb)      313b513b057b64c8            device  SM_T813
C:\Users\fredericvincent\Documents\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 49.5 MB/s (56995 bytes in 0.001s)
[server] INFO: Device: [samsung] samsung SM-T813 (Android 13)
[server] ERROR: Could not create default audio encoder for opus
List of audio encoders:
    --audio-codec=aac --audio-encoder='OMX.google.aac.encoder'
[server] ERROR: Exception on thread Thread[audio-encoder,5,main]
java.lang.IllegalArgumentException: Failed to initialize audio/opus, error 0xfffffffe (NAME_NOT_FOUND)
        at android.media.MediaCodec.native_setup(Native Method)
        at android.media.MediaCodec.<init>(MediaCodec.java:2000)
        at android.media.MediaCodec.<init>(MediaCodec.java:1978)
        at android.media.MediaCodec.createEncoderByType(MediaCodec.java:1933)
        at com.genymobile.scrcpy.AudioEncoder.createMediaCodec(AudioEncoder.java:292)
        at com.genymobile.scrcpy.AudioEncoder.encode(AudioEncoder.java:184)
        at com.genymobile.scrcpy.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-AudioEncoder(AudioEncoder.java:124)
        at com.genymobile.scrcpy.AudioEncoder$$ExternalSyntheticLambda0.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:1012)
INFO: Renderer: direct3d
WARN: Demuxer 'audio': stream explicitly disabled by the device
INFO: Texture: 1536x2048

**Comment by FredericVincent0** [comment]
> Quelle est la sortie dans la console?

scrcpy 2.1.1 https://github.com/Genymobile/scrcpy

démon ne fonctionne pas ; à partir de maintenant à tcp:5037
le démon a démarré avec succès
INFO : périphérique ADB trouvé :
INFO : --> (usb) périphérique 313b513b057b64c8 SM_T813
C:\Users\fredericvincent\Documents\scrcpy\scrcpy-server : 1 fichier poussé, 0 ignoré. 49,5 Mo/s (56995 octets en 0,001 s)
[serveur] INFO : Appareil : [samsung] samsung SM-T813 (Android 13)
[serveur] ERREUR : Impossible de créer l'encodeur audio par défaut pour opus
Liste des encodeurs audio :
--audio -codec=aac --audio-encoder='OMX.google.aac.encoder'
[serveur] ERREUR : Exception sur le thread Thread[audio-encoder,5,main]
java.lang.IllegalArgumentException : Échec de l'initialisation de l'audio/opus, erreur 0xfffffffe (NAME_NOT_FOUND)
sur android.media.MediaCodec.native_setup (méthode native)
sur android.media.MediaCodec.(MediaCodec.java:2000)
sur android.media.MediaCodec.(MediaCodec.java:1978)
sur android.media.MediaCodec.createEncoderByType(MediaCodec.java:1933)
sur com.genymobile.scrcpy. AudioEncoder.createMediaCodec(AudioEncoder.java:292)
sur com.genymobile.scrcpy.AudioEncoder.encode(AudioEncoder.java:184)
sur com.genymobile.scrcpy.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-AudioEncoder(AudioEncoder .java:124)
sur com.genymobile.scrcpy.AudioEncoder$$ExternalSyntheticLambda0.run(Source inconnue : 4)
sur java.lang.Thread.run(Thread.java:1012)
INFO : Renderer : direct3d
WARN : Demuxer 'audio' : flux explicitement désactivé par l'appareil
INFO : Texture : 1536x2048

**Comment by FredericVincent0** [comment]
hello SORRY for the inconvenience I finally succeeded for the audio it was scrcpy --audio-codec=opus # default that did not work but scrcpy --audio-codec=aac to work I will close this issue ok
