### ISSUE TITLE
Mouse Side buttons have weird behavior(I have a mouse with 6 side buttons)

### ISSUE THREAD

**Issue by Reveriii** [Genymobile/scrcpy#4202]
- [] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows 10 22H2 ]
 - scrcpy version: [2.1.1]
 - installation method: [Windows Release]
 - device model:SMA536E
 - Android version: [Android 13,One UI 5.1]

**Describe the bug**
I have a mouse that has 6 side buttons. ![image](https://github.com/Genymobile/scrcpy/assets/132616188/003aaf9a-eb54-4627-a4dd-75ef717b9225)
Starting from the bottom and right to left as seen in the picture the first button works properly and opens the multitask view as intended. The middle button on the bottom rotates the screen by 90 degrees,(see console output when i press it)
![image](https://github.com/Genymobile/scrcpy/assets/132616188/a69faef3-9343-433d-a69e-3a4449363b94)
The last button does nothing. The top row of buttons all highlight an app when pressed, multiple presses does not do anything further.
![image](https://github.com/Genymobile/scrcpy/assets/132616188/d7ab402d-7000-4400-9845-436d9317b18e)
Ive also tested with a normal two side button mouse and it works properly. Is there any way to remap the buttons or limit my side buttons to only 2 in scrcpy so i can access the notifications tray?

**Comment by rom1v** [comment]
> The middle button on the bottom rotates the screen by 90 degrees

It probably generates Alt+right. Try `scrcpy -Vverbose` to get more info.

> Is there any way to remap the buttons or limit my side buttons to only 2 in scrcpy so i can access the notifications tray?

If the mouse generates specific keyboard combinations, it should be configured in the mouse driver.

**Comment by Reveriii** [comment]
> > The middle button on the bottom rotates the screen by 90 degrees
> 
> It probably generates Alt+right. Try `scrcpy -Vverbose` to get more info.
> 
> > Is there any way to remap the buttons or limit my side buttons to only 2 in scrcpy so i can access the notifications tray?
> 
> If the mouse generates specific keyboard combinations, it should be configured in the mouse driver.

Yep it generates Alt+right, for some reason the logitech software defaulted to Alt+right for forwards so it worked in other places like browsers and windows explorer,  but kept the back button as a system back button, it works just fine now. thank you so much for the help, Im really loving the app!
