### ISSUE TITLE
Hear audio and mic at the same time

### ISSUE THREAD

**Issue by Gamusok** [Genymobile/scrcpy#4206]
Is it possible to route both the audio and the mic?
When I use  --audio-source=mic the audio playback stops, and I would like to have both
Thanks!

**Comment by rom1v** [comment]
Nope, scrcpy only exposes 1 audio stream.

If you want both, as a workaround, you can run two instances of scrcpy:

```bash
# for device audio and video
scrcpy
```

```bash
# for microphone
scrcpy --no-video --audio-source=mic
```

(of course, that way, you can't record everything in a single file with `--record=file.mkv`)

**Comment by Gamusok** [comment]
Oh yeah!! Good workaround, thanks a lot for the quick reply! It works like charm...

**Comment by Gamusok** [comment]
Isn't it possible to do some work around like this to have audio in both, my computer and my android device?

**Comment by rom1v** [comment]
> Isn't it possible to do some work around like this to have audio in both

Nope :/ https://github.com/Genymobile/scrcpy/issues/3875#issuecomment-1488138834

**Comment by Gamusok** [comment]
This is very strange, because actually that's the default behavior in the Oculus casting.
When you open it, if you activate sound in the computer, then the sound is in both devices, and you can turn up/down the volume independently in both devices. 

Therefore having sound in both devices doesn't seem contradictory. Or is the Oculus casting using a very different approach?

The  problem is that in my project I am using the Passthrough vision, which only scrcpy allows...

**Comment by bombshit** [comment]
I want to ask me that after the wired connection to the mobile phone, it can transmit sound normally, but as long as the mobile phone uses the microphone, the computer cannot hear the sound, is it the same problem as the landlord, does anyone know how to solve it，using v2.0

**Comment by bombshit** [comment]
I want to ask me that after the wired connection to the mobile phone, it can transmit sound normally, but as long as the mobile phone uses the microphone, the computer cannot hear the sound, is it the same problem as the landlord, does anyone know how to solve it

**Comment by bombshit** [comment]
I want to ask that after the wired connection to the mobile phone, it can transmit sound normally, but as long as the mobile phone uses the microphone, the computer cannot hear the sound, is it the same problem as the landlord, does anyone know how to solve it
