### ISSUE TITLE
in --no-video mode, scrcpy not terminate when disconnected

### ISSUE THREAD

**Issue by chieonol** [Genymobile/scrcpy#4207]
- [v] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [v] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: 2.1.1
 - installation method: release
 - device model: google pixel 2 xl, lg wing (and every devices)
 - Android version: 13

**Describe the bug**

If scrcpy has video, I can see terminal's process has adb(not showing scrcpy). And it terminates when disconnected so i can start a new one.
But in --no-video , terminal has adb and scrcpy. And only adb terminates when disconnected, scrcpy steel alive and terminal shows it still running, I cannot start new one until I've stop(ctrl+c or kill process in task manager)
I think scrcpy must be terminated too when adb terminated.

[ when ]                     video     video-disconneted      no-video           no-video-disconneted
processes                  adb               -                            adb,scrcpy        scrcpy           
can i use console?      no               yes                          no                    no

**Comment by chieonol** [comment]
I forgot images.
![화면 캡처 2023-08-01 174714](https://github.com/Genymobile/scrcpy/assets/93561822/7bfc7ea0-ee4a-4dda-9f19-408f883e5b30)
![화면 캡처 2023-08-01 174818](https://github.com/Genymobile/scrcpy/assets/93561822/f90800aa-333d-41a1-a1e3-83590d56974a)
![화면 캡처 2023-08-01 174945](https://github.com/Genymobile/scrcpy/assets/93561822/2ade879d-2d48-4427-ba8d-7c07d47ccfe7)
![화면 캡처 2023-08-01 175058](https://github.com/Genymobile/scrcpy/assets/93561822/2bb94a9c-5bab-42c8-847e-8a109a2eeb38)
![화면 캡처 2023-08-01 180008](https://github.com/Genymobile/scrcpy/assets/93561822/c4744e38-dd5d-4c8a-baf8-bf5a46830a68)

**Comment by rom1v** [comment]
Thank you for your report.

Fixed by 0983f0a194db154823842a4728f3c2bb5a3b1cc3.
