### ISSUE TITLE
Keeping screen off (alt+O) when scrcpy is closed?

### ISSUE THREAD

**Issue by Udgarth** [Genymobile/scrcpy#4209]
Is there an option to keep the screen turned off when scrcpy is closed in version 2.1.1? Right now, as soon as I close scrcpy, it would turn the phone's physical screen back on by default. 

On a previous version I could close scrcpy and have the phone running while the screen stays turned off, and it wouldn't turn on until I open scrcpy again to turn the screen back on (by turning the power off then on again). Unfortunately my SSD just died, so I cannot check which version I was running before.

**Comment by rom1v** [comment]
> Is there an option to keep the screen turned off when scrcpy is closed in version 2.1.1?

https://github.com/Genymobile/scrcpy/issues/4116#issuecomment-1608888544
https://github.com/Genymobile/scrcpy/issues/1764
https://github.com/Genymobile/scrcpy/issues/2888

**Comment by Udgarth** [comment]
Thanks! --no-cleanup worked like a charm.
