### ISSUE TITLE
#4183

### ISSUE THREAD

**Issue by didirodi** [Genymobile/scrcpy#4216]
Can't solve the error about #4183?
I desperately need the ability to crop the screen into zone 1 and zone 2 and run both screens at the same time.
However, when running both screens at the same time, one screen turns black and is not visible.
There is no error in Android 13, but an error occurs in version 12.

**Comment by rom1v** [comment]
Please do not duplicate your own issues.

I have no solution for this, the behaviornis decided by the device, not scrcpy.
