### ISSUE TITLE
audio not forwarded 

### ISSUE THREAD

**Issue by laoshaw** [Genymobile/scrcpy#4217]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
   ubuntu 22.04
 - scrcpy version: [e.g. 1.12.1]
   1.21
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
   apt install scrcpy
 - device model:
   pixel3
 - Android version: [e.g. 10]
  android 12

**Describe the bug**

just run scrcpy on ubuntu and I can use android freely on ubuntu including video playing, except audio stays on the phone(not forwarded)

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
* daemon not running; starting now at tcp:5037
* daemon started successfully
/usr/share/scrcpy/scrcpy-server: 1 file pushed. 0.9 MB/s (39473 bytes in 0.043s)
[server] INFO: Device: Google Pixel 3 (Android 12)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6.0 NVIDIA 525.125.06
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x2160
[server] INFO: Device clipboard set
INFO: Device clipboard copied
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
You need the latest version: https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md#latest-version

**Comment by rom1v** [comment]
> tried release scrcpy 2.1.1 but got error: java.lang.IllegalArgumentException: The server version (2.1) does not match the client (2.1.1), seems like a 2.1.1 release bug?

Read this comment wihich explains why the `install_release.sh` script may not be included in the tag, but only one commit after: https://github.com/Genymobile/scrcpy/issues/4098#issuecomment-1600332180

It is intended to be run from `master`.
