### ISSUE TITLE
How would one communicate to scrcpy server and send ultrafast input/sendevents in c++

### ISSUE THREAD

**Issue by GPlays09** [Genymobile/scrcpy#4218]
I would like to know how would one going about making c++ program to interface with scrcpy's interface link to mobile phone and use it to send inputs/ touch events as fast as the server allows.
And if there is any source / example material it would be great. 

adb shell input work really slow, and scrcpy's touch throughput works really fast, that is why I am asking.
I have already seen this https://github.com/Genymobile/scrcpy/issues/231#issuecomment-414111753 it said that you send event data to server with eventually control_event_serialize, but where does it write to?

**Comment by rom1v** [comment]
You should read https://github.com/Genymobile/scrcpy/blob/master/doc/develop.md#protocol
