### ISSUE TITLE
Drag and drop not working 

### ISSUE THREAD

**Issue by TneezyGH** [Genymobile/scrcpy#422]
![scrcpy_2019-02-04_18-45-27](https://user-images.githubusercontent.com/47330809/52227802-d9815e00-28b0-11e9-8974-c2c37abfb787.png)
When i try to upload a file, it doesn't work, even if i remove spaces. The error is on the screenshot ^^

Any solution ? (i'm in v. **1.6**)

**Comment by TneezyGH** [comment]
It works with th efile without space. How to do this with a file with a space

**Comment by TneezyGH** [comment]
I finally removed the  '''è''', and it is working 😄 
But is there a way for the manipulation to work with directories with accents ?

**Comment by rom1v** [comment]
> But is there a way for the manipulation to work with directories with accents ?

Yes, there is a way :wink:

It's now fixed on `dev` branch.
