### ISSUE TITLE
Demuxer 'audio': stream disabled due to missing decoder

### ISSUE THREAD

**Issue by eltrevii** [Genymobile/scrcpy#4225]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: windows
 - scrcpy version: latest (2.1.1)
 - installation method: windows release
 - device model: xiaomi 11 lite 5g ne (2109119DG)
 - Android version: 13

**Describe the bug**
it says `Demuxer 'audio': stream disabled due to missing decoder`

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
scrcpy 2.1.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)              d0dcfa95            device  2109119DG
C:\path\scrcpy-server: 1 file pushed, 0 skipped. 150.5 MB/s (56995 bytes in 0.000s)
[server] INFO: Device: [Xiaomi] Xiaomi 2109119DG (Android 13)
INFO: Renderer: direct3d
WARN: [FFmpeg] Could not find codec parameters for stream 0 (Video: png, none): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
ERROR: Could not find image decoder
WARN: Could not load icon
INFO: Texture: 464x1024
ERROR: Demuxer 'audio': stream disabled due to missing decoder
ERROR: Demuxer error
WARN: Killing the server...
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by eltrevii** [comment]
nvm it was because of some av*.dll files that were probably old so yea

**Comment by linkedbyte** [comment]
解决问题用的ffmpeg哪个版本呢？

**Comment by eltrevii** [comment]
@linkedbyte english please i dont understand
