### ISSUE TITLE
Only shows a single frozen image at start

### ISSUE THREAD

**Issue by quintesse** [Genymobile/scrcpy#423]
Using my Pixel 2 I can get scrcpy to start and connect to my phone. The mirrored image of my phone pops up on my Windows 10 PC and ... then nothing. The image is just static and won't ever change from that first image when the window opened.

For mouse clicks something similar happens: it registers only a single click and none thereafter.

(Btw, the mouse click always seems to register as a long-press, no matter how fast I click)

**Comment by rom1v** [comment]
That's unexpected (of course).

Could you try your device in another computer or OS, and another device on the same computer?

**Comment by quintesse** [comment]
Just tried it with a Samsung Galaxy (Android 7) and there it works. Tested my Pixel 2 (Android 9) on another Windows 10 PC and there it works :-/

Rebooted the PC and unfortunately that also didn't solve the issue.

Btw, I saw on the other PC that closing the mirror window also closed the console window, on my PC it stays open so I'm guessing it hangs somewhere. Any debugging I can do?

**Comment by rom1v** [comment]
What if you use a lower definition or bitrate?

    scrcpy -m800 -b2M

**Comment by user897943** [comment]
I replaced SDL2.dll in 1.8 with the one from 1.3 and it's working perfectly now.

**Comment by quintesse** [comment]
Just retested with 1.8 and everything works perfectly now. Closing. Thanks!
