### ISSUE TITLE
How to solve the problem of a black screen when entering a password (for security reasons)

### ISSUE THREAD

**Issue by xiezy1** [Genymobile/scrcpy#4230]
Hello, the developer of 'scrcpy' may experience a blank screen when entering a password while using scrcpy (for security reasons). How can I solve this problem

**Comment by hamadzidani** [comment]
did you solve it?

**Comment by Focsani** [comment]
I would disable that password, I have the same 'issue' it's a privacy-like screenshot for some of the apps.

**Comment by hamadzidani** [comment]
you do nothing about it except if you manage to recompile the application in question and remove "secure_flag" from it, then install it again.
