### ISSUE TITLE
scrcpy --window-title

### ISSUE THREAD

**Issue by BomjNarik** [Genymobile/scrcpy#4239]
Hello

I doesn't found info about can i using some default string for scrcpy.

I mean i want to change the standart name of scrcpy window to *name of device*+*serial of device*.
So, have scrcpy some variable values for this or i need got needed values from device via ADB and will make a batch or etc. ?  

For example i want to use this command:
scrcpy  --window-title="my device name" "serial number"

Thanks for your answer in advance

**Comment by rom1v** [comment]
Currently, `--window-title` only accepts a raw string (without variable replacement).

I considered implementing this feature a long tile ago, but some values are known on the server side, some others on the client side, and it provided only little value over a simple script, so it's not implemented.

**Comment by BomjNarik** [comment]
Ok
Thank you
So i will be use some ADB before scrcpy to use with got variables

This request can be closed
