### ISSUE TITLE
The screen of mirroring is blurred when the device screen turned off at recent tasks page.

### ISSUE THREAD

**Issue by StareStarrySky** [Genymobile/scrcpy#4242]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: 2.1.1
 - installation method: Windows release, scrcpy-win64-v2.1.1.zip
 - device model: Redmi_Note_4X
 - Android version: 7.0

**Describe the bug**
1. Using a data cable to connect to a computer;
2. Double click the file `scrcpy-noconsole.vbs`;
3. Go to the recent tasks page by operating the phone;
4. Using `Alt` + `O` to turn off the phone screen;
5. Right click to back to desktop in the mirroring.
Then, blurred.

**Comment by rom1v** [comment]
Could you post a screenshot?

**Comment by StareStarrySky** [comment]
@rom1v thanks for reply.

this is the result image.
Reopen the application can avoid this problem.

hmm, I don't think the severity of this problem is high~

![20230819121134759](https://github.com/Genymobile/scrcpy/assets/30280143/7a201a82-03e5-4ec0-aa27-0ccd81f76525)

**Comment by rom1v** [comment]
This is only when you turn the screen off (with <kbd>Alt</kbd>+<kbd>o</kbd> or `--turn-screen-off`), right?

Probably similar to #836: when the screen is off, some apps may "optimize" to avoid rendering. Here, it seems your system does not render (and just encodes garbage).

I guess that also happens with another [encoder](https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#encoder)?

This is device-specific, if you try with another device it should probably work…

**Comment by StareStarrySky** [comment]
Yes, only when turn the screen off at recent tasks. There's no problem with the screen constantly turning on or off.

The system version is locked for this device. I've try another phone([server] INFO: Device: [Xiaomi] Redmi 23013RK75C (Android 13)), and it's alright. So, it's broken due to the recent tasks(a part of this system) maybe.

For the problematic phone, other encoders also happens: 

```
E:\scrcpy>scrcpy.exe --list-encoders
scrcpy 2.1.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)          5984dea20304            device  Redmi_Note_4X
E:\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 60.4 MB/s (56995 bytes in 0.001s)
[server] INFO: List of video encoders:
    --video-codec=h264 --video-encoder='OMX.qcom.video.encoder.avc'
    --video-codec=h264 --video-encoder='OMX.google.h264.encoder'
    --video-codec=h265 --video-encoder='OMX.qcom.video.encoder.hevc'
[server] INFO: List of audio encoders:
    --audio-codec=aac --audio-encoder='OMX.google.aac.encoder'
```
