### ISSUE TITLE
Is there any chance to execute the screen mirroring among another frameworks??

### ISSUE THREAD

**Issue by oAmarilha** [Genymobile/scrcpy#4249]
Hi there, how are you doing??
I'm a tester from Brazil and I'm doing tests automated in airtest (python framework) and I would like if the screen could be share in my pc while the test is executed, but airtest gets the instance from adb and when I started scrcpy the framework losts the instance and can't continue the test, is there any method to work around this and share the screen belong the test??

**Comment by rom1v** [comment]
I don't know the context, but:

> when I started scrcpy the framework losts the instance

Your "framework" is probably using an adb version different from that of scrcpy. Use the same version everywhere and adb instances won't kill each other.

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#conflicts-between-adb-versions
