### ISSUE TITLE
Little Freeze every 3 sec.

### ISSUE THREAD

**Issue by Nounours54** [Genymobile/scrcpy#425]
Hello,
first thank you for this great app !

My issue is that with the lastest version (1.5 and 1.6) I have some little freeze (only in the app, not on my smartphone). Every around 3 sec. there is a freeze.
So, I came back on the 1.3 version and it works fine.

Smartphone Honor 8 Pro (DUK-L09) with Android 8.0, and Windows 10 Pro.

Sorry for my english ^^

**Comment by rom1v** [comment]
> My issue is that with the lastest version (1.5 and 1.6)
> So, I came back on the 1.3 version and it works fine.

What about version 1.4? (this may help to find the issue)

What if you take 1.6 release, then replace all DLL files by those from 1.3?

Also display FPS in the console (Ctrl+i in the _scrcpy_ window).

**Comment by rom1v** [comment]
@Nounours54 ?

**Comment by Nounours54** [comment]
Sorry, i don't come here very often.
I tried with the 1.8 release, there is the same problem.
So, I replaced all DLL files (1.3 --> 1.8) and it works very well.
Should I have to do this for every new version ?

**Comment by rom1v** [comment]
To know if the problem comes from from libav or SDL, could you replace only `SDL2.dll` or replace all `av*.dll`+`swresample-3.dll` separately, please?

**Comment by Nounours54** [comment]
Ok.
I only replaced the SDL2.dll and it works.

**Comment by rom1v** [comment]
OK, so this is due a change between SDL 2.0.8 and 2.0.9. So it should also work with SDL2.dll from scrcpy v1.4, right? (SDL 2.0.9 is in the Windows release since scrcpy v1.5)

**Comment by Nounours54** [comment]
Yes it is

**Comment by user897943** [comment]
Same thing happening with me, I did not try to replace anything but the app just does not work - screen will take ages to come up, then it's frozen whe it does.

**Comment by rom1v** [comment]
It may be related to https://discourse.libsdl.org/t/unstable-frame-rate-unexpectedly/25783.

A workaround to make it work with SDL 2.0.9 could be:

```diff
diff --git a/app/src/scrcpy.c b/app/src/scrcpy.c
index 61b3f8d..3cdcedc 100644
--- a/app/src/scrcpy.c
+++ b/app/src/scrcpy.c
@@ -44,7 +44,9 @@ static struct input_manager input_manager = {
 // init SDL and set appropriate hints
 static bool
 sdl_init_and_configure(bool display) {
-    uint32_t flags = display ? SDL_INIT_VIDEO : SDL_INIT_EVENTS;
+    uint32_t flags = display
+                   ? SDL_INIT_VIDEO | SDL_INIT_JOYSTICK
+                   : SDL_INIT_EVENTS;
     if (SDL_Init(flags)) {
         LOGC("Could not initialize SDL: %s", SDL_GetError());
         return false;
```
