### ISSUE TITLE
how to full screen?  ~@^_^@~

### ISSUE THREAD

**Issue by hold88888888** [Genymobile/scrcpy#4269]
If it can be full screen. That will be better~~ (suggestion)
 (￣▽￣)～■干杯
(｡･ω･｡)ﾉ♡

**Comment by hold88888888** [comment]
![屏幕截图 2023-08-31 121117](https://github.com/Genymobile/scrcpy/assets/105548184/d12c2aa7-140d-4792-b8ad-e94e47f5de1d)

**Comment by hold88888888** [comment]
There is still a white line on the top . And the screen is surrounded by black space.

**Comment by hold88888888** [comment]
There is still a white line on the top . And the screen is surrounded by black area.

**Comment by hold88888888** [comment]
![屏幕截图 2023-08-31 121117](https://github.com/Genymobile/scrcpy/assets/105548184/69647875-25a8-433e-8d72-de80af862c5c)

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/doc/window.md#fullscreen

**Comment by hold88888888** [comment]
> https://github.com/Genymobile/scrcpy/blob/master/doc/window.md#fullscreen

I found a new problem now.( •̥́ ˍ •̀ू )
When the width-height turns 2336-1080(full screen) to 1080-2336(portrait screen). It exit full screen and come back to desktop.Then i watch landscape mode
，it can't be the full screen that i opened before.(It stay still，window pattern)(๑ó﹏ò๑)

**Comment by hold88888888** [comment]
> https://github.com/Genymobile/scrcpy/blob/master/doc/window.md#fullscreen

I found a new problem now.( •̥́ ˍ •̀ू )
When the width-height turns 2336-1080(full screen) to  1080-2336(portrait screen).

 It exit full screen (automatically) and come back to desktop.

Then i watch landscape mode，it can't be the full screen that i opened before.(It stay still，window pattern)(๑ó﹏ò๑)

**Comment by hold88888888** [comment]
> https://github.com/Genymobile/scrcpy/blob/master/doc/window.md#fullscreen

I find a new problem now.( •̥́ ˍ •̀ू )
When the width-height turns 2336-1080(full screen) to 1080-2336(portrait screen).

It exit full screen (automatically) and come back to desktop.

Then i watch landscape mode，it can't be the full screen that i opened before.(It stay still，window pattern)(๑ó﹏ò๑)

**Comment by hold88888888** [comment]
> https://github.com/Genymobile/scrcpy/blob/master/doc/window.md#fullscreen

I find a new problem now.( •̥́ ˍ •̀ू )
When the width-height turns 2336-1080(full screen) to 1080-2336(portrait screen).

It exit full screen (automatically) and come back to desktop.(portrait screen).

Then i watch landscape mode，it can't be the full screen that i opened before.(It stay still，window pattern)(๑ó﹏ò๑)

**Comment by hold88888888** [comment]
scrcpy-win64-v2.1.1
I didn't express  clearly before.
If i use `scrcpy --fullscreen` , it won't eixt fullscreen

![屏幕截图 2023-09-01 093320](https://github.com/Genymobile/scrcpy/assets/105548184/7e9d40b7-4814-4877-9d67-ff3bc618d6de)

**Comment by hold88888888** [comment]
but the width and height was not really "full screen"

**Comment by hold88888888** [comment]
scrcpy-win64-v2.1.1
I didn't express clearly before.
If I use `scrcpy --fullscreen` , it won't eixt fullscreen
but the width and height was not really "full screen"

![屏幕截图 2023-09-01 093320](https://github.com/Genymobile/scrcpy/assets/105548184/295f1789-31e0-49a6-b1b5-f250e60ef3b8)

**Comment by hold88888888** [comment]
Then I changed the command , I used `scrcpy --window-width=2336 --window-height=1080`
This is "really fullscreen" , but it will exit automatically when I switch between landscape and vertical screens

**Comment by hold88888888** [comment]
![屏幕截图 2023-09-01 094321](https://github.com/Genymobile/scrcpy/assets/105548184/f65e9162-e3e9-4439-aea0-2f168205e3f0)
![屏幕截图 2023-09-01 094538](https://github.com/Genymobile/scrcpy/assets/105548184/a7d61332-a09f-4c29-96af-740235d9f968)

**Comment by hold88888888** [comment]
It's understandable that it will exit  (because I changed the size).
But I can't solve the problem.

**Comment by rom1v** [comment]
> but the width and height was not really "full screen"

One of {width, height} takes the whole screen:
 - there are black bars on your device screen (which are mirrored) in one dimension
 - there are black bars added on the computer to maintain the device screen aspect ratio
 
> Then I changed the command , I used scrcpy --window-width=2336 --window-height=1080
> This is "really fullscreen" , but it will exit automatically when I switch between landscape and vertical screens

This probably just makes your window larger than your computer screen. What is your computer resolution?

What you want is [cropping](https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#crop):
 - to remove the black bars which are present on the device,
 - to get a final size having the same aspect ratio as your computer screen.

**Comment by hold88888888** [comment]
> > but the width and height was not really "full screen"
> 
> One of {width, height} takes the whole screen:
>  - there are black bars on your device screen (which are mirrored) in one dimension
>  - there are black bars added on the computer to maintain the device screen aspect ratio
>  
> > Then I changed the command , I used scrcpy --window-width=2336 --window-height=1080
> > This is "really fullscreen" , but it will exit automatically when I switch between landscape and vertical screens
> 
> This probably just makes your window larger than your computer screen. What is your computer resolution?
> 
> What you want is [cropping](https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#crop):
>  - to remove the black bars which are present on the device,
>  - to get a final size having the same aspect ratio as your computer screen.

Thank you for the professional instructions(￣▽￣)～■干杯
I will try it soon(because i'm on the train( •̥́ ˍ •̀ू ))

**Comment by hold88888888** [comment]
> > but the width and height was not really "full screen"
> 
> One of {width, height} takes the whole screen:
>  - there are black bars on your device screen (which are mirrored) in one dimension
>  - there are black bars added on the computer to maintain the device screen aspect ratio
>  
> > Then I changed the command , I used scrcpy --window-width=2336 --window-height=1080
> > This is "really fullscreen" , but it will exit automatically when I switch between landscape and vertical screens
> 
> This probably just makes your window larger than your computer screen. What is your computer resolution?
> 
> What you want is [cropping](https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#crop):
>  - to remove the black bars which are present on the device,
>  - to get a final size having the same aspect ratio as your computer screen.


Thank you for the professional instructions(￣▽￣)～■干杯
I will try it soon(because i'm on the train
( •̥́ ˍ •̀ू ))

**Comment by hold88888888** [comment]
> > but the width and height was not really "full screen"
> 
> One of {width, height} takes the whole screen:
>  - there are black bars on your device screen (which are mirrored) in one dimension
>  - there are black bars added on the computer to maintain the device screen aspect ratio
>  
> > Then I changed the command , I used scrcpy --window-width=2336 --window-height=1080
> > This is "really fullscreen" , but it will exit automatically when I switch between landscape and vertical screens
> 
> This probably just makes your window larger than your computer screen. What is your computer resolution?
> 
> What you want is [cropping](https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#crop):
>  - to remove the black bars which are present on the device,
>  - to get a final size having the same aspect ratio as your computer screen.


Thank you for the professional instructions(￣▽￣)～■干杯
I will try it soon(because i'm on the train
( •̥́ ˍ •̀ू ))
But i'm convinced that it'll be solved after following the instructions
(•̤̀ᵕ•̤́๑)ᵒᵏᵎᵎᵎᵎ

**Comment by 1049731887** [comment]
Alt+g

**Comment by 1049731887** [comment]
Alt+f

**Comment by hold88888888** [comment]
> Alt+f

谢了老兄，你给的快捷键非常好用~~
不过问题仍然存在，泪目。

接下来我把整个流程给你看一下

首先 `scrcpy --window-width=2336 --window-height=1080` 可以铺满屏幕，如下图所示


![屏幕截图 2023-09-04 122921](https://github.com/Genymobile/scrcpy/assets/105548184/71a68e48-7550-4652-a025-432610748e76)

然后比如想换个视频看（B站），一变到竖屏，就自动退出了，此时power shell如下图所示


![屏幕截图 2023-09-04 123033](https://github.com/Genymobile/scrcpy/assets/105548184/c4f4ef55-93b9-4880-97c7-d6ce6c117e57)

我再切换到横屏，视频就会变成下方这样

![屏幕截图 2023-09-04 123053](https://github.com/Genymobile/scrcpy/assets/105548184/c214b486-bb49-4910-8bbf-bd9861a87edf)

然后我采用你给出的快捷键 ALT+F ，于是可以全屏，但无法铺满屏幕，如下图所示

![屏幕截图 2023-09-04 123120](https://github.com/Genymobile/scrcpy/assets/105548184/0b948bc5-9948-4f06-bdf5-33cc30b66716)

**Comment by hold88888888** [comment]
![-6dbafa73325a0048](https://github.com/Genymobile/scrcpy/assets/105548184/fc98426d-ce9a-459e-bdf0-97a2bf18bf16)

**Comment by 1049731887** [comment]
我windows系统刷抖音横屏正常哩
Linux系统横屏也正常，我觉得应该是设置了分辨率导致的，可以试试不设分辨率

**Comment by 1049731887** [comment]
黑边是正常的在手机里播放这个视频本来就会有黑边，除非视频大小与手机屏幕比例一样，而且和电脑比例一样才不会出现黑边

**Comment by 1049731887** [comment]
@hold88888888

**Comment by hold88888888** [comment]
> 黑边是正常的在手机里播放这个视频本来就会有黑边，除非视频大小与手机屏幕比例一样，而且和电脑比例一样才不会出现黑边

@1049731887 

（我举的这个例子不是很明显，换其他视频就很明显了，泪目）
（不过，你说的也是正确的）

不设置分辨率，仅全屏，如下图所示

![屏幕截图 2023-09-05 183826](https://github.com/Genymobile/scrcpy/assets/105548184/77696041-a2c4-4d91-a0b7-c8b620b73d32)

设置分辨率之后，如下图所示

![屏幕截图 2023-09-05 184131](https://github.com/Genymobile/scrcpy/assets/105548184/7f3a9884-2d62-4402-9432-8677b915a2c7)

不过我发现，我设置的分辨率确实太大了，才搞出了“铺满全屏”的样子，因为我发现第二张图片可以看到右边贴着边的联想管家加速球 @_@，这意味着并不是fullscreen，所以换到竖屏会“回到桌面”是可以理解的了

**Comment by hold88888888** [comment]
@1049731887
 
算是解决了吧哈哈谢谢

**Comment by hold88888888** [comment]
@rom1v 

problem solved

method 1：
 
`scrcpy -f`

method 2:

After setting the resolution ， not switch between landscape mode and Vertical mode

method 3：

If "exiting to desktop"(although it was actually at desktop before exiting ，looked like full screen)，close the program and open it again

**Comment by hold88888888** [comment]
@rom1v 

Problem solved

Method 1：

 `scrcpy -f`

Method 2:

After setting the resolution ， not switch between landscape mode and Vertical mode

Method 3：

If "exiting to desktop"(although it was actually at desktop before exiting ，looked like full screen)，close the program and open it again

**Comment by hold88888888** [comment]
@rom1v

Problem solved

Method 1：

 `scrcpy -f`

Method 2:

After setting the resolution ， don't  switch between landscape mode and Vertical mode

Method 3：

If "exiting to desktop"(although it was actually at desktop before exiting ，looked like full screen)，close the program and open it again

**Comment by bloodykheeng** [comment]
scrcpy -f works well
