### ISSUE TITLE
Black Brick

### ISSUE THREAD

**Issue by gitlisk** [Genymobile/scrcpy#4270]
**Environment**
 - OS: [Pop OS]
 - scrcpy version: [2.1.1]
 - installation method: [forgot]
 - device model: Samsung S21ultra
 - Android version: [latest?]

**The device is stuck with a black screen.**

Original command:

```
scrcpy  --turn-screen-off --no-audio --no-downsize-on-error --shortcut-mod=lalt --disable-screensaver  --tcpip=<device.ip>:5555
```

It worked fine.
CTRL+C in the terminal.

```
scrcpy 2.1.1 <https://github.com/Genymobile/scrcpy>
INFO: Connecting to device.ip:5555...
INFO: Connected to device.ip:5555
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 0.5 MB/s (56995 bytes in 0.121s)
[server] INFO: Device: [samsung] samsung SM-G998B (Android 13)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6.0 NVIDIA 535.104.05
INFO: Trilinear filtering enabled
INFO: Texture: 1080x2400
[server] INFO: Device screen turned off
[server] INFO: Forcing screen off
^C⏎                
````

Device remained black.
The device is still on. I connected it to a windows pc and it is being recognized.

How do i restore the screen functionality?
I can not connect to device via ip anymore

```
adb connect device.ip:5555
failed to connect to 'device.ip:5555': Connection refused
```

**Comment by rom1v** [comment]
Looks that a bug in the device ROM (scrcpy just requests to change the power mode to turn the screen off and on, but the device system performs the action).

> I can not connect to device via ip anymore

It looks like the system crashed then.

If pressing <kbd>POWER</kbd> to turn it off/on does not work, you should reboot.

> The device is still on. I connected it to a windows pc and it is being recognized.

If you plug it over USB, is it detected by `adb devices`? If so, try to run `scrcpy`. Or execute `adb reboot`.

If it does not work, turn the power on by pressing <kbd>POWER</kbd> for 5 seconds, if it stlil does not work, press <kbd>POWER</kbd> for 30 seconds.

**Comment by gitlisk** [comment]
I think the device restarts with a black screen...

'''
adb devices
* daemon not running; starting now at tcp:5037
* daemon started successfully
List of devices attached
R5CR60XB4CV	device
'''
mod+o 
mod+shift+o
still leaves the screen black
'''
scrcpy --shortcut-mod=lalt
scrcpy 2.1.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  R5CR60XB4CV                     device  SM_G998B
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 5.4 MB/s (56995 bytes in 0.010s)
[server] INFO: Device: [samsung] samsung SM-G998B (Android 13)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6.0 NVIDIA 535.104.05
INFO: Trilinear filtering enabled
INFO: Texture: 1080x2400
[server] INFO: Device screen turned off
[server] INFO: Device screen turned on
'''

**Comment by rom1v** [comment]
> Is it possible to boot up a phone without a functional screen and use it on the pc?

Oh, the screen is broken? So when you say "black screen", it's just in the mirroring window? (the physical device screen is black anyway, right?)

**Comment by gitlisk** [comment]
I have no idea if the screen is broken or not. I was working but when it stopped working I also dropped the phone and both problems occurred.

The physical device is black.
I managed to open the emergency menu while streaming to the pc but I can't enter pin or open stuff since it goes black

**Comment by rom1v** [comment]
OK, so if the mirroring is black, it's due to views with "secure flag" that cannot be mirrored since Android 12 (#36 #2129).

I guess your lock screen has this "secure flag" enabled.

**Comment by gitlisk** [comment]
Ok. Thanks for the support. 
I assume there is no way the app can hold my screen hostage even after a reboot right? 
Triggering  mod+o should turn the screen on if it would work right?
You think I can conclude that the fall damaged the screen somehow, 
its just weird that it went black and nothing is happening, 
have not seen a screen behave like this, 
usually it takes a lot more to completely break them.

**Comment by gitlisk** [comment]
It was the screen that broke. 
I am sorry for the trouble. 
Thanks for the software.
Hit me up if ya ever find yourself in Berlin.
