### ISSUE TITLE
The server version (2.1) does not match the client (2.1.1)

### ISSUE THREAD

**Issue by Igao3Mil** [Genymobile/scrcpy#4276]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Linux Mint Cinnamon
 - scrcpy version: 2.1.1
 - installation method: manual build
 - device model: is that really needed?
 - Android version: 10

**Describe the bug**
The server version in the `install_release.sh` file on the [2.1.1 release](https://github.com/Genymobile/scrcpy/releases/tag/v2.1.1)'s source code is set to use **scrcpy-server-v2.1** instead of **scrcpy-server-v2.1.1**, what makes scrcpy say this when you run:

```[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: The server version (2.1) does not match the client (2.1.1)
	at com.genymobile.scrcpy.Options.parse(Options.java:188)
	at com.genymobile.scrcpy.Server.main(Server.java:178)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338)
ERROR: Server connection failed
```

Simply changing the URL and the SHA256 solves the issue. It was just a little annoying.

**Comment by rom1v** [comment]
You must not execute `install_release.sh` from a tag, but one commit after (or `master`, which is the intended use case). See https://github.com/Genymobile/scrcpy/issues/4098#issuecomment-1600332180

**Comment by Igao3Mil** [comment]
Ah, so I should just download the master instead of the source code from the releases?

**Comment by rom1v** [comment]
Yes, `master` is basically the latest release (the development branch is `dev`).

**Comment by Igao3Mil** [comment]
Ok, thank you!
