### ISSUE TITLE
pre-build scrcpy not working

### ISSUE THREAD

**Issue by hannenuryazbahar** [Genymobile/scrcpy#428]
![ekran alintisi](https://user-images.githubusercontent.com/15361556/52370732-b7c8d800-2a64-11e9-9552-beec3c6cfd40.PNG)

when i try run scrcpy it does not start

**Comment by rom1v** [comment]
Does it work with a lower definitiin?

    scrcpy -m800

**Comment by hannenuryazbahar** [comment]
its working thanks..
