### ISSUE TITLE
Color looks too bright and lost details

### ISSUE THREAD

**Issue by GOGOsu** [Genymobile/scrcpy#4282]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10 22H2
 - scrcpy version: 2.1.1
 - installation method: Windows x64 zip from releases
 - device model: Xiaomi Redmi 12 Turbo
 - Android version: 13

**Describe the bug**
As description. When I use scrcpy the screen is too white and lost details. I tried using with -m 800 or --render-driver=software or without them, but nothing helps.

Terminal outputs seems normal:
```
C:\Users\GOGOsu\Downloads\scrcpy-win64-v2.1.1> ./scrcpy --render-driver=software
scrcpy 2.1.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)              a6***3c            device  23049RAD8C
C:\Users\GOGOsu\Downloads\scrcpy-win64-v2.1.1\scrcpy-serve... file pushed, 0 skipped. 69.5 MB/s (56995 bytes in 0.001s)
[server] INFO: Device: [Xiaomi] Redmi 23049RAD8C (Android 13)
INFO: Renderer: software
INFO: Texture: 1080x2400
```

The following screenshot shows the difference between scrcpy and adb exec-out screencap:
![image](https://github.com/Genymobile/scrcpy/assets/31916454/96802d4f-2ff1-4a7e-8126-04f56047ad10)

**Comment by rom1v** [comment]
How did you take the screenshot on the right?

How is the resulting image if you capture with:

```
adb exec-out screencap -p > file.png
```
?

Does it happen with all [encoders](https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#encoder)?

And if you increase the bitrate (`scrcpy -b20M`)?

(don't use "software" rendering)

Also related: #638

**Comment by GOGOsu** [comment]
1. the right image is captured by `adb shell screencap /sdcard/test.png; adb pull /sdcard/test.png`
2. the `adb exec-out screencap -p > file.png` produce a correct-looking file like the above command.
3. the screenrecord looks too white, like in issue.
4. with some encoders, see below.
5. increase the bitrate do not help.


encoders returned by `scrcpy --list-encoders`:
```
[server] INFO: List of video encoders:
    --video-codec=h264 --video-encoder='c2.qti.avc.encoder'
    --video-codec=h264 --video-encoder='OMX.qcom.video.encoder.avc'
    --video-codec=h264 --video-encoder='c2.android.avc.encoder'
    --video-codec=h264 --video-encoder='OMX.google.h264.encoder'
    --video-codec=h265 --video-encoder='c2.qti.hevc.encoder'
    --video-codec=h265 --video-encoder='OMX.qcom.video.encoder.hevc'
    --video-codec=h265 --video-encoder='c2.qti.hevc.encoder.cq'
    --video-codec=h265 --video-encoder='OMX.qcom.video.encoder.hevc.cq'
    --video-codec=h265 --video-encoder='c2.android.hevc.encoder'
[server] INFO: List of audio encoders:
    --audio-codec=opus --audio-encoder='c2.android.opus.encoder'
    --audio-codec=aac --audio-encoder='c2.android.aac.encoder'
    --audio-codec=aac --audio-encoder='OMX.google.aac.encoder'
```

all video encoder containing `qti` or `qcom` will produce abnormal color
the remaining 3 encoder (`c2.android.avc.encoder`, `OMX.google.h264.encoder`, `c2.android.hevc.encoder`) produce correct color, but with significant lag & jelly-like scrolling (even if -b20M / -b40M)

**Comment by rom1v** [comment]
> The screenrecord looks too white, like in issue.

Ok, this is a capture issue on your device then.

You could check if you have some "color enhancement" applied in your device settings that might confuse the capture.

**Comment by GOGOsu** [comment]
Thank you for your reply! I will try later and update the thread when I get some usable information.

**Comment by GOGOsu** [comment]
> I have the same problem, have you solved it?

Sadly, no. I tried everything in my phone's color settings, but no luck.

**Comment by GOGOsu** [comment]
It looks good with the fixes. so I'll close this issue.
