### ISSUE TITLE
video hangs. Sound, keyboard, mouse and clipboard (both ways) work 

### ISSUE THREAD

**Issue by mcDandy** [Genymobile/scrcpy#4298]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...] windows 11
 - scrcpy version: [e.g. 1.12.1] 2.1.1
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...] Windows release
 - device model: Pixel 6 pro
 - Android version: [e.g. 10] Android 14 (UPB5.230623.009)

**Describe the bug**
Screen mirror got stuck showing a screen at least 1 min after connection established. I was moving with mouse at the time. I was testing mouse, keyboard, clipboard and sound before.

On errors, please provide the output of the console (and `adb logcat` if relevant).

I think logcat output will be usefull. 
[logafterhang.log](https://github.com/Genymobile/scrcpy/files/12643079/logafterhang.log)

```
scrcpy 2.1.1 <https://github.com/Genymobile/scrcpy>
* daemon not running; starting now at tcp:5037
* daemon started successfully
INFO: ADB device found:
INFO:     -->   (usb)        1B181FDEE004KP            device  Pixel_6_Pro
D:\Users\Daniel Martinek\Downloads\scrcpy-win64-v2.0\scrcp... file pushed, 0 skipped. 33.7 MB/s (56995 bytes in 0.002s)
[server] INFO: Device: [Google] google Pixel 6 Pro (Android 14)
INFO: Renderer: direct3d
INFO: Texture: 1440x3120
INFO: Device clipboard copied
INFO: Device clipboard copied
[server] INFO: Device clipboard set
[server] WARN: Could not inject char u+0161
[server] WARN: Could not inject char u+0161
INFO: Device clipboard copied
INFO: Device clipboard copied
[server] INFO: Device clipboard set
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
Probably an encoder issue on the device.

Try with another [encoder](https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#encoder) or a lower [resolution](https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#bit-rate).

**Comment by mcDandy** [comment]
It looks that worked.
