### ISSUE TITLE
Allow to connect via Wifi, using Root

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Genymobile/scrcpy#43]
In case the device isn't connected via USB , the PC app could ask for IP, while the device is running one of the available apps for rooted devices, that opens adb via wifi.

Alternatively, you could make a helper app on Android itself, which would scan a QR code on the PC screen, so that each would find the other, and they will get connected.

**Comment by rom1v** [comment]
> In case the device isn't connected via USB , the PC app could ask for IP, while the device is running one of the available apps for rooted devices, that opens adb via wifi.

See https://github.com/Genymobile/scrcpy/issues/5

> you could make a helper app on Android itself

Too much work for no real benefit IMO.

**Comment by AndroidDeveloperLB** [comment]
I don't think it's a lot of work, especially compared to what was done on this project.

**Comment by chid** [comment]
This probably can be closed now that v1.1 has been released, see https://www.genymotion.com/blog/open-source-project-scrcpy-now-works-wirelessly/

**Comment by AndroidDeveloperLB** [comment]
@chid The request was for rooted devices.
Suppose I use one of the third party apps to connect via adb, will it also work?

**Comment by AndroidDeveloperLB** [comment]
Can you do it this way:
Connect via USB. Run PC app, and then via the PC app, let the device run adb to connect via Wifi, and the PC app will automatically connect to it when disconnected from USB 
?
