### ISSUE TITLE
After installing the KB5030211 patch, keyboard input is not working

### ISSUE THREAD

**Issue by shiqianwei0508** [Genymobile/scrcpy#4301]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: `Windows10 LTSC`
 - scrcpy version: `2.1.1`
 - installation method: `Windows Portable`
 - device model:
 - Android version: `13`

**Describe the bug**

After my system automatically installed the `KB5030211` patch, I couldn't input anything using the keyboard when I was  controling my Android phone with scrcpy. There were no logs in the terminal, as if scrcpy didn't receive any keyboard input from me at all.

> Note: The keyboard input was working fine before installing this patch. And after uninstalling the patch, the keyboard input was also back to normal.

```
None output in the terminal ! Nothing!
```

**Comment by rom1v** [comment]
Try with:

```
scrcpy -Vverbose
```

to get more logs about input events.

**Comment by shiqianwei0508** [comment]
Sorry, I do not want to reinstall the patch. After I remove the patch, everything is ok.
