### ISSUE TITLE
after updating my brew i am having issue with php

### ISSUE THREAD

**Issue by ekpotosammuel** [Genymobile/scrcpy#4305]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: macOS Catalina
 - brew version: Homebrew 4.1.12-2-g1f80e82
 - installation method: brew
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**
I can't access or install new PHP on my machine.

php -v                               
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicuio.72.dylib
  Referenced from: /usr/local/bin/php
  Reason: image not found
[1]    29627 abort      php -v

this is the error I get while trying to install PHP

Error: php: Failed to download resource "aom--homebrew-bus_qcif_15fps.y4m"
Failure while executing; `/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.12-2-g1f80e82\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.7\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://media.xiph.org/video/derf/y4m/bus_qcif_15fps.y4m` exited with 7. Here's the output:
curl: (7) Failed to connect to media.xiph.org port 443: Connection refused

**Comment by rom1v** [comment]
Wrong repo. You should report to homebrew.
