### ISSUE TITLE
Is it possible to correctly feed swipe events?

### ISSUE THREAD

**Issue by amosbird** [Genymobile/scrcpy#433]
There are cases when neither scrollling nor arrow keys work, such as navigating though the desktop of MIUI or switching to the prev/next video of tiktok. Is there any reliable way to generate swipe left/up/down/right events using scrcpy?

**Comment by rom1v** [comment]
A swipe is just a serie of mouse motion events with left click down, which should be correctly generated.

What's the problem with these apps? Could you provide a video or something to explain the problem?

**Comment by amosbird** [comment]
It's for better usability. https://la.wentropy.com/0fuM.webm     It's very cumbersome to swipe via mouse, trackpoint,  or trackpad

**Comment by amosbird** [comment]
it's actually not trivial. Some trial and error tests are needed.  https://la.wentropy.com/6Dz3
