### ISSUE TITLE
`mod`+`shift`+`o` cannot make the screen on

### ISSUE THREAD

**Issue by ktrNozomi** [Genymobile/scrcpy#4331]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: v2.1.1
 - installation method: Windows release
 - device model: LIO-AL00
 - Android version: HarmonyOS 4.0.0

**Describe the bug**

See the picture:

<img width="623" alt="Snipaste_2023-10-05_12-00-13" src="https://github.com/Genymobile/scrcpy/assets/86712470/930c8c55-1d22-441d-8571-ac1e1f2706b8">

```
scrcpy 2.1.1 <https://github.com/Genymobile/scrcpy>
INFO: Connecting to 192.168.1.101:5555...
INFO: Connected to 192.168.1.101:5555
C:\Users\user\.local\bin\scrcpy\scrcpy-...ped. 94.9 MB/s (56995 bytes in 0.001s)
[server] INFO: Device: [HUAWEI] HUAWEI LIO-AL00 (Android 12)
INFO: Renderer: direct3d
INFO: Texture: 1176x2400
[server] INFO: Device screen turned off
[server] INFO: Device screen turned on
[server] WARN: Could not inject char u+4e2d
WARN: Killing the server...
```

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/issues/3461#issuecomment-1223204907

**Comment by ktrNozomi** [comment]
> [#3461 (comment)](https://github.com/Genymobile/scrcpy/issues/3461#issuecomment-1223204907)

Thanks a lot!
