### ISSUE TITLE
Is it possible to see the size of recorded file while screen recording is happening?

### ISSUE THREAD

**Issue by mahaju** [Genymobile/scrcpy#4333]
I am screen recording my android device connected via usb using the following command in cmd:  

scrcpy --no-audio --record=file.mp4 

This file shows up in Windows explorer as 0 byte so it looks like its only saved after all recording is complete.

I am screen recording for a long duration. Is it possible to see what the file size would be currently, while it is being recorded? Or just an estimate is also fine. Is there any way to do this?

**Comment by rom1v** [comment]
There was a bug in scrcpy 2.0 which caused the file to be written at the end. Use the latest version (2.1.1).

**Comment by mahaju** [comment]
@rom1v  I am using 2.1.1 64-bit [scrcpy-win64-v2.1.1.zip](https://github.com/Genymobile/scrcpy/releases/download/v2.1.1/scrcpy-win64-v2.1.1.zip) (64-bit)

**Comment by rom1v** [comment]
> This file shows up in Windows explorer as 0 byte so it looks like its only saved after all recording is complete.

It is expected that it remains at 0 for few seconds, but then it should increase.

Even after 1 minute (and after you pressed F5 in your file browser to refresh), it remains at 0?

**Comment by mahaju** [comment]
@rom1v yes. Increases only after scrcpy is closed (ctrl+c), Arfe you using same 64 bit version?
Windows:
Edition	Windows 10 Pro
Version	22H2
OS build	19045.3448
Experience	Windows Feature Experience Pack 1000.19044.1000.0
