### ISSUE TITLE
Android 14: No Method getInternalDisplayToken

### ISSUE THREAD

**Issue by Reginer** [Genymobile/scrcpy#4335]
Android 14 android.view.SurfaceControl no method  getInternalDisplayToken .

https://github.com/Genymobile/scrcpy/blob/1ee46970e373ea3c34c3d9b632fef34982d7a52b/server/src/main/java/com/genymobile/scrcpy/wrappers/SurfaceControl.java#L96

**Comment by Reginer** [comment]
AOSP android.view.SurfaceControl  

  https://cs.android.com/android/platform/superproject/+/android-14.0.0_r2:frameworks/base/core/java/android/view/SurfaceControl.java

**Comment by Reginer** [comment]
Maybe 
```
import com.android.server.display.DisplayControl

DisplayControl.getPhysicalDisplayToken(physicalDisplayId) 
```

**Comment by rom1v** [comment]
See https://github.com/Genymobile/scrcpy/issues/3784#issuecomment-1748362800 and following comments.

**Comment by Reginer** [comment]
Don't close the issue yet . 
The problem real exist.

**Comment by rom1v** [comment]
> Don't close the issue yet .
> The problem real exist.

Sure, but there are already many issues about that in Android 14, I keep only one open.

**Comment by AndroidDeveloperLB** [comment]
@rom1v Yes, please have one post about Android 14 as it has plenty of issues, and also please put the link/s to the issue tracker, so that users here would consider to start them.

**Comment by rom1v** [comment]
It remains 3 scrcpy features broken in Android 14:
 - **turn screen off** is tracked by #3927
 - **crop** and **lock video orientation** are tracked by #4011
