### ISSUE TITLE
scrcpy: error while loading shared libraries: libdav1d.so.6

### ISSUE THREAD

**Issue by swishkin** [Genymobile/scrcpy#4336]
- [ x ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ x ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Artix Linux
 - scrcpy version: 2.1.1
 - installation method: pacman
 - device model: OnePlus 7 Pro
 - Android version: 13

**Describe the bug**

I updated my system today, launching scrcpy now exits with this error:

```
scrcpy -S -d
scrcpy: error while loading shared libraries: libdav1d.so.6: cannot open shared object file: No such file or directory

```

The same error was encountered in issue #3543, but after reinstalling scrcpy and dav1d packages, the error persists. Then I tried uninstalling scrcpy and installing (a manual reinstall, for whatever it's worth), but it had no impact on the issue. Uninstalling dav1d would break other dependent packages, so I wasn't sure if I could safely do that.

I verified with `locate libdav1d` that libdav1d is installed, but it looks like the version (7) is newer than what scrcpy is looking for (6).

```
...
/usr/lib/libdav1d.so
/usr/lib/libdav1d.so.7
/usr/lib/libdav1d.so.7.0.0
...
```

Is it possible to update scrcpy to look for the new version of the library? Would that break something, meaning I'll need to downgrade libdav1d to continue using scrcpy?

**Comment by rom1v** [comment]
This is a problem with your ffmpeg build, which looks for the wrong .so for dav1d. Try to reinstall/rebuild ffmpeg.

**Comment by swishkin** [comment]
Looks like you were correct. So, I've had ffmpeg-obs, which is required by obs-studio-tytan652. I installed obs-studio, replacing obs-studio-tytan652, and then replaced ffmpeg-obs with ffmpeg, and now both scrcpy and OBS work normally.
