### ISSUE TITLE
how to add an arabic language?

### ISSUE THREAD

**Issue by ahmedessa2002** [Genymobile/scrcpy#4340]
I need to add my language to write it from keyboard

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#special-characters-do-not-work

**Comment by DRSDavidSoft** [comment]
Ditto for persian keyboard as well 😂

**Comment by rom1v** [comment]
Try UHID keyboard: https://github.com/Genymobile/scrcpy/blob/master/doc/keyboard.md#physical-keyboard-simulation
