### ISSUE TITLE
Support for Meta Quest 3 with angled source

### ISSUE THREAD

**Issue by rolandwellinger** [Genymobile/scrcpy#4345]
As Meta Quest 1 & 2 are perfectly supported with this nice software. The Quest 3 brings a new challenge. Because the source screens are angled, the cropped section of the whole ist no leveled at the output stream. So we need to not just crop but also rotate the capturing section. I hope this can be done in a future update. Keep it up. And thanks

**Comment by ArtificiallyAndrew** [comment]
Using the source files, I have been able to isolate the code blocks for rotating the screens and added a few functions for Quest 3 & Pro rotation. However, I need to compile the code using MSYS2 as per the SCRCPY documentation. I have little experience using MSYS2 and haven't had time to figure it out.   

If somebody has experience using MSYS2 and has time to compile some code, let me know. I'd be happy to share a Quest 3 version of SCRCPY.

**Comment by rom1v** [comment]
Please test #5455 and the new `--angle` option.
