### ISSUE TITLE
Works on one phone but not on another phone

### ISSUE THREAD

**Issue by LanTenDragon** [Genymobile/scrcpy#435]
When I try using in on my main phone Redmi Note 2 with LineageOS, it shows this error 
![videostream](https://user-images.githubusercontent.com/43511642/53066244-d9689b80-3509-11e9-8a10-dea5b541553f.png)

But when I tried with my secondary phone Xperia ZR also with LineageOS, scrcpy is working just fine.

**Comment by rom1v** [comment]
What if you use a lower definition?

    scrcpy -m800

**Comment by npes87184** [comment]
The similar problem happens again and again. I recommend to do something for better user experience and reduce the number of the same issues as well (like the case of missing adb in the past).
For example, maybe we can catch exception and try lower definition automatically. After it, give a warning.

**Comment by HDragonHR** [comment]
Using 
> scrcpy -m800

still results in the same error.

Just making a wild guess here but is it because some phone do not have/support H264 encoders?

**Comment by rom1v** [comment]
> because some phone do not have/support H264 encoders?

Maybe.
