### ISSUE TITLE
Always on top for Mac OS

### ISSUE THREAD

**Issue by mikescamell** [Genymobile/scrcpy#436]
I really like using scrcpy and was excited to see the always on top feature added. But I believe this is just for Windows or Linux? It doesn't work on Mojave on my Mac at least. It would be great if this could be added.

**Comment by rom1v** [comment]
Indeed, it seems only implemented for X11 and Windows in SDL ([`src/video/x11/SDL_x11window.c`](https://hg.libsdl.org/SDL/file/6f0eb21dd7d1/src/video/x11/SDL_x11window.c#l154) and [`src/video/windows/SDL_windowswindow.c`](https://hg.libsdl.org/SDL/file/6f0eb21dd7d1/src/video/windows/SDL_windowswindow.c#l154)).

You should open a bug on [LibSDL](https://bugzilla.libsdl.org/), since _scrcpy_ just sets the flag.

**Comment by mikescamell** [comment]
Would the bug be something along the lines of "Allow always on top on Mac OS" like that I've asked here?

**Comment by npes87184** [comment]
> Would the bug be something along the lines of "Allow always on top on Mac OS" like that I've asked here?

Yes, for more detail. You can specify that the flag `SDL_WINDOW_ALWAYS_ON_TOP` doesn't apply to MacOS.

**Comment by gabrielformiga** [comment]
In case you still want this you can build sdl from my fork:
https://github.com/gabrielformiga/SDL-mirror/tree/mac_window_always_top

**Comment by rom1v** [comment]
Did you propose a patch to SDL upstream?

**Comment by gabrielformiga** [comment]
Not yet, but I'm gonna propose.

**Comment by gabrielformiga** [comment]
Just in case you want to track this:
https://bugzilla.libsdl.org/show_bug.cgi?id=4809

**Comment by rom1v** [comment]
Thank you :+1:

**Comment by hacker1024** [comment]
This has been merged, but always-on-top isn't working for me with 1.11 on Catalina...

https://github.com/spurious/SDL-mirror/commit/1c8dffa9b2fe89e3d15014b1994c21a0bbfca773

**Comment by rom1v** [comment]
@hacker1024 probably for the next release of SDL?

**Comment by hacker1024** [comment]
Oh, right

**Comment by hacker1024** [comment]
I just built with the master branch of sdl2 and can confirm that the patch works.

**Comment by gabrielformiga** [comment]
I think it's gonna be available on 2.0.12.
