### ISSUE TITLE
ERROR: Could not initialize SDL video: No available video device

### ISSUE THREAD

**Issue by hamadzidani** [Genymobile/scrcpy#4361]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Debian
 - scrcpy version: [e.g. 1.12.1]
 - installation method: Tried manual build, apt, snap
 - device model: Samsung A04
 - Android version: 13
 
**Describe the bug**
```
scrcpy 2.1.1 <https://github.com/Genymobile/scrcpy>
ERROR: Could not initialize SDL video: No available video device
ERROR: Could not start adb server
```
I have installed all the prerequisites as required from the `Readme.MD`, additionally, I installed dev libraries of `x11` and `Xorg`
The command `scrcpy --version` shows
```
scrcpy 2.1.1 <https://github.com/Genymobile/scrcpy>

Dependencies (compiled / linked):
 - SDL: 2.0.22 / 2.0.22
 - libavcodec: 58.134.100 / 58.134.100
 - libavformat: 58.76.100 / 58.76.100
 - libavutil: 56.70.100 / 56.70.100
 - libavdevice: 58.13.100 / 58.13.100
 - libusb: - / 1.0.25
```

I have set `scrcpy --display=0` because `scrcpy --list-displays` shows
```
scrcpy 2.1.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  R9WTA085GCE                     device  SM_A045F
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 3.2 MB/s (56995 bytes in 0.017s)
[server] INFO: List of displays:
    --display=0    (720x1600)
```
I also exported with `export SDL_VIDEODRIVER=x11` which again the same error occurred
```
scrcpy 2.1.1 <https://github.com/Genymobile/scrcpy>
ERROR: Could not initialize SDL video: x11 not available
ERROR: Could not start adb server
```
Not sure if this has anything to do with `adb` but `adb --version` is
```
Android Debug Bridge version 1.0.41
Version 28.0.2-debian
Installed as /usr/lib/android-sdk/platform-tools/adb
```
and `adb devices`
```
List of devices attached
R9WTA085GCE	device
```
I tried also over `tcpip`.

**Comment by rom1v** [comment]
From which graphical environment do you start scrcpy?

**Comment by hamadzidani** [comment]
> From which graphical environment do you start scrcpy?

from Guake Terminal

**Comment by rom1v** [comment]
```bash
echo $XDG_SESSION_TYPE
```

**Comment by hamadzidani** [comment]
`echo $XDG_SESSION_TYPE` returns `x11`.

**Comment by rom1v** [comment]
OK, and:

```bash
echo $DISPLAY
```

**Comment by hamadzidani** [comment]
`echo $DISPLAY` returns `:1`

**Comment by rom1v** [comment]
Is it correct?

```
export DISPLAY=:0
scrcpy
```

Does it work better?

**Comment by hamadzidani** [comment]
unfortunately not.

**Comment by hamadzidani** [comment]
```
scrcpy --list-displays
scrcpy 2.1.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     --> (tcpip)  192.168.1.4:5555                device  SM_A045F
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 1.2 MB/s (56995 bytes in 0.044s)
[server] INFO: List of displays:
    --display=0    (720x1600)
```
` --display=0` means the Android interface display while  
```
echo $DISPLAY
:1
```
is the display of the Linux system, right?

**Comment by rom1v** [comment]
Yes, `--display=` is the Android display.

Install xeyes, then run:
```bash
DISPLAY=:0 xeyes
DISPLAY=:1 xeyes
```

Does it work?

**Comment by hamadzidani** [comment]
the first command says `Error: Can't open display: :0` while the latter one opens a small window that has eyes dynamic drawing following the mouse.

**Comment by rom1v** [comment]
> while the latter one opens a small window that has eyes dynamic drawing following the mouse

OK, so `DISPLAY=:1` is correct.

Forget about `scrcpy --display=`, this has nothing to do with your X11 display (it's when you plug an external monitor on your Android device or when you configure a virtual display).

Create a file `sample.c` and compile it:

```c
#include <SDL2/SDL.h>

int main(void) {
    if (SDL_Init(SDL_INIT_VIDEO) == -1) {
        fprintf(stderr, "SDL error: %s\n", SDL_GetError());
        return 1;
    }

    SDL_Quit();

    printf("ok\n");
    return 0;
}
```

Compile it:
```bash
gcc sample.c -lSDL -o sample
```

And run it:
```bash
./sample
```

What is the result?

**Comment by hamadzidani** [comment]
`SDL error: No available video device`

**Comment by rom1v** [comment]
How did you install SDL2? Are you sure it is compiled with x11 support?

**Comment by hamadzidani** [comment]
`sudo apt install libsdl2-2.0.0 and libsdl2-dev`

**Comment by hamadzidani** [comment]
`sudo apt install libsdl2-2.0-0 and libsdl2-dev`. I followed [this answer and the first comment](https://stackoverflow.com/a/65339706/6177652) by recompiling [SDL2](https://wiki.libsdl.org/SDL2/Installation) from the source code. After that, I encountered an Audio driver problem but resolved it with `export SDL_AUDIODRIVER=dummy`.
