### ISSUE TITLE
How to get every frame on PC?

### ISSUE THREAD

**Issue by freedomofme** [Genymobile/scrcpy#437]
Thank you for your awesome project.

Now I want to get every frame of the video to do some image recognition.

As some issued mentioned before, there is no available interfaces currently. 

Could you tell me how to get the fame in source code level？

**Comment by rom1v** [comment]
I'd like to refactor a bit to split things more to reuse some parts more easily, but currently, it's not done.

So when a frame is available, the decoder pushes it and sends an event from its own thread: https://github.com/Genymobile/scrcpy/blob/v1.7/app/src/decoder.c#L232
The event is received in the main thread: https://github.com/Genymobile/scrcpy/blob/v1.7/app/src/scrcpy.c#L79
Which consumes the frame and render it here: https://github.com/Genymobile/scrcpy/blob/v1.7/app/src/screen.c#L261
