### ISSUE TITLE
(Linux) xdotool automated dragging does not work

### ISSUE THREAD

**Issue by SharkWipf** [Genymobile/scrcpy#4375]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Fedora 37
 - scrcpy version: 2.1.1
 - installation method: copr
 - device model: Pixel 8 Pro
 - Android version: 14

**Describe the bug**
While taps and drags manually work, and while taps through xdotool work fine too, drags through xdotool don't get captured by strcpy.
Mousedown events are properly captured, and manually moving the mouse after an xdotool mousedown properly drags, but doing an actual move with xdotool, while it holds the mousedown fine, don't get registered as a drag.

Steps to reproduce (Linux):
- Open up a Scrcpy session
- In a terminal, run `xdotool sleep 5 mousedown 1 mousemove_relative 250 0` and quickly move your mouse over the Scrcpy session to something you wish to drag (250px to the right, with this command)
- Observe how the mouse moves, but no drag is performed. If you move your mouse you'll notice it's still "sticky", still held down, and does perform dragging fine manually.
- Adding more sleeps/delays or more steps does not affect this outcome.

This might not be fixable Scrcpy-side if it relies on sdl for raw mouse input or something (though I don't know what options sdl actually offers for this), but I figured it'd be worth reporting anyway since I spent some time figuring out what was going on. It might save others some time.

**Comment by rom1v** [comment]
Please run with `scrcpy -Vverbose` to log the actual events.

**Comment by SharkWipf** [comment]
Curious, it does seem to be picking up the move (run with timeout as to not further contaminate the log, just ran the `xdotool sleep 5 mousedown 1 mousemove_relative 250 0`):

```
$ scrcpy -Vverbose -f --no-audio --time-limit 15
scrcpy 2.1.1 <https://github.com/Genymobile/scrcpy>
WARN: Could not disable minimize on focus loss
INFO: ADB device found:
INFO:     -->   (usb)  39201FDJG00796                  device  Pixel_8_Pro
DEBUG: Device serial: 39201FDJG00796
DEBUG: Using server: /usr/share/scrcpy/scrcpy-server
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 283.5 MB/s (56995 bytes in 0.000s)
[server] INFO: Device: [Google] google Pixel 8 Pro (Android 14)
DEBUG: Server connected
DEBUG: Starting controller thread
DEBUG: Starting receiver thread
[server] DEBUG: Using video encoder: 'c2.exynos.h264.encoder'
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 23.0.3
INFO: Trilinear filtering enabled
DEBUG: Using icon: /usr/share/icons/hicolor/256x256/apps/scrcpy.png
DEBUG: Demuxer 'video': starting thread
INFO: Texture: 1008x2240
DEBUG: Switched to fullscreen mode
VERBOSE: input: touch [id=finger] down position=205,1169 pressure=1.000000 action_button=000001 buttons=000001
VERBOSE: input: touch [id=finger] move position=723,1169 pressure=1.000000 action_button=000000 buttons=000001
INFO: Time limit reached
DEBUG: quit...
DEBUG: Demuxer 'video': end of frames
DEBUG: Receiver stopped
[server] DEBUG: Controller stopped
[server] DEBUG: Device message sender stopped
WARN: Killing the server...
DEBUG: Server disconnected
DEBUG: Server terminated
```

I also noticed that if I don't move and simply hold, it pops up the widget screen (on the home screen), but if I xdotool mousemove it even a little bit after holding, it doesn't pop up the widget selection screen. So the issue might be Android-side? Still weird, not sure why regular dragging works but programmatic dragging not.

**Comment by SharkWipf** [comment]
Update: If I start with small movements, it does work, so it is indeed an issue with how Android detects swipes.
Since it is not a Strcpy issue I'll close this issue now.
