### ISSUE TITLE
Open Android Apps

### ISSUE THREAD

**Issue by bendonahue99** [Genymobile/scrcpy#4378]
Can this be used to open Android apps (on an Nvidia Shield) remotely via a PC? 

Thanks

**Comment by rom1v** [comment]
You can control your Nvidia Shield remotely with mouse and keyboard, so you could probably open Android apps that way.

**Comment by bendonahue99** [comment]
Thanks, what I was really after is if there was a way I could send an ADB command to the shield to get it to launch a specific app. Not sure if this can be done a different way. I essentially want to be able to program a button on my streamdeck which will send the command (probably via a batch file) to open a different app on the Shield. 

scrcpy looked like it could be a good way to do that.

**Comment by rom1v** [comment]
adb is sufficient: https://stackoverflow.com/questions/4567904/how-to-start-an-application-using-android-adb-tools
