### ISSUE TITLE
scrcpy weird scaling, itstarts in 640x480 landscape?

### ISSUE THREAD

**Issue by Saurey** [Genymobile/scrcpy#438]
scrcpy-server.jar: 1 file pushed. 2.1 MB/s (19342 bytes in 0.009s)
INFO: Initial texture: 640x480

# disable auto rotation
adb shell settings put system accelerometer_rotation 0
# use custom rotation (0=portrait, 1=landscape)
adb shell settings put system user_rotation 1

playing around with these commands I was able to get it to go into portrait mode for a second when opening the Contacts app but it immediately goes landscape and contacts "unfortunately Contacts has closed" also tried to use the --crop with 1920:1080 settings but option was not recognised. Doing Ctrl + G does nothing but Ctrl + F does go fullscreen.

Runing on windows 10 and using Android 5 i've tried the latest version of scrcpy and 1.2 both same results.

Sorry if info is a bit non technical but if there is anything else i could provide that could help to solve this do let me know.

P.S Despite this issue i am having I know a lot of people love this tool so well done and keep up !!!

**Comment by rom1v** [comment]
Just to be sure I understand correctly, could you provide a screenshot of scrcpy when it starts?

The window is 640×480, but the actual content of the screen is portrait (and rotated 90°)?

**Comment by rom1v** [comment]
@Saurey ?
