### ISSUE TITLE
Bus error | Server connection failed

### ISSUE THREAD

**Issue by PikriNtr** [Genymobile/scrcpy#4385]
- [v ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [v ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10 Pro
 - scrcpy version: 2.0
 - installation method: Windows Release
 - device model: Infinix X670
 - Android version: 13

**Describe the bug**
Error when trying to connect either from server or usb method
```
C:\Users\PikriNtr\Downloads\scrcpy-win64-v2.0\scrcpy-win64-v2.0>scrcpy.exe
scrcpy 2.0 <https://github.com/Genymobile/scrcpy>
C:\Users\PikriNtr\Downloads\scrcpy-win64-v2.0\scrcpy-win64... file pushed, 0 skipped. 46.4 MB/s (52867 bytes in 0.001s)
Bus error
ERROR: Server connection failed
```

**Comment by PikriNtr** [comment]
btw already tried other version (still same)

**Comment by rom1v** [comment]
Does it happen with another device? (it's not clear if `Bus error` comes from the client or the server)

**Comment by PikriNtr** [comment]
> Does it happen with another device? (it's not clear if `Bus error` comes from the client or the server)

i cant tested, if i think more its just usb cable issue because i recently change my cable with the non original one

**Comment by PikriNtr** [comment]
.
