### ISSUE TITLE
The code cannot proceed because avcodec-60.dll,avformat-60.dll,avutil-58.dll,SDL2.dll was not found

### ISSUE THREAD

**Issue by BadriHilmi** [Genymobile/scrcpy#4389]
I tried reinstall the scrcpy  and still dont work. i install using winget

**Comment by rom1v** [comment]
Maybe scrcpy is not packaged correctly in Winget.

Try the official release.

**Comment by BadriHilmi** [comment]
probably later i try using chocolatey it work fine. might been winget problem

**Comment by Curio4** [comment]
I ran into the same problem, is there any solution how to fix it?

**Comment by rom1v** [comment]
Use the official release rather than the winget package.

**Comment by shinayser** [comment]
Same problem here

**Comment by b4shful** [comment]
Same here, seems like the winget release is messed up - I can see that it does indeed include all the required DLLs in the install directory, but the executable can't find them when you try to run it. 

It's worth noting that the usage instructions for the manual install on the repo say to run it by going into the install folder and opening a terminal in that folder, but whenever you install it via winget, it adds an alias for `scrcpy` which implies you should be able to call it from wherever. But my guess would be that this alias is not enough and you would need to change current working directory to the folder where scrcpy is first to make this work.

FWIW, when I run `where scrcpy` in Command Prompt I get:
```C:\Users\<username>\AppData\Local\Microsoft\WinGet\Links\scrcpy.exe```
Which is a symlink:
``` <SYMLINK>      scrcpy.exe [C:\Users\<username>\AppData\Local\Microsoft\WinGet\Packages\Genymobile.scrcpy_Microsoft.Winget.Source_8wekyb3d8bbwe\scrcpy-win64-v2.3.1\scrcpy.exe]```

If I open this location in Explorer and double click on that symlink, it actually works fine!

Leaving this here in case anyone takes a look at the winget package in the future.

**Comment by yume-chan** [comment]
It's caused by WinGet, see:

* #4027 
* https://github.com/microsoft/winget-pkgs/issues/107858
* https://github.com/microsoft/winget-cli/issues/2711

**Comment by wilks-ftf** [comment]
This is still a problem in April 2024 - please remove the suggestion to use winget from the setup / quickstarts if it does not work.

**Comment by rom1v** [comment]
> please remove the suggestion to use winget from the setup / quickstarts if it does not work.

Done: c27ab46efbcab0b9558a91e691d799ffef496c97

**Comment by aisgbnok** [comment]
This has been fixed for all versions of the [`Genymobile.scrcpy`](https://github.com/microsoft/winget-pkgs/tree/master/manifests/g/Genymobile/scrcpy) package in [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs), including the latest `3.1` release of scrcpy. scrcpy binaries (dlls, etc.) are now properly added to path through winget. This issue can be closed.
