### ISSUE TITLE
Display delay when play pubg

### ISSUE THREAD

**Issue by farhanramadhn** [Genymobile/scrcpy#439]
I get delay when playing pubg so what should I do? there might be a solution

**Comment by rom1v** [comment]
How much delay?

A lower definition could help:

    scrcpy -m 1024

**Comment by farhanramadhn** [comment]
around 2sec, I have set it to change but I got the slowmotion display

**Comment by rom1v** [comment]
2 seconds is huge. The expected delay is about 70~100ms.

If you use scrcpy over usb (not wifi), your computer is probably not able to decode the video stream in live (no hardware decoding and slow cpu).

If you press Ctrl+i, you'll get the measured framerate in the console. How many fps do you get?

**Comment by farhanramadhn** [comment]
average 30 fps + but somtimes i get frame drop

**Comment by rom1v** [comment]
And with even lower definition (even if it's unusable), lile `scrcpy -m 400`? In that case, the computer should be able to decode fast enough, so you should not get a huge delay. Is it the case?

**Comment by farhanramadhn** [comment]
Oke, better than before but i get small display

**Comment by rom1v** [comment]
Nothing scrcpy can do I guess. There is a performance issue either on the device or on the computer, so I'm closing.
