### ISSUE TITLE
Tools/Software To turn an Android Smartphone into a Laptop/PC external speaker/audio

### ISSUE THREAD

**Issue by SangkarJanda** [Genymobile/scrcpy#4394]
Are there any tools from Genymobile to turn an Android smartphone into external speakers/audio for a laptop/PC? The problem is, I've looked for software/tools on the internet and there aren't any. Meanwhile, my laptop/PC doesn't have an audio driver. Thank you 🙏🙏🙏

**Comment by rom1v** [comment]
Nope, sorry.

**Comment by SangkarJanda** [comment]
Ok
