### ISSUE TITLE
Unihertz Titan mirrors garbled screen with default encoder

### ISSUE THREAD

**Issue by runoono** [Genymobile/scrcpy#4399]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 windows 10, but this is probably os independent 
 - scrcpy version: [e.g. 1.12.1]
 v2.2
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 windows 10, ran out of a file
 - device model:
 Unihertz Titan Pocket, however had the same issue with the Unihertz Titan as well
 - Android version: [e.g. 10]
Android 13 with lineage os 
**Describe the bug**
the default video encoder outputs garbled video, 
![here's what the output looks like](https://github.com/Genymobile/scrcpy/assets/16387918/fdfe8613-81a9-4ceb-bd19-f5a0c4cc81cf)
the default encoder on this device is ``--video-encoder='OMX.MTK.VIDEO.ENCODER.AVC'`` changing it to any other encoder fixes this. I'm assuming this is happening to due to mediatek's encoder

this is the list of encoders I get when punch in ``--list-encoders``
```[server] INFO: Device: [Unihertz] Unihertz Titan_pocket (Android 13)
[server] INFO: List of video encoders:
    --video-codec=h264 --video-encoder='OMX.MTK.VIDEO.ENCODER.AVC'
    --video-codec=h264 --video-encoder='c2.android.avc.encoder'
    --video-codec=h264 --video-encoder='OMX.google.h264.encoder'
[server] INFO: List of audio encoders:
    --audio-codec=opus --audio-encoder='c2.android.opus.encoder'
    --audio-codec=aac --audio-encoder='c2.android.aac.encoder'
    --audio-codec=aac --audio-encoder='OMX.google.aac.encoder'```

**Comment by rom1v** [comment]
> the default encoder on this device is --video-encoder='OMX.MTK.VIDEO.ENCODER.AVC' changing it to any other encoder fixes this

OK, so it's an encoder issue on the device (maybe only at some resolution). Does the default encoder works with `scrcpy -m1024` for example?

Anyway, there's probably nothing scrcpy can do (just use another encoder).

**Comment by runoono** [comment]
> OK, so it's an encoder issue on the device (maybe only at some resolution). Does the default encoder works with `scrcpy -m1024` for example?

nope, no dice

> Anyway, there's probably nothing scrcpy can do (just use another encoder).

I guessed as much, I'm posting the issue more for the sake of documentation honestly, I tried a bunch of different solutions with similar issues, only though about trying this after I saw reading through ``--help`` command. 
I'm closing the issue, maybe I'll edit my main post to include the phrase "mediatek" as well, maybe it'll help someone else as well
