### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by qq2506389997** [Genymobile/scrcpy#4401]
Preface：
Hi man, I'm making this new request, it started when I found out that your original project doesn't have file upload functionality.

Purpose:
So I would like to add this little extension for file upload to your original project using python.

implementation strategy:
I will use python to interact with adb. The most important thing is to use the "device.push()" function in adb to achieve all this.

Implementation details:
I will use python+ppadb to realize the automated command line. For all these operations, I will use tkinterGUI to output the adb command with just the mouse, and successfully upload the files in the PC to the mobile phone.

![Uploading w.png…]()

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/doc/control.md#file-drop

**Comment by qq2506389997** [comment]
> [https://github.com/Genymobile/scrcpy/blob/master/doc/control.md#file-drop ](https://github.com/Genymobile/scrcpy/blob/master/doc/control.md#file-drop)

All right Man you make me have to admit, I'm blind
