### ISSUE TITLE
xiaomi 14 device can not use this function

### ISSUE THREAD

**Issue by msccreater** [Genymobile/scrcpy#4402]
**Environment**
 - OS: [ Windows]
 - scrcpy version: [e.g. 2.2]
 - installation method: [Windows release...]
 - device model: xiaomi 14
 - Android version: [e.g. 14]

**Describe the bug**
Turn device screen off (keep mirroring),  other func is ok, this func is not work,

**Comment by rom1v** [comment]
#3927
