### ISSUE TITLE
Screen only partly visible in Ubuntu 16.04 in a VM

### ISSUE THREAD

**Issue by heurekus** [Genymobile/scrcpy#441]
scrcpy works fine on my Ubuntu 16.04 when running on bare metal and in a Windows 10 guest VM on 16.04. When I run scrcpy in an Ubuntu 16.04 guest on this system, however, I can only see the upper left part of the screen while the lower right part of the screen is black, with a gradual shade from one to the other (see screenshot). Must have something to do with the VM-scrcpy combination as it runs fine in the other two setups described above. This effect is not limited to a certain Android device but happens with other devices as well.

![scrcpy-in-ubutu-1604-guest](https://user-images.githubusercontent.com/47881430/53680288-7d580100-3cd9-11e9-8b71-11eecce586de.png)

**Comment by rom1v** [comment]
> Must have something to do with the VM

Yes, probably.

Could you try any other application using SDL?

(random link: https://en.wikipedia.org/wiki/List_of_games_using_SDL)

**Comment by npes87184** [comment]
Hi, @heurekus 

What's your VM environment (QEMU, Vitrualbox)?

Thanks

**Comment by heurekus** [comment]
@npes87184: I'm using Virtualbox 6.0 with vmsvga graphics driver, the other two don't work with Ubuntu 16.04.

@rom1v: Will try a game later and let you know!

**Comment by heurekus** [comment]
The same issue is also present with Ubuntu 18.04 running in Virtualbox 6.0 as a guest, so it's not an Ubuntu 16.04 specific issue. Also, VMSVGA is used as virtual graphics card.

**Comment by heurekus** [comment]
@rom1v tried out Supertux as it was in the list you linked to above in the Ubuntu 16.04 guest. Works flawlessly, smooth including horizontal scrolling and full screen going dark shade effect when the Tux dies.

**Comment by rom1v** [comment]
OK, thank you for the feedback. I have no idea why.

**Comment by npes87184** [comment]
Hi, @heurekus 

I have tested it by using master branch `QEMU` and master branch `scrcpy`.
It works like a charm!

![default](https://user-images.githubusercontent.com/5494432/53690331-4a7a3f80-3da3-11e9-9ae8-4d95431d83e4.png)

There is my environment:

* Host: ubuntu-18.04-2
* Guest: ubuntu-18.04-2

QEMU configure:
```
./configure --target-list=x86_64-softmmu --enable-debug --enable-kvm --enable-libusb
```

QEMU command:
```
./x86_64-softmmu/qemu-system-x86_64 -enable-kvm -machine q35 -cpu host \
-device virtio-scsi-pci,id=scsi \
-device scsi-hd,drive=hd \
-drive if=none,id=hd,file=/media/yuchenlin/linux/ubuntu-18.04.qcow2,format=qcow2 \
-m 2048 \
-smp 2 \
-nic user,model=virtio-net-pci \
-usb \
-device qemu-xhci \
-device usb-host,vendorid=0xXXXX,productid=0xXXXX
-device vmware-svga
```

To see whether the problem is in virtualbox or not, could you please give `QEMU` a try?

Thanks,
Yu-Chen

**Comment by heurekus** [comment]
Good idea! Can't try that right now however, will come back to this later in the week.

**Comment by npes87184** [comment]
Hi, @heurekus 

Any news?

Thanks.
