### ISSUE TITLE
ERROR: Could not open audio device: ALSA: Couldn't open audio device: Host is down(fixed itself)

### ISSUE THREAD

**Issue by Marstaed** [Genymobile/scrcpy#4415]
Hello, I have a problem with the sound. Here is information about the hardware and terminal output.
I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).
 - OS: Fedora Linux 39
 - scrcpy version: 2.2
 - installation method: dnf
 - device model: Google Pixel 6a
 - Android version: 14

Terminal output:
```
scrcpy v2.2 <https://github.com/Genymobile/scrcpy>
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
INFO: ADB device found:
INFO:     -->   (usb)  2A151JEGR05439                  device  Pixel_6a
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 552.0 MB/s (64363 bytes in 0.000s)
[server] INFO: Device: [Google] google Pixel 6a (Android 14)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 23.2.1
INFO: Trilinear filtering enabled
INFO: Texture: 1080x2400
ERROR: Could not open audio device: ALSA: Couldn't open audio device: Host is down
ERROR: Demuxer error
```

I tried running it with the command: scrcpy --no-audio
As a result, there is video, but no sound.
Please help me solve the problem. 
Any help is greatly appreciated!

**Comment by Marstaed** [comment]
In this case, everything was fixed for me after rebooting the system.

**Comment by l376571926** [comment]
> Hello, I have a problem with the sound. Here is information about the hardware and terminal output. I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md). I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).
> 
> * OS: Fedora Linux 39
> * scrcpy version: 2.2
> * installation method: dnf
> * device model: Google Pixel 6a
> * Android version: 14
> 
> Terminal output:
> 
> ```
> scrcpy v2.2 <https://github.com/Genymobile/scrcpy>
> error: XDG_RUNTIME_DIR is invalid or not set in the environment.
> INFO: ADB device found:
> INFO:     -->   (usb)  2A151JEGR05439                  device  Pixel_6a
> /usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 552.0 MB/s (64363 bytes in 0.000s)
> [server] INFO: Device: [Google] google Pixel 6a (Android 14)
> INFO: Renderer: opengl
> INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 23.2.1
> INFO: Trilinear filtering enabled
> INFO: Texture: 1080x2400
> ERROR: Could not open audio device: ALSA: Couldn't open audio device: Host is down
> ERROR: Demuxer error
> ```
> 
> I tried running it with the command: scrcpy --no-audio As a result, there is video, but no sound. Please help me solve the problem. Any help is greatly appreciated!

you save my life.

**Comment by Marstaed** [comment]
;)

пн, 13 нояб. 2023 г., 12:11 李艺为 ***@***.***>:
