### ISSUE TITLE
Failed To Install scrcpy: "libvorbis"

### ISSUE THREAD

**Issue by Eren672** [Genymobile/scrcpy#4420]
**Environment**
 - OS: macOS 10.15
 - scrcpy version: 2.2
 - installation method: brew
 - device model: macOS 10.15
 - Android version: 13

**Bug Description**
I am trying to install scrcpy on my Mac. However, I get the following error when I run `brew install scrcpy`

I searched on existing issues and found a solution that suggested using a different version of curl installed by Homebrew and setting an environment variable called `HOMEBREW_FORCE_BREWED_CURL=1`. I followed the steps to do that but still got the same error.

I also tried to reinstall Homebrew and install the missing dependency manually, but none worked. 

Can anyone help me solve this issue and install scrcpy on my Mac? I would appreciate it. Thank you.

```
Error: scrcpy: Failed to download resource "libvorbis"
Download failed: Homebrew-installed `curl` is not installed for: https://downloads.xiph.org/releases/vorbis/libvorbis-1.3.7.tar.xz

**Comment by rom1v** [comment]
See #3505 or report to homebrew.
