### ISSUE TITLE
java.io.IOException: Could not read audio: -4

### ISSUE THREAD

**Issue by mattia-lecci** [Genymobile/scrcpy#4423]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: 2.2
 - installation method: Windows release
 - device model: OnePlus 9
 - Android version: 11

**Describe the bug**
I am trying to record the screen+audio while Microsoft Teams is running.
The video works as expected, the audio does not and actually crashes.
Using Youtube, both video and audio work as expected.

Test:
* Start `scrcpy -Nr tmp.mp4 -V debug`
* Start youtube
  * Play a music video (_NOTE: no issues. no audio coming out of the device, but audio perfectly working on the recorded video_)
* Close youtube
* Join an ongoing MS Teams meeting
  * The default audio option is device (_NOTE: audio can be heard coming from the device. no audio in the recorded video_)
  * Switching to "speaker" audio option (_NOTE: same as above + java.io.IOException shown below_)
  * Switching to no audio (_NOTE: no audio from phone or recorded video as expected_)
* Leave meeting
* Close MS Teams
* Start youtube
* Play a music video (_NOTE: no audio from either the device nor the recorded video. probable an effect of the previous crash?_)

```
>scrcpy -Nr tmp.mp4 -V debug
scrcpy v2.2 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)              215af537            device  LE2113
DEBUG: Device serial: 215af537
DEBUG: Using server (portable): C:\Program Files\scrcpy\scrcpy-win64-v2.2\scrcpy-server
C:\Program Files\scrcpy\scrcpy-win64-v2.2\scrcpy-server: 1 file pushed, 0 skipped. 71.9 MB/s (64363 bytes in 0.001s)
[server] INFO: Device: [OnePlus] OnePlus LE2113 (Android 11)
[server] DEBUG: Using audio encoder: 'c2.android.opus.encoder'
[server] DEBUG: Using video encoder: 'c2.qti.avc.encoder'
DEBUG: Server connected
DEBUG: Starting controller thread
DEBUG: Starting receiver thread
DEBUG: Demuxer 'video': starting thread
INFO: Recording started to mp4 file: tmp.mp4
DEBUG: Demuxer 'audio': starting thread
WARN: [FFmpeg] track 1: codec frame size is not set
[server] ERROR: Audio capture error
java.io.IOException: Could not read audio: -4
        at com.genymobile.scrcpy.AudioEncoder.inputThread(AudioEncoder.java:98)
        at com.genymobile.scrcpy.AudioEncoder.lambda$encode$1$com-genymobile-scrcpy-AudioEncoder(AudioEncoder.java:198)
        at com.genymobile.scrcpy.AudioEncoder$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:923)
[server] DEBUG: Audio encoder stopped
DEBUG: User requested to quit
DEBUG: Server disconnected
DEBUG: Server terminated
DEBUG: quit...
DEBUG: Demuxer 'video': end of frames
DEBUG: Demuxer 'audio': end of frames
DEBUG: Receiver stopped
INFO: Recording complete to mp4 file: tmp.mp4
DEBUG: Recorder thread ended
```

**Comment by rom1v** [comment]
-4 is `PERMISSION_DENIED`:

https://github.com/aosp-mirror/platform_frameworks_base/blob/47a3e1b818acc63853beb21ad9ecc0366b73cb7c/media/java/android/media/AudioSystem.java#L906

> Android version: 11

It's very hacky to bypass some permission restrictions that were in place in Android 11 (which are removed from Android 12+): https://github.com/Genymobile/scrcpy/blob/master/doc/audio.md#audio

So it's not surprising that in such cases permission can be denied again. It should work on Android 12+.

**Comment by mattia-lecci** [comment]
Thank you for your feedback. I tested it on and Android 13 phone (OnePlus 11) and the error does not appear.

Still, the behavior is unexpected. I'll open another issue related to the specific problem i'm facing.
