### ISSUE TITLE
cant show device screen, only  1 file pushed

### ISSUE THREAD

**Issue by LiweiDong** [Genymobile/scrcpy#4424]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 11
 - scrcpy version: 2.1.1 、 2.2
 - installation method: Windows release 
 - device model:
 - Android version: [e.g. 10]

```

D:\Download\scrcpy-win64-v2.1.1>scrcpy.exe
scrcpy 2.1.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)      1234567890ABCDEF            device
D:\Download\scrcpy-win64-v2.1.1\scrcpy-server: 1 file pushed, 0 skipped. 74.9 MB/s (56995 bytes in 0.001s)


```

**Comment by rom1v** [comment]
Does it work with `scrcpy --no-audio`?

Does it work with another [encoder](https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#encoder)?

**Comment by LiweiDong** [comment]
> Does it work with `scrcpy --no-audio`?
> 
> Does it work with another [encoder](https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#encoder)?

not works,  This is an embedded device without a screen. I'm not sure if it can be used this way.

**Comment by rom1v** [comment]
Try with `--turn-screen-off` maybe.

**Comment by LiweiDong** [comment]
> Try with `--turn-screen-off` maybe.

It's still not working.

**Comment by rom1v** [comment]
```
adb shell screenrecord /sdcard/file.mp4
adb pull /sdcard/file.mp4
```

Does it work?

**Comment by LiweiDong** [comment]
> adb shell screenrecord /sdcard/file.mp4

```➜  ~ adb shell screenrecord /sdcard/file.mp4
/bin/sh: screenrecord: not found ```

**Comment by LiweiDong** [comment]
> ```
> adb shell screenrecord /sdcard/file.mp4
> adb pull /sdcard/file.mp4
> ```
> 
> Does it work?

sorry, it works. i connected the wrong device.
