### ISSUE TITLE
Feature request: Allow to rotate the camera.

### ISSUE THREAD

**Issue by hellishvictor** [Genymobile/scrcpy#4426]
- OS: Win 7 x64 SP1
 - adb v34.0.4 (last version that works with Windows 7)
 - scrcpy version: 1.2.2
 - installation method: scrcpy-win64-v2.2.zip
 - device model: Samsung Galaxy 
 - Android version: 12

Hi, I just updated ScrCpy to the latest version and tested the new camera features, which are awesome, but it only works on horizontal mode, with the top of the device to the left, so it don't rotate at all. 
It would be great if were implemented an option to allow it to rotate along with the device, or just to switch it to vertical mode.

Cheers.

**Comment by rom1v** [comment]
`--rotation` rotates the content on the screen (but not the recording): https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#rotation

**Comment by hellishvictor** [comment]
--rotation=3 did the trick -> Goodbye DroidCam!

**Comment by tommy8372** [comment]
this flag doesn't have an effect for video4linux with camera source and stream always start in horizontal mode

i'm using below for linux webcam
`scrcpy --v4l2-sink=/dev/video10 --video-source=camera --camera-id=1 --no-audio --no-video-playback`

`--rotation=1` do the trick for me for video playback only, any idea how to solve this for camera?

**Comment by rom1v** [comment]
See #4441.

> this flag doesn't have an effect for video4linux with camera source and stream always start in horizontal mode

https://github.com/Genymobile/scrcpy/pull/4441#issuecomment-1820658788

**Comment by ManuLinares** [comment]
Is there any new development on this?

**Comment by rom1v** [comment]
> Is there any new development on this?

What do you try to achieve?

Camera orientation is supported for display and recording, but not for the video4linux feature.

https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#orientation

Cf [highlights of v2.3](https://github.com/Genymobile/scrcpy/releases/tag/v2.3) (but take the latest version, not v2.3).

**Comment by ManuLinares** [comment]
I need to be able to rotate the camera using v4l2loopback.

**How to reproduce:**
1. Connect the phone via USB
2. `scrcpy --video-source=camera --camera-facing=back --v4l2-sink /dev/video1 --no-audio-playback --no-video-playback --camera-fps 30 --camera-size=1280x720`
3. Open a Meet, Teams, Jitsi, etc. My face is upside down.

I expect to be able to rotate the webcam sink.

**Comment by rom1v** [comment]
Rotate the phone to get the expected orientation :smile: 

More seriously, it will require to filter the capture on the server side (refs https://github.com/Genymobile/scrcpy/issues/4011#issuecomment-1969174671).

**Comment by rom1v** [comment]
Please test #5455.
