### ISSUE TITLE
Input Chinese question

### ISSUE THREAD

**Issue by locklocklock1206** [Genymobile/scrcpy#4428]
When using the new version of scrcpy, [server] WARN: Could not input char will appear when entering Chinese in scrcpy. Can scrcpy still not input unicode

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#special-characters-do-not-work

**Comment by locklocklock1206** [comment]
But when using TCP/IP connections, HID is no longer available

**Comment by 809825706** [comment]
可以参考我的[方案](https://github.com/Genymobile/scrcpy/issues/1055#issuecomment-1876753109)

**Comment by rom1v** [comment]
Fixed by the new UHID method in scrcpy 2.4.
