### ISSUE TITLE
I run the program and nothing happens =(

### ISSUE THREAD

**Issue by itischenko** [Genymobile/scrcpy#443]
1. Meizu 6 pro plus
2. Root (custom firmware)
3. Adb drivers (latest) installed, and device found
4. Device connected via USB
5. USB debugging enabled
6. "Charge only" mode enabled
7. I run SCRCPY.EXE and nothing happens, please tell me what am I doing wrong?

I looked at similar topics, videos in YouTube and did not find anything (

![image](https://user-images.githubusercontent.com/48246237/53804810-82c37e80-3f59-11e9-8d2a-4d8f9cf87d34.png)

**Comment by rom1v** [comment]
There is probably a problem on the device side. Look at the logs with `adb logcat`.

**Comment by itischenko** [comment]
> There is probably a problem on the device side. Look at the logs with `adb logcat`.

Thanks for the answer. I entered `adb logcat` and СMD gives me a lot of data. What exactly should I see there?

**Comment by rom1v** [comment]
Let it run, and in another terminal start _scrcpy_. Then check if this prints some errors.

**Comment by itischenko** [comment]
> Let it run, and in another terminal start _scrcpy_. Then check if this prints some errors.

`03-05 15:38:12.710 15322 15333 W ACodec  : do not know color format 0x7f000011 =
 2130706449
03-05 15:38:12.711 15322 15333 W ACodec  : do not know color format 0x10 = 16
03-05 15:38:12.711 15322 15333 W ACodec  : do not know color format 0x7f00a000 =
 2130747392
03-05 15:38:12.712 15322 15333 W ACodec  : do not know color format 0x7f000789 =
 2130708361
03-05 15:38:12.713 15322 15333 I ACodec  : setupAVCEncoderParameters with [profi
le: Baseline] [level: Level31]
03-05 15:38:12.714 15322 15333 I ACodec  : [OMX.Exynos.AVC.Encoder] cannot encod
e HDR static metadata. Ignoring.
03-05 15:38:12.714 15322 15333 I ACodec  : setupVideoEncoder succeeded
03-05 15:38:12.714 15322 15333 W ACodec  : do not know color format 0x7f000789 =
 2130708361
03-05 15:38:12.715  2654  3725 E OMXNodeInstance: getConfig(a5e007a:Exynos.AVC.E
ncoder, ConfigAndroidIntraRefresh(0x6f60000a)) ERROR: UnsupportedIndex(0x8000101
a)
03-05 15:38:12.719  2654  2654 I BufferQueue: [unnamed-2654-27](this:0xf55a7000,
id:27,api:0,p:-1,c:-1) BufferQueue core=(2654:media.codec)
03-05 15:38:12.721 15322 15322 E Surface : Could not create instance of Surface
from IGraphicBufferProducer.`

**Comment by itischenko** [comment]
> Let it run, and in another terminal start _scrcpy_. Then check if this prints some errors.

`03-05 15:38:12.715  2654  3725 E OMXNodeInstance: getConfig(a5e007a:Exynos.AVC.Encoder, ConfigAndroidIntraRefresh(0x6f60000a)) ERROR: UnsupportedIndex(0x8000101a)
03-05 15:38:12.719  2654  2654 I BufferQueue: [unnamed-2654-27](this:0xf55a7000, id:27,api:0,p:-1,c:-1) BufferQueue core=(2654:media.codec)
03-05 15:38:12.721 15322 15322 E Surface : Could not create instance of Surface from GraphicBufferProducer.`

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/issues/151?

**Comment by itischenko** [comment]
> #151?

Yes, screenrecord is OK.
I got a test.mp4 with content after that

**Comment by itischenko** [comment]
> #151?

A lot of information in the logs, I do not understand what exactly I should see, there are no explicit error messages

**Comment by rom1v** [comment]
Nothing about `com.meizu.nightmode.MzNightModeManager` for example?

What if you start `scrcpy -m 800`?

**Comment by itischenko** [comment]
> Nothing about `com.meizu.nightmode.MzNightModeManager` for example?
> 
> What if you start `scrcpy -m 800`?

`03-05 16:10:38.261 16275 16306 I HLSP2P  : [TaskManager.cpp][INFO][UpdateGlobalInfo]totalDataSize: 0, totalMemorySize: 0, totalCacheSize: 0, PlayTaskAllFinish:0
03-05 16:10:38.381  2648  9005 I audio_hw_primary: adev_set_parameters(): kvpairs: mediaserver_monitor=1
03-05 16:10:38.381  2648  9005 I audio_hw_hwvolume: parse_hw_volume_parameters(): kvpairs: mediaserver_monitor=1
03-05 16:10:38.971 16683 16683 I Radio-JNI: register_android_hardware_Radio DONE
03-05 16:10:38.983 16683 16690 E SchedPolicy: open of /dev/cpuctl/bg_non_interactive/tasks failed: No such file or directory
03-05 16:10:39.005 16683 16683 I art     : Thread[1,tid=16683,Native,Thread*=0x7f87895a00,peer=0x12c060d0,"main"] recursive attempt to load library "/system/lib64/libmedia_jni.so"
03-05 16:10:39.005 16683 16683 I art     : Thread[1,tid=16683,Native,Thread*=0x7f87895a00,peer=0x12c060d0,"main"] recursive attempt to load library "/system/lib64/libmedia_jni.so"
03-05 16:10:39.005 16683 16683 I art     : Thread[1,tid=16683,Native,Thread*=0x7f87895a00,peer=0x12c060d0,"main"] recursive attempt to load library "/system/lib64/libmedia_jni.so"
03-05 16:10:39.007  2657  3515 I MediaPlayerService: MediaPlayerService::getOMX
03-05 16:10:39.008 16683 16696 I OMXClient: MuxOMX ctor
03-05 16:10:39.010  2654  2654 I OMXMaster: makeComponentInstance(OMX.Exynos.AVC.Encoder) in mediacodec process
03-05 16:10:39.012  2654  2654 I libexynosv4l2: node found for device s5p-mfc-en c: /dev/video7
03-05 16:10:39.012  2654  2654 I libexynosv4l2: open video device /dev/video7
03-05 16:10:39.016 16683 16696 W ACodec  : do not know color format 0x7f000011 = 2130706449
03-05 16:10:39.016 16683 16696 W ACodec  : do not know color format 0x10 = 16
03-05 16:10:39.016 16683 16696 W ACodec  : do not know color format 0x7f00a000 =  2130747392
03-05 16:10:39.017 16683 16696 W ACodec  : do not know color format 0x7f000789 = 2130708361
03-05 16:10:39.018 16683 16696 I ACodec  : setupAVCEncoderParameters with [profile: Baseline] [level: Level31]
03-05 16:10:39.020 16683 16696 I ACodec  : [OMX.Exynos.AVC.Encoder] cannot encode HDR static metadata. Ignoring.
03-05 16:10:39.020 16683 16696 I ACodec  : setupVideoEncoder succeeded
03-05 16:10:39.020 16683 16696 W ACodec  : do not know color format 0x7f000789 = 2130708361
03-05 16:10:39.021  2654  3726 E OMXNodeInstance: getConfig(a5e0085:Exynos.AVC.Encoder, ConfigAndroidIntraRefresh(0x6f60000a)) ERROR: UnsupportedIndex(0x8000101a)
03-05 16:10:39.024  2654  3324 I BufferQueue: [unnamed-2654-35](this:0xf55df000,id:35,api:0,p:-1,c:-1) BufferQueue core=(2654:media.codec)
03-05 16:10:39.030 16683 16683 E Surface : Could not create instance of Surface from IGraphicBufferProducer.
03-05 16:10:39.031 16683 16683 E Surface : java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
03-05 16:10:39.031 16683 16683 E Surface :      at android.os.Handler.<init>(Handler.java:200)
03-05 16:10:39.031 16683 16683 E Surface :      at android.os.Handler.<init>(Handler.java:114)
03-05 16:10:39.031 16683 16683 E Surface :      at com.meizu.nightmode.MzNightModeManager.<init>(MzNightModeManager.java:148)
03-05 16:10:39.031 16683 16683 E Surface :      at com.meizu.nightmode.MzNightModeManager.getDefault(MzNightModeManager.java:262)
03-05 16:10:39.031 16683 16683 E Surface :      at android.graphics.Canvas.<init>(Canvas.java:2606)
03-05 16:10:39.031 16683 16683 E Surface :      at android.view.Surface$CompatibleCanvas.<init>(Surface.java:595)
03-05 16:10:39.031 16683 16683 E Surface :      at android.view.Surface.<init>(Surface.java:93)
03-05 16:10:39.031 16683 16683 E Surface :      at android.media.MediaCodec.createInputSurface(Native Method)
03-05 16:10:39.031 16683 16683 E Surface :      at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:69)
03-05 16:10:39.031 16683 16683 E Surface :      at com.genymobile.scrcpy.Server.scrcpy(Server.java:28)
03-05 16:10:39.031 16683 16683 E Surface :      at com.genymobile.scrcpy.Server.main(Server.java:110)
03-05 16:10:39.031 16683 16683 E Surface :      at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
03-05 16:10:39.031 16683 16683 E Surface :      at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:277)
03-05 16:10:39.035  2654 16697 I EXYNOS_BASE_COMP: [0xf55e3000][Exynos_OMX_ComponentStateSet] current:(OMX_StateLoaded) dest:(OMX_StateIdle)
03-05 16:10:39.040  2654 16697 I libexynosv4l2: node found for device s5p-mfc-enc: /dev/video7
03-05 16:10:39.040  2654 16697 I libexynosv4l2: open video device /dev/video7
03-05 16:10:39.040  2654 16697 I EXYNOS_BASE_COMP: [0xf55e3000][Exynos_OMX_ComponentStateSet] OMX_EventCmdComplete
03-05 16:10:39.041  2654 16697 I EXYNOS_BASE_COMP: [0xf55e3000][Exynos_OMX_ComponentStateSet] current:(OMX_StateIdle) dest:(OMX_StateExecuting)
03-05 16:10:39.041  2654 16697 I EXYNOS_BASE_COMP: [0xf55e3000][Exynos_OMX_ComponentStateSet] OMX_EventCmdComplete
03-05 16:10:39.265 16275 16306 I HLSP2P  : [TaskManager.cpp][INFO][UpdateGlobalInfo]totalDataSize: 0, totalMemorySize: 0, totalCacheSize: 0, PlayTaskAllFinish:0
03-05 16:10:40.269 16275 16306 I HLSP2P  : [TaskManager.cpp][INFO][UpdateGlobalInfo]totalDataSize: 0, totalMemorySize: 0, totalCacheSize: 0, PlayTaskAllFinish:0
03-05 16:10:40.739  2979  3153 E WifiHAL : In GetLinkStatsCommand::handleResponse
03-05 16:10:40.739  2979  3153 E WifiHAL : Id = 0, subcmd = 0
03-05 16:10:40.739  2979  3153 E WifiHAL : len = 2364
03-05 16:10:40.739  2979  3153 E WifiHAL : num_channels: = 11
03-05 16:10:40.739  2979  3153 E WifiHAL : channel_size: = 264
03-05 16:10:40.739  2979  3153 E WifiHAL : total_size: = 320
03-05 16:10:40.739  2979  3153 E WifiHAL : radio: = 1635021679`

**Comment by itischenko** [comment]
> Nothing about `com.meizu.nightmode.MzNightModeManager` for example?
> 
> What if you start `scrcpy -m 800`?

sorry, I don't know how to format the code, it looks like trash

**Comment by rom1v** [comment]
OK, then it's exactly #151.

You could use #434 workaround.

**Comment by itischenko** [comment]
> OK, then it's exactly #151.
> 
> You could use #434 workaround.

Thanks for the help. I'm not a programmer, a regular user. In the topic that you sent, I realized that the problem was not solved because of the strange code of the developers. Once again, I am convinced that the Meizu is a complete shit
