### ISSUE TITLE
Standalone server : camera source

### ISSUE THREAD

**Issue by Utopiah** [Genymobile/scrcpy#4436]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
There is currently no way to select a camera from current options https://github.com/Genymobile/scrcpy/blob/a3cdf1a6b86ea22786e1f7d09b9c202feabc6949/server/src/main/java/com/genymobile/scrcpy/Options.java#L202

**Describe the solution you'd like**
Matching what the client can do, namely `--video-sources=camera` and `--camera-id=0`

**Describe alternatives you've considered**
-

**Additional context**
Useful for Lynx R1 XR HMD to get front facing cameras content.

**Comment by rom1v** [comment]
> There is currently no way to select a camera from current options

You linked an old scrcpy version.

https://github.com/Genymobile/scrcpy/blob/c3c7bf7af329c8a5fd9f0310eae3b4e0a5f86207/server/src/main/java/com/genymobile/scrcpy/Options.java#L373

**Comment by Utopiah** [comment]
Thanks, then I guess https://github.com/Genymobile/scrcpy/blob/master/doc/develop.md?plain=1#L420 should be updated accordingly.

**Comment by rom1v** [comment]
@Utopiah This section does not list all parameters, only the one added specifically to the server which are not used by the scrcpy client. I will not maintain all the internal parameters in the documentation.

**Comment by Utopiah** [comment]
Sorry I wasn't clear, I meant that this live documentation links to https://github.com/Genymobile/scrcpy/blob/a3cdf1a6b86ea22786e1f7d09b9c202feabc6949/server/src/main/java/com/genymobile/scrcpy/Options.java#L309-L329 rather than https://github.com/Genymobile/scrcpy/blob/c3c7bf7af329c8a5fd9f0310eae3b4e0a5f86207/server/src/main/java/com/genymobile/scrcpy/Options.java#L373 that you linked to or even https://github.com/Genymobile/scrcpy/blob/master/server/src/main/java/com/genymobile/scrcpy/Options.java#L373 and thus the parameters I was looking for, namely camera_id", camera_size, camera_facing, camera_ar, camera_fps or camera_high_speed are not listed.

**Comment by rom1v** [comment]
Oh, the reason is that if I link to master, the line numbers (or content) will change (and the documentation may not be updated each time I touch this file).

The content it points to is valid in that old version, but other changes may have occurred around.
