### ISSUE TITLE
Setup screen recording

### ISSUE THREAD

**Issue by Harshilmehta23** [Genymobile/scrcpy#444]
Hello,
do i need to setup anything for screen recording.
i m very new to this topic. i just want to record my android gameplay using this.
i have download latest build.and starting scrcpy. my android screen starts showing with best quality i have ever cast to pc. but when i put command scrcpy --record file.mp4 nothing happens. do i need to setup anything further to use commands?

**Comment by rom1v** [comment]
> when i put `scrcpy --record file.mp4` nothing happens

Where do you write this?

You need to open a console (cmd.exe), then go the the scrcpy directory, then execute this command.

See #385.

**Comment by Harshilmehta23** [comment]
> > when i put `scrcpy --record file.mp4` nothing happens
> 
> Where do you write this?
> 
> You need to open a console (cmd.exe), then go the the scrcpy directory, then execute this command.
> 
> See #385.

yes i m writing in that console only.

**Comment by Harshilmehta23** [comment]
ok thanks i got it. i was using this command after session has started.
any tips for recording at best quality. i m using pixel 2 as my android device. i want to record at best quality possible.

**Comment by rom1v** [comment]
> any tips for recording at best quality

Increase the bitrate:

    scrcpy -b16M -r file.mp4
