### ISSUE TITLE
I need an option to decide show or hide unlocking screen content

### ISSUE THREAD

**Issue by urcllr** [Genymobile/scrcpy#4442]
- [ ] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
Scrcpy can show unlocking screen content and I can unlock some phones on PC. But there're some phones scrcpy shows a black screen on PC and I have to do the same operation on phone.

**Describe the solution you'd like**
I need an option (command args or other ways) to decide whether scrcpy show or hide unlocking screen.

**Describe alternatives you've considered**

**Additional context**

**Comment by DanGLES3** [comment]
> * [ ]  I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.
> 
> **Is your feature request related to a problem? Please describe.** Scrcpy can show unlocking screen content and I can unlock some phones on PC. But there're some phones scrcpy shows a black screen on PC and I have to do the same operation on phone.
> 
> **Describe the solution you'd like** I need an option (command args or other ways) to decide whether scrcpy show or hide unlocking screen.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

That's not up to Scrcpy's control, the black screen is happening because these devices set a secure flag in the lockscreen to prevent screen captures from happening, Scrcpy can't override the secure flag of these devices, only way around it would be patching out the secure flag with root

**Comment by urcllr** [comment]
Knowing it's not related to scrcpy, I close the issue
