### ISSUE TITLE
Output image rotation

### ISSUE THREAD

**Issue by NoCultist** [Genymobile/scrcpy#446]
I found out many issues with some apps (mostly camera aps) that force portrait mode. The ADB commands to rotate phone orientation are unable to fix this issue so my idea is to very nicely ask if there is a possibility of adding a feature that would simply allow scrcpy to render image rotated by 90 or 180 degrees?

If there already exists a solution to my problem, I'm sorry but I wasn't able to track it down.

Regards
NoCultist

**Comment by rom1v** [comment]
> If there already exists a solution to my problem

Currently, there isn't.

But it has already been requested: https://github.com/Genymobile/scrcpy/issues/218.

**Comment by rom1v** [comment]
It's implemented on `dev` (#1151).
