### ISSUE TITLE
Basic commands for scrcpy Connection via USB debugging or wireless debugging

### ISSUE THREAD

**Issue by umos8** [Genymobile/scrcpy#4465]
Basic Command

(More than one device can be connected via TCPIP)

.\adb tcpip 5555 [ To connect a device via Wi-Fi ]
.\adb tcpip 5556 [ To connect another device via Wi-Fi ]
.\adb kill-server [To delete all servers]
.\adb devices [To view all devices installed in ADB]

Connection example for Wireless Debugging

.\adb pair 192.168.0.236:*****
.\adb connect 192.168.0.236:***** (screen code after linking)
.\scrcpy --no-audio -s 192.168.0.236:****

Connection example BY USB DEBUG

.\adb connect 192.168.0.174:5555
.\adb connect 192.168.0.236:5556
.\scrcpy --no-audio -s 192.168.0.174:5555 [ Phone ]
.\scrcpy --no-audio -s 192.168.0.236:5556 [ Tablet ]

**Comment by rom1v** [comment]
Please stop posting issues that are not issues (even if you removed your spams links).
