### ISSUE TITLE
Newbie has an issue

### ISSUE THREAD

**Issue by MrMondayHonday** [Genymobile/scrcpy#447]
So I am a newbie running Linux (lubuntu to be specific).
My skill writing code and making magic happen without dummie GUIs are limited at best.
I was looking for a free alternative to Vysor and found out about Scrcpy.

So I managed to install it good enough for me to launch it and get the screen casted from my mobile phone to my computer. All well and good. 

BUT
Trying to do operate the phone over USB just results with the terminal spitting out the following:
_WARN: Unknown event type: 5
WARN: Unknown event type: 5_

I have also tried to activate the TCP/IP wifi function, but I am having no success. This is not surprising as my my tech-wizardry is still weak.

As far as I gathered: You can turn on the wifi by hooking up the phone via USB and typing

adb tcpip 5555
adb connect 142.15.124.7:5555

in the terminal.
So I thought I should try it out.

This returns:

**adb tcpip 5555** 
_restarting in TCP mode port: 5555_

**adb connect 142.15.124.7:5555**
_connected to 142.15.124.7:5555_

So, I pull the cable and type scrcpy in the terminal to try to launch the app via wifi

this yields:
```
[100%] /data/local/tmp/scrcpy-server.jar
error: more than one device/emulator
ERROR: "adb reverse" returned with value 1
WARN: 'adb reverse' failed, fallback to 'adb forward'
ERROR: Exception on thread Thread[main,5,main]
java.io.IOException: Connection refused
at android.net.LocalSocketImpl.connectLocal(Native Method)
at android.net.LocalSocketImpl.connect(LocalSocketImp l.java:292)
at android.net.LocalSocket.connect(LocalSocket.java:1 45)
at com.genymobile.scrcpy.DesktopConnection.connect(De sktopConnection.java:32)
at com.genymobile.scrcpy.DesktopConnection.open(Deskt opConnection.java:37)
at com.genymobile.scrcpy.Server.scrcpy(Server.java:13 )
at com.genymobile.scrcpy.Server.main(Server.java:70)
at com.android.internal.os.RuntimeInit.nativeFinishIn it(Native Method)
at com.android.internal.os.RuntimeInit.main(RuntimeIn it.java:286)
```
can anyone give a muggle some pointers?

**Comment by rom1v** [comment]
First of all:

> WARN: Unknown event type: 5

I guess you compiled using the prebuilt_server, but you don't use the right version which matches your client code.

If you compile v1.7 (or master currently), you must use `scrcpy-server-v1.7.jar`.

**Comment by MrMondayHonday** [comment]
Thank you for your reply.
I looked it up and I had dumped scrcpy-server-v1.0.jar in the master folder.
Can I just dl and dump 1.7 in it? Where can I find the 1.7.jar?

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#prebuilt-server

You need to reconfigure your meson folder to use the new version:

    meson configure x -Dprebuilt_server=path/to/your/scrcpy-server-v1.7.jar

**Comment by MrMondayHonday** [comment]
Thank you. I will attempt it.

**Comment by MrMondayHonday** [comment]
my hat is off to rom1v. it worked!
Thank you so much.

By the way, how secure is the stream? should I be worried rivaling groups hacking into the stream? Thinking about using scrcpy for a few presentations that might land me a position somewhere.

**Comment by rom1v** [comment]
If you stream over wifi, it can be read.

But both over USB or wifi, sending an alternate video stream would require to connect to a TCP socket listening only on localhost.

**Comment by MrMondayHonday** [comment]
lately I have been getting the following error when I try to launch:
adb: error. connect failed: more than one device/emulator
ERROR "adb push" returned with value 1

What causes this?
