### ISSUE TITLE
Mouse and keyboard do not work - Android 14

### ISSUE THREAD

**Issue by nhMccl** [Genymobile/scrcpy#4475]
This is a solution, and it may not be necessary for most users, but after upgrading to Android 14, I could no longer interact with the screen with my mouse. The simple solution was to update to scrcpy-win64-v2.3.

**Comment by rom1v** [comment]
Yes, Android 14 changed some internal things: #4074
This specific issue was fixed in scrcpy 2.1.

**Comment by lubo99** [comment]
guys I have macos big sur and samsung galaxy s9 tab ultra on android 14. does not work even affter update to latest version via brew... any idea? I see the screen however I click and there is no response.

**Comment by lubo99** [comment]
scrcpy
dyld: Library not loaded: /usr/local/opt/jpeg-xl/lib/libjxl.0.7.dylib
  Referenced from: /usr/local/opt/ffmpeg/lib/libavformat.59.dylib
  Reason: image not found
zsh: abort      scrcpy


i tried to reinstall ffmpeg

==> Reinstalling ffmpeg 
==> Installing dependencies for ffmpeg: llvm, rust, ruby, vim, libvmaf, yasm, aom, aribb24, dav1d, freetype, fontconfig, frei0r, gmp, nettle, p11-kit, libevent, libnghttp2, unbound, gnutls, glib, xorgproto, xcb-proto, libxcb, util-macros, xtrans, libx11, cairo, gobject-introspection, harfbuzz, fribidi, libunibreak, libass, cjson, libmicrohttpd, mbedtls, librist, libssh, libvidstab, libvpx, openjpeg, opus, openldap, rtmpdump, curl, cargo-c, rav1e, libsamplerate, flac, mpg123, libsndfile, rubberband, sdl2, snappy, srt, svt-av1, leptonica, libarchive, pango, tesseract, x264, asciidoctor, gnu-getopt, xmlto, zeromq and zimg
==> Installing ffmpeg dependency: llvm
==> cmake -G Ninja .. -DLLVM_ENABLE_PROJECTS=clang;clang-tools-extra;lld;lldb;mlir;polly -DLLVM_ENABLE_RUNTIMES=compiler-rt;libcxx;libcxxabi;libunw
Last 15 lines from /Users/lubo/Library/Logs/Homebrew/llvm/01.cmake:
-- Looking for lzma_easy_encoder in /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/lib/liblzma.tbd
-- Looking for lzma_easy_encoder in /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/lib/liblzma.tbd - found
-- Looking for lzma_lzma_preset in /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/lib/liblzma.tbd
-- Looking for lzma_lzma_preset in /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/lib/liblzma.tbd - found
CMake Error at /usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find LibLZMA (missing: LIBLZMA_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/FindLibLZMA.cmake:105 (find_package_handle_standard_args)
  /tmp/llvm-20240113-93815-cgri74/llvm-project-17.0.6.src/lldb/cmake/modules/LLDBConfig.cmake:52 (find_package)
  /tmp/llvm-20240113-93815-cgri74/llvm-project-17.0.6.src/lldb/cmake/modules/LLDBConfig.cmake:62 (add_optional_dependency)
  /tmp/llvm-20240113-93815-cgri74/llvm-project-17.0.6.src/lldb/CMakeLists.txt:37 (include)


-- Configuring incomplete, errors occurred!

**Comment by lubo99** [comment]
and this

These open issues may also help:
`llvm@16`'s version of `llvm-config` doesn't include the correct `-L` flag for `zstd` when passed `--link-static` on Apple-silicon-based Macs https://github.com/Homebrew/homebrew-core/issues/158534


but my mac is INTEL based no m1 or m2

**Comment by rom1v** [comment]
OK so this is not related to this issue. Maybe similar to #3578.

**Comment by lubo99** [comment]
did not help. what helped was complete uninstall of homebrew and install macports and then scrcpy and adb....

**Comment by lubo99** [comment]
> OK so this is not related to this issue. Maybe similar to #3578.

Now after i fixed problém Macbook I am trying to connect from Android phone running termux with installed 2.3.1 scrcpy however no mirror window is opened. Any idea why? I guess audio messages bla bla is not the problem . Problem is mirror window not opened from termux running on the phone

/data/data/com.termux/files/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 30.1 MB/s (66007 bytes in 0.002

DEBUG: [Audio] Buffer underflow, inserting silence: 188 samples
DEBUG: [Audio] Buffer underflow, inserting silence: 240 s
