### ISSUE TITLE
adb: error: cannot stat 'scrcpy-server.jar': No such file or directory

### ISSUE THREAD

**Issue by bluekuen** [Genymobile/scrcpy#448]
I'm using Windows 7. Downloaded the Windows 64 bit Version.
Added the Folder to C:\Programs\scrcpy.
Added the Path of the Folder to my Path Environment Variable.
Now when i try to execute it, it doesn't find the jar. Can you please help me? 

That's the cmd output:

C:\Users\bluekuen>scrcpy --serial ad0617232e52f2d9a9
adb: error: cannot stat 'scrcpy-server.jar': No such file or directory
ERROR: "adb push" returned with value 1
Press any key to continue...

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/issues/278#issuecomment-429330345

> The problem is that `scrcpy` pushes the `scrcpy-server.jar` that it finds in `.` (your current directory). If you start `scrcpy` from `PATH`, it expects `scrcpy-server.jar` to be in `.`, i.e. the current directory, the one from where you call (the Windows version is "portable", it [overrides](https://github.com/Genymobile/scrcpy/blob/v1.4/Makefile.CrossWindows#L60) the [server path](https://github.com/Genymobile/scrcpy/blob/v1.4/app/src/server.c#L24-L30)).
>
> If you want your `scrcpy-server.jar` to be in a directory other than `.`, you need to give its full path in the env variable `SCRCPY_SERVER_PATH`.

**Comment by bluekuen** [comment]
Thanks for the fast answer. Unfortunately i don't get it. 
I don't have and don't want the scrcpy-server.jar in another directory. It's in the same directory as the other files. Or do i need to copy it in another directory and provide the SCRCPY_SERVER_PATH env variable?

**Comment by rom1v** [comment]
> I don't have and don't want the scrcpy-server.jar in another directory.

In a directory other than `.`, i.e. the directory you are currently in (`C:\Users\bluekuen` in your example).

**Comment by bluekuen** [comment]
Thank you so much @rom1v i accidentally named it SCRCPY_SERVER_JAR.
Now it's working! :+1:

**Comment by aashutoshrathi** [comment]
`SCRCPY_SERVER_PATH` was needed it my case too.
Thanks! @bluekuen

**Comment by bluekuen** [comment]
Nice to hear, sometimes it's the small things ! :)

**Comment by yaaangzh** [comment]
thanks！！I have the same problem
