### ISSUE TITLE
Aborted when launching scrcpy server through app_process

### ISSUE THREAD

**Issue by codematrixer** [Genymobile/scrcpy#4481]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: macOS
 - scrcpy version: v2.1.1
 - device model: samsungSM-G977N
 - Android version: 12

**Describe the bug**
Aborted when launching scrcpy server through this command. There is no additional log output.

```
adb -s R3CM7099XKZ shell CLASSPATH=/data/local/tmp/scrcpy-server-v2.1.1.jar app_process / com.genymobile.scrcpy.Server 2.1.1 log_level=info max_size=1080 max_fps=15 video_bit_rate=1300000 tunnel_forward=true send_frame_meta=false control=true audio=false stay_awake=true power_off_on_close=false clipboard_autosync=false
```
<img width="1284" alt="image" src="https://github.com/Genymobile/scrcpy/assets/21055620/fed3f8f3-4964-4e49-a07a-0b6786970ff5">

Supplementary information:
```
adb -s R3CM7099XKZ shell ls -l /data/local/tmp/
```
<img width="683" alt="image" src="https://github.com/Genymobile/scrcpy/assets/21055620/c1a53dc7-6219-4e4d-974e-358a3829704b">

**Comment by rom1v** [comment]
On some devices, I think app_process crashes if there are more than 256 chars :/ Could you check if it works with less parameters?

**Comment by PixelMatrixer** [comment]
After analyzing the phone's system log, it was found that the scrcpy-server-v2.1.1.jar file was corrupted. After re-uploading the file, the issue was resolved.

thanks.
