### ISSUE TITLE
Can't control device

### ISSUE THREAD

**Issue by fundokukiri** [Genymobile/scrcpy#4482]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Archlinux]
 - scrcpy version: [ v2.2.1]
 - installation method: [sudo pacman -S scrcpy]
 - device model: Mi 9T Pro aka K20 Pro
 - Android version: [11]

**Describe the bug**
I can't control my Android device but the image and sound are still available.

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
scrcpy --power-off-on-close --tcpip=192.168.0.2:5555 --shortcut-mod=lctrl --prefer-text

scrcpy v2.2 <https://github.com/Genymobile/scrcpy>
INFO: Connecting to 192.168.0.2:5555...
INFO: Connected to 192.168.0.2:5555
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 200.2 MB/s (64363 bytes in 0.000s)
[server] INFO: Device: [Xiaomi] Xiaomi Mi 9T Pro (Android 11)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 23.2.1-arch1.2
INFO: Trilinear filtering enabled
INFO: Texture: 1080x2336
```

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy#prerequisites
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work
