### ISSUE TITLE
The screen does not appear without any error

### ISSUE THREAD

**Issue by nekan1** [Genymobile/scrcpy#4499]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
- OS: Windows 10
- scrcpy version: 2.3.1
- installation method: Windows Build 64bit
- device model: samsung SM_G986N
- Android version: 13

**Describe the bug**

The screen does not appear without any error

PS D:\python> scrcpy
INFO: ADB device found:
C:\adb\scrcpy-server: 1 file pushed, 0 skipped. 16.1 MB/s (66007 bytes in 0.004s)
[server] INFO: Device: [samsung] samsung SM-G986N (Android 13)
PS D:\python>

**Comment by rom1v** [comment]
@lbuse Does it work better over USB?

If not, could you please try to run a "Hello world" as a java process on your device: https://blog.rom1v.com/2018/03/introducing-scrcpy/#run-a-java-main-on-android

**Comment by lbuse** [comment]
Yes, USB is working, but over Wi-Fi, it doesn't. 
The console app appears, but the screen never shows up, requiring me to force quit.

scrcpy --serial 93e56735 -Vdebug     
scrcpy 2.3.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  93e56735                        device  ONEPLUS_A5000
INFO:         (tcpip)  192.168.0.121:5555              device  ONEPLUS_A5000
DEBUG: Device serial: 93e56735
DEBUG: Using server: /opt/homebrew/Cellar/scrcpy/2.3.1/share/scrcpy/scrcpy-server
/opt/homebrew/Cellar/scrcpy/2.3.1/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 149.8 MB/s (66007 bytes in 0.000s)
[server] INFO: Device: [OnePlus] OnePlus ONEPLUS A5000 (Android 10)
[server] WARN: Audio disabled: it is not supported before Android 11
[server] DEBUG: Audio encoder stopped
DEBUG: Server connected
DEBUG: Starting controller thread
DEBUG: Starting receiver thread
INFO: Renderer: metal
DEBUG: Trilinear filtering disabled (not an OpenGL renderer
DEBUG: Using icon: /opt/homebrew/Cellar/scrcpy/2.3.1/share/icons/hicolor/256x256/apps/scrcpy.png
DEBUG: Demuxer 'video': starting thread
DEBUG: Demuxer 'audio': starting thread
WARN: Demuxer 'audio': stream explicitly disabled by the device
[server] DEBUG: Using video encoder: 'OMX.qcom.video.encoder.avc'
INFO: Texture: 1080x1920
DEBUG: User requested to quit
DEBUG: quit...
DEBUG: Demuxer 'video': end of frames
DEBUG: Receiver stopped
[server] DEBUG: Controller stopped
[server] DEBUG: Device message sender stopped
WARN: Killing the server...
DEBUG: Server disconnected
DEBUG: Server terminated

**Comment by rom1v** [comment]
Does `adb shell` work when connected over tcp/ip?

**Comment by nekan1** [comment]
@rom1v  
I found the reason, our company security policy block the adb. 
I think there is no way to through it, Thank  you guys.

**Comment by lbuse** [comment]
Yeah, I believe it is something similar for me. I was at the office where there is pfSense; now at home with OPNsense, it's working correctly.

**Comment by nekan1** [comment]
closed
