### ISSUE TITLE
crashes Clockworkmod Tether

### ISSUE THREAD

**Issue by hafkari** [Genymobile/scrcpy#450]
scrcpy has a conflict with Clockworkmod Tether and makes both apps crash ( win10 + usb ). I can run vysor and Clockworkmod Tether run together  with no problem.

**Comment by rom1v** [comment]
> scrcpy has a conflict with Clockworkmod Tether and makes both apps crash ( win10 + usb )

Do you have any logs, either in the console or in the output of `adb logcat`?

Just for info, tethering is available natively on Android, what does _Cockworkmod Tether_ do that the native tethering do not?

**Comment by hafkari** [comment]
Cell phone  operators allow 500 kb/s or less for tethering. Clockworkmod
Tether bypasses this limitation. I get full speed. 3-7 Mb/s for downloads.
I don't have log files. I don't know scrcpy option to keep log file. if
there is method let me know and I will do it.

**Comment by rom1v** [comment]
> Cell phone operators allow 500 kb/s or less for tethering. Clockworkmod Tether bypasses this limitation. I get full speed. 3-7 Mb/s for downloads.

Ok :+1:

> I don't have log files.

There is no file, just look at the console.

Anyway, if it happens with scrcpy, it will probably happen with adb allne. For example, if Clockworkmod tether uses adb, it needs to be the very same version (otherwse adb will restart its daemon, killing the other).

Start your tethering, then (I assume you use Windows) open a console (cmd.exe), go to the scrcpy directory, and execute `adb devices`. What is the result? Does it break your tethering?

**Comment by hafkari** [comment]
Here is what i got:

adb server version (32) doesn't match this client (40); killing...
could not read ok from ADB Server
* failed to start daemon
adb: error: failed to get feature set: cannot connect to daemon
ERROR: "adb push" returned with value 1
Press any key to continue...

**Comment by rom1v** [comment]
OK, so that's it: Clockworkmod Tether uses an old adb (32), which is different from the one in the scrcpy release (40).

Just override `adb.exe` and `Adb*.dll` in the Clockworkmod Tether directory by those from the _scrcpy_ directory.

**Comment by hafkari** [comment]
it worked. Thanks so much
