### ISSUE TITLE
scrcpy messes with device network connection through USB

### ISSUE THREAD

**Issue by ItsJustTee** [Genymobile/scrcpy#4503]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10 Pro 64bit
 - scrcpy version: 2.3.1
 - installation method: zip folder on Github
 - device model: Samsung Galaxy A32 5G
 - Android version: 13

**Describe the bug**
When only connecting via USB, scrcpy messes with my phone's network connection when I do not use the wifi to mirror, only USB.

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
What do you mean by "messes with my phone's network connection" ?

What problem do you observe? Any error message?

**Comment by ItsJustTee** [comment]
I was busy playing Arena breakout when I noticed an increase in Ping when connecting to official servers.

**Comment by rom1v** [comment]
What makes you think that this is related to scrcpy?

**Comment by ItsJustTee** [comment]
In my head, I thought that scrcpy still needed the wifi to be able to mirror my phone.

**Comment by rom1v** [comment]
Not if is connected via usb.

**Comment by ItsJustTee** [comment]
Oh, my apologies. Closing this as a non-scrpy issue.

**Comment by ItsJustTee** [comment]
Ok so, screenshots of me mirroring a mobile game through scrcpy 
![image](https://github.com/Genymobile/scrcpy/assets/37266538/cc5b87ea-9a17-417a-a772-556c28b8813a)

**Comment by ItsJustTee** [comment]
Command line arguments in use:
```scrcpy -m 1024 -b 4M -t```

**Comment by rom1v** [comment]
The message "Reconnecting" is in your game, so if you mirror the screen with scrcpy, you see the message. It does not mean it is related to scrcpy.
