### ISSUE TITLE
win version compile error on Ubuntu 22.04.3 LTS

### ISSUE THREAD

**Issue by feiser2016** [Genymobile/scrcpy#4504]
- [ V] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ V] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - Ubuntu 22.04.3
 - scrcpy version: [e.g. 1.12.1]
 - scrcpy 2.3.1
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - When I execute ./release.sh, the following error occurs

------------------------------------------------------------------------------------------------------------------------------------------------------------------
Project name: scrcpy
Project version: 2.3.1
C compiler for the host machine: i686-w64-mingw32-gcc (gcc 10.0.0 "i686-w64-mingw32-gcc (GCC) 10-win32 20220113")
C linker for the host machine: i686-w64-mingw32-gcc ld.bfd 2.38
C compiler for the build machine: ccache cc (gcc 11.4.0 "cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
C linker for the build machine: cc ld.bfd 2.38
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86
Host machine cpu: i686
Target machine cpu family: x86
Target machine cpu: i686
Windows resource compiler: GNU windres (GNU Binutils) 2.38
Found Pkg-config: NO
Found CMake: NO
Run-time dependency libavformat found: NO 

app/meson.build:101:0: ERROR: Pkg-config binary for machine 1 not found. Giving up.

A full log can be found at /home/royole/zhangyf/scrcpy/build-win32/meson-logs/meson-log.txt
make: *** [release.mk:77：build-win32] 错误 1

----------------------------------------------------------------------------------------------------------------------------------------------------

**Describe the bug**
win32 version compilation failure may be because Pkg-config cannot be detected， But I remember that the previous version could be compiled and passed.

$ pkg-config --modversion libavformat
58.76.100

**Comment by yume-chan** [comment]
A workaround is changing `pkg-config` (on the left side of `=`) back to `pkgconfig`:

https://github.com/Genymobile/scrcpy/blob/c6ff78f4147ad5505b45cce8f1d6f44c8585a9b5/cross_win32.txt#L9

https://github.com/Genymobile/scrcpy/blob/c6ff78f4147ad5505b45cce8f1d6f44c8585a9b5/cross_win64.txt#L9

I don't know if it requires a newer version of meson, or is caused by other setup differences.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/commit/85a94dd4b563e961304b2d9082932c5c1cc2e582

Probably a meson version

**Comment by feiser2016** [comment]
The Meson build system
Version: 0.61.2

**Comment by feiser2016** [comment]
pkg-config--->pkgconfig

Build type: cross build
Project name: scrcpy
Project version: 2.3.1
C compiler for the host machine: i686-w64-mingw32-gcc (gcc 10.0.0 "i686-w64-mingw32-gcc (GCC) 10-win32 20220113")
C linker for the host machine: i686-w64-mingw32-gcc ld.bfd 2.38
C compiler for the build machine: ccache cc (gcc 11.4.0 "cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
C linker for the build machine: cc ld.bfd 2.38
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86
Host machine cpu: i686
Target machine cpu family: x86
Target machine cpu: i686
Windows resource compiler: GNU windres (GNU Binutils) 2.38
Found pkg-config: /usr/bin/i686-w64-mingw32-pkg-config (0.29.2)
Run-time dependency libavformat found: YES 60.16.100
Run-time dependency libavcodec found: YES 60.31.102
Run-time dependency libavutil found: YES 58.29.100
Run-time dependency libswresample found: YES 4.12.100
Run-time dependency sdl2 found: YES 2.28.5
Found CMake: NO
Run-time dependency libusb-1.0 found: NO (tried pkgconfig)

app/meson.build:114:4: ERROR: Dependency "libusb-1.0" not found, tried pkgconfig

**Comment by yume-chan** [comment]
Delete `app/prebuilt-deps/data` folder and try again.

**Comment by feiser2016** [comment]
@yume-chan , thanks , compile success.
