### ISSUE TITLE
Cant open

### ISSUE THREAD

**Issue by Y2Grs** [Genymobile/scrcpy#451]
The program is not working for me. When I launch "scrcpy.exe" it always says everytime:
* daemon started successfully
adb: error: failed to get feature set: no devices/emulators found
ERROR: "adb push" returned with value 1

My phone is connecting to my laptop fine, I can look through my files on my phone. I tried a lower res and lower bitrate, it still functions the same. I also manually added the file location to the PATH in the Environmental Variables. Whenever I launch the "adb.exe" file it shows me a quick command prompt full of text and then closes itself so I think that means the adb is working, I'm not sure how this works but this isn't working for me. I am in need of help.

**Comment by rom1v** [comment]
Open `cmd.exe`, go to the _scrcpy_ directory (`cd your_scrcpy_path`), then execute `adb devices`.

Is your device listed as connected? If not, did you correctly enabled _USB debugging_? Maybe you need a [driver](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#on-windows-my-device-is-not-detected).

**Comment by Y2Grs** [comment]
My device doesn't show up, from my Android device in my notifications it says "USB debugging connected" so I think it's good but what about under my USB preferences does it matter which one I select out of these choices:
File Transfer
USB Tethering
MIDI
PTP
No data transfer

But I actually think you're right about the drivers, my laptop says it failed to get the drivers everytime I plug in my device. I don't know how to fix that if possible.

**Comment by Y2Grs** [comment]
Ok so I've advanced my progress, I installed the correct driver for my Android onto my laptop and now when I type "adb devices" it shows my device but then it says "authorizing", I clicked ok on the thing that popped up on my phone I don't understand.

**Comment by Y2Grs** [comment]
I unplugged my phone and plugged it back in and now my device is authorized. Thank you rom1v for the help I am all set. A driver update fixed my problem.
