### ISSUE TITLE
Set initial resolution from 480x640

### ISSUE THREAD

**Issue by ajsedwards** [Genymobile/scrcpy#452]
Hi, how can I set the initial texture resolution?  It's setting to 480x640 and this is causing the layout to be a mess with a notification over the top of my password pattern, so I am unable to unlock the phone.  I have tried -m -c -b parameters.

Thanks.

**Comment by rom1v** [comment]
Initially, it mirrors at the device definition.

You can limit the size with `-m`.

For example, if your device is 1920×1080, you can mirror at 1600×900 with:

     scrcpy -m 1600

**Comment by ajsedwards** [comment]
Thanks for the quick reply!  There is nothing I can do to get it to use more than 480x640 and it is showing a tiny area of my screen.  I managed to get logged in by connecting over network because then the "select USB function" notification was not over the password pattern.  After unlocking I then connected back with USB.

How can I change the device definition?

**Comment by rom1v** [comment]
Is it a real device (or an emulator)?

The width and height are retrieved [here](https://github.com/Genymobile/scrcpy/blob/v1.8/server/src/main/java/com/genymobile/scrcpy/wrappers/DisplayManager.java#L20-L21).

What is the result of:

    adb shell wm size

**Comment by ajsedwards** [comment]
It's a real phone, Samsung Galaxy Note 3. Running adb shell wm size returns "Physical size: 640x480".  Can I override this somehow?  The phone has a 1080x1920 display.

**Comment by rom1v** [comment]
OK, so the device does not report its size.

You an edit the source code to force your values [here](https://github.com/Genymobile/scrcpy/blob/v1.8/server/src/main/java/com/genymobile/scrcpy/wrappers/DisplayManager.java#L20-L21) (or [here](https://github.com/Genymobile/scrcpy/blob/v1.8/app/src/device.c#L17-L20) if you just want to change the client).

**Comment by ajsedwards** [comment]
Thanks, I issued this to set the size:
adb shell wm size 1080x1920

However after doing that the screen is jumbled.

**Comment by ajsedwards** [comment]
Resolved with:
adb shell size 1280x720
adb shell density 320
scrcpy

For some reason if I try to set size 1920x1080 then check what's set, it won't take 1920 and instead sets 1280x960 which isn't 16:9.

Well something seems screwed up with adb not getting the correct device profile.  Thanks for the help!

**Comment by rom1v** [comment]
> Well something seems screwed up with adb not getting the correct device profile.

(it's not adb, it's in your device rom, adb just gives a shell to get access to the value)

**Comment by olxclone** [comment]
ypu can incresae the max size by typing scrcpy -m 1950

**Comment by olxclone** [comment]
You can increase the max size by typing scrcpy -m 1950

**Comment by willbatista17** [comment]
Ask me a question, the screen resolution of my cel is 2400 x 1980 and my monitor is QHD.
And I would like to know if I can leave my resolution in QHD too and how to do it if there is a way ?
