### ISSUE TITLE
'man scrcpy' shows a `‐` instead of a `-`, causing errors

### ISSUE THREAD

**Issue by Ganton** [Genymobile/scrcpy#4528]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Kubuntu 23.10
 - scrcpy version: 1.25
 - installation method: apt
 - device model: [it does not matter]
 - Android version: [it does not matter]

**Describe the bug**

If the user executes `man scrcpy`, copies the `--disable‐screensaver` text that is seen, and executes `scrcpy --disable‐screensaver`: an `scrcpy: unrecognized option '--disable‐screensaver'` error message is seen.

I attach a screenshot of what is seen when `man scrcpy` is executed and the user looks for `-`. It turns out that `‐` is not `-`:

![Screenshot man](https://github.com/Genymobile/scrcpy/assets/2103153/5cf6aaa0-1f6e-4bd8-92ab-9facb9edd833)

Edited: This a screenshot of the difference between both symbols (because after reporting this bug: in the bug description and title, Github has replaced the first symbol with the second):

![difference](https://github.com/Genymobile/scrcpy/assets/2103153/36e12f23-7786-4088-8e07-ce89ef19e378)

Thanks for scrcpy and its quality.

**Comment by rom1v** [comment]
Thank you for your report.

Fixed by cbce42336dce0bb4cd2c47ed7dfa56d40fc3aca1.

The result probably depends on your manpage viewer or locale. On my machine, it prints a normal `-` anyway. Here I copied the text from the manpage and pasted:

```
$ echo --disable-screensaver | hd
00000000  2d 2d 64 69 73 61 62 6c  65 2d 73 63 72 65 65 6e  |--disable-screen|
00000010  73 61 76 65 72 0a                                 |saver.|
00000016
```

But if I copy tour text from this issue:

```
$ echo --disable‐screensaver | hd
00000000  2d 2d 64 69 73 61 62 6c  65 e2 80 90 73 63 72 65  |--disable...scre|
00000010  65 6e 73 61 76 65 72 0a                           |ensaver.|
00000018
```
