### ISSUE TITLE
The cursos doesn't work, Only the image

### ISSUE THREAD

**Issue by xtz4u** [Genymobile/scrcpy#453]
Hi 

First of all thank you for this amazing tool.

My problem is that the cursos doesn't work and I can't control the cellphone, I'm Using the 1.8 version I also tried with the 1.7 my mobile is a xiaomi redmi 4x with android 7.1.2 the adb is well configured.

![imagen](https://user-images.githubusercontent.com/48500259/54246710-00f8c580-4504-11e9-9afb-71aec4767713.png)

**Comment by zonay** [comment]
![image](https://user-images.githubusercontent.com/1244856/54255321-4519b380-4560-11e9-8363-133a824ad44b.png)
here you go.
