### ISSUE TITLE
Audio Playback not working on 2.3.1

### ISSUE THREAD

**Issue by Muffinmaker2** [Genymobile/scrcpy#4535]
**Environment**
 - OS: Linux Mint Cinnamon
 - scrcpy version: newest version: 2.3.1
 - installation method: apt install scrcpy
 - device model: Samsung Galaxy s23 plus SM-S916B
 - Android version: Android 14

**Describe the bug**
So my Setup with version 1.21.1 before updating was my Phone hooked up to my Pc via USB and a pair of Bluetooth Headphones connected to my Phone. Then i open a terminal and type scrcpy to start the mirroring. Now i have my Phone screen mirrored onto my PC and have audio from my Phone. 

After i made a issue that --turn-screen-off was broken but i just had a older version installed, i removed the version 1.21.1 i had and got me the latest 2.3.1. But now after i got the new version and i start a mirror now the audio turns off. i was going through the wiki a little and couldnt find anything that could turn on audio, just to turn it off.

```
$ scrcpy
scrcpy 2.3.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  R5CW12PGC0T                     device  SM_S916B
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 11.9 MB/s (66007 bytes in 0.005s)
[server] INFO: Device: [samsung] samsung SM-S916B (Android 14)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 23.0.4-0ubuntu1~22.04.1
INFO: Trilinear filtering enabled

```

**Comment by rom1v** [comment]
> my Phone hooked up to my Pc via USB and a pair of Bluetooth Headphones connected to my Phone

If you disconnect your bluetooth headphones, is the audio correctly forwarded to the computer? (#4083)

If you want to keep audio on the phone (not forward it to the computer), just disable it:

```
scrcpy --no-audio
```

https://github.com/Genymobile/scrcpy/blob/master/doc/audio.md

**Comment by Muffinmaker2** [comment]
Disconnecting Headphones makes it work again and i dont need the --no-audio setting because the audio comes out of the phone as i want. But connecting the Headphones again, audio seems to be turned off again and only comes back by using the --no-audio setting. Maybe i just misunderstood the Wiki ¯\_(ツ)_/¯

```
No audio

To disable audio:

scrcpy --no-audio
```
Thought disable audio = No Audio at all
But when --no-audio means no audio out of the Pc Speakers i would then close this issue :)

**Comment by rom1v** [comment]
> because the audio comes out of the phone as i want

That's unexpected, it should be forwarded to the computer (unless it fails to capture). Try to start scrcpy when the earphones are disconnected maybe. In practice, scrcpy capture the "remote submix" source, how it behaves concretely is up to the device system ROM.

> But when --no-audio means no audio out of the Pc Speakers i would then close this issue :)

`--no-audio` means scrcpy does not capture audio (so it keeps playing on the phone), like `--no-video` means scrcpy does not capture video.

**Comment by Muffinmaker2** [comment]
After unplugging and plugging my speaker it fixed it self :). Thanks for the help
