### ISSUE TITLE
Unable to select candidate word by number key when input chinese character

### ISSUE THREAD

**Issue by alexyutmp** [Genymobile/scrcpy#4537]
- [ x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [MacOS]
 - scrcpy version: 
     - SDL: 2.28.1 / 2.28.2
     - libavcodec: 60.3.100 / 60.3.100
     - libavformat: 60.3.100 / 60.3.100
     - libavutil: 58.2.100 / 58.2.100
     - libusb: - / 1.0.26
 - installation method: [snap]
 - device model:
   - Oppo A55S
   - Redmi 4A/3S
 - Android version: [6, 11, 12]

**Describe the bug**
- Switch to GBoard IME
- type key on keyboard by this sequence "wode" 
    - Now there are are candidates appear (我的｜我得｜我｜沃德｜卧）  
    <img width="364" alt="截屏2023-12-16 09 30 49" src="https://github.com/Genymobile/scrcpy/assets/1712501/780ef782-11d0-439f-b6db-b77bbc22bf82">
- I want to select the second one which is word (我得）by pressing number 2 on keyboard

Resut:
- The first word (我的）plus number "2" inputed in Edit box instead of 我得
<img width="361" alt="截屏2023-12-16 09 31 17" src="https://github.com/Genymobile/scrcpy/assets/1712501/6de59b72-9738-403b-bce2-c2871471902b">

Other Info:
I tested with variant version of GBoard:
all have issue like this
I tested Sogou Input Method, the old version 7.X works like charm, but Android 12 device doesn't allow it to be installed

Does anyone know any IME work like Sougou IME old version?
If there is one, it would be the best workaround for non english user.

Thanks author for this great project!!

**Comment by rom1v** [comment]
Maybe try `scrcpy --raw-key-events`.

**Comment by nftbty** [comment]
因为输入法本身就是为触摸设计的，就没有键盘数字选词的功能。用GBoard试了一下，可以用方向键上下左右选词，空格上屏。目前Windows上有个AnLink，不知是基于scrcpy二次开发还是从头开发，可以使用系统自带输入法，原理是通过把PC输入的字符放到手机剪贴板，然后自动粘贴实现的。你可以看看macOS上有没有类似的二次开发的软件。其实这个功能我觉得scrcpy可以引入。
