### ISSUE TITLE
Using SDL_AndroidShowToast to display toast messages in the phone

### ISSUE THREAD

**Issue by ahteck5** [Genymobile/scrcpy#4539]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

With the support of SDL2.0 in the latest version of scrcpy 2.3.1, i tried to use sdl_androidshowtoast but i am unable to use compile with the error message "undefined references to ... ". I have however ensure that "SDL.h" is included. Any idea?

**Comment by rom1v** [comment]
Scrcpy uses SDL for the client side (which runs on the computer).

This SDL function is useful when your Android application uses SDL on the device.

**Comment by ahteck5** [comment]
I see. I wanted to display toast message to the device from a window scrcpy. Seems like SDL_ttf  or opengl are the only options. Thanks for the info!
