### ISSUE TITLE
Include an updated prebuild server copy

### ISSUE THREAD

**Issue by Dvlnst** [Genymobile/scrcpy#454]
Hi,

It would be nice to have an updated copy of prebuild server inside the project (with a static name). The process to install/update the app for people who build it from source (and don't want to build the server) would be easier.

Would it be possible?

Thanks for this awesome app.

**Comment by rom1v** [comment]
Sorry, I won't commit a prebuilt binary in the git repository.

However, the prebuilt server hosted on github has a deterministic name, so you could write a simple script (`update_server.sh`) in the root project directory:

```bash
#!/bin/bash
set -e
if [ $# != 1 ]
then
    echo "Syntax: $0 <version>" >&2
    exit 1
fi

version="$1"
wget "https://github.com/Genymobile/scrcpy/releases/download/$version/scrcpy-server-$version.jar" -O "scrcpy-server-$version.jar"
meson configure x -Dprebuilt_server=scrcpy-server-$version.jar
```

```
./update_server.sh v1.8
ninja -Cx
```

**Comment by Dvlnst** [comment]
I already have a similar script but I'm reading the current version from meson.build file:
$ grep -w 'version:' ./meson.build | cut -d"'" -f2
output: 1.8

Kind regards.
