### ISSUE TITLE
Is it possible to run scrcpy on an Android device to control another?

### ISSUE THREAD

**Issue by 7wells** [Genymobile/scrcpy#4553]
Hello!

Is it possible to run scrcpy on an Android device to control another? Thus, I could use my mobile phone to control my Fire TV.

Sorry if this is not the right way to ask and if this was already asked and answered before. I used the search function but did not find anything in this regard.

All the best for the coming year!

**Comment by soopacrucial** [comment]
Hi. It has infact been asked before. There are a couple of attempts out there by other developers to port this to android but in my experience they don't work at all, or if you can manage to get it to connect they have almost none of the numerous useful features the original has, and unfortunately they are not being maintained. My understanding is that the underlying graphic software components make developing an android-to-android version of scrcpy not as trivial as you might think. I dare say that if it was straighforward to port to android, Romain would have done it ages ago. ¯\_(ツ)_/¯

**Comment by rom1v** [comment]
Refs #100
