### ISSUE TITLE
In scrcpy2.3.1, the following two commands don't work properly on Android 14.

### ISSUE THREAD

**Issue by Helaer** [Genymobile/scrcpy#4555]
Using these two commands on Android 14, the video screen size after startup is incorrect.
scrcpy --lock-video-orientation=90   # 90° 
scrcpy --lock-video-orientation=270  # 270° 
![QQ截图20231231102641](https://github.com/Genymobile/scrcpy/assets/52807664/4720aa53-0472-4ce2-8378-a03cadc01234)
![QQ截图20231231102709](https://github.com/Genymobile/scrcpy/assets/52807664/3c1b25f0-0b0b-4d4e-839d-351f8bb2b6ca)

**Comment by rom1v** [comment]
Yes, this is broken in Android 14. #4011

**Comment by rom1v** [comment]
As a workaround, depending on your use case, you can use `--orientation=90` instead : https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#orientation
