### ISSUE TITLE
Select index of display to be mirrored?

### ISSUE THREAD

**Issue by LeeHeap** [Genymobile/scrcpy#456]
Is it possible (or would it be possible to add) the ability to select which android display is mirrored? 
For example on Samsung DeX compatible devices such as the S9, Note 9 and S10, DeX runs on another (usually external) display while the phone itself is still displaying as usual. I'd like to mirror the DeX/external display, however launching scrcpy only mirrors the phone display.
Thank you for this incredible tool!

**Comment by rom1v** [comment]
Yes, it would be great, but I don't know how.

See https://github.com/Genymobile/scrcpy/issues/397.

(closing as duplicate)
