### ISSUE TITLE
[Question] Would it be possible to use scrcpy to cast Motorola's Ready For?

### ISSUE THREAD

**Issue by bergamin** [Genymobile/scrcpy#4581]
Turns out the native desktop mode made by Motorola is quite slow. Scrcpy seems a lot faster to me, but what it shows on the PC screen is not mirrored from the phone's screen. Seems like it's a second launcher running in the background that the Windows app captures instead of a normal launcher.

Would scrcpy be able to capture something like this, or can it only capture exactly what's being shown on the screen?

Thanks

**Comment by bergamin** [comment]
There is indeed!

But the display command didn't work

![image](https://github.com/Genymobile/scrcpy/assets/14339291/ac7e3076-88a9-4ae1-919f-57a82846e054)

Running from the installation folder because just calling scrcpy, it wasn't recognised

The Ready For display is probably display id 14 (1920x1080)

**Comment by rom1v** [comment]
You're using an old version (2.0), where the option was named `--display` instead of `--display-id`. Use the latest version.

**Comment by bergamin** [comment]
It works!

![image](https://github.com/Genymobile/scrcpy/assets/14339291/0d1c32e8-7d0f-45cc-9ea7-4a23e8f77498)

Some controls don't work well like screen resizing, but my assumption was correct. Scrcpy is much faster and has much better image quality than their solution:

![image](https://github.com/Genymobile/scrcpy/assets/14339291/6049add8-b971-4e7d-8a74-7900a5eae286)

I can live with having to reach for their solution for resizing stuff and whatnot. Thank you very much!

About updating, I assumed it updated on its own because it doesn't have a UI. How do I update scrcpy? Should I manually download and install the new versions?

Thanks!

**Comment by bergamin** [comment]
Well, since the issue was resolved, I'll close this. But I'm still waiting for how to properly update scrcpy. I couldn't find it in the docs

Thanks, @rom1v.

**Comment by rom1v** [comment]
There is no update mechanism the app itself.

On Windows, you must download the new version and extract it.

To receive a notification on new releases, click on Watch > Custom > Releases on the top of the github page.

**Comment by bergamin** [comment]
Alright, thanks! I just saw there is a `winget` installation too. I'll uninstall my current installation, which was downloaded directly from here and start using winget to keep it updated

Thanks again, this helped a lot!

**Comment by skygate2012** [comment]
Did you find a way to display the desktop mode without launching Ready For? I'll have to connect Ready For first then scrcpy for the extra display to be on.

**Comment by bergamin** [comment]
@skygate2012, no. I couldn't find a way of doing that. So you will either be stuck with the lag from Ready For (now called Smart Connect) or call the virtual display from scrcpy after launching it through Ready For, so having two windows showing the same thing essentially. There are a few things that don't work very well through scrcpy though, so you may still have to use the native one from time to time
