### ISSUE TITLE
Exist a way to do pc -> Android?

### ISSUE THREAD

**Issue by Legnatbird** [Genymobile/scrcpy#4583]
- [ ] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Mirroring my pc screen/audio to my android

**Describe alternatives you've considered**

**Additional context**

**Comment by rom1v** [comment]
Not scrcpy.
