### ISSUE TITLE
No connection could be made because the target machine actively refused it. (10061)

### ISSUE THREAD

**Issue by YousefEr** [Genymobile/scrcpy#4591]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**
When i write (adb connect (IP) it give me a code block

On errors, please provide the output of the console (and `adb logcat` if relevant).
No connection could be made because the target machine actively refused it. (10061)

Please paste terminal output in a code block.
cannot connect to (IP) No connection could be made because the target machine actively refused it. (10061)

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
See #1319

**Comment by YousefEr** [comment]
it was working when i download the scrcpy. or it can be the wifi for this is not working
