### ISSUE TITLE
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

### ISSUE THREAD

**Issue by YousefEr** [Genymobile/scrcpy#4594]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**
When i connect it give me a block code.

Please paste terminal output in a code block.
`cannot connect to 192.168.1.147:5555: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (10060)

or it can be the wifi because that it is not working

**Comment by rom1v** [comment]
Please stop duplicating your own issues: #4591 #4592

Are your device and your computer on the same network?

The problem is not specifically related to scrcpy, so you should search on stackoverflow: https://stackoverflow.com/questions/33462720/adb-unable-to-connect-to-192-168-1-105555

**Comment by YousefEr** [comment]
I try the (adb tcpip 5555) but it dont work and i will see in the website and if it worked in the website i will close the issue

**Comment by YousefEr** [comment]
it worked but it is lag

**Comment by rom1v** [comment]
If your network does not support the bandwidth, reduce the bitrate/resolution (`scrcpy -b2M -m1024`).
