### ISSUE TITLE
scrcpy run with green screen on mac

### ISSUE THREAD

**Issue by xiazhibin** [Genymobile/scrcpy#4595]
scrcpy it can run but the output is just green scrren, mouse click can affect the remote machine

╰─$ scrcpy -v
scrcpy 2.3.1 <https://github.com/Genymobile/scrcpy>

Dependencies (compiled / linked):
 - SDL: 2.28.5 / 2.28.5
 - libavcodec: 60.3.100 / 60.31.102
 - libavformat: 60.3.100 / 60.16.100
 - libavutil: 58.2.100 / 58.29.100
 - libusb: - / 1.0.26

**Comment by rom1v** [comment]
If you record (`scrcpy --record=file.mp4`), is the recorded file also green?

**Comment by xiazhibin** [comment]
Yes, it is green with record. 
I try scrcpy --list-encoders

**Comment by rom1v** [comment]
Yes, try with another encoder then.
https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#encoder

**Comment by xiazhibin** [comment]
I have try all encoder list by device , --video-codec=h264 --video-encoder='c2.android.avc.encoder' this work one time, I retry with --video-codec=h264 --video-encoder='c2.android.avc.encoder' , it still green

**Comment by xiazhibin** [comment]
╰─$ scrcpy   --video-codec=h264 --video-encoder='c2.android.avc.encoder' --record=/Users/xiazhibin/Downloads/file.mkv
scrcpy 2.3.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     --> (tcpip)  192.168.105.137:5555            device  ARC_AL00
/usr/local/Cellar/scrcpy/2.3.1/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 41.1 MB/s (66007 bytes in 0.002s)
[server] INFO: Device: [HUAWEI] HUAWEI ARC-AL00 (Android 12)
INFO: Recording started to matroska file: /file.mkv
INFO: Renderer: metal
INFO: Texture: 464x464
INFO: Recording complete to matroska file: /file.mkv
WARN: Killing the server...

**Comment by rom1v** [comment]
Oh, it's a watch.

Please post the recorded `file.mkv`.

With `screenrecord` (without scrcpy), does it work better:

```
adb shell screenrecord /sdcard/file.mp4
adb pull /sdcard/file.mp4
```

?

**Comment by xiazhibin** [comment]
There is output:
/system/bin/sh: screenrecord: inaccessible or not found

**Comment by xiazhibin** [comment]
I use ffmpeg to check the output video, it just 5kb/s bitrate ....

**Comment by rom1v** [comment]
> Yes, it is green with record.

The problem is the device encoder.

You might try with a size multiple of 32: `scrcpy -m 448`, but it will probably not work any better.

**Comment by xiazhibin** [comment]
😭nothing change with `scrcpy -m 448` still green
