### ISSUE TITLE
Failed to Update scrcpy-server File on Android Side

### ISSUE THREAD

**Issue by Aliceljm1** [Genymobile/scrcpy#4599]
- [ yes] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ yes] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: 2.3.1
 - installation method:Windows release
 - device model:
 - Android version: 8

Issue Description:

**Compilation and Logging:**
Compiled the server side of scrcpy on Windows using Android Studio.
Added extensive logging and generated an APK file.
Renamed the APK to scrcpy-server and placed it in the execution directory.

**Issue with Logs:**
Upon launching scrcpy, the logs added in Android Studio's LogCat are not visible.

**Testing and Observations:**
Replaced the scrcpy-server file with a regular text file (renamed as scrcpy-server), and scrcpy still functioned normally.
Suspect continuous use of the initially adb-pushed file.
Could not locate the scrcpy-server.jar on the Android device. The documented default path for adb push is /data/local/tmp/scrcpy-server.jar, but no file was found there.

**Queries:**
How should the scrcpy-server.jar file be updated?
Is it feasible to use the compiled APK as scrcpy-server.jar after renaming its extension? Uncertainty about this method.

**Comment by rom1v** [comment]
The file is pushed every time scrcpy is started, and is unlinked ("removed") almost immediately once executed.

If you want to push your own file instead, set `SCRCPY_SERVER_PATH=/path/to/your/scrcpy-server`. When you start scrcpy, it will push this one instead.

**Comment by Aliceljm1** [comment]
It worked. Thank you very much. This project gave me a lot of inspiration.
