### ISSUE TITLE
crash while recording the screen

### ISSUE THREAD

**Issue by Kyle-Falconer** [Genymobile/scrcpy#460]
I'm experiencing a crash while using the screen record option.

```
$ scrcpy --record file.mp4
/usr/local/Cellar/scrcpy/1.6/share/scrcpy/scrcpy-server.jar: 1 file pushed. 3.6 MB/s (19464 bytes in 0.005s)
2019-03-14 16:49:26.738 scrcpy[45296:14163306] INFO: Initial texture: 1280x800
[mp4 @ 0x7f944183a400] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 105345448 >= 105344914
```

Here are the versions I'm using:
```
$ scrcpy --version
scrcpy 1.6

dependencies:
 - SDL 2.0.9
 - libavcodec 58.35.100
 - libavformat 58.20.100
 - libavutil 56.22.100
```

I'm on macOS 10.12.6 (16G1815)

**Comment by rom1v** [comment]
Is it reproducible, or did it happen only once?

**Comment by Kyle-Falconer** [comment]
It happened multiple times on a particular device. Every time I would try to record, it would go for a minute or two, then crash.

**Comment by rom1v** [comment]
Ah great, this will allow to find the cause :+1:

Just for info, could you reproduce with v1.8 too?

If you can, the first step is to find out whether the device generates non monotonic timestamps, or if the client does not associate timestamps with the correct packet.

Could you log the value of `pts` [here](https://github.com/Genymobile/scrcpy/blob/master/app/src/stream.c#L98) and [here](https://github.com/Genymobile/scrcpy/blob/master/app/src/stream.c#L218), please? (in a way we can differentiate the first from the second)

Then when it crashes, post the list of printed values.

Thank you for your help.

**Comment by rom1v** [comment]
@Kyle-Falconer Did you manage to get some logs?

**Comment by rom1v** [comment]
Does it work now?

**Comment by Kyle-Falconer** [comment]
@rom1v I no longer have access to the specific device I was using to make it crash in the first place, and since then I have not been able to reproduce the issue with a different device of the same type.

I'll close this issue for now, will re-open if I can reproduce it with logs.
