### ISSUE TITLE
Can i configure buffer to save on file

### ISSUE THREAD

**Issue by Echenique** [Genymobile/scrcpy#4606]
today when i run scrcpy command with flag --record the process save file every 256kb. Its possivel change it, or create a flag for it..

example: running commando to get only audio device, saving file every 8kb is ready... 

i try change 'private static final int MESSAGE_MAX_SIZE = 1 << 18; ' to '1 << 14' but dont work for this..

**Comment by rom1v** [comment]
Scrcpy uses ffmpeg (the library, not the command line tool), so file buffering is managed by ffmpeg.

If you want to flush every packet, you must probably pass a flag to ffmpeg (the library), which seems to be exposed as `-flush_packets` in the ffmpeg command line tool: https://stackoverflow.com/a/50576757/1987178

**Comment by Echenique** [comment]
i have tested 'ffmpeg' command, and works for me with flush_packets, but idk how pass it to library in scrcpy. any idea?

**Comment by rom1v** [comment]
You could try:

```diff
diff --git a/app/src/recorder.c b/app/src/recorder.c
index 9e0b33959..36f906e90 100644
--- a/app/src/recorder.c
+++ b/app/src/recorder.c
@@ -114,7 +114,13 @@ sc_recorder_write_stream(struct sc_recorder *recorder,
     } else {
         st->last_pts = packet->pts;
     }
-    return av_interleaved_write_frame(recorder->ctx, packet) >= 0;
+    bool ok = av_interleaved_write_frame(recorder->ctx, packet) >= 0;
+    if (ok) {
+        // flush
+        av_write_frame(recorder->ctx, NULL);
+    }
+
+    return ok;
 }
 
 static inline bool
```

**Comment by Echenique** [comment]
i'm try to get only audio output with this command:

`scrcpy --no-video --no-audio-playback --audio-buffer=200 --record=audio.opus`

i made this changes, but still recording each 256kb... and i also tried this too directly:

return av_write_frame(recorder->ctx, packet) >= 0;

but nothing change.

**Comment by rom1v** [comment]
Indeed, the change in https://github.com/Genymobile/scrcpy/issues/4606#issuecomment-1904776080 impacts video recording (it seems every frame is written immediately), but does not change audio recording buffering.

(btw `--audio-buffer=` is an unrelated playback option, you don't need it here)

**Comment by rom1v** [comment]
With any of these two lines:

```diff
diff --git a/app/src/recorder.c b/app/src/recorder.c
index 9e0b33959..b319a6d02 100644
--- a/app/src/recorder.c
+++ b/app/src/recorder.c
@@ -156,6 +162,8 @@ sc_recorder_open_output_file(struct sc_recorder *recorder) {
     // still expects a pointer-to-non-const (it has not be updated accordingly)
     // <https://github.com/FFmpeg/FFmpeg/commit/0694d8702421e7aff1340038559c438b61bb30dd>
     recorder->ctx->oformat = (AVOutputFormat *) format;
+    recorder->ctx->flush_packets = 1;
+    recorder->ctx->flags |= AVFMT_FLAG_FLUSH_PACKETS;
 
     av_dict_set(&recorder->ctx->metadata, "comment",
                 "Recorded by scrcpy " SCRCPY_VERSION, 0);
```

it writes more often.

If you also add https://github.com/Genymobile/scrcpy/issues/4606#issuecomment-1904776080, it seems it flushes every packet.

**Comment by Echenique** [comment]
perfect! now the file was saved every packet and i can stream file without gap. thank you so much
