### ISSUE TITLE
Letter doubling when using ^

### ISSUE THREAD

**Issue by RobinCouture** [Genymobile/scrcpy#4607]
- [Yes] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [Yes] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: 2.1.1
 - installation method: Windows release
 - device model:Samsung Galaxy S7
 - Android version: 8.1

**Describe the bug**
When putting ^ on a letter, the letter is doubled (i.e typing û results in uû)

**Comment by rom1v** [comment]
Use `scrcpy --prefer-text`: https://github.com/Genymobile/scrcpy/blob/master/doc/control.md#text-injection-preference
