### ISSUE TITLE
Got some problems when build the server

### ISSUE THREAD

**Issue by KzDog** [Genymobile/scrcpy#461]
I want to build the server in **Ubuntu 16.04**, firstly, I got the same problem like #458 ,then I use **meson 0.37** to build again, and another problem occurred: 
```
Meson encountered an error:
Could not detect Ninja v1.6 or newer
```
I find that when I run
```
# client build dependencies
sudo apt install make gcc pkg-config meson ninja-build \
                 libavcodec-dev libavformat-dev libavutil-dev \
                 libsdl2-dev
```
I just can install **ninja-build v1.5** , I can not get ninja v1.6 or newer version for **Ubuntu 16.04** , so how should I solve the problem?
Waiting for your response, thanks.

**Comment by rom1v** [comment]
I don't have Ubuntu 16.04 here, but when I tested, I just had to install a newer `meson` via `pip3`, I don't remember any problem with ninja (but maybe because now the new _meson_ requires a more recent _ninja_).

Anyway, you can probably install a newer _ninja-build_ from backports: https://packages.ubuntu.com/xenial-backports/ninja-build

**Comment by KzDog** [comment]
> I don't have Ubuntu 16.04 here, but when I tested, I just had to install a newer `meson` via `pip3`, I don't remember any problem with ninja (but maybe because now the new _meson_ requires a more recent _ninja_).
> 
> Anyway, you can probably install a newer _ninja-build_ from backports: https://packages.ubuntu.com/xenial-backports/ninja-build

Thanks for your help, I downloaded a newer _ninja-build_ and run _meson_ command successfully, but when I run _ninja_ command, a new problem come in process:
```
[32/33] 'Generating scrcpy-server with a custom command.'
FAILED: server/scrcpy-server.jar 
'/home/wanjiasheng/my_workspace/scrcpy/server/./scripts/build-wrapper.sh' '../../scrcpy/server/.' 'server/scrcpy-server.jar' 'release'

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type FileHasher using BuildSessionScopeServices.createFileSnapshotter().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```
This is my **gradle** information:
```
------------------------------------------------------------
Gradle 2.10
------------------------------------------------------------

Build time:   2016-01-26 15:17:49 UTC
Build number: none
Revision:     UNKNOWN

Groovy:       2.4.5
Ant:          Apache Ant(TM) version 1.9.6 compiled on July 20 2018
JVM:          1.8.0_191 (Oracle Corporation 25.191-b12)
OS:           Linux 4.4.0-21-generic amd64
```
So what should I do? Thanks.

**Comment by rom1v** [comment]
For simplicity, you should try with the [prebuilt server](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#prebuilt-server), it will not call gradle at all.

It weird, it didn't have all these problems when I built on 16.04 (but 16.04 is quite old, now).

**Comment by KzDog** [comment]
> For simplicity, you should try with the [prebuilt server](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#prebuilt-server), it will not call gradle at all.
> 
> It weird, it didn't have all these problems when I built on 16.04 (but 16.04 is quite old, now).

Alright, thanks for your help.

**Comment by KzDog** [comment]
> > For simplicity, you should try with the [prebuilt server](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#prebuilt-server), it will not call gradle at all.
> > It weird, it didn't have all these problems when I built on 16.04 (but 16.04 is quite old, now).
> 
> Alright, thanks for your help.

I have solved the problem and build the server successfully, it looks like a permission issue.
Run `sudo chmod -R 777` for some folders and then the problem did not appear again.
