### ISSUE TITLE
add an option to disable keyboard/mouse control

### ISSUE THREAD

**Issue by almaceleste** [Genymobile/scrcpy#462]
I use this tool to stream my games from android through streaming application on my linux pc. I do not need use keyboard and mouse control from pc to android at all. Moreover I am afraid that my account in the game can be banned due to suspicion in cheating.  

Could you add an option to disable keyboard/mouse support.

**Comment by npes87184** [comment]
There is an option called `Read-only`.

To disable controls (everything which can interact with the device: input keys, mouse events, drag&drop files):

scrcpy --no-control
scrcpy -n

**Comment by almaceleste** [comment]
> There is an option called `Read-only`.
> 
> To disable controls (everything which can interact with the device: input keys, mouse events, drag&drop files):
> 
> scrcpy --no-control
> scrcpy -n

muchas gricias, amigo. I used the version 1.7 and it had not this option. now I have upgraded to the version 1.8 which have `--no-control` and I hope that is I want.

**Comment by Impr0ve** [comment]
I was able to fix this by adding the device IP to the incoming rules of Operating System and Network Noise I added the device IP and also in the quick settings used the block everything else and then in the connections I had to find the device IP and click allow for some reason also make sure force block incoming connections isn't enabled for those rules you added.
