### ISSUE TITLE
OTG mode , mouse right click not trigger BACK action

### ISSUE THREAD

**Issue by foobra** [Genymobile/scrcpy#4621]
- [√ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ √] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: macOS
 - scrcpy version: 2.3.1
 - installation method: brew
 - device model: Xiaomi 11
 - Android version: 13

**Describe the bug**
When I use normal mirror mode, right click act like BACK action.
But when I use --otg -K -M , right click not trigger BACK action, even if I add --forward-all-clicks .

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
Yes, there is no shortcut in otg mode (in normal mode, BACK is bound to "turn screen on or BACK", which is performed from the server on the device, and there is no server in otg mode since it works without adb).
