### ISSUE TITLE
Access denied finding property "qemu.sf.lcd_density" and Access denied finding property "odsign.verification.success"

### ISSUE THREAD

**Issue by Darshan-Saru** [Genymobile/scrcpy#4623]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 11
 - scrcpy version: 2.3.1 and 2.3
 - installation method: Windows release
 - device model: M2102J20SI
 - Android version: 12

**Describe the bug**
scrcpy 2.3 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)              50eda534            device  M2102J20SI
C:\Users\Dell\Downloads\scrcpy-win64-v2.3\scrcpy-win64-v2.... file pushed, 0 skipped. 86.7 MB/s (65851 bytes in 0.001s)
libc: Access denied finding property "odsign.verification.success"
[server] INFO: Device: [Xiaomi] POCO M2102J20SI (Android 12)
libc: Access denied finding property "qemu.sf.lcd_density"
libc: Access denied finding property "qemu.sf.lcd_density"
INFO: Renderer: direct3d
INFO: Texture: 1080x2400

and it crashes

**Comment by rom1v** [comment]
> and it crashes

What's the error message in the console when it "crashes"? (run from a terminal as explained [here](https://github.com/Genymobile/scrcpy/blob/master/doc/windows.md#run), do not run `scrcpy.exe` by double-clicking on it, otherwise it will close the terminal)

**Comment by Darshan-Saru** [comment]
after opening from terminal, it doesn't crash, Thanks
