### ISSUE TITLE
Scrcpy wont boot on mac - Blank icon

### ISSUE THREAD

**Issue by chpetersen** [Genymobile/scrcpy#463]
Hello when I try to boot scrcpy I just get a blank icon and nothing happens. My terminal looks just like scrcpy is running.

I have the following version:
scrcpy 1.8

dependencies:
 - SDL 2.0.9
 - libavcodec 58.35.100
 - libavformat 58.20.100
 - libavutil 56.22.100

No matter how long time i wait, nothing happens.
If I reboot it starts working again.

Attached screenshot
![Screenshot 2019-03-20 at 09 15 15](https://user-images.githubusercontent.com/7293201/54669129-e076cf80-4af0-11e9-8bf3-c2b79cb2c972.png)

**Comment by rom1v** [comment]
Check if there are errors on the device in the output of `adb logcat`.

**Comment by rom1v** [comment]
Also see #443.

**Comment by rom1v** [comment]
@chpetersen Any news?

**Comment by chpetersen** [comment]
For some reason it fixed it self. Will reopen if it happens again
