### ISSUE TITLE
Memory leak in function 'sc_adb_list_devices'

### ISSUE THREAD

**Issue by JoraGevorgyan** [Genymobile/scrcpy#4636]
The memory leak is found by a static analyzer developed at [CAST]( https://www.linkedin.com/company/cast-center/).

The memory allocated [in buf](https://github.com/Genymobile/scrcpy/blob/5a6b8310cae1e0741b4375ca760d9c8dd49822c4/app/src/adb/adb.c#L427) is not freed before [return](https://github.com/Genymobile/scrcpy/blob/5a6b8310cae1e0741b4375ca760d9c8dd49822c4/app/src/adb/adb.c#L461)

**Comment by rom1v** [comment]
Thank you. Fixed by 3333e67452e52a1e0cd1c68181067f9eccdeb582 on `dev` branch.
