### ISSUE TITLE
no video stream when control=true

### ISSUE THREAD

**Issue by jobala** [Genymobile/scrcpy#4637]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS:  Debian
 - scrcpy version: 2.3.1
 - installation method: manual
 - device model: emulator
 - Android version: 14

**Describe the bug**

I get the video stream when I run the command below

```
adb shell CLASSPATH=/data/local/tmp/scrcpy-server.jar \
    app_process / com.genymobile.scrcpy.Server 2.3.1 \
    tunnel_forward=true audio=false control=false cleanup=false \
    raw_stream=true max_size=1920
```

But I can't get a stream when I run the command 

```
adb shell CLASSPATH=/data/local/tmp/scrcpy-server.jar \
    app_process / com.genymobile.scrcpy.Server 2.3.1 \
    tunnel_forward=true audio=false control=true cleanup=false \
    raw_stream=true max_size=1920
```

The only difference between these two commands is specifying control=true

```
Please paste terminal output in a code block.
```

[server]: INFO: Device: [Google] emulator (android14)

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
If you enable control, the server awaits for another TCP connection for the control stream.

See https://github.com/Genymobile/scrcpy/blob/master/doc/develop.md#protocol

**Comment by jobala** [comment]
@rom1v thanks for getting back quickly. It is not clear from the documentation what I should do.

I did `adb forward `tcp:27813` `localabstract:scrcpy` are you saying I should forward another tcp port to `localabstract:scrcpy` and read/write to it?

**Comment by rom1v** [comment]
No, you keep redirecting only 1 port, but you connect to the server socket twice (so you get two sockets).

**Comment by jobala** [comment]
Ah I see, thanks. That worked.
