### ISSUE TITLE
Simulating Mouse Click Results In A Long Press

### ISSUE THREAD

**Issue by jobala** [Genymobile/scrcpy#4640]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Linux
 - scrcpy version: 2.3.1
 - installation method: manual
 - device model: emulator
 - Android version: 14

**Describe the bug**

I am simulating mouse click using the snippet below
```js
  public toBuffer(): Buffer {
    const buffer: Buffer = Buffer.alloc(TouchControlMessage.PAYLOAD_LENGTH + 1);
    let offset = 0;
    offset = buffer.writeUInt8(2, offset);
    offset = buffer.writeUInt8(0, offset); // DOWN
    offset = buffer.writeBigInt64BE(this.pointerId, offset);
    offset = buffer.writeUInt32BE(this.position.point.x, offset);
    offset = buffer.writeUInt32BE(this.position.point.y, offset);
    offset = buffer.writeUInt16BE(this.position.screenSize.width, offset);
    offset = buffer.writeUInt16BE(this.position.screenSize.height, offset);
    offset = buffer.writeUInt16BE(
      1,
      offset
    );
    offset = buffer.writeUint32BE(1, offset); // actionButtons
    offset = buffer.writeUint32BE(1, offset); // buttons
    return buffer;
  }
```

This results in a long press instead of a click

<img width="324" alt="Screenshot 2024-02-02 at 16 20 12" src="https://github.com/Genymobile/scrcpy/assets/12011447/4d4d1075-55ee-44e2-80e6-f88d7856c64f">

What am I doing wrong here?

**Comment by rom1v** [comment]
A click is one "press" (action down) event followed by a "release" (action up) event.

**Comment by jobala** [comment]
Ah I see thanks.
