### ISSUE TITLE
Adapt screen capture to future Android versions

### ISSUE THREAD

**Issue by rom1v** [Genymobile/scrcpy#4646]
In the future, we'll probably have to call `IDisplayManager.setDisplayIdToMirror()` (or not, to be investigated).

https://android.googlesource.com/platform/frameworks/base.git/+/1e8b7d543a63feb671ffef73064f414bbc85ba7b%5E%21/

**Comment by MemeCornucopia** [comment]
![image](https://github.com/Genymobile/scrcpy/assets/148788549/d0b35101-20a7-48fa-94ac-733a584de7f6)
I think that is the case now

**Comment by MemeCornucopia** [comment]
![image](https://github.com/Genymobile/scrcpy/assets/148788549/8ea85523-7c47-43c9-8850-c40d9327ee95)
I think that is the case now

**Comment by MemeCornucopia** [comment]
I cant use it with android 14 beta. after upgrading this happened

**Comment by DerekWuYD** [comment]
@rom1v\
Provide the #4657 ,this is a workaround we use internally at Google.
