### ISSUE TITLE
can't download scrcpy

### ISSUE THREAD

**Issue by xmokesmoke** [Genymobile/scrcpy#4647]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - scrcpy version: [e.g. 2.3.1]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:
 - Android version: [e.g. 10]

I cant download the scrcpy zip for windows 10 64bit. have tried everything but it won't download.

**Comment by rom1v** [comment]
I don't know what to say, the release is available here: https://github.com/Genymobile/scrcpy/blob/master/doc/windows.md

If you can't download, check your network configuration / firewall…

**Comment by jonnystaffs** [comment]
Sometimes Windows will block the download and say "This file is not commonly downloaded". You can click on the "i" and allow the download.
