### ISSUE TITLE
Frame drop on screen touch in pubg

### ISSUE THREAD

**Issue by StylishBoyGaming** [Genymobile/scrcpy#466]
when i touch the screen while playing pubg on android mobile it starts frame drops . please fix frame drops issue

**Comment by rom1v** [comment]
When you say "frame drop", does it freeze, or do you observe it by measuring the framerate?

If it freezes, try to replace SDL 2.0.9 by SDL 2.0.8 (see https://github.com/Genymobile/scrcpy/issues/425).

**Comment by StylishBoyGaming** [comment]
Its doesnt freeze ,there is only frame skip on realtime , when i touch my screen , i know it is due to packet delay variation ,,, can  you make help me

**Comment by rom1v** [comment]
> Its doesnt freeze ,there is only frame skip on realtime

How do you detect these "frame skip"? Intuitively or with some measurements?
Does it lag also on the device side when you touch the screen, or only in the scrcpy window?

> i know it is due to packet delay variation

If you touch the screen on the physical device, it probably just slows down your device while it processes the event, and is not able to render or encode or send fast enough. Which device is it?

**Comment by StylishBoyGaming** [comment]
frame skip only in scrcpy window only. and i am using redmi note 4

**Comment by rom1v** [comment]
[`scrcpy.exe` v1.8 with `skip_frames=false`](https://tmp.rom1v.com/scrcpy/issue466/1/scrcpy.exe)
_SHA256: dfe4c9e35b1d94b86e7294f0c002cafb1443c3c2805a1b9a8f400706bee99c46_

**Comment by StylishBoyGaming** [comment]
Thank You So Much

**Comment by rom1v** [comment]
Please tell me if that changes anything.

**Comment by StylishBoyGaming** [comment]
ok
