### ISSUE TITLE
Audio cracking during tcpip playback

### ISSUE THREAD

**Issue by Amrit-codes** [Genymobile/scrcpy#4668]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Arch]
 - scrcpy version: [2.3.1]
 - installation method: [pacman]
 - device model: [Samsung S21 FE]
 - Android version: [14]

**Audio Cracking**
When I am playing back audio using a tcpip connection, the audio is cracking. I have tried using audio buffer, audio bitrate, audio output buffer and audio codec flags. No such issue when playing back from usb connection

**Comment by rom1v** [comment]
Try `scrcpy --audio-buffer=1000`, it will add 1 second delay (1000ms). Do you still have audio glitches?

Now reduce the value until you get something working with minimal delay.

**Comment by Amrit-codes** [comment]
Thanks! 
That seems to have worked
