### ISSUE TITLE
Improve `server connection failed` error message

### ISSUE THREAD

**Issue by igorwojda** [Genymobile/scrcpy#4669]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Be more explicit with error message. Rather that showing "server connection failed" error check if there are valid adb devices and show "no devices connected error". 

**Additional context**
Current error
<img width="508" alt="image" src="https://github.com/Genymobile/scrcpy/assets/530122/8da8bcd7-f509-44c7-b47d-80cc2d2887dc">

**Comment by rom1v** [comment]
> show "no devices connected error".

That's basically the message "Could not find any ADB device".
