### ISSUE TITLE
Support Android < 21

### ISSUE THREAD

**Issue by freitzzz** [Genymobile/scrcpy#4679]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**

Support Android API lower than 21

**Describe the solution you'd like**

Hi @rom1v and community
I've been using scrcpy over the years and my feedback is always good and grateful that this tool exists!
Now back to my main question, I have a bunch of old Androids that run great in lower APIs (19 and 20), however scrcpy is not supported in these versions. I would like to know why it doesn't, because I'm willing to put the effort of forking the repo and making it work for lower APIs.

**Describe alternatives you've considered**

I don't want to flash LOS or AOSP on these devices because they run great on stock OS!

**Additional context**

N/A

**Comment by rom1v** [comment]
> I have a bunch of old Androids that run great in lower APIs (19 and 20), however scrcpy is not supported in these versions. I would like to know why it doesn't

See #98

**Comment by freitzzz** [comment]
Thanks a lot! I've seen your feedback about making scrcpy to work with older API versions, but will not quit trying to get a remote screen on my oldies :smiley:
