### ISSUE TITLE
Command to show FPS

### ISSUE THREAD

**Issue by Gapplay** [Genymobile/scrcpy#468]
> A command line option (`--print-fps`) could be added to enable it on start.

https://github.com/Genymobile/scrcpy/pull/418#issuecomment-475664365

**Comment by rom1v** [comment]
Thank you for the feature request.

However, I quickly checked, with `--no-display` (while recording), the frames are not counted because they are not even decoded. So this won't fit your needs.

**Comment by Gapplay** [comment]
no problem, The command could be still useful to show fps without pressing ctrl+i.

**Comment by RaenonX** [comment]
When will this command option becomes available? It seems that as of now (v1.14), this is still not yet supported.

**Comment by rom1v** [comment]
There is no such option yet. Why do you need it in practice? (you could just press Ctrl+i)

**Comment by RaenonX** [comment]
I use a batch file to start this every time. I know that I can press Ctrl+I
to start it. But if I want to track the FPS every time I use the app, then
I will need to press Ctrl+I every time I start it.
If this option is available, then I can simply start my bat file, then
focus onto the other window, no need to Ctrl+I.

**Comment by RaenonX** [comment]
> Implemented by #3030.

Thanks for implementing this 2 yr 11 mo-old baby!
