### ISSUE TITLE
sound is cutting in wireless mode

### ISSUE THREAD

**Issue by ahmeteid7** [Genymobile/scrcpy#4681]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [ Debian. zorin lite xfce(xubuntu20,04)]
 - scrcpy version: [3.2]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**
scrcpy sound in wirless mode is cutting ,but i work good in usb mode

**Comment by rom1v** [comment]
Increase the value of `--audio-buffer`.
