### ISSUE TITLE
audio forwarding not working on OPPO A92 android 11

### ISSUE THREAD

**Issue by ELLsanity** [Genymobile/scrcpy#4684]
PLEASE HELP!

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/doc/audio.md

**Comment by ELLsanity** [comment]
already tried that theres no audio, im not very good using this platform

**Comment by rom1v** [comment]
What is the full output in the console?

**Comment by ELLsanity** [comment]
the only problem was there was no audio then after trying the --require-audio , device now wont connect...
is there a way to reset scrcpy?

**Comment by rom1v** [comment]
What is the full output in the console (copy-paste the output when you [run it from a terminal](https://github.com/Genymobile/scrcpy/blob/master/doc/windows.md#run))?

**Comment by ELLsanity** [comment]
it connects and now disconnects unlike before the only issue was audio:

scrcpy 2.3.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)              debcd6f8            device  CPH2059
C:\Users\Acer\Desktop\Mundo\scrcpy-win64-v2.3.1\scrcpy-win... file pushed, 0 skipped. 32.6 MB/s (66007 bytes in 0.002s)
[server] INFO: Device: [OPPO] OPPO CPH2059 (Android 11)
INFO: Renderer: direct3d
INFO: Texture: 1080x2400
WARN: Device disconnected
Press Enter to continue...

**Comment by rom1v** [comment]
> it connects and now disconnects

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#device-disconnected

>  unlike before the only issue was audio

Did you read https://github.com/Genymobile/scrcpy/blob/master/doc/audio.md?

> For Android 11, you'll need to ensure that the device screen is unlocked when starting scrcpy. A fake popup will briefly appear to make the system think that the shell app is in the foreground. Without this, audio capture will fail.

**Comment by ELLsanity** [comment]
yes i read that but after the problem only happened after trying the --require audio now it disconnectsthe mirroring..

scrcpy 2.3.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)              debcd6f8            device  CPH2059
C:\Users\Acer\Desktop\Mundo\scrcpy-win64-v2.3.1\scrcpy-win... file pushed, 0 skipped. 36.8 MB/s (66007 bytes in 0.002s)
[server] INFO: Device: [OPPO] OPPO CPH2059 (Android 11)
INFO: Renderer: direct3d
INFO: Texture: 1080x2400
ERROR: Demuxer 'audio': stream disabled due to connection error
WARN: Device disconnected
Press Enter to continue...

plus the folder cannot be deleted / extracting new files from zip has errors...
how do i reset this, very frustrating, please help

**Comment by rom1v** [comment]
> yes i read that but after the problem only happened after trying the --require audio now it disconnectsthe mirroring..

If you `--require-audio` and that audio does not work, that fails (as expected).

> yes i read that

So when you start scrcpy, your device is unlocked, correct?

> plus the folder cannot be deleted / extracting new files from zip has errors...

That's a common Windows issue: if some program is running in a folder, you can't delete the file or the folder (contrary to Linux or macOS for example).

In your case, it's probably `adb.exe`. Kill it from your process manager, or execute `adb kill-server`.

**Comment by ELLsanity** [comment]
the device is unlocked, yes.
for some reason the device now shows as unspecified on control panel...
do i need adb drivers or something?
