### ISSUE TITLE
Is there a way to mirror android Screen without the need to enable USB DEBUGGING 

### ISSUE THREAD

**Issue by deynACB** [Genymobile/scrcpy#4685]
Good day! Is there a possible way to run scrcpy without the need to enable USB DEBUGGING. Some of my apps crash when that function is enabled on my Device (Xiaomi Pad 6). Thank you!

**Comment by rom1v** [comment]
> Good day! Is there a possible way to run scrcpy without the need to enable USB DEBUGGING.

No, only OTG mode (for keyboard and mouse) works without USB debugging, not mirroring.
