### ISSUE TITLE
Mirror PC screen to Android

### ISSUE THREAD

**Issue by xHybred** [Genymobile/scrcpy#4692]
Basically the opposite of what it's currently doing. I want to use my PC on my phones screen but with minimal input lag. The only current option for this is streaming which degrades quality and introduces latency. 

This app seems like a great candidate for this & would be extremely useful for me.

**Comment by rom1v** [comment]
> Basically the opposite of what it's currently doing.

That would be a totally different project technically.

Spoiler: at work, I'm working on a project which does this (and more, this is not just a standalone app to execute like scrcpy). It has been presented by j-b recently: https://www.youtube.com/watch?v=0RvosCplkCc
At 4:16, you can see an Android client mirroring a Windows server.

Not released yet.

**Comment by xHybred** [comment]
I honestly thought the process of mirroring pc to android would basically be the same as it is mirroring android to pc, are you saying it's not? Why wouldn't it be? I only suggested it because it seems easy to just do the opposite but if theirs more complexity & nuance to it then I understand why you haven't.

I'm looking forward to that app if it really allows wired zero latency mirroring, but I can't seem to find any resources which I can follow the development of the app. If you have any I'd be interested so I can be aware of when it releases

**Comment by rom1v** [comment]
> I honestly thought the process of mirroring pc to android would basically be the same as it is mirroring android to pc

Not the same APIs for capture, not the same APIs to encode, not the same windowing APIs, not the same APIs to render, not the same languages, not the same frameworks…
