### ISSUE TITLE
OPPO A92 CONNECTION PROBLEM

### ISSUE THREAD

**Issue by ELLsanity** [Genymobile/scrcpy#4693]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10 Pro 64 bit
 - scrcpy version: scrcpy-win64-v2.3.1
 - device model: OPPO A92
 - Android version: `11`

**Describe the bug**
when you connect the usb debugging enabled device it reads as audio source in device manager and in developers options, scrpy cant connect the device because its not adb device but when change to mtp in developers option then scrcpy reads it but then it disconnects, please help i need this badly thanks...

```
C:\Users\Acer\Desktop\Mundo\scrcpy-win64-v2.3.1>scrcpy -Vverbose
scrcpy 2.3.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)              debcd6f8            device  CPH2059
DEBUG: Device serial: debcd6f8
DEBUG: Using server (portable): C:\Users\Acer\Desktop\Mundo\scrcpy-win64-v2.3.1\scrcpy-server
C:\Users\Acer\Desktop\Mundo\scrcpy-win64-v2.3.1\scrcpy-ser... file pushed, 0 skipped. 22.3 MB/s (66007 bytes in 0.003s)
[server] INFO: Device: [OPPO] OPPO CPH2059 (Android 11)
DEBUG: Server connected
DEBUG: Starting controller thread
DEBUG: Starting receiver thread
[server] DEBUG: Using audio encoder: 'c2.android.opus.encoder'
[server] DEBUG: Using video encoder: 'OMX.qcom.video.encoder.avc'
INFO: Renderer: direct3d
DEBUG: Trilinear filtering disabled (not an OpenGL renderer
DEBUG: Using icon (portable): C:\Users\Acer\Desktop\Mundo\scrcpy-win64-v2.3.1\icon.png
DEBUG: Demuxer 'video': starting thread
DEBUG: Demuxer 'audio': starting thread
INFO: Texture: 1080x2400
[server] DEBUG: Failed to start audio capture, retrying...
DEBUG: Demuxer 'video': end of frames
ERROR: Demuxer 'audio': stream disabled due to connection error
DEBUG: Receiver stopped
WARN: Device disconnected
DEBUG: quit...
DEBUG: Server disconnected
DEBUG: Server terminated
```

**Comment by rom1v** [comment]
> WARN: Device disconnected

Failure to capture audio should not make the device disconnect.

Looks like there is a crash on the device or something.

Any relevant error in `adb logcat`?

**Comment by rom1v** [comment]
About USB disconnection: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#device-disconnected
