### ISSUE TITLE
scrcpy -b 2M se ejecuta sin audio

### ISSUE THREAD

**Issue by KINGZZTON** [Genymobile/scrcpy#4696]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
Which Android version? Which scrcpy version?

Why do you specify `-b 2M` in this issue? Do you have audio if you do not specify `-b 2M`?

**Comment by KINGZZTON** [comment]
copie el codigo directamente de la pagina para mejorar la calidad de imagen y lo ejecute como scrcpy -b 16M   y si me soluciona el problema de calidad de imagen pero no me captura audio

**Comment by rom1v** [comment]
Please write in English.

Which Android version? Which scrcpy version? What is the full console output?

**Comment by KINGZZTON** [comment]
scrcpy-win64-v2.3.1>scrcpy -b 16M
scrcpy 2.3.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)              1f89c973            device  M2101K6G
C:\Users\YAMID\Desktop\nueva version\scrcpy-win64-v2.3.1\s... file pushed, 0 skipped. 29.3 MB/s (66007 bytes in 0.002s)
[server] INFO: Device: [Xiaomi] Redmi M2101K6G (Android 13)
INFO: Renderer: direct3d
INFO: Texture: 1080x2400
INFO: Texture: 2400x1080

android 13 
scrcpy v2.3.1

**Comment by rom1v** [comment]
OK, everything looks fine. How is the volume level on your device?

If you record (`scrcpy --record=file.mp4`) and play with VLC, do you have audio?

What is the full output of `scrcpy -Vverbose`?

**Comment by KINGZZTON** [comment]
al parecer hay algunas interferencias al transmitir el audio y en ciertas aplicaciones ocupar funciones en las que se tenga que ocupar el microfono del dispositivo

**Comment by rom1v** [comment]
> al parecer hay algunas interferencias al transmitir el audio y en ciertas aplicaciones ocupar funciones en las que se tenga que ocupar el microfono del dispositivo

> Apparently there are some interferences when transmitting the audio and in certain applications occupying functions in which the device's microphone has to be used

#4084 #4087
