### ISSUE TITLE
PC screen mirroring to Android display

### ISSUE THREAD

**Issue by Nandor21** [Genymobile/scrcpy#4700]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

I've always wanted to look for a program that would run natively on linux and extend or at least mirror the pc display to older android devices, and control the mouse with touch etc, I don't know how it support the scrcpy this as I couldn't check, I'd appreciate if it works

The pc version would send the display of the pc on the android to an app (via usb or wifi) which would display it on the android device's display and send the touches to the pc

I'm dont know other alternatives for this solution

**Comment by rom1v** [comment]
#4692
