### ISSUE TITLE
Demuxer 'audio': stream disabled due to connection error

### ISSUE THREAD

**Issue by tingfengwanxiao** [Genymobile/scrcpy#4702]
when I Build everything from sources and I run it ,find problem
INFO: Renderer: direct3d
ERROR: Demuxer 'audio': stream disabled due to connection error
I find it same to https://github.com/Genymobile/scrcpy/issues/4656 ,I can't replace scrcpy-server you provide simply because I wan't change some file in server and compile myself scrcpy-server,so How can I change source to compile it sucessful to run.(PS:I needn't audio,can forbid it and only use video)

**Comment by 4332weizi** [comment]
I have the same problem, I installed it via brew.

Device: Pixel 7 Pro
System: Android 14 QPR3(API21.240119.009)

```
▶︎ scrcpy
scrcpy 2.3.1 <https://github.com/Genymobile/scrcpy>
* daemon not running; starting now at tcp:5037
* daemon started successfully
INFO: ADB device found:
INFO:     -->   (usb)  29281FDH300CV6                  device  Pixel_7_Pro
/opt/homebrew/Cellar/scrcpy/2.3.1/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 74.5 MB/s (66007 bytes in 0.001s)
[server] INFO: Device: [Google] google Pixel 7 Pro (Android 14)
INFO: Renderer: metal
INFO: Texture: 1080x2336
[server] ERROR: Exception on thread Thread[video,5,main]
java.lang.AssertionError: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
	at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:85)
	at com.genymobile.scrcpy.ScreenCapture.createDisplay(ScreenCapture.java:77)
	at com.genymobile.scrcpy.ScreenCapture.start(ScreenCapture.java:38)
	at com.genymobile.scrcpy.SurfaceEncoder.streamScreen(SurfaceEncoder.java:72)
	at com.genymobile.scrcpy.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-SurfaceEncoder(SurfaceEncoder.java:253)
	at com.genymobile.scrcpy.SurfaceEncoder$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
	at java.lang.Class.getMethod(Class.java:2937)
	at java.lang.Class.getMethod(Class.java:2449)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:83)
	... 6 more
WARN: Device disconnected
ERROR: Demuxer 'audio': stream disabled due to connection error
```

**Comment by rom1v** [comment]
@tingfengwanxiao What is the full output in the console?

@4332weizi #4656 #4657

**Comment by tingfengwanxiao** [comment]
Thank you .I reget msys64 and Installation it ,and solved!

**Comment by WFANG12719** [comment]
Same issuse on my Android 7.1.2 TV set-top box, here is the output: (btw, I have a very good visual contact from the box though, no voice transferred only)

already connected to 192.168.1.5:5555
scrcpy 2.3.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     --> (tcpip)        192.168.1.5:5555            device  p230
C:\scrcpy-win64-v2.3.1\scrcpy-server: 1 file pushed, 0 skipped. 73.9 MB/s (66007 bytes in 0.001s)
[server] INFO: Device: [Phicomm] Phicomm p230 (Android 7.1.2)
[server] WARN: Audio disabled: it is not supported before Android 11
INFO: Renderer: direct3d
WARN: Demuxer 'audio': stream explicitly disabled by the device
INFO: Texture: 1920x1080

**Comment by rom1v** [comment]
> Same issuse on my Android 7.1.2 TV set-top box

> WARN: Audio disabled: it is not supported before Android 11

As expected.
