### ISSUE TITLE
java.lang.NoSuchMethodException: startActivityAsUserWithFeature

### ISSUE THREAD

**Issue by anotheruserofgithub** [Genymobile/scrcpy#4704]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Ubuntu 18.04
 - scrcpy version: [uhid.27](https://github.com/Genymobile/scrcpy/commits/uhid.27) (based on 2.3.1)
 - installation method: manual
 - device model: custom ROM
 - Android version: 8.1

**Describe the bug**

Using the new `MOD+k` shortcut (in UHID) failed in [`ActivityManager.startActivityAsUserWithFeature()`](https://github.com/Genymobile/scrcpy/commit/fec2abe03e252d54166630ccca69a62cab94e5a0#diff-1a24c2089218479cebb925527de82f65d07d38a6f431158d6999d51117ce6598R457) with this backtrace:

```
$ scrcpy --keyboard=uhid --mouse=uhid
scrcpy 2.3.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  ***                      device  ***
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 4.2 MB/s (68615 bytes in 0.016s)
[server] INFO: Device: *** (Android 8.1.0)
[server] WARN: Audio disabled: it is not supported before Android 11
INFO: Renderer: opengl
INFO: OpenGL version: 4.6.0 NVIDIA 535.146.02
INFO: Trilinear filtering enabled
WARN: Demuxer 'audio': stream explicitly disabled by the device
INFO: Texture: 1280x800
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: startActivityAsUserWithFeature [interface android.app.IApplicationThread, class java.lang.String, class java.lang.String, class android.content.Intent, class java.lang.String, interface android.os.IBinder, class java.lang.String, int, int, class android.app.ProfilerInfo, class android.os.Bundle, int]
	at java.lang.Class.getMethod(Class.java:2068)
	at java.lang.Class.getMethod(Class.java:1690)
	at com.genymobile.scrcpy.wrappers.ActivityManager.getStartActivityAsUserWithFeatureMethod(ActivityManager.java:115)
	at com.genymobile.scrcpy.wrappers.ActivityManager.startActivityAsUserWithFeature(ActivityManager.java:124)
	at com.genymobile.scrcpy.Controller.openHardKeyboardSettings(Controller.java:457)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:214)
	at com.genymobile.scrcpy.Controller.control(Controller.java:97)
	at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:105)
	at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:764)
```

The reason is that my device uses SDK 27 while this method was added later ([SDK 30?](https://github.com/aosp-mirror/platform_frameworks_base/blob/main/core/java/android/app/IActivityManager.aidl#L443)) in [this commit](https://cs.android.com/android/_/android/platform/frameworks/base/+/ee29509ecd73c3910011b2bdc12d1ef28fcb5a3d:core/java/android/app/IActivityManager.aidl;dlc=998c6ad176d4c419f52184842692c3009379d3f5). So when `startActivityAsUserWithFeature()` fails you should probably use `startActivityAsUser()` instead, because it works [the same way](https://github.com/aosp-mirror/platform_frameworks_base/blob/main/services/core/java/com/android/server/am/ActivityManagerService.java#L3286-L3287) (`callingFeatureId` is [`null`](https://github.com/Genymobile/scrcpy/blob/fec2abe03e252d54166630ccca69a62cab94e5a0/server/src/main/java/com/genymobile/scrcpy/wrappers/ActivityManager.java#L129)). Maybe `startActivityAsUser()` should be used directly, even if it's deprecated?

**Comment by rom1v** [comment]
Thank you. Fixed by abc64b46c4ba21f7a6ca543d64f64b105a09d5a7 on `uhid.28`.
