### ISSUE TITLE
Unable to Control Device with scrcpy on Redmi K70 (Android 14)

### ISSUE THREAD

**Issue by fsfuzhu** [Genymobile/scrcpy#4706]
**Description:**

Hello,

I've encountered an issue with scrcpy version 2.3.1 where I am unable to control my Redmi K70, model 23113RKC6C, running Android 14. While the screen content is displayed correctly on my computer, any attempts to interact with the device (such as clicks or swipes) result in errors without any effect on the phone.

**Steps to Reproduce:**

1. Connect the Redmi K70 to the computer via USB.
2. Launch scrcpy using the command `scrcpy.exe` from the directory `D:\scrcpy-win64-v2.3.1`.
3. Try to interact with the device by clicking or swiping on the mirrored screen on the computer.

**Expected Result:**

The phone responds to interactions made through the scrcpy window, allowing control over the device.

**Actual Result:**

The phone does not respond to any interactions through the scrcpy window. The screen content is displayed without issue, but control is not possible.

**Error Messages:**

Upon attempting to interact with the device, the following error messages are displayed in the console:

```
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Method.invoke(Native Method)
    ...
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
    ...
[server] ERROR: Could not invoke method
...
```

(Repeated error messages indicating a `SecurityException` related to `INJECT_EVENTS` permission have been omitted for brevity.)

**Environment:**

- **Operating System**: Windows 10
- **scrcpy Version**: 2.3.1
- **Device**: Redmi K70
- **Device Model**: 23113RKC6C
- **Android Version**: 14

**Additional Information:**

- The device is connected via USB.
- Developer options and USB debugging are enabled on the device.
- The device is authorized for debugging with the computer.

I would appreciate any assistance or guidance on resolving this issue, as it is critical for my workflow to be able to control my device via scrcpy.

Thank you for your support.

![QQ截图20240226215025](https://github.com/Genymobile/scrcpy/assets/102003699/7b74af42-7011-4703-b2e6-47e2de93ae69)

**Comment by fsfuzhu** [comment]
[framework.zip](https://github.com/Genymobile/scrcpy/files/14411740/framework.zip)

**Comment by rom1v** [comment]
- https://github.com/Genymobile/scrcpy#prerequisites
- https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work
