### ISSUE TITLE
It seems scrcpy drop some frame?

### ISSUE THREAD

**Issue by tingfengwanxiao** [Genymobile/scrcpy#4710]
Hello,when I using  scrcpy --no-audio -Nr file.mp4 
and I find the duration of frames are different from the  reality.
For example, the first frame and second frame have 59ms duration in reality,but in scrcpy file.mp4,It only has duration of 23ms,it miss some frames or time and I can't use this duration to calculate.How can I get the whole frames or get the correct duration?

**Comment by rom1v** [comment]
> the first frame and second frame have 59ms duration in reality,but in scrcpy file.mp4,It only has duration of 23ms

How did you measure these values?

**Comment by tingfengwanxiao** [comment]
every picture I display current time

**Comment by rom1v** [comment]
> every picture I display current time

On the client side?

The frame timestamps recorded in your target file are captured on the server side, so that they are not impacted by network jitter (so even if a frame is late on your real time display, it is recorded with the correct one).

**Comment by rom1v** [comment]
Also see https://github.com/Genymobile/scrcpy/pull/2464

**Comment by tingfengwanxiao** [comment]
on server side,display by phone system time

**Comment by rom1v** [comment]
> every picture I display current time

Display the PTS instead. Current time of processing depends on many factors.

**Comment by tingfengwanxiao** [comment]
Oh, I understand. What I want is a yellow display, but what I get is a blue display, so some frames that actually have jitter seem to disappear for some time. How can I use the yellow display method?
![image](https://github.com/Genymobile/scrcpy/assets/49578058/6bc2ccfa-891f-43e4-81ee-e03440f21c77)

**Comment by rom1v** [comment]
Record your screen with OBS.

**Comment by tingfengwanxiao** [comment]
Thank you!Can you explain it in more detail? For example, how to modify or use parameters in the source code

**Comment by rom1v** [comment]
If you want to record what appears on the screen exactly, you don't need to modify the scrcpy source code, but instead capture the window with [OBS](https://obsproject.com/).

**Comment by rom1v** [comment]
> then record scrcpy in A and get file.mp4

How do you record?

If you record with an external device camera, and you compare with the result of `scrcpy --record=file.mp4`, they won't match: one depends on the frame display time, the other depends on the frame capture time (so there is jitter between them).

**Comment by tingfengwanxiao** [comment]
adb shell service call SurfaceFlinger 1101 i32 1

**Comment by tingfengwanxiao** [comment]
Just like in these two videos, file.mp4 record by scrcpy.file.mp4should have an interval of 15ms from the first frame to the second frame (416-431ms), but in the recording time of Scrcpy, the interval is 000-019ms, and the interval from the second frame to the third frame from 431 to 450 should be 19ms. However, in the video, there is only 14ms from 19-33, which results in a total interval of 398ms from the first frame to the tenth frame  should have been 416-814, but in reality it is 384ms. Meanwhile, the recorded by an external device, The interval display is normal, and there is not much difference between the timestamp  mark


https://github.com/Genymobile/scrcpy/assets/49578058/b88eaaf6-62f2-41ed-921c-e52c8a2ba64f

**Comment by rom1v** [comment]
The timestamps recorded by `scrcpy --record=file.mp4` are provided by `MediaCodec` (the field [`BufferInfo.presentationTimeUs`](https://developer.android.com/reference/android/media/MediaCodec.BufferInfo#presentationTimeUs)). These are a priori the time where the Surface is damaged, so there is no reason it matches the input video timestamps with infinite precision: it depends on your video player on the device (on the time it draws), on vsync, etc.

**Comment by tingfengwanxiao** [comment]
So do you have any good ways to match their timestamps

**Comment by tingfengwanxiao** [comment]
ok,You are right.It depend on vsync.I understand.
