### ISSUE TITLE
Always On Top Feature

### ISSUE THREAD

**Issue by chrisokoriedev** [Genymobile/scrcpy#4711]
**Is your feature request related to a problem? Please describe.**
I use this tool for mobile development but there are time i wish it had an always-on-top feature

**Describe the solution you'd like**
I always have my mirror device on the right switch windows make it hard to work with

**Describe alternatives you've considered**
Hmmm there's a feature on window that currently helps hmmm window tab manger

![Uploading image.png
![Uploading image_2024-03-01_074323210.png…]()
…]()

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/doc/window.md#always-on-top

**Comment by chrisokoriedev** [comment]
Okays thanks

**Comment by chrisokoriedev** [comment]
> https://github.com/Genymobile/scrcpy/blob/master/doc/window.md#always-on-top

Okay thanks 🙏🏿👍🏿👍🏿👍🏿👍🏿👍🏿

**Comment by SalimiHabib** [comment]
Hi

can this feature be used in runtime using shortcuts  ?

thank you
