### ISSUE TITLE
Notification bar display does not work

### ISSUE THREAD

**Issue by vvvamik** [Genymobile/scrcpy#4724]
**Environment**
 - OS: [Windows]
 - scrcpy version: [2.3.1.]
 - installation method: [Windows release]
 - device model:
 - Android version: [14]

When I pull down the notification bar with my mouse, it doesn't stay pulled down, but hides when I release it.

**Comment by rom1v** [comment]
scrcpy just forward mouse events, the device UI decides what to do.

Typically, the notification panel expansion depends on the mouse speed/acceleration and distance, so it might be more difficult to keep it open with a mouse than with fingers (although I have no problem on my device).

Note that for convenience, you can open it using [shortcuts](https://github.com/Genymobile/scrcpy/blob/master/doc/shortcuts.md) <kbd>MOD</kbd>+<kbd>n</kbd> and <kbd>MOD</kbd>+<kbd>MOD</kbd>+<kbd>n</kbd>.

**Comment by vvvamik** [comment]
> scrcpy just forward mouse events, the device UI decides what to do.
> 
> Typically, the notification panel expansion depends on the mouse speed/acceleration and distance, so it might be more difficult to keep it open with a mouse than with fingers (although I have no problem on my device).
> 
> Note that for convenience, you can open it using [shortcuts](https://github.com/Genymobile/scrcpy/blob/master/doc/shortcuts.md) MOD+n and MOD+MOD+n.

Thanks, the shortcut key works great.
