### ISSUE TITLE
Can't insert @ and other AltGr dependent characters with new UHID

### ISSUE THREAD

**Issue by AlfonsoGDiggia** [Genymobile/scrcpy#4725]
- [Y] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [Y] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 11
 - scrcpy version: 2.4
 - installation method: Wnidows Release
 - device model: Pixel 7 Pro
 - Android version: Android 14

**Describe the bug**
TL; DR: I cannot write @ or other AltGr dependent characters into android with the new UHID method (-K option).
I confirm that @ and other AltGr dependent characters work in v2.4 if the -K is omitted and the --prefer-text option is used instead.
I have checked that my keyboard layout is correctly configured in android.

Detailed explanation:
I have discovered the app in v2.3.1, and I've been following the UHID development with great expectation. Congrats on the great work performed.
But, I have discovered that I cannot insert @ while writing with the new UHID option. Neither #, ¬, €, or other AltGr dependent characters.

To sanity check, I have run scrcpy with the same arguments I was using with v.2.3.1, that is, no -K and with --prefer-text, and there are no problems. @ are correctly written on the phone.
And, AFAIK, I have correctly set up my keyboard layout. It's easy to check when you're spanish and you have a dedicated "ñ" key.

I have also noticed that the autocorrect feature gets crazy when gboard is "hidden" due to using a physical keyboard, but I get the feeling that's a Google feature.

**Comment by rom1v** [comment]
I am away from the computer right now, but I know it works for me on a Pixel 8.

It may depend on your software keyboard, I have not tested with Gboard. Could you test another keyboard just to confirm?

Or maybe <kbd>AltGr</kbd> is captured by Gboard for some feature and it can be customized?

I'll check later when I'm back on the computer.

**Comment by AlfonsoGDiggia** [comment]
Tried with Microsoft keyboard. AltGr+1,2 or 3 is used to select one of three possible predicted words.
Thx, Microsoft.

Using SimpleKeyboard (https://play.google.com/store/apps/details?id=rkr.simplekeyboard.inputmethod&hl=en_US) yields the same non-@ problem.

I can try another keyboard app, if it is valuable. Althugh that will have to wait until tomorrow, though.

**Comment by rom1v** [comment]
I confirm that `@` or `€` work correctly for me.

It works well with [OpenBoard](https://f-droid.org/fr/packages/org.dslul.openboard.inputmethod.latin/).
Then I switched to GBoard to test, and it also works for me.

I tested both keyboard on a Pixel 8 and on a OnePlus 7 Pro, it works.

So it might be a system setting not specifically related to the keyboard (something that captures <kbd>AltGr</kbr> on your device).

**Comment by AlfonsoGDiggia** [comment]
Tried with an [Openboard fork](https://play.google.com/store/apps/details?id=com.softwarevalencia.openboard.inputmethod.latin&hl=es_VE), no luck.
I've also tried switch languages, and therefore keyboard layouts, in the phone. Same results

Soo... I'm going to try to find what exactly is eating the input on the phone.
Thank you very much for the help!

To be fair, I don't know if this issue should be closed at this point, since I do not longer consider it a scrcpy issue.
Your repository, your choice, I guess.

**Comment by AlfonsoGDiggia** [comment]
Hi again! I've found out my problem: I'm using Windows.
 
So, just a FYI to document my findings: Android interprets differently `LCtrl+AltGr` than `AltGr`. 
My (spanish) Windows 11 generates `LCtrl+AltGr`.
 
So, when pressing `AltGr`, my Windows generates two key events, `LCtrl` and `RAlt` (according to online keyboard testers like [this](https://www.onlinemictest.com/keyboard-test/)), which are correctly send by scrcpy
 
Log extract (224 is `LCtrl`, 230 is `AltGr`): 
```
VERBOSE: hid keyboard: key down scancode=e0 (224) mod=01
VERBOSE: input: UHID input [1] 01 00 00 00 00 00 00 00 
VERBOSE: hid keyboard: key down scancode=e6 (230) mod=41
VERBOSE: input: UHID input [1] 41 00 00 00 00 00 00 00 
VERBOSE: keys[1f] = true
```

AFAIK, android does not know what to do with `LCtrl+AltGr` (if i'm understanding this [issue](https://github.com/codemirror/dev/issues/1183) correctly), so it does nothing.
However, if while holdin `AltGr` I press and depress `LCtrl`, the keyboards stops sending `LCtrl` as pressed, and I can use @ as long as I hold `AltGr`.
 
This problem does NOT occur in Ubuntu 22.04: only `AltGr` is sent as pressed in this case. Just checked it.
 
And, AFAIK, this IS expected behavior for Windows, according to [Wikipedia](https://en.wikipedia.org/wiki/AltGr_key#History) from even more than [10 years ago](https://superuser.com/questions/592970/can-i-make-ctrlalt-not-act-like-altgr-on-windows).

Maybe scrcpy can take care of this? Should scrcpy take care of this?

**Comment by rom1v** [comment]
Wow :open_mouth: Great work! :detective: 

> Maybe scrcpy can take care of this? Should scrcpy take care of this?

Scrcpy receives key events from [SDL](https://github.com/libsdl-org/SDL/), so maybe SDL should take care of this? (or not?)

**Comment by AlfonsoGDiggia** [comment]
> Scrcpy receives key events from [SDL](https://github.com/libsdl-org/SDL/), so maybe SDL should take care of this? (or not?)

I don't know what to tell you, this is my first ever Github issue 😂 Feel free to do with this issue and this information whatever you want.

Cheers!

**Comment by AlfonsoGDiggia** [comment]
Hi again! 

Just wanted to say that with the new v2.5 release, this issue has been solved.
So, if it is okay, I will mark this issue as closed. 

Thank you very much for the very good work! 👏👏
Cheers!

**Comment by rom1v** [comment]
:tada: Probably with the upgrade of the SDL library to the latest version :+1:

**Comment by Gattsuu** [comment]
Somehow I am facing this problem now. Was there a change through a Windows update maybe? I have only started using scrcpy very recently and can't confirm if this behavior changed or not.

**Comment by AlfonsoGDiggia** [comment]
I cannot reproduce the issue on my Pixel 7 Pro, Android 15 (may patch), and Windows 11 24H2 (KB5058411) and latest scrpy (3.2)

**Comment by Gattsuu** [comment]
I found out that now I can also press ALTGR twice to fix it temporarily instead of the CTRL thing. Good enough for me I guess but a fix would still be nice of course.

**Comment by MK73DS** [comment]
I experience the same issue. The right alt key isn't sent to the device it seems, even thought scrcpy captures it.
Right control works, and left alt also works if I change the mod key to something else. Note that if I change the mod key to `ralt`, the mod key doesn't work either.

When I open the keyboard tester on my PC, the right alt is correctly recognized. When I open the tester on my phone using `scrcpy -K`, it doesn't.

If I use `--keyboard=sdk`, then sending a character like `@` works fine (right alt + 0 on my french layout keyboard). But there are other issues I experience with this so I would like to use the `uhid` keyboard.

<pre>
VERBOSE: hid keyboard: key down scancode=e6 (230) mod=00
VERBOSE: input: UHID input [1] 00 00 00 00 00 00 00 00 
VERBOSE: hid keyboard: key up   scancode=e6 (230) mod=00
VERBOSE: input: UHID input [1] 00 00 00 00 00 00 00 00 
</pre>

I'm using scrcpy version 4.0 on Arch Linux, KDE plasma 6.7.0.
<pre>
$ scrcpy -v
scrcpy 4.0 <https://github.com/Genymobile/scrcpy>

Dependencies (compiled / linked):
 - SDL: 3.4.8 / 3.4.10
 - libavcodec: 62.28.101 / 62.28.102
 - libavformat: 62.12.101 / 62.12.102
 - libavutil: 60.26.101 / 60.26.102
 - libavdevice: 62.3.101 / 62.3.102
 - libusb: - / 1.0.30
</pre>
