### ISSUE TITLE
how i can fix it?

### ISSUE THREAD

**Issue by dororo003** [Genymobile/scrcpy#4729]
My scrcpy is experiencing an error again, how to solve the problem below
*scrcpy 2.4 <https://github.com/Genymobile/scrcpy>*
*ERROR: Could not find any ADB device*
*ERROR: Server connection failed*
*Press Enter to continue...*
help me bro @rom1v

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#device-not-detected
