### ISSUE TITLE
Screen grab

### ISSUE THREAD

**Issue by vlnistor** [Genymobile/scrcpy#4733]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
I want to take screens grabs on the phone from the PC controlling the phone and then transfer that screenshot to a folder inside the PC. 

**Describe the solution you'd like**
Ideally, there'd be a keyboard shortcut that once pressed, it'll take a screenshot and transfer it automatically to a folder that has been passed as a command line argument when I initiated the session.

**Describe alternatives you've considered**
Please do let me know of alternatives.

**Comment by rom1v** [comment]
#684
