### ISSUE TITLE
coneccion de una segunda pantalla pormedio de USB 

### ISSUE THREAD

**Issue by KINGZZTON** [Genymobile/scrcpy#4735]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by KINGZZTON** [comment]
busco conectar una segunda pantalla al mismo ordenador pero me aparece un herror debido a que ya se a iniciado scrcpy con un primer dispositivo
ya probe coneccion inalambrica con los comandos de (adb) pero va con mucho retraso

**Comment by rom1v** [comment]
In English, please!

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#several-devices-connected

**Comment by KINGZZTON** [comment]
identifying devices connected by (adb) wireless, such as (usb)
Yes, the screen of the two devices can be projected, but the wirelessly connected device has a lot of delay.

Is there the possibility of connecting the devices via USB, perhaps identifying each device connected by the aforementioned means?

**Comment by rom1v** [comment]
> but the wirelessly connected device has a lot of delay

If there is delay, then there is a network performance issue (either on the device, on your router or your computer). You can reduce the bit rate to minimize problems:

```bash
# reduce the bit rate
scrcpy -b2M
# also change the codec and reduce the resolution
scrcpy --video-codec=h265 --m1280 -b2M
```

> Is there the possibility of connecting the devices via USB, perhaps identifying each device connected by the aforementioned means?

Hmmm, yes. Plug several devices to USB ports, and select the device as documented :thinking: 

https://github.com/Genymobile/scrcpy/blob/master/doc/connection.md

**Comment by rom1v** [comment]
```bash
# connect to the first device:
scrcpy -s 1f89c973
# connect to the second device:
scrcpy -s LMK410MRFIMFPJORF6
```

(the serial of the second device is unexpected, what is the result of `adb devices` and `adb devices -l`?)

**Comment by KINGZZTON** [comment]
I don't know exactly what you are asking me for, so if it's not wrong, I'll send you what is executed in (CMD)

C:\Users\YAMID\Desktop\new version\scrcpy-win64-v2.3.1>scrcpy -s LMK410MRFIMFPJORF6
scrcpy 2.3.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO: (usb) 1f89c973 device M2101K6G
INFO: --> (usb) LMK410MRFIMFPJORF6 device LM_K410
C:\Users\YAMID\Desktop\new version\scrcpy-win64-v2.3.1\s... file pushed, 0 skipped. 43.5 MB/s (66007 bytes in 0.001s)
[server] INFO: Device: [LGE] lge LM-K410 (Android 11)
INFO: Renderer: direct3d
INFO: Texture: 720x1600

I already managed to connect the two devices, thank you very much for your great help
