### ISSUE TITLE
It logs me out of my system back to Login menu

### ISSUE THREAD

**Issue by mrlectus** [Genymobile/scrcpy#4739]
**Environment**
 - OS: [Linux - Arch]
 - scrcpy version: [e.g. 2.3.1]
 - installation method: [pacman]
 - device model:
 - Android version: [10]

This is a very strange behaviour and it has not been happening before, but when i run scrcpy   -m1024 on the terminal. It Logs me out of my system closing all app, I have to Log back in, Like what the hell is happening?

**Comment by rom1v** [comment]
Maybe a crash in your graphics drivers?

What if you run `scrcpy --render-driver=software`?

Or even if you do not mirror video (`scrcpy --no-video`, or `--scrcpy --record=file.mp4 --no-playback`)?

**Comment by mrlectus** [comment]
> Maybe a crash in your graphics drivers?
> 
> What if you run `scrcpy --render-driver=software`?
> 
> Or even if you do not mirror video (`scrcpy --no-video`, or `--scrcpy --record=file.mp4 --no-playback`)?

it was my login manager that was the issue
