### ISSUE TITLE
[POCO M3] Demuxer 'audio': stream explicitly disabled by the device

### ISSUE THREAD

**Issue by Nathasan1410** [Genymobile/scrcpy#4743]
- [V ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [V ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 11
 - scrcpy version: v2.4
 - installation method: zip download
 - device model: Poco M3 (M2010J19CG)
 - Android version: 10 QKQ1.200830.002
 - MIUI version: 12.0.11

I've tried several solution for this issue, but nothing worked out. Tried that vivo work around, changing audio encoders to aac and #4015, but nothing worked out.

Here is a few version of scrcpy that i've tried:
scrcpy-win64-v1.25-208-g282c9d787
scrcpy-win64-v2.0-57-ga7e16c2c0
scrcpy-win64-v2.0-93-g86e5c90ed
scrcpy-win64-v2.0-93-gfeb247f78
scrcpy-win64-v2.0-94-g1c2d4b18b
scrcpy-win64-v2.0-94-g9f9b852ae
scrcpy-win64-v2.4

this is the output from my terminal:
scrcpy-win64-v2.4>scrcpy --max-size=1024 --video-codec=h264 --video-bit-rate=6M --audio-bit-rate=128K --max-fps=30 --audio-encoder=aac
scrcpy 2.4 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  4826cc410621                    device  M2010J19CG
C:\Another Program\scrcpy-win64-v2.4\scrcpy-server: 1 file pushed, 0 skipped. 122.7 MB/s (69007 bytes in 0.001s)
[server] INFO: Device: [Xiaomi] POCO M2010J19CG (Android 10)
[server] WARN: Audio disabled: it is not supported before Android 11
INFO: Renderer: direct3d
WARN: Demuxer 'audio': stream explicitly disabled by the device
INFO: Texture: 472x1024

**Comment by rom1v** [comment]
> Android version: 10

> [server] WARN: Audio disabled: it is not supported before Android 11

As expected.

**Comment by Nathasan1410** [comment]
@rom1 my brain just farted, my bad bro, i just realized where's the problem after i post this
