### ISSUE TITLE
v2.4.0 is not available for Chocolatey

### ISSUE THREAD

**Issue by AlexV525** [Genymobile/scrcpy#4749]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: 2.3.0
 - installation method: Windows Chocolatey

https://community.chocolatey.org/packages/scrcpy

![image](https://github.com/Genymobile/scrcpy/assets/15884415/e2be5717-c24e-49f9-b967-007cadca4a45)
![image](https://github.com/Genymobile/scrcpy/assets/15884415/1b63f4b5-c9e8-45a3-a6ec-5d4f852f2bc4)

**Comment by rom1v** [comment]
Thank you for your report, I do not manage the chocolatey package, so you should probably report to Chocolatey (or the author package).

**Comment by AlexV525** [comment]
> Thank you for your report, I do not manage the chocolatey package, so you should probably report to Chocolatey (or the author package).

Ah TIL. Thanks for the reply!

I've found out the author is @n3rd4i so maybe if you guys can be bridged toghther then we can have the release and future releases up-to-date!
