### ISSUE TITLE
[Xiaomi Android 14] Light grays appearing as white only for scrcpy

### ISSUE THREAD

**Issue by carstenhag** [Genymobile/scrcpy#4756]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: macOS 14.3.1
 - scrcpy version: 2.4
 - installation method: brew
 - device model: MBP 16" M3 / Poco F5
 - Android version: 14

**Describe the bug**

Light grays are not shown. They are displayed as white. ADB and Android Studio render the colors correctly.

I am pretty sure this is happening since I upgraded the phone from Android 13 to Android 14 some weeks ago.

With a `[Google] google Pixel 6 (Android 14)` the issue is not occurring, which means the device is somehow influencing this.

```
/opt/homebrew/Cellar/scrcpy/2.4/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 71.2 MB/s (69007 bytes in 0.001s)
[server] INFO: Device: [Xiaomi] POCO 23049PCD8G (Android 14)
```

AS:
<img width="585" alt="as" src="https://github.com/Genymobile/scrcpy/assets/3776997/520ff3c8-6ffa-41a3-ae97-55252a8fc143">
ADB:
<img width="558" alt="adb-screencapture-output" src="https://github.com/Genymobile/scrcpy/assets/3776997/da3fd4e6-92db-4455-91e4-e5d8b6c3406a">
scrpcy:
<img width="554" alt="scrcpy" src="https://github.com/Genymobile/scrcpy/assets/3776997/7cd5658c-f9cb-4d6b-9654-935650762506">

**Comment by rom1v** [comment]
> ADB

What do you mean by adb here? screenrecord (`adb shell screenrecord /sdcard/file.mp4`)?

If you record then play the file (with VLC for example), does the problem occur?

```
scrcpy --record=file.mp4 --no-playback
```

**Comment by carstenhag** [comment]
Yep, I meant `adb shell screenrecord /sdcard/file.mp4`.

With `scrcpy --record=file.mp4 --no-playback` it does work correctly.
<img width="558" alt="Screenshot 2024-03-12 at 15 58 40" src="https://github.com/Genymobile/scrcpy/assets/3776997/4f29940f-3e26-4067-97ad-5be65545de70">

**Comment by carstenhag** [comment]
```
    val brush = Brush.horizontalGradient(listOf(Color.Black, Color.White))
    Canvas(
        modifier = Modifier.size(400.dp),
        onDraw = {
            drawCircle(brush)
        }
    )
```
With this one can see that after some specific gray value it just outputs white

<img width="554" alt="Screenshot 2024-03-12 at 16 00 21" src="https://github.com/Genymobile/scrcpy/assets/3776997/81b1dc5b-6ebc-44e9-83ff-3c5b706bc09e">

**Comment by rom1v** [comment]
In the console output, which renderer is used?

For example:
```
INFO: Renderer: opengl
```

I guess this is `metal` for you.

If so, could you try other values:

```
scrcpy --render-driver=opengl
scrcpy --render-driver=opengles2
scrcpy --render-driver=software
```

**Comment by carstenhag** [comment]
All of them look the same (partially horrible) way 😆 

```
 %  ~  scrcpy
scrcpy 2.4 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  3d97ed47                        device  23049PCD8G
/opt/homebrew/Cellar/scrcpy/2.4/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 111.3 MB/s (69007 bytes in 0.001s)
[server] INFO: Device: [Xiaomi] POCO 23049PCD8G (Android 14)
INFO: Renderer: metal
INFO: Texture: 1080x2400
^[[A^CWARN: Device disconnected
 %  ~  USAGE  scrcpy --render-driver=opengl
scrcpy 2.4 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  3d97ed47                        device  23049PCD8G
/opt/homebrew/Cellar/scrcpy/2.4/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 93.2 MB/s (69007 bytes in 0.001s)
[server] INFO: Device: [Xiaomi] POCO 23049PCD8G (Android 14)
INFO: Renderer: opengl
INFO: OpenGL version: 4.1 Metal - 88
INFO: Trilinear filtering enabled
INFO: Texture: 1080x2400
^CWARN: Device disconnected
 %  ~  USAGE  scrcpy --render-driver=opengles2
scrcpy 2.4 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  3d97ed47                        device  23049PCD8G
/opt/homebrew/Cellar/scrcpy/2.4/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 111.9 MB/s (69007 bytes in 0.001s)
[server] INFO: Device: [Xiaomi] POCO 23049PCD8G (Android 14)
INFO: Renderer: metal
INFO: Texture: 1080x2400
[server] WARN: Could not get initial audio timestamp
^CWARN: Device disconnected
 %  ~  USAGE  scrcpy --render-driver=software
scrcpy 2.4 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  3d97ed47                        device  23049PCD8G
/opt/homebrew/Cellar/scrcpy/2.4/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 221.6 MB/s (69007 bytes in 0.000s)
[server] INFO: Device: [Xiaomi] POCO 23049PCD8G (Android 14)
INFO: Renderer: software
INFO: Texture: 1080x2400
^CWARN: Device disconnected
 %  ~  USAGE  scrcpy --render-driver=metal
scrcpy 2.4 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  3d97ed47                        device  23049PCD8G
/opt/homebrew/Cellar/scrcpy/2.4/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 230.9 MB/s (69007 bytes in 0.000s)
[server] INFO: Device: [Xiaomi] POCO 23049PCD8G (Android 14)
INFO: Renderer: metal
INFO: Texture: 1080x2400

```

**Comment by ssalenik** [comment]
I've experienced the same issue before (not with scrcpy) and it was the encoder which was at fault (switching from the hardware encoder to x264 fixed it). I don't know if its possible the device is somehow defaulting to a different h264 encoder on A14? Though not sure why recording to a .mp4 would fix it.

**Comment by carstenhag** [comment]
`scrcpy --video-codec=h265` and `scrcpy --video-codec=h264` results in the mentioned error, with `scrcpy --video-codec=av1` the colors look fine.

**Comment by rom1v** [comment]
> I don't know if its possible the device is somehow defaulting to a different h264 encoder on A14?

You can list and change the [encoder](https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#encoder).

> it was the encoder which was at fault (switching from the hardware encoder to x264 fixed it). […] Though not sure why recording to a .mp4 would fix it.

Maybe your hardware encoder encodes with different parameters and set some metadata to handle color, and scrcpy does not handle them (either during the YUV-to-RGB conversion, either during rendering) while VLC does.

If you could try the same device on another computer with another OS (on Linux for example), that might help (or not).

**Comment by yume-chan** [comment]
Same as #4282

Maybe the device captures in HDR but SDL2 can't render them correctly?

**Comment by pain414410797** [comment]
I had the same problem, scrcpy and android studio mirror screens have a noticeable color difference
😂
![image](https://github.com/Genymobile/scrcpy/assets/46311976/1ff656dc-808e-4fdc-984d-3869f4ec1415)

**Comment by carstenhag** [comment]
@pain414410797 what Xiaomi phone are you using?

**Comment by yume-chan** [comment]
Some newer XiaoMi devices encodes in full color range. I found this fix, but updating it in every frame might not be the most efficient method:

```patch
diff --git a/app/src/display.c b/app/src/display.c
index c8df615d..ccc65902 100644
--- a/app/src/display.c
+++ b/app/src/display.c
@@ -199,6 +199,13 @@ sc_display_set_texture_size(struct sc_display *display, struct sc_size size) {
 static bool
 sc_display_update_texture_internal(struct sc_display *display,
                                    const AVFrame *frame) {
+    if (frame->color_range == AVCOL_RANGE_JPEG){
+      LOGE("JPEG color range detected");
+      SDL_SetYUVConversionMode(SDL_YUV_CONVERSION_JPEG);
+    } else {
+      SDL_SetYUVConversionMode(SDL_YUV_CONVERSION_AUTOMATIC);
+    }
+
     int ret = SDL_UpdateYUVTexture(display->texture, NULL,
                                    frame->data[0], frame->linesize[0],
                                    frame->data[1], frame->linesize[1],
```

`AVCodecContext` also has a `color_range` field, but seems that's not populated when decoding.

Recoding from Mi 11: [limited.zip](https://github.com/Genymobile/scrcpy/files/14633346/limited.zip)

Recording from RedMi K60: [full.zip](https://github.com/Genymobile/scrcpy/files/14633349/full.zip)

**Comment by rom1v** [comment]
:+1:

> updating it in every frame might not be the most efficient method

Although `SDL_SetYUVConversionMode()` just [writes](https://github.com/libsdl-org/SDL/blob/c17d2246fb0ed2fa5b16acbf1f2b3aa7e5ddd3cf/src/video/SDL_yuv.c#L38-L41) the provided value (so it should be fast), the color range should be known in [`AVCodecContext`](https://github.com/FFmpeg/FFmpeg/blob/aeebcd2f73161f201c65a7cd87154f5f21659e7f/libavcodec/avcodec.h#L695), which is given here:

https://github.com/Genymobile/scrcpy/blob/79968a0ae63179c39d5f1d4f4d97da020c9e07dd/app/src/screen.c#L281-L283

**Comment by yume-chan** [comment]
@rom1v I have tried exactly there, but `ctx->color_range` is `0`. When `sc_screen_frame_sink_open` was called, `ctx` is only initialized with codec ID. `color_range` should come from the config packet, so I added this log:

```patch
diff --git a/app/src/decoder.c b/app/src/decoder.c
index 5d42b8b0..123f9d44 100644
--- a/app/src/decoder.c
+++ b/app/src/decoder.c
@@ -43,6 +43,10 @@ sc_decoder_push(struct sc_decoder *decoder, const AVPacket *packet) {
         return true;
     }
 
+    if (decoder->ctx->width != 0) {
+        LOGE("color range before avcodec_send_packet: %d", decoder->ctx->color_range);
+    }
+
     int ret = avcodec_send_packet(decoder->ctx, packet);
     if (ret < 0 && ret != AVERROR(EAGAIN)) {
         LOGE("Decoder '%s': could not send video packet: %d",
@@ -50,6 +54,10 @@ sc_decoder_push(struct sc_decoder *decoder, const AVPacket *packet) {
         return false;
     }
 
+    if (decoder->ctx->width != 0) {
+        LOGE("color range after avcodec_send_packet: %d", decoder->ctx->color_range);
+    }
+
     for (;;) {
         ret = avcodec_receive_frame(decoder->ctx, decoder->frame);
         if (ret == AVERROR(EAGAIN) || ret == AVERROR_EOF) {

```

Output:

```text
> ./scrcpy -s af176a0b
scrcpy 2.4 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:           (usb)  73294bba                        device  M2011K2C
INFO:           (usb)  M01046406Y2031500412            device  mblu10
INFO:     -->   (usb)  af176a0b                        device  23013RK75C
D:\dev\yume-chan\scrcpy-devcontainer\scrcpy\dist\scrcpy-wi... file pushed, 0 skipped. 86.4 MB/s (69007 bytes in 0.001s)
[server] INFO: Device: [Xiaomi] Redmi 23013RK75C (Android 14)
INFO: Renderer: direct3d
INFO: Texture: 1440x3200
ERROR: color range before avcodec_send_packet: 0
ERROR: color range after avcodec_send_packet: 2
ERROR: color range before avcodec_send_packet: 2
ERROR: color range after avcodec_send_packet: 2
ERROR: color range before avcodec_send_packet: 2
ERROR: color range after avcodec_send_packet: 2
ERROR: color range before avcodec_send_packet: 2
ERROR: color range after avcodec_send_packet: 2
```

**Comment by yume-chan** [comment]
Or always request the encoder to encode in limited range?

```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/SurfaceEncoder.java b/server/src/main/java/com/genymobile/scrcpy/SurfaceEncoder.java
index 28435c09..467406fd 100644
--- a/server/src/main/java/com/genymobile/scrcpy/SurfaceEncoder.java
+++ b/server/src/main/java/com/genymobile/scrcpy/SurfaceEncoder.java
@@ -219,6 +219,9 @@ public class SurfaceEncoder implements AsyncProcessor {
         format.setInteger(MediaFormat.KEY_BIT_RATE, bitRate);
         // must be present to configure the encoder, but does not impact the actual frame rate, which is variable
         format.setInteger(MediaFormat.KEY_FRAME_RATE, 60);
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
+            format.setInteger(MediaFormat.KEY_COLOR_RANGE, MediaFormat.COLOR_RANGE_LIMITED);
+        }
         format.setInteger(MediaFormat.KEY_COLOR_FORMAT, MediaCodecInfo.CodecCapabilities.COLOR_FormatSurface);
         format.setInteger(MediaFormat.KEY_I_FRAME_INTERVAL, DEFAULT_I_FRAME_INTERVAL);
         // display the very first frame, and recover from bad quality when no new frames

```

**Comment by carstenhag** [comment]
Yep works fine with `scrcpy --video-codec-options=color-range=2`

**Comment by rom1v** [comment]
@yume-chan Does the patch from your [comment](https://github.com/Genymobile/scrcpy/issues/4756#issuecomment-2003228916) work for you?

I tested with `--video-codec-options=color-range=1`, I get the log `JPEG color range detected`, but visually it's incorrect (the same as without the patch). :thinking:

**Comment by yume-chan** [comment]
It works on Redmi K60 (Android 14), but not on Mi 11 (Android 13) with `--video-codec-options=color-range=1`.

If I record Mi 11 with `./scrcpy -s 73294bba --video-codec-options=color-range=1 -r m11_full.mp4` and play it in Windows Media Player, the color is incorrect, but also same as Scrcpy with my patch applied (`#ffffff` becomes `#ebebeb`. However Chrome can play the recording with correct color (white is still white). 

![image](https://github.com/Genymobile/scrcpy/assets/1330321/ee441a0d-15f1-4a04-a979-3d6421b2a5b0)

Here is Redmi K60, recorded with `./scrcpy -s af176a0b -r k60_full.mp4`, both the video and Scrcpy window (with my patch) have the correct color:

![image](https://github.com/Genymobile/scrcpy/assets/1330321/127ca40e-6234-4115-89ef-1a8446b5d27f)

**Comment by rom1v** [comment]
> both the video and Scrcpy window (with my patch) have the correct color:

OK, so if your patch fixes the problem, calling `SDL_SetYUVConversionMode()` fixes the problem on your machine, but it does nothing on mine. So I guess the YUV conversion is not properly applied on Linux/X11/OpenGL…

**Comment by rom1v** [comment]
@yume-chan I suggest to apply both changes (branch [`yuv`](https://github.com/Genymobile/scrcpy/commits/yuv/)):
 - db55edb196134ab39f14c76edfd35225055f1227: fix the rendering (even if it is currently not supported by the SDL opengl render driver)
 - bf625790faccd86b5cdf89234ee405825f76b662: request limited range by default (unless the user explicitly requests `--video-codec-options=color-range=1`

**Comment by rom1v** [comment]
Merged :rocket:
