### ISSUE TITLE
How to start a service in the server ?

### ISSUE THREAD

**Issue by KzDog** [Genymobile/scrcpy#476]
Can I start a **service** when I run `app_process` to start the server? I can not get the **context** in the server so I can't bind a service. I just get _null_ when I run _getApplicationContext()_ . Can this be achieved? Thanks.

**Comment by rom1v** [comment]
No, by default you have no `Context`. There is probably a way to get/create one, but I didn't investigated.

If you want to bind to a system service, you can retrieve it from the `ServiceManager` (see [`wrappers/`](https://github.com/Genymobile/scrcpy/tree/v1.8/server/src/main/java/com/genymobile/scrcpy/wrappers)).

**Comment by KzDog** [comment]
Yeah, Your suggestion is very good. I have studied the `ServiceManager` and I can get phone's IP from `WifiManager` by using reflection. But  now I want to bind a **customized service** and I can't achieve it. It seems we should find another way or stop trying.
