### ISSUE TITLE
ERROR: Could not open audio device: WASAPI can't find requested audio endpoint

### ISSUE THREAD

**Issue by Lingchen218** [Genymobile/scrcpy#4769]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows, ]
 - scrcpy version: [2.4]
 - installation method: [Windows release...]
 - device model:
 - Android version: [13]

ERROR: Could not open audio device: WASAPI can't find requested audio endpoint: 鎵句笉鍒板厓绱犮€
ERROR: Demuxer error
WARN: Killing the server...
```
If the computer doesn't have a sound card, it can display a warning message indicating the inability to play sound instead of exiting directly.

**Comment by Lingchen218** [comment]
I disabled the sound card of the remote computer during remote desktop. If the sound card was enabled, this error would not be reported.

**Comment by rom1v** [comment]
If you have non soundcard enabled, use `--no-audio`.

**Comment by Lingchen218** [comment]
> If you have non soundcard enabled, use `--no-audio`.

感谢你了，已成功解决
