### ISSUE TITLE
My output screen is glitched

### ISSUE THREAD

**Issue by itsnaufal** [Genymobile/scrcpy#4770]
- I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: Latest
 - installation method: Windows release
 - device model: Xiaomi Redmi 9
 - Android version: 12

**Describe the bug**

There is no error and the console log run just fine, but the output is glitched and broken.

The control, audio etc is working fine it just the display that is broken, i've tried using wireless mode but the result is the same, i even tried changing the usb cable but it just keep broken.

![image](https://github.com/Genymobile/scrcpy/assets/5900266/6f159d63-46d7-4ba3-845b-d6c8734c8059)

**Comment by rom1v** [comment]
Device encoder issue.

Either the default encoder does not support the resolution (try with a lower resolution, like `scrcpy -m1024`),
or it just does not work. Try with another [encoder](https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#encoder).

**Comment by itsnaufal** [comment]
Thank you. you were right it was encoder issue.

i found this encoder to be working just fine

`scrcpy -m 1024 -b 8M --max-fps 25 --video-codec=h264 --video-encoder='c2.android.avc.encoder' -Sw`
