### ISSUE TITLE
Select device during runtime

### ISSUE THREAD

**Issue by Link-Jon** [Genymobile/scrcpy#4775]
I want (to some extent) make this a little more user friendly -- Currently, if you have more than one ADB device connected, scrcpy gives you a list, some launch commands, and then quits.

It would be alot nicer and easier to to assign each device a number, (probably an array/table) and allow the user to input the number corresponding to that device. Alternatively, we could use the name or ID instead. It would likely be simpler this way, but i *think* it would be easier on user for just a number. (Technically, we could take all three at once, but that might get a bit bulky and problematic if for some reason two names, IDs, or numbers matched in any way.) 

_(I will probably try to implement this myself, but i tend to be rather lazy... It may not get done by me)_

**Comment by rom1v** [comment]
Note that scrcpy can be used from script or without terminal, so it should not wait for input from stdin.

**Comment by Link-Jon** [comment]
After 5 more minutes of research, i now see why this is the way it is -- scrcpy makes extensive use of launch cmds (--word -l) for the sake of a faster launch, making this issue mostly pointless (other than... if someone that doesn't understand how it works, they can either learn or use something else, and the first other programs i found either cant interact with the screen, or require payment in some way. Technically, the "'best'" solution here is likely to have a *mostly seperate fork that adds a UI. Problem: creation and upkeep would be pain)

**Comment by rom1v** [comment]
> scrcpy makes extensive use of launch cmds

Yes, this is a command line application. It has benefits and drawbacks.

In theory (for a better user experience), it would be great to get something more interactive between the client and the server, then extract a lib, then write a GUI (which framework? which trade-offs?) to interact with devices (for simplicity and feature discoverability), while keeping it lightweight and with the same features, but interactive (record/stop at any time, etc.)… and continue to maintain it. But this is too much work and investment that could reasonably be done in my free time. So I keep a monolithic command line app, with regular updates to adapt Android changes and add features, that's more realistic.
