### ISSUE TITLE
InjectInputEvent help

### ISSUE THREAD

**Issue by GPlays09** [Genymobile/scrcpy#4785]
I'm trying to reproduce what you did with InjectInputEvent

I run it from adb shell with... **am start package/activity**
I added the following permission:  **uses-permission android:name="android.permission.INJECT_EVENTS"**
I signed my apk file with my own keys

this is the code I use:
 
    private void injectInputEvent(MotionEvent event) {
        try {
            getInjectInputEvent().invoke(getInputManager(), event, 0);
        } catch (IllegalAccessException | InvocationTargetException | NoSuchMethodException e) {
            e.printStackTrace();
        }
    }

    private static Method getInjectInputEvent() throws NoSuchMethodException {

        Class<InputManager> cl = InputManager.class;
        Method method = cl.getDeclaredMethod("injectInputEvent", InputEvent.class, int.class);
        method.setAccessible(true);
        return method;
    }

    private static InputManager getInputManager() throws NoSuchMethodException, InvocationTargetException, IllegalAccessException {
        Class<InputManager> cl = InputManager.class;
        Method method = cl.getDeclaredMethod("getInstance");
        method.setAccessible(true);
        return (InputManager) method.invoke(cl);
    }

        long downTime = SystemClock.uptimeMillis();
        long eventTime = SystemClock.uptimeMillis();

        MotionEvent.PointerProperties[] pointerProperties = new MotionEvent.PointerProperties[1];
        MotionEvent.PointerCoords[] pointerCoords = new MotionEvent.PointerCoords[1];

        MotionEvent.PointerProperties properties = new MotionEvent.PointerProperties();
        properties.id = 0;
        properties.toolType = MotionEvent.TOOL_TYPE_FINGER;
        pointerProperties[0] = properties;

        MotionEvent.PointerCoords coords = new MotionEvent.PointerCoords();
        coords.x = x;
        coords.y = y;
        coords.pressure = 1;
        coords.size = 1;
        pointerCoords[0] = coords;

        MotionEvent event = MotionEvent.obtain(downTime, eventTime, MotionEvent.ACTION_DOWN, 1, pointerProperties, pointerCoords, 0, 0, 1, 1, 0, 0, InputDevice.SOURCE_TOUCHSCREEN, 0);
        injectInputEvent(event);

        eventTime += 1000; // Adjust event time if needed
        event = MotionEvent.obtain(downTime, eventTime, MotionEvent.ACTION_UP, 1, pointerProperties, pointerCoords, 0, 0, 1, 1, 0, 0, InputDevice.SOURCE_TOUCHSCREEN, 0);
        injectInputEvent(event);

and I get this warning / error:
`java.lang.NoSuchMethodException: com.example.receiver.InputManager.getInstance []
    at java.lang.Class.getMethod(Class.java:2937)
    at java.lang.Class.getDeclaredMethod(Class.java:2914)
    at com.example.receiver.InputHandler.getInputManager(InputHandler.java:59)
    at com.example.receiver.InputHandler.injectInputEvent(InputHandler.java:43)
    at com.example.receiver.InputHandler.Handle(InputHandler.java:84)
    at com.example.receiver.Main.main(Main.java:38)
    at com.example.receiver.MainActivity.lambda$onCreate$0(MainActivity.java:21)
    at com.example.receiver.MainActivity$$ExternalSyntheticLambda0.run(Unknown Source:2)`

**Comment by rom1v** [comment]
It seems that your specific error is because you try to use reflection to get a method from your own `InputManager` class instead than the `android.hardware.input.InputManager`.

But anyway, you won't be able to inject events that way from an Android application, it requires special permissions at system level (that are granted to shell).

**Comment by GPlays09** [comment]
how do you do it then?

**Comment by rom1v** [comment]
> how do you do it then?

https://blog.rom1v.com/2018/03/introducing-scrcpy/#run-a-java-main-on-android

**Comment by GPlays09** [comment]
how do you properly set action for n th pointer? For example if I want to inject a second pointer... I would set reportCount to 2 and set action to what? (only 0x05 doesn't work - ACTION_POINTER_DOWN, I know I have to use some sort of index masks and shift but I have no clue which one and how...)

**Comment by rom1v** [comment]
Run `scrcpy -Verbose` and see what happens when you inject keyboard and mouse events.
