### ISSUE TITLE
pls help

### ISSUE THREAD

**Issue by SyncMaster93** [Genymobile/scrcpy#4786]
my scrcpy started to lag all of a sudden.. dont know the issue 

https://gifyu.com/image/SVKi3

**Comment by SyncMaster93** [comment]
> Over USB?

yeah i solved it.. didnt know game FPS could affect scrcpy - until now wasnt any problems..

**Comment by rom1v** [comment]
> didnt know game FPS could affect scrcpy

You can limit the capture frame rate with `--max-fps=60` for example (if your computer is not able to decode in real time, or if your computer screen is 60Hz).

**Comment by SyncMaster93** [comment]
> > didnt know game FPS could affect scrcpy
> 
> You can limit the capture frame rate with `--max-fps=60` for example (if your computer is not able to decode in real time, or if your computer screen is 60Hz).

yeah i know but i just put my game on 30fps and now works 🗡️
