### ISSUE TITLE
Screen resolution incorrect

### ISSUE THREAD

**Issue by xianyuSF** [Genymobile/scrcpy#4791]
- [Y] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [Y] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows10
 - scrcpy version: 2.4
 - installation method: Windows release
 - device model: NX712J
 - Android version: 14

**Describe the bug**
After I upgrade my phone to Android 14，the captured screen resolution became incorrect.
My device screen's resolution is 1116x2480,but in scrcpy,it shows the texture is 1112x2480(aspect ratio isn't 20:9)
![scrcpy](https://github.com/Genymobile/scrcpy/assets/36237861/7434b31f-22de-48c7-9fe7-9adf4bc7756f)

**Comment by xianyuSF** [comment]
I tried "-m 2400",the texture became 2400x1080,aspect ratio becomes correct

**Comment by rom1v** [comment]
Scrcpy always rounds to the nearest multiple of 8, because many encoders expect the input to be a multiple of 8.
