### ISSUE TITLE
Wireless OTG mode

### ISSUE THREAD

**Issue by Anonuser-01** [Genymobile/scrcpy#4793]
- [X] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**

I currently use "scrcpy --keyboard=uhid --mouse=uhid" to control my device. The issue is, I don't actually want to see the device video on my computer, but there's no way currently to turn off both the video and audio feed. 

**Describe the solution you'd like**

I am essentially looking for a wireless version of "scrcpy --OTG". Please allow turning off device video and audio. Computer should just display the Android logo (same as OTG) and allow me to control my device. 

I would like to be able to use the following command:

scrcpy --keyboard=uhid --mouse=uhid --no-video --no-audio

![Screenshot_1](https://github.com/Genymobile/scrcpy/assets/149913646/77d27bed-ca19-47d5-a4f2-7ae8a0c99f4c)

**Describe alternatives you've considered**

No alternatives

**Additional context**

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/issues/4727#issuecomment-1978115575

**Comment by rom1v** [comment]
Please test #4868.

**Comment by Anonuser-01** [comment]
> Please test #4868.

Thanks for adding this feature. Are you able to share a mac version for testing?

**Comment by rom1v** [comment]
For macOS, you will need to build the client: https://github.com/Genymobile/scrcpy/blob/master/doc/build.md#option-2-use-prebuilt-server
(the prebuilt `scrcpy-server` is included in the binary zip in #4868)
