### ISSUE TITLE
cmd+o not working

### ISSUE THREAD

**Issue by ZzzzzzzSkyward** [Genymobile/scrcpy#4805]
OS: Android 14
Phone: Xiaomi 13
scrcpy version:2.1.1, but I guess this does not matter
installation: Win10 (installer?)
adb method: WLAN

I tried ctrl/alt/shift/win+o, but none of them closes the screen..

By the way, I want to ask two more questions. First, PC keyboard no longer sends key to phone to invoke the Chinese input method, who is to blame? Last, some screens are kept away from capturing, like some payment screen, it is a feature of Android14, or the phone's customized OS?

**Comment by yume-chan** [comment]
> I tried ctrl/alt/shift/win+o, but none of them closes the screen..

Turn off screen on Android 14 requires Scrcpy 2.3 https://github.com/Genymobile/scrcpy/releases/tag/v2.3

> PC keyboard no longer sends key to phone to invoke the Chinese input method

Which IME? Some Chinese IMEs don't respond to injected key events. UHID keyboard in Scrcpy 2.4 might help:

```sh
scrcpy --keyboard=uhid
```

> some screens are kept away from capturing, like some payment screen, it is a feature of Android14

This was added in Android 11.
