### ISSUE TITLE
Toggleable Activation and Deactivation for "Home/Back" shortcuts using UHID Mouse

### ISSUE THREAD

**Issue by ThEspecrum** [Genymobile/scrcpy#4818]
**Description:**
I frequently use SCRCPY to play from my smartphone, turning it like a Nintendo Switch in Deck mode
(Feel free to call me crazy, I accept it! 😅).

The recent implementation of UHID mode for the mouse has been a game-changer. Now, I can use the mouse natively, as if it were connected via OTG (with the added benefit of a larger display!).

However, there’s a minor inconvenience: the Right Click and the Center Click (Mouse Wheel) are currently mapped both to the Back and Home buttons. This dual assignment are a probles when I want to assign these buttons with mouse-compatible games. Doing so would inevitably exit the app.

**The Solution:**
I suggest introducing a toggleable feature with a shorcut that allows users to activate or deactivate the association between the mouse clicks and the Back and Home actions. This would improve the controls customization without affecting the overall app navigation.

**Coomand Line Alternative:**
An alternative would be to add an optional command when running SCRCPY to simply disable the shortcuts.

**Thank you for reading! 🙌**

**Comment by rom1v** [comment]
Try `--forward-all-clicks`.

**Comment by ThEspecrum** [comment]
Ok, I already tried it, and it works perfectly! Thank you so much!
