### ISSUE TITLE
Proprietary secure messenger app not showing on computer screen

### ISSUE THREAD

**Issue by ags1234** [Genymobile/scrcpy#4821]
scrcpy works for me, but I have to use a proprietary secure messenger app and when I open it on my phone scrcpy shows just a black screen on PC.
Is there a way to circumvent this?

**Comment by rom1v** [comment]
That's expected on Android 12+ (if they set the "secure flag" on their view): #36 #2129.

There are basically 3 (not so easy) ways to bypass it:
 - run the app on a device having Android < 12
 - root your device #3049 #3515 #4127
 - decompile/recompile your app to disable the "secure flag" (with a tool like [apk.sh](https://github.com/ax/apk.sh), or see https://github.com/Genymobile/scrcpy/issues/36#issuecomment-1423452461)

**Comment by ags1234** [comment]
Indeed, I am on Android 14.
I was hoping for an easier solution, line a command line parameter to start scrcpy with :)
Those 3 ways above are impossible for me to do.
Thank you for the clarification.
