### ISSUE TITLE
Honor Android 14 devices --turn-screen-off failed

### ISSUE THREAD

**Issue by eiyooooo** [Genymobile/scrcpy#4823]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [ALL]
 - scrcpy version: [2.4]
 - installation method: [ALL]
 - device model:Honor Android 14 devices, e.g. HONOR REP-AN00
 - Android version: [14]

**Describe the bug**
When server reaching here

https://github.com/Genymobile/scrcpy/blob/206809a99affad9a7aa58fcf7593cea71f48954d/server/src/main/java/com/genymobile/scrcpy/wrappers/DisplayControl.java#L31

server get killed, cause by 

```
Native registration unable to find class 'com/android/server/TrustedUIService'; aborting...
```

**Comment by eiyooooo** [comment]
Temporary solution: not change the power mode for all physical displays, using SurfaceControl to change only one display

**Comment by zoukyle** [comment]
My device is being affected by this bug too. @eiyooooo is there a walk-around for this issue? Thanks!

**Comment by eiyooooo** [comment]
> Is there a walk-around for this issue?

Temporary solution: not change the power mode for all physical displays, use SurfaceControl to change only one display instead

> ```diff
> git diff
> diff --git a/server/src/main/java/com/genymobile/scrcpy/Device.java b/server/src/main/java/com/genymobile/scrcpy/Device.java
> index 8d0ee231..671ef2c5 100644
> --- a/server/src/main/java/com/genymobile/scrcpy/Device.java
> +++ b/server/src/main/java/com/genymobile/scrcpy/Device.java
> @@ -319,7 +319,8 @@ public final class Device {
>       * @param mode one of the {@code POWER_MODE_*} constants
>       */
>      public static boolean setScreenPowerMode(int mode) {
> -        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
> +        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q
> +                && !(Build.BRAND.toLowerCase() + Build.MANUFACTURER.toLowerCase()).contains("honor")) {
>              // On Android 14, these internal methods have been moved to DisplayControl
> :
> ```

**Comment by AndroidDeveloperLB** [comment]
Note that Android Studio somehow does work with this.
Perhaps it would be good to check its code.

**Comment by rom1v** [comment]
@eiyooooo Does this also work:

```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/device/Device.java b/server/src/main/java/com/genymobile/scrcpy/device/Device.java
index ae4f50e59..39fbfdce6 100644
--- a/server/src/main/java/com/genymobile/scrcpy/device/Device.java
+++ b/server/src/main/java/com/genymobile/scrcpy/device/Device.java
@@ -323,7 +323,17 @@ public final class Device {
      * @param mode one of the {@code POWER_MODE_*} constants
      */
     public static boolean setScreenPowerMode(int mode) {
-        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
+        boolean applyToMultiPhysicalDisplays = Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q;
+
+        // Workaround for Honor devices:
+        //  - <https://github.com/Genymobile/scrcpy/issues/4823>
+        //  - <https://github.com/Genymobile/scrcpy/issues/4943>
+        if (Build.BRAND.equalsIgnoreCase("honor") && SurfaceControl.hasGetBuildInDisplayMethod()) {
+            // Does not work on Honor devices with Android 14
+            applyToMultiPhysicalDisplays = false;
+        }
+
+        if (applyToMultiPhysicalDisplays) {
             // On Android 14, these internal methods have been moved to DisplayControl
             boolean useDisplayControl =
                     Build.VERSION.SDK_INT >= Build.VERSION_CODES.UPSIDE_DOWN_CAKE && !SurfaceControl.hasPhysicalDisplayIdsMethod();
diff --git a/server/src/main/java/com/genymobile/scrcpy/wrappers/SurfaceControl.java b/server/src/main/java/com/genymobile/scrcpy/wrappers/SurfaceControl.java
index fc18a8e27..2ac1344e8 100644
--- a/server/src/main/java/com/genymobile/scrcpy/wrappers/SurfaceControl.java
+++ b/server/src/main/java/com/genymobile/scrcpy/wrappers/SurfaceControl.java
@@ -94,6 +94,15 @@ public final class SurfaceControl {
         return getBuiltInDisplayMethod;
     }
 
+    public static boolean hasGetBuildInDisplayMethod() {
+        try {
+            getGetBuiltInDisplayMethod();
+            return true;
+        } catch (NoSuchMethodException e) {
+            return false;
+        }
+    }
+
     public static IBinder getBuiltInDisplay() {
         try {
             Method method = getGetBuiltInDisplayMethod();
```

?

**Comment by AndroidDeveloperLB** [comment]
@rom1v  Send me the files to run, and I will try...

**Comment by rom1v** [comment]
@AndroidDeveloperLB The patch above applied on current `master` (basically v2.5):

- [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/4823/1/scrcpy-server) <sub>`SHA-256: 1f17da76699caa3af102563362cc50647ecc9a2a270577e7585c4a54d3063fc`</sub>

**Comment by eiyooooo** [comment]
> Does this also work:

I make a little improvement at #5109.

**Comment by AndroidDeveloperLB** [comment]
@rom1v About this:
https://github.com/Genymobile/scrcpy/issues/4823#issuecomment-2233014567

Seems to work fine too (on the device I've mentioned).
Please don't change it for other devices though, and also maybe it will be ok on Android 15, so please come back here after it's published to see if this fix is needed there as well, instead of applying this fix there too without a need for it.

**Comment by rom1v** [comment]
Merged :+1: 9d1d79b004ed7171f481225993d54c3b100411a7

> Please don't change it for other devices and Android versions though

It is very specific to Honor on Android 14 where the alternate method exists.

**Comment by wxjv99** [comment]
> Temporary solution: not change the power mode for all physical displays, use SurfaceControl to change only one display instead

[This plan](https://github.com/Genymobile/scrcpy/issues/4544#issuecomment-2526999714) may have solved the problem, but it needs to revert the temporary solution(#5109) and use Honor device for testing.

**Comment by yume-chan** [comment]
This is https://github.com/Genymobile/scrcpy/issues/4544#issuecomment-2526999714 with #5109 reverted: [scrcpy-server.zip](https://github.com/user-attachments/files/18221885/scrcpy-server.zip) (for client version 3.1)

Please test <kbd>Alt</kbd> + <kbd>O</kbd>/<kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd>O</kbd> on Honor devices

<details>
<summary>Diff</summary>


```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/device/Device.java b/server/src/main/java/com/genymobile/scrcpy/device/Device.java
index 3553dc27..5f84e3b0 100644
--- a/server/src/main/java/com/genymobile/scrcpy/device/Device.java
+++ b/server/src/main/java/com/genymobile/scrcpy/device/Device.java
@@ -135,20 +135,8 @@ public final class Device {
             return ServiceManager.getDisplayManager().requestDisplayPower(displayId, on);
         }
 
-        boolean applyToMultiPhysicalDisplays = Build.VERSION.SDK_INT >= AndroidVersions.API_29_ANDROID_10;
-
-        if (applyToMultiPhysicalDisplays
-                && Build.VERSION.SDK_INT >= AndroidVersions.API_34_ANDROID_14
-                && Build.BRAND.equalsIgnoreCase("honor")
-                && SurfaceControl.hasGetBuildInDisplayMethod()) {
-            // Workaround for Honor devices with Android 14:
-            //  - <https://github.com/Genymobile/scrcpy/issues/4823>
-            //  - <https://github.com/Genymobile/scrcpy/issues/4943>
-            applyToMultiPhysicalDisplays = false;
-        }
-
         int mode = on ? POWER_MODE_NORMAL : POWER_MODE_OFF;
-        if (applyToMultiPhysicalDisplays) {
+        if (Build.VERSION.SDK_INT >= AndroidVersions.API_29_ANDROID_10) {
             // On Android 14, these internal methods have been moved to DisplayControl
             boolean useDisplayControl =
                     Build.VERSION.SDK_INT >= AndroidVersions.API_34_ANDROID_14 && !SurfaceControl.hasGetPhysicalDisplayIdsMethod();
diff --git a/server/src/main/java/com/genymobile/scrcpy/wrappers/SurfaceControl.java b/server/src/main/java/com/genymobile/scrcpy/wrappers/SurfaceControl.java
index 3bae4a37..b8b41b91 100644
--- a/server/src/main/java/com/genymobile/scrcpy/wrappers/SurfaceControl.java
+++ b/server/src/main/java/com/genymobile/scrcpy/wrappers/SurfaceControl.java
@@ -95,15 +95,6 @@ public final class SurfaceControl {
         return getBuiltInDisplayMethod;
     }
 
-    public static boolean hasGetBuildInDisplayMethod() {
-        try {
-            getGetBuiltInDisplayMethod();
-            return true;
-        } catch (NoSuchMethodException e) {
-            return false;
-        }
-    }
-
     public static IBinder getBuiltInDisplay() {
         try {
             Method method = getGetBuiltInDisplayMethod();
```

</details>
