### ISSUE TITLE
No Audio Forwarding On Linux?

### ISSUE THREAD

**Issue by ItsJustTee** [Genymobile/scrcpy#4825]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Linux Mint 21.3
 - scrcpy version: 1.21.1
 - installation method: Software Manager
 - device model: Samsung Galaxy A34 5G
 - Android version: 14

**Describe the bug**
When connecting my Phone via USB through UBS3 on the back of my PC and envoking ```scrcpy``` in the Terminal, no audio can be heard even on full volume.

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed. 5.2 MB/s (39473 bytes in 0.007s)
[server] INFO: Device: samsung SM-A346E (Android 14)
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, int]
	at java.lang.Class.getMethod(Class.java:2937)
	at java.lang.Class.getMethod(Class.java:2449)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:103)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:111)
	at com.genymobile.scrcpy.Device.<init>(Device.java:93)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:63)
	at com.genymobile.scrcpy.Server.main(Server.java:309)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:415)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6.0 NVIDIA 545.29.06
INFO: Trilinear filtering enabled
INFO: Initial texture: 2336x1080

```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
You are using an outdated version (1.21).

Uninstall the package and install the latest version manually: https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md#latest-version

**Comment by ItsJustTee** [comment]
I realized just a few seconds ago. Any chance for a AppImage of scrcpy? I would not mind using an AppImage version :D

**Comment by ItsJustTee** [comment]
I did find an unofficial Repo for scrcpy AppImage releases here https://github.com/justaCasualCoder/Scrcpy-AppImage

I have no issues using this until official builds are made :D

**Comment by ItsJustTee** [comment]
Closing as completed.
