### ISSUE TITLE
help *again

### ISSUE THREAD

**Issue by SyncMaster93** [Genymobile/scrcpy#4834]
i dont know what to do anymore... i tried all commands and still lags.. its like scrcpy dont register any commands..

**Comment by rom1v** [comment]
Please give details. What did you do? What do you observe? What is the problem?

> its like scrcpy dont register any commands..

Read https://github.com/Genymobile/scrcpy/blob/master/doc/windows.md#run

**Comment by rom1v** [comment]
If you record (`scrcpy --record=file.mp4 --no-playback`), is the resulting file laggy?

**Comment by rom1v** [comment]
> im getting WARN: [FFmpeg] track 1: codec frame size is not set

Not a problem, that's just a warning. Could you post the resulting file?

**Comment by SyncMaster93** [comment]
> > im getting WARN: [FFmpeg] track 1: codec frame size is not set
> 
> Not a problem, that's just a warning. Could you post the resulting file (generated by `scrcpy --record=file.mp4 --no-playback`)?

well i tried that and it puts that warning

**Comment by rom1v** [comment]
Yes, but that's just a warning, ignore the warning. There is an error, but it automatically retries with a lower resolution.

So I think it works fine, just stop the recording after a few seconds with Ctrl+C in the console.

**Comment by SyncMaster93** [comment]
> Yes, but that's just a warning, ignore the warning. There is an error, but it automatically retries with a lower resolution.
> 
> So I think it works fine, just stop the recording after a few seconds with Ctrl+C in the console.

it lags
