### ISSUE TITLE
GPG key

### ISSUE THREAD

**Issue by bijela-gora** [Genymobile/scrcpy#4837]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
- Fedora 39

Is this correct key?

```
Importing GPG key 0xC9947AB8:
 Userid     : "zeno_scrcpy (None) <zeno#scrcpy@copr.fedorahosted.org>"
 Fingerprint: 2809 1D1D 2A7F 7DAF DF6A F726 66C4 7270 C994 7AB8
 From       : https://download.copr.fedorainfracloud.org/results/zeno/scrcpy/pubkey.gpg
```

**Comment by bijela-gora** [comment]
Thank you for your quick response!

If so, I will uninstall the package and build it manually.

**Comment by typingbeaver** [comment]
> Due to recent changes in Fedora's cryptographic policies, the old COPR repository keys were not automatically extended and need to be replaced; if you encounter an expired repository GPG key during upgrade, please delete the old key and re-import the new one.

```
sudo rpm -e $(rpm -q --qf "%{NAME}-%{VERSION}-%{RELEASE}\t%{SUMMARY}\n" gpg-pubkey | grep zeno | cut -f1)
sudo rpm --import https://download.copr.fedorainfracloud.org/results/zeno/scrcpy/pubkey.gpg
```
(https://copr.fedorainfracloud.org/coprs/zeno/scrcpy/)
