### ISSUE TITLE
Cannot Interact with the device

### ISSUE THREAD

**Issue by AliYar-Khan** [Genymobile/scrcpy#4849]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS:  Windows
 - scrcpy version: 2.0
 - installation method: Windows release
 - device model:
 - Android version: 11

**Describe the bug**
I have screen copy running, and it is mirroring the device but not able to interact with the device using mouse

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy#prerequisites

**Comment by AliYar-Khan** [comment]
@rom1v 
yeah with these options set still not working. My device is Redmi 10A and it is running Android 11+

**Comment by rom1v** [comment]
Have you rebooted your phone since you changed the options?

**Comment by AliYar-Khan** [comment]
yeah worked fine.
