### ISSUE TITLE
Video is 1.2FPS when selecting 15FPS --camera-fps

### ISSUE THREAD

**Issue by Uzver123** [Genymobile/scrcpy#4856]
**Environment**
 - OS: [Windows 10]
 - scrcpy version: [2.4]
 - installation method: [Windows 64Bit portable]
 - device model: OnePlus 8 Pro
 - Android version: [13]

**Describe the bug**
    --camera-id=0    (back, 4000x3000, fps=[15, 29, 30])
    --camera-id=1    (front, 2328x1748, fps=[15, 30])
    
    When i select --camera-fps=24 i am getting ~23fps video when i select --camera-fps=15 fps i am getting 
1.2fps
 full command `scrcpy -b1M --record-format=mp4 --no-audio-playback --video-source=camera --camera-id=0 --video-codec=h264 --camera-fps=15 --camera-size=320x240
`

**Comment by rom1v** [comment]
How do you know what frame rate you actually get?

What is the console output if you add `--print-fps`?

**Comment by Uzver123** [comment]
How do you know what frame rate you actually get?

Its recording the file i check fps then in mp4

I am getting this
```

[server] INFO: Device: [OnePlus] OnePlus IN2023 (Android 13)
[server] INFO: Using camera '0'
INFO: Renderer: direct3d
INFO: Texture: 320x240
INFO: FPS counter started
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
INFO: 1 fps
[server] INFO: Retrying...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying...
INFO: 1 fps
```

**Comment by rom1v** [comment]
Did you try with another encoder? https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#encoder

Is screen mirroring working correctly?

**Comment by Uzver123** [comment]
> Did you try with another encoder? https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#encoder

```
15fps broken  --video-codec=h264 --video-encoder='OMX.qcom.video.encoder.avc'
15fps working --video-codec=h264 --video-encoder='c2.android.avc.encoder'
15fps working --video-codec=h264 --video-encoder='OMX.google.h264.encoder'

15fps broken  --video-codec=h265 --video-encoder='OMX.qcom.video.encoder.hevc'
15fps broken  --video-codec=h265 --video-encoder='OMX.qcom.video.encoder.hevc.cq'
15fps broken  --video-codec=h265 --video-encoder='c2.android.hevc.encoder'
```
Wonder why no h265 codec work with 15fps only h264?

> Is screen mirroring working correctly?

Regular feed not camera is working okay.
