### ISSUE TITLE
Mouse input issues in games

### ISSUE THREAD

**Issue by playbyan1453** [Genymobile/scrcpy#4862]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).

 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: 2.4 (x64)
 - installation method: Windows
 - device model: Samsung S9 Plus (star2lte)
 - Android version: 10

**Describe the bug**
When playing games such as Minecraft using the `-MK` argument the right click mouse behaves differently from `--otg` argument, it should place blocks instead simulating press back button.

**Comment by rom1v** [comment]
Add `--forward-all-clicks`.
