### ISSUE TITLE
Neither directory contains a build file meson.build.

### ISSUE THREAD

**Issue by DeCarvalho83** [Genymobile/scrcpy#487]
1st, its not related to #35 
As @rom1v told me i did download prebuilt server from file with wget and ran the command told by prebuilt server part..

the file is saved under /home/ruti/scrcpy/ folder and original name

ls shows
>ruti@Ruti-Vayo:~/scrcpy$ ls
>scrcpy-server-v1.8.jar

the command line is
>meson x --buildtype release --strip -Db_lto=true \
>    -Dprebuilt_server=/path/to/scrcpy-server.jar

and im running this one
>meson x --buildtype release --strip -Db_lto=true \
>    -Dprebuilt_server=/home/ruti/scrcpy/scrcpy-server-v1.8.jar

the reply from console is
>Error during basic setup:
>Neither directory contains a build file meson.build.

To be sure the place is correct im using tab for auto-completation

 tried to look over here and there and didnt find any thing helpful, thats why im opening this one..

once again, i turned to linux today from windows.. so sorry if it is as simple as say simple.. but i really dont know a thing about linux. :)

**Comment by rom1v** [comment]
Do you execute this command from your `scrcpy` directory? What is the content of this directory? (`ls`)

**Comment by DeCarvalho83** [comment]
Hiho, well i did run from the directory.. after many tries i just gave up, sorry for late answer buz i went busy with college stuff..

I went back to windows.. im more used to it and scrcpy works w/o any problems (for me) on it..

Thans anyway

**Comment by rom1v** [comment]
> well i did run from the directory

From the directory where you `git clone` scrcpy?

**Comment by DeCarvalho83** [comment]
Didnt get you.
I was using the pre-built one..

so as stated in the issue post, i did download to the folder /home/ruti/scrcpy/ and ran it following the directions..

I tried build myself and i was having problem and then you told me to try the pre-built one..

**Comment by rom1v** [comment]
Only the server is prebuilt, the `meson` and following commands are to build the client on your machine, so you need to clone the repository and execute the commands there.

**Comment by DeCarvalho83** [comment]
So maybe it was the problem cuz after having problem with previous attempts i did delete the entire folder and download the server only..

Well.. my bad.. i'll run ubuntu from stick to make a test to be sure it was the problem and i'll back with an answer..

I just cant do it right now.. 
But i'll asap..

Sorry for my dumbness
Thanks in advance ;)
