### ISSUE TITLE
Perfect Pixel (alt+g) not working properly.

### ISSUE THREAD

**Issue by DienoX** [Genymobile/scrcpy#4880]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...] Windows
 - scrcpy version: [e.g. 1.12.1] newest 
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...] Windows release
 - device model: waydroid
 - Android version: [e.g. 10] 11

**Describe the bug**
Pixel perfect It's not working properly.
After using alt+g, the height is 4 pixels too low.
I use waydroid and on the waydroid screen via rdp the quality seems to be much better.
Below are my measurements from GIMP.
![image (1)](https://github.com/Genymobile/scrcpy/assets/2558401/5271c21d-e8bd-4012-9010-231353518068)
![image](https://github.com/Genymobile/scrcpy/assets/2558401/04eddbf9-493d-4967-9629-8b319fbb4c5b)

**Comment by rom1v** [comment]
> After using alt+g, the height is 4 pixels too low.

This is not alt+g, it's the window size of the device which is not a multiple of 8, so scrcpy rounds it down to the next multiple of 8 (it is a requirement for many encoders). Check the size reported by scrcpy, probably:

> INFO: Texture: 960x536

> I use waydroid and on the waydroid screen via rdp the quality seems to be much better.

You can adapt video quality by changing the codec, encoder and bitrate. See https://github.com/Genymobile/scrcpy/blob/master/doc/video.md

**Comment by rom1v** [comment]
You have nothing to apologize for. :wink:
