### ISSUE TITLE
Input only via tcpip

### ISSUE THREAD

**Issue by NeedsLoomis** [Genymobile/scrcpy#4891]
When I disable video and audio over tcpip I get the error "ERROR: No video, no audio, no OTG: nothing to do"

I use OTG mode in order to use my tablet as a second machine/screen while sharing a mouse and keyboard. It would be nice to have this functionality over wifi.

**Comment by rom1v** [comment]
See https://github.com/Genymobile/scrcpy/pull/4868 and https://github.com/Genymobile/scrcpy/issues/4727#issuecomment-1978115575.

**Comment by NeedsLoomis** [comment]
Nice, closing the request!
