### ISSUE TITLE
OBS unable capture scrcpy audio when --no-video option is used

### ISSUE THREAD

**Issue by 4nric** [Genymobile/scrcpy#4897]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS:  Windows
 - scrcpy version: 2.4
 - installation method: Windows release
 - device model: SM-G975N
 - Android version: 12

**Describe the bug**
I'm using OBS's Application Audio Capture, scrcpy is not listed if there's no scrcpy window active. This behavior may be intended and actually is cleaner, just have the terminal and no additional window. But OBS can't capture audio this way for now. I tried providing width and height values but those are ignored if --no-video is used. 

`scrcpy --no-video --audio-source=mic --window-width=100 --window-height=100 --window-title=mic `

**Comment by rom1v** [comment]
Please test this PR: https://github.com/Genymobile/scrcpy/pull/4868

**Comment by rom1v** [comment]
^ Basically, this version opens a window even when video playback is disabled. That way, you should be able to capture the window audio. Could you confirm, please?

**Comment by 4nric** [comment]
I can confirm obs can now capture scrcpy audio this way. Would be great to have both options, hidden and visible. Thanks!

**Comment by rom1v** [comment]
> I can confirm obs can now capture scrcpy audio this way. Would be great to have both options, hidden and visible. Thanks!

Thank you.

In this PR, by default a window will be open, but there is a new option `--no-window` to disable it.
