### ISSUE TITLE
Mouse click not working but Keyboard works perfectly

### ISSUE THREAD

**Issue by graphyle** [Genymobile/scrcpy#4902]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 11
 - scrcpy version: v2.4
 - installation method: Windows release
 - device model: Lenovo Tab M10 FHD Plus
 - Android version: 10

**Description**
Hello, the bug, as is it described in the title, is that the mouse click (allowing navigation on the device) doesn't works but, surprisingly, the keyboard works perfectly. Search and saw a lot of topic speaking about instructions like :

```
-m1750
```

This command helps well to resolve the resolutions problems, but not the "WARN: Ignore touch event, it was generated for a different device size" problem.

```
scrcpy 2.4 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  HPV2T7VQ                        device  Lenovo_TB_XXXXX
C:\Users\XXXXX\Downloads\scrcpy-win64-v2.4\scrcpy-win64-v2...file pushed, 0 skipped. 202.9 MB/s (69007 bytes in 0.000s)
[server] INFO: Device: [LENOVO] Lenovo Lenovo TB-XXXXX (Android 10)
[server] WARN: Audio disabled: it is not supported before Android 11
INFO: Renderer: direct3d
WARN: Demuxer 'audio': stream explicitly disabled by the device
INFO: Texture: 1920x1200
INFO: Texture: 1920x1080
[server] WARN: Ignore touch event, it was generated for a different device size
[server] WARN: Ignore touch event, it was generated for a different device size
```

Thanks for your help! ;)

**Comment by rom1v** [comment]
Try `scrcpy -m1728`.

Explanation: your device is 1920×1200, but the encoder decides on its own to change the output size (probably because it does not support a higher resolution) to 1920×1080. If you resquest a max size of 1728, it will encode at 1728×1080 (which is the same ratio as 1920×1200).

**Comment by graphyle** [comment]
Works perfectly, thanks a lot! ^^

**Comment by graphyle** [comment]
Works perfectly, thanks a lot! ^^
