### ISSUE TITLE
Performance Optimization Needed for Modified scrcpy Project

### ISSUE THREAD

**Issue by muyiraolong** [Genymobile/scrcpy#4913]
I have modified the scrcpy project to record mobile device behavior, convert the resulting video into images, and name these images based on the system timestamp displayed on the device. While I achieve good results on devices with powerful CPUs (with a timestamp discrepancy of less than 5ms compared to a trace), I encounter significant performance issues and high latency (with a timestamp discrepancy of over 15ms compared to a trace) on devices with less capable CPUs.

As I am working on a project where performance overhead is crucial, I would like to seek advice on potential optimizations that I could implement in the source code and instructions. Specifically, I'm wondering:

1. What areas of the scrcpy codebase should I focus on for improving performance, especially on lower-end devices?

2. Are there any known optimizations or techniques that could reduce the delay between capturing the screen and processing the resulting image?

I appreciate any guidance or suggestions that the community may have in addressing these performance challenges. Your assistance in this matter would be greatly appreciated. Thank you for considering my inquiry and for your time.

**Comment by rom1v** [comment]
The timestamps of captured frames are provided directly by MediaCodec with the encoded packet:

https://github.com/Genymobile/scrcpy/blob/206809a99affad9a7aa58fcf7593cea71f48954d/server/src/main/java/com/genymobile/scrcpy/SurfaceEncoder.java#L175
https://github.com/Genymobile/scrcpy/blob/206809a99affad9a7aa58fcf7593cea71f48954d/server/src/main/java/com/genymobile/scrcpy/Streamer.java#L82

This is (or should be) the capture time, not the time where you retrieve the encoded frame, so if you check the current time when MediaCodec provides a frame, it's a bit later, depending on your device/encoder, so it's expected that a trace would be "delayed" compared to the capture time. Maybe you should subtract the duration between the capture time and the current time immediately after the MediaCodec call returns if you want to compare with your own timestamped traces.
