### ISSUE TITLE
ERROR: audio demuxer and video decoder problems

### ISSUE THREAD

**Issue by AbsoluteTakeOff** [Genymobile/scrcpy#4923]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10 64 bit version
 - scrcpy version: v2.4
 - installation method: Windows release
 - device model: BRAVIA 4K 2015
 - Android version: 8.0.0

**Describe the bug**
My Android TV connect perfectly via adb but there are issue with audio and video on my tv

```
[server] INFO: Device: [Sony] Sony BRAVIA 4K 2015 (Android 8.0.0)
[server] WARN: Audio disabled: it is not supported before Android 11
INFO: Renderer: direct3d
WARN: Demuxer 'audio': stream explicitly disabled by the device
INFO: Texture: 1920x1080
ERROR: [FFmpeg] no frame!
ERROR: Decoder 'video': could not send video packet: -1094995529
ERROR: Demuxer error
```

**Comment by rom1v** [comment]
> ERROR: Decoder 'video': could not send video packet: -1094995529

```console
$ printf '%x' 1094995529 | xxd -r -p | rev
INDA
```

The error is `AVERROR_INVALIDDATA`. It seems that your device encoder does not produce valid data.

Try with another encoder: https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#encoder

**Comment by AbsoluteTakeOff** [comment]
> > ERROR: Decoder 'video': could not send video packet: -1094995529
> 
> ```
> $ printf '%x' 1094995529 | xxd -r -p | rev
> INDA
> ```
> 
> The error is `AVERROR_INVALIDDATA`. It seems that your device encoder does not produce valid data.
> 
> Try with another encoder: https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#encoder


Thanks for the help, it now shows the screen but still there is no sound. i used `scrcpy --max-size=1024` command to fix my issue. and this is my console:
`C:\Users\DELL\Desktop\scrcpy-win64-v2.4\scrcpy-server: 1 file pushed, 0 skipped. 23.0 MB/s (69007 bytes in 0.003s)
[server] INFO: Device: [Sony] Sony BRAVIA 4K 2015 (Android 8.0.0)
[server] WARN: Audio disabled: it is not supported before Android 11
INFO: Renderer: direct3d
WARN: Demuxer 'audio': stream explicitly disabled by the device
INFO: Texture: 1024x576`

**Comment by AbsoluteTakeOff** [comment]
By the way I saw this in Audio.md:

**- For Android 10 or earlier, audio cannot be captured and is automatically disabled.**

So I cant have audio? cuz my android tv has android 8.0.0.

**Comment by rom1v** [comment]
Correct, you can't enable audio for Android 8.

Btw, there is a warning in your logs:

> [server] WARN: Audio disabled: it is not supported before Android 11

**Comment by AbsoluteTakeOff** [comment]
> Correct, you can't enable audio for Android 8.
> 
> Btw, there is a warning in your logs:
> 
> > [server] WARN: Audio disabled: it is not supported before Android 11

Well I have a sony KD 55x8500D (BRAVIA 4K 2015), and sony stopped making updated for this model. can i just flash the TV using the google's official android 12 tv?
