### ISSUE TITLE
getDeviceName change

### ISSUE THREAD

**Issue by mudebug77** [Genymobile/scrcpy#4927]
Is your feature request related to a problem? Please describe.
Currently, it's challenging to identify which device's scrcpy-server is connected when multiple devices are connected simultaneously. This is particularly problematic when managing multiple devices remotely.

Describe the solution you'd like
I would like to propose adding a new parameter to scrcpy-server that allows users to customize the sendDeviceMeta identifier. This parameter would enable users to distinguish between different connected devices by providing a unique identifier or label.

Describe alternatives you've considered
One alternative could be modifying the source code to manually pass device identifiers. However, having a built-in parameter would streamline this process and make it more user-friendly.

Additional context
Adding this feature would enhance the usability of scrcpy-server in scenarios where multiple devices are connected simultaneously, providing users with more control and flexibility.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/doc/window.md#title ?

**Comment by mudebug77** [comment]
I don't want to modify the title of scrcpy; I want to build the scrcpy program myself to manage each device centrally. When scrcpy-server sends sendDeviceMeta, it's not unique. If I have 10 devices, I can only start scrcpy-server for one device at a time using adb, rather than starting scrcpy-server for all devices simultaneously because I can't get a unique identifier for each device.
