### ISSUE TITLE
Problem of cross-compile noconsole to windows from Ubunt

### ISSUE THREAD

**Issue by Lucifer050a** [Genymobile/scrcpy#494]
output scrcpy-noconsole.exe still open a console window.

this is double click:
![image](https://user-images.githubusercontent.com/9650227/55849981-36391780-5b85-11e9-83c5-0861d3a1cd13.png)

it's deffent between download program from github release:
![image](https://user-images.githubusercontent.com/9650227/55850394-b90ea200-5b86-11e9-984b-2db53fa114c6.png)

how to resolve it.

**Comment by rom1v** [comment]
Which version (commit) did you compile?

**Comment by Lucifer050a** [comment]
> Which version (commit) did you compile?
> 
> What if you revert [ffa8c66](https://github.com/Genymobile/scrcpy/commit/ffa8c66979d4262a95cad584894b9a5fbeea0e84)?

no matter revert this commit or checkout v1.8, it still open console window.
i'm compile on ubuntu 18.10 in hyper-v, version of libsdl2-dev is 2.0.8+dfsg1-4ubuntu1.

**Comment by rom1v** [comment]
What commands did you execute exactly?

**Comment by rom1v** [comment]
Did you just execute `./release.sh`?

**Comment by Lucifer050a** [comment]
> Did you just execute `./release.sh`?

I just folllow the chapter `System-specific steps->Linux->Debian/Ubuntu` and `System-specific steps->Windows->Cross-compile from Linux` of build.md step by step before.

Now i rebuild in a new installer of ubuntu, found the reason:
Before `sudo apt install python3-pip
pip3 install meson`(meson's version 0.47.2), several build programs run good;
After `pip3 install meson`(meson version 0.50.0), build programs will open a console window;
And i uninsall meson use pip3, program run good again.
Maybe some change in meson's new version. No bug or trouble in scrpy, but i think point this out in BUILD.md is better.

finally, thank your warmly reply.

**Comment by rom1v** [comment]
> I just folllow the chapter System-specific steps->Linux->Debian/Ubuntu and System-specific steps->Windows->Cross-compile from Linux of build.md step by step before.

Scrcpy needs a specific compilation flag, to pass to meson: `-Dwindows_noconsole=true`.
