### ISSUE TITLE
Different frame rate when i cast my device with the screen off

### ISSUE THREAD

**Issue by UsikaDesu** [Genymobile/scrcpy#4945]
This is my frame rate if i turn my device screen off and make it stay awake so i can save some energy for my phone
![image](https://github.com/Genymobile/scrcpy/assets/109031388/8bb8e317-0bb2-4eee-9e89-70666444f0d2)

This is my frame rate if i turn my device screen on but it makes my device a lot hot because the screen is on
![image](https://github.com/Genymobile/scrcpy/assets/109031388/86ed7051-bd67-4625-8653-722727248f31)

Is this normal?

Device: Poco F4

**Comment by rom1v** [comment]
See #4587
