### ISSUE TITLE
Can't scrcpy mirror the screen when the screen displays the password?

### ISSUE THREAD

**Issue by Ud1nG4con** [Genymobile/scrcpy#4951]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 
 - scrcpy version: 2.4
 - device model: Redmi note 11

my scrcpy run normal as usual, but when i open the apps that required a password the screen just show a black screen, just like when I open a chat that contains stickers on Telegram it only displays a black screen, but when the sticker is no longer visible on the screen, scrcpy is normal as it should be.

**Comment by rom1v** [comment]
Because your launcher app set the "secure flag" to prevent the screen to be captured.

Refs #36 #2129

**Comment by Ud1nG4con** [comment]
> Because your launcher app set the "secure flag" to prevent the screen to be captured.
> 
> Refs #36 #2129



> Because your launcher app set the "secure flag" to prevent the screen to be captured.
> 
> Refs #36 #2129

tanks for the answer
and how i fix that?

**Comment by rom1v** [comment]
> and how i fix that?

That's an Android limitation, there is nothing to "fix". There are basically 3 ways to bypass it:

 - run the app on a device having Android < 12
 - root your device (ref [#3049](https://github.com/Genymobile/scrcpy/issues/3049) [#3515](https://github.com/Genymobile/scrcpy/issues/3515))
 - decompile/recompile your app to disable the "secure flag" (with a tool like [apk.sh](https://github.com/ax/apk.sh))

**Comment by Ud1nG4con** [comment]
> Because your launcher app set the "secure flag" to prevent the screen to be captured.
> 
> Refs #36 #2129



> > and how i fix that?
> 
> That's an Android limitation, there is nothing to "fix". There are basically 3 ways to bypass it:
> 
> * run the app on a device having Android < 12
> * root your device (ref [#3049](https://github.com/Genymobile/scrcpy/issues/3049) [#3515](https://github.com/Genymobile/scrcpy/issues/3515))
> * decompile/recompile your app to disable the "secure flag" (with a tool like [apk.sh](https://github.com/ax/apk.sh))

okay then thanks for the advice.
