### ISSUE TITLE
Cannot build scrcpy

### ISSUE THREAD

**Issue by Federicomang** [Genymobile/scrcpy#4955]
Hi,

I can't build scrcpy on Windows 11 with the Linux subsystem. After launching the release.sh file the server is built but when it tries to build SDL it gets either `"Input/Output"` or `"Cannot allocate memory"` errors.

I also tried to launch release.sh on a computer with Ubuntu 22.04 and in that case it gets an `"ERROR: zlib requested but not found"` error when trying to build ffmpeg even though the library is installed.

Obviously I followed the guide for both Windows and Linux and therefore installed everything written in the guide.

Could anyone help me? My goal is to build scrcpy for Windows

Thank you

**Comment by Federicomang** [comment]
Thanks a lot, now ffmpeg has built but now it gives me an error when trying to cross-build for win32

The error is `Pkg-config binary for machine 1 not found. Giving up.`

I had already installed pkg-config via the following command `sudo apt-get install pkg-config`

**Comment by rom1v** [comment]
> Thanks a lot, now ffmpeg has built 

:+1: Documentation updated: b5849db32fdd4bd1bba4e8084e5bfa368f6e9747

> The error is `Pkg-config binary for machine 1 not found. Giving up.`

Your meson is too old.

Revert this commit to make it work: 85a94dd4b563e961304b2d9082932c5c1cc2e582

**Comment by Federicomang** [comment]
Perfect, now all works, thanks a lot!
