### ISSUE TITLE
Some Commands Dont Work

### ISSUE THREAD

**Issue by MrTeeXD** [Genymobile/scrcpy#496]
Hello, so i found out that some commands dont work and i was wondering if someone else is experiecing the same thing, i found some commands on this Repo's ReadMe

**Comment by rom1v** [comment]
You need to pass these parameters as command-line arguments, not write them in the console of scrcpy.

See https://github.com/Genymobile/scrcpy/issues/385.

**Comment by MrTeeXD** [comment]
So from my understanding, i need to use Command Prompt, correct?

**Comment by rom1v** [comment]
Yes, start `cmd.exe`, go to the _scrcpy_ directory using `cd your_scrcpy_path`, then execute `scrcpy` with arguments:

     scrcpy --version
