### ISSUE TITLE
Strange Audio Issue

### ISSUE THREAD

**Issue by ItsJustTee** [Genymobile/scrcpy#4971]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Kubuntu 24.04
 - scrcpy version: 2.4
 - installation method: Community AppImage
 - device model: Samsung Galaxy A34
 - Android version: 14

**Describe the bug**
Apparently, scrcpy tries to find a libjack.so file, but I am using PulseAudio. scrcpy worked before but now this just shows up.

```
/tmp/.mount_scrcpychBbZs/usr/bin/scrcpy: error while loading shared libraries: libjack.so.0: cannot open shared object file: No such file or directory
```

**Comment by rom1v** [comment]
Scrcpy does not, but maybe your SDL or ffmpeg builds do.

It might be related to your AppImage (I don't know). Maybe try a "native" build: https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md#latest-version

**Comment by ItsJustTee** [comment]
The only reason I use the AppImage is because the scrcpy in the software managers are out of date. It was a final recourse.

**Comment by rom1v** [comment]
Yes, I understand. But you might try the `./install_release.sh` script (documented in page pointed by the previous link)

**Comment by ItsJustTee** [comment]
Will do, thank you.

**Comment by ItsJustTee** [comment]
Closing as Third Party Build issues
