### ISSUE TITLE
Can't set camera to record when connected to scrcpy.exe or ADB

### ISSUE THREAD

**Issue by Fine-Tune** [Genymobile/scrcpy#498]
Hi,

When connected to scrcpy everything works fine, except I can't enable the camera app to record video or take a picture. I'm using open camera but with the default camera I have the same issue.

I'm trying to record a video while my phone is on a tripod and connected through USB to my desktop. I would like to set the camera in recording mode while monitoring what I'm filming on one of my desktop monitors.

When I press record, it doesn't stay in rec mode, yet a VID file is written on my sd card but has 0 data.

I tried cat-log to see what's wrong but it shows no errors at all.

Any suggestions would be welcome, thanks!

**Comment by Fine-Tune** [comment]
I should have mentioned, the phone is a Samsung S5Neo running Android 6.1

**Comment by kkarakk** [comment]
works just fine for me on native camera on  samsung a50 running Android pie v9.0 and a samsung s5 running(6.0.1) . have you tried recording the screen with camera open (scrcpy --record file.mp4) instead of recording with the camera. bad workaround i know but atleast you'll have SOME output...

**Comment by rom1v** [comment]
Both _scrcpy_ and your camera needs to encode the video with your hardware encoder. It may or may not support to do both simultaneously.

Can you start several _scrcpy_ instances for the same device?

Does it work with a lower definition (`scrcpy -m800` + record your camera)?

**Comment by Fine-Tune** [comment]
Hi, thanks for the replies.

When starting a second scrcpy instance it gives the following lines...

ERROR: Could not open video stream
ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xffffec77
at android.media.MediaCodec.native_configure<Native Method>
at INFO: Initial texture: 1080x1920
android.media.MediaCodec.configure<MediaCodec.java:1778>
at com.genymobile.scrcpy.ScreenEncoder.configure<ScreenEncoder.java157>
at com.genymobile.scrcpy.ScreenEncoder.streamscreen<ScreenEncoder.java68>
at com.genymobile.scrcpy.Scrcpy.Server.scrcpy<Server.java28>
at com.genymobile.scrcpy.Scrcpy.Server.main<Server.java110>
at com.android.internal.osRuntimeInit.nativeFinishInit<Native Method>
at com.android.internal.osRuntimeInit.main<Runtimeinit.java:257>

I tried the suggested method scrcpy -m800 but this also doesn't work.

@kkarakk: I do have same issue on the stock camera app aswell.

For now I'm using Screen Stream app as wokarround, extremally laggy but atleast I can see what I'm doing.

Thanks!

**Comment by SuperUserNameMan** [comment]
Hello, 

Same issue here with an Android 5.1 running on an "Archos 50d Helium" and Srcpy 1.11 from #944 running under Windows 8.1 x64.

Taking picture works for me, but recording video fails :
``java.lang.IllegaleStateException : failed to get surface``

**Comment by SuperUserNameMan** [comment]
PS : it works if ``scrcpy -m 480`` :-)
