### ISSUE TITLE
problem with click

### ISSUE THREAD

**Issue by Tr43212** [Genymobile/scrcpy#4988]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 8.1 Pro (build 9600.20778) 64-bit
 - scrcpy version: v2.4
 - installation method: Windows release
 - device model: Xiaomi Redmi Note 8 Pro (begiona)
 - Android version: 11

**Describe the bug**
Hello. Right-click and middle-click didn't work on my device. Left-click and mouse-scroll are just working fine. I enabled USB debugging, but it's still not working.

**Comment by Tr43212** [comment]
P/S: Right-click in OTG works, but in UHID doesn't work.

**Comment by rom1v** [comment]
By default, right click is a shortcut for BACK and middle click a shortcut for HOME.

To forward the clicks instead, use `scrcpy --forward-all-clicks`.

**Comment by Tr43212** [comment]
Thanks you so much, it's working now.

**Comment by rom1v** [comment]
Please also test #5022 :wink:
