### ISSUE TITLE
Game Capture Issues

### ISSUE THREAD

**Issue by MrTeeXD** [Genymobile/scrcpy#499]
I found a bug where if you change the Bitrate, scrcpy will no longer be picked up by OBS's Game Capture and you need to switch to Window Capture to hook on to scrcpy

**Comment by rom1v** [comment]
That's very weird, the bitrate is just an encoder parameter on the device-side.

**Comment by MrTeeXD** [comment]
I did nit break anything else

**Comment by rom1v** [comment]
Do you still have the problem?

I'm pretty sure the bitrate is unrelated to your problem.

**Comment by MrTeeXD** [comment]
Nope, all cleared up, i forgot about this issue. Thank you
