### ISSUE TITLE
Anti-aliasing when reducing resolution

### ISSUE THREAD

**Issue by nagisa-eevee** [Genymobile/scrcpy#4997]
- [Y] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
Severe heavy aliasing appear when reduce window size.

**Describe the solution you'd like**
Add anti-aliasing，such as bilinear.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by rom1v** [comment]
On OpenGL, mipmapping is enabled by default (unless you pass `--no-mipmaps`.

Try `scrcpy --render-driver=opengl`.

Unfortunately, on Windows, there is nothing exposed in SDL to enable mipmapping for directx, and opengl drivers are often not optimal on Windows.

**Comment by nagisa-eevee** [comment]
Sadly, these do not work for me (on Windows 10). However, I find using the Picture-in-Picture (PiP) feature of external softwares can solve this issue.
