### ISSUE TITLE
Wireless - my adb device is disconnected when removing usb

### ISSUE THREAD

**Issue by Bagggas** [Genymobile/scrcpy#500]
https://forums.oculusvr.com/community/discussion/67294/adb-wireless-scrcpy-adb-device-disappears-on-usb-disconnect

its like that but im on windows

**Comment by rom1v** [comment]
Is your device an Oculus Go?

**Comment by Bagggas** [comment]
its asus ze552kl sir

**Comment by rom1v** [comment]
What if you first disconnect usb, then `adb connect`?

**Comment by Bagggas** [comment]
![Screenshot_6](https://user-images.githubusercontent.com/48177875/56148957-a9072000-5fd5-11e9-8ec3-0200d66243b2.png)

it seems when i plug the usb and `adb devices` my device is available and when unplug its gone.

**Comment by KBeDeveloper** [comment]
Just follow those steps in -> http://codetheory.in/android-debug-bridge-adb-wireless-debugging-over-wi-fi/
