### ISSUE TITLE
Black Screen after Update of Android's One UI-Version 6.1

### ISSUE THREAD

**Issue by kagahd** [Genymobile/scrcpy#5009]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: macOS Sonomoa 14.5
 - scrcpy version: 2.4
 - installation method: brew
 - device model: Samsung Galaxy S22
 - Android version: 14
 - One UI-Version: 6.1

**Describe the bug**
Until the update of Androids One UI-Version to version 6.1, `scrcpy` worked correctly. After the Android update, `scrcpy` shows a black screen. The keyboard is still working, means, I can type on the keyboard and it's transmitted to the Android device. However, the mirrored screen is always black.

```
❯ scrcpy
scrcpy 2.4 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  R3CT20HC1ZR                     device  SM_S901B
/opt/homebrew/Cellar/scrcpy/2.4_1/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 18.0 MB/s (69007 bytes in 0.004s)
[server] INFO: Device: [samsung] samsung SM-S901B (Android 14)
INFO: Renderer: metal
INFO: Texture: 1080x2336
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
On all apps, or only the "protected" apps? (#36)

**Comment by kagahd** [comment]
> On all apps, or only the "protected" apps? (#36, #2129)

On all apps.
No errors are shown in the shell though.

**Comment by rom1v** [comment]
If you record with `screenrecord`, is it black?

```
adb shell screenrecord /sdcard/file.mp4
adb pull /sdcard/file.mp4
```

**Comment by kagahd** [comment]
Interesting! `screenrecord` works. I can see my Android device in the `file.mp4`. Do I need some additional settings?

**Comment by rom1v** [comment]
Oh, it might be a rendering issue then.

What if you record with scrcpy?

```
scrcpy --no-playback --record=file.mp4
```

**Comment by kagahd** [comment]
> What if you record with scrcpy?

That works too! 😄 And now?

**Comment by rom1v** [comment]
OK, then it's a rendering issue on the client side, not related to your Android update (maybe a SDL update related to metal rendering?)

Try with another render driver:

```
scrcpy --render-driver=opengl
scrcpy --render-driver=opengles
scrcpy --render-driver=opengles2
scrcpy --render-driver=software
```

**Comment by kagahd** [comment]
The first command results in this error:
```
❯ scrcpy --render-driver=opengl
scrcpy 2.4 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  R3CT20HC1ZR                     device  SM_S901B
/opt/homebrew/Cellar/scrcpy/2.4_1/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 275.9 MB/s (69007 bytes in 0.000s)
[server] INFO: Device: [samsung] samsung SM-S901B (Android 14)
INFO: Renderer: opengl
ERROR: Could not create OpenGL context: Failed creating OpenGL context
```
The last 3 commands just show a black mirrored screen. The same as `scrcpy`.

**Comment by kagahd** [comment]
Problem solved: it was a out-of-memory error. Once I closed some apps on my MacBook, `scrcpy` works correctly again.
Thanks @rom1v for your quick help!
