### ISSUE TITLE
Preview Quality

### ISSUE THREAD

**Issue by MrTeeXD** [Genymobile/scrcpy#501]
Hello, it seems like the preview is a little bit of low quality, for example, theres not enough sharpness any way of improving this?

**Comment by rom1v** [comment]
Could you post a screenshot, please?

**Comment by rom1v** [comment]
Similar to https://github.com/Genymobile/scrcpy/issues/40?

**Comment by MrTeeXD** [comment]
Here is the screenshot in scrcpy :
![Scrappy](https://user-images.githubusercontent.com/37266538/56285133-c98ac380-6116-11e9-9f53-6c3a1624a5e0.PNG)

**Comment by rom1v** [comment]
Please also send a capture of the device:

    adb exec-out screencap -p > image.png

What if you press Ctrl+G ("pixel perfect") in scrcpy?

**Comment by MrTeeXD** [comment]
![image](https://user-images.githubusercontent.com/37266538/56285857-816ca080-6118-11e9-8b78-53c3949e047d.png)

**Comment by MrTeeXD** [comment]
It seems like when i try to open the image, the photo viewer says its unsupported

**Comment by rom1v** [comment]
Probably duplicate of #40.
