### ISSUE TITLE
AUDIO ROUTE (audio device)

### ISSUE THREAD

**Issue by DWSonnet** [Genymobile/scrcpy#5011]
I would like to know if it is possible not to transmit the audio to my computer headphones but to my cell phone speakers.

**Comment by kaishshaikh376** [comment]
> I would like to know if it is possible not to transmit the audio to my computer headphones but to my cell phone speakers.

Yes it is possible via vbf or bat script with the" --no-audio" command

**Comment by DWSonnet** [comment]
I understand, but I also want the sound to be heard in the transmission

**Comment by rom1v** [comment]
#3875

**Comment by DWSonnet** [comment]
> #3875

Any solution? :(

**Comment by rom1v** [comment]
Closing as duplicate (see #3875).
