### ISSUE TITLE
Cannot compile 32-bit Windows binaries using a 64-bit Ubuntu-based build environment

### ISSUE THREAD

**Issue by Giantvince1** [Genymobile/scrcpy#5012]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Linux Mint 21.3 (based on Ubuntu 22.04)
 - scrcpy version: Latest ```dev``` with my own patches
 - installation method: N/A; build system bug
 - device model: N/A; build system bug
 - Android version: N/A; build system bug

**Describe the bug**
I am doing some work on my pull request #4977 but I cannot build Windows binaries as it tires to build the 32-bit version first, then the 64-bit version. However it refuses to build the 32-bit version as it seemingly cannot fing pkg-config, CMake, or libavformat (and other A/V-related packages) on my system despite them being installed. I cannot install both architectures at the same time, however, so this may be what is causing the problem, as it is expecting the 32-bit versions of these packages. Installing the 32-bit version forcefully removes the 64-bit versions though, making that an impossible choice.

Please keep in mind that building the Linux native binaries works perfectly, at least for the 64-bit binaries; I don't have an easy way to test if building 64-bit-only Windows binaries will work or not at this time, but I'm pretty sure that it would work.

On errors, please provide the output of the console (and `adb logcat` if relevant).

Please check ```https://gist.github.com/Giantvince1/b2047d0354f713d3e33d2e337c47f683``` for the full build log. The build log is WAY too massive to fit here, so I was forced to use some sort of method of storing the build log directly.

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
Did you install `mingw-w64-tools`?

Maybe try to revert this commit: https://github.com/Genymobile/scrcpy/commit/85a94dd4b563e961304b2d9082932c5c1cc2e582

(cf #4504)

**Comment by Giantvince1** [comment]
I do have ```mingw-w64-tools``` installed, as well as all other requirements for building the software. But again, the script is somehow checking for the 32-bit versions of certain packages, but I can't cross-install both architectures at once to allow it to complete. I'll see if reverting the commit mentioned may help.

**Comment by Giantvince1** [comment]
Update: reverting that exact commit actually allows it to fully build a Windows release! I will add my reversion of that commit to my PR #5014 so that anyone who needs to build a Windows version can do so from WSL.
