### ISSUE TITLE
Allow to show protected screen rather than black screen

### ISSUE THREAD

**Issue by freebrowser1** [Genymobile/scrcpy#5018]
**Is your feature request related to a problem? Please describe.**
Some (protected) screens are not shown in scrcpy by default

**Describe the solution you'd like**
Can there be an option to just show the contents of a protected screen via scrcpy ?

**Comment by rom1v** [comment]
Not possible without root since Android 12: #36 #2129

**Comment by freebrowser1** [comment]
But I am rooted and there appears to be a scrcpy-root which just adds the --root option which obviously can only be used on rooted devices.
Can this option be built in into the general scrcpy ?
