### ISSUE TITLE
scrcpy video outputs lines of colors

### ISSUE THREAD

**Issue by istrueuser** [Genymobile/scrcpy#5019]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: v2.4
 - installation method: Windows release
 - device model: RMX2020
 - Android version: 13

**Describe the bug**
Audio and controls works fine, but the video encoding might have gone wrong somewhere, yet I have tried both h264 and h265, they display almost the same screen. Literally nothing unusual in the console itself...

```
scrcpy 2.4 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     --> (tcpip)  192.168.0.109:5555              device  RMX2020
C:\Users\trueuser\OneDrive\Desktop\scrcpy-win64-v2.4\scrcp... file pushed, 0 skipped. 52.1 MB/s (69007 bytes in 0.001s)
[server] INFO: Device: [realme] realme RMX2020 (Android 13)
INFO: Renderer: direct3d
INFO: Texture: 1600x720
```

![image](https://github.com/Genymobile/scrcpy/assets/83166512/3144ca99-46bb-4a75-8a2d-061f067f7787)

**Comment by Riztard** [comment]
> Probably an encoder issue on the device.
> 
> 1. Try with another [encoder](https://github.com/Genymobile/scrcpy/blob/master/doc/video.md?rgh-link-date=2024-06-24T13%3A26%3A18Z#encoder).

nice that fixed my display problem
