### ISSUE TITLE
Device unauthorized with ADB Version 1.0.40

### ISSUE THREAD

**Issue by jmeehan11** [Genymobile/scrcpy#502]
When I try to connect to my Firestick using ADB version 1.0.40 I get the following:

```
C:\scrcpy-win64>adb connect 192.168.0.2
* daemon not running; starting now at tcp:5037
* daemon started successfully
failed to authenticate to 192.168.0.2:5555
```

However, if I use version 1.0.39, I can connect without issue:

```
C:\platform-tools>adb connect 192.168.0.2
* daemon not running; starting now at tcp:5037
* daemon started successfully
connected to 192.168.0.2:5555
```

scrcpy will not let me launch without the valid version of ADB:

```
C:\scrcpy-win64>scrcpy
adb server version (39) doesn't match this client (40); killing...
```

This seem to be somewhat of a known issue:
https://github.com/happyleavesaoc/python-firetv/issues/49

**Comment by rom1v** [comment]
The "failed to authenticate" error is a problem between your device and adb 1.0.40.

To use adb 1.0.39, either set the environment variable `ADB=/path/to/your/adb_1.0.39/adb`, or just replace `adb.exe` in the _scrcpy_ folder by the version you need.
