### ISSUE TITLE
How Do I Uninstall and Install the Latest Version of scrcpy on Windows 11?

### ISSUE THREAD

**Issue by theremedysoul** [Genymobile/scrcpy#5029]
Hello, I am a beginner with computers. My brother installed scrcpy for me, but one day the screen-off-function suddenly stopped working. 

The current version of scrcpy is 1.21. 

I found out that I need to update to the latest version. However, I do not know how to uninstall and install scrcpy. 

When I search, only the Linux version comes up. 

I would appreciate it if you could tell me how to do this.

**Comment by theremedysoul** [comment]
If there is a way to upgrade without uninstalling, please let me know that as well. I would like to use the screen off function while using scrcpy.

**Comment by rom1v** [comment]
The package from your distribution is outdated. You must uninstall it:

```
sudo apt remove scrcpy
```

And you must install it using these steps: https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md#latest-version

**Comment by theremedysoul** [comment]
> The package from your distribution is outdated. You must uninstall it:
> 
> ```
> sudo apt remove scrcpy
> ```
> 
> And you must install it using these steps: https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md#latest-version

Thank you for your response. However, the link you provided is for Linux. I am a Windows user. Would it be okay if I still follow this method? Also, unfortunately, I am a complete beginner with computers. Should I use the sudo command in cmd?

**Comment by rom1v** [comment]
Oh, sorry, for Windows, just delete your old folder, download the latest release and extract it: https://github.com/Genymobile/scrcpy/blob/master/doc/windows.md

**Comment by theremedysoul** [comment]
> Oh, sorry, for Windows, just delete your old folder, download the latest release and extract it: https://github.com/Genymobile/scrcpy/blob/master/doc/windows.md

Thank you very much. However, I'm afraid that if I uninstall scrcpy incorrectly, I won't be able to reinstall it. You suggested "sudo apt remove scrcpy," but the link "https://github.com/Genymobile/scrcpy/issues/1312" provides a different method. Which one is correct? As I mentioned, my brother installed scrcpy for me, and I simply clicked on the bat file. I don't know much about adb or scrcpy. Could you explain step by step how to do it from the beginning, including opening the cmd window?

**Comment by rom1v** [comment]
On Windows, scrcpy is not "installed", it is just extracted to a directory. You can have several versions in different independent folders. There is nothing to "uninstall" (you can delete the directory if you want).

> Could you explain step by step how to do it from the beginning, including opening the cmd window?

1. Ignore the version you already have.
2. Download the latest version: https://github.com/Genymobile/scrcpy/blob/master/doc/windows.md
3. Extract it
4. Open the folder
5. Follow these instructions: https://github.com/Genymobile/scrcpy/blob/master/doc/windows.md#run

**Comment by theremedysoul** [comment]
> The package from your distribution is outdated. You must uninstall it:
> 
> ```
> sudo apt remove scrcpy
> ```
> 
> And you must install it using these steps: https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md#latest-version



> The package from your distribution is outdated. You must uninstall it:
> 
> ```
> sudo apt remove scrcpy
> ```
> 
> And you must install it using these steps: https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md#latest-version



> The package from your distribution is outdated. You must uninstall it:
> 
> ```
> sudo apt remove scrcpy
> ```
> 
> And you must install it using these steps: https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md#latest-version

Thank you for your kindness. All the problems have been solved perfectly.
