### ISSUE TITLE
Request: launch with specified size and position

### ISSUE THREAD

**Issue by jpage4500** [Genymobile/scrcpy#503]
Hi - first off thanks for this excellent android tool!

I typically want my device/mirror window open in the same location & size on my screen.

Would it be possible to specify the size and position in the command line when starting scrcpy?

I typically show 2 devices side-by-side as well and that would allow me to launch them that way.. not the hardest thing to do manually but it would save some time if I could launch them that way

thanks
joe

**Comment by abhishekabk5** [comment]
This feature requires that the command line arguments be passes to this line. 
https://github.com/Genymobile/scrcpy/blob/e443518ed902b678ad33886a2e626bfb70f8cd45/app/src/screen.c#L155

**Comment by Plandercozeron** [comment]
Yes, +1 for out of the box feature to mirror multiple devices by a single command
P.S: If you use linux there's useful workaround: window shuffler https://github.com/UbuntuBudgie/window-shuffler
I often use scrcpy to mirror 6 devices or more and tiling comes really handy

**Comment by rom1v** [comment]
Had been implemented since v1.11.
