### ISSUE TITLE
black screen using Molly Foss (fork of signal messenger) 

### ISSUE THREAD

**Issue by Nuudels** [Genymobile/scrcpy#5034]
using scrcpy 2.4 under MX Linux 23.3 xfce

everything is working perfect, except molly. 
just getting black screen on my desktop.

thank you

**Comment by rom1v** [comment]
In Signal settings (probably in Molly too), Privacy, disable "Screen security".

**Comment by Nuudels** [comment]
Omg, thank you.

I misinterpreted the German text in settings:

Bildschirmschutz
Bildschirmfotos in der Anwendung und der Liste der letzten Anwendungen blockieren
Screen protector
Block screenshots in the application and recent applications list

Nice weekend for you all ;-)
