### ISSUE TITLE
No anti aliasing for software renderer

### ISSUE THREAD

**Issue by JijaProGamer** [Genymobile/scrcpy#5048]
**Environment**
 - OS: Windows 11
 - scrcpy version: 2.5
 - installation method: Windows Release
 - device model: Motorola G72
 - Android version: 13

When using the software renderer (--render-driver=software) all anti aliasing is disabled, making low resolutions such as 300 be extremely jagged, looking very poor and not being ideal for a computer vision project.

From what I see online other renderer types do have anti aliasing, but they cannot be recorded by FFmpeg as I need.

From the documentation, there is no option to make anti aliasing work, so I believe this is a bug with the software renderer.

**Comment by rom1v** [comment]
The renderer driver is just forwarded to SDL. The SDL software renderer does not support antialiasing. Anyway, it would be costly (see https://github.com/Genymobile/scrcpy/issues/40#issuecomment-792144693).

**Comment by JijaProGamer** [comment]
> The renderer driver is just forwarded to SDL. The SDL software renderer does not support antialiasing. Anyway, it would be costly (see [#40 (comment)](https://github.com/Genymobile/scrcpy/issues/40#issuecomment-792144693)).

Which renderer types do have anti aliasing then?

**Comment by rom1v** [comment]
With OpenGL (>= 3), mipmaps are enabled by default: bea7658807d276aeab7d18d856a366c83ee05827.

I had opened a feature request to support mipmaps with other renderers: https://github.com/libsdl-org/SDL/issues/4156

**Comment by JijaProGamer** [comment]
> With OpenGL (>= 3), mipmaps are enabled by default: [bea7658](https://github.com/Genymobile/scrcpy/commit/bea7658807d276aeab7d18d856a366c83ee05827).
> 
> I had opened a feature request to support mipmaps with other renderers: [libsdl-org/SDL#4156](https://github.com/libsdl-org/SDL/issues/4156)

Thanks, you're a life saver
