### ISSUE TITLE
python3_scrcpy:  ERROR: Command not found: [adb], [start-server]

### ISSUE THREAD

**Issue by Mr-Weik** [Genymobile/scrcpy#5049]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md?rgh-link-date=2024-06-19T02%3A32%3A57Z).
- [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen).

## When I used the method described in the title to record a video script, an exception ERROR: Command not found: [adb], [start-server] occurred

> When it said adb not found, I checked my adb environment and the corresponding device was found and listed. I also manually executed the corresponding cmd command in the code in the terminal, and it was able to record the video and save the file.What should I do?

### Machine environment
+ macOS  14.4.1
+ Python 3.9.9 
+ Android Debug Bridge version 1.0.41
	Version 34.0.4-10411341
	Installed as /Users/xxx/workspace/pycharm_code/set_env/platform-tools/adb
	Running on Darwin 23.4.0 (x86_64)
+ scrcpy 2.5 <https://github.com/Genymobile/scrcpy>
	- Dependencies (compiled / linked):
	 - SDL: 2.30.4 / 2.30.4
	 - libavcodec: 61.3.100 / 61.3.100
	 - libavformat: 61.1.100 / 61.1.100
	 - libavutil: 59.8.100 / 59.8.100
	 - libusb: - / 1.0.27
+ scrcpy path  /usr/local/bin/scrcpy

### Error code and description
```
import subprocess
import time
num = 1  
cmd = ['/usr/local/bin/scrcpy --no-playback  --no-window --record=/Users/xxx/workspace/Pycharm/output/and/start_{}.mp4'.format(num)]
proc = subprocess.Popen(cmd)
time.sleep(3)
proc.terminate() 
proc.wait()
print("Finish！")
```

```
exec: No such file or directory
ERROR: Command not found: [adb], [start-server]
ERROR: (make 'adb' accessible from your PATH or define its fullpath in the ADB environment variable)
ERROR: Could not execute "adb start-server"
ERROR: Could not start adb server
ERROR: Server connection failed
scrcpy 2.5 <https://github.com/Genymobile/scrcpy>
INFO: You may install 'adb' by "apt install adb"

```

**Comment by rom1v** [comment]
Is `adb` in your `PATH`?

```bash
echo $PATH
```

> ```python
> time.sleep(3)
> proc.terminate() 
> proc.wait()
> ```

If you try to record a video for 3 seconds, FYI there is an option for that:

```bash
scrcpy --record=file.mp4 --time-limit=3
```

**Comment by Mr-Weik** [comment]
@rom1v Yes, my PATH environment is as follows:
You can see that platform is output at the end
> ➜  ~ echo $PATH
/usr/local/Cellar/pyenv-virtualenv/1.2.3/shims:/Users/xxxx/.pyenv/shims:/Library/Frameworks/Python.framework/Versions/3.9/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin/pip3.9:/Users/xxxx/workspace/pycharm_code/set_env/platform-tools
➜  ~

Thanks for reminding me about the recording time. This is just a demo. I already know the duration parameters. Thanks.

**Comment by rom1v** [comment]
> ```python
> cmd = ['/usr/local/bin/scrcpy --no-playback  --no-window --record=/Users/xxx/workspace/Pycharm/output/and/start_{}.mp4'.format(num)]
> proc = subprocess.Popen(cmd)
> ```

I don't even understand how you manage to start the process: the array should contain split arguments.

```python
cmd = ['/usr/local/bin/scrcpy', '--no-playback', '--no-window', '--record=/Users/xxx/workspace/Pycharm/output/and/start_{}.mp4'.format(num)]
```

I tested with this program on my machine (Linux):

```python
import subprocess
import time
cmd = ['/usr/local/bin/scrcpy', '-m1024']
proc = subprocess.Popen(cmd)
time.sleep(3)
proc.terminate()
proc.wait()
print("Finish!")
```

it works fine.

**Comment by rom1v** [comment]
What is the result of `echo $ADB`?

**Comment by Mr-Weik** [comment]
@rom1v  I tried to execute it by separating the parameters, but the result was still "Command not found: [adb]". Running "echo $ADB" in the terminal did not produce any output, which appears to be the issue here.

**Comment by rom1v** [comment]
Does this work:

```python
cmd = ['adb', devices']
proc = subprocess.Popen(cmd)
```

?

> Running "echo $ADB" in the terminal did not produce any output, which appears to be the issue here.

No, it is expected to be unset.

But as a workaround, you can set it to the absolute path of your adb:

```bash
export ADB=/Users/xxx/workspace/pycharm_code/set_env/platform-tools/adb
```

I don't know why it cannot find it if you just execute `adb`.

**Comment by Mr-Weik** [comment]
@rom1v It's strange, when I run this code, it also prompts me that adb is not found, but when I manually execute adb devices in iterm2, it can output normally, so I restarted the computer, and then the script can run normally. This phenomenon is really puzzling, but it has been solved. Thank you for your help
