### ISSUE TITLE
Make Phone Screen Follow Mouse Direction When Playing FPS Games Without Manually Clicking

### ISSUE THREAD

**Issue by Ekanyani** [Genymobile/scrcpy#5054]
- [✅] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
When I play games like fps games / minecraft I want the screen to follow my mouse direction without having to click and drag.

**Describe the solution you'd like**
 I want the screen to follow my mouse direction without having to click and drag.

**Describe alternatives you've considered**
No alternative other than manually clicking and dragging the pointer to be able to move the screen.

**Additional context**

**Comment by rom1v** [comment]
Did you try with [physical mouse simulation](https://github.com/Genymobile/scrcpy/blob/master/doc/mouse.md#physical-mouse-simulation)?

**Comment by Ekanyani** [comment]
![image](https://github.com/Genymobile/scrcpy/assets/109494951/e86b4a5b-0996-4a13-9b3b-a3512b2696df)
It gives me this error

**Comment by rom1v** [comment]
With the latest version.

**Comment by Ekanyani** [comment]
Oh it works now after updating to the newest version, thx!
