### ISSUE TITLE
Camera Orientation

### ISSUE THREAD

**Issue by TagaTulay** [Genymobile/scrcpy#5060]
scrcpy --video-source=camera --no-audio --camera-facing=back

Tried this. By default, it is on landscape. When I tried my device to be on portrait, the camera does not automatically move to portrait.

I request that the camera should automatically  change its orientation.

**Comment by rom1v** [comment]
Camera rotation does (and will) not change automatically when you rotate the screen. See discussion https://github.com/Genymobile/scrcpy/issues/241#issuecomment-1637189924

But you can pass a parameter to set the orientation: https://github.com/Genymobile/scrcpy/blob/master/doc/camera.md#rotation

**Comment by TagaTulay** [comment]
Thanks. It seems the best way is to use shortcuts - rotate display.

**Comment by rom1v** [comment]
> Thanks. It seems the best way is to use shortcuts - rotate display.

Yes, except if you want to record with the correct orientation, you need `--orientation=xx`.
