### ISSUE TITLE
Touchscreen not captured properly without --no-mouse-hover

### ISSUE THREAD

**Issue by ScionOfDesign** [Genymobile/scrcpy#5067]
## Environment

 - **OS:** Windows 11
 - **Scrcpy version:** 2.5
 - **Installation method:** Windows Release 64 bit
 - **Device model:** Orange Pi
 - **Android version:** 12

## Describe the bug

When running `scrcpy.exe` with no flags, it works fine with the mouse. However, attempting to use the touchscreen either does not work at all or only sometimes works for a little bit.
Adding the flag `--no-mouse-hover` causes touchscreen input to be captured again.

**Comment by rom1v** [comment]
Please run with `scrcpy -Vverbose` and post the whole output when it fails to inject touchscreen events.

**Comment by ScionOfDesign** [comment]
Here is he log:
[Scrcpy.log](https://github.com/user-attachments/files/16120741/Scrcpy.log)

I alternated between touch and mouse.

**Comment by rom1v** [comment]
Thank you.

Out of curiosity, does it work with `scrcpy --mouse-bind=++++`?

**Comment by ScionOfDesign** [comment]
> Thank you.
> 
> Out of curiosity, does it work with `scrcpy --mouse-bind=++++`?

Yes, it does seem to work with that flag.

**Comment by rom1v** [comment]
OK 👌 

I will probably rework the decision to inject mouse or finger. Refs https://github.com/Genymobile/scrcpy/issues/5055#issuecomment-2209278528

**Comment by rom1v** [comment]
Fixed by #5076. Please test and confirm that it works :wink:

**Comment by ScionOfDesign** [comment]
Yes, this seems to work. Thank you!
