### ISSUE TITLE
Android Devices Transfer Data to Android Devices

### ISSUE THREAD

**Issue by kevinStrange** [Genymobile/scrcpy#508]
Is it possible to transfer to another Android device via a local socket? Android Devices Transfer Data to Android Devices

**Comment by rom1v** [comment]
To transfer what?

If you mean an Android scrcpy client, see https://github.com/Genymobile/scrcpy/issues/100.

**Comment by kevinStrange** [comment]
How to transmit data

**Comment by kevinStrange** [comment]
scrcpy-server.jar How is it compiled?

**Comment by rom1v** [comment]
> How is it compiled?

See [BUILD](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md).
