### ISSUE TITLE
sincronização de fps

### ISSUE THREAD

**Issue by TaldonT** [Genymobile/scrcpy#5085]
jogo um jogo de celular chamado standoff2, nele meu celular suporta 144 fps, 
fiz um arquivo .bat para poder transmitir para esse fps, mas o scrcpy fica congelando a imagem como se estivesse transmitindo em camera lenta, principalmente quando pulo no jogo, como posso resolver isso?
[114.txt](https://github.com/user-attachments/files/16199586/114.txt)

**Comment by TaldonT** [comment]
https://youtu.be/NA-_2IWNWQ8 como pode ver, todas as vezes que morro e vou renascer ele parece estar em câmera lenta e o áudio não fica sincronizado com o vídeo (obs. o áudio continua normal, só a imagem que não)

**Comment by rom1v** [comment]
1. Please write in English
2. Remove `--max-fps`, it's an option which limits the fps
3. What is the full output in the console with `--print-fps`(without capturing with OBS)?
4. If you record (`scrcpy -m1920 --record=file.mp4`) and play the file, is it ok?

**Comment by TaldonT** [comment]
1- excuse me
2- I already tried this way and the feeling was worse, but I can try again
3- The output that -- print-fps gives is not constant, it varies according to my fps in game, generally it is between 130 and 145
4- I'll try and include it here for you to take a look, I'll get back to you soon
Tks

**Comment by TaldonT** [comment]
Using --record=recording.mp4, every time I open the game the recording corrupts
In --print-fps the highest FPS shown was 170
Now according to your request my .bat file looks like this:
[meu arquivo.txt](https://github.com/user-attachments/files/16228098/meu.arquivo.txt)
And even removing the fps limiter. every time I relive or skip the videol presents THE slow motion aspect, my device is the RMX3709

**Comment by TaldonT** [comment]
I managed to fix it by decreasing -b (scrcpy.exe -b7M -m1920 --video-codec=h265 --print-fps
for /f "tokens=2 delims= " %%a in ('tasklist ^| findstr /i "adb.exe"') do taskkill /F /PID %%a)
