### ISSUE TITLE
Problem with my honor pad 9

### ISSUE THREAD

**Issue by Gheppi** [Genymobile/scrcpy#5088]
I have an Honor Pad 9 and I can't stream it to my PC. I activated USB debugging and enabled photo/video file transfer. I installed the latest version of scrpcy and my tablet version and android 14 or magicOS 8.
Can anyone help me solve this problem?

**Comment by rom1v** [comment]
What is the full output in the scrcpy console?

**Comment by Gheppi** [comment]
Sorry i resolved the problem

Il sab 13 lug 2024, 19:52 Romain Vimont ***@***.***> ha
scritto:

**Comment by Gheppi** [comment]
thanks

Il sab 13 lug 2024, 19:53 matteo gasperini ***@***.***>
ha scritto:
