### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by 916881120** [Genymobile/scrcpy#5094]
Hello, where can I find the output of the red box in the app source code? I want to intercept the logs sent from the phone. Thank you.
![1721048922901(1)](https://github.com/user-attachments/assets/38a7dc2d-af2a-44d3-9403-31c257ec541e)

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/cc8e6133b0c9975ef2ed16086960e822ab750404/server/src/main/java/com/genymobile/scrcpy/Ln.java#L17

**Comment by 916881120** [comment]
> https://github.com/Genymobile/scrcpy/blob/cc8e6133b0c9975ef2ed16086960e822ab750404/server/src/main/java/com/genymobile/scrcpy/Ln.java#L17

Hello, I found this location but I want to intercept it on the client side. When the server sends data to the client, I want to find this output location in the client source code. Can you help me? Thank you.

**Comment by rom1v** [comment]
There is none, the server directly prints to stdout/stderr, the client is not aware of the server logs.

**Comment by 916881120** [comment]
> 没有，服务器直接打印到 stdout/stderr，客户端不知道服务器日志。

Okay, thank you. scrcpy is the best screen projection software I have ever used.
