### ISSUE TITLE
mirroring problem in android 13

### ISSUE THREAD

**Issue by Dex94** [Genymobile/scrcpy#5095]
if firefox is put in incognito mode the screen in the program window is all black but it's okay on the phone. I see the message 'Disable private browsing' when I hover the mouse arrow over the icon, but the rest is all black. I tried it in another phone with older android version and it's all ok. The test is made using the same firefox apk version
![immagine](https://github.com/user-attachments/assets/7e74ef4b-2c0b-4543-8426-84268d64d831)
![immagine](https://github.com/user-attachments/assets/6d3d28c3-e1a9-4e41-a199-caa289c24a16)

**Comment by rom1v** [comment]
In Firefox settings > Private browsing > enable "Allow screenshots in private browsing".

On Android < 12, the content is captured in any case. On Android 12+, it is captured only when the app allows it.
