### ISSUE TITLE
scrcpy-server 2.5 build_without_gradle.sh error: cannot find symbol IOnPrimaryClipChangedListener

### ISSUE THREAD

**Issue by qq876551724** [Genymobile/scrcpy#5096]
Using the latest buildw_ithout_gradle.sh on July 16, 2024, this error occurred during the build process
`Platform: android-34
Build-tools: 34.0.0
Build dir: /d/workspace/scrcpy/server/build_manual
Generating java from aidl...
Compiling java sources...
com/genymobile/scrcpy/Device.java:10: error: cannot find symbol
import android.content.IOnPrimaryClipChangedListener;
                                     ^
  symbol:   class IOnPrimaryClipChangedListener
  location: package android.content
...
`
buildw_ithout_gradle.sh
`echo "Generating java from aidl..."
cd "$SERVER_DIR/src/main/aidl"
"$BUILD_TOOLS_DIR/aidl" -o"$GEN_DIR" android/view/IRotationWatcher.aidl
"$BUILD_TOOLS_DIR/aidl" -o"$GEN_DIR" \
    android/content/IOnPrimaryClipChangedListener.aidl
"$BUILD_TOOLS_DIR/aidl" -o"$GEN_DIR" android/view/IDisplayFoldListener.aidl
`

**Comment by rom1v** [comment]
Did you install the build tools 34.0.0?

Is `$BUILD_TOOLS_DIR` the correct path in the script?

https://github.com/Genymobile/scrcpy/blob/cc8e6133b0c9975ef2ed16086960e822ab750404/server/build_without_gradle.sh#L17-L19

**Comment by qq876551724** [comment]
> Did you install the build tools 34.0.0?
> 
> Is `$BUILD_TOOLS_DIR` the correct path in the script?
> 
> https://github.com/Genymobile/scrcpy/blob/cc8e6133b0c9975ef2ed16086960e822ab750404/server/build_without_gradle.sh#L17-L19

When using gitbash to build under Windows, the "$LAMBDA_JAR:$GEN_DIR" path cannot be adapted. It can be solved by using absolute path strength.

**Comment by qq876551724** [comment]
Thanks
