### ISSUE TITLE
I got SPS profile_idc 100, can I set profile_idc 66 (baseline)?

### ISSUE THREAD

**Issue by likezjuisee** [Genymobile/scrcpy#510]
[DRGGAM0850405292.zip](https://github.com/Genymobile/scrcpy/files/3116476/DRGGAM0850405292.zip)
This is H.264 raw data, but [Broadway ](https://github.com/mbebenita/Broadway)can not parse profile_idc 100 data. Broadway supports profile_idc 66 (baseline). So how can I set the screen data to baseline?

**Comment by likezjuisee** [comment]
Or can I encode the screen data with another video format, that will be played in the browser?

**Comment by rom1v** [comment]
Is it sufficient:

```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java b/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java
index c946e99..0265f51 100644
--- a/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java
+++ b/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java
@@ -143,6 +143,7 @@ public class ScreenEncoder implements Device.RotationListener {
         format.setInteger(MediaFormat.KEY_FRAME_RATE, frameRate);
         format.setInteger(MediaFormat.KEY_COLOR_FORMAT, MediaCodecInfo.CodecCapabilities.COLOR_FormatSurface);
         format.setInteger(MediaFormat.KEY_I_FRAME_INTERVAL, iFrameInterval);
+        format.setInteger(MediaFormat.KEY_PROFILE, MediaCodecInfo.CodecProfileLevel.AVCProfileBaseline);
         // display the very first frame, and recover from bad quality when no new frames
         format.setLong(MediaFormat.KEY_REPEAT_PREVIOUS_FRAME_AFTER, MICROSECONDS_IN_ONE_SECOND * REPEAT_FRAME_DELAY / frameRate); // µs
         return format;
```
?

**Comment by likezjuisee** [comment]
We have resolved this problem, besides KEY_FROFILE, KEY_LEVEL is also needed to set.
Thanks all the same.

**Comment by rom1v** [comment]
OK, thank you for your feedback. :+1:

The need seems too specific for adding a command-line option to select the profile/level, and you solved the problem on your side, so I'm closing.

**Comment by alligatorme** [comment]
@likezjuisee  #1226, it seems to be the final solution.
