### ISSUE TITLE
scrcpy not working

### ISSUE THREAD

**Issue by TheAsteroid894** [Genymobile/scrcpy#5105]
SCRCPY is just opening for a second and just closes and does not mirror the screen of my android device I waited for couple of minutes still dosent work the usb debbugging is also enabaled

**Comment by rom1v** [comment]
> SCRCPY is just opening for a second and just closes

What is the full output in the console?

Read https://github.com/Genymobile/scrcpy/blob/master/doc/windows.md#run to keep the console open on error.

**Comment by RegulusCentauri** [comment]
@rom1v 
I'm facing the same issue. Running unedited _scrcpy-console.bat_ and the window just pops up and closes down immediately. Downloaded the repo today. I still have your waaay older version (1.0 or something like that) of scrcpy and that one works fine.
I couldn't even find the scrcpy.exe file in the current folder structure at all - is there a chance it's missing from this build?

**Comment by rom1v** [comment]
> Downloaded the repo today.
>
> I couldn't even find the scrcpy.exe file in the current folder structure at all - is there a chance it's missing from this build?

You must not download the repo, but the release: https://github.com/Genymobile/scrcpy/blob/master/doc/windows.md

**Comment by RegulusCentauri** [comment]
> > Downloaded the repo today.
> > I couldn't even find the scrcpy.exe file in the current folder structure at all - is there a chance it's missing from this build?
> 
> You must not download the repo, but the release: https://github.com/Genymobile/scrcpy/blob/master/doc/windows.md

Right, makes sense actually, my bad -> worked, thanks! o7
