### ISSUE TITLE
Max & ideal bit-rate

### ISSUE THREAD

**Issue by duplex143** [Genymobile/scrcpy#511]
I'd like to know the ideal and max bit-rate. 8Mbps seems slow to me. I changed bit-rate to 100Mbps and couldn't notice any change. It's similar to 8Mbps one.

**Comment by rom1v** [comment]
The parameter is just forwarded to `MediaCodec`:

https://github.com/Genymobile/scrcpy/blob/ffa8c66979d4262a95cad584894b9a5fbeea0e84/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java#L142

How it is handled depends on your hardware encoder. Typically, above 10~15Mbps it changes nothing.

**Comment by duplex143** [comment]
Thanks for the reply. I've used Vysor and other apps in the past only to be vexed by their functionalities. `scrcpy` is sleek.

**Comment by vbuterin2** [comment]
why I cannot set it to 100 or 200M when I connect it via usb3.1?

**Comment by rom1v** [comment]
You can, but the codec decides what to do with the requested bitrate.
