### ISSUE TITLE
GH Discussions

### ISSUE THREAD

**Issue by Rudxain** [Genymobile/scrcpy#5117]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
The only contact channels are Reddit and Twitter, which require register/sign-up on their corresponding platforms.

- Twitter seems pretty unstable, "thanks" to Elon; and may require payments in the future
- Reddit [is simply bad, "thanks" to its CEO](https://en.wikipedia.org/wiki/2023_Reddit_API_controversy)

There are many other reasons why users may not like (or even outright hate) to be forced to use any of those platforms

**Describe the solution you'd like**
Enable GitHub Discussions. It's built into this platform. Most users of scrcpy will very likely have a GH account and would love to use it!

**Describe alternatives you've considered**
Adding more platforms, such as Matrix or Discord

**Additional context**

**Comment by rom1v** [comment]
> The only contact channels are Reddit and Twitter,

No, these are secondary channels. The main channel is via GitHub issues.

> Enable GitHub Discussions.

What's the benefit over GitHub issues? Very often, it is not clear whether something is an "issue" or a "discussion". What about discussions about an issue?

**Comment by Rudxain** [comment]
> No, these are secondary channels. The main channel is via GitHub issues.

Are you sure?

https://github.com/Genymobile/scrcpy/blob/cc8e6133b0c9975ef2ed16086960e822ab750404/README.md?plain=1#L149-L158

It seems Issues are mainly for bug-reports and feature-requests, not questions or discussions

> What's the benefit over GitHub issues?

Questions, such as #5118

> Very often, it is not clear whether something is an "issue" or a "discussion"

I can relate 😅. It's hard to decide

**Comment by rom1v** [comment]
While I think GitHub discussions might be more appropriate than "issues" for many questions (many users just seek help to make scrcpy work on their device), I fear that it will create confusion/duplication. Moreover, in theory, a lot of existing issues should be moved to discussions, but I will not review the 5000+ issues to clean up.

So for now, I think I will only keep issues, but add an explicit (empty) "Question" template:

```diff
diff --git a/.github/ISSUE_TEMPLATE/question.md b/.github/ISSUE_TEMPLATE/question.md
new file mode 100644
index 000000000..14dc373a3
--- /dev/null
+++ b/.github/ISSUE_TEMPLATE/question.md
@@ -0,0 +1,8 @@
+---
+name: Question
+about: Ask a question about scrcpy
+title: ''
+labels: ''
+assignees: ''
+
+---

and reword the `Contact` section:

```diff
diff --git a/README.md b/README.md
index 3185652b9..36c8c272b 100644
--- a/README.md
+++ b/README.md
@@ -148,11 +148,14 @@ documented in the following pages:
 
 ## Contact
 
-If you encounter a bug, please read the [FAQ](FAQ.md) first, then open an [issue].
+You can open an [issue] for bug reports, feature requests or general questions.
+
+For bug reports, please read the [FAQ](FAQ.md) first, you might find a solution
+to your problem immediately.
 
 [issue]: https://github.com/Genymobile/scrcpy/issues
 
-For general questions or discussions, you can also use:
+You can also use:
 
  - Reddit: [`r/scrcpy`](https://www.reddit.com/r/scrcpy)
  - Twitter: [`@scrcpy_app`](https://twitter.com/scrcpy_app)
```

What do you think?

**Comment by Rudxain** [comment]
> I will not review the 5000+ issues

I agree, that's too much work 😅

> "Question" template

That's a good solution! Now, I'm unsure if I should close this as "completed" or "not planned". According to the title, it should be "not planned", but the intention was "completed" in another way
