### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by ssccc** [Genymobile/scrcpy#513]
I'm using Huawei mate 10 pro with android 9.1.
it's showing a black screen, I can only see the navigation bar

**Comment by rom1v** [comment]
While a specific application is foreground, or for any?

**Comment by ssccc** [comment]
any

**Comment by rom1v** [comment]
Could you try to record your screen with `screenrecord`:

    adb shell screenrecord /sdcard/file.mp4
    adb pull /sdcard/file.mp4

Is the screen black on the video?

**Comment by duplex143** [comment]
@rom1v Btw, there's no workaround for playing DRM content I suppose. Like Netflix?

**Comment by ssccc** [comment]
How I am supposed to find the video nothing is happening

![image](https://user-images.githubusercontent.com/32818143/56771797-5a6d3900-67c0-11e9-847c-fa3dab550a06.png)

**Comment by ssccc** [comment]
The issue seems to be from my phone because I noticed that sometimes when I screenrecord from phone it's also black unless I restart my phone. Thank you

**Comment by rom1v** [comment]
> How am I supposed to find the video? nothing is happening

You need to pass these parameters as command-line arguments, not write them in the console of scrcpy.

See #385.
