### ISSUE TITLE
about mutliple devices for tcpip

### ISSUE THREAD

**Issue by GoGoogle** [Genymobile/scrcpy#514]
I'm use tcpip connect the mutliple devices,adb devices list is no serials.

```
adb devices
List of devices attached
192.168.1.3:5555      device
192.168.1.2:5556      device
```

so,how can use the scrcpy -s serials?

**Comment by rom1v** [comment]
scrcpy -s 192.168.1.3:5555

**Comment by GoGoogle** [comment]
> ```
> scrcpy -s 192.168.1.3:5555
> ```

Thx
