### ISSUE TITLE
scrcpy is dont working

### ISSUE THREAD

**Issue by walk1nn** [Genymobile/scrcpy#5146]
Hello, who can help me, i have a problem. When i am starting scrcpy is just opens and closes immediately.
But if im start scrcpy-console.bat i receive this error:
![image](https://github.com/user-attachments/assets/3c45b20d-9d51-4893-a4a8-6d84eba05f33)
I testet many versions of scrcpy, and not one worked

**Comment by rom1v** [comment]
Because you set an ADB environment variable. You don't need to do that (and it fails because you set it to a wrong value), so unset it, it will use the adb.exe from the scrcpy release.

**Comment by walk1nn** [comment]
> Because you set an ADB environment variable. You don't need to do that (and it fails because you set it to a wrong value), so unset it, it will use the adb.exe from the scrcpy release.
it work, thank you
