### ISSUE TITLE
scrcpy 2.5 isn't working with my Huawei Pura 70 Pro

### ISSUE THREAD

**Issue by KlyDaily** [Genymobile/scrcpy#5149]
scrcpy 2.5 isn't working on my Huawei Pura 70 Pro even when I have enabled USB Debugging. However, when I try it on my Samsung Galaxy Tab A8 (2021), scrcpy 2.5 works very well. What seems to be the issue here? Thank you in advance!

**Comment by rom1v** [comment]
What's the full output in the console?

https://github.com/Genymobile/scrcpy/blob/master/doc/windows.md#run

**Comment by KlyDaily** [comment]
`scrcpy 2.5 <https://github.com/Genymobile/scrcpy>
ERROR: Could not find any ADB device
ERROR: Server connection failed
Press Enter to continue...`

What should I do with this ?

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#device-not-detected
