### ISSUE TITLE
Audio not forwarded on Linux

### ISSUE THREAD

**Issue by sequencerr** [Genymobile/scrcpy#5150]
For some reason audio forwarding to PC works Windows but not on Debian 12

**Comment by rom1v** [comment]
Which scrcpy version do you use on Debian?

https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md#latest-version

**Comment by sequencerr** [comment]
> Which scrcpy version do you use on Debian?
> 
> https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md#latest-version

well which was latest on snap. sorry can't look now

**Comment by sequencerr** [comment]
Ohh, my bad. 

following this didn't help
https://snapcraft.io/install/scrcpy-updated/debian
`sudo snap install scrcpy-updated --edge`

I probably would need to manually install. Thanks for help!
