### ISSUE TITLE
ERROR: “adb reverse” returned with value 1

### ISSUE THREAD

**Issue by Djrfatjf** [Genymobile/scrcpy#5151]
Hello, I’m here because I need your help with this error,

phone: LG Optimus 4X HD P880

Android Version: 4.0.3 (Ice cream sandwich)

INFO: —> (usb) 015d25785e0c120c                          device
adb.exe: error closed
ERROR: “adb reverse” returned with value 1
WARN: ‘adb reverse” failed, fallback to adb ‘forward’
Segmentation fault
ERROR: connect: [10038] An operation was attempted on something that is not a socket.
ERROR: Server connection failed
Press Enter to continue…

**Comment by Djrfatjf** [comment]
and here is my logcat for more help.
[logcat.txt](https://github.com/user-attachments/files/16414594/logcat.txt)

**Comment by rom1v** [comment]
Scrcpy requires at least Android 5.

**Comment by Djrfatjf** [comment]
Fuck…
