### ISSUE TITLE
How to lock your phone?

### ISSUE THREAD

**Issue by TheMaster870** [Genymobile/scrcpy#516]
Is there a simple way to lock the phone, the equivalent of pressing the physical lock button on the side of the phone?

**Comment by rom1v** [comment]
Ctrl+p

**Comment by Gasic18** [comment]
> Ctrl+p

**doesn't work.**

**Comment by rom1v** [comment]
@Gasic18 Now the default modifier is Alt, so it's Alt+p.

See https://github.com/Genymobile/scrcpy/blob/master/doc/shortcuts.md
