### ISSUE TITLE
2.6版本某些app不能点击

### ISSUE THREAD

**Issue by aoy2024** [Genymobile/scrcpy#5163]
2.5里面正常点击
![微信截图_20240802211013](https://github.com/user-attachments/assets/d6e70166-4afb-4d5f-8452-56bc8d2f5a55)

[server] INFO: Device: [nubia] nubia NX712J (Android 14)
INFO: Renderer: direct3d
INFO: Texture: 864x1920

**Comment by aoy2024** [comment]
![Uploading 1.png…]()

**Comment by aoy2024** [comment]
[]
![Uploading 2.png…]()

**Comment by aoy2024** [comment]
![1](https://github.com/user-attachments/assets/10f0857a-8ab1-459d-af14-b0bf958fd072)
![2](https://github.com/user-attachments/assets/bd35f45e-a0e9-4335-b8cb-55e62187f651)

**Comment by aoy2024** [comment]
![Uploading 3.png…]()

**Comment by aoy2024** [comment]
![3](https://github.com/user-attachments/assets/1a1756eb-2dd5-4bb1-ac3b-189fc1ad925d)
![1](https://github.com/user-attachments/assets/dcd1d906-428c-477c-8d65-0878f50831d2)
![2](https://github.com/user-attachments/assets/c3f0d20e-cdf2-4938-9c10-5ee8f4b3315e)

**Comment by rom1v** [comment]
Thank you for your report (but please write in English).

Which is the easiest way to reproduce the problem? (some app on the PlayStore which does not require an account?)

Also follow #5162 (might be related, but might not).

**Comment by aoy2024** [comment]
> Thank you for your report (but please write in English).
> 
> Which is the easiest way to reproduce the problem? (some app on the PlayStore which does not require an account?)
> 
> Also follow #5162 (might be related, but might not).

It's not on Google Play, I uploaded it to OneDrive. Could you please test it
https://1drv.ms/u/c/6a0581d6d6152844/EaczUyOHJYBEvH7VXPE1BMUBdWS44jhleZbn0pS8lF3cnQ

**Comment by rom1v** [comment]
Please test https://github.com/Genymobile/scrcpy/issues/5162#issuecomment-2265937910.

**Comment by aoy2024** [comment]
> Please test [#5162 (comment)](https://github.com/Genymobile/scrcpy/issues/5162#issuecomment-2265937910).

Sorry, I don't understand code. I can't read it

**Comment by rom1v** [comment]
There is no code to understand, download the linked `scrcpy-server` and replace it in your scrcpy 2.6 folder.

**Comment by aoy2024** [comment]
> There is no code to understand, download the linked `scrcpy-server` and replace it in your scrcpy 2.6 folder.

After replacing the file, I can click normally and the problem has been solved. Thank you very much

**Comment by rom1v** [comment]
Fixed in scrcpy 2.6.1.
