### ISSUE TITLE
Inspecting the "local" `.pc` files it seemed the culprit was found.

### ISSUE THREAD

**Issue by moi666fuk** [Genymobile/scrcpy#5166]
Inspecting the "local" `.pc` files it seemed the culprit was found.
Their versions fit 'scrcpy -v' output.

For example, in /usr/local/lib/pkgconfig/libavformat.pc it says:
`Version: 58.68.100`

I also checked:
```
$ pkg-config --print-provides  libavformat
libavformat = 60.16.100
$ pkg-config --path  libavformat
/usr/lib/pkgconfig/libavformat.pc
```

But even after deleting those files, deleting the local repository, recloning and building afresh the same version numbers show up with './run d -v'

_Originally posted by @elig0n in https://github.com/Genymobile/scrcpy/issues/4976#issuecomment-2248875256_

**Comment by rom1v** [comment]
No need to create a new issue to duplicate a comment in another discussion.
