### ISSUE TITLE
FPS doesn't surpass 60 on a 120 capable device when device screen is turned off (-S is passed)

### ISSUE THREAD

**Issue by bloopiy** [Genymobile/scrcpy#5168]
_Please read the [prerequisites] to run scrcpy._

[prerequisites]: https://github.com/Genymobile/scrcpy#prerequisites

_Also read the [FAQ] and check if your [issue][issues] already exists._

[FAQ]: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md
[issues]: https://github.com/Genymobile/scrcpy/issues

## Environment

 - **OS:** - Windows
 - **Scrcpy version:** - 2.6.1
 - **Installation method:** - Windows release
 - **Device model:** - Samsung S24 Ultra
 - **Android version:** - 14

## Describe the bug

So when I pass the -S argument, the screen of my device (S24u) turns off as expected, but the output limits to max 60 fps (which can be seen by --print-fps), but when screen is turned back on (Ctrl + Shift + S) max framerate rises to 120, seen in the console. How do I get 120 fps max when my device screen is turned off?

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
See #3376.
