### ISSUE TITLE
WiFi 端口号 总是变化    WiFi port number always changes

### ISSUE THREAD

**Issue by Discover623** [Genymobile/scrcpy#5176]
![Snipaste_2024-08-07_11-32-40](https://github.com/user-attachments/assets/8b76f95f-6f7f-4866-b8eb-75b06f9bea35)
无线连接 端口号总是变化  有没有啥方法固定住或者说能不手动输入变化的端口号就能无线连接的，类似shizuku
的方法，他就不用输入端口号。
 大佬能解答下嘛
 
The wireless connection port number is always changing. Is there any way to fix it or to connect wirelessly without manually entering the changing port number? Similar to shizuku
’s method, he doesn’t need to enter the port number.
Can someone answer this question?

**Comment by rom1v** [comment]
Either you use the [wireless pairing](https://developer.android.com/tools/adb?hl=fr#wireless-android11-command-line) introduced in Android 11 (what you do), but then the port changes every time.

Or you connect once over USB to enable [adb over TCP/IP](https://github.com/Genymobile/scrcpy/blob/master/doc/connection.md#tcpip-wireless). It must be done after each phone reboot.
