### ISSUE TITLE
adb command not found

### ISSUE THREAD

**Issue by NecroSyri** [Genymobile/scrcpy#518]
Hi, I'm having a hard time running scrcpy,
it only worked once, I closed it and wanted to start it again, but I always end up with this error :
```
* daemon not running; starting now at tcp:5037
* daemon started successfully
scrcpy-server.jar: 1 file pushed. 0.5 MB/s (19734 bytes in 0.040s)
ERROR: 'adb' command not found (make it accessible from your PATH or define its full path in the ADB environment variable)
ERROR: Could not execute "adb reverse"
WARN: 'adb reverse' failed, fallback to 'adb forward'
ERROR: 'adb' command not found (make it accessible from your PATH or define its full path in the ADB environment variable)
ERROR: Could not execute "adb forward"
Press any key to continue...
```

Or the same error without the 2 first lines about daemon if I don't manually kill the adb.exe process.
My adb is in the folder, I also declared it in my user PATH (still targeting the one from the folder), and I've copied the content from platfrom-tool to scrcpy folder, all of this with always the same result but once, when I just booted the computer this morning and it worked.

I'm using a Pocophone and Windows 10

**Comment by rom1v** [comment]
What happens if you just execute:

    adb devices

?

**Comment by NecroSyri** [comment]
That's the weird thing, it works : 
```
PS G:\Downloads_shared\scrcpy-win64> adb devices
List of devices attached
8b3b909f        device
```
But when launching scrcpy.exe it doesn't

**Comment by rom1v** [comment]
What is the content of your `PATH`?

> I've copied the content from platfrom-tool to scrcpy folder

Please don't do that :scream:

What is the result of:

    adb --version
    .\adb --version

Also see #278.

You could also force a specific full path by setting the environment variable `ADB`, but this would only be a workaround.

**Comment by NecroSyri** [comment]
I copied platform-tool because some guide I found recommended to, probably outdated.

```
PS G:\Downloads_shared\scrcpy-win64> adb --version
Android Debug Bridge version 1.0.40
Version 28.0.2-5303910
Installed as G:\Downloads_shared\scrcpy-win64\adb.exe
PS G:\Downloads_shared\scrcpy-win64> .\adb --version
Android Debug Bridge version 1.0.40
Version 28.0.2-5303910
Installed as G:\Downloads_shared\scrcpy-win64\adb.exe
```

And in my user path I have this : G:\Downloads_shared\scrcpy-win64\ 
(among a few other things I can't share, I'm at work, also, not admin on this computer so I can't set variables for the system)

**Comment by rom1v** [comment]
> not admin on this computer so I can't set variables for the system

Oh, might be a confusion between system PATH and user PATH?

You can set `ADB` with:

    set ADB=G:\Downloads_shared\scrcpy-win64\adb.exe

Then:

    scrcpy

**Comment by NecroSyri** [comment]
Sorry I was a bit busy this morning, I tried it but it didn't worked, same result, and there's no other adb anywhere in the system Path so I doubt it's confision (and it seems to find the version and everything, I don't know why but the problem with adb only occurs for scrcpy, if I try adb commands, it works)

**Comment by rom1v** [comment]
> I retried just after doing the "adb devices", and had weird result, it worked, but still had some errors

This is very weird. It seems that sometimes it works, sometimes not.

**Comment by rom1v** [comment]
I recently added a commit to print the command when it fails, it could help:
https://github.com/Genymobile/scrcpy/commit/e443518ed902b678ad33886a2e626bfb70f8cd45

**Comment by NecroSyri** [comment]
Hi, unfortunately, my mission at this place is over so I don't have access to this computer anymore.
And I haven't been able to reproduce the problem at the new place, now it works fine for the scrcpy part,
I just can't connect wirelessly at work, but only on adb side, before launching scrcpy, and I think that's because of proxy or port restriction.
