### ISSUE TITLE
Device could not be connected (state=offline)

### ISSUE THREAD

**Issue by Omexy** [Genymobile/scrcpy#5188]
## Environment

 - **OS:** Windows 11 Pro 23H2 22631.3880
 - **Scrcpy version:** 2.6.1
 - **Installation method:** Windows release
 - **Device model:** Samsung S20 Ultra 5G
 - **Android version:** 13

## The issue itself

I have been trying to get scrcpy working with my S20 Ultra 5G and haven't gotten far at all. When I type ```scrcpy```, I get the response:

```
scrcpy 2.6.1 <https://github.com/Genymobile/scrcpy>
ERROR: Device could not be connected (state=offline)
ERROR: Server connection failed
```
After this, I tried ```adb devices -l``` and got the response:
```
List of devices attached
1234... (serial number)            offline transport_id:83
```
As a last attempt, I tried ```scrcpy --otg``` to check for driver issues and got this response:
```
scrcpy 2.6.1 <https://github.com/Genymobile/scrcpy>
INFO: Killing adb server (if any)...
ERROR: Multiple (4) USB devices:
ERROR:     --> other USB device (xxxx:xxxx)  other USB device
ERROR:     --> other USB device             (xxxx:xxxx)  other USB device
ERROR:     --> INTENDED DEVICE        (xxxx:xxxx)  SAMSUNG SAMSUNG_Android
ERROR:     --> other USB device       (xxxx:xxxx)  other USB device
ERROR: Select a device via -s (--serial)
```
I selected the device via -s as it stated, and got the same response as I did with ```scrcpy```.

Does anyone have any ideas how I can sort this? I re-installed OEM drivers, disabled and re-enabled USB debugging etc and I'm lost now. Thank you all in advance!

**Comment by rom1v** [comment]
https://stackoverflow.com/questions/30964854/android-studio-device-is-connected-but-offline

**Comment by Omexy** [comment]
Thank you for the swift response! After a few hours of troubleshooting, I found that it was the **USB cable** that was my issue. I changed it from my previous cable and all of a sudden, the device became unauthorised and then I authorised it and then it was labelled as a device.

**Comment by Omexy** [comment]
Issue solved by replacing previous USB cable with another.
