### ISSUE TITLE
IllegatStateException

### ISSUE THREAD

**Issue by chandru-m** [Genymobile/scrcpy#519]
![image](https://user-images.githubusercontent.com/14244096/57170612-da982d80-6dc2-11e9-897d-b8df9f873ff9.png)

**Comment by chandru-m** [comment]
"adb shell screenrecord /sdcard/video.mp4" works. Vysor works. However on running scrcpy , I see the device crashing as well. Tried the jar file suggested in the comments above.

**Comment by rom1v** [comment]
And with a lower definition?

    scrcpy -m1024

**Comment by rom1v** [comment]
#465
