### ISSUE TITLE
h264high  0xffffffc3 错误

### ISSUE THREAD

**Issue by wode2016501** [Genymobile/scrcpy#5194]
H264  HIGH 

SurfaceEncoder.java:223 
+++++++
	 if (videoMimeType.equals(MediaFormat.MIMETYPE_VIDEO_AVC)) {
	    Ln.d("-----------格式"+videoMimeType+"-------\n");
	    format.setInteger(MediaFormat.KEY_I_FRAME_INTERVAL, 1);
            format.setInteger(MediaFormat.KEY_PROFILE,MediaCodecInfo.CodecProfileLevel.AVCProfileHigh444);
            format.setInteger(MediaFormat.KEY_LEVEL, MediaCodecInfo.CodecProfileLevel.AVCLevel62);
	    Ln.d("-----------设置格式"+videoMimeType+"成功-------\n");
        }
++++++++

usr/local/bin/scrcpy
scrcpy 2.5 <https://github.com/Genymobile/scrcpy>
ERROR: wode_SDL_Init(SDL_INIT_VIDEO)
INFO: ADB device found:
INFO:     -->   (usb)  bc4b952a                        device  IN2020
DEBUG: Device serial: bc4b952a
DEBUG: Using server: /usr/local/share/scrcpy/scrcpy-server
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 6.7 MB/s (69856 bytes in 0.010s)
[server] INFO: Device: [OnePlus] OnePlus IN2020 (Android 13)
DEBUG: Server connected
DEBUG: Starting controller thread
DEBUG: Starting receiver thread
DEBUG: Using icon: /usr/local/share/icons/hicolor/256x256/apps/scrcpy.png
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 23.0.4-0ubuntu1~22.04.1
INFO: Trilinear filtering enabled
DEBUG: Demuxer 'video': starting thread
DEBUG: Demuxer 'audio': starting thread
[server] DEBUG: Using audio encoder: 'c2.android.opus.encoder'
[server] DEBUG: Using video encoder: 'OMX.qcom.video.encoder.avc'
[server] DEBUG: -----------比特率8000000-------

[server] DEBUG: -----------格式video/avc-------

[server] DEBUG: -----------设置格式video/avc成功-------

INFO: Texture: 1080x2376
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0xffffffc3
[server] INFO: Retrying with -m1920...
[server] INFO: Retrying...
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0xffffffc3
[server] INFO: Retrying with -m1600...
[server] INFO: Retrying...
[server] INFO: Retrying with -m1280...
[server] INFO: Retrying...
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0xffffffc3
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0xffffffc3
[server] INFO: Retrying with -m1024...
[server] INFO: Retrying...
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0xffffffc3
[server] INFO: Retrying with -m800...
[server] INFO: Retrying...
ERROR: SDL_PauseAudioDevice
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0xffffffc3
[server] DEBUG: Screen streaming stopped
DEBUG: Demuxer 'video': end of frames
DEBUG: Receiver stopped
DEBUG: Demuxer 'audio': end of frames
ERROR: Controller error
DEBUG: quit...
[server] DEBUG: Device message sender stopped
[server] DEBUG: Controller stopped
[server] ERROR: Exception on thread Thread[video,5,main]
android.media.MediaCodec$CodecException: Error 0xffffffc3
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:2214)
	at android.media.MediaCodec.configure(MediaCodec.java:2130)
	at com.genymobile.scrcpy.SurfaceEncoder.streamCapture(SurfaceEncoder.java:70)
	at com.genymobile.scrcpy.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-SurfaceEncoder(SurfaceEncoder.java:268)
	at com.genymobile.scrcpy.SurfaceEncoder$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)
[server] DEBUG: Audio encoder stopped
DEBUG: Server disconnected
DEBUG: Server terminated

**Comment by rom1v** [comment]
Your device encoder does not support this profile+level.

**Comment by wode2016501** [comment]
但是我在 https://github.com/myrao/ScreenRecorder 这个项目上似乎没有错误
他是 AVCProfileHigh-AVCLevel6

**Comment by wode2016501** [comment]
> 您的设备编码器不支持此配置文件+级别。
但是我在 [https://github.com/myrao/ScreenRecorder ](https://github.com/myrao/ScreenRecorder)这个项目上似乎没有错误
他是 AVCProfileHigh-AVCLevel6

**Comment by rom1v** [comment]
Scrcpy just calls MediaCodec, and the errors are reported by MediaCodec.

Btw, with the changes you posted:

```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/video/SurfaceEncoder.java b/server/src/main/java/com/genymobile/scrcpy/video/SurfaceEncoder.java
index 8fe0b2277..b21882228 100644
--- a/server/src/main/java/com/genymobile/scrcpy/video/SurfaceEncoder.java
+++ b/server/src/main/java/com/genymobile/scrcpy/video/SurfaceEncoder.java
@@ -235,7 +235,9 @@ public class SurfaceEncoder implements AsyncProcessor {
         if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
             format.setInteger(MediaFormat.KEY_COLOR_RANGE, MediaFormat.COLOR_RANGE_LIMITED);
         }
-        format.setInteger(MediaFormat.KEY_I_FRAME_INTERVAL, DEFAULT_I_FRAME_INTERVAL);
+        format.setInteger(MediaFormat.KEY_I_FRAME_INTERVAL, 1);
+        format.setInteger(MediaFormat.KEY_PROFILE, MediaCodecInfo.CodecProfileLevel.AVCProfileHigh444);
+        format.setInteger(MediaFormat.KEY_LEVEL, MediaCodecInfo.CodecProfileLevel.AVCLevel62);
         // display the very first frame, and recover from bad quality when no new frames
         format.setLong(MediaFormat.KEY_REPEAT_PREVIOUS_FRAME_AFTER, REPEAT_FRAME_DELAY_US); // µs
         if (maxFps > 0) {
```

It works fine on a Pixel 8 (the encoder supports it).

However, it does not work on an old Nexus 5 (the encoder does not support it):

```
[server] DEBUG: Using video encoder: 'OMX.qcom.video.encoder.avc'
INFO: Texture: 1920x1080
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0x80001001
[server] INFO: Retrying with -m1600...
[server] INFO: Retrying...
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0x80001001
[server] INFO: Retrying with -m1280...
[server] INFO: Retrying...
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0x80001001
[server] INFO: Retrying with -m1024...
[server] INFO: Retrying...
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0x80001001
[server] INFO: Retrying with -m800...
[server] INFO: Retrying...
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0x80001001
[server] DEBUG: Screen streaming stopped
DEBUG: Demuxer 'video': end of frames
DEBUG: Receiver stopped
[server] DEBUG: Device message sender stopped
[server] DEBUG: Controller stopped
WARN: Device disconnected
DEBUG: quit...
DEBUG: Controller stopped
[server] ERROR: Exception on thread Thread[video,5,main]
android.media.MediaCodec$CodecException: Error 0x80001001
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:1778)
	at com.genymobile.scrcpy.video.SurfaceEncoder.streamCapture(SurfaceEncoder.java:81)
	at com.genymobile.scrcpy.video.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-video-SurfaceEncoder(SurfaceEncoder.java:270)
	at com.genymobile.scrcpy.video.SurfaceEncoder$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:818)
DEBUG: Server disconnected
DEBUG: Server terminated
```

**Comment by rom1v** [comment]
Note that you don't need to recompile scrcpy to change these settings, there's an option to pass parameters to MediaFormat.

The profile you used is [AVCProfileHigh444](https://developer.android.com/reference/android/media/MediaCodecInfo.CodecProfileLevel#AVCProfileHigh444), which has value `64`, and the level is [AVCLevel62](https://developer.android.com/reference/android/media/MediaCodecInfo.CodecProfileLevel#AVCLevel62), which has value `524288`:

```
scrcpy --video-codec-options=profile=64,level=524288
```
