### ISSUE TITLE
some applications have black screen

### ISSUE THREAD

**Issue by amosbird** [Genymobile/scrcpy#520]
I've been using scrcpy quite frequently for a long time. There is one thing that bugs my once in a while -- screen blacks out. When doing password input, or after opening some applications, scrcpy renders a black screen however input events are still passed correctly. Is there any way to overcome this? I'm open to everything (rooting, magisk, custom rom).

**Comment by rom1v** [comment]
Do you use at least [v1.6](https://github.com/Genymobile/scrcpy/releases/tag/v1.6), which fixed #36?

**Comment by amosbird** [comment]
hmm, lemme update!

**Comment by amosbird** [comment]
thanks!
