### ISSUE TITLE
可以在链接成功后窗口显示的，同时创建一个虚拟摄像头吗，也吧画面实时推送到摄像头，方便网络视频聊天软件，可以直接展示手机画面

### ISSUE THREAD

**Issue by adminxy** [Genymobile/scrcpy#5206]
可以在链接成功后窗口显示的，同时创建一个虚拟摄像头吗，也吧画面实时推送到摄像头，方便网络视频聊天软件，可以直接展示手机画面

**Comment by adminxy** [comment]
如何在Windows电脑上实现该功能  https://github.com/Genymobile/scrcpy/blob/master/doc/v4l2.md

**Comment by rom1v** [comment]
#5207

**Comment by me2sy** [comment]
> 可以在链接成功后窗口显示的，同时创建一个虚拟摄像头吗，也吧画面实时推送到摄像头，方便网络视频聊天软件，可以直接展示手机画面
可以试试MYScrcpy 1.3.2 支持OBS虚拟摄像头，推流OBS，钉钉等
https://github.com/me2sy/MYScrcpy 
![image](https://github.com/user-attachments/assets/a5667154-9501-449c-84a3-90c12a5b027f)
