### ISSUE TITLE
Uhh... Bugged cursor... I guess?

### ISSUE THREAD

**Issue by GamingWithJanko** [Genymobile/scrcpy#5208]
_Please read the [prerequisites] to run scrcpy._

[prerequisites]: https://github.com/Genymobile/scrcpy#prerequisites

_Also read the [FAQ] and check if your [issue][issues] already exists._

[FAQ]: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md
[issues]: https://github.com/Genymobile/scrcpy/issues

## Environment

 - **OS:** Windows 11 x64 Home
 - **Scrcpy version:** Latest (2.6.1)
 - **Installation method:** ZIP
 - **Device model:** RedMi 13 Note Pro+ 5G (23090RA98G)
 - **Android version:** HyperOS (1.0.4.0.UNOEUXM) / Android 14 UP1A.231005.007 / Patch 2024-04-01

## Describe the bug

I dunno, what I'm looking at, except an error, when I move my cursor in the window.

On errors, please provide the output of the console (and `adb logcat` if relevant).

See Log.txt (File removed)

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy#prerequisites

**Comment by GamingWithJanko** [comment]
For some reason, I never saw THAT option.

Good to know.

Marking as solved.

Log-file has been removed.
