### ISSUE TITLE
SCRCPY closes itself a lot with WARN: Cannot terminate server

### ISSUE THREAD

**Issue by aetkas001** [Genymobile/scrcpy#521]
I recently started using SCRCPY and it worked fine, and still does sometimes, but very often it'll close after a random amount of time with the only error being WARN: Cannot terminate server

I'm connected via USB to one of the ports that are on the motherboard (I read that using front USB ports may be problematic due to low power.)

![Capture](https://user-images.githubusercontent.com/50270918/57181402-2994a000-6e61-11e9-9dda-792b317940f4.PNG)

When this happens, some of the time I'll hear the Windows USB connect, disconnect sound a few times, but this doesn't happen all the time when this error occurs.

On Windows 8.1, latest version of SCRCPY and Android 9.

**Comment by rom1v** [comment]
Yes, it looks like a USB connection issue.

**Comment by aetkas001** [comment]
> 
> 
> Yes, it looks like a USB connection issue.

Yep, so I'm trying it wirelessly and it's working fine. One question though: How do I set it up so it defaults to the lower bitrate when I run scrcpy.exe? Right now I have to open a cmd prompt and manually typed in "scrcpy -b2M -m800"

Thanks

**Comment by rom1v** [comment]
On Windows, create a file having extension `.bat` containing:

    scrcpy -b2M -m800

Then double-click on it.

An alternative would be to try with another USB cable :wink:

**Comment by aetkas001** [comment]
Thanks! I'll try that at some point but this works fine for now. :)

**Comment by aetkas001** [comment]
> 
> 
> On Windows, create a file having extension `.bat` containing:
> 
> ```
> scrcpy -b2M -m800
> ```
> 
> Then double-click on it.
> 
> An alternative would be to try with another USB cable wink

Actually I think I've solved the USB issue, but now I can't connect via USB because theres more than 1 device/emulator

How do I fix this?

**Comment by rom1v** [comment]
adb devices

gives you a list of connected devices, with their serial number.

Use:

    scrcpy -s your_device_serial_number

to start scrcpy for a specific device.

**Comment by aetkas001** [comment]
> 
> 
> ```
> adb devices
> ```
> 
> gives you a list of connected devices, with their serial number.
> 
> Use:
> 
> ```
> scrcpy -s your_device_serial_number
> ```
> 
> to start scrcpy for a specific device.

Thanks!
