### ISSUE TITLE
Capture window doesn't appear in OTG mode

### ISSUE THREAD

**Issue by QmroQ** [Genymobile/scrcpy#5220]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
- [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

## Environment

 - **OS:** Fedora 40
 - **Scrcpy version:** 2.6.1
 - **Installation method:** copr repo
 - **Device model:** Poco X3 Pro
 - **Android version:** 14

## Description
The window seems to appear in i3 but not in hyprland or sway, so I'm assuming it's a wayland problem

![i3](https://github.com/user-attachments/assets/e4cfa7a0-ec7a-40f3-ad12-96b6200a64ad)

![hyprland](https://github.com/user-attachments/assets/8bac82e9-e66e-46e7-ab7c-c3e8c6b2e965)

**Comment by NeumoNeumo** [comment]
I have the same problem. I am running `scrcpy --otg` on sway with xwayland enabled. When I use `SDL_VIDEODRIVER=wayland`, everything seems all right except the missing capture window. And when I set `SDL_VIDEODRIVER=x11`, it turns out successfully.

**Comment by rom1v** [comment]
See #5280.
