### ISSUE TITLE
Branch your source code based on Release info

### ISSUE THREAD

**Issue by Coool** [Genymobile/scrcpy#5224]
Hi, @rom1v !

Can you branch your source code with .., v1.23, v1.24, v1.25, v2.0 names and so on based on your tag info from Release section?

Thanks.

**Comment by rom1v** [comment]
From v2.0, there are `v2.0-install-release`, `v2.1-install-release`, and so on.

Why it is done that way: https://github.com/Genymobile/scrcpy/issues/4098#issuecomment-1600332180

From https://github.com/Genymobile/scrcpy/issues/4098#issuecomment-2267093795:

> I might consider to move the tag just after the binaries are generated in the future, that would "solve" the problem. 

So in the future, `v2.7` (for example) might point to the commit with the updated `install_release.sh` script (and README).

**Comment by Coool** [comment]
What does your release cycle issue have to do with to branch your code with names from your  already existing Release section according to hash found in specific version. Are you willing to do it or not? After we can talk about your decisions when better to create new release tag. My suggestion after you compiled all your stuff, created all needed checksums and updated all files with new sums you can create new release version. Or it's how you dealing with automatization consequences. Are GitHub actions building your binaries? OK, hope you branch out your repo based on already existing tags.

Thanks.

**Comment by rom1v** [comment]
Sorry, I may have answered too quickly.

> Can you branch your source code with .., v1.23, v1.24, v1.25, v2.0 names and so on based on your tag info from Release section?

> What does your release cycle issue have to do with to branch your code with names from your already existing Release section according to hash found in specific version.

I think I don't understand what you're requesting exactly.

**Comment by Coool** [comment]
How did you created dev branch and other branches on your repo? Same create versions branches. Go under Branch section create new branch with name from Release section and point source to hash from specific version. Or it's impossible!

**Comment by Coool** [comment]
You already have v1.18 version branch with [release-v1.18](https://github.com/Genymobile/scrcpy/tree/release-v1.18) name.

**Comment by rom1v** [comment]
I don't understand what you want (or why). Create your branch locally as you want. Each release has a tag (not a branch), for example `v2.6.1` (or `v1.18` as you mentioned).

**Comment by Coool** [comment]
I want depend on source author not some bloke like me. It's not hard for me to do on my repo but I'm just some untrusted bloke. This would meet the coding standard.

**Comment by Coool** [comment]
I'm not Git guru. Everybody have their percpective on things. I'm not arguing. But it's imposible to point to your repo version tags from my repo tags. GitHub only provides poiting to branches. I have other idea will try it then see if it works. Thanks for your input.

**Comment by rom1v** [comment]
> But it's imposible to point to your repo version tags from my repo tags.

I don't know about your repo, but here I can select tags (on GitHub, there are two tabs when you select a version: "branches" and "tags"). For example: https://github.com/Genymobile/scrcpy/tree/v2.6.1

> But what's up with [release-v1.18](https://github.com/Genymobile/scrcpy/tree/release-v1.18) branch?

That's a temporary branch when I prepared the release probably, like the hundreds other temporary branches that I never removed. :/

**Comment by Coool** [comment]
I stop bothering you with my stupid question. I did my way. Anyway you can't point to remote repo tag when you create new tag or edit existing one, ONLY to branches.

Thanks.
