### ISSUE TITLE
snap package adoption/collaboration

### ISSUE THREAD

**Issue by sisco311** [Genymobile/scrcpy#523]
Hi,

I'm working on a[ snap package for scrcpy](https://github.com/sisco311/scrcpy-snap). I have published the snap in the snap store's edge channel. After some user feedback I think I have managed to iron out most snap related issues and consider the snap stable enough to be published in the stable channel.

My question is that do you have any plans to adopt the snap or create your own snap for scrcpy in the near future? 

If not, then I would like to ask for your permission to (continue to) use the  scrcpy name for the  snap and publish it to the stable channel. 

I'm currently using the master branch to build scrcpy. Is it stable enough or should I use the latest release (v1.8) instead?

Best Regards,
sisco311

**Comment by rom1v** [comment]
Hi,

Thank you for your work :+1:

> do you have any plans to adopt the snap or create your own snap for scrcpy in the near future?

No, I don't. I am very happy when other people maintain packages independantly. :wink:

> If not, then I would like to ask for your permission to (continue to) use the scrcpy name for the snap and publish it to the stable channel.

Sure, please do.

> I'm currently using the master branch to build scrcpy. Is it stable enough or should I use the latest release (v1.8) instead?

`master` is more likely to be broken occasionally, so I would recommend to use tagged versions.

Cheers

**Comment by sisco311** [comment]
Thank you, rom1v!

v1.8 is in the stable channel. The version built from master is also available from the edge channel.

Will try my best to maintain the packages and answer any related issues.

Not sure if this is the right place to ask, but it would bee cool if you could mention the availability of the snap package somewhere in the README.

Kind Regards,
sisco311

**Comment by rom1v** [comment]
Thank you.

> Not sure if this is the right place to ask, but it would bee cool if you could mention the availability of the snap package somewhere in the README.

Please open a PR to mention it in https://github.com/Genymobile/scrcpy#linux :wink:

**Comment by rom1v** [comment]
> mention the availability of the snap package somewhere in the README

Done: de2016a48e3016e6f24858afa9c52a9a54e8ab47
