### ISSUE TITLE
[Linux] Cannot build/start v2.6.1 from the given source tar

### ISSUE THREAD

**Issue by mchlnix** [Genymobile/scrcpy#5236]
I downloaded the tarball from release 2.6.1 [1] and tried building them using the information here [2].

I could build it just fine, but when starting I get the error message, that the server and client versions are incompatible, since the server is still only 2.6.

It seems like you forgot to update the download link and check sum of the 2.6.1 server binary in the `install_release.sh` script.

I changed line 5 and 6 to:

```
PREBUILT_SERVER_URL=https://github.com/Genymobile/scrcpy/releases/download/v2.6.1/scrcpy-server-v2.6.1
PREBUILT_SERVER_SHA256=ca7ab50b2e25a0e5af7599c30383e365983fa5b808e65ce2e1c1bba5bfe8dc3b
```

After reinstalling with that it works as expected. 

I won't do a pull request, since it will be outdated as soon as you do a new release anyway. So this is just a reminder.

[1] https://github.com/Genymobile/scrcpy/releases/tag/v2.6.1
[2] https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md

**Comment by rom1v** [comment]
- https://github.com/Genymobile/scrcpy/issues/4098#issuecomment-1600332180
 - https://github.com/Genymobile/scrcpy/issues/4098#issuecomment-2267093795

**Comment by rom1v** [comment]
Tag `v2.7` points to the updated `install_release.sh` :rocket:
