### ISSUE TITLE
Server version not matching the client version in version 2.6.1

### ISSUE THREAD

**Issue by vpadois** [Genymobile/scrcpy#5238]
Hi,
When downloading the source code of release v2.6.1, the install script refers v2.6 for the server.

This can be solved by replacing in file install_release.sh the two lines :

PREBUILT_SERVER_URL=https://github.com/Genymobile/scrcpy/releases/download/v2.6/scrcpy-server-v2.6
PREBUILT_SERVER_SHA256=7b723ff79a27f14e6ebaaaae7ef9548c40651c94e64d178612b13adf7158eb2e

by

PREBUILT_SERVER_URL=https://github.com/Genymobile/scrcpy/releases/download/v2.6.1/scrcpy-server-v2.6.1
PREBUILT_SERVER_SHA256=ca7ab50b2e25a0e5af7599c30383e365983fa5b808e65ce2e1c1bba5bfe8dc3b

Thanks for this great project.

**Comment by rom1v** [comment]
- https://github.com/Genymobile/scrcpy/issues/4098#issuecomment-1600332180
 - https://github.com/Genymobile/scrcpy/issues/4098#issuecomment-2267093795

I will probably tag the version including the release sums for the next version to avoid the problem.

**Comment by vpadois** [comment]
I am closing it. 

And once again : thanks for this great piece of software !
