### ISSUE TITLE
MIC AND AUDIO

### ISSUE THREAD

**Issue by LAXMINARAYAN24** [Genymobile/scrcpy#5239]
I am using srcpy for boosting my volume on headphone through connecting it to pc and then phone . But when i play bgmi and turn on the mic and speaker its audio turn off in the headphone it comes from mobile .

**Comment by rom1v** [comment]
Duplicate of #4084 #4087.

**Comment by TamikGuk** [comment]
maybe there is some kind of program for combining sound or the like.
