### ISSUE TITLE
Can I use Copy-paste on OTG mode?

### ISSUE THREAD

**Issue by foobra** [Genymobile/scrcpy#5244]
I can't trigger Copy-paste when using mouse and keyboard under OTG mode

**Comment by rom1v** [comment]
In OTG mode, USB debugging is not used, and there is no server running on the device. The only communication is HID events over AOA, so copy-paste cannot be supported.

If you have USB debugging enabled, and want to control your device without mirroring, don't use OTG mode, but:

```
scrcpy --no-video --no-audio
```

In this mode, copy-paste works.

**Comment by foobra** [comment]
> In OTG mode, USB debugging is not used, and there is no server running on the device. The only communication is HID events over AOA, so copy-paste cannot be supported.
> 
> If you have USB debugging enabled, and want to control your device without mirroring, don't use OTG mode, but:
> 
> ```
> scrcpy --no-video --no-audio
> ```
> 
> In this mode, copy-paste works.

That's works as I want
