### ISSUE TITLE
When I open Scrcpy, it displays a black window, but I can still interact with and click on elements.

### ISSUE THREAD

**Issue by KRIISHSHARMA** [Genymobile/scrcpy#5248]
This issue is similar to [#3229](https://github.com/Genymobile/scrcpy/issues/3229).

Environment:

OS: Windows 10
scrcpy version: 2.6.1
Installation method: Attempted manual installation by cloning the repository
Device model: Nothing A063
Android version: 13

I've followed the solutions suggested in [issue #3229](https://github.com/Genymobile/scrcpy/issues/3229), but unfortunately, none of them resolved the problem. Restarting both the device and the PC didn't help either.

``` sh
C:\\\\\scrcpy-win64-v2.6.1\scrcpy.exe 
[server] INFO: Device: [Nothing] Nothing A063 (Android 13)
INFO: Renderer: direct3d
INFO: Texture: 1080x2400
```
![image](https://github.com/user-attachments/assets/d6c4f633-74dd-4df1-8e38-56bd53b2530b)

**Comment by rom1v** [comment]
If you record (`scrcpy --record=file.mp4`), is the recorded file "black"?

Does it happen with all apps opened on the device? Or only those with "flag secure" (#36 #2129)?

**Comment by KRIISHSHARMA** [comment]
> If you record (`scrcpy --record=file.mp4`), is the recorded file "black"?
> 
> Does it happen with all apps opened on the device? Or only those with "flag secure" (#36 #2129)?
 
1) Yes, it records perfectly.
2)No, the issue affects all apps, including the home screen, not just specific ones.

**Comment by KRIISHSHARMA** [comment]
Oh No , Okay thanks. I'll dig into it a bit more
