### ISSUE TITLE
Apps that doesn't work with USB debugging ON

### ISSUE THREAD

**Issue by TyRaNtM** [Genymobile/scrcpy#525]
Hello. The app works very well. Sadly, some apps doesn't work with USB debugging ON. For example some games like Fate GO, that if you open it with the mode active, the game closes automatically.  Basically, you can't use this game with SCRCPY. Is there a way to fix this? Making the app works without USB debugging? Or another solution? Thanks.

**Comment by rom1v** [comment]
> some apps doesn't work with USB debugging ON

I didn't know that.

Unfortunately, I think there is nothing we can do.
