### ISSUE TITLE
Fedora 40 "NAL_UNIT_PREFIX" error (0x0x7fc3f4002100)

### ISSUE THREAD

**Issue by QuarTheDev** [Genymobile/scrcpy#5251]
## Environment

 - **OS:** `Fedora Workstation 40`
 - **Scrcpy version:** `2.6.1`
 - **Installation method:** `dnf copr enable zeno/scrcpy && dnf install scrcpy`
 - **Device model:** `samsung SM-N960U`
 - **Android version:** Android 10, One UI 2.5

## Describe the bug
On a fresh Fedora Workstation 40 installation with bash `5.2.26`, when attempting to run `scrcpy` as normal, it outputs several errors. The usual Google search did not help solve my problem. Output below:

```
scrcpy 2.6.1 <https://github.com/Genymobile/scrcpy>
WARN: Could not disable minimize on focus loss
INFO: ADB device found:
INFO:     -->   (usb)  26293538a31c7ece                device  SM_N960U
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 416.1 MB/s (71112 bytes in 0.000s)
[server] INFO: Device: [samsung] samsung SM-N960U (Android 10)
[server] WARN: Audio disabled: it is not supported before Android 11
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 24.1.6
INFO: Trilinear filtering enabled
WARN: Demuxer 'audio': stream explicitly disabled by the device
INFO: Texture: 1080x2216
ERROR: [FFmpeg] [OpenH264] this = 0x0x7fc0f0002100, Error:NAL_UNIT_PREFIX: DecInitBits() fail due invalid access.
ERROR: [FFmpeg] DecodeFrame failed
ERROR: Decoder 'video': could not send video packet: -1313558101
ERROR: Demuxer error
```

Oddly, when ran as sudo, I get a slightly different output (make note of Line 2):
```
scrcpy 2.6.1 <https://github.com/Genymobile/scrcpy>
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
INFO: ADB device found:
INFO:     -->   (usb)  26293538a31c7ece                device  SM_N960U
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 402.5 MB/s (71112 bytes in 0.000s)
[server] INFO: Device: [samsung] samsung SM-N960U (Android 10)
[server] WARN: Audio disabled: it is not supported before Android 11
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 24.1.6
INFO: Trilinear filtering enabled
WARN: Demuxer 'audio': stream explicitly disabled by the device
INFO: Texture: 1080x2216
ERROR: [FFmpeg] [OpenH264] this = 0x0x7fc3f4002100, Error:NAL_UNIT_PREFIX: DecInitBits() fail due invalid access.
ERROR: [FFmpeg] DecodeFrame failed
ERROR: Decoder 'video': could not send video packet: -1313558101
ERROR: Demuxer error
```

I have installed all necessary dependencies/libraries, but nothing has changed. This exact setup (with Fedora 38, Windows 11, and Windows 10) has worked without error in the past with the same Samsung device (Galaxy Note9). It is worth noting that I am using both USB tethering and [GSConnect](https://github.com/GSConnect/gnome-shell-extension-gsconnect) while attempting to run scrcpy, but after testing without tethering or GSConnect present, I still get the same result.

Any help/guidance is appreciated. Thank you

**Comment by rom1v** [comment]
It is either an encoder issue, or a decoder issue.

To determine which one is buggy:
 - try to record (`scrcpy --record=file.mp4`) then play the file with a video player (like vlc or even firefox)
 - try with another [encoder](https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#encoder) (or another device)

**Comment by QuarTheDev** [comment]
Thank you @rom1v. The issue turned out to be encoder-related. I'll go ahead and document which encoders/codecs worked and did not work for me:

☒ `--video-codec=h264 --video-encoder='OMX.qcom.video.encoder.avc'`
☑ `--video-codec=h264 --video-encoder='c2.android.avc.encoder'`
☑ `--video-codec=h264 --video-encoder='OMX.google.h264.encoder'`
☒ `--video-codec=h265 --video-encoder='OMX.qcom.video.encoder.hevc'`
☒ `--video-codec=h265 --video-encoder='c2.android.hevc.encoder'`

Out of curiosity, would there be a way to set a default encoder/codec for `scrcpy`? What would I have to do to get some of the h265 codecs functional?

**Comment by rom1v** [comment]
It might still be a decoder error (which happens to be triggered only by a bitstream produced by some encoders).

Could you record a few seconds and post the file?

```
scrcpy --record=file.mp4 --no-playback
```

**Comment by QuarTheDev** [comment]
I understand and I apologize for the late reply - attached is the extracted `file.mp4` from the snippet you've provided.

https://github.com/user-attachments/assets/b9ee18e8-1c4c-4b88-8892-7a8cbe4edf1b

**Comment by rom1v** [comment]
OK, thank you. So this capture works perfectly in the browser, so if it does not work in scrcpy directly, there is a problem with the decoder :thinking:
