### ISSUE TITLE
Do you have any plans on adding an update mechanism to scrcpy?

### ISSUE THREAD

**Issue by bergamin** [Genymobile/scrcpy#5261]
It's a bit frustrating that we have to actively check for updates on GitHub, delete the folder and manually download a zip to substitute the contents of the previous folder.

But I understand. You would need to maintain an infrastructure. So maybe get it to update through an officially maintained package manager like MS Store?

**Comment by rom1v** [comment]
There are (third-party) packages via scoop or chocolatey: https://github.com/Genymobile/scrcpy/blob/master/doc/windows.md#install

**Comment by bergamin** [comment]
Does that auto-update? Or do I need to still keep checking for updates here and then manually call `choco install scrcpy` whenever I want to update?

**Comment by rom1v** [comment]
> Does that auto-update? 

I think so.

> MS Store apps can be installed through `winget`

c27ab46efbcab0b9558a91e691d799ffef496c97

**Comment by yume-chan** [comment]
> BTW, I think MS Store would be a nice place for your own official release

Win32 apps in MS Store still requires their own update mechanism.

![image](https://github.com/user-attachments/assets/bb068c44-3446-473d-8be6-cae2599c15c1)

Open any Win32 app in MS Store, you will see it says "manages its own updates"

**Comment by bergamin** [comment]
I thought you would just substitute the artefact in the store, like any other app store in the history of apps stores... MS should look into this...

Thanks for the explanation
