### ISSUE TITLE
How can i simulate keyboard (or mouse) hid with socket data

### ISSUE THREAD

**Issue by uwuv3** [Genymobile/scrcpy#5262]
I use [Scrcpy Client in Python](https://github.com/leng-yue/py-scrcpy-client).
I upgraded to 2.4 -> 2.6.1.
Normal key injection not working on supercell's games and i want to simulate hid, can anyone help me?

**Comment by me2sy** [comment]
Try MYScrcpy with HID Mouse support 
https://github.com/me2sy/MYScrcpy

or read how to realize hid mouse in python 
https://github.com/me2sy/MYScrcpy/blob/main/src/myscrcpy/core/control.py

**Comment by uwuv3** [comment]
> Try MYScrcpy with HID Mouse support https://github.com/me2sy/MYScrcpy
> 
> or read how to realize hid mouse in python https://github.com/me2sy/MYScrcpy/blob/main/src/myscrcpy/core/control.py

Thank you so much, i will use it
