### ISSUE TITLE
Error occured when excuting exe file.

### ISSUE THREAD

**Issue by hyunki** [Genymobile/scrcpy#5267]
Hi I tried to excute the scrcpy.exe but this error message pop up
What else I can try? I saw some other people have same problem like me.
I followed their answer but it didn't solved my problem.

### Environment
![image](https://github.com/user-attachments/assets/c2e75891-0413-4586-930f-4c31b8359c20)

### Error message
![image](https://github.com/user-attachments/assets/3df9f262-d3c0-4106-8bbe-ba3f9725d7d4)

### This is my adb path
![image](https://github.com/user-attachments/assets/bb76f74e-e211-4eb1-8528-f127d53a88d4)

![image](https://github.com/user-attachments/assets/11e7dfda-68b2-4b4c-bdca-28cf87c6893f)
user variable path C:\Program Files (x86)\ADB and Fastboot++\
system path C:\Program Files (x86)\ADB and Fastboot++\adb.exe

### adb devices result.
![image](https://github.com/user-attachments/assets/1f54d2ca-82e6-4d05-9ba3-8f7a6313cb39)

**Comment by rom1v** [comment]
The ADB environment variable must point to the executable, not the directory (so it must end with `adb.exe`).

But it is often better to NOT set the ADB environment variable so that it uses the one packaged with the release.

**Comment by hyunki** [comment]
solved Thank you!
