### ISSUE TITLE
Scrcpy --forward-all-clicks not working 

### ISSUE THREAD

**Issue by Hassan9292-beep** [Genymobile/scrcpy#5269]
Ok so I have a android 10 oneplus 7 pro I have an issue where I cant use my mouse right click after searching I found this page I tired the method  the (scrcpy --forward-all-clicks )one and it didn't worked it said forward all clicks is deprecated  instead use --mouse-bind=++++ so searched about it I found this scrcpy -KM --no-video --no-audio --mouse-bind=bhsn I tired it but I had no luck  can anyone help me with this in an easier way thankyou

**Comment by rom1v** [comment]
> Ok so I have a android 10 oneplus 7 pro I have an issue where I cant use my mouse right click

What happen when you right click? Run `scrcpy -Vverbose --no-audio`, perform a right click, then post the full output in the console.

**Comment by Hassan9292-beep** [comment]
> > Ok so I have a android 10 oneplus 7 pro I have an issue where I cant use my mouse right click
> 
> What happen when you right click? Run `scrcpy -Vverbose --no-audio`, perform a right click, then post the full console output here.

**Comment by Hassan9292-beep** [comment]
> > Ok so I have a android 10 oneplus 7 pro I have an issue where I cant use my mouse right click
> 
> What happen when you right click? Run `scrcpy -Vverbose --no-audio`, perform a right click, then post the full console output here.

Ok wait I will let you know

**Comment by Hassan9292-beep** [comment]
> > Ok so I have a android 10 oneplus 7 pro I have an issue where I cant use my mouse right click
> 
> What happen when you right click? Run `scrcpy -Vverbose --no-audio`, perform a right click, then post the full console output here.

I m going to directly connect my mouse to my phone and I will let you know if It works or not idk if I should use the mouse with the PC connected to the phone

**Comment by Hassan9292-beep** [comment]
> > Ok so I have a android 10 oneplus 7 pro I have an issue where I cant use my mouse right click
> 
> What happen when you right click? Run `scrcpy -Vverbose --no-audio`, perform a right click, then post the full console output here 
Ok so what I did was I runned the command as the one you mentioned  and then I removed the mouse and phone from my PC connected my 
Phone to the mouse directly when I press the right mouse button it still acts as a back instead of forward or like a PC right button would act can't I fix it

**Comment by Hassan9292-beep** [comment]
> > Ok so I have a android 10 oneplus 7 pro I have an issue where I cant use my mouse right click
> 
> What happen when you right click? Run `scrcpy -Vverbose --no-audio`, perform a right click, then post the full console output here.

Ok so what I did was I runned the command as the one you mentioned and then I removed the mouse and phone from my PC connected my
Phone to the mouse directly when I press the right mouse button it still acts as a back instead of forward or like a PC right button would act can't I fix it

**Comment by rom1v** [comment]
```
scrcpy --no-audio -Vverbose --mouse-bind=++++
````

What is the output in the console when you right-click? Does it perform a right-click? (in which app on Android?)

**Comment by Hassan9292-beep** [comment]
> ```
> scrcpy --no-audio -Vverbose --mouse-bind=++++
> ```
> 
> What is the output in the console when you right-click? Does it perform a right-click? (in which app on Android?)



> ```
> scrcpy --no-audio -Vverbose --mouse-bind=++++
> ```
> 
> What is the output in the console when you right-click? Does it perform a right-click? (in which app on Android?)

https://github.com/user-attachments/assets/a183030b-449b-4665-bed9-fe2ad2008cd5

**Comment by rom1v** [comment]
The video only shows some touch events, not clicks.

Please capture the whole console output as text (copy-paste).

**Comment by Hassan9292-beep** [comment]
> The video only shows some touch events, not clicks.
> 
> Please capture the whole console output as text (cop

> the

I don't understand what am I supposed to do can u guide me

**Comment by Hassan9292-beep** [comment]
Ok wait let me copy it

**Comment by Hassan9292-beep** [comment]
> The video only shows some touch events, not clicks.
> 
> Please capture the whole console output as text (copy-paste).

Can u guide me I don't understand what I need to do

**Comment by Hassan9292-beep** [comment]
> The video only shows some touch events, not clicks.
> 
> Please capture the whole console output as text (copy-paste).

How do I share clicks

**Comment by Hassan9292-beep** [comment]
> The video only shows some touch events, not clicks.
> 
> Please capture the whole console output as text (copy-paste).

![IMG_20240910_023441.jpg](https://github.com/user-attachments/assets/4f3e4bfb-bb29-406a-96fd-5dc563e902db)

**Comment by rom1v** [comment]
You definitely did not pass `--mouse-bind=++++` here. I can even see the command on your previous video; https://github.com/Genymobile/scrcpy/issues/5269#issuecomment-2339092724

**Comment by Hassan9292-beep** [comment]
> You definitely did not pass `--mouse-bind=++++` here. I can even see the command on your previous video; https://github.com/Genymobile/scrcpy/issues/5269#issuecomment-2339092724

What do I do then ya because I'did not understand the command for it

**Comment by rom1v** [comment]
Instead of:

```
scrcpy --no-audio -Vverbose
```

Run:

```
scrcpy --no-audio -Vverbose --mouse-bind=++++
```

**Comment by Hassan9292-beep** [comment]
> Instead of:
> 
> ```
> scrcpy --no-audio -Vverbose
> ```
> 
> Run:
> 
> ```
> scrcpy --no-audio -Vverbose --mouse-bind=++++
> ```

Ok wait

**Comment by Hassan9292-beep** [comment]
> Instead of:
> 
> ```
> scrcpy --no-audio -Vverbose
> ```
> 
> Run:
> 
> ```
> scrcpy --no-audio -Vverbose --mouse-bind=++++
> ```
It's working let me ask will it work if I connect my mouse with an otg with my phone

**Comment by Hassan9292-beep** [comment]
> Instead of:
> 
> ```
> scrcpy --no-audio -Vverbose
> ```
> 
> Run:
> 
> ```
> scrcpy --no-audio -Vverbose --mouse-bind=++++
> ```

It is working on the scrcpy app but how do I make it work on my mouse with my phone connected to it without the need of the PC and scrcpy

**Comment by rom1v** [comment]
Apparently with a physical mouse without scrcpy, the behavior before Android 11 was to press BACK on right-click: https://www.reddit.com/r/oneplus/comments/lfhqme/mouse_right_click_no_longer_navigate_back_on/

**Comment by Hassan9292-beep** [comment]
> Apparently with a physical mouse without scrcpy, the behavior before Android 11 was to press BACK on right-click: https://www.reddit.com/r/oneplus/comments/lfhqme/mouse_right_click_no_longer_navigate_back_on/

Am I supposed to find the answer in that link?

**Comment by Hassan9292-beep** [comment]
> Apparently with a physical mouse without scrcpy, the behavior before Android 11 was to press BACK on right-click: https://www.reddit.com/r/oneplus/comments/lfhqme/mouse_right_click_no_longer_navigate_back_on/

I'm on Android 10 tho

**Comment by rom1v** [comment]
> Am I supposed to find the answer in that link?

Why do you even ask instead of reading the page pointed by the link?

You're asking why without scrcpy the mouse right click performs a BACK. I didn't know (it's not even scrcpy), so I searched on the Internet for you, and I found this link explaining that before Android 11 (you are on Android 10), that was the behavior, and apparently it is not configurable.

**Comment by Hassan9292-beep** [comment]
> > Am I supposed to find the answer in that link?
> 
> Why do you even ask instead of reading the page pointed by the link?
> 
> You're asking why without scrcpy the mouse right click performs a BACK. I didn't know (it's not even scrcpy), so I searched on the Internet for you, and I found this link explaining that before Android 11 (you are on Android 10), that was the behavior, and apparently it is not configurable.

I read it then replied becz didn't find the solution for me in android 10 the option was never there I think in android 11 u can fix it but turning on permission monitoring in devolper options but we don't have that option in android 10 so Ig there is nothing I can do
