### ISSUE TITLE
Auto Cursor Click / Ghost Cursor Click

### ISSUE THREAD

**Issue by Fabrihakc** [Genymobile/scrcpy#5271]
Hello, good day, I have a problem with the program, recently it was working well for me and today when I started I had problems that it automatically "right clicks" the mouse on the phone screen, I thought it was my mouse but it is not, I put a otg to my cell phone and I had no problems, the problem only appears when I start the program and I want to use my keyboard and mouse. I am going to attach the commands that I have for the bat file:

@echo off
scrcpy.exe --pause-on-exit=if-error %* --mouse=uhid --keyboard=sdk 

No error appears in the console, it just clicks automatically by passing the cursor over anything on the screen of my cell phone. I noticed because when I enter the calculator on my cell phone, it only clicks automatically when passing over a number.

I hope you can understand, I'm using a translator
I'm using the latest version of scrcpy

Moto G13
processor: MediaTek Helio G85.
operating system: Android 14

notebook
processor :Intel celeron N3060.
ram: 8gb

**Comment by rom1v** [comment]
Run with `-Vverbose` and check in the console that a click is performed by scrcpy.
