### ISSUE TITLE
Video bitrate setting

### ISSUE THREAD

**Issue by AZCodingAccount** [Genymobile/scrcpy#5273]
Hey, scrcpy team,

I'm currently trying to mirror my Huawei MatePad to my computer, and I found that changing the bitrate setting (--video-bit-rate=32M) makes the screen much clearer. My question is: what is the trade-off for using a higher bitrate?

Additionally, I have a need to mirror my computer's screen to the tablet. Does scrcpy support this feature?

Thanks!

**Comment by rom1v** [comment]
> My question is: what is the trade-off for using a higher bitrate?

There is more data to transmit, so probably a bit more latency.

You should also try `--video-codec=h265`, depending on your device it might be more efficient (even at the default bit rate).

**Comment by AZCodingAccount** [comment]
thx, I have another question: why is my wireless debugging not working? When I run the command `adb connect 192.168.138.37:5555` while connected via USB, wireless connection works fine. However, after I disconnect the USB cable, I get an error. I'm sure both devices are on the same local network and the IP address is correct. What could be the reason for this?

**Comment by rom1v** [comment]
https://stackoverflow.com/questions/37267335/android-studio-wireless-adb-error-10061/41422712

**Comment by AZCodingAccount** [comment]
I want to add that the issue of connection refusal might not be due to what I mentioned earlier. The actual reason was that the tablet automatically turned off USB debugging when the USB connection was disconnected!
