### ISSUE TITLE
Can't turn screen off when mirroring while using Tecno Pova 5

### ISSUE THREAD

**Issue by zim267** [Genymobile/scrcpy#5274]
- OS: [LMDE (Linux Mint Debian Version) 6]
 - Scrcpy version: 2.6.1
 - Installation method: cloning from repo using terminal
 - Device model: Tecno LH7n
 - Android version: 14

When I tried to run scrcpy with the --turn-screen-off command, it only briefly opened, while the phone screen is still on, and then closes on its own. I don't have any problem with running scrcpy without the --turn-screen-off. But if I run scrcpy regularly (which works fine) and then tried to used the shortcut to turn the screen off, it also closes on its own immediately.

Here's my terminal output
~$ scrcpy --turn-screen-off
scrcpy 2.6.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  106293737Q007809                device  TECNO_LH7n
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 1.9 MB/s (71112 bytes in 0.036s)
[server] INFO: Device: [TECNO] TECNO TECNO LH7n (Android 14)
ATTENTION: default value of option force_glsl_version overridden by environment.
ATTENTION: default value of option force_compat_profile overridden by environment.
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 22.3.6
INFO: Trilinear filtering enabled
INFO: Texture: 2456x1080
Native registration unable to find class 'com/transsion/hubcore/server/trancare/trancare/TranTrancareCtrlNative'; aborting...
WARN: Device disconnected
Aborted

**Comment by rom1v** [comment]
Yes, on some devices with modified vendor ROMs with Android 14, it does not work.

I have no solution.

**Comment by CrimsonSZ-Q** [comment]
same here

**Comment by yume-chan** [comment]
Please test https://github.com/Genymobile/scrcpy/issues/4544#issuecomment-2526999714
