### ISSUE TITLE
Scrcpy never connects to server over wifi

### ISSUE THREAD

**Issue by rosteen** [Genymobile/scrcpy#528]
Hi,

 I've read through the related issues that I could find and still can't get this to work. I have a successful adb connection to the phone via port 5555, I can see that my machine is listening at port 27183, and while running scrcpy I can see that app_process is running on the phone:

`shell     12651 12649 900648 35024 __skb_recv a68a7598 S app_process`

However, once scrcpy gets to the point of connecting to the server it simply loops through all of the retries and then dies quietly. I've upped the number of attempts and the wait between attempts to the point where I was waiting 10 minutes to connect with no success, so it doesn't seem like this is simply due to the server not having started up yet. Any insight you could provide would be appreciated, as I'm stumped at this point - should I perhaps also be seeing another server process on the phone (e.g. com.genymobile.scrcpy.Server)? Further details are below and the output with ADB_TRACE=all is attached.

OS: Ubuntu 18.0.4
Phone: ZTE Majesty Tracphone running Android 7.1.1
adb version 1.0.41 (initially was running 1.0.31, but updating did not solve the issue)

[scrcpy_debugging.txt](https://github.com/Genymobile/scrcpy/files/3163929/scrcpy_debugging.txt)

**Comment by rom1v** [comment]
Do you use v1.8 with scrcpy-server.jar v1.8?

>     INFO: Starting server on phone...
>     INFO: Invalid Socket

These are your own logs, right?

Anything relevant in `adb logcat`?

**Comment by rosteen** [comment]
Thanks for the quick reply - it does work fine while connected over USB, I should have mentioned that. I'm using the pre-built server v1.8 and scrcpy is v1.8. You're correct that the two INFO lines are additional logging messages I added while trying to track down where the problem is.

I attached some adb logcat output, I'll admit to not really knowing what I'm looking for there. The file starts at the scrcpy server call and should include a good number of attempts to connect (I didn't let logcat run for the whole 100 attempts though). 

[adb_logcat.txt](https://github.com/Genymobile/scrcpy/files/3166717/adb_logcat.txt)

**Comment by rom1v** [comment]
(reusing my [comment](https://www.reddit.com/r/androidapps/comments/acdpdn/cannot_get_scrpy_to_work_with_wireless_adb/edalpq2/))

OK, let's try to establish a connection manually through a tcp-tcp adb tunnel.

First, download _netcat_ (`nc`) for ARM (I assume your Android device is ARM):
https://github.com/jakev/android-binaries/raw/master/nc _(sha256: 308390d5f07704e7da1a6796b324ae4076fb48695a994e9dafc0a0110f8ac652 when I downloaded it)_

Push it to the device and make it executable:

    adb push nc /data/local/tmp/
    adb shell chmod +x /data/local/tmp/nc

Enable tcp forwarding:

    adb forward tcp:1234 tcp:5678

Any connection to localhost:1234 on the computer will now be redirected to localhost:5678 on the device.

Start a TCP server listening on 5678 on the device:

    adb shell /data/local/tmp/nc -l -p 5678

It does nothing, it's expected. Keep this terminal open.

Open another terminal, and connect to localhost:1234 from your computer:

    nc localhost 1234

Now, type something, and press Enter: anything you write in this terminal should be printed to the device terminal after every newline.

Does it work?

**Comment by rosteen** [comment]
Ah, this doesn't appear to work either. Starting the server listening on the device appears to work, but after running nc on my computer when I type a string and hit enter the process ends and no text appears in the device terminal.

**Comment by rom1v** [comment]
(closing as it seems it is not a scrcpy issue)
