### ISSUE TITLE
ERROR: Could not create default video encoder for h264

### ISSUE THREAD

**Issue by YANGKUN87** [Genymobile/scrcpy#5286]
Environment
OS: Android
Scrcpy version: 2.6.1
Installation method: Windows release
Device model: TICWATCH
Android version: 9

Describe the bug

My terminal:

E:\TIC\scrcpy-win64-v2.6.1>scrcpy
scrcpy 2.6.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  7202X9C240379                   device  TicWatch_Pro
E:\TIC\scrcpy-win64-v2.6.1\scrcpy-serv...pped. 2.1 MB/s (71112 bytes in 0.032s)
[server] INFO: Device: [Mobvoi] mobvoi TicWatch Pro (Android 9)
[server] WARN: Audio disabled: it is not supported before Android 11
[server] ERROR: Could not create default video encoder for h264
List of video encoders:
    (none)
[server] ERROR: Exception on thread Thread[video,5,main]
java.lang.IllegalArgumentException: Failed to initialize video/avc, error 0xffff
fffe
        at android.media.MediaCodec.native_setup(Native Method)
        at android.media.MediaCodec.<init>(MediaCodec.java:1811)
        at android.media.MediaCodec.createEncoderByType(MediaCodec.java:1777)
        at com.genymobile.scrcpy.video.SurfaceEncoder.createMediaCodec(SurfaceEn
coder.java:219)
        at com.genymobile.scrcpy.video.SurfaceEncoder.streamCapture(SurfaceEncod
er.java:64)
        at com.genymobile.scrcpy.video.SurfaceEncoder.lambda$start$0$com-genymob
ile-scrcpy-video-SurfaceEncoder(SurfaceEncoder.java:268)
        at com.genymobile.scrcpy.video.SurfaceEncoder$$ExternalSyntheticLambda0.
run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:764)
ERROR: "adb reverse --remove" returned with value 1
ERROR: Could not retrieve device information
ERROR: Server connection failed

E:\TIC\scrcpy-win64-v2.6.1>
E:\TIC\scrcpy-win64-v2.6.1>scrcpy --list-encoders
scrcpy 2.6.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  7202X9C240379                   device  TicWatch_Pro
E:\TIC\scrcpy-win64-v2.6.1\scrcpy-serv...pped. 0.9 MB/s (71112 bytes in 0.075s)
[server] INFO: Device: [Mobvoi] mobvoi TicWatch Pro (Android 9)
[server] INFO: List of video encoders:
    (none)
[server] INFO: List of audio encoders:
    --audio-codec=aac --audio-encoder='OMX.google.aac.encoder'
    --audio-codec=flac --audio-encoder='OMX.google.flac.encoder'

E:\TIC\scrcpy-win64-v2.6.1>

**Comment by rom1v** [comment]
There is no video encoder on your device.

**Comment by YANGKUN87** [comment]
> 您的设备上没有视频编码器。

How should this problem be solved？

**Comment by YANGKUN87** [comment]
> 您的设备上没有视频编码器。

Can Android devices install encoder?
