### ISSUE TITLE
[question] how can I get window title from script?

### ISSUE THREAD

**Issue by almaceleste** [Genymobile/scrcpy#529]
I run scrcpy by bash script. I need to know window title to control it.  
how can I get it?

**Comment by rom1v** [comment]
The device sends the device model to the client application, which uses it as window title:

https://github.com/Genymobile/scrcpy/blob/39b5893c427ebe13d7cdf2e59930919bb7841bb5/server/src/main/java/com/genymobile/scrcpy/DesktopConnection.java#L58

https://github.com/Genymobile/scrcpy/blob/39b5893c427ebe13d7cdf2e59930919bb7841bb5/app/src/scrcpy.c#L368-L369

You can get the very same string (the device model) from `adb`:

    adb shell getprop ro.product.model

There is a feature request (#120) to set the window title via command line arguments.

**Comment by almaceleste** [comment]
thank you for reply. could you add option to get window title too? I think it would be useful

**Comment by rom1v** [comment]
> could you add option to get window title too

Just call:

    adb shell getprop ro.product.model
