### ISSUE TITLE
Can't execute ninja run on Ubuntu 17.10

### ISSUE THREAD

**Issue by mateebakber** [Genymobile/scrcpy#53]
I am unable to run ninja run on ubuntu 17.10 as it throughs following error, python version is 2.7.14

> [0/1] Running external command run.
exec: No such file or directory
ERROR: "adb push" returned with value 1
FAILED: meson-run 
/usr/bin/python3 /usr/share/meson/meson --internal commandrunner /home/ateeb/StudioProjects/scrcpy /home/ateeb/StudioProjects/scrcpy/x '' /usr/share/meson/mesonintrospect scripts/run-scrcpy.sh
ninja: build stopped: subcommand failed.

**Comment by stek29** [comment]
Do you have "adb" in your path?

**Comment by mateebakber** [comment]
thanks @stek29  It worked like a charm :+1:
