### ISSUE TITLE
Could not execute "adb push" on Mac

### ISSUE THREAD

**Issue by cotfas** [Genymobile/scrcpy#530]
Hello,

I`m trying to use the app on macbook pro mojave with android sdk set to PATH and ADB set to PATH and no mater what method I use I get:

```
cotfas:scrcpy work$ adb devices
List of devices attached
9889db394248483045	device

cotfas:scrcpy work$ scrcpy
exec: Permission denied
2019-05-12 01:24:06.902 scrcpy[80573:1648708] ERROR: Failed to execute adb
2019-05-12 01:24:06.902 scrcpy[80573:1648708] ERROR: Could not execute "adb push"
```

I`ve tried also to build the src manually and ./run /x but the same issue, I`m using it with Samsung S8 non-root.

ENV Var:
```
export ADB=~/Library/Android/sdk/platform-tools/
export ANDROID_HOME=~/Library/android/sdk/
```

*both paths are exported to PATH

ADB Version:

```
cotfas:scrcpy work$ adb
Android Debug Bridge version 1.0.41
Version 28.0.3-5475833
```

I`ve also tried to remove the ADB from the path and I get the same error.

Vlad

**Comment by cotfas** [comment]
Also tried with:

cotfas:scrcpy work$ adb devices
List of devices attached
9889db394248483045	device

cotfas:scrcpy work$ adb push /usr/local/share/scrcpy/scrcpy-server.jar /data/local/tmp
/usr/local/share/scrcpy/scrcpy-server.jar: 1 file pushed. 0.4 MB/s (19850 bytes in 0.047s)
cotfas:scrcpy work$ scrcpy
exec: Permission denied
2019-05-12 12:08:41.901 scrcpy[90214:1912846] ERROR: Failed to execute adb
2019-05-12 12:08:41.901 scrcpy[90214:1912846] ERROR: Could not execute "adb push"
cotfas:scrcpy work$



And also tried with an Samsung S4 mini, the same issue

**Comment by rom1v** [comment]
@cotfas

```
which adb
```

```
ADB=$(which adb) scrcpy
```

?

**Comment by cotfas** [comment]
It worked

cotfas:bin work$ which adb
/Users/work/Library/Android/sdk/platform-tools//adb
cotfas:bin work$ 
cotfas:bin work$ ADB=$(which adb) scrcpy
/usr/local/Cellar/scrcpy/1.8/share/scr...shed. 1.7 MB/s (19850 bytes in 0.011s)
2019-05-12 12:30:49.043 scrcpy[91360:1941974] INFO: Initial texture: 1080x2216


PS: I`ve tried from windows, it works out of the box when running the exe.

For the mac version what changes I should do in order to work with scrcpy directly?

Thank you

**Comment by rom1v** [comment]
```
cotfas:bin work$ which adb
/Users/work/Library/Android/sdk/platform-tools//adb
```

```bash
echo $PATH
```

You probably have an unexpected trailing `/` in your PATH after `platform-tools`. Try to remove it, so that `which adb` prints `/Users/work/Library/Android/sdk/platform-tools/adb`.

Then check if that fixes the problem.

**Comment by rom1v** [comment]
Oh, no! I didn't notice in your first post:

```
export ADB=~/Library/Android/sdk/platform-tools/
```

You just make `scrcpy` use this as `adb` executable.

Replace it by:
```
export ADB=~/Library/Android/sdk/platform-tools/adb
```

https://github.com/Genymobile/scrcpy/blob/39b5893c427ebe13d7cdf2e59930919bb7841bb5/app/src/command.c#L13-L21

**Comment by cotfas** [comment]
Replaced, now it works.

Thank you!

**Comment by rom1v** [comment]
@cotfas I added a commit to log adb commands on error: https://github.com/Genymobile/scrcpy/commit/e443518ed902b678ad33886a2e626bfb70f8cd45

In your case, it would have printed:

```
exec: No such file or directory
ERROR: Command not found: [/Users/work/Library/Android/sdk/platform-tools/], [push], [/usr/local/share/scrcpy/scrcpy-server.jar], [/data/local/tmp/scrcpy-server.jar]
ERROR: (make 'adb' accessible from your PATH or define its fullpath in the ADB environment variable)
ERROR: Could not execute "adb push"
```

The mistake would have been obvious.

**Comment by cotfas** [comment]
Not 100% sure but last night I`ve checked with the adb in PATH as well, as it was working from the terminal from other folder, but at the moment it works so far. I`m happy with it! Keep up the good work! :)

**Comment by rom1v** [comment]
> Not 100% sure but last night I've checked with the adb in PATH as well

The value defined in `ADB` has the highest priority. If it is wrong, even if `adb` is in your PATH, it will not work.

**Comment by cotfas** [comment]
It seems for the Samsung S4 mini I get

cotfas:~ work$ scrcpy 
/usr/local/Cellar/scrcpy/1.8/share/scr...shed. 2.4 MB/s (19850 bytes in 0.008s)
adb: error: closed
2019-05-12 16:58:54.009 scrcpy[5149:2264353] ERROR: "adb reverse" returned with value 1
2019-05-12 16:58:54.009 scrcpy[5149:2264353] WARN: 'adb reverse' failed, fallback to 'adb forward'
27183

On the S8, it works.

**Comment by rom1v** [comment]
Scrcpy requires at least Android 5, I guess your S4 mini has Android 4, right?

The adb command error is printed on "unexpected" error.

For `adb reverse`, _scrcpy_ accepts it and switchs to `adb forward` if it fails, due to a bug preventing `adb reverse` to work on TCP/IP (see #5). But `adb reverse` happens to be implemented since Android 5, so it will also fail on Android < 5, but it is not supported anyway, as other things are broken before Android 5).

**Comment by cotfas** [comment]
Yes, it has android 4.

I understand, no problem. :)

**Comment by cotfas** [comment]
When using multiple devices


cotfas:~ work$ 
cotfas:~ work$ adb devices
List of devices attached
9889db394248483045	device
DUM0219319006848	device

cotfas:~ work$ scrcpy -s DUM0219319006848
/usr/local/Cellar/scrcpy/1.8/share/scrcpy/scrcpy-server.jar: 1 file pushed. 2.5 MB/s (19850 bytes in 0.008s)
bind: Address already in use
2019-05-13 19:25:53.804 scrcpy[38593:5019732] ERROR: Could not listen on port 27183
cotfas:~ work$
