### ISSUE TITLE
Cant control my phone

### ISSUE THREAD

**Issue by pavel355** [Genymobile/scrcpy#5300]
Redmi Note 5 
MIUI  version: MIUI Global 12.0.2 Stable 12.0.2.0(PEIMIXM)
Android version: 9 PKQ1.180904.001

The program does not respond to my clicks on the phone screen in any way, nothing happens when I click

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy#prerequisites

**Comment by pavel355** [comment]
Android version is 9

**Comment by rom1v** [comment]
Sure, follow the instructions in the link I posted.
