### ISSUE TITLE
[QUESTION] how do I find running server control messages port number?

### ISSUE THREAD

**Issue by github-4o** [Genymobile/scrcpy#5307]
Target: send taps to device with scrcpy server already running
Plan: custom build of scrcpy with custom entry point, which only calls control message serialization and sends resulting data

In order to do it, me needs to know the device port that server expects control messages to appear on. Is there a way I can get this port number for a server already running on device? If no, can I get this info from a client, that uploaded and started this server on device?

**Comment by rom1v** [comment]
See https://github.com/Genymobile/scrcpy/blob/master/doc/develop.md#protocol

**Comment by github-4o** [comment]
Yep, I've read it, random port
client keeps connection to control port active aka 2nd client can't send control message to the server it didn't start?

**Comment by github-4o** [comment]
Thank you
