### ISSUE TITLE
Scrcpy fails on Sony Android TV

### ISSUE THREAD

**Issue by wolpers0815** [Genymobile/scrcpy#531]
I tried to run scrcpy on my Sony Android TV (65ZF9). But that didn't work due to a crash on the server side of scrcpy. Please have a look at the attached logs and tell me what is going wrong.

[client.log](https://github.com/Genymobile/scrcpy/files/3170020/client.log)
[zf9.log](https://github.com/Genymobile/scrcpy/files/3170021/zf9.log)

**Comment by rom1v** [comment]
```
2019-05-12 13:19:10.399 scrcpy[6021:7512540] INFO: Initial texture: 1920x1080
```

```
[13:19:08.646] :: 16961 - 16970 :: [E] - venc_omx_lib: p = Limit name="size" min="128x120" max="1280x720" 
[13:19:08.646] :: 16961 - 16970 :: [E] - venc_omx_lib: max resolution support 720p
```

It seems the encoder does not support more than 1280×720, but the Android screen is 1920×1080.

Try:

    scrcpy -m1280

**Comment by wolpers0815** [comment]
Unfortunately that doesn't help...

**Comment by rom1v** [comment]
Same error?

What if you decrease more?

    scrcpy -m800

**Comment by wolpers0815** [comment]
Yes, still the same no matter what resolution.

**Comment by rom1v** [comment]
Can you record a video with:

    adb shell screenrecord /sdcard/file.mp4
    adb pull /sdcard/file.mp4

?

**Comment by wolpers0815** [comment]
I'd like to but I can't... The screenrecord call gives me the following output:
ERROR: unable to start codec (err=-2147479551)
WARNING: failed at 1920x1080, retrying at 1280x720
ERROR: unable to start codec (err=-2147479551)

The tv's logcat regarding this screenrecord call is attached.
[zf9.log](https://github.com/Genymobile/scrcpy/files/3179575/zf9.log)

**Comment by rom1v** [comment]
OK, if it does not work even with `screenrecord`, there is a real problem with the encoder.

**Comment by wolpers0815** [comment]
So do you think that this is just an encoding issue? Yeah, the logs lead to that direction. But generally I could imagine that Sony has restricted the screen output to the one and only real hardware liquid crystal display due to DRM copy right issues. Thus I would like to proof that the screen copy itself is working by just storing for example one raw image per second to the sdcard. But for that I would have to dive a bit deeper into the scrcpy source code.
My current understanding is that the scrcpy server creates another (virtual(?)) display and encodes/writes its content to the scrcpy client. What I don't understand or what I didn't see is how the content from the hardware lcd comes to the scrcpy display. Does Android this automatically as soon as a second display like the scrcpy one becomes available (similar to the clone-mode on Windows)?

**Comment by rom1v** [comment]
> Thus I would like to proof that the screen copy itself is working by just storing for example one raw image per second to the sdcard.

```bash
adb exec-out screencap -p > screenshot.png
```

> I could imagine that Sony has restricted the screen output

That would lead to a black screen, not a segfault.

> What I don't understand or what I didn't see is how the content from the hardware lcd comes to the scrcpy display

This creates a "display" of the device screen:
https://github.com/Genymobile/scrcpy/blob/e443518ed902b678ad33886a2e626bfb70f8cd45/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java#L151-L153

Le display est "projeté" sur la surface utilisée par l'encodeur:
https://github.com/Genymobile/scrcpy/blob/e443518ed902b678ad33886a2e626bfb70f8cd45/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java#L68-L69

**Comment by wolpers0815** [comment]
Screencap works except for Netflix and television.

**Comment by rom1v** [comment]
Closing because it does not work with the native `screenrecord`, so there's probably nothing scrcpy can do.
