### ISSUE TITLE
Scrcpy doesn't work for audio forwarding in a TTY terminal

### ISSUE THREAD

**Issue by EDLLT** [Genymobile/scrcpy#5312]
_Please read the [prerequisites] to run scrcpy._

[prerequisites]: https://github.com/Genymobile/scrcpy#prerequisites

_Also read the [FAQ] and check if your [issue][issues] already exists._

[FAQ]: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md
[issues]: https://github.com/Genymobile/scrcpy/issues

## Environment

 - **OS:** Ubuntu 24.04
 - **Scrcpy version:** 2.7
 - **Installation method:** Installation from source
 - **Device model:** Custom built pc
 - **Android version:** 12

## Describe the bug

Scrcpy, in the newer versions, always displays a GUI. This is problematic because sometimes I try to audio forward my phone's audio while being on a TTY terminal but that doesn't work due to the lack of an X11 server.

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
scrcpy --no-video --keyboard=disabled --mouse=disabled --no-control --require-audio

ERROR: Could not restore CRTC
ERROR: Could not create window: Can't window GBM/EGL surfaces on window creation
```

**Comment by rom1v** [comment]
Add `--no-window`.

See Highlights of release 2.5: https://github.com/Genymobile/scrcpy/releases/tag/v2.5

**Comment by EDLLT** [comment]
Thank you
