### ISSUE TITLE
2 fingers tap & move: distinguish between zoom and scrolling

### ISSUE THREAD

**Issue by Hubert21** [Genymobile/scrcpy#5317]
Hello,
That would be great if there would be a way to distinguish, for the 2 finger tap, between a gesture where two fingers are spread apart (like for zooming) and a gesture where two fingers are moved together without changing the distance between them (like for scrolling the screen)
Thanks,

 - [X] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
Some software like Krita requieres zoom and scrolling, and to distinguish them (otherwise it randomly do both of them)

**Describe the solution you'd like**
a set of keys (like ctrl, ctrl+alt, or a letter if necessary) to distinguish them

**Describe alternatives you've considered**
N/A

**Comment by rom1v** [comment]
Scrcpy injects fingers touch events to the device, how it reacts is handled by Android.

**Comment by Hubert21** [comment]
thanks for you answer ; maybe if there was a way to inject positions of the the fingers movement so that the distance between them does not change ;
if it might help, this project seams to handle multi-touch https://github.com/openstf/minitouch

**Comment by rom1v** [comment]
Btw, did you read https://github.com/Genymobile/scrcpy/blob/master/doc/control.md#pinch-to-zoom-rotate-and-tilt-simulation ?

**Comment by Hubert21** [comment]
Thanks for the link. Indeed I do use the ctrl+click feature. Actually as with ctrl we do have the zoom/rotate, I think what is missing for me is the 2 fingers swipe

**Comment by rom1v** [comment]
> I think what is missing for me is the 2 fingers swipe

Vertically or horizontally?

Vertically, you can use Shift+click.

**Comment by Hubert21** [comment]
Thanks for pointing that out, I did not really understand that "tilt" was équivalent to a vertical 2 fingers swipe ; However on my device (samsung s10 and scrcpy 1.12.1+ds-1 on ubuntu) Shift+click does not seam to do anything.
As a side note, even if I have the version 1.12.1+ds-1 installed, scrcpy -v tells me it's version 1.24 (which introduced the tilt feature)

sudo apt install --only-upgrade scrcpy
=> scrcpy is already the newest version (1.12.1+ds-1).

scrcpy -v
=> scrcpy 1.24 <https://github.com/Genymobile/scrcpy>

Dependencies (compiled / linked):
 - SDL: 2.0.10 / 2.0.10
 - libavcodec: 58.54.100 / 58.54.100
 - libavformat: 58.29.100 / 58.29.100
 - libavutil: 56.31.100 / 56.31.100
 - libavdevice: 58.8.100 / 58.8.100
 - libusb: - / 1.0.23

**Comment by Hubert21** [comment]
Thanks! shift+click now works. 
My request is now limited to adding a horizontal tilt/scroll in addition to the vertical one with the Shift key. 
I succeeded doing so with the ctrl+alt combination:
    bool alt_pressed = keymod & KMOD_ALT;
    ...
            im->vfinger_invert_x = ( ctrl_pressed && !alt_pressed ) || shift_pressed;
            im->vfinger_invert_y = ctrl_pressed || alt_pressed;

I also tried several other methods that didn't work:
1. with the meta key
    bool gui_pressed = keymod & KMOD_GUI;
    ...
            im->vfinger_invert_x = ctrl_pressed || shift_pressed;
            im->vfinger_invert_y = ctrl_pressed || gui_pressed;
            
2. with ctrl+shift 
            im->vfinger_invert_x = (ctrl_pressed && !shift_pressed) || ( !ctrl_pressed && shift_pressed );
            im->vfinger_invert_y = ctrl_pressed;

**Comment by rom1v** [comment]
> My request is now limited to adding a horizontal tilt/scroll in addition to the vertical one with the Shift key.

https://github.com/Genymobile/scrcpy/pull/4529#issuecomment-1855397118

**Comment by Hubert21** [comment]
Thanks to your help and my hack, this is done!
If ctrl+alt+click is not planned to be used anywhere else, maybe my changes could be commited

**Comment by Hubert21** [comment]
I am using a drawing app on my phone (Krita or Simple Draw), for making schemas, take notes, grow ideas.
For all apps the phone is easier to use with scrcpy especially when using the computer for other things at the same time. It's easier for these drawing apps also.

**Comment by rom1v** [comment]
To add <kbd>Ctrl</kbd>+<kbd>Shift</kbd> for horizontal tilt, I think this is sufficient:

```diff
diff --git a/app/src/input_manager.c b/app/src/input_manager.c
index 3c7022b0f..879a9df3a 100644
--- a/app/src/input_manager.c
+++ b/app/src/input_manager.c
@@ -794,7 +794,7 @@ sc_input_manager_process_mouse_button(struct sc_input_manager *im,
     }
 
     bool change_vfinger = event->button == SDL_BUTTON_LEFT &&
-            ((down && !im->vfinger_down && (ctrl_pressed ^ shift_pressed)) ||
+            ((down && !im->vfinger_down && (ctrl_pressed || shift_pressed)) ||
              (!down && im->vfinger_down));
     bool use_finger = im->vfinger_down || change_vfinger;
 
@@ -835,7 +835,7 @@ sc_input_manager_process_mouse_button(struct sc_input_manager *im,
             sc_screen_convert_window_to_frame_coords(im->screen, event->x,
                                                                  event->y);
         if (down) {
-            im->vfinger_invert_x = ctrl_pressed || shift_pressed;
+            im->vfinger_invert_x = ctrl_pressed ^ shift_pressed;
             im->vfinger_invert_y = ctrl_pressed;
         }
         struct sc_point vfinger = inverse_point(mouse, im->screen->frame_size,
```

Could you confirm, please?

**Comment by rom1v** [comment]
Please review/test 7a9ea5c66fedbb5b3b1d02f51695aa4ab259dfe3.

**Comment by Hubert21** [comment]
That works perfectly, thanks :)

**Comment by unique-EJ** [comment]
> Merged into `dev` 🚀

@rom1v @Hubert21 👋 why is this in `dev` branch and not the `master`?
Please bring that over, with Ctrl+Shift for horizontal tilt referred to in the file `/doc/shortcuts.md`

... and sometimes vertical tilt does zoom, why is that? 🤔

**Comment by rom1v** [comment]
> 👋 why is this in dev branch and not the master?

Because it has been merged after the latest release. It will be in the next one:
https://github.com/Genymobile/scrcpy/blob/master/doc/build.md#branches

**Comment by unique-EJ** [comment]
@rom1v how is tilt not to 2 finger (laptop) touchpad scroll?
and I am using _scrcpy_ (2.7) now! Android 14 through my laptop.

**Comment by ballo** [comment]
> > how is tilt not 2 finger (laptop) touchpad scroll?
> 
> Scrcpy sends 2 fingers at the specified location to Android. The Android system reacts as it wants.

I see zero evidence of this using version 3.1 on MacOS. Do I need to enable this somehow?

**Comment by rom1v** [comment]
> I see zero evidence of this using version 3.1 on MacOS. Do I need to enable this somehow?

Enable pointer location on Android, you will see mouse click/move injection.

https://github.com/Genymobile/scrcpy/blob/master/doc/control.md#pinch-to-zoom-rotate-and-tilt-simulation

**Comment by ballo** [comment]
I searched for point and there were zero results

-------- Original Message --------

**Comment by ballo** [comment]
> > I see zero evidence of this using version 3.1 on MacOS. Do I need to enable this somehow?
> 
> Enable pointer location on Android, you will see mouse click/move injection.
> 
> https://github.com/Genymobile/scrcpy/blob/master/doc/control.md#pinch-to-zoom-rotate-and-tilt-simulation

Unless you're referring to the terrible ctrl-click gesture I don't see anything there
