### ISSUE TITLE
scrcy closes itself after I open Android Studio.

### ISSUE THREAD

**Issue by bimsina** [Genymobile/scrcpy#532]
scrcpy works fine until I open Android Studio (or VS code to develop apps in flutter). and when i try to run `adb devices` while Android Studio is still running i get:
```
List of devices attached
adb server version (41) doesn't match this client (40); killing...
could not read ok from ADB Server
* failed to start daemon
error: cannot connect to daemon
```
and when i run `scrcpy` I get:
```
adb server version (41) doesn't match this client (40); killing...
could not read ok from ADB Server
* failed to start daemon
adb: error: failed to get feature set: cannot connect to daemon
ERROR: "adb push" returned with value 1
Press any key to continue...
```
Vysor works completely fine even when Android Studio is running.

**Comment by rom1v** [comment]
It's because you use two different `adb` for scrcpy and Android Studio.

See https://github.com/Genymobile/scrcpy/issues/527.

**Comment by bimsina** [comment]
@rom1v  How do I find where my adb 41 binary is?

**Comment by rom1v** [comment]
The one used by Android Studio is in `$ANDROID_SDK/platform-tools/adb` (replace `$ANDROID_SDK` by the path where you installed the Android SDK).

**Comment by bimsina** [comment]
I had installed `scrcpy` from the snap store but now I built it manually and now it's working flawlessly.
Thanks!

**Comment by rom1v** [comment]
notify @sisco311
