### ISSUE TITLE
Sometimes, the OTG keyboard doesn't function properly; only the spacebar works.

### ISSUE THREAD

**Issue by jacob-nnc** [Genymobile/scrcpy#5323]
## Environment

 - **OS:** windows
 - **Scrcpy version:**  2.7
 - **Installation method:** Windows zip
 - **Device model:** 11th Gen Intel(R) Core(TM) i5-11300H @ 3.10GHz   3.11 GHz
 - **Android version:** 14

## Describe the bug

Use the following command to control your phone: 
```
.\scrcpy.exe --otg --mouse=disabled. 
```
The spacebar works normally, but other keys like letters and numbers don't seem to function. It's not happening every time, but most of the time it doesn't work properly.
no error, just no response. just like i dont press that key.
```
INFO: Killing adb server (if any)...
INFO: USB device found:
INFO:         198A38603837       (046d:c084)  Logitech G102 Prodigy Gaming Mouse
INFO:     --> 10ADAK2XMH000Y2    (2d95:6003)  vivo iQOO Z8
INFO:         0000               (13d3:5419)  Azurewave Integrated Camera
WARN: On this platform, libusb does not have hotplug capability; device disconnection will not be detected properly
```

**Comment by rom1v** [comment]
Run `scrcpt --otg -Vverbose`. If you press another key and it does not work, what is the content in the console?

Can you reproduce with AOA in normal mode (not OGG mode):
```
scrcpy --no-video --no-audio --keyboard=aoa --mouse=disabled
```

And with UHID:
```
scrcpy --no-video --no-audio --keyboard=uhid --mouse=disabled
```

It the problem specific to this device?

Can yoj reproduce with a real physical keyboard connected directly to the device?

**Comment by jacob-nnc** [comment]
I'm sorry, it's my fault. Actually, after connecting the OTG, the default input method was Chinese, which caused the key events to not work. After switching the input method by pressing Shift, the problem was solved. I sincerely apologize for taking up your time.
