### ISSUE TITLE
Any chance to access remote smartphone (via USB cable or Wifi) outside of current Wifi/LAN?

### ISSUE THREAD

**Issue by pstein** [Genymobile/scrcpy#5324]
Ok, I can access from my Windows Desktop computer my Android Smartphone via USB Cable or Wifi when the smartphone belongs to the same local Wifi network.

It works.

But is there any chance to do this when the smartphone is in a completely different LAN/Wifi network?

**Comment by rom1v** [comment]
Remote access it out of scope.

But you can still use SSH tunnels, it works in practice: https://github.com/Genymobile/scrcpy/blob/master/doc/tunnels.md#ssh-tunnel

**Comment by pstein** [comment]
ok, thank you
