### ISSUE TITLE
[Feature request] Pre-Compiled versions for systems other then Windows

### ISSUE THREAD

**Issue by mdziczkowski** [Genymobile/scrcpy#5327]
Hello. I would like to request inclusion of pre-compiled version of scrcpy for systems other then Windows, that the product would be in form of "out-of-the-box" to allow people who don't know how to program (or compile sources) could use it as well

**Comment by rom1v** [comment]
See #5306.

**Comment by mdziczkowski** [comment]
> See #5306.

It partially references to my request, because:

- there are several formats of debian packages (deb is only one of them)

- there are missing also pre-compiled version distributed not only as executables, installers or packages, but also in form of an extractable archive containing everything needed
