### ISSUE TITLE
Can't switch encoder, invalid server param

### ISSUE THREAD

**Issue by ptcee** [Genymobile/scrcpy#5329]
When trying to run scrcpy with --video-encoder='any encoder that isnt the one i'm defaulted to from --list-encoders I get ERROR: Invalid server param: ['c2.android.avc.encoder'] and ERROR: Server connection failed

Any idea how to fix this? It happens with every encoder I try.

**Comment by rom1v** [comment]
On Windows, try removing the `'`: `--video-enxoder=c2.android.avc.encoder`.

**Comment by rom1v** [comment]
Suggestions from `--list-encoders` fixed by ec602a0334357982d75b374f7ac753c5bef1216a.
