### ISSUE TITLE
PyADB instead of ADB. Possible workaround?

### ISSUE THREAD

**Issue by Plandercozeron** [Genymobile/scrcpy#533]
I'm using Ubuntu 18.10. ADB version 1.0.39.
May i use scrcpy in pair with PyADB instead of ADB?

The thing is ADB on my Ubuntu has bug or something
`adb devices` shows only 7 connected devices instead of 8 or more (ADB on windows works fine)
`pyadb devices` lists all devices properly.
First you push server.jar
Then what?

Thanks in advance

**Comment by npes87184** [comment]
Hi, @rom1v 

I have seen many problems about the protocol and the initialization and the protocol.

May we need to add some more developer guide in [DEVELOP.md](https://github.com/Genymobile/scrcpy/blob/master/DEVELOP.md)?

**Comment by rom1v** [comment]
> `adb devices` shows only 7 connected devices instead of 8 or more (ADB on windows works fine)
> `pyadb devices` lists all devices properly.

This is weird, since `pyadb` is just a wrapper which calls `adb`:
https://github.com/sch3m4/pyadb/blob/8f536c915c315eb9c4cc44088f5c067e68b02e3a/pyadb/adb.py#L108

**Comment by Plandercozeron** [comment]
I see. I tried both adb from /usr/bin (version 39) and adb from android studio from sdk/platfrom-tools/adb (version 41) - show max 7 devices. Probably the problem is within ubuntu itself.
Better ask in PyADB thread then

**Comment by Plandercozeron** [comment]
Made an issue at PyADB repo:
https://github.com/sch3m4/pyadb/issues/16
Not sure if i gonna get any answers and it seems repo is dead. Since PyADB really is a wrapper to ADB it's better to ask PyADB devs.
I guess you can close that issue then

**Comment by Plandercozeron** [comment]
Nevermind. Not even close to ADB or PyADB
Seems like linux kernel bug which is connected to **xhci_hcd** driver
`dmesg` gives me:
_Not enough host controller resources for new device state.
can't set config #1, error -12_

**Comment by Plandercozeron** [comment]
Resolved this case by overriding xHCI with EHCI
Disable xHCI
```
lspci -nn | grep USB \
| cut -d '[' -f3 | cut -d ']' -f1 \
| xargs -I@ setpci -H1 -d @ d0.l=0
```

Undo (d0.l=1):
```
lspci -nn | grep USB \
| cut -d '[' -f3 | cut -d ']' -f1 \
| xargs -I@ setpci -H1 -d @ d0.l=1
```

Now i can use my 20-port hub by 100% =)
