### ISSUE TITLE
Audio duplicate worked once and never again

### ISSUE THREAD

**Issue by Shuatome** [Genymobile/scrcpy#5330]
So Audio duplicate worked once when I was fiddling Scrcpy. But the time I tried to recreate it, nothing happed.
I deleted and install the latest Scrcpy(-win64-v2.7) nothing change.

**Comment by rom1v** [comment]
What's the full output in the console?

**Comment by Shuatome** [comment]
@rom1v Hello, I don't now how to check the output.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/doc/windows.md#run

**Comment by rom1v** [comment]
No, please post the whole console output (not just a random line). Also include the command line you execute.

> But the time I tried to recreate it, nothing happed.

What happens when you play audio from the device while scrcpy is running with audio duplicate?

**Comment by Shuatome** [comment]
C:\Users\Shua_me\Desktop\scrcpy-win64-v2.7>scrcpy --audio-source=playback
scrcpy 2.7 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     --> (tcpip)  192.168.1.6:5555                device  ASUS_AI2401_D
C:\Users\Shua_me\Desktop\scrcpy-win64-v2.7\scrcpy-server: 1 file pushed, 0 skipped. 46.6 MB/s (71200 bytes in 0.001s)
[server] INFO: Device: [asus] asus ASUS_AI2401_D (Android 14)
INFO: Renderer: direct3d
INFO: Texture: 2400x1080
Is this it?

**Comment by rom1v** [comment]
Yes, that's it.

> scrcpy --audio-source=playback

Here, you selected the "playback" audio source, but you did not requested to duplicate audio.

Run:

```
scrcpy --audio-dup
# or explicitly: scrcpy --audio-source=playback --audio-dup 
```

https://github.com/Genymobile/scrcpy/blob/master/doc/audio.md#duplication

**Comment by Shuatome** [comment]
Thank you.
