### ISSUE TITLE
Recording not working?

### ISSUE THREAD

**Issue by Mindputty** [Genymobile/scrcpy#5333]
Are there any known issues with using scrcpy in python scripts, specifically in how subprocess.Popen() has trouble with recording to file? I can record from command line, but when I try from within my script, the behaviour is unpredictable, recording only about 1% of the time, with the other 99% of the time being either 0 KB, 1KB, some variable number of KB, but always corrupt. I have tried python's terminate(), kill(), as well as process.send_signal(signal.CTRL_C_EVENT), all in conjunction with combinations of join() and wait() to ensure the process is completed. I have also used both processes and process groups, and threading. Has anyone else run into this issue, and if you solved it, how?

**Comment by rom1v** [comment]
#5195

**Comment by Mindputty** [comment]
@rom1v Thank you for the quick reply! I tried os.kill(pid, signal.SIGINT), but that isn't working. When using os.kill(pid, signal.CTRL_C_EVENT), it hangs indefinitely because I'm using join(). 

The strange thing is, although my script is supposed to open and close (and save) recordings 6 times during its execution, they all stay open. When the script terminates, they are all closed at that point and are saved correctly (!). Could it be that the script is cleaning up in a way that any individual call for close/terminate/kill is not doing properly? What signal does scrcpy need to terminate gracefully?

**Comment by Mindputty** [comment]
There seems to be an issue in ffmpeg driver that isn't working well (returns non-zero code). If having issues, try to switch to using a different format, such as mkv. Also, using thread or process termination through any non-windowed closing doesn't seem to work to save the recording gracefully. Instead, use python modules win32gui and win32con, find the name of the window using win32gui.FindWindow(), and then close the window using win32gui.PostMessage(windowName, win32con.WM_CLOSE, 0, 0)
