### ISSUE TITLE
Camera Streaming Camera Controls Possible?

### ISSUE THREAD

**Issue by serifpersia** [Genymobile/scrcpy#5336]
Would like to have GUI  application probably java based on pc that can control focus, exposure and all other camera parameters with adb scrcpy commands?

Currently I'm using camera streaming android 12 with no audio and it constantly does auto focus and it would be nice to have control over focus exposure levels shutter and so on.  Controls over the camera options would help.

How hard would this be to have access to camera controls? Does scrcpy already have something in place for this?

**Comment by rom1v** [comment]
> Would like to have GUI application probably java based

In general, a GUI (in Qt or something) for having widgets would be great. But that's too much work to develop/maintain. So it will remain in SDL with shortcuts for actions.

Probably not Java-based anyway (Swing?).

For camera options, see discussions in #4452.

**Comment by serifpersia** [comment]
> > Would like to have GUI application probably java based
> 
> In general, a GUI (in Qt or something) for having widgets would be great. But that's too much work to develop/maintain. So it will remain in SDL with shortcuts for actions.
> 
> Probably not Java-based anyway (Swing?).
> 
> For camera options, see discussions in #4452.

Yes I want to create GUI app for this but I need to know about access to camera controls that scrcpy might have. I will read that for sure. Thanks
