### ISSUE TITLE
In 1:1 pixel perfect I can only see the top of the phone

### ISSUE THREAD

**Issue by bsde1245** [Genymobile/scrcpy#534]
In 1:1 pixel perfect I can only see the top of the phone. How to see the remaining bottom portion which goes beyond the bottom portion of the screen?

**Comment by rom1v** [comment]
On some window manager, you can move your window above the screen (Ctrl+click & move). Otherwise (probably on Windows), I guess you can't.

This feature just resizes the window to the content, nothing more.

**Comment by justinechacko** [comment]
Thanks. Any way to increase width and height of the screen manually to a little bit?

**Comment by rom1v** [comment]
(I'm not sure to understand your last question) Just resize the window with your mouse (some window manager also provide Alt+RightClick).
