### ISSUE TITLE
AOA keyboard and mouse throught USB and adb debugging throught TCP/IP

### ISSUE THREAD

**Issue by baco81** [Genymobile/scrcpy#5343]
## Environment

- **Operating System (OS):** Windows 10
- **Scrcpy Version:** 2.7
- **Installation Method:** manual
- **Device Model:** Samsung Galaxy Tab A9+
- **Android Version:** 14

## **Describe the bug**

Sorry if this is reported somewhere else, newbie here. I am trying to use scrcpy with the following prompt:

```
@echo off
scrcpy.exe --select-tcpip --keyboard=aoa --mouse=aoa --no-video --no-audio --pause-on-exit=if-error %*
```

But I get the following errors:

```
ERROR: On Windows, it is not possible to open a USB device already open by another process (like adb).
ERROR: Therefore, --keyboard=aoa and --mouse=aoa may only work in OTG mode (--otg).
```

What I am trying to achieve is to use the AOA protocol for the keyboard and mouse through USB to control the device, while maintaining ADB debugging through TCP/IP. From my limited understanding, It should be technically possible.

I have tried passing the OTG argument and it is working fine, but I need other functions as clipboard synching that would require adb debugging.

Currently, I use both Samsung Flow for clipboard syncing and scrcpy for controlling the keyboard and mouse with OTG, which achieves the desired result. 

It would be nice and more convenient though if I could just use scrcpy for clipboard synching as well, making it a single solution for both tasks.

Thank you very much for your time.

**Comment by rom1v** [comment]
What you want is probably uhid instead of AOA:

 - https://github.com/Genymobile/scrcpy/blob/master/doc/keyboard.md#uhid
 - https://github.com/Genymobile/scrcpy/blob/master/doc/mouse.md#uhid

**Comment by baco81** [comment]
Thank for your answer.
I have tried uhid, but I found it less convenient than my current setup. The reason is that with OTG I am able to "wake up" the device when its screen has gone black, but I can't if using uhid instead. That forces me to wake the device first to be able to control it with the mouse and keyboard every time. And I don't want to use the always on argument, as I don't want my device screen to be always awake.

**Comment by rom1v** [comment]
> The reason is that with OTG I am able to "wake up" the device when its screen has gone black, but I can't if using uhid instead

On Android, it is true that AOA wakes up the device when moving the mouse.

But scrcpy supports waking up the device with right-click or Shift+right-click: https://github.com/Genymobile/scrcpy/blob/master/doc/mouse.md#mouse-bindings

**Comment by baco81** [comment]
> But scrcpy supports waking up the device with right-click or Shift+right-click in any case: https://github.com/Genymobile/scrcpy/blob/master/doc/mouse.md#mouse-bindings

I didn't know that. I have tried it and, while I still find more "natural" to wake up the device just moving the mouse, it works good enough. Thank you very much!!

As per my original request, I have tried running two scrcpy instances, one with aoa for the keyboard and mouse through USB and another one for ADB debugging through TCP/IP but for some reason I can't it get to work (at least, in Windows).

Anyway, I think this "issue" can be closed as I can just use shift+right-click while in uihd mode as suggested. Thank you again for your time.

**Comment by rom1v** [comment]
> As per my original request, I have tried running two scrcpy instances, one with aoa for the keyboard and mouse through USB and another one for ADB debugging through TCP/IP but for some reason I can't it get to work (at least, on Windows).

Refs #4028 #4032 #4035
