### ISSUE TITLE
adb Debugging using the doc does not work for me

### ISSUE THREAD

**Issue by Gottox** [Genymobile/scrcpy#5346]
## Environment

 - **OS:** linux
 - **Scrcpy version:** master
 - **Installation method:** manual / `./run` script
 - **Device model:** Pixel 6a
 - **Android version:** GrapheneOS 14

## Describe the bug

When I try to run scrcpy in [debugging mode](https://github.com/Genymobile/scrcpy/blob/master/doc/develop.md#debug-the-server), I get the following output, without giving me the opportunity attach the debugger:

```
./run build -s xxxxxxxxxxxxxx
scrcpy 2.7 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  xxxxxxxxxxxxxx                  device  Pixel_6a
DEBUG: Device serial: xxxxxxxxxxxxxx
DEBUG: Using SCRCPY_SERVER_PATH: build/server/scrcpy-server
build/server/scrcpy-server: 1 file pushed, 0 skipped. 139.8 MB/s (170166 bytes in 0.001s)
INFO: Server debugger waiting for a client on device port 5005...
DEBUG: Interrupting socket
DEBUG: Server disconnected
DEBUG: Server terminated
ERROR: Server connection failed
```

Am I doing something wrong here?

**Comment by rom1v** [comment]
I think the "API" to debug has changed again on new Android versions. To be fixed:

https://github.com/Genymobile/scrcpy/blob/665ccb32f5306ebd866dc0d99f4d08ed2aeb91c3/app/src/server.c#L253

(but I don't know what needs to be changed)

**Comment by Gottox** [comment]
maybe related: #2722

**Comment by Gottox** [comment]
maybe related:
* https://stackoverflow.com/questions/54550668/cannot-debug-app-when-using-wrapper-script
* https://developer.android.com/ndk/guides/wrap-script#packaging_wrapsh

**Comment by Gottox** [comment]
I didn't get any meaningful output from running adb shell manually too... :/

```
~/src/scrcpy (feature/mpris ✗) adb -s xxxxxxxxxxxxxx shell 'CLASSPATH=/data/local/tmp/scrcpy-server.jar' app_process '-XjdwpProvider:internal -XjdwpOptions:transport=dt_socket,suspend=y,server=y,address=5005' / com.genymobile.scrcpy.Server 2.7 'scid=xxxxxxxx' 'log_level=debug'

~/src/scrcpy (feature/mpris ✗) echo $?
1
```

**Comment by Gottox** [comment]
So at least we know that it has been broken since 2020. I have yet no idea on how to fix it... :/ https://android.googlesource.com/platform/art/+/fc58809f7b932d86234130be15487017dc37b0cf%5E!/#F3
