### ISSUE TITLE
GPG signing key for  SHA256SUMS.txt expired in March, 2024

### ISSUE THREAD

**Issue by leftdisconnected** [Genymobile/scrcpy#5350]
Though somewhat difficult for me to find, the [GPG key](https://blog.rom1v.com/about/) for the SUMS file expired earlier this year.  While the primary key has no expiration set, the subkeys all have expirations of 2024-03-14, which was 3 years from original creation.

My apologies if an updated key is available from a source that I'm unaware of, but the key available at the link above and from keyserver.ubuntu.com are unchanged.

I appreciate the effort it takes to manage keys and sign releases and recognize that almost no one actually checks them - just weirdos like me - but _if_ the signatures are being produced then the signing key will require routine expiration updates and should probably be linked to from some About or FAQ section.

Once expired, there's little reason to continue signing as verification fails even though the signature otherwise checks out.  We should indeed distribute the keys from a different domain than the signatures, but users may need help in finding those keys.

Thanks for all that you do.

**Comment by rom1v** [comment]
Hi,

The expiration date has been updated on 2024-05-15, and was published to openpgp.org: https://keys.openpgp.org/search?q=456958E85A185DD5C2D1E4E80C822B298461FA03

```bash
curl https://keys.openpgp.org/vks/v1/by-fingerprint/456958E85A185DD5C2D1E4E80C822B298461FA03 | gpg --show-key --with-subkey-fingerprint
```

Indeed, I did not update my about page (now [it's done](https://blog.rom1v.com/about/)). Thank you for the reminder :wink:

And I also updated on `keyserver.ubuntu.com`: https://keyserver.ubuntu.com/pks/lookup?search=456958E85A185DD5C2D1E4E80C822B298461FA03&fingerprint=on&op=index

**Comment by leftdisconnected** [comment]
My apologies as my keyserver didn't have the update.  Thank you and I will yet again change my keyserver ;).
