### ISSUE TITLE
Call audio not routed

### ISSUE THREAD

**Issue by a-singer** [Genymobile/scrcpy#5351]
_Please read the [prerequisites] to run scrcpy._

[prerequisites]: https://github.com/Genymobile/scrcpy#prerequisites

_Also read the [FAQ] and check if your [issue][issues] already exists._

[FAQ]: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md
[issues]: https://github.com/Genymobile/scrcpy/issues

## Environment

 - **OS:** Windows 10
 - **Scrcpy version:** 2.7
 - **Installation method:** Windows release
 - **Device model:** Kapsys Smartvision 3
 - **Android version:** 11

## Describe the bug

Hi, Sorry if this is glaringly obvious but I can't find what to search for and it's certainly not in the FAQ. The closest I can see is 4491, where phone audio makes all audio stop, and that's not happening here. Everything is working, but on my Android 11 device, the audio from the phone is not being sent to the PC. All the other audio I've tested is being sent, it's just the phone which is the only app I have tried where the audio insists on being piped to the device's headphones, not the PC. Is this expected and, if not, is there a way to solve it? Note that I cannot use the playback source, as this is Android 11. If I may ask, would the playback source be useful here?

**Comment by rom1v** [comment]
Audio call cannot be captured programmatically AFAIK (only via bluetooth probably).
