### ISSUE TITLE
Keyboard method of pushing file or installing APK?

### ISSUE THREAD

**Issue by a-singer** [Genymobile/scrcpy#5352]
Hi, I'm totally blind and am not really good at dragging and dropping. If I may ask, is there a method to push a file, or install an APK, through the keyboard? On the shortcuts page, I do see a link to the push function, for example, but no shortcut key. I may well be missing something, so would be most grateful for a pointer.

**Comment by rom1v** [comment]
> is there a method to push a file, or install an APK, through the keyboard?

No, there isn't. You can open a terminal and execute `adb push myfile.txt /sdcard/` (that's basically what scrcpy does).

**Comment by a-singer** [comment]
Would it be possible to have a keyboard command to do this, if I may ask? It's not vital, as you say, it can be done by ADB, but it would be nice to have so it can be done from within the mirror.

**Comment by rom1v** [comment]
No, there is no widget in SDL (the framework used by scrcpy) to enter the file path (or select a file) anyway.

**Comment by a-singer** [comment]
Thanks very much for the quick and thorough response, I really do appreciate the speed and, needless to say, the accessibility of the entire project and mirroring (it's not so much one accessible system as the only accessible system I've found of mirroring both audio and input).
