### ISSUE TITLE
WARNING: linker: Warning: "/apex/com.android.conscrypt/lib64/libc++.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)

### ISSUE THREAD

**Issue by rahaaatul** [Genymobile/scrcpy#5353]
## Environment

 - **OS:** Windows
 - **Scrcpy version:** 2.7
 - **Installation method:** Scoop
 - **Device model:** Vivo v2043
 - **Android version:** 11

## The bug

```powershell
pwsh> scrcpy
scrcpy 2.7 <https://github.com/Genymobile/scrcpy>
C:\Users\RGX\scoop\apps\scrcpy\current\scrcpy-server: 1 file pushed, 0 skipped. 30.1 MB/s (71200 bytes in 0.002s)
[server] INFO: Device: [vivo] vivo V2043 (Android 11)
INFO: Renderer: direct3d
INFO: Texture: 720x1600
WARNING: linker: Warning: "/apex/com.android.conscrypt/lib64/libc++.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)
```

Also, if I use `--no-video-playback` I get something like this:
![image](https://github.com/user-attachments/assets/cec2920d-4967-40d3-80cd-792083024762)
and a mouse appears in my phone and controllable for no reason. This did not happen when I use using package from winget.

**Comment by rom1v** [comment]
> WARNING: linker: Warning: "/apex/com.android.conscrypt/lib64/libc++.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)

That's a warning from your phone (probably when you execute anything with `app_process`), not related to scrcpy a priori.

> Also, if I use `--no-video-playback` I get something like this:
> …
> and a mouse appears in my phone and controllable for no reason.

Yes, that's the expected behavior. By default, video, audio and control are enabled. If you disable "video playback" (which will also completely disable video in your case), then it remains audio and control.

Read the highlights of the 2.5 release for explanations (and how to get the behavior you want): https://github.com/Genymobile/scrcpy/releases/tag/v2.5

> This did not happen when I use using package from winget.

Because it was an older version.

**Comment by rahaaatul** [comment]
Thanks for replying. I didn't check the new features, I thought everything was as usual (because I updated with scoop and no change logs was provided).

> That's a warning from your phone (probably when you execute anything with app_process), not related to scrcpy a priori.

But I didn't get this warning before in previous versions (winget)? Should I try using previous versions with scoop?

**Comment by rom1v** [comment]
You can try with older versions, yes (you can use the old official releases, they're still available).

**Comment by rahaaatul** [comment]
I just tried previous versions and getting the same error.

> That's a warning from your phone (probably when you execute anything with `app_process`).

Can you give an example what you mean by that? My foreground app is Instagram and even though I close that and go to home screen, I still get that warning.

Also `winget` is providing `v2.4` as the latest version.

**Comment by rom1v** [comment]
> Also `winget` is providing v2.4 as the latest version.

Packages on winget or others are maintained by third-party developers.

Anyway, the winget package has issues: #4027 #4389 #4956.
It is not suggested anymore in the documentation: c27ab46efbcab0b9558a91e691d799ffef496c97

> Can you give an example what you mean by that?

Scrcpy executes `adb shell app_process …` to run a Java "executable" on Android. Your vendor (vivo) applies internal changes to AOSP, and that may cause some warnings or issues (there are a lot with vivo phones), whether they are related to scrcpy or not.

**Comment by rahaaatul** [comment]
Thank you. Appreciate the help.
