### ISSUE TITLE
Is there a way to launch Scrcpy (or Scrcpy cmd) with a prefilled command?

### ISSUE THREAD

**Issue by JxhanPatel** [Genymobile/scrcpy#5358]
I use Scrcpy on Windows 11 with 2 devices connected over USB (sometimes simultaneously), If both devices are connected at the same time, Scrcpy app does not directly launch, I have to Open Cmd then select using `scrcpy -s xxxxxxxxxxxx` for each the device
so is there a way to have these commands pre-written? (and better if accessible via shortcut).
Phone 1 = Android 13 
Phone 2 = Android 9

**Comment by rom1v** [comment]
Yes, read the end of https://github.com/Genymobile/scrcpy/blob/master/doc/windows.md#run

**Comment by JxhanPatel** [comment]
Hey Man! Thanks for the reply! It was very useful.
Just another thing, I have created two .bat file for each device, is it possible to get the same function as .vbs (no console) file for the same?
Also a bit out of context but is there anyway i can in these files in my start menu?

Thanks.

**Comment by JxhanPatel** [comment]
> Hey Man! Thanks for the reply! It was very useful. Just another thing, I have created two .bat file for each device, is it possible to get the same function as .vbs (no console) file for the same? Also a bit out of context but is there anyway i can Pin these files in my start menu?
> 
> Thanks.


I figured it out!
I created a new .vbs file and these are the edits i did:
```
strCommand = "_cmd /c scrcpy -s xxxxxxxxx --turn-screen-off --stay-awake_"

For Each Arg In WScript.Arguments
    strCommand = strCommand & " """ & replace(Arg, """", """""""""") & """"
Next

CreateObject("Wscript.Shell").Run strCommand, 0, false
```

Shared if someone else needs it.
(it opens Scrcpy without console with any custom command)
