### ISSUE TITLE
[Discussion] Questions About Issue #87

### ISSUE THREAD

**Issue by MrTeeXD** [Genymobile/scrcpy#536]
So i took the time to read through the whole of issue #87 and from my understanding, the ability to use the mouse and keyboard in a shooter game on mobile is not implemented yet ?

**Comment by rom1v** [comment]
The keyboard should work, isn't it?

The mouse events are forwarded (when you click for example), but currently it is not possible to "capture" the mouse, and you need this to play FPS games (#269).

**Comment by MrTeeXD** [comment]
I have tried to test this but when executing the instructions on issue #87 it does not seem to work like a bluetooth mouse and keyboard should work

**Comment by MrTeeXD** [comment]
Yes but when i launch a game to supports mouse and keyboard, it does not, i have tried to execuite ```".\scrcpy --raw-key-events"``` , it says : ```"unknown option -- raw-key-events"```

**Comment by rom1v** [comment]
`--raw-key-events` was an experiment implemented on a separate branch: https://github.com/Genymobile/scrcpy/tree/rawkeyevents

But it should work correctly without that option now, isn't it?

**Comment by MrTeeXD** [comment]
Nope, i executed that in Powershell and it printed out that message

**Comment by rom1v** [comment]
Which message?

Do not pass `--raw-key-events`, it does not exist.

**Comment by MrTeeXD** [comment]
The message that says ```unknown event``` , i have tried Ctrl + G and it gives the same results

**Comment by rom1v** [comment]
> it printed out that message

> The message that says `unknown event`

You never posted that message.

Could you copy exactly the output you get?

**Comment by MrTeeXD** [comment]
Alright, when executing the --raw-key-event ?

**Comment by rom1v** [comment]
> when executing the --raw-key-event ?

https://github.com/Genymobile/scrcpy/issues/536#issuecomment-493094151

> Do not pass `--raw-key-events`, it does not exist.

**Comment by MrTeeXD** [comment]
Do you mean the Ctrl + G thing?

**Comment by rom1v** [comment]
> the ability to use the mouse and keyboard in a shooter game on mobile

Oh, it's probably #269.
