### ISSUE TITLE
Add h264_cuvid decoding

### ISSUE THREAD

**Issue by wode2016501** [Genymobile/scrcpy#5364]
尝试添加
demuxer.c: 
// const AVCodec *codec = avcodec_find_decoder(codec_id);
 const AVCodec *codec = 0;
  if(codec_id==AV_CODEC_ID_H264)
		    codec=avcodec_find_decoder_by_name("h264_cuvid");
	    else
		    codec=avcodec_find_decoder(codec_id);
log:
wode@ubuntu:/media/wode/0e449915-b15f-4add-bf32-647e92a1d144/ubuntu-arm64/src/scrcpy-2.6.1/build$ ninja ;app/scrcpy  '--no-audio'    '--no-control'
[2/2] Linking target app/scrcpy
scrcpy 2.6.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  vc6hnnmjb6k74pmr                device  M2004J7AC
DEBUG: Device serial: vc6hnnmjb6k74pmr
DEBUG: Using server: /usr/local/share/scrcpy/scrcpy-server
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 20.2 MB/s (78413 bytes in 0.004s)
[server] INFO: Device: [Xiaomi] Redmi M2004J7AC (Android 10)
DEBUG: Server connected
DEBUG: Using icon: /usr/local/share/icons/hicolor/256x256/apps/scrcpy.png
[server] DEBUG: Using video encoder: 'OMX.MTK.VIDEO.ENCODER.AVC'
[server] DEBUG: Display: using SurfaceControl API
INFO: Renderer: opengl
INFO: OpenGL version: 4.6.0 NVIDIA 535.183.01
INFO: Trilinear filtering enabled
DEBUG: Demuxer 'video': starting thread
WARN: [FFmpeg] Invalid pkt_timebase, passing timestamps as-is.
scrcpy: ../app/src/screen.c:297: sc_screen_frame_sink_open: Assertion `ctx->pix_fmt == AV_PIX_FMT_YUV420P' failed.
已中止 (核心已转储)
wode@ubuntu:/media/wode/0e449915-b15f-4add-bf32-647e92a1d144/ubuntu-arm64/src/scrcpy-2.6.1/build$ [server] DEBUG: Screen streaming stopped

**Comment by rom1v** [comment]
- #3800
 - https://github.com/libsdl-org/SDL/issues/5405
