### ISSUE TITLE
#include Error

### ISSUE THREAD

**Issue by dillonfrederica** [Genymobile/scrcpy#5372]
https://github.com/Genymobile/scrcpy/blob/c15df01171793dca7074a012f4703a185d99169d/app/src/events.h#L8

Cannot find `SDL_events.h`

Change `SDL_events.h` To `SDL2/SDL_events.h`

**Comment by rom1v** [comment]
Thank you, rebased and merged on dev: 89c4f455b0f9a4ada6a6552ddc6684b0344115cd

I don't know why it works for me (i.e. why the `cc` commands executed include `-I/usr/include/SDL2`).

What is your environment? and meson and c compiler versions?
