### ISSUE TITLE
Idea when opening multiple devices

### ISSUE THREAD

**Issue by cotfas** [Genymobile/scrcpy#538]
An ideea to use a random port opened so you don`t have to enter a new one by cli.

**Comment by cotfas** [comment]
Made a script that helps starting in random ports and passing parameter when you have more than one device connected.

Copy to /usr/local/bin/android.sh

run
android.sh 
*will take first device connected

run
android.sh [param]
*where param is the device counter, example, for first device connected use 1, for second device use 2, etc


`
#!/bin/bash


random-port() {
    while [[ not != found ]]; do
        # 2000..33500
        port=$((RANDOM + 2000))
        while [[ $port -gt 33500 ]]; do
            port=$((RANDOM + 2000))
        done

        # 2000..65001
        [[ $((RANDOM % 2)) = 0 ]] && port=$((port + 31501)) 

        # 2000..65000
        [[ $port = 65001 ]] && continue
        echo $port
        break
    done
}


 printf "Random port used = %05d\n" $(random-port) 


#List of devices attached
#9889db394248483045  device
#emulator-5554   device



#scrcpy -p $(random-port) 


adb devices > adbdevices

fileItemString=$(cat adbdevices |tr "\n" " ")
fileItemArray=($fileItemString)
Length=${#fileItemArray[@]}
echo $Length

#echo ${fileItemArray[0]}
#echo ${fileItemArray[1]}

# taking firts word
#echo "asd dd"  | head -n1 | cut -d " " -f1




parameter=$1
echo $parameter


if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
    parameter=1
fi


counter=1
for i in $(seq 4 2 $Length)
do
    var=${fileItemArray[$i]}
  
    if [ $parameter = $counter ]; then
        echo $var
        #executing
        scrcpy -p $(random-port) -s $var
    else
      echo "try again"
    fi

   counter=$((counter + 1))
done
`

**Comment by rom1v** [comment]
A mechanism had been implemented on `dev`: dc7fcf3c7a7a0e26c2447990206b798742e062c7
