### ISSUE TITLE
With Ubuntu 24.10 doesn't start

### ISSUE THREAD

**Issue by sedax90** [Genymobile/scrcpy#5380]
## Environment

 - **OS:** Ubuntu 24.10
 - **Scrcpy version:** 2.7
 - **Installation method:** deb
 - **Device model:** Samsung galaxy A51
 - **Android version:** 13

## Describe the bug
Start fail for a missing library.

```
scrcpy -Swtd
scrcpy: error while loading shared libraries: libavformat.so.60: cannot open shared object file: No such file or directory
```

**Comment by rom1v** [comment]
Your scrcpy binary was built against another version of ffmpeg that your system has.

> Installation method: deb

From where?

Uninstall your version, and follow these steps: https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md#latest-version

**Comment by sedax90** [comment]
Solved, thanks!
