### ISSUE TITLE
How to unlcok screen lock?

### ISSUE THREAD

**Issue by WaleedMortaja** [Genymobile/scrcpy#5391]
When I try to control my device, it works perfect when it is already unlocked (or does not have screen lock). However, when the screen is locked, and I try to enter the pin/pattern, all I see is a black screen.

How can I unlock the screen lock when connecting using scrcpy? Is this a privacy feature from scrcpy that can be modified?

Side question: I, of course, would appreciate not to send the pin/pattern in clear text. I did not see any mention for encryption in the codebase. However, I am not really sure. So, Is the scrcpy connection encrypted securely?

**Comment by rom1v** [comment]
Your lock screen app set the "secure flag" not to be captured. Since Android 12 this is enforced even for shell user, so scrcpy can't capture the screen.

Scrcpy uses adb, which is not encrypted.

**Comment by WaleedMortaja** [comment]
Can you provide an encryption in scrcpy itself?

**Comment by WaleedMortaja** [comment]
Would you mind opening a separate issue yourself for the encryption feature request?

**Comment by WaleedMortaja** [comment]
If anyone reach this issue, I found a two workarounds:

1. You can use the `-K` option and use your laptop keyboard to enter the PIN (related issue: GrapheneOS/os-issue-tracker#4616)
2. Unlock the phone (profile) manually for once, you can then use the `scrcpy --new-display` option when connecting to the phone to create a new virtual display instead of mirroring the phone screen. The new display does NOT ask for the PIN.

As mentioned above, neither `adb` nor `scrcpy` currently encrypt the communication, so there is a risk of the PIN being capture if you are using `adb` over Wi-Fi

**Comment by QAQDE** [comment]
Just confirmed, -K works on my GrapheneOS Android 16 for unlocking.
