### ISSUE TITLE
Screenrecord with multiple devices connected

### ISSUE THREAD

**Issue by somejet** [Genymobile/scrcpy#5392]
Hi guys! 
I have updated scrcpy to 2.7 recently (previously i had quite old version, 2.1 or so, don't remember actually).
And I can't figure out how to record screen when i have several devices connected

Previously I had automated script for this, where I used both -s <serial> key and --record. It worked perfectly fine, but now it just share screen and thats it:

```
% /usr/local/bin/scrcpy
 -s RZCT40VW82D --no-playback --no-window --record=/Applications/Screen_records/2024-10-21__10-16-05.mp4
scrcpy 2.7 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  RZCT40VW82D                     device  SM_A536B
/usr/local/Cellar/scrcpy/2.7/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 42.8 MB/s (71200 bytes in 0.002s)
[server] INFO: Device: [samsung] samsung SM-A536B (Android 14)
INFO: Renderer: metal
INFO: Texture: 1080x2400
^Z
zsh: suspended  /usr/local/bin/scrcpy
zsh: command not found: -s
```

Is it a bug or you dropped this ability intentionally?

**Comment by rom1v** [comment]
> zsh: suspended  /usr/local/bin/scrcpy zsh: command not found: -s

You have a new line between `/usr/local/bin/scrcpy` and the remaining of the command, so it executes `/usr/local/bin/scrcpy`, then `-s …`, which does not exist.

**Comment by somejet** [comment]
oh, you're absolutely right! thank you very much
