### ISSUE TITLE
Many hours to install scrcpy?

### ISSUE THREAD

**Issue by morrissey007** [Genymobile/scrcpy#5394]
Started the install of scrcpy via macports at 8:00,  at 11:30 and its still installing,  over 3 hours and still going, is this normal?  (Mac mini, M1).

**Comment by rom1v** [comment]
No, that's absolutely not normal.

The problem is that on some macOS versions, macPorts and/or brew need to recompile the whole earth to build ffmpeg and SDL. See thread https://github.com/Genymobile/scrcpy/issues/2256#issuecomment-1030029493

**Comment by morrissey007** [comment]
OK, thank you. I looked at #2256 but it isnt clear how to speed up the install.

**Comment by rom1v** [comment]
There are now static binaries.
