### ISSUE TITLE
linux support soon?

### ISSUE THREAD

**Issue by Rahumi-f** [Genymobile/scrcpy#5395]
So, I have been wondering if there will be Linux support any time soon?

**Comment by rom1v** [comment]
What do you mean? Scrcpy works on Linux.

https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md

**Comment by Rahumi-f** [comment]
when i do the ./install_release.sh it shows this error:

  [scrcpy] Downloading prebuilt server...

--2024-10-22` 17:45:51--  https://github.com/Genymobile/scrcpy/releases/download/v2.7/scrcpy-server-v2.7

Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/111583593/2c633ac2-97b4-45a3-b5f3-a6710f7e3c55?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20241022%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241022T144552Z&X-Amz-Expires=300&X-Amz-Signature=18f0c349d202969f3cf88715398d7b2413b06ebdde603b3e6a63da140fd3468c&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dscrcpy-server-v2.7&response-content-type=application%2Foctet-stream [following]
--2024-10-22 17:45:52--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/111583593/2c633ac2-97b4-45a3-b5f3-a6710f7e3c55?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20241022%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241022T144552Z&X-Amz-Expires=300&X-Amz-Signature=18f0c349d202969f3cf88715398d7b2413b06ebdde603b3e6a63da140fd3468c&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dscrcpy-server-v2.7&response-content-type=application%2Foctet-stream
Resolving objects.githubusercontent.com (objects.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.108.133, ...
Connecting to objects.githubusercontent.com (objects.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 71200 (70K) [application/octet-stream]
Saving to: ‘scrcpy-server’

scrcpy-server       100%[================>]  69.53K  --.-KB/s    in 0.1s    

2024-10-22 17:45:53 (502 KB/s) - ‘scrcpy-server’ saved [71200/71200]

[scrcpy] Verifying prebuilt server...
scrcpy-server: OK
[scrcpy] Building client...
./install_release.sh: line 15: meson: command not found

**Comment by rom1v** [comment]
> meson: command not found

You did not install the required packages as described in the documentation: https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md#latest-version

**Comment by Rahumi-f** [comment]
it tells me this :

libusb-1.0-0 is already the newest version (2:1.0.27-1).
libusb-1.0-0 set to manually installed.
You might want to run 'apt --fix-broken install' to correct these.
Unsatisfied dependencies:
 adb : Depends: android-libbase (>= 34.0.5) but it is not going to be installed
       Depends: android-libboringssl (>= 14.0.0+r45) but it is not going to be installed
       Depends: android-libcutils (= 1:34.0.5-3) but it is not going to be installed
       Depends: android-liblog (>= 34.0.5) but it is not going to be installed
       Depends: android-libziparchive (>= 34.0.5) but it is not going to be installed
       Recommends: android-sdk-platform-tools-common (>= 28.0.2~) but it is not going to be installed
 ffmpeg : Depends: libavcodec61 (>= 7:7.0)
          Depends: libavdevice61 (>= 7:7.0) but it is not going to be installed
          Depends: libavfilter10 (>= 7:7.0)
          Depends: libavformat61 (>= 7:7.0)
          Depends: libavutil59 (>= 7:7.0) but it is not going to be installed
          Depends: libplacebo349 (>= 7.349.0) but it is not going to be installed
          Depends: libpostproc58 (>= 7:7.0) but it is not going to be installed
          Depends: libswresample5 (>= 7:7.0) but it is not going to be installed
          Depends: libswscale8 (>= 7:7.0) but it is not going to be installed
 g++ : Depends: gcc (= 4:13.2.0-7) but 4:14.1.0-2 is to be installed
 gcc : Depends: cpp (= 4:14.1.0-2) but 4:13.2.0-7 is to be installed
       Depends: cpp-x86-64-linux-gnu (= 4:14.1.0-2) but 4:13.2.0-7 is to be installed
       Depends: gcc-14 (>= 14.1.0-4~) but it is not going to be installed
       Depends: gcc-x86-64-linux-gnu (= 4:14.1.0-2) but 4:13.2.0-7 is to be installed
 git : Depends: git-man (> 1:2.45.2) but 1:2.43.0-1 is to be installed
 libavcodec-dev : Depends: libavcodec61 (= 7:7.0.2-3)
 libavdevice-dev : Depends: libavdevice61 (= 7:7.0.2-3) but it is not going to be installed
                   Depends: libavfilter-dev (= 7:7.0.2-3) but it is not going to be installed
                   Depends: libpostproc-dev (= 7:7.0.2-3) but it is not going to be installed
                   Depends: libswscale-dev (= 7:7.0.2-3) but it is not going to be installed
 libavformat-dev : Depends: libavformat61 (= 7:7.0.2-3)
 libavutil-dev : Depends: libavutil59 (= 7:7.0.2-3) but it is not going to be installed
 libsdl2-dev : Depends: libasound2-dev but it is not going to be installed
               Depends: libdbus-1-dev but it is not going to be installed
               Depends: libdecor-0-dev but it is not going to be installed
               Depends: libdrm-dev but it is not going to be installed
               Depends: libgbm-dev but it is not going to be installed
               Depends: libibus-1.0-dev but it is not going to be installed
               Depends: libpulse-dev but it is not going to be installed
               Depends: libsamplerate0-dev but it is not going to be installed
               Depends: libsndio-dev but it is not going to be installed
               Depends: libudev-dev but it is not going to be installed
               Depends: libwayland-dev but it is not going to be installed
               Depends: libxcursor-dev but it is not going to be installed
               Depends: libxfixes-dev but it is not going to be installed
               Depends: libxi-dev but it is not going to be installed
               Depends: libxinerama-dev but it is not going to be installed
               Depends: libxkbcommon-dev but it is not going to be installed
               Depends: libxrandr-dev but it is not going to be installed
               Depends: libxss-dev but it is not going to be installed
               Depends: libxv-dev but it is not going to be installed
               Depends: libxxf86vm-dev but it is not going to be installed
 libswresample-dev : Depends: libswresample5 (= 7:7.0.2-3) but it is not going to be installed
 pkg-config : Depends: pkgconf (>= 1.8.1-3) but it is not going to be installed
Error: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

**Comment by rom1v** [comment]
Your package manager has problem. Try `apt --fix-broken install` as suggested.

Did you added repos in your `sources.list` (they can mess up everything).

**Comment by Rahumi-f** [comment]
no i actually didnt do any thing
