### ISSUE TITLE
Error while building ninja on macOS, High Sierra, 10.13.3

### ISSUE THREAD

**Issue by soder82** [Genymobile/scrcpy#54]
I got this error. FAILURE: Build failed with an exception.

* Where:
Build file '/Users/jacobsoderman/github/scrcpy/server/build.gradle' line: 1

* What went wrong:
```
A problem occurred evaluating project ':server'.
  java.lang.UnsupportedClassVersionError: com/android/build/gradle/AppPlugin : Unsupported major.minor version 52.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 39s
ninja: build stopped: subcommand failed.
```

/Söder

**Comment by rom1v** [comment]
> `Unsupported major.minor version 52.0`

You need Java 8.

**Comment by soder82** [comment]
OK. Thanks. But I read further down and downloaded the .jar instead.

But I then got this error.

$ ninja
ninja: error: '/Users/mainuser/github/scrcpy-server.jar', needed by 'server/scrcpy-server.jar', missing and no known rule to make it

/Söder

**Comment by rom1v** [comment]
What was the initial `meson` command you executed?

**Comment by soder82** [comment]
In the readme file, under Prebuilt server, after I've specified the path the downloaded scrcpy-server-v1.0.jar, 

meson x --buildtype release --strip -Db_lto=true \
    -Dprebuilt_server=/path/to/scrcpy-server.jar
cd x
ninja
sudo ninja install

It was then I typed "ninja" I got that...

/Söder

**Comment by abacao** [comment]
I'm having the same issue:
/scrcpy$ meson x --buildtype release --strip -Db_lto=true -Dprebuilt_server=~/Documents/scrcpy-server-v1.0.jar

> WARNING: You are using 'ANSI_X3.4-1968' which is not a a Unicode-compatible locale.
> WARNING: You might see errors if you use UTF-8 strings as filenames, as strings, or as file contents.
> WARNING: Please switch to a UTF-8 locale for your platform.
> The Meson build system
> Version: 0.37.1
> Source dir: /home/z003utcv/Documents/scrcpy
> Build dir: /home/z003utcv/Documents/scrcpy/x
> Build type: native build
> Project name: scrcpy
> Native c compiler: cc (gcc 6.3.0)
> Build machine cpu family: x86_64
> Build machine cpu: x86_64
> Found pkg-config: /usr/bin/pkg-config (0.29)
> Native dependency libavformat found: YES 57.56.101

cd x
ninja

> ninja: error: '../server/~/Documents/scrcpy-server-v1.0.jar', needed by 'server/scrcpy-server.jar', missing and no known rule to make it

Native dependency libavcodec found: YES 57.64.101
Native dependency libavutil found: YES 55.34.101
Native dependency sdl2 found: YES 2.0.5
Build targets in project: 6

**Comment by rom1v** [comment]
@abacao Try using the full absolute path for the server:

```bash
meson x --buildtype release --strip -Db_lto=true -Dprebuilt_server="$HOME"/Documents/scrcpy-server-v1.0.jar
```

**Comment by soder82** [comment]
I now understand I had to rename the server file. Stupid by me.

But now at ninja run, I got this problem, I think has to do with adb. How do I set the path for that?

$ ninja run
[0/1] Running external command run.
exec: No such file or directory
2018-03-12 21:49:49.302 scrcpy[10239:797835] ERROR: "adb push" returned with value 1
FAILED: meson-run 
/usr/local/opt/python/bin/python3.6 /usr/local/Cellar/meson/0.45.0/libexec/bin/meson --internal commandrunner /Users/mainuser/github/scrcpy /Users/mainuser/github/scrcpy/x '' /usr/local/opt/python/bin/python3.6 /usr/local/Cellar/meson/0.45.0/libexec/bin/meson scripts/run-scrcpy.sh
ninja: build stopped: subcommand failed.

**Comment by stek29** [comment]
So, it's fixed?

**Comment by erhanbicer** [comment]
Option 1 solved the problem
https://stackoverflow.com/a/28208121/7540894
