### ISSUE TITLE
Build warning with meson 0.50.1

### ISSUE THREAD

**Issue by npes87184** [Genymobile/scrcpy#540]
server/meson.build:5: WARNING: Custom target input '.' can't be converted to File object(s).
This will become a hard error in the future.

**Comment by rom1v** [comment]
Fixed by #553.

**Comment by RaviBeagle** [comment]
Hello,

Is this really fixed ? I am trying to build scrcpy on jetson nano (an ARM64 board).

meson x --buildtype release --strip -Db_lto=true -Dprebuilt_server=/home/rreddy78/scrcpy-server-v1

The Meson build system
Version: **0.55.3**
Source dir: /home/rreddy78/scrcpy
Build dir: /home/rreddy78/scrcpy/x
Build type: native build
Project name: scrcpy
Project version: 1.16
C compiler for the host machine: cc (gcc 7.5.0 "cc (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0")
..
..
**server/meson.build:24: WARNING: Custom target input '/home/rreddy78/scrcpy-server-v1' can't be converted to File object(s).
This will become a hard error in the future.**
Build targets in project: 3

And  I get Ninja error:

rreddy78@jetson:~/scrcpy$ ninja -Cx
ninja: Entering directory `x'
[20/26] Generating scrcpy-server-prebuilt with a custom command
FAILED: server/scrcpy-server 
cp /home/rreddy78/scrcpy-server-v1 server/scrcpy-server
cp: -r not specified; omitting directory '/home/rreddy78/scrcpy-server-v1'
[25/26] Compiling C object app/scrcpy.p/src_sys_unix_command.c.o
ninja: build stopped: subcommand failed.

For now I will also try to build the server too..

**Comment by rom1v** [comment]
```
cp: -r not specified; omitting directory '/home/rreddy78/scrcpy-server-v1'
```
Looks like `scrcpy-server-v1` is a directory. You must pass the filepath.

**Comment by RaviBeagle** [comment]
> Looks like `scrcpy-server-v1` is a directory. You must pass the filepath.

But I am just following the instructions given:

![image](https://user-images.githubusercontent.com/598688/94247384-aafb3f80-ff3a-11ea-9d36-e86d9f0d8425.png)

**Comment by rom1v** [comment]
Yes, if the `scrcpy-server` path is `/path/to/scrcpy-server` (it's a file), then you must execute that.

It seems that `/home/rreddy78/scrcpy-server-v1` is a directory on your computer.

**Comment by RaviBeagle** [comment]
Thanks. I get linking errors. I have libv4l in my system..

/usr/local/lib/libavcodec.so: undefined reference to `v4l2_open'
/usr/local/lib/libavcodec.so: undefined reference to `v4l2_close'
/usr/local/lib/libavcodec.so: undefined reference to `v4l2_ioctl'

**Comment by rom1v** [comment]
> `/usr/local/lib/libavcodec.so`

Where does your ffmpeg come from?

The one from the system is at `/usr/lib/x86_64-linux-gnu/libavcodec.so`.

**Comment by RaviBeagle** [comment]
I have a custom ffmpeg from NVIDIA.

**Comment by rom1v** [comment]
OK, so there is probably a problem with it, in particular where it finds its dependencies.

Check `ldd /usr/local/lib/libavcodec.so`.

**Comment by RaviBeagle** [comment]
Thanks. Working now.I got a  dbus crash. But this is a problem with SLD2. I have to run with sudo..

**Comment by rom1v** [comment]
> I have to run with sudo.

:scream:

**Comment by RaviBeagle** [comment]
![image](https://user-images.githubusercontent.com/598688/94257608-2d8afb80-ff49-11ea-8e1b-de4ddbcbc2e8.png)

sudo scrcpy --rotation 1  -m 1920 

I am running Sentio  on phone and using scrcpy for mirroring..To get better resolution do i increase bitrate ?

**Comment by RaviBeagle** [comment]
I believe its fine now. My phone colours are so much better than my old monitor :) hat I had a doubt..

**Comment by sercan447** [comment]
"server/meson.build:24: WARNING: Custom target input '/home/sercanus/scrcpy-server-v1' can't be converted to File object(s)."
I want to build the code and do development. but i can't build
I can't build. I'm getting angry now.
why not why

**Comment by rom1v** [comment]
`/home/sercanus/scrcpy-server-v1` Does this file exist? It should be `scrcpy-server-v1.17`.

**Comment by sercan447** [comment]
this folder or file does not exist. I don't know exactly what to do

I went into the directory with cd /scrcpy
then i ran the following command.

meson foldername --buildtype release --strip -Db_lto=true -Dprebuilt_server=/home/sercanus/scrcpy/scrcpy-server-v1

but I got an error
"server/meson.build:24: WARNING: Custom target input '/home/sercanus/scrcpy-server-v1' can't be converted to File object(s)."


I don't know how to compile and run the codes.
I will be glad if you help :)

**Comment by rom1v** [comment]
> then i ran the following command.
>
> meson foldername --buildtype release --strip -Db_lto=true -Dprebuilt_server=/home/sercanus/scrcpy/scrcpy-server-v1

That's the problem, you explicitly passed this path to the file which does not exist: `-Dprebuilt_server=/home/sercanus/scrcpy/scrcpy-server-v1`

**Comment by sercan447** [comment]
I have created a folder named "servfolder" under the scrcpy directory
and I ran the command again

meson xmn --buildtype release --strip -D b_lto=true -D prebuilt_server=/home/sercanus/Projects/scrcpy/servfolder

but I got the same error again

"server/meson.build:24: WARNING: Custom target input '/home/sercanus/Projects/scrcpy/servfolder' can't be converted to File object(s)."

**Comment by rom1v** [comment]
You must path the full path to the server, filename included.

Probably something like:
`-Dprebuilt_server=/home/sercanus/Projects/scrcpy/servfolder/scrcpy-server-v1.17`

**Comment by sercan447** [comment]
which server are we talking about ?

**Comment by sercan447** [comment]
because there is no such thing

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#prebuilt-server

**Comment by sercan447** [comment]
"meson xmn --buildtype release --strip -D b_lto=true -D prebuilt_server=/home/sercanus/Projects/scrcpy/copy-server/scrcpy-server-v1.17"

I have succeeded this step now. but I still don't understand how to run it

**Comment by sercan447** [comment]
I downloaded the above serverv.17 file and created a folder named "copy-server" in my scrcpy folder and moved the serverv1.7 file there. then I wrote the following code

meson xmn --buildtype release --strip -D b_lto=true -D prebuilt_server=/home/username/Projects/scrcpy/newfoldercrate/scrcpy-server-v1.17"
