### ISSUE TITLE
can't connect android

### ISSUE THREAD

**Issue by 233laoliu** [Genymobile/scrcpy#5401]
_Please read the [prerequisites] to run scrcpy._

[prerequisites]: https://github.com/Genymobile/scrcpy#prerequisites

_Also read the [FAQ] and check if your [issue][issues] already exists._

[FAQ]: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md
[issues]: https://github.com/Genymobile/scrcpy/issues

## Environment

 - **OS:** [windows]
 - **Scrcpy version:** [e.g. 2.7]
 - **Installation method:** [e.g.Windows release]
 - **Device model:*usb*
 - **Android version:** [e.g. 14]

PS C:\Users\laoliu> adb devices
List of devices attached
192.168.1.6:37529       offline

PS C:\Users\laoliu> adb pair 192.168.1.6:41293
Enter pairing code: 610831
Successfully paired to 192.168.1.6:41293 [guid=adb-10AE3Y0KBZ005X0-4BNNW1]
PS C:\Users\laoliu> adb devices
List of devices attached
192.168.1.6:37529       offline

PS C:\Users\laoliu> adb shell
adb.exe: no devices/emulators found
PS C:\Users\laoliu> adb connect 192.168.1.6:37529
cannot connect to 192.168.1.6:37529: 由于目标计算机积极拒绝，无法连接。 (10061)
PS C:\Users\laoliu> adb connect 192.168.1.6:43369
connected to 192.168.1.6:43369
PS C:\Users\laoliu> adb shell
PD2309:/ $ ls
acct        data           init.environ.rc       metadata     product                 system_ext
apex        data_mirror    init.vivo.common.rc   mnt          sdcard                  vendor
bin         debug_ramdisk  init.vivo.project.rc  odm          second_stage_resources  vendor_dlkm
bugreports  dev            init.vivo.rc          odm_dlkm     storage                 vgc
cache       etc            init.vivo.soc.rc      oem          sys
config      factory        linkerconfig          postinstall  system
d           init           logdata               proc         system_dlkm
PD2309:/ $ ^D
PS C:\Users\laoliu> adb devices
List of devices attached
192.168.1.6:43369       device

PS C:\Users\laoliu> E:\HugoMoveData\User\laoliu\Downloads\scrcpy-win64-v2.7\scrcpy-win64-v2.7\scrcpy.exe
scrcpy 2.7 <https://github.com/Genymobile/scrcpy>
ERROR: CreateProcessW() error 5
ERROR: Failed to execute: [C:\Users\laoliu\platform-tools], [start-server]
ERROR: Could not execute "adb start-server"
ERROR: Could not start adb server
ERROR: Server connection failed
PS C:\Users\laoliu> adb devices
List of devices attached
192.168.1.6:43369       device

PS C:\Users\laoliu> adb devices
List of devices attached
192.168.1.6:43369       device

PS C:\Users\laoliu> adb devices
List of devices attached
192.168.1.6:43369       device

PS C:\Users\laoliu> E:\HugoMoveData\User\laoliu\Downloads\scrcpy-win64-v2.7\scrcpy-win64-v2.7\adb.exe devices
List of devices attached
192.168.1.6:43369       device

PS C:\Users\laoliu> E:\HugoMoveData\User\laoliu\Downloads\scrcpy-win64-v2.7\scrcpy-win64-v2.7\scrcpy.exe
scrcpy 2.7 <https://github.com/Genymobile/scrcpy>
ERROR: CreateProcessW() error 5
ERROR: Failed to execute: [C:\Users\laoliu\platform-tools], [start-server]
ERROR: Could not execute "adb start-server"
ERROR: Could not start adb server
ERROR: Server connection failed
PS C:\Users\laoliu> C:\Users\laoliu\platform-tools\adb.exe devices
List of devices attached
192.168.1.6:43369       offline

PS C:\Users\laoliu>

**Comment by rom1v** [comment]
> ERROR: Failed to execute: [C:\Users\laoliu\platform-tools], [start-server]

https://github.com/Genymobile/scrcpy/issues/4139#issuecomment-1620538271
https://github.com/Genymobile/scrcpy/issues/3302#issuecomment-1140190302

**Comment by 233laoliu** [comment]
OK thanks
