### ISSUE TITLE
Do not work mouse control

### ISSUE THREAD

**Issue by VanGrun** [Genymobile/scrcpy#5406]
Hello, i have windows 8.1 on me notebook and Xiaomi MI11 Lite.
Do not work mouse control.
![log](https://github.com/user-attachments/assets/cff33535-d13e-4988-b4ef-04a36816d9d7)

There is some way it work ?

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy?tab=readme-ov-file#prerequisites

**Comment by VanGrun** [comment]
Ok. It help me
