### ISSUE TITLE
No screen, Encoding error on SDMC android box

### ISSUE THREAD

**Issue by aggo1036** [Genymobile/scrcpy#5408]
## Environment

 - Windows 10 64-bit Pro
 - scrcpy 2.7
 - Windows release zip-file.
 - SDMC DV8919x
 - Android 12

**BUG.**
Screen is not rendering.
[server] ERROR: Encoding error: java.lang.IllegalStateException: null

**Description**.
Wireless debugging is hidden from the supplier. So instead [ADB WiFi 3.3.160](https://adb-wifi.en.uptodown.com/android) was installed through USB and set as autostart on boot. I can now seemingly connect as if wireless debugging was installed/enabled. When accept adb connection the screen is shown as "USB Debugging" if that is of any interest.

**Terminal output in a code block.**
```
C:\Users\.....\Desktop\scrcpy-win64-v2.7>scrcpy --video-codec=h265 --max-size=1920 --max-fps=60 --no-audio --keyboard=uhid
scrcpy 2.7 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     --> (tcpip)  192.168.50.97:5555              device  Telia_Nordic_STB
C:\Users\.....\Desktop\scrcpy-win64-v2.7\scrcpy-server: 1 file pushed, 0 skipped. 82.7 MB/s (71200 bytes in 0.001s)
[server] INFO: Device: [SDMC] Telia Telia Nordic STB (Android 12)
INFO: Renderer: direct3d
INFO: Texture: 1920x1080
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m1600...
[server] INFO: Retrying...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m1280...
[server] INFO: Retrying...
```
If I just go "scrcpy -m640" everything comes to a halt at INFO: Texture: 640x360 same as before.
Any ideas of where to go from here?

**Comment by rom1v** [comment]
You can try with another encoder: https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#encoder

**Comment by aggo1036** [comment]
> You can try with another encoder: https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#encoder

This is what I got

INFO:     --> (tcpip)  192.168.50.97:5555              device  Telia_Nordic_STB
```
C:\Users\obbola\Desktop\scrcpy-win64-v2.7\scrcpy-server: 1 file pushed, 0 skipped. 46.4 MB/s (71200 bytes in 0.001s)
[server] INFO: Device: [SDMC] Telia Telia Nordic STB (Android 12)
[server] INFO: List of video encoders:
    --video-codec=h264 --video-encoder='OMX.amlogic.video.encoder.avc'
    --video-codec=h264 --video-encoder='c2.android.avc.encoder'
    --video-codec=h264 --video-encoder='OMX.google.h264.encoder'
    --video-codec=h265 --video-encoder='OMX.amlogic.video.encoder.hevc'
[server] INFO: List of audio encoders:
    --audio-codec=opus --audio-encoder='c2.android.opus.encoder'
    --audio-codec=aac --audio-encoder='c2.android.aac.encoder'
    --audio-codec=aac --audio-encoder='OMX.google.aac.encoder'
    --audio-codec=flac --audio-encoder='c2.android.flac.encoder'
    --audio-codec=flac --audio-encoder='OMX.google.flac.encoder'
```

**Comment by aggo1036** [comment]
Thanks it worked now! 

`scrcpy --video-codec=h264 --video-encoder=c2.android.avc.encoder --max-size=1920 --max-fps=60 --no-audio --keyboard=uhid`

**Comment by aggo1036** [comment]
Solved.
