### ISSUE TITLE
Misconfigured color format causes abnormal display images

### ISSUE THREAD

**Issue by TsaiHao** [Genymobile/scrcpy#5413]
_Please read the [prerequisites] to run scrcpy._

[prerequisites]: https://github.com/Genymobile/scrcpy#prerequisites

_Also read the [FAQ] and check if your [issue][issues] already exists._

[FAQ]: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md
[issues]: https://github.com/Genymobile/scrcpy/issues

## Environment

 - **OS:** MacOS
 - **Scrcpy version:** 2.7
 - **Installation method:** brew
 - **Device model:** Macbook Pro with M1pro chip
 - **Android version:** 11 (FireOS8)

## Describe the bug

I'm using scrcpy with a FOS8 Smart TV device powered by a MediaTek CPU. While most functionalities work correctly, the preview video displayed on my computer exhibits misconfigured color channels. Specifically, the red and blue channels appear to be swapped.

#### Screenshots
Here is the screenshot of a running scrcpy preview window:
<img width="1920" alt="scrcpy" src="https://github.com/user-attachments/assets/a82b44d3-6f92-499a-96eb-3fb44a22d86a">

This is a screenshot from the device.
![screen](https://github.com/user-attachments/assets/b4c8dc86-37a1-480d-b513-e94979f11287)

#### Technical Details
After investigating the code, I identified a potential issue related to the color format configuration: 

In `SurfaceEncoder.java`
```
        format.setInteger(MediaFormat.KEY_COLOR_FORMAT, MediaCodecInfo.CodecCapabilities.COLOR_FormatSurface);
```
This line sets an opaque color format that relies on the vendor's implementation.

In `display.c`:
```
    SDL_Texture *texture = SDL_CreateTexture(renderer, SDL_PIXELFORMAT_YV12,
                                             SDL_TEXTUREACCESS_STREAMING,
                                             size.width, size.height);
```
Here, the display color format is hardcoded to `SDL_PIXELFORMAT_YV12`, which may not align with the actual encoder output.

#### Questions
Dynamic Color Format Detection:
Is it possible to determine the specific color format used by the encoder after configuration and transmit this information to the host computer? This would allow the display module to create a corresponding texture that matches the encoder's format.

Configurable Display Color Format:
If dynamically configuring the display format is not feasible, could an option be added to allow users to specify the desired color format via the command line? This would enable fine-tuning to address issues like the color channel mismatch I’m experiencing.

**Comment by rom1v** [comment]
Thank you for your report.

>```java
> format.setInteger(MediaFormat.KEY_COLOR_FORMAT, MediaCodecInfo.CodecCapabilities.COLOR_FormatSurface);
> ```

This is the input format (the screen content is captured from a surface), not the output format.

> ```c
> SDL_Texture *texture = SDL_CreateTexture(renderer, SDL_PIXELFORMAT_YV12,
> ```

This is the internal representation of the OpenGL texture. Changing it to `SDL_PIXELFORMAT_IYUV` would not change the visual result for example.

What matters is the decoded format (used by the FFmpeg decoder, which might depend on the encoded format), then how it is uploaded to SDL:

https://github.com/Genymobile/scrcpy/blob/67d4dfb5ffcfeaddf3363e73fdf3b2c500fd5842/app/src/display.c#L258-L261

---

Can you reproduce the problem with another [encoder](https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#encoder)?

Can you please run scrcpy with this additional patch, and post the console output:

```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/video/SurfaceEncoder.java b/server/src/main/java/com/genymobile/scrcpy/video/SurfaceEncoder.java
index 5a9417da8..26cb316c8 100644
--- a/server/src/main/java/com/genymobile/scrcpy/video/SurfaceEncoder.java
+++ b/server/src/main/java/com/genymobile/scrcpy/video/SurfaceEncoder.java
@@ -86,6 +86,29 @@ public class SurfaceEncoder implements AsyncProcessor {
 
                     mediaCodec.start();
 
+                    MediaFormat fmt = mediaCodec.getOutputFormat();
+                    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
+                        for (String key : fmt.getKeys()) {
+                            Object o;
+                            switch (fmt.getValueTypeForKey(key)) {
+                                case MediaFormat.TYPE_STRING:
+                                    o = fmt.getString(key);
+                                    break;
+                                case MediaFormat.TYPE_INTEGER:
+                                case MediaFormat.TYPE_LONG:
+                                case MediaFormat.TYPE_FLOAT:
+                                    o = fmt.getNumber(key);
+                                    break;
+                                case MediaFormat.TYPE_BYTE_BUFFER:
+                                    o = fmt.getByteBuffer(key);
+                                    break;
+                                default:
+                                    o = null;
+                            }
+                            Ln.i("===== " + key + " = " + o);
+                        }
+                    }
+
                     alive = encode(mediaCodec, streamer);
                     // do not call stop() on exception, it would trigger an IllegalStateException
                     mediaCodec.stop();
```

**Comment by TsaiHao** [comment]
Thank you for your analysis.

*1. Can you reproduce the problem with another encoder?*
I've tried run `scrcpy` with this command:
```bash
scrcpy -V verbose --video-encoder=c2.android.avc.encoder --no-audio
```
Using the software encoder did fix the preview issue.

*2. Can you please run scrcpy with this additional patch, and post the console output?*
Here is the output of the output format, in which the `color-format` property is not present:
```bash
➜  scrcpy git:(master) ✗ ./run x -V info --no-audio
scrcpy 2.7 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  GCP3WA0022060012                device  AFTOLCBC82
x/server/scrcpy-server: 1 file pushed, 0 skipped. 240.3 MB/s (129603 bytes in 0.001s)
[server] INFO: Device: [Amazon] Amazon AFTOLCBC82 (Android 11)
INFO: Renderer: metal
INFO: Texture: 1920x1080
[server] INFO: ===== max-bitrate = 8000000
[server] INFO: ===== crop-right = 1919
[server] INFO: ===== level = 8192
[server] INFO: ===== latency = 2
[server] INFO: ===== mime = video/avc
[server] INFO: ===== profile = 8
[server] INFO: ===== bitrate = 8000000
[server] INFO: ===== priority = 1
[server] INFO: ===== intra-refresh-period = 0
[server] INFO: ===== color-standard = 0
[server] INFO: ===== color-transfer = 0
[server] INFO: ===== crop-bottom = 1079
[server] INFO: ===== prepend-sps-pps-to-idr-frames = 0
[server] INFO: ===== crop-left = 0
[server] INFO: ===== width = 1920
[server] INFO: ===== input.time-stretch = 1.0
[server] INFO: ===== bitrate-mode = 1
[server] INFO: ===== color-range = 2
[server] INFO: ===== crop-top = 0
[server] INFO: ===== frame-rate = 60
[server] INFO: ===== height = 1080
```

After I found that the abnormal preview couldn't be reproduced with the software encoder, I've also run a CTS test case [EncodeVirtualDisplayTest](https://cs.android.com/android/platform/superproject/main/+/main:cts/tests/tests/media/codec/src/android/media/codec/cts/EncodeVirtualDisplayTest.java;l=88?q=EncodeVirtualDis&sq=&ss=android%2Fplatform%2Fsuperproject%2Fmain) could be related to this issue. On my TV device, this test failed to pass and reported a color related error:
```bash
$ adb shell am instrument -w -e class android.media.cts.EncodeVirtualDisplayTest#testEncodeVirtualDisplay android.media.cts

android.media.cts.EncodeVirtualDisplayTest:
Error in testEncodeVirtualDisplay(android.media.cts.EncodeVirtualDisplayTest):
java.lang.RuntimeException: No match for color r=183 g=69 b=0
	at android.media.cts.EncodeVirtualDisplayTest.checkSurfaceFrame(EncodeVirtualDisplayTest.java:513)
	at android.media.cts.EncodeVirtualDisplayTest.doTestEncodeVirtual(EncodeVirtualDisplayTest.java:370)
	at android.media.cts.EncodeVirtualDisplayTest.encodeVirtualDisplayTest(EncodeVirtualDisplayTest.java:262)
	at android.media.cts.EncodeVirtualDisplayTest.access$000(EncodeVirtualDisplayTest.java:71)
	at android.media.cts.EncodeVirtualDisplayTest$EncodeVirtualWrapper.run(EncodeVirtualDisplayTest.java:157)
	at java.lang.Thread.run(Thread.java:923)
```

Therefore, I suppose it's primarily a MTK encoder implementation issue. Consequently, a bug report has been filed with the internal MediaTek team for further investigation. Thank you for your assistance.
