### ISSUE TITLE
Can launch in windows

### ISSUE THREAD

**Issue by AlphaHans** [Genymobile/scrcpy#5427]
## Environment

 - **OS:**  Windows
 - **Scrcpy version:** 2.7
 - **Installation method:** windwos.zip
 - **Device model:** vivo V2307A
 - **Android version:**  14

## Describe the bug

```
ERROR: CreateProcessW() error 5
ERROR: Failed to execute: [C:\Users\hans\AppData\Local\Android\Sdk\platform-tools], [start-server]
ERROR: Could not execute "adb start-server"
ERROR: Could not start adb server
ERROR: Server connection failed
Press Enter to continue...
```

However, I tested it, and running the command（“adb start-server")  in an independent terminal works.
```
C:\Users\hans>adb start-server

C:\Users\hans>adb --version
Android Debug Bridge version 1.0.41
Version 35.0.1-11580240
Installed as C:\Users\hans\AppData\Local\Android\Sdk\platform-tools\adb.exe
Running on Windows 10.0.22631

C:\Users\hans>
```

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/issues/3302#issuecomment-1140190302

**Comment by AlphaHans** [comment]
> [#3302 (comment)](https://github.com/Genymobile/scrcpy/issues/3302#issuecomment-1140190302)

thanks，i had sloved it
