### ISSUE TITLE
scrcpy Not Responding after connecting

### ISSUE THREAD

**Issue by sekazi** [Genymobile/scrcpy#543]
I just setup scrcpy today and earlier it was functioning fine. I installed nothing. I updated nothing. WIndows did not install updates. The only change is my PC was restarted if that was even the cause of the problem.

When I run scrcpy now even if I connect directly by USB instead of wireless it will freeze right after connecting and go not responding. I looked through possible causes here and one suggestion was iCUE but even after I uninstalled that and restarted it did not solve the issue. There was an update for my nVidia drivers so I installed those and it did not solve the issue.

Sometimes if I leave the window open long enough it will update the image but still remain frozen after that.

Below is a video of what it is doing.
https://youtu.be/NyAVyI4R1M0

**Comment by rom1v** [comment]
Looks like a driver issue. If you can find the source code line where it blocks, it would help (but I don't know how to do that on Windows, on Linux it would be easy with gdb).

Does it work if you only record instead of display?

    scrcpy --no-display --record file.mkv

(disconnect the device to stop recordkng on Windows)

I suggest you test on USB to debug, because you could get unrelated freezes over TCP (when packets are lost).

**Comment by sekazi** [comment]
Recording works flawlessly. I tested the recording in both wired and wireless and both times it worked with no issues. 

I tested it again in both wired and wireless and it still freezes right after the window opens to show the screen.

It is really odd that it worked fine when I first used it with no problems at all and a few hours later it no longer worked. I tried different USB ports with no change.

**Comment by rom1v** [comment]
So this is definitely a graphical driver issue. If recording works well, then the client correctly receives the stream, it's just the display that fails.

**Comment by rom1v** [comment]
Related to https://github.com/Genymobile/scrcpy/issues/419?

**Comment by sekazi** [comment]
I do not think it is related to OBS as it freezes even without OBS running. I have a GTX 1080 on my PC.

I tried the following without success.  
1. Reinstalled nVIDIA Game Ready drivers with a clean install then restarted.
2. Installed the nVIDIA Creator Ready drivers with a clean install then restarted.
3. Created a nVIDIA profile for scrcpy.exe and set it to max performance and changed other settings.
4. Ran scrcpy as Admin, Disable full screen optimization, various compatibility modes.
5. Killed all running programs and services not essential.

None of that worked. My PC does not have integrated graphics so I cannot try it with that instead.

So I grabbed my Macbook and launched Windows 10 in Parallels and tried it there and it works without issues just like it did earlier yesterday on my desktop. I am going to try and think of other possible solutions. Maybe it will end up working fine with the Oculus Quest when I get it Tuesday.

I will report back if I find a solution or other things I try.

**Comment by sekazi** [comment]
I uninstalled OpenJDK and installed Oracle Java to see if that would solve the issue but it did not.

I tried older versions of scrcpy to see if that would work but version 1.5 and newer just froze like usual and 1.4 and older would not launch due to an error about scrcpy-server.jar not being a directory.

**Comment by rom1v** [comment]
Oh, I remember now: use SDL 2.0.8 instead of 2.0.9. https://github.com/Genymobile/scrcpy/issues/425#issuecomment-470936377

**Comment by ghxstdev** [comment]
I am experiencing the same issue.
Takes up to a minute for the screen share to launch which instantly freezes.

versions:
1.8 x64 and x32
1.7 x64 and x32

Will try older versions.

**Comment by sekazi** [comment]
> Oh, I remember now: use SDL 2.0.8 instead of 2.0.9. [#425 (comment)](https://github.com/Genymobile/scrcpy/issues/425#issuecomment-470936377)

That was exactly the problem. As soon as I replaced the SDL2.dll with the one in v1.3 it worked without any problems. Is there anything the new dll did that the old one did not?
