### ISSUE TITLE
I would like to pin the no console VBS script version to my start menu

### ISSUE THREAD

**Issue by rthfhgyhy567** [Genymobile/scrcpy#5438]
Is there a way to do this?  In windows 10 I can't pin batch files or VBS script files to the start menu, which means that I have to search for the file in my computer in order to open it or make a shortcut and put it on my desktop (can't pin a shortcut of said file types to the start menu either).

Such a great app if it wasn't so autistic sounding and hard to use

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/issues/2159#issuecomment-801898530
