### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by Vamael** [Genymobile/scrcpy#544]
![image](https://user-images.githubusercontent.com/49615683/57989797-718e0680-7aa0-11e9-8147-2044dd2fc37b.png)

adb is enabled on my huwaei mate 20 lite

**Comment by rom1v** [comment]
Try with a lower definition.

Open a console (`cmd`), go to the scrcpy directory, and execute:

    scrcpy -m1024

**Comment by Vamael** [comment]
ye now it works thank
