### ISSUE TITLE
Slow motion video sometimes on S23 Ultra

### ISSUE THREAD

**Issue by rthfhgyhy567** [Genymobile/scrcpy#5440]
## Environment

 - **OS:** [e.g. Debian, Windows, macOS...] **Windows**
 - **Scrcpy version:** [e.g. 2.5] **2.7 64 bit**
 - **Installation method:** [e.g. manual build, apt, snap, brew, Windows release...] **Windows**
 - **Device model:** **S23 Ultra**
 - **Android version:** [e.g. 14] **14**

## Describe the bug

The video sometimes appears in slow motion and makes it very distracting to use.  How can I change the quality down to troubleshoot?

**Comment by rom1v** [comment]
Try to reduce the resolution: `scrcpy -m1024`.

**Comment by rthfhgyhy567** [comment]
How do I do that?

**Comment by rthfhgyhy567** [comment]
Also here's a tip.  Instead of making the name scrcpy (short for screen copy?) which just sounds like unpronounceable gibberish.  Change the name to Scropy.  I think more people will start using this program once there is a more recognizable sounding name.  A config editor INI would also be nice too

**Comment by rom1v** [comment]
> How do I do that?

Read https://github.com/Genymobile/scrcpy/blob/master/doc/windows.md#run

**Comment by rthfhgyhy567** [comment]
That fixed it but I think the core problem was that I was using a USB 2.0 port (I like to use that to be safe when using Android) and it was bottlenecking the performance.

Thanks for the quick responses (unlike vysor where I bought a lift time key and they were no where to be found when I had issues)

**Comment by rom1v** [comment]
By default, the video bitrate is 8Mpbs, and USB2 supports 480Mbps, so it is unlikely USB2 is the bottleneck.

However, if the resolution is too high (some modern devices have 4k displays), this takes longer to encode, transmit, decode, and use more memory bandwidth.
