### ISSUE TITLE
OpenGL filter prototype: no frame received

### ISSUE THREAD

**Issue by rom1v** [Genymobile/scrcpy#5444]
On-device OpenGL video filters will allow to:
 - reimplement `--lock-video-orientation` on Android >= 14 to fix #4011 
 - reimplement `--crop` on Android >= 14 to fix #4162
 - apply a custom capture rotation, useful to mirror a Meta Quest 3 for example (#4658)
 - support virtual display rotation (#5428)
 - rotate the camera capture for V4L2 (#4426)

I wrote a quick&dirty prototype (branch [`opengl_filter`](https://github.com/Genymobile/scrcpy/commits/opengl_filter/)), but I'm blocked because `onNewFrameAvailable()` is never called:

https://github.com/Genymobile/scrcpy/blob/4397dfba89241e764a84c20ec09aca181f22f978/server/src/main/java/com/genymobile/scrcpy/video/VideoFilter.java#L80

I'm pretty sure this is related to threading ([`setOnFrameAvailableListener()`](https://developer.android.com/reference/android/graphics/SurfaceTexture#setOnFrameAvailableListener(android.graphics.SurfaceTexture.OnFrameAvailableListener,%20android.os.Handler)) also accepts a `Handler`), but I did not manage to make it work.

Once this listener is called on every frame, I can implement the shaders to perform the transforms I want, but I need this to work to get started.

Any help welcome.

**Comment by yume-chan** [comment]
https://github.com/Genymobile/scrcpy/compare/opengl_filter...yume-chan:scrcpy:opengl_filter_v2?expand=1

I copied some OpenGL code from https://github.com/google/grafika, and mimicked how https://cs.android.com/android/platform/superproject/main/+/main:frameworks/av/cmds/screenrecord/Overlay.cpp initialized it.

**Comment by rom1v** [comment]
Thank you very much! It works perfectly.

I have everything I need to start working on it :tada: :heart:
