### ISSUE TITLE
Can we have multi windows for every open apps, just like wsa

### ISSUE THREAD

**Issue by foobra** [Genymobile/scrcpy#5445]
- [ v] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

I want to open multi apps and use multi scrcpy windows to show them, just like windows on android

**Comment by rom1v** [comment]
The virtual displays feature is merged on `dev` branch. See #5370.

**Comment by James4Ever0** [comment]
You can have a better experience with SWM.

Check out here: https://github.com/james4ever0/swm
