### ISSUE TITLE
ERROR: Failed to open output device: /dev/video2 ERROR: Demuxer error

### ISSUE THREAD

**Issue by Khaos1221** [Genymobile/scrcpy#5449]
_Please read the [prerequisites] to run scrcpy._

[prerequisites]: https://github.com/Genymobile/scrcpy#prerequisites

_Also read the [FAQ] and check if your [issue][issues] already exists._

[FAQ]: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md
[issues]: https://github.com/Genymobile/scrcpy/issues

## Environment

 - **OS:** [Nobara(fedora)]
 - **Scrcpy version:** [Latest on fedora -copr repository]
 - **Installation method:** [dnf]
 - **Device model:**(Cmf by NOthing)
 - **Android version:** [14]

## Describe the bug

BUGS - want to use the Video cam but it just tells me ERROR: Failed to open output device: /dev/video2
ERROR: Demuxer error

On errors, please provide the output of the console (and `adb logcat` if relevant).

ON running adb logcat its very huge and doesnt stop
```
research@nobara-pc Downloads]$ scrcpy --video-source=camera --camera-size=1920x1080 --camera-facing=front --v4l2-sink=/dev/video2 --no-playback 
scrcpy 2.4 <https://github.com/Genymobile/scrcpy>
INFO: No audio playback, no recording: audio disabled
INFO: Video orientation is locked for v4l2 sink. See --lock-video-orientation.
INFO: Camera video source: control disabled
INFO: ADB device found:
INFO:     --> (tcpip)  192.168.0.106:45429             device  A015
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 68.1 MB/s (69007 bytes in 0.001s)
[server] INFO: Device: [Nothing] Nothing A015 (Android 14)
[server] INFO: Using camera '1'
ERROR: Failed to open output device: /dev/video2
ERROR: Demuxer error
WARN: Killing the server...

```
I also tried adding --no-adio but same effects
Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
Did you create a loopback device with v4l2loopback?

What is the number of the device?

https://github.com/Genymobile/scrcpy/blob/master/doc/v4l2.md

**Comment by Khaos1221** [comment]
I didnt speciify the correct number sorry :disappointed: 
but heres another error



O: v4l2 sink started to device: /dev/video7
[server] WARN: Camera disconnected
[server] WARN: Camera capture failed: frame 171
[server] WARN: Camera capture failed: frame 172
[server] WARN: Camera capture failed: frame 173
WARN: Device disconnected


device is on (A14)
