### ISSUE TITLE
No audio forwarding from Nvidia Shield

### ISSUE THREAD

**Issue by stagelevel** [Genymobile/scrcpy#5450]
I have scrcpy set up on my MacBook so that I can access my Nvidia Shield. It works perfectly.

However, I can't seem to get audio to work. My Shield is on Android 11 and fully up to date. I read the information provided on audio forwarding:

**_For Android 11, you'll need to ensure that the device screen is unlocked when starting scrcpy. A fake popup will briefly appear to make the system think that the shell app is in the foreground. Without this, audio capture will fail._**

This never happens when I connect to my Shield. Is there something I'm missing here?

Thank you

**Comment by rom1v** [comment]
For future users, the problem was apparently solved:

```
scrcpy --audio-codec=aac
```

Refs https://www.reddit.com/r/scrcpy/comments/1gkyok4/no_audio_forwarding_from_nvidia_shield/
