### ISSUE TITLE
Camera ssh

### ISSUE THREAD

**Issue by toto6976** [Genymobile/scrcpy#5453]
Good evening
I have an error with scrcpy camera over ssh tunnel. Is it works with ssh or not ?

**Comment by rom1v** [comment]
Yes. What did you do and what's the error?

**Comment by toto6976** [comment]
Here is what i do :
ssh -CN -L5038:localhost:5037 -R27183:localhost:27183 90.58.xxx.xxx -p5024
export ADB_SERVER_SOCKET=tcp:localhost:5038
scrcpy --list-cameras
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
scrcpy: unrecognized option '--list-cameras'

**Comment by rom1v** [comment]
1.21 is ultra-old. Use the latest version (currently 2.7).

**Comment by toto6976** [comment]
I install 2.7 version. Everything is ok. Thank you.
