### ISSUE TITLE
Black borders displayed; CTRL+X / double clicking is ignored.

### ISSUE THREAD

**Issue by BrainSlugs83** [Genymobile/scrcpy#548]
Running the following command to launch the 64-bit build linked from `readme.md` on master:

```
:: Insert real serial below
SET SERIAL=-s 0000deadbeef0000
scrcpy-noconsole %SERIAL% -m 1024 -b 4M -n -f -T
```
The window is rendered as full screen, always on top, but there is black bars around all four edges of what's displayed.  Double clicking on any of them or pressing CTRL+X is ignored.  There's no way to stretch the video to fit the screen AFAICT. -- Perhaps this is a documentation bug?  Not sure.

**Comment by BrainSlugs83** [comment]
Nevermind... I realized the black bars on the left and right side are there on the phone (the test video's AR did not match my phone's display)... and since my phone's AR does not match my screen's display, I end up with additional black bars at the top and bottom... -- I can fix this with cropping if I need to.  Please disregard.

**Comment by Leuhan77** [comment]
hello, did you manage to get the black borders out for use with the full screen?

**Comment by rom1v** [comment]
If the device screen and the computer screen don't have the same aspect ratio, either:
 1. you get black borders
 2. you crop one dimension so that the other dimension fits the screen
 3. you stretch the video to fit the screen

Scrcpy always respect aspect ratio, so 3 is not possible.

You could [crop](https://github.com/Genymobile/scrcpy#crop) bottom and top (or left and right) for the capture so that the aspect ratio is the same. Otherwise, you get black borders.

**Comment by Leuhan77** [comment]
> Si la pantalla del dispositivo y la pantalla de la computadora no tienen la misma relación de aspecto, ya sea:
> 
> 1. obtienes bordes negros
> 2. recorta una dimensión para que la otra dimensión se ajuste a la pantalla
> 3. estiras el video para que se ajuste a la pantalla
> 
> Scrcpy siempre conserva la relación de aspecto, por lo que 3 no es posible.
> 
> Puede [recortar la](https://github.com/Genymobile/scrcpy#crop) parte inferior y superior (o la izquierda y la derecha) para la captura de modo que la relación de aspecto sea la misma. De lo contrario, vistas bordes negros.

I am mirroring the secondary screen of a j8 on my pc with scrcpy and it looks complete, can't I do that?

**Comment by Leuhan77** [comment]
I try to do the same as I do on the samsung j8, which is to simulate a secondary screen of 1280x720 213 dpi, this way if I run scrcpy --display, it opens with the entire screen occupied

 but when doing it on my main smartphone when executing scrcpy --display I get a black screen

**Comment by Leuhan77** [comment]
> Si la pantalla del dispositivo y la pantalla de la computadora no tienen la misma relación de aspecto, ya sea:
> 
> 1. obtienes bordes negros
> 2. recorta una dimensión para que la otra dimensión se ajuste a la pantalla
> 3. estiras el video para que se ajuste a la pantalla
> 
> Scrcpy siempre conserva la relación de aspecto, por lo que 3 no es posible.
> 
> Puede [recortar la](https://github.com/Genymobile/scrcpy#crop) parte inferior y superior (o la izquierda y la derecha) para la captura de modo que la relación de aspecto sea la misma. De lo contrario, obtendrá bordes negros.

How can I do the second option?

**Comment by Leuhan77** [comment]
my screen is 720x1600
