### ISSUE TITLE
iOS Safari and other browsers stop video playback after receiving H264 IDR frame over WebRTC

### ISSUE THREAD

**Issue by IAMouMeng** [Genymobile/scrcpy#5485]
Hi, I'm trying to push H264 codec to a web browser by webrtc. However, when starting scrcpy, the first IDR frame sent often doesn't play on the iOS Safari browser. When the screen rotates and the H264 IDR frame is sent again, the video will show. On any browser, when the video plays for 600 frames, scrcpy sends an IDR frame, but the video element stops because of this IDR frame.How to solve this?

**Comment by Meoshiat** [comment]
You going to jail bitch
