### ISSUE TITLE
Failed to load shared libraries libx265.so.209

### ISSUE THREAD

**Issue by G4PLS** [Genymobile/scrcpy#5486]
Didnt find an issue regarding this and it only appeared after updating my system around 2 days ago.

## Environment

 - **OS:** Arch Linux KDE
 - **Scrcpy version:** 2.7-2
 - **Installation method:** Installed with pacman
 - **Device model:** Samsung S24
 - **Android version:** Dont think thats relevant for this issue
 
 Im on kernel 6.11.7-arch1-1

## Describe the bug

```
[gapls@pc-gapls /]$ scrcpy
scrcpy: error while loading shared libraries: libx265.so.209: cannot open shared object file: No such file or directory
```

I looked in my /lib folder and i have a libx265 but its so.212. I already tried removing scrcpy with -Rs and reinstalling but the issue persists. Is this just a "Im stupid rn" issue or an issue with the app itself

**Comment by Genxster1998** [comment]
For now you can just just soft link existing lib as *.209 in same lib till it is updated for scrcpy

**Comment by MangoTCF** [comment]
Nope, I have the same setup(different phone but that doesn't matter), if I symlink the lib, it breaks further down the line with libavcodec not having the x265_api_get_209 symbol

**Comment by G4PLS** [comment]
> Nope, I have the same setup(different phone but that doesn't matter), if I symlink the lib, it breaks further down the line with libavcodec not having the x265_api_get_209 symbol

I did it and got the same thing, just forgot to instantly copy the message and was to lazy to set it up again just to post it on github

**Comment by jurassicjordan** [comment]
what was the fix for this?

**Comment by rom1v** [comment]
Rebuild against your current libraries.
