### ISSUE TITLE
Fails to record if output filename includes colon (":")

### ISSUE THREAD

**Issue by yrtimiD** [Genymobile/scrcpy#5487]
## Environment

 - **OS:** Ubuntu
 - **Scrcpy version:** 2.7
 - **Installation method:** manual
 - **Device model:**
 - **Android version:** 14

## Describe the bug
If the filename specified with `--record` parameter includes colon (`:`) character the app fails to create that file:
```shell
$ scrcpy --no-audio --show-touches --record="`date -Iseconds`.mp4"
scrcpy 2.7 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     --> (tcpip)  emulator-5554                   device  sdk_gphone64_x86_64
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 207.8 MB/s (71200 bytes in 0.000s)
[server] INFO: Device: [Google] google sdk_gphone64_x86_64 (Android 14)
ERROR: Failed to open output file: 2024-11-14T22:57:44+02:00.mp4
ERROR: Recording failed to 2024-11-14T22:57:44+02:00.mp4
```

Such file name is valid on linux and nothing should prevent app from creating it.

**Comment by m7stock** [comment]
The filename is passed to ffmpeg, which interprets it as an URL with a protocol. As a workaround, you can explicitly prepend the file protocol like this:

```
scrcpy --no-audio --show-touches --record="file:`date -Iseconds`.mp4"
```

I'll see if I can contribute a fix for this.
