### ISSUE TITLE
winget manifest require update (stuck on v2.4) 

### ISSUE THREAD

**Issue by welpdx** [Genymobile/scrcpy#5488]
```
C:\>winget search scrcpy
Name      Id                           Version    Match       Source
---------------------------------------------------------------------
scrcpy    Genymobile.scrcpy            2.4                    winget


>winget show Genymobile.scrcpy
Found scrcpy [Genymobile.scrcpy]
Version: 2.4
Publisher: Genymobile
Publisher Url: https://github.com/Genymobile
Publisher Support Url: https://github.com/Genymobile/scrcpy/issues
Author: Genymobile
Moniker: scrcpy
...
Release Notes Url: https://github.com/Genymobile/scrcpy/releases/tag/v2.4
Tags:
  android
  control
  device
  display
Installer:
  Installer Type: portable (zip)
  Installer Url: https://github.com/Genymobile/scrcpy/releases/download/v2.4/scrcpy-win64-v2.4.zip
  Installer SHA256: 9dc56f21bfa455352ec0c58b40feaf2fb02d67372910a4235e298ece286ff3a9
  Release Date: 2024-03-02
  Offline Distribution Supported: true
```

perhaps manifest should be updated to `https://github.com/Genymobile/scrcpy/releases/latest` to always update to the latest?

**Comment by rom1v** [comment]
I'm not in charge of the winget package, it's done by third-party devs.

I recently removed the reference to winget because apparently there were problems: https://github.com/Genymobile/scrcpy/issues/4956#issuecomment-2138768774

**Comment by welpdx** [comment]
Thanks for the quick reply. 

Did some digging, according to [ms docs](https://github.com/microsoft/winget-pkgs/issues/192018), I can create a package update submission as a "community member". I have made a new submission there. https://github.com/microsoft/winget-pkgs/issues/192018

There also is a way to auto update your winget manifest via github workflows. The devs of powertoys and oh-my-posh has been utilizing this so that it updates manifest each time they push out a new release on their github repo"
Using [wingetcreate](https://github.com/microsoft/winget-create):

[PowerToys](https://github.com/microsoft/PowerToys/blob/main/.github/workflows/package-submissions.yml)
[Oh-My-Posh](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/.github/workflows/winget.yml)

Maybe it will take some time to set up but might be worth it for the windows winget users? Thanks again

**Comment by welpdx** [comment]
Oh I see. Winget has issues with accessing dlls due to using symbolic links. 
https://github.com/microsoft/winget-pkgs/issues/166969#issuecomment-2278416009

https://github.com/microsoft/winget-cli/issues/2711
- Looks like there was development here on oct 7th 
- https://github.com/microsoft/winget-cli/issues/2711#issuecomment-2403370806
- Is this fixed then?

**Comment by Meoshiat** [comment]
Going to jail

**Comment by aisgbnok** [comment]
This has been fixed for all versions of the [`Genymobile.scrcpy`](https://github.com/microsoft/winget-pkgs/tree/master/manifests/g/Genymobile/scrcpy) package in [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs), including the latest `3.1` release of scrcpy. scrcpy binaries (dlls, etc.) are now properly added to path through winget. This issue can be closed.

**Comment by welpdx** [comment]
Thanks @aisgbnok! Great work! 
Finally I can upgrade scrcpy just with winget! Yay
Merry Christmas y'all!
