### ISSUE TITLE
Linking failed when i do 'ninja'

### ISSUE THREAD

**Issue by Plandercozeron** [Genymobile/scrcpy#549]
Ubuntu 18.10. Had some C libs related updates (Just saying. I'm not developer at all)
Removed scrcpy and wanted to build it again. Using pre-build *.jar

### When i do `ninja`
I move to `scrcpy/x` and do `ninja`
And get this
 
```
[1/2] Linking target app/scrcpy.
FAILED: app/scrcpy
cc  -o app/scrcpy 'app/app@@scrcpy@exe/src_main.c.o' 'app/app@@scrcpy@exe/src_command.c.o' 'app/app@@scrcpy@exe/src_control_event.c.o' 'app/app@@scrcpy@exe/src_controller.c.o' 'app/app@@scrcpy@exe/src_convert.c.o' 'app/app@@scrcpy@exe/src_decoder.c.o' 'app/app@@scrcpy@exe/src_device.c.o' 'app/app@@scrcpy@exe/src_file_handler.c.o' 'app/app@@scrcpy@exe/src_fps_c
ounter.c.o' 'app/app@@scrcpy@exe/src_frames.c.o' 'app/app@@scrcpy@exe/src_input_manager.c.o' 'app/app@@scrcpy@exe/src_lock_util.c.o' 'app/app@@scrcpy@exe/src_net.c.o' 'app/app@@scrcpy@exe/src_recorder.c.o' 'app/app@@scrcpy@exe/src_scrcpy.c.o' 'app/app@@scrcpy@exe/src_screen.c.o' 'app/app@@scrcpy@exe/src_server.c.o' 'app/app@@scrcpy@exe/src_str_util.c.o' 'app/a
pp@@scrcpy@exe/src_tiny_xpm.c.o' 'app/app@@scrcpy@exe/src_sys_unix_command.c.o' 'app/app@@scrcpy@exe/src_sys_unix_net.c.o' -flto -Wl,--no-undefined -Wl,--as-needed -Wl,-O1 -Wl,--start-group /usr/lib/x86_64-linux-gnu/libavformat.so /usr/lib/x86_64-linux-gnu/libavcodec.so /usr/lib/x86_64-linux-gnu/libavutil.so /usr/lib/x86_64-linux-gnu/libSDL2.so -Wl,--end-group

/usr/bin/ld: //usr/lib/x86_64-linux-gnu/libopenmpt.so.0: undefined reference to `std::random_device::_M_getentropy() const@GLIBCXX_3.4.25'
collect2: error: ld returned 1 exit status
[2/2] Generating scrcpy-server with a custom command.
:server:preBuild UP-TO-DATE
:server:preReleaseBuild UP-TO-DATE
:server:compileReleaseAidl UP-TO-DATE
:server:compileReleaseRenderscript UP-TO-DATE
:server:checkReleaseManifest UP-TO-DATE
:server:generateReleaseBuildConfig UP-TO-DATE
:server:prepareLintJar UP-TO-DATE
:server:mainApkListPersistenceRelease UP-TO-DATE
:server:generateReleaseResValues UP-TO-DATE
:server:generateReleaseResources UP-TO-DATE
:server:mergeReleaseResources UP-TO-DATE
:server:createReleaseCompatibleScreenManifests UP-TO-DATE
:server:processReleaseManifest UP-TO-DATE
:server:splitsDiscoveryTaskRelease UP-TO-DATE
:server:processReleaseResources UP-TO-DATE
:server:generateReleaseSources UP-TO-DATE
:server:javaPreCompileRelease UP-TO-DATE
:server:compileReleaseJavaWithJavac UP-TO-DATE
:server:compileReleaseNdk NO-SOURCE
:server:compileReleaseSources UP-TO-DATE
:server:lintVitalRelease
:server:mergeReleaseShaders UP-TO-DATE
:server:compileReleaseShaders UP-TO-DATE
:server:generateReleaseAssets UP-TO-DATE
:server:mergeReleaseAssets UP-TO-DATE
:server:transformClassesWithDexBuilderForRelease UP-TO-DATE
:server:transformDexArchiveWithExternalLibsDexMergerForRelease UP-TO-DATE
:server:transformDexArchiveWithDexMergerForRelease UP-TO-DATE
:server:mergeReleaseJniLibFolders UP-TO-DATE
:server:transformNativeLibsWithMergeJniLibsForRelease UP-TO-DATE
:server:transformNativeLibsWithStripDebugSymbolForRelease UP-TO-DATE
:server:processReleaseJavaRes NO-SOURCE
:server:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:server:packageRelease UP-TO-DATE
:server:assembleRelease

BUILD SUCCESSFUL in 1s
27 actionable tasks: 1 executed, 26 up-to-date
ninja: build stopped: subcommand failed.
```

### When i do `sudo ninja install`

```
[1/2] Linking target app/scrcpy.
FAILED: app/scrcpy
cc  -o app/scrcpy 'app/app@@scrcpy@exe/src_main.c.o' 'app/app@@scrcpy@exe/src_command.c.o' 'app/app@@scrcpy@exe/src_control_event.c.o' 'app/app@@scrcpy@exe/src_controller.c.o' 'app/app@@scrcpy@exe/src_convert.c.o' 'app/app@@scrcpy@exe/src_decoder.c.o' 'app/app@@scrcpy@exe/src_device.c.o' 'app/app@@scrcpy@exe/src_file_handler.c.o' 'app/app@@scrcpy@exe/src_fps_counter.c.o' 'app/app@@scrcpy@exe/src_input_manager.c.o' 'app/app@@scrcpy@exe/src_lock_util.c.o' 'app/app@@scrcpy@exe/src_net.c.o' 'app/app@@scrcpy@exe/src_recorder.c.o' 'app/app@@scrcpy@exe/src_scrcpy.c.o' 'app/app@@scrcpy@exe/src_screen.c.o' 'app/app@@scrcpy@exe/src_server.c.o' 'app/app@@scrcpy@exe/src_str_util.c.o' 'app/app@@scrcpy@exe/src_tiny_xpm.c.o' 'app/app@@scrcpy@exe/src_stream.c.o' 'app/app@@scrcpy@exe/src_video_buffer.c.o' 'app/app@@scrcpy@exe/src_sys_unix_command.c.o' 'app/app@@scrcpy@exe/src_sys_unix_net.c.o' -flto -Wl,--no-undefined -Wl,--as-needed -Wl,-O1 -Wl,--start-group /usr/lib/x86_64-linux-gnu/libavformat.so /usr/lib/x86_64-linux-gnu/libavcodec.so /usr/lib/x86_64-linux-gnu/libavutil.so /usr/lib/x86_64-linux-gnu/libSDL2.so -Wl,--end-group
lto1: fatal error: bytecode stream in file ‘app/app@@scrcpy@exe/src_main.c.o’ generated with LTO version 4.2 instead of the expected 7.1
compilation terminated.
lto-wrapper: fatal error: cc returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

**Comment by rom1v** [comment]
Did you remove the whole `x` folder, and retried from scratch?

```
meson x --buildtype release --strip -Db_lto=true \
    -Dprebuilt_server=/path/to/scrcpy-server.jar
cd x
ninja
sudo ninja install
```

**Comment by Plandercozeron** [comment]
Yes. I even pulled this repo again  
### Whole log
The Meson build system
Version: 0.47.2
Source dir: /home/andrew/git_projects/scrcpy
Build dir: /home/andrew/git_projects/scrcpy/x
Build type: native build
Project name: scrcpy
Project version: 1.8
Native C compiler: cc (gcc 5.5.0 "cc (Homebrew gcc 5.5.0_4) 5.5.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency libavformat found: YES 58.12.100
Native dependency libavcodec found: YES 58.18.100
Native dependency libavutil found: YES 56.14.100
Native dependency sdl2 found: YES 2.0.8
Configuring config.h using configuration
Build targets in project: 6
Found ninja-1.8.2 at /usr/bin/ninja
[33/33] Linking target app/scrcpy.
FAILED: app/scrcpy 
cc  -o app/scrcpy 'app/app@@scrcpy@exe/src_main.c.o' 'app/app@@scrcpy@exe/src_command.c.o' 'app/app@@scrcpy@exe/src_control_event.c.o' 'app/app@@scrcpy@exe/src_controller.c.o' 'app/app@@scrcpy@exe/src_convert.c.o' 'app/app@@scrcpy@exe/src_decoder.c.o' 'app/app@@scrcpy@exe/src_device.c.o' 'app/app@@scrcpy@exe/src_file_handler.c.o' 'app/app@@scrcpy@exe/src_fps_counter.c.o' 'app/app@@scrcpy@exe/src_input_manager.c.o' 'app/app@@scrcpy@exe/src_lock_util.c.o' 'app/app@@scrcpy@exe/src_net.c.o' 'app/app@@scrcpy@exe/src_recorder.c.o' 'app/app@@scrcpy@exe/src_scrcpy.c.o' 'app/app@@scrcpy@exe/src_screen.c.o' 'app/app@@scrcpy@exe/src_server.c.o' 'app/app@@scrcpy@exe/src_str_util.c.o' 'app/app@@scrcpy@exe/src_tiny_xpm.c.o' 'app/app@@scrcpy@exe/src_stream.c.o' 'app/app@@scrcpy@exe/src_video_buffer.c.o' 'app/app@@scrcpy@exe/src_sys_unix_command.c.o' 'app/app@@scrcpy@exe/src_sys_unix_net.c.o' -flto -Wl,--no-undefined -Wl,--as-needed -Wl,-O1 -Wl,--start-group /usr/lib/x86_64-linux-gnu/libavformat.so /usr/lib/x86_64-linux-gnu/libavcodec.so /usr/lib/x86_64-linux-gnu/libavutil.so /usr/lib/x86_64-linux-gnu/libSDL2.so -Wl,--end-group  
/usr/bin/ld: //usr/lib/x86_64-linux-gnu/libopenmpt.so.0: undefined reference to `std::random_device::_M_getentropy() const@GLIBCXX_3.4.25'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
[1/2] Linking target app/scrcpy.
FAILED: app/scrcpy 
cc  -o app/scrcpy 'app/app@@scrcpy@exe/src_main.c.o' 'app/app@@scrcpy@exe/src_command.c.o' 'app/app@@scrcpy@exe/src_control_event.c.o' 'app/app@@scrcpy@exe/src_controller.c.o' 'app/app@@scrcpy@exe/src_convert.c.o' 'app/app@@scrcpy@exe/src_decoder.c.o' 'app/app@@scrcpy@exe/src_device.c.o' 'app/app@@scrcpy@exe/src_file_handler.c.o' 'app/app@@scrcpy@exe/src_fps_counter.c.o' 'app/app@@scrcpy@exe/src_input_manager.c.o' 'app/app@@scrcpy@exe/src_lock_util.c.o' 'app/app@@scrcpy@exe/src_net.c.o' 'app/app@@scrcpy@exe/src_recorder.c.o' 'app/app@@scrcpy@exe/src_scrcpy.c.o' 'app/app@@scrcpy@exe/src_screen.c.o' 'app/app@@scrcpy@exe/src_server.c.o' 'app/app@@scrcpy@exe/src_str_util.c.o' 'app/app@@scrcpy@exe/src_tiny_xpm.c.o' 'app/app@@scrcpy@exe/src_stream.c.o' 'app/app@@scrcpy@exe/src_video_buffer.c.o' 'app/app@@scrcpy@exe/src_sys_unix_command.c.o' 'app/app@@scrcpy@exe/src_sys_unix_net.c.o' -flto -Wl,--no-undefined -Wl,--as-needed -Wl,-O1 -Wl,--start-group /usr/lib/x86_64-linux-gnu/libavformat.so /usr/lib/x86_64-linux-gnu/libavcodec.so /usr/lib/x86_64-linux-gnu/libavutil.so /usr/lib/x86_64-linux-gnu/libSDL2.so -Wl,--end-group  
lto1: fatal error: bytecode stream in file ‘app/app@@scrcpy@exe/src_main.c.o’ generated with LTO version 4.2 instead of the expected 7.1
compilation terminated.
lto-wrapper: fatal error: cc returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by rom1v** [comment]
There is a problem with LTO, try to not enable it:
```
meson x --buildtype release --strip -Dprebuilt_server=/path/to/scrcpy-server.jar
```

**Comment by rom1v** [comment]
https://techoverflow.net/2017/06/22/how-to-resolve-fatal-error-bytecode-stream-generated-with-lto-version-instead-of-the-expected/

**Comment by Plandercozeron** [comment]
Error appears without LTO.
Had a chance to discuss it with our CPP developer. So as i got it right from his explanation some libraries from dependencies: `libavformat`, `libavcodec`, `libavutil`, `sdl2` are build using different compilators. The thing is that last time i built scrcpy was december and since then i remember i had some updates on this libraries. So i guess it's Ubuntu's fault
Is this helpful information?
Maybe some workaround?  
May i use binary built on another system and put it into `/usr/local/bin/scrcpy`?

**Comment by rom1v** [comment]
> The thing is that last time i built scrcpy was december and since then i remember i had some updates on these libraries.

But if that was the case, you could just rebuild _scrcpy_ against these upgraded dependencies (like #325).

**Comment by Plandercozeron** [comment]
Well, output is kind of similar to what i got without LTO parameter. I will try on fresh Ubuntu on VM then update it and see what happens

**Comment by Plandercozeron** [comment]
Yep, that's weird. Had 18.10 upgraded to 19.04 on my VM and then ran build which have been finished with success. I hope i can use this binary on my real system. Don't want to mess with docker with this one. Maybe i can reinstall libs or do something like this?
### Output 
The Meson build system
Version: 0.49.0
Source dir: /home/andrew/git/scrcpy
Build dir: /home/andrew/git/scrcpy/x
Build type: native build
Project name: scrcpy
Project version: 1.8
Native C compiler: cc (gcc 8.3.0 "cc (Ubuntu 8.3.0-6ubuntu1) 8.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Dependency libavformat found: YES 58.20.100
Dependency libavcodec found: YES 58.35.100
Dependency libavutil found: YES 56.22.100
Dependency sdl2 found: YES 2.0.9
Configuring config.h using configuration
Build targets in project: 6
Found ninja-1.8.2 at /usr/bin/ninja
[33/33] Linking target app/scrcpy.
[sudo] password for andrew: 
[0/1] Installing files.
Installing app/scrcpy to /usr/local/bin
Stripping target 'app/scrcpy'
Installing server/scrcpy-server.jar to /usr/local/share/scrcpy
 inflated: META-INF/MANIFEST.MF
May 27, 2019 12:17:32 AM java.util.jar.Attributes read
WARNING: Duplicate name in Manifest: Manifest-Version.
Ensure that the manifest does not have duplicate entries, and
that blank lines separate individual sections in both your
manifest and in the META-INF/MANIFEST.MF entry in the jar file.
May 27, 2019 12:17:32 AM java.util.jar.Attributes read
WARNING: Duplicate name in Manifest: Built-By.
Ensure that the manifest does not have duplicate entries, and
that blank lines separate individual sections in both your
manifest and in the META-INF/MANIFEST.MF entry in the jar file.
May 27, 2019 12:17:32 AM java.util.jar.Attributes read
WARNING: Duplicate name in Manifest: Created-By.
Ensure that the manifest does not have duplicate entries, and
that blank lines separate individual sections in both your
manifest and in the META-INF/MANIFEST.MF entry in the jar file.

**Comment by Plandercozeron** [comment]
Alright, put `scrcpy` binary that i built on my VM to my real system and it worked. Except it couldn't exec ADB from `/usr/bin` so i had to declare ADB in `.bashrc` with Android SDK path.
