### ISSUE TITLE
Option to disable system decorations on virtual displays

### ISSUE THREAD

**Issue by ubdjshdb** [Genymobile/scrcpy#5494]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
When using virtual displays (via `--new-display --start-app=...`) on Samsung phones (tested on S23, One UI 6.1, Android 14), they render a broken taskbar and home screen (part of Samsung's "New DeX" which is only supposed to be available on tablets but appears here too).

**Describe the solution you'd like**
Add an option to disable `VIRTUAL_DISPLAY_FLAG_SHOULD_SHOW_SYSTEM_DECORATIONS`, which prevents these broken UI elements from rendering.
https://github.com/Genymobile/scrcpy/blob/bd9d93194b04970655b22f1eb96d5ad2bd4f2c75/server/src/main/java/com/genymobile/scrcpy/video/NewDisplayCapture.java#L89

**Additional context**
UI with `VIRTUAL_DISPLAY_FLAG_SHOULD_SHOW_SYSTEM_DECORATIONS` present:
![image](https://github.com/user-attachments/assets/510d567c-7bb6-4f14-8b73-d5aee91ff683)

UI with `VIRTUAL_DISPLAY_FLAG_SHOULD_SHOW_SYSTEM_DECORATIONS` patched out of the scrcpy server code:
![image](https://github.com/user-attachments/assets/16dac3fd-fabb-47e4-a2ba-20d8f9876192)

**Comment by rom1v** [comment]
Makes sense.

Implemented on `glfilter.61`, see https://github.com/Genymobile/scrcpy/pull/5455#issuecomment-2480829957

**Comment by ubdjshdb** [comment]
Closing since it got merged into `dev`.
