### ISSUE TITLE
server/build_without_gradle.sh fails with an error "aidl: No such file or directory"

### ISSUE THREAD

**Issue by Drugoy** [Genymobile/scrcpy#5495]
```
git clone --branch v2.7 'https://github.com/Genymobile/scrcpy.git'
cd ./scrcpy/server/
./build_without_gradle.sh
```
results into
```
Platform: android-34
Build-tools: 34.0.0
Build dir: /github/Genymobile/scrcpy/server/build_manual
Generating java from aidl...
./build_without_gradle.sh: line 48: /build-tools/34.0.0/aidl: No such file or directory
```
https://github.com/Genymobile/scrcpy/blob/v2.7/server/build_without_gradle.sh#L48
seems to be expecting 'aidl' executable to be pre-built, but lacks instructions building it.

As far as I understand: this error is pretty important as it seems to be blocking Debian packages from being released, as Debian package building internal policies forbid downloading files from the internet, so <a href="https://github.com/Genymobile/scrcpy/blob/v2.7/install_release.sh#L9">this approach</a> is a <a href="https://salsa.debian.org/yangfl-guest/scrcpy/-/jobs/6136939#L2737">no go</a> and the server instead has to be built locally.
I expected that running <a href="https://github.com/Genymobile/scrcpy/blob/v2.7/server/build_without_gradle.sh">./server/build_without_gradle.sh</a> would produce a server build, but it fails with said error.

**Comment by rom1v** [comment]
> seems to be expecting 'aidl' executable to be pre-built, but lacks instructions building it.

It is included with the Android SDK. Make sure you have installed Android build-tools 34.

**Comment by Drugoy** [comment]
I see, thanks.
I don't have Android SDK and Debian 12's mainline repo only has Android SDK Platform 33 Installer as the most recent one.

**Comment by rom1v** [comment]
You can set environment variables to override the default values (to point to another SDK version).
