### ISSUE TITLE
ninja failing when executing ninja in x folder

### ISSUE THREAD

**Issue by tonyl9109** [Genymobile/scrcpy#550]
when execute ninja in x folder throws this:

```
The Meson build system
Version: 0.37.1
Source dir: /home/tony/Descargas/scrcpy-master
Build dir: /home/tony/Descargas/scrcpy-master/x
Build type: native build
Project name: scrcpy
Native c compiler: cc (gcc 6.3.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29)
Native dependency sdl2 found: YES 2.0.5
Build targets in project: 6
ninja: error: manifest 'build.ninja' still dirty after 100 tries
```

**Comment by rom1v** [comment]
What if you remove the `x` folder:

    rm -rf x

And retry from scratch?

**Comment by tonyl9109** [comment]
already try it, still gives the same error, it just loop forever and eventually dies

**Comment by Plandercozeron** [comment]
Try `ninja clean` first then run `ninja` again

**Comment by tonyl9109** [comment]
so running  ninja -d explain throws:
ninja explain: output build.ninja older than most recent input ../meson.build (1558694733 vs 1558697112)

it was just a time stamp issue, build.ninja had an older time stamp than mason.build, i just adjust my pc time to an hour later and it run.
