### ISSUE TITLE
Couldn't open audio device

### ISSUE THREAD

**Issue by Suyaris** [Genymobile/scrcpy#5507]
## Environment

 - **OS:** Nobara Linux 40
 - **Scrcpy version:** 2.4
 - **Installation method:** dnf
 - **Device model:** OnePlus 8T+ 5G
 - **Android version:** 14

## Describe the bug

I am unable to run scrcpy without --no-audio and would like to play audio from my PC instead of my device. I have a DAC but do not have a sound capture card.

```
sudo scrcpy --video-codec h265 -K
scrcpy 2.4 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  09bf1d4b                        device  KB2007
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 102.7 MB/s (69007 bytes in 0.001s)
[server] INFO: Device: [OnePlus] OnePlus KB2007 (Android 14)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6.0 NVIDIA 565.57.01
INFO: Trilinear filtering enabled
INFO: Texture: 1080x2400
ERROR: Could not open audio device: ALSA: Couldn't open audio device: Host is down
ERROR: Demuxer error
```

**Comment by Suyaris** [comment]
I use pipewire instead of ALSA. I tried setting the `SDL_AUDIODRIVER` to `pipewire` with no luck.
What are the prerequisites for audio forwarding? Are there any hardware requirements like having a sound capture card instead of a DAC?

**Comment by rom1v** [comment]
> Are there any hardware requirements like having a sound capture card instead of a DAC?

That SDL can open the audio output to play audio.

**Comment by Suyaris** [comment]
I got the audio forwarding to work now.
Setting `SDL_AUDIODRIVER=pipewire` was unnecessary. The cause of the audio issue was running `scrcpy` with `sudo`.
Everything seems to be working as intended once I removed `sudo`
