### ISSUE TITLE
Keyboard shortcut suggestions: take Ctrl+L, Ctrl+T, etc.

### ISSUE THREAD

**Issue by KeronCyst** [Genymobile/scrcpy#551]
On my Bluetooth keyboard, I can type Ctrl+L when in Chrome and it'll select the address bar, just like if I were in Chrome on desktop. I can also type Ctrl+T to open a new tab. Is scrcpy capable of the same thing?

**Comment by lilydjwg** [comment]
scrcpy seems to not support key combinations currently.

**Comment by rom1v** [comment]
_scrcpy_ captures `Ctrl` for its own shortcuts.

**Comment by elig0n** [comment]
I find I need native ctrl+ shortcuts available for things like `termux` .
Maybe a command line parameter or special keyboard escape combination can be implemented to disable scrcpy's shortcuts temporarily so one can use the native ones.

**Comment by rom1v** [comment]
See #555 

I'm working on it (#1446). It will probably be possible in v1.15.

**Comment by rom1v** [comment]
Implemented in v1.15 (#1598).
