### ISSUE TITLE
HID Mouse doesn't work properly with virtual display

### ISSUE THREAD

**Issue by Squaduck** [Genymobile/scrcpy#5527]
## Environment

 - **OS:** OpenSUSE Tumbleweed
 - **Scrcpy version:** 3.0
 - **Installation method:** Manual Build
 - **Device model:** Moto G Power (2022)
 - **Android version:** 12

## Describe the bug

HID mouse appears on the device screen, and not on the virtual display. None of the screen edges lead to the virtual display.

Command I used: `scrcpy --new-display=1280x720 --start-app=org.mozilla.firefox -M`

**Comment by rom1v** [comment]
It depends on the device, see discussions here: https://github.com/Genymobile/scrcpy/pull/5370#issuecomment-2440181130

**Comment by Squaduck** [comment]
Ah. That makes sense
