### ISSUE TITLE
 Can't turn screen off when using a Virtual Display

### ISSUE THREAD

**Issue by NoName50** [Genymobile/scrcpy#5528]
## Environment

 - **OS:** Windows
 - **Scrcpy version:** 3.0
 - **Installation method:** Windows x64 release
 - **Device model:** Xiaomi Poco F5
 - **Android version:** 13

## Describe the bug

run scrcpy with option '--new-display' and '-S'
or press MOD+o after the scrcpy window popup
nothing will happen

**Comment by chopin1998** [comment]
same on Linux...

**Comment by rom1v** [comment]
#5522
