### ISSUE TITLE
Bug: cmdline parm "--forward-all-clicks" prevents start

### ISSUE THREAD

**Issue by pstein** [Genymobile/scrcpy#5532]
I extracted the west scrcpy v3.0 on my Windows 10 system
I connected my Samsung Galaxy Android 14 smartphone via USB cable with my computer.

When I enter now (on CmdPrompt):

`scrcpy-noconsole.vbs --kill-adb-on-close`

The Android screen is shown.

When I enter:

`scrcpy-noconsole.vbs --kill-adb-on-close --forward-all-clicks`

then nothing happens.

Whats wrong?

**Comment by rom1v** [comment]
It does not exist anymore, use --mouse-bind.

Run from the console, you will have the error message.

**Comment by pstein** [comment]
Thank you, but the problem persist:

scrcpy-noconsole.vbs --kill-adb-on-close

works, but

scrcpy-noconsole.vbs --kill-adb-on-close --mouse-bind

works not

**Comment by rom1v** [comment]
> scrcpy-noconsole.vbs --kill-adb-on-close --mouse-bind

You must run `scrcpy`, not `scrcpy-noconsole.vbs`.

And read this doc: https://github.com/Genymobile/scrcpy/blob/master/doc/mouse.md#mouse-bindings

`--mouse-bind=++++`

**Comment by pstein** [comment]
ok, works.
Thank you
