### ISSUE TITLE
how to disable phone screen, but still use it on pc?

### ISSUE THREAD

**Issue by fisforfaheem** [Genymobile/scrcpy#5535]
is it possible?

**Comment by fisforfaheem** [comment]
cant paste it here 
![image](https://github.com/user-attachments/assets/f9109d8d-16a9-4a42-abea-f81410c2fb4c)

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/doc/windows.md#run

**Comment by yohanna64** [comment]
alt o
