### ISSUE TITLE
In Windows, if a full-screen scrcpy window loses focus, the window hides itself.

### ISSUE THREAD

**Issue by jef-pearlman** [Genymobile/scrcpy#554]
In Windows 10, if you are using the full-screen option (either -f on the command line or control-f), and the scrcpy window loses focus, it hides itself.  This is often undesirable: sometimes I want to bring a small window above scrcpy so I can see something.  Even more often, I'm trying to run scrcpy on one monitor and do related work on the other monitor, but this is impossible in full screen mode.  You can work around it somewhat by taking it out of full screen and maximizing the window, though this isn't ideal.

**Comment by rom1v** [comment]
> This is often undesirable.

I agree this can be undesirable. If you apply this patch, you get the behavior you want:

```diff
diff --git a/app/src/scrcpy.c b/app/src/scrcpy.c
index b777b77..b0cc729 100644
--- a/app/src/scrcpy.c
+++ b/app/src/scrcpy.c
@@ -76,6 +76,11 @@ sdl_init_and_configure(bool display) {
     }
 #endif
 
+    // Disable minimize on focus loss
+    if (!SDL_SetHint(SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS, "0")) {
+        LOGW("Could not disable minimize on focus loss");
+    }
+
     // Do not disable the screensaver when scrcpy is running
```

However, I'm not sure we should change the default behavior, because on Alt+tab, it's annoying that _scrcpy_ stays in fullscreen.

**Comment by rom1v** [comment]
> If you don't mind I'd like to say that having the ability to have the full screen window persistent would be a huge addition. Streamers who interact with chat by typing for example are constantly switching focus from games to browser windows and back. Having the window minimize when doing that is quite an issue for such users.

https://www.reddit.com/r/DissidiaFFOO/comments/btsjnu/scrcpy_an_open_source_android_pc_mirroring/epduy2e/

Let's change the behavior. We'll see if there are complaints.
99009f2ef217fa8324f43a91cbcdb06a9968ac46

**Comment by jef-pearlman** [comment]
Not sure if this is good github etiquette, but thanks for the change!  v1.9 working beautifully.

**Comment by nllinux** [comment]
Hello, 

Please can someone tell me exactly how to apply this patch? (I have not applied a patch before, but I'm a quick learner) I am on windows 10 with scrcpy working fine but would love it if full screen would stay on while I am working on the other 3 screens.  
Thanks in advance.

**Comment by rom1v** [comment]
Which scrcpy version do you use? Use the latest.
