### ISSUE TITLE
SCRCPY 3.0 windows 64 pack with Trojan:Script/Wacatac.B!ml detected

### ISSUE THREAD

**Issue by pidobeuliou** [Genymobile/scrcpy#5540]
SCRCPY 3.0 windows 64 pack with Trojan:Script/Wacatac.B!ml detected.
The zip file has ben automatically removed from the computer and placed in quarantaine.

Previous versions of SCRCPY zip files don't include this Trojan:Script/Wacatac.B!ml

**Comment by rom1v** [comment]
#5531
