### ISSUE TITLE
Periodic freezes

### ISSUE THREAD

**Issue by anta999** [Genymobile/scrcpy#5544]
## Environment

 - **OS:**Debian testing
 - **Scrcpy version:** last from github
 - **Installation method:** manual build
 - **Device model:** XIAOMI POCO X3
 - **Android version:** 13

## Describe the bug

There are periodic freezes for a long time, and quite often. This is very annoying. It unfreezes in about 10-15 seconds or the connection drops

```
INFO: ADB device found:
INFO:     --> (tcpip)  192.168.0.76:5555               device  M2102J20SG
INFO: Device already connected via TCP/IP: 192.168.0.76:5555
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 174.7 MB/s (90224 bytes in 0.000s)
[server] INFO: Device: [Xiaomi] POCO M2102J20SG (Android 13)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6.0 NVIDIA 560.35.03
INFO: Trilinear filtering enabled
INFO: Texture: 1080x2400
INFO: Device clipboard copied
```

**Comment by rom1v** [comment]
Does it happen over USB?

Probably the "expected" head-of-line blocking of TCP, when packets are lost. Over TCP/IP, try to reduce the bit rate:

```
scrcpy -m1024 -b 4M
```

**Comment by rom1v** [comment]
Over wifi, this is expected: https://en.wikipedia.org/wiki/Head-of-line_blocking

Scrcpy just transmits the whole stream over TCP over adb, it never attempts to drop network packets. It is designed to work locally over USB, the wireless mode is just a by-product of using adb, but scrcpy is not tailored for this use case. It assumes the connection is reliable.
