### ISSUE TITLE
cant use in android15?

### ISSUE THREAD

**Issue by ESK222** [Genymobile/scrcpy#5548]
i upgrade my pad(xiaomi pad 6s pro),hyperos2(android15),and i found cant use scrcpy,i can use in hyperos1(android14),It is not supported in android15？bad english+_+
![Screenshot_2024-11-27-22-52-44-089_com android se](https://github.com/user-attachments/assets/433f87c4-96c8-41df-8b68-77a38577403b)

**Comment by rom1v** [comment]
When you execute `scrcpy` from a console, what is the error message?

https://github.com/Genymobile/scrcpy/blob/master/doc/windows.md#run

**Comment by ESK222** [comment]
I used it directly until a Chinese user created a controller based on Scrcpy, which may not support Android 15.
I opened scrcpy directly and found that it can be used. Thank you
