### ISSUE TITLE
support passing in Home and Ctrl-x keys

### ISSUE THREAD

**Issue by lilydjwg** [Genymobile/scrcpy#555]
When I press the `End` key, my cursor jumps to the end of line. But when I press the `Home` key, it returns to the home screen instead of jumping to the start of line.

Key combinations like Ctrl-sth don't work either.

I suggest adding an option to enable all of this, and make scrcpy-specific keys prefixed by a certain key (e.g. the host key in Virtualbox, or the prefix key in screen / tmux).

Even better, can you emulate the keyboard as a physical keyboard (like physically connected to the phone).

This kind of improvements will make typing in scrcpy easiler because the user will not need to switch between mouse and keyboard that often.

**Comment by leiserfg** [comment]
It it will be pretty useful for using termux.

**Comment by rom1v** [comment]
> But when I press the Home key, it returns to the `home` screen instead of jumping to the start of line.

Fixed by 5d473efeb5c4f42a75aad6ab5892e2813358c0c9.

**Comment by rom1v** [comment]
What do you think about #1446 to solve this problem?

**Comment by rom1v** [comment]
Fixed by #1598.
