### ISSUE TITLE
Virtual screen error in IQOO NEO 6

### ISSUE THREAD

**Issue by kalKestis19** [Genymobile/scrcpy#5552]
I am using IQOO NEO 6, with scrcpy windows latest release on windows 11. 
I am on android 14 and the normal mirroring works fine, but the virtual display option brings up just a white screen, as seen in the video below. 
Also one thing to mention, when using the virtual display mode to launch a specific app from the terminal, that works just fine.

https://github.com/user-attachments/assets/37a0f70b-510e-4da8-b12d-3ddcc8801ba1

**Comment by rom1v** [comment]
Some devices have no "launcher" for virtual displays. In that case, you must start an app in the virtual display (that app mah be a custom launcher).

**Comment by kalKestis19** [comment]
What launcher would you recommend

**Comment by rom1v** [comment]
You may use your default launcher (find it in `scrcpy --list-apps`).

Or you can use for example this open source launcher (Fossify Launcher, available on F-Droid): https://f-droid.org/en/packages/org.fossify.home/

**Comment by ACodeHX** [comment]
> You may use your default launcher (find it in `scrcpy --list-apps`).您可以使用默认启动器（在`scrcpy --list-apps`中找到它）。
> 
> Or you can use for example this open source launcher: Fossify Launcher, available on F-Droid (https://f-droid.org/en/packages/org.fossify.home/)或者您可以使用例如这个开源启动器：Fossify Launcher，可在 F-Droid 上使用（ https://f-droid.org/en/packages/org.fossify.home/ ）

OS: Windows 23h2
Scrcpy version: 3.0
Device model: realme GT Neo5 SE
Android version: 14


No matter whether I use Fossify Launcher or set it as the default home screen, the display is still like this:
![Snipaste_2024-11-30_22-42-50](https://github.com/user-attachments/assets/602b1dd2-70a9-47f8-aa0e-9ea86add1fef)

**Comment by rom1v** [comment]
Even with:

```bash
scrcpy --no-vd-system-decorations --start-app=org.fossify.home
```

?

**Comment by ACodeHX** [comment]
> Even with:
> 
> ```shell
> scrcpy --no-vd-system-decorations --start-app=org.fossify.home
> ```
> 
> ?

This works now.
![Snipaste_2024-11-30_22-57-13](https://github.com/user-attachments/assets/b7a9d769-e354-4893-ad0a-8439a7d763ab)
