### ISSUE TITLE
Google Pixel 7 Pro not connecting

### ISSUE THREAD

**Issue by BerndSx** [Genymobile/scrcpy#5556]
Hello,
I just found your app which I would use for explaiing the smartphone to older people.
I'm using a Google Pixel 7 Pro and already enabled the USB-Debug mode.
Starting your bat-file ends up with this error:
ERROR: Could not find any ADB device
ERROR: Server connection failed
Press Enter to continue...
Can you help me?

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#device-not-detected
