### ISSUE TITLE
Gamepads: cannot use LT/RT or L2/R2

### ISSUE THREAD

**Issue by tuevudeptrai** [Genymobile/scrcpy#5559]
btw I've saw someone have this problem, ask in nov or sum but I don't know anything about what you guys have been saying cause my knowlegde in technology is very poorly, so please help me.

Window 10

Scrcpy version 3.0
installation method: through the release
Device model: Xiaomi mi 10 (tho I don't think this is important)
Android version: 13

IDK if this is a bug, but I can't us L2/R2 or LT/RT (I've using UHID, AOA idk why but I can't use that it keep saying )

ERROR: Could not find any USB device

I use a general controller and then use reWasd to mapping key use it like a DS4 or Xbox controller. (this is where I think the AOA have problem because the AOA don't support wireless gamepad, but I've disable reWasd and try again but it keep saying it again)

Althought I've wanderring in like 3-4 days in reddit and search every Github (almost) I've come across the LHLaurini, Yume-Chan, and the even the #5362 Rom1v version of CRCPY, but I don't know how to install LHLaurini and Yume-chan version (I'm very sorry for my poor english and knowlegde in Technology) the #5362 Rom1v version althought I've install it, but I can't use the right joystick anymore sadly

Please help me. please fix that or help me with how to install LHLaurini version or something like that

**Comment by tuevudeptrai** [comment]
even the generic gamepad L2/R2 still aren't working

**Comment by tuevudeptrai** [comment]
and please help me with the LHLaurini Scrcpy install, I can't install it

**Comment by rom1v** [comment]
Please test #5623.

**Comment by rom1v** [comment]
Please confirm that https://github.com/Genymobile/scrcpy/pull/5623#issuecomment-2525251847 fixes all your problems with gamepads.

**Comment by tuevudeptrai** [comment]
work like a charm, thanks you, I was off for a few day sorry I haven't replied soon
