### ISSUE TITLE
how i can disable mobile screen while using on PC?

### ISSUE THREAD

**Issue by pushpak1300** [Genymobile/scrcpy#556]
i want to disable my mobile screen while using it on Windows. how i can do that?

**Comment by rom1v** [comment]
Not implemented yet. See https://github.com/Genymobile/scrcpy/issues/175#issuecomment-473412085.

**Comment by rom1v** [comment]
Implemented on `dev` by 12a3bb25d39037931f577dc0165b3e517aad92df.
