### ISSUE TITLE
About Scrcpy3.0 support for Intel Macs 

### ISSUE THREAD

**Issue by YanYiGe2023** [Genymobile/scrcpy#5569]
Since Scrcpy3.0, the macOS version has been downloaded in Releases, so you don't need to compile it yourself, but it doesn't work with Intel processor Macs.

I wish I could add a build of Intel Mac. It's just too much of a pain to install in Homebrew
Thank you

**Comment by rom1v** [comment]
It's implemented on`dev` branch: #5526.

The next release will include a build for macOS-x86_64.

**Comment by YanYiGe2023** [comment]
> 它在分支上实现： #5526。`dev`
> 
> 下一个版本将包括 macOS-x86_64 的构建版本。

谢谢

**Comment by YanYiGe2023** [comment]
> It's implemented on`dev` branch: #5526.
> 
> The next release will include a build for macOS-x86_64.

Thank you
