### ISSUE TITLE
Security Warning Upon Downloading Scrcpy Version 3.0

### ISSUE THREAD

**Issue by zcoriander** [Genymobile/scrcpy#5570]
![图片](https://github.com/user-attachments/assets/6de71249-f6e6-4051-8a97-ff93f3555225)
Dear Scrcpy Development Team,
I am writing to inform you of an issue I encountered while attempting to update my Scrcpy software to the latest version, 3.0. It has been some time since I last used Scrcpy, and as I plan to use it again in the future, I decided to check for updates.
Upon finding that version 3.0 is available, I proceeded with the download. However, after downloading the file for version 3.0, a warning was triggered by my security center, alerting me to a potential threat. This unexpected behavior from a reputable tool like Scrcpy has raised concerns about the safety of the downloaded file.
I understand that new versions of software can sometimes trigger false positives in antivirus programs due to their unfamiliarity or because they contain code that looks suspicious to less sophisticated detection algorithms. Nonetheless, such warnings can be alarming to users and may deter them from using the updated software.
To ensure the safety and trustworthiness of the Scrcpy project, I would appreciate it if you could look into this matter. If there are any known issues with the distribution of version 3.0, please provide guidance on how to proceed safely. Additionally, if possible, please consider submitting the new version to various antivirus vendors for whitelisting, which can help prevent similar warnings in the future.
Thank you for your attention to this matter. I look forward to your response and hope to continue using Scrcpy with confidence.
Best regards,
Date: November 30, 2024

**Comment by rom1v** [comment]
Duplicate of #5540.

**Comment by rom1v** [comment]
Duplicate of #5531.
