### ISSUE TITLE
The virtual display is awesome! Can I make it run Samsung Dex Launcher instead of the stock Launcher?

### ISSUE THREAD

**Issue by zr0fve** [Genymobile/scrcpy#5577]
When I connect an HDMI cable to my samsung phone, it defaults to Samsung Dex Launcher on the output display. I wonder if I could somehow do the same with scrcpy virtual display?

I tried a few things:

I also tried launching Samsung Dex via Phone app and I only can get upto the starting logo then black screen:
![image](https://github.com/user-attachments/assets/fd7c272d-bd17-4dc0-8e92-767f8fabc0ae)

I also tried the following:
```scrcpy.exe -b 20M --max-size=1920 -Sw -t --prefer-text --max-fps=60 --window-title Android --new-display=1920x1080/420 --video-codec=h265 --no-vd-system-decorations --start-app=com.sec.android.app.desktoplauncher
scrcpy 3.0 <https://github.com/Genymobile/scrcpy>
C:\Users\user\Downloads\srcpy\scrcpy-win64-v3.0\scrcpy-se... file pushed, 0 skipped. 89.7 MB/s (90224 bytes in 0.001s)
[server] INFO: Device: [samsung] samsung SM-S918B (Android 14)
[server] INFO: New display: 1920x1080/420 (id=37)
INFO: Renderer: direct3d
INFO: Texture: 1920x1080
[server] INFO: Starting app "Samsung DeX home" [com.sec.android.app.desktoplauncher] on display 37...
[server] WARN: Cannot create launch intent for app com.sec.android.app.desktoplauncher

**Comment by zr0fve** [comment]
@parkerlreed  Thank you! I'll close this question. I think `--display-id` serves the purpose I want. I double checked the docs but totally missed this

**Comment by azkadev** [comment]
this is really amazing, but it doesn't work for the default launcher, i tried to make my own desktop launcher and finally it works without any problems

**Comment by parkerlreed** [comment]
> this is really amazing, but it doesn't work for the default launcher, i tried to make my own desktop launcher and finally it works without any problems

What did you end up doing?

**Comment by hrachkovinovoto** [comment]
> > this is really amazing, but it doesn't work for the default launcher, i tried to make my own desktop launcher and finally it works without any problems
> 
> What did you end up doing?

hyperdroid on the app store (free) works pretty good as a launcher with virtual display to access everything else on my phone. I created a .bat file and added these to make it work. My phone is a moto g100 which has ready-for but unfortunately just like the samsung dex users we cannot access it without an hdmi dummy so this is our only alternative for now and I am glad it exists: 
scrcpy.exe  -b 25M --new-display=1920x1080 --start-app=com.binary.hyperdroid

**Comment by MetalGearSolidNerd** [comment]
> hyperdroid on the app store (free) works pretty good as a launcher with virtual display to access everything else on my phone. I created a .bat file and added these to make it work. My phone is a moto g100 which has ready-for but unfortunately just like the samsung dex users we cannot access it without an hdmi dummy so this is our only alternative for now and I am glad it exists: scrcpy.exe -b 25M --new-display=1920x1080 --start-app=com.binary.hyperdroid

I tried out hyperdroid and it kind off works but is there a way to maximize/minimize apps and access recent apps using hyperdroid. I could not find anything. Basically hyperdroid does not seem to be starting apps in freeform mode.

An alternative launcher is SmartDock which can be found on F-Droid.
