### ISSUE TITLE
recod file video

### ISSUE THREAD

**Issue by toto6976** [Genymobile/scrcpy#5583]
Good morning,

I use scrcpy on linux. When I run the scrcpy --record=file.mp4 command, where is the video file saved? 
```

$ scrcpy --record=file.mp4 --tcpip=192.168.1.14:5555
scrcpy 2.5 <https://github.com/Genymobile/scrcpy>
INFO: Connecting to 192.168.1.14:5555...
INFO: Connected to 192.168.1.14:5555
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 60.3 MB/s (69624 bytes in 0.001s)
[server] INFO: Device: [LGE] lge LG-H870 (Android 14)
INFO: Recording started to mp4 file: file.mp4
[server] ERROR: Could not create default audio encoder for opus
List of audio encoders:
    --audio-codec=aac --audio-encoder='OMX.google.aac.encoder'
    --audio-codec=flac --audio-encoder='OMX.google.flac.encoder'
[server] ERROR: Exception on thread Thread[audio-encoder,5,main]
java.lang.IllegalArgumentException: Failed to initialize audio/opus, error 0xfffffffe (NAME_NOT_FOUND)
        at android.media.MediaCodec.native_setup(Native Method)
        at android.media.MediaCodec.<init>(MediaCodec.java:2094)
        at android.media.MediaCodec.<init>(MediaCodec.java:2072)
        at android.media.MediaCodec.createEncoderByType(MediaCodec.java:2027)
        at com.genymobile.scrcpy.AudioEncoder.createMediaCodec(AudioEncoder.java:289)
        at com.genymobile.scrcpy.AudioEncoder.encode(AudioEncoder.java:181)
        at com.genymobile.scrcpy.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-AudioEncoder(AudioEncoder.java:121)
        at com.genymobile.scrcpy.AudioEncoder$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:1012)
INFO: Renderer: opengl
INFO: OpenGL version: 3.3 (Compatibility Profile) Mesa 24.1.3-2
INFO: Trilinear filtering enabled
WARN: Demuxer 'audio': stream explicitly disabled by the device
WARN: Audio stream recording disabled
INFO: Texture: 1440x2880
INFO: Recording complete to mp4 file: file.mp4
WARN: Killing the server...
```

**Comment by rom1v** [comment]
> When I run the scrcpy --record=file.mp4 command, where is the video file saved?

It is saved in the current directory (since you passed a relative path). Type `pwd` to know what is the current directory.

> java.lang.IllegalArgumentException: Failed to initialize audio/opus, error 0xfffffffe 

Your device has no OPUS encoder, so you must run:

```
scrcpy --audio-codec=aac --record=file.mp4
```

**Comment by toto6976** [comment]
i don't want to record audio

it was in my home file .
Thank you

**Comment by rom1v** [comment]
> i don't want to record audio

OK, then you can disable it with `--no-audio` (but on your device without OPUS encoder, the effect is the same).

**Comment by toto6976** [comment]
something else: when I go through an ssh tunnel, the .mp4 file is saved on the server or on the PC from which I opened the tunnel?

**Comment by rom1v** [comment]
It is saved on the client side (where scrcpy is running).

**Comment by toto6976** [comment]
I can't find any traces of the mp4 file on the smartphone. Is it only on the PC?

**Comment by rom1v** [comment]
Yes, it is only recorded on the PC.

**Comment by toto6976** [comment]
Ah...OK I didn't understand everything

Le mar. 3 déc. 2024, 14:45, Romain Vimont ***@***.***> a
écrit :

**Comment by toto6976** [comment]
so the mp4 file is saved on the smartphone and transferred to the PC?

**Comment by rom1v** [comment]
> so the mp4 file is saved on the smartphone and transferred to the PC?

No, it is not saved on the smartphone. The client on the PC receives each compressed frames individually, and it muxes them locally to mp4 or mkv (along with audio packets).

**Comment by rom1v** [comment]
> You must therefore ensure that there is sufficient space on the smartphone.

No, it is not recorded on the smartphone!

The file is created completely on the computer. The device just sends compressed packets frame by frame to the client that it decodes and plays if playback is enabled on one hand, and muxes to a file if recording is enabled on the other hand: https://github.com/Genymobile/scrcpy/blob/master/doc/develop.md#video-and-audio-streams

**Comment by rom1v** [comment]
No, scrcpy records one file per session. You can split it afterwards witv FFmpeg as you like.

**Comment by toto6976** [comment]
Is there a default limit for the file created?

**Comment by rom1v** [comment]
No.

**Comment by toto6976** [comment]
I thought that the 'time-limit' only concerned mirroring and not recording!
