### ISSUE TITLE
Creating a shortcut for Scrcpy

### ISSUE THREAD

**Issue by 2635599** [Genymobile/scrcpy#559]
i have downloaded the zip archive and installed the unofficial snap and with neither i can create a simple shortcut to run it. all i can do is launch konsole and enter scrcpy to run it from there. can someone please walk me through creating a shortcut for scrcpy i can place on the startmenu? thanks

KDE Neon 64 Bit On Kernel 5.1, 430 nVidia Driver
Asus 970 Gaming/Aura, AMD FX 6300, 16Gig DDR3, 
Samsung 120Gig 850 EVO, AOC 29" Ultra Wide 2560x1080, nVidia 750Ti,
USB 3 Card, Drives 2TB, 1.5TB, 1TB / 750Gig, 500Gig

**Comment by rom1v** [comment]
> i have downloaded the zip archive

It's for Windows.

> and installed the unofficial snap and with neither i can create a simple shortcut to run it.

Why?

What is the result of `which scrcpy`?

**Comment by 2635599** [comment]
the result is: /snap/bin/scrcpy

as for the zip it is meant for linux. i downloaded it, extracted it, moved the folder where i wanted it, opened konsole from it's folder, typed in scrcpy, it launched the modules it needed and ran perfectly. i only did the snap cause after doing a search of the system i could not find a file to either copy or link to the desktop. after installing the snap i did another search and still no launcher found.

**Comment by rom1v** [comment]
> as for the zip it is meant for linux

Which zip are you talking about? I thought it was the one linked in the [README](https://github.com/Genymobile/scrcpy/blob/master/README.md#windows).

> the result is: /snap/bin/scrcpy

What happens if you create a link pointing to `/snap/bin/scrcpy`?

(I had never used snap, so I don't really know)

**Comment by 2635599** [comment]
i will check again for a shortcut and let you know.

before i forget great program. i like the fact that i don't have to install it on the phone and it actually will play my video from the phone unlike visor.

**Comment by 2635599** [comment]
o.k. this is what i get when i go to the snap folder:  /home/mrgrimm/snap/scrcpy/ : there is no bin folder, and i do have show hidden files on.

![no bin](https://user-images.githubusercontent.com/22320686/58437201-c66fe500-807d-11e9-83f4-cf40824758ec.png)

**Comment by rom1v** [comment]
Not `/home/mrgrimm/snap/scrcpy`, but `/snap/bin/scrcpy`.

**Comment by 2635599** [comment]
LOL of course i looked at the wrong branch. that works perfectly. thanks ever so much, greatly appreciated.
