### ISSUE TITLE
Launcher on virtual display

### ISSUE THREAD

**Issue by osimon72** [Genymobile/scrcpy#5592]
Hi, 
thanks 1st for the great app. I love it and starte to to use the virtual display. great add-on.
Unfortunately I see only a dot and when pressing on it I get a orange box with some very small text input field. No idea how to use it.
Perhaps there is some sizing issue. Would love to get some hint how to use it to avoid opening wiht only one app via command line.
![17332967101626384280262377883265](https://github.com/user-attachments/assets/4ad8bcc6-2e21-483f-968e-8efab3fbe0c6)

Br, Oliver

**Comment by rom1v** [comment]
On devices where the "launcher" is broken, you should run without [system decorations](https://github.com/Genymobile/scrcpy/blob/master/doc/virtual_display.md#system-decorations) and start an app:

```
scrcpy --no-vd-system-decorations --start-app=…
```

For example, the app you're starting may be a launcher (e.g. [Fossify Launcher](https://f-droid.org/fr/packages/org.fossify.home/)):

```
scrcpy --no-vd-system-decorations --start-app=org.fossify.home
```
