### ISSUE TITLE
Adding "-e" param doesn't let you choose the tcpip device in case of multiple device attached

### ISSUE THREAD

**Issue by Morteza-Rastgoo** [Genymobile/scrcpy#5593]
[FAQ]: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md is mentioned that you can select the device but it doesn't quiet work if you have two or more devices connected to tcpip
[issues]: https://github.com/Genymobile/scrcpy/issues  not exact match found in the issues so I'll create a new one.

## Environment

 - **OS:**  macOS.
 - **Scrcpy version:** 3.0 
 - **Installation method:** brew
 - **Device model:** Any
 - **Android version:** 13 or any other version

## Describe the bug

Try to connect to one of many tcpip devices attached and you'll get the following error and not able to connect to the desired device

```
morteza@computer adb_scripts % scrcpy -e
scrcpy 3.0 <https://github.com/Genymobile/scrcpy>
ERROR: Multiple (2) ADB devices over TCP/IP:
ERROR:     --> (tcpip)  192.168.2.3:1234             device  Volvo_XC40
ERROR:     --> (tcpip)  emulator-5556                   device  Volvo_GAS_Moose_Emulator
ERROR: Select a device via -s (--serial), -d (--select-usb) or -e (--select-tcpip)
ERROR: Server connection failed
morteza@computer adb_scripts % scrcpy -e 192.168.2.3:1234
scrcpy 3.0 <https://github.com/Genymobile/scrcpy>
2024-12-04 11:05:17.319 scrcpy[64475:4011423] ERROR: Unexpected additional argument: 192.168.2.3:1234
morteza@computer adb_scripts % scrcpy -e "192.168.2.3:1234"
scrcpy 3.0 <https://github.com/Genymobile/scrcpy>
2024-12-04 11:05:28.703 scrcpy[64528:4011897] ERROR: Unexpected additional argument: 192.168.2.3:1234
morteza@computer adb_scripts % scrcpy --select-tcpip "192.168.2.3:1234"
scrcpy 3.0 <https://github.com/Genymobile/scrcpy>
2024-12-04 11:08:58.187 scrcpy[65300:4020097] ERROR: Unexpected additional argument: 192.168.2.3:1234
```

**Comment by rom1v** [comment]
`-e` is only for "the device connected over TCP/IP (if there is exactly one)".

If there are more devices, you need `-s`: https://github.com/Genymobile/scrcpy/blob/master/doc/connection.md#selection

**Comment by Morteza-Rastgoo** [comment]
Correct! Confused by tcpip. Thanks!
