### ISSUE TITLE
Audio outputting only on 1 side (left in my case)

### ISSUE THREAD

**Issue by Likver** [Genymobile/scrcpy#5595]
## Environment

 - **OS:** Windows 8.1
 - **Scrcpy version:** 3.0
 - **Installation method:** Windows release
 - **Device model:** ZTE Blade A51
 - **Android version:** 11

## Describe the bug

Audio output can only be heard on 1 side, doesnt matter which codec i use.

https://github.com/user-attachments/assets/3b9cfe72-c925-485b-9fed-11c5c24bd2ba

I am using an usb connection if that is relevant.

**Comment by rom1v** [comment]
I'm not sure to understand. There is sound on both sides on your video (maybe with a higher volume on the left, but it probably depends on how you recorded it and your computer settings).

If you record with `scrcpy --record=file.mp4`, how is the audio in the recorded file?

**Comment by Likver** [comment]
i uh... feel really dumb right now

so the "issue" was just that i had the audio balance all the way to the left side in my phone's audio equalizer, it is that way for when i am using the phone's speakers, and it automatically changes to neutral balance when i connect a headphones, didnt think about that xd

sorry
