### ISSUE TITLE
V4L Loopback fails to write header data.

### ISSUE THREAD

**Issue by KtheVeg** [Genymobile/scrcpy#5597]
## Environment

 - **OS:** Arch Linux `6.11.6-arch1-1`
 - **Scrcpy version:** 3.0
 - **Installation method:** Downloaded from Github Releases page
 - **Device model:** SM-G973W (Samsung Galaxy S10)
 - **Android version:** 12

## Describe the bug

When attempting to stream my phone screen/camera to `/dev/videoN`, ffmpeg shows an "Invalid ioctl for device" error, and attempting to run `v4l2-ctl --list-devices` results in the error `Unable to detect what device /dev/video0 is, exiting.`

The video playback window appears perfectly functional, however. Only the v4l loopback is failing to work properly.

The command I'm running is `sudo scrcpy --v4l2-sink=/dev/video0 --video-codec=h264`, which results in the following output:
```
scrcpy 3.0 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  -----------                     device  SM_G973W
./scrcpy-server: 1 file pushed, 0 skipped. 142.7 MB/s (90224 bytes in 0.001s)
[server] INFO: Device: [samsung] samsung SM-G973W (Android 12)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6.0 NVIDIA 565.57.01
INFO: Trilinear filtering enabled
INFO: v4l2 sink started to device: /dev/video0
INFO: Texture: 1440x3040
ERROR: [FFmpeg] ioctl(VIDIOC_G_FMT): Inappropriate ioctl for device
ERROR: Failed to write header to /dev/video0
WARN: Could not send packet to v4l2 sink
ERROR: Could not send frame to v4l2 sink
```
(No further output, but scrcpy still sends video output to the playback window)

Running the exact same command without sudo results in this output:
```
scrcpy 3.0 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  R38MB046ZNM                     device  SM_G973W
./scrcpy-server: 1 file pushed, 0 skipped. 149.8 MB/s (90224 bytes in 0.001s)
[server] INFO: Device: [samsung] samsung SM-G973W (Android 12)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6.0 NVIDIA 565.57.01
INFO: Trilinear filtering enabled
ERROR: Failed to open output device: /dev/video0
INFO: Texture: 1440x3040
ERROR: Demuxer error
ERROR: Demuxer 'audio': stream disabled due to connection error
```
(This quits without showing any playback window)

I've installed [`v4l2loopback-dkms`](https://archlinux.org/packages/extra/any/v4l2loopback-dkms/) and [`ffmpeg`](https://archlinux.org/packages/extra/x86_64/ffmpeg/).

**Comment by rom1v** [comment]
> v4l2-ctl --list-devices results in the error Unable to detect what device /dev/video0 is, exiting.

Weird. video0 is typically your webcam (not a v4l2 sink).

Did you execute `sudo modprobe v4l2loopback`? https://github.com/Genymobile/scrcpy/blob/master/doc/v4l2.md

> sudo scrcpy --v4l2-sink=/dev/video0 --video-codec=h264

(btw, never run `scrcpy` with `sudo`)

**Comment by KtheVeg** [comment]
> Weird. video0 is typically your webcam (not a v4l2 sink).
I'm trying to use scrcpy with v4l2 to use as a webcam. I don't have any other webcams.

> Did you execute sudo modprobe v4l2loopback? https://github.com/Genymobile/scrcpy/blob/master/doc/v4l2.md
Yes, I loaded v4l2loopback using modprobe. I used lsmod and it showed up on the list.

> (btw, never run scrcpy with sudo)
As for using sudo, it wouldn't even start without sudo when trying to use v4l2loopback. If I omitted anything related to v4l, it'd work without sudo. I got further using sudo, because at least I can see it show up in the playback window, but it still showed the errors.

**Comment by rom1v** [comment]
`v4l2-ctl --list-devices` results in the error `Unable to detect what device /dev/video0 is, exiting.`

It should report something similar to this:

```console
$ v4l2-ctl --list-devices
Dummy video device (0x0000) (platform:v4l2loopback-000):
	/dev/video2
…
```

**Comment by KtheVeg** [comment]
> It should report something similar to this:

Nope, outputs `Cannot open device /dev/video0, exiting.` instead

**Comment by rom1v** [comment]
> Nope, outputs Cannot open device /dev/video0, exiting. instead (when using /dev/video2 instead of video0)

(you should use `/dev/video0` if your device is video0, on my computer video0 is the webcam, and v4l2loopback creates `/dev/video2`).

You have a problem with your v4l2loopback if `v4l2-ctl` cannot even list the device.

**Comment by KtheVeg** [comment]
I've reinstalled all v4l2loopback packages, and still nothing. I don't think it's v4l2loopback, because ffmpeg seemed to not be too happy with it. Unless ffmpeg takes the output of v4l2loopback then pipes into another place. What else could be the issue? What other things can I try?

**Comment by rom1v** [comment]
If `v4l2-ctl` cannot list your device, the problem is v4l2, not ffmpeg.

Did you try rebooting after installing v4l2-loopback? (don't know if it's necessary, but since it's a kernel module…)

**Comment by KtheVeg** [comment]
Ok, I've made it work. I didn't realize that the kernel modules wasn't persisting across reboots. It works now, I had to reinstall, reboot, then reinsert the module using modprobe. I tried rebooting before but probably forgot to re-add the module. Thanks for the assist nonetheless

**Comment by Caitex212** [comment]
My solution:
```
sudo v4l2loopback-ctl add -n "Webcam" /dev/video1
```
