### ISSUE TITLE
Version display for 3.0.1

### ISSUE THREAD

**Issue by dmagician038** [Genymobile/scrcpy#5602]
## Environment

 - **OS:**                               Windows
 - **Scrcpy version:**             3.0.1
 - **Installation method:**     Manual by zip
 - **Device model:**              SGS22
 - **Android version:**          14

## Describe the bug

`scrcpy --version` printing ver 3.0, Should it report 3.0.1 (although it is minor version change)?

### Output of `scrcpy --version`

```
scrcpy 3.0 <https://github.com/Genymobile/scrcpy>

Dependencies (compiled / linked):
 - SDL: 2.30.9 / 2.30.9
 - libavcodec: 61.19.100 / 61.19.100
 - libavformat: 61.7.100 / 61.7.100
 - libavutil: 59.39.100 / 59.39.100
 - libusb: - / 1.0.27
```

**Comment by rom1v** [comment]
Oops, the commit upgrading the version was left on another branch…

**Comment by dmagician038** [comment]
Ok, happens to the best ones (from personal experience)

😊
