### ISSUE TITLE
scrcpy not being maintained in Homebrew?

### ISSUE THREAD

**Issue by jpage4500** [Genymobile/scrcpy#5603]
Hi, I installed scrcpy on my Mac (M1) via homebrew but noticed it hasn't gotten an update in a while.. at least if I'm reading it right the version in [Homebrew](https://formulae.brew.sh/formula/scrcpy) is 3.0. 

I personally like using homebrew since it's pretty easy to manage updates.. but, I'll move over to downloading from github if necessary.. 

https://github.com/Genymobile/scrcpy/blob/master/doc/macos.md#from-a-package-manager

```
~/Downloads$ brew upgrade scrcpy
Warning: scrcpy 2.5 already installed
```

**Comment by rom1v** [comment]
`brew update`, I guess?

**Comment by jpage4500** [comment]
I'm going to close this issue sorry.. for some dumb reason I thought 3.0 was really out of date but it's only 1 week. I noticed a new version just pushed - tried to update to it via homebrew and nothing happened.. clearly it's not really out of date in any way.. sorry!
