### ISSUE TITLE
audiobuffer and videobuffer for virtual display

### ISSUE THREAD

**Issue by imGrooti** [Genymobile/scrcpy#5610]
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rom1v** [comment]
`--video-buffer` and `--audio-buffer` work on the client side, regardless of which display (or even camera) it renders.

**Comment by imGrooti** [comment]
my mistake . i didn't check the display-buffer is changed to video-buffer
