### ISSUE TITLE
Overlay app not registering clicks in 3.0.2

### ISSUE THREAD

**Issue by LoreleiCasswell** [Genymobile/scrcpy#5616]
## Environment

 - **OS:** Windows 10 Pro
 - **Scrcpy version:** 3.0, 3.0.2
 - **Installation method:** Windows release
 - **Device model:** Pixel 8
 - **Android version:** 15

## Describe the bug

I use an app called Poke Genie that creates an overlay over Pokémon Go and uses the screen recording API to calculate information about Pokémon not normally shown. When scanning, this app should update every time you click behind it, so that the overlay constantly updates with new details. In scrcpy 3, it doesn't update unless I interact with the overlay directly. It seems like Poke Genie isn't aware of the clicks for some reason. Tapping the phone's display directly while scrcpy 3 is open results in expected behavior.

The first video shows expected behavior recorded in scrcpy 2.7. The overlay updates as I move through Pokémon.

https://github.com/user-attachments/assets/5bee8ac3-9ec0-4f42-9bcc-ac81284bfce6

This video is recorded in scrcpy 3.0.2. The overlay doesn't update unless I interact with it directly and dismiss it.

https://github.com/user-attachments/assets/1c649fba-2fc8-497c-896d-25397286155f

**Comment by rom1v** [comment]
Please test #5614.

**Comment by LoreleiCasswell** [comment]
Solved issue. Thanks!

**Comment by rom1v** [comment]
Thank you for the test :+1:

It will be merged before the next release.
