### ISSUE TITLE
When the scrcpy window does not have focus, clicking does not transfer to the phone

### ISSUE THREAD

**Issue by BaconCatBug** [Genymobile/scrcpy#562]
I use scrcpy to multitask while doing stuff on my phone. When I click on the window after it has lost focus the click does not transfer to the phone, necessitating a double click.

Is there any way to allow scrcpy to forward that focusing click?

**Comment by rom1v** [comment]
It had been broken, but fixed by 068253a3a299a60d78c7c1b0e760f4bbe3b75bc1 (not released yet).
