### ISSUE TITLE
the mouse click becomes unresponsive in the secure screen

### ISSUE THREAD

**Issue by yuyiqilin** [Genymobile/scrcpy#5637]
OS: Windows 11
Scrcpy version: 3.0.2
Installation method: Windows release

Sorry, I’ve found other bugs. Has the mouse click algorithm changed in version 3.0.2? There are two places where it’s not working as smoothly. One is that when I enable the pointer_location display, I can’t see the trace of the mouse movement. The other is on the payment screen of the app (the screen is black), where the mouse click becomes unresponsive (tested on Android 10, no bugs, but there’s a problem on Android 14). This bug exists whether the video thread is enabled or not. I tested version 2.7, and there was no such bugs.

**Comment by cactysman** [comment]
I can confirm doing things like entering the screen lock pattern has worked fine on the v2 branch and stopped working in v3. I've done that all the time and for now I'm using v2 for that.

**Comment by yuyiqilin** [comment]
> I can confirm doing things like entering the screen lock pattern has worked fine on the v2 branch and stopped working in v3. I've done that all the time and for now I'm using v2 for that.

So v3 does have some problems when it comes to dealing with the secure screen.

**Comment by rom1v** [comment]
Probably fixed by #5614.

**Comment by rom1v** [comment]
Could you please confirm this is fixed by scrcpy 3.1?

**Comment by yuyiqilin** [comment]
> Could you please confirm this is fixed by scrcpy 3.1?

Yes，it worked well now.
