### ISSUE TITLE
cannot record

### ISSUE THREAD

**Issue by Sprtcrnbry** [Genymobile/scrcpy#564]
thanks for the super useful program.
the problem is after specifying the record option the program didn't display the device screen and doesn't record, no file is generated by the program
i installed it using snap, mirroring and controlling the device works smoothly without problems if i don't include the record option

console log:
```
/usr/local/share/scrcpy/scrcpy-server.jar: 1 file pushed. 3.0 MB/s (19734 bytes in 0.006s)
INFO: Initial texture: 720x1280
ERROR: Failed to open output file: record.mkv
ERROR: Could not open recorder
```

scrcpy -v output:
```
scrcpy 1.8

dependencies:
 - SDL 2.0.8
 - libavcodec 57.107.100
 - libavformat 57.83.100
 - libavutil 55.78.100
```

**Comment by rom1v** [comment]
Seems related to the snap package.

cc @sisco311

**Comment by sisco311** [comment]
Fixed. Now you should be able to save the recording in your home directory.
Run:
`sudo snap refresh scrcpy`
to update your snap

**Comment by Sprtcrnbry** [comment]
thanks, its working now

**Comment by rom1v** [comment]
Thank you very much :+1:

For reference: https://github.com/sisco311/scrcpy-snap/commit/2506ec6ed9bda611ece92a2220cc4d0b47e4675f
