### ISSUE TITLE
Framerate difference based on whether the device display is on.

### ISSUE THREAD

**Issue by SJh29** [Genymobile/scrcpy#5641]
_Please read the [prerequisites] to run scrcpy._

[prerequisites]: https://github.com/Genymobile/scrcpy#prerequisites

_Also read the [FAQ] and check if your [issue][issues] already exists._

[FAQ]: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md
[issues]: https://github.com/Genymobile/scrcpy/issues

## Environment

 - **OS:** Windows
 - **Scrcpy version:** 3.0.2
 - **Installation method:** Windows Release
 - **Device model:** Google Pixel 6
 - **Android version:** 14

## Describe the bug
While mirroring the device screen, there is a noticeable frame rate difference based on whether the device display is on or not. 
During normal mirroring, my fps is roughly in the range of 90-120 fps. This is while the device is simply on the homescreen, and the launcher does not have any graphic intensive process or widget. The moment I turn off the display using `MOD + O`, the fps drops down to 20-60 fps.

My launch parameters are as follows:
```scrcpy --max-fps=90 --video-codec=h265 -m 2400 --tcpip=X.X.X.X:44115```

**Comment by rom1v** [comment]
Duplicate of #5607.

**Comment by SJh29** [comment]
Closing it as duplicate
