### ISSUE TITLE
Error: Phone hard locks then restarts during use since Android P update

### ISSUE THREAD

**Issue by loopgru** [Genymobile/scrcpy#566]
I'm happy to run whatever logging out diagnostics are required, but will need some guidance. Scrcpy terminal doesn't yield anything useful.

S8+, Android P, stock and nothing exciting running beyond bxactions and Tasker. No issues when not streaming, no pattern I've discerned to which apps are running when the lock occurs. Usually happens inside 10 minutes.

**Comment by rom1v** [comment]
Something in `adb logcat`? Does the device heat too much?

**Comment by loopgru** [comment]
Not a heat issue- phone is still cool to the touch and I've had it hotter gaming with no issue.

I've got a logcat dump here, but I don't really know what I'm looking for. Maybe this from the crash dump?

Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 32474 (SFWatchDogThrea), pid 32449 (surfaceflinger)

**Comment by rom1v** [comment]
```
Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 32474 (SFWatchDogThrea), pid 32449 (surfaceflinger)
```
Yes, probably this.

Do you have the full core dump?

**Comment by loopgru** [comment]
If it is contained in the logcat, yes? If so, or if there is some other way I can get it, I can throw it in a pastebin.

**Comment by loopgru** [comment]
It's a consistent crash / easy issue to replicate, so please let me know what you need and I'll happily oblige.

**Comment by rom1v** [comment]
Does it still happen?

**Comment by loopgru** [comment]
I discontinued use due to this issue. I can test if you want, but at the moment the office (where I had this set up) is closed due to COVID.

**Comment by rom1v** [comment]
OK, yes please test when you can.

For now, I'm closing, since it looks like a ROM issue.
