### ISSUE TITLE
Candidate word of Gboard is not showing on virtual display

### ISSUE THREAD

**Issue by 809825706** [Genymobile/scrcpy#5662]
_Please read the [prerequisites] to run scrcpy._

[prerequisites]: https://github.com/Genymobile/scrcpy#prerequisites

_Also read the [FAQ] and check if your [issue][issues] already exists._

[FAQ]: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md
[issues]: https://github.com/Genymobile/scrcpy/issues

## Environment

 - **OS:** Linuxmint 22
 - **Scrcpy version:** 3.1
 - **Installation method:**manual build
 - **Device model:** oneplus 5 
 - **Android version:** 14 (lineage os 22)

## Describe the bug

when I try to type words in any app on virtual display by Gboard, candidate words only show on the main screen even in pad model. it is the problem of Gboard or android system?

**Comment by rom1v** [comment]
:shrug:

**Comment by 809825706** [comment]
I found the solution:just enable the desktop mode to virtual display in developer options
