### ISSUE TITLE
Lunching scrcpy in turn adb.exe, creates a ghost adb device "emulator-5562 Offline"

### ISSUE THREAD

**Issue by JustIIRed** [Genymobile/scrcpy#5666]
## Environment

 - **OS:** Windows 11
 - **Scrcpy version:** 3.1
 - **Installation method:** Windows release (github zip)
 - **Device model:**
 - **Android version:** 15

## Problem
It appears when adb.exe is launched it creates a offline emulator which confuses scrcpy and will sometimes work and some not. 
I can hot fix this by running scrcpy.exe from a separate .bat file containing the -s parameter so it always runs from the right device.
although I wish this wasn't the case so I can just run scrcpy normally
Edit : All tests ran that were broken were with 1 device connected, the two shown are from testing the hotfix with 2 bat files each with there own serial added. Default behavior from scrcpy is choosing a random adb device which is why it will crash on launch because there is "multible" devices ie the ghost emulator-5562 or if you have more than 1 real devices ie 2 Phones.
Edit 2 : I'm dumb it was Windows Subsystem for Android, Specifically the " NTKDaemon.exe " process found using [TCPView](https://learn.microsoft.com/en-us/sysinternals/downloads/tcpview)
Didn't realize WSA was still enabled on this machine as WSA will no longer be supported beginning March 5, 2025.
**Sorry for any confusion scrcpy is great!!**

Hotfix , Save as "Anything .bat" and replace "device_serial_number."
Run the bat from the scrcpy folder or make a shortcut.
```
@echo off
scrcpy -s device_serial_number
```

I don't think this is scrcpy's fault creating the ghost, I do think a easy fix could be implemented such as a txt file in the scrcpy files like " set-device.txt " which the user could overwrite what scrcpy detects and uses that device so scrcpy doesn't crash and opens correctly each time. This could also allow the mirroring of multiple devices at once which i tested does work no issues
![image](https://github.com/user-attachments/assets/a9719b57-a917-4196-89ae-e2631b7d97e5)

---
When scrcpy works
```
scrcpy 3.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  [ My Phone Serial# ]                  device  Pixel_8_Pro
[ Path Here ]\scrcpy-win64-v3.1\scrcpy-wi...file pushed, 0 skipped. 106.1 MB/s (90640 bytes in 0.001s)
[server] INFO: Device: [Google] google Pixel 8 Pro (Android 15)
INFO: Renderer: direct3d
INFO: Texture: 1008x2240
```

Running -adb devices
```
...scrcpy-win64-v3.1>adb devices
List of devices attached
[ My Phone Serial# ]  device
emulator-5562   offline
```
Lunching scrcpy after scrcpy has been opened before
```
scrcpy 3.1 <https://github.com/Genymobile/scrcpy>
ERROR: Multiple (2) ADB devices:
ERROR:     -->   (usb)  [ My Phone Serial# ]                  device  Pixel_8_Pro
ERROR:     --> (tcpip)  emulator-5562                  offline
ERROR: Select a device via -s (--serial), -d (--select-usb) or -e (--select-tcpip)
ERROR: Server connection failed
Press Enter to continue...
```

Lunching scrcpy after killing adb.exe process
```
scrcpy 3.1 <https://github.com/Genymobile/scrcpy>
* daemon not running; starting now at tcp:5037
* daemon started successfully
INFO: ADB device found:
INFO:     -->   (usb)  [ My Phone Serial# ]                  device  Pixel_8_Pro
[ Path Here ]\scrcpy-win64-v3.1\scrcpy-wi... file pushed, 0 skipped. 99.7 MB/s (90640 bytes in 0.001s)
[server] INFO: Device: [Google] google Pixel 8 Pro (Android 15)
INFO: Renderer: direct3d
INFO: Texture: 1008x2240
```

**Comment by rom1v** [comment]
> It appears when adb.exe is launched it creates a offline emulator

No, you probably have something on your computer (Android Studio, something else?) running an emulator which is detected by adb.

**Comment by JustIIRed** [comment]
Edit 2 : I'm dumb it was Windows Subsystem for Android, Specifically the " NTKDaemon.exe " process found using [TCPView](https://learn.microsoft.com/en-us/sysinternals/downloads/tcpview)
Didn't realize WSA was still enabled on this machine as WSA will no longer be supported beginning March 5, 2025.
Sorry for any confusion scrcpy is great!!
