### ISSUE TITLE
Useless on Android 14 (black screen)

### ISSUE THREAD

**Issue by Jimmy-DSA** [Genymobile/scrcpy#5671]
_Please read the [prerequisites] to run scrcpy._

[prerequisites]: https://github.com/Genymobile/scrcpy#prerequisites

_Also read the [FAQ] and check if your [issue][issues] already exists._

[FAQ]: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md
[issues]: https://github.com/Genymobile/scrcpy/issues

## Environment

 - **OS:** Windows 10
 - **Scrcpy version:** 3.1
 - **Installation method:** Windows release
 - **Device model:** Galaxy M35
 - **Android version:** 14

## Describe the bug

On Android 14, no protected screen allows screen capture anymore; the screen just goes black. Now there's no difference compared to using the native screen capture mechanism. I know this must be very difficult to work around, but life finds a way — life always finds a way.

![image](https://github.com/user-attachments/assets/ae381df0-5871-4727-9754-34d73a7b0e5b)

**Comment by rom1v** [comment]
#2129 #36
