### ISSUE TITLE
Fps always 0

### ISSUE THREAD

**Issue by Vinest1412** [Genymobile/scrcpy#5678]
![wewew](https://github.com/user-attachments/assets/3a57360b-8245-4d08-84e0-11e07664b6e2)

why i always get fps 0??

**Comment by rom1v** [comment]
Because your screen content does not change.

> The frame rate is intrinsically variable: a new frame is produced only when the screen content changes. For example, if you play a fullscreen video at 24fps on your device, you should not get more than 24 frames per second in scrcpy.

https://github.com/Genymobile/scrcpy/blob/master/doc/video.md#frame-rate
