### ISSUE TITLE
Why AV1 Encoder so laggy?

### ISSUE THREAD

**Issue by Deathphobia11** [Genymobile/scrcpy#5681]
## Environment

 - **OS:** Windows 11 23H2
 - **Scrcpy version:** 3.1
 - **Installation method:** Windows release
 - **Device model:** TECNO POVA 6 Pro 5G
 - **Android version:** 14

## Describe the bug

My device can run smoothly on H.265 bitrate 16M but AV1 absolutely lag and very much latency.

ps. sorry for my language.

My PC
Intel i5-13500
Geforce RTX4070
RAM DDR5 16GBx2 6400Mhz

**Comment by rom1v** [comment]
Your device has probably no hardware encoder for AV1 (so it uses a software encoder).

Check with `scrcpy --list-encoders`.

**Comment by Deathphobia11** [comment]
![2024-12-18_010309](https://github.com/user-attachments/assets/4da0df25-c7bc-4530-853c-4e77ce5533ce)

Thank you for your reply.

I use software encoder but still so laggy. Because my device has no hardware encoder. Right?
