### ISSUE TITLE
Linux static builds broken on Debian Bookworm

### ISSUE THREAD

**Issue by LHLaurini** [Genymobile/scrcpy#5689]
## Environment

 - **OS:** Debian 12 (Bookworm)
 - **Scrcpy version:** 3.1, and future versions
 - **Installation method:** Linux static build
 - **Device model:** Irrelevant
 - **Android version:** Irrelevant

## Describe the bug

The [release workflow](https://github.com/Genymobile/scrcpy/blob/master/.github/workflows/release.yml) uses `ubuntu-latest`. That used to be `ubuntu-22.04`, but [is currently being upgraded to `ubuntu-24.04`](https://github.com/actions/runner-images/issues/10636). For scrcpy, it seems the change took effect between 3.0.2 and 3.1, so the first was built with 22.04 and the latter with 24.04.

While Ubuntu 22.04 ships with glibc 2.35, Ubuntu 24.04 uses glibc 2.39 ([source](https://repology.org/project/glibc/versions)). Glibc is backward-compatible, but not forward-compatible. That means that version 3.0.2 (and earlier) requires glibc 2.35+ and version 3.1 requires glibc 2.39+.

Therefore, if I try to run version 3.1 on Debian Bookworm (glibc 2.36), I get:
```
./scrcpy: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by ./scrcpy)
```

Debian Bookworm is the latest stable version, so it should probably be supported. I believe building with `ubuntu-22.04` should make the binaries compatible with the stable version of the most popular distros.

**Comment by rom1v** [comment]
Here is a binary built by `ubuntu-22.04`:

```diff
diff --git .github/workflows/release.yml .github/workflows/release.yml
index da021c6e1..efe1bac5d 100644
--- .github/workflows/release.yml
+++ .github/workflows/release.yml
@@ -84,7 +84,7 @@ jobs:
         run: release/test_client.sh
 
   build-linux-x86_64:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-22.04
     steps:
       - name: Check architecture
         run: |
```

- [`scrcpy-linux-x86_64-v3.1-5689.tar.gz`](https://tmp.rom1v.com/scrcpy/5689/1/scrcpy-linux-x86_64-v3.1-5689.tar.gz) <sub>`SHA-256: e47d16049b72b5c52263197b4826be80ef67a2b73cc4703fb83b7347d44f537`</sub>
- 
Does it work better?

**Comment by LHLaurini** [comment]
> Does it work better?

Yes, it seems to work normally.

**Comment by rom1v** [comment]
Merged into `dev`: 95c4f03c1bfd566b383780977b3473ebad6477ee

It will be used for the next release.

**Comment by tarikgraba** [comment]
@rom1v could you trigger a new "release" build with this build pipline? (not urgent)

**Comment by rom1v** [comment]
Not a release, but a build of the current `dev` branch: https://github.com/rom1v/scrcpy/actions/runs/12852156421
