### ISSUE TITLE
Google Chrome浏览器在手机息屏状态下不显示网页内容是什么情况？

### ISSUE THREAD

**Issue by 389377616** [Genymobile/scrcpy#5690]
就是远控手机的时候，手机处于息屏状态的时候打开Google Chrome浏览器打开网页都是只显示白屏，只要取消息屏状态点亮手机屏幕才能显示网页内容，其它浏览器就可以在息屏状态下支持显示网页内容.

**Comment by rom1v** [comment]
Duplicate of #836.

(also, please post in English)
