### ISSUE TITLE
Improve the Scrcpy Mouse Detection Quality for FPS Games

### ISSUE THREAD

**Issue by Kitsunecchi** [Genymobile/scrcpy#5701]
- [ ] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem?**
Yes

**Describe the feature request you'd like**
Currently scrcpy supports the full function of keyboard use well, but I think the quality of connectivity and synchronisation from mouse to mobile on scrcpy needs to be improved as this allows scrcpy to be more flexible than buying OTG cables. I hope this message was well received and I hope in the next update the mouse quality can be improved on scrcpy.

**Comment by rom1v** [comment]
What do you mean by "improved"? What's the problem?

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/doc/mouse.md#physical-mouse-simulation

**Comment by Kitsunecchi** [comment]
> What do you mean by "improved"? What's the problem?

ooh there is a way, thank you for pointing it out to me. With this my problem is solved, once again thank you.

**Comment by Kitsunecchi** [comment]
> https://github.com/Genymobile/scrcpy/blob/master/doc/mouse.md#physical-mouse-simulation

It does work but why i cannot click anything?
