### ISSUE TITLE
Require to install python-setuptools 

### ISSUE THREAD

**Issue by flinox** [Genymobile/scrcpy#571]
When i'm trying to install:

> pip3 install meson

i'm getting the error:

> 
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>     ModuleNotFoundError: No module named 'setuptools'
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-zld0wjn6/meson/

So i suggest to include the requirement for install meson:

> sudo apt-get install python-setuptools

Reggards!

**Comment by rom1v** [comment]
Thanks for the report.

Which distrib/version?
