### ISSUE TITLE
On Google TV (Mi TV Box S 2nd Gen) Enter key isn't recognized in Search box

### ISSUE THREAD

**Issue by qwer1304** [Genymobile/scrcpy#5714]
Please read the [prerequisites](https://github.com/Genymobile/scrcpy#prerequisites) to run scrcpy.

Also read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md) and check if your [issue](https://github.com/Genymobile/scrcpy/issues) already exists.

Environment
OS: [e.g. Debian, Windows, macOS...] Windows
Scrcpy version: [e.g. 2.5] 3.1
Installation method: [e.g. manual build, apt, snap, brew, Windows release...] Windows release
Device model: Mi TV Box S 2nd Gen (MiTV-AFKR0)
Android version: [e.g. 14] 11
Describe the bug

- Select Apps
- Move to Search box
- Press Enter

Screen with search box opens

- Enter some text
- Press Enter

The Enter key isn't recognized as Enter in Search box. It's recognized as some key press (since I hear the sound of a key being pressed), but it doesn't perform the action - launching search.

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment]
Pressing <kbd>Enter</kbd> injects <kbd>Enter</kbd> to the device, the same as executing:

```
adb shell input keyevent ENTER
```

How the app reacts to this key is not under control of scrcpy.

Try <kbd>Shift</kbd>+<kbd>Enter</kbd> or similar, maybe they implemented some shortcut…

**Comment by qwer1304** [comment]
@rom1v _How the app reacts to this key is not under control of scrcpy._
Except that it works correctly with a physical keyboard attached to the device (USB and BT) and does NOT work through scrcpy.

**Comment by rom1v** [comment]
> Except that it works correctly with a physical keyboard attached to the device (USB and BT) and does NOT work through scrcpy (when Gboard is the selected keyboard).

OK, physical keyboards use a separate code path in Android. What is the behavior of 

```
adb shell input keyevent ENTER
```

?

**Comment by qwer1304** [comment]
@rom1v _OK, physical keyboards use a separate code path in Android. What is the behavior of

adb shell input keyevent ENTER_

But I found out that KEYCODE_ENTER 66 works correctly. Keycode 28 (the default for Enter) does not.

**Comment by rom1v** [comment]
Pressing <kbd>Enter</kbd> on your keyboard triggers <kbd>AKEYCODE_ENTER</kbd>:

https://github.com/Genymobile/scrcpy/blob/5ae01749bf4fad9fb4d8bf7c879dc60f479c1013/app/src/keyboard_sdk.c#L30

https://github.com/Genymobile/scrcpy/blob/5ae01749bf4fad9fb4d8bf7c879dc60f479c1013/app/src/android/keycodes.h#L178

I just tested on my computer and my device, it correctly injects 66:

```console
$ scrcpy -Vverbose --no-audio --no-mouse-hover
…
VERBOSE: input: key down code=66 repeat=0 meta=000000
VERBOSE: input: key up   code=66 repeat=0 meta=000000
```

> Keycode 28 (the default for Enter) does not.

28 is `AKEYCODE_CLEAR`:

https://github.com/Genymobile/scrcpy/blob/5ae01749bf4fad9fb4d8bf7c879dc60f479c1013/app/src/android/keycodes.h#L99

Where did you read 28?

**Comment by qwer1304** [comment]
@rom1v _Where did you read 28?_
First, that's what the physical keyboard outputs.
Second, adb shell cat /system/usr/keylayout/Generic.kl lists 28 as ENTER (and 66 as F8).
Third, there's lots of pages in the 'Net where people are struggling with keycode 28 not being mapped correctly. Some apps map it to DPAD_ENTER instead of ENTER.

It seems that it depends at what level in the stack you look, because when I map code 28 to 66 in EKH it does NOT work correctly.

**Comment by rom1v** [comment]
> First, that's what the physical keyboard outputs.
> Second, `adb shell cat /system/usr/keylayout/Generic.kl` lists 28 as ENTER (and 66 as F8).

That's low level key numbers, what matters when injecting SDK events is the keycode (`AKEYCODE_ENTER`).

> But I found out that KEYCODE_ENTER 66 works correctly.

So when you execute:

```
adb shell input keyevent ENTER
```

It works correctly?

That's basically exactly what scrcpy does (injecting `AKEYCODE_ENTER`).

**Comment by qwer1304** [comment]
@rom1v _so when you execute:_ `adb shell input keyevent ENTER`
`It works correctly?`

No! Only when I execute  `adb shell input keyevent KEYCODE_ENTER` or ` `adb shell input keyevent 66` it works correctly.

**Comment by rom1v** [comment]
Ok, that's basically what scrcpy does.

Run:

```
scrcpy -Vverbose --no-audio --no-mouse-hover
```

and press <kbd>Enter</kbd> in the scrcpy window. What code is shown in the logs?

**Comment by qwer1304** [comment]
VERBOSE: input: key down code=66 repeat=0 meta=200000
VERBOSE: input: key up   code=66 repeat=0 meta=200000

**Comment by rom1v** [comment]
I get:

```
VERBOSE: input: key down code=66 repeat=0 meta=000000
VERBOSE: input: key up   code=66 repeat=0 meta=000000
```

The difference is you inject `meta=200000`, which is `AMETA_NUM_LOCK_ON`:

https://github.com/Genymobile/scrcpy/blob/5ae01749bf4fad9fb4d8bf7c879dc60f479c1013/app/src/android/input.h#L76

Does turning off num lock change anything?

**Comment by qwer1304** [comment]
@rom1v 
```
VERBOSE: input: key down code=66 repeat=0 meta=000000
VERBOSE: input: key up   code=66 repeat=0 meta=000000
```
Work too

**Comment by qwer1304** [comment]
@rom1v The problem I reported occurs with the option -K (uhid) used. Then the physical ENTER event is 28. It is also reported by adb shell getevent

**Comment by rom1v** [comment]
What is the verbose output when you enable UHID and press <kbd>Enter</kbd>?

```
scrcpy -Vverbose --no-audio --no-mouse-hover -K
```

**Comment by qwer1304** [comment]
@rom1v 
```
VERBOSE: keys[28] = true
VERBOSE: hid keyboard: key down scancode=28 (40) mod=00
VERBOSE: input: UHID input [1] 00 00 28 00 00 00 00 00
VERBOSE: keys[28] = false
VERBOSE: hid keyboard: key up   scancode=28 (40) mod=00
VERBOSE: input: UHID input [1] 00 00 00 00 00 00 00 00
```

**Comment by rom1v** [comment]
> scancode=28 (40)

0x28 (40) is the correct scancode for <kbd>Enter</kbd>:
 - https://wiki.libsdl.org/SDL2/SDL_Scancode
 - https://usb.org/document-library/hid-usage-tables-15 (§10 pages 89-90)

I don't know why your device/app does not react as expected.

**Comment by qwer1304** [comment]
@rom1v OK, we're getting somewhere here: 28 is decimal (0x1c), but you wrote decimal 40 (0x28). The physical device sends 0x1c according to `adb shell getevent`.

**Comment by rom1v** [comment]
> The physical device sends 0x1c according to `adb shell getevent`. Can we try sending somehow 0x1c instead and see what happens?

0x1c is `y`. But sure, test whatever you want.

Write the values you want in the HID report:
https://github.com/Genymobile/scrcpy/blob/5ae01749bf4fad9fb4d8bf7c879dc60f479c1013/app/src/hid/hid_keyboard.c#L298

**Comment by qwer1304** [comment]
@rom1v  I mean without recompiling, using pre-compiled scrcpy.

**Comment by rom1v** [comment]
If you want to hardcode random values, you have to recompile. This specific change can be performed either on the client or the server, but at least one of them must be recompiled.

**Comment by qwer1304** [comment]
@rom1v Interestingly, eventhough scrcpy reports 28 (40), getenv reports that it got 1c from scrcpy. Perhaps your just your reporting is mixed up?

**Comment by rom1v** [comment]
Post your full getevent output.

**Comment by qwer1304** [comment]
@rom1v 
C:\Program Files\scrcpy-win64-v3.1>adb shell getevent
add device 1: /dev/input/event9
  name:     "BT KEYBOARD System Control"
add device 2: /dev/input/event8
  name:     "BT KEYBOARD Consumer Control"
add device 3: /dev/input/event7
  name:     "BT KEYBOARD Keyboard"
add device 4: /dev/input/event6
  name:     "scrcpy"
add device 5: /dev/input/event5
  name:     "Xiaomi RC Keyboard"
add device 6: /dev/input/event3
  name:     "Xiaomi RC Consumer Control"
add device 7: /dev/input/event4
  name:     "virtual-search"
add device 8: /dev/input/event2
  name:     "ir_keypad"
could not get driver version for /dev/input/mice, Inappropriate ioctl for device
add device 9: /dev/input/event1
  name:     "cec_input"
add device 10: /dev/input/event0
  name:     "input_btrcu"
/dev/input/event6: 0004 0004 00070028
/dev/input/event6: 0001 001c 00000001
/dev/input/event6: 0000 0000 00000000
/dev/input/event6: 0004 0004 00070028
/dev/input/event6: 0001 001c 00000000
/dev/input/event6: 0000 0000 00000000

**Comment by qwer1304** [comment]
@rom1v 
The same happens with keypad (numlock) enter:
getenv:
```
/dev/input/event6: 0004 0004 00070058
/dev/input/event6: 0001 0060 00000001
/dev/input/event6: 0000 0000 00000000
/dev/input/event6: 0011 0000 00000001
/dev/input/event6: 0004 0004 00070058
/dev/input/event6: 0001 0060 00000000
/dev/input/event6: 0000 0000 00000000
```
scrcpy:
```
VERBOSE: keys[58] = true
VERBOSE: hid keyboard: key down scancode=58 (88) mod=00
VERBOSE: HID keyboard state synchronized
VERBOSE: input: UHID input [1] 00 00 53 00 00 00 00 00
VERBOSE: input: UHID input [1] 00 00 58 00 00 00 00 00
VERBOSE: UHID output [1] 01
VERBOSE: keys[58] = false
VERBOSE: hid keyboard: key up   scancode=58 (88) mod=00
VERBOSE: input: UHID input [1] 00 00 00 00 00 00 00 00
```

**Comment by rom1v** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/input-event-codes.h?id=059dd502b263d8a4e2a84809cf1068d6a3905e6f#n103

IIUC, the HID key is encoded in `00070028` (0x28 in the LSB)
0x1c just happens to be the Linux keycode for ENTER: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/input-event-codes.h?id=059dd502b263d8a4e2a84809cf1068d6a3905e6f#n103
But it is just a coincidence that it is equal to 28 in decimal. The correct HID code to inject is 0x28.

Try with different keys, for example `c`:

```
/dev/input/event5: 0004 0004 00070006
/dev/input/event5: 0001 002e 00000000
/dev/input/event5: 0000 0000 00000000
```

0x6 (from 00070006): matches the HID keycode 6 for 'c'.
0x2e (46): the linux key for 'c': https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/input-event-codes.h?id=059dd502b263d8a4e2a84809cf1068d6a3905e6f#n121

**Comment by qwer1304** [comment]
@rom1v OK, at least I know where to look for the input codes. I'll try different variants later and report the findings.

**Comment by qwer1304** [comment]
@rom1v So, I found out a difference between the BT and the virtual keyboards behavior viz-a-viz handling of the ENTER key eventhough getitem and scrcpy logging report exactly the same. With the BT keyboard the ENTER is processed correctly, but with virtual keyboard it is ignored. So it seems there's a small difference in the processing chain that causes this, eventhough most keys work as expected.
Note that the BT keyboard uses the Generic.kl keylaout file since there's no keylayout file with its vendor_id in its name.
