### ISSUE TITLE
Improving scrcpy add support for non-english Characters such as arabic.

### ISSUE THREAD

**Issue by ahmedx3001** [Genymobile/scrcpy#5715]
Add support for non english charecter like arabic in scrcpy-server  it would be great 👍 pls (:
![image](https://github.com/user-attachments/assets/36c0c161-0040-481c-934b-d3040dc03c7e)

**Comment by rom1v** [comment]
Use UHID keyboard mode: https://github.com/Genymobile/scrcpy/blob/master/doc/keyboard.md#physical-keyboard-simulation

**Comment by ahmedx3001** [comment]
I don’t really like Uhid I prefer using SDK instead

> Use UHID keyboard mode: https://github.com/Genymobile/scrcpy/blob/master/doc/keyboard.md#physical-keyboard-simulation

**Comment by rom1v** [comment]
Then you can't inject arabic characters.
