### ISSUE TITLE
Closing and opening laptop lid while scrcpy has focus produces errors

### ISSUE THREAD

**Issue by myself248** [Genymobile/scrcpy#572]
I have my laptop set to remain running when I close the lid to carry it around. It does, however, turn off the screen and turn it back on when I open it again. After doing so, I see this message in the console:

The key you just pressed is not recognized by SDL. To help get this fixed, please report this to the SDL forums/mailing list <https://discourse.libsdl.org/> X11 KeyCode 151 (143), X11 KeySym 0x1008FF2B (XF86WakeUp).

This tends to cause really weird behavior in the Android app that happens to be foreground at the moment. Simple workaround is to make sure scrcpy doesn't have focus when folding the lappy...

**Comment by rom1v** [comment]
> I have my laptop set to remain running when I close the lid to carry it around. It does, however, turn off the screen and turn it back on when I open it again.

I cannot reproduce on my laptop :(

> This tends to cause really weird behavior in the Android app that happens to be foreground at the moment.

This is very weird, because only specific keycodes are converted and forwarded:

https://github.com/Genymobile/scrcpy/blob/5d473efeb5c4f42a75aad6ab5892e2813358c0c9/app/src/convert.c#L76

Could you use the version of `scrcpy-server.jar` I posted in https://github.com/Genymobile/scrcpy/issues/547#issuecomment-496291279, to get more logs about events, please?

**Comment by rom1v** [comment]
@myself248 Did you find some time to test with more logs?

**Comment by myself248** [comment]
No, I've got the new server being pushed to the phone, but I haven't sat down to figure out how to apply the patch to the client. New to all this, sorry. 

The weird behavior in the Android app may have been a coincidence, I can't reproduce it reliably and the app in question is pretty crashy anyway.

**Comment by rom1v** [comment]
> I haven't sat down to figure out how to apply the patch to the client.

At the root of the project, execute `patch -p1`. It will wait for input. Paste the content of the patch:

```diff
diff --git a/app/src/scrcpy.c b/app/src/scrcpy.c
index b777b77..d843810 100644
--- a/app/src/scrcpy.c
+++ b/app/src/scrcpy.c
@@ -147,10 +147,14 @@ handle_event(SDL_Event *event, bool control) {
             if (!control) {
                 break;
             }
+            LOGD("TEXTINPUT: [%s]\n", event->text.text);
             input_manager_process_text_input(&input_manager, &event->text);
             break;
         case SDL_KEYDOWN:
         case SDL_KEYUP:
+            LOGD("%s %x (%c)\n",
+                 event->type == SDL_KEYDOWN ? "KEYDOWN" : "KEYUP",
+                 (int) event->key.keysym.sym, (char) event->key.keysym.sym);
             // some key events do not interact with the device, so process the
             // event even if control is disabled
             input_manager_process_key(&input_manager, &event->key, control);
```

Then press Ctrl+D twice.
