### ISSUE TITLE
Is there any way to know whether the scrcpy has been connected or not

### ISSUE THREAD

**Issue by hoousun** [Genymobile/scrcpy#575]
On the server side (Android device), is there any way to know whether the scrcpy has been connected or not?
If possible, I want to do some automation with Tasker based on the scrcpy connection state.

**Comment by rom1v** [comment]
No, there isn't. See #153.

Out of curiosity, what do you want to automate based on the scrcpy state?

**Comment by latel** [comment]
because scrcpy can not work if phone is locked, so I want to set a larger screen lock time to prevent frequently screen locks

**Comment by rom1v** [comment]
> because scrcpy can not work if phone is locked

What do you mean? Black screen?

Is your problem related to the question in this issue?

**Comment by gooseraticate40** [comment]
Hello, to tack on to this I had a question -- is it even possible for an android app to detect the usage of this or screen mirroring software like this in general? I do not want to get banned from games for using this for accessibility reasons and just want to be sure. Thank you!
