### ISSUE TITLE
Copy text from Android to PC 

### ISSUE THREAD

**Issue by luanfsf** [Genymobile/scrcpy#577]
It would be interesting if we could copy text from any android app to PC, similar to how we copy text from PC and paste on Android inputs.

**Comment by rom1v** [comment]
Hi,

I implemented it last week. See https://github.com/Genymobile/scrcpy/issues/145#issuecomment-497484917.

It will be in the next release.

**Comment by luanfsf** [comment]
Thanks! :+1: @rom1v
