### ISSUE TITLE
Brew Install ADB 

### ISSUE THREAD

**Issue by MichaelDHarris** [Genymobile/scrcpy#578]
Tried

```brew cask install android-platform-tools```

got error 

```Error: Download failed on Cask 'android-platform-tools' with message: Download failed: https://dl.google.com/android/repository/platform-tools_r28.0.3-darwin.zip```

found solution with 

```brew install homebrew/cask/android-platform-tools```

**Comment by rom1v** [comment]
Not related to scrcpy. I'm closing as it seems you found a solution :+1:

**Comment by Hutao1** [comment]
good
