### ISSUE TITLE
Add an option to disable the device screen

### ISSUE THREAD

**Issue by Bratmaxe1981** [Genymobile/scrcpy#580]
Hy, thanks for your great work.
Is it possible to add a command line argument, that disable the device screen (or set it to the lowest brightness)? It is possible with tasker, but would be nice if your app can do it automatically.

I usee your app to control my device with my computer and so I don't need the device screen, and my OLED Screen can burn in, if it shows the same screen for hours.

**Comment by rom1v** [comment]
Hi,

I implemented it few days ago on `dev` branch, see #175.

It will be available in the next release.
