### ISSUE TITLE
Failed to execute adb

### ISSUE THREAD

**Issue by cyo57** [Genymobile/scrcpy#581]
Win10x64, scrcpy-win64-v1.8, 
ADB can be used normally

ERROR: Failed to execute adb
ERROR: Could not execute "adb push"

**Comment by rom1v** [comment]
From the _scrcpy_ directory, what is the result of these commands:

    adb --version
    .\adb --version
    adb push scrcpy-server.jar /data/local/tmp/scrcpy-server.jar

?

**Comment by rom1v** [comment]
Does it work?
