### ISSUE TITLE
how do you use the branched version?

### ISSUE THREAD

**Issue by Shuaiouke** [Genymobile/scrcpy#585]
as the title says, only the original win64 version works, others are totally different

**Comment by rom1v** [comment]
Sorry, I don't understand your question.

Which "branched" version? Which "others"? How different?

**Comment by Shuaiouke** [comment]
like the scrcpy-FPS, how do I launch it?

**Comment by rom1v** [comment]
> scrcpy-FPS

If you want to print framerate logs in the console, press `Ctrl`+`i` to enable/disable the fps counter.

(not sure it answers your question).

**Comment by Shuaiouke** [comment]
I mean there isn't a executable file in the folder... how do I launch scrcpy

**Comment by Shuaiouke** [comment]
BTW fraps seem to also work with scrcpy

**Comment by rom1v** [comment]
> how do I launch scrcpy

For [Windows](https://github.com/Genymobile/scrcpy/blob/master/README.md#windows), just download [`scrcpy-win64-v1.9.zip`](https://github.com/Genymobile/scrcpy/releases/download/v1.9/scrcpy-win64-v1.9.zip), extract it, and run `scrcpy.exe`.

**Comment by Shuaiouke** [comment]
yes but it doesn't print FPS
 or one more example: rawkeyevents, it passes key straight to the phone, but there's a branch on github, how do I make scrcpy.exe pass the raw key to the phone?

**Comment by rom1v** [comment]
> yes but it doesn't print FPS

If you press `Ctrl`+`i` while scrcpy is running, it will print the framerate every second in the console.

> or one more example: rawkeyevents, it passes key straight to the phone, but there's a branch on github, how do I make scrcpy.exe pass the raw key to the phone?

Oh, I get it. You are confused by the github interface.

Branches are [git branches](https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell), and are used for development purpose. Ignore that and just take the release if you're an end-user.

**Comment by Shuaiouke** [comment]
is there a way to fully play PUBG on my computer by controlling my phone? since it seems like only wasd is working

**Comment by rom1v** [comment]
> since it seems like only wasd is working

(I don't have the game) What does not work?

You could be interested in discussions in #87 and #269.

**Comment by Shuaiouke** [comment]
I can't use my mouse, plz get one, it's free(just to improve the quality for gaming)

**Comment by rom1v** [comment]
> just to improve the quality for gaming

Yes, some improvements have to be made in this area…
When I have time.

**Comment by Shuaiouke** [comment]
Then how do I trigger the passthrough of raw key events? CTRL + ?

**Comment by rom1v** [comment]
> Then how do I trigger the passthrough of raw key events?

What I called "raw key events" is just injecting key events instead of text to fix #87. "Raw key events" are already used for letters.

What is your problem with keys? What do you observe in PUBG?

**Comment by Shuaiouke** [comment]
I can only to WASD, not any other operations

**Comment by rom1v** [comment]
What keys do you press for "other operations"?

**Comment by Shuaiouke** [comment]
like tab to open inventory, Q&E to lean... all of that, since if you plug a keyboard onto ur phone, PUBG allows these movements

**Comment by rom1v** [comment]
OK, that's weird:
 - `TAB` is [mapped](https://github.com/Genymobile/scrcpy/blob/4940746bcba1ef50dec9add25cf231e8596407af/app/src/convert.c#L83)
 - `Q` and `E` are letters, and are forwarded as is, like `W`, `A`, `S`, `D` (unless `Q&E` refers to something else)

**Comment by Shuaiouke** [comment]
can you make the phone think it's connected to an actual keyboard?

**Comment by rom1v** [comment]
See #279.

The problem is that, contrary to what happens with an actual keyboard, the USB connection is reversed: the computer is the host and the device is the slave. Some Android device implement [HID over AOA (over USB)](https://source.android.com/devices/accessories/aoa2#hid-support), to be able to reverse the roles. (and in practice, like #14, it would only work on Linux)

**Comment by Shuaiouke** [comment]
so basically it makes it a real keyboard if i use the linux version? I have ubuntu :)

**Comment by Shuaiouke** [comment]
or do I have to do settings

**Comment by rom1v** [comment]
Please read #279. HID over AOA is not implemented in scrcpy.

**Comment by Shuaiouke** [comment]
sadness :( why not
