### ISSUE TITLE
Unrecognized option `--turn-screen-off'

### ISSUE THREAD

**Issue by SamuelBlickle** [Genymobile/scrcpy#588]
Somehow i do get the message `scrcpy: unrecognized option '--turn-screen-off'` when I try to start the app with `scrcpy --turn-screen-off`, same with `-S`.

This is on a Mac mini (installed via brew) with a S9+.

Am I doing something wrong?

**Comment by rom1v** [comment]
scrcpy --version

You probably have v1.8.

v1.9 is not in homebrew yet. See https://github.com/Homebrew/homebrew-core/pull/40918.

**Comment by SamuelBlickle** [comment]
Wow, now I feel a little stupid :D Thank you for your help!

**Comment by rom1v** [comment]
> now I feel a little stupid

There is no reason.
