### ISSUE TITLE
Multitouch and Long press on window laptop

### ISSUE THREAD

**Issue by opnay** [Genymobile/scrcpy#59]
it can't possible multitouch on my window laptop.
My laptop is LG Gram 2018 touch model(15Z680-HA76K).
And i tested on my laptop, and using touch.

Scroll, Drag and almost things are working. but, multitouch and long press are not working.

so, can you support for touchable window pc?

**Comment by rom1v** [comment]
Thank you for your report.

Yes, this is missing for now. See https://github.com/Genymobile/scrcpy/issues/22

**Comment by rom1v** [comment]
Implemented on `dev` branch. See #22.
