### ISSUE TITLE
frame drops low quality and delay in 0.3 or0.4 sec

### ISSUE THREAD

**Issue by dopetech** [Genymobile/scrcpy#591]
i am facing frame drops low quality and delay in 0.3 or 0.4 sec issue how to ix these issues 
i want to change mirror quality and screen resolution  
i already have sol.for sharing phone audio to pc

**Comment by rom1v** [comment]
Over USB or Wifi?

If you press `Ctrl`+`i`, it will print the framerate every second and the number of skipped frames on the computer-side. Could you paste a sample of this output, please?

> i want to change mirror quality and screen resolution

    scrcpy -m 1024

(or some other value)
