### ISSUE TITLE
Mouse Scroll crash android system

### ISSUE THREAD

**Issue by migueBarrera** [Genymobile/scrcpy#592]
If you make scroll the system crash.

Device:
ODroid with android 6.0

Log:
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.InputDevice.setPointerShape(int)' on a null object reference
 MessageQueue-JNI:  at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4259)

**Comment by rom1v** [comment]
The application you use probably did not expect to get a null object here.

(What application is it? Please provide the whole stack trace.)

There was a similar issue with flutter: https://github.com/flutter/engine/pull/7986.

**Comment by migueBarrera** [comment]
Launcher, system browser , any app.

**Comment by rom1v** [comment]
Could you post the whole stacktrace, please?

**Comment by migueBarrera** [comment]
yes.
In this case i use scroll on launcher.
`06-13 13:56:03.938  4206  4206 E MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
06-13 13:56:03.938  4206  4206 E MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.InputDevice.setPointerShape(int)' on a null object reference
06-13 13:56:03.938  4206  4206 E MessageQueue-JNI:      at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4259)
06-13 13:56:03.938  4206  4206 E MessageQueue-JNI:      at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4107)
06-13 13:56:03.938  4206  4206 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3653)
06-13 13:56:03.938  4206  4206 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3706)
06-13 13:56:03.938  4206  4206 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3672)
06-13 13:56:03.938  4206  4206 E MessageQueue-JNI:      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3798)
06-13 13:56:03.938  4206  4206 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3680)
06-13 13:56:03.938  4206  4206 E MessageQueue-JNI:      at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3855)
06-13 13:56:03.938  4206  4206 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3653)
06-13 13:56:03.938  4206  4206 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3706)
06-13 13:56:03.938  4206  4206 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3672)
06-13 13:56:03.938  4206  4206 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3680)
06-13 13:56:03.938  4206  4206 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3653)
06-13 13:56:03.938  4206  4206 E MessageQueue-JNI:      at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5959)
06-13 13:56:03.938  4206  4206 E MessageQueue-JNI:      at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5933)
06-13 13:56:03.938  4206  4206 E MessageQueue-JNI:      at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5894)
06-13 13:56:03.938  4206  4206 E MessageQueue-JNI:      at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6062)
06-13 13:56:03.938  4206  4206 E MessageQueue-JNI:      at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
06-13 13:56:03.938  4206  4206 E MessageQueue-JNI:      at android.os.MessageQueue.nativePollOnce(Native Method)
06-13 13:56:03.938  4206  4206 E MessageQueue-JNI:      at android.os.MessageQueue.next(MessageQueue.java:323)
06-13 13:56:03.938  4206  4206 E MessageQueue-JNI:      at android.os.Looper.loop(Looper.java:135)
06-13 13:56:03.938  4206  4206 E MessageQueue-JNI:      at android.app.ActivityThread.main(ActivityThread.java:5422)
06-13 13:56:03.938  4206  4206 E MessageQueue-JNI:      at java.lang.reflect.Method.invoke(Native Method)
06-13 13:56:03.938  4206  4206 E MessageQueue-JNI:      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
06-13 13:56:03.938  4206  4206 E MessageQueue-JNI:      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
06-13 13:56:03.938  4206  4206 D AndroidRuntime: Shutting down VM
--------- beginning of crash
06-13 13:56:03.939  4206  4206 E AndroidRuntime: FATAL EXCEPTION: main
06-13 13:56:03.939  4206  4206 E AndroidRuntime: Process: com.android.launcher, PID: 4206
06-13 13:56:03.939  4206  4206 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.InputDevice.setPointerShape(int)' on a null object reference
06-13 13:56:03.939  4206  4206 E AndroidRuntime:        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4259)
06-13 13:56:03.939  4206  4206 E AndroidRuntime:        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4107)
06-13 13:56:03.939  4206  4206 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3653)
06-13 13:56:03.939  4206  4206 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3706)
06-13 13:56:03.939  4206  4206 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3672)
06-13 13:56:03.939  4206  4206 E AndroidRuntime:        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3798)
06-13 13:56:03.939  4206  4206 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3680)
06-13 13:56:03.939  4206  4206 E AndroidRuntime:        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3855)
06-13 13:56:03.939  4206  4206 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3653)
06-13 13:56:03.939  4206  4206 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3706)
06-13 13:56:03.939  4206  4206 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3672)
06-13 13:56:03.939  4206  4206 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3680)
06-13 13:56:03.939  4206  4206 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3653)
06-13 13:56:03.939  4206  4206 E AndroidRuntime:        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5959)
06-13 13:56:03.939  4206  4206 E AndroidRuntime:        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5933)
06-13 13:56:03.939  4206  4206 E AndroidRuntime:        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5894)
06-13 13:56:03.939  4206  4206 E AndroidRuntime:        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6062)
06-13 13:56:03.939  4206  4206 E AndroidRuntime:        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
06-13 13:56:03.939  4206  4206 E AndroidRuntime:        at android.os.MessageQueue.nativePollOnce(Native Method)
06-13 13:56:03.939  4206  4206 E AndroidRuntime:        at android.os.MessageQueue.next(MessageQueue.java:323)
06-13 13:56:03.939  4206  4206 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:135)
06-13 13:56:03.939  4206  4206 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5422)
06-13 13:56:03.939  4206  4206 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-13 13:56:03.939  4206  4206 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
06-13 13:56:03.939  4206  4206 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
06-13 13:56:03.942  3164  3474 W ActivityManager:   Force finishing activity com.android.launcher/com.android.launcher2.Launcher`

**Comment by rom1v** [comment]
Thank you.

It seems it is a bug in Android which has been fixed by [`caca1114b2cf78551b2008156986a644d15317ef`](https://android.googlesource.com/platform/frameworks/base.git/+/caca1114b2cf78551b2008156986a644d15317ef%5E%21/).
