### ISSUE TITLE
Playing games, it´s possible?

### ISSUE THREAD

**Issue by richardsonvix** [Genymobile/scrcpy#594]
I tried to play the game Hill Climb 2 Racing, but when the game appears on the phone is closed, how to solve this?

Is it possible to play? What parameters are interesting to modify for this?

**Comment by rom1v** [comment]
> when the game appears on the phone is closed

When the game appears, what is closed? (the game or scrcpy)

**Comment by richardsonvix** [comment]
Yesterday in 4 tests the game opened the splash screen and then closed when
I finished (when displaying the initial screen of the game) returning to
the home of the launcher, today opened completely, but very, very slowly.

>

**Comment by rom1v** [comment]
Maybe your device is not powerful enough to render a game and encode the screen simultaneously.

Does it work with a tiny definition:

    scrcpy -m400

?

**Comment by richardsonvix** [comment]
Thanks, I´ll try this.

>
