### ISSUE TITLE
ubuntu16.04 build failed

### ISSUE THREAD

**Issue by LZHD** [Genymobile/scrcpy#596]
```
BUILD FAILED in 1s
2 actionable tasks: 2 executed
[37/37] Linking target app/scrcpy.
In function ‘__recv_alias’,
    inlined from ‘run_receiver’ at ../app/src/net.c:86:12:
/usr/include/x86_64-linux-gnu/bits/socket2.h:39:9: warning: call to ‘__recv_chk_warn’ declared with attribute warning: recv called with bigger length than size of destination buffer
  return __recv_chk (__fd, __buf, __n, __bos0 (__buf), __flags);
         ^
ninja: build stopped: subcommand failed.
```

**Comment by rom1v** [comment]
I don't understand how it is possible:

https://github.com/Genymobile/scrcpy/blob/1807de4955e7d80d513f96a21026cd542886dc4f/app/src/receiver.c#L63-L69

It seems it is a bug in an old version of `gcc`:
 - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=751812
 - https://github.com/civetweb/civetweb/issues/103

As a workaround, try to disable link-time optimizations, by removing `-Db_lto=true` in your meson command:

    meson x --buildtype release --strip

**Comment by LZHD** [comment]
V1.8 ---> android-28
V1.9 ---> android-29
![选区_001](https://user-images.githubusercontent.com/9976942/59564136-c9a33300-9075-11e9-8ae1-088ca44a2f10.png)

**Comment by LZHD** [comment]
@rom1v 
cannot stat '/usr/local/bin/scrcpy-server.jar': No such file or directory
ERROR: "adb push" returned with value 1

**Comment by rom1v** [comment]
@LZHD `git pull` (update to current `master) and retry

**Comment by LZHD** [comment]
@rom1v 
thank you very much.
run successfully
