### ISSUE TITLE
Failed to execute adb kali linux snap

### ISSUE THREAD

**Issue by ljorge705** [Genymobile/scrcpy#598]
Kali linux
version: edge v1.9-15-g4940746
phone: oneplus 3t
android s.o: 9.0

```
root@jorge:~# scrcpy
/usr/local/share/scrcpy/scrcpy-server....shed. 3.2 MB/s (19734 bytes in 0.006s)
ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: Expecting 5 parameters
	at com.genymobile.scrcpy.Server.createOptions(Server.java:53)
	at com.genymobile.scrcpy.Server.main(Server.java:109)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:384)
```

**Comment by rom1v** [comment]
cc @sisco311

**Comment by sisco311** [comment]
Don't run the snap as root. 

snaps run confined under a restrictive security sandbox, so the snap uses its builtin adb (version 1.0.39) command.

The adb tool does not follow the UNIX philosophy. It provides a server, a client and a daemon. Different versions are not compatible. /rant

Try to run scrcpy as your regular user.
