### ISSUE TITLE
adb issues

### ISSUE THREAD

**Issue by arnauldb** [Genymobile/scrcpy#599]
Hello,

I try to use scrcpy (I had it working at work), but on my Linux Mint 18.3 Sylvia at home I have this error message:
```
scrcpy
adb server version (41) doesn't match this client (39); killing...
* daemon started successfully
adb: error: failed to get feature set: device offline
ERROR: "adb push" returned with value 1
```

I installed adb by downloading the latest Linux zip from Google, [https://dl.google.com/android/repository/platform-tools-latest-linux.zip](https://dl.google.com/android/repository/platform-tools-latest-linux.zip) .

My adb adb version is 1.0.41 and is the only one on my computer.

Thank you for any help.

**Comment by rom1v** [comment]
> My adb version is 1.0.41 and is the only one on my computer.

It's not the only one, you probably have a program which restarts adb commands with adb 1.0.39.

Check `ps -ef | grep adb`.

**Comment by arnauldb** [comment]
Thank you rom1v, I just had it working but I have weird error messages due to my adb problems:
![BmDdboN](https://user-images.githubusercontent.com/13196747/59567169-9488e780-9059-11e9-824a-a9ca5a547e98.png)

If: 
```
 $  ps -ef | grep adb
arnauld  20848     1  0 19:03 ?        00:00:00 adb -L tcp:5037 fork-server server --reply-fd 5
arnauld  20855 20785  0 19:03 pts/3    00:00:00 adb shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 0 8000000 false - false true
arnauld  23240 23168  0 19:11 pts/4    00:00:00 grep --color=auto adb
```

When I do:
```
$  whereis adb
adb: /home/arnauld/adb-fastboot/platform-tools/adb
 arnauld  arnauldxxxxxx  ~  $  
```

**Comment by rom1v** [comment]
If you use the snap package, it seems it uses adb 1.0.39: https://github.com/Genymobile/scrcpy/issues/598#issuecomment-502468194

**Comment by arnauldb** [comment]
Yes, I use the snap package. But my problem seems to be solved now. I restarted my computer and my adb issue is gone. Thank you for this tool.

**Comment by sisco311** [comment]
> > My adb version is 1.0.41 and is the only one on my computer.
> 
> It's not the only one, you probably have a program which executes adb commands with adb 1.0.41, but scrcpy uses a version 1.0.39 from your PATH.
> 
> Check `ps -ef | grep adb`.
> 
> You can force a specific `adb`:
> 
> ```shell
> ADB=/path/to/adb scrcpy
> ```

Strictly confined snaps run in complete isolation and can not access any system resources without requesting specific access via an interface.

So the snap will fail to execute any instance of adb specified by the ADB variable.

I'm working on this issue. My plan is to split the snap package in two and provide multiple versions of adb as standalone snaps for the scrcpy snap.
