### ISSUE TITLE
error while installing scrcpy in linux lite 3.8(ubuntu version 16.04)

### ISSUE THREAD

**Issue by sep2001aryan** [Genymobile/scrcpy#602]
"In function ‘__recv_alias’,
    inlined from ‘run_receiver’ at ../app/src/net.c:86:12:
/usr/include/i386-linux-gnu/bits/socket2.h:39:9: warning: call to ‘__recv_chk_warn’ declared with attribute warning: recv called with bigger length than size of destination buffer
  return __recv_chk (__fd, __buf, __n, __bos0 (__buf), __flags);
         ^"
after executing
"ninja"
it showed the above error

**Comment by rom1v** [comment]
See #596.
