### ISSUE TITLE
Enabling "Grayscale" on Android Device does not display grayscale when mirrored

### ISSUE THREAD

**Issue by slenderbowman** [Genymobile/scrcpy#603]
This also occurs with color inversion and color correction. Unsure if this would be a feature request or bug.

**Comment by rom1v** [comment]
Android probably applies the filter afterwards (not on the surface which is encoded).

**Comment by reversegear** [comment]
that is how andorid's grey-scale and color inversion works.

to reconfirm take a screenshot in grey-scale view the screenshot in it will be in color

**Comment by slenderbowman** [comment]
yeah a screenshot does exhibit that behavior. Oh well, it is likely more trouble than it is worth/could just run Windows in grey-scale. Thank you.
