### ISSUE TITLE
screen tearing while swiping

### ISSUE THREAD

**Issue by amosbird** [Genymobile/scrcpy#604]
scrcpy plays quite well normally, however sometimes when scrolling or some animation is triggered, screen tears (it seems the resolution lowers and bumps quickly). And it takes a few seconds to settle down. Is it because of some issue of SDL / ffmpeg ?

**Comment by rom1v** [comment]
> it seems the resolution lowers and bumps quickly

I thinks it's just due to fast motion, which is more difficult to encode, especially in real-time.

> And it takes a few seconds to settle down.

See the end of this paragraph: https://github.com/Genymobile/scrcpy/blob/master/DEVELOP.md#screen-video-encoding

**Comment by amosbird** [comment]
Does it mean there is nothing we can do to better handle fast motion?

**Comment by rom1v** [comment]
Try to increase bitrate.

**Comment by amosbird** [comment]
I tried increasing bitrate to `64M`. It seems to have some effect but not obvious. What's a reasonable value? Shall I try some very large value like `1024M`?

**Comment by rom1v** [comment]
No, beyond a certain value, it won't have any effect (the encoder will not increase the bitrate indefinitely).

**Comment by amosbird** [comment]
OK. How can I modify scrcpy so that frames are generated no matter whether changes occur? I checked https://github.com/Genymobile/scrcpy/blob/master/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java#L90   but don't find the code that branches `change` flag.

**Comment by rom1v** [comment]
This is managed by Android internally: `MediaCodec` encodes a new frame when the surface changes. This is not configurable.

**Comment by redlaw2305** [comment]
If on linux make sure to have:  Option "TearFree" "true"  in xorg.conf
to make sure it works first try xrandr --output output --set TearFree on to turn it on temporarily if anything goes wrong just reboot, if the tearing is gone edit xorg.conf.

**Comment by rom1v** [comment]
No, the tearing occurs on the device side, even before it is displayed on the computer.

**Comment by redlaw2305** [comment]
I used scrcpy wireless and with usb both gave screen tear in fullscreen or window and it went away once i turned on tearfree surely this answer is usefull to someone.
