### ISSUE TITLE
add net_close(socket);

### ISSUE THREAD

**Issue by barry-ran** [Genymobile/scrcpy#607]
https://github.com/Genymobile/scrcpy/blob/b91ecf52256da73f5c8dca04fb82c13ec826cbd7/app/src/server.c#L156-L159
should close socket be added here?
```
if (net_recv(socket, &byte, 1) != 1) { 
     // the server is not listening yet behind the adb tunnel 
     net_close(socket);
     return INVALID_SOCKET; 
 }
```

**Comment by rom1v** [comment]
Yes, thank you :+1:

91ecb4f218f9a0f348ed8aee47919d6c2f4779a9
