### ISSUE TITLE
Windows Compatibility

### ISSUE THREAD

**Issue by reiniellematt** [Genymobile/scrcpy#61]
I've tried to run it on my Windows 10 32 bit machine but it said that "scrcpy.exe is not compatible with the version of Windows you're running." Is it only for 64 bit?

**Comment by rom1v** [comment]
Yes, the prebuilt is 64 bits. But you can build it manually, it should work.

**Comment by reiniellematt** [comment]
Any instructions on how to build in on 32bit? Or is the instruction on the
README also applies to 32 bit
