### ISSUE TITLE
Integration with Visual Studio Code

### ISSUE THREAD

**Issue by Wigny** [Genymobile/scrcpy#610]
Hello, your tool is amazing, the best I've ever encountered!
I'm using it along with the Visual Studio Code to view my app in real time, and for that, I have to keep splitting the screen of my notebook, and it bothers me a lot.
It would be interesting if there was an extension of your project in the VSCode Marketplace, as it is a form of integration in which the screen of the smartphone was shown inside the own editor, as is the case of the [Browser Preview](https://marketplace.visualstudio.com/items?itemName=auchenberg.vscode-browser-preview) ([gif](https://raw.githubusercontent.com/auchenberg/vscode-browser-preview/master/resources/demo.gif)), where a browser is opened within the VSCode .
I would love an extension like that. Many thanks and I'm sorry my English, I'm Brazilian :)

**Comment by rtrahms** [comment]
Question to Wigny:  when you say you're using the app with Visual Studio code, did you integrate scrcpy into a VS solution/project for the client?  If so, any guidance you could offer on that?  We are considering integrating the scrcpy client code into VS with some other functions.
Thanks in advance!
Rob

**Comment by yob8509** [comment]
We need to do the same thing here,did you find the way?
Thanks

**Comment by rrousselGit** [comment]
Hello!

@rtrahms This was about [Visual studio "code"](https://code.visualstudio.com/), not Visual Studio. So there's no solution/project there

I'm having the same need, as a Flutter developer and extensive user of VS code.
I quite like having the IDE in full-screen mode with scrcpy next to it. But doing so on mac requires a lot of operations with the mouse, which makes it painful to setup.

**Comment by Wigny** [comment]
Hello, @rrousselGit. That's exactly what I meant: a solution for Visual Studio Code. Developing with Flutter using scrcpy would be incredibly interesting if such integration with VS Code existed.

**Comment by rom1v** [comment]
I'm closing because it's out-of-scope for scrcpy itself. But anyone interested could implement it separately :wink:

**Comment by MAHakeem-MK** [comment]
Name: flutter Preview
Id: rexthedev.flutter-preview
Description: Preview a live version of your flutter application in an VS Code pane.
Version: 0.0.1
Publisher: rexthedev
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=rexthedev.flutter-preview

Try out this tool, at least you can have a look at your app's ui.

**Comment by qq147735456** [comment]
May I ask how to build and compile this project in Visual Studio 2019

**Comment by dream10201** [comment]
<img width="1912" height="867" alt="Image" src="https://github.com/user-attachments/assets/23c059df-1257-4094-a2ea-4cda5dd445f9" />

**Comment by Aradhya1905** [comment]
**📦 VS Code Scrcpy**
- **Marketplace**: [VS Code Scrcpy](https://marketplace.visualstudio.com/items?itemName=KarthikAradhya.vscode-scrcpy)
- **GitHub**: https://github.com/Aradhya1905/vscode-scrcpy

### Features
- **Real-time screen mirroring** in VS Code sidebar with full touch control
- **H.264 video streaming** up to 60 FPS with configurable resolution
- **Device controls** — Navigation, volume, power etc.
- **File Manager** — Browse, pull, and delete files on your device
- **ADB Shell** — Run ADB commands
- **Logcat Viewer** — Filter by package/level and crash detection
- **APK Installation** — Drag and drop to install

### Screenshots

![Screen Mirroring](https://raw.githubusercontent.com/Aradhya1905/vscode-scrcpy/main/images/screen-mirror.jpg)
*Real-time device display with touch controls*


![Logcat & Shell](https://raw.githubusercontent.com/Aradhya1905/vscode-scrcpy/main/images/MoreOptions.jpg)
*APK installer, ADB logcat, and shell*

### Requirements
- ADB in your PATH
- Android device with USB debugging enabled

Built using [@yume-chan's](https://github.com/yume-chan/ya-webadb) excellent TypeScript ADB/Scrcpy implementations
