### ISSUE TITLE
[server] ERROR

### ISSUE THREAD

**Issue by YanYangB** [Genymobile/scrcpy#613]
I also want to get the video stream only from the android like #129 . 
But when I run the command:
```
➜ /home/yanyang > adb shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 0 800000 true 
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: Expecting 5 parameters
	at com.genymobile.scrcpy.Server.createOptions(Server.java:71)
	at com.genymobile.scrcpy.Server.main(Server.java:132)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
```
I use it in Ubuntu18.04 
```
scrcpy 1.9

dependencies:
 - SDL 2.0.8
 - libavcodec 57.107.100
 - libavformat 57.83.100
 - libavutil 55.78.100
```
adb version: 1.0.41
Thanks.

**Comment by YanYangB** [comment]
I also want to get the video stream only from the android like #129 .
But when I run the command:

> ➜ /home/yanyang > adb shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 0 800000 true [server] ERROR: Exception on thread Thread[main,5,main] java.lang.IllegalArgumentException: Expecting 5 parameters at com.genymobile.scrcpy.Server.createOptions(Server.java:71) at com.genymobile.scrcpy.Server.main(Server.java:132) at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method) at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340) 

I use it in Ubuntu18.04

> scrcpy 1.9
dependencies:
SDL 2.0.8
libavcodec 57.107.100
libavformat 57.83.100
libavutil 55.78.100

adb version: 1.0.41
Thanks.

**Comment by rom1v** [comment]
There are more parameters now:

    adb shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 0 8000000 false - false true

See:
https://github.com/Genymobile/scrcpy/blob/91ecb4f218f9a0f348ed8aee47919d6c2f4779a9/server/src/main/java/com/genymobile/scrcpy/Server.java#L76-L93

**Comment by YanYangB** [comment]
Thanks for your reply. It is the parameters problem. 
But there are other problems:
`adb shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 0 800000 true - true true`
Then it block the terminal, is it normal?
Then I use another terminal run the command: 
`adb forward tcp:8080 localabstract:scrcpy`
Then I run a python script just like #129 , I can get the dummy byte (0), but I can't get the next 68 bytes. 
I try to wait a minute, but there are no bytes any more.

**Comment by rom1v** [comment]
Is there any message in `adb logcat`?

**Comment by rom1v** [comment]
Oh, of course it does not work anymore: now there are two sockets: ec71a3f66ab48c2fdd1728753acc09edbd4db570.

So you need to:

```bash
adb push scrcpy-server.jar /data/local/tmp/scrcpy-server.jar
adb forward tcp:8080 localabstract:scrcpy
adb shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 0 800000 true - true true
```

And you need to connect two sockets successively:
```bash
# video socket
nc localhost 8080
# control socket
nc localhost 8080
```

(the protocol between the server and the client is internal and can change at any time, I really need to expose a libscrcpy…)

**Comment by YanYangB** [comment]
Thank you so much !!
It's an amazing job.
Looking forward to your libscrcpy.

**Comment by NickStemerdink** [comment]
I'm having the same problem when following the [common steps of build.md](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#common-steps).

```
./run x
2019-07-12 12:30:04.693 scrcpy[12993:8476893] DEBUG: Using SCRCPY_SERVER_PATH: x/server/scrcpy-server.jar
x/server/scrcpy-server.jar: 1 file pushed. 5.4 MB/s (19734 bytes in 0.003s)
ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: Expecting 5 parameters
	at com.genymobile.scrcpy.Server.createOptions(Server.java:53)
	at com.genymobile.scrcpy.Server.main(Server.java:109)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:308)
```

**Comment by rom1v** [comment]
You must use the same version for the client and the server.

So `git pull` and use the last [prebuilt server](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#prebuilt-server).

**Comment by NickStemerdink** [comment]
Using the prebuilt server worked, thanks.

**Comment by siam-titan** [comment]
God I hope this thread isn't dead, I'm now facing an issue where after pushing the scrcpy-server file and adding classpath, I'm seeing that the client and server version doesn't match.

[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: The server version (1.24) does not match the client (0)
	at com.genymobile.scrcpy.Server.createOptions(Server.java:167)
	at com.genymobile.scrcpy.Server.main(Server.java:331)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)

Same commands were ran from above. I'm using scrcpy version 1.24, and downloaded the proper prebuilt server (scrcpy-server-v1.24) from the repo. Still the client version seems to show (0). What can I do?

**Comment by rom1v** [comment]
You must pass the paramters expected by `scrcpy-server`, as they are sent by the client: https://github.com/Genymobile/scrcpy/blob/v1.24/app/src/server.c#L163-L258

**Comment by siam-titan** [comment]
> 
```
adb shell CLASSPATH=/data/local/tmp/scrcpy-server-v1.24 app_process / com.genymobile.scrcpy.Server 0 800000 true - true true
``` 
This is what I'm using, is there something wrong with the parameters I'm passing?

**Comment by rom1v** [comment]
> This is what I'm using, is there something wrong with the parameters I'm passing?

Yes, this is wrong.

Check how the parameters are passed: https://github.com/Genymobile/scrcpy/blob/v1.24/app/src/server.c#L163-L258

```
adb shell CLASSPATH=/data/local/tmp/scrcpy-server-v1.24 app_process / com.genymobile.scrcpy.Server 1.24
```

is probably sufficient.

**Comment by siam-titan** [comment]
After running the code, I'm getting this error now,
```
adb shell CLASSPATH=/data/local/tmp/scrcpy-server-v1.24 app_process / com.genymobile.scrcpy.Server 1.24
```
[server] INFO: Device: Google AOSP on IA Emulator (Android 9)
[server] ERROR: Exception on thread Thread[main,5,main]
java.io.IOException: Connection refused
	at android.net.LocalSocketImpl.connectLocal(Native Method)
	at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:292)
	at android.net.LocalSocket.connect(LocalSocket.java:145)
	at com.genymobile.scrcpy.DesktopConnection.connect(DesktopConnection.java:45)
	at com.genymobile.scrcpy.DesktopConnection.open(DesktopConnection.java:72)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:74)
	at com.genymobile.scrcpy.Server.main(Server.java:335)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)

I'm having a really hard time understanding the code you provided unfortunately. What can I do now?

**Comment by rom1v** [comment]
@siam-titan This post might help you: https://code.videolan.org/rom1v/vlc/-/merge_requests/20

**Comment by siam-titan** [comment]
@rom1v thank you so much man, issues related to scrcpy was solved by that link. The stream works properly when I'm playing it with vlc/ffplay. But dunno why in the browser the video is corrupted. It's surely live because I can see the colors change when I interact with the emulator. I'm using h264-live-player library to decode the stream. Is there anything I can do now?
