### ISSUE TITLE
Dbus error, cannot start on ARM64

### ISSUE THREAD

**Issue by SaberMage** [Genymobile/scrcpy#615]
I successfully built scrcpy on my Linux L4T device running on ARM64 architecture. The application ran successfully and worked ONCE, but ever since then it has given me issues. Can't remember for the life of me what/if I did anything different on that one successful run.

The screenshot attached displays the error I am currently seeing.

![scrcpy Error Message](https://user-images.githubusercontent.com/1035144/59980982-2a28f780-95c3-11e9-9dc2-fb4d77828bca.png)

**Comment by rom1v** [comment]
https://forum.odroid.com/viewtopic.php?t=30652

> A workaround for the issue is to kill ibus (not dbus):
>
>     sudo killall ibus-daemon

**Comment by SaberMage** [comment]
@rom1v Perfect! This worked. Guess I should have searched **without** "scrcpy" as a keyword. I hadn't considered it might be a Linux distro issue. Thanks for the help.
