### ISSUE TITLE
App crash while rotating device screen

### ISSUE THREAD

**Issue by arley1708** [Genymobile/scrcpy#616]
Hii, first of all I love this app so much. For me, its the best screen mirroring app that I have ever tried.
But, I want to report my problem, maybe someone can help. If i start scrcpy with my device rotation is horizontal, then the app will crash if i rotate it to vertical, and it happens the otherwise.
I have tried different pc, cable, devices, and the result are same.

**Comment by rom1v** [comment]
Do you have any logs in the console?
In the output of `adb logcat` when it crashes?
Does the device still appears as connected in the output of `adb devices` after the crash?

**Comment by arley1708** [comment]
Hi thanks for your help, i found the problem sir. This problem occurs when i use the scrcpy as game capture for live streaming app. And it runs like normal if the scrcpy runs itself without being game captured by the live streaming app.
After crash, i must restart the cmd to run scrcpy again. And the device is still connected "adb devices". 
![IMG_20190624_085236](https://user-images.githubusercontent.com/52034842/59985947-9c024f00-965e-11e9-8f26-5c76049f8883.jpg)
![IMG_20190624_085200](https://user-images.githubusercontent.com/52034842/59985949-9c024f00-965e-11e9-9315-8a4b1e757b98.jpg)
![IMG_20190624_090040](https://user-images.githubusercontent.com/52034842/59985950-9c024f00-965e-11e9-85fd-fea4bb0cb712.jpg)
![IMG_20190624_085116](https://user-images.githubusercontent.com/52034842/59985951-9c9ae580-965e-11e9-8eda-114f53aff5fb.jpg)

**Comment by rommansabbir** [comment]
Yeah, same here.

**Comment by rom1v** [comment]
Fault Module Name: graphics-hook64.dll

It seems this library is related to OBS.

**Comment by arley1708** [comment]
So how can i fix it sir

**Comment by rom1v** [comment]
I guess you should report the problem on [OBS forums](https://obsproject.com/forum/), maybe they know a solution/workaround.

(FYI, I tested on Linux, it works fine, even when I rotate the device.)
