### ISSUE TITLE
[Hotkeys] Keyboard layout not recognized when switched in runtime

### ISSUE THREAD

**Issue by Plandercozeron** [Genymobile/scrcpy#617]
- ubuntu 18.10 (layout switch is set to `Caps Lock`)
- scrcpy 1.8

I use russian and US layouts. 
1) I start scrcpy while using russian layout —> hotkeys don't work
2) Switch layout to US —> hotkeys still don't work
3) Restart scrcpy with US layout —> hotkeys work

**Comment by rom1v** [comment]
Key events are generated by [SDL](https://libsdl.org/). I'm afraid there is nothing we can do in _scrcpy_.

**Comment by Plandercozeron** [comment]
I see. Maybe there's point to mark this issue as known. Don't think there're many people who use multiple layouts. Leaving it to you. Issue has no severity at all.
