### ISSUE TITLE
Display tun on, on right Mouse Button and Parameter --turn-screen-off

### ISSUE THREAD

**Issue by Bratmaxe1981** [Genymobile/scrcpy#618]
Hi.

thanks for adding the turn-screen-off parameter. 
it works, but if the screen get to sleep, I have to klick on the right mouse button du activate it again.
But if I do this, the screen on the phone also wake up. 
Is it possible to send the the go to sleep command every time the screen turn on (or every 15 Secondes / every minute) and the USB cabel is connected and the parameter ist active?
If you deaktivate the Power button it may happen, that you get locked out of your own phone.

Thanks

**Comment by rom1v** [comment]
> it works, but if the screen get to sleep, I have to klick on the right mouse button du activate it again.
But if I do this, the screen on the phone also wake up.

Yes, this is the Android behavior: https://github.com/Genymobile/scrcpy/issues/175#issuecomment-473412085.

> Is it possible to send the the go to sleep command every time the screen turn on (or every 15 Secondes / every minute) and the USB cabel is connected and the parameter ist active?

Too hacky. `--turn-screen-off` is just an option to turn it off on start. If you execute actions to turn it (like the power button), you can stlil turn it off again using `Ctrl`+`o`.

**Comment by Bratmaxe1981** [comment]
okay thanks, I'll use the CTRL+o funktion..
