### ISSUE TITLE
APK-Installation with locked screen

### ISSUE THREAD

**Issue by Bratmaxe1981** [Genymobile/scrcpy#619]
Hy.

I don't know if it is a bug, but I can install an apk-File by dropping it down on the locked screen on windows, and it gets installed without any response or question. 
Isen't it a security problem, if I can do that, without unlocking the phone screen?

**Comment by rom1v** [comment]
It's just like if you executed:

    adb install file.apk

manually (screen locked or not).

> without any response or question

_scrcpy_ does only report things in the console (it could be improved to use an OSD instead).
