### ISSUE TITLE
Not working with netflix

### ISSUE THREAD

**Issue by massimilianov97** [Genymobile/scrcpy#62]
I tried netflix and the audio works great, but unfortunately the screen il totally black!!
Do you have a workaround or are you aware of the problem looking for a fix?
Thanks

**Comment by rom1v** [comment]
They're probably [protecting the screen](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#i-get-a-black-screen-for-some-applications-like-silence).

You have the same problem if you record using `screenrecord`:

    adb shell screenrecord /sdcard/file.mp4
    adb pull /sdcard/file.mp4

Without modifying the ROM, this is the expected behavior :disappointed:

**Comment by massimilianov97** [comment]
thanks anyway

**Comment by massimilianov97** [comment]
I've solved. But it needs Xposed Framework. There is a module called DisableFlagSecure but in this case there is the need for a phone rooted and with Xposed...not easy but works great

**Comment by jaynford** [comment]
> It should work with v1.6.

I am still getting a black screen on Netflix/Hulu/YoutubeTV. I am doing it over the network if that makes any difference.

**Comment by rom1v** [comment]
`scrcpy -v` returns 1.6? If compiled manually with prebuilt server, did you correctly used prebuilt server v1.6?

(I ask just to be sure)

It can still happen on v1.6 though, we told me that it depends on the DRM used (widevine L3 vs widevine L1).

**Comment by jaynford** [comment]
Yeah -v returns 1.6. On Windows and accessing an Nvidia Shield TV. It works great otherwise, but still getting that video protection kicking in.
