### ISSUE TITLE
[specify network]when I have multiple network conencted

### ISSUE THREAD

**Issue by latel** [Genymobile/scrcpy#620]
Hey there, 

I have multiple network connected, an ethernet and a wifi network, I want to connect to my android wirelessly, but scrcpy always use my ethernet ip to connect, this is the problem, sorry for my poor English.

![image](https://user-images.githubusercontent.com/5621862/60065886-e99eba80-9737-11e9-90ea-748e2651b24d.png)

**Comment by rom1v** [comment]
> but scrcpy always use my ethernet ip to connect

_scrcpy_ just uses `adb`. Did you connect using `adb connect`? What is the result of `adb devices` after that?

**Comment by latel** [comment]
> > but scrcpy always use my ethernet ip to connect
> 
> _scrcpy_ just uses `adb`. Did you connect using `adb connect`? What is the result of `adb devices` after that?

you mis-understand my question :), I have not yet connected to my phone, because adb is selecting the wrong network.

my mac is connected to both ethernet and wifi, ethernet has the highest priority,
my phone is connected to wifi,

when I use adb connect ****, adb automatically use the ethernet, of course, is unable to connect to my phone which is under the wifi network.

**Comment by rom1v** [comment]
> because adb is selecting the wrong network.

> when I use adb connect ****, adb automatically use the ethernet

How did you come to that conclusion?

`adb` does not "select" any network, it's your system which decides the route depending on the IP.

What is the result of `ip route`? What is your device IP?

**Comment by carstenhag** [comment]
Likely you will need to just change the network order in the mac settings. Other things will change with that though, of course.
