### ISSUE TITLE
Scrcpy: unrecognized option '--no-display'

### ISSUE THREAD

**Issue by yingying96** [Genymobile/scrcpy#621]
Tried to run something like this and linux ubuntu shows the error message - unrecognized option '--no-display'.

The following command works on Mac terminal but not the linux one.
`cmd = "scrcpy --no-display " + "--serial " + o + " --record " + "logs/" + o + ".mp4 -p " + str(sport) `

When i run scrcpy --version, it displays scrcpy 1.5

Not too sure if this is a bug?

**Comment by yingying96** [comment]
I guess it was because I was running headless for my linux VM so it did not recognize the --no display command. Removing the --no display command helped to remove the error.

**Comment by rom1v** [comment]
> When i run scrcpy --version, it displays scrcpy 1.5

Then you run an old verson. Build and install the last one (currently v1.9).

**Comment by npes87184** [comment]
There are several users try to use new features on older version.

It may be unrelated and ugly. But, what do you think about adding a feature which will check new version when scrcpy is up?

There are some advantages on this feature:

1. If there are some CVEs in the future. User can notice that there is a new and fixed version
2. Prevent the same issue happening again.
3. Promote new features and fixes.
4. maybe more...

But it may need to link libcurl and somehow not elegant.

**Comment by yingying96** [comment]
Oh i see. Any idea how to update scrcpy? I run the installation commands again on linux but seems like it's not working. Still at 1.5.

**Comment by npes87184** [comment]
> Oh i see. Any idea how to update scrcpy? I run the installation commands again on linux but seems like it's not working. Still at 1.5.

How do you install scrcpy before?

**Comment by rom1v** [comment]
> It may be unrelated and ugly. But, what do you think about adding a feature which will check new version when scrcpy is up?

I agree with your points, but I would prefer not to notify a server when someone starts _scrcpy_. It would be ok with an explicit option (`--check-updates`), but then it would be useless.

> I run the installation commands again on linux but seems like it's not working.

    git pull

from your scrcpy repo to update the sources, then bulid the sources (if you use the [prebuilt server](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#prebuilt-server), don't forget to use the last version).

**Comment by npes87184** [comment]
> > It may be unrelated and ugly. But, what do you think about adding a feature which will check new version when scrcpy is up?
> 
> I agree with your points, but I would prefer not to notify a server when someone starts _scrcpy_. It would be ok with an explicit option (`--check-updates`), but then it would be useless.

Oh, I see.

Thank you.

> 
> > I run the installation commands again on linux but seems like it's not working.
> 
> ```
> git pull
> ```
> 
> from your scrcpy repo to update the sources, then bulid the sources (if you use the [prebuilt server](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#prebuilt-server), don't forget to use the last version).
