### ISSUE TITLE
it there any way that I can reduce latency?

### ISSUE THREAD

**Issue by Shuaiouke** [Genymobile/scrcpy#622]
can I sacrifice video quality to trade lower latency? Simular to https://github.com/Genymobile/scrcpy/issues/77

**Comment by rom1v** [comment]
Try reducing the definition and the bitrate:

    scrcpy -m800 -b2M

**Comment by Shuaiouke** [comment]
do I need to change the number?

**Comment by Shuaiouke** [comment]
and just asking, how do you make livings out of this thing

**Comment by Shuaiouke** [comment]
and it don't make a difference for me

**Comment by rom1v** [comment]
> do I need to change the number?

`-m`/`--max-size` is the maximum width and height. Use the size you want.
`-b`/`--bit-rate` is… the bitrate. Default is 8 Mbps. Use the value you want too.

> and just asking, how do you make livings out of this thing

I was an employee at Genymobile when I developed the first version. Now I develop it on my free time, totally volunteer.

But don't worry for me, I am paid as a [Videolabs](https://videolabs.io/) employee to work on other cool open source projects (VLC) :wink:

> and it don't make a difference for me

Then you won't get a better latency. Is it over USB? How much latency do you have? It should not be more than 100ms (and probably lower).

**Comment by Shuaiouke** [comment]
indirect advertisement XD and my phone is 4k but when I reduce it to 800*something, the latency is like 0.001% better

**Comment by Shuaiouke** [comment]
and if I set bitrate higher than 8m, will the quality be better?

**Comment by rom1v** [comment]
> and if I set bitrate higher than 8m, will the quality be better?

It's encoder-dependant. In practice, 12m or 16m can increase, beyond has no effect.

**Comment by Shuaiouke** [comment]
ok

**Comment by Shuaiouke** [comment]
also, are you planning on making keybinding?
like those emulators when you press a key it presses a certain place on the screen

**Comment by rom1v** [comment]
No, I am not planning that.

**Comment by Shuaiouke** [comment]
ok thx

**Comment by jfmaradiaga** [comment]
> Try reducing the definition and the bitrate:
> 
> ```
> scrcpy -m800 -b2M
> ```

Thank you very much, this solved my problem.

**Comment by wiiznokes** [comment]
You can also limit fps. I was able to reduce latency + upgrade the resolution by limiting the framerate in my game. You can use the `--print-fps` to have an idea for the value, and you can also use `--max-fps=30`.
Also, using the codec h264 is probably better than av1 or h265.
