### ISSUE TITLE
support for utf8 character in installing apk file.

### ISSUE THREAD

**Issue by NewUserHa** [Genymobile/scrcpy#628]
always `Failure [INSTALL_FAILED_INVALID_URI]`.
```
INFO: Installing C:\腾讯视频.apk...
Performing Push Install
C:\腾讯视频.apk: 1 file pushed. 3.7 MB/s (40536023 bytes in 10.447s) There's display issue as well(at this line)
        pkg: /data/local/tmp/腾讯视退+
Failure [INSTALL_FAILED_INVALID_URI]
INFO: C:\腾讯视频.apk successfully installed
```

**Comment by rom1v** [comment]
What if you execute directly:

    C:\腾讯视频.apk

?

**Comment by NewUserHa** [comment]
didn't have default open with. nothing happens

**Comment by rom1v** [comment]
(I edited my message)

**Comment by NewUserHa** [comment]
the same.

**Comment by rom1v** [comment]
If you have the same error with `adb` alone, then it's a bug in `adb`. Nothing we can do in scrcpy to fix it. :(

**Comment by NewUserHa** [comment]
I found there're some adb support unicode. scrcpy may consider using those

**Comment by NewUserHa** [comment]
or create temp name before giving to adb and print apks' app name for user experience

**Comment by NewUserHa** [comment]
also, I saw that issue which implements a Qt GUI for scrcpy.

I think scrcpy could beat a lot of business software if add a startup UI for choosing devices, and a button for recording for broadcasting, instead of a overloaded GUI to make this like the OBS.

**Comment by NewUserHa** [comment]
the auto rotating will reposition the whole window. making the middle always the same may fix this.

**Comment by rom1v** [comment]
I think it's fixed in `adb` now.
