### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by massimilianov97** [Genymobile/scrcpy#63]
Application like netflix or Silence have a security flag blocking any screenshot(and so scrcpy), I've found a solution but it needs Xposed Framework. There is a module called DisableFlagSecure but in this case there is the need for a phone rooted and with Xposed...not easy but works great

**Comment by rom1v** [comment]
Thank you for the information.

But I think you wanted to post your comment here: https://github.com/Genymobile/scrcpy/issues/62
