### ISSUE TITLE
Some games not registering clicks

### ISSUE THREAD

**Issue by Aimsucks** [Genymobile/scrcpy#635]
Clicks are not working in Infinitode 2 and Infinitode, but they work in all my other games. Is there any kind of option I need to enable for them to work?

Here is a video I made trying to show this issue:
https://youtu.be/Lth0tK1zIkc

**Comment by mentz** [comment]
The problem persists on v1.10. I'm using a LG G7 ThinQ running stock vendor Android 8.0.0.

**Comment by rom1v** [comment]
I don't know why they don't receive clicks.

Do they receive keyboard events (if there is somewhere you can type text)?

When you click, are there any relecant logs in `adb logcat`?

**Comment by rom1v** [comment]
Fixed on `master` by 17d53be3ef9d376e48a7f9e90cf6c87cf8fbf8f5.
