### ISSUE TITLE
SCRCPY not responding to touchscreen input

### ISSUE THREAD

**Issue by BigDogBoy** [Genymobile/scrcpy#636]
I have a triple boot system, between Windows 10, Ubuntu (the OS I'm using right now) 19.04, and Zorin OS 15. When I'm using SCRCPY on Windows, I can use my touchscreen for input, in addition to the keyboard, and mouse, but not in Ubuntu; [in Ubuntu] it works, as regular, elsewhere, just not with SCRCPY. I'm currently using the SNAP package; I tried building it from source, but that didn't work; I tried for 15 hours, and failed, each time, and finally opted for the preconfigured SNAP package.

**Comment by rom1v** [comment]
@sisco311 any idea?

**Comment by rom1v** [comment]
> I tried building it from source, but that didn't work; I tried for 15 hours, and failed, each time

:scream: 

Where did it fail?

Did you use the [prebuilt server](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#prebuilt-server)?

Did you follow [BUILD.md](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md)?

```bash
# runtime dependencies
sudo apt install ffmpeg libsdl2-2.0-0

# client build dependencies
sudo apt install make gcc git pkg-config meson ninja-build \
                 libavcodec-dev libavformat-dev libavutil-dev \
                 libsdl2-dev

git clone https://github.com/Genymobile/scrcpy
cd scrcpy

meson x --buildtype release --strip -Db_lto=true \
    -Dprebuilt_server=/path/to/scrcpy-server.jar # edit the path!
cd x
ninja
sudo ninja install

**Comment by sisco311** [comment]
You can use snappy-debug to parse the log file(s) for errors in real time. 
`sudo snap install snappy-debug`
Run it in a terminal:
`sudo snappy-debug`
then start `scrcpy` in another terminal window.
Post the output of snappy-debug here.

**Comment by BigDogBoy** [comment]
I have NO idea where it failed; that's why I posted; yes I used the prebuilt server, and I (as best as possible) tried to follow build.md; "MAN, that thing is "as clear as pea soup", to understand.".

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by unclehowell** [comment]
Was just told it is implemented on development branch and will be in the next release.  Same issue as well.

**Comment by SowingFiber** [comment]
Hello, If anybody still has issues with scrcpy touch, try to lower the resolution at which your phone is being displayed. I ran into this problem, because, I have a newer phone, with a relatively older laptop. The laptop graphics were able to support the high res display of my phone, but the touch didn't work. 

To mitigate this issue I used the following command.

```

    scrcpy -m 768  #This 768 number is the resolution you can set. You can go lower for older phones.

```

**Comment by rom1v** [comment]
Thank you for your feedbacks.

> The laptop graphics were able to support the high res display of my phone, but the touch didn't work.

This is weird. If you switch to fullscreen, does it work?

If you try to click anywhere in the window, does it sometimes click somewhere at a wrong position on the device?

**Comment by SowingFiber** [comment]
I just tested it out. And I could not see any visible touches.
So i thought I'd test it thoroughly. I went into developer settings and turned on the following options

- Show touches
- Show pointer location
- Show surface updates

Then I launched `scrcpy` and switched to full screen.
I tried touching, tapping, scrolling. But I didn't get any feedback. 

I went back to using `scrcpy -m 1080` and it worked fine.

**Comment by rom1v** [comment]
OK, that's very surprising to me.

When you click, do you see any error in the output of `adb logcat`?

What if you keep the full definition, but use a lower bitrate?

```bash
scrcpy -b2M
```

**Comment by SowingFiber** [comment]
First of all, I'm not very versatile in reading adb logcat. 
So I'll post it in a [gist](https://gist.github.com/SowingFiber/a1b35b33bea787da13d327aef2aa9f0d) for you to look at.

Still did not get any touch input even at a lower bitrate.

**Comment by rom1v** [comment]
OK, nothing special on the Android side when you start scrcpy. Maybe the computer is so busy that it may not process input touch correctly… If you could try another device on this computer, and this device on another computer, that could be interesting…

**Comment by SowingFiber** [comment]
That could be very interesting indeed. However, I have one computer and one device at my disposal currently. When I get more devices, I'll respond back, in this comment itself.

**Comment by rom1v** [comment]
Does it still happen?

**Comment by BigDogBoy** [comment]
The issue is resolved; I've got a whole different computer, and installation.
