### ISSUE TITLE
No protocol specified segmentation fault

### ISSUE THREAD

**Issue by Mike-M-12** [Genymobile/scrcpy#639]
Just installed scrcpy on my Ubuntu 18.04 machine using snap, v1.9. I have usb debugging turned on my Moto G6, and the device says it's connected properly. When I run `scrcpy` I get an error about protocol and a segmentation fault:

```
me@me-ubuntu:~$ scrcpy
* daemon not running; starting now at tcp:5037
* daemon started successfully
/usr/local/share/scrcpy/scrcpy-server....shed. 3.0 MB/s (22470 bytes in 0.007s)
No protocol specified
Segmentation fault (core dumped)
```

Let me know if there is additional info I can dump.

**Comment by rom1v** [comment]
I think the segmentation fault is on the device side.

Are there more logs in `adb logcat`? What is the device and Android version?

**Comment by rom1v** [comment]
Oh, it seems `No protocol specified` comes from X: https://unix.stackexchange.com/questions/209746/how-to-resolve-no-protocol-specified-for-su-user

So aybe a _snap_ issue? cc @sisco311

**Comment by Mike-M-12** [comment]
I am connected to the Linux box via VNC, would that affect X?

**Comment by Mike-M-12** [comment]
Actually, after looking at your link, the fix was fairly easy, just

```
xhost +
```

From what I understand, there was an issue with which user was allowed xhost access. Thanks @rom1v !

**Comment by rom1v** [comment]
:+1:

I'm still interested in where the segfault come from? In particular, is _scrcpy_ assuming that something is ok while it's not, or does it crash in some non-scrcpy related code?

(if you know how to build in debug mode and execute scrcpy in gdb, we'll get the answer :wink:)

**Comment by sisco311** [comment]
It's an issue with the snap package. I don't use VNC, but I was able to create a similar scenario by un-setting the DISPLAY variable. 

[Here](https://pastebin.ubuntu.com/p/6mXZ7RkNM8/) is the output of `run x` and `/snap/bin/scrcpy`

And [here](https://pastebin.ubuntu.com/p/RPdfYGcXp4/) is the output of journalctl when the snap is segfaulting.

**Comment by arieltools** [comment]
I was able to reproduce this. Uninstalling the snap and re-instaling it resulted in the tool to work again.

**Comment by wcypierre** [comment]
I was also able to reproduce this in a xubuntu VM hosted using Proxmox.

The link in the unix stackexchange did the trick!

**Comment by SyntHaxTErrOrNot** [comment]
Sent from my Huawei phone-------- Original Message --------Subject: Re: [Genymobile/scrcpy] No protocol specified segmentation fault (#639)From: wcypierre To: Genymobile/scrcpy CC: Subscribed 
I was also able to reproduce this in a xubuntu VM hosted using Proxmox.
The link in the unix stackexchange did the trick!

**Comment by LGR3** [comment]
Same Ubuntu 18 here; I realized that I was in sudo mode.

With **`exit`** and running `scrcpy` again all worked.
