### ISSUE TITLE
Minimize problem

### ISSUE THREAD

**Issue by tonypachino** [Genymobile/scrcpy#640]
how can i minimize apps when my phone have only physical options buttons?

**Comment by jie170601** [comment]
May be you can click the center button of the mouse to return the home, or use ctrl+s to APP_SWITCH mode.

**Comment by tonypachino** [comment]
> 
> 
> May be you can click the center button of the mouse to return the home, or use ctrl+s to APP_SWITCH mode.

Which keyboart combination i can use to close apps if i'm only on touchpad of my laptop and i don't have a mouse?

**Comment by jie170601** [comment]
Ctrl+b/Ctrl+Backspace: click on Back
Ctrl+h: click on Home

you can use scrcpy --help for more info.
