### ISSUE TITLE
Use Cmd+c/Cmd+c on Mac OS?

### ISSUE THREAD

**Issue by rom1v** [Genymobile/scrcpy#642]
On Mac OS, should we use Cmd instead of Ctrl to copy-paste?

If yes, we should ifdef the same way we do for the volume:
https://github.com/Genymobile/scrcpy/blob/49612561233b3cde41339ee08c71892e42649706/app/src/input_manager.c#L293-L297

here:
https://github.com/Genymobile/scrcpy/blob/49612561233b3cde41339ee08c71892e42649706/app/src/input_manager.c#L312-L327

**Comment by npes87184** [comment]
IMO, it should be `cmd`.

**Comment by rom1v** [comment]
OK. Are there any other shortcuts which should use Cmd instead of Ctrl on MacOS?

**Comment by npes87184** [comment]
In MacOS, (almost) all ctrl should be replaced by cmd.

**Comment by carstenhag** [comment]
Yeah, on mac I usually only use ctrl on the terminal

**Comment by rom1v** [comment]
Mac users, please test #676 :wink: Thank you

**Comment by rom1v** [comment]
Mac users, I would like your opinion on #1446 :)
