### ISSUE TITLE
SCRCPY mp4 file with no timestamps?

### ISSUE THREAD

**Issue by initialdg** [Genymobile/scrcpy#643]
When I play my recorded mp4 file in Windows Media Player classic I cant seem to 'skip'through the video like with other mp4 files? Eg - If I skip forward 5 seconds the seek bar keeps moving but the video is not showing. Seems like it doesnt have correct time stamps or headers etc??

Also when I open the mp4 file in the Smart Cutter program, I cant seem to edit it. Eg - I cant cut parts of the video.

Any help would be greatly appreciated. Thanks.

**Comment by rom1v** [comment]
Did you record with scrcpy v1.9? Is there any actiivity on the device screen (if the content does not change, no new frame is generated)?

Does it work in VLC?

**Comment by initialdg** [comment]
I dont think it was v1.9 actually. I downloaded scrcpy in March. 
And yes the video does play in the media players, but I cannot edit it etc

**Comment by rom1v** [comment]
OK, you should retry with the last version then.

In particular, v1.7 fixed mp4 headers: #351 #416

**Comment by initialdg** [comment]
Just recorded then with v1.9 but still the same problem :(

**Comment by rom1v** [comment]
> And yes the video does play in the media players
and you can seek?

> but I cannot edit it etc

The video has a variable framerate (it produces a new frame whenever a changes occurs on the device surface). Maybe your video editor does not support it correctly. I just tested with pitivi, it can edit it.

**Comment by initialdg** [comment]
Okay after some research and playing around it seems that that is what the problem is - the recorded mp4 file is just like you said is Variable Framerate and thus the Smart Cutter program I normally use to cut mp4's does not work. I am using Windows so I cant use pitivi.

There are cutting programs that do work but they can only cut by key frame and I need one that can do frame accurate cuts like in Smart Cutter. I tried using Handbrake to convert the mp4 from VFR to CFR and it works all good but there is quality loss :( 
If I chose "lossless" option in Handbrake the file size is insanely large... so I have three questions:

1) Are you able to change it so that scrcpy records the mp4 in Constant Framerate?

2) If not, do you know any Windows programs that can cut by frame accurate cutting and not just by key frames for VFR mp4 files?

3) Do you know any program that can change from VFR to CFR without re-encoding?

**Comment by rom1v** [comment]
> Are you able to change it so that scrcpy records the mp4 in Constant Framerate?

No, `MediaCodec` encodes a frame whenever the underlying surface change (and only when it changes).

> If not, do you know any Windows programs that can cut by frame accurate cutting and not just by key frames for VFR mp4 files?

No. But if you cut at a frame which is not a keyframe, how do you render it? You need the info from the previous keyframes (and possibly other previous frames). Maybe the correct solution is to cut at keyframe but add metadata (in a mkv for example) to indicate where it should start exactly.

> Do you know any program that can change from VFR to CFR without re-encoding?

IMO this is not possible. Of course you can just change the timestamps, but this won't be the "same" video (the rhythm won't be the same).
