### ISSUE TITLE
setClipboardText BUG？

### ISSUE THREAD

**Issue by mo2phone** [Genymobile/scrcpy#644]
```java
   public void setClipboardText(String text) {
        serviceManager.getClipboardManager().setText(text);
        Ln.i("Device clipboard set");
    }
```

before android api 11 is setText,

but,

after android api 11

```java
String text = copyField.getText().toString();
myClip = ClipData.newPlainText("text", text);
myClipboard.setPrimaryClip(myClip);
```

My English is not very good, please understand!!!

**Comment by rom1v** [comment]
The wrapper API is simplified. It exposes `getText()` but calls `setPrimaryClip()` internally:
https://github.com/Genymobile/scrcpy/blob/49612561233b3cde41339ee08c71892e42649706/server/src/main/java/com/genymobile/scrcpy/wrappers/ClipboardManager.java#L24-L34

**Comment by mo2phone** [comment]
> 
> 
> The wrapper API is simplified. It exposes `getText()` but calls `setPrimaryClip()` internally:
> 
> https://github.com/Genymobile/scrcpy/blob/49612561233b3cde41339ee08c71892e42649706/server/src/main/java/com/genymobile/scrcpy/wrappers/ClipboardManager.java#L24-L34


![2019-07-12_002131](https://user-images.githubusercontent.com/52404502/61067998-79807c00-a43b-11e9-8f2d-90bae35a3737.jpg)

**Comment by mo2phone** [comment]
but why in Clipboard no data?

**Comment by rom1v** [comment]
Select some text on your computer, press `Ctrl`+`c`. Then go to your device (in some text field or text area), and press `Ctrl`+`Shift`+`v`.

Does it print the following line in the console:
```
[server] INFO: Device clipboard set
```
?

If yes, then you should be able to long-click on a text field on your device, then press PASTE.

**Comment by mo2phone** [comment]
> 
> 
> Select some text on your computer, press `Ctrl`+`c`. Then go to your device (in some text field or text area), and press `Ctrl`+`Shift`+`v`.
> 
> Does it print the following line in the console:
> 
> ```
> [server] INFO: Device clipboard set
> ```
> 
> ?
> 
> If yes, then you should be able to long-click on a text field on your device, then press PASTE.

ctrl+c and ctrl v wrok well，but ，in phone Clipboard no data？

![2019-07-12_003134](https://user-images.githubusercontent.com/52404502/61068490-bc8f1f00-a43c-11e9-840c-3a7f30393238.jpg)

**Comment by rom1v** [comment]
> ctrl+c and ctrl v wrok well

Not `Ctrl`+`v` (which injects characters one by one), but `Ctrl`+`Shift`+`v`.

**Comment by mo2phone** [comment]
> 
> 
> > ctrl+c and ctrl v wrok well
> 
> Not `Ctrl`+`v` (which injects characters one by one), but `Ctrl`+`Shift`+`v`.



step by step，1，2，3，4
![2019-07-12_004045](https://user-images.githubusercontent.com/52404502/61069147-3ecc1300-a43e-11e9-8726-d98b67e43236.jpg)

**Comment by rom1v** [comment]
If you long-press on a text area, then press PASTE, does it work?

I don't know what is your "CLIPBOARD" component on your device. Is it specific to your app? Is it filled when you just long-press and click "COPY" from anywhere (without scrcpy)?

**Comment by mo2phone** [comment]
> 
> 
> If you long-press on a text area, then press PASTE, does it work?
> 
> I don't know what is your "CLIPBOARD" component on the bottom of your device. Is it specific to your app? Is it filled when you just long-press and click "COPY" from anywhere (without scrcpy)?

![2019-07-12_005133](https://user-images.githubusercontent.com/52404502/61069699-7b4c3e80-a43f-11e9-82d1-449fe23290f4.jpg)

**Comment by rom1v** [comment]
I meant, the same (COPY), but from another app (your browser for example). Does it fill the clipboard in this app?

Also:

> If you long-press on a text area, then press PASTE, does it work?

**Comment by mo2phone** [comment]
> browser

test in firefox browser ，the result is same;

**Comment by rom1v** [comment]
If you `Ctrl`+`Shift`+`v` in scrcpy, then long-press on a text area, then press PASTE, does it work or not?

**Comment by mo2phone** [comment]
> 
> 
> If you `Ctrl`+`Shift`+`v` in scrcpy, then long-press on a text area, then press PASTE, does it work or not?

can't paste because the clipboard has no data, or paste is a piece of data on the clipboard

**Comment by rom1v** [comment]
Are there any relevant logs in the output of `adb logcat` when you `Ctrl`+`Shift`+`v`?

**Comment by mo2phone** [comment]
![2019-07-12_011346](https://user-images.githubusercontent.com/52404502/61071136-e51a1780-a442-11e9-9fd6-d3f0f10117ee.jpg)

I changed the input method and can detect the contents of the paste board,
But I in the system input method inside, still show paste board is empty

**Comment by mo2phone** [comment]
来自粘贴板=From paste board

**Comment by mo2phone** [comment]
`public class MainActivity extends AppCompatActivity {

    RelativeLayout  mainLayout;
    EditText            mEditText;
    Button               mBtnCopy;
    static   int         ID_EDIT_INPUT=0x01;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mainLayout=new RelativeLayout(this);
        RelativeLayout.LayoutParams params=new RelativeLayout.LayoutParams(RelativeLayout.LayoutParams.MATCH_PARENT,
                RelativeLayout.LayoutParams.WRAP_CONTENT);
        params.addRule(RelativeLayout.ALIGN_PARENT_TOP);
        mEditText=new EditText(this);
        mEditText.setText("copy test 007");
        mEditText.setId(ID_EDIT_INPUT);
        mainLayout.addView(mEditText,params);

        mBtnCopy=new Button(this);
        params=new RelativeLayout.LayoutParams(RelativeLayout.LayoutParams.WRAP_CONTENT,
                RelativeLayout.LayoutParams.WRAP_CONTENT);
        params.addRule(RelativeLayout.ALIGN_PARENT_BOTTOM|RelativeLayout.CENTER_HORIZONTAL);
        params.addRule(RelativeLayout.BELOW,ID_EDIT_INPUT);
        mBtnCopy.setText("Do Copy ");
        mBtnCopy.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                ClipboardManager clipboardManager = (ClipboardManager) getSystemService(Context.CLIPBOARD_SERVICE);
                //创建ClipData对象
                ClipData clipData = ClipData.newPlainText("null", mEditText.getText());
                //添加ClipData对象到剪切板中
                clipboardManager.setPrimaryClip(clipData);
            }
        });
        mainLayout.addView(mBtnCopy,params);

        setContentView(mainLayout);
    }`

i write a demo，copy to clipboard is work well

![2019-07-12_105423](https://user-images.githubusercontent.com/52404502/61098983-6e593a80-a493-11e9-8dbe-a3b8efa6a0a6.jpg)


![2019-07-12_105335](https://user-images.githubusercontent.com/52404502/61098956-584b7a00-a493-11e9-9aee-992e15a8f7fa.jpg)

**Comment by mo2phone** [comment]
look here ，https://blog.csdn.net/ys743276112/article/details/79083798

**Comment by rom1v** [comment]
Your sample is basically what scrcpy [does](https://github.com/Genymobile/scrcpy/blob/master/server/src/main/java/com/genymobile/scrcpy/wrappers/ClipboardManager.java) (but from an app with an Android `Context`).

Anything in `adb logcat` when you `Ctrl`+`Shift`+`v`?

**Comment by mo2phone** [comment]
> 
> 
> Your sample is basically what scrcpy [does](https://github.com/Genymobile/scrcpy/blob/master/server/src/main/java/com/genymobile/scrcpy/wrappers/ClipboardManager.java) (but from an app with an Android `Context`).
> 
> Anything in `adb logcat` when you `Ctrl`+`Shift`+`v`?

07-12 18:05:24.707  1459  4821 I ClipboardService: getSEAMSCategory, before checking range, category: 0, seinfo: platform:privapp:targetSdkVersion=26
07-12 18:05:24.707  1459  4821 I ClipboardService: getSEAMSCategory, category: 0, seinfo: platform:privapp:targetSdkVersion=26
07-12 18:05:24.714 30329 30347 I scrcpy  : Device clipboard set
07-12 18:05:24.719  1459  3194 D PackageManager: setEnabledSetting : userId = 0 packageName = com.google.android.gms cmp = com.google.android.location.drivingmode.DrivingModeSettingsNoSummaryActivity newState = 2 callingPackage = 10187/com.google.android.gms.persistent
07-12 18:05:24.719  1459  4813 I ClipboardService: getSEAMSCategory, before checking range, category: 1023, seinfo: untrusted:targetSdkVersion=26
07-12 18:05:24.719  1459  4813 I ClipboardService: getSEAMSCategory, category: 0, seinfo: untrusted:targetSdkVersion=26
07-12 18:05:24.730  1459  4813 I ClipboardService: getSEAMSCategory, before checking range, category: 1023, seinfo: untrusted:targetSdkVersion=26
07-12 18:05:24.730  1459  4813 I ClipboardService: getSEAMSCategory, category: 0, seinfo: untrusted:targetSdkVersion=26
