### ISSUE TITLE
input method did not work in HUAWEI P20

### ISSUE THREAD

**Issue by zerobikappa** [Genymobile/scrcpy#645]
computer operation: 5.2.0-arch2-1-ARCH
phone model: HUAWEI P20
issue: when using the computer keyboard to type, the characters were directly posted on screen instead of being passed to input method application.

**Comment by rom1v** [comment]
When you type, the text is injected by sending a sequence of `InputEvent`:
https://github.com/Genymobile/scrcpy/blob/master/server/src/main/java/com/genymobile/scrcpy/Controller.java#L139-L149

Each one is injected via `InputManager.injectInputEvent()`.
https://github.com/Genymobile/scrcpy/blob/master/server/src/main/java/com/genymobile/scrcpy/wrappers/InputManager.java#L29

It probably bypasses the input method… like `adb shell input text` does.

**Comment by zerobikappa** [comment]
thank you...I tried `adb shell input text abc` but the same problem occurred. It is not the issue for `scrcpy`. I reported this issue to HUAWEI customer service.

**Comment by Rapiz1** [comment]
Got the same issue here.
Is it possible to type by using the input method of the computer and send the character to the phone? I think it maybe more useful.

**Comment by Rapiz1** [comment]
Looks like there has already been a discussion: https://github.com/Genymobile/scrcpy/issues/279

**Comment by Rapiz1** [comment]
Sorry, looks like we are not talking about the same thing. I will open another issue
