### ISSUE TITLE
Will it leave “scrcpy-server.jar” on the phone?

### ISSUE THREAD

**Issue by yuyuen72** [Genymobile/scrcpy#647]
It looks like it pushes “scrcpy-server.jar” to the phone every time it connects, so if I use it frequently, will there be a lot of “scrcpy-server.jar” in my phone?

**Comment by rom1v** [comment]
It always pushes it to the same location, and it removes it immediately:

https://blog.rom1v.com/2018/03/introducing-scrcpy/#clean-up-the-device
