### ISSUE TITLE
Using mouse to handle my phone

### ISSUE THREAD

**Issue by mafsan786git** [Genymobile/scrcpy#652]
I'm getting some problem, in ubuntu my mouse is not working when I'm clicking on phone screen.
Thank you

**Comment by rom1v** [comment]
Which device?

Also see [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-clicks-do-not-work).

**Comment by mafsan786git** [comment]
Redmi note 4 android

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/issues/70#issuecomment-373286323
