### ISSUE TITLE
Crash with Genymobile/gnirehtet

### ISSUE THREAD

**Issue by mrvearn** [Genymobile/scrcpy#654]
Just to let you know, v1.9 crash / FC after run gnirehtet (reverse tethering). If I run gnirehtet 1st, then run scrcpy after that, gnirehtet will crash. I will continue to use 1.8 until new update release as it has no issue so far.
You may check gnirehtet page here if you interested : https://github.com/Genymobile/gnirehtet

**Comment by rom1v** [comment]
I guess you just don't use the same adb version for gnirehtet and scrcpy. Use 1.0.41 for both.

**Comment by mrvearn** [comment]
Thank You!! problem solved!
