### ISSUE TITLE
Problem with Turkish characters

### ISSUE THREAD

**Issue by kofte** [Genymobile/scrcpy#656]
When I try to type ş Ş, ğ Ğ, lowercase ı I, and uppercase i İ, software does not recognise those and gives an error in terminal like "[server] WARN: Could not inject char u+0131"
Also, pressing "ı" does give the error but pressing Shift + "ı" does not. But pressing Shift + i gives "[server] WARN: Could not inject char u+0130" but then writes uppercase "ı I" (uppercse "i" in other languages)

**Comment by kofte** [comment]
![example](https://user-images.githubusercontent.com/906680/61585883-1a73e300-ab70-11e9-9886-696b0a1800d6.gif)

**Comment by npes87184** [comment]
There are some problem about char injection. See #431.

Please use `ctrl` + `shift` + `v` to paste char from PC's clipboard into device's as workaround now.

**Comment by rom1v** [comment]
Text injection on Android only supports ASCII.

https://blog.rom1v.com/2018/03/introducing-scrcpy/#inject-text

**Comment by czarls** [comment]
There is also an issue with polish characters, only few of them are supported.
Missing are:
`u+0119
u+0105
u+0142
`

**Comment by rom1v** [comment]
Closing as duplicate of #37.

**Comment by rom1v** [comment]
Please test #1426 (works on Android >= 7).
