### ISSUE TITLE
my phone is in read-only mode

### ISSUE THREAD

**Issue by jonathanparsy** [Genymobile/scrcpy#658]
Hi,
I've installed scrcpy, it looks great.
it shows my phone, but i can't do nothing from the PC
(i'm using a Ubuntu 19.04 and a Xiaomi Redmi 7)
thx for your help

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-clicks-do-not-work
https://github.com/Genymobile/scrcpy/issues/70#issuecomment-373286323

**Comment by jonathanparsy** [comment]
Thx it works fine now
