### ISSUE TITLE
Option to set default file transfer path

### ISSUE THREAD

**Issue by shmaltz** [Genymobile/scrcpy#659]
Is there an option to set a default file transfer path for files transferred to the device?

I am trying to send over pictures, but when I try to use them in messaging apps, they don't show up. I have to manually go to the phones root and open and share it from there.

Any idea how to fix this?

Thanks!

**Comment by rom1v** [comment]
Implemented by a90ccbdf3b37694aac8c34cd6d0837d511c81843.

    scrcpy --push-target=/sdcard/some/directory/

**Comment by shmaltz** [comment]
Thank you!

I noticed that when pushing images to the device, that messaging apps, etc, don't recognize the image right away, seemingly because the media gallery hasn't been updated. Is there a way to automatically refresh the phones media gallery so the photo is usable in these apps right away?

**Comment by rom1v** [comment]
A long time ago, it was possible with:

```
adb shell am broadcast -a android.intent.action.MEDIA_MOUNTED -d file:///mnt/sdcard
```

I think it does not work anymore (not tested).

**Comment by shmaltz** [comment]
Thank you!

**Comment by rom1v** [comment]
Maybe:

    adb shell am broadcast -a android.intent.action.MEDIA_SCANNER_SCAN_FILE -d file://

https://github.com/aosp-mirror/platform_frameworks_base/blob/839c6cffaa936627a6fb1939cb283c6dabfd5346/cmds/screencap/screencap.cpp#L103

**Comment by shmaltz** [comment]
Will this code cause it to constantly scan automatically, or will I have to run this command every time I upload a file?

**Comment by rom1v** [comment]
I guess every time. I did not test.
