### ISSUE TITLE
memleak

### ISSUE THREAD

**Issue by aezaekill** [Genymobile/scrcpy#66]
Hi.
It seems like memory usage is constantly increasing. After using scrcpy for serveral minutes (8 Minutes to be exact) it uses 1.6 GB of RAM. After 9 Minutes it already uses 1.8 GB of RAM.

I am running it on Windows 10 if this makes any difference.

Regards.

**Comment by rom1v** [comment]
Thank you for your report.

Duplicate of https://github.com/Genymobile/scrcpy/issues/26. It is fixed on `master`, and will be available in the next release.
