### ISSUE TITLE
[Linux] adb: error: cannot stat '/usr/local/bin/scrcpy-server.jar': No such file or directory

### ISSUE THREAD

**Issue by leinardi** [Genymobile/scrcpy#660]
I built and installed scrcpy (git tag v1.9) on Fedora 30 following the instructions from the readme but, when I tried to start it, I got this error:

```
$ scrcpy 
adb: error: cannot stat '/usr/local/bin/scrcpy-server.jar': No such file or directory
ERROR: "adb push" returned with value 1
```
Looks like that ninja is installing `scrcpy-server.jar` in `/usr/local/share/scrcpy/scrcpy-server.jar` but `scrcpy` is looking for it in `/usr/local/bin/scrcpy-server.jar`.

Symlinking it didn't work:
```
$ scrcpy 
adb: error: cannot stat '/usr/local/bin/scrcpy-server.jar': Too many levels of symbolic links
ERROR: "adb push" returned with value 1
```

A workaround is to provide a copy of the sever on that path:
```
$ sudo cp /usr/local/share/scrcpy/scrcpy-server.jar /usr/local/bin/scrcpy-server.jar
```

**Comment by rom1v** [comment]
You need few commits after v1.9. Just `git pull`.

See #583

**Comment by leinardi** [comment]
Yep, can confirm that current master is working :+1:

**Comment by marineramanjay** [comment]
scrcpy 
INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
adb: error: cannot stat '/usr/local/share/scrcpy/scrcpy-server.jar': No such file or directory
ERROR: "adb push" returned with value 1
os - deepin linux distro

**Comment by rom1v** [comment]
How did you install it?

It seems the file is not there:

    ls -l /usr/local/share/scrcpy/

**Comment by marineramanjay** [comment]
i installed it using sudo snap install scrcpy 
then core 18 error was coming so i installed core by sudo snap install core 
then again downloaded scrcpy it got installed 
now when i am running scrcpy
INFO: scrcpy 1.10 https://github.com/Genymobile/scrcpy
adb: error: cannot stat '/usr/local/share/scrcpy/scrcpy-server.jar': No such file or directory
ERROR: "adb push" returned with value 1
this error is coming

**Comment by marineramanjay** [comment]
scrcpy 
INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
* daemon not running; starting now at tcp:5037
ADB server didn't ACK
Full server startup log: /tmp/adb.1000.log
Server had pid: 6705
--- adb starting (pid 6705) ---
adb I 11-10 02:59:49  6705  6705 main.cpp:57] Android Debug Bridge version 1.0.39
adb I 11-10 02:59:49  6705  6705 main.cpp:57] Version 1:8.1.0+r23-5~18.04
adb I 11-10 02:59:49  6705  6705 main.cpp:57] Installed as /snap/scrcpy/174/usr/lib/android-sdk/platform-tools/adb
adb I 11-10 02:59:49  6705  6705 main.cpp:57] 
error: could not install *smartsocket* listener: Permission denied

* failed to start daemon
adb: error: failed to get feature set: cannot connect to daemon
ERROR: "adb push"

**Comment by rom1v** [comment]
>     error: could not install smartsocket listener: Permission denied

https://github.com/Genymobile/scrcpy/issues/667

**Comment by marineramanjay** [comment]
adb: error: cannot stat '/usr/local/share/scrcpy/scrcpy-server.jar': No such file or directory
not able to fix this  
please help deepin os

**Comment by marineramanjay** [comment]
~/scrcpy$ ninja -Cx
ninja: Entering directory `x'
[1/1] Generating scrcpy-server with a custom command.
FAILED: server/scrcpy-server.jar 
/home/amanjay/scrcpy/server/./scripts/build-wrapper.sh /home/amanjay/scrcpy/server server/scrcpy-server.jar release

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':server'.
> The SDK directory '/home/amanjay/android/sdk' does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 805ms
ninja: build stopped: subcommand failed.

**Comment by rom1v** [comment]
>     The SDK directory '/home/amanjay/android/sdk' does not exist.

The problem is explicit.

**Comment by rom1v** [comment]
@marineramanjay If you just want to build the client, you can use the [prebuilt server](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#prebuilt-server) instead (so that you don't have to build the Android part).

**Comment by marineramanjay** [comment]
# i have downloaded this jar many times step by step but at this point i am not able to find the error

meson x --buildtype release --strip -Db_lto=true \
>     -Dprebuilt_server=/path/to/scrcpy-server.jar
Error during basic setup:

Neither directory contains a build file meson.build.

**Comment by rom1v** [comment]
>     Neither directory contains a build file meson.build.

You must execute this command from the directory where you `git clone` the repository.

**Comment by marineramanjay** [comment]
amanjay@MarinerPC:~$ git clone https://github.com/Genymobile/scrcpy
fatal: destination path 'scrcpy' already exists and is not an empty directory.
amanjay@MarinerPC:~$ cd scrcpy
amanjay@MarinerPC:~/scrcpy$ meson x --buildtype release --strip -Db_lto=true
Directory already configured, exiting Meson. Just run your build command
(e.g. ninja) and Meson will regenerate as necessary. If ninja fails, run ninja
reconfigure to force Meson to regenerate.

If build failures persist, manually wipe your build directory to clear any
stored system data.

To change option values, run meson configure instead.
amanjay@MarinerPC:~/scrcpy$ ninja -Cx
ninja: Entering directory `x'
[1/1] Generating scrcpy-server with a custom command.
FAILED: server/scrcpy-server.jar 
/home/amanjay/scrcpy/server/./scripts/build-wrapper.sh /home/amanjay/scrcpy/server server/scrcpy-server.jar release

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':server'.
> The SDK directory '/home/amanjay/android/sdk' does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 860ms
ninja: build stopped: subcommand failed.
amanjay@MarinerPC:~/scrcpy$ ^C
amanjay@MarinerPC:~/scrcpy$

**Comment by marineramanjay** [comment]
Thanks a lot @rom1v  for all ur help finally got my mistake corrected .
