### ISSUE TITLE
GBoard switches language when typing "I (space)"

### ISSUE THREAD

**Issue by twiitar** [Genymobile/scrcpy#661]
Hello,

When typing on my physical Computer keyboard while connected via scrcpy it often happens that GBoard switches the keyboard language from English to Japanese, the next keyboard language in line. This usually occurs when typing "I (space)" within a sentence.

Typing at a slower speed to avoid the issue does avoid it, typing at a normal (faster) speed usually triggers it.

**Comment by rom1v** [comment]
In AnySoft Keyboard, there is a setting (enabled by default) so that Shift+space from a physical keyboard switches the language. Maybe there is a similar option in your keyboard settings?

**Comment by rom1v** [comment]
Does it switch keyboard on Shift+space (without typing `I`)?

**Comment by twiitar** [comment]
Hello, yes, you're absolutely correct. As I've never connected a Bluetooth
keyboard to my phone the issue never came up. I'll figure out how to
disable it if it's possible.

Thank you very much and sorry for bothering you with this useless report.

Romain Vimont <notifications@github.com> schrieb am Di., 23. Juli 2019,
10:18:

**Comment by rom1v** [comment]
No problem, it may be useful for the next person having the same problem. :wink:
