### ISSUE TITLE
Record screen with stable frame rate?

### ISSUE THREAD

**Issue by williamfzc** [Genymobile/scrcpy#664]
really nice project, save my time! :)

I am trying to use it to record screen and calculate some time cost, such as start-up time of applications. But the frame rate is not stable (changing between 15-20).

Is it possible to make it stable? eg: locking it to 15? 

> "Skipped frames" are recorded, even if they are not displayed in real time (for performance reasons).

BTW, I do not unstand what it means. Does it mean that the "skipped frames" also will be writed in video?

Thanks for your project!

**Comment by rom1v** [comment]
> the frame rate is not stable (changing between 15-20).

Yes, it generates a new frame whenever the screen content changes. When it does not change, you get 0 fps, when you play a video, it changes at the rate of the video...

> Is it possible to make it stable? eg: locking it to 15?

No, this is how MediaCodec works when encoding a surface.

Each frame has a timestamp stored in the recorded file (used by the video players to display them at the correct time), so you can get a very precise timing (there are probably tools to get them easily, but I don't know).

> Does it mean that the "skipped frames" also will be writed in video?

Yes. Unless `--render-expired-frames` is enabled, a frame may be skipped if a more recent one has already been received and decoded. But this only affects rendering in the scrcpy window.

**Comment by williamfzc** [comment]
Thanks for your reply, and I have found a way to get them easily. ffmpeg can change FPS of videos, and I try:

this is a video recording by camera:

<img width="766" alt="image" src="https://user-images.githubusercontent.com/13421694/64060064-44ea9e80-cbfa-11e9-82cb-b9f59dff66f0.png">

this is a video recording by scrcpy:

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/13421694/64060078-80856880-cbfa-11e9-9bec-7242bf678653.png">

as you can see, 

- real_cost = 3.93333 - 1.83333 = 2.1
- scrcpy_cost = 4.288 - 1.822 = 2.466
- error = 2.466 - 2.1 = 0.366

but if you use ffmpeg to encode this video recording by scrcpy:

```bash
ffmpeg -i "test.mp4" -c:v libx264 -preset ultrafast -crf 15 -r 30 -threads 8 -c:a copy "test_new.mp4"
```

you will get:

<img width="715" alt="image" src="https://user-images.githubusercontent.com/13421694/64060141-5da78400-cbfb-11e9-956f-d1d2970899e8.png">

- ffmpeg+scrcpy_cost = 5.4 - 3.3 = 2.1
- error = 2.1 - 2.1 = 0

precise enough I think. In this way, I can easily calculate launch time (or something else) without camera!

these reports were built with [stagesepx](https://github.com/williamfzc/stagesepx), which based on opencv.

this may help someone else.

**Comment by williamfzc** [comment]
hi :) I have another small question:

> Every frames in these videos recorded by scrcpy are [I frame type](https://github.com/leandromoreira/digital_video_introduction#frame-types).

Is that correct?
Thanks!

**Comment by rom1v** [comment]
No, that is not correct. There can be as much as 10 seconds between two I-frames.

**Comment by ShiverZm** [comment]
i have a question?every time i receive  the data of screen,it is  also a frame ? i do not need to calculate an frame length? one time one frame ?right?

**Comment by rom1v** [comment]
Everytime [`dequeueOutputBuffer()`](https://developer.android.com/reference/android/media/MediaCodec.html#dequeueOutputBuffer(android.media.MediaCodec.BufferInfo,%20long)) returns a value >= 0, you get a packet, which in H.264 in practice is exactly one frame.

It also gives the PTS (Presentation TimeStamp) and the packet length:
https://github.com/Genymobile/scrcpy/blob/8ec077ce1b5ae3c8a5993e062668220e7c684c30/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java#L118-L135

**Comment by ShiverZm** [comment]
but i saw the buffers pc received every time,the buffers contain 00 00 00 01 (frame header) more then one

**Comment by ShiverZm** [comment]
i was wrong

**Comment by ShiverZm** [comment]
emmm,i use our company lib to parse the graphic buffer pc receive, but the picture is not clear,
how can i get some message of graphic like frame length from the buffer,because the mate tell me our lib need the frame size. 
by the way,in decoder.c,"read_packet_with_meta" how to use this?
