### ISSUE TITLE
Error: could not install *smartsocket* listener: Permission denied

### ISSUE THREAD

**Issue by rodrigocichetto** [Genymobile/scrcpy#667]
Trying to run my Galaxy S9 on Ubuntu gives the following error:
```
* daemon not running; starting now at tcp:5037
ADB server didn't ACK
Full server startup log: /tmp/adb.1000.log
Server had pid: 20075
--- adb starting (pid 20075) ---
adb I 07-26 16:16:06 20075 20075 main.cpp:57] Android Debug Bridge version 1.0.39
adb I 07-26 16:16:06 20075 20075 main.cpp:57] Version 1:8.1.0+r23-5~18.04
adb I 07-26 16:16:06 20075 20075 main.cpp:57] Installed as /snap/scrcpy/136/usr/lib/android-sdk/platform-tools/adb
adb I 07-26 16:16:06 20075 20075 main.cpp:57] 
error: could not install *smartsocket* listener: Permission denied

* failed to start daemon
adb: error: failed to get feature set: cannot connect to daemon
ERROR: "adb push" returned with value 1
```
I have enabled usb debugging on my device.

**Comment by rom1v** [comment]
What is the result of

    adb devices

?

**Comment by rodrigocichetto** [comment]
```
List of devices attached
29e3b8dcca3f7ece	device
```

**Comment by rom1v** [comment]
cc @sisco311

**Comment by rodrigocichetto** [comment]
I followed the [build the app manually](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md) and it worked! :smile: 

I also had to install Android API 29 by Android Studio.

Thanks!

**Comment by sisco311** [comment]
@rodrigocichetto I'm glad you managed to get it work. But it would be cool to find out why the snap did not work for you.

The error usually occurs when the snap is not connected to the network and/or network-bind slots of the core snap. This should happen automatically at installation time.

You can check the interface connections with:
`snap connections scrcpy`

If for some reason the snap is not connected to the above mentioned slots, you can connect it manually:
`sudo snap connect scrcpy:network :network`
`sudo snap connect scrcpy:network-bind :network-bind`

Of course the core snap must be installed on your system before you make the connections:
`sudo snap install core`
