### ISSUE TITLE
Frame Skipped drastically

### ISSUE THREAD

**Issue by shinnatan** [Genymobile/scrcpy#670]
Hi, First of all your app is super awesome! Thanks for making this cool app.

I got this kind of issue where it skipped alot of frames. But the game itself has a 55-60 fps.

btw I have like 0 knowledge about coding stuffs, if you're answering this about encoding pls explain in the most simple way.  ( T _ T )

Thanks

![3333](https://user-images.githubusercontent.com/53430461/62042008-368a1b00-b227-11e9-934c-9f5aa3df582e.jpg)

**Comment by rom1v** [comment]
Maybe your computer is not fast enough to render a frame before the next one is decoded.

Is there any noticeable lag if you disable skipping frames:

    scrcpy --render-expired-frames

?

**Comment by shinnatan** [comment]
![ddd](https://user-images.githubusercontent.com/53430461/62042899-5d495100-b229-11e9-90cb-ade72e3ad985.jpg)

Here are some more info about my computer

**Comment by shinnatan** [comment]
I don't know but does it have anything to do with Windows10 setting stuffs? 
btw I connect my phone with USB

**Comment by shinnatan** [comment]
![adda](https://user-images.githubusercontent.com/53430461/62043869-b6b27f80-b22b-11e9-93d7-c12705827bda.jpg)
not only ingame but even home screen it got the additional frame skipped

pls help :(

**Comment by rom1v** [comment]
Please try what I suggested https://github.com/Genymobile/scrcpy/issues/670#issuecomment-515942125

**Comment by shinnatan** [comment]
Thank you, 

Sorry this might be a stupid question but how do I fix it with  "scrcpy --render-expired-frames"

any link instruction on how to use it? sorry about this, I have like 0 knowledge about coding

**Comment by rom1v** [comment]
1. Open a terminal (`cmd`)
2. Go to your scrcpy directory: `cd C:\foo\scrcpy`
3. Run `scrcpy --render-expired-frames`

**Comment by DarkKnight0715** [comment]
Hi. 
I just wanted to say that the latest version of SCRCPY is still skipping frames. 
Can u pls help?

**Comment by rom1v** [comment]
> I just wanted to say that the latest version of SCRCPY is still skipping frames.

That's expected, if a frame is not rendered before a new one is available, it is skipped (and printed as skipped in the console if you enable framerate logging).

**Comment by skaterkate** [comment]
Just wanna share if it could be any help for others who are trying to sort out or lessen this frame skipping issue on low end systems:

I'm running on **Vega 8 OpenGL** from a **Ryzen 3 3200g** using a **Poco F1** phone and I was experiencing moderate frame skips specially when mirroring Battle Royale mode from _Call of Duty: Mobile_. The argument **--encoder 'c2.android.avc.encoder'** helped a lot to reduce frame skips to almost nothing. It was quite handy considering that --render-expired-frames argument was deprecated from the previous version. I'm using the latest one at the time of writing this. I hope you can try other encoders too at your disposal.
