### ISSUE TITLE
view half

### ISSUE THREAD

**Issue by duwurensheng010** [Genymobile/scrcpy#671]
Rotate screen to vertical screen，The view has half。 My device use 3399.

**Comment by rom1v** [comment]
I don't understand. A screenshot might help?

**Comment by duwurensheng010** [comment]
![image](https://user-images.githubusercontent.com/7730269/62110512-233b8600-b2e1-11e9-98dc-5d0fe25f96e0.png)

**Comment by duwurensheng010** [comment]
My device is in portrait display

**Comment by rom1v** [comment]
Ok, your device probably does not notify rotation changes correctly (i.e. `onRotationChanged()` is not called):

https://github.com/Genymobile/scrcpy/blob/02692ffa42c66c1c3dc93752c2fe2bec74e0240b/server/src/main/java/com/genymobile/scrcpy/Device.java#L29-L41

Could you confirm (by adding a log or something), if you know how to?

**Comment by rom1v** [comment]
Does it occurs only when you start in landscape then rotate, or also when you start in portrait mode?

**Comment by duwurensheng010** [comment]
Horizontal screen is ok,   Vertical screen shows the problem。Not happening at the moment of switching。

**Comment by rom1v** [comment]
Can you record a video with `screenrecord`:

    adb shell screenrecord /sdcard/file.mp4
    adb pull /sdcard/file.mp4

Is the video ok?

What are the results of:

    adb shell wm size
    adb shell dumpsys window

(both in portrait and landscape mode)?

**Comment by duwurensheng010** [comment]
video also has the problem,  this is portrait info

[info.pdf](https://github.com/Genymobile/scrcpy/files/3445881/info.pdf)

**Comment by duwurensheng010** [comment]
The problem only appears when the portrait screen is displayed.

**Comment by rom1v** [comment]
> video also has the problem

OK, so if even `screenrecord` has the problem, there is a bug in your Android ROM (probably not reporting correctly physical and logical width and height).

**Comment by gw86** [comment]
Same issue here on dedicated device without any chances for fixing ROM. Is there any chance to work around it somehow?

**Comment by LU616FER** [comment]
Sorry for my bad English (it's not my native language, I'm using google translator), but I discovered the problem, in the "developer options" tab, scroll until you find "minimum width" probably the minimum width of the smartphone is smaller than the one that runs on the scrcpy, I had the same problem, I set the maximum size to 800p and the width was 376p, and the "minimum width" in the developers option was 400 and something (I don't remember) and just put the minimum pixel width in same minimum pixel width configured in scrcpy
