### ISSUE TITLE
Can I change dir to save record file?

### ISSUE THREAD

**Issue by GBwuka** [Genymobile/scrcpy#672]
when I start scrcpy to save screen record using scrcpy -Nr /data/test.mp4, it will occure error, error info :
ERROR: Failed to open output file: /data/test.mp4
ERROR: Could not open recorder

env: centos
if I want to save the screen record file in other dir, How could I do?

Thank You!

**Comment by rom1v** [comment]
The target location is on your computer. There is no `/data` on your computer.

**Comment by GBwuka** [comment]
> The target location is on your computer. There is no `/data` on your computer.

/data dir on my computer
![image](https://user-images.githubusercontent.com/1592742/62111156-90035000-b2e2-11e9-97ef-750fae7e186f.png)

**Comment by rom1v** [comment]
Oh! You probably don't have the permission, then.

```bash
echo test > /data/aaa.mp4
ls -ld /data
```

**Comment by GBwuka** [comment]
when i use dir i has permission, but still error 
![image](https://user-images.githubusercontent.com/1592742/62111552-6139a980-b2e3-11e9-9228-a676e79409d5.png)

if it related to the snap package.
when i use home directory. it work.

**Comment by rom1v** [comment]
Ah ok, it's the snap package, which only authorize the home directory. See #564.

**Comment by GBwuka** [comment]
if i want to authorize other dir , is there any solution?

**Comment by rom1v** [comment]
Without snap, everything is authorized.

With snap, cc @sisco311.

**Comment by sisco311** [comment]
The only workarounds I can think of right now is to mount the partition in your home directly or bind mount the directory in your home dir.

**Comment by GBwuka** [comment]
ok  i will try . thank you very much!
