### ISSUE TITLE
ERROR: Could not listen on port 27183

### ISSUE THREAD

**Issue by ramiua** [Genymobile/scrcpy#674]
```
$ lsb_release -a
LSB Version:	core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04

$ java -version
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
$ adb --version
Android Debug Bridge version 1.0.39
Version 1:8.1.0+r23-5~18.04
Installed as /usr/lib/android-sdk/platform-tools/adb
$ adb devices 
List of devices attached
FAAxxxxxxx	device

$ scrcpy -v
scrcpy 1.9

dependencies:
 - SDL 2.0.8
 - libavcodec 57.107.100
 - libavformat 57.83.100
 - libavutil 55.78.100
$ scrcpy 
/usr/local/share/scrcpy/scrcpy-server.jar... pushed. 4.6 MB/s (22470 bytes in 0.005s)
listen: Operation not permitted
ERROR: Could not listen on port 27183
```

**Comment by rom1v** [comment]
Your port 27183 is already used.

You can find which process is listening on this port:
```
ss -lnt
```

You can use another one:

```
scrcpy -p 1234
```

**Comment by ramiua** [comment]
$ ss -lnt | grep  27183
$ scrcpy -p 1234
/usr/local/share/scrcpy/scrcpy-server.jar... pushed. 3.9 MB/s (22470 bytes in 0.005s)
listen: Operation not permitted
ERROR: Could not listen on port 1234
$

**Comment by rom1v** [comment]
You don't have permission to listen :confused:

Does this fail with an error:
```
netcat -l -p 1234
```
?

**Comment by ramiua** [comment]
$ netcat -l -p 1234
^C
$ 
# no errors

**Comment by rom1v** [comment]
What exact version (the hash from which you compiled)?

Is there anything on your computer which could deny listening on port to _scrcpy_?

**Comment by ramiua** [comment]
$ bash --version
GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

#### other program who open a listening port can work correctly

**Comment by franky79** [comment]
I'm having exactly the same issue with Debian Buster. I installed the snap package if that helps.

**Comment by sisco311** [comment]
@franky79 
Try to kill all running instances of adb:
`scrcpy.adb kill-server`

If the error persists check your logs for audit entries (as root):
`grep audit /var/log/kern.log`
or
`grep audit /var/log/syslog`
or if you are using systemd
`journalctl -k | grep audit`

**Comment by franky79** [comment]
@sisco311 There are no audit entries. Although I couldn't start the server anymore:

`/snap/bin/scrcpy.adb start-server
* daemon not running; starting now at tcp:5037
ADB server didn't ACK
Full server startup log: /tmp/adb.1000.log
Server had pid: 24111
--- adb starting (pid 24111) ---
adb I 08-08 08:55:57 24111 24111 main.cpp:57] Android Debug Bridge version 1.0.39
adb I 08-08 08:55:57 24111 24111 main.cpp:57] Version 1:8.1.0+r23-5~18.04
adb I 08-08 08:55:57 24111 24111 main.cpp:57] Installed as /snap/scrcpy/145/usr/lib/android-sdk/platform-tools/adb
adb I 08-08 08:55:57 24111 24111 main.cpp:57] 
error: could not install *smartsocket* listener: Operation not permitted

* failed to start daemon
error: cannot connect to daemon`

Btw. /tmp/adb.1000.log does not exist. adb from debian is working. To me it looks like there is some adb mismatch between snap and system.

**Comment by ramiua** [comment]
$ adb kill-server 
$ scrcpy
INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
* daemon not running; starting now at tcp:5037
ADB server didn't ACK
Full server startup log: /tmp/adb.1000.log
Server had pid: 3929
--- adb starting (pid 3929) ---
adb I 08-09 20:03:54  3929  3929 main.cpp:57] Android Debug Bridge version 1.0.39
adb I 08-09 20:03:54  3929  3929 main.cpp:57] Version 1:8.1.0+r23-5~18.04
adb I 08-09 20:03:54  3929  3929 main.cpp:57] Installed as /snap/scrcpy/145/usr/lib/android-sdk/platform-tools/adb
adb I 08-09 20:03:54  3929  3929 main.cpp:57] 
error: could not install *smartsocket* listener: Operation not permitted

* failed to start daemon
adb: error: failed to get feature set: cannot connect to daemon
ERROR: "adb push" returned with value 1
$

**Comment by sisco311** [comment]
What's the output of:
`snap connections scrcpy`

**Comment by ramiua** [comment]
$ snap connections scrcpy
Interface       Plug                   Slot  Notes
adb-support     scrcpy:adb-support     -     -
desktop         scrcpy:desktop         -     -
desktop-legacy  scrcpy:desktop-legacy  -     -
home            scrcpy:home            -     -
network         scrcpy:network         -     -
network-bind    scrcpy:network-bind    -     -
opengl          scrcpy:opengl          -     -
unity7          scrcpy:unity7          -     -
wayland         scrcpy:wayland         -     -
x11             scrcpy:x11             -     -

**Comment by s1291** [comment]
Try to kill the process first:

```
kill -9 $(sudo netstat -ap | grep :27183 | awk '{print $7}' | grep -Eo '[0-9]+')
```

**Comment by SenthilVikram** [comment]
> 

worked, thanks a lot
