### ISSUE TITLE
[BUG] 'PASTE' not working correctly

### ISSUE THREAD

**Issue by pundoo** [Genymobile/scrcpy#675]
Sometimes when copying from PC and pasting on the phone, it pastes wrong character than the actual one. For instance, copy a long URL and paste on the phone, you'll notice some of the letters mismatch.

**Comment by rom1v** [comment]
Please provide an example URL and the pasted text.

Do you past with Ctrl+v (which injects character by character) or Ctrl+Shift+v (to synchronize clipboard and paste manually on the phone?

**Comment by pundoo** [comment]
I paste with `Ctrl+V`

Example URL :
**Original** - https://u8559303.ct.sendgrid.net/wf/click?upn=ZURb9TyHfBzynM7GcDTky4VjkeLtSAddaNZnFoAZD38H4bOlGsNEabCIvPv1f-2B7qwQ-2Ft2U8wNV3ZH9XuPItKaSlvLi-2BdrJjYF66bv6jwG1sP-2BbLeK5RI2q86j34ki-2Fi-2FAn-2B6M-2FKmky9r5UmHzNKXZQ-3D-3D_k30L1g9os2oVvimdrkEeHEvEKWgQQoA1EloMRyKH4l4w1kVSERgAFuNJAQSxSyOeQ1HN-2Fw5MoTXzTthuVf0obiKX2rK1ZStn1Fon31HpWzY2iQXkSbLMW1mzVWLLVjpPplM1nkBujL4GxQ7ALV1nNl4HFABxIXF4s0s1YOYM7jtwsFZUgIYQ2c7Kx4UHUCk8f7ipKBaeeqh3Iw01RslOgA-3D-3D
**Pasted** -  https://u8559303.ct.sendgrid.net/wf/click?up=ZURb9TyHfBzynM7GcDTky4VjkeLtSAddaNZnFoAZD38H4bOlGsNEabCIvPv1f-2B7qwQ-2Ft2U8wNV3ZH9XuPItKaSlvLi-2BdrJjYF66bv6jwG1sP-2BbLeK5RI2q86j34ki-2Fi-2FAn-2B6M-2FKmky9r5UmHzNKXZQ-3D-3D_k30L1g9os2oVvimdrkEeHEvEKWgQQoA1EloMRyKH4l4w1kVSERgAFuNJAQSxSyOeQ1HN-2Fw5MoTXzTth

Here, it doesn't even paste the complete text, and 'upn=' was pasted as 'up='. Usually this happens at random occasions. Sometimes happens even when you type on the keyboard. If you type for example 'u' on the (physical pc) keyboard, it'll print 'i' on the phone (not always, but randomly), same with other characters.

**Comment by rom1v** [comment]
> Here, it doesn't even paste the complete text

Text injection by copy-paste is limited to 300 chars (it takes time to inject chars separately, so we need some limit):
https://github.com/Genymobile/scrcpy/blob/6b3d9e3eab1d9ba4250300eccd04528dbee9023a/app/src/control_msg.h#L12

> 'upn=' was pasted as 'up='. Usually this happens at random occasions. Sometimes happens even when you type on the keyboard.

Which Android keyboard do you use? I cannot reproduce.

https://github.com/Genymobile/scrcpy/blob/6b3d9e3eab1d9ba4250300eccd04528dbee9023a/server/src/main/java/com/genymobile/scrcpy/Controller.java#L194

What if you replace `INJECT_INPUT_EVENT_MODE_ASYNC` by `INJECT_INPUT_EVENT_MODE_WAIT_FOR_RESULT` or `INJECT_INPUT_EVENT_MODE_WAIT_FOR_FINISH`?

https://github.com/Genymobile/scrcpy/blob/master/server/src/main/java/com/genymobile/scrcpy/wrappers/InputManager.java#L11-L13

(It will take more time to inject chars though.)

**Comment by pundoo** [comment]
First off, I don't wanna undergo the hassle of rebuilding it, so not sure if changing event will do any better.
As for the keyboard, I use Gboard. However, by typing on keyboard I meant physical (PC) keyboard, not virtual. Also, it happens randomly so, its kinda expected not to always replicate it.

**Comment by rom1v** [comment]
> First off, I don't wanna undergo the hassle of rebuilding it, so not sure if changing event will do any better.

Here is server v1.9 with `INJECT_INPUT_EVENT_MODE_WAIT_FOR_FINISH`: [`scrcpy-server.jar`](https://tmp.rom1v.com/scrcpy/issue675/1/scrcpy-server.jar)
_SHA256: e1b46dbe37d1d52c689a8a04bc049b7e32539d614c17cc3da831a985cd96dce1_

Just replace it in your scrcpy folder.

> However, by typing on keyboard I meant physical (PC) keyboard, not virtual.

Yes, but text injection is still impacted by the Android keyboard.

> Also, it happens randomly so, its kinda expected not to always replicate it.

I tried several times, the URL is always correct (just truncated at 300 chars).

**Comment by pundoo** [comment]
Nope. No Luck. Still 'upn=' gets pasted as 'up='.
BTW, just tried pasting a paragraph of text, it even adds random new character to words that wasn't in the original text.

**Comment by pundoo** [comment]
> Yes, but text injection is still impacted by the Android keyboard.

Ah.. that's where the issue was. It appears that auto-correction of Gboard was the culprit.

Yet, not sure if the character alternation (when typing on keyboard) was due to this. I'll test extensively and let you know.
