### ISSUE TITLE
连接后显示手机分辨率黑屏无画面

### ISSUE THREAD

**Issue by Tu-maimes** [Genymobile/scrcpy#677]
魅族手机

**Comment by Tu-maimes** [comment]
1

**Comment by Tu-maimes** [comment]
1

**Comment by rom1v** [comment]
In English, please.

**Comment by npes87184** [comment]
Same as #240.

**Comment by Tu-maimes** [comment]
D:\scrcpy\scrcpy-win64\scrcpy-server.jar: 1 file pushed. 1.1 MB/s (22470 bytes in 0.020s)
INFO: Initial texture: 1080x1920

After running, only the above contents will be displayed。Without other Windows。the phone's screen lights up as it runs。Meizu phone

**Comment by rom1v** [comment]
Thank you for the translation :wink:

So I'm closing as duplicate of #240.
