### ISSUE TITLE
inclusion in f-droid?

### ISSUE THREAD

**Issue by ckhung** [Genymobile/scrcpy#68]
Hi! [f-droid](https://f-droid.org/) is kind of the mobile equivalent of debian. It would be nice to have scrcpy included in their repository. Would you have time to  [open an issue](https://gitlab.com/fdroid/rfp/issues) there? Or I can do it too, but obviously with much less technical inputs to them. Thanks!

**Comment by rom1v** [comment]
There is no APK to _install_ on the device, everything is controlled from the computer, so there is nothing to package in F-Droid.
