### ISSUE TITLE
How to remove title bar

### ISSUE THREAD

**Issue by cutoseo** [Genymobile/scrcpy#680]
How to remove the title bar, let me know which file to edit it, thank you
![Capture](https://user-images.githubusercontent.com/19404487/62337978-f2399c00-b500-11e9-8365-52beac6063dc.PNG)

**Comment by rom1v** [comment]
```diff
diff --git a/app/src/screen.c b/app/src/screen.c
index 18d24dd..34ba467 100644
--- a/app/src/screen.c
+++ b/app/src/screen.c
@@ -152,6 +152,8 @@ screen_init_rendering(struct screen *screen, const char *window_title,
 #endif
     }
 
+    window_flags |= SDL_WINDOW_BORDERLESS;
+
     screen->window = SDL_CreateWindow(window_title, SDL_WINDOWPOS_UNDEFINED,
                                       SDL_WINDOWPOS_UNDEFINED,
                                       window_size.width, window_size.height,
```

**Comment by cutoseo** [comment]
![Capture](https://user-images.githubusercontent.com/19404487/62363293-3fd9f700-b549-11e9-9dca-5f7e09f63aaa.PNG)
after removing the border it will look like in this image, still doing as you say, thank you
sorry for using google translate

**Comment by rom1v** [comment]
If you apply the patch I just provided, this is what you will get.

**Comment by cutoseo** [comment]
> If you apply the patch I just provided (just add the `SDL_WINDOW_BORDERLESS` flag), this is what you will get.

Thanks, I'll do it on Ubuntu
