### ISSUE TITLE
Mouse clicks do not work

### ISSUE THREAD

**Issue by behzadpooldar** [Genymobile/scrcpy#682]
Hello everybody, i have a problem with scrcpy , i did it succesfully and i can see the mobile screen on my windows BUT my mouse in windows doesnt work on the mirror mobile screen , what is the probelm ?

**Comment by rom1v** [comment]
Which device?

See https://github.com/Genymobile/scrcpy/issues/70#issuecomment-373286323.

**Comment by AlexMnrs** [comment]
Same here. I can see the mobile screen but mouse doesn't seem to do anything.

Xiaomi Mi 9.

Thank you!

**Comment by moluoyu** [comment]
thanks. my bro.i use xiaomi too.i didn't realize there is the second usb option.

**Comment by SkyPaladin** [comment]
Is that setting exclusive to the Xiaomi? Doesn't exist on my Moto G5 Plus.

**Comment by BIGDONUTS030** [comment]
I'm using Oppo and that option doesnt appear in the settings. It has only USB Debugging

**Comment by BIGDONUTS030** [comment]
> > I'm using Oppo and that option doesnt appear in the settings. It has only USB Debugging
> 
> Is there any error message in the console when you click?
This is what it said ( [server] WARN: Ignore touch event, it was generated for a different device size )

**Comment by rom1v** [comment]
Then see #2031.

**Comment by AYUSHMAAN-B** [comment]
Even with the second debugging option, it is not working on POCO M2 Pro. Can anybody help me with this? Thank you.

**Comment by rom1v** [comment]
Your device must be rebooted after this second option is enabled.

**Comment by AYUSHMAAN-B** [comment]
Thank you it worked.
