### ISSUE TITLE
SuperSu/KingoRoot

### ISSUE THREAD

**Issue by Bradyok** [Genymobile/scrcpy#686]
![image](https://user-images.githubusercontent.com/21972065/62413744-68f99680-b5e0-11e9-9c7f-3f4b6859ad17.png)

When I try to run SuperSu or KingoRoot on my device, the screen becomes unusable. Is there any way to allow this to enable root access on my device that does not have a screen?

**Comment by Bradyok** [comment]
Additional Information: when I press SuperSu or KingoRoot it says this:

INFO: Initial texture: 1920x1080
INFO: New texture: 1080x1920

So it seems it is inverting the resolution and breaking your program.

**Comment by rom1v** [comment]
> INFO: Initial texture: 1920x1080
> INFO: New texture: 1080x1920

This is just a device rotation.

Does it work with screenrecord:

    adb shell screenrecord /sdcard/file.mp4
    adb pull /sdcard/file.mp4

?

**Comment by Bradyok** [comment]
![image](https://user-images.githubusercontent.com/21972065/62413976-03a7a480-b5e4-11e9-95e7-364cd349a788.png)
Same issue

**Comment by rom1v** [comment]
OK, so if it does not work even with `screenrecord`, it won't work.
