### ISSUE TITLE
Android 9's MTP setting need constant setting & re-setting.

### ISSUE THREAD

**Issue by BardsDirge** [Genymobile/scrcpy#688]
Every time i plug my Galaxy-A50 into my mac [OS10.12] i can't get scrcpy working unless i switch the "default usb configuration" from "file transfer" to "charging", and then back over to  "file transfer". several times a day it will just disconnect and need this reassurance from me.

if i don't, i receive:

> /usr/local/Cellar/scrcpy/1.9/bin/scrcpy ; exit;
> adb: error: failed to get feature set: no devices/emulators found
> 2019-08-04 01:36:20.313 scrcpy[3423:5613800] ERROR: "adb push" returned with value 1
> logout
> Saving session...
> ...copying shared history...
> ...saving history...truncating history files...
> ...completed.
> 
> [Process completed]

i saw an app on youtube called "MTP Default" that looked promising but it vanished. 

anyone else have the same issue?
suggestions?

**Comment by Plandercozeron** [comment]
It's about Android 9, file transfer mode and ADB. Not scrcpy
Didn't help me if i set MTP as default mode in develop menu with Huawei devices
But works with Samsung J7, A6, A6+, A7

Also quick googling gave this:
https://forum.xda-developers.com/pixel-2-xl/how-to/set-mtp-default-usb-configuration-make-t3749880
