### ISSUE TITLE
[Feature request] Mouse Pointer visibility when recording

### ISSUE THREAD

**Issue by cypherinfo** [Genymobile/scrcpy#689]
Hello, congratulations for your great free app; it is one of the references in its kind. 
I'd like to see it a reference in the future too, that's why I invite you when recording, to make visible the mouse pointer too. 
That's would a great improvement for those making a video tutorial and maybe will make Scrcpy one of the few if not the only one to feature that possibility.
Thank you.
![Nokia1 pointer](https://user-images.githubusercontent.com/922409/62425996-d7714e00-b6df-11e9-956a-72679831a267.png)

**Comment by rom1v** [comment]
The video is hardware-encoded on the device side. For recording, the video stream is just muxed, on the client side. This avoids to reencode, which is better for both quality and performance.

Incrusting a mouse pointer would require to reencode the video.

Also, the device produces a new frame only when the screen content changes. A mouse pointer could change between frames (especially when the device screen content does not change), so this would imply to insert new frames.

**Comment by Erudition** [comment]
On the contrary, connecting a usb mouse to an android device (such as via OTG) makes a pointer show up that you can use just like any other - so you could have scrcpy send mouse movements to do the same.

**Comment by rom1v** [comment]
@Erudition Yes, using HID over AOA, the mouse is shown on the device (so it would probably be recorded). (But it would only work on Linux.)

Ref:
 - https://github.com/Genymobile/scrcpy/issues/87#issuecomment-378775565
 - https://github.com/Genymobile/scrcpy/issues/279#issuecomment-453819354

**Comment by Erudition** [comment]
Oh well that's perfect then!

**Comment by maddinmcfly** [comment]
Any chance, that i can have the cursor position visible on my android device all the time? Like, i can look at the device and control it with seeing my cursor? Thx

**Comment by rom1v** [comment]
@maddinmcfly No: https://github.com/Genymobile/scrcpy/issues/2088#issuecomment-773370723
