### ISSUE TITLE
Is it possible to record the video merging with the audio flowing by usbaudio (rom1v/usbaudio)  in Linux  

### ISSUE THREAD

**Issue by aleksmarcelo** [Genymobile/scrcpy#690]
Would be nice to have an extra option to also record the audio, something like --audioin / -ai <audio-input>, so the video captured could be nicely be recorded with the sound too.  

Thank you

**Comment by rom1v** [comment]
USBaudio is a hacky temporary solution. It was first implemented in a separate branch of scrcpy (#14), but it was not viable.

Instead, I think we should implement proper audio forwarding from Android Q: https://developer.android.com/preview/features/playback-capture

That way, we will receive audio packets, and we could encode/mux them along with the video stream.

**Comment by aleksmarcelo** [comment]
+1

Em dom, 4 de ago de 2019 13:28, Romain Vimont <notifications@github.com>
escreveu:
