### ISSUE TITLE
scrcpy-noconsole.exe shows a console

### ISSUE THREAD

**Issue by tordenflesk** [Genymobile/scrcpy#691]
scrcpy-noconsole.exe shows a console after upgrading to 1.10
![](https://i.imgur.com/YUrZtaR.png)

**Comment by jimnordb** [comment]
Can confirm. 

![image](https://user-images.githubusercontent.com/17293360/62519937-ceda5e00-b82c-11e9-86b5-e3bf12fd8acf.png)

**Comment by thorito** [comment]
Idem
![image](https://user-images.githubusercontent.com/594395/62603071-6905d900-b8f5-11e9-89fc-1acdb9a26214.png)

**Comment by rom1v** [comment]
Indeed.

Even if I rebuild v1.9 with my current mingw, the "no console" flag (`-mwindow`) does not work.

It's probably a bug in mingw.

**Comment by rom1v** [comment]
From IRC:

> mingw-w64 does require you to use WinMain for -mwindows to work

I'll test that later.

**Comment by dukemagus** [comment]
one more to confirme the bug

**Comment by sweenwolf** [comment]
Yeah I faced it too

**Comment by WrathX** [comment]
This is happening for me as well

**Comment by rom1v** [comment]
If someone wants to work on it, the solution is probably to use `WinMain()` instead of `main()` (https://github.com/Genymobile/scrcpy/issues/691#issuecomment-519308360) in a `#ifdef WINDOWS_NOCONSOLE` block.

**Comment by pundoo** [comment]
@rom1v Can you please provide the fixed build? I can test it. _(I'm not so familiar with C/C++, otherwise I'd do it myself)_

**Comment by KeronCyst** [comment]
Same; I thought I was going crazy with my shortcut adjustment!

**Comment by icantremember** [comment]
Me too, but at least it shows the bugdroid as the console icon :)

**Comment by rom1v** [comment]
I found a workaround: 18f2e33a8bf967a813142dbe9556813032ec9f0b

I backported it on v1.10 so that you can test:

[`scrcpy-noconsole`](https://tmp.rom1v.com/scrcpy/issue691/1/scrcpy-noconsole.exe) _SHA256: f7722aa6c5a56fb215cea02395376863de83cc51b16be9e6b784a7923fbc611f_

**Comment by fefo-dev** [comment]
Using it along with https://github.com/Genymobile/scrcpy/issues/650#issuecomment-550530774 and no issues so far, the console never pops.

**Comment by rom1v** [comment]
Fixed in v1.11.
