### ISSUE TITLE
Chrome and Webview renderers freeze when 'screen-off' is used

### ISSUE THREAD

**Issue by TotalChris** [Genymobile/scrcpy#696]

**Comment by TotalChris** [comment]
Android Q Beta 5, Pixel 2 XL, scrcpy 1.10

**Comment by metaa** [comment]
I can confirm on Android Q on a Pixel 2 XL with the newest version of scrcpy.
The page just displays as blank as long as the flag is used.

![image](https://user-images.githubusercontent.com/5056880/71317215-141ac780-247e-11ea-8b18-521c1cf186bf.png)

**Comment by srevinsaju** [comment]
see #836

**Comment by rom1v** [comment]
That's unfortunate, but there is probably nothing scrcpy can do :/
