### ISSUE TITLE
How to change settings using cmd.exe

### ISSUE THREAD

**Issue by procircuitscrub** [Genymobile/scrcpy#697]
I am trying to figure out how to change the settings to improve performance. I am currently getting a really blurry screen, almost like the bitrate is too high, and it is currently running at 1440p. I would rather run this at 1080p and possibly lower the bitrate in order to get higher fps. I am using this program in order to capture gameplay through OBS and stream it to Twitch. I can't seem to get the cmd prompt to navigate to the correct file path.

This is what I see 
![image](https://user-images.githubusercontent.com/29701861/62598935-df381a80-b8b8-11e9-8ca1-5a8e65f77bde.png)

I need to figure out how to drop this to 1080p and then lower the bitrate (or raise it, not sure which) in order to get rid of this blurry image any time there is motion on screen.

I have never navigated to a folder or opened a program using cmd, i'm sure i'm just doing it wrong. Thanks in advance. 

gif of what i'm talking about:
https://gyazo.com/0e6c4dd8205ae694713cbff4ec265dd0

**Comment by procircuitscrub** [comment]
Also, sorry in advance, I know you have attempted to answer this for others on here, but I wasn't able to get it working with how it was explained in other threads.

**Comment by procircuitscrub** [comment]
![image](https://user-images.githubusercontent.com/29701861/62599526-7487de80-b8ba-11e9-8e7a-e176b51a88ce.png)
This is my file path

**Comment by rom1v** [comment]
Hi,

To minimize the encoding artifacts, you need to increase bitrate per surface (so increase the bitrate or decrease the resolution).

Go to the scrcpy using cd (adapt the path):

    cd C:\Downloads\scrcpy

Then execute:

    scrcpy -m 1080 -b16M

**Comment by procircuitscrub** [comment]
So what would I type exactly in cmd if my path is C:\Users\PC\Desktop\Scrcpy ???

**Comment by procircuitscrub** [comment]
Wonderful, it's running perfectly now, I figured my PC could handle it easily, i'm on a Ryzen 2600 CPU and RX 580. Thanks so much!

**Comment by rom1v** [comment]
If you want to always run it with these arguments, create a file with `.bat` extension (for example `myscrcpy.bat`) in the scrcpy folder, containing:

     scrcpy -m1080 -b16M

Then you can just double-click on it.

**Comment by procircuitscrub** [comment]
![image](https://user-images.githubusercontent.com/29701861/62603527-16f88f80-b8c4-11e9-9c33-7f1bee1bc4fc.png)
Any idea how I can get my Note 9 to just stop doing this? It's Mega frustrating, because it seems to do it after a set period of time with me not physically touching the screen.

**Comment by procircuitscrub** [comment]
Any idea how I can get my Note 9 to just stop doing this? It's Mega frustrating, because it seems to do it after a set period of time with me not physically touching the screen.
![image](https://user-images.githubusercontent.com/29701861/62603657-5e7f1b80-b8c4-11e9-92b8-8736022a5514.png)
