### ISSUE TITLE
Wireless mirroring is lagging in redmi note 3

### ISSUE THREAD

**Issue by aanandharaja** [Genymobile/scrcpy#699]
iam using redmi note 3 phone, with usb its working very fine but wireless its so slow, using ubuntu 19.04. even i tried 420 resolution but its lagging. how to fix this issue.

**Comment by rom1v** [comment]
Try to reduce the bitrate:

    scrcpy -m800 -b2M

**Comment by aanandharaja** [comment]
> Try to reduce the bitrate:
> 
> ```
> scrcpy -m800 -b2M
> ```

tried but still lagging

**Comment by aanandharaja** [comment]
scrcpy -m800 -b2M

/usr/local/bin/scrcpy-server.jar: 1 fi...shed. 0.1 MB/s (22470 bytes in 0.273s)
error: more than one device/emulator
ERROR: "adb reverse" returned with value 1
WARN: 'adb reverse' failed, fallback to 'adb forward'
INFO: Initial texture: 448x800

what is that error and warning? its normal or any thing wrong in my settings?

**Comment by rom1v** [comment]
That's expected. See #5.

You can reduce the bitrate more:

    scrcpy -m800 -b1M

If it still lags, your network is not good enough.

**Comment by aanandharaja** [comment]
> That's expected. See #5.
> 
> You can reduce the bitrate more:
> 
> ```
> scrcpy -m800 -b1M
> ```
> 
> If it still lags, your network is not good enough.

my net speed is 50Mbps even i tried with my friend network its 100Mbps. still lags.

**Comment by rom1v** [comment]
Does it work correctly over USB?

**Comment by aanandharaja** [comment]
> Does it work correctly over USB?

yes working fine in usb.

**Comment by aanandharaja** [comment]
scrcpy -m800 -b1M
/usr/local/bin/scrcpy-server.jar: 1 fi...shed. 0.2 MB/s (22470 bytes in 0.137s)
error: more than one device/emulator
ERROR: "adb reverse" returned with value 1
WARN: 'adb reverse' failed, fallback to 'adb forward'
INFO: Initial texture: 448x800
INFO: FPS counter started
INFO: 9 fps
INFO: 2 fps
INFO: 3 fps
INFO: 4 fps
INFO: 6 fps
INFO: 6 fps
INFO: 10 fps (+5 frames skipped)
INFO: 13 fps (+3 frames skipped)
INFO: 5 fps
INFO: 6 fps
INFO: 5 fps (+1 frames skipped)
INFO: 17 fps (+5 frames skipped)
INFO: 6 fps
INFO: 15 fps (+8 frames skipped)
INFO: 1 fps
INFO: 3 fps
INFO: 5 fps
INFO: 5 fps
INFO: 5 fps
INFO: 10 fps (+4 frames skipped)
INFO: 10 fps (+3 frames skipped)
INFO: 17 fps (+4 frames skipped)
INFO: 3 fps
INFO: 6 fps
INFO: 4 fps
INFO: 5 fps
INFO: 15 fps (+13 frames skipped)
INFO: 13 fps (+3 frames skipped)
INFO: 15 fps (+13 frames skipped)
INFO: 12 fps
INFO: 31 fps (+29 frames skipped)
INFO: 36 fps (+26 frames skipped)
INFO: 33 fps (+27 frames skipped)
INFO: 32 fps (+28 frames skipped)
INFO: 16 fps (+6 frames skipped)
INFO: 1 fps
INFO: 2 fps
INFO: 1 fps
INFO: 2 fps
INFO: 2 fps
INFO: 3 fps
INFO: 10 fps (+10 frames skipped)
INFO: 2 fps
INFO: 15 fps (+1 frames skipped)
INFO: 26 fps (+20 frames skipped)

**Comment by rom1v** [comment]
> my net speed is 50Mbps even i tried with my friend network its 100Mbps. still lags.

Packet loss is probably the culprit here, due to [TCP Head-of-line blocking](https://en.wikipedia.org/wiki/Head-of-line_blocking). Even if you get a high bitrate, your network can lose packets too often.

It would need more investigations (with wireshark or tcpdump), but it seems confirmed by the fps results: as soon as you receive the lost packet (retransmitted), you receive all the pending frames at once (so the client skips them all except the last one).

**Comment by aanandharaja** [comment]
![Selection_091](https://user-images.githubusercontent.com/53866289/62630078-ec521980-b94b-11e9-8e57-fc68654dee59.png)

This is what iam getting

**Comment by aanandharaja** [comment]
![-Android Logcat Crash Redmi_Note_3 192 168 1 10:5555: android-logcat-text-crash-192 168 1 10:5555_092](https://user-images.githubusercontent.com/53866289/62632099-87002780-b94f-11e9-8f8b-388b2ba77e1e.png)

**Comment by aanandharaja** [comment]
> scrcpy --render-expired-frames -m800 -b1M
Using this command its works fine but video mirroring the quality is not good,  the mains problem is if i enable the Bluetooth for audio transfer, its very laggy. without Bluetooth much better.

**Comment by Genxster1998** [comment]
From #1795 , Problem is not **5ghz** for me , where I live ,there's rarely **2.4ghz** traffic exist (no other device) .also the distance btw phone and pc is like 1 metre .
Again I tried on Oreo , same result ,btw does **adb forward** perform bad against **adb reverse** ? 
I am using b 1m and definition 800 still ...
choppy on p2p connection with ping (1-5ms).
So , is this device specific now ? 
Thanks for quick reply ☺️ 
Have a great day
