### ISSUE TITLE
Mouse clicks do not work

### ISSUE THREAD

**Issue by Pong420** [Genymobile/scrcpy#70]
I am using Xiaomi max 2 on macOS High Sierra 10.13.3

```
scrcpy v1.0

dependencies:
 - SDL 2.0.8
 - libavcodec 57.107.100
 - libavformat 57.83.100
 - libavutil 55.78.100
```

**Comment by izayl** [comment]
Xiaomi Mi 6 has the same issue

**Comment by izayl** [comment]
@Pong420 Maybe [this issue](https://github.com/Genymobile/scrcpy/pull/27#issuecomment-372017580) can fix. But I have not test it.

**Comment by Pong420** [comment]
@izayl seems not work for me

**Comment by rom1v** [comment]
Duplicate of https://github.com/Genymobile/scrcpy/issues/18.

Already fix on v1.1.

**Comment by izayl** [comment]
@rom1v I have pull the newest code of master. But the problem still exist.

**Comment by rom1v** [comment]
scrcpy -v

?

**Comment by rom1v** [comment]
Did you compile using prebuilt server v1.1?

**Comment by Pong420** [comment]
sorry, how to check prebuilt server version?

v1.1 still not work
```
scrcpy v1.1

dependencies:
 - SDL 2.0.8
 - libavcodec 57.107.100
 - libavformat 57.83.100
 - libavutil 55.78.100
```

**Comment by izayl** [comment]
I find the reason of the issue，switch below option for obtain the permission of simulating Input

![image](https://user-images.githubusercontent.com/10740043/37449656-0693071e-2866-11e8-86f9-50dec962dd67.png)

**Comment by rom1v** [comment]
Did you compile everything, or downloaded the prebuilt server (the Android part)?

If you don't know, please give the result of:

    mesonconf x

(from the scrcpy root directory)

**Comment by Pong420** [comment]
Solved by enable the permission of simulating Input

Thanks all

**Comment by rom1v** [comment]
@izayl Thank you very much! I added a [question](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-clicks-do-not-work) in the FAQ.

**Comment by halilozercan** [comment]
Nokia 8 does not have that option in developer settings. My problem turned out be a slightly weird one. If I move scrcpy window from the screen it started on to a different monitor, mouse inputs become unreponsive.

**Comment by rom1v** [comment]
@halilozercan https://github.com/Genymobile/scrcpy/issues/15

**Comment by Nostalgene** [comment]
the 

> I find the reason of the issue，switch below option for obtain the permission of simulating Input
> 
> ![image](https://user-images.githubusercontent.com/10740043/37449656-0693071e-2866-11e8-86f9-50dec962dd67.png)

the screen off mirroring function does not work with either Ctrl+
o or terminal command …it says “unrecognised option” 
help please.. my phone is poco F1

**Comment by rom1v** [comment]
> the screen off mirroring function does not work with either Ctrl+o or terminal command …it says “unrecognised option”

(please do not post on an unrelated issue)

You need scrcpy v1.9.

    scrcpy --version

**Comment by ZythonNera** [comment]
> Xiaomi Mi 6 has the same issue

My Xiaomi Mi 6 no problem in windows.

**Comment by dottyunnan** [comment]
I want to know recording MP4's format.

**Comment by Ggot** [comment]
why  my android  OPPO R15 no USB debugging(Security settings) option? so  I  cannot  click my simulating screen .

**Comment by mochadwi** [comment]
thanks this is xiaomi issue, but also occurred in a few devices @Pong420

**Comment by n-3rd23** [comment]
thank you enabling USB debugging (security settings) worked on my phone mi 4

**Comment by mherweg** [comment]
On a Redmi 6A I get the popup "Sign in with you Mi Account"  :-(

**Comment by SkyPaladin** [comment]
> I find the reason of the issue，switch below option for obtain the permission of simulating Input
> 
> ![image](https://user-images.githubusercontent.com/10740043/37449656-0693071e-2866-11e8-86f9-50dec962dd67.png)

No such setting exists for me on Android 8.1. Device is a Motorola Moto G5 Plus.

**Comment by Kein** [comment]
In MIUI you are locked behind Mi Account link in order to enable ADBinput for keyboard and mouse. To bypass that (with **root**):

1. Enable USB debugging
2. Run any terminal as root
3. `setprop persist.security.adbinput 1`
4. That's all, nothing else is required

I dont believe root-less solution is possible because MIUI permission service will block any user-app trying to do the same.

**Comment by LosEagle** [comment]
> In MIUI you are locked behind Mi Account link in order to enable ADBinput for keyboard and mouse. To bypass that (with **root**):
> 
>     1. Enable USB debugging
> 
>     2. Run any terminal as root
> 
>     3. `setprop persist.security.adbinput 1`
> 
>     4. That's all, nothing else is required
> 
> 
> I dont believe root-less solution is possible because MIUI permission service will block any user-app trying to do the same.

I'm assuming the permission service can't be safely disabled with adb, right?

**Comment by Kein** [comment]
No, the security core cannot be uninstalled or disabled, it is rooted deep.

**Comment by ahmedsallam544** [comment]
how to enable this setting on Xiaomi Note 7 ? 
this screen does not appear

**Comment by VBK007** [comment]
Bro I have not above usb debugging security setting in Relame U1
I want to control through keybord and mouse help???

**Comment by Kein** [comment]
Read the thread

**Comment by Gojan444** [comment]
Man I have a Redmi 8 MIUI11 with Android 10
Click/Mouse doesn't work, I have enabled the developer options (the security options too) but the simulated entry doesn't appear. 
If I Root my phone, can I access that option? 
Thank you very much also in advance, you have done a great job with scrcpy, making life easier for hundreds (if not thousands) of people, I love you. 
**I really want to make PC control work**  😢 

![image](https://user-images.githubusercontent.com/11066988/91271004-218bfe00-e73f-11ea-86a9-bf7bb8f179a8.png)

**Comment by rom1v** [comment]
> the security options too

Then it should work. What's the output in the console?

**Comment by Gojan444** [comment]
> Then it should work. What's the output in the console?

Hi man,  yesterday at the time of my comment the console did not show anything different, scrcpy showed the image and even some keyboard shortcuts (alt +) in my windows worked well.
So today I tried to restart both my PC and my SmartPhone, and then I got the   `"adb push" returned with value 1`    Error.  
I tried to fix it (by closing scrcpy and restart my xiaomi a couple times)  and then Control (click) works well 😄 !  
So forgive me for my earlier comment, I am happy that it finally works well, **thank you very much!**

**Comment by EnzoKronus** [comment]
> I find the reason of the issue，switch below option for obtain the permission of simulating Input
> 
> ![image](https://user-images.githubusercontent.com/10740043/37449656-0693071e-2866-11e8-86f9-50dec962dd67.png)

thanks this works for me!

**Comment by Mixterix-AL** [comment]
> I find the reason of the issue，switch below option for obtain the permission of simulating Input
> 
> ![image](https://user-images.githubusercontent.com/10740043/37449656-0693071e-2866-11e8-86f9-50dec962dd67.png)


It does not work on Xiaomi Redmi Note 9S Android 10, when I try to activate the option, it is never activated, and I cannot use Scrycpy

**Comment by truebit** [comment]
On Oppo，turn on "Disable permission monitoring" in "Developer options"/"APPS" section.

**Comment by matthewstrasiotto** [comment]
Everyone using a Xiaomi device - 

@Mixterix-AL @ahmedsallam544 

Others have discussed rooting your device, which, in my opinion, unless you really want root for other reasons, is a a bit overkill.

The simple solution is to do what your manufacturer is telling you - "Sign in with your Mi account".

Personally, I find the constraint odd - If I'm activating devtools & running adb, chances are I have a good idea of whatever it is I want to do, and I've already dismissed one or two warning dialogues already- but, personally, I take it on good faith that the manufacturer is trying to protect me from myself.

I'm unsure of exactly why people are so reluctant to follow the "easy" fix, and make an account- they support SSO via Google + Facebook.

Is it privacy concerns? Their privacy policy is a little disconcerting.

![image](https://user-images.githubusercontent.com/39424834/111090984-a4629200-8585-11eb-9255-74dfac282c58.png)

Personally, I signed into a Mi account, activated the setting, and signed out of the account again & everything seems to be working just fine.

**Comment by Kein** [comment]
> Personally, I signed into a Mi account, activated the setting, and signed out of the account again & everything seems to be working just fine.

Cant un-upload all the personal data they already fetched from your phone on the sign-up process.

**Comment by matthewstrasiotto** [comment]
> > Personally, I signed into a Mi account, activated the setting, and signed out of the account again & everything seems to be working just fine.
> 
> Cant un-upload all the personal data they already fetched from your phone on the sign-up process.

Great point @Kein . 

For me personally, given the SSO process didn't seem to activate an OAuth consent screen, it looked like maybe I'd already made this arguable mistake at some point in the span of my Pocofone ownership

**Comment by matthewstrasiotto** [comment]
@Kein , I updated my comment with a more in-depth discussion of the tradeoffs.

**Comment by TejasDhanda-L11** [comment]
> On Oppo，turn on "Disable permission monitoring" in "Developer options"/"APPS" section.

it still isn't working on oppo

**Comment by rom1v** [comment]
> it still isn't working on oppo

#2031

**Comment by 7wells** [comment]
> 
> 
> I find the reason of the issue，switch below option for obtain the permission of simulating Input
> 
> ![image](https://user-images.githubusercontent.com/10740043/37449656-0693071e-2866-11e8-86f9-50dec962dd67.png)

When I try to enable this, I get the message that I shall connect to the network and try again later. Why that? Is there any workaround for this? Do I also have to register and sign in to my Mi account? As the phone is brand new, I haven't done this yet. Thanks for your help, guys!

**Comment by Anjula998** [comment]
Mouse click do not work

**Comment by Anjula998** [comment]
How to use m31 samsung

**Comment by EngZeeshanAli** [comment]
> I find the reason of the issue，switch below option for obtain the permission of simulating Input
> 
> ![image](https://user-images.githubusercontent.com/10740043/37449656-0693071e-2866-11e8-86f9-50dec962dd67.png)

This works for me Thanks...

**Comment by HanzMcs** [comment]
Xiaomi Redmi 10s WASD(keyboard) for motion analog game not working

**Comment by rom1v** [comment]
If the game does not implement WASD, that's expected :/

**Comment by xandro972** [comment]
I really Love it Sir, 
btw I am wondering. how about add sound ? So i can hear from my Laptop. 
thx in advance

**Comment by SarveshPatil5** [comment]
i have Xiaomi Redmi note 10 pro ( **android 12** ) and having this error please need some help
**ERROR: Encoding error: java.lang.IllegalStateException: null**

**Comment by rom1v** [comment]
Please do not post on a randum unrelated thread.

See #3051

**Comment by punkxxx1519** [comment]
I have the doubt of how I can connect a joystick to play sky chidren of the light will there be a solution for that

**Comment by eurkas** [comment]
How can I play the video on the Android TV remotely using Windows. And play the video on the same TV and not on the computer

**Comment by imkkdev** [comment]
> I find the reason of the issue，switch below option for obtain the permission of simulating Input
> 
> ![image](https://user-images.githubusercontent.com/10740043/37449656-0693071e-2866-11e8-86f9-50dec962dd67.png)

on XiaoMI Phone ，also need to reboot

**Comment by ethicbelief** [comment]
> i have Xiaomi Redmi note 10 pro ( **android 12** ) and having this error please need some help **ERROR: Encoding error: java.lang.IllegalStateException: null**

Estou com o mesmo problema, poderia me ajudar, caso tenha resolvido ?

**Comment by Ahmadprogrmmer** [comment]
> 



> Thanks you @imkkdev I am using Xiaomi Mi11t Lite MIUI13/ Android 12 Phone, I can confirm it works after set the USB debug security settings and reboot, reboot is must!

Bro did it work on 8.1.0 android

**Comment by AyoCodess** [comment]
> I find the reason of the issue，switch below option for obtain the permission of simulating Input
> 
> ![image](https://user-images.githubusercontent.com/10740043/37449656-0693071e-2866-11e8-86f9-50dec962dd67.png)

thank you

**Comment by nafanz** [comment]
Thanks for the tip, I'll just add when I tried to turn it on, they asked me to log into my mi community account. 
After that everything worked.

**Comment by Ontropy** [comment]
Yea restarting after enabling the security settings is a MUST as @neonleo said. Thank you it works perfectly now. I spent so much time trying to figure it out without having it restarted.

**Comment by hexearth** [comment]
My Device: Xiaomi M2101K6G (Android 12)

It does not work as it requires a connection or account to Xiaomi but since I don't want an account, it will never work, unless someone finds the app that we can remove to bypass this.

![xiaomi-usb](https://user-images.githubusercontent.com/114895962/224547640-90fb297e-5eb6-417d-a64c-50fc017c55e9.png)

**Comment by Ontropy** [comment]
> My Device: Xiaomi M2101K6G (Android 12)
> 
> It does not work as it requires a connection or account to Xiaomi but since I don't want an account, it will never work, unless someone finds the app that we can remove to bypass this.
> 
> ![xiaomi-usb](https://user-images.githubusercontent.com/114895962/224547640-90fb297e-5eb6-417d-a64c-50fc017c55e9.png)

You could try shifting from miui to something else.

**Comment by vajra108** [comment]
> Thanks you @imkkdev I am using Xiaomi Mi11t Lite MIUI13/ Android 12 Phone, I can confirm it works after set the USB debug security settings and reboot, reboot is must!

omg so much time lost because I didn't reboot, thank you!

**Comment by rom1v** [comment]
@vajra108 Thank you, I just mentioned it in the doc: 21df2c240e544b1c1eba7775e1474c1c772be04b

**Comment by F640** [comment]
> My Device: Xiaomi M2101K6G (Android 12)
> 
> It does not work as it requires a connection or account to Xiaomi but since I don't want an account, it will never work, unless someone finds the app that we can remove to bypass this.
> 
> ![xiaomi-usb](https://user-images.githubusercontent.com/114895962/224547640-90fb297e-5eb6-417d-a64c-50fc017c55e9.png)

You can just make a throwaway Mi account in browser with disposable (or throwaway or temporary) email services, and fill fake info if they ask for while making Mi account. Create account, sign in, turn on, then sign out. Rebooting your device also recommended afterwards. Just hope they won't ask your phone number.

**Comment by Jamalalqale** [comment]
Just disable the MIUI optimization

**Comment by owenstake** [comment]
> Thanks you @imkkdev I am using Xiaomi Mi11t Lite MIUI13/ Android 12 Phone, I can confirm it works after set the USB debug security settings and reboot, reboot is must!

reboot save my day!

**Comment by kilo1994** [comment]
Running Android 14 on the Pixel 7 Pro.  No "USB debugging (Security Settings)" option under Develop
![image](https://github.com/Genymobile/scrcpy/assets/149531790/d75aed79-f9a7-4253-941b-bf80544870bc)

**Comment by rom1v** [comment]
On Android 14, use the latest version (v2.1.1 currently)

**Comment by kilo1994** [comment]
That did it, thanks!

**Comment by eevmanu** [comment]
> On Android 14, use the latest version (v2.1.1 currently)

thx @rom1v 

---

to anyone who could find this helpful, the version I had via `apt` isn't equal or greater than v2.1.1 ...

```sh
$ apt show scrcpy 2>/dev/null | grep -i version
Version: 1.17-1
```

... neither the version from `snap`

```sh
$ snap info scrcpy | grep -A 4 channels
channels:
  latest/stable:    v1.25             2022-12-28 (399)  87MB -
  latest/candidate: ^
  latest/beta:      v1.25-1-g4c43784f 2022-12-28 (401)  87MB -
  latest/edge:      v1.21-2-g5704ec6  2021-12-07 (358) 101MB -
```

because I was having this error

<details>
<summary> error stack trace </summary>

```sh
[server] ERROR: Exception on thread Thread[Thread-2,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.ServiceManager.getInputManager(ServiceManager.java:75)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:192)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:196)
	at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:231)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:102)
	at com.genymobile.scrcpy.Controller.control(Controller.java:79)
	at com.genymobile.scrcpy.Server$3.run(Server.java:132)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.ServiceManager.getInputManager(ServiceManager.java:72)
	... 7 more
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:207)
	at android.hardware.input.InputManager.getInstance(InputManager.java:274)
	... 9 more
```

</details>

so the only way I had was building by myself, thx for the [guide](https://github.com/Genymobile/scrcpy/blob/master/doc/build.md) and the [prebuilt server](https://github.com/Genymobile/scrcpy/releases/download/v2.4/scrcpy-server-v2.4), with that everything was really easy

`$ meson setup x --buildtype=release --strip -Db_lto=true -Dprebuilt_server=/path/to/scrcpy-server
`

<details>
<summary> output </summary>

```sh
The Meson build system
Version: 0.56.2
Source dir: "${HOME}"/tmp/scrcpy
Build dir: "${HOME}"/tmp/scrcpy/x
Build type: native build
Project name: scrcpy
Project version: 2.4
C compiler for the host machine: cc (gcc 11.2.0 "cc (Ubuntu 11.2.0-7ubuntu2) 11.2.0")
C linker for the host machine: cc ld.bfd 2.37
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency libavformat found: YES 58.76.100
Run-time dependency libavcodec found: YES 58.134.100
Run-time dependency libavutil found: YES 56.70.100
Run-time dependency libswresample found: YES 3.9.100
Run-time dependency sdl2 found: YES 2.0.14
Run-time dependency libavdevice found: YES 58.13.100
Run-time dependency libusb-1.0 found: YES 1.0.24
Checking for function "strdup" : YES
Checking for function "asprintf" : YES
Checking for function "vasprintf" : YES
Checking for function "nrand48" : YES
Checking for function "jrand48" : YES
Checking for function "reallocarray" : YES
Header <sys/socket.h> has symbol "SOCK_CLOEXEC" : YES
Configuring config.h using configuration
Build targets in project: 2

Found ninja-1.10.1 at /usr/bin/ninja
```

</details>

`$ ninja -Cx`

<details>
<summary> output </summary>

```sh
ninja: Entering directory `x'
[69/69] Linking target app/scrcpy
```

</details>

**Comment by Step72** [comment]
I use scrcpy on mac os 14.4.1 and redmi note 12 with android 14 but impossible to make the mouse click work!
<img width="448" alt="Capture d’écran 2024-04-17 à 17 09 03" src="https://github.com/Genymobile/scrcpy/assets/18511992/a8239ccf-d6fc-42fa-a14c-79387a1b9e60">

**Comment by rom1v** [comment]
@Step72 https://github.com/Genymobile/scrcpy#prerequisites

**Comment by Step72** [comment]
@rom1v I can't validate my phone! Every time I have an error
<img width="521" alt="Capture d’écran 2024-04-17 à 18 22 59" src="https://github.com/Genymobile/scrcpy/assets/18511992/4d0e5051-3001-4b7f-934d-76e0f19adc77">

**Comment by rom1v** [comment]
```
scrcpy --otg -s 6da1ded7
```

**Comment by Step72** [comment]
if I put scrcpy --otg -s 6da1ded7 I can no longer use my mouse for my computer! This completely dooms my mouse to my phone. Why when I click on, for example, an application on my phone does it not open for me?

**Comment by rom1v** [comment]
It's OTG mode. If you don't want OTG mode, then don't pass `--otg`. What do you want to do?

**Comment by Step72** [comment]
I don't understand, I can't connect anymore
<img width="634" alt="Capture d’écran 2024-04-18 à 09 38 32" src="https://github.com/Genymobile/scrcpy/assets/18511992/4bab14bc-5393-417c-86bf-145c6de25b6a">

**Comment by Step72** [comment]
Watch [this video](https://we.tl/t-fCV8yR8ocz)
Why does it not open when I click on the Facebook app? On the other hand, if we look to the left at the terminal, we can clearly see that something is working!

If I run scrcpy --otg -s 6da1ded7 The mouse in my computer no longer works with my computer, computer! It is dedicated only to my phone. How can I simply press a key on the phone screen from the computer, for example [Teamvier](https://we.tl/t-3dcqxjhkym) ?

**Comment by Step72** [comment]
It's okay, it works perfectly.
**permettre d'accorder des autorisations et de simuler une entrée via USB** Was not activated
<img width="523" alt="Capture d’écran 2024-04-18 à 12 04 56" src="https://github.com/Genymobile/scrcpy/assets/18511992/00710435-0273-466e-9aee-f4ca9a827799">

**Comment by InternetTourrer** [comment]
Hi I might be missing something obvious here but I can't find the option for "USB debugging (Security Settings)" I am on the latest version and have enabled just "USB Debugging" and cannot get mouse or keyboard to work. (Using Samsung Z Fold 3)
![Screenshot_20240617_225012_Settings](https://github.com/Genymobile/scrcpy/assets/173106986/f56a0cd7-31c9-457d-85c1-ab6c088ad544)

**Comment by llinfeng** [comment]
> ... I can't find the option for "USB debugging (Security Settings)" I am on the latest version and have enabled just "USB Debugging" and cannot get mouse or keyboard to work. (Using Samsung Z Fold 3)

Likewise, I cannot get mouse nor keyboard to work on a Samsung Tab S9 (Android 14). I can only see what's on the tablet's screen. I think this can be something new after upgrading this tablet to Android 14.

> What is the full console output when you run scrcpy?



<details>
  <summary>Here is what I directly see when running `scrcpy` in Windows command-line (after having connected to the Samsung tablet through adb) on this tablet.</summary>
  
```
c:\programdata\chocolatey\lib\scrcpy\tools\scrcpy-server: 1 file pushed, 0 skipped. 74.7 MB/s (41159 bytes in 0.001s)
[server] INFO: Device: samsung SM-X710 (Android 14)
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, int]
        at java.lang.Class.getMethod(Class.java:2937)
        at java.lang.Class.getMethod(Class.java:2449)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:103)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:111)
        at com.genymobile.scrcpy.Device.<init>(Device.java:103)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:65)
        at com.genymobile.scrcpy.Server.main(Server.java:335)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:385)
INFO: Renderer: direct3d
INFO: Initial texture: 1600x2560
[server] ERROR: Exception on thread Thread[Thread-2,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at com.genymobile.scrcpy.wrappers.ServiceManager.getInputManager(ServiceManager.java:65)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:195)
        at com.genymobile.scrcpy.Device.injectKeyEvent(Device.java:206)
        at com.genymobile.scrcpy.Device.injectKeyEvent(Device.java:210)
        at com.genymobile.scrcpy.Controller.injectKeycode(Controller.java:148)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:88)
        at com.genymobile.scrcpy.Controller.control(Controller.java:75)
        at com.genymobile.scrcpy.Server$3.run(Server.java:133)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.ServiceManager.getInputManager(ServiceManager.java:62)
        ... 8 more
Caused by: java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:207)
        at android.hardware.input.InputManager.getInstance(InputManager.java:401)
        ... 10 more
```
</details>

<details>
  <summary>And, similarly, with a Samsung S22 Ultra.</summary>

Here, I noticed that the first `[server] ERROR` is logged immediately upon connection. The second `[server] ERROR` is logged when I tried to send a right-mouse-click.
  
```
c:\programdata\chocolatey\lib\scrcpy\tools\scrcpy-server: 1 file pushed, 0 skipped. 53.2 MB/s (41159 bytes in 0.001s)
[server] INFO: Device: samsung SM-S908U1 (Android 14)
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, int]
        at java.lang.Class.getMethod(Class.java:2937)
        at java.lang.Class.getMethod(Class.java:2449)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:103)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:111)
        at com.genymobile.scrcpy.Device.<init>(Device.java:103)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:65)
        at com.genymobile.scrcpy.Server.main(Server.java:335)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:385)
INFO: Renderer: direct3d
INFO: Initial texture: 720x1544
[server] ERROR: Exception on thread Thread[Thread-2,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at com.genymobile.scrcpy.wrappers.ServiceManager.getInputManager(ServiceManager.java:65)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:195)
        at com.genymobile.scrcpy.Device.injectKeyEvent(Device.java:206)
        at com.genymobile.scrcpy.Device.injectKeyEvent(Device.java:210)
        at com.genymobile.scrcpy.Controller.pressBackOrTurnScreenOn(Controller.java:264)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:108)
        at com.genymobile.scrcpy.Controller.control(Controller.java:75)
        at com.genymobile.scrcpy.Server$3.run(Server.java:133)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.ServiceManager.getInputManager(ServiceManager.java:62)
        ... 8 more
Caused by: java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:207)
        at android.hardware.input.InputManager.getInstance(InputManager.java:401)
        ... 10 more

```
</details>

@rom1v Please advise if there is a `scrcpy` flag for more verbose logs if the logs above are too preliminary.

**Comment by rom1v** [comment]
What is your scrcpy version? I guess you don't use the latest version (currently 2.5).

**Comment by llinfeng** [comment]
Indeed, I was using old `scrcpy` previously (v1.24). Upgrading to v2.4.0 solved the issue already. (I ran `choco upgrade scrcpy` to upgrade.)

**Comment by elias8808** [comment]
I can't use my mouse or keyboard. Has anyone found a solution?

**Comment by elias8808** [comment]
solved. you must enable "usb debugging security settings" on your cell phone and then when connecting the cell phone to the PC, you must select "file transfer". this is how it worked for me.

**Comment by LarryP327** [comment]
I see quite a few comments with similar issues. My mouse, keyboard, and audio will not work using scrcpy. I am using scrcpy-win64-v3.1. I double-clicked the "no-console.vbs" as it said in the setup video on YouTube. I have restarted my phone and computer. The screen mirroring works. I do not see "USB debugging security settings" in the developer options. However, USB debugging is turned on. I have a Pixel 9 running Andriod 15. Is there a fix?

**Comment by rom1v** [comment]
> I double-clicked the "no-console.vbs"

Run from a console, you might have more details: https://github.com/Genymobile/scrcpy/blob/master/doc/windows.md#run

If you still don't have any relevant error, run with `scrcpy -Vverbose` to see what's injected.

**Comment by LarryP327** [comment]
I'm a complete novice at this. Where would I run scrcpy -Vverbose from?

**Comment by rom1v** [comment]
Read the link in my previous comment, it's explained.

**Comment by LarryP327** [comment]
It came up with an error. "Could not find any ADB device" "server connection failed".

**Comment by elfomze** [comment]
I'm facing the same issue on:
Host: 
OS: Ubuntu 22.04.5 LTS x86_64 
Host: Precision 7680 
Kernel: 6.8.0-51-generic 

Phone:
Samsung Galaxy S24U 512gb black (Europe)

Output of `srcpy -V verbose` after launching, seeing the screen and making a few clicks on mouse and keyboard:
```
[server] INFO: Device: samsung SM-S928B (Android 14)
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, class java.lang.String, int]
	at java.lang.Class.getMethod(Class.java:2950)
	at java.lang.Class.getMethod(Class.java:2450)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:128)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:138)
	at com.genymobile.scrcpy.Device.<init>(Device.java:100)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:64)
	at com.genymobile.scrcpy.Server.main(Server.java:334)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:395)
[server] ERROR: Exception on thread Thread[Thread-2,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.ServiceManager.getInputManager(ServiceManager.java:75)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:192)
	at com.genymobile.scrcpy.Device.injectKeyEvent(Device.java:203)
	at com.genymobile.scrcpy.Device.pressReleaseKeycode(Device.java:211)
	at com.genymobile.scrcpy.Device.pressReleaseKeycode(Device.java:216)
	at com.genymobile.scrcpy.Controller.control(Controller.java:66)
	at com.genymobile.scrcpy.Server$3.run(Server.java:132)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.ServiceManager.getInputManager(ServiceManager.java:72)
	... 7 more
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:207)
	at android.hardware.input.InputManager.getInstance(InputManager.java:401)
	... 9 more
DEBUG: Server connected
DEBUG: Starting controller thread
DEBUG: Starting receiver thread
INFO: Renderer: opengl
INFO: OpenGL version: 3.1 Mesa 20.0.8
INFO: Trilinear filtering enabled
DEBUG: Using icon: /usr/local/share/icons/hicolor/256x256/apps/scrcpy.png
INFO: Initial texture: 1080x2336
DEBUG: Starting demuxer thread
[server] DEBUG: Using encoder: 'c2.qti.avc.encoder'
VERBOSE: input: touch [id=finger] down position=404,1354 pressure=1.000000 buttons=000001
VERBOSE: input: touch [id=finger] move position=408,1354 pressure=1.000000 buttons=000001
VERBOSE: input: touch [id=finger] up   position=408,1354 pressure=0.000000 buttons=000000
VERBOSE: input: key down code=62 repeat=0 meta=200000
VERBOSE: input: key up   code=62 repeat=0 meta=200000
DEBUG: User requested to quit
DEBUG: quit...
DEBUG: End of frames
DEBUG: Receiver stopped
WARN: Killing the server...
DEBUG: Server disconnected
DEBUG: Server terminated
```

**Comment by elfomze** [comment]
> [@elfomze](https://github.com/elfomze) You're probably not running the latest version of scrcpy (currently 3.1).

Yep, my bad. I was running the old unofficial(?) snap version. 3.1 works 🙏

**Comment by csa-x** [comment]
my simcard doesn't work, can't enable it.

**Comment by artillerymans** [comment]
Do you have to plug in the SIM and turn the switch on for this to work?
My status.
1. Enabled USB security settings
2.Device is not SIM inserted
The result is not working

**Comment by iuriimattos2** [comment]
Mouse clicks root-less solution works for me `.\scrcpy --mouse=uhid --keyboard=uhid` 
But usb debugging cannot be enabled without Mi Account and SIM card.

**Comment by ahmedqabd** [comment]
The touch screen isn't working, I need a screen replacement
ERROR: Could not find any ADB device
ERROR: Server connection failed

**Comment by 7d4d9e33** [comment]
> Mouse clicks root-less solution works for me `.\scrcpy --mouse=uhid --keyboard=uhid` But usb debugging cannot be enabled without Mi Account and SIM card.

Wait, that requirement just to enable adb on xiaomi devices is a thing now? To this day only security settings and install via adb require them for me for full adb functionality. (limited) adb has never asked such requirements.
