### ISSUE TITLE
Android 6.0 green screen only in 1.10 but worked in 1.9

### ISSUE THREAD

**Issue by BartmanEH** [Genymobile/scrcpy#700]
works in v1.9 but only green screen in v1.10

**Comment by rom1v** [comment]
SDL and FFmpeg dll have been updated.

Please try to replace `SDL2.dll` by the one in v1.9.
If it does not work, try to replace `av*.dll` and `sw*.dll` by the ones in v1.9.

**Comment by BartmanEH** [comment]
replacing just SDL2.DLL results in:
![image](https://user-images.githubusercontent.com/6135879/62639183-fd2f6a80-b90c-11e9-9425-f251c9aad34c.png)

**Comment by rom1v** [comment]
Here is v1.10 + downgrade SDL 2.0.10 to SDL 2.0.8: [`scrcpy-win64.zip`](https://tmp.rom1v.com/scrcpy/issue700/1/scrcpy-win64.zip)
_SHA256: 92c13caf8dd204ff7f2d5d33a301e2a0f486893e52fd0074b4f483a08fd988e8_

**Comment by BartmanEH** [comment]
Well it turns out I was using the Win32 version and that was just a green screen. I tried the Win64 version of v1.10 and it seems to be working. Sorry for the wild goose chase and thanks for your support. Such a great app!
