### ISSUE TITLE
Scrpy not working on p30 lite

### ISSUE THREAD

**Issue by wichvel** [Genymobile/scrcpy#701]
Hi everyone,

I tried to run scrcpy on a p30 lite and didnt work, then I run it on a samsung s4 and j5 and work fine and a motorola and work fine but on the p30 lite it says:
![IMG_20190807_113953](https://user-images.githubusercontent.com/53872880/62640899-239ed700-b908-11e9-94a4-52d65138c3ed.jpg)

If someone knows what can I do? Thanks

**Comment by rom1v** [comment]
Try with a lower definition:

    scrcpy -m 1024

**Comment by wichvel** [comment]
Wow you are a genious! Worked!!!! Thanks a lot!!!!

**Comment by RWOverdijk** [comment]
@rom1v Is there a way to get it in all its glory? scrcpy is really sharp on other devices, and a bit low quality on the p30 lite.

**Comment by rom1v** [comment]
Increase the definition until it fails:

    scrcpy -m1024
    scrcpy -m1280
    scrcpy -m1600
    ...

**Comment by RWOverdijk** [comment]
Scientific 😄 Any way to get this automated? I wouldn't mind getting my hands dirty. Surely there's a reason this happens, right?

**Comment by rom1v** [comment]
> Surely there's a reason this happens, right?

The hardware encoder in your device is not able to encode the video with the requested configuration.

**Comment by rom1v** [comment]
> Surely there's a reason this happens, right?

The hardware encoder in your device is not able to encode the video with the requested configuration.
