### ISSUE TITLE
macOS error: Python already installed

### ISSUE THREAD

**Issue by srujanb** [Genymobile/scrcpy#703]
I have installed scrcpy before using homebrew on my other mac and it worked just fine. When I am trying to do it on my new machine, I am getting this error: 

    Error: python is already installed from !
    Please `brew uninstall python` first."

Do I really need to uninstall python first? Idk why could that be necessary.

**Comment by rom1v** [comment]
Sorry, I have no idea. It seems a bug in brew:

> Error: python is already installed from !

It seems there is an unexpected empty string between `from` and `!`
