### ISSUE TITLE
Desktop keyboard cannot input Chinese characters

### ISSUE THREAD

**Issue by ylrace** [Genymobile/scrcpy#705]
phone：xiaomi 6 Android 9
desktop：win10
Hi.I can not input Chinese characters.The screen only shows English  characters.
![image](https://user-images.githubusercontent.com/47076935/62673431-071aa180-b9d1-11e9-8180-c59f3dd7ebab.png)

**Comment by rom1v** [comment]
Yes, I'm closing as duplicate of #632 (and others).

**Comment by rom1v** [comment]
Please test #1426 (works on Android >= 7).
