### ISSUE TITLE
Mouse clicks do not work on certain screen sizes

### ISSUE THREAD

**Issue by gusti-syahputera** [Genymobile/scrcpy#706]
When `scrcpy` is run, the mouse clicks do not work on certain devices. These are the printed messages of such devices:
`$scrcpy`
`INFO: Initial texture: 600x1024`
`INFO: New texture: 608x1024`

This is the printed messages of majority devices (no "New texture" and mouse clicks work):
`$scrcpy`
`INFO: Initial texture: 720x1280`

Back to the first devices, when the screen size is reduced with the `--max-size` option, there are two possibilities according to the value:
1. The "New texture" message is not printed and mouse clicks work perfectly. For example:
`$scrcpy --max-size 600`
`INFO: Initial texture: 352x600`
2. The "New texture" message is printed and the mouse clicks do not work. For example:
`$scrcpy --max-size 700`
`INFO: Initial texture: 456x776`
`INFO: New texture: 464x776`

**Comment by rom1v** [comment]
When it does not work, are there any relevant messages in `adb logcat`?

**Comment by gusti-syahputera** [comment]
> When it does not work, are there any relevant messages in `adb logcat`?

No, there is no message on adb logcat that related to this issue.

**Comment by gusti-syahputera** [comment]
I have managed to get another behaviours with different screen sizes and orientations.

1. In native resolution, device is in portrait:
`$scrcpy`
`INFO: Initial texture: 600x1024`
`INFO: New texture: 608x1024` (mouse clicks does not work)
...rotating to landscape...
`INFO: New texture: 1024x600` (mouse clicks work)
...rotating back to portrait...
`INFO: New texture: 608x1024` (mouse clicks does not work)

2. Screen sizes is reduced with certain value, for example 500:
`$scrcpy --max-size 500`
`INFO: Initial texture: 288x496` (mouse clicks work)
...rotating to landscape...
`INFO: New texture: 496x288` (mouse clicks work too)
...rotating back to portrait...
`INFO: New texture: 288x496` (mouse clicks work)

3. Screen size is reduced with another value, for example 600:
`$scrcpy --max-size 600`
`INFO: Initial texture: 352x600` (mouse clicks work)
...rotating to landscape...
`INFO: New texture: 608x352` (mouse clicks does not work)
...rotating back to portrait...
`INFO: New texture: 352x600` (mouse clicks work)

Additional information:
- The particular device has native resolution of 1024x600 which is close to but not exactly 16:9.
- When the mouse clicks does not work, black border appears on the right side of the window.
- Keyboard, middle mouse click and right mouse click works in all conditions.
- The issue occurs in GNU/Linux and Windows.

**Comment by rom1v** [comment]
OK, thank you for the details, I got it.

In scrcpy, the video dimensions is always rounded to a multiple of 8 (floor). This is why for example 500 is rounded to 496.

The server initially retrieves the device size and sends it immediately to the client so that it can initialize before receiving the first frame.

The problem is that your hardware encoder produces frames with dimensions rounded to the next multiple of 16 (so it does not match the requested dimensions). Since the client only consider frame sizes, it computes every location for the given frame size it knows.

But to avoid glitches on rotation (a click expressed in portrait mode that would be interpreted after the device has been rotated), the server willingly ignore the events with unexpected dimensions. That's why mouse clicks do not work. With this hack, it will work:

```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/Device.java b/server/src/main/java/com/genymobile/scrcpy/Device.java
index 538135d..1d6b4ef 100644
--- a/server/src/main/java/com/genymobile/scrcpy/Device.java
+++ b/server/src/main/java/com/genymobile/scrcpy/Device.java
@@ -104,11 +104,6 @@ public final class Device {
         ScreenInfo screenInfo = getScreenInfo(); // read with synchronization
         Size videoSize = screenInfo.getVideoSize();
         Size clientVideoSize = position.getScreenSize();
-        if (!videoSize.equals(clientVideoSize)) {
-            // The client sends a click relative to a video with wrong dimensions,
-            // the device may have been rotated since the event was generated, so ignore the event
-            return null;
-        }
         Rect contentRect = screenInfo.getContentRect();
         Point point = position.getPoint();
         int scaledX = contentRect.left + point.getX() * contentRect.width() / videoSize.getWidth();
```

For your device, you need a multiple of 16:

```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/Device.java b/server/src/main/java/com/genymobile/scrcpy/Device.java
index 538135d..2dc0c3b 100644
--- a/server/src/main/java/com/genymobile/scrcpy/Device.java
+++ b/server/src/main/java/com/genymobile/scrcpy/Device.java
@@ -76,11 +76,11 @@ public final class Device {
         // Principle:
         // - scale down the great side of the screen to maxSize (if necessary);
         // - scale down the other side so that the aspect ratio is preserved;
-        // - round this value to the nearest multiple of 8 (H.264 only accepts multiples of 8)
-        w &= ~7; // in case it's not a multiple of 8
-        h &= ~7;
+        // - round this value to the nearest multiple of 16
+        w &= ~15; // in case it's not a multiple of 16
+        h &= ~15;
         if (maxSize > 0) {
-            if (BuildConfig.DEBUG && maxSize % 8 != 0) {
+            if (BuildConfig.DEBUG && maxSize % 16 != 0) {
                 throw new AssertionError("Max size must be a multiple of 8");
             }
             boolean portrait = h > w;
@@ -88,8 +88,8 @@ public final class Device {
             int minor = portrait ? w : h;
             if (major > maxSize) {
                 int minorExact = minor * maxSize / major;
-                // +4 to round the value to the nearest multiple of 8
-                minor = (minorExact + 4) & ~7;
+                // +8 to round the value to the nearest multiple of 16
+                minor = (minorExact + 8) & ~15;
                 major = maxSize;
             }
             w = portrait ? minor : major;
diff --git a/server/src/main/java/com/genymobile/scrcpy/Server.java b/server/src/main/java/com/genymobile/scrcpy/Server.java
index 3bd2fcd..83ac0bf 100644
--- a/server/src/main/java/com/genymobile/scrcpy/Server.java
+++ b/server/src/main/java/com/genymobile/scrcpy/Server.java
@@ -73,7 +73,7 @@ public final class Server {
 
         Options options = new Options();
 
-        int maxSize = Integer.parseInt(args[0]) & ~7; // multiple of 8
+        int maxSize = Integer.parseInt(args[0]) & ~15; // multiple of 15
         options.setMaxSize(maxSize);
 
         int bitRate = Integer.parseInt(args[1]);
```

**Comment by gusti-syahputera** [comment]
Nicely done. Thank you for resolving this issue and your work for this software.

**Comment by rom1v** [comment]
Note that I did not merge the diff I provided. I am not sure we should limit all devices to multiples of 8 (most of devices support it).

As a workaround on the released version, just take care to provide a multiple of 16 to the `-m` option:

    scrcpy -m 592
