### ISSUE TITLE
Cannot unlock screen using keyboard

### ISSUE THREAD

**Issue by guillaumedc** [Genymobile/scrcpy#71]
As stated in the issue title, I cannot unlock the screen (PIN) using the client keyboard.

**Comment by rom1v** [comment]
What is your device?

I just tested on a Nexus 5, it works.

**Comment by guillaumedc** [comment]
My device is a LG G4.
I'm using LineageOS 14.1.

**Comment by jseybold** [comment]
Are you at the pin prompt? I have to swipe up to get to the prompt, then I can enter the pin. Another method is you can hit tab until the fingerprint unlock icon is selected, then spacebar/enter, then put your pin in.

Starting from a window with the screen off, I do:
```
Ctrl+P
Tab
Tab
Spacebar
PIN
Enter
```

**Comment by guillaumedc** [comment]
Yes, I am at the pin prompt.
Typing makes dots appear, so numbers are considered.
But when I validate, I got «wrong pin» error.

How can I debug this?

Version used: 1.5

**Comment by rom1v** [comment]
The "app" managing the lock screen just does not support keyboard for entering PIN.
