### ISSUE TITLE
Can scrpy be extended to work with using adb from the recovery (twrp) ?

### ISSUE THREAD

**Issue by aiamuzz** [Genymobile/scrcpy#713]
@rom1v ...

I was wondering if `scrcpy` would work with the recovery adb ?

```
$ adb devices
List of devices attached
036axxx931657b	recovery
```

If not would it be a good idea(achievable) to extend it to work even with the recovery adb access ?

thanks.

**Comment by aiamuzz** [comment]
currently its stuck at ... with nothing happening beyond ...

```
$ scrcpy -b1M -m600
INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server.jar: 1 file pushed. 0.2 MB/s (22546 bytes in 0.098s)
/sbin/sh: app_process: not found

```

I am assuming there is some app(server) that gets installed on the device before scrcpy can mirror the screen ... i guess if its possible to have that app functionality(server) installed(integrated) into the recovery package(architecture) ... then scrcpy could be extended to recovery screen mirroring ?

**Comment by rom1v** [comment]
During recovery, I guess everything needed to run the server is not available (I think that zygote is not even started).

**Comment by aiamuzz** [comment]
> During recovery, I guess everything needed to run the server is not available (I think that zygote is not even started).

hmmmm ... ok ... would have been nice if it were possible though.

**Comment by aiamuzz** [comment]
> During recovery, I guess everything needed to run the server is not available (I think that zygote is not even started).

@rom1v ... these days the custom recoveries are much more than a simple collection of CLI functions ... If i remember right twrp recovery has a file manager which works like an app ... I guess a version bare minimum version of scrcpy server that is adapted to the limited recovery environment should not be far off ... given how technology's strides are nothing short of leaps and bounds !!!

**Comment by hacker1024** [comment]
> During recovery, I guess everything needed to run the server is not available (I think that zygote is not even started).

That's true, ART doesn't exist in recoveries. TWRP, however, provides root access via ADB. Would it be theoretically possible to write a native server that records the screen in a different way?

**Comment by giguhbo019jda** [comment]
Still interested in this feature even in some very limited way. TWRP gives adb root access, maybe there are still some ways to control the device even at very low fps? Right now there is an option only to use “adb pull /dev/graphics/fb0” and get a picture via ffmpeg and if the touch screen is alive, then use TWRP blindly. It is not even clear how to get just video stream in very low fps. Maybe someone has already found solutions?

**Comment by minsiam** [comment]
could you tell me about the "only option"? ("adb pull /dev/graphics/fb0")

**Comment by leao-nardo** [comment]
> could you tell me about the "only option"? ("adb pull /dev/graphics/fb0")

https://stackoverflow.com/questions/4654770/how-to-capture-the-screen-using-dev-graphics-fb0-android

found more info here . but this "I run adb pull /dev/graphics/fb0 fb0  got adb: error: remote object '/dev/graphics/fb0' does not exist" is same error i get tring in a normal phone ui , i will test in the one in recovery later
