### ISSUE TITLE
Huawei has achieved the same function. Is there any difference?

### ISSUE THREAD

**Issue by liaoqingmo** [Genymobile/scrcpy#716]
https://b23.tv/av63102276

**Comment by rom1v** [comment]
I have no idea. If you can test both, please tell us 😉

**Comment by WANASX** [comment]
@rom1v   bro scrcpy with my huawei keyboard donr work with pubg just work to go  and back and left and right but i cant fire or change aim

**Comment by floating-cat** [comment]
Currently I found two difference between scrcpy and Huawei:
1. Huawei can use desktop input method to type Chinese.
2. Current drag & drop in scrcpy would push file to /sdcard/ on the device, but Huawei use multi window drag and drop mechanism to copy text to EditView, send file to that app.
(like https://www.androidauthority.com/drag-and-drop-text-multi-window-android-n-679164/ and https://9to5google.com/2019/03/14/android-files-app-drag-and-drop-windows/)

**Comment by rom1v** [comment]
@floating-cat Thank you for your feedbacks.

> Huawei can use desktop input method to type Chinese.

OK. Definitely that's something missing in scrcpy. It requires to install an app on the device.
https://github.com/Genymobile/scrcpy/issues?q=is%3Aissue+is%3Aopen+label%3Aunicode

> Huawei use multi window drag and drop mechanism to copy text to EditView, send file to that app. (like https://www.androidauthority.com/drag-and-drop-text-multi-window-android-n-679164/ and https://9to5google.com/2019/03/14/android-files-app-drag-and-drop-windows/)

It seems it's internal to the device, so if you drag&drop from one window to the other with a Huawei device supporting this feature, it should work too.
