### ISSUE TITLE
AUR android-tools dependency

### ISSUE THREAD

**Issue by DanielMazurkiewicz** [Genymobile/scrcpy#718]
Would be nice if AUR installation would automatically install "android-tools" package

**Comment by rom1v** [comment]
https://aur.archlinux.org/packages/scrcpy/

> android-tools (android-sdk-platform-tools-dummy, android-tools-git, android-sdk-platform-tools) (optional) – required if adb is not already installed

I guess it is not installed automatically on purpose, for people who installed the Android SDK.

cc @nvllsvm

**Comment by DanielMazurkiewicz** [comment]
@rom1v oh, that is interesting, none of these were installed, had to install manually android tools

**Comment by nvllsvm** [comment]
@rom1v correct - it's an opt depend as I'm guessing most users already have adb installed from either the SDK Manager (me) or through the android-tools package.
