### ISSUE TITLE
adb push failed to execute

### ISSUE THREAD

**Issue by RiaanBurger** [Genymobile/scrcpy#723]
Using the snap:

```sh
scrcpy
```

```
INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
exec: Permission denied
ERROR: Failed to execute: [/home/riaan/.Android/Sdk/platform-tools/adb], [push], [/snap/scrcpy/145/usr/local/share/scrcpy/scrcpy-server.jar], [/data/local/tmp/scrcpy-server.jar]
ERROR: Could not execute "adb push"
```

Based on other issues I saw, some more troubleshooting info:

Device is listed:

```sh
adb devices
```

```
List of devices attached
192.168.1.68:5656       device
```

ADB version is 1.0.41:

```sh
/home/riaan/.Android/Sdk/platform-tools/adb --version
```

```
Android Debug Bridge version 1.0.41
Version 29.0.2-5738569
Installed as /home/riaan/.Android/Sdk/platform-tools/adb
```

ADB can push:

```sh
adb push /snap/scrcpy/145/usr/local/share/scrcpy/scrcpy-server.jar /data/local/tmp/scrcpy-server.jar
```

```
/snap/scrcpy/145/usr/local/share/scrcpy/scrcpy-server.jar: 1 file pushed. 1.8 MB/s (22546 bytes in 0.012s)
```

**Comment by rom1v** [comment]
cc @sisco311

**Comment by RiaanBurger** [comment]
Ah, got it. The snap uses an internal version of adb:

```sh
scrcpy.adb version
```

```sh
Android Debug Bridge version 1.0.39                                                                                     
Version 1:8.1.0+r23-5~18.04                                                                                             
Installed as /snap/scrcpy/145/usr/lib/android-sdk/platform-tools/adb
````

Run the snap-internal adb (it should kill the default one if it is already running):

```sh
scrcpy.adb devices
```

```
List of devices attached
adb server version (41) doesn't match this client (39); killing...
* daemon started successfully
```

Reconnect and authorise:

```sh
scrcpy.adb connect 192.168.1.68:5656
```

```
connected to 192.168.1.68:5656
```

Remember to authorise on the mobile device.

Now scrcpy works:

```sh
scrcpy
```

**Comment by cotfas** [comment]
Hello!
I have a similar problem:

`scrcpy -p 1234 -s HT5******`

scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
exec: Permission denied
2022-01-19 18:11:27.272 scrcpy[22827:1449496] ERROR: Failed to execute: [/Users/#####/Library/Android/sdk/platform-tools], [-s], [HT5******], [push], [/usr/local/Cellar/scrcpy/1.21/share/scrcpy/scrcpy-server], [/data/local/tmp/scrcpy-server.jar]
2022-01-19 18:11:27.273 scrcpy[22827:1449496] ERROR: Could not execute "adb push"
2022-01-19 18:11:27.412 scrcpy[22827:1449489] ERROR: Server connection failed


When trying:


```
cd /usr/local/Cellar/scrcpy/1.21/share/scrcpy/
ll


total 80
drwxr-xr-x  3 vlad.cotfas  admin     96 Nov 29 23:15 .
drwxr-xr-x  5 vlad.cotfas  admin    160 Nov 29 23:15 ..
-rw-r--r--  1 vlad.cotfas  admin  40067 Nov 29 23:15 scrcpy-server
```

```
USER_ONLY-MacBook-Pro scrcpy % adb shell ls -l /dala/local/tmp
adb: more than one device/emulator
USER_ONLY-MacBook-Pro scrcpy % adb shell ls -l /dala/local/tmp
ls: /dala/local/tmp: No such file or directory
USER_ONLY-MacBook-Pro scrcpy % adb shell ls -l /dala/local/tmp
ls: /dala/local/tmp: No such file or directory
USER_ONLY-MacBook-Pro scrcpy % adb shell ls -l /dala/
ls: /dala/: No such file or directory
```

```
USER_ONLY-MacBook-Pro scrcpy % adb shell ls -l /storage/emulated/0/
total 168...
drwxrwx--x 2 root sdcard_rw 4096 2018-09-22 20:24 Alarms
drwxrwx--x 5 root sdcard_rw 4096 2018-09-22 21:23 Android
drwxrwx--x 4 root sdcard_rw 4096 2019-01-14 21:14 DCIM
drwxrwx--x 2 root sdcard_rw 4096 2019-12-14 22:03 Download
drwxrwx--x 2 root sdcard_rw 4096 2018-09-22 20:24 Movies
.......
```

*The /data folder is not accessible by Xplore app as well, how can I change the TMP server path from android part to send the server to /storage/ folder?
Thank you!

**Comment by rom1v** [comment]
>ERROR: Failed to execute: [/Users/#####/Library/Android/sdk/platform-tools], [-s], [HT5******], [push], [/usr/local/Cellar/scrcpy/1.21/share/scrcpy/scrcpy-server], [/data/local/tmp/scrcpy-server.jar]

You set your `ADB` environment variable to a wrong value':

```bash
# wrong
export ADB=/Users/#####/Library/Android/sdk/platform-tools
# correcr
export ADB=/Users/#####/Library/Android/sdk/platform-tools/adb
```

**Comment by cotfas** [comment]
But does not have nothing to do with doing the ADB push command manually!

Check this:

```
USER_ONLY-MacBook-Pro scrcpy % adb shell ls -l /dala/local/tmp
adb: more than one device/emulator
USER_ONLY-MacBook-Pro scrcpy % adb shell ls -l /dala/local/tmp
ls: /dala/local/tmp: No such file or directory
USER_ONLY-MacBook-Pro scrcpy % adb shell ls -l /dala/local/tmp
ls: /dala/local/tmp: No such file or directory
USER_ONLY-MacBook-Pro scrcpy % adb shell ls -l /dala/
ls: /dala/: No such file or directory
```

and then this:


```
USER_ONLY-MacBook-Pro scrcpy % adb shell ls -l /storage/emulated/0/
total 168...
drwxrwx--x 2 root sdcard_rw 4096 2018-09-22 20:24 Alarms
drwxrwx--x 5 root sdcard_rw 4096 2018-09-22 21:23 Android
drwxrwx--x 4 root sdcard_rw 4096 2019-01-14 21:14 DCIM
drwxrwx--x 2 root sdcard_rw 4096 2019-12-14 22:03 Download
drwxrwx--x 2 root sdcard_rw 4096 2018-09-22 20:24 Movies
.......
```


Checked with XPLORE android APP on the device, I can not access any /data/ folder!! also /ROOT folder I can not access it, it stays in loading and nothing happens, I can only access /storage/emulated/0/ which is internal. So, how can we change the destination jar installation path from:

`ERROR: Failed to execute: [/Users/#####/Library/Android/sdk/platform-tools], [-s], [HT5******], [push], [/usr/local/Cellar/scrcpy/1.21/share/scrcpy/scrcpy-server], [/data/local/tmp/scrcpy-server.jar]`

To `/storage/emulated/0/`

**Comment by rom1v** [comment]
> ```
> USER_ONLY-MacBook-Pro scrcpy % adb shell ls -l /dala/local/tmp
> ls: /dala/local/tmp: No such file or directory
> USER_ONLY-MacBook-Pro scrcpy % adb shell ls -l /dala/
> ls: /dala/: No such file or directory
> ```

It's not `dala`, but `data`.

**Comment by cotfas** [comment]
Hmm, you were right, now I see in the LS, also push adb command worked and the jar is shown in the device. But why it keeps saying "exec: Permission denied" ? (it is the first time when it happened to me..)

**Comment by rom1v** [comment]
> But why it keeps saying "exec: Permission denied" ? (it is the first time when it happened to me..)

Post the whole output.

**Comment by cotfas** [comment]
It is the same output:


```
scrcpy -p 1234 -s HT5******

scrcpy 1.21 https://github.com/Genymobile/scrcpy
exec: Permission denied
2022-01-19 18:11:27.272 scrcpy[22827:1449496] ERROR: Failed to execute: [/Users/#####/Library/Android/sdk/platform-tools], [-s], [HT5******], [push], [/usr/local/Cellar/scrcpy/1.21/share/scrcpy/scrcpy-server], [/data/local/tmp/scrcpy-server.jar]
2022-01-19 18:11:27.273 scrcpy[22827:1449496] ERROR: Could not execute "adb push"
2022-01-19 18:11:27.412 scrcpy[22827:1449489] ERROR: Server connection failed
```

**Comment by cotfas** [comment]
and `which adb`

/usr/local/bin/adb

* think I installed with brew install adb tools or smt like that

**Comment by rom1v** [comment]
> It is the same output:

So it is the same answer/solution: https://github.com/Genymobile/scrcpy/issues/723#issuecomment-1017165855

**Comment by cotfas** [comment]
But why on other phone it worked..

**Comment by cotfas** [comment]
I also have in the PATH
echo $PATH

/Users/#####/Library/Android/sdk/platform-tools

**Comment by cotfas** [comment]
But if setting it up to:

/Users/#####/Library/Android/sdk/platform-tools/adb wouldn`t cause issues??

I know there you have to set only folders, and I might also need to use other cli from `platform-tools` when developing apps.

**Comment by rom1v** [comment]
The `PATH` environment variable contains folders where the system must search for executables.

`ADB` is an environment variable specifically used by _scrcpy_ to give use a specific full-path for `adb`. If it is not set, it just execs `adb` (which is searched in the `PATH` environment variable by the system).

In short, unset your `ADB` variable.

**Comment by cotfas** [comment]
It worked, but I am 100% sure there will be a bottle neck somewhere in the development part, as I have the feeling Android Studio will take the ADB from /usr/.. instead the one from platform-tools, but will see. Tnx

**Comment by rom1v** [comment]
The `ADB` environment variable is only used by scrcpy, not by Android Studio or others.

**Comment by cotfas** [comment]
Thank you! From my opinion is to show to the user a hit message when the error occurs to others (in the terminal, maybe link to this PR., but this is just a suggestion 😊).
