### ISSUE TITLE
Building on Raspberry Pi 3 (Buster) fails at "ninja"

### ISSUE THREAD

**Issue by Arakon** [Genymobile/scrcpy#727]
Hi.
The build instructions specifically say not to run ninja with sudo. However, when I try that, I only get:

ninja: error: opening build log: Permission denied

Are there any updated instructions?

**Comment by rom1v** [comment]
wmaybe because you initially run it with root.

Remove your builddir and retry as non-root.

**Comment by fjleon1980** [comment]
i got this to run on my rp4, it was a nice surprise

**Comment by Arakon** [comment]
> 
> 
> wmaybe because you initially run it with root.
> 
> Remove your builddir and retry as non-root.

I had initially tried that, and that won't even let me create the folder without using sudo.

**Comment by reversegear** [comment]
> 
> 
> i got this to run on my rp4, it was a nice surprise

you got hardware acceleration working on scrcpy with PI ?

**Comment by fjleon1980** [comment]
how would i know if i got hardware acceleration working?

**Comment by reversegear** [comment]
> 
> 
> how would i know if i got hardware acceleration working?

smooth display without much load on RPI CPU. 
temperature doesnt shootup like crazy
no choppy videos.
