### ISSUE TITLE
为什么scrcpy打开错误，而scrcpy-noconsole能正常打开

### ISSUE THREAD

**Issue by jxcmdds** [Genymobile/scrcpy#728]
这是打开scrcpy显示的内容
adb: error: cannot stat 'C:\Users\小李，小冀，小小冀\Desktop\scrcpy-win64-v1.\scrcpy-server.jar': No such file or directory
ERROR: "adb push" returned with value 1
Press any key to continue...
设备ID能看到，USB设置全部打开，scrcpy-noconsole一切正常，但因为打不开scrcpy，我设置无线连接也是错误的
adb: error: cannot stat 'C:\Users\小李，小冀，小小冀\Desktop\scrcpy-win64-v1.\scrcpy-server.jar': No such file or directory 
这一句的文件明明有的

**Comment by rom1v** [comment]
What happens when you execute manually:

    adb push "C:\Users\小李，小冀，小小冀\Desktop\scrcpy-win64-v1.\scrcpy-server.jar'"

I guess `adb` or Windows do not support "special" characters (in your username) well.

A workaround could be to use a relative path:

```bat
cd "C:\Users\小李，小冀，小小冀\Desktop\scrcpy-win64-v1."
set SCRCPY_SERVER_PATH=scrcpy-server.jar
scrcpy
```

**Comment by jxcmdds** [comment]
谢谢你  解决了
