### ISSUE TITLE
ADBKeyBoard may help to solve the unicode input related issues

### ISSUE THREAD

**Issue by Rapiz1** [Genymobile/scrcpy#729]
I have read some issues related to non-ASCII characters input like supporting non-English keyboard layout, Chinese input and so on.

One of the ideas that tried to solve the problem was to use the computer's input method, and due to something like `adb input text '世界你好'` not working, failed.

So, if we can directly send unicode string to the device,  we can solve the problem, right?
I did some searching on the Internet and have found this: [ADBKeyBoard](https://github.com/senzhk/ADBKeyBoard)
Here's the steps I think will work ( Sorry for my limited knowledge on Java and Andord programming):
1. Invoke the computer's input method and get the character the user want to input.
2. Use ADBKeyBoard to send it to the phone.

But there is also one drawback: This may destroy the gaming experience because the phone no longer receives the key event.

But this can be work around:
We can enable ADBKeyBoard when the Android input method is detected, or just provide an option to enable ADBKeyBoard.

**Comment by rom1v** [comment]
Ref: https://github.com/Genymobile/scrcpy/issues/431#issuecomment-471245573
