### ISSUE TITLE
No hotkey to turn screen back on

### ISSUE THREAD

**Issue by UnixRonin** [Genymobile/scrcpy#735]
There is a hotkey Ctrl+o in scrcpy to turn the screen off while keeping desktop mirroring active.  However, there is no hotkey to turn the screen back **ON**, should you need to do so (for instance in the case of some application which does not quite work properly with scrcpy), except by using Ctrl+p (power button), which then requires you to unlock the phone again.

Can Ctrl+o be changed to be a toggle, so that it turns the device screen off if on, and on if off?  Would this still force a device unlock, or only if the phone was locked by the user or left until it timed out and auto-locked?

**Comment by rom1v** [comment]
I first implemented a shortcut for this, but it was problematic: https://github.com/Genymobile/scrcpy/issues/175#issuecomment-498156112

So I removed it.

**Comment by UnixRonin** [comment]
Ah, I see.  I didn't find the older ticket.
Is there any other way to do it that doesn't start by locking the phone?

**Comment by rom1v** [comment]
I don't know any other way :(

**Comment by sjuxax** [comment]
The "screen on" function has worked well enough for me. There was one incident where the device got in a semi-broken state, but the feature is worth it for me the 99% of the time it works without incident. I have a branch at https://github.com/sjuxax/scrcpy/tree/screen-on that contains a reversion of the commit that took out the toggle if anyone's interested in building that.

If someone has ideas on a test case or more information about how to reliably reproduce/troubleshoot this, let me know and I'd be happy to fiddle around with pinning down the behavior and getting it upstream. Will also test myself if I can get it to break again.

**Comment by KeronCyst** [comment]
Off-topic out of curiosity: does this actually save any battery, or does the back light stay on despite [CTRL]+O being invoked?

**Comment by rom1v** [comment]
It should. I haven't done any measurement though.

**Comment by rom1v** [comment]
I reactivated Ctrl+Shift+o in v1.14.
