### ISSUE TITLE
BUG: opacity problem while casting with screen off on MIUI 10

### ISSUE THREAD

**Issue by deep5050** [Genymobile/scrcpy#737]
Notification shade opacity goes high while mirroring with (ctrl-O) screen off. 

![Screenshot (385)](https://user-images.githubusercontent.com/27947066/63240840-04d90280-c26f-11e9-97ea-c37f7f5b26e7.png)

while using Gmaps. :{
![Screenshot (387)](https://user-images.githubusercontent.com/27947066/63241150-38685c80-c270-11e9-8e94-d9d12844fd07.png)

**Comment by deep5050** [comment]
![Screenshot (387)](https://user-images.githubusercontent.com/27947066/63241058-e7f0ff00-c26f-11e9-807d-98d24b026009.png)

**Comment by rom1v** [comment]
Ref #1301 #1306

**Comment by rom1v** [comment]
Nothing scrcpy can do I guess, sorry :(
