### ISSUE TITLE
Srccpy over a vpn

### ISSUE THREAD

**Issue by Lucaacer** [Genymobile/scrcpy#738]
It's not an actual issue, I just want to report that, through zerotier vpn, I have been able to connect via wifi my pc and my phone (both connected to the vpn) over wifi.

Everything works smooth and such thing can be useful if the phone and the laptop/desktop are not in the same place and also when the phone is in your pocket or bag and you cannot read the ip address. You just have to adb connect to the vpn address of the phone on port 5555.

**Comment by llpj** [comment]
Doesn't the phone needs to be usb plugged first to enable adb over tcp ?

**Comment by Lucaacer** [comment]
Yes, to move from usb to tcpip, you have got to plug in the phone, but just once

**Comment by zulfi0** [comment]
sorry if my english bad :)
i tried with zerotier vpn and it does work perfectly, but it's only work if android use the same vpn (same id). my question is how to use scrcpy with other vpn like portmap ? if i forgot my phone at home and want to connect it with just portmap (like tun0) ip ?

**Comment by Kolya-gfx** [comment]
Do you think it will work through Radmin VPN? And do I understand correctly that this way you can connect your phone to your PC at any distance?

**Comment by rom1v** [comment]
Read SSH tunnel: https://github.com/Genymobile/scrcpy/blob/master/doc/tunnels.md
