### ISSUE TITLE
Make android device feel the application as second screen

### ISSUE THREAD

**Issue by MohamedElshafey** [Genymobile/scrcpy#740]
Question: How can i make my android device feel that it's mirroring so it can feel the screen attached like Mirroring by Smart View for example, that's because i want to use [Presentation](https://developer.android.com/reference/android/app/Presentation) to show something different on the second screen, is that possible ?

**Comment by tchangeme** [comment]
同样想知道是否支持

**Comment by gxj8885718** [comment]
plus one!

**Comment by rom1v** [comment]
IIUC, duplicate of #397?

**Comment by MohamedElshafey** [comment]
@rom1v yes it's the same issue
