### ISSUE TITLE
How to ensure scrcpy is always at -b2M -m800

### ISSUE THREAD

**Issue by mv0hra** [Genymobile/scrcpy#741]
How can I have scrcpy always be set at -b2M -m800 rather than to have manually do this in cmd?

**Comment by rom1v** [comment]
There is no config file.

Create a file with `.bat` extension (`scrcpy.bat`) containing:
```bat
scrcpy -b2M -m800
```

And double-click on that file.

**Comment by mv0hra** [comment]
> There is no config file.
> 
> Create a file with `.bat` extension (`scrcpy.bat`) containing:
> 
> ```batchfile
> scrcpy -b2M -m800
> ```
> 
> And double-click on that file.

Forgot about doing that as an option.
Thanks for this great tool.
