### ISSUE TITLE
No USB Debugging possibilities?

### ISSUE THREAD

**Issue by T3hFyrefly** [Genymobile/scrcpy#742]
A similar application for Samsung devices. SideSync is able to screenshare and be remote controlled without USB debugging being enabled, tested with my Note 9. I've also noticed that All my other devices LG G8 and Zenfone 3 require the USB mode set to charging, however the Note 9 is able to connect to scrcpy while in File Transfer mode. Switch from Charging to File Transfer mode while connected will terminate scrcpy on anyother device. My Note 9 can switch back n forth with out having to restart scrcpy. I've only tested this with the stock rom from each device. I'm curious as to whats different and how its interacting with the device that other companies who have also provided similar software like ASUS which also require USB debugging seem to be doing differently.

Obviously this isn't a real issue, but I believe it might be possible to get scrcpy to operate without USB debugging with either a custom rom or possibly a root application, assuming its something on the software end and not some fancy proprietary chip on the phones board. That would be a different project in its entirety probably but its something I think is worth looking into.

**Comment by cswl** [comment]
Persumaly SideSync is a system app with tons of system previleges and security?

A custom ROM or root solution defeats the purpose of no root required..

Afaik `adb` wont listen on remote ports.... I wonder if we can put a mirror in the phone itself

**Comment by rom1v** [comment]
Since they control both the ROM and the client, they probably added a special access for their software. If anyone have a solution to do this without USB debugging, please share :)
