### ISSUE TITLE
Meizu 15 not showing on laptop screen.

### ISSUE THREAD

**Issue by InstinctSnipes** [Genymobile/scrcpy#744]
Hello there,

whenever I do the command things it works successfully but the android screen ain't showing on my laptop screen... any fix to this??

Model: M881H
Device: Meizu 15
Android Version: 7.1.1
Scrcpy version: v1.10
ROM: Flyme 7.0.2.1G

Thank you.

**Comment by Lucaacer** [comment]
What is the output of

adb devices ?

**Comment by rom1v** [comment]
See #151

**Comment by InstinctSnipes** [comment]
Sorry but I'm no good at scripting/coding, I'm just a user of this thing...
Can someone show me how to fix this step by step or a video that I can watch?
I used the command adb shell screenrecord /sdcard/test.mp4
adb pull /sdcard/test.mp4 like what you said on #151 
I received a recording of my android screen even though there's nothing on my laptop screen.

![fix](https://user-images.githubusercontent.com/54466823/63644357-abc01180-c73b-11e9-9259-82b969a196e0.PNG)

**Comment by Lucaacer** [comment]
> Sorry but I'm no good at scripting/coding, I'm just a user of this thing...
> Can someone show me how to fix this step by step or a video that I can watch?
> I used the command adb shell screenrecord /sdcard/test.mp4
> adb pull /sdcard/test.mp4 like what you said on #151
> I received a recording of my android screen even though there's nothing on my laptop screen.
> 
> ![fix](https://user-images.githubusercontent.com/54466823/63644357-abc01180-c73b-11e9-9259-82b969a196e0.PNG)

From what I can understand, you could have a look at the settings of your meizu and disable night mode. I suppose it's the option that removes the blue light during after a certain hour. After reading the other posts, it looks that the issue is somehow related to night mode.

**Comment by rom1v** [comment]
Could you try this (on v1.10), please? https://github.com/Genymobile/scrcpy/issues/921#issuecomment-552102176

**Comment by rom1v** [comment]
Should have been fixed few releases ago.
