### ISSUE TITLE
能否支持坚果R1，三星，华为的大屏模式呢？

### ISSUE THREAD

**Issue by tchangeme** [Genymobile/scrcpy#745]
可以通过一线通接上一个HDMI的欺骗器，启动大屏模式后，在通过无线的方式或其他方式连接到锤子坚果的TNT或三星的DEX模式，那就太牛了。现在有太多人为了使用大屏模式，买了触控屏，但也有很多人喜欢大屏模式，比如TNT，但是已经有笔记本或PC了，如果能用这种方式解决，应该还是很有市场的。

**Comment by tchangeme** [comment]
期望，能够实现

**Comment by ZerOri** [comment]
开发者又看不懂中文 - -

**Comment by tchangeme** [comment]
翻译不好列

**Comment by Rapiz1** [comment]
把你的需求写成英语。
Write your issue in English.

**Comment by rom1v** [comment]
I don't understand the question (even with Google translate)… :/

**Comment by npes87184** [comment]
I guess that he means [samsung dex mode](https://en.m.wikipedia.org/wiki/Samsung_DeX).

**Comment by rom1v** [comment]
OK, thanks. IMO it would be a whole separate project.
