### ISSUE TITLE
Desktop shortcut for Linux

### ISSUE THREAD

**Issue by plwt** [Genymobile/scrcpy#748]
Hello

Great work with scrcpy, this really impressive software.

To make my life easier, I have written a desktop icon for Linux that allows a user to a) run scrcpy, 2) run scrcpy with touches showing, and 3) record footage from scrcpy - all without using the terminal.

Would there be any opposition to me submitting a pull request to edit the readme.md file to include a link to my shortcut for those that may find it useful?  (Edit would make clear that this is external to the amazing work you are doing).

(Never submitted a pull request before, so thought I get in touch beforehand!)

**Comment by pabloab** [comment]
Those three things seems much more than just a desktop icon. If you added features to a scrcpy fork, please send a pull request of the code. That's much better than changing Readme to external resources.

**Comment by yan12125** [comment]
The desktop icon part looks like the same feature request as #295. I guess recording a footage can be achieved with the new v4l2 feature in 1.18.

**Comment by rom1v** [comment]
> I guess recording a footage can be achieved with the new v4l2 feature in 1.18.

To record a file, it's better to use `scrcpy --record file.mp4` though: the timestamps are from the device, and no frame may be skipped.

**Comment by yan12125** [comment]
Awesome! Those additional actions can be added to the desktop file as `Desktop Action XXX` groups.
