### ISSUE TITLE
GUI for this tool

### ISSUE THREAD

**Issue by chitranjanbaghi** [Genymobile/scrcpy#749]
Please create a gui for this tool, so that it can be used easily, not all people are familar with cammand line, Please make it happen. it really deserve a graphical user interface.
here is someone created https://github.com/Tomotoes/scrcpy-gui but it is only for windows, Please add on for linux.

**Comment by rom1v** [comment]
> Please create a gui for this tool

Adding a "real" GUI would probably require to use a UI framework other than SDL (I would still keep SDL since it's very fast). See https://github.com/Genymobile/scrcpy/issues/707#issuecomment-520941669

> A (long-term) path I have in mind […] is:
> 1. refactor to expose the "engine" as a lib (libscrcpy)
> 2. make the (current) SDL app use the lib (I want to keep the SDL version because it is very light)
> 3. implement another UI in Qt, also using libscrcpy, to get a UI similar to #612

> here is someone created https://github.com/Tomotoes/scrcpy-gui

Great :+1:

> it is only for windows

Hmm, no: https://github.com/Tomotoes/scrcpy-gui#requirements

**Comment by srevinsaju** [comment]
> Adding a "real" GUI would probably require to use a UI framework other than SDL (I would still keep SDL since it's very fast). See #707 (comment)

How is the new [guiscrcpy](https://github.com/srevinsaju/guiscrcpy), a completely independent module with direct android controls. 
It looks like this, so no intervention with the SDL layer 
![screen using guiscrcpy](https://user-images.githubusercontent.com/48695438/63826445-a6470f00-c967-11e9-8463-a68faf19223c.png)

**Comment by chitranjanbaghi** [comment]
> > Adding a "real" GUI would probably require to use a UI framework other than SDL (I would still keep SDL since it's very fast). See #707 (comment)
> 
> How is the new [guiscrcpy](https://github.com/srevinsaju/guiscrcpy), a completely independent module with direct android controls.
> It looks like this, so no intervention with the SDL layer
> ![screen using guiscrcpy](https://user-images.githubusercontent.com/48695438/63826445-a6470f00-c967-11e9-8463-a68faf19223c.png)

wow, this is amazing, but after downloading the guiscrpy-1.10-27082019-linux I am unable to do anything when I double click it doesn't run and ask me to choose some program to open this file.

I am running linux mint, what am I missing, Please help.

**Comment by srevinsaju** [comment]
@chitranjanbaghi, thanks for using guiscrcpy. you have to open a terminal at this current directory, and follow the below commands,

 `chmod +x guiscrcpy* `
`.\guiscrcpy*`

Thanks for this issue, will update the README.MD to make it more intuitive

**Comment by kittydoor** [comment]
A mention of guiscrcpy in the README.md might be a good idea. It took me a bit of digging through issues to find this thread, and information like this rots over time so it's always good to have some quick links from the main project spanning out :)
