### ISSUE TITLE
Use scrcpy to utilize Android devices as external USB monitors

### ISSUE THREAD

**Issue by gitguys** [Genymobile/scrcpy#75]
The performance of scrcpy is very fast and it works with just about every Android device I throw at it whether it's connected on Mac or PC.

Would it be possible to utliize scrcpy to allow Android devices to act as an external USB monitor for Mac and PC computers?  Other apps that attempt to do this often don't work.  This would be a great tool.

**Comment by rom1v** [comment]
> Android devices to act as an external USB monitor for Mac and PC computers

So that you may use your Android device as a secondary screen? It is a whole different project (the video stream and events would be in the opposite direction compared to _scrcpy_).

**Comment by gitguys** [comment]
> would be in the opposite direction compared to scrcpy

Yes, it would reverse the video stream and events.  Could some of the code/concepts from scrcpy be utilized to do this or would someone have to start from scratch?

**Comment by rom1v** [comment]
> Could some of the code/concepts from scrcpy be utilized to do this 

Concepts, probably: encode the video, stream it, decode on the other side.
Code, probably less: the device and computer sides of the application use different API and languages.
