### ISSUE TITLE
--max-size option give wrong resolution

### ISSUE THREAD

**Issue by wantanmee** [Genymobile/scrcpy#752]
PC: win10 with scrcpy 1.10
Phone: Samsung Galaxy Note 8

when I start scrcpy without `--max-size` option, output is "INFO: Initial texture: 1440\*2960". However, if I start using `scrcpy -m 740`, output is "INFO: Initial texture: 360\*736"

aspect-ratio is changed

**Comment by rom1v** [comment]
That's expected. It rounds to a multiple of 8, because encoders do not support non-multiples of 8.
