### ISSUE TITLE
scrcpy without video

### ISSUE THREAD

**Issue by 104m4tt0** [Genymobile/scrcpy#753]
Hi,
Thanks for your project because it's wonderfoul and solve a lot of problem ..
i would like to know if is it possible to exclude video virtualization and keep the control on android device.
Thanks for your patience.

bye bye 

antonio

**Comment by rom1v** [comment]
Technically (i.e. if you modify the code), it's possible, but in _scrcpy_, if you disable video, you can't click to control the device (or press any key because there is no window to intercept them).

**Comment by 104m4tt0** [comment]
So isn't possible to ctrl input on android display without a windows display.
I would consider to modify the code to make like an input ctrl remotely, exactly reverse mode of android pc ctrl app.
Do you think will be possible ?

**Comment by 104m4tt0** [comment]
I mean like deskdock .. i don't know how but is possibe to share keyboard and mouse and clipboard without mirroring.

**Comment by herrenP** [comment]
> So isn't possible to ctrl input on android display without a windows display.
> I would consider to modify the code to make like an input ctrl remotely, exactly reverse mode of android pc ctrl app.
> Do you think will be possible ?

This is possible directly using ADB but maybe you already knew that.

```
•100% ➜ adb shell input 
Usage: input [<source>] <command> [<arg>...]

The sources are: 
      dpad
      keyboard
      mouse
      touchpad
      gamepad
      touchnavigation
      joystick
      touchscreen
      stylus
      trackball

The commands and default sources are:
      text <string> (Default: touchscreen)
      keyevent [--longpress] <key code number or name> ... (Default: keyboard)
      tap <x> <y> (Default: touchscreen)
      swipe <x1> <y1> <x2> <y2> [duration(ms)] (Default: touchscreen)
      draganddrop <x1> <y1> <x2> <y2> [duration(ms)] (Default: touchscreen)
      press (Default: trackball)
      roll <dx> <dy> (Default: trackball)

```

**Comment by rom1v** [comment]
@104m4tt0 https://github.com/Genymobile/scrcpy/issues/87#issuecomment-378775565
@herrenP it would be slow (#231)

**Comment by herrenP** [comment]
> @104m4tt0 [#87 (comment)](https://github.com/Genymobile/scrcpy/issues/87#issuecomment-378775565)
> @herrenP it would be slow (#231)

Ah, cool stuff! Nice thinking. :)
