### ISSUE TITLE
Why not use scrcpy approach to turn phone into graphic tablet?

### ISSUE THREAD

**Issue by Plandercozeron** [Genymobile/scrcpy#754]
Just a thought. Maybe someone could make it. Or this already exists...
You use phone as input device with scrcpy approach of using *.jar
On PC you move your window with "working area" which has fixed aspect ratio equal to phone's and send touch events there as mouse button clicks. And you can change size of that window.
There're apps for taking handwritten notes but you have to install APK, then you have to install client (OS limited, of course).

**Comment by rom1v** [comment]
> You use phone as input device with scrcpy approach of using *.jar

I am not sure you can capture device input (it's the reverse of what scrcpy does, injecting input events).

**Comment by tchangeme** [comment]
非常希望能够实现这个功能。现在很多安卓手机都有桌面模式，要是可以启用桌面模式就很棒了。
