### ISSUE TITLE
Checkrsum Error?!

### ISSUE THREAD

**Issue by Badminecraftdevelopment** [Genymobile/scrcpy#755]
whaat does this mean 
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: 3b1634fa348c0f0064e43f3fb673e30a5e46f2b51cd6cd0d4a0cbf326e71c90e
  Actual: 34480b13120e2167060795060b6738c26622c341498cf6303b17b143642b14cd
 Archive: /Users/Root./Library/Caches/Homebrew/downloads/0c113ab0098bc4c3f2e8f410741b6104f2928fe63eb38cf98f8dcc3362f02ac4--ef80617d1e17e0878a909baad62a75ba265c0e00.patch
To retry an incomplete download, remove the file above.
and as it says i deleted the file and again checksum error

**Comment by rom1v** [comment]
Some related homebrew issue: https://github.com/Homebrew/brew/issues/3419
