### ISSUE TITLE
NO render drive

### ISSUE THREAD

**Issue by Badminecraftdevelopment** [Genymobile/scrcpy#758]
Im running a VM Win 7 x86 lite version and it say it couldnt find render driver

**Comment by npes87184** [comment]
Please provide more information.

For example:

* Which hypervisor used?
* What setting about virtual machine?

Also, there are some discussion about virtual machine in #441 .

**Comment by Badminecraftdevelopment** [comment]
hypervisor = ??
setttings pretty much default exept a update that allows 2.0 usb and 3.0

**Comment by npes87184** [comment]
Hypervisor, for example, QEMU, virtualbox, etc.

**Comment by d5d** [comment]
目前用群晖VMM虚拟win7 32位，手机连接电脑正常，找不到渲染驱动。

**Comment by pbt39ppc** [comment]
esxi vm, win7x64_pro

`
C:\Users\admin\Downloads\scrcpy-win64-v1.12.1>scrcpy
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
C:\Users\admin\Downloads\scrcpy-win64-...shed. 0.5 MB/s (26202 bytes in 0.050s)
CRITICAL: Could not create renderer: Couldn't find matching render driver
Press any key to continue...

`
