### ISSUE TITLE
scrcpy not working

### ISSUE THREAD

**Issue by DanieL64bits** [Genymobile/scrcpy#759]
hi! I have one problem with scrcpy!!! 
then I start scrcpy it shows me this error
 
https://imgur.com/btClPfs

I added the adb to path and nothing happend!
plase help!!

**Comment by srevinsaju** [comment]
Did you try adding an ADB.exe and its associated dlls to the scrcpy path. You can download platformtools from google and extract it to, where scrcpy executable is located

**Comment by rom1v** [comment]
Unset your `ADB` environment variable (or set it to the `adb.exe` executable, not folder). See https://github.com/Genymobile/scrcpy/issues/769#issuecomment-533495032
