### ISSUE TITLE
keep display off -S command now works, but, on wake up, device screen resumes playback

### ISSUE THREAD

**Issue by srevinsaju** [Genymobile/scrcpy#760]
I used the turn display off function, now it works correctly on my phone, only problem is that, on device wake up after sleep, The device screen starts woking again.

**Comment by rom1v** [comment]
See #735

**Comment by srevinsaju** [comment]
Can we add adb shell svc power .. functionality. I saw it in one of the stackoverflow questions, and in one of the issues.
I can easily implement it in guiscrcpy by starting a subprocess in Python, but I checked your code and I thought of adding a pull request, but seems like I have no idea of C. I don't even know how to compile it..

**Comment by rom1v** [comment]
> Can we add adb shell svc power 

https://github.com/Genymobile/scrcpy/issues/631#issuecomment-622621215
