### ISSUE TITLE
Newbie on Mac -  help with installation please

### ISSUE THREAD

**Issue by amaddocks** [Genymobile/scrcpy#766]
I had this running on my PC no problems - great app. But I'm a newbie to Mac and having trouble completing the install as I get this error: -bash: brew: command not found

**Comment by msabwat** [comment]
Hi, 

Please follow the instructions in this link :
https://brew.sh/

**Comment by amaddocks** [comment]
Thanks - I followed the second prompt in the mac terminal then it is asking
for password?
I don't have a password for admin on my mac.

**Comment by msabwat** [comment]
This is not recommended but you can follow [this](https://github.com/Homebrew/brew/blob/master/docs/Installation.md#untar-anywhere) procedure.

**Comment by amaddocks** [comment]
Thanks for the help and suggestions. I will look into the password issue
first and see if I can resolve that way and try your suggestion if the
first doesn't work.

**Comment by amaddocks** [comment]
I got the password issue resolved - terminal doesn't like no password which
is how I had it set before so it's all successfully installed and running a
dream. Thanks for your help.
