### ISSUE TITLE
Adb push error

### ISSUE THREAD

**Issue by bluminbu** [Genymobile/scrcpy#769]
INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: no devices/emulators found
ERROR: "adb push" returned with value 1
Press any key to continue... this keeps happening i do not know how to fix it

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#on-windows-my-device-is-not-detected

**Comment by Skyyblaze** [comment]
I have the same issue. I have ADB and the platform-tools set up separately from scrcpy with a PATH variable in Windows and ADB devices in a CMD detects my phone just fine but scrcpy
gives me the same push error.

I can see it tries to use my native PATH set adb.exe but it still fails.

**Comment by rom1v** [comment]
@Skyyblaze In _scrcpy_ you get the error `adb: error: failed to get feature set: no devices/emulators found`?

**Comment by Skyyblaze** [comment]
> 
> 
> @Skyyblaze In _scrcpy_ you get the error:
> 
> ```
> adb: error: failed to get feature set: no devices/emulators found
> ```
> 
> ?

No, my error is as follows:

`INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
ERROR: Failed to execute: [C:\Android\platform-tools], [push], ["D:\Android\scrcpy-win64\scrcpy-server.jar"], ["/data/local/tmp/scrcpy-server.jar"]
ERROR: Could not execute "adb push"
Press any key to continue...`

The paths are correct, I have ADB installed in C:\Android\platform-tools and ADB is running.

**Comment by rom1v** [comment]
You set `SCRCPY_SERVER_PATH` incorrectly. Either unset it (it should provide the correct behavior, otherwise please report an error), or set it to `C:\Android\platform-tools\adb.exe`.

**Comment by Skyyblaze** [comment]
> 
> 
> You set `SCRCPY_SERVER_PATH` incorrectly. Either unset it (it should provide the correct behavior, otherwise please report an error), or set it to `C:\Android\platform-tools\adb.exe`.

I feel I'm missing something obvious. Where is SCRCPY_SERVER_PATH set? I don't see it in my Windows variables.

**Comment by rom1v** [comment]
> I don't see it in my Windows variables.

What is the result of:
```dos
echo %SCRCPY_SERVER_PATH%
```
?

**Comment by Skyyblaze** [comment]
> 
> 
> > I don't see it in my Windows variables.
> 
> What is the result of:
> 
> ```
> echo %SCRCPY_SERVER_PATH%
> ```
> 
> ?

That's the result:

`%SCRCPY_SERVER_PATH%`

**Comment by rom1v** [comment]
@inzamamraja Is your device Android >= 5?

**Comment by inzamamraja** [comment]
im tring to test 4.4

**Comment by inzamamraja** [comment]
Its working on other Android version but not Android=> 4.4.4

**Comment by rom1v** [comment]
Yes, that's expected (cf README).

**Comment by inzamamraja** [comment]
so it will not work for 4.4.4 ???

**Comment by rom1v** [comment]
No, it will not work. More details: https://github.com/Genymobile/scrcpy/issues/98#issuecomment-440940470

**Comment by Skyyblaze** [comment]
> 
> 
> @Skyyblaze Sorry, it's `ADB`, not `SCRCPY_SERVER_PATH`, which is incorrectly set.

Sorry for the late reply, I don't visit Github often and I don't get any notifications so it's easy to forget.

`echo %ADB%`

returns:

`C:\Android\platform-tools`

which is where my adb.exe is located.

**Comment by rom1v** [comment]
This is the problem: set `ADB` to `C:\Android\platform-tools\adb.exe` instead of `C:\Android\platform-tools` (it must contain the path to the executable).

**Comment by Skyyblaze** [comment]
> 
> 
> This is the problem: set `ADB` to `C:\Android\platform-tools\adb.exe` instead of `C:\Android\platform-tools` (it must contain the path to the executable).

Wow thanks for this, this was a classic newbie mistake on my end, I did this and everything works beautifully now! I never thought anything might be wrong with my variable as all ADB commands I tried manually always worked without the executable being listed. The more you know!

**Comment by rom1v** [comment]
> I never thought anything might be wrong with my variable

Yeah, if it is set, scrcpy use its value as the executable path:
https://github.com/Genymobile/scrcpy/blob/ffdbf5990ba82fa206248b4a411442a6885dbcca/app/src/command.c#L14-L22
