### ISSUE TITLE
Any way to reduce latency?

### ISSUE THREAD

**Issue by AqyxHD** [Genymobile/scrcpy#77]
The Latency is really good. Would it be even smaller if i use a high quality USB Cable instead of my 8 year old Samsung Galaxy S1 Cable? I want to use it for Gaming (every millisecond could help)

**Comment by rom1v** [comment]
I don't think so (but it is just an opinion). The latency is mainly due to the video encoding/decoding.

**Comment by AqyxHD** [comment]
Ok then. Too bad my Redmi Note 3 Pro doesnt support HDMI/MHL

**Comment by AqyxHD** [comment]
> The latency is mainly due to the video encoding/decoding.
Insnt there any way to output a raw Video file then?

**Comment by rom1v** [comment]
> Insnt there any way to output a raw Video file then?

A raw H.264 video file would not be very helpful, since the framerate is not constant.

But yes, it's possible (without _scrcpy_):

```bash
adb exec-out screenrecord --output-format=h264 - > file.h264
```

Or you can record to an mp4:

```bash
adb shell screenrecord /sdcard/file.mp4
adb pull /sdcard/file.mp4
```

**Comment by AqyxHD** [comment]
Thank you

**Comment by AqyxHD** [comment]
When i do adb exec-out screenrecord --output-format=h264 - > file.h264 i cant see my Phone screen on my pc

**Comment by rom1v** [comment]
@AqyxHD Yes, that is expected: it saves a raw file to `file.h264` (it's independent of _scrcpy_).

Scrcpy does not support recording to file.
