### ISSUE TITLE
手机作为外接显示器

### ISSUE THREAD

**Issue by Qiyue0726** [Genymobile/scrcpy#770]
类似于SpaceDesk那样，将手机作为第二屏幕，可以做点别的事

**Comment by Eclocksss** [comment]
English plz

**Comment by Rapiz1** [comment]
Translation: 
Feature request:
Simliar to Spacedesk, make the phone act as a secondary monitor.

I think this is off topic.

**Comment by BEEEEEG-YOSHI** [comment]
why isn't this closed
