### ISSUE TITLE
can i play the audio of my phone on my computer ?

### ISSUE THREAD

**Issue by Eclocksss** [Genymobile/scrcpy#771]
and i hope to improve the sharpness of the video so that the letter are more able to read

**Comment by Eclocksss** [comment]
And it will be better if could set the windows on the toppest

**Comment by npes87184** [comment]
Forward audio please refer #14 .

And there is an option called `--always-on-top` so that `scrcpy` can always be above others.

**Comment by Eclocksss** [comment]
> Forward audio please refer #14 .
> 
> And there is an option called `--always-on-top` so that `scrcpy` can always be above others.

![image](https://user-images.githubusercontent.com/54049075/64259079-f8d18e00-cf5a-11e9-9986-edc9d66e3c91.png)
sorry i don't know whats wrong,the shortcut works but command didn't

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/issues/385#issuecomment-451895997

**Comment by Eclocksss** [comment]
> [#385 (comment)](https://github.com/Genymobile/scrcpy/issues/385#issuecomment-451895997)

thank you so much,now i got it.
