### ISSUE TITLE
[Q] Unable to Connect to Scrcpy Wirelessly

### ISSUE THREAD

**Issue by UchihaKite** [Genymobile/scrcpy#772]
![wirelessly1](https://user-images.githubusercontent.com/20590483/64073278-5a8ab300-cc50-11e9-91e6-935595b18a9d.JPG)

Hello! First of all, I wanted to thank everyone for all of your hard work. This is a fantastic program, and has helped me out a lot! However, I tried to use Scrcpy Wirelessly, and as you can see in the attached image, it didn't work out as I would have liked.

I am trying to figure out the reason for this, I followed the steps one by one, and in the cmd prompt it said I was connected, but once I unplugged my phone and tried using Scrcpy, the attached image is what I got. Any and all help would be fantastic :D

**Comment by rom1v** [comment]
>    adb server version (32) doesn't match this client (41); killing...

Because you used an old `adb` to execute `adb connect`, etc. Use the one provided with _scrcpy_.

_(please copy-paste console text instead of screenshot, so that it can be searched easily)_

**Comment by UchihaKite** [comment]
Oh duh! That was silly of me lol I really appreciate you taking the time to help me out, man! Everything is working perfectly now, I'm surprised at how smoothly this runs! Thanks again!

I'll remember in the future to just copy-paste console text in the future, I apologize for that.
