### ISSUE TITLE
Failed to execute "adb push"

### ISSUE THREAD

**Issue by Lezon** [Genymobile/scrcpy#773]
```
* ERROR: Failed to execute: [D:\Scrcpy\scrcpy-win64-v1.10], [push], ["D:\Scrcpy\scrcpy-win64-v1.10\scrcpy-server.jar"], ["/data/local/tmp/scrcpy-server.jar"]
* ERROR: Could not execute "adb push"
```

**Comment by rom1v** [comment]
You probably set the environment variable `ADB` to `D:\Scrcpy\scrcpy-win64-v1.10`.

You probably wanted to set it to `D:\Scrcpy\scrcpy-win64-v1.10\adb.exe`.

**Comment by Lezon** [comment]
> You probably set the environment variable `ADB` to `D:\Scrcpy\scrcpy-win64-v1.10`.
> 
> You probably wanted to set it to `D:\Scrcpy\scrcpy-win64-v1.10\adb.exe`.

Thank you!
^_^

**Comment by java-code-former** [comment]
> You probably set the environment variable `ADB` to `D:\Scrcpy\scrcpy-win64-v1.10`.
> 
> You probably wanted to set it to `D:\Scrcpy\scrcpy-win64-v1.10\adb.exe`.

ths,useful~
