### ISSUE TITLE
Scrcpy closes in Mac Os 10.14.6

### ISSUE THREAD

**Issue by MarcoAntonioPass** [Genymobile/scrcpy#774]
I have android 9 and running "scrcpy" returns this: 
```
2019-09-01 14:35:06.534 scrcpy[8216:237862] INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.10/share/scrcpy/scrcpy-server.jar: 1 file pushed. 0.8 MB/s (22662 bytes in 0.027s)
2019-09-01 14:35:07.224 scrcpy[8216:237862] INFO: Initial texture: 1080x2160
```

**Comment by rom1v** [comment]
Do you have a Meizu device? #744 #151

**Comment by MarcoAntonioPass** [comment]
> Do you have a Meizu device? #744 #151

No, i have Moto G6 Plus

**Comment by rom1v** [comment]
Are there any relevant logs in the output of `adb logcat`?

You say it closes, this means that it works, and after sole delay it closes automatically, right?

**Comment by MarcoAntonioPass** [comment]
> ¿Hay registros relevantes en la salida de `adb logcat`?
> 
> Dices que se cierra, esto significa que funciona, y después de algún retraso se cierra automáticamente, ¿verdad

Yes, it closes shortly after executing "scrcpy".

`adb logcat` shows many many lines. I think none that attracts attention. Should I look for a specific line?

**Comment by rom1v** [comment]
> Yes, it closes shortly after executing "scrcpy".

Try with another USB cable. See #281 and #283.

**Comment by MarcoAntonioPass** [comment]
> > Sí, se cierra poco después de ejecutar "scrcpy".
> 
> Intente con otro cable USB. Ver [# 281](https://github.com/Genymobile/scrcpy/issues/281) y [# 283](https://github.com/Genymobile/scrcpy/issues/283) .

It works, but with a low resolution, maybe it is the low quality cable?
