### ISSUE TITLE
scrcpy working fine in landscape but not in portrait mode

### ISSUE THREAD

**Issue by rickx** [Genymobile/scrcpy#777]
Hi and thanks for this wonderful project.
My issue is with some devices, not all. Of course the ones where I need it to work...
I can move the device to make it rotate or start already rotated - that makes no difference. In landscape it shows like this:

![2019-09-02 15_24_12-TOUCHZONE_V3](https://user-images.githubusercontent.com/1685369/64117700-25887880-cd96-11e9-97c5-2d058ee873b9.png)

while in portrait I get this

![2019-09-02 15_24_42-TOUCHZONE_V3](https://user-images.githubusercontent.com/1685369/64117722-320cd100-cd96-11e9-8582-882d76b95eea.png)

As you can see some parts of the screen come through but you can't really read or see anything in detail. Clicking works fine.

Logcat does not show any noticeable difference between working and not working streams. But here's the beginning of the one not working:

```
09-02 12:41:24.778 13968 13999 I OMXClient: Using client-side OMX mux.
09-02 12:41:24.787   239  1040 E ROCKCHIP_VIDEO_ENC: ===========Rockchip_OMX_ComponentConstructor
09-02 12:41:24.797 13968 13999 W ACodec  : do not know color format 0x7f000789 = 2130708361
09-02 12:41:24.800 13968 13999 I ACodec  : setupVideoEncoder succeeded
09-02 12:41:24.801 13968 13999 W ACodec  : do not know color format 0x7f000789 = 2130708361
09-02 12:41:24.806   239   239 E OMXNodeInstance: getParameter(4b:rk._encoder.avc, ParamConsumerUsageBits(0x6f800004)) ERROR: UnsupportedIndex(0x8000101a)
09-02 12:41:24.835   239 14000 E ROCKCHIP_VIDEO_ENC: EncParam.framerate  = 60 outPort->sPortParam.format.video.xFramerate = 3932160 8000000
09-02 12:41:24.835   239 14000 E ROCKCHIP_VIDEO_ENC: ConvertOmxAvcLevelToAvcSpecLevel: 512
09-02 12:41:24.835   239 14000 D pv_avcenc_api: cml->intraPicRate 600 bitPerSecond 8000000
09-02 12:41:24.837   239 14000 D pv_avcenc_api: init intraPeriodCnt 600
09-02 12:41:24.838   239 14000 E ROCKCHIP_VIDEO_ENC: ===========Rkvpu_OMX_BufferProcess_Create
09-02 12:41:24.839   239 14004 E ROCKCHIP_VIDEO_ENC: ===========Rkvpu_OMX_InputProcessThread
09-02 12:41:24.852   239 14004 E ROCKCHIP_VIDEO_ENC: ==================:Rkvpu_SendInputData
09-02 12:41:24.853   239 14004 E ROCKCHIP_VIDEO_ENC: DAWN:================ success open pvrsrvkm
09-02 12:41:24.853   239 14004 E ROCKCHIP_VIDEO_ENC: Rkvpu_ProcessStoreMetaData: pVIdeoEnc-> bRgb2yuvFlag == OMX_TRUE
09-02 12:41:24.853   239 14004 E ROCKCHIP_VIDEO_ENC: video.nFrameWidth 600 video.nFrameHeight 1024
09-02 12:41:24.856   239 14004 D         : drift 0 bitrate 8000000 virtualbitcnt 0 realbitcnt 0
09-02 12:41:24.952   239 14004 E ROCKCHIP_VIDEO_ENC: ==================:Rkvpu_SendInputData
09-02 12:41:24.952   239 14004 E ROCKCHIP_VIDEO_ENC: Rkvpu_ProcessStoreMetaData: pVIdeoEnc-> bRgb2yuvFlag == OMX_TRUE
09-02 12:41:24.952   239 14004 E ROCKCHIP_VIDEO_ENC: video.nFrameWidth 600 video.nFrameHeight 1024
09-02 12:41:24.955   239 14004 D         : drift 0 bitrate 8000000 virtualbitcnt 133333 realbitcnt 449424
```

This is an Android 6 device. On my Android 9 smartphone it works without any issues in any orientation. I also tried to go back (from v.1.10) to version 1.5 but they all showed the same behaviour.

Any idea? Or workaround?

**Comment by rom1v** [comment]
Looks like #55

If you record in portrait mode with `adb screenrecord`:

    adb screenrecord /sdcard/file.mp4
    adb pull /sdcard/file.mp4

Does it work?

**Comment by rickx** [comment]
hmm I was sure it would work. Actually it doesn't. What does that mean?

**Comment by rom1v** [comment]
Probably a hardware encoder bug.

Maybe you could check if there is another one available: https://github.com/Genymobile/scrcpy/issues/666#issuecomment-519886178

Or maybe the bug is not triggered with a lower definition?

    scrcpy -m 800

**Comment by rickx** [comment]
I'll check the encoder thing. I already tried reducing everything with parameters. Thanks

**Comment by rickx** [comment]
Just to let you know and in case someone else has something similar: reducing to -m600 was the solution here. Even -m800 which I'd tested before was to much.  Thanks again. You can close (or maybe I can...)
