### ISSUE TITLE
Is it possible to support Chinese input method

### ISSUE THREAD

**Issue by mybu** [Genymobile/scrcpy#778]
Is it possible to support Chinese input method。

**Comment by lpful** [comment]
@mybu You may try ARDC [https://www.cnblogs.com/we-hjb/p/9220084.html](url)

**Comment by lpful** [comment]
![ARDC中文输入法](https://user-images.githubusercontent.com/50052327/65381516-ab5c6b80-dd25-11e9-83ab-c1cd4f07c3ae.gif)

**Comment by rom1v** [comment]
Duplicate of #37 (and many others)

**Comment by rom1v** [comment]
Please test #1426 (works on Android >= 7).
