### ISSUE TITLE
"Aborted" error while running scrcpy.exe with a custom build

### ISSUE THREAD

**Issue by anuragpattanayak3** [Genymobile/scrcpy#780]
INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy> C:\Users\tgt109\Desktop\fbsfbs\scrcpy\x\server\: 1 file pushed. 0.2 MB/s (22538 bytes in 0.090s) 
Aborted

This is the exact command line result I am getting when I try to execute the .exe file.

**Comment by anuragpattanayak3** [comment]
I set the SCRCPY_SERVER_PATH environment variable as a solution to this but it didn't work.

**Comment by rom1v** [comment]
> `C:\Users\tgt109\Desktop\fbsfbs\scrcpy\x\server'

What is `server` here?

> I set the SCRCPY_SERVER_PATH environment variable as a solution to this but it didn't work.

Please unset it and paste the error message you get.

`Aborted` is on the device. What is its version of Android?

What is the result:

    adb shell ls -l /data/local/tmp

?

**Comment by anuragpattanayak3** [comment]
Actually i was using a custom build. I removed the scrcpy_server_path from environment variable and its working now

**Comment by anuragpattanayak3** [comment]
thanks for the response.
