### ISSUE TITLE
Accents error

### ISSUE THREAD

**Issue by agsola** [Genymobile/scrcpy#781]
According to this post: https://blog.rom1v.com/2018/03/introducing-scrcpy/#handle-accented-characters I would expect accents to work. However, when I introduce an accent through the keyboard, I first press the accent and then the vowel, but when it shows in the mobile is shows both the vowel without the accent and then with the accent, so if I try to insert for example á, it shows "aá". 

Could it be fixed?

**Comment by rom1v** [comment]
> Could it be fixed?

Yes, with an option to select some "input mode": https://github.com/Genymobile/scrcpy/issues/650#issuecomment-512800386

(I'm closing as duplicate of #650)

**Comment by rom1v** [comment]
Please test #1426 (works on Android >= 7).
