### ISSUE TITLE
Special (Accent) characters missing

### ISSUE THREAD

**Issue by TigerMarton** [Genymobile/scrcpy#782]
Hy rom1v!

First of all, you are a special man! I love your program :D
I followed the progression of the application for a long time, and I seen that you have started to add support for special characters too.
But there are still some missing.

Űű : WARN: Could not inject char u+170, u+171
Őő : WARN: Could not inject char u+150, u+151

Is it possible to add these too? 

Thanks!

**Comment by rom1v** [comment]
Other accented characters don't work: https://github.com/Genymobile/scrcpy/pull/194

It will require to implement input events via a separate IME: https://github.com/Genymobile/scrcpy/issues/431#issuecomment-471245573

**Comment by TigerMarton** [comment]
Okay, thanks for the quick reply.

Have a great day!

**Comment by rom1v** [comment]
Please test #1426 (works on Android >= 7).
