### ISSUE TITLE
Is any quickly way to pass utf8 text from computer to android ?

### ISSUE THREAD

**Issue by angelmic** [Genymobile/scrcpy#786]
Hi

I need to do hundred times paste utf8 text to my android device. Is any way to speed up current way: to `Ctrl` + `Shift` + `v` to put text into android's clipboard then do paste.

**Comment by Plandercozeron** [comment]
Try sending 'Paste' event with ADB (Android 7.0+)
`adb shell input keyevent 279`

or just send whole text with
`adb shell input "your_text"`

**Comment by rom1v** [comment]
Oh, that's great a great trick! Thank you :+1:

```
adb shell input keyevent PASTE
```

I will probably use it to improve non-ascii support.

**Comment by rom1v** [comment]
Ref #1426

**Comment by rom1v** [comment]
Fixed by fc1dec027093ee8a2746a212db0c72a9d96d39a4.
