### ISSUE TITLE
detection and screen touches.

### ISSUE THREAD

**Issue by instasck** [Genymobile/scrcpy#792]
How scrapy do screen touch (touch on pc)? is it sendevent or adb input ?

What about detection? can application know it under screen mirroring ?

**Comment by rom1v** [comment]
See https://github.com/Genymobile/scrcpy/issues/231#issuecomment-414111753

**Comment by instasck** [comment]
> See [#231 (comment)](https://github.com/Genymobile/scrcpy/issues/231#issuecomment-414111753)

But While I tried to getevent for my touchscreen I found out none while play with the mirror screen.

**Comment by pabloab** [comment]
Touchscreen support is issue #22 .

On my `xinput` output was Atmel (tested with `evtest`). Now I wonder if I could `set-prop` [libinput properties](https://wiki.archlinux.org/index.php/Libinput#Via_xinput) to change touchscreen events to mouse events.
