### ISSUE TITLE
[Feature] Control without phone screen turning on

### ISSUE THREAD

**Issue by kriki200** [Genymobile/scrcpy#793]
Any way to use it without the phone screen on.

**Comment by rom1v** [comment]
```
scrcpy --turn-screen-off
```

or `Ctrl`+`o` at any time in the scrcpy window.

**Comment by fefo-dev** [comment]
@rom1v I tried to make a shortcut to launch the no console executable with this parameter and it didn't work. Is it possible?

**Comment by kriki200** [comment]
@fefo-dev I got it working...
@rom1v thanks, misunderstood the documentation initially, on the other note is there any way for right click (while scren is off) to automatically go into this mode instead of also turning on the screen while doing it. I've also got another requests that the screen would turn off when minimizing the window .

**Comment by kriki200** [comment]
And another one, when the window gets minimized if oz could stop streaming and continue when its maximized again.

**Comment by iamjoshuabcxvii** [comment]
is it possible to control the device with no mirroring?, I just want to control the device with mouse and keyboard with no mirroring on the computer.

**Comment by srevinsaju** [comment]
@iamjoshuabcxvii , you can do it with the gui interface, even without scrcpy on guiscrcpy
https://srevinsaju.github.io/guiscrcpy/
guiscrcpy - your PC is your Android device

**Comment by iamjoshuabcxvii** [comment]
> @iamjoshuabcxvii , you can do it with the gui interface, even without scrcpy on guiscrcpy
> https://srevinsaju.github.io/guiscrcpy/
> guiscrcpy - your PC is your Android device

it looks like the same SCRCPY anyway, is there a way to not mirror the phone screen really and just control it with mouse and KB?.

**Comment by srevinsaju** [comment]
You can do it with your mouse , no keyboard. The panels remain open and are connected even though mirroring is not enabled, implying you can power on / off your device remotely or press the home key without mirroring. You can also do swipes

**Comment by rom1v** [comment]
@iamjoshuabcxvii No, not possible with _scrcpy_.

Ref https://github.com/Genymobile/scrcpy/issues/87#issuecomment-378775565 and https://github.com/Genymobile/scrcpy/issues/279#issuecomment-453819354

**Comment by rom1v** [comment]
> is there any way for right click (while scren is off) to automatically go into this mode instead of also turning on the screen while doing it

See #760

**Comment by QuakeString** [comment]
this feature not working, there is a error showing 

![Screenshot_20190914_084948](https://user-images.githubusercontent.com/5375918/64902407-9d2aa180-d6cc-11e9-8481-481f12adaf54.png)

**Comment by rom1v** [comment]
Which Android version?

**Comment by npes87184** [comment]
> this feature not working, there is a error showing
> 
> ![Screenshot_20190914_084948](https://user-images.githubusercontent.com/5375918/64902407-9d2aa180-d6cc-11e9-8481-481f12adaf54.png)

@rom1v I have meet this call stack on my oneplus 7 pro with Android 10 beta 1. The exception happens in reflection target. I guess it is a bug from beta build.

**Comment by fefo-dev** [comment]
Finally got it to work. For some reason -s didn't work withscrcpy-noconsole but --turn-screen-off did.

For reference I created a .bat file with _scrcpy-noconsole --turn-screen-off_ . However, the .bat itself creates a cmd window to run the command, and closing it closes scrcpy. So I found a way to run all off that silently from a .vbs file with _CreateObject("Wscript.Shell").Run "your.bat", 0, True_ . Trying to run scrpcy with arguments directy failed for me, but it should be some syntax issue.

**Comment by rom1v** [comment]
> For some reason -s didn't work

Because it's `-S`? :)

**Comment by kriki200** [comment]
> 
> 
> > is there any way for right click (while scren is off) to automatically go into this mode instead of also turning on the screen while doing it
> 
> See #760

Can a hotkey be made to auto issue ctrl+o after the right click?

**Comment by manishSbisht** [comment]
> > this feature not working, there is a error showing
> > ![Screenshot_20190914_084948](https://user-images.githubusercontent.com/5375918/64902407-9d2aa180-d6cc-11e9-8481-481f12adaf54.png)
> 
> @rom1v I have meet this call stack on my oneplus 7 pro with Android 10 beta 1. The exception happens in reflection target. I guess it is a bug from beta build.

Same errors here with Android Q stable release.
Unable to control from PC while starting with ```-S``` tag.
Also while launched normally(without ```-S```), input control from PC is lost as soon as ```Ctrl+O``` is pressed, also screen on both ends get turned off.



> > For some reason -s didn't work
> 
> Because it's `-S`? :)

I have used uppercase "-S".

Below is the error messages I'm getting:
```
C:\scrcpy\scrcpy-server.jar: 1 file pushed. 1.3 MB/s (22470 bytes in 0.016s)
INFO: Initial texture: 720x1280
[server] ERROR: Exception on thread Thread[Thread-1,5,main]
java.lang.AssertionError: java.lang.NoSuchMethodException: android.view.SurfaceControl.getBuiltInDisplay [int]
        at com.genymobile.scrcpy.wrappers.SurfaceControl.getBuiltInDisplay(SurfaceControl.java:82)
        at com.genymobile.scrcpy.Device.setScreenPowerMode(Device.java:164)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:113)
        at com.genymobile.scrcpy.Controller.control(Controller.java:73)
        at com.genymobile.scrcpy.Server$1.run(Server.java:45)
        at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NoSuchMethodException: android.view.SurfaceControl.getBuiltInDisplay [int]
        at java.lang.Class.getMethod(Class.java:2072)
        at java.lang.Class.getMethod(Class.java:1693)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.getBuiltInDisplay(SurfaceControl.java:80)
        ... 5 more
```

**Comment by rom1v** [comment]
> Same errors here with Android Q stable release.

>     java.lang.NoSuchMethodException: android.view.SurfaceControl.getBuiltInDisplay [int]

This is weird, because you enter the code where `Build.VERSION.SDK_INT < Build.VERSION_CODES.Q`:

https://github.com/Genymobile/scrcpy/blob/1f8ba1ca79f4915f3a7b3c5199258904e3192445/server/src/main/java/com/genymobile/scrcpy/wrappers/SurfaceControl.java#L83-L85

What is the value of `Build.VERSION.SDK_INT` on your device?

```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/wrappers/SurfaceControl.java b/server/src/main/java/com/genymobile/scrcpy/wrappers/SurfaceControl.java
index 5b5586f..ffa49ee 100644
--- a/server/src/main/java/com/genymobile/scrcpy/wrappers/SurfaceControl.java
+++ b/server/src/main/java/com/genymobile/scrcpy/wrappers/SurfaceControl.java
@@ -6,6 +6,8 @@ import android.os.Build;
 import android.os.IBinder;
 import android.view.Surface;
 
+import com.genymobile.scrcpy.Ln;
+
 @SuppressLint("PrivateApi")
 public final class SurfaceControl {
 
@@ -80,6 +82,8 @@ public final class SurfaceControl {
         try {
             // the method signature has changed in Android Q
             // <https://github.com/Genymobile/scrcpy/issues/586>
+            Ln.d("SDK_INT = " + Build.VERSION.SDK_INT);
+            Ln.d("VERSION_CODES.Q = " + Build.VERSION_CODES.Q);
             if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q) {
                 return (IBinder) CLASS.getMethod("getBuiltInDisplay", int.class).invoke(null, builtInDisplayId);
             }
```

**Comment by rom1v** [comment]
@f3liperamos It's fixed on `dev` branch (the next release will have the fix). See #835

**Comment by f3liperamos** [comment]
> @f3liperamos It's fixed on `dev` branch (the next release will have the fix). See #835

Great! I didn't see that issue before because it was on closed state already and I didn't notice we had all those oneplus users opening bugs, my bad.

I was willing to ~try~ share some info since I had the device (and it's probably not a common one) but I have no experience with android&java stuff.

Thanks for your had work!
