### ISSUE TITLE
Wireless Connection problem Windows 10

### ISSUE THREAD

**Issue by jashgopani** [Genymobile/scrcpy#794]
I did the following on windows 10:

> `adb tcpip 5555`
> `adb connect _MY IP_:5555` (usb connected)
> then disconnected usb
> `scrcpy`
> 
> INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
> adb server version (40) doesn't match this client (41); killing...
> * daemon started successfully
> adb: error: failed to get feature set: no devices/emulators found
> ERROR: "adb push" returned with value 1
> Press any key to continue...

Help me with this please

**Comment by rom1v** [comment]
You don't use the same `adb` version (40) for `adb connect`. Use the one from the _scrcpy_ folder (version 41).

**Comment by jashgopani** [comment]
Thanks a lot ! Its working now
