### ISSUE TITLE
how to modify scrcpy-server JAVA part and DEBUG  

### ISSUE THREAD

**Issue by ShiverZm** [Genymobile/scrcpy#797]
as this title , there is a need that  i must modify java part  but i don know how debug this...
.....beg you for help

**Comment by drauggres** [comment]
This is how I did it:
```shell
# Build debug version
cd server
./scripts/build-wrapper.sh . /tmp/scrcpy-server.jar debug

# Copy jar to device
adb push /tmp/scrcpy-server.jar /data/local/tmp/scrcpy-server.jar

# Forward socket to local port
adb reverse localabstract:scrcpy tcp:27183

# Forward port for debugger
adb forward tcp:8888 tcp:8888

# Run scrcpy
adb shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process -agentlib:jdwp=transport=dt_socket,suspend=y,server=y,address=8888 / com.genymobile.scrcpy.Server 0 8000000 false - false
```

Connect your debugger to `localhost:8888`

**Comment by ShiverZm** [comment]
what about windows platform ? i did not run  "cd server
./scripts/build-wrapper.sh . /tmp/scrcpy-server.jar debug", it was too short time so that i always cannot came to  debugger,

**Comment by rom1v** [comment]
@drauggres Thank you.

I just documented it on `dev` branch: https://github.com/Genymobile/scrcpy/commit/683f7ca848ad4785557d116dcea466f1b5654ef9
