### ISSUE TITLE
Low fps / high latency on Redmi Note 5

### ISSUE THREAD

**Issue by wehrwolfi** [Genymobile/scrcpy#798]
Hello ! 
First of all, many thanks and congratulations to your project that I use everyday for random screen mirroring of my phone on PC.

I have a Xiami Redmi Note 5 and used SCRCPY on various Windows 10 computers (i5, i7, AMD...).

When I use SCRCPY for just "surfing" on my phone, it's OK and perfect. If I set it to 1:1 pixel, the picture is great.

But when it comes to gaming (tried it on Modern Combat 5, Republique, Awakening)... it's impossible to use, no matter which parameter I enter (I tried to play with bandwidth, with screen resolution, with frame skipping, ctrl+G, ctrl + F, even tried to record...). 
On such games, my FPS is about 10-15 FPS with an hight input lag that makes it impossible to play.
On my phone screen, everything is smooth.

I tried to disable battery saving mode, or game performance enhancing from MIUI. Tried different USB cables... nothing.

Could you please help ? I'm very frustrated as I have found the perfect app but this particular application doesn't work for me.

Many thanks in advance !

**Comment by rom1v** [comment]
> But when it comes to gaming (tried it on Modern Combat 5, Republique, Awakening)... it's impossible to use, no matter which parameter I enter

Even with a lower definition?

    scrcpy -m 800

> even tried to record

If you record, is the recorded file "laggy"?

I guess the device is not powerful enough to render a 3D game and record screen simultaneously…

**Comment by wehrwolfi** [comment]
Yes, I have even tried -m 400.
The recorded file doesn't seem laggy but you notice the lag mostly because of delay between phone and PC, like 2 seconds.
I'm surprised that this device could be considered as not powerful enough as it has a good Antutu score and I can play all recent games on it without any problem.

**Comment by wehrwolfi** [comment]
On the video file properties I can see FPS=17, and bitrate=637kbits/s

**Comment by rom1v** [comment]
> you notice the lag mostly because of delay between phone and PC, like 2 seconds.

The timestamps of the video are generated on the device-side, so if you can notice the lag in the recorded file, it occurred on the device before transmission to the PC :(

**Comment by wehrwolfi** [comment]
OK, thank you for your help. Strange thing is, as I said, that even when mirroring, I can play with no problem on my phone's screen with no lag.
