### ISSUE TITLE
Use it from an android device?

### ISSUE THREAD

**Issue by cscaloni** [Genymobile/scrcpy#799]
Hi!! Is it exist any trick to use the scrcpy from another android device instead of a win, linux or mac?

thanks you very much for your work!

**Comment by rom1v** [comment]
#100

**Comment by cscaloni** [comment]
Thanks @rom1v !!! I have tried but it doesn't work like i would like....

I want to manage a fire strick from my android mobile. 

- Dont't lanscape in my mobile
- I can't use it over internet
- The touch is not responding well, not in the position that i am trying to click

:(
