### ISSUE TITLE
Forward phone notifications

### ISSUE THREAD

**Issue by AMDG2** [Genymobile/scrcpy#8]
Thank you for this incredible tool !

Do you think it is possible to forward the notifications from the phone to the PC ?

**Comment by rom1v** [comment]
Technically, it's possible (like [KDEConnect](https://github.com/KDE/kdeconnect-kde)).

But I'm not sure this feature makes sense for scrcpy: the screen is displayed on your computer (notifications included), why add desktop notifications?

**Comment by AMDG2** [comment]
To be able to keep it in the background and be interrupted while doing something else on the computer.

But I can understand that this is out of scope :)

**Comment by rom1v** [comment]
> But I can understand that this is out of scope :)

Moreover, currently, there is exactly one socket between device and computer, from the device to the computer for the raw video (without any additional layer to avoids copies/demuxing), and for input events from the computer to the device.

Such a feature would require an additional channel (either a new socket, or adding a layer for the communication between the device and the computer), so it is not worth it.

Maybe an additional communication channel may be added later, if there is a good reason, but probably not for notifications… :)

**Comment by MichelDiz** [comment]
Well, notifications on desktop wouldn't only fit to personal use purposes. If you have a significant portion of devices connected to a Dev PC and you wanna test out some notifications API. This would be handy. I think the project "Expo" has it's own Notification API besides the native one.

Let's say you wanna also simulate SMS codes or contract a SMS service to test development. This feature in scrcpy could capture all the text from it and the dev would do some automation. Could use some tool like "fastlane". There are several possibilities.

Cheers.
