### ISSUE TITLE
Error during basic setup

### ISSUE THREAD

**Issue by mhdtouban** [Genymobile/scrcpy#80]
Am getting 
Error during basic setup:

Neither directory contains a build file meson.build.

when running  `meson x --buildtype release --strip -Db_lto=tru`
tried to reinstall it but this didn't help as am getting build is already installed.

MacOS: 10.13.3

**Comment by rom1v** [comment]
> Neither directory contains a build file meson.build.

See https://github.com/Genymobile/scrcpy/issues/35.

> build is already installed

Remove the build directory:

    rm -rf x

**Comment by mhdtouban** [comment]
Got this error:

Dependency libavformat found: NO

app/meson.build:21:0: ERROR: Dependency 'libavformat' not found, tried Extra Frameworks and Pkg-Config:

Native dependency 'libavformat' not found

**Comment by rom1v** [comment]
Did you [install the packages](https://github.com/Genymobile/scrcpy/blob/master/README.md#mac-os)?

**Comment by mhdtouban** [comment]
yes
```
Warning: sdl2 2.0.8 is already installed
Warning: ffmpeg 3.4.2 is already installed
```

**Comment by mhdtouban** [comment]
and here is the full log: 
```
Build started at 2018-03-18T13:29:27.492806
Main binary: /usr/local/opt/python/bin/python3.6
Python system: Darwin
The Meson build system
Version: 0.45.0
Source dir: /Users/abdullah/dev/java/scrcpy/scrcpy
Build dir: /Users/abdullah/dev/java/scrcpy/scrcpy/x
Build type: native build
Project name: scrcpy
Sanity testing C compiler: cc
Is cross compiler: False.
Sanity check compiler command line: cc /Users/abdullah/dev/java/scrcpy/scrcpy/x/meson-private/sanitycheckc.c -o /Users/abdullah/dev/java/scrcpy/scrcpy/x/meson-private/sanitycheckc.exe
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /Users/abdullah/dev/java/scrcpy/scrcpy/x/meson-private/sanitycheckc.exe
Native C compiler: cc (clang 9.0.0 "Apple LLVM version 9.0.0 (clang-900.0.39.2)")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /opt/local/bin/pkg-config (0.29.1)
Determining dependency 'libavformat' with pkg-config executable '/opt/local/bin/pkg-config'
Dependency libavformat found: NO

app/meson.build:21:0: ERROR: Dependency 'libavformat' not found, tried Extra Frameworks and Pkg-Config:

Native dependency 'libavformat' not found

```

**Comment by rom1v** [comment]
Thanks to @stek29, _scrcpy_ is now available in Homebrew. Could you try:

    brew install scrcpy

?

**Comment by qumberrizvi** [comment]
Please open it back. This issue persists on Ubuntu 20.04.

**Comment by Biswa96** [comment]
libavformat is provided by ffmpeg.

**Comment by r-luo** [comment]
@Biswa96 I'm encountered the same issue and it persists after I did `sudo apt install ffmpeg` (installed the runtime dependencies)

**Comment by LeeBinder** [comment]
same problem trying to compile the latest v.1.25 in macOS (Intel), see [here](https://github.com/Genymobile/scrcpy/issues/2256#issuecomment-1364321625).
