### ISSUE TITLE
Gboard behaviour change with accents

### ISSUE THREAD

**Issue by fefo-dev** [Genymobile/scrcpy#800]
Seems like Google changed the Gboard issue noted at the end of https://blog.rom1v.com/2018/03/introducing-scrcpy/#handle-text-input . Now it works as expected on 1.3, and similarly to other keyboards on 1.9.

**Comment by rom1v** [comment]
Thank you for the info!

**Comment by rom1v** [comment]
I confirm it now works. I removed the note from the blogpost. :+1:
