### ISSUE TITLE
无线连接失败

### ISSUE THREAD

**Issue by sundayong** [Genymobile/scrcpy#802]
![image](https://user-images.githubusercontent.com/15940458/64827068-7f3e3d80-d5f5-11e9-9093-bf3c37454e37.png)

**Comment by zerobikappa** [comment]
> ![image](https://user-images.githubusercontent.com/15940458/64827068-7f3e3d80-d5f5-11e9-9093-bf3c37454e37.png)

did you run`adb tcpip -s yourDeviceName 5555` before you run this command?

**Comment by rayworks** [comment]
Please follow the wireless configuration steps:

> 1. Connect the device to the same Wi-Fi as your computer.
> 2. Get your device IP address (in Settings → About phone → Status).
> 3. Enable adb over TCP/IP on your device: `adb tcpip 5555`.
> 4. Unplug your device.
> 5. Connect to your device: `adb connect DEVICE_IP:5555` _(replace `DEVICE_IP`)_.
> 6. Run `scrcpy` as usual.
