### ISSUE TITLE
Don't have phone default control

### ISSUE THREAD

**Issue by hrace009** [Genymobile/scrcpy#805]
on my device it don't have button like bellow:
![image](https://user-images.githubusercontent.com/7691118/64916933-d7bb3980-d7b3-11e9-9167-b5feab2801de.png)

How to enable it?

**Comment by rom1v** [comment]
Your device use physical buttons. Scrcpy does not emimate them, so you can use  the shortcuts instead. See #7.

**Comment by hrace009** [comment]
okay thanks
