### ISSUE TITLE
Scrcpy never finished pushing scrcpy-server.jar when connecting through SSH tunnel

### ISSUE THREAD

**Issue by herrenP** [Genymobile/scrcpy#807]
I have successfully run scrcpy on several different devices with different Android versions when they have been connected to my PC directly via USB or when setting the device's ADB server to TCPIP mode.

Now, I have a third case where I have a small linux computer in between my PC and the Android device. The Android device is connected directly to this small linux computer. So, on my PC I setup a local port forward using SSH to the small linux computer and I can verify that when running `adb devices` on my PC I do indeed see the correct Android device. However, when I run scrcpy I get this output and it just stays there (I've waited roughly 5 minutes - usually this step takes a few seconds only):
```
INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
[100%] /data/local/tmp/scrcpy-server.jar
```

I am confident that the SSH tunnel itself is not the problem because I have a Java program that successfully does different operations on this device through this tunnel.

The device run Android Nougat. The ADB version used on both my PC and the small linux computer is 1.0.36 (this is not something I can change at the time unfortunately).

Scrcpy is installed as a Snap. Version info:
```
•100% ➜ scrcpy -v      
scrcpy 1.10

dependencies:
 - SDL 2.0.8
 - libavcodec 57.107.100
 - libavformat 57.83.100
 - libavutil 55.78.100
```
This is currently a show stopper for me. Is there anything else I could try?

**Comment by rom1v** [comment]
Does this help: https://github.com/Genymobile/scrcpy/issues/144#issuecomment-414646089
?

**Comment by herrenP** [comment]
> Does this help: [#144 (comment)](https://github.com/Genymobile/scrcpy/issues/144#issuecomment-414646089) ?

It does indeed. Thank you very much! :)
