### ISSUE TITLE
Cmd Showing That scrcpy.server.jar is pushed but phone is not mirrored.

### ISSUE THREAD

**Issue by kunalsindhwani** [Genymobile/scrcpy#811]
Device Used - Samsung Galaxy s8
OS- Mac
<img width="807" alt="Screenshot 2019-09-21 at 5 10 38 AM" src="https://user-images.githubusercontent.com/50311439/65359141-3ce8b200-dc2e-11e9-84f5-0291c33adc75.png">

**Comment by rom1v** [comment]
```
adb logcat
```

Any related error?

What if you reduce the definition:

    scrcpy -m1024

?

**Comment by kunalsindhwani** [comment]
> ```
> adb logcat
> ```
> 
> Any related error?
> 
> What if you reduce the definition:
> 
> ```
> scrcpy -m1024
> ```
> 
> ?

It doesn't work . on further debugging , i realised that whenever i run "scrcpy" , my device got disconnected. Following are the images for the same. Left Side is "adb logcat" . Right side is terminal . As soon as i executed "scrcpy" command my device got disconnected
<img width="1280" alt="Screenshot 2019-09-21 at 3 21 58 PM" src="https://user-images.githubusercontent.com/50311439/65369782-2a00cc80-dc84-11e9-8bcc-b5cee9469149.png">
<img width="1280" alt="Screenshot 2019-09-21 at 3 22 26 PM" src="https://user-images.githubusercontent.com/50311439/65369786-32590780-dc84-11e9-928a-29dff8b782ab.png">
<img width="1278" alt="Screenshot 2019-09-21 at 3 22 41 PM" src="https://user-images.githubusercontent.com/50311439/65369787-3a18ac00-dc84-11e9-8aa2-19d42d89f1df.png">

**Comment by rom1v** [comment]
Try with another USB cable or use another USB slot. See #281 #283.
