### ISSUE TITLE
Copy and pasting from device to computer

### ISSUE THREAD

**Issue by wincelee** [Genymobile/scrcpy#813]
Copy and pasting from device to computer not working

**Comment by wincelee** [comment]
For android 9 pie and when using usb type c

**Comment by rom1v** [comment]
Is it on mac OS? https://github.com/Genymobile/scrcpy/issues/145#issuecomment-533500768

Does it work with scrcpy v1.9 instead of v1.10?

**Comment by rom1v** [comment]
When you copy with scrcpy, are there related errors in the output of `adb logcat`?

Also, could you test the same device on another computer? And another device on the same computer?

**Comment by wincelee** [comment]
Its in a windows computer

**Comment by wincelee** [comment]
when am copying from device to computer using the usb type A, the older usb versions its just working fine

**Comment by wincelee** [comment]
Its in a windows computer

**Comment by rom1v** [comment]
> when am copying from device to computer using the usb type A, the older usb versions its just working fine

That is very surprising, scrcpy communicates over a socket over adb, it doesn't care whether it's over USB-A or USB-C (it doesn't even know), and copy-pasting is totally independant of the communication channel.

**Comment by wincelee** [comment]
When am copying from device to computer using the older models of usb type
A its just working fine, but when am now using usb type c its not copying,
i dont know if the issue is in usb type c

**Comment by rom1v** [comment]
Ah ok, so it's probably the device. `adb logcat` could help to find the cause.

**Comment by wincelee** [comment]
I have tried in huawei p20 lite and even nokia 6.1 plus wich are both using
usb type c, try copying in any device that is using type c let me check the
logcats

**Comment by rom1v** [comment]
Could you test #1423 please?

**Comment by wincelee** [comment]
Issue was solved by newer versions thank you
