### ISSUE TITLE
MacOS Run “brew install scrcpy” error

### ISSUE THREAD

**Issue by denymz** [Genymobile/scrcpy#814]
Mac OS version ：10.15 beta
run brew install scrcpy 
Output：
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
janet

Warning: You are using macOS 10.15.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this pre-release version.

Error: The following formula
  [#<Dependency: "python" []>, #<Options: []>]
cannot be installed as binary package and must be built from source.
Install the Command Line Tools:
  xcode-select --install

and if run “xcode-select --install”
Output：
xcode-select: error: command line tools are already installed, use "Software Update" to install updates

**Comment by rom1v** [comment]
> Warning: You are using macOS 10.15.
> We do not provide support for this pre-release version.

This is a _homebrew_ issue (and the problem is explained).

**Comment by Coool** [comment]
[scrcpy](https://github.com/Coool/scrcpy-macOS-Binaries) for macOS
