### ISSUE TITLE
screen annotation not working with record

### ISSUE THREAD

**Issue by bsde1234** [Genymobile/scrcpy#817]
I am using `-r` parameter for recording in ubuntu. I am using gnome tweak tool draw on you desktop for drawing. But draw is not visible in recording. Also mouse pointer not showing. Using version 1.10

**Comment by rom1v** [comment]
This is expected, the video is recorded on the device. You can even record without opening a window.

**Comment by rom1v** [comment]
Also see https://github.com/Genymobile/scrcpy/issues/689#issuecomment-518016863.
