### ISSUE TITLE
What is the best way to interrupt recording (programmable) in Windows?

### ISSUE THREAD

**Issue by williamfzc** [Genymobile/scrcpy#818]
:) hi

```
scrcpy --no-display --record file.mp4
scrcpy -Nr file.mkv
# interrupt recording with Ctrl+C
# Ctrl+C does not terminate properly on Windows, so disconnect the device
```

I can only get a broken video after sending a CTRL_C_EVENT signal to scrcpy process.
And, `disconnect the device` is not a programmable way.
I have to restart my adb-server instead (it works), but it may influence other devices.

Any suggestions ~?

**Comment by rom1v** [comment]
> I can only get a broken video after sending a CTRL_C_EVENT signal to scrcpy process.

Yes, it is not good.

> Any suggestions ~?

Unfortunately, no good solution.

You could kill the `adb shell` process which runs the server.

**Comment by williamfzc** [comment]
![image](https://user-images.githubusercontent.com/13421694/65600715-429a1b00-dfd3-11e9-8529-81c5c263fcdf.png)

```python
import subprocess
import time

p = subprocess.Popen(['scrcpy', '--record', 'haha.mkv'])
time.sleep(3)
p.kill()
```

emmm, both of them were broken thoroughly I think.

> You could kill the adb shell process which runs the server.

It works. A little weird but much better than restart adb server at least. Thanks!

**Comment by rom1v** [comment]
> both of them were broken thoroughly I think.
If you record longer (and actually move thkbgs on screen), data will be written to the mkv, and it will play in VLC or whatever. With mp4, data will be written, but it will not play.

**Comment by williamfzc** [comment]
ok, thank you :) 

## about how to find the adb shell process which runs the server

check the cmdline of the process named `adb.exe`. scrcpy's cmdline will always be:

```
'adb', 'shell', 'CLASSPATH=/data/local/tmp/scrcpy-server.jar', 'app_process', '/', 'com.genymobile.scrcpy.Server', '0', '8000000', 'false', '-', 'true', 'true'
```

**Comment by rom1v** [comment]
You could also kill the process _on the device_ instead:

    adb shell pkill app_process

(assuming it is the only one running)

**Comment by williamfzc** [comment]
BTW, 

> For Windows, for simplicity, prebuilt archives with all the dependencies (including adb) are available

Scrcpy will use the adb, which was included in prebuilt archives by default, if you configure scrcpy to $PATH.

And if you already have an installed adb on your PC, actually you can not access your phone with this adb directly, because current adb design only supports one adb server connection per adbd.

So if you gonna running `adb shell pkill app_process`, you need to keep only one adb in your $PATH (or, keep a specific order?). What's more, `pkill` seems to works above android 6 at least.

For now I prefer killing the adb shell process which runs the server.

**Comment by lbathina** [comment]
I see the same issue with macOS as well. It will be helpful to have stop method/option with scrcpy to be executed from command line

**Comment by rom1v** [comment]
On macOS, Ctrl+C should work as expected, doesn't it?

**Comment by rom1v** [comment]
I implemented a fix for Windows: 28abd98f7fef5161ede934a41287b2c0ec1d7668

Please test by replacing these files in the v1.13 release:
 - [`scrcpy.exe`](https://tmp.rom1v.com/scrcpy/issue818/1/scrcpy.exe)
  _SHA256: 5c6516793f638d7d2b5ef518b1c59421087e1a3bbc3a1e3ac3a44617b6d2315d_
 - [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/issue818/1/scrcpy-server)
  _SHA256: 6d124307e081b8bbccc478dcf82731aad3cc994e7502197c9bae3847d3169dc7_

**Comment by lbathina** [comment]
@rom1v Manually it had no issues. I was able to get it worked on macOs via Java programming.  I am looking for linux binary so I could get that installed in my test environment for which I do not have root access. Is it possible that linux binary is available?

**Comment by williamfzc** [comment]
> @rom1v Manually it had no issues. I was able to get it worked on macOs via Java programming. I am looking for linux binary so I could get that installed in my test environment for which I do not have root access. Is it possible that linux binary is available?

What about docker? https://github.com/Genymobile/scrcpy/pull/94

> I implemented a fix for Windows: 28abd98

Thanks! I will try later.

**Comment by rom1v** [comment]
> Is it possible that linux binary is available?

Linux binaries must be different for each distrib/version. That's why I don't publish them (but I I provide the prebuilt server, and building from linux is "easy" if you gollow the steps).

**Comment by LBensman** [comment]
> > Is it possible that linux binary is available?
> 
> Linux binaries must be different for each distrib/version. That's why I don't publish them (but I I provide the prebuilt server, and building from linux is "easy" if you gollow the steps).

AFAIU, if you perform static compile, then you can have a single build that will work on various distributions/versions.  It also means that any and every library that scrcpy uses (client-side, obviously) also needs to be a static library (i.e. either use static version if distribution has it, or build one from source).

**Comment by rom1v** [comment]
@LBensman Absolutely. A static build would be great, but is not supported for now.

If someone want to improve the build system to optionally build sdl and ffmpeg (only the parts scrcpy is using) and link statically, please do.

**Comment by walkthunder** [comment]
@rom1v so the static build feature is closed? Really need it.

**Comment by cjjdream** [comment]
> 

I faced to the same question。 would you find any solutions for the issue for JVM？
