### ISSUE TITLE
scrcpy not working on windows 10

### ISSUE THREAD

**Issue by bluekuen** [Genymobile/scrcpy#821]
Hello, 

i have Win 10 64 bit and downloaded newest scrcpy. 
I added SCRCPY_SERVER PATH and ADB to Path Environment Variable but i get the following Error:
```
PS C:\Program Files\ScrCpy> scrcpy
INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
ERROR: Command not found: [C:\Program Files\ScrCpy], [push], ["C:\Program Files\ScrCpy"], ["/data/local/tmp/scrcpy-server.jar"]
ERROR: (make 'adb' accessible from your PATH or define its fullpath in the ADB environment variable)
ERROR: Could not execute "adb push"
Press any key to continue...
```
![grafik](https://user-images.githubusercontent.com/35228746/65670998-bde8e480-e046-11e9-86eb-ce5fc707b151.png)
![grafik](https://user-images.githubusercontent.com/35228746/65671079-e244c100-e046-11e9-81b7-8b7c2c66e277.png)

Did i forget something?

**Comment by rom1v** [comment]
> I added SCRCPY_SERVER PATH and ADB to Path Environment Variable

You should not set `ADB` if you use the one from the scrcpy folder.

If you really want to set it, it must point to the `adb` executable, not its folder: https://github.com/Genymobile/scrcpy/issues/769#issuecomment-533495032

**Comment by bluekuen** [comment]
thank you! got it working again!
