### ISSUE TITLE
Deprecated Gradle features were used

### ISSUE THREAD

**Issue by npes87184** [Genymobile/scrcpy#825]
Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.

The detail get from --warning-mode all shows 
```
> Task :server:processReleaseResources UP-TO-DATE
Changing the value for a property with a final value has been deprecated. This will fail with an error in Gradle 6.
0.
```

**Comment by rom1v** [comment]
It's seems to be a bug in the Android plugin: https://discuss.gradle.org/t/gradle-5-1-1-bug/32021/8
