### ISSUE TITLE
Error: Exception on Thread

### ISSUE THREAD

**Issue by sevku** [Genymobile/scrcpy#827]
`INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server.jar: 1 file pushed. 5.6 MB/s (22546 bytes in 0.004s)
INFO: Initial texture: 1080x2160
[server] ERROR: Exception on thread Thread[main,5,main]`

**Comment by rom1v** [comment]
```
adb logcat
```

for more details.

**Comment by rom1v** [comment]
Possibly: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#i-get-an-error-could-not-open-video-stream
