### ISSUE TITLE
Choppy performance redmi note 7

### ISSUE THREAD

**Issue by Critiko** [Genymobile/scrcpy#828]
Using this with the Redmi 4 works flawlessly. Recently got a Redmi note 7 and with this device the stream is less smooth, pretty stuttery. The device should be faster. Using the fps counter shows a lot of frames being skipped (+1 to +5, ocassional spike to +13) on the redmi note 7 even when just looking at homescreen. Performance in phone itself is smooth.

Whether I use -m 1920, 1280 or 800 all provide same performance.
The recorded file --record file.mp4 is smooth upon playback.

Is there any option I might be missing on the phone that is causing this?

**Comment by rom1v** [comment]
> The recorded file --record file.mp4 is smooth upon playback.

> Using the fps counter shows a lot of frames being skipped (+1 to +5, ocassional spike to +13)

This suggests that the problem may be on the computer side (but not sure).

**Comment by Critiko** [comment]
I see, I'll try to connect it to an USB 3.0 on the back of my PC and set power savings to high performance.

**Comment by Critiko** [comment]
Hmm.. no idea. I've ordered a USB 3.1 to 3.1 cable since my pc has one usb 3.1 connector, maybe that will work.

Do the skipped frames indicate my pc being the problem or the fact that the recording is smooth?

**Comment by rom1v** [comment]
> Do the skipped frames indicate my pc being the problem or the fact that the recording is smooth?
If you have 15 skipped frames by seconds, the PC has probably a problem.
