### ISSUE TITLE
Different aspect ratio on device and PC

### ISSUE THREAD

**Issue by Adalphos** [Genymobile/scrcpy#830]
My phone have wide aspect ratio and my PC have 4:3 (1024x768). I need to fit display to full screen. Is possible to stretch out window to full 4:3 ratio? Using CTRL+F preserved wide aspect ratio.

**Comment by rom1v** [comment]
No, scrcpy always respect aspect ratio.

**Comment by CorgJR** [comment]
As a quick fix, I'd suggest using OBS (Open Broadcaster Studio) and creating a window capture scene, stretching it, then view the fullscreen preview.

**Comment by rom1v** [comment]
Out of curiosity, what is the use case? Why would you want a distorted image?

**Comment by fefo-dev** [comment]
You can change resolution on the fly with _adb shell wm size 1024x768_ (mind the orientation). If you mess too much reboot. Some info: https://stackoverflow.com/questions/18500611/android-how-to-use-adb-shell-wm-to-simulate-other-devices

**Comment by aiamuzz** [comment]
@rom1v  ... i don't know if i am a victim of an optical illusion ... even i am getting a feeling ... the device window on my laptop and its aspect ration isn't the same i am used to when i work directly on my tablet ... the scrcpy window on the laptop seems a little off !!!

Is there anyway i can fetch the aspect ration out of the package scrcpy and see if it matches the aspect ration of the device's specs ?

**Comment by rom1v** [comment]
You can get the video dimensions in the console:
```
$ scrcpy
INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server....shed. 3.4 MB/s (22686 bytes in 0.006s)
INFO: Initial texture: 1080x1920
```

Or you can just take a screenshot, and "measure" (with any image editor).

**Comment by aiamuzz** [comment]
FYI ... my device is a Nexus 9 ... and according to its specs its screen is `2048x1536` ... is there a way  i can grab the scrcpy window's screen resolution and see if its the same ...

**Comment by aiamuzz** [comment]
> You can get the video dimensions in the console:
> 
> ```
> $ scrcpy
> INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
> /usr/local/share/scrcpy/scrcpy-server....shed. 3.4 MB/s (22686 bytes in 0.006s)
> INFO: Initial texture: 1080x1920
> ```
> 
> Or you can just take a screenshot, and "measure" (with any image editor).

hahahaha ... you are right ... the console shows the correct screen dimensions ... seems an optical illusion !!!

I'll have to try the screenshot method ... :laughing: ... to further debug my illusion ...
after my issue gets resolved ... https://github.com/Genymobile/scrcpy/issues/833
