### ISSUE TITLE
adb device unauthorized

### ISSUE THREAD

**Issue by SwankyTigers** [Genymobile/scrcpy#831]
Hello,
when i lanched scrcpy the following message appear:
INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: device unauthorized.
This adb server's $ADB_VENDOR_KEYS is not set
Try 'adb kill-server' if that seems wrong.
Otherwise check for a confirmation dialog on your device.
ERROR: "adb push" returned with value 1
Press any key to continue...
Can you help me ?

**Comment by rom1v** [comment]
https://stackoverflow.com/questions/32132434/set-adb-vendor-keys
