### ISSUE TITLE
Flipped display [ZTE Blade V7 Lite]

### ISSUE THREAD

**Issue by Hippobotus** [Genymobile/scrcpy#832]
Hello,

I am using a [ZTE Blade V7 Lite](https://www.gsmarena.com/zte_blade_v7_lite-7944.php) and the display is flipped as you can see in the images below. Hope you can look into this. 

Thank you.

![ZTE_BLADE_V0720_2](https://user-images.githubusercontent.com/54347199/65932254-83fd5100-e43f-11e9-9bc8-f3ef8e5b39ea.png)

**Comment by rom1v** [comment]
Weird. If you rotate your device, is the video still flipped?

**Comment by Hippobotus** [comment]
Even with auto-rotate the display is flipped (horizontally).

**Comment by rom1v** [comment]
Now, you could use `scrcpy --rotation 2` to workaround the problem.
