### ISSUE TITLE
Wifi Direct?

### ISSUE THREAD

**Issue by papermache** [Genymobile/scrcpy#834]
I would like to use scrcpy over wifi direct instead of TCPIP or USB-C. That way if I am in a public place I can still connect my phone to my laptop, for example.

**Comment by rom1v** [comment]
No idea. https://android.stackexchange.com/questions/176973/is-it-possible-to-adb-via-wifi-direct

**Comment by rickx** [comment]
wifi direct is still wifi. So, supposed you have pc and phone both supporting wifi direct (hard) and they actually see/detect each other (harder), what you'll get is plain old tcp/ip. What else could it be anyway?

**Comment by papermache** [comment]
Here is a demo: https://android.googlesource.com/platform/development/+/master/samples/WiFiDirectDemo

Taken from: https://github.com/NaniteFactory/Wifi-Direct-on-Linux
