### ISSUE TITLE
window didn't restore 9:16 after turning off screen with 16:9

### ISSUE THREAD

**Issue by NewUserHa** [Genymobile/scrcpy#840]
found once in which it should be turned off screen after the timeout, after turning on by right-clicking, content resizes to a small 9:16 at inputting pin interface within the original window size(didn't change at now). then after unlocking the phone seems like content just rotating back to 16:9, and making scrcpy resize the window to that size.
I didn't recall every detail and didn't reproduce by myself again.

**Comment by rom1v** [comment]
Thank you for the info.

I could not reproduce, feel free to reopen if you can reproduce and have more information.
