### ISSUE TITLE
Some Polish diacritics are not picked up from a keyboard

### ISSUE THREAD

**Issue by vulterey** [Genymobile/scrcpy#844]
Hi,

I've noticed that some Polish diacritic signs are not picked up by scrcpy despite proper setup up language.
What is weirder only some of the signs are not picked up properly.
Signs are typed by pressing right Alt key and corresponding letter on the keyboard (except ź which is under x)
So, the signs which works are: ó, ć, ś, ź, ń
**The signs which are not working: ż, ł, ę, ą.** 
Any fix will be appreciated.

Regards
Adam

**Comment by rom1v** [comment]
Please test #1426 (works on Android >= 7).

**Comment by vulterey** [comment]
> Please test #1426 (works on Android >= 7).

Hi, 
I Just freshly tested v1.13 on Android 10
Still no luck/no change.
Same letters are injected properly but some of them still not.

As previously, I can type in the letters: ó, ć, ś, ź, ń

But for the letters  ż, ł, ę, ą, nothing appears in the type in box (no matter what app I use): 
In the console I get warnings:
[server] WARN: Could not inject char u+0105
[server] WARN: Could not inject char u+0119
[server] WARN: Could not inject char u+0142
[server] WARN: Could not inject char u+017c

**Comment by rom1v** [comment]
> I Just freshly tested v1.13 on Android 10

v1.13 is "before" #1426 (which will not be merged anyway, cf thread).

**Comment by vulterey** [comment]
Ok, no probs.
Thank you for trying anyway.

Overall still best app for testing some of the features of my apps.

Regards
Adam
