### ISSUE TITLE
I can't use commands in windows 

### ISSUE THREAD

**Issue by lologacela** [Genymobile/scrcpy#845]
Hello, I downloaded the software and  stars without problems, but I want to use the function Always on Top, but the command line don't work, I copy and paste the code:
scrcpy --always-on-top

And nothing hapen
![2019-10-07 13_14_59-NVIDIA GeForce Overlay](https://user-images.githubusercontent.com/33681450/66337689-426c1a80-e905-11e9-80b0-1ded9e64b005.png)
 
I don't know it is because I extract the folder in C and not on my desktop

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/issues/385#issuecomment-451903274
