### ISSUE TITLE
.xe works but don´t on Comand Line

### ISSUE THREAD

**Issue by lologacela** [Genymobile/scrcpy#846]
![2019-10-07 13_37_53-I can't use commands in windows · Issue #845 · Genymobile_scrcpy2](https://user-images.githubusercontent.com/33681450/66339684-3eda9280-e909-11e9-954a-1b02756243d1.png)
I use the exe file and I don't have problems, but when I use the command I have this error, I want to use the command, always on top, I'm pretty new on this

**Comment by rom1v** [comment]
Use v1.10.

**Comment by lologacela** [comment]
Thank, you, that was the problem, and that I need to use the command before open the program, there's a way to put commands when the program is already open?

**Comment by rom1v** [comment]
No, you can't change the parameters afterwards.

Note that you can just create some `file.bat` in the scrcpy folder containing your command:

```
scrcpy --always-on-top
```

Then you can just double-click on it.

**Comment by lologacela** [comment]
> 
> 
> No, you can't change the parameters afterwards.
> 
> Note that you can just create some `file.bat` in the scrcpy folder containing your command:
> 
> ```
> scrcpy --always-on-top
> ```
> 
> Then you can just double-click on it.

Thanks you, I cant put 2 comands at same tame time? Something like that:
--always-on-top
--turn-screen-off
And if is possible how I put this on command line?

**Comment by srevinsaju** [comment]
scrcpy --always-on-top --turn-screen-off

In one line

**Comment by lologacela** [comment]
> 
> 
> scrcpy --always-on-top --turn-screen-off
> 
> In one line

Ok, thank you
