### ISSUE TITLE
I can´t make screen recording

### ISSUE THREAD

**Issue by lologacela** [Genymobile/scrcpy#847]
I make an bat file to record, this is the text inside:
cd\ 
C:\scrcpy-win64-v1.10\scrcpy.exe --always-on-top --turn-screen-off -r file.mkv

But don't work and the program send this message
![2019-10-07 15_15_08-Documento1 - Word](https://user-images.githubusercontent.com/33681450/66345684-202ec880-e916-11e9-92de-3435dd6a1731.png)

**Comment by rom1v** [comment]
You call the command from `C:\`, so the file is to be recorded in `C:\file.mp4`. Do you have write permissions there?

**Comment by lologacela** [comment]
> 
> 
> You call the command from `C:\`, so the file is to be recorded in `C:\file.mp4`. Do you have write permissions there?

I think so, I'm going to change the path file

**Comment by rom1v** [comment]
cd C:\scrcpy-win64-v1.10
    scrcpy -r file.mkv

**Comment by lologacela** [comment]
> 
> 
> ```
> cd C:\scrcpy-win64-v1.10
> scrcpy -r file.mkv
> ```
I can change the save file path? I want maintain scrcpy
 on C

**Comment by lologacela** [comment]
> 
> 
> > ```
> > cd C:\scrcpy-win64-v1.10
> > scrcpy -r file.mkv
> > ```
> 
> I can change the save file path? I want maintain scrcpy
> on C

**Comment by lologacela** [comment]
The commands dont work

**Comment by rom1v** [comment]
What does not work? What is the output?
