### ISSUE TITLE
accent mark

### ISSUE THREAD

**Issue by Josemi-21** [Genymobile/scrcpy#849]
Using Windows 10 with spanish-Spain language, spanish keyboard (QWERTY).
When I press accent mark (tilde) over a vowel several anomalous behaviors occur:
1. Duplicate the vowel in question, showing once without tilde, and other tilde.
2. Eliminate the previous characters of the word where I press the accent, to show, either only the vowel with a tilde, or the duplicate vowel, in this case, the first time with a tilde, followed without a tilde.

**Comment by rom1v** [comment]
Thank you for your report.

This is a duplicate of #650 (see comments there).

**Comment by rom1v** [comment]
Please test #1426 (works on Android >= 7).
