### ISSUE TITLE
Creating a .bat File For Recording

### ISSUE THREAD

**Issue by MrTeeXD** [Genymobile/scrcpy#850]
Hello. I am interested in creating a Batch File to make scrcpy record a Video. What can I do?

**Comment by rom1v** [comment]
In the scrcpy folder, just create a file named `something.bat` containing:

```
scrcpy --record file.mkv
```

**Comment by MrTeeXD** [comment]
Ahh. thank you. this will make my life a bit easier.

**Comment by MrTeeXD** [comment]
Hey @rom1v How would I combine another command with this one?

**Comment by rom1v** [comment]
scrcpy --record file.mkv --fullscreen
