### ISSUE TITLE
MacOS install without Homebrew

### ISSUE THREAD

**Issue by araptunovich** [Genymobile/scrcpy#854]
Hello crew,

I tried the scrcpy install via homebrew for mac and received the following error once it got to installing ninja:

Error: An exception occurred within a child process:  Utils::InreplaceError: inreplace failed/usr/local/Cellar/glib/2.62.1/lib/pkgconfig/glib-2.0.pc:  expected replacement of "Libs: -lintl -L${libdir} -lglib-2.0" with "Libs: -L${libdir} -lglib-2.0 -L/usr/local/opt/gettext/lib -lintl"

I tried both brew upgrade and brew doctor with no luck. The Homebrew folks on the IRC believe it's because I am on 10.12.6 and said I should install directly here without Homebrew. How can I install here without homebrew? I followed the manual install as well and run into the exact same issue/error with ninja when running: brew install sdl2 ffmpeg. Thank you for any help!

**Comment by rom1v** [comment]
Just follow [`BUILD.md`](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md).

```bash
# install dependencies
brew install sdl2 ffmpeg pkg-config meson

# download prebuilt server v1.10
wget https://github.com/Genymobile/scrcpy/releases/download/v1.10/scrcpy-server-v1.10.jar
# check its checksum
echo 'cbeb1a4e046f1392c1dc73c3ccffd7f86dec4636b505556ea20929687a119390  scrcpy-server-v1.10.jar' | sha256sum -c

# configure
meson x --buildtype release --strip -Db_lto=true \
    -Dprebuilt_server=scrcpy-server-v1.10.jar
# build
ninja -Cx
# install
ninja -Cx install
```

**Comment by araptunovich** [comment]
I am getting 'Command not found' when doing:
wget https://github.com/Genymobile/scrcpy/releases/download/v1.10/scrcpy-server-v1.10.jar
I downloaded manually and placed on the desktop and am getting:
Annas-MBP-3:~ anna$ meson x --buildtype release --strip -Db_lto=true \
> -Dprebuilt_server=/Users/Anna/Desktop/scrcpy-server-v1.10.jar

ERROR: Neither directory contains a build file meson.build.

Any further help would be appreciated! Thank you!

**Comment by rom1v** [comment]
Just download the file with anything you want (your browser for example).

**Comment by araptunovich** [comment]
Thank you for all the help. Still running into issues :( here is where I am at now:

`Last login: Fri Oct 11 12:37:57 on ttys000
Annas-MBP-3:~ anna$ echo 'cbeb1a4e046f1392c1dc73c3ccffd7f86dec4636b505556ea20929687a119390 scrcpy-server-v1.10.jar' sha256sum -c
cbeb1a4e046f1392c1dc73c3ccffd7f86dec4636b505556ea20929687a119390 scrcpy-server-v1.10.jar sha256sum -c
Annas-MBP-3:~ anna$ eson x --buildtype release --strip -Db_lto=true \
>     -Dprebuilt_server=scrcpy-server-v1.10.jar
-bash: eson: command not found
Annas-MBP-3:~ anna$ ninja -Cx
ninja: Entering directory `x'
ninja: error: loading 'build.ninja': No such file or directory
Annas-MBP-3:~ anna$ 
`

**Comment by rom1v** [comment]
> ```
> eson: command not found
> ```

It's `meson`.

> ```
> sha256sum: command not found
> ```

It's just to verify the checksum of the file. Skip this step if you don't care.

**Comment by araptunovich** [comment]
`Annas-MBP-3:~ anna$ meson x --buildtype release --strip -Db_lto=true \
>     -Dprebuilt_server=scrcpy-server-v1.10.jar

ERROR: Neither directory contains a build file meson.build.
Annas-MBP-3:~ anna$ `

**Comment by rom1v** [comment]
> Neither directory contains a build file meson.build.

You need to run this command from the repo of scrcpy that you cloned:

```
git clone https://github.com/Genymobile/scrcpy
cd scrcpy
meson ...
```
