### ISSUE TITLE
[QUESTION] How does scrcpy get device clipboard?

### ISSUE THREAD

**Issue by srevinsaju** [Genymobile/scrcpy#855]
Can anyone please give the part of code, where device clipboard is collected in scrcpy?

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/1f8ba1ca79f4915f3a7b3c5199258904e3192445/server/src/main/java/com/genymobile/scrcpy/wrappers/ClipboardManager.java#L24-L34

**Comment by srevinsaju** [comment]
Thank you @rom1v
