### ISSUE TITLE
Turkish special characters 

### ISSUE THREAD

**Issue by alperenbabagil** [Genymobile/scrcpy#856]
Turkish ı,ş,ğ,I,Ş,Ğ characters cannot be entered with computer keyboard

**Comment by dani763f** [comment]
+1 Danish special characters (æøå) also doesn't work (at least on the snap version of the app).

**Comment by rom1v** [comment]
Duplicate of #37.

**Comment by rom1v** [comment]
Please test #1426 (works on Android >= 7).
