### ISSUE TITLE
android.media.MediaCodec$CodecException: Error 0xfffffc0e

### ISSUE THREAD

**Issue by oneforallallforone** [Genymobile/scrcpy#857]
![Snipaste_2019-10-12_19-40-53](https://user-images.githubusercontent.com/52807529/66700924-d3d5f500-ed28-11e9-90a1-fef78d1e9790.png)
无法投屏，其他设置满足要求。
no image. other set is right.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#i-get-an-error-could-not-open-video-stream
