### ISSUE TITLE
some error when push file to device(drag & drop)

### ISSUE THREAD

**Issue by elisir516** [Genymobile/scrcpy#858]
hi,guys.
when i pushed file to device, i met some error:
for the files with English letters, most were successful but the file "Daniel Yergin - Quest_ Energy, Security, and the Remaking of the Modern World, The.epub" was renamed to "Daniel Yergin - Quest_ Energy, Security, and the Remaking of the Modern World, The.e"

for the files with chinese letters,  most met error:
（中）笑笑 - 悖论.epub was successfully pushed but renamed to "（中）笑笑 -" with the same size.
androbench跑分对比.xlsx pushed successfully, but the device recieved with wrong name"androbench跑分对怠" and 0B size.
some other got error response like:
adb: error: failed to copy 'Linux从入门到精通.pdf' to '/sdcard/Download/.': remote couldn't create file: Is a directory

does anyone know what happened and how to fix it? thanks!

**Comment by rom1v** [comment]
`adb` itself has the problem (try `adb push your_file_with_chinese_chars /sdcard`), and scrcpy just calls `adb` for that.

**Comment by elisir516** [comment]
> `adb` itself has the problem (try `adb push your_file_with_chinese_chars /sdcard`), and scrcpy just calls `adb` for that.

thank you for your reply. i'll try

**Comment by rom1v** [comment]
Oh, it seems to work now (adb 1.0.41):

```
$ touch '（中）笑笑 - 悖论.epub'
$ adb push '（中）笑笑 - 悖论.epub' /sdcard/
（中）笑笑 - 悖论.epub: 1 file pushed.
$ adb shell ls /sdcard/*.epub
/sdcard/（中）笑笑 - 悖论.epub
```
