### ISSUE TITLE
Pair phone with computer once for all with a USB cable, and then always use wireless, even after reboot

### ISSUE THREAD

**Issue by josephernest** [Genymobile/scrcpy#859]
Hi,
The procedure https://github.com/Genymobile/scrcpy#wireless works very well. However I noticed that after a computer reboot / phone reboot, just doing:

    adb connect 192.168.1.14:5555
    scrcpy

doesn't work anymore.

The solution is to **connect by USB cable again**, and re-do the `adb devices`, 
`adb tcpip 5555` process.

Question: is it possible to pair phone and computer forever, such that it's no longer needed to connect them via USB first each time, and always use Wifi connection instead?

PS: my phone IP is fixed (router setting).

**Comment by srevinsaju** [comment]
Check your developer settings for ADB over Network setting

**Comment by dilbert168** [comment]
I have same question.  Could you explain what to look for "developer settings for ADB over Network setting" ?

Thanks so much.

**Comment by josephernest** [comment]
@srevinsaju can you give more details? Where to find these settings, and what to do?

**Comment by srevinsaju** [comment]
Sorry about that, I couldn't get the screenshot from mobile, I have got a stackoverflow answer, scroll to the bottom, 
https://stackoverflow.com/questions/4893953/run-install-debug-android-applications-over-wi-fi

**Comment by josephernest** [comment]
I don't have this option like on the screenshot of the main answer (see the
comment, many people have the same issue).

The only problem is that after a reboot, I have to reuse USB cable again...

**Comment by srevinsaju** [comment]
Is your android rooted?

**Comment by josephernest** [comment]
Not rooted

**Comment by srevinsaju** [comment]
You might have to use third party apps to do so. If you were rooted, you could have used scheduling apps to run the command to enable ADB over WiFi without a PC over the root terminal.

**Comment by Buddzbass** [comment]
I am able to connect to my phone via wifi after shutting down and/or restarting my iMac without plugging in a USB.

I use the following commands:

`adb start-server`
`* daemon not running; starting now at tcp:5037`
`* daemon started successfully`

`adb -s <DEVICE_NAME> connect <YOUR_IP>:5555`

you should receive the following msg.

`connected to <YOUR_IP>:5555`

sometimes, on the first few attempts, it times out and you may see a message like this:

`failed to connect to '<YOUR_IP>:5555': Operation timed out`

but it should connect after a couple of tries, if not the first

to get your device name. Use `adb devices` when you phone is plugged through USB and it will show in listed devices.

**Comment by josephernest** [comment]
Would you have any idea @rom1v about how to make the pairing computer <--> android phone **permanent**, and *not* have to re-connect them by cable after each reboot?

Thanks in advance!

**Comment by rom1v** [comment]
Without root, I think it's not possible. Maybe in Android 11? https://www.xda-developers.com/android-11-native-wireless-adb/

**Comment by josephernest** [comment]
Thanks for your feedback Romain @rom1v !

**Comment by reversegear** [comment]
> 
> 
> Would you have any idea @rom1v about how to make the pairing computer <--> android phone **permanent**, and _not_ have to re-connect them by cable after each reboot?
> 
> Thanks in advance!

as a temporary solution you can use this app https://play.google.com/store/apps/details?id=com.ttxapps.wifiadb&hl=en_IN (works only with rooted android device)
