### ISSUE TITLE
I just felt so awkward about not reading FAQ carefully!

### ISSUE THREAD

**Issue by He-haitao** [Genymobile/scrcpy#861]
Why right-click can not power on my MI8, and I can not control my phone to do something like open wechat or something. When i use cell phone data, and adb connet can not connect my phone? Also I can not transfer files to my phone? what is going on?  WIN10,MI8,

**Comment by npes87184** [comment]
Please provide more detail, for example, does console print something? Anything in `adb logcat`?

**Comment by rom1v** [comment]
> Why right-click can not power on my MI8

Does Ctrl+p power it on and off?

> I can not control my phone to do something like open wechat or something

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#i-can-only-mirror-i-cannot-interact-with-the-device

> When i use cell phone data, and adb connet can not connect my phone?

You mean when you are not connected over wifi? To connect to your device, the computer and the device must be on the same network.

> Also I can not transfer files to my phone?

What do you do to transfer files? If you drag&drop a file, it is copied to `/sdcard` on the device. Any error in the console? What if you copy with `adb push your_fille.txt /sdcard`?

**Comment by He-haitao** [comment]
sorry for that, acturally it can copy file to my phone, i just don't know where it is, thanks for that, but another thing is that i can't control my phone from my computer, such as can i operate an app from my comupter?

**Comment by He-haitao** [comment]
> Please provide more detail, for example, does console print something? Anything in `adb logcat`?

> > Why right-click can not power on my MI8, and I can not control my phone to do something like open wechat or something.
> 
> https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#i-can-only-mirror-i-cannot-interact-with-the-device
> 
> > When i use cell phone data, and adb connet can not connect my phone?
> 
> You mean when you are not connected over wifi? To connect to your device, the computer and the device must be on the same network.
> 
> > Also I can not transfer files to my phone?
> 
> What do you do to transfer files? If you drag&drop a file, it is copied to `/sdcard` on the device. Any error in the console? What if you copy with `adb push your_fille.txt /sdcard`?

sorry for that, acturally it can copy file to my phone, i just don't know where it is, thanks for that, but another thing is that i can't control my phone from my computer, such as can i operate an app from my comupter?

**Comment by rom1v** [comment]
> I see the link, and i enabled the usb debugging mode

Not only `USB debugging`, but `USB debugging (security settings)`. https://github.com/Genymobile/scrcpy/issues/70#issuecomment-373286323

**Comment by He-haitao** [comment]
finally, i know how to interact with it now. In MI8, i need to allow usb debug(security settings), before i just allow usb debug. And it's my fault not to read the FAQ carefully. Really Appreciate for your warmful reply!

**Comment by He-haitao** [comment]
if i want to edit my sticky notes in my phone from my computer, like inputing some chinese words. And now my IME is chinese and my phone IME is also IME, but i still can not input chinese but english? Does this can be solved or has been solved?

**Comment by rom1v** [comment]
> i still can not input chinese but english?

Yes, only ASCII (+ some accented characters) is supported: https://blog.rom1v.com/2018/03/introducing-scrcpy/#handle-accented-characters

Handling chinese would require a keyboard app: https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3Aunicode

**Comment by lpful** [comment]
![503f1f6e8b58fcae4a26f903d9a18480_37056-20180624121532219-527114242](https://user-images.githubusercontent.com/50052327/66844202-7cda5500-efa0-11e9-868d-3cd42181eb02.gif)
[https://www.cnblogs.com/we-hjb/p/10989928.html](url)

**Comment by lpful** [comment]
> if i want to edit my sticky notes in my phone from my computer, like inputing some chinese words. And now my IME is chinese and my phone IME is also IME, but i still can not input chinese but english? Does this can be solved or has been solved?

You may try ARDC.
