### ISSUE TITLE
Met black screen when play video under sdk23(including)

### ISSUE THREAD

**Issue by skier-peng** [Genymobile/scrcpy#863]
1. i met black screen when i was playing video part. other part of the screen seems ok. 
2. i tried scrcpy -m 1200 or -m 800, it not works. 
3. the video is record well at devices with sdk level higher than sdk27
<img width="620" alt="屏幕快照 2019-10-14 下午12 44 33" src="https://user-images.githubusercontent.com/1625886/66729885-d9465300-ee80-11e9-9cea-9ab840e380c4.png">

**Comment by rom1v** [comment]
That's expected for content restricted by hardware DRM.

**Comment by skier-peng** [comment]
but， the same content works well since sdk24。
![屏幕快照 2019-10-14 下午2 49 59](https://user-images.githubusercontent.com/1625886/66733421-17983e00-ee92-11e9-962d-b1869891d49a.png)

**Comment by rom1v** [comment]
Probably because the app uses a software DRM for some version and a hardware DRM for the some others.

**Comment by skier-peng** [comment]
i use scrcpy with version 1.10。 i try to confirm the drm style ,but the video with no drm has the same problem. so maybe some other reason lead to this. 
by the way, i try to use the minicap, it has the same problem

**Comment by skier-peng** [comment]
additional: i use software decode in my  media player, then the content would be displayed.

**Comment by skier-peng** [comment]
@rom1v hello，i read the mediacodec apurface uses native video buffers without mapping or copying them to ByteBuffers; thus, it is much more efficient. You normally cannot access the raw video data when using a Surface, but you can use the ImageReader class to access unsecured decoded (raw) video frames. This may still be more efficient than using ByteBuffers, as some native buffers may be mapped into ByteBuffer#isDirect ByteBuffers. When using ByteBuffer mode, you can access raw video frames using the Image class and getInput/OutputImage(int).

**Comment by rom1v** [comment]
Probably not, performance would not be good.
