### ISSUE TITLE
Build error (gradle?)

### ISSUE THREAD

**Issue by testbughub** [Genymobile/scrcpy#864]
Hi!

Sorry if this is a rookie question, but I can't seem to figure it out by myself.

So when I try to use ./release.sh, I get this error;

```
The Meson build system
Version: 0.49.2
Source dir: /home/lamarca/Downloads/scrcpy
Build dir: /home/lamarca/Downloads/scrcpy/build_test
Build type: native build
Project name: scrcpy
Project version: 1.10
Native C compiler: cc (gcc 8.3.0 "cc (Debian 8.3.0-6) 8.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29)
Dependency libavformat found: YES 58.20.100
Dependency libavcodec found: YES 58.35.100
Dependency libavutil found: YES 56.22.100
Dependency sdl2 found: YES 2.0.9
Configuring config.h using configuration
Program ./scripts/build-wrapper.sh found: YES (/home/lamarca/Downloads/scrcpy/server/./scripts/build-wrapper.sh)
WARNING: Project targetting '>= 0.37' but tried to use feature introduced in '0.48.0': console arg in custom_target
DEPRECATION: build_always is deprecated. Combine build_by_default and build_always_stale instead.
Build targets in project: 8
WARNING: Project specifies a minimum meson_version '>= 0.37' but uses features which were added in newer versions:
 * 0.48.0: {'console arg in custom_target'}
Found ninja-1.8.2 at /usr/bin/ninja
ninja: Entering directory `build_test'
[32/40] Generating scrcpy-server with a custom command.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':server'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/home/lamarca/Downloads/scrcpy/local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
[38/40] Linking target app/scrcpy.
FAILED: server/scrcpy-server.jar 
/home/lamarca/Downloads/scrcpy/server/./scripts/build-wrapper.sh /home/lamarca/Downloads/scrcpy/server server/scrcpy-server.jar debug
ninja: build stopped: subcommand failed.
```

Does anyone know why I get this error?
Any help is much appreciated!

**Comment by rom1v** [comment]
Where is your Android SDK installed?

Either set `ANDROID_SDK` or `ANDROID_SDK_ROOT` to its directory, or create a file `local.properties` in the scrcpy repo, containing:
```
sdk.dir=/path/to/your/android/sdk
```

**Comment by testbughub** [comment]
Oh I had forgotten to install the SDK. Oops!
Where is it located normally?

**Comment by testbughub** [comment]
Never mind, I had misunderstood how to get the SDK.
But I get another error now;
`The Meson build system
Version: 0.49.2
Source dir: /home/lamarca/Downloads/scrcpy
Build dir: /home/lamarca/Downloads/scrcpy/build_test
Build type: native build
Project name: scrcpy
Project version: 1.10
Native C compiler: cc (gcc 8.3.0 "cc (Debian 8.3.0-6) 8.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29)
Dependency libavformat found: YES 58.20.100
Dependency libavcodec found: YES 58.35.100
Dependency libavutil found: YES 56.22.100
Dependency sdl2 found: YES 2.0.9
Configuring config.h using configuration
Program ./scripts/build-wrapper.sh found: YES (/home/lamarca/Downloads/scrcpy/server/./scripts/build-wrapper.sh)
WARNING: Project targetting '>= 0.37' but tried to use feature introduced in '0.48.0': console arg in custom_target
DEPRECATION: build_always is deprecated. Combine build_by_default and build_always_stale instead.
Build targets in project: 8
WARNING: Project specifies a minimum meson_version '>= 0.37' but uses features which were added in newer versions:
 * 0.48.0: {'console arg in custom_target'}
Found ninja-1.8.2 at /usr/bin/ninja
ninja: Entering directory `build_test'
[32/40] Generating scrcpy-server with a custom command.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':server'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/home/lamarca/Downloads/scrcpy/local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 866ms
[38/40] Linking target app/scrcpy.
FAILED: server/scrcpy-server.jar 
/home/lamarca/Downloads/scrcpy/server/./scripts/build-wrapper.sh /home/lamarca/Downloads/scrcpy/server server/scrcpy-server.jar debug
ninja: build stopped: subcommand failed.`

**Comment by testbughub** [comment]
Never mind, I misunderstood how to get the SDK.
But I get another error now;
`[0/1] Generating scrcpy-server with a custom command.

> Configure project :server
File /home/lamarca/.android/repositories.cfg could not be loaded.
Checking the license for package Android SDK Build-Tools 28.0.3 in /home/lamarca/Documents/Android/licenses
Warning: License for package Android SDK Build-Tools 28.0.3 not accepted.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':server'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     build-tools;28.0.3 Android SDK Build-Tools 28.0.3
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
  
  Using Android SDK: /home/lamarca/Documents/Android

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
FAILED: server/scrcpy-server.jar 
/home/lamarca/Downloads/scrcpy/server/./scripts/build-wrapper.sh /home/lamarca/Downloads/scrcpy/server server/scrcpy-server.jar release
ninja: build stopped: subcommand failed.`

How do I accept the license agreement and get the missing components?

**Comment by rom1v** [comment]
https://stackoverflow.com/questions/39760172/you-have-not-accepted-the-license-agreements-of-the-following-sdk-components

(Note: use ``` for code blocks in GitHub comments)

**Comment by testbughub** [comment]
Ah, sorry. I'll remember that.
Well, no luck so far. I get a java error when I try to use ./sdkmanager --licenses.
I hope it's okay if I post it here:

```Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 5 more```

**Comment by testbughub** [comment]
Well, I got it to work by downloading the pre-built server.
Thanks for the help anyway!
