### ISSUE TITLE
Mouse Input OK, But PC touchscreen Fails

### ISSUE THREAD

**Issue by unclehowell** [Genymobile/scrcpy#865]
I haven't managed to get the PCs touchscreen to work, scrcpy doesn't recognise it's inputs, only the mouse clicks. Where do I even begin with this issue? Must I open up the server.jar file and fix it in there? I have a SurePOS 500 running the latest Ubuntu, with Elo Touch drivers and then I host Android on a Raspberry Pi, which is stuck to the side (connected via Ethernet, with the PC's wireless shared to the Ethernet). Curious how I get the Scrcpy window to detect mouse and touchscreen ???

**Comment by rom1v** [comment]
It's implemented on `dev` branch (and will be in the next release).

See #22.

**Comment by unclehowell** [comment]
champion.
