### ISSUE TITLE
Trying to reduce my bitrate

### ISSUE THREAD

**Issue by KxngLeoKaos** [Genymobile/scrcpy#868]
Im trying to input the command prompt to reduce bitrate but it keeps saying that its not an internal or external command 

Could you please take me step by step through the process

C:\Users\chrisana>scrcpy --bit-rate 2M
'scrcpy' is not recognized as internal or external command, operable program or batch file

**Comment by getutsav** [comment]
You are on windows, you will need to specify the entire path

scrcpy --bit-rate 2M 

should be 

scrcpy.exe --bit-rate 2M

**Comment by rom1v** [comment]
On Windows, you can call a command with or without an explicit `.exe`.

The problem is that you must call it from the scrcpy directory (`cd C:\path\to\scrcpy`), or add its directory in your `PATH`.
