### ISSUE TITLE
Scrcpy green screen 

### ISSUE THREAD

**Issue by WetWilly5** [Genymobile/scrcpy#869]
I connected my Galaxy s3 to scrcpy after updating to android 5.0. since it wouldn't work with previous version and I get a green screen when mirroring.  Tried different resolutions to no avail.  Any answers?

**Comment by rom1v** [comment]
If you record with `scrcpy -r record.mkv`, and play the file with VLC, is it still green?

What about:

    adb shell screenrecord /sdcard/file.mp4
    adb pull /sdcard/file.mp4

?

**Comment by HubDawn** [comment]
I have the same issue. Going to fullscreen fixes this.

**Comment by rom1v** [comment]
@HubDawn weird. What if you resize the window? I guess that if you record everything is ok when you play the recorded file.

@WetWilly5 does fullscreen fixes this for you too?

**Comment by Q-out** [comment]
I've got a green screen here too. Last it worked was on my PC with my 1+3 on Android 9, now I'm on a laptop with the phone updated to Android 10, so when I can get back on the PC I'll come back and confirm if it works or not there.

Otherwise so far I've tried lowering resolution/bitrate, going fullscreen, resizing the window, but nothing has worked yet. I can control the device through scrcpy properly, but the screen is green.

Both the recordings from `scrcpy -r record.mkv` and `adb shell screenrecord /sdcard/file.mp4` are green.

**Comment by rom1v** [comment]
> Both the recordings from scrcpy -r record.mkv and adb shell screenrecord /sdcard/file.mp4 are green.

OK, so it is probably a device issue (or a playback/driver issue on the computer).

**Comment by Q-out** [comment]
Ah, yeah, probably a device issue; It's not working on the PC either, where scrcpy is still v1.9 and not much else has changed since the last time it worked. Apart from the update to Android 10 on my phone.

**Comment by Q-out** [comment]
Just gonna pop in and say it's still the same green screen with v1.11.

**Comment by rosuH** [comment]
Same issues here.
- OnePlus 3T  Android 10 [LOS 16 Nightly](https://forum.xda-developers.com/oneplus-3/oneplus-3--3t-cross-device-development/rom-lineageos-16-0-oneplus-3-3t-t3866517)
- scrcpy-win64-v1.11 (Mac either.)

```shell
# The console show green screen but file.mp4 is not.
shell screenrecord /sdcard/file.mp4
```
```shell
# Both console and file.mp4 are green.
scrcpy -r record.mkv
```
I suspect it's a ROM problem, so I am flashing another ROM and  I will attach the follow-up results to this issues.

---
Thanks for your working.

**Comment by rosuH** [comment]
I've tried [PixelExperience with Android 9](https://forum.xda-developers.com/oneplus-3/oneplus-3--3t-cross-device-development/rom-pixel-experience-9-0-t3855763) but have same issues.
Seem like a device problem.

**Comment by Q-out** [comment]
Disabling "Tethering Hardware Acceleration" in Developer Options fixed it for me. @rosuH you might want to try that.

**Comment by rewchik** [comment]
I have same issue.
ADB logcat: 
01-06 22:02:10.037   529   529 I HwBinder:529_1: type=1400 audit(0.0:12290): avc: denied { read } for scontext=u:r:hal_sensors_default:s0 tcontext=u:r:hal_sensors_default:s0 tclass=socket permissive=1
01-06 22:02:10.055   523   683 E SDM     : HWDevice::Commit: ioctl MSMFB_ATOMIC_COMMIT, device = 2 errno = 22, desc = Invalid argument
01-06 22:02:10.055   523   683 I SDM     : HWDevice::DumpLayerCommit: mdp_commit: flags = 2000, release fence = ffffffff
01-06 22:02:10.055   523   683 I SDM     : HWDevice::DumpLayerCommit: left_roi: x = 0, y = 0, w = 0, h = 0
01-06 22:02:10.055   523   683 I SDM     : HWDevice::DumpLayerCommit: right_roi: x = 0, y = 0, w = 0, h = 0
01-06 22:02:10.055   523   683 I SDM     : HWDevice::DumpLayerCommit: layer = 0, pipe_ndx = 10, z = 0, flags = 4
01-06 22:02:10.055   523   683 I SDM     : HWDevice::DumpLayerCommit: src_width = 768, src_height = 1280, src_format = 13
01-06 22:02:10.055   523   683 I SDM     : HWDevice::DumpLayerCommit: src_rect: x = 0, y = 0, w = 720, h = 1280
01-06 22:02:10.055   523   683 I SDM     : HWDevice::DumpLayerCommit: dst_rect: x = 0, y = 0, w = 720, h = 1280
01-06 22:02:10.055   523   683 E SDM     : HWCDisplay::CommitLayerStack: Commit failed. Error = 11
01-06 22:02:10.069   523   683 E SDM     : HWDevice::Commit: ioctl MSMFB_ATOMIC_COMMIT, device = 2 errno = 22, desc = Invalid argument
01-06 22:02:10.069   523   683 I SDM     : HWDevice::DumpLayerCommit: mdp_commit: flags = 2000, release fence = ffffffff
01-06 22:02:10.069   523   683 I SDM     : HWDevice::DumpLayerCommit: left_roi: x = 0, y = 0, w = 0, h = 0
01-06 22:02:10.069   523   683 I SDM     : HWDevice::DumpLayerCommit: right_roi: x = 0, y = 0, w = 0, h = 0
01-06 22:02:10.069   523   683 I SDM     : HWDevice::DumpLayerCommit: layer = 0, pipe_ndx = 10, z = 0, flags = 4
01-06 22:02:10.069   523   683 I SDM     : HWDevice::DumpLayerCommit: src_width = 768, src_height = 1280, src_format = 13
01-06 22:02:10.069   523   683 I SDM     : HWDevice::DumpLayerCommit: src_rect: x = 0, y = 0, w = 720, h = 1280
01-06 22:02:10.069   523   683 I SDM     : HWDevice::DumpLayerCommit: dst_rect: x = 0, y = 0, w = 720, h = 1280
01-06 22:02:10.069   523   683 E SDM     : HWCDisplay::CommitLayerStack: Commit failed. Error = 11

P.S. I see this only when start scrcpy :)

**Comment by JxM-92** [comment]
Hey, idk if someone got to fix this, but I fixed this by accident...
idk why, but if the screen is green then you have to start scrcpy with "-m 1024" or some multiplier of it, like 512, 2048, 4096, etc...
idk why it is like that, I found this by randomly using 512 and then trying 1024...

**Comment by newillusion** [comment]
I have same issue with small difference:
When device screen come to off, i can see normal translation about 0.1s, after that window become black. When device screen on, black window become green.

If record it to video file, in file will be the same - green lit, 3 frame of normal image, and black lit.

**Comment by JxM-92** [comment]
> Hey, idk if someone got to fix this, but I fixed this by accident...
> idk why, but if the screen is green then you have to start scrcpy with "-m 1024" or some multiplier of it, like 512, 2048, 4096, etc...
> idk why it is like that, I found this by randomly using 512 and then trying 1024...

I have to add, that this works fine but it won't work if you go higher than what the maximum phone resolution, so I suggest using 1024 or 2048 if your phone's resolution is higher than that, you gotta check that out...

**Comment by monees007** [comment]
I was getting the error in windows 10 tablet mode. ( This mode opens everything in full screen ) Problem solved on going back to desktop mode.
