### ISSUE TITLE
How do I reduce bitrate for scrcpy wireless

### ISSUE THREAD

**Issue by KxngLeoKaos** [Genymobile/scrcpy#870]
i try the code but it says scrcpy is not an internal or external command....

Could you please give me a solution step by step?

**Comment by rom1v** [comment]
1. Open a console (`cmd.exe`)
2. Go to your scrcpy directory (`cd C:\path\of\scrcpy`)
3. Run `scrcpy -b 4M` (for a bitrate of 4M).
