### ISSUE TITLE
Use scrcpy on Android

### ISSUE THREAD

**Issue by qdtjvszxc** [Genymobile/scrcpy#873]
There's a Magisk module for ADB & Fastboot: [https://github.com/Magisk-Modules-Repo/adb-ndk](url). I can control other another Android device (like Android TV box) using adb on my Android phone. 
I can also use adb in linux chroot on Android. But it's hard to run service which is needed for scrcpy.
Is it possible to make scrcpy work as a Magisk module on android? If so, it will be a Android TV Remote Control.

**Comment by rom1v** [comment]
(see #100)
