### ISSUE TITLE
not working with OS Catalina

### ISSUE THREAD

**Issue by amaddocks** [Genymobile/scrcpy#876]
Upgraded to Catalina now on launching the app OS says --''adb'' cannot be opened because the developer cannot be verified. macOS cannto verify that this app is free from malware--  
I have the latest version presumably as I downloaded 30 Aug '19.

**Comment by rom1v** [comment]
Did you install it from homebrew?

**Comment by amaddocks** [comment]
Yes it was all working fine with Mojave till I upgraded to Catalina

**Comment by djallberto** [comment]
I managed to fix this: `cd /usr/local/Caskroom/android-platform-tools/29.0.5/platform-tools && open .`. Then right-click on adb, press `Open` and this time, you can click `Open` instead of `Move to Bin`

**Comment by amaddocks** [comment]
doesn't work - I'm not able to right click on adb when launching the app. I only have "move to bin" or "cancel" options. I don't understand your file path. If I put that file path into terminal it does not recognise it. Could you / anyone help on this ?

**Comment by djallberto** [comment]
@amaddocks probably it depends on how you installed adb. Did you use `brew`? Try finding where `adb` is installed on your machine and right click on it

**Comment by amaddocks** [comment]
Thanks. I installed the latest version and reinstalled ADB but now I get this message. Any ideas / help is much appreciated:

2019-12-01 14:59:09.872 scrcpy[96226:232670] INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: more than one device/emulator
2019-12-01 14:59:09.880 scrcpy[96226:232670] ERROR: "adb push" returned with value 1
Admins-Mac-mini:~ admin$

**Comment by rom1v** [comment]
There are probably several devices listed in `adb devices`.

You can run scrcpy for a specific one with:

    scrcpy -s SERIAL

> I installed the latest version

The latest is currently 1.11, not 1.10 (but independant of your problem).

**Comment by amaddocks** [comment]
Thanks - how do I remove one of the devices (this would be the simpler way
as I won't be using the first device I installed)

**Comment by amaddocks** [comment]
ok I just unplugged the other device and yay it works again !! Thanks for all your help !!

**Comment by vicfonoma** [comment]
for me worked if make an upgrade to adb

**Comment by DennisOosterling** [comment]
For future people having the same issue.
`brew cask upgrade android-platform-tools` did the trick for me.

**Comment by TheSidhesh** [comment]
I tried installing adb through brew and through platform-tools directly and both dont work for me. I still get the same error: “adb” cannot be opened because the developer cannot be verified.

I see two buttons "Move to trash" and "Cancel".

**Comment by AlexandraBeautyman** [comment]
> for me worked if make an upgrade to adb

How do you do that?

**Comment by aarkalyk** [comment]
For anyone wondering how to solve this, right after you run the command, without closing the "Move to bin or cancel" dialog box, open `System Preferences` -> `Security & Privacy` -> `General` -> 
in `Allow apps downloaded from` section hit `Open anyway`. Run the command again, and hit `Open` in the dialog box.

**Comment by hasansidd** [comment]
for me i had to go into security and privacy and give full disk access to android studio and adb

**Comment by ubaidillahSriyudi** [comment]
> I managed to fix this: `cd /usr/local/Caskroom/android-platform-tools/29.0.5/platform-tools && open .`. Then right-click on adb, press `Open` and this time, you can click `Open` instead of `Move to Bin`

thanks it works

**Comment by nsjcorps** [comment]
> brew cask upgrade android-platform-tools

This worked for me. Thanks!

**Comment by nihp** [comment]
I have installed androidsdk and it is in the path /usr/local/Caskroom/android-sdk/4333796/.


Inside the platform-tools I have found adb. /usr/local/Caskroom/android-sdk/4333796/platform-tools.

How can i open the emulator.

“emulator” cannot be opened because the developer cannot be verified.
macOS cannot verify that this app is free from malware.
![Screenshot 2020-07-29 at 10 42 23 AM](https://user-images.githubusercontent.com/36992338/88759370-42852180-d188-11ea-97f1-b3fd4ff7de7a.png)

**Comment by aaltotsky** [comment]
@nihp Did you find any solutions for the "emulator" issue? I have the same error on Catalina.

**Comment by nihp** [comment]
I have removed and again installed android studio and created new emulator.
