### ISSUE TITLE
Cannot Change High DPI Scaling by using command in FAQ

### ISSUE THREAD

**Issue by getutsav** [Genymobile/scrcpy#877]
Hello,
The FAQ lists using 

scrcpy.exe > Properties > Compatibility > Change high DPI settings > Override high DPI scaling behavior > Scaling performed by: Application 

to change the scaling behavior but when I put in the command in the prompt I get an error saying 

C:\Users\U\Desktop\scrcpy-win64-v1.10>scrcpy.exe > Properties > Compatibility > Change high DPI settings > Override high DPI scaling behavior > Scaling performed by: Application
ERROR: Unexpected additional argument: high

What do I do to fix this ?

**Comment by getutsav** [comment]
![image](https://user-images.githubusercontent.com/6811749/67272425-227a5080-f4da-11e9-8d8f-57328818de17.png)

**Comment by rom1v** [comment]
> ```
> scrcpy.exe > Properties > Compatibility > Change high DPI settings > Override high DPI scaling behavior > Scaling performed by: Application
> ```

This is not the command to type, it's just a list of menus to click.

On `scrcpy.exe`, (probably) right-click, there should be a menu `Properties`, etc… (I don't have a Windows to check).

**Comment by getutsav** [comment]
Aah my bad, I did all that but my display still looks the same as before :(

**Comment by rom1v** [comment]
> This is what it looks like right now and changing the bitrate does nothing

Did you reduce the definition or just resized the window?

You could try if the result is better with:

    scrcpy -m800

**Comment by rom1v** [comment]
(see #40)
