### ISSUE TITLE
macOS Shortcuts changes

### ISSUE THREAD

**Issue by mtvg** [Genymobile/scrcpy#880]
A recent change in `scrcpy` moved `Ctrl-` based shortcuts to `Cmd-` based shortcuts, with a few exceptions: `Ctrl-M` and `Ctrl-H`. This is a very confusing choice as it is hard to remember which shortcut uses `Ctrl` vs `Cmd`. I often accidentally hide (`Cmd-H`) or minimize (`Cmd-M`) my window. 

Is it possible to override the system defaults and use `Cmd-` across all `scrcpy` shortcuts, either by default or optional? Applications like Photoshop have this option for users.

**Comment by rom1v** [comment]
I don't know if SDL can receive Cmd+H or Cmd-M. See https://github.com/Genymobile/scrcpy/pull/676#issuecomment-517260539

**Comment by mtvg** [comment]
Thanks for your answer. I looked a bit into it and seems like Cmd-M should be easily solvable by modifying the NSMenu after SDL initialization, but haven't found a path for Cmd-H yet. Will keep digging to see how other applications like Photoshop are doing it.

**Comment by rom1v** [comment]
Please give your opinion on #1446 :wink:
