### ISSUE TITLE
mouse does not working in black desert mobile

### ISSUE THREAD

**Issue by skemayam** [Genymobile/scrcpy#881]
phone control and other game is working fine but for this particular game it does not register mouse click

**Comment by rom1v** [comment]
Maybe because the game does not react to mouse events?

**Comment by skemayam** [comment]
> Maybe because the game does not react to mouse events?

but when i use right click, it shows a windows asking want to leave the game or not. any add on to solve this?

**Comment by skemayam** [comment]
vysor click working fine for this game

**Comment by rom1v** [comment]
> i use right click, it shows a windows asking want to leave the game or not

Because right click sends BACK to the device, not a click.

> vysor click working fine for this game

Hmm, interesting.

**Comment by rom1v** [comment]
Ref #635.

Just fixed it on `master` by 17d53be3ef9d376e48a7f9e90cf6c87cf8fbf8f5.
