### ISSUE TITLE
Checking ADB connection on Android device

### ISSUE THREAD

**Issue by dilbert168** [Genymobile/scrcpy#882]
I have the scrcpy setup and working over WiFi to Android device.
Now I have a question, is there a way (API) on Android "scrcpy-master" 
- check the status of the "scrcpy" has ran and displayed ?
- check data transport performance ?

Any reference code would be excellent.  Thanks so much

**Comment by rom1v** [comment]
> check the status of the "scrcpy" has ran and displayed ?

#153 ?

> check data transport performance ?

There's nothing implemented for that.

**Comment by dilbert168** [comment]
I try to see the flow of the code on Android using the logcat but nothing show for scrcpy when connected.  Something I done wrong ?

  adb logcat -s scrcpy

**Comment by rom1v** [comment]
> I try to see the flow of the code on Android using the logcat but nothing show for scrcpy when connected

There are only few log messages on the device-side. Btw, they are also printed into the console.

You could try to copy some text from your computer (Ctrl+C), then Ctrl+Shift+V in the scrcpy window, it sets the clipboard and logs at INFO level.

**Comment by dilbert168** [comment]
Thanks.  See logcat message using your method.

As for my question, I went through #153 and couldn't find the method to check for device "connected" to desktop.  In #575, you stated there isn't a method, correct ?

**Comment by rom1v** [comment]
No, there is nothing to notify some app that scrcpy is running.
