### ISSUE TITLE
Scrcpy Crashing A Few Seconds After Launching

### ISSUE THREAD

**Issue by 2635599** [Genymobile/scrcpy#883]
i've been running the snap of scrcpy for several months now without issue, but today every time i launch scrcpy after only a few seconds it crashes. i'm not getting any error message when it does. i just switched to edge to see if that might resolve the issue and it didn't. i've added vysor back to chrome to see if that would also crash or stay stable and it works fine. 

kubuntu 19.04 kernel 5.2.1 64 bit
phone: moto e5 play

**Comment by rom1v** [comment]
Try with another USB cable or plug it into another USB port.

See #281 #283.

**Comment by 2635599** [comment]
YEA u da man, LOL.

looks like changing the port did the trick. thanks
