### ISSUE TITLE
Error on windows 10

### ISSUE THREAD

**Issue by NGgeek** [Genymobile/scrcpy#884]
I am trying to use this for streaming but i got the error 
"adb server version (31) doesn't match this client (41); killing...
could not read ok from ADB Server
* failed to start daemon
adb.exe: failed to check server version: cannot connect to daemon"
when I run adb devices

**Comment by rom1v** [comment]
Find the program on your computer which uses adb 31, and replace its adb with v41.

**Comment by NGgeek** [comment]
How do I do that on Windows?

**Comment by acamanezZz** [comment]
Hi...
i m using win10 too..
n this is what i got from c:prompt when i tried activate scrcpy:

C:\adb>adb devices
List of devices attached
* daemon not running; starting now at tcp:5037
* daemon started successfully
G**********KUC device


C:\adb>scrcpy
scrcpy-server.jar: 1 file pushed. 0.3 MB/s (19342 bytes in 0.063s)
error: closed
ERROR: "adb reverse --remove" returned with value 1
Invalid return value 0 for stream protocol
INFO: Initial texture: 720x1280
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
ERROR: Could not open video stream
WARN: Cannot terminate server

C:\adb>

I m unsure where to put my problem n who can help, but i trust this community could give me some pointers i think n sori to use yr issue NGgeek to hilite mine...
thx for the advice(s) in advance

**Comment by rom1v** [comment]
Does your device have at least Android 5?

**Comment by acamanezZz** [comment]
yes... it's android 7.0



*Mohd Azli Nordin,*
*012-2959 357*
*MACROTECH SOLUTION SDN BHD*
*man.macrotech@gmail.com <man.macrotech@gmail.com>*

**Comment by acamanezZz** [comment]
and ive tried using win 32bit and 64bit.. both same errors



*Mohd Azli Nordin,*
*012-2959 357*
*MACROTECH SOLUTION SDN BHD*
*man.macrotech@gmail.com <man.macrotech@gmail.com>*

**Comment by acamanezZz** [comment]
and yr response is highly appreciated...



*Mohd Azli Nordin,*
*012-2959 357*
*MACROTECH SOLUTION SDN BHD*
*man.macrotech@gmail.com <man.macrotech@gmail.com>*

**Comment by rom1v** [comment]
You could check: https://stackoverflow.com/questions/31525431/getting-error-closed-twice-on-adb-reverse

**Comment by rom1v** [comment]
> How do I do that on Windows?

I don't know. What program do you use could use an old adb version?

Find `adb` in the list of processes. (I don't know Windows very well, google it)
