### ISSUE TITLE
Remote support

### ISSUE THREAD

**Issue by gadgadskiy** [Genymobile/scrcpy#89]
Hi!
Do you support any remote abilities to use scrcpy?
For example I have PC with connected android device and and another PC in the same local network. Can I view this device via scrcpy from another PC?

**Comment by rom1v** [comment]
Duplicate of https://github.com/Genymobile/scrcpy/issues/5.

See https://www.genymotion.com/blog/open-source-project-scrcpy-now-works-wirelessly/.
