### ISSUE TITLE
Request: option to force Ctrl+O whenever using scrcpy

### ISSUE THREAD

**Issue by KeronCyst** [Genymobile/scrcpy#891]
Like a command line or something.

**Comment by rom1v** [comment]
```
scrcpy --turn-screen-off
```

**Comment by KeronCyst** [comment]
Sweet!

**Comment by KeronCyst** [comment]
I tried it and it didn't work. As in, I let the phone idle a long time, and then I unlocked it, and then the screen went on again. Am I doing this right?

`...\scrcpy-win64-v1.10\scrcpy.exe -noconsole --turn-screen-off`

**Comment by TrackLiao** [comment]
Would you mind adding a new hotkey e.g Ctrl + L, that execute Ctrl + P, pause 0.5 second, then Ctrl + O ? In this way I believe wake up with screen off (on for less than a second) will works and save the phone's battery, thank you
