### ISSUE TITLE
Request: Support Multiple Devices

### ISSUE THREAD

**Issue by jayshin** [Genymobile/scrcpy#894]
Is there any plan to support multiple devices?

For example, if there are two connected devices, scrcpy shows the list of devices first then shows the device in a separated screen by clicking an item of the list.

**Comment by rom1v** [comment]
You can run several _scrcpy_ and specify the serial of the devices (as displayed by `adb devices`):

```
scrcpy -s 0123456789abcdef
scrcpy -s fedcba9876543210
```
