### ISSUE TITLE
Where do the scrcpy log files get written?

### ISSUE THREAD

**Issue by RogerPAlexander** [Genymobile/scrcpy#895]
I've been trying to change the scrcpy app icon (mac OS Dock icon) by altering icon_xpm.  There are SDL LOGE / LOGW etc statements throughout the code, but I simply  I cannot find the log files where these error messages are written!  makes debugging difficult.

**Comment by rom1v** [comment]
By default, they are just printed to `stdout`/`stderr` (the console).

https://github.com/Genymobile/scrcpy/blob/master/app/src/log.h
