### ISSUE TITLE
Open multiple instances at once

### ISSUE THREAD

**Issue by AtomBis** [Genymobile/scrcpy#897]
Please excuse my noobness. I've got a batch file to run 5 instances of scrcpy from Oculus Go's. It opens the first scrcpy window fine but will only open the second window after I close the first. This continues, only opening the next window when I close the previous one.
Works fine when running each from separate a cmd window.

**Comment by rom1v** [comment]
I'm not expert at Windows batches scripts, but probably just use `START`:
```bat
START scrcpy -s serial1
START scrcpy -s serial2
```

**Comment by AtomBis** [comment]
That did it!

Thanks

**Comment by cee3xc** [comment]
how about for linux? (debian)

**Comment by rom1v** [comment]
On linux, add `&` tonrun a command in background:

```bash
command &
```

**Comment by cee3xc** [comment]
face-palm...i had been looking thru the man pages and yea anyway ty, its nice bc with the tint2 panel having 2 workspaces in boron its nice to be able to see my phone if i switch workspaces....

**Comment by James4Ever0** [comment]
You can open multiple instances for multiple applications with stored session in SWM.

Check out here: https://github.com/james4ever0/swm
