### ISSUE TITLE
LG G6 Problem

### ISSUE THREAD

**Issue by alexflex2000** [Genymobile/scrcpy#899]
Hi and thanks for this very nice project ! 
I can't figure out how to make it work on my LG G6.
No miror screen appears. No error message.
Win 10 / Android 8.0
Running the compiled version for WIN 32 / WIN 64
USB Debugging ON
BUT,  unnable to find other option like "USB debugging (security sttings) Allow granting permissions and simulating input..."

Thanks for your help
Alex

**Comment by rom1v** [comment]
What text do you see in your console?

Also check the output of `adb logcat` for errors when you start scrcpy.

**Comment by alexflex2000** [comment]
Thanks for your aswer.
I just get  the normal response like :
C:\Users\master\Downloads\scrcpy-win32-v1.10\scrcpy-server.jar: 1 file pushed. 10.7 MB/s (22546 bytes in 0.002s)  (and waitting...) 

and concerning the adb logcat, I get that : 
11-01 16:55:36.190  2028  2028 I dhcpcd  : eth0: renewing lease of 192.168.147.128
11-01 16:55:36.190  2028  2028 I dhcpcd  : eth0: sending REQUEST (xid 0x2b5586cb), next in 3.2 seconds
11-01 16:55:36.190  2028  2028 I dhcpcd  : eth0: received ACK with xid 0x2b5586cb
11-01 16:55:36.190  2028  2028 I dhcpcd  : eth0: acknowledged 192.168.147.128 from 192.168.147.254
11-01 16:55:36.314 29544 29544 I sh      : [root] Hostonly IP: 192.168.147.128
11-01 16:55:36.325 29550 29550 I /system/etc/init.andy.eth0.sh: [root] Hostonly IP: 192.168.147.128 
11-01 16:55:36.368 29544 29544 I sh      : [root] Hostonly Gateway: 192.168.147.1
11-01 16:55:36.377 29556 29556 I /system/etc/init.andy.eth0.sh: [root] Hostonly Gateway: 192.168.147.1 
11-01 16:55:36.382 29544 29544 I sh      : PING 192.168.147.1 (192.168.147.1) from 192.168.147.128 eth0: 56(84) bytes of data.
11-01 16:55:36.382 29544 29544 I sh      : 64 bytes from 192.168.147.1: icmp_seq=1 ttl=128 time=0.286 ms
11-01 16:55:36.386 29544 29544 I sh      : [root] 192.168.147.1 through eth0: REACHABLE
11-01 16:55:36.395 29562 29562 I /system/etc/init.andy.eth0.sh: [root] 192.168.147.1 through eth0: REACHABLE 
11-01 16:55:36.403 29544 29544 I sh      : [root] 192.168.147.1 through eth0: added to legacy_system
11-01 16:55:36.413 29566 29566 I /system/etc/init.andy.eth0.sh: [root] 192.168.147.1 through eth0: added to legacy_system 

Do you see something wrong ?
Thanks
A.

**Comment by rom1v** [comment]
You just copied 14 lines of your `adb logcat` output, there are probably thousands…

Don't paste them, but just check if some more errors are logged happen when you start scrcpy.

**Comment by alexflex2000** [comment]
Thank you so much for your help !
It was my fault : I studied the logs and found that I had a conflict with an Android emulator (Andy) 
and the scrcpy  file was sent to the wrong device. Silly mistake.
It is now working very well
Thanks again for your time and help.
A.
