### ISSUE TITLE
Windows portable : no result while running the executable

### ISSUE THREAD

**Issue by pyluyten** [Genymobile/scrcpy#9]
Running the app on Windows using the pre-compiled version, does not display any device screen, and actually does not display anything at all.

**Comment by rom1v** [comment]
If you open a `cmd.exe` and go to the _scrcpy_ directory, what is the result of `adb devices` (while your device is plugged)?

**Comment by pyluyten** [comment]
it says "List of devices attached", but i do not see any result (looking in scrcpy directory - maybe i should look elsewhere)

**Comment by rom1v** [comment]
OK, so that's the problem: your device is not detected by adb.

Did you enable "USB debugging"? Maybe some [driver](https://developer.android.com/studio/run/win-usb.html) is needed for your device?

**Comment by pyluyten** [comment]
"USB debugging" is already enabled. Unfortunately i will not be able to test installation of driver on this computer. Maybe someone else can reproduce issue

**Comment by redwolf2** [comment]
@pyluyten You need to install the adb driver in order to connet. Then you should see the plugged device using `adb devices`. https://developer.android.com/studio/run/oem-usb.html

**Comment by AHrubik** [comment]
@pyluyten Also make sure the device isn't in Media Transfer mode (MTP). Set it to charge only.

**Comment by pyluyten** [comment]
I do not have admin rights on this workstation, so i think the oem-usb cannot be installed. I think you might close the issue, and as soon as i have another windows workstation where i can install driver i will check with this one.

Maybe should i open another issue because there is not output in cmd (scrcpy should tell me no device was found by adb)

**Comment by banjaloupe** [comment]
I had this same issue and installing the drivers appeared to be the solution:

1. Installing the appropriate drivers/software from the page redwolf2 linked above: https://developer.android.com/studio/run/oem-usb.html
2. Using "adb devices" now starts the daemon and listed the phone-- mine was initially unauthorized, so I had to agree to a modal pop-up on the phone's screen (which allows me to set the computer as trusted).
3. Running scrcpy.exe after this brings up the phone's screen as expected.

**Comment by rom1v** [comment]
Since the portable binary does not display output (unless run in MSYS2), always check that `adb devices` detect your device before trying _scrcpy_ (at least until we find a solution so that the binary built is MSYS2 print output when run in `cmd.exe`).

**Comment by emansih** [comment]
I am having the same issue. Running on Windows 10

Running from cmd.exe
```
C:\Users\User\Downloads\scrcpy-windows-with-deps-v1.0\scrcpy-windows-v1.0>adb kill-server

C:\Users\User\Downloads\scrcpy-windows-with-deps-v1.0\scrcpy-windows-v1.0>scrcpy.exe

C:\Users\User\Downloads\scrcpy-windows-with-deps-v1.0\scrcpy-windows-v1.0>adb devices
List of devices attached
<snip>      device

```

Running from mingw64 gives a slightly more detailed output albeit a short one.

```
MINGW64 ~/Downloads/scrcpy-windows-with-deps-v1.0/scrcpy-windows-v1.0
$ ./scrcpy.exe
ERROR: "adb reverse" returned with value 1

MINGW64 ~/Downloads/scrcpy-windows-with-deps-v1.0/scrcpy-windows-v1.0
$ adb devices
List of devices attached
<snip>      device
```

**Comment by rom1v** [comment]
>     ERROR: "adb reverse" returned with value 1

Is it Android >= 5?

**Comment by emansih** [comment]
yes, it running Android 7.0

**Comment by rom1v** [comment]
OK. Then, what is the result of:

    adb reverse localabstract:scrcpy tcp:1234

?

**Comment by emansih** [comment]
interesting... 

```
C:\Users\User\Downloads\scrcpy-windows-with-deps-v1.0\scrcpy-windows-v1.0>adb kill-server

C:\Users\User\Downloads\scrcpy-windows-with-deps-v1.0\scrcpy-windows-v1.0>adb reverse localabstract:scrcpy tcp:1234
* daemon not running; starting now at tcp:5037
* daemon started successfully
error: more than one device/emulator

C:\Users\User\Downloads\scrcpy-windows-with-deps-v1.0\scrcpy-windows-v1.0>adb devices
List of devices attached
<snip>      device
```

**Comment by rom1v** [comment]
Is your device connected using `adb connect`? https://github.com/Genymobile/scrcpy/issues/5

**Comment by emansih** [comment]
yikes, it was previously running adb connect.(i did kill adb server on my pc though) toggling adb works. thanks!

**Comment by konatachan** [comment]
I have the same issue, but my ADB sees the device



```
C:\Users\Ni\Desktop\scrcpy-windows-v1.0
λ adb devices
List of devices attached
16c9a4dc        device

C:\Users\Ni\Desktop\scrcpy-windows-v1.0
λ scrcpy

C:\Users\Ni\Desktop\scrcpy-windows-v1.0
λ

```

**Comment by aezaekill** [comment]
Hi,
i have the same issue using my Windows 10 PC and Pixel 2 XL.

"adb devices" shows the device:
List of devices attached
710KPX**********  device

"adb reverse localabstract:scrcpy tcp:1234" leads to:
* daemon not running; starting now at tcp:5037
* daemon started successfully

"scrcpy" does nothing at all.
Is there a verbose mode or a logfile i could provide to support further investigation of the problem?

Regards and thanks for your help.

**Comment by rom1v** [comment]
> Is there a verbose mode or a logfile i could provide to support further investigation of the problem?

In theory, `scrcpy` prints some output on _stdout_ (in the console).

There is a problem with the Windows version when started in a `cmd.exe` though: it prints nothing. I don't know why yet.

However, if you run the very same `scrcpy.exe` from [MSYS2](https://www.msys2.org/) (`mingw64`), then it correctly prints output. If `scrcpy` does not work, it may help to know why.

**Comment by aezaekill** [comment]
I already tried running it using a Git-Bash. This results in the following:

```
usr@PC MINGW64 /d/Downloads/scrcpy-windows-v1.0
$ adb devices
List of devices attached
adb server is out of date.  killing...
* daemon started successfully *
710KPXV*****  device

usr@PC MINGW64 /d/Downloads/scrcpy-windows-v1.0
$ ./scrcpy.exe
```

After that bash is waiting but it seems like it is not responding anymore.

**Comment by rom1v** [comment]
> I already tried running it using a Git-Bash

So there is no output in git bash :( You should have output on MSYS2…

> Got it! It is working now.

:+1:

**Comment by dasmaera** [comment]
I've had a very similar issue when attempting to run scrcpy for the first time on two computers that were not authorized for debug access. Once approved via the trust access dialog on the phone, nothing happens but adb.exe is left running and on my first attempt scrcpy.exe was also still running with no visible UI. 

It worked as intended after killing / restarting the executable.

**Comment by Ruhul768** [comment]
Ruhul768

**Comment by TheInitializer** [comment]
I'm having the same issue...

```
$ ./scrcpy.exe
ERROR: "adb reverse" returned with value 1
WARN: 'adb reverse' failed, fallback to 'adb forward'

$
```

I'm trying to connect over WiFi as the USB connection with this device is hard to get to work.

**Comment by rom1v** [comment]
@TheInitializer Your issue is probably more related to https://github.com/Genymobile/scrcpy/issues/5#comment-373688710. Could you test with the current `master` version?

**Comment by Monaasada** [comment]
#فیلم_سکسی_جدید👇👇

#کانال_سکسی_شهوانی #فیلم_سوپر
#کانال_شهوانی #داستان_سکسی
#شهوانی #الکسیس #جنده #خوشگل
#سکس_شهوانی #اهنگ #جدید 
#غمگین #کس #کون. #کتاب
#کانال_سکسی #کم_سن. #محله #خبر
#کانال_فیلم_سکسی #SEX
#کانال_فیلم_سوپر #فوتبال
#کانال_پورن  #احمدوند
#کانال_داستان_سکسی
@film_sckse
@film_sckse
@film_sckse
https://t.me/joinchat/AAAAAFD3pbOaZHeFHUxrYg
https://t.me/joinchat/AAAAAFD3pbOaZHeFHUxrYg
https://t.me/joinchat/AAAAAFD3pbOaZHeFHUxrYg
https://t.me/joinchat/AAAAAFD3pbOaZHeFHUxrYg
https://t.me/joinchat/AAAAAFD3pbOaZHeFHUxrYg

**Comment by Monaasada** [comment]
#فیلم_سکسی_جدید👇👇

#کانال_سکسی_شهوانی #فیلم_سوپر
#کانال_شهوانی #داستان_سکسی
#شهوانی #الکسیس #جنده #خوشگل
#سکس_شهوانی #اهنگ #جدید 
#غمگین #کس #کون. #کتاب
#کانال_سکسی #کم_سن. #محله #خبر
#کانال_فیلم_سکسی #SEX
#کانال_فیلم_سوپر #فوتبال
#کانال_پورن  #احمدوند
#کانال_داستان_سکسی
https://telegram.me/joinchat/AAAAAFD3pbOaZHeFHUxrYg
https://telegram.me/joinchat/AAAAAFD3pbOaZHeFHUxrYg
https://telegram.me/joinchat/AAAAAFD3pbOaZHeFHUxrYg
https://telegram.me/joinchat/AAAAAFD3pbOaZHeFHUxrYg

**Comment by Monaasada** [comment]
#فیلم_سکسی_جدید👇👇

#کانال_سکسی_شهوانی #فیلم_سوپر
#کانال_شهوانی #داستان_سکسی
#شهوانی #الکسیس #جنده #خوشگل
#سکس_شهوانی #اهنگ #جدید 
#غمگین #کس #کون. #کتاب
#کانال_سکسی #کم_سن. #محله #خبر
#کانال_فیلم_سکسی #SEX
#کانال_فیلم_سوپر #فوتبال
#کانال_پورن  #احمدوند
#کانال_داستان_سکسی
https://telegram.me/joinchat/AAAAAFD3pbOaZHeFHUxrYg
https://telegram.me/joinchat/AAAAAFD3pbOaZHeFHUxrYg
https://telegram.me/joinchat/AAAAAFD3pbOaZHeFHUxrYg
https://telegram.me/joinchat/AAAAAFD3pbOaZHeFHUxrYg

https://www.instagram.com/film_sckse/
https://www.instagram.com/film_sckse/
https://www.instagram.com/film_sckse/

**Comment by rom1v** [comment]
I added a workaround in the [FAQ](https://github.com/Genymobile/scrcpy/blob/9cac38fe589070085b411859141e4af196154124/FAQ.md#on-windows-i-have-no-output-in-the-console), this may be useful to find the cause in case of errors.

**Comment by PanCrucian** [comment]
One more note. If more than 1 android devices are connected to your PC, then manually "adb connect" (which device u need)
