### ISSUE TITLE
Update 1.1

### ISSUE THREAD

**Issue by ssmalan94** [Genymobile/scrcpy#90]
how to update to 1.1 in Mac?
"brew upgrade scrcpy" is not working

**Comment by rom1v** [comment]
How did you install it initially?

If you compiled it manually as explained in the README, you need to `git fetch && git checkout v1.1`, then recompile.

If you used the [prebuilt server](https://github.com/Genymobile/scrcpy#prebuilt-server), download the new one. If its path is not the same, execute:

    mesonconf x -Dprebuilt_server=/path/to/scrcpy-server.jar

**Comment by ssmalan94** [comment]
how to recompile?
Checked out the latest branch

**Comment by rom1v** [comment]
> how to recompile?

```bash
cd x
ninja
sudo ninja install
```

(https://github.com/Genymobile/scrcpy/blob/master/README.md#common-steps)

**Comment by ssmalan94** [comment]
Did...:)

**Comment by ssmalan94** [comment]
Working fine. Thanks
