### ISSUE TITLE
adb.exe: error: more than one device/emulator

### ISSUE THREAD

**Issue by aria-dev** [Genymobile/scrcpy#900]
I've connect my device via TCPIP at 5555 port.

Result of `adb devices`
```
adb devices
List of devices attached
192.168.0.107:5555      device
```

Device IP: `192.168.0.107:5555`

Running `scrcpy` gives the result: 
```
INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
D:\scrcpy\scrcpy-server.jar: 1 file pushed. 1.6 MB/s (22546 bytes in 0.013s)
adb.exe: error: more than one device/emulator
ERROR: "adb reverse" returned with value 1
WARN: 'adb reverse' failed, fallback to 'adb forward'
27183
INFO: Initial texture: 720x1280
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
Press any key to continue...
```

I tried using `scrcpy -s 192.168.0.107:5555` as the ip address was returned as the device serial when using `adb devices`

Which gave the same issue.

Then I used  `adb shell getprop ro.serialno` to get my device's serial no ; `8HUW4HV4Y9SSR4S8`

Then with this new serial no I tried: `scrcpy -s 8HUW4HV4Y9SSR4S8` which gave a new error:

```
INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: device '8HUW4HV4Y9SSR4S8' not found
ERROR: "adb push" returned with value 1
Press any key to continue...
```

This might be because the device is not connected via usb and the default serial returned is the Local ip address.

I've tried all previous solutions. Did not work.

**Comment by rom1v** [comment]
The message `more than one device or emulator` is "expected" over wifi (see #5). This is not your real error here.

Does it work over USB?

**Comment by SowingFiber** [comment]
Yes, it does work over USB. Alternatively, I've tried this using a different phone and it worked without a hitch. But for the phone I want to test, with, I am getting issues.

**Comment by rom1v** [comment]
This very same device works over USB?

Check the output of `adb logcat` when you start scrcpy for this device.

**Comment by SowingFiber** [comment]
No, not the same device. I’ll comment soon with the logcat.

**Comment by chopin2712** [comment]
First, try to restart your computer and retry the command `scrcpy`

If the problem still occurs, the following should works:

1. Make sure `adb` is installed
2. Run `adb devices` to get the list of devices
3. Copy your device ID
4. Run `scrcpy -s ID` just replace ID by your device's name you copied above.

The problem should be solved this way.

**Comment by wazerstar** [comment]
I'm not sure why I had so many problems AFTER reformatting machine, would give me the same problems, even tho giving the serial ID it would never work.

I use this and works everytime on my windows session to adb android

Starting mass kill and disconnect and adding a few breaks did it all for me.

```
adb kill-server
adb kill-server
adb kill-server
timeout /t 1 /nobreak
adb disconnect
adb disconnect
timeout /t 1 /nobreak
adb connect 192.168.1.10:5555
timeout /t 1 /nobreak
adb tcpip 5555
timeout /t 1 /nobreak
scrcpy -m1280
```

**Comment by rom1v** [comment]
Over tcpip, you will have this message due to a bug with `adb reverse` on the device (see #5), but scrcpy will then switch automatically to `adb forward`.

**Comment by wazerstar** [comment]
> 
> 
> Over tcpip, you will have this message due to a bug with `adb reverse` on the device (see #5), but scrcpy will then switch automatically to `adb forward`.

Why is it that this works for me in this batch

https://streamable.com/bm2b2
```
adb kill-server
adb disconnect
adb disconnect
adb connect 192.168.1.10:5555
adb tcpip 5555
timeout /t 1 /nobreak
scrcpy -m1280
```

But removing 1 disconnect then it does not.


https://streamable.com/7tznp
```
adb kill-server
adb disconnect
adb connect 192.168.1.10:5555
adb tcpip 5555
timeout /t 1 /nobreak
scrcpy -m1280

```

**Comment by mochadwi** [comment]
After a while, I've forgot that setup the adb to debug over WIFI, after disconnected it using `adb disconnect` I'm able to debug over USB again.
