### ISSUE TITLE
Camera closes in landscape

### ISSUE THREAD

**Issue by haytham-med** [Genymobile/scrcpy#901]
Hi, when i enable rotation, and i put device in landscape mode, then open camera in scrcpy, it won't open. I tried open camera app, works, but not the default camera app. Thanks

**Comment by rom1v** [comment]
There is probably a resource conflict.

Does it work with a lower definition:

    scrcpy -m800

?

**Comment by haytham-med** [comment]
Seems fine with scrcpy -m800, although camera won't rotate.

**Comment by rom1v** [comment]
Now you could rotate with `Ctrl`+`←` and `Ctrl`+`→` though :)
