### ISSUE TITLE
win10，Unable to copy and paste Chinese。cmd ：[server] WARN: Could not inject char u+7533

### ISSUE THREAD

**Issue by 11fen** [Genymobile/scrcpy#907]

**Comment by rom1v** [comment]
#37 

As a workaround, paste with Ctrl+Shift+v to set the device clipboard, then use the native Paste of your device.

**Comment by 11fen** [comment]
谢谢，我一直以为是在计算机上操作Ctrl+Shift+v，不过这个不太方便。我现在使用https://play.google.com/store/apps/details?id=com.hgoldfish.lafdup和scrcpy
一同使用。


Thanks, I always thought it was Ctrl+Shift+v on the computer, but this is not very convenient. I am using https://play.google.com/store/apps/details?id=com.hgoldfish.lafdup and scrcpy now
Use together.

**Comment by 11fen** [comment]
不是ctrl+f，想放大整个设备，就像安卓模拟器，解决视力问题。
Not ctrl+f, want to enlarge the entire device, just like the Android emulator, solve the vision problem.

**Comment by edevelops** [comment]
The same issue for Cyrillic
