### ISSUE TITLE
Scrcpy not displaying video on pc in landscape

### ISSUE THREAD

**Issue by bluekatt17** [Genymobile/scrcpy#908]
I have the Samsung galaxy a10e and when I try to play YouTube,Netflix or hulu the video won't display once in landscape mode. It plays on my phone but the screen is black on PC?

**Comment by rom1v** [comment]
Does it work in portrait mode?

If yes, try with a lower definition:

     scrcpy -m1024

Netflix probably uses hardware DRM, so black screen is expected.

**Comment by bluekatt17** [comment]
I tried to lower definition snd still having the same  problem

**Comment by rom1v** [comment]
> Does it work in portrait mode?

**Comment by harry-hathorn** [comment]
Yeah so i have an app that streams video that i'm trying to mirror to my pc screen. The screen is black and it does use DRM.

What work arounds are there for this? Is there another way I can mirror my screen without any lag and mirror the DRM video?

**Comment by sorryusernameisalreadytaken** [comment]
> 
> 
> Yeah so i have an app that streams video that i'm trying to mirror to my pc screen. The screen is black and it does use DRM.
> 
> What work arounds are there for this? Is there another way I can mirror my screen without any lag and mirror the DRM video?

I want to know tha too. Having a chance to stream one of thoose retricted/protected streams could be a huge benefit for a lot of users. I dont want to copy content, for this you can use better a hardware instead of streaming it to another remote. I want just a chance for all thoose users out there.
