### ISSUE TITLE
[h264 @ 000000000252c700] Invalid level prefix

### ISSUE THREAD

**Issue by QGB** [Genymobile/scrcpy#911]
C:\QGB\software\scrcpy-win64>scrcpy
scrcpy-server.jar: 1 file pushed. 0.7 MB/s (19178 bytes in 0.026s)
INFO: Initial texture: 720x1280

Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
[h264 @ 000000000252c700] Invalid level prefix
[h264 @ 000000000252c700] error while decoding MB 12 68
[h264 @ 000000000252c700] concealing 577 DC, 577 AC, 577 MV errors in P frame
WARN: Cannot terminate server
Press any key to continue...

**Comment by rom1v** [comment]
See #347
