### ISSUE TITLE
consumeRotationChange()

### ISSUE THREAD

**Issue by linggongzhi** [Genymobile/scrcpy#914]
scrcpy是通过consumeRotationChange()这个方法来实现自动横屏的吗？我想投屏效果是竖着显示横屏内容该怎么修改啊，比如看视频的时候，点击全屏，就会横屏，能不能投屏的效果不自动横屏呢？就竖着显示。
Is scrcpy using the consumerotationchange () method to achieve automatic horizontal screen? I think the screen effect is how to modify the content of vertical display horizontal screen. For example, when watching video, click the full screen, the horizontal screen will be displayed. Can the effect of screen projection not automatically horizontal screen? It's just a vertical display.

**Comment by rom1v** [comment]
> Is scrcpy using the consumerotationchange () method to achieve automatic horizontal screen?

It just restarts the encoder with different dimensions when it detects rotation change.

> Can the effect of screen projection not automatically horizontal screen? It's just a vertical display.

If the device screen is rotated, your scrcpy should automatically resizes itself to display the video horizontally. Which device is it? Could you post a video of what happens, please (`scrcpy -m800 --record video.mkv`)?

**Comment by linggongzhi** [comment]
I just want to modify scrcpy-server.jar, the vertical frame, and the horizontal content。
[https://www.facebook.com/permalink.php?story_fbid=2509165326000641&id=100007215934496](url)

**Comment by rom1v** [comment]
I'm not sure to understand. Do you want https://github.com/Genymobile/scrcpy/issues/218?

**Comment by linggongzhi** [comment]
> I'm not sure to understand. Do you want #218?

谢谢，我已解决，我会旋转90度再发流给前端web页面显示，也就是竖着显示横屏。
