### ISSUE TITLE
Scrcpy Snap not working

### ISSUE THREAD

**Issue by 2635599** [Genymobile/scrcpy#917]
i just installed the snap for scrcpy via discover and it launched once, and now won't launch again. the fact that it ran tells me my setting on the phone are correct. not getting any error message when it refuses to launch. any idea what might be going on?  thanks

kubyntu 19.10 64 bit

**Comment by rom1v** [comment]
Doesn't it print anything when you start it from the console?

cc @cisco311

**Comment by rom1v** [comment]
cc @sisco311

**Comment by 2635599** [comment]
```
gravedigger@Digger:~$ scrcpy
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.
INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server.jar: 1 file pushed. 0.6 MB/s (22546 bytes in 0.037s)
bind: Address already in use
ERROR: Could not listen on port 27183
gravedigger@Digger:~$ sudo su
[sudo] password for gravedigger: 
root@Digger:/home/gravedigger# scrcpy
Command 'scrcpy' is available in '/snap/bin/scrcpy'
The command could not be located because '/snap/bin' is not included in the PATH environment variable.
scrcpy: command not foun
```

**Comment by rom1v** [comment]
OK, this is clearly a problem with the snap package. Maybe @sisco311 could help you.

Meanwhile, you can [build](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md) it (use the [prebuilt server](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#prebuilt-server) for simplicity). It should work.

**Comment by 2635599** [comment]
thanks but no not going through that again.

**Comment by 2635599** [comment]
i'd rather get the snap fixed.

**Comment by rom1v** [comment]
#674

**Comment by marineramanjay** [comment]
sudo snap install scrcpy
error: cannot perform the following tasks:
- Mount snap "scrcpy" (174) (cannot find required base "core18")
please tell how to fix this

**Comment by sisco311** [comment]
@2635599 for the ld.so error, try
`export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0`
https://bugs.launchpad.net/snapd/+bug/1757198

Not sure about the other error. Do you have a firewall?

@marineramanjay  try to install the core snap manually:
`snap install core`
https://github.com/snapcrafters/gimp/issues/60

**Comment by sathyamganesh** [comment]
![Untitled](https://user-images.githubusercontent.com/56997344/68647354-b2dd0b80-0543-11ea-91b9-d8acce36937f.png)

server pushes file only. Phone mirror not visible.

**Comment by rom1v** [comment]
@sathyamganesh Not related to snap(your screen shows that you are on Windows).

See https://github.com/Genymobile/scrcpy/issues/921#issuecomment-552102176

**Comment by 2635599** [comment]
ok the snap is working. looks like the main issue was and is with kubuntu 19.10 dropping proper support for the phone. that's a involved story i won't get into now.  that said like i said scrcpy is working correctly, but i'll be damn if i can find it's app launcher anywhere. right now i'm opening discover, searching for scrcpy, and launching it from there.  thoughts on finding my launcher? thanks

**Comment by 2635599** [comment]
> but i'll be damn if i can find it's app launcher anywhere. right now i'm opening discover, searching for scrcpy, and launching it from there. thoughts on finding my launcher? thanks

can i please get some help with this? thanks

**Comment by rom1v** [comment]
There is no "launcher". Just type `scrcpy` (with optional arguments) in a console.

**Comment by 2635599** [comment]
thanks for that worked like a charm for two launches. now in get the below, and as you can see from the image scrcpy does still start if done through discover.  any idea why it won't start from the konsole after it did twice? thanks

```
gravedigger@Digger:~$ scrcpy
INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
adb: error: cannot stat '/usr/local/share/scrcpy/scrcpy-servech file or directory
ERROR: "adb push" returned with value 1
gravedigger@Digger:~$ sudo su
[sudo] password for gravedigger: 
root@Digger:/home/gravedigger# scrcpy
INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
adb: error: cannot stat '/usr/local/share/scrcpy/scrcpy-servech file or directory
ERROR: "adb push" returned with value 1
root@Digger:/home/gravedigger# scrcpy
INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
adb: error: cannot stat '/usr/local/share/scrcpy/scrcpy-servech file or directory
ERROR: "adb push" returned with value 1
root@Digger:/home/gravedigger# 
```

https://i.imgur.com/VewbOZC.png

**Comment by rom1v** [comment]
> `/usr/local/share/scrcpy/scrcpy-servech`

There is a typo in the server path. Did you define `SCRCPY_SERVER_PATH` or something?

**Comment by 2635599** [comment]
yea it's one of the reasons i included the code so didn't have to expand konsole. as for the file not found i don't buy that since i've done no logoffs, reboots, run any cleaners, or done any updates since before running scrcpy the 2 times from the konsole. only thing i did after trying to run it the last time was give root privileges and try again.

**Comment by rom1v** [comment]
There is probably a problem between the absolute path on the system and the path "inside snap".

@sisco311 ?

**Comment by 2635599** [comment]
ok no worries on that. in the mean time there has to be a executable the launch button on discover is linked to, or no starting scrcpy from discover. all i want to do is create a shortcut on the desktop like i did in cinnamon, neon, and kubuntu 18.04 and 19.04 when i was running them.

**Comment by 2635599** [comment]
> There is no "launcher". Just type `scrcpy` (with optional arguments) in a console.

yes there is a EXECUTABLE under /root/bin/ just found it.

**Comment by sisco311** [comment]
The executable of the snap is under /snap/bin/scrcpy and/or /var/lib/snapd/snap/bin/scrcpy

You can create a [.desktop](https://developer.gnome.org/integration-guide/stable/desktop-files.html.en) file for it if you want.

Don't run the snap as root.

**Comment by MCMic** [comment]
I tried to switch from an old manually built scrcpy to the snapped one, but I get:
```
$ snap run scrcpy
INFO: scrcpy 1.11 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: device unauthorized.
This adb server's $ADB_VENDOR_KEYS is not set
Try 'adb kill-server' if that seems wrong.
Otherwise check for a confirmation dialog on your device.
ERROR: "adb push" returned with value 1
```
```
$ snap run scrcpy.adb devices
List of devices attached
0978fc9d        unauthorized
```

Nothing is showing up on the phone, is there anything I can do to switch it to authorized? (it’s connected through USB and scrcpy 1.4 and system’s adb are working fine.

**Comment by rom1v** [comment]
Try to `adb kill-server`, unplug your phone, replug it and retry.

**Comment by MCMic** [comment]
Thanks, it worked, it prompted for authorization on the phone and now v1.11 from snap works!

**Comment by Jolapache** [comment]
To make scrcpy working on Debian Stretch I had to modify the line secure_path in the /etc/sudoers

Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"

Inspired by this post: [](https://dev.getsol.us/T7745)

**Comment by PranavBhattarai** [comment]
pranav@exam ~> scrcpy
Command 'scrcpy' is available in '/snap/bin/scrcpy'
The command could not be located because '/snap/bin' is not included in the PATH environment variable.
scrcpy: command not found

`Scrcpy v1.14`

@rom1v

**Comment by goomnoom** [comment]
I have problem with scrcpy on Debian 10 snap . Say command not found

**Comment by PranavBhattarai** [comment]
@goomnoom 
u can use "**snap scrcpy**" as a temporary solution.
But there is a permanent fix to that issue which I don't remember now.

**Comment by goomnoom** [comment]
Thanks I will try snap scrcpy .
:~$ snap scrcpy .this right command?
