### ISSUE TITLE
Add multiple devices support to mirror 

### ISSUE THREAD

**Issue by afahrurozi** [Genymobile/scrcpy#92]
can we make multiple devices to run mirroring?

**Comment by rom1v** [comment]
Just run several `scrcpy` instances with the serials of the connected devices (as listed by `adb devices`).

    scrcpy -s serial1
    scrcpy -s serial2

**Comment by sindweller2** [comment]
in second device, i am getting error like this : 

> ERROR: Could not listen on port 27183

any workaround?

**Comment by josephchrzempiec** [comment]
Hello i have this same problem. If i plug in two cell phones and try to run Scrcpy i get errors saying


C:\adb>scrcpy
adb: error: failed to get feature set: more than one device/emulator
ERROR: "adb push" returned with value 1

Can someone please help me? I'm this weekend trying to record something with 2 phones and i can not.


Joseph

**Comment by rom1v** [comment]
@josephchrzempiec
https://github.com/Genymobile/scrcpy/issues/92#issuecomment-375646122

**Comment by josephchrzempiec** [comment]
Hello when i tried that i get this error


C:\adb>scrcpy -s serial1
adb: error: failed to get feature set: device 'serial1' not found
ERROR: "adb push" returned with value 1

**Comment by rom1v** [comment]
You need to replace `serial1` by your device serial as displayed by `adb devices`.

**Comment by josephchrzempiec** [comment]
okay my device is eaf8a975 What is the command to make that work? eaf8a975 scrcpy --port 1234? I'm a little lost.

**Comment by adsf117** [comment]
Hi It did come up both phones using a port for each device , open a console for each device and assign a port 

> scrcpy -s {device name} -p {portNumber} 

thx! @rom1v

**Comment by rom1v** [comment]
Actually, unless you start them almost simultaneously, you don't need a distinct port for each.

**Comment by tieorange** [comment]
sudo did the job for me:

scrcpy -s 234324fsdfasdf4r
sudo scrcpy -s 6058ediba07c4f8c4 -p 114

**Comment by rom1v** [comment]
@tieorange You don't need `sudo` if you choose a port >= 1024.

https://www.w3.org/Daemon/User/Installation/PrivilegedPorts.html

**Comment by AlexanderCxPx** [comment]
pls, where I write "scrcpy -s (serial)"?

**Comment by p10neer10** [comment]
> pls, where I write "scrcpy -s (serial)"?

cmd.exe

**Comment by hrithikrtiwari** [comment]
![image](https://user-images.githubusercontent.com/42163313/125771946-8cc4ab7f-e16d-485f-b27d-013f65a40b48.png)
![image](https://user-images.githubusercontent.com/42163313/125772051-b986b906-9037-49ff-97ee-2df3a51c1980.png)
Thanks It works great
