### ISSUE TITLE
scrcpy doesn't work further after mentioning -- " INFO: Initial texture : 512x1024 "

### ISSUE THREAD

**Issue by see-see** [Genymobile/scrcpy#922]
Hi, I was using scrcpy(v1.6) quite well until i recently updated my mobile android OS.
When I run the scrcpy(v1.6), it connects and it pushes the JAR file as well... BUt strangely nothing happens after it prints " INFO: Initial texture : 512x1024 ". Same is with scrcpy(v1.10).

PS: The developers option and debugging via usb is on. And to add further, if my mobile screen is off and then when I try starting scrcpy, the mobile screen lights up. So im guessing the file is pushed but not responding any further. Attached logcat file, if it helps.

[new 2.txt](https://github.com/Genymobile/scrcpy/files/3827274/new.2.txt)

**Comment by rom1v** [comment]
Thank you for your report.

> ```
> 11-09 17:55:25.594  8571  8571 E Surface : java.lang.NullPointerException: Attempt to read from field 'android.os.MessageQueue android.os.Looper.mQueue' on a null object reference
> 11-09 17:55:25.594  8571  8571 E Surface :      at android.os.Handler.<init>(Handler.java:234)
> 11-09 17:55:25.594  8571  8571 E Surface :      at android.os.Handler.<init>(Handler.java:141)
> 11-09 17:55:25.594  8571  8571 E Surface :      at com.realme.darkmode.DarkModeManager.<init>(DarkModeManager.java:149)
> 11-09 17:55:25.594  8571  8571 E Surface :      at com.realme.darkmode.DarkModeManager.getInstance(DarkModeManager.java:186)
> 11-09 17:55:25.594  8571  8571 E Surface :      at android.graphics.BaseCanvas.<init>(BaseCanvas.java:68)
> ```

This is the same as #921 (so I'm closing). I guess the device is a Realme 3 pro?

**Comment by see-see** [comment]
The device is Realme 1

**Comment by rom1v** [comment]
Please test this: https://github.com/Genymobile/scrcpy/issues/921#issuecomment-552098899
