### ISSUE TITLE
how to listen on the change of the screen ?rotation

### ISSUE THREAD

**Issue by ShiverZm** [Genymobile/scrcpy#925]
(maybe i know  i look like  i am fool)
i am viewing your code ,i know the aidl listens the phone rotation,but how the pc knows phone is roating?

**Comment by rom1v** [comment]
> how the pc knows phone is roating

The PC doesn't know the device rotation.

When the device rotates, it just receives a frame having another dimension, so it resizes itself.

(Note that it would not be sufficient if we would need to draw a device around the video on the client side)

**Comment by iTestinglab** [comment]
> > how the pc knows phone is roating
> 
> The PC doesn't know the device rotation.
> 
> When the device rotates, it just receives a frame having another dimension, so it resizes itself.
> 
> (Note that it would not be sufficient if we would need to draw a device around the video on the client side)

you means client auto resize itself when  it receives a frame having another dimension.
But f I only use the scrcpy server, and then use the jmuxer to decode on frontend, how will the frontend listen when the screen is rotated. Only when it is monitored can the jmuxer be reset
