### ISSUE TITLE
Oculus Go touch pad click keyevent

### ISSUE THREAD

**Issue by Chris470** [Genymobile/scrcpy#938]
I am looking to remotely control a users direction on an Oculus Go project. 

To do so the game currently supports turning via clicking a direction on the the touch pad (Hit left or right on the touch pad and it rotates you 90 degrees in that direction), or you can just turn your head to look around.

Are there any keyevents for the Oculus Go touch pad clicks, or is there a another way to change which way a user is facing using scrcpy?

**Comment by rom1v** [comment]
```
adb shell input keyevent DPAD_LEFT
```
?

**Comment by Chris470** [comment]
Thanks, though unfortunately it doesn't do anything. Apparently there are .kl files which contain keyevents on android devices. I will take a look through those on the Go and see if I can find anything.

**Comment by rom1v** [comment]
```
$ adb shell input
Usage: input [<source>] <command> [<arg>...]

The sources are: 
      mouse
      keyboard
      joystick
      touchnavigation
      touchpad
      trackball
      stylus
      dpad
      touchscreen
      gamepad

The commands and default sources are:
      text <string> (Default: touchscreen)
      keyevent [--longpress] <key code number or name> ... (Default: keyboard)
      tap <x> <y> (Default: touchscreen)
      swipe <x1> <y1> <x2> <y2> [duration(ms)] (Default: touchscreen)
      press (Default: trackball)
      roll <dx> <dy> (Default: trackball)
```

Maybe `adb shell input touchpad <something>`.
