### ISSUE TITLE
Wireless Connection Problems (10060)

### ISSUE THREAD

**Issue by Leo200467** [Genymobile/scrcpy#941]
Hello 
I was able to mirror my Oculus Go to my PC using USB Cable and SCRCPY.
Now, im trying to mirror without the cable but im having a few issues. These are the steps that im doing:
- Plug the Oculus to PC with USB cable;
- Run CMD and cd to SCRCPY folder;
- ADB Devices, * daemon not running, starting now at tcp:5037, *daemon started successfully;
- Now my Oculus Go is listed as a device;
- Time to run adb tcpip 5555;
- adb shell ip addr show wlan0 to get the Oculus IP for connection;
- adb connect IP_ADDRESS: 5555;
**Then comes the error:**
- After a few seconds, returns 10060 error, translating the message: cannot connect to IP_ADDRESS:PORT, connection failed because connected component didnt awnser correclty after a period of time or the established connection failed because the connected host didnt respond.

I already did quite a few internet solutions, even ones i found here in Git. 
Tryied another port, opened up in firewall for sure. 
Another problem is the command "adb server", it returns "could not read ok from ADB Server * could not start server*".

Im i doing anything wrong? Did i missed something?

**Comment by rom1v** [comment]
Is your OculusGo on the same LAN as your computer?

(could you give the actual local IP address of your computer and your Oculus Go?)

**Comment by Leo200467** [comment]
They are both connected to the same Wi-Fi Network.
The IP Address show by the command is 192.168.10.152 ( also appears a /24 by side with the adb shell ip addr show, dont know what is this).
The PC Address show by IPCONFIG is (IPV4) 192.168.10.111.

**Comment by rom1v** [comment]
I think there may be a problem with the adb server on your Oculus Go.

The steps you did seem correct: https://developer.oculus.com/documentation/mobilesdk/latest/concepts/mobile-adb/

**Comment by Leo200467** [comment]
Any tips about that? 
I will look about it anyway, its good that i can do it by cable but using Wi-Fi would help me alot.
