### ISSUE TITLE
How to wirelessly view 2 devices at the same time

### ISSUE THREAD

**Issue by MikePlayzHD** [Genymobile/scrcpy#945]
So i have been able to only view one device wired and one wireless using the scrcpy -s command on linux

**Comment by rom1v** [comment]
List them with `adb devices`. You should be able to start `scrcpy -s` for each one.

**Comment by ihwf** [comment]
> List them with `adb devices`. You should be able to start `scrcpy -s` for each one.

when I run one, and I start another with `scrcpy -s` it error !
This is error info:
`bind: Address already in use`
`scrcpy[15070:1261952] ERROR: Could not listen on port 27183`

**Comment by rom1v** [comment]
It listens only until the device is connected, so if you start the second one few seconds after the first one is connected, it should work.

Alternatively, you could use a different port for the other device: `scrcpy -p 27184`.

**Comment by rom1v** [comment]
I think I will improve the `-p` option to support a range: `-p start:end`, with a default range `27183:27200`, so that it try the ports sequentially until one works. That would avoid this kind of problem.

**Comment by ihwf** [comment]
> I think I will improve the `-p` option to support a range: `-p start:end`, with a default range `27183:27200`, so that it try the ports sequentially until one works. That would avoid this kind of problem.

Great! It work! Thanks! It's a good idea about this change

**Comment by rom1v** [comment]
Implemented in `dev` (see #951).

**Comment by rom1v** [comment]
Released in v1.13.
