### ISSUE TITLE
Stuck on INFO: Initial texture | Display window never opens

### ISSUE THREAD

**Issue by flinstones1** [Genymobile/scrcpy#946]
Hello, I'm trying to run scrcpy-win64-v1.11 on Windows 10. I have also tested scrcpy-win64-v1.10 which gives me the same issue.

I'm connected with ADB over WiFi to a Sony Android TV, Sony Bravia 2015 (KDL-50W800C)

Running scrcpy without any flags gives me the following:
`INFO: Initial texture: 1920x1080`
I've also tried running at different resolutions, `-m 800`, but the issue is the same.
Scrcpy just hangs on that line indefinitely.

**Comment by flinstones1** [comment]
I have just noticed something strange.
After a reboot of my TV, if I run `scrcpy -m 1280` (also tested with 800), it makes the connection and displays the screen.
I can disconnect this and reconnect this also without problem given that I specify a custom resolution.
However, once I just run `scrcpy` (which for my device defaults at 1920x1080) it cause the error described in my original post. I can at this point never connect anymore even using the previously working custom resolutions until after a reboot.

Hope this information might be useful to you. As for fixing this bug, I'm now perfectly able to use the software given that I specify a lower resolution the first time I run scrcpy after a reboot, so there is no rush.

**Comment by rom1v** [comment]
When it fails, could you post the device logs:

```
adb logcat -d logs.txt
```

**Comment by flinstones1** [comment]
Which part are you interested in? Lots of sensitive information in there.

**Comment by rom1v** [comment]
OK, then clean the whole log beforehand: `adb logcat -c`, then start scrcpy, then dump the logs.

It should result in a small part which should not contain sensitive info.
