### ISSUE TITLE
Enable screen touch when device screen is off(keep mirroring) is enabled

### ISSUE THREAD

**Issue by hunterx9** [Genymobile/scrcpy#948]
Hi, is there a way to enable screen touches on my mobile when the device screen off is enabled. Basically what happens when device screen off is enabled is that i cannot do anything on my mobile screen so i have to control it from the computer. It would be great if my mobile screen is off while I control the screen touch from mobile as i am playing games/youtube/apps,etc and the screen is mirrored on my computer. Is this possible? If so where can i add it on the source code

**Comment by rom1v** [comment]
I think you want to show touches on mouse clicks (regardless of whether `--turn-screen-off` is set).

For now, the option only enable an option on the device which shows physical touches, not injected events.

See https://github.com/Genymobile/scrcpy/issues/44

**Comment by manishxshrestha** [comment]
Hmm, so there is no way to touch the screen while the device screen off is enabled?

**Comment by rom1v** [comment]
Oh, ok, I did not understand what you wanted.

I don't think that's possible, if screen is off, it does not trigger touch events.

**Comment by sisco311** [comment]
Don't have another device to make more tests, but it works on my Sony Xperia Z2 (D6503), Android version 6.0.1, scrcpy v1.10 & v1.11

Even when the phone's screen is off (Ctrl+o or --turn-screen-off) I can still use its touch screen.

**Comment by manishxshrestha** [comment]
Hm it does not work on my samsung m20, android version 9. So i guess it doesnt work in android pie?

**Comment by reversegear** [comment]
> 
> 
> Hmm, so there is no way to touch the screen while the device screen off is enabled? Its like an overlay that keeps the screen off but touching on the screen is disabled. It would have been great if i could use my mobile as a controller while playing games on a bigger screen. Display on the phone while doing so is a distraction.

as  a workaround reduce the brightness to lowest using [RootDim [root]](https://play.google.com/store/apps/details?id=mobi.pruss.superdim&hl=en) screen is almost invisible.

**Comment by manishxshrestha** [comment]
> > Hmm, so there is no way to touch the screen while the device screen off is enabled? Its like an overlay that keeps the screen off but touching on the screen is disabled. It would have been great if i could use my mobile as a controller while playing games on a bigger screen. Display on the phone while doing so is a distraction.
> 
> as a workaround reduce the brightness to lowest using [RootDim [root]](https://play.google.com/store/apps/details?id=mobi.pruss.superdim&hl=en) displayis almost invisible.

well rootdim is for older phones that require root(maybe). Apps like Dimly can set the brightness on mobile to lowest but the thing is if the brightness is set to lowest then the screen on my computer also get dim.

**Comment by reversegear** [comment]
> 
> 
> > > Hmm, so there is no way to touch the screen while the device screen off is enabled? Its like an overlay that keeps the screen off but touching on the screen is disabled. It would have been great if i could use my mobile as a controller while playing games on a bigger screen. Display on the phone while doing so is a distraction.
> > 
> > 
> > as a workaround reduce the brightness to lowest using [RootDim [root]](https://play.google.com/store/apps/details?id=mobi.pruss.superdim&hl=en) displayis almost invisible.
> 
> well rootdim is for older phones that require root(maybe). Apps like Dimly can set the brightness on mobile to lowest but the thing is if the brightness is set to lowest then the screen on my computer also get dim.

[Dimly ](https://play.google.com/store/apps/details?id=es.richardsolano.filter&hl=en_IN)& [Lower Brightness Screen Filter](https://play.google.com/store/apps/details?id=nu.lower.brightness&hl=en_IN) actually what these apps does is enable translucent overlay. which is not exactly reducing brightness. :)
irrespective of phone screen brightness scrcpy should follow the PC brightness.

**Comment by manishxshrestha** [comment]
Hm, it does not follow PC brightness :(

when dimly brightness is set to lowest:
<a href="https://ibb.co/dQN1Z0J"><img src="https://i.ibb.co/LCTbKzh/image.png" alt="image" border="0"></a><br /><a target='_blank' href='https://freeonlinedice.com/'></a><br />

when dimly brightess is adjusted:
<a href="https://ibb.co/mS7zqwh"><img src="https://i.ibb.co/6N5sPxD/image.png" alt="image" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>upload photo</a><br />

**Comment by rom1v** [comment]
I'm closing, as it seems it's a device ROM specific behavior, not related to scrcpy.
