### ISSUE TITLE
get position of given window

### ISSUE THREAD

**Issue by tierline1** [Genymobile/scrcpy#952]
how to get screen coordinates of window where android screen translates?

**Comment by rom1v** [comment]
Not sure to understand the question, but maybe the answer is:
https://github.com/Genymobile/scrcpy/blob/8ec077ce1b5ae3c8a5993e062668220e7c684c30/server/src/main/java/com/genymobile/scrcpy/Device.java#L101-L117

Otherwise, please give more context on what you are trying to do :wink:

**Comment by tierline1** [comment]
I mean, i need left (X) and top (Y) coordinates of the window with android screen, pls see screenshot
![image](https://user-images.githubusercontent.com/25299783/69643541-86151200-1074-11ea-96d1-89f7deb926c3.png)

**Comment by rom1v** [comment]
[`SDL_GetWindowPosition`](https://wiki.libsdl.org/SDL_GetWindowPosition).

Note that you can set the position with:

    scrcpy --window-x 300 --window-y 300
