### ISSUE TITLE
Segmentation fault with v1.11_windows64bit pre-built

### ISSUE THREAD

**Issue by xidameng** [Genymobile/scrcpy#958]
Hi My device is connected via wifi
but once running scrcpy, i got segmentation fault 
![image](https://user-images.githubusercontent.com/41950436/69775534-000fdd00-11d4-11ea-82aa-34e30a204eaf.png)

**Comment by rom1v** [comment]
When this happens, what is the result of `adb logcat`?

The `Segmentation fault` message is probably on the device side (on windows, it would not print a message but rather open a crash dialog I think).

**Comment by xidameng** [comment]
hi I then downloaded the v1.10 which worked like a charm for me. I think we can close this issue for now:)   thanks~~

**Comment by rom1v** [comment]
Which device is it? Which Android version?

Could you test https://github.com/Genymobile/scrcpy/issues/944#issuecomment-557550516 please?

**Comment by xidameng** [comment]
btw segmentation fault is on my PC side, and the command prompt didn't crash

I am using Redmi K20 (a sub brand of Xiaomi) with latest android, the phone shipped with custom rom I think

**Comment by xidameng** [comment]
> Which device is it? Which Android version?
> 
> Could you test [#944 (comment)](https://github.com/Genymobile/scrcpy/issues/944#issuecomment-557550516) please?

sorry I am an android developer, am afraid I can't help you on this

**Comment by rom1v** [comment]
At the end of the comment, there are `scrcpy.exe` and `scrcpy-server`, just replace them in your v1.11 release.

**Comment by rom1v** [comment]
> btw segmentation fault is on my PC side

How do you know that?

(The messages from the device may be printed on this console)

**Comment by xidameng** [comment]
> At the end of the comment, there are `scrcpy.exe` and `scrcpy-server`, just replace them in your v1.11 release.

Hi, thanks alot! they worked!  :)

**Comment by rom1v** [comment]
Cool :+1:
