### ISSUE TITLE
Segmentation fault on linux when connecting to Xiaomi Mi 9T

### ISSUE THREAD

**Issue by GSlzr** [Genymobile/scrcpy#959]
Using version 1.11 a segmentation fault occurs when connecting to a Xiaomi Mi 9T under Ubuntu 18.04

`scrcpy
INFO: scrcpy 1.11 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 0.8 MB/s (25454 bytes in 0.031s)
Segmentation fault`

**Comment by rom1v** [comment]
Which Android version?

https://github.com/Genymobile/scrcpy/issues/944#issuecomment-557550516
At the end of this comment, please test `scrcpy.exe` and `scrcpy-server` (just replace them in your v1.11 release).

Ref #958

**Comment by GSlzr** [comment]
I am using Android 9.

With version 1.10 of scrcpy it works

**Comment by rom1v** [comment]
> With version 1.10 of scrcpy it works

OK, please confirm that it also works with binaries linked in https://github.com/Genymobile/scrcpy/issues/944#issuecomment-557550516

**Comment by GSlzr** [comment]
I was just trying with the edge snap and it works fine.

**Comment by sayginburak** [comment]
I am facing the same issue with Xiaomi Mi 8 but on macos. how can I install 1.10 version? do I need to build from the source code or is there any other way?

**Comment by rom1v** [comment]
> how can I install 1.10 version? do I need to build from the source code or is there any other way?

Yes, to install another version, you have to build from sources.

But now, v1.12 is out, it should be updated soon in Homebrew: https://github.com/Homebrew/homebrew-core/pull/47662
