### ISSUE TITLE
Automatically enable/disable debugging features

### ISSUE THREAD

**Issue by benwa** [Genymobile/scrcpy#96]
An option to automatically turn on (and off) System UI demo mode and Show Taps would be pretty neat.

Or perhaps a system broadcast could be an option to show when scrcpy has started/stopped so users can use Tasker to perform specific tasks is more flexible?

**Comment by rom1v** [comment]
> Show Taps

This one:
![show_touches_option](https://user-images.githubusercontent.com/543275/37874856-4e7a2b7e-3037-11e8-8f5d-9b4c2ebcd04c.png)
?

> System UI demo mode

What is this?

**Comment by benwa** [comment]
Yup for Show touches, I think they just renamed it on a different version of Android.
System UI demo mode will show the battery as fully charged, make the time static, and hide all notifications from displaying or taking up space on the status bar.

**Comment by benwa** [comment]
I think it's in AOSP. Showed up in Marshmallow.  It's under Developer Options, but I know it's been moved around in different versions.

This page shows how to work with it with adb commands.
https://android.googlesource.com/platform/frameworks/base/+/master/packages/SystemUI/docs/demo_mode.md

**Comment by rom1v** [comment]
> This page shows how to work with it with adb commands.

Great, I didn't know that :+1:
It has many options, so I'm not sure it is relevant to expose them in scrcpy.

However, adding an argument for _show taps_ would make sense (the only problem is that it will stay ON if the device is unplugged while scrcpy is running).

**Comment by benwa** [comment]
How about the broadcast method then? So when scrcpy starts/ends a broadcast is sent out, then the user can do whatever they'd like with Tasker/MacroDroid/whatever.

**Comment by rom1v** [comment]
> How about the broadcast method then?

    adb shell am broadcast -a com.android.systemui.demo -e command enter

and

    adb shell am broadcast -a com.android.systemui.demo -e command exit

?

I'm not sure to understand what they do on their own (without the other commands). Could you explain, please?

**Comment by benwa** [comment]
Sorry, I meant have scrcpy running on the device send out its own broadcast.
https://developer.android.com/guide/components/broadcasts.html#sending_broadcasts

So you'd have one broadcast (sometimes called intents just to make it more confusing) of say com.genymobile.scrcpy.START and one of com.genymobile.scrcpy.END
On the device, Tasker can look for those broadcasts and perform actions based on it.  This would give more flexibility for the user to do whatever they'd want instead of baking it into scrcpy.


I chose Show Touches and System UI demo mode as an example as I can see that use case being used with scrcpy a lot.

**Comment by rom1v** [comment]
Ah ok, I get it :wink: 

> Sorry, I meant have scrcpy running on the device send out its own broadcast.

OK :+1:

Or equivalently:

    adb shell am broadcast -a com.genymobile.scrcpy.START

(the server installed on the device has no `Context` to send broadcasts)

> This would give more flexibility for the user to do whatever they'd want instead of baking it into scrcpy.

OK. I like the idea, but I'm not sure it is worth to implement it directly in scrcpy (it's an advanced usage, and a simple wrapper script would do the job).

However, I will probably still implement _show touches_, because I think it should be available without developing a specific app to implement custom actions (or using a third-party app).

**Comment by benwa** [comment]
Ah, didn't know you needed a context for that.  Anyway, sounds good to me, thank you!

**Comment by rom1v** [comment]
> Ah, didn't know you needed a context for that.

[`sendBroadcast`](https://developer.android.com/reference/android/content/Context.html#sendBroadcast(android.content.Intent)) is a `Context` method.

**Comment by rom1v** [comment]
I added an option to enable "show touches_ (implemented on `dev`): https://github.com/Genymobile/scrcpy/commit/66ec2528930ef85d238152d95d9b220b70c94f11.

    scrcpy --show-touches

or

    scrcpy -t

**Comment by xJigs** [comment]
how to go back to wired? need help
