### ISSUE TITLE
Q: No digital signatures and no info in binaries.

### ISSUE THREAD

**Issue by xcme** [Genymobile/scrcpy#961]
Hello!

I found your project today and it really looks well but I was surprised after downloading binaries. I saw there are no digital signatures or descriptions of any kind, even version numbers. Neither in scrcpy or adb. I have checked official Android SDK and found no signatures there.

I want to ask is it safe to use such 'unknown' binaries? I have no idea why Google doesn't provide info of ADB but what about scrcpy? Could you provide any clarifications?

Thanks in advance!

**Comment by rom1v** [comment]
I didn't register to any Windows stuff to get a "Microsoft-signed certificate".

I publish `SHA256SUMS.txt` (the hashes) and `SHA256SUMS.txt.asc` (the GPG signature of the hashes, using the key you can retrieve from default keyservers, having these [fingerprints](https://blog.rom1v.com/about/)).

`adb` is downloaded from google server and checked against the expected SHA256:
https://github.com/Genymobile/scrcpy/blob/8bc056b9c68eea7bccfa5d9123a70443fb1d75b2/prebuilt-deps/Makefile#L37-L40
Anyone can check that the included `adb.exe` is the same as this one.
