### ISSUE TITLE
scrcpy abort error on Ubuntu 19.10 snap install with Fire table hd 8 

### ISSUE THREAD

**Issue by sudoyang** [Genymobile/scrcpy#964]
Fire OS 5.6.4.0, which is based on Android 5.1.1 Lollipop

scrcpy verison is 1.11

I have follow the some method about abort issue but it does not work. There is no extra folder at /data/local/tmp. 

![Captured_20191129_16:19:09_001](https://user-images.githubusercontent.com/2531404/69890606-ab985a80-12c4-11ea-909d-10610f8337bf.png)

![Captured_20191129_16:19:33_001](https://user-images.githubusercontent.com/2531404/69890612-afc47800-12c4-11ea-8115-fdd4901b9655.png)

This is log file

[log.txt](https://github.com/Genymobile/scrcpy/files/3906408/log.txt)

**Comment by rom1v** [comment]
See #944

**Comment by rom1v** [comment]
(just build the `dev` branch)

**Comment by sudoyang** [comment]
Thanks for the fast reply. Let me have a try.

**Comment by sudoyang** [comment]
Sorry, can you give me the link about how to build via dev branch. Thanks!

**Comment by sudoyang** [comment]
Worked! Thanks!
