### ISSUE TITLE
Redmi 5 Plus android 8.1 cannot control device

### ISSUE THREAD

**Issue by iiasceri** [Genymobile/scrcpy#970]
Redmi 5 Plus android 8.1 cannot control device

So Screen Mirroring Works But Controls Not...
CTRL + O works tho...

**Comment by iiasceri** [comment]
It didn't work on android 9 as well miui 11 if thats a issue you think...

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#i-can-only-mirror-i-cannot-interact-with-the-device

**Comment by iiasceri** [comment]
First of all, dude you are supper fast with response
Second USB Debugging (Security settings)"Allow granting permissions and simulating input via USB debugging" did the trick
Third thank you
Fourth I'm stupid cause Im android dev myself xD
