### ISSUE TITLE
Wireless linux issue

### ISSUE THREAD

**Issue by uzairleo** [Genymobile/scrcpy#971]
Bro i do the same procedure as u mention there but it doesnt wok any more it give me error that this feature was remove from repo and no more available

**Comment by rom1v** [comment]
Please copy-paste the exact error message.

**Comment by uzairleo** [comment]
w8 i will send u the screenshot

**Comment by uzairleo** [comment]
this error coming again and again whenever i want to connect wirelessly

**Comment by rom1v** [comment]
> this error coming again and again whenever i want to connect wirelessly

Which error? (you didn't posted anything)

**Comment by uzairleo** [comment]
hey bro i email u look at the previous email

**Comment by rom1v** [comment]
(Look at the github thread, there is no screenshot or details.)

**Comment by uzairleo** [comment]
ok w8 dear i will share there

**Comment by uzairleo** [comment]
![adbpushissue](https://user-images.githubusercontent.com/52172428/69911343-f4beea80-143b-11ea-9fc1-bae4bbbf27b8.png)

**Comment by uzairleo** [comment]
thats the problem adb push returned with value 1

**Comment by uzairleo** [comment]
but it workl good with data cable

**Comment by rom1v** [comment]
You have another program on your computer which keeps executing `adb` command using an old version of `adb`. Find it and stop it.

**Comment by uzairleo** [comment]
like how how ?

**Comment by uzairleo** [comment]
also i have another problem bro when ever i build my app in flutter using flutter sdk then this geny mobile mirro and control stop working automatically

**Comment by uzairleo** [comment]
???

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/issues/527#issuecomment-491213496

**Comment by uzairleo** [comment]
/home/uzairleo/Pictures/error.png

**Comment by rom1v** [comment]
>when ever i build my app in flutter using flutter sdk then this geny mobile mirro and control stop working automatically

Then your flutter SDK probably use its own (old) `adb`.

**Comment by uzairleo** [comment]
![error](https://user-images.githubusercontent.com/52172428/69911439-559af280-143d-11ea-92fe-ab11d27520e3.png)

**Comment by uzairleo** [comment]
how should i solve this issue

**Comment by yahiafarghaly** [comment]
@uzairleo remove the word _**DEVICE_IP**_  from the command 

> adb connect DEVICE_IP 192.xxx....
and it should work
