### ISSUE TITLE
 failed to get feature set: more than one device/emulator

### ISSUE THREAD

**Issue by gobinda01** [Genymobile/scrcpy#973]
![Screenshot (64)](https://user-images.githubusercontent.com/57617896/69910872-8af11180-1438-11ea-8ba0-393f4c6f33f5.png)
how to slove this issue - failed to get feature set: more than one device/emulator

**Comment by rom1v** [comment]
```
scrcpy -s 7d31c4dd
scrcpy -s 192.168.43.211:5556
```

_Please copy-paste terminal text instead of posting a screenshot, so that the content is searchable._
