### ISSUE TITLE
Cannot write special characters with the computer's keyboard

### ISSUE THREAD

**Issue by chopin2712** [Genymobile/scrcpy#974]
Hi 
I've just installed scrcpy on my laptop and when I write “é” or other similar French characters, nothing is typed on my device and I need to add it manually using the phone keyboard, so this is a real waste of time and it is sometimes faster to write using the device than using the computer's keyboard.

Can you help me?

Thanks in advance!

**Comment by rom1v** [comment]
What is your keyboard on the device?

In theory, it should work (and works for me): https://blog.rom1v.com/2018/03/introducing-scrcpy/#handle-accented-characters

**Comment by chopin2712** [comment]
@rom1v My keyboard is AnySoftKeyboard

**Comment by rom1v** [comment]
Weird, I cannot reproduce. It works for me with AnySoftKeyboard (both in French and English) or Simple Keyboard…

**Comment by QkiZMR** [comment]
I have same problem. I'm using Gboard and when I'm trying to type from PC keyboard any Polish characters like ęóśłżźćń I can't. I'm typing it by pressing right alt and some letter like eoslzxcn.

**Comment by rom1v** [comment]
> Polish characters like ęóśłżźćń

This is expected. See #194.

**Comment by alexdevos** [comment]
Hello @rom1v ! Exactly same problem as @chopin2712 on my phone (AnySoftKeyboard) but I [commented](https://github.com/Genymobile/scrcpy/issues/650#issuecomment-593092704) on issue #650 ... a bit lost in all those accent issues, sorry.

**Comment by hakeryk2** [comment]
Same issue for me with gboard - no polish characters.

**Comment by rom1v** [comment]
Closing as duplicate of #37.

**Comment by rom1v** [comment]
Please test #1426 (works on Android >= 7).
