### ISSUE TITLE
Scrcpy not using the port it's assigned

### ISSUE THREAD

**Issue by GraveDigger1** [Genymobile/scrcpy#975]
i just installed manjaro 18.1.3 and installed scrcpy snap. i ran it once after installing it and it worked perfectly. now when i try to run it i get told something else is using port 27183. thing is according to netstat scrcpy is assigned to port 27183. i have no firewall in place, so that's no an issue. i really have no idea what's going on with scrcpy.

```
[gravedigger@Digger ~]$ sudo netstat -tulpn | grep -w 27183
[sudo] password for gravedigger: 
tcp        0      0 127.0.0.1:27183         0.0.0.0:*               LISTEN      5255/scrcpy         
[gravedigger@Digger ~]$ 
[gravedigger@Digger ~]$ 
[gravedigger@Digger ~]$ 
[gravedigger@Digger ~]$ 
[gravedigger@Digger ~]$ scrcpy
INFO: scrcpy 1.11 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 5.3 MB/s (25454 bytes in 0.005s)
bind: Address already in use
ERROR: Could not listen on port 27183
[gravedigger@Digger ~]$ 
```

**Comment by rom1v** [comment]
Scrcpy should listen on that port only a few seconds. If it's already bound, it has not been unbound correctly (for some reason, maybe related to snap).

You can just use another port:
https://github.com/Genymobile/scrcpy/issues/951

**Comment by GraveDigger1** [comment]
thanks for that "scrcpy -p 27184" worked like a charm. thanks again.

**Comment by rom1v** [comment]
> now i'd like to creat a short cut using that switch. according to konsole the scrcpy executable should be in /usr/local/share/scrcpy/, but when i go to /usr/local/share/ the only thing in there is a man folder and nothing in that. any idea where i might actually find it, and perhaps why konsol is saying it's somewhere it's not? thanks

The server is in `$PREFIX/share/scrcpy/` but the client binary is in `$PREFIX/bin/` (the default `PREFIX` is `/usr/local`).

**Comment by GraveDigger1** [comment]
ok i found the location /snap/bin/scrcpy and was able to create my shortcut with the following comment and command:
konsole
/snap/bin/scrcpy -p 27185

works like a charm. thank you both, greatly appreciate the help and scrcpy.

**Comment by unominhtuan** [comment]
Sorry for reopening, I got the same error when running scrcpy from c #. this is my command "CLASSPATH = / data / local / tmp / server.jar app_process / com.genymobile.scrcpy.Server 1.12.1 1024 8000000 30 true - false true"

How do I fix my command to fix this error?
