### ISSUE TITLE
android studio debug app_process step

### ISSUE THREAD

**Issue by chenyunbbs** [Genymobile/scrcpy#976]
Please help me How Use android studio debug app_process step.
     
 hank you very much.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/DEVELOP.md#debug-the-server

**Comment by chenyunbbs** [comment]
> https://github.com/Genymobile/scrcpy/blob/master/DEVELOP.md#debug-the-server

adb forward tcp:5005 tcp:5005 command Whether to execute in com. If it is executed in com, the connection fails。I'm using Android studio. Is there a more detailed explanation?

**Comment by chenyunbbs** [comment]
> https://github.com/Genymobile/scrcpy/blob/master/DEVELOP.md#debug-the-server

meson x -Dserver_debugger=true
# or, if x is already configured
meson configure x -Dserver_debugger=true


Where is this configuration configured

**Comment by rom1v** [comment]
> Where is this configuration configured
When you build:
https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#common-steps

**Comment by chenyunbbs** [comment]
> > 是否以com执行。如果以com执行
> 
> 对不起，我听不懂。你什么意思？
> 
> > 此配置在哪里配置
> 
> 构建时：[https](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#common-steps)：
> [//github.com/Genymobile/scrcpy/blob/master/BUILD.md#common-steps](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#common-steps)

I want to write scrcpy server code in Android studio, but I can only write APK program in Android studio to debug and execute on mobile phone. I want to debug and execute scrcpy server code in Android studio

**Comment by rom1v** [comment]
Firstly, do you manage to build scrcpy using the [BUILD](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md) instructions?

> I can only write APK program in Android studio to debug and execute on mobile phone.

You may not build the program using Android Studio, only develop and debug with Android Studio, but you must build following the instructions.

**Comment by chenyunbbs** [comment]
> Android Studio开发和调试

My current practice is to develop an empty APK program through Android studio, then add the main method of Java to execute, and then compile it into APK to extract the DEX file inside to execute, but I can't debug the executed DEX program
