### ISSUE TITLE
adb.exe Kill Batch File

### ISSUE THREAD

**Issue by MrTeeXD** [Genymobile/scrcpy#977]
So, I have created a .bat file that Kills the adb.exe process that gets left behind when scrcpy closes or stops when the device has beeen disconnected. This is Windows only.

[scrcpy-process-kill.zip](https://github.com/Genymobile/scrcpy/files/3913856/scrcpy-process-kill.zip)

**Comment by rom1v** [comment]
`adb kill-server` should also work.
