### ISSUE TITLE
Wrong default config for scrcpy_options.max_size

### ISSUE THREAD

**Issue by jurkov** [Genymobile/scrcpy#978]
There is a tiny bug in **app/src/scrcpy.h** on line 45:
`.max_size = DEFAULT_LOCAL_PORT`

I think this should be:
`.max_size = DEFAULT_MAX_SIZE`

**Comment by rom1v** [comment]
Oops! Thank you: 86fcd89d8046318e6a40a5c7938999db6fe7acd0.

It had been introduced by 0e301ddf19c45de50ed728419adff9e6792332bf. In practice, it had no practical impact because the default port is 27183, which is far bigger than the size of the screen size width and height.
