### ISSUE TITLE
using any resolution higher than 1280x800 causes scrcpy to fail on a tablet with 16:10 screen

### ISSUE THREAD

**Issue by barfin** [Genymobile/scrcpy#981]
![Screenshot from 2019-12-04 14-24-02](https://user-images.githubusercontent.com/37030489/70137090-77e17a00-16a2-11ea-9c25-abe885f6a8b9.png)

**Comment by rom1v** [comment]
It's a limitation of your hardware encoder. See https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#i-get-an-error-could-not-open-video-stream

**Comment by barfin** [comment]
> It's a limitation of your hardware encoder. See https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#i-get-an-error-could-not-open-video-stream

Whoops
