### ISSUE TITLE
scrcpy close while vs code starts and if vs code already started then scrcpy not working

### ISSUE THREAD

**Issue by RashminDungrani** [Genymobile/scrcpy#985]
jarvis@debian:~$ scrcpy
adb server version (41) doesn't match this client (39); killing...
* daemon started successfully
/usr/local/share/scrcpy/scrcpy-server-...shed. 4.0 MB/s (19734 bytes in 0.005s)
INFO: Initial texture: 720x1280
jarvis@debian:~$

**Comment by rom1v** [comment]
See #527.

**Comment by RashminDungrani** [comment]
> See #527.

That's Not my solution, everything run find until vs code not start

**Comment by rom1v** [comment]
The reason of this message is that there are two different `adb` running on your system. You need to use the same version for all your programs.

For `scrcpy`, you can set the environment variable `ADB` to the full path of the `adb` executable you want to use.

**Comment by RashminDungrani** [comment]
jarvis@debian:~$ scrcpy
INFO: scrcpy 1.11 <https://github.com/Genymobile/scrcpy>
adb server version (41) doesn't match this client (39); killing...
ADB server didn't ACK
Full server startup log: /tmp/adb.1000.log
Server had pid: 4088
--- adb starting (pid 4088) ---
adb I 12-08 15:25:53  4088  4088 main.cpp:57] Android Debug Bridge version 1.0.39
adb I 12-08 15:25:53  4088  4088 main.cpp:57] Version 1:8.1.0+r23-5
adb I 12-08 15:25:53  4088  4088 main.cpp:57] Installed as /usr/lib/android-sdk/platform-tools/adb
adb I 12-08 15:25:53  4088  4088 main.cpp:57] 
adb I 12-08 15:25:53  4088  4088 adb_auth_host.cpp:416] adb_auth_init...
adb I 12-08 15:25:53  4088  4088 adb_auth_host.cpp:174] read_key_file '/home/jarvis/.android/adbkey'...
adb I 12-08 15:25:54  4088  4088 adb_auth_host.cpp:391] adb_auth_inotify_init...
adb server killed by remote request

* failed to start daemon
adb: error: failed to get feature set: cannot connect to daemon
ERROR: "adb push" returned with value 1

**Comment by JoelOvien** [comment]
@rom1v  please how do i set the environment variable ADB to the full path of the adb executable you want to use??
