### ISSUE TITLE
Audio isses - Oculus Go casting

### ISSUE THREAD

**Issue by keya-s** [Genymobile/scrcpy#987]
I am currently using scrcpy to cast from 4 Oculus Go's during a one-on-one performance piece. Each performance runs for about 45-50 minutes during which 2 headsets are connected to 1 Macbook pro. One of the headsets loses audio quite suddenly during casting on multiple occasions. Is there any reason this could be connected to using scrcpy? It doesn't really happen outside of casting and we're using Skybox VR player to run the videos. Please help!

**Comment by rom1v** [comment]
> Is there any reason this could be connected to using scrcpy?

Hmmm, no. Scrcpy does not even play audio (for now).
