### ISSUE TITLE
Support game controllers

### ISSUE THREAD

**Issue by laqyx** [Genymobile/scrcpy#99]
I know its note quite the goal of this project but would it be possible to use an Xbox 360 controller connected to the pc on my android phone trough scrcpy

**Comment by rom1v** [comment]
Technically, it's possible: [`GameController`](https://wiki.libsdl.org/CategoryGameController).

It would probably add some complexity to make the mappings customizable, though.

**Comment by librewish** [comment]
Might as well consider keyboard mapping for games like pubg

**Comment by AyraHikari** [comment]
Any update from this?

**Comment by Lolihunter1337** [comment]
Would also like to know

**Comment by m4heshd** [comment]
I've been killing myself for hours now looking how to do this. 😔 Pretty much impossible unless you're able to simulate windows touch events using the controller.

**Comment by Dom-R** [comment]
+1 to this idea. Would love to be able to use my Xbox controller to play on games that support controllers.

**Comment by wolfy01** [comment]
@m4heshd Maybe it's possible to map it to windows key presses? I don't really know though, just a big guess.

**Comment by taskmaster9001** [comment]
hi devs, are you working on this? I was trying to play Minecraft through scrcpy today when I found this issue. Would be great if this makes it to the application!

**Comment by 01yakiek** [comment]
I'm up for this, too!
I've not been able to find a perfect non-usb bluetooth controller that fits comfortably in my hands, and my phone doesn't support charge + usb otg at the same time, especially the device battery drains out quite fast while gaming.

Playing on scrcpy with controller, and with a bigger screen plus not having to worry about battery would be a blast!

**Comment by LHLaurini** [comment]
From some quick investigation, I've discovered this is possible by using `uinput`. Normal apps don't have permission to use it, but the adb shell has. That means we can emulate any input device we want, including controllers. I *may* try writing a pull request when I have time, but it shouldn't be too much work.

**Comment by scaldav** [comment]
Hello!

I tried to install and use #2130, but it's not working for me.
Should I make any particular configuration?

Please help me!

**Comment by LHLaurini** [comment]
@scaldav If #2130 doesn't work for you, it's likely your phone isn't supported (at least not without root). Using the same method as in #2632 would probably make it work on all devices, but I'm currently not working on that anymore. Might give it a shot again someday, but I don't guarantee anything.

**Comment by scaldav** [comment]
Hello and thank you for taking time to answer!

I didn't manage to get to my Android device: when I try to launch scrcpy in
the CMD line after the ADB connect command, it says that scrcpy is not
found. Any idea of why?

Il gio 10 feb 2022, 06:36 Luiz Henrique Laurini ***@***.***>
ha scritto:

**Comment by 27hectormanuel** [comment]
Any updates on this I would like to use my Xbox Wired controller via my PC

**Comment by paliszarok** [comment]
any updates? pls add...

**Comment by DarkevilPT** [comment]
Yo yo yo I also wanna play diablo immortal with my gamepad! It's the only and only missing feature we need!! plzz

**Comment by rom1v** [comment]
Implemented by #5270, released in scrcpy 2.7 :rocket:
