### ISSUE TITLE
Segmentation Fault on Mi 8 Lite

### ISSUE THREAD

**Issue by arisawali2014** [Genymobile/scrcpy#991]
![image](https://user-images.githubusercontent.com/31904944/70381227-38a07b00-1979-11ea-9d43-396ed8a173a2.png)
Doesn't show the casting but only show the "Segmentation Fault"
i'm using Mi 8 Lite MIUI 11 Android 9

**Comment by rom1v** [comment]
See https://github.com/Genymobile/scrcpy/issues/959

**Comment by Trevor-ctrl** [comment]
I also have this problem,could you tell me the way to fix it.

**Comment by arisawali2014** [comment]
wow thank's @rom1v it's work fine!

**Comment by rom1v** [comment]
v1.12 is out. Problem fixed.

**Comment by Trevor-ctrl** [comment]
THANKS,it works!
