### ISSUE TITLE
scrcpy not working while working on android project in vscode

### ISSUE THREAD

**Issue by RashminDungrani** [Genymobile/scrcpy#992]
scrcpy version 1.11
adb --version
Android Debug Bridge version 1.0.39
Version 1:8.1.0+r23-5

when i try to start the server it gives me error like
```
jarvis@debian:~$ adb kill-server
jarvis@debian:~$ adb start-server
adb server version (41) doesn't match this client (39); killing...
ADB server didn't ACK
Full server startup log: /tmp/adb.1000.log
Server had pid: 7311
--- adb starting (pid 7311) ---
adb I 12-08 16:05:04  7311  7311 main.cpp:57] Android Debug Bridge version 1.0.39
adb I 12-08 16:05:04  7311  7311 main.cpp:57] Version 1:8.1.0+r23-5
adb I 12-08 16:05:04  7311  7311 main.cpp:57] Installed as /usr/bin/adb
adb I 12-08 16:05:04  7311  7311 main.cpp:57] 
adb I 12-08 16:05:04  7311  7311 adb_auth_host.cpp:416] adb_auth_init...
adb I 12-08 16:05:04  7311  7311 adb_auth_host.cpp:174] read_key_file '/home/jarvis/.android/adbkey'...
adb I 12-08 16:05:04  7311  7311 adb_auth_host.cpp:391] adb_auth_inotify_init...
adb server killed by remote request
--- adb starting (pid 7321) ---
adb I 12-08 16:05:05  7321  7321 main.cpp:60] Android Debug Bridge version 1.0.41
adb I 12-08 16:05:05  7321  7321 main.cpp:60] Version 29.0.5-5949299
adb I 12-08 16:05:05  7321  7321 main.cpp:60] Installed as /home/jarvis/Android/Sdk/platform-tools/adb
adb I 12-08 16:05:05  7321  7321 main.cpp:60] 
adb I 12-08 16:05:05  7321  7321 auth.cpp:437] adb_auth_init...
adb I 12-08 16:05:05  7321  7321 auth.cpp:412] adb_auth_inotify_init...
adb I 12-08 16:05:05  7321  7327 transport.cpp:282] emulator-5554: read thread spawning
adb I 12-08 16:05:05  7321  7328 transport.cpp:295] emulator-5554: write thread spawning
adb I 12-08 16:05:05  7321  7321 adb.cpp:110] emulator-5554: already offline
adb I 12-08 16:05:05  7321  7329 transport.cpp:282] 5f20b737d240: read thread spawning
adb I 12-08 16:05:05  7321  7330 transport.cpp:295] 5f20b737d240: write thread spawning
adb I 12-08 16:05:05  7321  7321 adb.cpp:110] 5f20b737d240: already offline

* failed to start daemon
error: cannot connect to daemon

```

It works but until my flutter project not opens in vscode
```
jarvis@debian:~$ scrcpy
INFO: scrcpy 1.11 <https://github.com/Genymobile/scrcpy>
adb server version (41) doesn't match this client (39); killing...
* daemon started successfully
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 0.8 MB/s (25454 bytes in 0.032s)
INFO: Initial texture: 720x1280
WARN: Device disconnected
```

**Comment by rom1v** [comment]
Use the same `adb` as the one used in VSCode. Use the latest 1.0.41.

How did you install `adb`?

**Comment by RashminDungrani** [comment]
i just copy android studio adb directory to bin directory
OK Now it's working

**Comment by RashminDungrani** [comment]
I just copy android studio adb to bin directory
after upgrading adb now it's working
Thanks a lot

one more issue
Ctrl+m for the thirst button is not working
i am using rooted AOSP ROM in Redmi 4

**Comment by RashminDungrani** [comment]
> I just copy android studio adb to bin directory
> after upgrading adb now it's working
> Thanks a lot
> 
> one more issue
> well ctrl + b, h,m working but...
> How to view all opened apps

**Comment by MIKEGUIJARRO** [comment]
### Hi! Could you elaborate in how to change the paths. 

I already have the two paths
`:/$locate android-sdk/platform-tools/adb`
1. `/snap/scrcpy/204/usr/lib/android-sdk/platform-tools/adb`
2. `/usr/lib/android-sdk/platform-tools/adb`

When I try to assign the android adb path to scrcpy as you mentioned in other posts I have this output:

`$ADB=/usr/lib/android-sdk/platform-tools/adb scrcpy`
```
INFO: scrcpy 1.12 <https://github.com/Genymobile/scrcpy>
exec: No such file or directory
ERROR: Command not found: [/usr/lib/android-sdk/platform-tools/adb], [push], [/usr/local/share/scrcpy/scrcpy-server], [/data/local/tmp/scrcpy-server.jar]
ERROR: (make 'adb' accessible from your PATH or define its fullpath in the ADB environment variable)
ERROR: Could not execute "adb push"
```
I am learning to use bash, so I might done something wrong.

**Comment by rom1v** [comment]
If you use the snap version, your `adb` is related to the root of your snap container (you cannot access the one from your host environment). https://github.com/Genymobile/scrcpy/issues/723

**Comment by preeyam2000sahu** [comment]
I had the exact same issue and after hours of trying different things I decided to re-route the ADB path variable every time when I use scrcpy. This is the command :- `ADB=/home/preeyam/Android/Sdk/platform-tools/adb scrcpy` I run in my terminal.
Also the issue is with the adb version in the snap package of scrcpy and I couldn't replace it because it has read-only access.Hope this helps!

**Comment by rom1v** [comment]
@sisco311 Would it be possible to just temove the `adb` provided with the snap package, so that it uses the one from the system?

This snap-`adb` causes a lot of issues.

**Comment by kanishkdgrt** [comment]
> Use the same `adb` as the one used in VSCode. Use the latest 1.0.41.
> 
> How did you install `adb`?

but how ?

**Comment by javohir-ergashboyev** [comment]
> i just copy android studio adb directory to bin directory OK Now it's working
Could yu explain how can we do it

**Comment by javohir-ergashboyev** [comment]
> i just copy android studio adb directory to bin directory OK Now it's working

Could someone explain how can I do it? please

**Comment by javohir-ergashboyev** [comment]
> 

Ok I have recently found solution for this issue. Since it is impossible 2 adb work in the same time, you should use one of them. To implement this 1. open vscode 2. in vscode terminal ''export ADB=/home/javohir/Android/Sdk/platform-tools/adb scrcpy'' run this command. 3. Then run "scrcpy'' command as well. I hope it will work. However you should do above steps every time you open vscode!
