### ISSUE TITLE
ERROR: Could not parse bit-rate: value (8000000) out-of-range (0; -1)

### ISSUE THREAD

**Issue by z826540272** [Genymobile/scrcpy#995]
F:\Users\vilin\Desktop\scrcpy-win64-v1.10>scrcpy.exe -b 8000000
ERROR: Could not parse bit-rate: value (8000000) out-of-range (0; -1)
after upgrade to 1.12, 1.10 works fine

**Comment by reversegear** [comment]
i confirm this issue in scrcpy 1.12
scrcpy 1.11 works fine though

**Comment by rom1v** [comment]
:scream:

I fixed it on `dev`. In practice, it only happens in the Windows release (compiled with mingw32).

I will probably release a 1.12.1 soon for this issue.

Meanwhile, here is a win64 binary (replace it in your v1.12 release):
[`scrcpy.exe`](https://tmp.rom1v.com/scrcpy/issue995/1/scrcpy.exe) _SHA256: cb613178edb521b440fe89782a67c6c29446f52bf469dc3ce44b8270b0604357_

**Comment by arapka** [comment]
> Meanwhile, here is a win64 binary (replace it in your v1.12 release):

Is scrcpy-noconsole also available? Thanks.

**Comment by rom1v** [comment]
I just released v1.12.1.
