### ISSUE TITLE
How to view opened apps

### ISSUE THREAD

**Issue by RashminDungrani** [Genymobile/scrcpy#998]
> I just copy android studio adb to bin directory
> after upgrading adb now it's working
> Thanks a lot
> 
> one more issue
> well ctrl + b, h,m working but...
> How to view all opened apps

_Originally posted by @RashminDungrani in https://github.com/Genymobile/scrcpy/issues/992#issuecomment-563845623_

**Comment by rom1v** [comment]
Sorry, I don't understand the question.

What do you want to do, what do you do and what do you observe?

**Comment by RashminDungrani** [comment]
like Left: Back button for Ctrl + B
Middle: Home button for Ctrl + H
Right: Overview button for  ?

**Comment by WalterEbbers** [comment]
From what i know is that when you are using scrcpy you can view the overview with Ctrl + S.
